### ISSUE TITLE
Map Protection and zPermissions

### ISSUE THREAD

**Issue by ntrixter** [webbukkit/dynmap#1015]
Dynmap v1.0 and zPermissions v0.9.14 and bukkit #2457

I have a world named "newawesome" with a map named "cave30ne".  The map is protected, the world is not. I'm trying to give access to a player named "trixc". when i give trixc "dynmap.map.newawesome.cave30ne: true" she is able to see the map but ONLY when she is online. If she goes offline and then reloads the dynmap page the map is no longer visible. I noticed that if the player is OP then they will still see the map when offline. How do i setup dynmap so the map works when the (non OP) player is offline?

At first i thought it was something to do with case sensitivity. It looks like zPermissions is not case sensitive and i thought dynmap may be so i spent a half hour of changing config files from "NewAwesome" to "newawesome" and it did not help. 

Not sure what other information you would need so just ask and i'll get it. Thanks

**Comment by Psy-Virus** [comment]
I'll close this because no active convo since years. Pls reopen if still needed.
