### ISSUE TITLE
Notification of people coming online

### ISSUE THREAD

**Issue by jezh42** [webbukkit/dynmap#1023]
Hey i posted a while ago on the forums page about this i just never really got around to posting this here. Anyways one thing i would like added is if you could have email notifications if someone comes online and you could have a list. i dunno but i would like this because i am never on when my friends are on. and you could set it so that if they go online then offline in in a period of 5 - 10 minutes it would only send one email so your inbox will not flood.

not trying to be a stalker just trying to be social

**Comment by Psy-Virus** [comment]
I think this shouldn't be a part of Dynmap. This could be more or less easily achieved by a small login-event-based mod. And I think I saw such plugins and/or mods several times for different platforms.
