### ISSUE TITLE
DynMap-Mobs: EnderDragons don't show up

### ISSUE THREAD

**Issue by BlueJayofEvil** [webbukkit/dynmap#1030]
DynMap version: HEAD snapshot (dated Nov 22, 2012)
DynMap-Mobs version: HEAD/0.40 (dated Nov 20, 2012)
CB: Spigot build 255
DynMap-Mobs config: http://pastebin.com/DCs7aE6E
Issue: EnderDragon icon(s) do not show up (with the Mob layer enabled, of course.)
In case it matters, I spawned the EnderDragon with Essentials' /mob command. The issue persists even after a server restart.

**Comment by Psy-Virus** [comment]
Old issue, probably fixed. If not, pls reopen.
