### ISSUE TITLE
Sign markers aren't working in Forge build

### ISSUE THREAD

**Issue by vScourge** [webbukkit/dynmap#1203]
I'm using Dynmap for Forge, with a custom set of mods, and I cannot get sign-based markers to work.  This is using:

Dynmap 1.6-188 (alpha-2) (Forge)
Forge Mod Loader 4.7.35.556
MinecraftForge v6.6.2.534
Minecraft 1.4.7

If I create a sign with "[dynmap]" as the first line, it does not create a marker, and leaves that string unchanged on the new sign.  Dynmap works fine otherwise.  I am able to manually add/delete markers fine using the /dmarker commands, the problem is specific to sign-based markers.

I tried removing all mods (except dynmap on the server) and the behavior is the same.

I've had this problem for a few weeks and originally thought it was permissions-related.  I tried the new flat "permissions.xml" feature but it didn't help.  It also does not work for server ops, so I suspect it's not permissions after all.  In any case I do get the following line in my server.log file and ForgeModLoader logfile:

2013-03-26 15:13:34 [INFO] [dynmap] Using permissions.yml for access control

... and here's the contents of that file (minus top comments):

```
defaultuser:
  - render
  - show.self
  - hide.self
  - sendtoweb
  - stats
  - marker.list
  - marker.listsets
  - marker.icons
  - webregister
  - webchat
  - marker.sign

#playername1:
#  - fullrender
#  - cancelrender
#  - radiusrender
```

Let me know if you need more info.  And thanks!

**Comment by GamerSocke** [comment]
The sign marker feature is not working in the dynmap 3.0 beta 3 version.
The server runs withforge-1.12.2-14.23.5.2768-universal.jar and about 100 other mods (i can post you the mod list if needed).

I changed the enablesigns option in the configuration.txt ln107 "enablesigns: true".
I write a sign as an server-op e.g.

[dynmap]
set:markers
icon:house
Home

All the lines are still visible on the sign.
Markers added with the dmarker add command are showing up on the web interface.

**Comment by ThaDaVos** [comment]
Sorry to open this up again, but will this ever be supported on the just forge version?

**Comment by LaysDragon** [comment]
I encounter same issue here,and trying to track down the code implemented the sign feature.
looks like the sign event listener it not finish yet at forge 1.12.2.
So it won't work until it finished :/

https://github.com/webbukkit/dynmap/blob/10d03ef2ee6d18ecc1e23dca1dc4c3563e6f16a3/forge-1.12.2/src/main/java/org/dynmap/forge_1_12_2/DynmapPlugin.java#L721-L738
