### ISSUE TITLE
[Feature] Add overlay layer for pending renders

### ISSUE THREAD

**Issue by dragonpaw** [webbukkit/dynmap#1210]
Add overlays for in-process renders. It seems like lots of other addons exist to show various overlays, but oddly there's none for pendering render activity.

Example: I type /dynmap radiusrender x y r, I'd like to see that show up with a border on the map while it's updating. (So I can see that it's in progress, as well as where it will be.)

I've had to do a lot of spot updates of the map, and it would help a lot.

**Comment by Psy-Virus** [comment]
Didn't dynmap-diag do this?

pls reopen or create a new issue, if thiss needed.
