### ISSUE TITLE
Update leaflet to support IE touch events

### ISSUE THREAD

**Issue by jessenic** [webbukkit/dynmap#1276]
Latest leaflet seems to work fine on my Surface RT but dynmap does not support MS Pointer touch events because it uses old version of leaflet. Could you update leaflet to support touch on IE?

Also I think
-ms-touch-action: none; /\* Disable touch behaviors, like pan and zoom */
Is needed in CSS to disable other touch actions that are not handled by the map

**Comment by SimonOrJ** [comment]
I recently learned about Leaflet, and I decided to take a light look into it.  Leaflet is currently on 0.7.7, and it has touch support for the Microsoft web browsers.  As a MS Edge user, upgrading to support touch inputs from Edge will be so useful.

I tried to get it working by adding some missing L.TileLayer class function _createTileProto() (which successfully allowed players and chat to show), but I ran into another JS error about animation (error with function front.parentNode.appendChild(front)).  I hope looking into updating Leaflet is somewhere on to-do list.
