### ISSUE TITLE
In Dimensional Doors, new pocket dimensions break player/time updating (Also: Too many pocket dimensions!)

### ISSUE THREAD

**Issue by aendrew** [webbukkit/dynmap#1278]
The Dimensional Doors mod including with Tekkit Lite starting at version 0.6.1 seems to be causing Dynmap some grief.
1. Using a dimensional door (hereafter "DD") that creates a new pocket dimension seems to cause the bug mentioned [here](https://github.com/webbukkit/dynmap/issues/1153#issuecomment-17750583). The clock keeps looping the same 3 seconds, and player positions stay static (Or at least, the player entering the DD -- haven't tested it with other players yet). Same behaviour when entering a naturally-spawned DD that goes to a brand new dimensional dungeon (In fact, I first realized this was the issue after spawning some new chunks and entering a dimensional dungeon from one of those). 
2. Restarting the server fixes the issue (At least, until a new pocket dimension or dimensional dungeon is created).
3. Using a DD to go to an existing pocket dimension or dimensional dungeon does _not_ trigger the bug.
4. Even if new dimensions have their maps disabled by default, the bug still occurs (See below).

Somewhat related to this issue: every brand-new pocket dimension shows up as its own map. These are inherently pretty small (~1 chunk, IIRC), and given as they're comprised entirely of "Fabric of Reality", show up as nothing but black blocks. There really is no reason for Dynmap to bother mapping these as a result: while right-clicking a "fabric of reality" block with another block causes it to turn into that block, I think the Fabric of Reality's block ID stays the same (Which is why, even if you cover an entire pocket dimension with dirt blocks, it still shows up as a black square in Rei's Minimap).

Further, given how many of these tend to get created (You can go many layers down into a pocket dimension, creating a new one each time you place a DD inside a pocket dimension), it makes the rest of Dynmap pretty unusable to have them enabled. With default Dynmap settings, somewhere between 50 and 100 are populating my world list (With random Mystcraft worlds interspaced between) -- all of them small blank squares, and this is only ~2 weeks after updating to 0.6.1.

Any help? Thanks!

**Update:** I've set "enabled: false" in templates/normal.txt. Having now manually disabled each and every Pocket Dimension, I no longer have them bogging down my list of worlds in Dynmap. However, if I place a DD that creates a new pocket dimension, the broken player/time bug still occurs. So, it seems as if said bug might be due less to some kind of race condition between Dynmap and Dimensional Doors when creating new pocket dimensions and more to the act of creating a pocket dimension itself.

**Comment by Psy-Virus** [comment]
If still an issue with recent versions of DM, pls reopen or create a new one.
