### ISSUE TITLE
Update Maven repository

### ISSUE THREAD

**Issue by Philipp15b** [webbukkit/dynmap#1285]
@mikeprimm  set up an official Maven repository in #1010, but it seems it's a bit old by now. The newest DynmapCoreAPI there is version 1.3. An update would be nice.

**Comment by FabioZumbi12** [comment]
It is possile to update again? Tha latest is 2.0.

**Comment by mikeprimm** [comment]
Sure - I'll post an update tonight

**Comment by jascotty2** [comment]
@mikeprimm Dynmap is up to version 3.0 - can we get the repo updated again, please?

**Comment by UltraGameCoder** [comment]
Please @mikeprimm

**Comment by UltraGameCoder** [comment]
Im also not sure which maven repo to use for the line markers api.
(I want to obtain the regions created with the lines on the dynmap)

Current maven code:
```XML
<repository>
       <id>dynmap-repo</id>
       <url>http://repo.mikeprimm.com/org/dynmap/</url>
</repository>
<dependency>
       <groupId>DynmapCoreAPI</groupId>
       <artifactId>dynmap</artifactId>
       <version>2.0</version>
</dependency>
```

**Comment by erikzimmermann** [comment]
I know it's old, but I haven't found anything else.
Here's the working maven code:

```xml
<repository>
    <id>dynmap-repo</id>
    <url>http://repo.mikeprimm.com/</url>
</repository>

<dependency>
    <groupId>org.dynmap</groupId>
    <artifactId>DynmapCoreAPI</artifactId>
    <version>2.0</version>
    <scope>provided</scope>
</dependency>
```

**Comment by mikeprimm-triva** [comment]
3.x is under groupId us.dynmap - same repo
