### ISSUE TITLE
Show optional Playercount + Name from FakePlayer

### ISSUE THREAD

**Issue by o0Julia0o** [webbukkit/dynmap#1297]
hi,

could you show as option the fakeplayers(name + playercount, no position of course) from FakePlayersOnline: http://dev.bukkit.org/server-mods/fakeplayers & http://dev.bukkit.org/server-mods/chgusers ?

thx

Julia

**Comment by Psy-Virus** [comment]
Closing this feature request because of the age. If still interesting or needed pls reopen or create a new one.
