### ISSUE TITLE
Request: Immibis' Microblocks

### ISSUE THREAD

**Issue by kencinder** [webbukkit/dynmap#1302]
I'm not seeing any of the blocks in my maps, even if they're created from Vanilla blocks. I take it this one may be tricky with how his mod works...but maybe not?

Kind of odd seeing almost all of my buildings missing and all the machines etc exposed though.

**Comment by atomiklan** [comment]
What version of Dynmap and minecraft was this fixed for? We have been trying off and on for over a year now to get microblocks to render on our map, but documentation seems so scattered and about so many different versions. We're using 1.6.4 with Bukkit which I guess means we are using Dynmap-2.1-forge-1.6.4 in our mods folder with the Dynmap API bridge in the plugins directory. Any additional guidance would be fantastic.

**Comment by kencinder** [comment]
I don't recall exactly, but I would have been running 1.4.7 or 1.5.2 when I opened this issue.

If you're running Bukkit, you shouldn't be using the DynmapForge. You must be running Cauldron in the case of mods and bukkit plugins.
I would try updating to 2.2 - http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft
(Including the bridge)

I can't offer more help, I'm running a 1.7.10 server and haven't had time to set up Dynmap. It's possible this issue has re-appeared. I would however recommend you dump Immibis' Microblocks and use Forge Multipart regardless.

**Comment by atomiklan** [comment]
Thanks for the reply. Yes, we're using Cauldron and Dynmap as a whole is working on our Tekkit 1.6.4 Bukkit server. Check out the separate issue Adam linked above. I called it Forge as thats what was listed in the link. "Minecraft v1.6.4 with Forge v9.11.1, Cauldron v1.6.4: DynmapForge v2.2" and "DynmapCBBridge API Bridge plugin for Cauldron (also requires DynmapForge): DynmapCBBridge v2.2"

**Comment by kencinder** [comment]
Sorry I didn't notice the reference above, obviously it's an issue with Immibis' and Forge Multipart.

I'd put money on it being something changed with Forge's handling of this, that mike will hopefully be able to spot based on changes he made with what I initially reported, as he did fix it then.
