### ISSUE TITLE
Holes in the map where they should be none.

### ISSUE THREAD

**Issue by SaitoForte** [webbukkit/dynmap#1331]
If I zoom in, the map looks fine, but once start zooming out, it starts looking like this no matter how many times I re-render it from scratch: ![3481xee](https://f.cloud.github.com/assets/4700319/657032/226b36a2-d53f-11e2-8d07-aba184c2cb92.png)

**Comment by jmurrayufo** [comment]
I am seeing almost this exact issue on the current release version of Dynmap (Dynmap-2.1-forge-1.7.10) under a default install of the Feet the Beast Dire Wolf pack. 

![blackboxes](https://cloud.githubusercontent.com/assets/442011/6690803/2dbcec70-cc88-11e4-9bd9-e214a3f80f76.png)

Things I've tried (without noticeable effect) so far. 
* Reinstall server &&/|| dynmap. 
* Clear all configurations and start fresh
* Disable Spout integration
* Open limits on server TPS and tick msec time limits to give the server more time
* Force FullRender of the flat map 
 * This actually temporarily fixes the issue, and the black locations are filled in. 


Other then running a full render once a day to fix the boxes, I have no solutions to fix the current flat map on the server. Surface maps do not show this issue. 

What I have noticed is that this seems to happen at the edge of player loaded areas. The black boxes always end up bordering around locations with heavy player activity. As far as I can tell, these chunks arn't being updated by the players and should not effect the map anyway.

**Comment by jmurrayufo** [comment]
Seems fixed in Dynmap-2.2-alpha-2-forge-1.7.10.jar

**Comment by mikeprimm** [comment]
Yep - it SHOULD be fixed in the now-released Dynmap-2.2-alpha-1 code (versus the earlier development builds and/or previous released version).  You will need to run appropriate renders (fullrender, radiusrender, whatever) to 'fix' the existing holes - sorry, no easy fix to avoid that.

**Comment by jmurrayufo** [comment]
Full render with some stress of players and chunk loaders has yet to display the issue under Dynmap-2.2-alpha-2-forge-1.7.10.jar. We will continue to try to break it for the time being, but this seems to have fixed the issue! 

We were already running nightly full renders to avoid the issue (turning off map saving would get rid of it during the render process), so a new full render wasn't an issue at all. 

Many thanks for the fix, was driving me insane trying to fix it...

**Comment by mikeprimm** [comment]
Sorry - I've known it was a legit issue for some time, but it was a tricky one to actually run to ground.  Problem involved handling of chunk loading of chunks that were in the process of being unloaded/saved when we requested them, so it generally happened at the edge of areas where players were actively moving, teleporting, and/or logging off.... :)

**Comment by jmurrayufo** [comment]
This is the most legitimate time to use the term "Edge Case" I think I have ever seen... But I would agree. Our chunk-loaders in particular were bad at showing the issue.

**Comment by Psy-Virus** [comment]
This is still a recurring issue. But because of the age I'll close it.
There are probably a ton of duplicates.
