### ISSUE TITLE
[Feature Request] GalactiCraft

### ISSUE THREAD

**Issue by Sodiet** [webbukkit/dynmap#1341]
Hello. Please, add support of nice and fastest growing mod. About him:
Site: http://micdoodle8.com/mods/galacticraft
Forum: http://forum.micdoodle8.com/index.php
Jenkins: http://ci.micdoodle8.com/job/Galacticraft/

**Comment by MadEgg** [comment]
Dynmap-2.0.0-alpha-2-forge-10.13.0.jar in combination with GalacticraftCore-1.7-3.0.8.266.jar still does not work proberly. For the moon, only the cave made is somewhat rendered, the surface and flat maps are both completely empty.

This is in the BTP12-full mod-pack. Having map-support for the moon (and other planets? Haven't tested yet) would be awesome.

**Comment by ExDomino** [comment]
Dynmap 2.1 and Galacticraft 3.0.11, moon and mars are still entierely black.

**Comment by lellis2k** [comment]
Yeah still blank for me, can we mod it manually?

**Comment by ExDomino** [comment]
Label says it's already implemented, it's thus a bug.

**Comment by lellis2k** [comment]
Yeah I'm still not getting any galacticraft blocks rendering.
Running Dynmap-2.2-forge-1.7.2.jar

![capture](https://cloud.githubusercontent.com/assets/3228976/9106346/797e83f4-3c17-11e5-8b9e-c5f586c0bf45.PNG)

**Comment by bobkruithof** [comment]
This issue should be reopened. I can confirm as well that space dimensions are not rendered as promised.

**Comment by draknyte1** [comment]
Any chance on a re-look at this?
