### ISSUE TITLE
How Do I Implement Custom Icons?

### ISSUE THREAD

**Issue by MichaelGermany** [webbukkit/dynmap#1348]
I read https://github.com/webbukkit/dynmap/wiki/Using-markers#marker-icons and I was interested in making my own icons for a few things. The only thing I can't figure out is how to actually import it. I type in the command, "/dmarker addicon id:GR", but I can't figure out how to finish it. I use the FTP File Access in Multicraft. The PNG file is in a directory titled, "DynMap Markers" in the initial page (/). I've tried various file paths, but I can't figure it out.
Ex:
/DynMap Markers/GR.png
/DynMap_Markers/GR.png
/FTP Client/DynMap Makers/GR.png
Etc, etc...

Anyone that can help with this?

**Comment by Tomm-yT** [comment]
Is it not possible to make a 32x32 icon, because I get an error every time I try.

**Comment by SimonOrJ** [comment]
https://github.com/webbukkit/dynmap/wiki/Using-markers#marker-icons

That should work

**Comment by Tomm-yT** [comment]
Ok thanks!

**Comment by TheSexyLlamaFTW** [comment]
DUDE I LOVE YOU this was a life saver!
