### ISSUE TITLE
IIS instructions out of date, no longer working

### ISSUE THREAD

**Issue by gkinsman** [webbukkit/dynmap#1360]
When attempting to follow the IIS setup instructions found here: https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-IIS, I am presented with a black page after setting the tilespath in the configuration, restarting the server, and triggering a full render.

Also, there is no config.js in the standalone directory (only a configuration.php which is quite different to that specified in the instructions). I am using the default IIS path, and have also tried the troubleshooting steps to no avail. I have added the json mime type as well.

The configuration found at localhost/dynmap/up.aspx?path=configuration can be found here: https://gist.github.com/gkinsman/5972267

Given that the instructions are 7 months old, perhaps you could provide enough information to make it successfully work, and I could flesh out the details and potential problems?

Cheers,
George

**Comment by Psy-Virus** [comment]
@generrosity, maybe something for your Wiki work?

**Comment by generrosity** [comment]
Yikes I hope you haven't be tagging me often @psy-virus ! I've unsubscribed from alerts now just incase

**Comment by generrosity** [comment]
I might give it a look as I am supposed to be a Windows server admin, see about brushing it up to spec
