### ISSUE TITLE
[Feature Request] Chat ONLY Page

### ISSUE THREAD

**Issue by JeremyZh** [webbukkit/dynmap#1362]
Hey guys,
I there any way I could make a page that has only the chat feature of dynmap? I would also like it to have the same login system with dynmap.

Thanks!
JeremyZh

**Comment by Psy-Virus** [comment]
This can be coded with https://github.com/xPaw/PHP-Minecraft-Query and a web front end.
Shouldn't be Dynmaps job, I think.
