### ISSUE TITLE
MoreMaterials and Dynmap - Custom block issue

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#1372]
Im not really surprised this happened however I am curious about what I can do to fix it..

So I have a custom block that is placed in the game via Spout's plugin "MoreMaterials". In-game it appears as: http://i.imgur.com/XXayb9M.jpg

however, when Dynmap does a full render, I get this on the web page(s):
http://i.imgur.com/sEgRVam.png

I tried looking into how to add in custom blocks and shapes and such, but I guess I am not intelligent enough to understand that.. It seems to me, however, that at one point MoreMaterials had some sort of support because when I start the server, I get this; http://pastebin.com/GPqLVFk8

Not sure what to do, any help to resolve the issue as much as possible would be greatly appreciated.

Thanks! :)

**Comment by Psy-Virus** [comment]
Since Dynmap Mod Scraper this shouldn't be an issue anymore. If it is still an issue, pls reopen or create new.
