### ISSUE TITLE
[Feature Request] Teleport to markers

### ISSUE THREAD

**Issue by Programie** [webbukkit/dynmap#1381]
It would be really awesome if players with a specific permission could use the markers set with /dmarker as warp locations and teleport to them.

A command like /dmarkertp id:[the marker id] or /dmarkertp label:[the marker label] would be cool.

**Comment by warsix4** [comment]
Although this is closed, it's unanswered, and if it has been answered elsewhere then the issue was not linked here. Could you link that for us @Psy-Virus ?

**Comment by Psy-Virus** [comment]
@warsix4,
https://github.com/webbukkit/dynmap/issues?utf8=%E2%9C%93&q=label%3A%22Listed+Feature%22+is%3Aclosed+teleport

Using the search function won't kill ya. ;)
