### ISSUE TITLE
People cannot connect to the map

### ISSUE THREAD

**Issue by Carlk** [webbukkit/dynmap#1389]
I want to setup Dynmap so that people can connect to http:/25.81.40.238. Can someone please help me. Whenever someone tries to connect, they get this message "Oops! Google Chrome could not connect" or whatever their browser says for something like this. So,can someone help me to solve this problem?

**Comment by Cewkaurai** [comment]
I have a similar issue: I'm trying to get the plugin working, but it says "ERR_CONNECTION_REFUSED". I have it set to the default (8123), btw.

**Comment by jwshields** [comment]
@Cewkaurai **This issue is nearly 5 years old, why bump it?**

Check your port forwarding and firewall. Please create a new issue if you need more help.
