### ISSUE TITLE
Request for user-defined servlet support

### ISSUE THREAD

**Issue by pucgenie** [webbukkit/dynmap#1397]
Hi, while browsing through DynmapCore java sourcecode I've seen that little effort would be needed to support foreign servlets in the embedded Jetty server.
One could provide canonical names of Java servlet classes in configuration.txt to be configured for Jetty. (I have a low-performance server that would benefit from running just one java instance for Bukkit and web-things together...)

Quick'n'dirty code change: at the end of org.dynmap.DynmapCore.loadWebserver() append something like {
String customServlets = configuration.getString("custom-servlets", "disable");
        if (!"disable".equals(customServlets)) {
            StringTokenizer p2smapping = new StringTokenizer(customServlets, ";", false);
            while (p2smapping.hasMoreTokens()) {
                String[] pathservlet = p2smapping.nextToken().split(",", 0);
                try {
                    addServlet(pathservlet[0], (HttpServlet) Class.forName(pathservlet[1]).getConstructor().newInstance());
                } catch (InvocationTargetException ex) {
                    Log.severe("Could not instantiate a custom servlet.", ex);
                } catch (NoSuchMethodException ex) {
                    Log.severe("Could not instantiate a custom servlet.", ex);
                } catch (ClassNotFoundException ex) {
                    Log.severe("Could not find a custom servlet in classpath.", ex);
                } catch (IllegalAccessException ex) {
                    Log.severe("Could not instantiate a custom servlet.", ex);
                } catch (InstantiationException ex) {
                    Log.severe("Could not instantiate a custom servlet.", ex);
                }
            }
        }
}

BR,
Johannes

PS: Should I create an issue ticket for this in DynmapCore?

**Comment by Psy-Virus** [comment]
If this is still relevant, pls recreate the issue or send a direct PR.
