### ISSUE TITLE
Write "dynmap fullrender" output to console/log

### ISSUE THREAD

**Issue by Programie** [webbukkit/dynmap#1398]
I just created a cronjob on my server which starts a fullrender every day via RCON.

The problem: I don't see any message in the server log. The "Full render starting on world 'main'..." only get's sent to the client connected via RCON (My cronjob).

Yes, I could simply redirect the RCON output to my server.log, but that does not fixes the next problem: Write a message to the log as soon as the render job finished.

It would be cool to have some option in the configuration.txt of dynmap to configure logging (e.g. whether fullrenders and radiusrenders should be logged, or just one of them, or nothing).

**Comment by Psy-Virus** [comment]
That's actually not a bad thing.
Listed
