### ISSUE TITLE
Water Rendering Grey, Instead of blue

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#1403]
Hello, i understand you have had the same issue about a year ago with another client, i am using the misa texture pack for 1.6.2, i had a good ol' look through the configuration and could not find anything related to fixing this effect. I understand the client requires mcpatcher to fix the custom colors in the water. So basically is there still a method using dynamic map to allow custom colors?

Note: The water was working as it should for you dynmap builds that worked with 1.5.2 its only the latest update builds where it does not.

**Comment by User198263321** [comment]
This is probably not going to get fixed but I'll put this here anyways. The water is rendering back on mc 1.4.7 with Dynmap 2.0.0-775

![image](https://user-images.githubusercontent.com/53535277/123341068-501f6480-d51b-11eb-8f6c-9dad3591e8d1.png)
