### ISSUE TITLE
Terrafirmacraft support broken (partly fixed) -- but thatch still doesn't render

### ISSUE THREAD

**Issue by kotoroshinoto** [webbukkit/dynmap#1408]
i noticed you had dynmap working with TFC at one point, but now ... it doesnt.

might have broken with the changes that came with 1.6.2

--edit: most of it works now, but thatch doesn't render at all

**Comment by InsaneJ** [comment]
Using Dynmap Dynmap-2.4-forge-1.7.10 and TerraFirmaCraft-0.79.29.922 the grass blocks seem to render with transparent sides. The top of the grass block renders as expected so this can only be seen in surface maps like below:
![dynmap-tfc-grass_block_sides1](https://user-images.githubusercontent.com/1933471/36200312-94e03678-117c-11e8-8aae-bed8ffe6fc84.png)

![dynmap-tfc-grass_block_sides2](https://user-images.githubusercontent.com/1933471/36200322-99e6849c-117c-11e8-9acf-25c3dfc6923e.png)

This happens with default settings. I've also tried using the mod scraper but this didn't solve this issue.

**Comment by Psy-Virus** [comment]
If this issue still persists, okease reopen it or create a new one with updated details.
