### ISSUE TITLE
Smeltery, Fancy Bricks and others won't render.

### ISSUE THREAD

**Issue by ThatDorkyGuy** [webbukkit/dynmap#1412]
Hey Mike - we appreciate and love your mod. I am running FTB Unleashed + Gregtech thrown in and using MCPC+ 1.5.2-R1.1-Forge738-B636 and your DynmapForge 1.9 Alpha 3 - 7.8.1 (Head - from like a week ago).

I have the DynmapForge in my Mods folder, The Bridge in the Plugins. I've done a full render. Everything shows for the most part, but things like, Fancy Bricks and Smelteries won't show. I'm guessing it's the Smelt Bricks overall.

I have done a bunch of research and have added these lines to my config (this may not even be relevant anymore, but through googling, this is what I found):

buildcraft-support: true
ic2-support: true
ic2-chargingbench-support: true
ic2-powerconverters-support: true
netherores-support: true
railcraft-support: true
forestry-support: true
redpower2-support: true
computercraft-support: true

My map is located at: 198.8.93.49:8117

As you can see, our spawn is broken in to 4 corners. Each corner has a pyramid with a beacon in the middle and the pyramids are made from Fancy Bricks. The roads that you see, the outside border of them, are also made from Fancy Bricks (I was to say it's Fancy Blue Bricks, Fancy Red, Fancy Purple and Fancy green). I personally have a smeltery on my plot which is located by the bloodwood trees in the right corner (you'll notice them by the leaves towards the ground as they grow upside down). You see a shadow spot there for the smeltery.

My question is, is there something I can do to get these blocks to show? Perhaps I am missing something basic?

I have not edited anything in the shaders, nor am I using a texture pack. This is all standard Dynmap.

Thank you so much Mike!

-ThatDorkyGuy
http://www.thatdorkyguy.com (Minecraft Community)

**Comment by Psy-Virus** [comment]
No convo since years - Closing
