### ISSUE TITLE
Markers only show after setting markup

### ISSUE THREAD

**Issue by G4meM0ment** [webbukkit/dynmap#1422]
I've used the cmds /dmarker add id:<id> <name> set:<set>.
It give me a positive feedback that the marker was created. And on checking it with /dmark list it returns the marker corretly but "markup" is set to false.
A look on the map doens't show any of the markers. I used the update command and set markup:true now the marker shows up until I reload the map webpage.
markup is still true for the marker and after setting it to true again it will show up again until next reload.
I'm using Spigot 1.6.2-R0.2 several standart plugins (I could give you a list on request, but it shouldn't affect dynmap). The OS Iam using is Linux. I haven't used imported icons.

BTW: I enabled labels and signs and signs won't turn into markers. [dynmap] and information like icon:<incon> stays.

**Comment by Psy-Virus** [comment]
No updates since years. Assuming it's fixed - closed
