### ISSUE TITLE
Translate messages

### ISSUE THREAD

**Issue by mrcobayo** [webbukkit/dynmap#1426]
Hello! how translate messages of dynmap in my server?

For example "you are now visible in Dynmap" to "Te has vuelto visible en el mapa online" (spanish)

??

**Comment by generrosity** [comment]
Searching I found this confirmation that its doable in the configuration.txt (other than errors) - https://github.com/webbukkit/dynmap/issues/456

**Comment by Psy-Virus** [comment]
@generrosity, since you're working on the wiki. Is there a page for the translation stuff? If not, could you create one?
