### ISSUE TITLE
IE10 Metro zoom not working

### ISSUE THREAD

**Issue by WarriorXK** [webbukkit/dynmap#1444]
When using the metro IE10 app zooming on a dynmap webpage it actually zooms the page instead of the map, I've tested and confirmed with problem with Dynmap 1.6 and dynmap 1.9-1811.

**Comment by Psy-Virus** [comment]
There are zoom buttons on the left. They can be tapped.
If this is not enough or still an issue, please reopen this issue or open a new one if there's no other issue, regarding this problem, existing.
