### ISSUE TITLE
Black patches zoomed out but not when zoomed in. Artifacts

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#1448]
The title speaks for itself. When a full render is complete the zoomed out view has areas that are black. However, when you zoom in on these areas, they appear to be fully rendered. This happens in both the flat and surface modes. However, it is considerably worse in the surface view. I have tried completely removing dynmap by deleting the jar and folder, then restarting after replacing the jar. No change. Tried running same scenarios on another system. No change. Tried running it on a completely fresh world. No change. Help! To see this issue visit http://ferelgon.minecraftier.org:8123

EDIT: The artifacts seem to disappear at around zoom level 7. I still can't figure this out. After I made the flat view hires the artifacts on it got as bad as the surface map.

**Comment by Psy-Virus** [comment]
Known bug.
