### ISSUE TITLE
Mekanism, UE, TE

### ISSUE THREAD

**Issue by grimuars** [webbukkit/dynmap#1476]
Hello!

Do you plan add support for Mekanism & Universal Electricity mods?

And for new version of Thermal Expansion (now dynmap spam to log with messages like [WARNING] Resource assets/thermalexpansion/textures/blocks/Engine_Steam.png for mod ThermalExpansion not found).

Thank you!

**Comment by Psy-Virus** [comment]
if the Dynmap Modscraper or block scanner isn't working or helping and it's still an issue, please open a new issue with updated details.
