### ISSUE TITLE
Essentials config option causing names not to appear on map/sidebar.

### ISSUE THREAD

**Issue by Bronski** [webbukkit/dynmap#1478]
It looks like Essentials(Chat?) is having an issue with Dynmap.  When this setting in Essentials config is set "change-displayname: true", names won't display for users on Dynmap anymore.  I'm not sure which plugin is at fault.

CB 2943 (1.7.2 dev) / Ess 2.13.31 (dev) / Dyn 1.9.1

**Comment by Psy-Virus** [comment]
If this is still an issue, please reopen it with updated details.
