### ISSUE TITLE
Adminium Map integration with dynmap with web login enabled

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#1487]
This would be more of a feature request (don't know where else to write this, new to github).
Is it possible to add an exclusion for app access to dynmap via adminium app on iOS?
Otherwise entering login details becomes a pain every time with web login required.

Thanks

**Comment by Psy-Virus** [comment]
If this is still an issue, please reopen it or create a new one with a better explanation about what you want to achieve. With other words, I don't get it and will close it because it's old and no one reacted to it :-P
