### ISSUE TITLE
Requesting Support for ProjectRed

### ISSUE THREAD

**Issue by Malific** [webbukkit/dynmap#1493]
RedPower2 is has been remade as ProjectRed, it's part of the 1.6.4 Direwolf20 FTB Mod pack.

As of right now you still have all the rp2 -texture and -model files but they don't reference anything since the mod itself has changed names.

File and texture location/formatting has changed as well, I'm sorry to say.

I've been trying to write a renderdata file for some basic support since my largest structure is Marble and doesn't get rendered on the map, but I'm having zero luck. The Texture References (<index>:<texture-id>) section of your wiki could really use some practical examples like the Texture Definitions section has.

I then tried just using the block-id-alias in the configuration file... but it doesn't like metadata and crashed my whole server when I tried to do things that way.

**Comment by cyris69** [comment]
Not trying to resurrect a crypt but having similar issue with dynmap for 1.7.10. Got the recent scraper and have textures and models output. Now what do I do with those files?
