### ISSUE TITLE
Shader temperature not working.

### ISSUE THREAD

**Issue by doums** [webbukkit/dynmap#1498]
Hello,

Sorry for my bad English but I'am french so.. I need help setting up my dynmap :

```
I use the HDMap hires map templates (I enable hires in configuration.txt). And I would like to make a temperature map for the normal world. In template folder/custom-normal-hire.txt i add this :

- class: org.dynmap.hdmap.HDMap
name: temperature
title: "temperature"
prefix: bt
perspective: iso_N_90_hires
shader: temperature
lighting: default
mapzoomin: 3


But the render of the temperature map on web page dynmap is bad : The map is completely blue. It's normal ?
```

http://hpics.li/c1b4e80

```
Yet on my map you can see jungles, extreme hills, mega taiga, mesa...
```

Dynmap version : 1.9.1-1830
Minecraft version : 1.7.2 with Bukkit

**Comment by Psy-Virus** [comment]
Is this still an issue? If so, please recheck with latest supported versions. If this doesn't help reopen this issue or open a new one with updated details.

**Comment by MentalDisorder** [comment]
> Is this still an issue? If so, please recheck with latest supported versions. If this doesn't help, reopen this issue or open a new one with updated details.

Still an issue with the latest version. Though it seems to be rather wonky.  I had a partial render done (had to stop for different reasons) where it actually seemed to use colors, but when I resumed it later, it just plastered blue all over it. You can even see the relief of the actual landscape below it, but it's all blue now. 

Some pointers might help, as there are no examples on how a map would be well configured to work with that shader. Haven't gotten to test it yet (large maps are still rendering), but I fear that rainfall and other's might have similar issues?

This is how I defined the map:
```
 - class: org.dynmap.hdmap.HDMap
        name: surface.temp
        title: "Flat Temperature"
        prefix: temp1
        perspective: iso_S_90_vlowres
        shader: temperature
        lighting: default
        mapzoomin: 2

```


![image](https://user-images.githubusercontent.com/637443/62617901-3b2f8d00-b913-11e9-8ff8-876a09d09ae0.png)
