### ISSUE TITLE
Grass is black

### ISSUE THREAD

**Issue by AdmiralAnimE** [webbukkit/dynmap#1499]
Using Bukkit 1.7.2 R0.2 Beta, tried Dynmap 1.9.2 alpha1 and alpha2.
I'm using John Smith Lecacy pack to render the map, but the grass in every biome is black. I assume the map is using grass_top.png, which is present.

This is the actual map: http://hmcp.servegame.com:8123/
And a screenshot if it's not working/online:
![asd](https://f.cloud.github.com/assets/6396538/1907843/eea72022-7cde-11e3-9572-3d107c4b49ff.jpg)

Btw, the Mobs and Worldguard addons are not showing on the map.

**Comment by otse** [comment]
![image](https://user-images.githubusercontent.com/1123362/80686113-85bbef80-8ac8-11ea-8bb0-6705f461ce54.png)
Hi, ChromaHills is giving me these black grass spots.

Edit: Every texture pack gives me the same black fringes! Do I need a new issue?

**Comment by samuelh2005** [comment]
>
> Edit: Every texture pack gives me the same black fringes! Do I need a new issue?
>
@otse You probably do, because this one is closed.
