### ISSUE TITLE
Disable chat channels from webchat

### ISSUE THREAD

**Issue by Fjordcraft** [webbukkit/dynmap#1501]
Is there any way to disable townychat channels from being visible on the web chat on the map from dynmap? I know I can disable all chat's but since admin chat and mod chat isn't visible I have a small hope there is some way of doing this.  I've been searching on google and looked thru all configs for possible ways to do something like this.

**Comment by Psy-Virus** [comment]
This seems to be towny related. Please open an issue for this in the [towny issue tracker](https://github.com/webbukkit/Dynmap-Towny/issues), if something you'd like to have implemented.
