### ISSUE TITLE
Implement CraftBukkit Async Chunk Loading

### ISSUE THREAD

**Issue by aikar** [webbukkit/dynmap#1508]
Using Reflection, implement Async Chunk loading so that dynmap does not trigger lots of Sync Chunk Loads.

**Comment by SpiderRobotMan** [comment]
I know this is really old, but has it ever been implemented? Having lots of trouble with dynmap loading chunks.

**Comment by Psy-Virus** [comment]
If I remember right, there's a new issue regarding async chunk loading. I'll close this.
If my memory is completely broken, please reopen this or create a new issue with updated details. Thanks
