### ISSUE TITLE
Performance Mode option

### ISSUE THREAD

**Issue by aikar** [webbukkit/dynmap#1509]
Requesting support for a Performance Mode flag that tells DynMap to not automatically load any chunks needed to render, and to instead simply add them to a watch list so that if a player triggers them instead with movement (very common case) that it would then be processed.

The chunk to be rendered and the current loaded surrounding chunks needed should be cached until the missing chunks are loaded incase movement happens to unload another chunk that was needed still, but these cached chunks should have a 3 minute~ time to live.

This kind of queue would greatly help where dynmap is essentially jumping the gun and loading a chunk sync that is likely to be loaded any moment now async.

If Async Chunk Loading is implemented, this option will still be useful to reduce the overall # of loaded chunks from DynMap, and if a chunk never gets loaded that was needed, then simply let that tile stay out of date.

I would much rather have out of date tiles to save server performance.

**Comment by Psy-Virus** [comment]
This is already implemented as a "shut up dynmap if there's too much load" option.
