### ISSUE TITLE
Havign trouble with making players visible

### ISSUE THREAD

**Issue by stevewall85** [webbukkit/dynmap#1514]
I have used Dynmap for a good long time and love it! With the current updates when any player logs in opped or not they dont show on dynmap unless i use /dynmap show  other then that i have seen that dynmap appears to treat everyone as a hidden player and stores them in the hidden player file automatically. I dont have the option set to use that as a white list and most things are default. Any help is appreciated.

This server is running CraftBukkit version git-Spigot-1308 (MC: 1.7.2) (Implementing API version 1.7.2-R0.3-SNAPSHOT)

http://pastebin.com/70D1PMw1   - dyn config 
http://pastebin.com/651MVR08   - world guard report 
http://pastebin.com/40xcAW1b    - vnp config

**Comment by Psy-Virus** [comment]
Closing due to old issue.
