### ISSUE TITLE
Dynmap-1.9.2-forge-9.11.1 on OpenMediaVault server white screen.

### ISSUE THREAD

**Issue by drago87** [webbukkit/dynmap#1536]
Hi i have installed McMyAdmin on a OpenMediaVault server and when i start the server and try to conect to ip:8123 i only get a white screen. (i'm also using dynmap-mobs-0.90)
It worked when i had the McMyAdmin on my win 8.1 gaming computer.

**Comment by Psy-Virus** [comment]
This is not directly related to Dynmap. If this problem still persists, you should ask your hosting company for advice or ask in a support forum.
