### ISSUE TITLE
separate path for json files

### ISSUE THREAD

**Issue by timriker** [webbukkit/dynmap#1541]
Mike, as we discussed on irc:

When not using stand alone, json files are in the same directory as the php files. It would be nice to have the json files written in dynmap/web/json/ instead of dynmap/web/standalone/ by both the dynmap plugin and the webchat server side. This would allow linking that directory to a ram drive on platforms that support it.

I'd have an init script or run-on-reboot cronjob do this as root:

```
# mkdir /run/dynmap
# chown www-data:www-data /run/dynmap
```

then link dynmap/web/json to /run/dynmap or change a configuration.txt value to point there which both the plugin and the web interface would need to adjust. The symlink version avoids running a php script and can be just static files as the path is still there.

now all json writes for player postition, webchat, etc are just hitting /run which is tmpfs and stays in memory. True even for non-login setups.

Feature for advanced users to be sure, but should be relatively easy to implement.

**Comment by timriker** [comment]
This is closed, but was it accepted and implemented, or rejected?

**Comment by Psy-Virus** [comment]
Hover over the "Feature Listes" label.

It will be listed in a separate issue. So we have a consolidation of features and not everything spread over 700 open issues.
