### ISSUE TITLE
[request] Web-fonts for Markers

### ISSUE THREAD

**Issue by FrozenBeard** [webbukkit/dynmap#1543]
Webfonts have exploded for many reasons in web-design, Developing support to use a web-font icon pack would dramatically increase the Icons available ten fold, as well as resource and bandwidth saving.

http://fortawesome.github.io/Font-Awesome/
http://shoestrap.org/downloads/elusive-icons-webfont/

**Comment by Psy-Virus** [comment]
Cool idea. on the List.

**Comment by FrozenBeard** [comment]
@Psy-Virus  bloody hell I requested this in 2014! Font awesome has EXPLODED since then and is massive, the other ones shut down new website https://fontawesome.com/
