### ISSUE TITLE
Players are not invisible until Server reload

### ISSUE THREAD

**Issue by MayorMike** [webbukkit/dynmap#1544]
The way I want it is that all players are invisible to each other. 

Unfortunately, any new user that registers to the Map can see everyone unless the server gets Reloaded and then it works how it should.

Admins can see everyone at anytime with the seeall permission.

Any clues?
Thanks for your time.

EDIT: One of my players just informed me that he is seeing others again, but it doesn't seem to be all. 
Dynmap Towny causing this?

**Comment by Psy-Virus** [comment]
Does this issue still persist? Then please reopen or create a new issue with updated details.
