### ISSUE TITLE
ComputerCraft blocks not rendering

### ISSUE THREAD

**Issue by gellis12** [webbukkit/dynmap#1545]
I've installed the ComputerCraft pr2 public beta and Dynmap 1.93 on a Forge server, and all CC blocks are either rendering incorrectly, or not at all. The few blocks that do show up (such as advanced monitors, disk drives, and the front of advanced computers) simply render as solid grey with a dark grey outline at the edge of the block. Networking cable shows up as unconnected tiny grey cubes, and turtles and the sides of computers do not render at all. Have I missed something blatantly obvious in a config file, or is this Dynmap not agreeing with the ComputerCraft beta version?

A large wall of Advanced Monitors
![screen shot 2014-03-12 at 10 26 46 pm](https://f.cloud.github.com/assets/4123225/2406466/2ea8ebba-aa70-11e3-9a61-bf91bab809ad.PNG)

An Advanced Computer (with an invisible side) next to a Disk Drive
![screen shot 2014-03-12 at 10 26 21 pm](https://f.cloud.github.com/assets/4123225/2406467/2eb0847e-aa70-11e3-84ec-59deb5299eb2.PNG)

**Comment by Psy-Virus** [comment]
Still an issue? Then reopen or create a new one with updated details.
