### ISSUE TITLE
Webpage keeps refreshing

### ISSUE THREAD

**Issue by hockeymikey** [webbukkit/dynmap#1546]
The map loads and everything seems fine but then right after it refreshes the page and it goes in an endless loop.  I'm using apache for it.  The configuation should be fine because it was working good before a few days ago when this started happening.  The OS is ubuntu.  I read an earlier issue with apache not have permission well I did.

chown -R www-data:www-data /var/www

To try to give it permission with no success.  Should I add apache to the group that the JVM is in?  How would I find and go about doing this?

Thanks.

**Comment by dskw** [comment]
Same problem here, but I cannot see any missing files. So far I have changed the configuration to update only on chunkpopulation and chunkgeneration.

There was also one tile constantly being updated for no visible reason, so I've replaced all blocks in that coordinate and the tileupdates stopped.

So now there is nothing left that could cause these updates. Even purgeworld and fullrender do not help. The page is constantly updating for no good reason.
Is there any way to debug this?

**Comment by pyro000** [comment]
I think that I solved it resetting all apache and minecraft server.

**Comment by Isla-Liu** [comment]
if u are keeping refresh to ?worldname=&*
the good for code way is try restart minecraft server and nginx server,or drop dynmap database and reset.
if still don't work,second fix way is go to /web/js/map.js
line 651~654
```JavaScript
				if(me.options.confighash != update.confighash) {
				    window.location = me.getLink();
					return;
				}
```
Comment out them like
```JavaScript
		                //if(me.options.confighash != update.confighash) {
				//    window.location = me.getLink();
				//	return;
				//}
```

**Comment by Underlyingglitch** [comment]
I know that this is a very late response. Commenting out the me.options.confighash etc. line did resolve the problem. It started another. 

The ingame time jumps between somewhere in the day, to somewhere at night all the time. (In the game it is actually night.) So when dynmap thinks it's night, the online players show up in the list, and on the map. But when it thinks its day, they dont appear to be online?

Could it be that 2 things are writing to dynmap? (I'm using a second apache server for the webserver) One with the correct data, and one with false data?
