### ISSUE TITLE
Immibis Microblocks not rendering

### ISSUE THREAD

**Issue by vScourge** [webbukkit/dynmap#1547]
None of my blocks from Immibis Microblocks render on our Dynmap.  It looks like support for that was added in 1.8... is there something special I need to do to enable it?

Using Forge 9.11.1.965, MC 1.6.4, Immibis Microblocks 57.6.3, and Dynmap 1.9.2-111

**Comment by ADoby** [comment]
Not working with:
Dynmap v2.2 (1.6.4 Version)
Forge 9.11.1.965 (1.6.4)
immibis-microblocks 57.6.3

Map looks awful :D

**Comment by TheCherry** [comment]
same here :( have now to build my whole house with normal blocks, else can everybody look into it ...

**Comment by Psy-Virus** [comment]
Is this still an issue? Then please reopen or create a new issue.
