### ISSUE TITLE
Underground biomes and factorization mods not supported?

### ISSUE THREAD

**Issue by skicek** [webbukkit/dynmap#1556]
Hello,
Underground biomes and factorizations mods are not supported? because in Dynmap v1.9.3: version there are not rendering on the map http://mc.runescape.pc.pl:8123/ 
but if i use Dynmap v1.9.4-alpha-1 i got memory heave load on cpu and memory...

**Comment by Psy-Virus** [comment]
I think with the mod scraper and the block scanner this shouldn't be a problem anymore? If still an issue, please reopen or recreate.
