### ISSUE TITLE
Deleting dynmap

### ISSUE THREAD

**Issue by Maxipan** [webbukkit/dynmap#1562]
So I installed dynmap and enjoyed using it. Now that I wanted to do a server reset and delete everything, I also went ahead and deleted dynmap over ftp. It has been deleting for 24 hours now and still isn't finished. Is there a faster way to do this cause the deleting isn't even half way done.

Thank you
Maxipan

**Comment by SashaGelert** [comment]
Another option would be to relocate the dynmap data.  instead of keeping all map data in the global folder, store it within the world-save folder.  This would allow a quick deletion of everything without having to fiddle with enable/disable, etc.

**Comment by jwshields** [comment]
This was solved 4 years ago. Why bump it?

**Comment by EmanuelSimard** [comment]
rm -rf /home/minecraft/plugins/dynmap
