### ISSUE TITLE
Issue with Custom Icons.

### ISSUE THREAD

**Issue by yaitsbilly** [webbukkit/dynmap#1563]
Would this be correct?

/dmarker addicon id:flag Flag file:Path to icon

keep getting,
 File:"Filename" required

**Comment by Kingdingbat** [comment]
I have the same problem. I can only get it to work if I upload the file to the root directory of bukkit and do not use the "/" on the file path. For example, I can only be successful if I use "file:imagename.png" but not "file:/imagename.png"
