### ISSUE TITLE
Immibis microblocks not working propertly

### ISSUE THREAD

**Issue by skicek** [webbukkit/dynmap#1576]
http://mc.runescape.pc.pl:8123/# all microblocks from immibis are rendered as stone. Today i updated to 1.9.4. Mc 1.6.4 version

edit.
also ore from metallurgy v3.3.2 is not rendered.

**Comment by Psy-Virus** [comment]
Mc 1.6.4 isn't supported anymore. If the issue still exists with MC >= 1.8.9 pls reopen or create a new issue with updated details
