### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by AdmiralAnimE** [webbukkit/dynmap#1582]
I love this plugin, however I have a big problem with used memory. Currently I'm using bukkit build 3020 with dynmap 1.9.4 on windows 7, but I've had the problem for months, maybe more. I guess at some point you changed something in the plugin. I've had the map on my server for years, but there were no memory issues at the beginning. 

I tried to find what's causing the huge memory usage/leak on my server, removed one by one the plugins - the result is dynmap. I'm using bukkitGUI to set and monitor the server's memory usage. Currently set at max 2GB. So with everything else running on my pc, I should have 4500-5000mb max memory usage. However, sometimes it goes to 7000, even 7800. I have only 8GB. The server cannot use more than 2GB, and it isn't. The problem is that when i start the server and wait for maybe 30 min, i can see the memory going up a few mb per second. If i remove dynmap and restart the server, it doesn't go up. This is happening every time, doesn't matter if the server is empty or not. If i stop the server, the memory is not released, so i have about 4500-5000 without the server running!? I have to restart the pc, if want normal memory usage again.

Can you tell me what's causing it, can it be fixed, what can i do?

**Comment by Psy-Virus** [comment]
Still an issue? Then please reopen or create a new one with updated details.
