### ISSUE TITLE
1.9.4 Breaks Sign Markers

### ISSUE THREAD

**Issue by FrozenBeard** [webbukkit/dynmap#1591]
I see that you implemented default Marker-set for signs! Which is superb, Its just after updating form 1.9.2, Using Signs to create Markers no longer works, Has the config file changed much?
Also what config option do I add for Default sign marker-set and what section do I put it under? do you have a recent config file I can compare mine too?

EnableSigns: True
Configuration.txt http://pastebin.com/FyBvEFAE

**Comment by durand1w** [comment]
Do we know if this should work on a Forge only 1.10.2 server?  I know previously there was no forge update sign event, but trying to confirm if it should or should not work despite the configuration flag.
