### ISSUE TITLE
Some large areas not being rendered at the furthest distance. When zooming in 2 ticks they display correctly.

### ISSUE THREAD

**Issue by AdamEttenberger** [webbukkit/dynmap#1600]
Running Bukkit 1.7.9-R0.1

![untitled](https://cloud.githubusercontent.com/assets/3311850/3056528/8d8bd3da-e1cb-11e3-939d-9b3af6d5ae16.png)

**Comment by rocky1138** [comment]
This is happening to me. I'm on the latest version.

https://minecraft.xandorus.com.
