### ISSUE TITLE
World Limits not working

### ISSUE THREAD

**Issue by doomlordking** [webbukkit/dynmap#1606]
I tried limiting my map with visibilitylimits: didn't work then hiddenlimits: still did not work, it still displays all the land.

Dynmap version: core=1.9.4-1940, plugin=1.9.4-991
CraftBukkit version git-Spigot-1455 (MC: 1.7.9) (Implementing API version 1.7.9-R0.1-SNAPSHOT)
Dynmap-Towny-0.50.jar
World.txt http://pastebin.com/fA7Pqr4r

**Comment by BleesTFE** [comment]
Fucking 2 years ago and no response yet. And this is one fucking popular plugin too. That's crappy
