### ISSUE TITLE
IP for our server shows a different server's dynmap

### ISSUE THREAD

**Issue by RogueWolf5** [webbukkit/dynmap#1617]
Earlier, when we first downloaded dynmap, it worked perfectly. One day, it stopped showing our server's map and instead showed the map of another server. We didn't change anything, it just happened. Our old server got deleted, and I tried installing dynmap on our new server. I typed in our IP with the :8123 at the end, and it pulled up a dynmap of a server called Creeper Craft. I've double checked and I'm using our server's correct IP, but it's still showing Creeper Craft.

**Comment by killyouslow** [comment]
Change the port number in your dynmap config to use some other port, like instead of 8123 try 8000 or 7000 or 7123, should fix the problem no sweat :P oh and dont forget to port forward the new port number!
