### ISSUE TITLE
Dynmap not displaying mods and player icons correctly

### ISSUE THREAD

**Issue by sunsmasher** [webbukkit/dynmap#1622]
So I have two issues. First, out of no where, Dynamp stopped displaying player tokens. This is the most odd because for the history of the server it's always worked properly.

Secondly, I have two mods that are not displaying items on Dynamp: Twilight forest and More foods. Neither mod seems to work, and I've tried several different versions of Dynmap.

I am running a server with Forge 1.7.2, and Dynmap-1.9.4.1-forge-10.12.0.
http://tian.serverminer.com:24899/
Thanks.

**Comment by Psy-Virus** [comment]
Mc 1.7.2 isn't supported anymore.
