### ISSUE TITLE
No spawn_bed data is being saved to my markers file

### ISSUE THREAD

**Issue by gmoff01** [webbukkit/dynmap#1632]
I have spawn beds enabled in the config:

```
showspawnbeds: true
spawnbedlabel: "Spawn Beds"
spawnbedicon: bed
spawnbedhidebydefault: false
spawnbedminzoom: 0
spawnbedformat: "%name%'s bed"
```

And it does enable the layer for my map, but no icons appear.  On closer inspection, it appears that no data for them is being saved to the markers.yml file:

spawn_beds:
        circles: {
            }
        hide: false
        markers: {
            }
        layerprio: 0
        areas: {
            }
        deficon: default
        lines: {
            }
        label: Spawn Beds
        minzoom: 0

This has been the case across many versions of dynmap over the last few years, currently v2.0.0-alpha-1.  Is there something I'm missing that is preventing data from being saved?  Player locations and offline locations work fine.

**Comment by Psy-Virus** [comment]
Still an issue with latest supported DM versions? Then reopen or recreate the issue pls
