### ISSUE TITLE
Server stop responding upon completion of fullrender

### ISSUE THREAD

**Issue by chuck4100** [webbukkit/dynmap#1634]
As per title, three maps now have given me the "server stopped responding" crash. Didn't see an existing ticket for it.
Pasted the error.
http://pastebin.com/u2ABqCXD

**Comment by Tsunayoshi** [comment]
I can confirm this problem. I have to fullrender every map with world:surface world:cave... and after every completed map the server stops responding. No crash, only no resond on  the console.
after a hard stop and restart of the server, the fullrender will start again. so I do a cancelrender. The files, after that 	procedure, in my mysql database are up-to-date.

So this should be reopen!
Also version 2. alpha 1 and 2
