### ISSUE TITLE
Biome shader  : caption/legend on dynmap

### ISSUE THREAD

**Issue by mblob** [webbukkit/dynmap#1641]
cauldron-1.7.2-1.1147.04.103
Dynmap-1.9.4.1-forge-10.12.0
DynmapCBBridge-1.9.4

Is a caption/legend implemented for biome shader enabled map ?
I found tht old thread : 
https://forums.bukkit.org/threads/misc-dynmap-v1-9-2-real-time-minecraft-maps-1-4-7-through-1-7-2r0-3.489/page-163.

Am i missing some configuration option ? 
Is it available in some dev builds?

Tht would quiet usefull.

**Comment by berlincount** [comment]
Hmmm. I'm not sure this ticket was closed with a solution? Could I get a bit more information, please?

**Comment by ghost** [comment]
This was requested in `MaterialDynmap` - SNDST00M/material-dynmap#49.
