### ISSUE TITLE
Block-id-alias expects numbers instead of block names

### ISSUE THREAD

**Issue by Xalcon** [webbukkit/dynmap#1659]
I'm using 2.0.0 Alpha-2 (1.7.10) with a selfbuild modpack, including natura. I tried removing the cloud rendering by adding Natura:Cloud to the configuration file, but the server is crashing on startup with a NumberFormatException. It looks like the configuration options is still expecting the obsolete block id instead of the block name.

http://pastebin.com/yR9HZSkn

**Comment by TheBrain0110** [comment]
This should probably be reopened, since numerical ids have been deprecated for a while now. It would be much better to support named IDs

**Comment by Brycey92** [comment]
Please reopen this!
