### ISSUE TITLE
Dynmap webregister page does not react on register/login

### ISSUE THREAD

**Issue by Jirachi93** [webbukkit/dynmap#1660]
hi there,

i am trying to register and/or login on the dynmap login.html.

when i am in minecraft and enter /dynmap webregister i get the registration code.

when i enter the information on the login.html and hit register the page does not react in any way.
i also dont get an error code or anything.

the same goes for the login. because i just could not register my friend tried it for me and it worked on his first attempt.

so i am still having the problem of not being able to login cause the page does not react when i hit the login button.

the login works for any of my friends and i tried out the following browsers:

opera next
firefox
chrome
Internet Explorer.

none of these worked for me so the problem needs to hide somewhere else... i am running the latest versions of java and flash player on a WIN7 64bit.

Please help me fixing it.

kind regards

Jirachi

**Comment by rysson** [comment]
I have the same bug.

forge-1.10.2-12.18.3.2316
Dynmap-2.4-forge-1.10.2

**Comment by MCTyler** [comment]
Same Bug!
`[05:37:52 INFO]: This server is running CraftBukkit version git-Spigot-23b6354-0481ae9 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[05:37:52 INFO]: Checking version, please wait...
[05:37:53 INFO]: You are running the latest version
[05:37:54 INFO]: [dynmap] Full render of map 'surface' of 'world' in progress - 3000 tiles rendered (403.88 msec/tile, 319.88 msec per render)
>dynmap version
[05:38:00 INFO]: Dynmap version: core=2.5-Dev201706100401, plugin=2.5-Dev201706100405`

**Comment by Psy-Virus** [comment]
UIs this still valid with DM versions > 1.8.9? Then pls reopen or recreate

**Comment by Wolfy8198** [comment]
I'm having the same bug. When I use /dynmap webregister, go to the web page and put in the code, a username, and password, then click register, the web page doesn't respond. I'm running Dynmap version 3.1 on a 1.16.5 purpur server.

**Comment by MCTyler** [comment]
@Wolfy8198 I don't see support for 1.16.5.
