### ISSUE TITLE
No display while using external server and MySQL

### ISSUE THREAD

**Issue by ams2990** [webbukkit/dynmap#1682]
I have configured Dynmap to use an external web server. I also configured it to use a MySQL server for storage. After doing a fullrender, I see ~2400 rows in the `dev_Tiles` table. However, when I loaded the Dynmap page, I got a plain black screen. No sidebar, no zoom buttons, no nothing. I changed the backend to `filetree`, restarted the server, reloaded the page, and got the sidebar and zoom buttons, as I expected.

**Comment by TheMasterofBlubb** [comment]
Pls tell me where did u use this command Client or Server? I think im having the same issue right now
