### ISSUE TITLE
Not rendering colors

### ISSUE THREAD

**Issue by brianamcw** [webbukkit/dynmap#1712]
Dynmap is rendering my world but it is mostly black and white, very little terrain detail though the mountains display and lava does show up correctly?

**Comment by Psy-Virus** [comment]
Did you update your `<BuildTools.jar>`?

**Comment by brianamcw** [comment]
I tried but I guess I didn't understand the post like I said it crashed my server doing it the way I did which was wrong apparently. I got a reply at my hosting server site with a link to the latest Spigot release and replaced the jar on my server with that one which then started up fine and now dynmap has rendered me a perfect map. I did also tried to use the dynmap worldgaurd plugin for rendering the regions and that failed I had to remove it I think the plugin is too old probably for either the worldgaurd or dynmap version I am using and I can't find a newer version so I guess that option is out.

**Comment by ticklemehballlz** [comment]
What server version are you using? 

If you are using Spigot, then please run BuildTools.jar and then copy the Spigot jar that is created and placed into your user account directory, move this to your minecraft folder and reboot the server.

**Comment by mikeprimm** [comment]
Yep - that is downlevel Spigot bug.  Only option is updating it properly.
