### ISSUE TITLE
Not Showing Online Players Cauldron_1-7-10_1-1207-01-198

### ISSUE THREAD

**Issue by Morketh** [webbukkit/dynmap#1713]
i have installed the same dynmap file (Dynmap-2.0.0-forge-10.13.0) with both Vanilla_Server_1-7-10_Forge_10-13-2-1236 and with Cauldron_1-7-10_1-1207-01-198
online players are visible on the Vanilla server and not displayed on the cauldron server all other map functions work including chat and rendering not sure whats the problem here i hope its not a bug and just something i haven't provided to cauldron any help in this problem would be gratefully accepted
thanks again in advance

**Comment by mikeprimm** [comment]
On cauldron, try adding the DynmapCBBridge plugin

**Comment by Morketh** [comment]
looks like a good plugin, however version 2.0.0 available on Curse only supports MC 1.6.4 also the code doesn't look like its been updated for about 3 months and that was the 1.6.4 update. will that version work with 1.7.10? its not a big issue nor a high priority. i will toss in the plugin and if it breaks  the server (not surprising if it does) i will just wait till the plugin updates.
thank you for the help @mikeprimm

**Comment by hanakocz** [comment]
I have Cauldron version 1231 and everything works perfectly:) Without any other plugins, just probably right setup of config

**Comment by Morketh** [comment]
not exactly sure what it was nor did i really change anything and 3 days ago it just started to show players online im not sure what that was all about but normaly when i set up a regular forge server it worked out of the box even in my developing evironment on my localhost im going to mark this as solved but im not able to provide any reason as how or why it was solved
