### ISSUE TITLE
Huge pending files and Dynmap not rendering certain maps

### ISSUE THREAD

**Issue by orgiz** [webbukkit/dynmap#1714]
Hi,

Since I updated to Spigot 1.8 and Dynmap 2.1 alpha I now have some render problems on two of my maps. 

My problem maps are:
Cyber
Cyber_nether

Cyber2 seems to be alright and the map are updating like it should.

I can see that all tiles are put in the pending file and it wont get rendered at all.
Cyber.pending has about 9300 pending tiles
Cyber_nether.pending has about 2200 pending tiles.
See this image:
http://imgur.com/hqDJvMg

Log from /dynmap stats
http://pastebin.com/xtQxkJhA

configuration.txt:
http://pastebin.com/CtCAKxD6

world.txt:
http://pastebin.com/FNu4AwiE

Versions:
Spigot:
git-Spigot-13716d9-eae50b4 (MC: 1.8)

Dynmap:
2.1-SNAPSHOT-1077

Can you please help me point out the problem?

My Cyber map is huge (750 GB), so im thinking "saverestorepending: true" can have somthing to do with this?

Worth mention, my server have crashed several times due to the 1.8 update.

Best regards,
Orgiz

**Comment by orgiz** [comment]
This are the shutdown message from Dynmap: 
http://pastebin.com/GHkavaRA

**Comment by fungreenfox** [comment]
I have the same problem with the main world. The map is Triggered update queue size: 100 + 1091850 and should be zero very fast.

**Comment by mikeprimm** [comment]
Check /dynmap pause output - if your tps is below 18, default configuration will cause rendering to pause until its faster than that.  You can change the settings in configuration.txt
