### ISSUE TITLE
Issue with WorldBorder on Dynmap

### ISSUE THREAD

**Issue by MetalGearDaner** [webbukkit/dynmap#1715]
This is the result of the error. No information printed on console, using latest dynmap build & Spigot 1.8.
(Map is not rendered)
http://i.imgur.com/qOXmTHG.png

**Comment by mikeprimm** [comment]
No image on imgur - repost

**Comment by MetalGearDaner** [comment]
Woops, I will upload the imagen this afternoon. (GMT+1)

**Comment by MetalGearDaner** [comment]
Here is the image:

http://i.imgur.com/yEjY9gA.png

**Comment by mikeprimm** [comment]
Try latest dev build - you might need to flush browser cache (shift-reload) after updating to see fix quickly.

**Comment by MetalGearDaner** [comment]
I've just installed latest development build (v2.2-alpha-1), refreshed browser cache, and it does not seem to be fixed. The border errors continue appearing.

**Comment by MetalGearDaner** [comment]
Now fixed, don't know why, but now the problem doesnt appear!
