### ISSUE TITLE
Textures support - 1.7.10 - GregTech, Chisel, PFAA, Forestry

### ISSUE THREAD

**Issue by hanakocz** [webbukkit/dynmap#1717]
Hi, I would like to have texture support for these well used mods. Thanks
GregTech : http://forum.industrial-craft.net/index.php?page=Thread&threadID=7156
Chisel : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2254671-chisel-2-2-2-0
PFAA: Gelologica : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293751-per-fabrica-ad-astra-geologica
Forestry : https://github.com/ForestryMC/ForestryMC/

Thanks if at least any of these will be added. Maps look ugly without them:)

**Comment by mikeprimm** [comment]
v2.1 GA should have these - at least most of their blocks.  Give it a try

**Comment by hanakocz** [comment]
Ah, very nice! Thank you. Just Chisel is not rendered at all and Carpenters Blocks are showing as redstone....however Chisel seems to be quite more work to do and Carpenters.....well..Don´t know how well can Dynmap render extraordinary shapes of blocks not dependant on ID but which block is placed on them...

Whatever...as I said, Thank you for this great upgrade of our maps :)

**Comment by cullorblind** [comment]
I'm seeing the same thing with Chisel and Carpenters Blocks as well running 10.13.2 on forge 1.7.10 10.13.2.1272.

eg: http://world.suspiciousdisco.com:8123/?worldname=world&mapname=surface&zoom=6&x=127&y=64&z=240

**Comment by evilhamsterman** [comment]
I see the same thing, most chisel blocks didn't even render till I ran the mod scrapper. Carpenter's block render as redstone dust. Also JABBA barrels are not rendered, they aren't even picked up by the scrapper for some reason

**Comment by cullorblind** [comment]
I finally ran the mod scraper on mine, and it's looking a lot better, with the exception that carpenters blocks still render as redstone.  There's quite a few other less noticable model problems with enderio conduits, botania blocks, and forge microblocks don't render at all, but I can live with those for now.

Thanks for a wonderful mapping tool.

**Comment by Zehir** [comment]
See #1671 for Chisel
