### ISSUE TITLE
Map Rendering Issue

### ISSUE THREAD

**Issue by aznboi589** [webbukkit/dynmap#1721]
When my map renders, the maps not showing the landscaping correctly. It's just a coming up with a few blocks here and there and a black background. I've attached a screenshot. I'm running Spigot 1.8 I believe and the latest 2.1 update.
![issue](https://cloud.githubusercontent.com/assets/4505976/5718142/28bed4d4-9ad0-11e4-9350-730c8f64df7a.png)

**Comment by aznboi589** [comment]
I switched to CraftBukkit 1.8 and it works fine, even on 2.2 Alpha. Seems to be a Spigot Issue.

**Comment by mikeprimm** [comment]
You are running and old and unsupported Spigot 1.8 - one probably downloaded from someplace, versus built using BuildTool.jar (the only proper way to get it).  See http://www.spigotmc.org/threads/buildtools-updates-information.42865/ to build yourself a legit and supported Spigot 1.8
