### ISSUE TITLE
[Dynmap-Herochat][1.8]Chat from web interface cannot been seen in browser, but can be seen ingame.

### ISSUE THREAD

**Issue by snhnry** [webbukkit/dynmap#1723]
Users attempting to chat through the web interface cannot see the chat they send, but users ingame receive the message fine, and messages from the game to the web interface show up fine. This leads to web users being unsure if they have successfully sent a chat message.

I'm on Spigot 1.8, but the issue has persisted down through 1.7.9, at least.
Dynmap version: core=2.1-SNAPSHOT-2032, plugin=2.1-SNAPSHOT-1091
Dynmap-Herochat version: 0.50
HeroChat version: 5.6.7

**Comment by mikeprimm** [comment]
Check latest dev build of Dynmap-Herochat - http://mikeprimm.com/dynmap/builds/Dynmap-HeroChat/Dynmap-HeroChat-0.50.jar

**Comment by snhnry** [comment]
Thanks for replying, it still works fine. Any updates on removing the debug text I mentioned?

**Comment by mikeprimm** [comment]
Ah - forgot about that :)  Doing it now.

**Comment by snhnry** [comment]
I really appreciate all the work you're doing for this. Unfortunately a new problem has popped up. Now no chat of any kind is being logged to console.  All commands are logged but nothing from Herochat can be seen in console. Any ideas?
