### ISSUE TITLE
Incomplete Tile Renders

### ISSUE THREAD

**Issue by cmr2333** [webbukkit/dynmap#1727]
Hello everyone!

I've hit a small issue while migrating servers. I switched server hosting providers from Fragnet to Mineocity and got everythings transferred over without a hitch. Everything seems to be working perfectly, however my dynmap seems to not be rendering tiles correctly. I've reinstalled dynmap a few times already  (deleted the dynmap2.1.jar and re-uploaded the latest version and deleted the dynmap folder). The tiles appear to be only partially rendered. I used the exact same template and configuration files from my old host (which worked perfectly) so I am at a loss as to why it is no longer working.

As you can see in the provided link, the tiles appear very dark and only partially rendered. Some structures appear to be fully rendered..but most is just blacked out. Prior to moving servers the map rendered perfectly.

Any ideas?

Screenshot of the map:
http://imageshack.com/a/img673/121/iznSDM.png

Configuration file:
http://pastebin.com/r5B8GTUr
Template File used:
http://pastebin.com/0CTBayhK
worlds.txt:
http://pastebin.com/vahtZ1ja

**Comment by Psy-Virus** [comment]
Looks similar to  #1721, #1711 :-)

**Comment by cmr2333** [comment]
Thanks. It turns out I was not using the proper jar file. I was using an old version of 1.8 Spigot provided by my host and not the one I built and uploaded myself.

**Comment by Psy-Virus** [comment]
You're welcome.
And if all is fixed, please close this issue :-)
