### ISSUE TITLE
Dynmap Forge doesn't update render

### ISSUE THREAD

**Issue by MrsMeowys** [webbukkit/dynmap#1728]
Hello.

I installed a forge server which is using right now dynmap forge 1.7.10. but when people are loading new chunks, or changing the terrain, the map doesn't update by itself like it does in my vanilla server. I have to do a fullrender everyday. I tried to google the problem but can't seem to find a fix for it. How to fix it?

Thank you.

**Comment by MineMine** [comment]
Same problem :(

**Comment by MineMine** [comment]
I found what is the problem

when your server is in load situation (as dynmap configuration)

dynmap doesn't update the map server 

you can decrease dynmap criteria for following options in dynmap/configuration.txt

dynmap default value is 18.0 
you can lower this value, but beware if your server is in busy lowering the vaule can cause unstable situation

># If TPS of server is below this setting, update renders processing is paused
update-min-tps: 16.0 
# If TPS of server is below this setting, full/radius renders processing is paused
fullrender-min-tps: 16.0
# If TPS of server is below this setting, zoom out processing is paused
zoomout-min-tps: 16.0<

**Comment by mikeprimm** [comment]
Yep - that is the right action.  You can see the status by checking '/dynmap pause'

**Comment by lippoliv** [comment]
```
‎18‎:‎31‎:‎05 CONSOLE: 
[INFO] Full/Radius renders are ACTIVE
‎18‎:‎31‎:‎05 CONSOLE: 
[INFO] Update renders are ACTIVE
‎18‎:‎31‎:‎05 CONSOLE: 
[INFO] Zoom out processing is ACTIVE
```

But still: no update render.
I also can't find theese three values in my configuration.txt...

**Comment by MrsMeowys** [comment]
update-min-tps: 16.0 
fullrender-min-tps: 16.0
zoomout-min-tps: 16.0
I edited these on my configuration.txt and still doesn't work.
I also have them active when I do '/dynmap pause'.
Anything else I should edit?
