### ISSUE TITLE
DynmapForge v2.1 webserver-port  doesn't work

### ISSUE THREAD

**Issue by laudamian** [webbukkit/dynmap#1729]
Hi, 
I have problem, or I'm just stupid, but I use this option in my Couldron 1.7.2 server and everything worked ok.
Currently I am using 1.7.10 Couldron and I wanted redirect dynmap to another port  (8123 can't be used in my case), here is my config file:
settings {
     B: UseForcedChunks = true
     B: webserver-port = 8920
}

As you can see, is different from the originals in a line that is not loaded.

Does changing the port has been removed? Maybe its syntax has changed?

**Comment by lymem** [comment]
You need to change the port specification in the configuration.txt file in the dynmap folder.

**Comment by mikeprimm** [comment]
Right - everything that matters goes in configuration.txt: the forge-specific config file is only for the settings you already find in that file.
