### ISSUE TITLE
Remove "IE9 mode" meta tag

### ISSUE THREAD

**Issue by RoboMWM** [webbukkit/dynmap#1735]
Hi,
Not sure why you have the IE 9 compatibility meta tag in the default html page - it appears to not be needed, as IE 10/11 render the page just fine; In fact, the meta tag purposely cripples them in the following ways:

- Makes tile loads "choppy" 
- Makes zooming "choppy"
- Unable to use any form of touch (when tag is removed, pinch-zoom works, but not panning - although you could "pan" with two fingers.)
- being unable to follow players.
- No sidebar animation

**Comment by mikeprimm** [comment]
Cool - just removed it
