### ISSUE TITLE
[request] Disable rendering particular chunks

### ISSUE THREAD

**Issue by the-vindicar** [webbukkit/dynmap#1738]
I set up a Thaumcraft-based automatic wood farm, and it seems to throw Dynmap into a fit because chunk updates faster than Dynmap can render it. Is there a way to stop rendering particular chunks? I'd rather not move the whole thing underground.

**Comment by mikeprimm** [comment]
Completely, no.  But, you might want to set the 'tileupdatedelay' to a larger number (see https://github.com/webbukkit/dynmap/blob/master/src/main/resources/configuration.txt#L231 ).  This controls the minimum time between when a tile has its first potential update and when dynmap will bother to try to update render it.  If you don't mind the delay, setting this to something large (3600 for once an hour) will prevent continuously updating chunks from being re-rendered more than once per hour or so.
