### ISSUE TITLE
[Request] Option to open link in new tab/window

### ISSUE THREAD

**Issue by colajunkie13** [webbukkit/dynmap#1739]
I use the Logo component.
I would like the link to open in a new tab,
which in HTML is achieved by adding target="_blank" (or a non-existent frame) as target of the <a> tag.
So an new option for the logo component (something like "newwindow: true/false" or "targetframe: _blank") would be just what i'm looking for.

**Comment by generrosity** [comment]
Quick answer would be to customize the HTML files directly.

Closing request as very old - please do reopen if feature is still required - the single dev is currently working on 1.13 and 1.14 upgrades.
