### ISSUE TITLE
[Bug] Changing minecraft name, dynmap is unable to pull skin. Results in steve skin on map.

### ISSUE THREAD

**Issue by mibby** [webbukkit/dynmap#1742]
Dynmap core 2.2-snapshot-2038
Dynmap plugin 2.2-snapshot 1098

Seems all users who have changed their minecraft name, their skin is stuck on the default steve skin on the map. Doesn't want to update.

**Comment by killyouslow** [comment]
ive experienced this too, seems to me that Dynmap is not UUID compatible, skins will not update no matter what settings i use in the basic overlay config. please update Dynmap to UUID compatiblity !!!

**Comment by roopekoo** [comment]
Dynmap should be updated to support UUIDs so players faces updates to real ones.

**Comment by mibby** [comment]
@roopekoo Well, it doesn't and I don't see any UUID commits on the repo either.

**Comment by Cpt-Beefheart** [comment]
I believe someone had previously mentioned that the skin repository for the new ones or for all was changing from Amazon to mojang's own place. Is that the issue?

Alternatively does the user above have config changed from the default to not fetch new skins?

**Comment by killyouslow** [comment]
where should i point dynmap to fetch skins? amazon or mojang? exact links would be helpful please

**Comment by theravensrequiem** [comment]
Any update on this?

**Comment by mikeprimm** [comment]
Check latest dev builds, and just-released 2.2-alpha-1
