### ISSUE TITLE
Dynmap not updating to changes to landscape made with world edit

### ISSUE THREAD

**Issue by killyouslow** [webbukkit/dynmap#1743]
When i use world edit to remove stuff from my worlds, the changes aren't made to my dynmap,

What am i doing wrong?

**Comment by colajunkie13** [comment]
iirc: WorldEdit does not fire the kind of events, dynmap is registered to by default (usually player interaction and WorldEdit does server commands, no player interaction).
So just force dynmap to render (for example /dynmap updaterender).

**Comment by tylerhoot** [comment]
best fix is to just tell it to do a full render once a while to catch all word edits changes or just walk in the area then the dynmap update renderer will see change and update it.

**Comment by killyouslow** [comment]
Hey ty guys for the helpfull input :D
