### ISSUE TITLE
dynmap not rendering properly.

### ISSUE THREAD

**Issue by Jylers** [webbukkit/dynmap#1744]
title says all and here is how it is rendering: [render image](http://i.imgur.com/NfNhTOa.png)

**Comment by Jylers** [comment]
also renders stone as coal ore

**Comment by UNST3RBLICH** [comment]
Having this same issue, which also renders items that are no longer on the map, overlaying them with items that are currently there.

**Comment by BoneGrey** [comment]
Same issue as both others. Though I didn't have this issue until after upgrading to Dynmap v2.1 from v2.0

**Comment by Jylers** [comment]
Have either of you tried upgrading to the latest Spigot/Bukkit? That is what fixed it for me.

**Comment by BoneGrey** [comment]
I fixed mine. I'm running an unofficial bukkit 1.8 server. I just missed
some textures in the process of putting together.
