### ISSUE TITLE
Map shows while rendering, but goes pitch black when rendering is complete

### ISSUE THREAD

**Issue by 404UNFca** [webbukkit/dynmap#1745]
Kind of odd. I've just installed everything properly (to my knowledge). Whilst rendering, the map and players show up properly (though the Nether and End seem to default load 30,000,000 255 30,000,000 as the starting co-ords. I had my worldspawn set to those co-ords originally, but changed them).

As well, now the site isn't even loading for me, and when it does, it loads halfway then gives me an error about some co-ords JS not being able to load.

198.245.49.206:8123

What do?

**Comment by mikeprimm** [comment]
Hit your map - looks OK - is problem resolved?

**Comment by 404UNFca** [comment]
Sorry for not closing this myself sooner, if that's even possible. I'm still learning the Github ropes.
