### ISSUE TITLE
Dynmap PlotMe not remembering plots correctly.

### ISSUE THREAD

**Issue by Konsider** [webbukkit/dynmap#1746]
Using Spigot 1.8.1, DynmapPlotMe and Dynmap (using MySql)...

PlotMe Dynmap data isn't being remembered after a server restart. The plots are not fully represented on the Dynmap and only start appearing when people are at them. Once the server restarts, everything is reset again and no PlotMe information is displayed on the map again. As time goes on the plots start appearing again, but on each server restart, things are forgotten again.

Sometimes there will be central square of like 10x10 plots that is remembered, but that only happens occasionally and never anything outwith that square.

**Comment by mikeprimm** [comment]
DynmapPlotMe isn't mine - nothing I can do to fix it.   In general, the items posted to dynmap by an integration plugin are not persisted by dynmap, but by the integration plugin OR the source plugin.

**Comment by Konsider** [comment]
Thanks for the reply Mike. It was just because you bundle DynmapPlotMe with Dynmap that I thought you might be the person to speak to. Thanks for your time though.

**Comment by mikeprimm** [comment]
Looks like the repo for that is https://github.com/ZachBora/Dynmap-PlotMe - not sure if he's doing issues there, or at http://dev.bukkit.org/bukkit-plugins/dynmapplotme/tickets/

**Comment by Konsider** [comment]
Thanks man :+1:
