### ISSUE TITLE
Dynmap Canary time looping

### ISSUE THREAD

**Issue by tylerhoot** [webbukkit/dynmap#1747]
on flat or any of the normal biome worlds non neither the time loops 3 seconds over and over again the map still shows progress but the clock is incorrect ver 2.2-snapshot-23-core verson2.2-snapshot-2038

**Comment by jbodhorn** [comment]
I'm having the same issue, clock goes back and forth between 7:00 and 7:01

**Comment by Psy-Virus** [comment]
Issue still relevant? If so, pls reopen or recreate the issue with updated Details.
