### ISSUE TITLE
Dynmap breaking after X amount of uptime

### ISSUE THREAD

**Issue by AlexisWiiu** [webbukkit/dynmap#1748]
So I've recently had issues after installing the latest build of Dynmap from spigotmc.org. I have not discovered the reason behind this issue before now(Dynmap), so this report comes rather late.

MC Version: 1.8

Spigot Version: Latest 1.8 Build compiled from BuildTools(January 25th).

What issue occurs?

The issue that occurs is that after X amount of uptime when someone tries to log into the Dynmap webpage it does not react to clicking on 'Login' or 'Register'. It also breaks Essentials command /ban, leaving an 'Error:Null' when attempting to ban someone. The same goes for Essentials command /mute. It also breaks EssentialsSpawn respawning players after death in a specific location that I do not see defined anywhere. All commands leave NullPointer exceptions in console. 

What temporarily fixes this issue?
A full server reboot fixes the issue for X amount of time until it reoccurs.

What permanently fixes this issue?
Renaming dynmap.jar to dynmap.jar.disabled

Dynmap has been set up on my Dedi by myself, following the points from Dynmaps plugin page on Spigot. I have NOT yet tried to reinstall Dynmap from the bottom and up, but all the files were fresh from the 1.8 Dynmap update.

Thoughts/Progress. As I have read through the Dynmap config it seems to be latching into Essentials for Banlist, Muted players and Spawnpoints for players by Bed. Essentials changes this to the /spawn location due to my settings. I'm not sure if I've configured it wrong so it does not have the right permissions to latch into Essentials, thus why it is breaking.

I ran Dynmap fine on my server during Spigot 1.7.5-1.7.9.

**Comment by mikeprimm** [comment]
Dynmap has no ties to Essentials, nor with anything associated with Essentials implementation of bans (it only looks at vanilla bans).  If you have the Dynmap-Essentials plugin, that will access some information (player homes and warps), but that's all.  If you don't have that plugin, dynmap has no interactions with Essentials.

**Comment by AlexisWiiu** [comment]
Do you have any ideas/solutions to what it could be doing then?

**Comment by Psy-Virus** [comment]
Is this issue still relevant? Then pls reopen or recreate it with updated Details.
