### ISSUE TITLE
Feature Request: Web UI Parameter

### ISSUE THREAD

**Issue by ryan1161** [webbukkit/dynmap#1749]
Hi I was wonder if you could implement some more Web UI Parameter options like to disable the compass and the chat. I would love to just have the spawn show and players faces with the time of day. I'm trying to create a widget for my website to basically look like a little map on the side but all I can use for now is noggui. Im on the latest dynamap forge for 1.7.10.

**Comment by mikeprimm** [comment]
https://github.com/webbukkit/dynmap/wiki/Web-UI-Parameters - hidechat will get rid of the chat.  Removing the compass without using nogui is missing, so I'll need to add that.

**Comment by mikeprimm** [comment]
OK - nocompass setting added to latest dev build

**Comment by ryan1161** [comment]
It look great but still need some buttons hidden like the location and check box plus the link button for the chat. You can see what I mean at my website ryandward.com scroll to the bottom the maps on the right.
