### ISSUE TITLE
Dynmap not loading correctly?

### ISSUE THREAD

**Issue by swimmerwoad** [webbukkit/dynmap#1753]
Well dynmap is not loading correctly, as you can see the black parts of it, and all the textures are wrong. I am using version 2.1

http://i.imgur.com/RyOaKVk.png <--- Picture

**Comment by mikeprimm** [comment]
Need details - what version of MC?   If you are using a downloaded version of Spigot 1.8, don't - build a clean, recent one using BuildTool, as the old 1.8 Spigots that folks have put on various sites are a) obsolete, b) buggy, c) possibly dangerous/untrustworthy for other reasons

**Comment by swimmerwoad** [comment]
I used BuildTools to get the spigot

**Comment by bmhm** [comment]
Hello swimmerwoad,

I used the new spigot jar tool and it worked really well. You might want to give it a try. Also,  don't forget to do a full render on startup. 

So please try this first and see if that works.
