### ISSUE TITLE
Dynmap crash in Spigot  #35 for MC 1.8.3

### ISSUE THREAD

**Issue by exnw** [webbukkit/dynmap#1754]
I've had a dynmap crash in the latest spigot 1.8.3 (#35) as well.
Tried both stable and development build.

The spigot version is rather new so I can imagine it is either a spigot or dynmap problem.

dynmap 2.1 (build 1091) http://pastebin.com/x4MYek1Y
dynmap 2.2 (build 1103) http://pastebin.com/irvaVM29

**Comment by meoso** [comment]
same here ; 2.2 on spigot 1.8.3

**Comment by mibby** [comment]
@mikeprimm 

Confirmed I'm also experiencing the crashing with the latest Spigot 1.8.3 compile and latest dynmap dev build.

Crash log.
http://paste.ubuntu.com/10611513/
Errors leading up to the crash.
http://paste.ubuntu.com/10611514/

Updated from Spigot 1.8.3 git-Spigot-ea179b3-6e0120a to Spigot 1.8.3 git-Spigot-c80bcce-22ee419 (latest as of 03/16 12:30 PM PST) . Dynmap now crashes the server. Removing dynmap, no more crashing.
Dynmap v2.2-SNAPSHOT-1103

**Comment by mikeprimm** [comment]
Build latest Spigot 1.8.3 - issue was a Spigot issue, which has since been corrected.

**Comment by exnw** [comment]
Thank you, though it seems I've now gotten a different crash.

http://pastebin.com/GET6eWhZ

**Comment by exnw** [comment]
thanks, this seemed to have resolved it :)

**Comment by meoso** [comment]
thank you @mikeprimm , resolved here also.

**Comment by mikeprimm** [comment]
Cool - good to hear!  Thanks for the confirmation, folks!
