### ISSUE TITLE
Server tiles to Webserver?

### ISSUE THREAD

**Issue by trulywitty** [webbukkit/dynmap#1755]
I looked at all the options (could of missed it) to try to find a way so it uploads the tiles to a webserver/vps instead of saving the tiles to the server itself?

If its already implemented how would I go about doing it?

**Comment by Remanent** [comment]
in configuration.txt, around line 297, should be the following..

# The path where the tile-files are placed.
tilespath: web/tiles

changes the tilespath to the path to your webserver (i think apache's default is in /var/web, so /var/web/tiles.

also, assuming that you arne't using the internal webserver, you'll need to change:

line 300:

# The path where the web-files are located.
webpath: web

to something like /var/www or whatever apache's default is.

finally, line 316 needs to be changed to true..

# Disables Webserver portion of Dynmap (Advanced users only)
disable-webserver: false (this to true)

more specific instructions on how to configure dynmod are availabe in the wiki, located:

https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server
https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-apache2-under-Debian
https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-Apache-httpd-under-Arch-Linu
https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-lighttpd-under-Arch-Linuxx
https://github.com/webbukkit/dynmap/wiki/Setting-up-with-Nginx-server-on-Centos

**Comment by trulywitty** [comment]
Wow thanks man. Just got it to work. Now I can store the 1 million png files on my webserver Dx

**Comment by Remanent** [comment]
No problem man.  Glad I was able to help.. I've done it before, but with Apache on Ubuntu.. And that was like two years ago. Have fun!
