### ISSUE TITLE
List of markers and ability to center map on markers

### ISSUE THREAD

**Issue by Arnuh** [webbukkit/dynmap#1756]
I have a world that's is really spread out and I feel a list of markers under its set that are clickable to center map on that marker would be very helpful to look around without having to click all the players and see if they are near my desired area.

Somewhere on the sidebar, maybe under players list would have a section for each set that displays all its markers.

**Comment by Psy-Virus** [comment]
Often asked for definitely a feature that's worth being implemented.

Listed.
