### ISSUE TITLE
Railcraft textures are not rendered

### ISSUE THREAD

**Issue by Terpo** [webbukkit/dynmap#1759]
Hello, 
After updating our modpack most of the railcraft blocks are not rendered anymore. I tried both versions of dynmap: Dynmap-2.1-forge-1.7.10.jar  && Dynmap-HEAD-forge-1.7.10.jar
Both render nothing.

Using the DynmapModScraper did help a bit, but most of the important building blocks are still invisible. I am not sure but could it be that the xcount / ycount for textures is broken?

texture:id=railcraft/brick.abyssal.0,filename=assets/railcraft/textures/blocks/brick.abyssal.png
texture:id=railcraft/brick.abyssal.1,filename=assets/railcraft/textures/blocks/brick.abyssal.png
texture:id=railcraft/brick.abyssal.2,filename=assets/railcraft/textures/blocks/brick.abyssal.png
texture:id=railcraft/brick.abyssal.3,filename=assets/railcraft/textures/blocks/brick.abyssal.png
texture:id=railcraft/brick.abyssal.4,filename=assets/railcraft/textures/blocks/brick.abyssal.png
texture:id=railcraft/brick.abyssal.5,filename=assets/railcraft/textures/blocks/brick.abyssal.png
brings the index 0 for all abyssal blocks

texture:id=railcraft/brick.abyssal,filename=assets/railcraft/textures/blocks/brick.abyssal.png,xcount=6
nothing / black is rendered

I've also tried other formats but nothing works :/

**Comment by Tayrtahn** [comment]
Here's a possible clue I found on the Special Texture File Types page:

> GRID - this is the default format, corresponding to an array of square textures <xcount> wide and <ycount> high. **Each texture needs to be an even power of 2 pixels across**. The index of the textures is ordered from the top left (index=0) moving to the right across the first row (ending with index=<xcount>-1), before advancing to the left edge of the next row (index=<xcount>), and so forth.

The width of the Railcraft block textures? 96 pixels - not a power of 2.

I'm going to experiment with the custom format and see if I can get something out of that.

**Comment by mskurnik** [comment]
I am in the same boat here.  I can get the first tile in the grid to load but not the other ones.  The only workaround I can think of is to use a script or photoshop to break the images into their sub textures.

**Comment by Psy-Virus** [comment]
Ist this issue still valid? Then please reopen or recreate the issue with updated details.
