### ISSUE TITLE
Mixed content when used behind SSL proxy

### ISSUE THREAD

**Issue by bmhm** [webbukkit/dynmap#1762]
Hi there,

thanks for the plugin. I put nginx with https:// (TLS1.x) in front of port 8123. The file blank.png is still loaded via http://. Can you please fix this by using protocol relative URIs? (instead of: http://host/ use //host/). Thanks!

**Comment by mikeprimm** [comment]
This is a function of the fact that Jetty (our internal web server - not part of Dynmap, per se) always maps redirects to be absolute (even though we provide them with a relative one), and that the proxy isn'g providing the X-Forwarded-Proto header to indicate the source protocol.  See

http://wiki.eclipse.org/Jetty/Howto/Configure_mod_proxy#Proxying_SSL_on_Apache_to_HTTP_on_Jetty

for the Apache answer: I believe the same action can be done via proxy_set_header setting in NGINX

**Comment by bmhm** [comment]
Hi, thanks for your answer. I somewhat cannot believe that jetty enforces a protocol. And no, the proxy_set_header has no effect (already using it). 


    server {
        listen         443 ssl spdy;
        server_name    map.mc.domain.de;
        keepalive_timeout       70;
    
        gzip on;
        expires 1d;
    
        ssl_certificate         /etc/nginx/ssl/map.mc.domain.de.chain.crt;
        ssl_certificate_key     /etc/nginx/ssl/map.mc.domain.de.key;
        ssl_trusted_certificate /etc/nginx/ssl/sub.class2.server.ca.pem;
        ssl_protocols           TLSv1 TLSv1.1 TLSv1.2;
        ssl_session_cache       builtin:1000                    shared:SSL:50m;
        ssl_session_timeout     5m;
        ssl_prefer_server_ciphers on;
    
        # source: http://www.kuketz-blog.de/nsa-abhoersichere-ssl-verschluesselung-fuer-apache-und-nginx/
        ssl_ciphers              "EECDH+AESGCM EDH+AESGCM EECDH -RC4 EDH -CAMELLIA -SEED !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !RC4";
    
        ssl_dhparam             /etc/nginx/ssl/dhparam.pem;
        add_header              Strict-Transport-Security       "max-age=31536000; includeSubdomains;";
    
        ssl_stapling on; # enable on release 1.3.7
        resolver 8.8.4.4;
    
        rewrite_log on;
        error_log /var/log/nginx/map.mc.error.log notice;
        access_log /var/log/nginx/map.mc.access.log;
    
        location / {
            proxy_pass       http://127.0.0.1:8123;
            proxy_set_header X-Forwarded-Proto  https;
            proxy_set_header Host      $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
     
    server {
        listen         80;
        server_name    map.mc.domain.de;
        rewrite        ^ https://map.mc.domain.de permanent;
    }



Still, Firefox and Chrome will show 

    Mixed Content: The page at 'https://map.mc.domain.de/' was loaded over HTTPS, but requested an insecure image 'http://map.mc.domain.de/images/blank.png'. This content should also be served over HTTPS.

So… looks as if blank.png is REQUESTED via http. Some javascript file, perhaps? The file js/hdmap.js contains a request to blank.png. Perhaps DynmapTileLayer.extend will only request via http? Haven't looked into it yet.

**Comment by bmhm** [comment]
Nailed it down to this: https://github.com/webbukkit/DynmapCore/blob/master/src/main/resources/extracted/web/standalone/SQLite_tiles.php#L75

If a tile is not found, this header is being generated. Instead of a relative URL  ("../images/blank.png") it might be better to use sth like this (untested):

    header("Location: "
        . "//" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] 
        . "../images/blank.png");

Same applies to MySQL backend and markers.

I got distracted by hdmap.js, which defines the option ```errorTileUrl: 'images/blank.png',``` which is not used in this case.

**Comment by bmhm** [comment]
While this didn't help either, I now switched to file based serving, i.e. disabling the internal web server.

I had to add

    location /tiles {                                                                                                                                                                                                 
        try_files $uri /images/blank.png;
    } 

and also create a symlink to my tiles directory (obiously), but it's not mentioned in the docs over here: https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server

HTH

**Comment by HenrySlawniak** [comment]
Facing the same issue on https://ardacraft.io/map/

`````
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name ardacraft.io;

  ssl_certificate {{SEKRET}};
  ssl_certificate_key {{SEKRET}};

  include /etc/nginx/conf.d/ssl-params;

  location /images/blank.png {
    access_log off;
    add_header Content-Type image/png;
    return 200 "";
  }

  location /map {
    return 302 https://$host$request_uri/;
  }

  location /map/ {
    access_log off;
    proxy_pass http://mc.ardacraft.me:8123/;
    proxy_set_header X-Forwarded-Proto  https;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_connect_timeout 10;
  }
}
````

**Comment by nethershaw** [comment]
Really? This issue has been open for a year and a half, and @mikeprimm's only comment is "we're using Jetty, and Jetty does it wrong."

Thanks. That's incredibly frakking helpful.

@mikeprimm do what @bmhm says or turn the project over to someone who can bloody maintain it.

**Comment by brantje** [comment]
+1 It's 2016, we have LE please give us an option to allow https.

**Comment by mikeprimm** [comment]
It's open source - if it's so important to you, fix it your fucking self.

**Comment by bmhm** [comment]
@mikeprimm  if it is not fixed, please leave this issue open until someone issued a pull request which actually fixed the problem. I am looking into it.

But closing an issue means either "resolved" or "not a bug". I think "won't fix for now" shouldn't be one of the reasons for closing an issue.

Btw: "fix it your f***** self" doesn't particularly encurage others to actually fix those issues. If you just wrote "Can someone please look into it, I don't have the time right now", I'd feel much better.

**Comment by mattwbb** [comment]
+1. Can't seem to get this working myself.

**Comment by wioxjk** [comment]
@bmhm 
I totally agree. Mikeprimm is not nice and does not seems to understand simple things when it comes to webbservers.
For example this "issue": https://github.com/webbukkit/dynmap/issues/2005
Was blamed on a misconfigured webserver even if I stated that it was running on Jetty - he did not even bother to read the information I provided.

**Comment by HenrySlawniak** [comment]
Can we not bicker? It is open source, you shouldn't be demanding people work on it for you. You are free to fork it, and continue on if you are unhappy with the way it is currently maintained.

**Comment by bmhm** [comment]
@HenrySlawniak yes, none of us did want to bicker. But instead of leaving the issue open while we prepare pull requests and give useful input, the issue gets closed with the words "do it your f***** self".

I believe a big project shouldn't be forked too early. It will only confuse users. Let's try to focus on fixing bugs instead.

@mikeprimm please be so kind as to accept the pull request, thank you.
