### ISSUE TITLE
(1.5.2 Hexxit Server) Resource for mod ExtrabiomesXL not found

### ISSUE THREAD

**Issue by Virenias** [webbukkit/dynmap#1768]
Hello,

I'm running Hexxit v1.0.10 on a Minecraft 1.5.2 server with which I'm using mcpc-plus-1.5.2-R1.1-forge738-B653 and Dynmap-2.0.0-forge-7.8.1. Now I'm having trouble with items from ExtrabiomesXL rendering on the map. There's an error in the console that says the resources for ExtrabiomesXL aren't being found.

I've pasted it below:

>10:32:51 [INFO]  Loading resource pack standard
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/autumnshrub.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/browngrassshort.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/browngrasstall.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/calla.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/cattail.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/crackedsand.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/deadgrassshort.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/deadgrasstall.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/deadgrassyellow.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/hydrangea.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/leafpile.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/leavesacaciafancy.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/leavesbrownautumnfancy.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/leavesfirfancy.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/leavesorangeautumnfancy.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/leavesredautumnfancy.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/leavesredwoodfancy.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/leavesyellowautumnfancy.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/logacaciaside.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/logacaciatop.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/logfirside.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/logfirtop.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/logcypressside.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/logcypresstop.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/logjapanesemapleside.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/logjapanesemapletop.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/orangeflowers.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/planksacacia.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/planksfir.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/planksredwood.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/plankscypress.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/planksjapanesemaple.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/planksrainboweucalyptus.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/planksautumn.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/planksbaldcypress.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/plankssakura.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/purpleflowers.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/quicksand.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/redrock.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/redrockcobble.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/redrockbrick.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/redrockslabside.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/redrockslabtop.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/root.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/saplingbrownautumn.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/saplingorangeautumn.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/saplingredautumn.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/saplingyellowautumn.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/saplingfir.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/saplingredwood.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/saplingacacia.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/saplingcypress.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/tinycactus.png for mod ExtrabiomesXL not found
10:32:52 [WARNING]  Resource mods/extrabiomesxl/textures/blocks/toadstools.png for mod ExtrabiomesXL not found

Here's a few screenshot examples of blocks and trees from ExtrabiomesXL not rendering:

>http://gyazo.com/bd0c60b487c735c9f9eb336bbfd5dc75
http://gyazo.com/df107103fbb6ab65199bef6f1f2244e9

So is there anyway I can fix this so that items from ExtrabiomesXL will show up on my Dynmap? Also, my apologies if older version of Minecraft aren't supported anymore. I was just hoping to find an answer here.

**Comment by mikeprimm** [comment]
1.5.2 is out of support - sorry
