### ISSUE TITLE
Ability To Disable Prefixes?

### ISSUE THREAD

**Issue by Mythcartoonist** [webbukkit/dynmap#1769]
Would there be anyway to disable showing the prefixes of Permission Groups on Dynmap? For example, I just want my name to be "Mythcartoonist" but it currently only shows up as "[Member]Mythcartoonist". It seemed to show up as just the name in previous versions but now as I'm setting up my new server I can't seem to make it the same. Thanks in advance for the help!

![capture](https://cloud.githubusercontent.com/assets/10608021/7268168/4c6d9dc2-e894-11e4-83c9-c8e38b828cfc.PNG)

**Comment by Psy-Virus** [comment]
Is this still a valid issue? Then please recreate or reopen the issue.
