### ISSUE TITLE
Gamemode changing

### ISSUE THREAD

**Issue by AgonCrafter** [webbukkit/dynmap#1772]
Hello,
i have a big problem with dynmap, i have tried all versions but there is always the same bug :/ 
Dynmap is a plugin for a Minecraft server thats almost impossible to imagine, but with this bug, I can't keep the plugin on my Server. 
The bug is that, when i change the world (do not care whether Portal / teleportation / Warp / Gamemode3 mouseweel / ....) the gamemode changes into survivalmode.
The problem is not that I must always enter /gm 1, the real problem is that an admin can't spy on a griefer, because the Gamemode 3 (spectator) is not longer worldcross with the dynmap.

My (relevant) Plugins: Multiverse\-Core\-Inventories\-Portals\-NetherPortals; CommandBook; Word Guard; Worldborder; World Edit

thank you in advance:)

**Comment by Cpt-Beefheart** [comment]
Hi, 
Dynmap does not control your gamemode, I believe what you want to achieve has to do with settings in your server.properties file and your multiverse config.  
For admin spying like you mentioned maybe try the vanish-nopacket plugin which works well with dynmap, and it won't matter what gamemode the staff member is in.  You can then also make it so your staff can log in without it being announced.  Also, spying on griefers seems so 2 years ago and takes up your valuable time so I suggest to try out plugins like GriefPrevention and Residence and make it so grief is not possible in the first place ;)  Finally, I am not 100% but I think /dynmap hide doesn't revert when changing worlds but I'm writing without double checking.  That command and /dynmap show are useful as well though. 
Regards,

**Comment by AgonCrafter** [comment]
Ok, thanks for recommending Vanish No Packet, I'll check it out on my Server in the next days.

I have already WorldGuard with automatic rent/buy Plugins, because you said that i should try GriefPrevention.
Actually i ment with "griefer" not this ones who destroy everything, but this ones who use Hack-Clients like X-Ray, Fly, ........ and i have already Plugins against this but there are always "loopholes" so i can't trust this Plugins 100%.
