### ISSUE TITLE
Dynmap MFR Not rendering (1.7.10)

### ISSUE THREAD

**Issue by exmex** [webbukkit/dynmap#1774]
![Tile](http://mc.madroxide.com/maps/tiles/world/t/4_-1/z_134_-6.png?1430232620399)![Tile](http://mc.madroxide.com/maps/tiles/world/t/4_-1/z_136_-6.png?1430234400157)
![Tile](http://mc.madroxide.com/maps/tiles/world/t/4_-1/z_134_-8.png?1430234721775)![Tile](http://mc.madroxide.com/maps/tiles/world/t/4_-1/z_136_-8.png?1430233385639)

Ingame Image:
![Ingame](http://i.imgur.com/PYTzHgo.jpg)

The "Tower" is out of MFR's Larged paved Stone Bricks. 
In the fenced area there are a Rancher and a Breeder. Everything isn't rendering.

Using DynMap as Mod Version 2.1

**Comment by AgonCrafter** [comment]
Hello exmex,
i have had a similar problem when i use WorldEdit.
That could be the issue, if you use WorldEdit too.

**Comment by exmex** [comment]
Using WorldEdit in general or using WorldEdit to create the construction? If the 2nd, then no. I did built it by hand.

**Comment by AgonCrafter** [comment]
If you have only installed it then it should not be a problem. Only the blocks you create with WorldEdit can be a problem.
Try "/dynmap render" this reders the chunk you are standing in.

**Comment by exmex** [comment]
Nope. Didn't worked...

**Comment by Zerzix** [comment]
I am seeing the same issue with Chisle2 blocks

**Comment by exmex** [comment]
Great! So it is a problem of Dynmap? Not mine :+1:

**Comment by cg49me** [comment]
There are certain blocks that simply don't have supported textures, and thus render "incorrectly", sometimes as transparent.  You can use DynmapModScraper to fix some of them, but it won't get them all.  You can also request texture support for certain mods (no guarantee, but doesn't hurt).

**Comment by Psy-Virus** [comment]
MC < 1.8.9 are not supported anymore. If you still have this issue with a supported version of Dynmap, please reopen or recreate this issue with updated details.
