### ISSUE TITLE
Strange TPS issue

### ISSUE THREAD

**Issue by Cmoor** [webbukkit/dynmap#1775]
Hello, I've been using Dynmaps for quite awhile and in desperate need of help. I tried going on the spigot forums about it but haven't got a straight answer yet. I don;t know why I didn't before but now I'm going right for the source. My TPS has been acting weird, it shoots up and down and I feel it is to do with Dynmaps because on the timings it shows a large amount of resources being used up by it. I have a screenshot of it. What can I do to help reduce lag on my server, especially when players are using it via webserver. I have tried disabling some components but honestly I'm confused on what some of them do so I keep them to default in case i mess something up. I did that once and it was a very bad mistake. Anyways see the pic and hopefully I can get an answer/solution. Thanks in advance.
![image](https://cloud.githubusercontent.com/assets/8010625/7403960/38afb0d8-eeaa-11e4-885b-0140b684dfad.png)

**Comment by Cmoor** [comment]
update:
I have reduced mobs/animals so that helped a bit but still doesn't explain the lag issue with dynmap =\

**Comment by mikeprimm** [comment]
Your configuration looks to have problems - should't have both InternalClientUpdateComponent AND JsonFileClientUpdateComponent at the same time.  Are the JSON files (the standalone directory) on a network drive, or something slow?
