### ISSUE TITLE
Map is full of BLACK ZONES!

### ISSUE THREAD

**Issue by Ares49** [webbukkit/dynmap#1776]
Hello, i have read some issues like mine, but I could't solve it yet.
This is how my servers shows the dynmap:
http://159.8.75.38:21286/

I have Bukkit version 1.6.4-R2.0, game version 1.8 + and Spigot 1.8 with the default configuration of Mcprohosting. I unistalled dynmap and i have rendered few times before asking help. 
Could you help me please?

**Comment by Cmoor** [comment]
i had the issue of black spots all over my webserver as well and what i did is something your not gonna like. but first, are you saving through flatfile or mysql?

**Comment by mikeprimm** [comment]
Be sure you are running at least Dynmap 2.2-alpha-1 (2.2-alpha-2 is better).  You will need to refresh render.
