### ISSUE TITLE
Ugly Borders

### ISSUE THREAD

**Issue by AgonCrafter** [webbukkit/dynmap#1777]
Hello,
i have problems with the borders on my dynmap ......... and i don't know why:/
I have rendered my maps with the /dynmap radiusrender [radius] command.
I also use WorldBorder on my Server.

My Map----} bit.ly/agon-build-dynmap

Plugin Version: v2.2-alpha-1
Server Version: Spigot 1.8

Thanks in advance :)

**Comment by mikeprimm** [comment]
Border looks fine - what am I looking for?

**Comment by AgonCrafter** [comment]
This is how borders looks on other Servers:
![image](https://cloud.githubusercontent.com/assets/12116119/7556206/ceb4e876-f767-11e4-9753-6a39f2b6b49f.jpg)
And so they looks on my Server:
![image](https://cloud.githubusercontent.com/assets/12116119/7556212/0a1c4008-f768-11e4-8fdb-3732cd1bf5fe.jpg)

**Comment by Psy-Virus** [comment]
This looks like you used the trim command and dynmap didn't automatically remove the map tiles outside of the border. An updaterender or the deletion of the map and a new fullrender in this area should fix this.
