### ISSUE TITLE
[INVALID TEMPLATE] error

### ISSUE THREAD

**Issue by zD12** [webbukkit/dynmap#1778]
Hi there,
I disabled seeing chat for all Dynmap users, to prevent this error- however, it's still being displayed.  When a user speaks in our IRC server, it displays as:
[INVALID TEMPLATE] [IRC] Hi?
Instead of:
[IRC] NAME: Hi?

We've connected our IRC and MC server via PurpleIRC.
We're currently running on: [dynmap-2.1](http://addons-origin.cursecdn.com/files/853/318/dynmap-2.1.jar)
Our config may be located here:
https://gist.githubusercontent.com/zD12/988985362e2bc3170379/raw/49a62a3993778c1f5afb05bc3cd0d21d6879603b/Dynmap-Config

I'd love for this error to be patched.  I've contacted PurpleIRC's developers already, said it was an issue with Dynmap.

**Comment by mikeprimm** [comment]
The [INVALID TEMPLATE] isn't coming from us - that string doesn't exist anywhere in our code.  Cannot say I'm familiar with PurpleIRC, but any integration with it is not part of Dynmap.
