### ISSUE TITLE
MySQL error Spamming console.

### ISSUE THREAD

**Issue by Phykick** [webbukkit/dynmap#1779]
Basically, this:

03.05 19:32:18 [Server] ERROR Tile exists error - User blue_user already has more than 'max_user_connections' active connections
03.05 19:32:16 [Server] ERROR Tile matches hash error - User blue_user already has more than 'max_user_connections' active connections
03.05 19:32:16 [Server] ERROR Tile write error - Duplicate entry '1-116--174-1' for key 'PRIMARY'
03.05 19:32:16 [Server] ERROR Tile exists error - User blue_user already has more than 'max_user_connections' active connections
03.05 19:32:15 [Server] ERROR Tile exists error - User blue_user already has more than 'max_user_connections' active connections
03.05 19:32:15 [Server] ERROR Tile matches hash error - User blue_user already has more than 'max_user_connections' active connections
03.05 19:32:14 [Server] ERROR Tile read error - User blue_user already has more than 'max_user_connections' active connections
03.05 19:32:14 [Server] ERROR Tile exists error - User blue_user already has more than 'max_user_connections' active connections
03.05 19:32:12 [Server] ERROR Tile matches hash error - User blue_user already has more than 'max_user_connections' active connections
03.05 19:32:11 [Server] ERROR Tile write error - Duplicate entry '1-116--180-1' for key 'PRIMARY'
03.05 19:32:11 [Server] ERROR Tile exists error - User blue_user already has more than 'max_user_connections' active connections
03.05 19:32:11 [Server] ERROR Tile exists error - User blue_user already has more than 'max_user_connections' active connections
03.05 19:32:10 [Server] ERROR Tile matches hash error - User blue_user already has more than 'max_user_connections' active connections

repeats over and over again.
Anyone know how to fix it?

What is 'max_user_connections' and how do I change 'em?

Using dynmap-2.2 alpha and error occurs on /fullrender command.
Thanks.

**Comment by Psy-Virus** [comment]
Google is your friend ;-)
[click me](http://dba.stackexchange.com/questions/47131/how-to-get-rid-of-maximum-user-connections-error)

**Comment by mikeprimm** [comment]
Good advice, @Psy-Virus  :)   We need some connections (5), so you need to be sure the account allows us to have at least that many
