### ISSUE TITLE
Markers Not Found by /dmarker

### ISSUE THREAD

**Issue by jwkicklighter** [webbukkit/dynmap#1780]
I'm able to add a marker just fine using the `dmarker add` command, and the markers will show up in the web browser map (and survive refreshing the web page/server reboots). However, listing the markers with `dmarker list` only ever shows the default spawn markers. And if I try to edit/delete the custom markers with `dmarker delete id:<my-id>` the console gives the error of `Error: marker not found - <my-id>`.

**Comment by cg49me** [comment]
Are the markers in question in a different set than default?

**Comment by jwkicklighter** [comment]
Yes, they are all in different sets (I created 4 separate sets to use).

**Comment by cg49me** [comment]
For markers in different sets than default, you have to include "set:<set i.d.>" in the command.

I.E.:  /dmarker list set:set2

**Comment by jwkicklighter** [comment]
Okay, that makes sense. I'm still unable to edit the markers though.

**Comment by Kingdingbat** [comment]
I also seem to have this problem. I can actually see the markers when I list them, and I can see that I have the correct id, but when I type "/dmarker [delete|update|etc] id:<marker-id> it says not found, even though I can see them both in the list and on the text file.

**Comment by Psy-Virus** [comment]
Is this still an issue with latest supported versions? Then please create a new issue with updated details.
