### ISSUE TITLE
Problem with the deftemplatesuffix

### ISSUE THREAD

**Issue by lncogmito** [webbukkit/dynmap#1781]
Each time i'm running my servers (1.7.10 and 1,8) or the dynmap plugin, the deftemplatesuffix become vlowers instead of hires like I want...

I don't understand what i need to do to use the plugin without this "bug"

**Comment by Psy-Virus** [comment]
Closing due to no enough info and outdated Dynmap versions.

If this is still an issue, please reopen and update the details.
