### ISSUE TITLE
Disabling cave map overall or certain groups?

### ISSUE THREAD

**Issue by gravestristen** [webbukkit/dynmap#1782]
Is it in any way possible to only let admins + use the cave map feature only, and if not how do I disable it overall?

**Comment by cg49me** [comment]
https://github.com/webbukkit/dynmap/wiki/Permissions

**Comment by gravestristen** [comment]
and this wiki deny it for them in the browser?

**Comment by Psy-Virus** [comment]
Nope, but the informations within ;-)

Install one of the mentioned permission plugins on your server => look trough the documentations from the plugin of your choice => create groups (for example admins, users and guests).
Configure that groups to fit your needs. (add the appropriate permissions for what they should be able to do and what not)
Add the users, who should see the cave-map to the admin group and the users who shouldn't to the users and/or the guest group.

You will have to play around a little bit, to find out how it works best in your case.

I hope you do not expect a copy and paste solution, there are many tutorials and samples on the web. You should get at least some on YouTube ;-)

**Comment by gravestristen** [comment]
we have group manager already

**Comment by Psy-Virus** [comment]
That must not be a problem. I personally don't know anything about that "Group Manager" plugin.
Maybe it's compatible to one of the others, so it will work with Dynmap.
