### ISSUE TITLE
I have heard that it is possible to change the textures for dynmap but I don't see anywhere that explains it.

### ISSUE THREAD

**Issue by gravestristen** [webbukkit/dynmap#1783]
its Purebedcraft 16x

**Comment by Cmoor** [comment]
found this for you, the last guy to comment seems to have the answer, i think this is what i did to get my texture pack to work.
http://www.minecraftforum.net/forums/support/server-support/server-administration/1924718-dynmap-configuration-custom-shaders-textures

**Comment by gravestristen** [comment]
thank you very much!
