### ISSUE TITLE
Suggestion:  Style Formatting for Web Chat

### ISSUE THREAD

**Issue by cg49me** [webbukkit/dynmap#1784]
I'm one of those weirdos that likes to change how the web chat appears in-game.  We currently have the option to do color formatting, but it would be nice to also have style formatting (bold, italic, underline, etc.).

It's currently pseudo-do-able using the section sign (§), but on new lines, the format is reset.

**Comment by Psy-Virus** [comment]
I'll list this. But it probably will be low priority.
