### ISSUE TITLE
Skins not actual

### ISSUE THREAD

**Issue by seema84** [webbukkit/dynmap#1791]
After Skins change (at Mojang) Player Skins noch changed in Dynmap.

Version: v2.2-alpha-2 and older

**Comment by Psy-Virus** [comment]
Hey @seema84,

did you check your config.txt against the original one dynmap provides?
The fetch link was changed some times ago ;)

**Comment by seema84** [comment]
You mean the configuration.txt File.
Yes - i change the link befor Dynmap changed.

This is my fetch link ->
"http://skins.minecraft.net/MinecraftSkins/%player%.png"

**Comment by Psy-Virus** [comment]
Is this still an issue with latest supported Dynmap versions? Then please recreate the issue with updated details.
