### ISSUE TITLE
MySQL change the config.js generation!!!

### ISSUE THREAD

**Issue by TheMasterofBlubb** [webbukkit/dynmap#1792]
I use Dynmap since a week and figured out to let it work with my NAS as SQL Server and Nitrado for Minecraft hosting. A database is created and gets updated. But when copying the web files it schows Configuration not found. There are no restriction for the sqluser dynmap on the db dynmap so it normally should load it. Any suggestions?

**Comment by TheMasterofBlubb** [comment]
I found the problem but i dont know how to solve it. The Problem is that the generated dynmap web files are still working on the tiles data format and not on the sql. The sql related are there but they never get used.

**Comment by TheMasterofBlubb** [comment]
Ok update. Everything is almost working. 
Fixed : MySQL_update.php is missing the value world at the $world = $_REQUEST['world'] -> manually set to 'world'->working
Still Issue: I need the Tiles to load from Database.

**Comment by TheMasterofBlubb** [comment]
Ok everything is fixed. I will make a small tutorial when i get home today.

**Comment by kwakmantim** [comment]
Can you post that small tutorial?

**Comment by TheMasterofBlubb** [comment]
When using MySQL setup your database. Check if the ServerPluging writes the data into the DB. Normally it works fine. How you setup the right Database you can see on a tutorial video on Youtube it depends on your System. Now the configs of the Webfiles.
config.js http://pastebin.com/byJvPtb0
check if your MySQL_config containsthenessecary login data(doublecheck is never bad).
now when loading the page it schould try to open the tiles over PHP explodes the path and converts its into DB paths. Thx for reading(took me all in all 96 h of work until i got it * absolute newbie to php*)

**Comment by TheMasterofBlubb** [comment]
To the developer: Pls change the creation function for the config.js when one is using MySQL. Shouldnt be a big deal and would help many people. I leave it open to see that the developers acknowledged and working on it.

Greetings from Germany.

**Comment by Psy-Virus** [comment]
If you fixed it on the code side, a PR would be nice. ;)

If this is still an issue with the latest versions of Dynmap, please reopen the issue or as I said, send in a PR :)

Thanks from Ger too :P
