### ISSUE TITLE
Extremely slow render on extremely fast computer

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#1794]
I have let Dynmap run on my server for about an hour now and I set it to render in only the "surface" map for now. But so far it has only generated about 0.5 square kilometers! I have a quad-core Intel Core i5, a superclocked GTX 750 Ti graphics card, and 8 GB of DDR3-1600 RAM. Does my computer have a bottleneck or is it Dynmap? With the WorldBorder plugin, beforehand, I locked the world size to 10 square kilometers and filled in all the empty chunks. Also, I have 6 GB of RAM allocated to my server. During this render, in Task Manager, the RAM usage has been hovering around 50%.

**Comment by Psy-Virus** [comment]
You probably need to change the render threads in the config file.
If this issue still exists with latest versions, please create a Post in the forum that will go online in the near future.
