### ISSUE TITLE
Dynmap keeps pausing any render I issue.

### ISSUE THREAD

**Issue by Janeke100** [webbukkit/dynmap#1799]
Hey,

Whenever I try to do a render for our world, console gives me this message: 
[13:55:05] [Dynmap Render Thread/INFO]: [dynmap] Paused Full render for world 'world' - world unloaded

I have no idea what to do. I tryed reinstalling Dynmap but that did nothing. all I did was in "worlds.txt" change the resolution to midres (for surface, flat and cave). 
I changed it back but that didn't change anything.

anyone have an idea?

**Comment by Cpt-Beefheart** [comment]
I would say the world you are trying to render is not named 'world'.

**Comment by Janeke100** [comment]
It is called 'world'. I'm, 100% sure

**Comment by Cpt-Beefheart** [comment]
Hehe, that doesn't sound so sure, but as long as the folder is called world.  
If console is saying the world isn't loaded, that isn't really a dynmap issue.  If you really 'only' edited the worlds.txt file, then configure the plugin.

**Comment by Janeke100** [comment]
I don't know how I did it but I fixed it eventually, thanks a bunch for wanting to help out man!
