### ISSUE TITLE
Cave will not go away. 

### ISSUE THREAD

**Issue by CLGREEN94** [webbukkit/dynmap#1801]
Good evening. 

I am having a issue with DynMap not removing the 'Cave' map on one of the worlds. I have no idea why or where it's telling DynMap to run the cave function. 

Here is a config of my worlds.txt 

http://pastebin.com/Tz70RxNY

As you can see I have removed all the code for the cave stuff like it says on the wiki. Am I missing something in my tired state? 

Thanks. 

- Callum

**Comment by Cpt-Beefheart** [comment]
Hi Callum,
That file looks ok, but with dynmap there are various configuration file that can do the same thing, so perhaps it is one of the others. For instance, your maps section is in worlds.txt, mine is within my custom-normal-hires template. (I don't show nether of the end on our map). Check out your own normal-hires template to see if you have a conflict. ((Worlds.txt saying not to show caves, but template saying to show them perhaps.))
Regards,

I ask if you deleted the cave folder also, but really I don't know what is telling it to display.  The configuration.txt and the normal-hires

**Comment by CLGREEN94** [comment]
Hi Cpr-Beefheart, 

Thanks for getting back to me so fast. 

I just made a change in the "normal-hires template" config and it worked. Thanks for all your help. 

- Callum
