### ISSUE TITLE
Conflict with BTP12 results in unresponsive server

### ISSUE THREAD

**Issue by EgbertW** [webbukkit/dynmap#1802]
I have a server running with Bevo's Tech Pack 12 Full with none of the optional mods installed. I have also installed Dynmap.

Recently, we've been experiencing some issues where the server becomes fully unresponsive: it appears to be online but when you try to connect you get a message saying: "Timed out". Stopping and restarting the server does not help, the problem persists.

I've been able to find a workaround: remove the BTP12/dynmap folder fully. This results in an empty map, after which I can run a dynmap fullrender again to render the world. It will continue to run for a while but at some point the problem returns.

The weird thing is: not a single error message in the server log. The console is responsive, no errors. However, also no mention of players trying to connect.

Another observation: the dynmap/ folder contains several .pending files when the problem arises. I don't know if this is related.

Is there any way I can provide more meaningful information to find the cause of this issue?

**Comment by Psy-Virus** [comment]
Is this still a relevant issue with latest and/or supported Dynmap versions? then please consider open a new issue with updated details under use of the provided Template.
