### ISSUE TITLE
Is there any way to enable connected textures with a custom shader for dynmap?

### ISSUE THREAD

**Issue by Janeke100** [webbukkit/dynmap#1803]
Hey,

For our project we use Dynmap to keep an overview of the land and our texturepack of choice is Conquest (or resourcepack, as it's called since god knows what update) Its a very nice RP with some awesome connected textures which we use a lot. the only problem is you can't see them connect on Dynmap and it makes everything look a little worse which is a shame.

Anyone have any idea how I can enable them?

thanks a bunch in advance!

Regards,
Jan

**Comment by Kixot14** [comment]
+
Will be great, is it possible to enable connected textures (like glass, wool, Cshieled stone bricks...) in map rendering!

**Comment by Psy-Virus** [comment]
CTM seems to be supported. At least there's an option in the configuration.txt

`# ctm-support: if true, Connected Texture Mod (CTM) in texture packs is enabled (default)
ctm-support: true`

If this is still an issue with latest supported versions of Dynmap, please consider posting on the new forum that will go online in the near future.
