### ISSUE TITLE
Dynmap Forge doesn't update render

### ISSUE THREAD

**Issue by MrsMeowys** [webbukkit/dynmap#1807]
Hello.
I am using Dynmap-2.1-forge-1.7.10.jar and the map doesn't update render when people are loading new chunks.

I have this when /dynmap pause:
[20:53:56 INFO]: Full/Radius renders are ACTIVE
[20:53:56 INFO]: Update renders are ACTIVE
[20:53:56 INFO]: Zoom out processing is ACTIVE

Also my configuration it's this: http://pastebin.com/p95FzHfg

Thank you.

**Comment by mikeprimm** [comment]
Your using rendertrigger values from Bukkit versus Forge (like the configuration.txt was copied from a Bukkit install).  Default rendertrigger settings for Forge are:

    render-triggers:
      - blockupdate
      #- blockupdate-with-id
      #- lightingupdate
      - chunkpopulate
      - chunkgenerate
      #- none

**Comment by MrsMeowys** [comment]
Thank you so much! That worked.
I am sorry but I need to ask you something else. Is there a way to show the worldborder circle in the map with forge?
Thank you.

**Comment by mikeprimm** [comment]
Are you on Forge, or on Cauldron?  The Bukkit version of WorldBorder has API support for the Dynmap API (which can be used on Cauldron via the DynmapCBBridge plugin).  If not, you can use the /dmarker command to add a circle matching the dimensions of your border manually - see https://github.com/webbukkit/dynmap/wiki/Using-markers for details

**Comment by MrsMeowys** [comment]
Thank you very much, solved!
