### ISSUE TITLE
Dynmap Scroll Not Working

### ISSUE THREAD

**Issue by merriec** [webbukkit/dynmap#1808]
Standard setup.  But the scroll was not working.  Upped both scrollback to 90 and visible lines to 15.  Saved file and restarted server, still not working.  The usual plugins are in, and using MCTowns, but do not see anything in that config file that should interfere with dynmap.  Any ideas?

**Comment by Psy-Virus** [comment]
Is this still an issue with latest Dynmap versions? Then please consider to open a new issue with updated details under use of the provided Template.
