### ISSUE TITLE
includehiddenplayers: true

### ISSUE THREAD

**Issue by B3stcraft** [webbukkit/dynmap#1809]
Hi, I have includehiddenplayers set to true cuz I ilke people to see online players but not their position.

is There a way to hide certain users (like admins or mods) even if includehiddenplayers is set tu true?

**Comment by B3stcraft** [comment]
any solution?

**Comment by Psy-Virus** [comment]
This should be postet in the forum that will go online in the near future. Keep and eye on the Sites where Dynmap is present to check for the link and stuff.
