### ISSUE TITLE
Have worlds to be default off unless specifically activated?

### ISSUE THREAD

**Issue by Tythus** [webbukkit/dynmap#1810]
I Want it so that rather than when I make a new world having to disable it it can be by default disabled

**Comment by wbattel4607** [comment]
+1

**Comment by Cpt-Beefheart** [comment]
+1 yes it would be nice.  It can be a hassle when testing around loading different maps.

**Comment by slayster** [comment]
+1 Yes would be a good option to have. It auto adding dimensions can be particularly annoying if you're using a mod such a Dimensional Doors.

**Comment by NoobInGame** [comment]
+1

**Comment by Canisaur** [comment]
Did any one of you try searching?  This was answered [back in 2011](http://dev.bukkit.org/bukkit-plugins/dynmap/tickets/16-option-to-disable-maps-by-default/).

Go to the dynmap/templates directory and set the templates you're using to enabled: false.  Then in dynmap/worlds.txt, add each dim you want shown like so:

   - name: world
     title: Overworld
     enabled: true

   - name: DIM-1
     title: Nether
     enabled: true

... and so on.  You can see what dims you have by typing '/dynmap reload' into the console and looking for lines like "[Dynmap] World 'DIM-7' disabled".  Just copy the text in the quotes and put it for the "name:"

**Comment by Cpt-Beefheart** [comment]
So change ticket to be one for adding said information to the setup and config documentation?
