### ISSUE TITLE
Support for Railcraft 9.6+

### ISSUE THREAD

**Issue by Tayrtahn** [webbukkit/dynmap#1811]
It looks like the Railcraft mod support file included with Dynmap is for Railcraft version 8.3.2.0... which is pretty old at this point. Something must have changed in the way Railcraft uses its textures, because everything renders as a black void in Dynmap.

The mod scraper doesn't fare much better. Following some tips from issue #1759, it's possible to get the cosmetic blocks to render, but only using one of their six textures each. There are still plenty of other graphic oddities in addition, like the curious rendering of upside-down abyssal stone stairs in the attached image.

![wrong_stairs](https://cloud.githubusercontent.com/assets/85356/8943914/676741e2-354b-11e5-93f8-477737cc4081.png)

It would be great to get official support for modern Railcraft back in Dynmap. It's a popular mod and it offers a number of cosmetic blocks that are quite useful (and look pretty horrible with the current config).

**Comment by WiduX** [comment]
+1 to this. On my server, someone is building a concrete workshop, and it just shows up a black frame with floating blocks inside.

**Comment by Tayrtahn** [comment]
I was able to get the different texture variations working for abyssal, quarried, etc. blocks by extracting the textures from the Railcraft jar, slicing them up, and making a new jar with the separated textures (to be used server-side only). It works, but it was a massive pain. It'd be really nice to get sliced textures working in Dynmap. I'm not dedicated enough to go through the process for all of Railcraft.

**Comment by Psy-Virus** [comment]
I think this should be handled by railcraft and not by Dynmap. If Dynmap would support all the mods that include non standard rendering and stuff there will never be an end of adding support and probably slow down Dynmap dev and optimizing.

I'll tag this as mod related feature request and list it. But the best way would be if railcraft supports Dynmap and not the other way around.
