### ISSUE TITLE
Support Non-Power-of-Two Textures

### ISSUE THREAD

**Issue by Tayrtahn** [webbukkit/dynmap#1812]
In exploring the issues with Railcraft rendering, I noticed that Dynmap only supports power-of-two textures when slicing them into an indexed grid. Recent versions of Railcraft annoyingly store certain textures in 96x16 pixel images, and this appears to be why Dynmap can't load them.

Would it be possible to add non-power-of-two support to the grid slicer?

**Comment by Psy-Virus** [comment]
This would probably end in a complete rewrite of the render engine.
Railcraft should use the dynmap API to implement support for it.
