### ISSUE TITLE
dynmap not loading with mysql

### ISSUE THREAD

**Issue by PhanaticD** [webbukkit/dynmap#1815]
I am using 2.2 for spigot 1.8.8 and getting the issue where the map is not loading

I did a jstack on my server and see a lot of this relating to dynmap: http://pastebin.com/p97VH0cV

however checking the mysql database for a while shows no active processes

**Comment by Psy-Virus** [comment]
On my side all works great. Double checked your Dynmap MySQL config and MySQL User config?
Does the MySQL user have write permissions for your Dynmap database?
Have you tried it with a default Dynmap config, only set up with your Database settings?
