### ISSUE TITLE
Cannot get config.js?_=2.1-SNAPSHOT-2032

### ISSUE THREAD

**Issue by ReFruity** [webbukkit/dynmap#1816]
Hi! I really like your map, but I'm stuck trying to set up nginx proxy.

I have node.js app running and I want the map to be available at `example.com/map`, so here is my nginx config:

```
proxy_cache_path  /var/www/cache levels=1:2 keys_zone=map:8m max_size=1g inactive=24h;

server {
    listen 80;

    server_name example.com;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /map {
        root /srv/minecraft-server/plugins/dynmap/web;
        proxy_pass http://127.0.0.1:8123/?worldname=world&mapname=surface;
        proxy_set_header            Host $host;
        proxy_cache                 map;
        proxy_cache_key "$host$uri";
        proxy_cache_valid  200 302  60m;
        proxy_cache_valid  404      10m;
        proxy_cache_use_stale       error timeout invalid_header updating http_500 http_503 http_504;
        proxy_connect_timeout 10;
    }
}
```

And my slightly modified [configuration.txt](http://pastebin.com/g2JN7NVR)

When I go to `example.com/map`, chrome cannot get any `js` or `css` files like `http://example.com/js/leaflet.js?_=2.1-SNAPSHOT-2032`. In `/srv/minecraft-server/plugins/dynmap/web/js` files are not suffixed with `?_=2.1-SNAPSHOT-2032`, but it still works when I go to `example.com:8123`. Maybe I'm stupid and don't understand some basic stuff. How do I work around this?

**Comment by ReFruity** [comment]
Ok, update. We considered moving map to subdomain. I'll provide you with a [link](http://map.aionics.ru), so you can see this error for yourself. 

New nginx config:

	server {
		listen 80;

		server_name map.aionics.ru;

		access_log /var/www/map.aionics.ru/logs/access.log;
		error_log /var/www/map.aionics.ru/logs/error.log;

		location / {
			try_files $uri $uri/ =404;
			alias /srv/minecraft-server/plugins/dynmap/web/;

			location ~ ^/(.*\.php)$ {
				alias /srv/minecraft-server/plugins/dynmap/web/$1;
				fastcgi_pass 127.0.0.1:8123;
				fastcgi_param SCRIPT_FILENAME $request_filename;
				include fastcgi_params;
			}
		}
	}

I got this config from a friend, who is running very old version of dynmap and a similar setup. It works for him. Any suggestions?

**Comment by ReFruity** [comment]
I still can't fix this problem. Can anyone explain how in the world is config.js generated, where it is located and how to tell nginx to fetch it correctly?

**Comment by luckydonald** [comment]
No Clue. But having the same problem.

**Comment by luckydonald** [comment]
I was able to put a config file I found in this [issue](https://github.com/webbukkit/dynmap/issues/1792#issuecomment-111806608) ([pastebin](http://pastebin.com/byJvPtb0)) into bukkit/plugins/dynmap/web/standalone.
After **restarting** the server, that file got replaced by a generated one.

**Comment by luckydonald** [comment]
Here is our apache config:
```apache 
<VirtualHost *:80>
    ServerName example.com
    DocumentRoot /var/www/example
    Alias /map/tiles /home/luckydonald/bukkit/plugins/dynmap/web/tiles/
    RewriteEngine on
    RewriteRule /map/up/(.*) http://localhost:8123/up/$1 [P]
    RewriteRule /map/standalone/(.*) http://localhost:8123/standalone/$1 [P]
</VirtualHost>

<Directory /home/luckydonald/bukkit/plugins/dynmap/web/tiles/>
    #Order allow,deny # this is old apache syntax!!
    #Allow from all   # this is old apache syntax!!
    Require all granted
</Directory>

<Proxy http://localhost:8123/*>
    #Order deny,allow # this is old apache syntax!!
    #Allow from all   # this is old apache syntax!!
    Require all granted
</Proxy>
```

**Comment by Psy-Virus** [comment]
Hey there, if this is still an issue or if you came to a solution for this and have a how to, please head over to https://forums.dynmap.us/ and open a thread there.
I'll close this because it doesn't seem to be a bug of Dynmap and there's no active communication since years.
