### ISSUE TITLE
Vanilla worldborder is not visible on map.

### ISSUE THREAD

**Issue by DarwinTrue** [webbukkit/dynmap#1818]
Dynmap v2.2
Tested spigot servers 1.8.8 and 1.8.3
showworldborder: true

**Comment by mrdarrengriffin** [comment]
It's not implemented yet I believe.

**Comment by Taybosquee** [comment]
I am having the same issue.

**Comment by leasoncre** [comment]
also don't see the boarder v2.2-alpha-1

**Comment by Psy-Virus** [comment]
Please try with the latest builds on http://www.dynmap.us/builds/dynmap

If you still have issues setting up Dynmap, please register at https://forums.dynmap.us

Thanks
