### ISSUE TITLE
Fullrender that only renders non-rendered tiles?

### ISSUE THREAD

**Issue by Tythus** [webbukkit/dynmap#1819]
Is this even possible?

**Comment by Psy-Virus** [comment]
Yepp it is.
Click http://lmgtfy.com/?q=dynmap+map+update and use the first result.
If that doesn't fit, use some of the other 107.000 results. I bet you'll find your answer within the top 10 ;-)
:bulb: HINT: It's also written within the result description :bulb: 

### And pls don't forget to close this issue. :-)

**Comment by Tythus** [comment]
you didn't read at all that only updates tiles that already exist what I want to do is for it to only render tiles that havn't been rendered ever for example I take dynmap off for a week due to reasons then re add it how do i only make it add new tiles and not redo the entire map

**Comment by Psy-Virus** [comment]
That's not correct. 
> /dynmap updaterender: attempts to render tiles needing updating, starting at current location, for all maps. Stops at edge of map and at tiles that don't need updating.

That means: Let's say you've black spots (Not rendered tiles) on your map, one of them is at coordinates x1:z1.
And all tiles around it are up to date.
You would type in your server console: dynmap updaterender world 1 1 map

The updaterender checks the tile and sees that it isn't up to date and renders it. Now the renderer jumps to the next one and checks if the tile is up to date and If it is up to date, it wont be rendered and so on and so on.
It also could take a long time, if your map is some dynmap versions old or you changed any light setting or something in that direction.

You also could do a radiusrender if you know how big your render area is.

**Comment by Tythus** [comment]
ohhhh well update render is not really the best term when i was reading it sounded more like a update tiles you already have kind of deal not ones you have never rendered

**Comment by Psy-Virus** [comment]
So your question is answered?

**Comment by masterX244** [comment]
and afaik you can trigger radiusrender on arbitrary base coordinates by specyfing them in the command (documented on the commands wiki page)
