### ISSUE TITLE
Possibility of slime chunk layer?

### ISSUE THREAD

**Issue by mrdarrengriffin** [webbukkit/dynmap#1824]
Would it be possible to detect which chunks are slime block chunks and put them as an extra layer. Thanks.

**Comment by Cpt-Beefheart** [comment]
Just use this http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262200-v3-7-amidst-strongholds-village-biome-etc-finder

**Comment by mrdarrengriffin** [comment]
I mean to be built in to DynMap so that players can see Slime Chunks. I don't want to release the seed. If not, I will just use their API and do it myself :P

**Comment by Cpt-Beefheart** [comment]
Hehe, you're a nicer host than I.  If my players want to find slime chunks they have to the old fashion way.

**Comment by Psy-Virus** [comment]
Still something you want to achieve? Head over to the new support forum at https://forums.dynmap.us
