### ISSUE TITLE
Feature Request: Ability to add server icon/logo that will redirect back to server website.

### ISSUE THREAD

**Issue by PsychoNavigator** [webbukkit/dynmap#1827]
As it says on the tin, what I am looking for is a way to be able to add a server icon/logo at the top left corner above the zoom buttons that will let players navigate back to the main website.

**Comment by mikeprimm** [comment]
Existing feature - see https://github.com/webbukkit/dynmap/wiki/Component-Configuration#logo-component

**Comment by PsychoNavigator** [comment]
Alright, thank you. Is it possible to use an image instead of text, however?
