### ISSUE TITLE
Is setting a custom texture pack done via a custom shader? Are 1.8 resource packs supported?

### ISSUE THREAD

**Issue by FrozenBeard** [webbukkit/dynmap#1829]
I have been trying to figure out how to set a custom resource/texture pack to render in Dynmap for years, Ive never been able to get it to work, I just found this page in the documentation that says to setup a custom shader:
https://github.com/webbukkit/dynmap/wiki/Defining-custom-shaders#defining-a-custom-texturepackhdshader-shader

Reading the "texturepack" requirements, it looks as if he latest Resource packs are not supported? Im hoping the documentation is out of date, as im searching through my Dokucraft/assets/minecraft/textures and I cant see a terrain.png etc.

I finally thought I managed to find out how to do it then ran into this!
So I have 2 questions, 
* Will the latest Resource Packs be supported? (I want to use Dokucraft http://dokucraft.co.uk/downloads/dokucraft-light/)
* After setting this up in custom-shaders.txt how do I set it as the default when I render out my maps? Or will this automatically be the default?

**Comment by FrozenBeard** [comment]
Tested this on my development server and figured it out.
For anyone that needs to set a custom texture pack or custom resource pack for Dynmap, you have to create a custom shader as posted above into custom-shaders.txt that links to your dokucraft.zip which is in the texturepacks folder, then you have to edit all your /templates/ and change the shader to the shader name you created.
Then re-render everything.

**Comment by NatoBoram** [comment]
Isn't there an easier way than to modify the 21 files in `plugins/dynmap/templates/`?
