### ISSUE TITLE
Dynmap Task: Unknown(Single) lag.

### ISSUE THREAD

**Issue by mibby** [webbukkit/dynmap#1831]
@mikeprimm Is there any way to further improve the mysterious `Task: Unknown(Single)` event lag?

dynmap v2.3-SNAPSHOT-1120

Timing profile.
http://timings.aikar.co/?url=12236025
Dynmap config.
http://paste.ubuntu.com/12236041/
Dynmap renderer template.
http://paste.ubuntu.com/12236043/

I can run a profiler if needed.

**Comment by Psy-Virus** [comment]
Please retry with the latest supported version of Dynmap https://forums.dynmap.us

If you still have issues, please head over to the new Support Forum over at https://forums.dynmap.us

Thanks
