### ISSUE TITLE
Feature request: display fences in flat view

### ISSUE THREAD

**Issue by Cpt-Beefheart** [webbukkit/dynmap#1832]
Just wondering if it is technically possible to do such a thing.

**Comment by rautamiekka** [comment]
I'm almost sure it is, otherwise a workaround can be used:
1) detect fences like normal
2) draw a, for example, 4-pixels cross unfilled box center of the block
3) if applicable, draw 2-pixels thick bars between adjacent fences

**Comment by mikeprimm** [comment]
They do display, when the scale is such that they are thick enough to contribute visibly to the view.  Default flat view is only 2 pixels per block, and fences are only 2-4 pixels wide out of 16 pixels (1/8 to 1/4 of the width of a block).  If you use a higher scale on flat view, you will see them.
