### ISSUE TITLE
Feature request: display plants in flat view (replaces #1813)

### ISSUE THREAD

**Issue by Cpt-Beefheart** [webbukkit/dynmap#1833]
Curious about this as well.  I put replaces #1813 because that one is specifically for tall grass, yet all grass,flowers,crops are not rendered in flat view. May as well make it a more concise and complete issue/request.

**Comment by Cpt-Beefheart** [comment]
Curious about this as well.  I put replaces #1813 because that one is specifically for tall grass, yet all grass,flowers,crops are not rendered in flat view. May as well make it a more concise and complete issue/request.

**Comment by mikeprimm** [comment]
Plants, flowers, and the rest are invisible from the top in the real game too - the model is an X pattern of 2 zero thickness surfaces.

**Comment by Cpt-Beefheart** [comment]
Yes indeed, this was more a curiosity about a work around as is done with in-game maps showing green for crops instead of the farmland underneath.  They are that one thing that really sticks out to the eye in difference from surface to flat maps.

Thanks!

**Comment by mikeprimm** [comment]
Let me give it a bit more thought - I might be able to come up with some sort of option that would give you something without being too much of a mess (it'd be an optional setting that switched the 'crossed' model to something that would have some thickness from above).  The trick is to make the model something that would still render appropriately in a isometric view, but give the top-down visibility you want.

**Comment by Psy-Virus** [comment]
Listed this as a feature.
