### ISSUE TITLE
Connected textures or something else, some blocks with one id and data

### ISSUE THREAD

**Issue by trancefer** [webbukkit/dynmap#1835]
Hi, sorry for my english. Can you help me find answer. I post a message on forum (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft?comment=2402)

Search in wiki documentation and forum, but dont understand how can i apply diffirent textures in one block (example: if one block stay in world is have one texture, but if this blocks count 3 and is stay near firts block get - one texture, second - another, and third - another). I think its use connected textures in game, but how its realise in dynmap. May be i need use layer or patch in model.txt.

Can you tell me its possible? If yes give me example please. thank you.

**Comment by trancefer** [comment]
Thinking must use CTMVertTextureRenderer in model.txt for this blocks. Can you add tutorial in wiki, or post example. Thanks

**Comment by Psy-Virus** [comment]
If his is still relevant, please head over to https://forums.dynmap.us and ask your question at our new support forum.
The Issue section on Dynmap should remain only for bugs, help by crashes and feature requests.

Thanks
