### ISSUE TITLE
[req] Forge Essentials compatability for Dynmap Forge

### ISSUE THREAD

**Issue by Ban5** [webbukkit/dynmap#1836]
I have been using dynmap for years under bukkit and group manager. for 1.8 we switched to forge, dynmap forge, and forge essentials.
I have found that only ops can use dynmap forge even if the non op has the permission nodes.

Would it be possible to allow forge essentials to control access to dynmap commands.

thanks love your work!

**Comment by Psy-Virus** [comment]
Please try the latest versions of Dynmap http://www.dynmap.us/builds/

If you still have support questions, please head over to https://forums.dynmap.us 
That's our new support forum.

Thanks
