### ISSUE TITLE
My map is missing random blocks, it's not usable at all

### ISSUE THREAD

**Issue by Ricket** [webbukkit/dynmap#1837]
![2015-09-16 03_56_06-minecraft dynamic map](https://cloud.githubusercontent.com/assets/196978/9899301/ef4c74ea-5c26-11e5-94b3-d5a025d0b2ec.png)

How do I diagnose?

I'm running Dynmap-2.2-forge-1.7.10 on a server based on FTB: Horizons Daybreaker.

**Comment by Ban5** [comment]
I had a similar problem on Dynmap-2.2-forge-1.8. try /dynmap fullrender that cleared it up for me

**Comment by Ricket** [comment]
Thanks. This cleared it up for me as well.

Possible reproduction steps:

I installed the 1.8.0 version of the mod (whoops!) and started the server, saw the mod didn't load and realized my error. Stopped server, deleted 1.8.0 version, installed version Dynmap-2.2-forge-1.7.10. Now I started the server, then after it was started I stopped it, and I edited the configuration.txt line with the port number (nothing else) -- but I accidentally edited the port to be the same as the minecraft server port. Started the server, later noticed my desired port wasn't listening and found my mistake; stopped the server and fixed it, started server, then opened it in the browser.

My thinking is perhaps the port number conflict caused map generation to begin but get interrupted (AddressInUseException probably?). Maybe that's a root cause.

**Comment by heil-stalin** [comment]
close it if updating to newest version and doing fullrender fixed it.

**Comment by Ricket** [comment]
Was the issue properly fixed in the latest version? "fullrender" is a workaround but shouldn't be necessary, IMO.

**Comment by kurisubrooks** [comment]
This issue has been present in all versions of Dynmap. It does this because of Minecraft's inconsistent chunk loading. 

Basically, when you first start the world it loads chunks, whilst Dynmap loads in parallel to that. Because the chunks load out of order, Dynmap loads the ones that are currently available, leaving blank spots in the map for ungenerated/not-loaded chunks. 

`/dynmap fullrender` is the only workaround for this, and I don't see how the devs would be able to fix this issue.

**Comment by heil-stalin** [comment]
I've ran fullrender many times, and it still doesn't fix massive sections of map missing. Kind of a waste of resources on a 15k x 15k map.

**Comment by rocky1138** [comment]
Was this ever fixed? Despite fullrendering several times, I still have black spots in my map. Strangely, only at the most zoomed out level. zooming in one the black spots shows tiles.

https://minecraft.xandorus.com

**Comment by heil-stalin** [comment]
Probably not. That sounds just like what happened to me nearly a year ago, but I had to zoom in about 3 times iirc.

**Comment by Psy-Virus** [comment]
Please try the latest version of Dynmap for you MC Server http://www.dynmap.us/builds/

If you still need support, please head over to https://forums.dynmap.us

Thanks
