### ISSUE TITLE
Duplicate removeEntities() in chunk unload

### ISSUE THREAD

**Issue by aikar** [webbukkit/dynmap#1838]
Been chasing down major issues with Entities randomly duplicating, and looks like Dynmap is the culprit.

I haven't found source of duplication aspect yet, but one aspect I have found wrong that may be the trigger is that dynmap is attempting to remove entities from the chunk twice:

public void unloadChunkNoSave(World w, Chunk c, int cx, int cz) {
        this.removeEntitiesFromChunk(c);
        w.unloadChunk(cx, cz, false, false);
    }

w.unloadChunk() is already calling removeEntities().

This method has no double call check, and therefor will insert the entity into the remove queue twice... this is causing really weird behavior and who knows what kind of impact.

[00:17:25 INFO]: [dynmap] version 2.2-SNAPSHOT-1106 is enabled - core version 2.2-SNAPSHOT-2044

**Comment by aikar** [comment]
https://gist.github.com/aikar/421b1017b04f49f140f1

**Comment by aikar** [comment]
I think found the source of my dupe issue. It's not dynmaps fault for that issue (though this issue is still something that should be resolved) but dynmap calling .loadChunk with generate=false hits a bug in CraftBukkit where a chunk that's also triggered to be loaded async at the same time causes the chunk to be loaded twice.

I've patched CB and will be PR'ing that, but that .removeentities in dynmap should be removed.

**Comment by Black-Hole** [comment]
This also lowers console spam in recent Spigot versions like:
[14:06:02 WARN]: Tried to add entity Pig with pending removal and duplicate UUID 88b6603c-ee26-5a69-bb18-9ae474816e75
