### ISSUE TITLE
Request: Real map grid overlay

### ISSUE THREAD

**Issue by FrozenBeard** [webbukkit/dynmap#1843]
There would be many great benefits of having an optional overlay available to players and staff based on a real map grid, I mocked this up really quickly as an example.
![Dynmap Map Grid Overlay](http://i.imgur.com/fbnanpx.jpg)

**Comment by Psy-Virus** [comment]
This is definitely something that would help talking about areas and stuff.
It's easier to say/write, I'm at D12 instead of 4985x1094.

Listed

**Comment by FrozenBeard** [comment]
Thanks for digging up my old suggestions! This is like the 10th one you have dug up! Would still like this to happen.
