### ISSUE TITLE
dynmap chat box

### ISSUE THREAD

**Issue by sashakwpb** [webbukkit/dynmap#1844]
im new to this

defaults are 

  messagettl: 5
    # Optional: set number of lines in scrollable message history: if set, messagettl is not used to age out messages
    #scrollback: 100

so if the default messagettl is set to 5  i think that means the text will show for 5 seconds

i also assume this overrides that scrollback 100

----------

what do i put after messagettl, so that scrollback 100 is the override?

how many lines can i show when scroll back is 100?

**Comment by Tayrtahn** [comment]
You'll need to uncomment the scrollback setting to make it do anything. Remove the "#" at the start of the line.

**Comment by sashakwpb** [comment]
tyvm :)

that worked for me.
