### ISSUE TITLE
Tiles wont render.

### ISSUE THREAD

**Issue by mrdeadlocked** [webbukkit/dynmap#1845]
Dynmap will not render tiles with the following mod installed

http://www.curse.com/mc-mods/minecraft/235107-notenoughids

The mod allows for the ITEM ID cap to be increased. The Logs show nothing when it comes to error about tiles, and zero crashes. Player movment on map works, health indicators, but on /tiles/world/ the ct, flat and t folders do not load and zero images inside.

https://gist.github.com/mrdeadlocked/b70e9a035d73a62d95db

https://gist.github.com/mrdeadlocked/9df3896bbd2fffa1db4e

**Comment by Psy-Virus** [comment]
This should be fixed in the latest versions of Dynmap. http://www.dynmap.us/builds/

If you still have issues, please create a new issue with updated details under the use of the provided issue template.
