### ISSUE TITLE
Can't open map in broswer.

### ISSUE THREAD

**Issue by PixelTimeOfficial** [webbukkit/dynmap#1846]
Can't open map in broswer, however I can keep rendering in the server. but localhost:8123 and myip:8123 does not work. My server is hosted in amazon datacenter and I have a unique IP. I opened many ports, for instances MySQL, and there were 20 servers hosted. I used spigot Bungeecords. Not working, please help

**Comment by mikeprimm** [comment]
Have you opened port 8123 on the firewall for the server (both external and internal - iptables or whatever you might have on the server box itself that may restrict visibility of nonstandard ports)?

**Comment by Feierr** [comment]
I got it to work somehow, how do i change the title of the broswer? The default is Minecraft dynamic map. I changed the webpage-title, but however it does not work? Maybe a bug?

**Comment by mikeprimm** [comment]
Uncomment the 'webpage-title' setting in configuration.txt, and customize the value:

     #webpage-title: "My Awesome Server Map"
