### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by epicbastion** [webbukkit/dynmap#1847]
looking for more granular permissions for the web view, is it possible to do the following?

Dynmap currently has 2 permissions for webmap views.  World / map and seeall players.  My server is a questing server and we would like to add some permissions to the webmap viewing as part of our quests.

dvp=dynmap view permission
1. add per world map layer permissions.  each marker layer or addon layer would have a permission.  
   perms= dvp.[layername] and dvp.[layername].[worldid]
2. add per world map self location view.  each player would have a permission to see themselves on the map.  perms= dvp.viewself and dvp.viewself.[worldid]
3. add per world map others location view.  each player would have a permission to see others on the map.  perms= dvp.viewothers and dvp.viewothers.[worldid]
4. add permission modifier for map world view.  where now the perm is dynmap.map.[world-id].[map-id] modified perm = dvp.map and dvp.map.[worldid]

all of these would use the login required condition of dynmap.

I use vault and pex with the world qualifier for my groups.   these perms would be attached to groups so when parsing, each mapview would look for; dvp.perm first and dvp.[perm].[worldid] second, if found it would return true and allow viewing of the perm granted.

pex parses perms as player, player-world, group, group-world.  vault passes the grant to the plugin.

example 1:  perm is granted to player-world or group-world:
group1=dvp.map
group2=dvp.viewself
player is granted;
group1 in w1 and w3
group2 in w2 and w3
result would be player seeing:
1. the map for w1
2. their playerface on w2
3. the map and their playerface on w3

this allows the use of the same named group for multiple worlds with out requiring more than one group per perm.

example 2:  perm dvp.[layername] is granted to player or group, not world specific, this would grant the player to see [layername] on all maps, 

group=dvp.worldborder all group members would see the world borders on all views but nothing else.

second perm level would be dvp.[perm].[worldid], again if true at any level allow viewing.  in the same manner as above this allows using either player or group with out world perm specificity.

group=dvp.viewself.w1 - the player would see their playerface on w1 but nothing else.

if no perm is found then webmap would return;
1. dvp.map or .[worldid] - a blank page for the world map
2. dvp.[layername] or .[worldid] - no markers or addon layers 
3. dvp.viewself or .[worldid] - no self location
4. dvp.viewothers or .[worldid] - no others location

**Comment by Psy-Virus** [comment]
I'll list this feature as a few more perms to manage the dynmap web GUI would be cool.
