### ISSUE TITLE
Request: Show minecraft Region files

### ISSUE THREAD

**Issue by FrozenBeard** [webbukkit/dynmap#1848]
At present there is no easy way to look at a map and display the minecraft region files as an overlay.

What's a region? groups of 32×32 chunks are stored in a region file, this is what's stored in the world folder as r.x.z.mcr files, where x and z are the region's coordinates.
http://minecraft.gamepedia.com/Region_file_format

Why would we need to be able to visually see region areas? 
1. Any vanilla/Long term survival map needs giant areas regenerated that have been destroyed over time and have nobody living in them, you can quickly do this be deleting a region file, but how do we know what region file to delete? we need to have them shown on a map.
2. we need a way to edit giant areas of a map offline, and then we can upload the changed region files to the live world without having to upload the entire world, this means you can cordon off an area of the map you will be doing major work in, edit that offline in MCedit and then upload the region files to the live server when its done. Why do we need to visualize this? so we can choose areas that don't overlap where people are living or have live development that would be overwritten, we can codon off areas of the map using dynmap to see where the region is set.

**Comment by Cpt-Beefheart** [comment]
You could always use what Dinnerbone made to figure that out for you easily ;)
https://dinnerbone.com/minecraft/tools/coordinates/

**Comment by FrozenBeard** [comment]
@Cpt-Beefheart This has been around for a very long time, this does not visualize on a map where the regions are, we need to be able to SEE them.

**Comment by Cpt-Beefheart** [comment]
Ah, you meant to say thanks for trying to help.

**Comment by FrozenBeard** [comment]
Bump

**Comment by Psy-Virus** [comment]
![grafik](https://user-images.githubusercontent.com/6222200/49743375-e3188c00-fc9a-11e8-89c8-7c9b27a60fcd.png)

I'm quite sure this was implemented a while before 2015 as I always had this shown...

**Comment by FrozenBeard** [comment]
@Psy-Virus mine does not show this? https://map.piratemc.com/

**Comment by Psy-Virus** [comment]
@FrozenBeard, search for `show-mcr`in the `configuration.txt`.

Sry for the late response. :( :D

**Comment by TomLewis** [comment]
@Psy-Virus Awesome thank you, super simple! Shame we cant visualise it over the map so people can see quickly, and just click.
