### ISSUE TITLE
Player name strikethrough &m error 

### ISSUE THREAD

**Issue by DoMiNiOuS** [webbukkit/dynmap#1849]
I have a prefix on PermissionsEx:
&c&m---&7{- &6&oAdmin&7 -}&c&m---&e

this works great but when I view the web dynmap the strikethrough &m never stops & goes through everything. Pex starts striking at &m & stops at &7 then starts again at the next &m.
I set use-name-colors: true so all the colors are fine, just the strikethrough issue.
Also tried the reset &r but no joy.
Am I missing something?
Tested & same applies to underline &n, italic &o and bold &l.
I love dynmap & have everything running great except this.
Many thanks

**Comment by Psy-Virus** [comment]
Is this still an issue in the latest dynmap versions? http://www.dynmap.us/builds/

If so, please open a new feature request by using the provided feature request template.
