### ISSUE TITLE
Only render 'flat' map.

### ISSUE THREAD

**Issue by leasoncre** [webbukkit/dynmap#1850]
i want to set dynmap to only render the 'flat' map and not the surface or cave maps. but dynmap seems to want to keep re-rendering the surface and cave maps.

I have tried deleting them from the template file (normal-hires)
And done: /dmap mapdelete world:surface/cave 
As well as: /dynmap purgemap world surface/cave
Dynmap still wants to render the undesired maps. i have checked the configs/wikis/etc, but i haven't found a way to specifically disable those map types (ie: surfacemap:disable)
Thanks.

**Comment by Cpt-Beefheart** [comment]
You need to edit the template for the world type you are wishing to accomplish this for, normal, nether, or end.  Do note that this will affect all worlds of that type.  For example, I only show flat for nether, so my custom-nether.txt file is like the following, either delete the lines for surface and cave, or just comment them out.
Ex:
templates:
  # Nether world template (HDMap hires)
  nether-hires:
    # Number of extra zoom-out levels for world (each level is twice as big as the previous one)
    extrazoomout: 2
    center:
      x: 0
      y: 64
      z: 0
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: servercustom
        lighting: nethershadows
        # Map background color (day or night)
        background: "#300806"
        mapzoomin: 1

**Comment by leasoncre** [comment]
--solved-- 
CLOSED
