### ISSUE TITLE
Dynmap not showing my world

### ISSUE THREAD

**Issue by JoshAGSE** [webbukkit/dynmap#1852]
Whenever I type my server ip in the search bar with the port 8123, it displays someone else's server. the ip is s10.hosthorde.net:8123, I changed it to my port in the config file and in the search bar but it still doesn't work. It says it can't load that webpage. Any ideas why this is happening?

**Comment by EvilOlaf** [comment]
You probably do not have a dedicated ip address for your Minecraft server.  In most times this can be identified by not being able to use the default port 25565.

As the dynmap is running at default 8123 this port is occupied by someone else server. 
Ask your host how to fix this.
