### ISSUE TITLE
Could not retrieve configuration: error

### ISSUE THREAD

**Issue by 2108U9** [webbukkit/dynmap#1853]
so. I have dynmap woking well. at Http://map.scoutcraft.eu (tell me if links isnt allowed, and ill remove it) But i try to add it as an <object> to embed it on another place i get a popup window saying "Could not retrieve configuration: error" I tried with diffrent browsers aswell....

**Comment by Psy-Virus** [comment]
Link dead, old issue, no information about what versions and stuff, closing.

If you still need support, please head over to https://forums.dynmap.us
