### ISSUE TITLE
Cannot access webserver at localIP:8123 only localhost:8123

### ISSUE THREAD

**Issue by lmaopat3** [webbukkit/dynmap#1854]
I have checked my firewall and have allowed the access of TCP 8123, i have also portfowarded my TCP 8123, i could use localhost:8123 no problems but when i try to use localip:8123 it told me "No Data Received, ERR_EMPTY_RESPONSE" what should i do? D:

**Comment by EvilOlaf** [comment]
Check your settings. Maybe dynmap is bound to 127.0.0.1

**Comment by lmaopat3** [comment]
Yes it is bound to 127.0.0.1, on the web but how do i change it? i could not find the setting

**Comment by KovuTheHusky** [comment]
The setting is in `configuration.txt` and is called `webserver-bindaddress`. Make sure it's commented out with a hash or make sure it's set to `0.0.0.0` and NOT `127.0.0.1`.
