### ISSUE TITLE
sidebaropened:true does not allow to unpin

### ISSUE THREAD

**Issue by EvilOlaf** [webbukkit/dynmap#1855]
```
# Set sidebaropened: 'true' to pin menu sidebar opened permanently, 'pinned' to default the sidebar to pinned, but allow it to unpin
sidebaropened: true
```

Actually when this is set to `true` the button for unpinning as it is there when this is disabled is not shown anymore. Therefore the sidebar can not be unpinned.

`core=2.2-2058, plugin=2.2-1118`

**Comment by KovuTheHusky** [comment]
I believe you're looking for `sidebaropened: pinned`. It's pinned by default and can be unpinned by the user.

**Comment by EvilOlaf** [comment]
Uhm... Maybe :P I'll give it a try. Thanks.
