### ISSUE TITLE
Players not seeing themselves when using the Login feature.

### ISSUE THREAD

**Issue by nsjmurray** [webbukkit/dynmap#1856]
I have searched everywhere high and low for a solution to this problem and I just can not find one.
Basically i have successfully set up the Web register feature however players do not see themselves when they log in, Here is my config 

http://pastebin.com/0TxviMzS

I have followed the instructions on the wiki to a tee but simply can not get it working.

**Comment by Psy-Virus** [comment]
Is this still a problem with the latest versions?
http://www.dynmap.us/builds/dynmap/

If so, please head over to the new Dynmap community support forum at https://forums.dynmap.us/
