### ISSUE TITLE
Linux screen command issue

### ISSUE THREAD

**Issue by LyingCak3** [webbukkit/dynmap#1857]
I am not sure if this is an issue with dynmp, centos or screen, but if you start a minecraft server with a screen and then detach from it, dynmap stops updating.

Specs:
Centos 7 server
Nginx web server, not using built in web server
Java: openjdk 1.8.0_65
Minecraft 1.7.10
Forge 1566
Screen version: 4.01.00devel

Screen has had some bugs with centos 7 so it may just be an issue with those two, but am bringing light to it here just in case it is not.

**Comment by FagSoft** [comment]
I'm using Ubuntu 14.04, external web server config (Apache), and screen. No problems with the rendering if detached, as I've noticed.

Forge executable: forge-1.7.10-10.13.4.1448-1.7.10-universal.jar  (Resonant Rise modpack).
Dynmap: 2.1
Screen version 4.01.00devel (GNU) 2-May-06
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by SunnyTeater** [comment]
Hey,
If you still have the problem try "tmux"  it is the same like "screen" 
All what u need to know about tmux is here:  https://www.ocf.berkeley.edu/~ckuehl/tmux/

**Comment by rautamiekka** [comment]
§tmux§ can't be used as directly as §screen§; §tmux nano /foo/bar§ doesn't work, §screen nano /foo/bar§ does. Or at least didn't.

**Comment by Psy-Virus** [comment]
If there are still issues, please try the latest version or head over to the new Dynmap community support forum at https://forums.dynmap.us/

Mod DL: http://www.dynmap.us/builds/dynmap/
