### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by herobrine2999** [webbukkit/dynmap#1859]
Ive setup dynmap with everything sucessful no errors i set up the web server with no errors
when i try viewing it in the browser every time it says that i get timed out
ERR_CONNECTION_TIMED_OUT

**Comment by FagSoft** [comment]
This sounds like you're either trying to connect to the wrong address or port, or that the web server is listening to the wrong port. I recommend using `netstat -apn` to find out which port it's listening on, and checking the syslog/web server log.
