### ISSUE TITLE
World Border

### ISSUE THREAD

**Issue by TSenter** [webbukkit/dynmap#1860]
Does dynmap support Minecraft's vanilla worldborder? As in, does it display on the map, or is there an option to do so?

**Comment by KovuTheHusky** [comment]
There should be a setting in `configuration.txt` called `showworldborder`.

**Comment by eightbitx** [comment]
The `configuration.txt` setting `showworldborder` doesn't seem to do anything. Can not see the vanilla worldborder on the map.
