### ISSUE TITLE
no configuration.txt with forge version

### ISSUE THREAD

**Issue by bentterp** [webbukkit/dynmap#1861]
Sorry, but I can't figure this one out myself.

I have installed Dynmap-2.2-alpha-2-forge-1.8.0.jar on a server running forge-1.8-11.14.4.1577 and need to change the webserver-port because I have more than one MC server running on the machine.

But, the only configuration file that gets created is ./config/Dynmap.cfg containing the B:UseForcedChunks=true setting.

The other MC server on the machine is running Spigot with the Dynmap plugin rather than the mod so that behaves aas in the documentation, ie there is ./plugins/dynmap/configuration.txt with "webserver-port: 8123".

But where is that setting supposed to go in the forge version when there is no such file created?

regards,
Bent

(crossposted to minecraftforum also)

**Comment by Ban5** [comment]
dynmap forge config file is in /dynmap

**Comment by KovuTheHusky** [comment]
The default location for the configuration file for DynmapForge is `./dynmap/configuration.txt`.

**Comment by bentterp** [comment]
Thanks, but it doesn't work for me. I created the dynmap folder manually under config and as no configuration.txt got created when restarting the server, then I copied from my spigot server and changed the port number and restarted again, but it still isn't recongnized:
[root@tux2 terpmod]# ls -la config/dynmap/
total 24
drwxr-xr-x.  2 minecraft minecraft    30 30 dec 07.14 .
drwxr-xr-x. 11 minecraft minecraft  4096 30 dec 07.11 ..
-rw-r--r--.  1 minecraft minecraft 18158 30 dec 07.14 configuration.txt
[root@tux2 terpmod]# grep -e 8123 -e 8124 config/dynmap/*
webserver-port: 8124
[root@tux2 terpmod]# grep -e 8123 -e 8124 logs/fml-server-latest.log 
[07:15:07] [Server thread/FATAL] [Dynmap/Dynmap]: [Dynmap] Failed to start WebServer on address 0.0.0.0:8123 : Address already in use
[root@tux2 terpmod]# 

Any suggestions?
regards,
  Bent

**Comment by KovuTheHusky** [comment]
It's not in the config folder, that's the point I was trying to make. It's in the root folder - the one with the Forge JAR and everything. I've tested it with the same build of Forge and Dynmap and it worked fine. Maybe it's a permissions problem?

Also, there's a newer version of Dynmap available on Curse. Version 2.2 is no longer in alpha. http://minecraft.curseforge.com/projects/dynmapforge/files

**Comment by bentterp** [comment]
Solved :-) Had to move my other server instance away from port 8123 first, and then the dynmap folder got created, but under the root, not under config or mods subfolders.

May I suggest that when the plugin/mod deploys, then it could create it's configfiles etc before starting the webserver etc, so that in situations like this, then a configfile would get created and the config could be changed....

regards,
  Bent

**Comment by bentterp** [comment]
Closing
