### ISSUE TITLE
Apache2 mod_proxy loads a wrong configuration file

### ISSUE THREAD

**Issue by codebucketdev** [webbukkit/dynmap#1863]
Hello Guys,

Recently I installed Dynmap and created a virtual host in my apache2 configuration using mod_proxy:

``````
ProxyPreserveHost On
ProxyRequests Off

# Servers to proxy the connection, or;
# List of application servers:
# Usage:
# ProxyPass / http://[IP Addr.]:[port]/
# ProxyPassReverse / http://[IP Addr.]:[port]/
# Example: 
ProxyPass / http://localhost:8123/
ProxyPassReverse / http://localhost:8123/```
``````

But when I am trying to open the website, I get a blank black screen instead of the map shown!
So I opened the Developer tools in Firefox to check, if every file is loading correctly without errors and noticed a difference between the connection via apache2 and directly to the integrated webserver.

Here a screenshot of the resources that are being loaded when I am connecting directly to the integrated webserver of Dynmap:
![Before](http://rly.li/a03m/3ig047)

And here a screenshot of the resources that are being loaded when I am connecting to the apache2 server with the mod_proxy:
![After](http://rly.li/704l/2ie0r4)

So the difference is that the integrated webserver is returning a wrong configruation file to my apache2 server, which results in a black screen!

But why is this happening?

**Comment by silelmot** [comment]
i got it working:

i created a symlink for the original "/plugins/dynmap/web/tiles" in the folder on the websever.
than i deleted the Alias-Command and the <Directory>-Part for the "tiles" in vhost
working!

**Comment by jonathanselea** [comment]
I am also getting a blank page when I am trying to ReverseProxy through another webserver.
My vhost config looks like this:

`<IfModule mod_ssl.c>
<VirtualHost *:443>


        ServerAdmin [CONSORED]
        DocumentRoot /var/www
      

        ProxyRequests off
        ProxyPass "/map" "http://192.168.2.31:8123"
        ProxyPass "/mcadmin" "http://192.168.2.31:8080"
        ProxyPassReverse "/map" "http://192.168.2.31:8123"
        ProxyPassReverse "/mcmadin" "http://192.168.2.31:8080"

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        <Directory /srv/1000/owncloud>
                Options FollowSymLinks
                AllowOverride All
                Require all granted
        </Directory>

      
SSLCertificateFile /etc/letsencrypt/live/[ADDRESS]/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/[ADDRESS]/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
ServerName [ADDRESS]
ServerAlias [ALIAS]
SSLCertificateChainFile /etc/letsencrypt/live/home.selea.se/chain.pem
</VirtualHost>

</IfModule>`

For your notice, it seems like CSS and pictures is not going tru the ReverseProxy.
I guess that dynmap have something hard-coded somewhere.

**Comment by Psy-Virus** [comment]
`ProxyPassReverse "/mcmadin" "http://192.168.2.31:8080"`
There's a typo.

Closing this because it's not directly Dynmap related. If you still think that this needs attention, please head over to the new Dynmap community Forum at https://forums.dynmap.us .
