### ISSUE TITLE
Skins dont work

### ISSUE THREAD

**Issue by Kixot14** [webbukkit/dynmap#1865]
If players change their skins with SkinsRestorer plugin (https://www.spigotmc.org/resources/skinsrestorer.2124/), this skin will not be visible on the map.
Only default skins, by name (which set on minecraft.net site) are displayed.

I set fetchskins and refreshskins to true, but it's not help...

**Comment by Kixot14** [comment]
Also i tried to delete 'faces' directory, and run map again. But skin still displayed by the licensed player names.

**Comment by cw1204772** [comment]
It seems that the "Dynmap" plugin obtains the user skin form skin.minecraft.net directly according to player name recorded in Bukkit. The "Skinsrestorer" plugin stores the whole skin data in "plugin/Skinsrestorer/cache.json". I don't know how to modify Dynmap to use the skin cache stored by Skinsrestorer. 
However, I find that in "plugin/Skinsrestorer/config.json", Skinsrestorer provides "GET_PROFILE_URL" and "GET_SKIN_PROFILE_URL" to get the player data within Skinsrestorer. (This may suggest Skinsrestorer have a backend server that store all the data of players around the world). 
Maybe someone can help us with integrating these 2 plugins?

**Comment by Kixot14** [comment]
So... ??
Up!

**Comment by Psy-Virus** [comment]
configuration.txt

```
# Customize URL used for fetching player skins (%player% is macro for name)
skin-url: "http://skins.minecraft.net/MinecraftSkins/%player%.png"
```
