### ISSUE TITLE
Feed The Beast Infinity 1.7.10 Missing Blocks

### ISSUE THREAD

**Issue by darksaboteur** [webbukkit/dynmap#1866]
Hi,
I am running a FTB 1.7.10 server with dynmaps Dynmap-2.3-alpha-1-forge-1.7.10.jar (I have also tried earlier versions, Dynmap-2.2-forge-1.7.10.jar and Dynmap-2.1-forge-1.7.10.jar).

The render is missing some blocks from some mods and I am not sure how to fix it.

The relevant portion of the server log is at http://pastebin.com/sExW7sT4

Is it a configuration setting I am missing or are the mods unsupported?

Thanks,
Nick

**Comment by darksaboteur** [comment]
![missing blocks](https://cloud.githubusercontent.com/assets/10037552/12050432/8e62ca5a-af49-11e5-8d7d-bd160cc85c55.png)

**Comment by rob5251** [comment]
You can try using ModScraper to fix a majority of missing blocks, but it doesn't get everything.
You can download it from the DynMap main post (It's about half way down the main post)
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft
