### ISSUE TITLE
'followZoom'  and  'followMap'  don't work! (and one more issue...)

### ISSUE THREAD

**Issue by Kixot14** [webbukkit/dynmap#1867]
Don't know what else to add here...

server core: CraftBukkit version git-Spigot-2f787bd-ea28011 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

DynMap version: 2.2 (release)

**Comment by Kixot14** [comment]
And looks like 'shadowStrength' parameter don't work to!
I tried to change this in 'lightings.txt' and on 'custom-lightings.txt', but this don't give any effect...
All shadows under blocks is very dark... http://f-picture.net/fp/87cec266453c4f0c9997f3056b5c98e8

**Comment by Kixot14** [comment]
P.S. Little suggestion:

Can you add altitude effect to triggers, like 'blockPlayced' and 'blockBreak' ??
For example: If i set AltitudeRenderEffect to 50 - thats mean tiles don't be rendered if player placed or break blocks at Y-50 or lover...

**Comment by Psy-Virus** [comment]
If this still happens with the latest versions of Dynmap http://www.dynmap.us/builds/dynmap/
Please head over to the new support Forum at https://forums.dynmap.us
