### ISSUE TITLE
No confirmation of successful custom icon import

### ISSUE THREAD

**Issue by Kingdingbat** [webbukkit/dynmap#1868]
When importing a custom icon using the "/dmarker addicon" command,  I do not receive any kind of response when it is successful. If I do something wrong, do receive the appropriate error message, but when the import is successful, I do not receive any confirmation message. I only know that it works when I try the same import again and it says that the icon already exists.

Using Craftbukkit 1.8.8
Dynmap 2.2-1118

**Comment by Psy-Virus** [comment]
So if there's an error, you get a message and if there's no error, you don't get an error message? Sounds fair.
If this still happens with the latest versions of Dynmap an you think this needs attention, please head over to https://forums.dynmap.us to discuss that or open a new feature request here on github by using the provided form.

thanks
