### ISSUE TITLE
Issues with rendering moded blocks.

### ISSUE THREAD

**Issue by ThatGaskin** [webbukkit/dynmap#1869]
I'm trying to get the dynmap to show moded blocks. Tried using DynmapModScraper (versions   DynmapModScraper-HEAD-forge-10.13.0.jar and DynmapModScraper-2.1-alpha-1-forge-1.7.10.jar ) 

Not sure if it should happen but when i put the configuration files into dynmap/renderdata/modsupport they disappear after I restart the server. 

Link to my dynmap:
http://94.23.38.47:8123/?worldname=world&mapname=surface&zoom=8&x=-139&y=64&z=-21

**Comment by rob-bb** [comment]
Hi,

You need to create a new directory called custom, place it at dynmap/renderdata/custom/  and put the DynmapModScraper files in there.
