### ISSUE TITLE
Blocks not working

### ISSUE THREAD

**Issue by macDaddypro** [webbukkit/dynmap#1872]
will this ever be fixed?
[Dynmap Render Thread/INFO] [Dynmap]: [Dynmap] Loading resource pack standard
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/brickbasalt.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/brickmarble.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/cobblebasalt.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/oreperidot.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/oreruby.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/oresapphire.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/stonebasalt.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/stonemarble.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/storageperidot.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/storageruby.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/ore/storagesapphire.png for mod ProjRed|Exploration not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/0.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/1.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/10.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/11.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/12.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/13.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/14.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/15.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/2.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/3.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/4.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/5.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/6.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/7.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/8.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/lights/lampoff/9.png for mod ProjRed|Illumination not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/architect_front.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/architect_sides.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/architect_top.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/autoWorkbench_side.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/autoWorkbench_top.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/blockFillerSides.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/blockFillerTopOn.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/blockFrame.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/blockMarker.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/blockPathMarker.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/blockPlainPipe.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/builder_front.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/builder_side.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/builder_top.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/engineWoodBottom.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/engineWoodSide.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/engineWoodTop.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/engineStoneBottom.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/engineStoneSide.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/engineStoneTop.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/engineIronBottom.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/engineIronSide.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/engineIronTop.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/filteredBuffer_all.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/floodgate_bottom.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/floodgate_side.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/floodgate_top.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/fuel_flow.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/fuel_still.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/hopperBottom.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/library_side.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/library_topbottom.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/miningwell_back.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/miningwell_front.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/miningwell_side.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/miningwell_top.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/oil_flow.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/oil_still.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeFluidsCobblestone.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeFluidsEmerald_standard.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeFluidsGold.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeFluidsIron_standard.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeFluidsSandstone.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeFluidsStone.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeFluidsVoid.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeFluidsWood_standard.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsCobblestone.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsDaizuli_black.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsDiamond_item.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsEmerald_standard.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsEmzuli_standard.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsGold.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsIron_standard.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsLapis_black.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsObsidian.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsQuartz.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsSandstone.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsStone.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsVoid.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeItemsWood_standard.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipePowerCobblestone.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipePowerDiamond.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipePowerGold.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipePowerIronM128.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipePowerQuartz.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipePowerStone.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipePowerWood_standard.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeStripes.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pipeStructureCobblestone.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pump_bottom.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pump_side.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/pump_top.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/quarry_front.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/quarry_side.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/quarry_top.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/refineryBack.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/tank_bottom_side.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/tank_top.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/buildcraft/textures/blocks/trunk_green.png for mod BuildCraft|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/compat/liqcondredmetal.png for mod ProjRed|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/compat/liqcondredmetal_flow.png for mod ProjRed|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/compat/liqredstone.png for mod ProjRed|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/projectred/textures/blocks/compat/liqredstone_flow.png for mod ProjRed|Core not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/biomesoplenty/textures/blocks/barley.png for mod BiomesOPlenty not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.Infested.1.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.Infested.2.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.Infested.3.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.Infested.4.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.Infested.5.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.Weed.1.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.Weed.2.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.Weed.3.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.Weed.4.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.Weed.5.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.stick.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/ic2/textures/blocks/crop/blockCrop.stick.upgraded.png for mod IC2 not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/apiaristchest.0.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/apiaristchest.1.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/apiaristchest.2.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/apiaristchest.3.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/apiaristchest.4.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/arbchest.1.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/arbchest.2.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/arbchest.3.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/arbchest.4.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/lepichest.1.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/lepichest.2.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/lepichest.3.png for mod Forestry not found
[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/forestry/textures/blocks/lepichest.4.png for mod Forestry not found

**Comment by rob5251** [comment]
I found why this happens; inside the .jar file is a resource folder with some mod compatibility already packed. The problem is that some of these definitions are referencing improper file paths now so it wont properly load in the textures.

If you try to produce your own updated texture definitions you have to delete the ones inside the .jar so the ones you define in the generated config area take over.

I managed to get ProjRed working after using DynmapModScaper and my method above.

**Comment by macDaddypro** [comment]
Thanks Rob. yeah I had messed around with DynmapModScraper and it worked. I still get the errors for blocks missing but the blocks show. I also just put the DynmapModScraper files right into the jar file and it worked. Still got the not found erros but blocks rendered.

Some blocks for mods like MPS tinker table made a strange block.

running forge server 1.7.10.10.13.4.1614

It would be really cool if Dynmap figure out mod blocks.

Dynmap modscraper does a good job and like I said I was able to get buildcraft blocks to render. pipes looks strange.

Anyway. thanks again for the reply. Hope one day dynmap can figure out mod blocks. or at least for the popular mods like the new Buildcraft etc

**Comment by rob5251** [comment]
No problem and yeah I'd like to see Carpenter Block support at some point too. I'm sure some of the items may be able to be done if you messed around with the model configs, but I'm not sure how to do any of that really.

**Comment by atnaguzin** [comment]
That's my renderdata for:
1. IndustrialCraft2 2.2.811-experimental
http://mc.lngserv.ru/map_cl/renderdata/IC2-texture.txt
2. ProjectRed 1.7.10 4.7.0pre12.95 (only base and lighting)
http://mc.lngserv.ru/map_cl/renderdata/ProjRed_Core-texture.txt
http://mc.lngserv.ru/map_cl/renderdata/ProjRed_Illumination-texture.txt
