### ISSUE TITLE
Enable 1 zoom level and delete tiles of all others...

### ISSUE THREAD

**Issue by bloggy** [webbukkit/dynmap#1873]
Hi there,
I wonder how I could only have 1 zoom level available for my dynmap and delete the tiles of all "inactive" zoom levels which I already have rendered?

**Comment by Psy-Virus** [comment]
If you want to remove all zoom tiles, simply search for tiles with a `z` in the file name. the more `z`'s the file name has, the higher the zoom out level.
The same applies to the hash files.
