### ISSUE TITLE
dynmap Factions dont work

### ISSUE THREAD

**Issue by Educationals** [webbukkit/dynmap#1874]
hi I use faction version of dr shock, namely Factions UUID I particularly have a problem with dynmap. He told me that he does not know where the problem lies. There is config.

http://imgur.com/RuBYpC8
This is my dynmap web: http://82.208.17.11:30719/

I can´t see a particular color and SafeZone WarZone and Home marker flags are factions
I have this version dynmap: plugin=2.2-1118

thanks for help!

**Comment by Educationals** [comment]
-_-

**Comment by Psy-Virus** [comment]
Still an issue with the latest Dynmap versions?
http://www.dynmap.us/builds/dynmap/

Then please head over to the community forum ( https://forums.dynmap.us ) to determine if there's an config issue or similar.
