### ISSUE TITLE
Dynmap spongeforge issue

### ISSUE THREAD

**Issue by Likton** [webbukkit/dynmap#1875]
I get an issue with the dynmap mod. Indeed, when I try to enter the dynmap command, sponge says that an other plugin maybe use the same alias. In fact, it's when I use the /dynmap reload command. 
This issue prevent dynmap to accept any new configuration what I could do. It makes me angry a lot! :confused: 

A sponge developper tried to help me. You can see his answer after:

"OK so I pulled Dynmap into my development environment (source code: https://github.com/webbukkit/DynmapForge/tree/1.8.01)
(@mikeprimm fix your build.gradle! I had to add http://repo.mikeprimm.com/ manually)

It loads fine when launching (except for this message):

[Dynmap] ***\* DYNMAP CANNOT READ CHUNKS (UNSUPPORTED CHUNK LOADER) ****
Typing dynmap at the console works, dynmap reload doesn't, here's the exception stacktrace: http://pastebin.com/WTcDyiwc1

It seems that dynmap is re-registering commands again when reloading which shouldn't be allowed because the old command still exists. (forge/vanilla doesn't seem to care and just overwrites the old command). It's possible using SpongeAPI to unregister commands but in forge/vanilla that is not possible.
This is a dynmap issue and should be reported to them."

So, I report this to you. If you can help or solve this, it should be wonderfull! :)

**Comment by simon816** [comment]
@Likton I should point out this crash is with [DynmapForge](https://github.com/webbukkit/DynmapForge) and not the bukkit plugin.

The original forum thread can be found here: https://forums.spongepowered.org/t/dynmap-issue/10775

**Comment by Likton** [comment]
Yes I know Modulocraft is me ^^. Yes I know this is with DynmapForge, but where can I highlight this ?   elsewhere ?

**Comment by mikeprimm** [comment]
DynmapForge build should not pull from repo - it is the 3rd build in a series, if you want to work it yourself: build DynmapCoreAPI, then DynmapCore - this will give your local repo the code you need for DynmapForge.

I'll see about handling compatibility with whatever is wrappering the chunk loader with Sponge - we coremod it there, so it'll probably take re-implementing those hooks particular to the Sponge-specific wrapper class to make it work.

/dynmap reload has never worked on Forge - probably never will.

**Comment by simon816** [comment]
It's completely possible for you to reload your plugin, it's just you need to make sure that you only reload what _actually_ needs reloading (e.g. config) re-registering commands is a pointless thing to reload (unless I'm missing something here)

**Comment by mikeprimm** [comment]
Not when parts of your configuration impact things like coremodding and hooks that cannot be unregistered when they are registered.  Point is immaterial - I'm not bothering to support it.

**Comment by mikeprimm** [comment]
Initial port to Forge 1.8.9 is now available - http://dynmap.us/builds/DynmapForge/Dynmap-2.3-alpha-1-forge-1.8.9.jar
