### ISSUE TITLE
Player head shown as black

### ISSUE THREAD

**Issue by TroyMLP** [webbukkit/dynmap#1876]
https://i.gyazo.com/989ff1bd400fe538de1623130b57c2c1.png

That is a link to my playerhead on my Dynmap, this happened with I changed my minecraft name.. is there a way to correct this? I have tried deleting the web tiles under 8x8 16x16 32x32 and body hoping that it would correct the issue, not so much....

please advise.

**Comment by Psy-Virus** [comment]
Still an issue with the latest version of dynmap? http://www.dynmap.us/builds/dynmap/
Then please head over to the new community forum. https://forums.dynmap.us/
