### ISSUE TITLE
Med-res and higher is blurry on certain zoom levels (2D)

### ISSUE THREAD

**Issue by WizardCM** [webbukkit/dynmap#1878]
![Example](http://i.imgur.com/JCjzIjw.png)

The above tile was taken at a zoom level of 4 at a scale of 10. You'll notice the glowstone blends slightly with the surrounding grass. A scale of 9 was even worse. Is there anything I can do configuration-wise or will this require a code-fix?

Extra details: This is using the vanilla resource pack (16x). Low res worked fine, except that it's designed not to render fences (which I need). Medium scale (8) resulted in fences only rendering horizontally.

Other Zoom levels:

| 2 | 3 | 5 | 6 |
| --- | --- | --- | --- |
| ![Example](http://i.imgur.com/RR593Pv.png) | ![Example](http://i.imgur.com/LKWwm1X.png) | ![Example](http://i.imgur.com/atQdrnz.png) | ![Example](http://i.imgur.com/RJuqThE.png) |

(anything closer than a zoom level of 5 works fine)

**Comment by Psy-Virus** [comment]
The blurriness probably comes from the fact that those pictures are getting down scaled and compressed, so the plug-in is re calculating how it will look. it is like if you look at a flash light that's near a car with lights on. If you're far away enough, they will blend over. (probably a bad explanation but yeah...)

Anyways, this doesn't seem to be a bug but a support request. If you still have this "problem" and want to discuss this further, please head over to the new community forum at https://forums.dynmap.us and provide as much details as u can.

Thanks
