### ISSUE TITLE
Dynmap Web Issue

### ISSUE THREAD

**Issue by M3M079** [webbukkit/dynmap#1879]
My friend installed Dynmap on her server and has me doing the config for her, when she installed Dynmap and got the I.P. the map does not render properly or the config is not set right. Here is a screenshot of how the map looks after rendering:
![screen shot 2016-02-02 at 7 40 22 pm](https://cloud.githubusercontent.com/assets/17037441/12771349/e3bdb4cc-c9e5-11e5-9a81-21e70aa1d571.png)

**Comment by Psy-Virus** [comment]
You should try the latest versions ( http://www.dynmap.us/builds/dynmap/ ) and recheck the config if this issue is still persisting.
Also as this is probably not a bug but a support question, please head over to the new community forum ( https://forums.dynmap.us ) to get support.
