### ISSUE TITLE
Web Errors 

### ISSUE THREAD

**Issue by SunnyTeater** [webbukkit/dynmap#1880]
Hey,  

I want to let dynmap run under the webserver nginx, but i get the following error in the browser.

http://www.directupload.net/file/d/4255/8zmrkuw5_png.htm
It seems to be a problem from dynmap, not from nginx. 
I already installed dynmap new and checked the github wiki. 

My page is: 
http://maps.sunnyteater.de

nginx page config: 
https://gist.github.com/SunnyTeater/d90ca58344fc264ed410

configuration.txt 
https://gist.github.com/SunnyTeater/f6c6b20fa2ef7228562b        

Edit: 
12:42 - added nginx page, added configuration.txt

**Comment by Psy-Virus** [comment]
Hey there,
is this still an issue with [the latest Versions of Dynmap](http://www.dynmap.us/builds/dynmap/)?

If so, please head over to the new community forums at https://forums.dynmap.us and we'll try to figure that out with you!

thanks
