### ISSUE TITLE
Tiles folder across internet

### ISSUE THREAD

**Issue by elessday** [webbukkit/dynmap#1883]
Hi,

Is it just possible to change the path of the folder named "tiles" for the web interface ? (in the source code directly ?)
I want to keep the same adress ip of my minecraft server to consult my dynmap and host the "tiles" path (the heavy part) on another host.

I tryied to change the path in configuration.txt, but it doesn't work.

I don't care if the map is not rendered in real time, i can sync the files by another way.

Thank you in advance for your reply...

(Sorry for my bad english)

**Comment by Psy-Virus** [comment]
Hey @elessday,

Pls take a look into the `# URL for client configuration (only need to be tailored for proxies or other non-standard configurations)` section of your `configuration.txt` nearly at the end

The updating could be done via vpn and mounted tiles dir as network drive or something similar. :-)

Another method would be to use MySQL. 

:-)
