### ISSUE TITLE
Server Crash on 1.8.9 

### ISSUE THREAD

**Issue by MCShammer** [webbukkit/dynmap#1884]
Tried to Start the server with Forge 11.15.0.1715, Just trying to help by submitting the Bug report.

Exception in server tick loop crash.

[crash-2016-02-11_12.35.16-server.txt](https://github.com/webbukkit/dynmap/files/127231/crash-2016-02-11_12.35.16-server.txt)

**Comment by LemADEC** [comment]
Update your Java runtime

**Comment by MCShammer** [comment]
Well, now I feel stupid. Updating Java fixed it, thank you.
