### ISSUE TITLE
INFO org.dynmap.snakeyaml.parser.ParserException: while parsing a block collection; expected , but found BlockMappingStart

### ISSUE THREAD

**Issue by TimTheEnchanter0** [webbukkit/dynmap#1885]
I have begun using dynmap for my moded Server and it has been working OK, I didn't like how some chunks were not there and only the ones around a player would load, so I looked into how to fix it and found the full render locations functions in a tutorial, as soon as I saved the file and started the server I got this message

2 15:38:18 [Server] Server thread/ERROR [FML]: The following problems were captured during this phase
13.02 15:38:18 [Server] Server thread/ERROR [FML]: Caught exception from Dynmap
13.02 15:38:18 [Server] INFO org.dynmap.snakeyaml.parser.ParserException: while parsing a block collection; expected <block end>, but found BlockMappingStart
13.02 15:38:18 [Server] INFO at org.dynmap.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:519) ~[ParserImpl$ParseBlockSequenceEntry.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[ParserImpl.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:146) ~[ParserImpl.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:203) ~[Composer.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.snakeyaml.composer.Composer.composeNode(Composer.java:158) ~[Composer.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.snakeyaml.composer.Composer.composeDocument(Composer.java:123) ~[Composer.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.snakeyaml.composer.Composer.getSingleNode(Composer.java:106) ~[Composer.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:121) ~[BaseConstructor.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.snakeyaml.Yaml.loadFromReader(Yaml.java:480) ~[Yaml.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.snakeyaml.Yaml.load(Yaml.java:423) ~[Yaml.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.ConfigurationNode.load(ConfigurationNode.java:86) ~[ConfigurationNode.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.DynmapCore.enableCore(DynmapCore.java:510) ~[DynmapCore.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.forge.DynmapPlugin.onStart(DynmapPlugin.java:1356) ~[DynmapPlugin.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.forge.DynmapPlugin.serverStarted(DynmapPlugin.java:1933) ~[DynmapPlugin.class:?]
13.02 15:38:18 [Server] INFO at org.dynmap.forge.DynmapMod.serverStarted(DynmapMod.java:128) ~[DynmapMod.class:?]
13.02 15:38:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
13.02 15:38:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
13.02 15:38:18 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
13.02 15:38:18 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
13.02 15:38:18 [Server] INFO at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
13.02 15:38:18 [Server] INFO at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
13.02 15:38:18 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
13.02 15:38:18 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
13.02 15:38:18 [Server] INFO at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
13.02 15:38:18 [Server] INFO at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
13.02 15:38:18 [Server] INFO at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
13.02 15:38:18 [Server] INFO at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
13.02 15:38:18 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
13.02 15:38:18 [Server] INFO at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
13.02 15:38:18 [Server] INFO at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
13.02 15:38:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
13.02 15:38:18 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
13.02 15:38:18 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
13.02 15:38:18 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
13.02 15:38:19 [Server] Server shut down (running)
13.02 15:38:19 [Server] Not restarting crashed server.
13.02 15:38:19 [Server] Server stopped

Help with debugging this Please, I don't know what to do.

Any help is appreciated! Thanks!

**Comment by Psy-Virus** [comment]
this error happened while Dynmap was parsing your config files. You didn't follow the YAML rules. Please check them at http://www.yamllint.com/ to see where the error happened.
