### ISSUE TITLE
Seems that "web" directory setting isn't functioning.

### ISSUE THREAD

**Issue by VergilPrime** [webbukkit/dynmap#1886]
tilespath: ../../dynmap/web/tiles
webpath: ../../dynmap/web

The tiles are being stuffed where I want them but I had to copy all the others from their standard spot in plugins/dynmap/web/.  This appears to have begun once I updated from 2.2 Alpha to 2.2

**Comment by Psy-Virus** [comment]
Please retry with the latest version of Dynmap http://www.dynmap.us/builds/dynmap/
And maybe try to use full paths instead of relative ones.

If you still encounter problems, please head over to the new dynmap community forum at https://forums.dynmap.us
