### ISSUE TITLE
some problem with DNS

### ISSUE THREAD

**Issue by ganseky** [webbukkit/dynmap#1893]
i install the dynmap plugin on a 1.8.8 bukkit server 
with the XX.XXX.XXX.XXX:8123 the dynmap work perfectly
but in http://dynmap.mydomaine.com the map apear but the is no content in the page in the 

<div id="mcmap"></div>

moreover i folow the tutorial to install dns on debian 
https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-apache2-under-Debian

i search by myself and i found 

ReferenceError: componentconstructors is not defined
<anonyme> for script js 
markers.js
chat.js:2:1
 chatballoon.js:1:1
 chatbox.js:1:1
 playermarkers.js:1:1
 link.js::1
 timeofdayclock.js:1:1
 coord.js:1

**Comment by Psy-Virus** [comment]
As there was no discussion since years, I'll close this issue.
If this problem still persists, please create a new one.
