### ISSUE TITLE
Dynmap website ip

### ISSUE THREAD

**Issue by Jan3ka** [webbukkit/dynmap#1894]
Im having a problem with my dynmap website. It seems that someone with the same ip I have is using dynmap too so whenever I Do www.myip:8123 it shows me their dynmap and not mine. Can someone help me ?

**Comment by SimonOrJ** [comment]
Try changing your server's dynmap port to something other than 8123 from the dynmap configuration file.

**Comment by Scarecrowbirdie** [comment]
Same thing is happening to me. Craft bukkit 1.9  haven't tried the port thing yet.
