### ISSUE TITLE
Getting a error in Dynmap.

### ISSUE THREAD

**Issue by cademullen** [webbukkit/dynmap#1897]
So im using cauldron 1.7.10 on CreeperHost, and i have direworlf20 installed. So when i downloaded the lasted version of dynmap, i noticed that it was only a .jar, and it was not making a folder, so i installed a dynmap with a folder already in it, and it started to work. Im get a black map on the page, and when i go in game to render, it says its rendering, but it is not. So people are telling me to install the forge version and install the bukkit bridge so i tried that and it did not work. I tried with the old dynmap folder and removed it and both did not work. The error im getting is [dynmap] Exception during render job: world=world, map=null in console. Thats it, so im not sure what is going on.

**Comment by cademullen** [comment]
12:46:03  [Info] [dynmap] version 0.70-1263 is enabled - core version 0.70-323
12:46:03  [Info] [dynmap] Loaded 3 maps of world 'world'.
12:46:03  [Info] [dynmap] Loaded 744 pending tile renders for world 'world
12:46:03  [Info] [dynmap] World 'DIM-7' disabled
12:46:03  [Info] [dynmap] Loaded 2 maps of world 'DIM-1'.
12:46:03  [Info] [dynmap] World 'DIM-47' disabled
12:46:03  [Info] [dynmap] Loaded 2 maps of world 'DIM1'.
12:46:03  [Error] [dynmap] Exception during render job: world=world, map=null
12:46:03  [Warn] java.lang.NullPointerException
12:46:03  [Info] [dynmap] Enabled
12:46:04  [Error] [dynmap] Exception during render job: world=world, map=null

**Comment by Psy-Virus** [comment]
Since there was no conversation for years, I'll close this issue.
If you need further support, please open a new issue.
