### ISSUE TITLE
Tiles outside the border

### ISSUE THREAD

**Issue by Kixot14** [webbukkit/dynmap#1901]
When someone tp outside the border, border rejects his back, but anyway chunk make generate and trigger make render tiles of this chunk. http://prnt.sc/acprvz
And as a result, after long period of time we have ugly view of our map and need to delete all old tiles and do full rerender.

So maybe you can add command, which can remove solo tiles in **X** amount of blocks outside the border??

Or something like "chunkDEgenerate" trigger, which can delete tiles when for example i delete chunks outside the border with **/worldBorder trim** command.

Or just add option to prevent map rendering in **X** amount of blocks outside the border.

**Comment by Feld0** [comment]
+1. Would love to have one of the options described by @Kixot14. A full render can take a week or longer on larger servers.

**Comment by FedUpWith-Tech** [comment]
implemented with dmap https://github.com/webbukkit/dynmap/wiki/Configuring-Maps-and-Worlds-using-dmap
