### ISSUE TITLE
maxChunksPerTick option

### ISSUE THREAD

**Issue by Kixot14** [webbukkit/dynmap#1902]
In Dynmap config exist option **maxchunkspertick**: by default set to **200**
What exacly do this option? Does it make crop growth slower, if i set it to lower then 200 ??

And does it the same with **chunks-per-tick** in **Spigot.yml**? If yes, which option will override??

**Comment by EvilOlaf** [comment]
First I was like 'these are completely different settings', but then I was like 'hmmm, actually that is a pretty interesting question'.

sub.

**Comment by Kixot14** [comment]
Yes, Olaf. Actually!
And noone can't give me normal answer for this question!

**Comment by FedUpWith-Tech** [comment]
[From wiki](https://github.com/webbukkit/dynmap/wiki/Base-Plugin-Settings)
```
maxchunkspertick : this setting, an integer, limits the number of map chunks loaded during a given server tick (50ms). As loading of map chunks is the main source of load on the Bukkit server's main thread, this can be used to limit any lag that may be resulting from map processing.
```
