### ISSUE TITLE
Shaders in dynmap

### ISSUE THREAD

**Issue by Kixot14** [webbukkit/dynmap#1904]
How can i configure my Dynmap to set this amazing render shaders, like in this screen? https://pp.vk.me/c631828/v631828247/68c9/DVkD9GZ6Bg0.jpg
Is it real ??

And how much more resources it will consume, compared with render without shaders ??

**Comment by seema84** [comment]
This is a rendered image. No, this is not possible in Dynmap.

**Comment by SimonOrJ** [comment]
http://chunky.llbit.se/

Close?

**Comment by Kixot14** [comment]
Thank for info. Chunky is amazing program!

**Comment by capnslipp** [comment]
Old issue, I know, but it appears someone out there has gotten Chunky working as a DynMap renderer: https://github.com/leMaik/ChunkyMap

No idea how well it works, but it could potentially be what the OP was looking for.

**Comment by S0ly** [comment]
lemaik is the creator of chunky, he made an add-on for dynmap to work whit chunky in real time, since chunky is also coded in java
