### ISSUE TITLE
Essentials markers

### ISSUE THREAD

**Issue by WyRe** [webbukkit/dynmap#1911]
First ... congrats for that great plugin ... :D

Secondly are you aware about EssentialsX migration? (respect Dynmap-Essentials addon)

And I would like to know if there are specific commands to Dynmap-Essentials addon, for instance to hide some home markers from the map.

Thanks you so much.

**Comment by mikeprimm** [comment]
I'll give a look at a port to EssentialsX - I know there are a few forks around: is that the one folks are gravitating to?

**Comment by WyRe** [comment]
Sure, so I think at least, to Spigot doesn't work properly legacy version of Essentials for Bukkit. 

I've written this because of so many java exceptions what I get in my newest spigot versions... (when I include your addon to dynmap).

**Comment by mikeprimm** [comment]
Try latest dev build - it's build with EssentialX v2.0.1, and seems to be working (I'm seeing warp markers and such).

**Comment by WyRe** [comment]
Fine, apparently I have not got any java exception anymore. Good job and thank you very much :P

**Comment by WyRe** [comment]
However... what about dynmap-essentials commands (to hide some markers, for instance)?
