### ISSUE TITLE
Not available player up/down button

### ISSUE THREAD

**Issue by HimaJyun** [webbukkit/dynmap#1913]
Because the value of playerlist.height is greater, up / down button on the player list is not available.
The line 374 of map.js will be available in it to be modified as follows.
`playerlist.height(sidebar.innerHeight() - (playerlist.offset().top - worldlist.offset().top) - 64);`
to
`playerlist.height(sidebar.innerHeight() - (playerlist.offset().top - worldlist.offset().top) - 90);`

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release- please open a new issue if this persists.
