### ISSUE TITLE
Console errors all the time because of incompatibilty?

### ISSUE THREAD

**Issue by bloggy** [webbukkit/dynmap#1914]
I am using Terrain Control for generating my world. Since the 1.9 update I get these errors spammed in the console:

http://pastebin.com/gQPsVuqk

Are you able to fix it?
I am on latest Spigot 1.9 Dev Build + Latest Terrain Control + Latest Dynmap

**Comment by bloggy** [comment]
Any update on this???

**Comment by gbl** [comment]
Duplicate of https://github.com/webbukkit/dynmap/issues/1908 ?

**Comment by FedUpWith-Tech** [comment]
Duplicate of #1908, fixed in later builds of TerrainControl
