### ISSUE TITLE
Tile incomplete 

### ISSUE THREAD

**Issue by elessday** [webbukkit/dynmap#1915]
Hi,

Some files named "zzz......png" are incomplete. 

Like that :
![zzzzz_0_0](https://cloud.githubusercontent.com/assets/17133810/13867957/9935273a-ecc4-11e5-81f2-e47f2f1bd1ae.png)

Is it possible to activate the full render of tiles named "zzz..." when a modification on the server is made ? Because all the others tiles are ok.

Thanks in advance :)

**Comment by elessday** [comment]
![pbtiles](https://cloud.githubusercontent.com/assets/17133810/13900944/001a7712-ee13-11e5-90b7-3ea11139c9c5.PNG)

It concerne only files named "zzzz" or "zzz" "zz" ... For the others it's ok :/

**Comment by elessday** [comment]
Up ! Plz :)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
