### ISSUE TITLE
Colored names in playerlist wont show at web.

### ISSUE THREAD

**Issue by Rudomeister** [webbukkit/dynmap#1918]
Colored names wont show even colored names is set to true.

Under:
- class: org.dynmap.InternalClientUpdateComponent
  is:
  use-name-colors: true

This worked with the 1.8 version all the way. But not after new map with spigot 1.9.
- Using groupmanager as permissionplugin.
- Use of the same configurationfile as 1.8 version.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release- please open a new issue if this persists.
