### ISSUE TITLE
Dynmap Rendered, but definitely not my world.

### ISSUE THREAD

**Issue by coltonredwine** [webbukkit/dynmap#1919]
I have a server hosted with a service called Fluctis Hosting.

They have native support of bukkit plug ins, and I've had zero trouble so far;

However, I installed Dynmap, and everything seemed to load just fine... but I then realized the map that loaded wasn't mine. In fact it kind of looks like it might be someone else's....... I can tell because of the world spawn, and the fact none of my structures are visible, and the structure that is near the world spawn looks like it was built by someone else... any insight?

**Comment by EvilOlaf** [comment]
The port is already in use by someone else. Ask your provider for a free port and change accordingly in your configuration.
