### ISSUE TITLE
Custom marker icons aren't working in Forge

### ISSUE THREAD

**Issue by Fureniku** [webbukkit/dynmap#1923]
As it says on the tin, the image doesn't load. Path is correct - it won't accept an incorrect path so the images do exist.

You can see what I mean on my map here, there's a few around spawn. It's only custom ones not working; built-in icons work fine.

http://148.251.9.227:8123/

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or no longer relevant- please open a new issue if this persists.
