### ISSUE TITLE
Microblocks are invisible

### ISSUE THREAD

**Issue by adamk33n3r** [webbukkit/dynmap#1924]
Looking at #1302 it looks like this was supposed to have been implemented but when I render my map all microblocks are invisible. I'm guessing this may be because it's no longer Immibis but part of Forge Multipart now.

Is there any work in getting this functioning? :)

**Comment by atomiklan** [comment]
We are having the same trouble. Finally ended up here after on and off searching over the last year or so for a solution to this problem. Not sure what version you are on. We're running the latest Tekkit which runs Minecraft 1.6.4 and for Dynmap we currently have Dynmap-2.1-forge-1.6.4 with DynmapCBBridge-2.1 in our production server. This got Dynmap working, however same problem you mention above, Forge Microblocks are completely invisible on map. Not sure how Forge Microblocks are related (if any) to Immbis Microblocks. I do see that there is a 2.2 for both as well as a 2.3 in alpha. I have had mixed results stability wise on a dev server with these so I have not moved to production just yet. I will do some more testing soon to see how these two versions do by themselves with a blank Tekkit+Bukkit (aka MCPC+ or whatever) server install.

**Comment by atomiklan** [comment]
So I can now confirm that even Dynmap-2.2-alpha-1-forge-1.6.4 and Dynmap-2.3-alpha-1-forge-1.6.4 do not seem to work either. This is however a small ray of hope. This just may be how Dynmap interprets block data to generate this particular map, but it does look like the underground map partially recognizes the Forge Microblocks. See attached screen shots 1 - 3.
![capture1](https://cloud.githubusercontent.com/assets/5174240/14220846/bc4b3ecc-f830-11e5-8c4f-eb93cdd47019.png)
![capture2](https://cloud.githubusercontent.com/assets/5174240/14220847/bc4e46da-f830-11e5-8346-5645826a017e.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5174240/14220848/bc4ec506-f830-11e5-8187-f635949c7d8b.PNG)

**Comment by adamk33n3r** [comment]
Oh I never mentioned what version. That would be helpful. I'm using 1.7.10 with the latest recommended version of Forge.

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
