### ISSUE TITLE
[Feature Request] Javascript: Use replaceState() to Update URL post-drag

### ISSUE THREAD

**Issue by chuushi** [webbukkit/dynmap#1927]
https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method

history.replaceState() can be used to change the URL on the address bar without reloading the page.  I believe implementing this would save a click of a button when people want to share their current view of the map.  In addition, clicking on the refresh button will return the window to the place where the person last left off instead of bringing the person to the default view.

For example, the resulting code to execute can be:

`history.replaceState( null , null , "?worldname=world&mapname=flat&zoom=1&x=0&y=0&z=0" )`

This will change the parameter portion of the URL into what's written as a string in the third argument of replaceState().

Clicking on the link button on the bottom left corner does something similar already, so I believe you can just take the code implemented for that and use some parts for use in the replaceState().

**Comment by pquerner** [comment]
IE 8 and 9 would not support this out of the box. 
http://caniuse.com/#feat=history

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
