### ISSUE TITLE
Dynmap causing a lot more lag with v2.3-alpha-2 

### ISSUE THREAD

**Issue by SurvivalQuest** [webbukkit/dynmap#1928]
After updating from v2.3-alpha-1 to v2.3-alpha-2, the server has been experiencing more lag. The "Task: Unknown(Single)" event in the timings report is very high for Dynmap.

Timings: https://timings.spigotmc.org/?url=15838591
configuration: http://pastebin.com/YFhWveq1
Spigot 1.9.2

**Comment by Sikatsu** [comment]
Where did you get alpha 2?

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
