### ISSUE TITLE
'protected-player-info' not working

### ISSUE THREAD

**Issue by LukyLucaz** [webbukkit/dynmap#1930]
> ```
> # If true, player positions/status is protected (login with ID with dynmap.playermarkers.seeall permission required for info other than self)
> protected-player-info: true
> ```

I have a pretty straightforward problem. I set  "protected-player-info' to 'true' in the config, but even when logged in, nobody can see their own location.

**Comment by Dragonisser** [comment]
Same here.

Doesn't seem to work in dynmap-2.2 or dynmap-2.3-alpha-1

**Comment by tomi35** [comment]
It's still not working, not even in 2.4-SNAPSHOT-1146.

**Comment by wioxjk** [comment]
problem persist if any OP run /show ${PLAYERNAME} ?

**Comment by tomi35** [comment]
It was my fault. I didn't realize I had to enable the login in the configuration. With that it works fine. Although I think it would be nice if it was working without that, using the IP address as identification.

**Comment by tomi35** [comment]
After deeper testing, it turned out that the protected-player-info attribute is buggy. If the player has the right permission and logged in, he/she can see all the players on the server. However, after removing the '
_dynmap.playermarkers.seeall_ permission he/she cannot see anyone, not even his/her own position.

**Comment by ultimate255** [comment]
I want to have it so players can ONLY see their own positions.
Setting protected-player-info to True makes it impossible for anyone to see their own positions.
Even with login.

This is so frustrating, because at one point this had been working.

Any workarounds?

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.

This does appear to be fixed in builds > 3.0
