### ISSUE TITLE
ProjectRed/Railcraft Not rendering - need help with modscrapper

### ISSUE THREAD

**Issue by BonaireDreams** [webbukkit/dynmap#1931]
Hello Mikeprimm,

I need a little assistance getting ProjectRed and Railcraft blocks to render. 
Specs:
Direwolf20-v1.7.10 
Forge 10.13.4.1558

I first installed the recommened dynamp Minecraft v1.7.10 with Forge v10.13.2, Cauldron v1.7.10: DynmapForge v2.2 and rendered our world. As we had not started to build I was too concerned about a few black blocks as I know keeping up with all the mods is a nightmare. Now that folks are building using marble and railcrafts stone they are becoming a little more whiney. ;) I'd like to see if I can get them rendering. I managed to work around some using block aliases but of course that doesn't work for metadata. So I thought I'd try the dev releases.
I replaced the jar with Minecraft v1.7.10 with Forge v10.13.2, Cauldron v1.7.10: DynmapForge v2.3-alpha-1: but admit I did not delete the dynmap folder first. So I'm nor sure if there specific renderdata  left over from the previous version I need to clear?

That made no change (yes I did a rednerradius on a section of the world) So I downloaded DynmapModScraper for MC v1.7.10 (Forge v10.13.0). It ran great in my SP and generated the .txt files. I copied the ones for railcraft and project red into the dynmap/renderdata/modsupport still no change. I read on a previous issue here (also for Prjred and RC) that the files should be in a custom folder. So I created that and moved the files. restarted server again, rendered a section and still no change.

Am I missing a step? Is there some previous renderdata stored elsewhere that I need to clear so that dynmap will use the external files?

Thanks for the help.

**Comment by jasonmbrown** [comment]
Im also trying to Fix a few of the Railcraft Blocks. Im ok for the moment with incorrectly Rendered Blocks, As long as there is something Rendered. But I can't get any "Sub" Blocks from railcraft to render at all and Im not sure what Im doing wrong. I heard someone manually Split the files and Got them To render, But im not sure How to set the blocks textures after I have split the png's and thrown them inside another jar...

**Comment by Lukas45** [comment]
Better late than never I guess.
ProjectRed has to be split into 3 seperate files.
ProjectRed_Core
ProjectRed_Exploration
ProjectRed_Illumination

Where it has to be split is pretty easy to see in the ProjectRed_Core-textures.txt file, it very clearly marked where the next ProjectRed section begins

**Comment by FedUpWith-Tech** [comment]
To my knowledge this should be fixed with blockscan- if anyone cares and the issue persists, reopen.

**Comment by Discomanco** [comment]
At least to add what I said some 4 years ago:
The block scanner would catch ProjectRed, but would put it all in 1 unified file, which didn't apply properly to the blocks. So it had to manually be split into 3 separate files to work.
If that's still the case, no clue, but worth checking out if you're working on Dynmap
