### ISSUE TITLE
World Full Render Issue - Minecraft 1.9.2 

### ISSUE THREAD

**Issue by adrianpinnock** [webbukkit/dynmap#1932]
Hello,

My problem is, when ever I try and full render my map Dynmap starts to render the biomes correctly at first but then stops all of sudden. It still renders terrain but the terrain it starts to render does not match the biome and is generally very plan looking. 

I am currently running a spigot server for MC 1.9.2 and I not sure why this is happen. I am running dedicated server with a 6 core CPU and 18GB for ram. 

Any insight as to why this is happening would be appreciated.

![dynmap](https://cloud.githubusercontent.com/assets/1498139/14590526/848bb5d8-04ca-11e6-929c-00db95158e1c.png)

**Comment by EvilOlaf** [comment]
Not sure but maybe a known issue. 
I did not use dynmap without worldborder, but I know from my use with WB that the last chunk line before the void does not match on each cardinal direction.

**Comment by Sikatsu** [comment]
Yep same issue using dynmap and worldborder. Hope they maybe can fix it.

**Comment by BonaireDreams** [comment]
Just wanted to add for Mikeprimm that this does not appear to happen on the forge. Wolrdborder-forge, radius at 4000 from spawn and all biomes are perfect right to the edge of the void on a full render. So perhaps only Spigot related?

**Comment by megaxlr** [comment]
This is probably due to the way Minecraft handles the generation of Chunks. The chunk will only be populated with snow, flowers and trees if there are two or more adjacent chunks loaded and populated. Suggested fix: Hide non-populated chunks from web-view.
