### ISSUE TITLE
[Feature Request] Add the Fog of War effect on explored but out of range tiles

### ISSUE THREAD

**Issue by Soz3r** [webbukkit/dynmap#1934]
I had this idea for Fog of War where the map would have a CSS rgba(0,0,0,0.5) layer over tiles or chunks that hasn't had a block-render within 10 chunks or so.  If a block is placed at 0, 64, 0, then fog of war would lift the rgba(0,0,0,0.5) to rgba(0,0,0,0) and look bright and clear within a wide range from the tile updated. 

This would allow people to explore something fresh by seeking darker areas on the map while having the entire map previously rendered, lessening the strain on the CPU when the players are exploring.  This would drastically improve the immersion of having a map and wanting to explore areas.  While the terrain could still be seen on the map, having a darker area would prove no one has built there and give that authentic sense of exploration, rather than seeing everything on the map at a glance.

This would be a cool cross between this:
http://wiki.hatventures.net/images/thumb/5/58/Dynmap1.png/700px-Dynmap1.png

and this:
http://i57.tinypic.com/69j62h.jpg

Which might look a little like this:
https://upload.wikimedia.org/wikipedia/commons/e/ee/Freeciv-net-screenshot-2011-06-23.png

**Comment by jonathanselea** [comment]
This sound like a very cool feature. I have'nt realized that I need it until now, I hope that this get implemented.

**Comment by FrozenBeard** [comment]
This is a fantastic idea. To have a fog of war around the entire map and expose areas that the players are only, just like in the old RTS games. 
http://static.giantbomb.com/uploads/original/0/24/10713-fog2.jpg

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
