### ISSUE TITLE
Icons and markers

### ISSUE THREAD

**Issue by Poweringg** [webbukkit/dynmap#1937]
Hi, i have a question, how i can set more lines and bigger icons? as on image in yellow square.
Thanks for reply.
![000](https://cloud.githubusercontent.com/assets/15527318/14935568/6fa61580-0ed6-11e6-90e9-af36e6fd0bbd.png)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
