### ISSUE TITLE
Visibilitylimits not working

### ISSUE THREAD

**Issue by BleesTFE** [webbukkit/dynmap#1938]
So I set my visibilitylimits to from X:-500 Z:-500 to X2:500 Z2:500, yet I can still see the stone (I put it as a filament).
What I need is to only see like a floating island with the 1000x1000, the rendered area and then some stone, which also for some stupid reason takes time to render, even though I set the renderlimit to X:-500 Z:-500 and X2:500 Z2:500. I don't know what I've done wrong tbh, had some problems with rendering only those 1000x1000 too, you really need some clearer render intructions and tutorials on the plugin. And you need area claim like factions so you render only x amount out in a square. As I understand there's only full render which render every single f*cking block, and radiusrender which renders a circle.

Here's my "worlds" .txt document:
http://pastebin.com/BegrmnsU
Any settings I need to change?

Sorry to criticize so much, there's just so much that's unclear, for a noob like me, about this plugin. Totally awesome plugin!

**Comment by MrWouterNL** [comment]
I'm having the same issue.

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
