### ISSUE TITLE
Trees not generating on map

### ISSUE THREAD

**Issue by Small-Ku** [webbukkit/dynmap#1940]
The chunk that no tree generated on map is generated by WorldBorder with Glowstone ++ 1.9.2
![image](https://cloud.githubusercontent.com/assets/16464896/15134608/4beb6fce-16a0-11e6-9e4e-e7a802d241f4.png)

**Comment by KovuTheHusky** [comment]
If the trees aren't actually being generated at all (missing from the game world), it's a problem with Glowstone or WorldBorder.

**Comment by Small-Ku** [comment]
There are trees actually but not showing on map.
![image](https://cloud.githubusercontent.com/assets/16464896/15269701/1dad736c-1a3a-11e6-8eee-150d99232f9f.png)
![2016-05-15_01 12 09](https://cloud.githubusercontent.com/assets/16464896/15269703/25c4ea8a-1a3a-11e6-8e84-8bcead22cd16.png)

**Comment by jouki** [comment]
Try to generate the world again with DEFAULT settings (if you're using WorldBorder), I had the same problem (trees around the spawn and any further was nothing on dynmap). I'm using latest version of craftbukkit version (1.9.4)

I changed the settings of pregeneration of world to speed up the generation of world and that was the cause why the dynmap didn't render snow and trees (or anything else on surface)
