### ISSUE TITLE
Can't use CloudFlare

### ISSUE THREAD

**Issue by viet** [webbukkit/dynmap#1941]
When I use CloudFlare proxy for Dynmap (already setup on port 80 with and without nginx proxy), I got this error:

```
Forbidden
You don't have permission to access / on this server.

Apache/2.4.10 (Debian) Server at domain.tld Port 80
```

Is there a way to fix it?

**Comment by SlimaKCoder** [comment]
Try to fix permissions or/and change nginx root directory :)

**Comment by AnrDaemon** [comment]
This should really be closed, as this is in no way a dynmap issue.
