### ISSUE TITLE
Support for ForgeMultipart from Chicken-Bones

### ISSUE THREAD

**Issue by RouL** [webbukkit/dynmap#1942]
Hi,

it would be absolutely nice to have a built-in support for Chicken-Bones mods [ForgeMultiPart](https://github.com/Chicken-Bones/ForgeMultipart). Currently all the blocks from that mod are simply "invisible" on dynmap. I thought about trying to write model- and texture-files for it but since it is using NBT data to determine the "material" of the block, I think it's not possible.

PS: If it is too much work: I would totally understand it, bit I thought at least I'll give it a try. ;)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
