### ISSUE TITLE
How to uncheck markersets on dynmap by default?

### ISSUE THREAD

**Issue by bloggy** [webbukkit/dynmap#1943]
I tried this:

/dmarker updateset id:mymarkerset hide:true

But it does not work. When I create a new set with the parameters hide:true the set is not even shown in the dynmap top left corner. So players can not check the checkbox at all.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
