### ISSUE TITLE
Request: Rotation, Overlay, Layer, and "Child of" maps.

### ISSUE THREAD

**Issue by GeigerCounter** [webbukkit/dynmap#1945]
Rotation maps: Allow maps to have multiple perspectives specified or at least the ability to specify a map as a rotation of another map. Toggled by compass rose and arrow keys. ( e.g. having the surface map display the default map with SE perspective, and rotate to a corresponding NW perspective on click of the compass rose. ) All perspectives would have to be rendered separately, of course, but that is not a concern.

Overlay maps: Specify maps to act as overlays of existing maps, with configurable transparency. ( e.g. to allow a flat topography map to be overlaid upon a standard flat map. ) Toggled in the same manner as API defined overlays for the various plugins. Configurable in the file for overlay behavior. Like so.

overlay:
  #map name of overlay 
- topography
  #hidden by default until turned on with checkbox
  hidden: true
  #layer level, 0 will layer it on "top" of all other overlays with 0, 1-9 will render in order
  layer: 0
  #transparency percentage (inverse opacity)
  transparency: 0.8
  #hide from sidebar's map list? If so the overlay can't be viewed as its own solid map.
  hidesidebar: true

Layer maps: Maps that are only rendered up to a certain z-level. Another way to view underground structures for instance.

"Child of" maps: Maps that don't show on the sidebar list and must be toggled from its "parent" map by button press. ( e.g. PageUp/PageDwn to view different layer maps of the main map. ) Like all others, these would be rendered separately. Possibly accessed by a series of four coloured click buttons for view on mobile?

These may require lots of work, but they would make dynmap all the more useful. I'll contribute what I can and test anything, but I don't have the skill to implement all this myself.

**Comment by FedUpWith-Tech** [comment]
I believe this is possible in newer version of dynmap but I'm going to close this as its likely no longer relevant, please open a new issue if you still need help
