### ISSUE TITLE
Question: Defining new Blocks

### ISSUE THREAD

**Issue by ReltivlyObjectv** [webbukkit/dynmap#1946]
I am trying to add Aether II support to dynmap, but the instructions are very vague. What file in what directory do the [Block Definitions](https://github.com/webbukkit/dynmap/wiki/Defining-a-Simple-Block) go and what are the exact names and locations of the files that need to be created or changed? 

I know there were some changes made between versions, so for reference, I am using:
-Thermos 1558
-Aether 1.7.10-1.6
-Dynmap-2.0.0-forge-10.13.0

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
