### ISSUE TITLE
Dynmap Crashing with no explanation

### ISSUE THREAD

**Issue by ReltivlyObjectv** [webbukkit/dynmap#1948]
I am trying to define custom blocks, and dynmap crashes the server right after it says that textures are loaded. I am running Thermos 1558
Log Immediately before crash:
`[03:15:42] [Server thread/INFO]: [Dynmap] Mod Support processing completed
[03:15:43] [Server thread/INFO]: [Dynmap] aether[1.7.10-1.6] textures enabled
`

/minecraftdirectory/dynmap/renderdata/aether-texture.txt :
`version:1.7.10
modname:aether
texturepath:assets/aether/textures/blocks/
texture:id=Holystone
texture:id=Quicksoil
block:id=166,allfaces=0:Holystone
~
`

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
