### ISSUE TITLE
Strange Bug by activated Updaterender

### ISSUE THREAD

**Issue by Cha0sPudd1ng** [webbukkit/dynmap#1954]
When i have Updaterender enabled, i get this strange bugs, and when i deaktivate this, it works normal.

[https://www.youtube.com/watch?v=E1s_8L4r8Rg&feature=youtu.be](https://www.youtube.com/watch?v=E1s_8L4r8Rg&feature=youtu.be)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
