### ISSUE TITLE
Dynmap not updating when new chunks are generated/blocks are placed by players

### ISSUE THREAD

**Issue by robotnikthingy** [webbukkit/dynmap#1957]
I've noticed dynmap is not updating chunks at all when people explore new parts of the-end or the main world. It doesnt update the map either when players place blocks like it used to as well

here is my configuration file
http://pastebin.com/e6h2w6ek

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
