### ISSUE TITLE
Fullrender does not work. Says starting Fullrender but does not render anything

### ISSUE THREAD

**Issue by robotnikthingy** [webbukkit/dynmap#1958]
Hi, I re-installed dynmap from scratch on my server, and it wont render anything using the fullrender command

the console does not show any errors at all, and doesnt display any updated rendering information like it usually would. here is what the console says during startup
http://pastebin.com/RcAAbEud

heres my config file
http://pastebin.com/Abja31G9

Using spigot 1.9.4
Using Dynmap v2.3-alpha-2 from the spigot website

**Comment by Rocologo** [comment]
You must also check your webserver log, it could esily be wrong filesystem permissions.

**Comment by robotnikthingy** [comment]
where can I find the webserver log? Im using the standalone built in webserver

**Comment by robotnikthingy** [comment]
also I noticed it has a bunch of pending files in the dynmap folder

**Comment by robotnikthingy** [comment]
I think I figured it out. I had to set
update-min-tps
fullrender-min-tps

to a low number like 1 for it to work
