### ISSUE TITLE
[Feature Request] Add toggle whether or not dynmap automatically adds new world maps on world creation

### ISSUE THREAD

**Issue by BlackCoyote** [webbukkit/dynmap#1959]
I have a system that creates new worlds on the fly, but every world always gets shown on the dynmap. I found no option to disable it from automaticly trying to show new worlds.

If this config option already exists, where can I find it? If not, could it be added?

Thanks

**Comment by BlackCoyote** [comment]
Any news on this?

**Comment by EvilOlaf** [comment]
If a world is unconfigured it will be show on dynmap by default. You need to set enabled to false for each individual world you do not want to be shown.

**Comment by BlackCoyote** [comment]
@EvilOlaf Yes, I'm aware. That's the issue and the reason I'm making this issue post. With dynmap installed on a server I cannot generate new worlds on the fly without dynmap trying to render them.

My only option at this point would be to have my code automaticly edit the dynmap config and put the UID of the temporary world i'm creating in the config, save it, reload dynmap, and only then create it. Then when I'm disposing the world I would have to remove it from the config again.

This should be avoidable with a new config option within dynmap that would allow you to avoid dynmap from trying to render or just show worlds in general besides the ones listed in config.

**Comment by EvilOlaf** [comment]
Actually dynmap is not automatically rendering a new world when created. There is no trigger for this.
Though there is a trigger to render new generated chunks. This can be disabled. Maybe that helps a bit.

**Comment by BlackCoyote** [comment]
@EvilOlaf Hey thanks, that does make things a bit more clear.

 However as far as I can see, I still cannot stop dynmap from rendering new generated chunks on default for any new world automaticly, without preventing it from rendering chunks in the default worlds.

**Comment by EvilOlaf** [comment]
Yes. the triggers are set for all worlds globally and can afaik not be set for individual worlds.
I noticed that you can enable/disable worlds from ingame using the command `/dmap worldset worldname enabled:<true|false> : Set world 'worldname' enabled or disabled`
Maybe you can integrate this command into your world generation to be fired after the world has been generated or maybe even before if you know the name of your world.

**Comment by BlackCoyote** [comment]
@EvilOlaf I'll use that as a workaround for now, though it's not a fix I'd be happy with as permanent answer, since it requires console commands that might spam console or logs,  and it requires you to temporarily pause any ongoing dynmap renders.

**Comment by Kainzo** [comment]
I'd really like to have this, as this screws up several things for an automatic instancing system.

**Comment by dordsor21** [comment]
Can also eat up GBs of storage if you forget to set the world as disabled _every fucking time_ you make a new world (which is quite frequent for me). I can't believe this isn't a feature yet.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.

**Comment by RainfallHaruno** [comment]
This is actually a good request. I don't know how it was discontinued 5 years ago. I guess @BlackCoyote might not express it too clear. So bascially, when we create a new world, it will automatically be shown on the dynmap webpage. I would like an option to toggle it off, so any new maps wouldn't be automatically shown there. 

I don't want to be manually deletemap for everyone of them. It would be very useful for cases like mythicdungeons.
