### ISSUE TITLE
Dynmap render is off by 4k blocks.

### ISSUE THREAD

**Issue by Piero512** [webbukkit/dynmap#1960]
I've noticed recently that my dynmap is off by about 2k blocks. 
This is how I see myself on the Dynmap
![2016-06-12-133818_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6634316/15993150/00784612-30a3-11e6-8a5a-9569dab489a2.png)
This is where I should be
![2016-06-12-134059_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6634316/15993182/5714187a-30a3-11e6-82ef-8b2a0ea6fed8.png)
This is my actual position as /position command
![2016-06-12_13 37 51](https://cloud.githubusercontent.com/assets/6634316/15993189/79e78bf2-30a3-11e6-8976-b4498dbf667b.png)
I also noted that there's a problem with the spawn. It is dynmap centered on the spawn of the world?

**Comment by SimonOrJ** [comment]
Have you or anyone recently change the `worlds.txt` file or ran a command that modifies the flie?  Changing the "worlds.maps[#].perspective" to a lower/higher resolution can result in player position offset, which means you need to re-render the entire map.

**Comment by Piero512** [comment]
I backed up the server using tar.gz compression because I needed to re-allocate it. Maybe because I ran /dmap mapdelete world:flat and then I added it back. I would hate to rerender that huge map

**Comment by SimonOrJ** [comment]
You can try changing the map perspective to the one you think the server used previously.  That might fix the offset problem.

**Comment by Piero512** [comment]
None that would help it. I've purged the map now, so be it. Closed.
