### ISSUE TITLE
Dynmap fullrender cancelled, how to resume?

### ISSUE THREAD

**Issue by Sikatsu** [webbukkit/dynmap#1961]
Hello,

2 days ago I enabled dynmap fullrender in the evening. However, 18hours later when most people came online again from school, dynmap was still not finished and giving a lot of lagg on the server.

So, I had to cancel the render before I lose players because of lagg.

Now I'd like to resume the last part of the map over the night, but using /dynmap fullrender it will not resume where it was left off, but instead start all over again.

How can I render the last parts to the red border?

http://mc.villagercraft.eu:8050/

Hope someone can help me out quickly.

Thanks in advance.

**Comment by dwa1275** [comment]
I haven't been able to do this as well, I worked around it as I think the config will dump all chached files and just need to start over, what you can do is /dunmap fullrender 10, this is half the prossing limit witch is actually 20 and will reduce lag, but will also take much longer to render the map, other option is to get more RAM, at least until you have the map done, it looks to me that you have the map fill as well

**Comment by EvilOlaf** [comment]
My idea to work around this would be increasing the `fullrender-min-tps` settings to something like `19.5`, so under load dynmap will pause rendering by itself.
