### ISSUE TITLE
Generate part of map in 3D

### ISSUE THREAD

**Issue by jewome62** [webbukkit/dynmap#1965]
Hello,

I have a big map (20000x20000) with a flat dynmap on.
I want generate some 3D maps only for some locations as Spawn or Town.

But I can't declare twice or more the same world.
How i can do this ?

Thanks for your help

**Comment by dwa1275** [comment]
if you have already done /dynmap fullrender you will have to wait till its done, and a map size that large will take a few days to complete, I just got done with a 15000 world, so to do the 3D map at locations, and the map is not finished the do /dynmap cancelrender to stop all renders, then /dynmap radiusrender (radius) to cover the area you are trying to do 3D, I do my areas at 500, this will take about 10 15 minutes, it will start with flat, then cave, after the map will get an update with the 3D portion
