### ISSUE TITLE
Bone block rendered in black

### ISSUE THREAD

**Issue by minoneer** [webbukkit/dynmap#1966]
The new 1.10 bone blocks are rendered in black:

![bones](https://cloud.githubusercontent.com/assets/6442649/16192433/952ed91e-36e9-11e6-89ca-6232818f9077.png)

All lines are built with bone blocks, having a white color ingame.

dynmap version: 2.3-1142
server version: git-Paper-"37f586b" (spigot 1.10)

**Comment by tryzombie501** [comment]
I have this problem and magma blocks are also not visible in on the map for me.

**Comment by dwa1275** [comment]
its because the id type of the blocks are not supported at this time, seeing how this was just updated for 1.9.* , so the 1.10 blocks are not yet there, just keep watching for updates

**Comment by minoneer** [comment]
I can add Beetroot plants to that list

**Comment by sigmaroot** [comment]
Yes, same here. Blocks with ID's 213 to 216 are rendered in black / transparent. That are all new 1.10 blocks.

**Comment by sigmaroot** [comment]
*bump* :cry:

**Comment by Platinteufel** [comment]
same here

**Comment by WonderDave** [comment]
This issue is resolved in yesterday's build (2.4-1148):  https://www.spigotmc.org/resources/dynmap.274/updates

**Comment by sigmaroot** [comment]
Tested and verified. Safe to close.

**Comment by minoneer** [comment]
Problem has been resolved
