### ISSUE TITLE
Zoom Region Graphical Bug

### ISSUE THREAD

**Issue by Weregoose** [webbukkit/dynmap#1968]
![dynmap-bug](https://cloud.githubusercontent.com/assets/1588173/16438782/647a5760-3d67-11e6-868f-f84caeb62f43.png)

While shift-clicking to select a zoom region, if you send another left mouse button event meanwhile (e.g., with a keyboard/mouse macro), it doesn't wipe the first selection rectangle before drawing a new one, so you can effectively paint the map with these. Most users will never experience this, as they tend to release the mouse button before clicking again.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
