### ISSUE TITLE
Microsoft Edge & IE 11 Touch Problem

### ISSUE THREAD

**Issue by taoyouh** [webbukkit/dynmap#1971]
On Microsoft Edge and IE 11 on Windows 10, touching is not able to manipulate the map.

**Comment by SimonOrJ** [comment]
This is due to the outdated [Leaflet](http://leafletjs.com/).  Because there was too much changes between the current version (that Dynmap uses) and the version that supports IE/Edge touch events, nobody bothered to do anything about it (yet).  #1276

**Comment by taoyouh** [comment]
I also tried to fix this but found it very difficult to accomplish.




On Sat, Jul 2, 2016 at 4:17 PM +0800, "Simon" <notifications@github.com> wrote:





This is due to the outdated [Leaflet](http://leafletjs.com/).  Because there was too much changes between the current version (that Dynmap uses) and the version that supports IE/Edge touch events, nobody bothered to do anything about it (yet).  #1276

---

**Comment by taoyouh** [comment]
So the latest leaflet version has solved this problem , but the Dynmap didn't move to it?

**Comment by SimonOrJ** [comment]
Mhm.  Looks like Mikeprimm never found time to figure out what the Leaflet changed to break it again. :/

The Latest leaflet does have IE11 and Edge touch support.

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.

**Comment by database64128** [comment]
Just opened #3462.
