### ISSUE TITLE
[Feature Request] Add Cuberite support

### ISSUE THREAD

**Issue by PureTryOut** [webbukkit/dynmap#1972]
I would love to see Dynmap support [Cuberite](http://www.cuberite.org). It's a FOSS Minecraft server alternative written in C++, you can compare it to Bukkit and Spigot. It uses Lua for it's plugins. API documentation is available [here](http://api-docs.cuberite.org/).

Since it's devs welcome any plugin, they are probably eager to help out wherever needed.

**Comment by mishailovic** [comment]
+1 if they can do this

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.

**Comment by PureTryOut** [comment]
That... Seems weird. Why would you want it all in a single issue? That just makes it hard to track what's done and what not, and you can't have useful discussions on such requests.

**Comment by FedUpWith-Tech** [comment]
The discussions will not happen on the megathread, just a collection place for people to see what requests are already there and to browse as well as a tracker for us to centrally see what features people want. We had 60 open feature requests and having 60 open issues for those feature requests really drives up the issue count which can deter people from helping with this project or from looking for help.

**Comment by PureTryOut** [comment]
I guess having a list of feature requests is good, but you can accomplish that by using labels properly which... Well, you were already doing.

If people are deterred from a silly issue count without even looking into what those issues actually are, then I'm not sure you should even want them as developers :wink:

**Comment by FedUpWith-Tech** [comment]
You're probably right, but the elephant in the room is that 50 of those 60 feature requests are greater than one year old and at the current rate almost none of them will ever be implemented. I could just close the requests until more active development returns if it ever does or I can condense it so it will be easier to maintain if/when active development returns.
