### ISSUE TITLE
[Feature Request] Interface with mods to get modded block textures

### ISSUE THREAD

**Issue by AnrDaemon** [webbukkit/dynmap#1974]
These mods:

carpentersblocks (torch)
enderio (combustion gen., vat)
forestry (chests)
projectred (liquids, lights, ores)
thermalexpansion (workbench)

can't find textures for some of their updated blocks.
I managed to cobble something from their existing textures, what I managed to cross-match, but I would really appreciate a proper update.

**Comment by ShadowDrakken** [comment]
What I'd love to see is DynMap asking mods how to render the blocks. The render pipelines are already there, and DynMap could cache the low res versions of the blocks so it only needs to ask when it encounters new blocks

**Comment by AnrDaemon** [comment]
The render pipelines are not there, as it is a standalone server. And render is SideOnly(Side.CLIENT).

**Comment by FedUpWith-Tech** [comment]
This is implemented via [DynmapBlockScan](https://www.reddit.com/r/feedthebeast/comments/f9gker/howto_add_missing_mod_textures_to_dynmap_112/)
