### ISSUE TITLE
Plugin overrides -bukkit.* perm

### ISSUE THREAD

**Issue by VoltMC** [webbukkit/dynmap#1975]
Greetings! Wanted to report that whenever I add the plugin to my server, it apparently overrides the -bukkit.\* permission I have in place, which allows players to use commands such as /pl, /ver, among others that were previously disabled before adding the plugin.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
