### ISSUE TITLE
Support for some Japanese mods needed

### ISSUE THREAD

**Issue by l19980623** [webbukkit/dynmap#1976]
Hi, I really loved the mod and it did amazing job beside some Japanese mods. Their textures are missing. I am using version 2.3. Here are some that I found so far:
- BambooMod (forum.minecraftuser.jp/viewtopic.php?t=172)
- TofuCraft (http://forum.minecraftuser.jp/viewtopic.php?f=13&t=1014)

Hope they can be looked into and add support for. Thanks!

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
