### ISSUE TITLE
Triggers Not Working?

### ISSUE THREAD

**Issue by loganintech** [webbukkit/dynmap#1977]
Hi there. I'm trying to run Dynmap with a couple addons on my server and it seems like the triggers are not working. Using spigot 1.10 with these plugins:

![](http://i.imgur.com/drEy1yo.png)

[Here is my current configuration file](http://hastebin.com/ukalorurim.hs)
[And a worlds file](http://hastebin.com/fesugufiqe.hs)

No rush, thanks for the help.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
