### ISSUE TITLE
[Request] Chat timestamps

### ISSUE THREAD

**Issue by Discomanco** [webbukkit/dynmap#1979]
Possible to get an option to add timestamps into the webchat?
I've been trying to do it myself, but I haven't done a lot of JS, and not quite sure where to add what.

**Comment by Lukas45** [comment]
Managed to get it working with some assist - would still be cool to get official support for it though.
For others who seek the same, this method will require to use the player icons spot.
File: chatbox.js
functions added:
```
	Date.prototype.getFullHours = function () {
		if (this.getHours() < 10) {
	   return '0' + this.getHours();
   }
   return this.getHours();
};

	Date.prototype.getFullMinutes = function () {
   if (this.getMinutes() < 10) {
       return '0' + this.getMinutes();
   }
   return this.getMinutes();
};

	Date.prototype.getFullSeconds = function () {
		if (this.getSeconds() < 10) {
	   return '0' + this.getSeconds();
   }
   return this.getSeconds();
};
```

variables added:
```
	var timeHours = new Date().getFullHours();
	var timeMinutes = new Date().getFullMinutes();
	var timeSeconds = new Date().getFullSeconds();
```

variables edited:
```
	var playerIconContainer = $('<span/>')
		.addClass('messageicon').append("["+timeHours+":"+timeMinutes+":"+timeSeconds+"] ");
```

http://pastebin.com/MkvK7QLc

**Comment by FedUpWith-Tech** [comment]
This should be a PR, if the author is still active they should move this over there but will close for now.
