### ISSUE TITLE
No API Documentation

### ISSUE THREAD

**Issue by darkllama23** [webbukkit/dynmap#1981]
I am trying to create a plugin using the DynMap API but I can't find the documentation anywhere and I don't know where to start.

**Comment by darkllama23** [comment]
After looking at the source code for the dynmap essentials plugin I was able to find out how to get what I needed done, but I highly recommend a documentation of some sort

**Comment by SimonOrJ** [comment]
You're looking at the wrong place for the API.  Go here: https://github.com/webbukkit/dynmap-api
