### ISSUE TITLE
[Feature Request] /radiuspurge command to selectively purge an area of the map

### ISSUE THREAD

**Issue by molor** [webbukkit/dynmap#1982]
Hello. Can you add the /radiuspurge command?

**Comment by molor** [comment]
Please [2]

**Comment by roopekoo** [comment]
This could be useful when trying to fix blacks spots on the map that can't be fixed with overwriting the image data with /render, /radiusrender /updaterender commands. (At least in my case)

**Comment by molor** [comment]
Please /3/

**Comment by molor** [comment]
Please /4/

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.

**Comment by molor** [comment]
Ye it's closed but Please /5/
Still waiting from 2016..
