### ISSUE TITLE
[Request] Add ability to filter maps by logged in user

### ISSUE THREAD

**Issue by HammerHedd** [webbukkit/dynmap#1983]
I have a number of worlds, some of which are not for the general public. However, having a good map of things like the creative builder world are really useful for the builders. 

Would it be possible to have configure certain maps to only show in the web interface for particular users or groups? It could work by permission or whatever is easiest. Maybe tag each map with a public or private node and then have the private node check for group permissions?

It would be a great feature.

**Comment by AmauryCarrade** [comment]
[You could maybe use this](https://github.com/webbukkit/dynmap/wiki/Web-ui-login-support-and-permissions).
