### ISSUE TITLE
Includehiddenplayers are still hidden

### ISSUE THREAD

**Issue by Areomayo** [webbukkit/dynmap#1985]
As the title says, im having minor problems with the configuration.txt on a minecraft server im hosting for me and my friends, I've changed the value of includehiddenplayers = true, but when my players on the server goes underground they vanish from the map, until they go up again to the surface. i remember from previously servers i've hosted, i just changed that value to true and players were visable even if they went in a cave.

My setup is as following,
FTB Infinity Evolved 2.5.0 on a Debian server. minecraft vers. 1.7.10
Dynmap-2.3-forge-1.7.10.jar 
Im running dynmap webserver on an IIS server instead of the minecraft server.

Heres a pastebin of my configuration.txt file http://pastebin.com/E29SW2p3

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
