### ISSUE TITLE
[Request] Allow other plugins to post chat messages to the web using Dynmap API

### ISSUE THREAD

**Issue by robotnikthingy** [webbukkit/dynmap#1987]
Hi, I'm making a chatbot plugin for spigot, and while it displays messages in game for people to see, there is no way right now for me to make so people veiwing the online map can see the messages.

Can you create a method for the Dynmap API which allows plugins to post messages to the web chat?

**Comment by SimonOrJ** [comment]
https://github.com/webbukkit/DynmapCoreAPI/blob/master/src/main/java/org/dynmap/DynmapCommonAPI.java#L28

Use null or empty string for the sender part.

**Comment by robotnikthingy** [comment]
Didn't even notice that, thanks!
