### ISSUE TITLE
Crashes with SQL and /dynmap purgemap

### ISSUE THREAD

**Issue by wesley27** [webbukkit/dynmap#1990]
Hello, after changing dynmap to use MySQL and running fullrender, my server started randomly crashing every half hour to every few hours, with a slightly different stack trace every time. There's no errors before the crash, or anything else that could have caused it. Now that the map is mostly rendered, it crashes less and less and now rarely.

Also, similarly, when I just ran the /purgemap command, it crashed my server with this stack: http://pastebin.com/ZehT11Ri
It worked, and deleted the map, but, crashed the server in doing so.

**Comment by Deathwhitch** [comment]
Similar issue,  switched to mysql and did a full ever with no issues.  Since the full render however no tiles are updating.  From block changes or new chunk generation.  Map works on mysql database but wont update.

**Comment by jonathanselea** [comment]
@wesley27 Sound like an performance issue.
Is it possible for you to test it with a mySQL/mariaDB installation on another server?
I had no issues with the dynmap when I used mariaDB as storage on a separate webserver that I use.
