### ISSUE TITLE
Be more friendly to front-ends.

### ISSUE THREAD

**Issue by AnrDaemon** [webbukkit/dynmap#1992]
I want to be able to serve the world map even if the server is down.
I've set nginx as reverse proxy like this:

```
server {
    listen       80;
    server_name  sfs.rootdir.org;

    # RealIP config
    include extra/proxy_upstream;

    # Block access to VCS dirs.
    include extra/access_vcs;

    access_log "@HOME@/logs/access.log" combined;
    error_log  "@HOME@/logs/error.log" warn;

    charset UTF-8;

    add_header "X-UA-Compatible" "IE=edge" always;

    root   "@HOME@/htdocs";
    index  index.html;
    try_files $uri $uri/ =404;

    location ^~ /up/ {
        proxy_pass http://<actual MC server address>:8123/up/;
        proxy_send_timeout 2s;
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # deny access to .ht* files
    location ~ /\.ht {
        deny  all;
    }
}
```

However, this poses two issues that can't be solved gracefully:
1. The file `standalone/config.js`, even if named "standalone", is, in fact, dynamically generated. Which makes it unnecessarily hard to kickstart the proxy, but alas, it isn't updated often. In fact, I see it didn't update after I've initially set the proxy and resolved the sync of the two troubling files.
2. The file `up/configuration` is generated dynamically, which is kind of expected, but inability to fetch it from webpage botching the map and makes the proxy completely useless.

I've worked around both problems to a degree by adjusting the proxy config like this:

```
    location ^~ /up/ {
        try_files $uri @dynmap;
    }
    location @dynmap {
        proxy_pass http://<actual MC server address>:8123;
        proxy_send_timeout 2s;
    }
```

and setting up a script to download the two mentioned files and replace the ones I have in webroot, if they are changed.

```
#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

file1="$HOME/htdocs/standalone/config.js"
conf1="$(mktemp "$file1.XXXXXXXX")"

file2="$HOME/htdocs/up/configuration"
conf2="$(mktemp "$file2.XXXXXXXX")"

trap 'rm "$conf1" "$conf2" 2> /dev/null' EXIT HUP INT ABRT TERM

setfacl -m 'u:anrdaemon:rwX,g:www-data:rX,m::rwx' "$conf1" "$conf2"

if curl --silent --fail --output "$conf1" -- "http://<actual MC server address>:8123/standalone/config.js"; then
    diff -q "$file1" "$conf1" 2>&1 > /dev/null || mv "$conf1" "$file1"
fi

if curl --silent --fail --output "$conf2" -- "http://<actual MC server address>:8123/up/configuration"; then
    diff -q "$file2" "$conf2" 2>&1 > /dev/null || mv "$conf2" "$file2"
fi
```

…but this is not the end of the story. For some reason, if the latter file is stale in some way, the map go on a crazy self-refresh rampage until the new version of the file is served.

I would really appreciate more sane solution to the issue.

**Comment by jonathanselea** [comment]
I actually has the same issue as you do, or sort of. I posted more information in this thread:
http://serverfault.com/questions/799012/dynmap-throu-mod-proxy-on-a-external-webserver

**Comment by AnrDaemon** [comment]
And the mentioned workaround is - ?
The script I posted is merely a crutch and it won't help if server is down for more than a few hours.
