### ISSUE TITLE
Dynmap crashed on deleted dimension.

### ISSUE THREAD

**Issue by AnrDaemon** [webbukkit/dynmap#1993]
https://gist.github.com/AnrDaemon/7598aed0c95d09d1638ea71a7b6bdc09

Crashes when a dimension is deleted from the pool. That's… not really a good excuse to crash the server.

**Comment by mikeprimm** [comment]
It's a forge error, but I'll see if I can work around it

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
