### ISSUE TITLE
Dynmap, worldborder extended but can't seem to updaterender?

### ISSUE THREAD

**Issue by Sikatsu** [webbukkit/dynmap#1994]
I've just extended my worldborder, but when I use /dynmap updaterender or /dynmap radiusrender it immediatly says completed. How can I render the new parts of the worldborder?

**Comment by jonathanselea** [comment]
Travel to the location that is not yet rendered, or specify the coordinates where the updaterender should start from.

**Comment by SimonOrJ** [comment]
Alternatively, you can use another plugin that can load all chunks around the world first, then run `/dynmap fullrender` on the server.  I know one of the old world border setting plugin can do that, but I forgot what it was.

**Comment by Sikatsu** [comment]
I got further with the /wb fill command, but now it shows small black squares: http://mc.villagercraft.eu:8050/

Any advise?

**Comment by ghost** [comment]
WorldBorder sometimes forgets to generate some chunks - to fix this, you have to make sure the plugin (fill) will still load chunks that it thinks are generated.

For example, if you want to do this with the default settings:
`/wb world fill 20 208 true`
The `true` is important in this command.
