### ISSUE TITLE
Teleportcode on click

### ISSUE THREAD

**Issue by wucke13** [webbukkit/dynmap#1996]
Hey,
I just got this idea: what if you could click on a point on the map causing a textbubble to appear with the code to teleport to the point, you clicked (like /tp x y z). I used the /tp command a lot with coordinates from the map, but transfering the coordinates manually annoys after some time. What do you think about it? This probably could be done in a few lines of code...

**Comment by mikeprimm** [comment]
The work is finding the surface in a non-flat mode - - point on a 2-d view is a ray into a 3D view, so finding the point where that ray itersects the visible surface is the trick.  We do it during render, for obvious reasons, but don't store the results, so I'd have to put in some server logic to either trace the single ray, or remember the height map of the renders tiles - both are possible, but a bit more than a couple of lines of GUI code.  The hover position we do now is based on 'cheating' - assuming the y coordinate is 65 and working it x and z from that: that is easy enough, if the result would be acceptable...
