### ISSUE TITLE
Render progress output suppression

### ISSUE THREAD

**Issue by LarsCawley** [webbukkit/dynmap#1997]
Is it possible to suppress the output text when performing a radius render?  We only want to map small areas around players with an alias of '/dynmap radiusrender radius 1' to render the area just around them.  It would be great if Dynmap did this silently, or with a single line of feedback.

**Comment by Developaws** [comment]
You can suppress messages by using "/dynmap quiet"

**Comment by LarsCawley** [comment]
Thank you for that.  I find I am still getting render messages with my alias.
map:
  - dynmap radiusrender 1
  - dynmap quiet
  - "say I tried to be quiet!"
The result of what you see above is:
A line of text about how a radius render is starting.
[my name] I tried to be quiet!
Followed by more Dynmap feedback messages.
Dynmap 2.3-2074, Spigot 1.10.2-R0.1

**Comment by mikeprimm** [comment]
https://github.com/webbukkit/dynmap/blob/master/src/main/resources/configuration.txt#L345 - you can use this setti to globally control how often progress is reported: set it to a big number, and you'll pretty much only get mat start and end reports for renders.
