### ISSUE TITLE
WebUI aid

### ISSUE THREAD

**Issue by AsylumDreams** [webbukkit/dynmap#1999]
Aloha :)

Using:

SpongeForge 1.10.2-1698
MinecraftForge 12.18.1.2073
Dynmap Head Forge 1.9.4 (from here: dynmap.us/builds/DynmapForge/?C=M;O=D)

And struggling to work out how to make it possible to register. I can bring up the screen, but clicking register has no response.
 Tried rummaging around in the config but nothing in the last couple of hours has worked.
 Taking a break before returning to it and re-reading the wiki, but thought may as well post here to see if I can get something definitive :)

Please and thank you ^_^

**Comment by mikeprimm** [comment]
Register - you mean the login stuff?  Just want to understand where we are here.  Internal or external web server?

**Comment by AsylumDreams** [comment]
I mean for webchat and such, sorry for being unspecific ^_^

**Comment by AsylumDreams** [comment]
And for an external web server.
 Just to necro this as I'd forgotten about it u.u

**Comment by jwshields** [comment]
How is your server set up? What httpd are you using? What are the permissions on the "standalone" folder? How is your config set up, is it pointed to the correct directory? Are you using a SQL backend or flatfile? 
What is the exact problem that's happening? Messages not being sent, either in game to web or web to in game? can't log in, can't register?

**Comment by AsylumDreams** [comment]
Oh aloha
 Thanks for the reply.


Am now running SpongeForge 1.10.2 2171 5.1.0 B 2008, MinecraftForge 1.10.2 12.18.3.2185 and Dynmap Head Forge 1.10.2 2.4-SNAPSHOT-2080

I can run the command to bring up the registration code but when it comes to entering it within the prompt screen within the browser, nothing happens when register is clicked. There is no actioning of the click.

Config is here: http://pastebin.com/S0rfTBeu

 And the fact that I have no backend set-up yet is likely why it won't fire based on your querying that already.
 
I've not managed to find any walk-throughs on how to set webregister up for DynMap - have been assuming that any particulars will arise as I go through the motions, including the creation and implementation of an SQL.

**Comment by jwshields** [comment]
I see, alright.
Going over your config now....
You say you're using the external web server, but your config shows the internal one as being active.
If your client isn't updating the json files, it won't pick up the things you send it from the webui. 

When you set up the backend properly, (with your web server, php, db, and the plugin) messaging and registering should "just work"

There are a few guides on this wiki of getting it set up properly, but I've found them to be a bit outdated and recommend some insecure options.
If you want help setting things up, you can ping me separately (info on my profile here)

**Comment by SimonOrJ** [comment]
Yeah, as jwshields mentions, `org.dynmap.JsonFileClientUpdateComponent` part should be uncommented.

Also, what version of PHP are you running for your external web server?

**Comment by AsylumDreams** [comment]
I am not as of yet.
I was being somewhat churlish and expecting it to point me in the right direction for things as I went.

On holiday atm but will be back in a few days.

Thanks for all the attempts at absolvong my idiocy though guys :)

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, Jan 7, 2017 at 6:59 AM +0000, "Simon Chuu" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, as jwshields mentions, org.dynmap.JsonFileClientUpdateComponent part should be uncommented.

Also, what version of PHP are you running for your external web server?
