### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by SuaWez** [webbukkit/dynmap#2000]
Hello, 
I have installed dynmap on my Server (Running spigot 1.9.2), but when I go in my server website:port the page isn't showing up and the page say "ERR_CONNECTION_REFUSED".

My OS is Centos 6

**Comment by EvilOlaf** [comment]
Either dynmap is not working so the port is closed or iptables rejecting the connection or you are using the wrong address/port.

**Comment by SuaWez** [comment]
Iptables is disabled, the address configured in the config is 0.0.0.0 which cause the server to bind to all interfaces.. and the console doesn't give errors.

You can test it at http://zurecraft.eu:1598/

**Comment by EvilOlaf** [comment]
Port is filtered, so some kind a firewalled.

**Comment by SuaWez** [comment]
Trust me if I say that there isn't any kind of firewall yet, because all you can see isn't blocked in any way.

Well, I don't know if cloudflare means something but I don't think so, because it doesn't even work with the IP (cloudflare is binded on the domain ofc)

**Comment by jonathanselea** [comment]
Does your dynmap listen on that port?
`netstat -ltpn`

**Comment by SuaWez** [comment]
![38290d013e1c4429f6d16232214d66bc](https://cloud.githubusercontent.com/assets/19228739/18950857/6379b2c4-8642-11e6-8006-381a18b0fd90.png)

**Comment by wioxjk** [comment]
Someone can close this "issue". Server is down / A record is missing

**Comment by SuaWez** [comment]
@wioxjk  I solved it by myself, because no answer was useful.

Thanks anyway.
