### ISSUE TITLE
How can I mass add marker icons via editing a config?

### ISSUE THREAD

**Issue by FrozenBeard** [webbukkit/dynmap#2001]
From what I can see there are 2 places custom markers are saved in the Dynmap, in the root of ./dynmap in Markers folder and markers.yml

web/tiles/_markers_ and marker_worldname.json

If I wanted to manually add in all the world flags ~200 what file would I have to edit and where would be the best place to add all the 16x16 PNG flags? Theres no way im going to manually add each one in via the console!

**Comment by SimonOrJ** [comment]
I believe you need to edit and update both markers.yml and the markers folder while the server/dynmap is shut down.  Try adding one marker using the command, then check out what the Dynmap changed in markers.yml or the markers directory.

From what the wiki tells me, Dynmap automatically copies the image file to another directory for use with dynmap.  I added two custom markers using the command, but I haven't checked where the Dynmap copied the marker image.

I'll check it whenever I have a free time at home.  I'm pretty sure that one of the steps to take is to edit the markers.yml if you want to go manual.

**Comment by FrozenBeard** [comment]
For future reference, my method was fine, the issue I had is I did this when dynmap was still running, a /dynmap reload does not fix it, and it just needed a server reboot.
If anyone is interested in my import of 250 world flags, im happy to share how I achieved it.
