### ISSUE TITLE
Webchat Not Working Correctly

### ISSUE THREAD

**Issue by nathan93** [webbukkit/dynmap#2002]
Hello! 

The webchat feature of dynmap is not working correctly... When a user sends a message via the dynmap chatbox, it will show up on the server, but not in the dynmap chatbox. 

Also, is there a way to make it so messages fade out after a longer period of time in the WebUI?

**Comment by rautamiekka** [comment]
WEB->Server chat haven't worked for eons; I recall it worked before 1.7, not fully sure. Even after so long it's not working, so I've started to think it simply can't be fixed cuz of something in the Server software.

**Comment by SimonOrJ** [comment]
It's working just fine on my server.  I'm not sure what can be causing it to not work.

**Comment by mikeprimm** [comment]
Works fine in general - what plugins do you have?  Anything that messes with chat behavior or formatting can break things

**Comment by Remanent** [comment]
I am having the same issue as well.   I am unable to send messages from the web interface of dynmap to the ingame chat, and i don't see it in the server console.  Any messages in game show up in the web interface for dynmap.  using /dynmap sendtoweb (messages goes here) works as well.

I have id's to ips enabled, and therefore any users that has logged in cannot send a message to the server.

if i have my iphone pull up the webserver, and have it not on my wifi (using AT&T's network) the message goes through (shows up as web-001), but as soon as i rejoin my wifi, it ignores any messages.

**Comment by pupugit** [comment]
For me, when writing in webchat, the integrated webserver returns a http 500 error (but some users are able to write in webchat)
![sendmessage](https://cloud.githubusercontent.com/assets/24830511/25576447/6389cae0-2e5f-11e7-861e-a410056a5a2d.png)
I tried in 3 different browsers (chromium 60, firefox 53, ie edge)

**Comment by codahq** [comment]
Did anybody find a workaround for this yet?

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
