### ISSUE TITLE
Blurry map when using jpg regardless of quality

### ISSUE THREAD

**Issue by wucke13** [webbukkit/dynmap#2003]
Most browsers try to interpolate and smooth out jpg's. That causes the map to appear blurry when using jpg as image format, even if the highest quality is selected. I would suggest to simply add the following code to the CSS class of the tiles:
`
image {
    -ms-interpolation-mode: nearest-neighbor;
        image-rendering: -webkit-optimize-contrast;
        image-rendering: -moz-crisp-edges;
        image-rendering: pixelated;
}
`

**Comment by mikeprimm** [comment]
I'll give it a look - thanks
