### ISSUE TITLE
Source Code Disclosure - Detectify

### ISSUE THREAD

**Issue by wioxjk** [webbukkit/dynmap#2005]
GET /standalone/MySQL_access.php HTTP/1.1
User-Agent
Mozilla/5.0 (compatible; Detectify) +https://detectify.com/bot/fd15421794cc1529da604605edacccce62dbff18
Accept-Encoding
gzip, deflate
Accept-Language
en-US
Accept
text/html,application/xhtml+xml,application/xml; q=0.9,image/webp,*/*; q=0.8
Host
mydomain
Cookie
JSESSIONID=1p33jjy454nxr170hwi0jw9kth
Cache-Control
no-store, no-cache
Pragma
no-cache
Response Headers
HTTP/1.1 200 OK
Strict-Transport-Security
max-age=15552000; includeSubDomains
Content-Length
132
Date
Tue, 27 Sep 2016 14:13:27 GMT
Last-Modified
Mon, 22 Aug 2016 18:58:29 GMT
Server
Jetty(8.y.z-SNAPSHOT)

RESULT:

<?php
require_once('MySQL_funcs.php');

if ($loginenabled) {
    $rslt = getStandaloneFile('dynmap_access.php');
	eval($rslt);
}
?>

**Comment by jonathanselea** [comment]
Also

text/html,application/xhtml+xml,application/xml; q=0.9,image/webp,*/*; q=0.8

echo "<h1>500 Error</h1>";
   echo $errormsg;
   cleanupDb();
   exit;
}

function initDbIfNeeded() {
   global $db, $dbhost, $dbuserid, $dbpassword, $dbname, $dbport;
   
   if (!$db) {
      $db = mysqli_connect('p:' . $dbhost, $dbuserid, $dbpassword, $dbname, $dbport);
      if (mysqli_connect_errno()) {
         abortDb("Error opening database");
	  }
   }
}

function getStandaloneFileByServerId($fname, $sid) {
   global $db, $dbprefix;
   
   initDbIfNeeded();
   $stmt = $db->prepare('SELECT Content from ' . $dbprefix . 'StandaloneFiles WHERE FileName=? AND ServerID=?');
   $stmt->bind_param('si', $fname, $sid);
   $res = $stmt->execute();
   $stmt->store_result();
   $stmt->

**Comment by jonathanselea** [comment]
Also:
text/html,application/xhtml+xml,application/xml; q=0.9,image/webp,*/*; q=0.8
echo "<h1>500 Error</h1>";
   echo $errormsg;
   cleanupDb();
   exit;
}

function initDbIfNeeded() {
   global $db, $dbhost, $dbuserid, $dbpassword, $dbname, $dbport;
   
   if (!$db) {
      $db = mysqli_connect('p:' . $dbhost, $dbuserid, $dbpassword, $dbname, $dbport);
      if (mysqli_connect_errno()) {
         abortDb("Error opening database");
	  }
   }
}

function getStandaloneFileByServerId($fname, $sid) {
   global $db, $dbprefix;
   
   initDbIfNeeded();
   $stmt = $db->prepare('SELECT Content from ' . $dbprefix . 'StandaloneFiles WHERE FileName=? AND ServerID=?');
   $stmt->bind_param('si', $fname, $sid);
   $res = $stmt->execute();
   $stmt->store_result();
   $stmt->

**Comment by jonathanselea** [comment]
<?php
ob_start();
require_once('MySQL_funcs.php');
include('MySQL_config.php');
require('MySQL_getlogin.php');
ob_end_clean();

session_start();

if(isset($_POST['j_password'])) {
  $password = $_POST['j_password'];
}
else {
  $password = '';
}
if(isset($_POST['j_verify_password'])) {
  $verify = $_POST['j_verify_password'];
}
else {
  $verify = '';
}
if(strcmp($password, $verify)) {
  echo "{ \"result\": \"verifyfailed\" }"; 
  return;
}

if(isset($_POST['j_username'])) {
  $userid = $_POST['j_username'];
}
else {
  $userid = '-guest-';
}
if(isset($_POST['j_passcode'])) {
  $passcode = $_POST['j_passcode'];
}
else {
  $passcode = '';
}
$good = false;

$useridlc = strtolower($userid);

$_SESSION['userid'] = '-guest-';

$good = false;

if(strcmp($useridlc, '-guest-')) {
  if(isset($pendingreg[$useridlc])) {
     if(!strcmp($passcode, $pendingreg[$useridlc])) {
        $ctx = hash_init('sha256');
        hash_update($ctx, $pwdsalt);
        hash_update($ctx, $password);
        $hash = hash_final($ctx);
        $_SESSION['userid'] = $userid;
        $good = true;
		$newlines[] = arra

**Comment by jonathanselea** [comment]
This should not be accessible in the webbrowser.
Live example:
https://home.selea.se/standalone/MySQL_register.php

**Comment by SimonOrJ** [comment]
Tip: Enclose the code in three ticks (\`\`\`) on top and bottom, like so:
\`\`\`
(code)
\`\`\`

As for your webserver disclosing PHP codes, it looks like your webserver wasn't set up properly.  Did you install the PHP driver for your webserver?

**Comment by SimonOrJ** [comment]
I just checked out your website.  It says that it's run on Jetty, which most likely means you're using the Dynmap's built-in webserver.  You don't need to worry about the standalone directory; it's for running the web portion of Dynmap through a separate "standalone" web server.

**Comment by jonathanselea** [comment]
Yes, it is using the build in webbserver. I just use a reverseproxy do add some https support.

Can I enclose the code in the standalone webserver for dynmap? Would be nice

**Comment by SimonOrJ** [comment]
There's a whole wiki article on how to run the dynmap on an external web server.  That's what my server is doing.  If you want to take a look, check http://game.arcaneminecraft.com/dynmap/ out and turn on the developer tools (via [F12]).  It's using Lighttpd.

The wiki page: https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server

**Comment by wioxjk** [comment]
As long I can ReverseProxy it via apache.
I currently have one webbserver mod mod_ssl, mod_proxy and mod_security2.
My other servers is running "behind" my webbserver. Just to make thing easier.

**Comment by SimonOrJ** [comment]
If it works, it works ¯\\\_(ツ)\_/¯

Í didn't exactly understand proxy, and I wanted dynmap to take the simplest route without having to go through outside network, so I went for lighttpd.

Anyhow, the source codes for everything in the web/standalone directory are in here: https://github.com/webbukkit/DynmapCore/tree/master/src/main/resources/extracted/web/standalone

**Comment by mikeprimm** [comment]
This is a misconfigred web server - make sure your server is configured to execute PHP versus just return it: not a Dynnap issue.

**Comment by wioxjk** [comment]
@mikeprimm 
How can this be missconfigured when it is the internal one that is delivered with dynmap?

**Comment by mikeprimm** [comment]
The internal web server doesn't USE the PHP scripts....

**Comment by wioxjk** [comment]
So I can just delete the files then? Is that what you are saying?

**Comment by wioxjk** [comment]
Can I deleted the files?
@mikeprimm 
@SimonOrJ

**Comment by mikeprimm** [comment]
You can remove any PHP files from your install if you are using the internal web server - they are only there for use with an external web server, like Apache.

**Comment by wioxjk** [comment]
@mikeprimm 
Alright, thanks!
Guess my server was not missconfigured then ;) ;) ;) ;)
