### ISSUE TITLE
Disable Caves and Surface Map

### ISSUE THREAD

**Issue by nathan93** [webbukkit/dynmap#2006]
Is there a way to easily disable the cave map and surface map so that only the surface map will render and so the buttons for the caves and surface will not show up on the web viewer? Is there a command or a setting in the config to do this?

**Comment by EvilOlaf** [comment]
Yes, there is. Read the FAQ: https://dev.bukkit.org/bukkit-plugins/dynmap/pages/faq/

**Comment by nathan93** [comment]
I read that and the reason I made this is because I found that to be extremely vague and unhelpful so I wanted clarification.

**Comment by mikeprimm** [comment]
Easy options are here - https://github.com/webbukkit/dynmap/wiki/Configuring-Maps-and-Worlds-using-dmap

**Comment by Zelow79** [comment]
Are these methods the same for the .jar versions as well? Tried to remove the -cave line in the .txt files under the templates folder and saved them to new files as custom-*.txt and its still showing up the same. Do I need to tell it what template to use some how?

**Comment by SimonOrJ** [comment]
You have to run a /dmap command to delete the "surface" and/or "cave" map, or edit the "worlds.txt" file to take out references to surface and cave maps.

I don't know what you mean by .jar versions as dynmap as a whole is a java project.

**Comment by Igzak** [comment]
Pause all maps with (/dynmap pause all)
Then use these settings for your world (/dmap mapset world:flat)
Then delete the surface map (/dmap mapdelete world:surface)
Un-pause all (/dynmap pause none)
You can also remove the cave view with the same command (/dmap mapdelete world:cave)

**Comment by jaknz** [comment]
This works, but how do I remove the already rendered tiles from my plugins/dynmap/web/tiles directory? Have several GB of unused and unwanted images now.

Solved! `/dynmap purgemap world cave`
