### ISSUE TITLE
Dynmap Visibilitylimit question

### ISSUE THREAD

**Issue by xMelvinnx** [webbukkit/dynmap#2008]

**Comment by xMelvinnx** [comment]
Ps. I have already read all the help pages but for me they are not ckear enough xD

**Comment by SimonOrJ** [comment]
You would want to turn off all the rendering triggers in the configuration.txt, then run `/dynmap renderraduis <radius>` at the area you want to render or re-render.  There may be a better solution, but that's all I've got so far.

**Comment by xMelvinnx** [comment]
What this means is I only render the park? And disable all the options that will render anything else?

**Comment by xMelvinnx** [comment]
There is an option to set visibilitylimits in one of the /txt files, but I tried to enable it but it didn't work. Can maybe someone help me with enabling this? :D
