### ISSUE TITLE
Error 500 when trying to load the update file.

### ISSUE THREAD

**Issue by JoeyHaalboom** [webbukkit/dynmap#2010]
Hey, 

Im getting a Error 500 spammed in my webbrowser console:

`/dynmap/web/standalone/updates_world.php/728 500 (Internal Server Error)`

There are the files in standalone:

`
config.js
MySQL_configuration.php  
MySQL_update.php
configuration.php 
MySQL_funcs.php          
register.php
dynmap_access.php  
MySQL_getlogin.php       
sendmessage.php
dynmap_config.php 
MySQL_login.php          
SQLite_markers.php
dynmap_login.php   
MySQL_markers.php        
SQLite_tiles.php
login.php          
MySQL_register.php       
tiles.php
markers.php        
MySQL_sendmessage.php    
update.php
MySQL_access.php   
MySQL_tiles.php         
updates_world.php
`

My config.js

`var config = {
 url : {
  configuration: 'standalone/configuration.php',
  update: 'standalone/updates_{world}.php/{timestamp}',
  sendmessage: 'standalone/sendmessage.php',
  login: 'standalone/login.php',
  register: 'standalone/register.php',
  tiles: 'standalone/tiles.php?tile=',
  markers: 'standalone/markers.php?marker='
 }
};`

The map doesnt update but it opens.

**Comment by SimonOrJ** [comment]
Try copying the contents of `web/standalone/` into your web server again.  Do tell us how that goes.
