### ISSUE TITLE
[Feature Request] Add the ability to unregister webusers

### ISSUE THREAD

**Issue by ScuroK** [webbukkit/dynmap#2012]
Hello
I use the login-enabled function so that only registered players can access the map. 
But now i want to remove a user. how can i unregister him??

**Comment by hairpinNAT** [comment]
I am also interested how to remove registered user from webchat.
Any hint?

**Comment by hairpinNAT** [comment]
Still trying to find solution. I know when you register user via /dynmap webregister there is a file ../plugins/dynmap/webauth.txt where you can see hashed users passwords. In the beginning of file is a comment #DO NOT EDIT THIS FILE. So how to delete any of registered users?

**Comment by LArchitectt** [comment]
I'm also trying to find a solution.
Any hint?

Thanks!

**Comment by Kowagirl** [comment]
> Still trying to find solution. I know when you register user via /dynmap webregister there is a file ../plugins/dynmap/webauth.txt where you can see hashed users passwords. In the beginning of file is a comment #DO NOT EDIT THIS FILE. So how to delete any of registered users?

Looking for this feature too, though editing that file seems to work fine, just delete the line with the user.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
