### ISSUE TITLE
MySQL Error?

### ISSUE THREAD

**Issue by skulltraill** [webbukkit/dynmap#2013]
`[16:43:28] [Dynmap Render Thread/ERROR]: [dynmap] Face exists error - The last packet successfully received from the server was 44,512,878 milliseconds ago. The last packet sent successfully to the server was 44,512,949 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.`

Thing is, the MySQL server is on the same box, so idk how it would time out?

**Comment by wioxjk** [comment]
@skulltraill 
You are getting this message because your mysql server does not give an answer back. Try to restart mysql from time to time.

**Comment by skulltraill** [comment]
Ok, thanks, I'll try that...
