### ISSUE TITLE
port 8123 in use?

### ISSUE THREAD

**Issue by Edraket01** [webbukkit/dynmap#2014]
Hi, I have an issue. server states ERROR Failed to start WebServer on address 178.20.170.113:8123 : Address already in use. I cannot find a wau to solve this?

**Comment by EvilOlaf** [comment]
Another instance of dynmap is blocking the port. Usual problem when multiple instances of bukkit running on the same machine or to say using the same IP address.
Change `webserver-port:` in your config to something else or ask your host if it is possible to get access to the default port in some way.

**Comment by wioxjk** [comment]
Do you run it on Linux? provide the output of the command "netstat -ltpn" please

**Comment by Edraket01** [comment]
Thanks, 8124 works :-)
