### ISSUE TITLE
MySQL Issue 

### ISSUE THREAD

**Issue by MissFox0810** [webbukkit/dynmap#2015]
Hi,

I am getting this error when attempting to use a MySQL server, I checked the MySQL server and its not getting hits. I'm i missing something?

<pre>
[Dynmap] Error updating Maps table - No suitable driver found for jdbc:mysql://[hiddensqlservername]:3306/mcmap
</pre>

Dynmap Version: core=2.2-2058, plugin=2.2-143

**Comment by Wicowyn** [comment]
Try add mysql connector into your mods folder
https://dev.mysql.com/downloads/connector/j/

**Comment by jwshields** [comment]
To add onto @Wicowyn's comment, I ran into this issue the other day, it seemed like, in my experience, that Dynmap didn't see the SQL connector that Bukkit had, I had to **drop that .jar file into the plugins/dynmap/ folder** to get it to work.
