### ISSUE TITLE
1.10 blocks rendering as invisible

### ISSUE THREAD

**Issue by nammerbom** [webbukkit/dynmap#2019]
I'm surprised this hasn't been a more frequent issue, but for some reason 1.10 blocks are rendering as a black/transparent texture. We are using a custom shader on the latest release of the plugin. 

Example:
Red nether brick (id 215) renders black on dynmap
https://gyazo.com/86c66310b7fef448aa3289d399a86caa

in game, it correctly textures as a grey asphalt texture
https://gyazo.com/064f567052bfc90d5932dee2967418a2

There is connected textures for it, but I have connected textures turned off as it caused other ctm blocks to render transparent. The block texture non-ctm is the same resolution as the rest of the blocks in the resource pack. Other 1.10 blocks that are not textured in our resource pack also render as transparent

**Comment by sigmaroot** [comment]
Take a look at #1966 

This problem is known for more than 4 months but nobody is responsive at this time. It seems that Dynmap is no longer continued... :cry:

**Comment by wioxjk** [comment]
Really sad actually, dynmap is such an awesome plugin and the interest should be much higher.

**Comment by Alfro** [comment]
Could we use [texture definition files](https://github.com/webbukkit/dynmap/wiki/Defining-a-Simple-Block) to fix this while it's not implemented? I am going to give it a try on my server.

**Comment by nammerbom** [comment]
I have never heard of those before, give it a try and see if it works! Also, there are model definition files - would i be able to properly render custom models in my resource pack that way?

**Comment by Alfro** [comment]
@nammerbom I think it was meant for custom pack, originally, so most likely yes.

**Comment by nammerbom** [comment]
Have you figured out how to do it? I think I did the texture definition file right, but I'm not sure how to do the block definition file

**Comment by Alfro** [comment]
Hi @nammerbom!
I actually didn't even get to try it. I've been quite busy lately. But I've read that the latest update of the plugin should fix this: https://www.spigotmc.org/resources/dynmap.274/updates

(I still need to test it though, as usual :P)

**Comment by sigmaroot** [comment]
Tested and verified. Safe to close.
