### ISSUE TITLE
Dynmap + Nginx Reverse Proxy

### ISSUE THREAD

**Issue by jwshields** [webbukkit/dynmap#2025]
Apologies for making two issues at once.
I am also attempting to run Dynmap with Nginx doing a reverse proxy.
Currently I have it set up so that http://mywebsite/map/ forwards requests to http://localhost:8123/
The tutorials are out of date by what looks like four years, and I had to piece together information to get it mostly working.
Right now, most things work with this location block, but I'm getting errors for "/images/blank.jpg"
If I add another location block for "/images" with the same content, I get a Jetty 404 page; which is better than the nginx 404, but still not ideal. 
Any ideas?

        location /map/ {
                rewrite ^/map/(.*) /$1 break;
                proxy_pass http://localhost:8123;
                sub_filter "http://mywebsite/" "http://mywebsite/map/";
                sub_filter_once off;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host$uri;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_redirect off;
                proxy_cache map;
                proxy_cache_key "$host$uri";
                proxy_cache_valid 200 302 60m;
                proxy_cache_valid 404     10m;
                proxy_cache_use_stale error timeout invalid_header updating http_500 http_503 http_504;
                proxy_connect_timeout 10;
                }

**Comment by wioxjk** [comment]
Same issue with Apache reverse proxy too. Nothing that seems to affect the performance or the map in my case,

**Comment by magno32** [comment]
This setup would be simpler if we could change the context path for the web-app, is this possible?  FWIW, I'm having the same issue.

**Comment by keplersj** [comment]
I was just able to serve Dynmap behind a NGINX reverse proxy. Based off your config @jwshields, it should be as simple as:
```nginx
location /map {
            rewrite ^/map/(.*) /$1 break;
            proxy_pass http://localhost:8123;
}
```

**Comment by wioxjk** [comment]
> I was just able to serve Dynmap behind a NGINX reverse proxy. Based off your config @jwshields, it should be as simple as:
> 
> ```nginx
> location /map {
>             rewrite ^/map/(.*) /$1 break;
>             proxy_pass http://localhost:8123;
> }
> ```

The difference is that you proxy it to "/", while OP is using "/map".
