### ISSUE TITLE
Solution to worldedit not updating renders

### ISSUE THREAD

**Issue by popcorn9499** [webbukkit/dynmap#2029]
I found a possible solution to the dynmap not updating due to worldedit changes. I thought you guys may like to know about it. there is a api for a modification of worldedit called fastasyncworldedit. They created a api called [Blocks hub](https://www.spigotmc.org/resources/blockshub.331/)  It is a really good api and fastasynworldedit makes the game alot faster anyways. Another thing is that coreprotect can see worldedit changes to my knowledge anyways. Just thought this may help you guys with the problem

**Comment by EvilOlaf** [comment]
Dynmap also provides an API to start rendering a particular area.
