### ISSUE TITLE
buble label

### ISSUE THREAD

**Issue by AngDrew** [webbukkit/dynmap#2030]
1. how to make icon label on map that will popup buble like poly-line label when clicked?
the default icon label is mouse hover to see the label

2. and how to make if i want both hover and click?

**Comment by SimonOrJ** [comment]
These are impossible with current web implementation.

**Comment by FedUpWith-Tech** [comment]
I'm going to close this but leave it tagged as a feature request. the web side of dynmap isn't getting much love and at most its getting bug fixes. This technically could be possible with a custom web interface but seems a bit complicated for dynmap to do without a major overhaul of the web end
