### ISSUE TITLE
Dynmap the_end fullrender

### ISSUE THREAD

**Issue by Coniface** [webbukkit/dynmap#2033]
Hi,

I've been trying to generate a dynmap for my end map on Spigot 1.11. It always freezes completely the server. Plus, it only generates the main island. I've read that I'm meant to specify the coordinates of another chunk in the worlds, I did so but yet it fails generating and crashes before. It might be related to my previous issue though (#2032).

If you know anything about that, your help's welcome.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
