### ISSUE TITLE
Dynmap markers the_end

### ISSUE THREAD

**Issue by Coniface** [webbukkit/dynmap#2034]
Hi,

When using the dynmap, markers as players and signs randomly appear on the map. I mean that sometimes they are displayed but most of the time, they are just not taken in consideration.
For now, we can check our coordinates to use the flat map and know where we are and where we're going but it would be handy to get it fixed and use the dynmap as it should be used.

I'm running the last version of spigot (MC: 1.11) and Dynmap 2.3.

Thanks for your help.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
