### ISSUE TITLE
Incomplete render map

### ISSUE THREAD

**Issue by kevinjon27** [webbukkit/dynmap#2037]
Have problems when render map. If any ideas or the problems was solved please share here.

image:
![map](https://cloud.githubusercontent.com/assets/12078441/21498678/6f6b0190-cc61-11e6-8a05-344843e774c7.png)

you can find at : http://207.46.231.70:1500

**Comment by Alfro** [comment]
Looks alright to me now:
![it salright](https://cloud.githubusercontent.com/assets/11334172/21540988/943c1ed4-cdb3-11e6-9e75-c1826efba0ff.png)
