### ISSUE TITLE
[Feature] Allow cave maps to specify a minimum height

### ISSUE THREAD

**Issue by ddcruver** [webbukkit/dynmap#204]
This would allow you to make a cave map of only above sea level and a cave map of only below sea level.

Also you could create as many different cross sections you like. Possibly I want only the highest structures or only the bottom 10 levels of the map.

**Comment by JRII972** [comment]
Hey, does this work on the last snapshot ?

**Comment by masmc05** [comment]
> Hey, does this work on the last snapshot ?

should work, custom perspectives weren't removed
