### ISSUE TITLE
Iframe pulling issues for dynmap

### ISSUE THREAD

**Issue by worldofmadness** [webbukkit/dynmap#2040]
[](https://puu.sh/teI1W/404e45b524.png)

in CMS and normal html file as a test the iframe does the size but pulls no data to view but goto the link and it works.

 **<iframe src="http://IP:PortNumber5" width="100%" height="1200" frameBorder="0"> <p>Your browser does not support iframes.</p> </iframe>** <<<--- thats the code we use but still nothing when using iframe. my other iframe codes work fine on both sites any ideas what the problem is?

**Comment by SimonOrJ** [comment]
The `width="100"` attribute may be the problem.  What element (tag) is your iframe surrounded by, and what's the size of it?

**Comment by worldofmadness** [comment]
i have found the issue but am trying to figure out a work around because the wesite runs on http**s**:// it doesnt like the HTTP:// at all and google likes to block it as a non secure script

**Comment by SimonOrJ** [comment]
Looks like you've got it. Web browsers can load content from other secure site on another secure site. You'll have to use a webserver with SSL and proxy it, or  use a webserver with SSL and set up dynmap using the external webserver method.

An easy solution will be to make that page load only as http.
