### ISSUE TITLE
PHP 7 Compatibility?

### ISSUE THREAD

**Issue by uncovery** [webbukkit/dynmap#2041]
Is dynmap PHP7 compatible? I ran a checker before upgrading and got a couple of those here:

File: /bukkit/plugins/dynmap/web/standalone/MySQL_register.php
> Line 69: Removed function "split" called
    split('=', rtrim($lines[$i]));

File: /bukkit/plugins/dynmap/web/standalone/login.php
> Line 50: Removed function "split" called
    split('=', rtrim($lines[$i]));

File: /bukkit/plugins/dynmap/web/standalone/register.php
> Line 60: Removed function "split" called
    split('=', rtrim($lines[$i]));

File: /bukkit/plugins/dynmap/web/standalone/MySQL_login.php
> Line 51: Removed function "split" called
    split('=', rtrim($lines[$i]));

Does someone have experience running Dynmap on PHP7?

**Comment by SimonOrJ** [comment]
As it stands now, no.

I've made a PR to fix this, but webbukkit team hasn't been on it yet.

https://github.com/webbukkit/DynmapCore/pull/76

Just replace those "split" with "explode"

**Comment by wioxjk** [comment]
@SimonOrJ does only that make dynmap compatible with php7.0?

**Comment by SimonOrJ** [comment]
The usage of `split()` in the four files is the only thing that breaks php7.0 compatibility as far as I've seen.

**Comment by wioxjk** [comment]
@SimonOrJ That is good news, thank for providing that info.

**Comment by SimonOrJ** [comment]
https://github.com/webbukkit/DynmapCore/pull/76 really needs to be pulled into master soon.  The default repository for latest version of Ubuntu no longer contains  `php5`.

**Comment by wioxjk** [comment]
@mikeprimm

**Comment by mikeprimm** [comment]
@SimonOrJ PR looks good - thanks @SimonOrJ!
