### ISSUE TITLE
Occasionally slow web interface tile loading with SQLite

### ISSUE THREAD

**Issue by shepherdjerred** [webbukkit/dynmap#2043]
I'm not sure if this is an issue with my server (I do run a pretty cheap Kimsufi box), however loading tile seems to take ages. I use SQLite mostly because having thousands of files is a nightmare when making backups. I'm running Ubuntu 16.04 with apache2 2.4.18.

URL: https://ts-mc.net/livemap/survival/

What happens is I'll load up the page and tiles will usually load pretty fast initially However after scrolling around the map, it takes a considerable amount of tile for anything to load (but one it starts loading, it again goes pretty fast). If I open up a new tab, Chrome will show a message in the bottom left saying it's waiting for an available socket, and the page won't load. Accessing the site from another device while this is happening works fine, so that leads me to believe the blocking issue is only client side. I've confirmed this on my desktop, laptop, and phone, so I don't think it has to do with the device itself though, rather that the client can't open any more sockets due to them all being taken up by Dynmap trying to load images, which for some reason aren't actually loading.

I don't know what could be causing this, is it possible that using SQLite is the issue? I could always move to MySQL without issue if that's the case. I don't remember these issues being present with filesystem storage, however I'd rather not go back to it if that's possible.

If any more details are needed, I'd be happy to provide them. Thanks!

**Comment by SimonOrJ** [comment]
Even if you have to deal with thousands of files, saving the map using files is the most efficient way to go.  When the map is really big, using SQL has the potential to slow down the map loading.

**Comment by ShepherdJerred** [comment]
Not sure why performance is so abysmal though. I now switched back to filesystem but I'd really like to use SQLite..

**Comment by wioxjk** [comment]
@ShepherdJerred 
What does `htop` tell you when you are loading the map?
btw, I love your "Portal Template"

**Comment by ShepherdJerred** [comment]
Well as I said I switched back to a filesystem, I can't really test that anymore.
