### ISSUE TITLE
Cannot read property 'error' of null

### ISSUE THREAD

**Issue by FinlayDaG33k** [webbukkit/dynmap#2044]
Hii there,

I'm trying to setup Dynmap with an external web server.
However, all I get when doing the stuff below is a black screen with an error in the Javascript Console.
the error is:
```
Uncaught TypeError: Cannot read property 'error' of null
    at map.js?_=2.3-2074:29
    at success (jquery.json.js?_=2.3-2074:82)
    at Object.obj.success (jquery.json.js?_=2.3-2074:19)
    at fire (jquery-1.11.0.js?_=2.3-2074:3099)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.js?_=2.3-2074:3211)
    at done (jquery-1.11.0.js?_=2.3-2074:9310)
    at XMLHttpRequest.callback (jquery-1.11.0.js?_=2.3-2074:9720)
    (anonymous) @ map.js?_=2.3-2074:29
    success @ jquery.json.js?_=2.3-2074:82
    obj.success @ jquery.json.js?_=2.3-2074:19
    fire @ jquery-1.11.0.js?_=2.3-2074:3099
    fireWith @ jquery-1.11.0.js?_=2.3-2074:3211
    done @ jquery-1.11.0.js?_=2.3-2074:9310
    callback @ jquery-1.11.0.js?_=2.3-2074:9720
```

This is what I've done:

1. Create `config.js` on the Bukkit server in `~/server/plugins/dynmap/web/standalone`
2. Restart the server (not reloading as said in #1816)
3. copy the `web` directory over to the webserver
4. Profit??

However, this didn't work as I get an error thrown at my face.
This is my `config.js`:
```
var config = {
 url : {
  configuration: 'standalone/MySQL_configuration.php',
  update: 'standalone/MySQL_update.php?world={world}&ts={timestamp}',
  sendmessage: 'standalone/MySQL_sendmessage.php',
  login: 'standalone/MySQL_login.php',
  register: 'standalone/MySQL_register.php',
  tiles: 'standalone/MySQL_tiles.php?tile=',
  markers: 'standalone/MySQL_markers.php?marker='
 }
};
```

I hope somebody can help me :)

Cheers

**Comment by wioxjk** [comment]
And if you change the DocumentRoot to the standalone map directly into the dynmap catalogue?
Your config.js does not write into the files you copied...

**Comment by FinlayDaG33k** [comment]
`And if you change the DocumentRoot to the standalone map directly into the dynmap catalogue?`
Then all I get is a tree view of the `standalone`-folder.

`Your config.js does not write into the files you copied...`
How do you mean?

**Comment by wioxjk** [comment]
You have to create a symlink of your documentroot to the standalone catalogue in dynmap.

Follow this guide, and it will work (assuming you already configure the webserver correctly)
https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server

**Comment by FinlayDaG33k** [comment]
there's a slight problem I think: namely, my tiles are NOT in a folder, they are in a MySQL database :\

**Comment by wioxjk** [comment]
well, then you have to re-render it

**Comment by FinlayDaG33k** [comment]
Because my webhost and VPS can use the same MySQL Database, but my webhost can't access my VPS.

**Comment by wioxjk** [comment]
Are you really trying to send mysql data over WAN?

**Comment by FinlayDaG33k** [comment]
No? 
the webserver and the VPS can see each other.
But the webserver can NOT access the files on the VPS.
But, the webserver CAN access a MySQL database that is hosted on my VPS.
Which is why I use MySQL for the communication.
It's not WAN, just LAN.

**Comment by samuelbertrand** [comment]
Had the same issue. You need to enable PHP on your website to be able to use MySQL.
