### ISSUE TITLE
Dynmap command doesn't exist

### ISSUE THREAD

**Issue by MrAmericanMike** [webbukkit/dynmap#2045]
When I load an existing world with Dynmap enabled the /dynmap command is not there.

Its a world that was on a server and was sent to me. I opened an old world that was created without dynamap on it and the commands do work.

Any idea about what can be causing this?

Using 2.4 Alpha 1.7

**Comment by wioxjk** [comment]
have you installed it?

**Comment by SimonOrJ** [comment]
are you sure you're on the right server?

**Comment by MrAmericanMike** [comment]
Well, it's a single player world. Yes the mod is on the mods folder and works on other worlds, but not on this one, not sure why. I opened to LAN to enable cheats, switched to creative just in case, and nothing.
Maybe some info on the worldsave of that world I got was preventing me from using some commands, dunno.

**Comment by wioxjk** [comment]
Do you even run bukkit/spigot?!

**Comment by MrAmericanMike** [comment]
I guess I forgot to mention, I'm using the Forge version. No the Spigot or Bukkit ones.
But I repeat, I got the mod working on other worlds, it's just this specific one where the game says that /dynmap is not a command.

**Comment by Steffbeard** [comment]
Any luck? I have this problem too. Running 1.7.10 Dynmap Forge
