### ISSUE TITLE
Markersets disappearing

### ISSUE THREAD

**Issue by AveoCross** [webbukkit/dynmap#2046]
Hi. I have Dynmap Mod latest forge version on my server. I'm using nginx on Debian (internal server in dynmap disabled). I tried adding marker set and custom marker to that set and after that Markerset with Markers disappear after couple of seconds. But if I add Marker to default "markers" markerset, everything works good and markers are visible. 
After a while:
I just tried again and now I have other symptoms:
Created marker set, created marker and added to new marker set, reloaded dynmap, marker is visible but new markerset on list in dynmap website is not. I have marker "Aveo" added to markerset "Domy" but "Domy" is not visible. 
Any solutions?
Website link: http://aveocross.ml/dynmap/

**Comment by AveoCross** [comment]
Nah. Markers in new marker set still disappearing with marker set. Only markers in default "markers" marker set are visible.

**Comment by SimonOrJ** [comment]
Don't reload dynmap when you are modifying and working with markers.  It will break markers until the next server restart.  I've had this issue firsthand and it frustrated the heck out of me, so I don't even bother with the reload subcommand.

**Comment by AveoCross** [comment]
I just checked and i don't have any of these markers and sets in markers.yml.

**Comment by AveoCross** [comment]
I just added marker set and markers to it and didn't reloaded dynmap. And this really helped! Server restarted and markers and sets are still visible!
I don't close this issue because I don't think that bug with dynmap reloading is good ;)
