### ISSUE TITLE
Texture tinting with greyscale colors only change color saturation

### ISSUE THREAD

**Issue by Nagapito** [webbukkit/dynmap#2047]
I am trying to tint the ExtraUtilities blocks but I cant get the black-to-white colors...
If I set colorMult with any sort of grey value, it doesnt tint the block with the color I indicated but instead changes the color saturation...

The value FFFFFF does nothing and as I go down , AAAAAA, 555555, 000000, the block only gets darker but keeping the same color, like dark brown for the oak planks instead of grey and dark grey,

**Comment by SimonOrJ** [comment]
that is exactly what the tinting does.  Tint does not change the overall saturation, but overlays the specified color over the existing color.  You're looking at the wrong option.

Also, where did you find the tint option?

**Comment by Nagapito** [comment]
Exactly unless you try to tint with a coulor on the grey spectre. Then, it just desaturates the texture ...

Check this: http://minecrafttuga.cloudapp.net:8123/?worldname=world&mapname=surface&zoom=9&x=-30&y=64&z=-214

These are extra utilities coloured planks. First one is white and its tinted with FFFFFF, it shows normal oak texture.
Second one is grey, tinted with something like AFAFAF, it shows a darker oak texture.
Third one is dark grey, with something like 555555, shows almost as black.
The rest of the other planks, are correctly tinted.

Tinteing is set on custom renderdata files when applying the texture:
block:id=%colorWoodPlanks,data=1,stdrot=true,colorMult=CC803F,face0-5=17000:planks_oak
17000 indicates that the texture should be tinted with the colorMult value

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
