### ISSUE TITLE
DynMap Webserver https support lack

### ISSUE THREAD

**Issue by XxTWMLxX** [webbukkit/dynmap#2049]
The Dynmap plugin has its own webserver default hosting on port 8123.
using HTTP could HTTPS support be added.

I host a MC bukkit server from my ip having a domain name. and i have a webserver as well running on port 80/443.
However the webserver i run redirects all http to https making the browser do it automatically via a cached entry in the browser if a page is missed by the server and tried to be accessed with http. so to use dynmap i need to clear the cache every time i try to use it or it redirects to https and wont load.

Example: mydom.com/page2 will redirect to https://mydom.com/page2. keeping my site more secure but when i try to access http://mydom.com:8123 it redirects to https://mydom.com:8123 because my domain is configured to do this. but dynmap doesnt support https.

This is problem and will become a bigger problem as soon https will be required by firefox and chrome or it will flag the page as insecure and make you "proceed" to unsafe page with warning. 

It would be a good idea to add https support.
I cant use dynmap without it, that kind of sucks.

[Edit]
Tried to iframe the pages into pages on my actual webserver but then browser throws a insecure content on secure page mixed content warning.

**Comment by jwshields** [comment]
The https redirection is not an issue and what HSTS is supposed to do.

**Comment by wioxjk** [comment]
You could always set up ReverseProxy. If you running apache I can provide you with an working config (you have to change it att little to make it work with your setup thou)

**Comment by FrozenBeard** [comment]
I asked for this ages ago, and spent the entire of today setting up nginx and moving over my web folder, as I got https to work with nginx, BUT dynmap now does NOT work at all, just a black screen, nothing.

**Comment by jwshields** [comment]
Please post your configs so that we can see what's happening, your dynmap conf, your nginx conf, as well as the file structure/layout of how it's being accessed. (ie, are you doing a reverse proxy with the internal Jetty server, or are you using Nginx as the sole httpd?
Most likely it sounds that Dynmap isn't updating the JSON and that config is probably wrong.

**Comment by FrozenBeard** [comment]
@jwshields Thanks for the reply man! I created a new ticket! https://github.com/webbukkit/dynmap/issues/2068
I cant find any JSON file, and im not sure why, I posted configs in there, my Nginx is working fine, im using it as the https server itself, I didn't think of using it as a proxy! 
Map is http://map.piratemc.com

**Comment by jwshields** [comment]
Will reply there.

**Comment by GeekzGamingz** [comment]
@wioxjk Hey, I've been trying to follow your guide, but I feel like I'm missing a crucial step somewhere and I'm not sure what to do. Do you have a Discord that I can add you at so I can pick your brain? Any help would be most appreciated.
