### ISSUE TITLE
Dynmap full render question

### ISSUE THREAD

**Issue by Sikatsu** [webbukkit/dynmap#2050]
Does dynmap fullrender skip already generated chunks? I extended my worldborder a bit and run a /dynmap fullrender, is this the right way to do? Or is this only making the sqlite file huger?

The current file size is 17GB. http://mc.villagercraft.eu:8050/

Is that normal?

**Comment by wioxjk** [comment]
Fullrender does render previous rendered tiles.
In your case, you should look into "updaterender"

**Comment by Sikatsu** [comment]
I see. So I just made my sqlite file bigger for no reason? :/ 

Is that going to give problems?

Also, I can't seem to get rid of the black squares on dynmap with none of the renders.

**Comment by wioxjk** [comment]
Does the problem persist of you purge the map and do a fullrender again?

**Comment by Sikatsu** [comment]
The fullrender already costs me 2 days without any visible changes. Players have enough of the lagg to try it another time :/

Also, dynmap seems to lagg since I extended the border: https://timings.spigotmc.org/?url=gefedorove

Did I forgot something? I did extend it and use updaterender. (and after that fullrender without success)

**Comment by Sikatsu** [comment]
@wioxjk I did purge the map, then set it to ''vlowres'' instead and run another fullrender, it didn't work however.

http://mc.villagercraft.eu:8050/

**Comment by wioxjk** [comment]
Try do travel to thoose areas and do a radiusrender 200 or something

**Comment by wioxjk** [comment]
@Sikatsu 
Did you prerender the map or something? For example, with worldborder?
You did render it with a setting that increased the chunk render limit I guess?

Try to fill it with worldborder. That's where the real issue is.

**Comment by Sikatsu** [comment]
Radiusrender doesn't work, it doesn't change anything. Travelling works, but takes really really long.

I indeed pre-rendered the world with worldborder.
What exactly do you mean with chunk render limit?

I did fill the worldborder/

**Comment by wioxjk** [comment]
The issue here is not really on dynmap, it is worldborders fault.

Dynmap can't render chunks if there is nothing to render.
(I do run worldborder and dynmap on a VERY lagre map, I had the same problem as you do)

**Comment by Sikatsu** [comment]
The developer of worldborder claimed it's not an issue with worldborder, blegh

Well the small black squares will render once you travel there, but the black lines don't wanna go away until you zoom in on them.

**Comment by wioxjk** [comment]
Can you link the thread?
@Sikatsu

**Comment by Sikatsu** [comment]
Yes I can

https://github.com/Brettflan/WorldBorder/issues/78#issuecomment-277621359

**Comment by wioxjk** [comment]
@Sikatsu 
May I ask, what java args are you using for you Spigot server? And how much load does your server have when using fill?

**Comment by Sikatsu** [comment]
Last time I checked the load was 88%.
I don't know about the java args as I don't have an dedicated server but just a minecraft host.

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
