### ISSUE TITLE
Can the visibilitylimits option works only on a map not a whole world?

### ISSUE THREAD

**Issue by Davinais** [webbukkit/dynmap#2051]
Hello,

Since the images of hires surface have a large size, and only a part of the world I'd like to display in the surface map. I want to limit the area which dynmap would render. However, I want to browse the full flat map at the same time. Is there a way to limit the visibility area only on a single map? Thanks.

**Comment by FedUpWith-Tech** [comment]
this is possible with dmap or editting world.txt on the latest version but I'm going to close this as it is likely irrelevant due to age, feel free to open a new issue or reopen this one if you still need help
