### ISSUE TITLE
Missing water color (black)

### ISSUE THREAD

**Issue by TomberWolf** [webbukkit/dynmap#2052]
DynmapForge v2.3 with the Conquest resource pack (non-installer version) creatures black water tiles.

Link to the non-installer version for MC 1.7.10: http://adf.ly/l24Lk (Sorry, I don't know an ad-free link)

http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1242763-conquest-wip-weekly-updates

![dynmapblackwater](https://cloud.githubusercontent.com/assets/9993839/22771237/c27fcf2c-ee95-11e6-989f-16b3bf525e9b.jpg)

**Comment by Alfro** [comment]
Link to the texturepack skipping the ads: https://ravand.org/texturepacks/Conquest_.zip
:)

**Comment by TomPiXX** [comment]
Nope. That's the wrong version. That one is not working with Dynmap for Forge 1.7.10...

**Comment by Alfro** [comment]
It's exactly the version you added though. I just took the download link after the add and pasted it.

**Comment by C4BR3R4** [comment]
I have the same problem

I use:
- Spigot v1.11.2-R0.1-SNAPSHOT
- dynmmap v2.4 https://www.spigotmc.org/resources/dynmap.274/
- Resource Pack Conquest_ v1.11 http://conquest.ravand.org/

**Comment by User198263321** [comment]
Same issue.

I use:

Dynmap 2.0.0-775
Minecraft version 1.4.7
Forge version 6.6.2.534
![image](https://user-images.githubusercontent.com/53535277/123341210-95439680-d51b-11eb-987d-ae41e87c6088.png)

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
