### ISSUE TITLE
Configure option to change cache storage location

### ISSUE THREAD

**Issue by idlenexusgaming** [webbukkit/dynmap#2053]
It would be nice to be able to change the location for the cache file storage. How difficult would it be to add this option? My game server files are in one location and the map stuff is on another network storage. Please advise. Thanks.

**Comment by wioxjk** [comment]
There is already a option for it.

**Comment by idlenexusgaming** [comment]
Great! I couldn't find it in a google search. Would you be able to provide details or link to details?

**Comment by idlenexusgaming** [comment]
nevermind. Just wasn't search for the correct terms: tilespath

**Comment by wioxjk** [comment]
You can also use mySQL as backend too :)
