### ISSUE TITLE
Unable to use Dynmap Commands Ingame.

### ISSUE THREAD

**Issue by Frost212** [webbukkit/dynmap#2055]
Running Dynmap Forge V 2.4.0 on Minecraft V 1.10.2 with Forge version 12.18.3.2185 With Level 4 op. When i try to use any admin command (Any of the /dmap or /dynmap (render, fullrender etc) It gives me a "You do not have permission to use this command" Error. 

Edit: Can't use /dynmap show or hide either.

**Comment by jwshields** [comment]
What permissions plugin are you using? 
Are you sure you've granted the right dynmap perms to your user/group?

**Comment by Frost212** [comment]
Using forge, not bukkit Jw. No permissions plugin for it.

**Comment by AtaxiaGames-GM** [comment]
I'm having the same issue.

**Comment by Icepick869** [comment]
Having the same issue. Have made the /dynmap/permissions.yml file as indicated here on github, but non-op players can't use them.

**Comment by therimmer96** [comment]
I figure this is the best place for this. Sorry for the necro.

Would appreciate a way to do this. FTBu permissions would be super nice. Or maybe just a button that signed in people can use on the actual map page.

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
