### ISSUE TITLE
It's shows my public IP address

### ISSUE THREAD

**Issue by shadowcaptain21** [webbukkit/dynmap#2058]
Pls fix this it's showing my public IP address when I type in the chat which is not safe for me

**Comment by jwshields** [comment]
Read the configuration file. There is an option in there. 
Or create an account & sign in.

**Comment by SimonOrJ** [comment]
https://github.com/webbukkit/dynmap/blob/master/src/main/resources/configuration.txt#L45

Set that to true on your dynmap configuration.

**Comment by shadowcaptain21** [comment]
ok thanks

**Comment by wioxjk** [comment]
Not safe for you... bullshit

**Comment by rautamiekka** [comment]
^ [D]DoS is one.

**Comment by wioxjk** [comment]
@rautamiekka 
Well, he better stop using the internet, because his IP is visible everywhere.
Kids are to scared of ddos.

**Comment by shadowcaptain21** [comment]
this GitHub is supposed to help people not to blame them or something and
excuse me??kids??lol i wish tho and lol im talking to people who are worthy
and lol i think your the one who are kids if you can't help others then
stay out don't feel your too smart but ur not shame.....

**Comment by shadowcaptain21** [comment]
And btw you might want to know the importance of IP address if your not
scared to get attack by ddos or hack your internet kindly give me your IP
address I'll show what is the word 'scared' don't think you can't stop ddos
or hacking your internet by using VPN or changing your IP the technology
now can do anything 'nothing is impossible'

**Comment by wioxjk** [comment]
sure,
my IP:
81.235.28.194

You are welcome, kiddo

**Comment by wioxjk** [comment]
Was waiting the whole day yesterday from @shadowcaptain21 wrath, but it was very silent.
