### ISSUE TITLE
world_nether error

### ISSUE THREAD

**Issue by LXXIIInet** [webbukkit/dynmap#2060]
I keep getting the following error when trying to do anything with world_nether: Cannot set order on disabled or undefined world

the world is setup in the worlds.txt file MCMyAdmin under world management and so forth but I can not get that one world to work. The other two are working fine. Just not that one.

Any ideas?

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
