### ISSUE TITLE
is this still current ?

### ISSUE THREAD

**Issue by Bealze** [webbukkit/dynmap#2061]
https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server

I'm trying to use this so i can enable https as soon no site running in HTTP will be able to be seen under some new stuff coming out.

or if i was too symlink what file/ folder would i want to symlink to a https covered domain name

**Comment by SimonOrJ** [comment]
You can symlink the `web/` directory to the webserver and turn on `org.dynmap.JsonFileClientUpdateComponent` component by removing comments on this class declaration and the list below and commenting out the `org.dynmap.InternalClientUpdateComponent` component and its list.  That'll require PHP on the webserver.

If you'd like to move the `web/` to another place, you will need to follow the instructions in the link.  It does work, but symlinking it may be easier.

Alternatively, you can use proxy using Apache, Nginx, or other proxy-capable web server and leave Dynmap configurations unchanged.  Both options will allow you to use https provided that the web server software supports it.
