### ISSUE TITLE
Modded blocks and biomes not rendering

### ISSUE THREAD

**Issue by LiskoSlayer63** [webbukkit/dynmap#2062]
If using custom biomes like a Biomes O' Plenty with Dynmap all biomes and blocks added by BoP will be rendered invisible. Is there any chances to get dynmap render those?

Relative to [DynmapForge#63](https://github.com/webbukkit/DynmapForge/issues/63).

**Comment by Possemaster** [comment]
Same issue, all minecraft standard blocks are rendered. Only all mod blocks appear transparent.
Even with a modded texturepack I got the same render.

![dynmap_mods1](https://cloud.githubusercontent.com/assets/7541145/24136955/dbfa97fc-0e11-11e7-8bdc-2173a0401c28.PNG)
![dynmap_mods2](https://cloud.githubusercontent.com/assets/7541145/24136956/dbfe6daa-0e11-11e7-93b1-bc87b78a173c.PNG)

If you want the link to the map : https://www.wonderworlds.nl/map/beyond
Modpack used: FTB Beyond 1.1.0 Release
Forge Version: FTBserver-1.10.2-12.18.3.2254-universal

Latest Server start Log:
[fml-server-latest.txt](https://github.com/webbukkit/dynmap/files/857366/fml-server-latest.txt)

**Comment by Possemaster** [comment]
I know now why these block don't render.
The mod supports 1.10.2 but WIthin the JAR file all Block definitions (renderdata) are for 1.7 mods. So they do not coorlate to the 1.10.2 Mods.

@Mod Author: Is it possible to create a JSON converter for the assets/models and assets/textures so we can run a command from dynamp to check the mods that are installed and generate the renderdata for Dynmap based on the data the mod provides in the aseets folder?

**Comment by rautamiekka** [comment]
@Possemaster Please edit the @ mention above this comment, it's mentioning a person who has nothing to do with this.

**Comment by Mrtenz** [comment]
Any fixes for this yet?

**Comment by RileyGuy** [comment]
Yeah, the mod scraper isn't updated, what are we supposed to do?

**Comment by mikeprimm** [comment]
I'm actually starting a very 'big' project, which will allow Dynmap to render pretty much any block in a v1.8 or later MC mod that is using the JSON model format they introduced then (which was the same change that made ModScraper not a workable solution).  I've been working it this week, and hope to start having alpha level code in the next week or so - it'll be a BIG change: very disruptive, possibly unstable for a bit (the version including it will DEFINITELY be a 'v3.0' level update).  I'll try to remember to post here when the first builds are available - I'll definitely need help with testing.

**Comment by Mrtenz** [comment]
Sounds great! I will definitely help testing on my server when the first alpha versions are released.

**Comment by Possemaster** [comment]
@mikeprimm Count me in. I will help testing this out.

**Comment by RileyGuy** [comment]
I wouldn't mind testing this as well.

**Comment by Sunconure11** [comment]
Sounds good.

**Comment by legracen** [comment]
Count me in for testing.

**Comment by mikeprimm** [comment]
OK - I'll keep things posted here: this is just about to become my 'main side project' - I just finished a major port of another mod I own for a private server (one that provides a couple thousand custom blocks...) from 1.7.10 to 1.11.2, which served as a 'deep education' on the post 1.7 'block state' and 'block model' scheme, so I'm definitely feeling ready to get busy on this.  As with most things Mojang, the new system isn't quite as good as it could have been - there will be times where custom blocks aren't going to be handled properly without some additional code or data provided by us, but I'm honestly thinking that we can get to where 90%+ of custom blocks 'just work'.

**Comment by gdude2002** [comment]
I'd be pretty hype for this as well. You're bringing hope for people looking for a solution to a years-old problem, props.

**Comment by pupugit** [comment]
v3 is available now on your buildsite. did you allready include your magic ub there? is there something we have to do on our side to "activate" it?

**Comment by legracen** [comment]
Any chance i could bend your ear @mikeprimm so i can try and build it and test for 1.10.2?

**Comment by mikeprimm** [comment]
I'll have a full set of 3.0 builds by the time there is relevant content to test - no worries!

**Comment by legracen** [comment]
Good to Hear @mikeprimm . I will keep my eye on it :) and you really should have a donate button for all the work you put in man.

**Comment by smmmadden** [comment]
Looking forward to seeing the next release of Dynmap!  Hoping also there will be bungee support to have one address to share out and a drop down to switch between the worlds. :-)

**Comment by fcpwiz** [comment]
@pupugit Where are the v3 builds?

**Comment by mikeprimm** [comment]
http://www.dynmap.us/builds/DynmapForge/ for Forge, http://www.dynmap.us/builds/dynmap for Spigot/Bukkit.  The 'bleeding edge' dev mod for adding modded blocks automatically is DynmapBlockScan (currently only for forge 1.11.2 - http://www.dynmap.us/builds/DynmapBlockScan/

**Comment by fcpwiz** [comment]
@mikeprimm Thanks. So without DynmapBlockScan, what does DynmapForge v3 do that's new?

**Comment by mikeprimm** [comment]
Not much yet - the split is temporary: DynmapBlockScan is hugely unstable and in rapid development, while Dynmap v3.0 will be making smaller changes to support it (and other less destabilizing changes).  I'll be merging them when they get closer to being done.  The work for DynmapBlockScan is kind of huge, with lots more to do.

**Comment by charmesal** [comment]
I notice that v3.0 is only available for 1.11.2 and 1.12.
is 1.11.2 compatible with 1.10.2 or can we use the "Dynmap-HEAD-forge-1.10.2.jar" on a 1.10.2 server?

**Comment by mikeprimm** [comment]
I'll be adding builds for 1.10.2 as I get further in to developing v3.0 - its a big release, and keeping N different versions working while its core function is being done is a pain in the ass: time better spent elsewhere.  Once v3.0 is more complete and stable on 1.11.2 and 1.12, I'll add builds for 1.10.2, 1.9.4, and 1.8.9.

**Comment by charmesal** [comment]
Okay that makes sense. Thanks for the reply.

Also; I know there is no set timeframe but could you tell us whether it'll take around 1 or more like 4 months?
This way people know if they can wait or just use a different version of minecraft maybe.

**Comment by mikeprimm** [comment]
I'm really hoping to have the bulk of the major dev work done within the next month.

**Comment by pupugit** [comment]
Many many thanks @mikeprimm! The BlockScan Mod works like a charm! It makes the Webmap much more beautiful!

**Comment by charmesal** [comment]
@pupugit Didn't work for me. I updated both mods to the latest version and tested it on a new server so no old maps were present. It scanned all mods but I keep getting these 4 messages:

"[Dynmap Render Thread/WARN] [Dynmap]: [Dynmap] Resource assets/actuallyadditions/textures/blocks/models/modelcoffeemachine.png for mod actuallyadditions not found"
"[Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] extrautils2:assets/extrautils2/blockstates/playerchest.json : Failed to open blockstate" 
"[Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] cfm:bath_top:  NO MATCHING HANDLER"
"[Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] forestry:still: Animated block - needs to be handled specially"

I understand that it doesn't work perfectly but it's not doing anything at all for me.
Did you use a different (not default) config?
Are you using Windows or Linux?

**Comment by AveoCross** [comment]
Glorious! Glad to see new version. I will participate in alpha testing on my server :D

**Comment by Asherslab** [comment]
is there a GitHub link or anything where i can see progress on this BlockScan mod?

**Comment by thefinaldegree** [comment]
@Asherslab You can see the current status here: [https://github.com/webbukkit/DynmapBlockScan/issues/1](https://github.com/webbukkit/DynmapBlockScan/issues/1)

**Comment by Charm8er** [comment]
Has this ever been fixed?  Having the same issue 3 years later...

**Comment by FedUpWith-Tech** [comment]
> Has this ever been fixed?  Having the same issue 3 years later...

Have you looked at dynmap blockscan?

Dynmap standalone will never be able to render modded blocks by design.

**Comment by Charm8er** [comment]
> > Has this ever been fixed?  Having the same issue 3 years later...
> 
> Have you looked at dynmap blockscan?
> 
> Dynmap standalone will never be able to render modded blocks by design.

Does this replace Dynmap or work with it?

**Comment by FedUpWith-Tech** [comment]
> > > Has this ever been fixed?  Having the same issue 3 years later...
> > 
> > 
> > Have you looked at dynmap blockscan?
> > Dynmap standalone will never be able to render modded blocks by design.
> 
> Does this replace Dynmap or work with it?

Explanation:
https://www.reddit.com/r/feedthebeast/comments/bwa5q6/how_to_dynmap_mod_textures/

Pregenerated textures:
https://github.com/FedUpWith-Tech/DynmapBlockScan-Data
