### ISSUE TITLE
[Feature Request] Websocket for map updates

### ISSUE THREAD

**Issue by chuushi** [webbukkit/dynmap#2064]
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_a_WebSocket_server_in_Java

Most MC players should be using up-to-date browsers.  I believe Dynmap will benefit from using websockets to give the live map viewers instant and update of player position, health, and map tile location while keeping the used bandwidth to the minimum.  The traditional method can be used for those not on the modern browsers or those unable to access the websocket port.

**Comment by moose51789** [comment]
i think this would be a great idea.  i've been trying to wrap my head around the source code for this complex beast to see about bringing the web interface up to snuff for modern usage

**Comment by SimonOrJ** [comment]
I'm still interested in trying to and help bring this into Dynmap.  I hope @mikeprimm considers this for the Dynmap v3.0.0.  We have to think forward.  All modern browsers have websocket support, so this should be implemented in place of RESTful way.

**Comment by moose51789** [comment]
hes already got a 3.x build going, i didn't notice anything change at all though.  I guess we could always fork this and start doing so?  see if he'd merge it in.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
