### ISSUE TITLE
Exceptions loading resource packs

### ISSUE THREAD

**Issue by cryolithic** [webbukkit/dynmap#2065]
I've tried loading a few different resource packs, and I always seem to run into an exception at the point it loads the pack to begin a render.

Error from logfile here: http://pastebin.com/HPwimbQD

Config is nearly default. Changes are as follows:
custom-shaders.txt
http://pastebin.com/Fgxfmjq1

templates/normal-hires.txt
http://pastebin.com/hNHuEix1

and the file /texturepacks/Invictus-4.2.zip exists.

I've also tried it with 3 other texture packs to the same effect.  

Spigot server was built last week, so roughly latest 1.11, and dymap is 2.4

**Comment by SimonOrJ** [comment]
This is related to (and original issue of) #2067. It's the malformed shulker box rendering code.

**Comment by FedUpWith-Tech** [comment]
Fixed in #2109
