### ISSUE TITLE
RedProtect via MySQL - regions markers disappearing

### ISSUE THREAD

**Issue by krzxsiek** [webbukkit/dynmap#2066]
Spigot Minecraft: 1.11.2
Dynmap: 2.4 [filetree]
RedProtect: 7.1.2 (b308) [MySQL]

Hello,

I have a problem when I set RedProtect database to MySQL
All region markers are not showing up. Also when I create new region, marker disappear after reloading or restarting server.

Any suggestions?

**Comment by SimonOrJ** [comment]
Do NOT reload when working with dynmap markers.  It's a pain in the a$$.

Restart instead.

#2046
