### ISSUE TITLE
Progress until it works with 1.10.2?

### ISSUE THREAD

**Issue by mrzzarr** [webbukkit/dynmap#2069]
Hello!

I'm sorry if I'm redundant here, but I wonder how long until it works with 1.10.2?

I have a modded world and wish to have a map.

I'm a developer myself and I know that "how long time" sometimes is like asking how long is a rope.

I have not developed any mods myself so I don't know the difference between the Bukkit API for 1.7.10 and 1.10.2, but I know it's massive.

I know that id's of blocks was changed between 1.7.x to 1.8.x.

Best Regards
/ Rasmus

**Comment by wioxjk** [comment]
What is your question about? What should work with 1.10.2?

**Comment by mrzzarr** [comment]
I'm sorry if I formulated the question poorly.

I think I should ask, does DynMap work with Minecraft 1.10.2 with Bukkit API 2185?

Best Regards

**Comment by wioxjk** [comment]
I guess you mean 1.11.2?

**Comment by mrzzarr** [comment]
Quick answer!

No I mean 1.10.2 (I have a HermitPack server).

Best Regards

**Comment by wioxjk** [comment]
Alright!
Do you facing issues when you are deploying dynmap on your server? Dynmap does work with current versions.

**Comment by mrzzarr** [comment]
Thanks!

No I asked as a precaution so that I don't get a mishap on my server.

Is there a tutorial how to install?

Best Regards

**Comment by wioxjk** [comment]
Are you using dynmap today?
You can just put the dynmap.jar file into your "plugin" directory:
https://www.spigotmc.org/resources/dynmap.274/

**Comment by mrzzarr** [comment]
No I have never used it, thanks!

Best Regards

**Comment by SimonOrJ** [comment]
> I have not developed any mods myself so I don't know the difference between the Bukkit API for 1.7.10 and 1.10.2, but I know it's massive.

FYI, all the plugins written using Bukkit/Spigot 1.7.10 API and higher are generally compatible with all future server versions.  Nothing much has changed API-wise except for some additions to the API and deprecations, so the difference between the Bukkit API for 1.7.10 and 1.10.2 *is not massive*.  When in doubt, I always test the plugin with a test server.

**Comment by mrzzarr** [comment]
Thanks for explaining that! :D
