### ISSUE TITLE
Freezes on start

### ISSUE THREAD

**Issue by CitrusFruit** [webbukkit/dynmap#2070]
For some odd reason I cannot get fullrender or updaterender to work, as soon as I start either it says 'Update render starting on world 'World'...; but doesn't actually do anything. I've tried to cancel it and try again but the same problem persists so now I'm stuck with what to do next. Oh and there's no errors in-game or on the console.

**Comment by wioxjk** [comment]
What does the console say when you try do perform at "dynmap cancelrender" there?
