### ISSUE TITLE
SSL and web server setup

### ISSUE THREAD

**Issue by WyRe** [webbukkit/dynmap#2071]
Well, recently I've added a SSL cert to my personal web, hosted in my personal server using Apache2, the point is that the <iframe> wher I've included dynmap (using http://mydomain.dom:8123) has stopped working because of force ssl. 

First I would like to know where could I find documentation to setup dynmap to user SSL, I've been reading articles like this:
https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server
or this:
https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-apache2-under-Debian
(despite of I've got ArchLinux instead Debian)

I cannot get dynmap working through my apache server, I've moved /srv/craftbukkit/plugins/dynmap/web folder to /srv/http/dynmap and modified the settings as you specify in first link but dynmap stop works, also I've to say that my sites is located in /srv/http/mymainwebsite/wordpress and I've created a vhost pointing this folder to assign my domain at main website. Also I've added to my vhost setup FallbackResource to remove index.php from several URI, so I need to add exceptions like /dynmap. 

However I cannot do work dynmap in anyway, it doesn't work with http://publicIP:8123 and doesn't with http://publicIP/dynmap (with exception added) when I've setup through my apache server. 

what do you recommend me to enable ssl in my dynmap? this is my site https://lentium.xyz

Thank you so much.

**Comment by beals1pt0** [comment]
Good luck i have tried everything with no luck  if you figure it out i would love to know how you did it

**Comment by WyRe** [comment]
Well, I've found that link https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-Apache-httpd-under-Arch-Linux which fits better to my requirements. Now ... I would like to know what do you mean with:

"**contents of the `web` directory found in the zip**"

in the sentence:

"Copy the contents of the `web` directory found in the zip to `/srv/http/dynmap/`"

Located in that link, because I don't see any **zip file**, I only have got `/srv/craftbukkit/plugins/dynmap/web` folder what I can copy to /srv/http/dynmap folder or move, because that folder has got a considerable size. I wouldn't like to have got it duplicated.

Thank you so much.

**Comment by SimonOrJ** [comment]
copy `<Server Directory>/plugins/dynmap/web/` over to `/var/www/html/` or whereever the webserver is.  Your /web directory is big because it has a lot of map tiles.  You should move the `<dynmap>/web/tiles/` over to somewhere else first, then do the copying. put the `tiles/` back on the webserver directory.

**Comment by wioxjk** [comment]
My use case:
http://serverfault.com/questions/799012/dynmap-throu-mod-proxy-on-a-external-webserver

You can see it working:
https://mc.selea.se/map

**Comment by WyRe** [comment]
Yes, finally I've opted to use a reverse proxy as workaround; I think your Jetty internal server should support SSL, I'll stay in here, above all in #2049 to watch out the progress with this.

Also I'll accept @SimonOrJ answer as valid, despite off I've don't tested; my tries have been based on move all `/web` directory to my apache folder, so I guess I was wrong not moving back `/tiles` folder; however, I still think that [wiki entry](https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-Apache-httpd-under-Arch-Linux) is so confusing and should be better specified.

Thanks you all.

**Comment by wioxjk** [comment]
@WyRe 
If you feel that the Documentation is unclear or  confusing - you are more then welcome to improve it!
I also think that the ReverseProxy solution should be in the documentation.

Running the dynmap directly on jetty does not really have the security that apache offer (mod_security2, HSTS etc), also installing SSL on jetty is more complicated for most minecraft-server owners today.

**Comment by WyRe** [comment]
@wioxjk dynmap really doesn't need so much security since is not transmitting sensible data through itself, maybe web chat as much but yes, I think the most near solution to this issue is maybe run dynmap using your conventional webserver in order to manage that ssl certs. 

However I think devs could implement any kind of setup parameter tu specify SSL certs to Jetty, maybe that's a lot of work, I guess. 

Anyway thank you for your interest.
