### ISSUE TITLE
Night map is preload by default

### ISSUE THREAD

**Issue by jfernandz** [webbukkit/dynmap#2073]
When I open [my dynmap](https://mcmap.lentium.xyz) in my web browser is first loaded night map, once server time is set the map changes to day or night as appropriate.

Is there someway to setup by default day map? I think that would be more logical. 

Thank you so much.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
