### ISSUE TITLE
Only showing Underground...?

### ISSUE THREAD

**Issue by cm8263** [webbukkit/dynmap#2074]
Hi,

I'm not really sure what has happened here, I tried adding a Texture Pack and I think I have done something wrong.

http://i.christophermoore.website/image.php?di=L2MB

normal-hires:
`version: 0.20
#
# Default template for "Normal" environment worlds (deftemplatesuffix="lhires")
#  Uses the HDMap renderer with view from the SE with the "hires" resolution (16 pixels per block edge)
#
#   This file MAY need to be replaced during an upgrade - rename file to 'custom-normal-hires.txt' if you wish to customize it
#
templates:
  # Template for normal world (HDMap hires)
  normal-hires:
    enabled: true
    # Number of extra zoom-out levels for world (each level is twice as big as the previous one)
    extrazoomout: 2
    #center:
    #  x: 0
    #  y: 64
    #  z: 0
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture-mcr-grid
        lighting: shadows
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "Surface"
        prefix: t
        perspective: iso_SE_30_hires
        shader: stdtexture-mcr-grid
        lighting: shadows
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: cave
        title: "Cave"
        prefix: ct
        perspective: iso_SE_60_lowres
        shader: cave
        lighting: default
        mapzoomin: 3`

shaders:
`#
# This file contains default standard shader definitions.  The contents of this file are replaced and updated
# during upgrades, so new or updated shader definitions should be done in the custom-shaders.txt file
#
shaders:
  # Default shader - used if shader not specified or invalid
  - class: org.dynmap.hdmap.TexturePackHDShader
    name: default
    texturepack: standard

  # Color scheme based shaders
  - class: org.dynmap.hdmap.DefaultHDShader
    name: defaultscheme
    colorscheme: default

  - class: org.dynmap.hdmap.DefaultHDShader
    name: ovocean
    colorscheme: ovocean
   
  - class: org.dynmap.hdmap.DefaultHDShader
    name: flames
    colorscheme: flames

  - class: org.dynmap.hdmap.DefaultHDShader
    name: sk89q
    colorscheme: sk89q
   
  - class: org.dynmap.hdmap.DefaultHDShader
    name: amidst
    biomecolored: biome
    colorscheme: amidst

  # Biome based shaders
  - class: org.dynmap.hdmap.DefaultHDShader
    name: biome
    biomecolored: biome
    
  - class: org.dynmap.hdmap.DefaultHDShader
    name: temperature
    biomecolored: temperature
    
  - class: org.dynmap.hdmap.DefaultHDShader
    name: rainfall
    biomecolored: rainfall
    
  # No transparency default color scheme shader
  - class: org.dynmap.hdmap.DefaultHDShader
    name: no_transparency
    colorscheme: default
    transparency: false
  
  # Cave view shader
  - class: org.dynmap.hdmap.CaveHDShader
    name: cave

  # Cave view shader - only lit caves
  - class: org.dynmap.hdmap.CaveHDShader
    name: lit-cave
    onlyiflit: true

  # Cave view shader - hide various soft blocks
  - class: org.dynmap.hdmap.CaveHDShader
    name: cave-noplants
    hiddenids: [ 6, 17, 18, 31, 32, 37, 38, 39, 40, 50, 55, 78, 81, 83, 86, 99, 100, 103, 104, 105, 111, 115 ]
    
  # Texture pack based shader for standard Minecraft textures
  - class: org.dynmap.hdmap.TexturePackHDShader
    name: stdtexture
    texturepack: soartexfanver.zip

  # Standard texture cave view shader
  - class: org.dynmap.hdmap.TexturePackHDCaveShader
    name: stdtexture-cave
    texturepack: soartexfanver.zip
    max-sky-light: 0
    min-emitted-light: 1
    
  # Texture pack based shader for standard Minecraft textures, without biome-tinted grass/leaves
  - class: org.dynmap.hdmap.TexturePackHDShader
    name: stdtexture-nobiome
    texturepack: soartexfanver.zip
    biomeshaded: false

  # Texture pack based shader for standard Minecraft textures, with grid for region file borders (512x512)
  - class: org.dynmap.hdmap.TexturePackHDShader
    name: stdtexture-mcr-grid
    texturepack: soartexfanver.zip
    grid-scale: 512
    
  # Topological map shader    
  - class: org.dynmap.hdmap.TopoHDShader
    name: topo
    color127: "#FFFFFF"
    color111: "#8B4513"
    color95: "#D2B48C"
    color79: "#FFFF00"
    color63: "#008000"
    color47: "#228B22"
    color31: "#104010"
    color15: "#6B8E23"
    color0: "#696969"
    linecolor: "#000000"
    watercolor: "#0000FF"
    wateralpha: 1.0

  # Topological map shader (spread over 256 height)
  - class: org.dynmap.hdmap.TopoHDShader
    name: topo256
    color255: "#FFFFFF"
    color222: "#8B4513"
    color190: "#D2B48C"
    color158: "#FFFF00"
    color126: "#008000"
    color94: "#228B22"
    color62: "#104010"
    color30: "#6B8E23"
    color0: "#696969"
    linecolor: "#000000"
    watercolor: "#0000FF"
    wateralpha: 1.0

  # Topological map shader (hide plants and other soft features)    
  - class: org.dynmap.hdmap.TopoHDShader
    name: topo-noplants
    color127: "#FFFFFF"
    color111: "#8B4513"
    color95: "#D2B48C"
    color79: "#FFFF00"
    color63: "#008000"
    color47: "#228B22"
    color31: "#104010"
    color15: "#6B8E23"
    color0: "#696969"
    linecolor: "#000000"
    watercolor: "#0000FF"
    wateralpha: 1.0
    hiddenids: [ 6, 17, 18, 31, 32, 37, 38, 39, 40, 50, 55, 78, 81, 83, 86, 99, 100, 103, 104, 105, 111, 115 ]
 
   # Topological map shader (hide plants and other soft features)    
  - class: org.dynmap.hdmap.TopoHDShader
    name: topo256-noplants
    color255: "#FFFFFF"
    color222: "#8B4513"
    color190: "#D2B48C"
    color158: "#FFFF00"
    color126: "#008000"
    color94: "#228B22"
    color62: "#104010"
    color30: "#6B8E23"
    color0: "#696969"
    linecolor: "#000000"
    watercolor: "#0000FF"
    wateralpha: 1.0
    hiddenids: [ 6, 17, 18, 31, 32, 37, 38, 39, 40, 50, 55, 78, 81, 83, 86, 99, 100, 103, 104, 105, 111, 115 ]
 
  # Alternate topological map shader (thanks to TerraNetworkOrg!)
  - class: org.dynmap.hdmap.TopoHDShader
    name: TerraNetworkOrgTopo
    color127: "#4F2101"
    color120: "#8B4513" 
    color108: "#D2B48C"
    color96: "#C99653"
    color84: "#CB9C0B"
    color72: "#B1B62E"
    color60: "#0F8D0F"
    color48: "#14703B"
    color36: "#106343"
    color24: "#0E5347"
    color12: "#939393"
    color0: "#696969"
    linecolor: "#000000"
    watercolor: "#1F1FEA"
    wateralpha: 1.0
    
  # Inhabited time map shader    
  - class: org.dynmap.hdmap.InhabitedHDShader
    name: inhabited
    color10: "#0000FF"
    color30: "#00FFFF"
    color100: "#008000"
    color300: "#FFFF00"
    color1000: "#FF8000"
    color3000: "#FF0000"`

Thanks in advance.

**Comment by cm8263** [comment]
UPDATE:

Getting a new error now - 

`[16:53:23 INFO]: [dynmap] Loading resource pack Soartex_Fanver
[16:53:24 ERROR]: [dynmap] Exception during render job: world=world, map=org.dynmap.hdmap.HDMap@4ad4132
[16:53:24 WARN]: java.lang.ArrayIndexOutOfBoundsException
[16:53:24 WARN]: 	at java.lang.System.arraycopy(Native Method)
[16:53:24 WARN]: 	at org.dynmap.hdmap.TexturePack.copySubimageFromImage(TexturePack.java:878)
[16:53:24 WARN]: 	at org.dynmap.hdmap.TexturePack.makeShulkerSideImage(TexturePack.java:1074)
[16:53:24 WARN]: 	at org.dynmap.hdmap.TexturePack.patchShulkerImages(TexturePack.java:1104)
[16:53:24 WARN]: 	at org.dynmap.hdmap.TexturePack.processDynamicImage(TexturePack.java:1344)
[16:53:24 WARN]: 	at org.dynmap.hdmap.TexturePack.<init>(TexturePack.java:852)
[16:53:24 WARN]: 	at org.dynmap.hdmap.TexturePack.getTexturePack(TexturePack.java:683)
[16:53:24 WARN]: 	at org.dynmap.hdmap.TexturePackHDShader.getTexturePack(TexturePackHDShader.java:57)
[16:53:24 WARN]: 	at org.dynmap.hdmap.TexturePackHDShader.access$000(TexturePackHDShader.java:22)
[16:53:24 WARN]: 	at org.dynmap.hdmap.TexturePackHDShader$ShaderState.<init>(TexturePackHDShader.java:128)
[16:53:24 WARN]: 	at org.dynmap.hdmap.TexturePackHDShader.getStateInstance(TexturePackHDShader.java:323)
[16:53:24 WARN]: 	at org.dynmap.hdmap.HDMapManager.getShaderStateForTile(HDMapManager.java:136)
[16:53:24 WARN]: 	at org.dynmap.hdmap.IsoHDPerspective.render(IsoHDPerspective.java:1088)
[16:53:24 WARN]: 	at org.dynmap.hdmap.HDMapTile.render(HDMapTile.java:79)
[16:53:24 WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:708)
[16:53:24 WARN]: 	at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:641)
[16:53:24 WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:190)
[16:53:24 WARN]: 	at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206)
[16:53:24 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:53:24 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:53:24 WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[16:53:24 WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[16:53:24 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[16:53:24 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[16:53:24 WARN]: 	at java.lang.Thread.run(Thread.java:745)
`

**Comment by wioxjk** [comment]
Does look like that dynmap does not like that resourcepack.

**Comment by cm8263** [comment]
Well I need it. Does anyone have a fix?

**Comment by SimonOrJ** [comment]
The exception seems to be caused by malformed or unchecked code for the texture of shulker boxes.

Sidenote/tip:  put *multiline* code between three tick marks. e.g.

> \`\`\`yaml (or any programming language if (markup) code, yaml in the dynmap configuration case)
> [multiline code here]
> \`\`\`

This will make codes, Java exception dumps, and configurations easier to read)

**Comment by wioxjk** [comment]
@SimonOrJ 
So in other words, the problem is with the resourcepack and not dynmap? right?

**Comment by SimonOrJ** [comment]
The exception @cm8263 posted contains
```
...
at org.dynmap.hdmap.TexturePack.copySubimageFromImage(TexturePack.java:878)
at org.dynmap.hdmap.TexturePack.makeShulkerSideImage(TexturePack.java:1074)
...
```
which implies there is a problem with the Shulker Box side or "sub-image" rendering implementation.

However, there's a chance something bigger was miscoded that causes the entire texture pack to not render the world properly.

**Comment by cm8263** [comment]
Ok, and the solution is?

I can't replace the pack before you say that.

**Comment by cm8263** [comment]
Ok, found a fix.

Delete all the Shulker Textures, worked like a charm.

**Comment by SimonOrJ** [comment]
so I guess the problem roots from trying to render Shulker Boxes.  Removing Shulker texture really isn't a final solution since other texture packs can may be affected as well, but if it works for you, I guess it works ¯\\_(ツ)_/¯

**Comment by SimonOrJ** [comment]
Just noticed this is pretty much a duplicate of #2067.

**Comment by FrozenBeard** [comment]
The "workaround" Never worked for me using multiple Custom resource packs, it would always render the grass black, but render leaves fine.
Using the new 2.5 and an OLD 1.10 Dokucraft Resource pack, it starts rendering some blocks black.
http://i.imgur.com/ahZcaqn.png
And then I removed the shulker boxes manually form the 1.11 Dokucraft Texture pack and did a full render, and it renders all the grass black.
http://i.imgur.com/Vo3Rb6e.png
