### ISSUE TITLE
dynmap with Biomes o' plenty?

### ISSUE THREAD

**Issue by nate2014jatc** [webbukkit/dynmap#2077]
not sure if this is a thing, google isn't any help at all.

If it's not, can we put in a feature request?

**Comment by alexschrod** [comment]
See #1392, #1955, etc. It's a common, recurring problem.

**Comment by nate2014jatc** [comment]
So, to clarify;
Broken 2013, fixed with new alpha build in 2013.
Broken 2016, fixed again with a new build in 2016.
Broken 2017, await potential fix?

I'll also try the latest build from the mikeprimm.com buildsite.
Currently looking like [Dynmap-HEAD-forge-1.11.jar](http://mikeprimm.com/dynmap/builds/DynmapForge/Dynmap-HEAD-forge-1.11.jar) or [Dynmap-2.4-forge-1.11.jar](http://mikeprimm.com/dynmap/builds/DynmapForge/Dynmap-2.4-forge-1.11.jar)

**Comment by alexschrod** [comment]
I mean, I just listed two examples; if you search the issues for this project, you can find several more.

**Comment by nate2014jatc** [comment]
What's the primary difference between the two versions?

I don't see anything in the main descriptions to indicate what's what.

**Comment by Hexawolf** [comment]
Broken today on 1.12.2, shows black zones.

**Comment by FedUpWith-Tech** [comment]
See #2262
