### ISSUE TITLE
Config errors cause further reloads to fail

### ISSUE THREAD

**Issue by TheBrain0110** [webbukkit/dynmap#2080]
If Dynmap is running, you can change the configs and issue a `/dynmap reload` command. Great for testing new settings. But if you test something invalid, the reload will fail due to broken config, and then any further commands are ignored with `Dynmap failed to initialize properly: commands not available`.

Which makes sense for most commands, but it also means you're unable to fix the config and reload again to make it work without restarting the whole server.

Can you hardcode the `reload` command to always be available?

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
