### ISSUE TITLE
Block IDs >4096 not supported

### ISSUE THREAD

**Issue by TheBrain0110** [webbukkit/dynmap#2081]
I was trying to use the block-id-alias as a quick and dirty way of rendering Biomes o Plenty blocks (ie, map silty grass to minecraft grass, crag rock to stone, etc), but my entries weren't having any effect:

```
block-id-alias:
#    "14": 1
#    "15": 1
#    "16": 1
    # Biomes o Plenty basic terrain support
     "5096" : 2
     "5097" : 3
     "5101" : 1
     "5102" : 168
     "5103" : 12
     "5104" : 79
     "5105" : 49
     "5106" : 159
     "5107" : 87
```

So I went poking around the code, and found in MapManager.java:
```
    public void setBlockIDAlias(int id, int newid) {
        if ((id > 0) && (id < 4096) && (newid >= 0) && (newid < 4096)) {
            blockidalias[id] = (short)newid;
        }
```

Clearly modern (especially modded) minecraft versions use block IDs >4096, in the case of my pack BoP being in the 5000s.

I'll probably patch that check and build my own, but I don't know what other places in the code will need changing as well, so sending a PR won't be very useful.

Ideally the whole block ID handling would be changed to handle named IDs (minecraft:dirt, biomesoplenty:grass, etc), and possibly metadata values as well. But that, just like supporting the new json custom renderer, is a much bigger project to take on. So for now the easiest fix is just allow block IDs >4096 in aliases, and we can work with that.

**Comment by TheBrain0110** [comment]
So I finally got around to setting up my environment and compiling a custom build. I'm not sure what the actual new block ID limit is, so at first I tried replacing all instances of 4096 in DynmapCore with 40960, but that crashed on startup with an array out of bounds error, so I settled on 8192 which seems good enough.

But it still doesn't seem to have any effect, since none of my aliased blocks are rendering. And I'm not really in a position right now to learn the codebase deep enough to try any more fundamental fixes.

**Comment by SimonOrJ** [comment]
It is possible the block numbering uses `short` for block id.  Unsigned `short` has maximum value of 32767, and that might explain why 40960 failed.

**Comment by rautamiekka** [comment]
Why have such a limit anyway ? Since you certainly can exceed 4096, and even reach 8192 with a really heavy mod pack, it should be set to be essentially limitless; even if it's kept as an integer due to programming limitations, 32-bit unsigned int will go long way, and I don't need to say that much about 64-bit unsigned int.

**Comment by TheBrain0110** [comment]
Hey, it works!
Turns out I was looking at the *item* IDs when looking at the Biomes o Plenty blocks to alias, which are different from the block IDs. Once I found the correct ones, they rendered properly.

As it turns out, item IDs can be arbitrarily large, but block IDs are in fact still limited to 4096 by default. But I ended up going over that limit with a few decorative building mods that add tons of block IDs, so there's also a handy coremod called Not Enough IDs that ups the block limit as well (to 65536 I believe). Point being, this patch may not in fact be necessary by default for most people, but there are cases where you might need block IDs >4096. In fact, here's how my new and correct aliases look:

```
     #biomesoplenty:grass, natura:colored_grass : minecraft:grass
     "872" : 2
     "4105" : 2
     #biomesoplenty:dirt : minecraft:dirt
     "873" : 3
     #biomesoplenty:grass_path : minecraft:grass_path
     "874" : 208
     #biomesoplenty:farmland_0, biomesoplenty:farmland_1 : minecraft:farmland
     "875" : 60
     "876" : 60
     #biomesoplenty:stone : minecraft:stone
     "877" : 1
     #biomesoplenty:crag_rock : minecraft:mossy_cobblestone
     "878" : 48
     #biomesoplenty:dried_sand, biomesoplenty:sand (Quicksand) : minecraft:sand
     "879" : 12
     "996" : 12
     #biomesoplenty:hard_ice : minecraft:packed_ice
     "880" : 174
     #biomesoplenty:ash_block : minecraft:obsidian
     "881" : 49
     #biomesoplenty:mud : minecraft:stained_hardened_clay
     "882" : 159
     #biomesoplenty:flesh : minecraft:netherrack
     "883" : 87
     #biomesoplenty:log_X, natura:overworld_logs : minecraft:log, minecraft:log2
     "896" : 17
     "897" : 17
     "898" : 17
     "899" : 17
     "900" : 17
     "4110" : 162
     "4111" : 162
     "4112" : 162
     #biomesoplenty:leaves_X, natura:overworld_leaves : minecraft:leaves, minecraft:leaves2
     "901" : 18
     "902" : 18
     "903" : 18
     "904" : 18
     "905" : 18
     "906" : 18
     "907" : 18
     "4113" : 161
     "4114" : 161
     "4115" : 161
     #biomesoplenty:planks_0 : minecraft:planks
     "908" : 5
     #biomesoplenty:sapling_X, natura:overworld_sapling : minecraft:sapling
     "983" : 6
     "984" : 6
     "985" : 6
     "4116" : 6
     "4117" : 6
     "4118" : 6
     #biomesoplenty:plant_X : minecraft:tallgrass
     "986" : 31
     "987" : 31
     #biomesoplenty:double_plant : minecraft:double_plant
     "988" : 175
     #natura:barley_crop, natura:cotton_crop : minecraft:wheat
     "4136" : 59
     "4137" : 59
     #biomesoplenty:mushroom : minecraft:brown_mushroom
     "989" : 39
     #biomesoplenty:flower_X, natura:bluebells_flower : minecraft:yellow_flower, minecraft:red_flower
     "990" : 37
     "991" : 38
     "4119" : 37
     #biomesoplenty:flower_vine, ivy, tree_moss : minecraft:vine
     "992" : 106
     "993" : 106
     "994" : 106
     #biomesoplenty:hot_spring_water : minecraft:water
     "1000": 9    
     #natura:clouds : minecraft:air
     "4104" : 0
```

**Comment by mikeprimm** [comment]
Block IDs are 12 bits - function of Anvil format, not anything I control, so until MC revs that format to allow more than 12 bits, block ID numbers are limited to 4095.  If it ever DOES change, we'll handle it just fine :)
