### ISSUE TITLE
An internal error occured while attemping to peform this command

### ISSUE THREAD

**Issue by AndreSantoz** [webbukkit/dynmap#2083]
I'm on 1.7.10 with a modpack, running the jar file: thermos-1.7.10-1614.58 and I have tried dynmapforge 1.7.10, dynmap 2.4,2.1,2.0 and it still won't work. D: Please help.

**Comment by SimonOrJ** [comment]
You have given absolutely no information on what you tried to do that led to an internal error, and the issue title is extremely general.  Please add details.
