### ISSUE TITLE
XSS Vulnerablity

### ISSUE THREAD

**Issue by connection-lost** [webbukkit/dynmap#2088]
player.setDisplayName("<script>alert("hi~");</script>");

**Comment by wioxjk** [comment]
I dont see why fixing this is necessary

**Comment by connection-lost** [comment]
When player is able to create custom markers.

**Comment by SimonOrJ** [comment]
Fixing this is **necessary**.  It is a security vulnerability.  HTML should be sanitized after all.

**Comment by wioxjk** [comment]
@connection-lost 
That is more like a feature ;)

@SimonOrJ 
Yes, it is a vulnerability. I must also admit that I completely forgot that dynmap can be configured to require authentication (something that I have never used). In that case it is not a waste of time fixing this.
Totally agree that code should be correct.

Otherwhise, I can't see why this is a really dangerous thing in this case - yet.

**Comment by connection-lost** [comment]
Not considering whether "it is okay for server admin to xss attack a player".

But sometimes a player can change their name, or create a custom marker to show on dynmap. Say I am a bad player and create a marker called "My Awesome Shop<script>window.location.href='phishingsite.net';</script>". Then everyone else will be redirected to that website.

**Comment by wioxjk** [comment]
@connection-lost 
Excellent point!

**Comment by mikeprimm** [comment]
Should be fixed in today's dev builds for 2.6 and 3.0
