### ISSUE TITLE
spigot tripwires not activating

### ISSUE THREAD

**Issue by thepapanoob** [webbukkit/dynmap#2089]
Hello,

whenever i enable dynmap on my Spigot server (its the only plugin i have) tripwires no longer activate and they dont fall of if i remove the block they sit on! they used to work fine but randomly started at some point. whenever i remove dynmap it works fine but as soon as i activate it it starts doing it...

i pretty much run default config but with json file update. The folders have correct permissions and the logs dont print any errors. TPS is always at 20.

it seems like dynmap has a eventlistener that prevents it from being activated.

Any help would be apreciated :)
Thank you!

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
