### ISSUE TITLE
DynMap lines vanish immediately after page reload

### ISSUE THREAD

**Issue by TheRealNate** [webbukkit/dynmap#2091]
So I have created quite a few lines already, but with this one line I am trying to create:

I create the line, it shows up, reload the page immediately, gone.

I tried putting it in a brand new set, it showed up again, then when I reloaded the page, gone.

I'm using the Latest DynMap on Latest Spigot.

**Comment by TheRealNate** [comment]
The new set has disappeared as well. If I try to recreate the line/set with same ID/name it says "already exists"

**Comment by SimonOrJ** [comment]
Have you used `/dynmap reload`?  It's known to mess with Dynmap marker file (#2046),

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
