### ISSUE TITLE
(1.11.2) Chat Register : nothing happen

### ISSUE THREAD

**Issue by MamylaPuce** [webbukkit/dynmap#2095]
Hello all, sorry for my bad english : i'm french...

I have a problem which I cannot resolve : i have the good things in Configuration.txt but when i get the registration code in order to register with my ID and my password, nothing happen when i clic on "Register", absolutely nothing...

Same way for my friends when i obtain their code with /dynmap webregister "player-ID" for each of them. They put their ID, they choose a password and put the right code on Registration Code and NOTHING HAPPEN... no wrong message, no fail, no error xxx... juste : NOTHING

I... really don't know what is the problem... i have tried to reset all and start again with fresh Configuration.txt, i can see my map, i can do renders and all works fine except the login and register... same way : nothing happen

Is there's anyone who has already met this problem ? I cannot find a solution on the web.

**Comment by SimonOrJ** [comment]
What do you mean by "good things" in your configuration?  How is the web side of dynmap set up?  Does it use internal web server or external web server?

**Comment by MamylaPuce** [comment]
That is my Configuration.txt : [configuration.txt](https://github.com/webbukkit/dynmap/files/1025158/configuration.txt)

it's external server i think because I reserved a port on my "BoxToPlay" pannel for my Dynmap... internal is when you host the Dynmap on "localhost" right ? I think that everything is written well in the Configuration.txt file (that's what i wanted to say).

One of my friend (Computing Professional) think that's it could be a "php" problem and we did not still solve the problem...

**Comment by SimonOrJ** [comment]
Based on your configuration, you're using internal webserver, which means it may be an issue with the plugin itself.  It should not have anything to do with PHP.

How do you run your minecraft instance?  Does it have write permission to the `plugins/dynmap/` directory?

**Comment by MamylaPuce** [comment]
Mmm... no, there's no file called "permisson" in any folder while i can use /dynmap webregister "player_ID", and i do not have a "plugin" folder either, when i launch the server for the first time after putting "Dynmap...jar" into "Mods" folder, it write a "Dynmap" folder at the same level of all others files and folders of the server. We payed for it so it's not hosted on my PC or one of my friends...

It's a Forge server : **minecraft_server.1.11.2.jar** 
with : **forge-1.11.2-13.20.0.2294-universal.jar**

I use Filezilla when i need to modify or add some files (like Configuration.txt from Dynmap folder for example) into the server and i have a user pannel on : **_https://www.boxtoplay.com/panel_** where i can run or stop the server, use the console, modify configuration, manage the whitelist...etc. (and so many things...).

You think that I have make an error in the configuration.txt file ?

**Comment by smmmadden** [comment]
okay, there are two things - 1. Dynmap is built for Bukkit/Spigot/Paper Spigot, etc. servers, not Forge.  Forge is a modded server and client and it requires Forge Plugins for [Forge Servers](https://www.bisecthosting.com/clients/knowledgebase/52/How-to-add-plugins-to-a-Forge-server.html).  Take a look here for the list of available [plugins, texture packs, mod packs, etc](https://mods.curse.com/mc-mods/minecraft/category/forge).

For Spigot Servers, you explicitly create a plugins folder where the server gets created.  Once it starts up, it creates another folder (in most cases) with the configuration files.

**Comment by MamylaPuce** [comment]
That's it, and the instal. of Dynmap with Forge is not a problem or the problem for me because it works very fine for us except the login/register part. I know that Forge is different from Bukkit/Spigot and others Plugins. With Forge, we need to put Dynmap...jar into the Mods folder created by Forge, that's how Dynmap can works with Forge. After that, a Dynmap folder is created, after rebooting the server, with all files you need like Configuration.txt and Words.txt for example.

- We followed well the procedure on the official link : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft

- We configure our Dynmap to have a map on the good port : it works very well and i was able to launch _/dynmap fullrender world_ to have the perspective we wanted => it works very well. I think there is no mistake in the installation of Dynmap with Forge on our server.

- But : we can't use the Login/Register panel because while we create a registration code with the console or directly in game, nothing happen when we clic on the "Register" button and that's my problem for our server... we want to protect the chat and all our Dynmap web access with this tool but it seems that it could provide from a PHP issue.

Actually, i can't do nothing more because i'm not at home, i will ask the "BoxtoPlay" admins. on what php version they have on the PC which hosted our server, and... we will see after... i don't know what but... we will see... it will be another step towards a possible success way ^^

**Comment by kjstanfield** [comment]
I would like to add I am having the same issue, the register button does not appear to be responding.
Using the chrome dev tools I noticed a POST 500 (Server Error) as I attempt to click the register button.
The map works perfectly fine, only having issues with the registration process.

Error with my server IP redacted.
`jquery-1.11.0.js?_=${project.version}-${BUILD_NUMBER}:9666 POST  [IP REDACTED]  500 (Server Error)`

I also tested this on my phone using data instead of wifi to rule out any network issues on my end and another browser.  Is there something in the config I am missing to allow this post to go through?

Hosting FTB Beyond version 1.7.0
Forge version 12.18.2.2281
MC Version 1.10.2

**Comment by rautamiekka** [comment]
@kjstanfield 
> MC Version 1.10.2

!= 1.11.2

**Comment by Codingale** [comment]
I get a 500 error, no stack trace in the Forge 1.12.2 version.

Literally just: `Error: 500`

**Comment by Kraiiii** [comment]
Seems to be happening to me too using dynmap-3.0-beta-1-forge-1.12.2.jar on a dedicated forge server every time I press the register button this message appears in the F12 console:
```
XML Parsing Error: syntax error
Location: http://myserverip:8123/up/register
Line Number 1, Column 1:
```

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
