### ISSUE TITLE
1.12 support built, but no download option?

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#2096]
Hi MikePrimm - thanks for getting the 1.12 update done.  I looked on [Spigot](https://www.spigotmc.org/resources/dynmap.274/) and the [forum pages](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft) for the download, but they both still show v2.4 for 1.11.2.  Can you update the same pages with the newest version?  Thanks!! -Steve

**Comment by sid-engel** [comment]
Any news on this?

**Comment by SimonOrJ** [comment]
It's updated on Saturday. Close?
