### ISSUE TITLE
Dynmap on Spigot 1.12 causes server to shutdown

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#2097]
As per the comment on [Spigot](https://hub.spigotmc.org/jira/browse/SPIGOT-3263), it appears that one of the plugins is shutting down the server and preventing the ability to test the pre-release of 1.12.  Dynmap is used by Minecraft and by Residence Plugin.  Dynmap fails first and then Residence fails due to the dependency.  The plugin owner for Residence is updating that plugin to be more resilient when Dynmap is not available.  The same holds true here, if Dynmap fails to load, it should disable itself and allow the server to continue to start "without it".

**Comment by Steamsing** [comment]
do you mind sending or upload the 1.12 java files to me privately?

**Comment by smmmadden** [comment]
Hopefully @mikeprimm will be able to update the plugin for 1.12 and post the file somewhere for us to download.  Right now, I don't see any way of downloading the built jar file.

**Comment by mikeprimm** [comment]
The current checked in source code for Dynmap should work with 1.12-pre2 - unfortunately, I've got some problems with my private build server that prevented me from doing a proper 'build and deploy' of a formal update.  I'm hoping to get that ironed out in the next day or so.  Worst case, I can post a link to a hand build tonight - not the way I prefer to distribute, but I don't want to hold up folks on 1.12 longer than I can avoid.

**Comment by Steamsing** [comment]
i would love to have the plugin asap cause i love it but take your time

**Comment by smmmadden** [comment]
thank you, would love to get a build asap also since there is a tight dependency on Residence using Dynmap, haven't been able to test either with the pre5 (latest) or pre2 builds.

**Comment by Steamsing** [comment]
@mikeprimm can you upload i that today, it would be great i wanna test it out on 1.12 cause im updating my server to 1.12 pre 5 in a moment :)

**Comment by mikeprimm** [comment]
Here's a link to the current dev build - give it a spin: http://git.westeroscraft.com:8080/view/Dynmap/job/dynmap/lastSuccessfulBuild/artifact/target/dynmap-2.5-SNAPSHOT.jar

**Comment by Rostik02** [comment]
Thank you @mikeprimm. I've tested it on a 1.12-pre5 craftbukkit server and it seems to work :D

**Comment by smmmadden** [comment]
Confirmed mikeprimm, server and residence plugin is much happier now.  Still have a couple other plugins to get fixed before the server stays up long enough to do some testing.  If I find anything, will create an issue for it.  Thanks again!!

**Comment by Steamsing** [comment]
Much better it works atleast right now :)

**Comment by ardentcrest** [comment]
above link not working

**Comment by mikeprimm** [comment]
Finally got my formal build server fixed yesterday - current dev build link is now http://www.dynmap.us/builds/dynmap/dynmap-2.5-SNAPSHOT.jar
