### ISSUE TITLE
Invalid CTM Method: ctm_compact

### ISSUE THREAD

**Issue by lastsamurai26** [webbukkit/dynmap#2098]
I try to use the Ressource Pack PureBDCraft for Version 1.11.2 64x
but when i starting the Rendering i get this messege 

Spigot Version 1.11.2
Dynmap 2.4

[22:38:41] [Dynmap Render Thread/INFO]: [dynmap] No matching method: assets/minecraft/mcpatcher/ctm/hard_materials/clay/magenta/hardened_clay_stained_magenta.properties
[22:38:41] [Dynmap Render Thread/INFO]: [dynmap] Invalid CTM Method: ctm_compact

how can i fix this ?

**Comment by dan-nkl** [comment]
Have got the same problem.

**Comment by fusionmc-evilscoop** [comment]
me too

**Comment by MadHalaster** [comment]
Also wondering about this. 
Still seeing this issue with Dynmap-3.0-alpha-1-forge-1.12.2.jar and PureBDCraft for version 1.12.2 64x.

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.

**Comment by ChrissW-R1** [comment]
We still have this error in version 1.18.1 (build 216) of PaperMC.

For example:
`assets/minecraft/optifine/ctm/0verlay/08_clay/clay.properties`

Full log: https://pastebin.com/f9cMS06L

**Comment by JurgenKuyper** [comment]
> We still have this error in version 1.18.1 (build 216) of PaperMC.
> 
> For example: `assets/minecraft/optifine/ctm/0verlay/08_clay/clay.properties`
> 
> Full log: https://pastebin.com/f9cMS06L

only ctm is supported, not ctm_compact
