### ISSUE TITLE
[Feature Request] Support for BungeeCord Servers/Maps

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#2100]
@mikeprimm  - I know you're only keeping the maintenance of the plugin updated, but I've recently switched to using BungeeCord Server and putting all my worlds under it.  This as you know is the proxy for the rest of the worlds by keeping them behind the proxy server (BungeeCord) and restricting direct access.  Unfortunately, it still opens the server for intrusion because of the dynmap port on the spigot server itself which means they are still getting hit directly.  What I'm proposing is a change that a Dynmap plugin be installed on BungeeCord plugin folder (not the mc spigot servers), that have pointers to the mc server dynmap ports.  So BC would be the proxy to display the maps for each world in that plugin.

I'm not expecting any rendering be done thru bungee, only a web page that allows for a drop down list of the worlds registered by BungeeCord that I can switch between them and get the generated maps from the back end servers.  So basically what this guy did for the same setup, but the download link isn't working.
http://maps.yeahwh.at/ 

Thanks for considering taking this to a new level. :-)
Steve

**Comment by mikeprimm** [comment]
If security/load is a concern, have you considered using the external server support (that is, set up Apache on the public side with the PHP scripts, and use the MySQL database storage option for the map data?).  The main concern is, as you indicated, the rendering needs to be done where the world data lives, but the web interface needs to be able to get to the results of the rendering - so, ideally, put the DB server near the web server and have the dynmaps push their images to it.

I'd like to do something with BungeeCord at some point, but it'll likely still involve something like this sort of pattern (even if it meant pushing the images to the proxy server as files, versus as database content).

**Comment by smmmadden** [comment]
Switching to MySQL as the storage option could be done, but the amount of time to re-generate 7 worlds with one of them being 10,000,000 blocks (1/3 size of max), it's just not feasible given how long it takes to create them.  Since bungee already knows of the spigot servers under it, I would conceivably put the dynmap (or API) plugin at Bungee's plugin folder and then have it communicate with the spigot servers and their /plugins/dynmap folders to render the map.  

This would still keep the security from accessing the spigot servers directly as bungee would be the proxy and the drop down on that page would look similar to the map here http://maps.yeahwh.at has.  Switching the map in the top right would pull in the map from that server.  Does that make more sense in what I'm trying to achieve?  It feels more natural that the proxy server would handle any communications to the server by default.  This falls under the umbrella due to the servers being hidden behind bungee.

**Comment by rautamiekka** [comment]
Surely Dynmap could migrate the tiles between storage formats through a command such as `/dynmap movetiles {mysql|files|...}` (originally had it `migratetiles`) when rendering is stopped ? That'd beat re-rendering.

**Comment by JohnB17** [comment]
Is this going to be added?

**Comment by rautamiekka** [comment]
Hasn't checked, but Waterfall (better yet Travertine) might be needed to achieve something like this.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
