### ISSUE TITLE
"protected-player-info" Bug

### ISSUE THREAD

**Issue by freak-dk** [webbukkit/dynmap#2103]
Hello

The bug described in the post below happens to me aswell, 
https://github.com/webbukkit/dynmap/issues/1930

Hopefully this is something you would look into fixing :-) 

This sums it up,
"After deeper testing, it turned out that the protected-player-info attribute is buggy. If the player has the right permission and logged in, he/she can see all the players on the server. However, after removing the '
dynmap.playermarkers.seeall permission he/she cannot see anyone, not even his/her own position."

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
