### ISSUE TITLE
Dynmap folder will not appear

### ISSUE THREAD

**Issue by Wontedyew15** [webbukkit/dynmap#2107]
So i have had dynmap before and was able to run it fine. But i removed it after that due to reasons, and now when i tried to add it back, it wont create a folder for the config, and when i type /dynmap it comes up with an internal error. Any extra info needed i can send.

**Comment by smmmadden** [comment]
start by telling us what version are you trying to get working, what server you are running it on and version, exactly how did you "add it back" and try to get it working?  Did you add all the permissions, if so what did you add and what permission system are you using (and version).

There are numerous combinations and everyone's can be unique - so without more detail, it'll be impossible to help.

**Comment by Wontedyew15** [comment]
hmm sorry update, i downgraded to a previous version of craftbukkit, because i think the new update isn't compatable, but i got dynmap working fine, and have fully renderised my server, but when it comes to accessing my map i am having trouble, i am adding all the info in the right formation but it wont allow me to go to my website, any help on doing so ?

**Comment by smmmadden** [comment]
check your firewall's and make sure you are using the port in the configuration.txt file (towards the bottom).  The default is 8123, so you'll need to either open it up so you can access it from your computer or change it to an available port.  There's a ton of details in the WIKI page, so check it out if you get stuck.

**Comment by Wontedyew15** [comment]
Ok so i tried to do this:
I did http://213.32.24.96:12849
the first part is my ip adress, and i removed the end part after the : i then added the webserver port i added which is 12849, after doing that it never worked, please help haha

**Comment by smmmadden** [comment]
This is exactly what I mentioned.  Update your firewall rules to allow external access to that IP & Port.

This site can’t be reached
213.32.24.96 refused to connect.
Search Google for 213 12849
ERR_CONNECTION_REFUSED
