### ISSUE TITLE
Layer priority not correctly working

### ISSUE THREAD

**Issue by MicleBrick** [webbukkit/dynmap#2108]
I have a system with territory area markers and chunk area markers. The layer priority on the chunk area markers is set to 0, and the territory area markers 100. However, it shows the name of the territory area marker when clicking on chunk area marker!

![image](https://user-images.githubusercontent.com/6323125/27097839-98017b8c-5043-11e7-8edf-7f3bd94995e6.png)

I would greatly appreciate any way to fix this.

**Comment by SimonOrJ** [comment]
0 is the highest (top) priority.

**Comment by Miclebrick** [comment]
Yes, the settlement chunks are set to 0 priority (highest) and the big territory is set to 100

**Comment by SimonOrJ** [comment]
Whoops, I might've read your original issue wrong.

This is a weird issue.  The inner part of rectangle volume should not be clickable when it has no height.

**Comment by Miclebrick** [comment]
Height? That's a thing?

**Comment by Miclebrick** [comment]
Finally found a solution - if I put them in the same marker set, it works!

**Comment by Miclebrick** [comment]
The most obvious solution seems to be making the territory area marker a polyline marker, but that would mean that you can't see the name of the territory at all

**Comment by Miclebrick** [comment]
I'm still having this problem...

**Comment by Miclebrick** [comment]
Bump? Is that a thing on github?

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
