### ISSUE TITLE
Does dynmap v2.5 Fix the Shulker-box bug with custom texture packs?

### ISSUE THREAD

**Issue by FrozenBeard** [webbukkit/dynmap#2109]
Reference https://github.com/webbukkit/dynmap/issues/2067

**Comment by SimonOrJ** [comment]
[It doesn't seem so--not yet](https://github.com/webbukkit/DynmapCore/blob/master/src/main/java/org/dynmap/hdmap/TexturePack.java)

**Comment by FrozenBeard** [comment]
@SimonOrJ How do we get it fixed? its been forever and its a glaring bug.
I updated to the 1.12 version of Dynmap and it started rendering black blocks on some textures.
i cant update my Texture pack because of this bug.

**Comment by foldedpaper** [comment]
I have been experiencing the same issue with the "Faithful 32x" texture pack. In Dynmap version 2.4, the workaround mentioned in #2074 (i.e. simply deleting shulker box textures from the texture pack) removed the "SubimageFromImage" console exceptions, and allowed renders to work as normal.

However, with Dynmap 2.5, the workaround no longer works. The console still throws Index out of Bounds exceptions on attempting to "copySubimageFromImage". What's more, it seems that these exceptions now prevent renders from completing--I am seeing the dynmap queue fill with pending tile renders, which only complete if I manually issue a render command.

**Comment by FrozenBeard** [comment]
The "workaround" from #2074 Never worked for me using multiple Custom resource packs, it would always render the grass black, but render leaves fine. 
Using the new 2.5 and an OLD 1.10 Dokucraft Resource pack, it starts rendering some blocks black.
http://i.imgur.com/ahZcaqn.png
And then I removed the shulker boxes manually form the 1.11 Dokucraft Texture pack and did a full render, and it renders all the grass black.
http://i.imgur.com/Vo3Rb6e.png

**Comment by mikeprimm** [comment]
Just coded fix in latest 2.6 builds - please give a try, and report if it helps

**Comment by foldedpaper** [comment]
Not to distract too much from @FrozenBeard , but my issue with the shulker-box bug is resolved with today's 2.6-SNAPSHOT. I no longer receive Index out of Bounds exceptions with custom texture pack, and renders with the custom pack now trigger and update as expected. 

Hopefully @FrozenBeard sees a fix for his bugs too.

Thanks for the support, @mikeprimm

**Comment by CloakedAlien** [comment]
dynmap-2.6-SNAPSHOT.jar solved the shulker box crash for us too!

**Comment by FrozenBeard** [comment]
It did fix my issue too :)

**Comment by BrainStone** [comment]
@mikeprimm Yes, that fixes the error

**Comment by BBoyJD10** [comment]
Where can i get snapshot from

**Comment by FrozenBeard** [comment]
@BBoyJD10 http://dynmap.us/builds/dynmap/ use 2.6 from here, I haven't used any of the later builds, I have no idea what's changed in those.
