### ISSUE TITLE
Spigot 1.12 / Dynmap 2.5 doesn't render player skins

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#2111]
After upgrading to Spigot 1.12 and Dynmap 2.5 builds, the players on the map are showing the default "steve" skin and not the actual player skins.  Also running BungeeCord Server 1.12 so Spigot Servers are set for offline in case that helps.
![image](https://user-images.githubusercontent.com/10309346/27263021-44b84d16-5430-11e7-844a-89978647729d.png)

showplayerfaces: true
type: playermarkers
showplayerfaces: true
showplayerhealth: true
**If true, show player body too (only valid if showplayerfaces=true**
showplayerbody: true
**Option to make player faces small - don't use with showplayerhealth**
smallplayerfaces: false
**Optional - make player faces layer hidden by default**
hidebydefault: false
skin-url: "https://www.minecraftskinstealer.com/player.php?user=%player%"

The image above is myself so if you replace %player% with smmmadden it'll show my skin.  Papoo is only the nickname in the server so it may be that we're not passing the actual player name or something changed in 1.12 causing this link to no longer work?

**Comment by Codewow** [comment]
Not sure if you've updated since you posted this, but the latest build as of today is working with skins.

**Comment by smmmadden** [comment]
I was looking for the dev build mikeprimm mentioned v2.6 but can't seem to locate the dev builds here.  The current 2.5 build does shows the steve skin, not the actual players.

**Comment by smmmadden** [comment]
I'm now running with BungeeCord 1.12.1 / Spigot 1.12.1 and Dynmap 2.5-Dev201706100405 but still seeing the default skin and have updated the skin check in the configuration.txt file.
# Control loading of player faces (if set to false, skins are never fetched)
fetchskins: true
# Control updating of player faces, once loaded (if faces are being managed by other apps or manually)
refreshskins: true
# Customize URL used for fetching player skins (%player% is macro for name)
#skin-url: "http://s3.amazonaws.com/MinecraftSkins/%player%.png"
skin-url: "https://www.minecraftskinstealer.com/player.php?user=%player%"
I've tried http as well since it redirects to the same url as https, but dynmap is not retrieving it.  The default in the configuration.txt file no longer works - returns an access denied message.

**Comment by TheZenKitteh** [comment]
I'm having this issue as well on 1.12.1 with Dynmap 2.5
Player heads are the default Steve.

**Comment by smmmadden** [comment]
@mikeprimm - any idea when 3.0 will be available or a fix for the skins in 2.x ?  I'll be upgrading our servers shortly to 1.12.2 so would love to say it works there. :-)

**Comment by FireController1847** [comment]
Can report I'm having this issue. Using skins like..
```
 skin-url: "https://minotar.net/skin/%player%.png" 
```
...should work, but it does not.

**Comment by ScuroK** [comment]
I have the same issue. Can someone fix this please?
im using spigot 1.12.2 and dynmap 2.5

I think spigot recently changed they way skulls are handled. maybe thats why?

**Comment by mikeprimm** [comment]
Mojang just retired the legacy skin API - the latest dev builds of v2.6-alpha-2 or v3.0-alpha-1 have updated code (as of earlier tonight) to handle this.

**Comment by Cookies98** [comment]
Did someone fix it ???

**Comment by FireController1847** [comment]
@Cookies98 According to @mikeprimm, it is fixed in the latest dev builds of v2.6-alpha-2 or v3.0-alpha-1.

**Comment by smmmadden** [comment]
there was another posting about this, but yes it is fixed for the Forge and Bukkit development builds.  I've confirmed both - the solution was to comment out or remove the skins-url so that the code uses the supported API to get the skins along with the new build FireController1847 stated.  In otherwords, don't hard code any url to get skins, let the plugin/mod take care of it.

**Comment by Cookies98** [comment]
@FireController1847 Where can i download the v2.6-alpha-2 build for spigot ?

**Comment by smmmadden** [comment]
The duplicate issue is here - it was at the top of the list and the urls for both are listed.  https://github.com/webbukkit/dynmap/issues/2199

**Comment by Cookies98** [comment]
@smmmadden Thank you ^^

**Comment by mikeprimm** [comment]
Latest Spigot/Bukkit builds are here - http://dynmap.us/builds/dynmap/
Latest Forge builds are here - http://dynmap.us/builds/DynmapForge/
