### ISSUE TITLE
Add all SVG stroke options available in DynMap line dmarker (especially dashArray)

### ISSUE THREAD

**Issue by rysson** [webbukkit/dynmap#2113]
Hi, 
First, awesome work!

There are attributes in /dmarker 
  * color - outline color (#RRGGBB format)
  * opacity - Opacity of the outline strokes (0.0 = transparent, 1.0 = solid)
  * weight - Stroke weight of outline (0=minimum, higher=thicker)

SVG can support a few more:
  * stroke-dasharray
  * stroke-linecap
  * stroke-linejoin

The best is got them all, but only *stroke-dasharray* is supported now by web/js/leaflet.js:
```
web/js/leaflet.js:4095:      this._path.setAttribute('stroke-dasharray', this.options.dashArray);
```

When I type: 
```
/dmarker updateline id:m2 set:dashArray:"5 15"
[10:28:04] [Server thread/INFO]: Updated line id:m2 (M2)
```
there is no error, but nothing is changed in markers.yml or on web view.

The same with `/dmarker updateline id:m2 set:dashArray:"5,15"`  (leaflet.js:4382 converts "A,B" → "A B").

Please, add support for **dashArray** (or more) in dmarker line (and dmarker area).

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
