### ISSUE TITLE
Change sea level in DynMap Forge 

### ISSUE THREAD

**Issue by rysson** [webbukkit/dynmap#2114]
It will be nice to change sea level by DynMap command.
Workaround is to stop server edit forgeworlds.yml and start it again.

If DymMap could read sea level from MC, it will be the best.

**Comment by rysson** [comment]
I've found another repo: https://github.com/webbukkit/DynmapForge/
Should I report issues there or here?

Sorry, but all links (forum, course) point to https://github.com/webbukkit/dynmap/

**Comment by mikeprimm** [comment]
I'll add this for versions that support the getSeaLevel() API.

**Comment by mikeprimm** [comment]
Change completed for 1.9.4, 1.10.2, 1.11.2, and 1.12
