### ISSUE TITLE
Dynmap 2.5 disables some permissions

### ISSUE THREAD

**Issue by SlimeDog** [webbukkit/dynmap#2115]
Spigot 1.12 latest or 1.11.2
dynmap 2.5
scores of other up-to-date 1.12-supporting plugins

With dynmap enabled, I lose some op permissions, for example: _testfor_ and _summon_. With the same configuration, except _dynmap.jar_ removed, all is correct. In-game message is:
> I'm sorry, but you do not have permission to perform this command. Please contact server administrator...​

No log/console errors, or other indications that anything is amiss.

Any ideas?

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.

**Comment by SlimeDog** [comment]
No idea. The ticket is over 3 years old. We haven't re-installed dynmap since then. :(

**Comment by FedUpWith-Tech** [comment]
Yeah, the github fell in disrepair when the plugin dev retired. I'm maintaining the github now and the original dev is psuedo maintaining the plugin till someone can take it over but due to the size of the repo its near impossible
