### ISSUE TITLE
Dynmap with XAMPP

### ISSUE THREAD

**Issue by Slasherss1** [webbukkit/dynmap#2117]
How to create web server like: http://localhost/map

**Comment by Psy-Virus** [comment]
Sry bud, that's the wrong place for this question!
It is an issue tracker not a forum.
There are tons and tons of tutorials you can find on Youtube or using Google.
And if you search for a simple and ready to use solution, give it up.

You also should consider to read the Dynmap documentation.

I guess this Issue can be closed.

:-)

**Comment by JanSzumotalski** [comment]
I try to search in google, but... NOPE.

**Comment by SimonOrJ** [comment]
https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server

**Comment by Slasherss1** [comment]
Timed out (It's 2019 already)
