### ISSUE TITLE
 [dynmap] Failed to start WebServer on address 0.0.0:8123 : Address already in use

### ISSUE THREAD

**Issue by PieIsLyfe** [webbukkit/dynmap#2119]
Please help! I'm on mac and I can't get dynamo to work. There is only one other error: [dynmap] Error reading plugins/dynmap/markers.yml

**Comment by SimonOrJ** [comment]
As it says in your title, you already have an application using port 8123.  If you have separate instance of dynmap, try changing the port in configuration.txt.

Your second error happened because your markers.yml file is misformated or corrupt.  Fix it or delete it.
