### ISSUE TITLE
1.12 black concrete doesn't render when there isn't a block underneath.

### ISSUE THREAD

**Issue by mibby** [webbukkit/dynmap#2120]
Dynmap 2.6-SNAPSHOT-Dev201707061526
Spigot 1.12

As long there is a block placed underneath, black concrete shows up on the map. When nothing is underneath, black concrete isn´t visible on the live map.

**Comment by Grimdari** [comment]
I can confirm this with my map.  Black concrete blocks do not render on the map if there is no other block beneath.

**Comment by Pangamma** [comment]
Confirmed for me as well.

**Comment by Pangamma** [comment]
But for me, black concrete just renders as white no matter what.

**Comment by TheRealB** [comment]
Same here, black concrete doesnt get rendered

**Comment by saturnux** [comment]
i can't use block-id-alias. it's a bloc with subname.

**Comment by Pangamma** [comment]
Doesn't matter what height it is, it doesn't get rendered for me. Please fix? This is affecting my build style. I have to use coal blocks instead of black concrete to get things to show up properly on dynmap.

**Comment by FlatoutDude** [comment]
this also happens for me, i have a world that uses black concrete for a large majority of my builds (roadways) and they don't render correctly.

**Comment by broyuken** [comment]
I can confirm that I have the same issue. Is this actually being looked at? This issue has been open for coming up on a year now. Is dynmap dead?

**Comment by Pangamma** [comment]
How has this not been fixed yet?... Yeah, I'm also wondering if dynmap is dead.

**Comment by FedUpWith-Tech** [comment]
Sorry to necro this thread- I'm not sure when but this issue is not present in the latest version of dynmap. I'm closing this thread but someone please re-open it if they can provide an example of this behavior on any of the latest dynmap versions.
