### ISSUE TITLE
Dynmap on Ubuntu with Apache2

### ISSUE THREAD

**Issue by MineTim** [webbukkit/dynmap#2122]
Hey, I have a question for the Dynmap-Plugin.

I have a Ubuntu-Server (without apache2) and I want to use that plugin in web without :8123. In the wiki, I read a way how-to, but this thread is very old and it does not work. Can you help me that I am able to use that feature?

Greetings
Tim

**Comment by smmmadden** [comment]
the configuration.txt file has the default port of 8123, but you can change it to whatever you like and whatever is "open" to your players.  Change the port, update your firewall and restart the minecraft server.

**Comment by SimonOrJ** [comment]
The wiki page for "Setting up without internal server" is mostly still relevant, except for the latest version, you can use latest version of PHP and other small stuff.

**Comment by MinecraftTim123** [comment]
And how can set the URL to <MyIP/dynmap>

Cause in this wiki, I saw that this is possible (with debitan/ubuntu)

**Comment by MinecraftTim123** [comment]
The Link: "https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-apache2-under-Debian"

**Comment by SimonOrJ** [comment]
I know you can use proxy on Nginx... and I am more fluent in nginx, so I'm not sure if I'll be able to help you.

One thing you can do is use [this guide in setting up without internal webserver](https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server), but if you want to use the internal web server, you can also search up how to do web proxy using apache on Google.

Or, use nginx instead. Your choice.  Someone well-documented the Nginx proxy usage (with internal web server) over on issue #2025.

**Comment by MinecraftTim123** [comment]
But as i can see, there are errors while using, is there a way how to use Dynmap without issues?

**Comment by SimonOrJ** [comment]
> there are errors while using

I can't know what errors you're getting unless you show it.  Screenshot it or something.

**Comment by MinecraftTim123** [comment]
No, I meant the problems in the issue #2025



 But I will try that!

**Comment by MinecraftTim123** [comment]
Do I have to copy that file into /etc/apache2/sites-avaible?

**Comment by MinecraftTim123** [comment]
Please help :C

**Comment by smmmadden** [comment]
help with what?  You've referenced #2025 and there are links on how to configure Ubuntu above. No software is bug free, it is up to us to qualify the issue and report it so that it can be prioritized and fixed in an upcoming build.

How far did you get? What errors are you seeing? Did you try to get the default dynmap to work first?  This would either show there is a config issue or problem with the website setup.  No one here can see your screens or know how far you've gotten, so unless you provide screenshots and/or logfile or console messages, there isn't anything anyone can do.

**Comment by MinecraftTim123** [comment]
Hey there, sorry for my delayed answer! :/

I started configuring and at https://localhost:8123, I saw the whole dynmap, everythings works fine.

I tryed to put the script into the /etc/apache2/sites-avaible -folder, but apache2 doesn't restart ("apace2.service is not activated" or so) and after deleting and restarting works everything fine - but without the dynmap-file, so I was not able to test.

Can somebody help me?

**Comment by MinecraftTim123** [comment]
As this moment, I put the web-folder from dynmap into the /var/www/html. But now I don't have a clue what I have to do...


Please help me! :C

**Comment by InsaneJ** [comment]
You can use Apache2 as a proxy server to host a dynmap on a subdomain. This is what we have been doing for years and it works without any problems.

Create a DNS record for a subdomain for your website. Something like: dynmap.yourDomain.com. If you do not know how to do this, ask your hosting provider.
Create an Apache2 configuration file for the new subdomain. If you use Ubuntu 16.04 such files are probably located in /etc/apache2/sites-enabled. Call the file something like: dynmap.yourDomain.com
In this file put something like this:
```
<VirtualHost *:80>
ProxyPreserveHost On
ServerName dynmap.yourDomain.com
ProxyPass / http://serverIP:8123/
ProxyPassReverse / http://serverIP:8123/
</VirtualHost>
```
Now keep in mind that this uses HTTP and is not secure. You should really use HTTPS. If you need a certificate I recommend using a free one from the LetsEncrypt.org project.

You will need to change the values in the Apache2 configuration file to match your server. This means using the correct serverIP and the correct domain name.

In the Dynamp configuration you will need to add the IP of your web server. This may be the same as your Minecraft server, but it can also be a different machine with a different IP. You need to add the web server's IP address in Dynmap's configuration.txt under trusted-proxies. Something like this:
```
trusted-proxies:
  - "123.123.123.1"
```
Then restart Minecraft and restart your Apache2 web server. Wait for the server to start. Then after a few minutes you should be able to access your Dynamp on http://dynmap.yourDomain.com

Good luck!

**Comment by WyRe** [comment]
@InsaneJ 

You also need to enable these modules

```
sudo a2enmod proxy
sudo a2enmod proxy_http
sudo a2enmod proxy_balancer
```

And your site config file `yourdomain.dom.config` file must be placed in `/etc/apache2/sites-available`, then you are gonna be able to load it using

`sudo a2ensite yourdomain.dom.config`

That will create a symlink to `/etc/apache2/sites-enabled`

This is going to reverse forward the dynmap port (8321 usually) to 80 http port. So you don't need to forward the dynmap port in your router; you just need to forward 80 http port. Then apache2 will do the work. It will forward internally the incoming petitions throught 80 http port to 8321 dynmap's port.

**Comment by Psy-Virus** [comment]
I wonder why nobody is mentioning a name-based virtual host with DocumentRoot right to the `dynmap/web` files. This way you can disable the built in web server and save some ram and CPU...

**Comment by Psy-Virus** [comment]
And also, this thread is over a year old... I'll close this... XD

Further discussion on https://forums.dynmap.us please....

You trapped me Mr. @WyRe :D

**Comment by WyRe** [comment]
> I wonder why nobody is mentioning a name-based virtual host with DocumentRoot right to the `dynmap/web` files. This way you can disable the built in web server and save some ram and CPU...

I like much more to manage ssl certs with my web server, right now I've not ssl enabled, but in a future I think it will be easier than using Jetty.


@Psy-Virus 

Yeah, pretty old issue, but I think always is fine document your solutions, now it is in here documented forever xddd. My minecraft server have been down for some time ago and I've switched it on about a few weeks ago in a different machine.

**Comment by InsaneJ** [comment]
@Psy-Virus I don't use name-based virtual hosts with DocumentRoot in the Dynmap directory because my web servers and my Minecraft servers are not on the same (virtual) machines. You could setup something with NFS/Samba/iSCSI or whatever, but using a proxy is much easier to implement and works just as well.

**Comment by Psy-Virus** [comment]
@InsaneJ, ofc for this setup it makes sense. But for a completely local setup it would be a waste of resources obviously^^

**Comment by WyRe** [comment]
> I wonder why nobody is mentioning a name-based virtual host with DocumentRoot right to the `dynmap/web` files. This way you can disable the built in web server and save some ram and CPU...

@Psy-Virus I had a few issues ago with Apache managing dynmap, that's why I prefer built-in Jetty server. Mainly regarding to dynmap-minecraft auth system.

**Comment by wioxjk** [comment]
> > I wonder why nobody is mentioning a name-based virtual host with DocumentRoot right to the `dynmap/web` files. This way you can disable the built in web server and save some ram and CPU...
> 
> @Psy-Virus I had a few issues ago with Apache managing dynmap, that's why I prefer built-in Jetty server. Mainly regarding to dynmap-minecraft auth system.

https://serverfault.com/questions/799012/dynmap-through-mod-proxy-on-a-external-webserver
