### ISSUE TITLE
Players can use Webchat only when logged in to the minecraft server

### ISSUE THREAD

**Issue by afroman84** [webbukkit/dynmap#2127]
Hello,
i have set `webchat-permissions: true`, and the permission check works, blocking chat lines when players do not inherit the dynmap.webchat, but for some strange reason players can enter lines that successfully publish on the bukkit chat only when they are actually connected to the minecraft server.

configuration.txt (here: https://hastebin.com/ilobabelix.vbs)

I wrote here because i cannot find anything to work around and make the chat work for users not logged in to the minecraft server.
The plugin version is: Dynmap version: core=2.5-Dev201706100401, plugin=2.5-Dev201706100405
The server version is: Paper version git-Paper-1152 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

thank you for help

**Comment by afroman84** [comment]
Please help, the webchat is NOT WORKING until player is online logged into the server. Any workaround or should i give up with the webchat? Once upon a time it worked, or do i remember wrong?

**Comment by jwshields** [comment]
If a player logs in, then logs out of the game, can they send messages from webchat?

The important lines are 50-59.
If a player logs into the game, their IP is recorded and the messages they send will be matched against that record; if a player hasn't logged in, or their IP has changed since last logging into the game, the message is ignored. banned players can't chat at all; and in order to chat from the web, you need to login to dynmap (which means creating an account on the server in game with `/dynmap webregister`) and the user needs the chat permission in order to be able to send messages.

```
    # (optional) if true, player login IDs will be used for web chat when their IPs match
    use-player-login-ip: true
    # (optional) if use-player-login-ip is true, setting this to true will cause chat messages not matching a known player IP to be ignored
    require-player-login-ip: true
    # (optional) block player login IDs that are banned from chatting
    block-banned-player-chat: true
    # Require login for web-to-server chat (requires login-enabled: true)
    webchat-requires-login: true
    # If set to true, users must have dynmap.webchat permission in order to chat
    webchat-permissions: true
```


Also lines 333-336.
Users can view the map, but are not required to login; even when not logged in, a chat bar is still presented.
```
# Enable login support
login-enabled: true
# Require login to access website (requires login-enabled: true)
login-required: false
```

**Comment by afroman84** [comment]
> If a player logs in, then logs out of the game, can they send messages from webchat?

actually no, he can't. When logged in he can use the webchat, when logged out, he can't.

these are 50-59 lines from configuration.txt on my server:
`    # (optional) if true, player login IDs will be used for web chat when their IPs match
    use-player-login-ip: true
    # (optional) if use-player-login-ip is true, setting this to true will cause chat messages not matching a known player IP to be ignored
    require-player-login-ip: true
    # (optional) block player login IDs that are banned from chatting
    block-banned-player-chat: true
    # Require login for web-to-server chat (requires login-enabled: true)
    webchat-requires-login: true
    # If set to true, users must have dynmap.webchat permission in order to chat
    webchat-permissions: true
`
these are 333-336:
`# Enable login support
login-enabled: true
# Require login to access website (requires login-enabled: true)
login-required: false
`
i don't know what is causing this dysfunction, i have tried several times to solve but had no success.
Of course players have the dynmap.webchat permission and created their webchat account using /dynmap webregister

**Comment by SimonOrJ** [comment]
I've started to experience this issue when I migrated away from PermissionsEx to LuckPerms.  Players can chat from the web only when they're also logged into the game.

It seems that it's the permissions plugin that's causing the chat to not work.  What permissions plugin are you using?

**Comment by afroman84** [comment]
I am using luckperms! Maybe we have found the source of the problem, so let’s contact the developer for a check on this

**Comment by ReaperCrewGreen** [comment]
This appears to be happening again in DynMap 3 beta 3 (1.13.2)

I am also running luckperms for permissions.

@lucko @mikeprimm
