### ISSUE TITLE
Dynmap jQuery not defined?

### ISSUE THREAD

**Issue by dannysmc95** [webbukkit/dynmap#2128]
I am getting an error regarding Dynmap where it does not render anything; saying jQuery is not defined. If you go here: https://map.kaos-network.com/

It was working, but now it doesn't not made any config changes, so little confused?

Thanks,
Danny

**Comment by altrisi** [comment]
It's working fine for me (in that website)

**Comment by q220** [comment]
Working fine for me as well, no errors in Google Chrome developer console (F11). Does your browser block javascript?

**Comment by SimonOrJ** [comment]
@dannysmc95, if this issue is solved, consider closing it. Thank you!
