### ISSUE TITLE
Is there a way to recover a map from dynmap?

### ISSUE THREAD

**Issue by Zughy** [webbukkit/dynmap#2129]
via .hash files or I dunno

**Comment by smmmadden** [comment]
not sure what you mean by recover a map from dynmap.  Typically speaking, if there is a problem with the map not getting rendered, you just execute the command to update the render or render it in part/full.  Short of that, backing up the rendered files could be restored if it stays current but I don't see any value in that considering what its used for.

**Comment by Zughy** [comment]
No, what I meant is, if I have stored in the plugin saving folder some map renders (I guess the .hash files), is there a way to recover the actual map, (the chunks, the .mca files) if it doesn't exist anymore in the server?

**Comment by rautamiekka** [comment]
**Reconstruct the Minecraft map from Dynmap's data after losing the actual map**, to put it in other way.

**Comment by altrisi** [comment]
I think dynmap isn't saving the blocks in the chunk (because they are teorically saved in the world folder) so I think it isn't possible.

**Comment by SimonOrJ** [comment]
What you mean by "map" is Minecraft world.  The term "map" automatically refers to the drawing of a geographical area, which is what Dynmap generates.  That is where the confusion seems to happen in the first reply.

As @altrisi says, there is no way to generate chunks from dynmap maps.  The .hash files are generated by Dynmap and just for Dynmap to keep track of rendering the map tiles (if I understand it correctly).  Rest of the files are image tiles, so the best you can do is put blocks down by using the map tile as your reference.

Do a backup of your Minecraft worlds regularly.  It's important to do that more than you think.

**Comment by rautamiekka** [comment]
^ I think reconstruction of the surface from Dynmap's pics would be possible, but it's loads of work. It may even be more processing than the creation of those pics.

**Comment by Zughy** [comment]
Thank you everyone for your patience :)
@SimonOrJ backups are important indeed
@rautamiekka so could it be possible or developers need to work a lot to implement it? Anyway, mine was just a curiosity, as we solved our problem (my team and I) with a few backups

**Comment by rautamiekka** [comment]
^ It'd be **_a lot_** of trial and error to implement and the CPU usage it'll take to process the pics back into a functional world surface might be bad.

**Comment by altrisi** [comment]
Please if it have been resolved close this issue. There are a lot of done but not closed issues in this repository and it can be confusing to developers (and also makes new people see like there are lots of issues). Thanks
