### ISSUE TITLE
404 Errors loading tiles

### ISSUE THREAD

**Issue by itsgatto** [webbukkit/dynmap#2130]
Hello, i'm having the next issue :/

I have done a clean install of Dynmap, then i followed the guide to run it without the internal webserver, this is essential because i don't have too much resources available on the machine, my webserver is apache2 under CentOS with PHP 5.6. Everything works good, i can see some parts of the map (still rendering), and i can see the players online and everything, but if you open the dev mode of chrome you can see a lot (hundreds of them indeed) of 404 errors like:

`GET https://dynmap.itsgatto.com/tiles/world/flat/-8_1/zzzzz_-256_32.png?1501298966435 404 ()`

The permissions and file ownership is correct, it generates the tiles but the web keeps trying to load tiles that don't exist yet, it hurts the peformance as i know.

**To clarify, this doesn't happen with the integrated web server**, so i guess that isn't normal :/

I would appreciate any type of help, i really want to use the map in that way, the map url is: https://dynmap.itsgatto.com/ if you want to take a look, thanks!

**Comment by simonchow96** [comment]
Hello. I am now experiencing the same issue, but I can see your dynmap is working great now. What should I do to solve the problem?

Thanks a lot!

**Comment by itsgatto** [comment]
Hello, in your configuration.txt of the Dynmap plugin folder you need to find the next section:
`# URL for client configuration (only need to be tailored for proxies or other non-standard configurations)`

Then you need to make it look like this:
`# URL for client configuration (only need to be tailored for proxies or other non-standard configurations)
url:
    # configuration URL
    configuration: "standalone/configuration.php"
    # update URL
    update: "standalone/update.php?world={world}&ts={timestamp}"
    # sendmessage URL
    sendmessage: "standalone/sendmessage.php"
    # login URL
    login: "standalone/login.php"
    # register URL
    register: "standalone/register.php"
    # tiles base URL
    tiles: "standalone/tiles.php?tile="
    # markers base URL
    markers: "standalone/markers.php?marker="
    `
Update the URL values to these and you should be good after restarting the server. :)

**Comment by simonchow96** [comment]
Yeah Problem Solved! Many thanks to you @itsgatto !
