### ISSUE TITLE
[2.4-forge-1.11.2] Mod has direct reference System.exit() This is not allowed - server warning

### ISSUE THREAD

**Issue by bhi-elliot** [webbukkit/dynmap#2131]
Thank you for this great mod!
Not sure if it's a big issue or if there is anything that can be done about it, but thought I'd report the following server warning upon loading Dynmap on a Forge/Sponge server.

Hope it helps!

```
[Server thread/WARN] [FML]: =============================================================
[Server thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[Server thread/WARN] [FML]: Offender: org/dynmap/jetty/server/ShutdownMonitor$ShutdownMonitorThread.run()V
[Server thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[Server thread/WARN] [FML]: =============================================================
```

**Comment by KovuTheHusky** [comment]
"That's harmless BS from Forge - they try to get cute and detect calls to System.exit() for some reason, and the web server library we use (Jetty) happens to include the call in its bytes (even though we would never call the corresponding code)."

https://github.com/webbukkit/DynmapForge/issues/53#issuecomment-179452809

**Comment by CplPibald** [comment]
Broke and re-placed the door and no crash now.  The only thing out of the ordinary is that when I first walked up to it, the bottom half was stone texture, but quickly changed to stone brick when I got close.

Thanks for your work on this!
