### ISSUE TITLE
can't go to the web?

### ISSUE THREAD

**Issue by hypersmc** [webbukkit/dynmap#2134]
my problem is that i can't go to the web like http://138.201.33.17:9939/ wont do anything.
![image](https://user-images.githubusercontent.com/16544278/29703914-f1423930-8977-11e7-9782-44fd0ff37c4c.png)

**Comment by smmmadden** [comment]
did you update your firewall rules to allow traffic to hit that IP on that port?

**Comment by q220** [comment]
ERR: Connection refused. Definitely firewall problem here.

**Comment by jwshields** [comment]
Please close this issue if you've solved the issue or are in no longer need of assistance; or provide an update & close it.
