### ISSUE TITLE
protected-player-info: true, even if we are logged we can't see ourself

### ISSUE THREAD

**Issue by Benjamin-Loison** [webbukkit/dynmap#2135]
Hello,

I am using DynMap 2.2 with a 1.7.10 Thermos server.
This is not the last version but the changelog doesn't seem to add any patch to my bug.

The bug is about no displaying the players (and not myself too when I am logged) when I switch on true "protected-player-info". I have the same problem as in this post: https://github.com/webbukkit/dynmap/issues/1930
No more information on the web...

Futhermore which branch is used for compatible 1.7.10 Thermos/Cauldron/MCPC+ version (because I found the tag 1.7 but I know that 1.7.2 mod for instance is not compatible with 1.7.10) ?
Because I am readdy to edit the code and compile DynMap to patch this bug if needed.

EDIT: PS: Here is all my configuration file: https://pastebin.com/dfx9aqWn

Thank you

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
