### ISSUE TITLE
Black blocks

### ISSUE THREAD

**Issue by Huggbeesw** [webbukkit/dynmap#2136]
So, I just rendered a map and there's just black blocks in one location, you can see for yourself here: http://91.211.247.88:8123 look in worldX btw. Anyone know how can I fix it?

**Comment by q220** [comment]
Can't see because the server is refusing to establish a connection. However black boxes can be caused because the chunk is not generated yet. You could try a dynmap radiusrender or fullrender to see if the area updates.
