### ISSUE TITLE
disable grabbing

### ISSUE THREAD

**Issue by Wqrld** [webbukkit/dynmap#2138]
is there a way to disable the moving of the camera and if possible just have a region in which the camera can move?

**Comment by FedUpWith-Tech** [comment]
This isn't possible, there are some workarounds if you write a custom website but I'm going to close this due to age and assume it is no longer relevant

**Comment by Wqrld** [comment]
> This isn't possible, there are some workarounds if you write a custom website but I'm going to close this due to age and assume it is no longer relevant

no longer relevant for me, but i'd expect other users could still use this for smaller maps
