### ISSUE TITLE
Dynmap -> straight one block black lines

### ISSUE THREAD

**Issue by mehlelnei** [webbukkit/dynmap#2139]
Pictures: [https://imgur.com/a/BoTLd](https://imgur.com/a/BoTLd)

if l zoom in - out, do updaterender(fullrender before), night/day, different texture pack(tried with default too), even if l reset the entire dynmap the problem is still keeps raping. (ofc this black lines are not shown on the server)

We run EpicWorldGenerator(8) with WordBorder (fully generated 10K x 10K map), we tried vanillia map aswell.

Server version: now Paper, tried Spigot too. (1.12.1)
Dynmap version: 2.5

Sorry if l had some grammar mistakes, English is not my main language.

**Comment by jwshields** [comment]
Do they come up if you try a radiusrender at a point where the block isn't appearing?
Are any errors/logs coming up in the console when those areas attempt to get rendered?

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
