### ISSUE TITLE
ProjectRed problem with rendering

### ISSUE THREAD

**Issue by LynSisCZ** [webbukkit/dynmap#2140]
Good day, I used DynmapModScaper for render data, but no effect on the map is still black instead.

https://img.gamepro.cloud/lynsis/1506388096.png

**Comment by Psy-Virus** [comment]
Guess u're using ProjectRed for 1.10.2.

**Comment by Psy-Virus** [comment]
Guess u're using ProjectRed for 1.10.2.

The ModScraper doesn't support 1.10.2; as far as I know.

But the devs are working on a Dynmap version with better mod support. At least for 1.12.
And maybe there will be a backport for 1.10.2.

**Comment by DvnBthlo** [comment]
Sorry i use a ProjectRed 1.7.10

**Comment by Psy-Virus** [comment]
Ah, okay.

**Comment by Psy-Virus** [comment]
Ah, okay.

Take a look at this:
https://github.com/webbukkit/dynmap/issues/1872

**Comment by Psy-Virus** [comment]
Just saw, the links in the last post are dead
These are my configs for Project Red. They're not perfect but work okay enough.^^
[ProjRed_Core-models.txt](https://github.com/webbukkit/dynmap/files/1333224/ProjRed_Core-models.txt)
[ProjRed_Core-texture.txt](https://github.com/webbukkit/dynmap/files/1333227/ProjRed_Core-texture.txt)
[ProjRed_Exploration-models.txt](https://github.com/webbukkit/dynmap/files/1333228/ProjRed_Exploration-models.txt)
[ProjRed_Exploration-texture.txt](https://github.com/webbukkit/dynmap/files/1333225/ProjRed_Exploration-texture.txt)
[ProjRed_Illumination-texture.txt](https://github.com/webbukkit/dynmap/files/1333226/ProjRed_Illumination-texture.txt)

**Comment by DvnBthlo** [comment]
Ok i try it ;)
