### ISSUE TITLE
Don't work dynmap since 2 days.

### ISSUE THREAD

**Issue by MineServidorCraft** [webbukkit/dynmap#2141]
My dynmap isn't work. Dynmap worked yesterday, buy today said that: 

https://proxy.spigotmc.org/43efa6fdda2df1adc12992f75344cfd3c3294afe?url=https%3A%2F%2Fi.imgur.com%2FTv2jYF7.png

https://proxy.spigotmc.org/b66dee8a59c4802e54e9353267eb093b5b5a6cdd?url=https%3A%2F%2Fi.imgur.com%2FTqKXp08.png

**Comment by SimonOrJ** [comment]
what happened to the `./plugins/dynmap/web/index.html` file?  Looks like someone may have deleted it on accident.

**Comment by jwshields** [comment]
Please close this issue if you are no longer in need of assistance.
