### ISSUE TITLE
Trimming Dynmap tiles

### ISSUE THREAD

**Issue by InsaneJ** [webbukkit/dynmap#2142]
Is there a way to trim Dynmap tiles outside of a given area (rectangle, circle)?
I couldn't find any information on how to do this. If there is no way to do the following, perhaps this could become a feature request?

On the HappyDiggers TerraFirmaCraft server we have a world border enabled and use Dynamp. This works well. At some point the world border was disabled and some people wandered off. Not a big deal. The only down side to this is that there are now a bunch of chunks outside of the world border area which look ugly.

The chunks outside of the world border have been removed through the world border plugin. However the tiles still exist in Dynmap. Is there a way to trim Dynmap tiles outside of a given area? In our case that would be the coordinates of the world border plus it's padded area. If that is not yet possible, would you consider adding this feature?

Perhaps something like:
```
/dynmap trim rectangle x1,z1 x2,z2
/dynmap trim circle x,z <radius in blocks>
```

If you're wondering why I don't just purge the tiles and render all of them again. Our TerraFirmaCraft world is 100.000 by 30.000 blocks which would take quite a while to render again.

**Comment by FedUpWith-Tech** [comment]
This is possible using dmap and editing the worlds.txt file- I'm going to close this and assuming this is no longer relevant, please open a new issue if you still need help
