### ISSUE TITLE
[3.0] NullPointerException during "Building terrain"

### ISSUE THREAD

**Issue by miiichael** [webbukkit/dynmap#2146]
I realise this is still early days for 3.0, but on the off chance that this is actually useful to you...

Crash occurred while attempting to open an existing single player world (created before dynmap was added). Minecraft 1.12.2, Forge 14.23.0.2512, Dynmap-3.0-alpha-1, DynmapBlockScan-3.0-alpha-1, and a (deliberately unconventional) collection of mods, including optifine.

[crash-2017-10-21_13.22.00-server.txt](https://github.com/webbukkit/dynmap/files/1403818/crash-2017-10-21_13.22.00-server.txt)

I can dig up more logs if required.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
