### ISSUE TITLE
Domain doesn't work

### ISSUE THREAD

**Issue by FrankHeijden** [webbukkit/dynmap#2147]
`http://91.121.145.119:8200` works, but `https://maps.aquacraft.eu/survival/` doesn't seem to work for me. On my mobile phone `https://maps.aquacraft.eu/survival/` works, on my desktop not. 

If i use a tro browser or proxysite.com it seems to work for me.

Im using Chrome on my desktop as default browser.
Is this issue dynmap related? 

Thanks,
Frank

**Comment by FrankHeijden** [comment]
Issue solved, cloudfare was interrupting the service. Thanks anyways!

**Comment by Kainzo** [comment]
I'd like to know how you resolved this through cloudflare, please.

**Comment by FrankHeijden** [comment]
I don’t know for sure anymore, but I remember I had issues with cloudflare’s pagespeed improvements.

**Comment by Kainzo** [comment]
ill try that, thanks....
