### ISSUE TITLE
Can we make water not transparent, or change the height (hide water temples)

### ISSUE THREAD

**Issue by falazar** [webbukkit/dynmap#2151]
We are running a large scale CivWar server, and would like to hide Ocean Monuments from the dynmap, wanted to change the transparency.  Have only found one option so far that works, but changes the map style alot.

Is there a better way to do this?

Thanks!

**Comment by falazar** [comment]
bump

**Comment by falazar** [comment]
Bumps :}

**Comment by jwshields** [comment]
@mikeprimm is the owner of this repo, he might be able to provide some insight.
I also think he accepts pull requests if you make the change to make this happen.

**Comment by mikeprimm** [comment]
Can be done with custom texture pack (since the alpha is used)

**Comment by falazar** [comment]
Not sure how to do that, looking for a solution.
