### ISSUE TITLE
Dynmap spamming "Processing ZoomInOut"

### ISSUE THREAD

**Issue by GeigerCounter** [webbukkit/dynmap#2155]
There's no reason this needs to be logged to console, especially not ever few minutes. Most of my server's logs are these messages. I couldn't find anything in the config on how to disable it. There should be a config option to suppress these messages.

**Comment by jwshields** [comment]
Could you paste a log with a few of those messages? 
My server, and most others I've seen don't have that being constantly spammed.
Has anybody ran a command to cause dynmap to do something?

**Comment by jwshields** [comment]
If you no longer need assistance, please close this issue.
