### ISSUE TITLE
bug with texture

### ISSUE THREAD

**Issue by achencraft** [webbukkit/dynmap#2158]
![dynmap](https://user-images.githubusercontent.com/25326403/32677377-79fdd52c-c65e-11e7-9e0c-cb56b470347c.jpg)

Hello,
I discovered this evening a problem with the map generation on Dynmap.

everything worked well during 2 years, but suddenly this evening, black areas appear when I build ...

I don't do anything in config or other files :/

I need to have a correct web map :'(

What can i do ? It's the latest dynmap version on spigot.

**Comment by jwshields** [comment]
Could you try a radiusrender from in game to attempt to rerender that area?

**Comment by achencraft** [comment]
yes no pb
you can see results here => http://strasbourg.achencraft.fr/

**Comment by achencraft** [comment]
All the area become black and my ressource pack disappear :o

**Comment by jwshields** [comment]
The game should be re-rendering that area if you issued the command, I'm looking at your page now-
What does the console show?

**Comment by achencraft** [comment]
![sans titre 3](https://user-images.githubusercontent.com/25326403/32678840-5ceffde2-c664-11e7-91fe-9b195154e983.jpg)

and the console :


[22:12:49] [Async Chat Thread - #11/INFO]: [strasbourg][Cr?ateur] frimoussedu67 >> test
--
[22:11:12] [Server thread/INFO]: frimoussedu67 issued server command: /dynmap radiusrender 50

**Comment by achencraft** [comment]
[dynmap.txt](https://github.com/webbukkit/dynmap/files/1462790/dynmap.txt)

That all the log durind the command
ProtocolLib maybe ?

**Comment by achencraft** [comment]
I allow myself to relaunch the subject to know if a solution is possible.

Reinstall fully Dynmap would work?

**Comment by jwshields** [comment]
I do not know if a reinstall would work. You could give that a try. But I am not personally well versed in texture packs for Dynmap.

**Comment by achencraft** [comment]
ok I will retry without texture pack

And if there is no result => reinstall

I'll keep you informed

**Comment by achencraft** [comment]
Hey

after reinstalling the plugin
I find that the problem come from my ressource pack

I will search the problem inside

Thanks

**Comment by achencraft** [comment]
ok, I find the problem in the pack

This is the fiveth version of the pack, and I don't know how, but problem of directories' structure


You can see the result here : http://www.strasbourg.achencraft.fr/


Thanks

**Comment by jwshields** [comment]
It looks like the map loads properly now. 
Could you close the issue if it's resolved?

**Comment by achencraft** [comment]
Yes no problem

thanks
