### ISSUE TITLE
Standalone web server no tile

### ISSUE THREAD

**Issue by TheBlueKingLP** [webbukkit/dynmap#2159]
I run the dynmap on a standalone web server on the same machine as the spigot server, but I can't get any tile on the map.

**Comment by jwshields** [comment]
**Please post your config and system information.**
What OS, what web server, what file storage backend, what does your dynmap config look like, what does your web server config look like?
Do you receive any error messages? Have you done any searching on the issue tracker or wiki on documentation here?

**Comment by smmmadden** [comment]
in addition, did you ever run the /dynmap fullrender initially?  Did this ever work or is this a new install?  What version of Dynmap and Spigot are you running with?

**Comment by TheBlueKingLP** [comment]
OS: Ubuntu 16.04.3LTS
Web Server: Apache2 Latest
Storage: MySQL
dynmap config: https://pastebin.com/s98Z3GY7 (For safety reason, domain name, server name and password has been removed from the file)
Web Server Config: https://pastebin.com/qMUJ97gg ( * = something don't want others to know)
I ran the full render a few time
Dynmap version: core=2.5-Dev201706100401, plugin=2.5-Dev201706100405
The server is running CraftBukkit version git-Spigot-d21162c-61e0c69 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by jwshields** [comment]
Dynmap config,
line 32: remove `?useSSL=False` from the string
line 309 can be removed/commented
line 312, does the minecraft user have permissions to write to the /var/www/ directory?

Apache conf;
who is apache running as?
And, I'm assuming PHP works and is configured properly for it?

**Comment by jwshields** [comment]
Actually, looking at the source, line 32 of dynmap conf _should_ be okay, but remove it just to test.
Can you verify the db is getting written to?

**Comment by TheBlueKingLP** [comment]
32:dynmap can access the MySQL server, and has read/write permission
why remove line 309?
312: yes, it has permission

**Comment by jwshields** [comment]
Can you verify data is being written to the db?
309 is for the filestore; not used when you're using the DB iirc
can you verify if you can run a command as the MC user, like `touch` `mkdir` etc in the map folder in www?

**Comment by TheBlueKingLP** [comment]
MC user?

**Comment by jwshields** [comment]
What user is Minecraft running as?
What user is apache running as?
Are they the same?
If you log in/su as the minecraft user, can you write to the apache www content directory?

**Comment by TheBlueKingLP** [comment]
minecraft and apache are running as root and www-data

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
