### ISSUE TITLE
[Dynmap] Player faces arnt showing

### ISSUE THREAD

**Issue by Legobobgo** [webbukkit/dynmap#2164]
I have encountered and Issue where player faces aren't showing up on the map. I've looked through the configs and can't seem to find what the issue its.

**Comment by jwshields** [comment]
**Please post your configs.**
What OS, what versions? Spigot/Bukkit? Are you using the internal webserver or an external one?
Can you show us what's happening so that we can replicate it?
You've not provided any info for us to troubleshoot with.

**Comment by jwshields** [comment]
Please close this issue if you no longer need assistance.
