### ISSUE TITLE
dynmap texture issue

### ISSUE THREAD

**Issue by FrankHeijden** [webbukkit/dynmap#2166]
Hey,

using the `iso_SE_30_hires` perspective cocoa's are displayed like this:

![50a81105944bc82c4372514788bce7fe](https://user-images.githubusercontent.com/22407829/33244647-aa6e8bee-d2fb-11e7-8bc0-a4543dbbd26d.png)

is there a fix for this issue?

**Comment by patchchristensen** [comment]
Dynmap won't load mod textures by default. In 1.7.10 you can use the modscraper to fix this issue. 
Download and instructions here
http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft
