### ISSUE TITLE
Error parsing the config files

### ISSUE THREAD

**Issue by Zeyphre** [webbukkit/dynmap#2167]
When I add the information to link the plugin to my MySQL Database (I only have mysql selected), the configuration.txt file fails to parse "deftemplatesuffix: hires" (I tested this with an edited and unedited configuration.txt in http://yamllint.com/) and it shows the unedited file as correct, but the edited file as incorrect. (The only change with the two is the mySQL Database values)

**Comment by jwshields** [comment]
**Please post your config.**
YAML is super sensitive and needs to use spaces instead of tabs, as well as a bunch of other quirks.

**Comment by jwshields** [comment]
Please close this issue if you no longer need assistance.
