### ISSUE TITLE
Adding markers and areas online

### ISSUE THREAD

**Issue by lifehome** [webbukkit/dynmap#2168]
We are having a city-scale project undergoing, and would like to have districts sliced up. The districts has been sliced on some Photoshop-like software, and we are ready to build things on it. But when comes to dynmap, we see the hassle to add markers and areas from config to textpads, and necessity of copying coordinates from dynmap to somewhere else back and forth.

So I am suggesting that dynmap can allow logged in users, to add markers and areas by clicking on a single spot, or adding areas by selecting multiple point.

**Comment by lifehome** [comment]
Give a bump.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
