### ISSUE TITLE
[Request] Add Label Description feature to wiki

### ISSUE THREAD

**Issue by BrainStone** [webbukkit/dynmap#2170]
While it is very nice that the descriptio feature for labels exists, it is a real bummer that there is no documentatio for it in the wiki and it therefore has become a very obscure feature that barely anyone knows about while it is extremely handy!

**Comment by Reg-Ed** [comment]
If this is what I think it is, it's what i've been looking for.  How do I add descriptions to my markers on the map?

**Comment by Reg-Ed** [comment]
@BrainStone How do you use the description field for markers then?
