### ISSUE TITLE
Storage Drawers Support

### ISSUE THREAD

**Issue by Remanent** [webbukkit/dynmap#2173]
@mikeprimm 
Is there any chance we can get [Storage Drawers](https://minecraft.curseforge.com/projects/storage-drawers) added to dynmap's [supported mod list](https://github.com/webbukkit/dynmap/wiki/Support-for-MinecraftForge-based-mods)?

I looked briefly into adding the models / textures, but i think that's going to be beyond me :(

Thank you for your work on dynmap, i've been using it on a server i host for my friends, and we're looking to add storage drawers to the server.

**Comment by FedUpWith-Tech** [comment]
This is possible now using dynmap-blockscan. If you still need help with this please use that issue tracker
