### ISSUE TITLE
Texture pack not loading. 

### ISSUE THREAD

**Issue by xacrimon** [webbukkit/dynmap#2176]
System: Debian
Server: Spigot 12.2

I made a custom shader and set custom.zip as my texture pack. The uploaded custom.zip which is just renamed soartex fanver to dynmap/texturepacks

When starting a render I get this https://pastebin.com/Zs8yAzbU

**Comment by ExplosG** [comment]
Is this about the malformed shulker thing?

**Comment by RanmaKei** [comment]
Try removing the mcpatcher folder in the texture pack or texture zip.

**Comment by xacrimon** [comment]
Solved, is was a malformed shulker texture
