### ISSUE TITLE
Add webserver info from #1978 to wiki

### ISSUE THREAD

**Issue by TonyGravagno** [webbukkit/dynmap#2177]
There is a wealth of good info in #1978 which should be added into the wiki. I'll take a shot at this as time permits. I just didn't want to see that Q&A ticket closed without preserving the valuable information.

**Comment by jwshields** [comment]
If a ticket is closed, it should still be available/searchable in the project; Just wouldn't show up as an "active" issue.
@mikeprimm has write privileges to this repo. I'm unsure who else does.
I've also proposed a couple of other wiki page updates, but they've not gone through.
#2027 #2026 #2068 #2024

**Comment by TonyGravagno** [comment]
Just coming back to this to check status. It doesn't make much sense to propose changes if they aren't going to get accepted. I'll wait until we see more interaction. Thanks.

**Comment by FedUpWith-Tech** [comment]
Sorry to necro this post- I now have write privileges on the wiki, Some of the proposed pages seem out of date to me but I am in no means an expert. if @jwshields  can update me on what changes he would like made I will gladly update the wiki (I plan to update the wiki as well once I slog through the open issues)
