### ISSUE TITLE
Problem z dynmapą

### ISSUE THREAD

**Issue by BlacckSnsei** [webbukkit/dynmap#2178]
Witam używałem poradnika: https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server

Ktoś może podać mi przykład tego: 
# The path where the web-files are located.
webpath: /path/to/web/server/dynmap/web

Mam osobny host ale nie wiem jak to ma wyglądać co za co odpowiada.

**Comment by user5145** [comment]
I will try to translate to english.

> Hi, I have used this guide [https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server](https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server)
> Please, give me an example of this **The path where the web-files are located**
> webpath: /path/to/web/server/dynmap/web
> I have a second host, but i don't know how to set it up

you have asked for the example, but they are already on wiki page.
for linux/mac

> The path where the tile-files are placed.
> tilespath: /path/to/web/server/dynmap/web/tiles
> The path where the web-files are located.
> webpath: /path/to/web/server/dynmap/web

and windows
> The path where the tile-files are placed.
> tilespath: c:\\path\\to\\web\\server\\dynmap\\web\\tiles
> The path where the web-files are located.
> webpath: c:\\path\\to\\web\\server\\dynmap\\web

here you have a real-life example, maybe it will be more helpful
tilespath: E:\\xampp\\htdocs\\tiles
webpath: E:\\xampp\\htdocs

Summing wiki up you need to comment 4 config lines and uncomment 4, copy everything from spigot/plugins/dynmap/web to folder which is used by your web server (probably htdocs), check permissions, add path to that folder where you have copied dynmap/web conent to plugins/dynmap/configuration.txt and restart your server.
