### ISSUE TITLE
Version 3 available yet?

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#2180]
I recall earlier last year @mikeprimm mentioned there was a dev build version 3 in the works.  Is this still going to be released?  Last version I have is dynmap-2.5.jar from 6/10/2017.  For Forge, I'm using Dynmap-2.6-beta-1-forge.1.12 and both are for Minecraft 1.12.2.

No issue to report, just looking for update on the next big thing in Dynmap. :-)

-Steve

**Comment by mikeprimm** [comment]
I've been really getting my butt kicked with work - that said, I am going to try to get back to working on v3.0 (in particular, the DynmapBlockScan based support for handling most mods automatically.  Sorry for the long delays and slow responses - life does get in the way sometimes :)

**Comment by smmmadden** [comment]
no worries Mike I completely understand. :-)

**Comment by jwshields** [comment]
Life happens! That's fine; thank you for all the work in the first place- you've provided such a valuable tool to the Minecraft community.

**Comment by patchchristensen** [comment]
Mike your awesome and we appreciate your hard work. Look forward to testing that dynmapblockscan for you some more.
