### ISSUE TITLE
Dynmap doesn't create the folder/doesn't work

### ISSUE THREAD

**Issue by adriaface** [webbukkit/dynmap#2184]
I tested it in our webserver and in my personal pc and im getting the same error.
Our server is built with kcauldron + 1.7.10 forge

Console Log:
`ERROR]: Could not load 'plugins\Dynmap-2.3-forge-1.7.10.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml`

How can i fix it? 

Thank you!

Edit: the .jar file is in the plugins folder

**Comment by temotodochi** [comment]
move it in the mods folder.

**Comment by jwshields** [comment]
This issue isn't closed, could you please do that?

**Comment by mikeprimm** [comment]
It's a mod, not a plugin - and if it works on kcauldron, that'd be a pleasant surprise :)
