### ISSUE TITLE
Problem Write File

### ISSUE THREAD

**Issue by BilelLM** [webbukkit/dynmap#2185]
Hi,

The dynmap is not working on my webserver, i can't see the tiles, i've followed the tutorial.

The console return me this type of error

``[20:44:30][Server thread/WARN]: [dynmap] Could not create directory for tiles ('/home/snwarbard/dynmap/tiles').``
``[20:22:18] [Server thread/INFO]: [dynmap] Image file /home/snwarbard/dynmap/tiles/_markers_/pin.png - unable to write - failed``

Can someone help me please.

Thank's
SNW

**Comment by jwshields** [comment]
Check permissions.
Dynmap can't write to the tiles folder

**Comment by SNWarbard** [comment]
The permission value is 775...

**Comment by jwshields** [comment]
Who is dynmap/bukkit/spigot/mc running as?
who owns that directory?
Are they the same user? If so, we'd need to check deeper; if not, who is the owning group? are both users in that group?

If the dynmap user isn't a part of the group that owns the dir, or not the same user, 775 only allows read and execute, not write, for 'other' users.

**Comment by SNWarbard** [comment]
I didn't understood everything but the owner of that directory is me
I tried to put it at 777 but it didn't work.

**Comment by starhobbit** [comment]
what OS do u use? RHEL-like? Then it's may be a problem with selinux...
/home/snwarbard/dynmap this path have 777?

**Comment by jwshields** [comment]
**Do not chmod 777**
It is a huge security risk and very unsafe.

**Comment by SNWarbard** [comment]
I know I just try it i never let them with this permission lol

**Comment by SNWarbard** [comment]
Nobody know ?

**Comment by starhobbit** [comment]
what about selinux? or may be appArmor

**Comment by mikeprimm** [comment]
"[20:44:30][Server thread/WARN]: [dynmap] Could not create directory for tiles ('/home/snwarbard/dynmap/tiles').:"
Check perms for /home/snwarbard/dynmap to see if the dynmap process is allowed to create and/or access /home/snwarbard/dynmap/tiles directory - the second error is a consequence of the first (cannot save files when you can't make or see the path to get to it).  Other thing is to be sure the volume in question has space, isn't out of inodes, and isn't a read-only volume.
