### ISSUE TITLE
Could not update map: Forbidden (Apache)

### ISSUE THREAD

**Issue by SeruhioX** [webbukkit/dynmap#2187]
Good, the web interface is giving me this error "Could not update map: Forbidden", I tried to give permission to .json within the web, but the permissions are overwritten instantly by the previous ones

**Comment by adracamas** [comment]
You running in linux?  Could be a owner/group permission issue with the files.

**Comment by jwshields** [comment]
Sounds like a permissions issue.
Who owns the directory where the map html files are stored?
Is Dynmap/bukkit running as the same user? or does it have perms to write to that folder?
