### ISSUE TITLE
Mssing Feature: Render tile update triggered by programatic (plugin) block change.

### ISSUE THREAD

**Issue by Reg-Ed** [webbukkit/dynmap#2189]
I'm currently working on a plugin that periodically changes blocks at (seemingly) random locations throughout the world, using Block.setType(Material.WHATEVER).  A little testing reveals that these plugin-based block changes don't trigger a tile render, which makes sense given that Dynmap listens for Player BlockPlace or BlockBreak and actually, the Spigot API doesn't seem to have an event for programatic block changes.

My world is quite large and so making sure that Dynmap is correctly up to date with the actual chunk data is very important.  Short of programatically issueing a '/dynmap radiusrender' with a radius of '1' each time my plugin changes a block (which seems a bit of a fudge), I don't see a way to get Dynamp to update when my plugin changes (places or breaks) a block.

Am I missing something?  Is there anything you can do your end to watch for these kinds of block changes, or is there an API or something for Dynmap that I can use to add blocks to the render update queue each time I change one?

N.B. I did try to find a Dynmap API before posting this, but came up short.

**Comment by FedUpWith-Tech** [comment]
I'm assuming this is no longer relevant so I am going to close this. If you would still like to see this please open a new issue.
