### ISSUE TITLE
Fences/Iron Bars rendering incorrectly in isometric view.

### ISSUE THREAD

**Issue by Reg-Ed** [webbukkit/dynmap#2190]
Fences next to chests render attached to the chests, and single iron bars render as a four-way cross instead of a single pillar, both of which can be seen in the screenshot below:

![fences](https://user-images.githubusercontent.com/25720855/35184867-dc1eb8ea-fdf2-11e7-8c41-1efebd2f36e3.png)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
