### ISSUE TITLE
Can not find the server in Browser

### ISSUE THREAD

**Issue by Redmessi** [webbukkit/dynmap#2191]
Hi i made a new server with minehub.de - and i installed the latest dynmap: 2.5

The Problem is: when i put my id 89.163.242.213:8123 shows up a message that says:

This website is not accessible
89.163.242.213 refused the connection.
Search Google for 163 242 213 8123
ERR_CONNECTION_REFUSED

it even nothin happens if i change the port

i saw that in my server Properties i no IP added - but as soon as i add the server IP (wich is show above) the server can not start. 

so i just let this properties line free - and in dynmap properties there is 0.0.0.0 wich stands for open network -

normally it should work  - but it does not
Please help me!

Informations:
Minecraft 1.12.2
Windows 8.1 64bit

**Comment by svmine** [comment]
I'm also having trouble with the ssl certificate.
Give me information to fix this. Thank you
