### ISSUE TITLE
[06:15:30] [FATAL] [Dynmap] Error updating Maps table - No suitable driver found for jdbc:mysql://dal.sql.cubedhost.com:3306/gs4934

### ISSUE THREAD

**Issue by LockManipulator** [webbukkit/dynmap#2192]
I get this error message when starting the server and the dynmap page in browser shows a directory. Tiles is the only directory there and when I click it, it just brings me to a blank page that says Error: 500.

**Comment by jwshields** [comment]
Sounds like you have multiple problems.
Dynmap can't talk to your mysql DB.
Add the mysql.jar driver to the dynmap directory in plugins.
Also, **_please use the search function_**: https://github.com/webbukkit/dynmap/issues/2015

And, you will need to provide more info in regards to the web server to properly troubleshoot why you're getting the 500 error.
Please provide your config, os, minecraft/bukkit/dynmap versions, are you using internal/external webserver?

**Comment by LockManipulator** [comment]
I added but it's still not showing in the browser. Fixed the error messages in console though.

**Comment by jwshields** [comment]
Please provide more information than that.
Your webserver is misconfigured. That's all we can really determine right now from what you've given us-

Provide your dynmap config, as well as your config for the httpd (if you're not using the built in dynmap httpd).

**Comment by Pingger** [comment]
> 
> 
> Sounds like you have multiple problems.
> Dynmap can't talk to your mysql DB.
> Add the mysql.jar driver to the dynmap directory in plugins.
> Also, **_please use the search function_**: #2015
> 
> And, you will need to provide more info in regards to the web server to properly troubleshoot why you're getting the 500 error.
> Please provide your config, os, minecraft/bukkit/dynmap versions, are you using internal/external webserver?

Used the search function and didn't find the issue you are referencing! https://github.com/webbukkit/dynmap/issues?utf8=%E2%9C%93&q=is%3Aissue+no+mysql+driver

**Comment by Psy-Virus** [comment]
>> Sounds like you have multiple problems.
>> Dynmap can't talk to your mysql DB.
>> Add the mysql.jar driver to the dynmap directory in plugins.
>> Also, **_please use the search function_**: #2015
>> And, you will need to provide more info in regards to the web server to properly troubleshoot why you're getting the 500 error.
>> Please provide your config, os, minecraft/bukkit/dynmap versions, are you using internal/external webserver?

>Used the search function and didn't find the issue you are referencing! https://github.com/webbukkit/dynmap/issues?utf8=%E2%9C%93&q=is%3Aissue+no+mysql+driver

Using your link, I found this:

![2019-02-19_li](https://user-images.githubusercontent.com/6222200/53047493-d4b4d080-3492-11e9-93b4-1da8a94e6a54.jpg)

So what?! ;)

**Comment by Psy-Virus** [comment]
But is this issue resolved?
