### ISSUE TITLE
Gamemode Change only WITH Dynmap!

### ISSUE THREAD

**Issue by Regnak85** [webbukkit/dynmap#2193]
I know, its not in Dynmap, to change Gamemodes but:

I installed my Server, everything is fine. If i change worlds, GM 1 is not changing to GM 0.

Now i Install Dynmap. I change world -> GM1 automatically -> GM0
I got Multiverse, i even have the permission to bypass Gamemode changes...
So, i deinstall Dynmap... And everything is fine again. Gamemode doesnt change on World Change!
So, why is this? Dynmap can`t change Gamemodes, but only with Dynmap installed i got this Problem!

**Comment by jwshields** [comment]
What's the problem here?
Seems unrelated to dynmap, and even then, Dynmap shouldn't really touch the game modes.
