### ISSUE TITLE
Delete incorrectly rendered tiles

### ISSUE THREAD

**Issue by philipsdirk** [webbukkit/dynmap#2194]
So I use the plugin to send the map to [map.smartcraft.ml](url).
I recently changed the orientation so the map faces north. But the old map that was facing east is still partly visible. Is it possible to only delete the old tiles so I don't have to re-render the whole map?
Thanks for your help.

PS
This is my first post on GitHub so sorry if I break some kind of lay-out guideline.

**Comment by jwshields** [comment]
How are you storing the map? 
I'd recommend a `fullrender` command but that could introduce a large load on your server.

If SQL, maybe truncate the table, but the entire map would have to be re-rendered.
If filetree, I think removing the files and index should help as well.
