### ISSUE TITLE
Lighting configs

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#2195]
Hello! As always - love dynmap. I'm using the HEAD Jan-2018 dynmapforge and blockscan - and loving it. 

I am trying to customize the lighting - specifically lightening the nether a little.

I have confirmed I am changing the correct map and files - setting the maps lighting to 'default' brightens it up after a radiusrender; NetherShadows and Default both work in Flat and iso maps nicely; changing the map to my custom lighting works too. My custom lighting appears in "lightinglist" too.  Restarted server and reloaded, no obvious log errors, etc etc.

However ... changing the values isn't making a difference. If I reduce the custom parameters down to nothing like how 'default' is defined, it doesn't change. Specifically, changing the ambiance in the custom lighting, nor tweaking ambiancelight=4 in the original lightings.txt doesn't change the render. 

Just looking for quick tips on anything I might have missed here - thanks!

**Comment by mikeprimm** [comment]
Try latest builds - I just fixed an issue where ambientlight setting was being ignore on forge :)

**Comment by generrosity** [comment]
Its almost like a valentines day gift! Or a discount-chocolate-day gift for kiwis as it is ;) 

Love that the face API has been tweaked over. The lighting doesnt *seem* to have changed?

If it helps - the extreme situation of one map is rendering nether at bedrock with a clipped height, and custom lighting like below (although the rest of the nether doesn't seem to be brighter either);

lightings:
    - class: org.dynmap.hdmap.ShadowHDLighting
      name: genenether
      shadowstrength: 0.5
      ambientlight: 10

**Comment by mikeprimm** [comment]
which build did you pull?  what does '/dynmap version' report?

**Comment by generrosity** [comment]
Dynmap version: core=2.6-SNAPSHOT-Dev201802150423, plugin=2.6-alpha-2-2030

Which would have been this at the time -  Dynmap-HEAD-forge-1.10.2.jar                                 14-Feb-2018 21:24  4.9M

**Comment by generrosity** [comment]
Update on lighting with our map - the End changanged with lighting: brightnight, but recent renders are converting over to standard shadowed unlit terrain. 

Everything else seems to be working - at a guess its like none of the lighting options are working. I'll look at killing off the lighting/custom-lighting files just to make sure 😒😊 just being perfectionist as I love how useful this map is for our more shy noob players

**Comment by deb0ch** [comment]
Hey ! It's October 2019 and I am facing the same issue. I can't see anything in my Nether world and am trying to brighten it up - to no avail.

I checked that the changes I made were taken into account with `/dmap maplist nether_world` that showed correctly that my lighting was `shadows` - the same as the normal world maps, but purging the nether world and re-rendering it led to the same super-dark-can't-see-anything lighting.

Is it a bug ? Did I miss something ? Is it even normal that by default the nether is so dark that unlit netherrack appears as plain black, making tiles undistinguishable ?

`/dynmap version` is showing `Dynmap version: core=3.0-beta-5-218, plugin=3.0-beta-5-218`

**Comment by FajnB** [comment]
This is exactly what I was talking about.
https://github.com/webbukkit/dynmap/issues/2930

**Comment by skerit** [comment]
I've been messing with the nether lighting configurations for a while now, nothing seems to actually happen. It's still insanely dark. I would like to get it as bright and clear as Voxelmap does.

I'm guessing this might be because changing the ambient light level doesn't seem to do much (it's at 15 by default anyway?) and it tries to get the light level of the sky, which just isn't there?

**Comment by generrosity** [comment]
Closing my old lighting case off - yes, you need to use bright-day and such. No longer using forge or have the previous setup, but in Fabric 1.18 got a happy slicer on Nether working.

![image](https://user-images.githubusercontent.com/12838061/155120192-e432c233-0014-41c9-b68d-e0dddcbf9b6f.png)
