### ISSUE TITLE
Could not retrieve configuration: Not Found (Nginx + Dynmap + MySQL)

### ISSUE THREAD

**Issue by JO3QMA** [webbukkit/dynmap#2197]
Hi!
I am trying to disable the internal webserver of dynmap and use nginx that is running on the same machine.

I followed all these steps listed here
[[Add Wiki Page] Dynmap + Nginx + No Internal Web Server #2027 ](https://github.com/webbukkit/dynmap/issues/2027)

However, when accessing Dynmap, "`Could not retrieve configuration: Not Found`" appears as an error.
I found that when I select MySQL / sqlite as the storage type, I get this error.
We also confirmed that if you select filetree as the storage type, it will be displayed without problems.
How can I do if I want to use an external http server while using MySQL?

configuration.txt
[https://gist.github.com/JO3QMA/ed47f1138971bd5cf28e7629b3dfbae2](here)

**Comment by JO3QMA** [comment]
After adding / bukkit / path / plugins / dynmap / web / to open_basedir in php.ini it worked fine.

**Comment by jwshields** [comment]
You shouldn't need to add the directory to your php path.
What worked for me was symlinking my www/map directory to /home/minecraft/plugins/dynmap/web/

**Comment by JO3QMA** [comment]
thx. I restored the symbolic link and moved normally. XD
