### ISSUE TITLE
I can't see dynmap and error on console

### ISSUE THREAD

**Issue by MineServidorCraft** [webbukkit/dynmap#2198]
If i put dynmap on my sv get this error:

https://pastebin.com/Mfnb9Zie

I can't see the map. (I was change of server hosting)

**Comment by adracamas** [comment]
Is dynmap throwing errors on load?

**Comment by jwshields** [comment]
Paperspigot is returning an error saying that dynmap isn't enabled.
This doesn't seem to be a dynmap issue.
Make sure the user has op perms to execute dynmap commands, as well as the plugin being enabled.
