### ISSUE TITLE
Skins wont show up

### ISSUE THREAD

**Issue by ScuroK** [webbukkit/dynmap#2199]
Im using 1.12.2 (spigot) and dynmap 2.5

The skins dont show up on the map, only the default steve textures are visible.
I've checked out some other 1.12.2 server's dynmaps and i didnt see the skins there aswell.

Another problem i have is that i can see the armor of the players but i've set "send health" to false. But i still see the hearts and the armor symbols but they are just empty. how can i remove this?

**Comment by EnderDragonEP** [comment]
I have same issue.... looks like the default skin url "http://skins.minecraft.net/MinecraftSkins/%player%.png" it not work anymore...

**Comment by Dreadonator** [comment]
Its not about the skin url. I have the correct one but it doesnt work!

**Comment by EnderDragonEP** [comment]
But it display 404 not no found... I remember it works before.
![image](https://user-images.githubusercontent.com/30905525/36160453-28998330-111c-11e8-9165-89961c69c82e.png)

**Comment by MrSpock78** [comment]
Same with https://use.gameapis.net/mc/images/rawskin/%player% :/

**Comment by seema84** [comment]
Dinnerbone say:
"This API has been retired. Please migrate to the new one."

https://bugs.mojang.com/browse/WEB-985

**Comment by smmmadden** [comment]
good to know, I've been using http://www.minecraftskinstealer.com/player.php?user=%player% but even then it shows the steve's skin.  So which url is it?  I see talks of API's and java calls, but no direct replacement for the dynmap skins-url value.

**Comment by ScuroK** [comment]
http://s3.amazonaws.com/MinecraftSkins/ScuroK.png

But i dont think the url is the problem.

**Comment by Adam759** [comment]
If anybody has a solution to this it would be greatly appreciated. If I find anything I will definitely post here. It is always so frustrating and annoying when developers just pull API's without warning and it breaks things.

**Comment by seema84** [comment]
https://github.com/webbukkit/dynmap/commit/48fbecac40463cf60a61e7a1e16d7f61016ab5e5

**Comment by mikeprimm** [comment]
Check out latest dev builds for v2.6-alpha-2 or v3.0 - I just reworked the code to not use the legacy skin URLs that Mojang apparently retired.

**Comment by smmmadden** [comment]
can you share the link to them Mike?

**Comment by mikeprimm** [comment]
http://dynmap.us/builds/dynmap for Spigot/Bukkit version, http://dynmap.us/builds/DynmapForge for Forge versions

**Comment by smmmadden** [comment]
great!!  Thank you very much!

**Comment by smmmadden** [comment]
Just swapped out my Dynmap-2.5.jar for Dynmap-3.0-SNAPSHOT.jar and still the map shows the steve skin.   Should I be changing the configuration.txt to use a different url than this:
# Customize URL used for fetching player skins (%player% is macro for name)
skin-url: "http://s3.amazonaws.com/MinecraftSkins/%player%.png"

**Comment by mikeprimm** [comment]
If you are pointing at a custom URL, it will need to be one that is working properly (a number of sites are broken because they used the Mojang API that was just retired).  I tested the dynmap-3.0 version on spigot built yesterday, so pretty sure it is working there...

**Comment by smmmadden** [comment]
so I should revert back to the default? 
skin-url: "http://skins.minecraft.net/MinecraftSkins/%player%.png"

**Comment by Adam759** [comment]
Yes, or simply comment it out. If it is different it will override the patch. The patch gets the url from minecraft itself internally rather than an external API.

**Comment by smmmadden** [comment]
commented out and now it works on the spigot worlds too!  Thanks!

**Comment by ScuroK** [comment]
@mikeprimm im not sure but it seems like after updating to 3.0 players randomly time out and disconnect from the server

**Comment by Wqrld** [comment]
which url do we need? 
https://skins.minecraft.net/MinecraftSkins/wqrld.png doesnt work for me

**Comment by seema84** [comment]
@Wqrld 
you dont need this url in dynmap 2.6 or 3.0
http://dynmap.us/builds/dynmap/

**Comment by MrsMeowys** [comment]
Hello,

I am using dynmap-3.x-HEAD.jar and the skin-url: "http://skins.minecraft.net/MinecraftSkins/%player%.png" but skins sstill doesn't show up!
What else do I need to do?

**Comment by Wqrld** [comment]
it indedeed doesnt seem to be fixed: https://minotar.net/skin/%player%.png works for me though

**Comment by MrsMeowys** [comment]
Yup I deleted the faces folder from web.
I'll try use minotar URL. Thanks for the suggestion.

**Comment by sigmaroot** [comment]
3.x-HEAD.jar and skin-url: "http://skins.minecraft.net/MinecraftSkins/%player%.png" works for me.

**Comment by Luysita** [comment]
Skins aren't working again, is there a way to get UUID instead of Player name?

**Comment by sigmaroot** [comment]
@Luysita Did you use the recent build?

http://dynmap.us/builds/dynmap/dynmap-3.0-SNAPSHOT.jar

It's still working for me fine.

**Comment by Luysita** [comment]
@sigmaroot yes I am. Which link are you using for the skins though?

**Comment by sigmaroot** [comment]
Did you just read what I've written 5 days ago?

With this version, it **does not matter** which skin-url you have set in your configuration because it is not used anymore.

Please have a look in https://github.com/webbukkit/dynmap/commit/48fbecac40463cf60a61e7a1e16d7f61016ab5e5

As you can see there he is checking a players JSON data to get a valid URL.

**Comment by smmmadden** [comment]
just comment out the url's in the configuration.txt file and let the code handle it.  That's the fix I did with this and the previous 2.6 build and it works perfectly.

**Comment by sigmaroot** [comment]
It's working for me with non-out-commented skin-url:

`# Customize URL used for fetching player skins (%player% is macro for name)`
`skin-url: "http://skins.minecraft.net/MinecraftSkins/%player%.png"`

**Comment by Luysita** [comment]
@sigmaroot yes I did read it and it isn't working for me.

**Comment by sigmaroot** [comment]
@Luysita  Have you tried to make a backup of your configuration and dynmap folder and regenerate both?

Maybe somethings wrong with your cache and so on...

**Comment by Wqrld** [comment]
@sigmaroot https://skins.minecraft.net/MinecraftSkins/Wqrld.png return cert errors and a 404 for
https://skins.minecraft.net/MinecraftSkins/Wqrld.png

**Comment by sigmaroot** [comment]
@Wqrld Please read the whole issue and not only the last statement before commenting on it.

As I said two times before:

> With this version, it **does not matter** which skin-url you have set in your configuration because it is not used anymore.
> 
> Please have a look in https://github.com/webbukkit/dynmap/commit/48fbecac40463cf60a61e7a1e16d7f61016ab5e5
> 
> As you can see there he is checking a players JSON data to get a valid URL.

So: Yes, it does not work anymore with the plain URL, it returns a 404. Mojang retired it! But this URL is not used anymore with the new version http://dynmap.us/builds/dynmap/dynmap-3.0-SNAPSHOT.jar

**Comment by seema84** [comment]
guys please read https://bugs.mojang.com/browse/WEB-985

https://skins.minecraft.net/MinecraftSkins/ will never come back
(you dont need this url in dynmap 3.0)

**Comment by sigmaroot** [comment]
Yea, Mojang retired it and it is closed forever. Update to the 3.0, that's the working version without the need to set, remove, add, change or modify the skin-url because it is worthless like a dry leaf from now on 😄

**Comment by TheWrongAlice** [comment]
Any idea when this can be released on Github? (https://github.com/webbukkit/dynmap/releases)
I am using a system that pulls versions from there.

**Comment by seema84** [comment]
@TheWrongAlice 
use this http://dynmap.us/builds/dynmap/

**Comment by zrovihr** [comment]
> 
> 
> Yea, Mojang retired it and it is closed forever. Update to the 3.0, that's the working version without the need to set, remove, add, change or modify the skin-url because it is worthless like a dry leaf from now on 😄

Im using dynmap 3.0 for bukkit but its still not appearing?. So do I delete this link from the config or what?..
Tried deleting it but still no skin?. Is getting skins possible with Online-Mode being off in the minecraft server.properties?

edit : i got the skins by using online mode on but now the map is all black and it wont render anything.
