### ISSUE TITLE
Scrolling worlds in side panel

### ISSUE THREAD

**Issue by stevmei** [webbukkit/dynmap#2200]
Hello,

Thanks for keeping alive this awesome project. Due to the new UUID-skin problematic, I've recently updated to your 3.0-DEV nightly build.

As I see, you've implementet a new feature: Scrolling worlds in the right side panel. For this, just a question: Is it possible to disable this scolling somehow?

Thank you very much!

**Comment by MrSpock78** [comment]
Same with latest 2.6 build. I´d like the worlds static.

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
