### ISSUE TITLE
Unable to write error & roll backs on relog

### ISSUE THREAD

**Issue by Xethermic** [webbukkit/dynmap#2202]
Fully rendered flat map, when rendering surface mode i get the errors of unable to write .png files even though my ram usage is at 40%.

Second error; after i get the unable to write it leads to players not being able to play, they can move and place blocks but when they relog they get put back to where they started and the blocks they placed remain.

**Comment by jwshields** [comment]
Do you have any error logs?
Doesn't seem like a Dynmap issue though.
Check your disk space, it's likely full.
