### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by dagonzaros** [webbukkit/dynmap#2203]
Had to disable the jar to get server to start, it fully starts successfully then crashes. This is running on cent7, Spigot 1.12.2-r1

https://pastebin.com/FdSk76RV

**Comment by jwshields** [comment]
You've got a corrupt chunk. Dynmap didn't cause the crash explicitly, but when trying to render the chunk, Spigot ran into a problem trying to read it

**Comment by dagonzaros** [comment]
Used this, https://www.spigotmc.org/wiki/using-the-minecraft-region-fixer/ fixed, thank you so much.
