### ISSUE TITLE
Server Fatal Shutdown with RP & Dynmap

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#2204]
Not sure who's side this falls under so posting in both.  The does appear to be a conflict between the two mods.   https://github.com/FabioZumbi12/RedProtect/issues/253

**Platform:**  Windows 10 Pro x64
**Java:** 1.8.0_162x64
**Forge:** 1.12.2-14.23.1.2555
**Minecraft:** 1.12.2
**Sponge:** SpongeForge-1.12.2-2611-7.1.0-BETA-2911.jar
**Permissions:** LuckPerms-Sponge-4.0.130.jar

Conflicts causing crash:
**Dynmap:** Dynmap-2.6-alpha-2-forge-1.12.2.jar
**RedProtect:** RedProtect-7.3.0-b68-Universal.jar 

**Mods:** 
![image](https://user-images.githubusercontent.com/10309346/36744668-6f01f1b4-1bbb-11e8-8d9f-df6d276ccf17.png)

Thanks - Steve

**Comment by jwshields** [comment]
I looked over the other issue you linked and the error logs provided...
Can you run your dynmap config through a YAML checker? It seems the error is stemming from something YAML related in Dynmap but doesn't give info as to what.

**Comment by smmmadden** [comment]
sure, not a problem.  Will advise as soon.  Thanks!

**Comment by smmmadden** [comment]
all the .txt yaml files were fine for Dynmap with the exception of forgeworlds.yml oddly enough.  I haven't touched this file.

The error is:
Error : Unable to parse.
Line : 3           nether: false
![image](https://user-images.githubusercontent.com/10309346/36767006-60cc8e56-1c06-11e8-8d6b-55d11dfec772.png)
There are no tabs or extra spaces that I can see with the everything visible.
![image](https://user-images.githubusercontent.com/10309346/36767043-9ebf37b8-1c06-11e8-8a9a-844b45ca1634.png)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
