### ISSUE TITLE
Dynmap rendering Block with double Slab Textures [Custom Texturepack]

### ISSUE THREAD

**Issue by stormboomer** [webbukkit/dynmap#2206]
I have a problem with the texture dynmap uses when rendering blocks which also have double slabs. It seems like Dynmap is using the texture for double slabs to render:
- the normal block (no slabs)
- slab
- double slab

Is there anything I can do so dynmap renders with the correct texture of my custom texturepack?

I'm using Spigot 1.12.2 and Dynmap3
- CraftBukkit version git-Spigot-c3093ef-7e94e65 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- Dynmap version: core=3.0-SNAPSHOT-Dev201802150432, plugin=3.0-SNAPSHOT-Dev201802150437

![dynmaptexturebug](https://user-images.githubusercontent.com/25079531/37252307-583431dc-251f-11e8-9b1e-8ebee410e206.png)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
