### ISSUE TITLE
Grass Path rendered Black - SpongeForge

### ISSUE THREAD

**Issue by Lorrainrm** [webbukkit/dynmap#2209]
Ello!
Seems i cant get it rendered using 
spongeforge-1.12.2-2611-7.1.0-BETA-2963
Dynmap-2.6-beta-1-forge-1.12
forge-1.12.2-14.23.2.2627-universal.jar

Tried other texturepack, but still =/

Peace

**Comment by TomSputz** [comment]
Are you using any other mods?

**Comment by Lorrainrm** [comment]
VariedCommodities_1.12.2(06nov17)
CustomNPCs_1.12.206feb182

**Comment by Lorrainrm** [comment]
Just updated to Most Recent CustomNPCs
https://cdn.discordapp.com/attachments/423946043395407882/424557741353336832/CustomNPCs_1.12.217mar18snapshot.jar

**Comment by Lorrainrm** [comment]
Any idea or suggestion?

**Comment by Lorrainrm** [comment]
Any idea or suggestion?

**Comment by FedUpWith-Tech** [comment]
Sorry to necro this thread- grass path seems to render correctly on the latest version of dynmap. Please re-open with an example of  this behavior on the any of the latest dynmap versions
