### ISSUE TITLE
Feature Request: hidestyle reveals layer

### ISSUE THREAD

**Issue by Ayplow** [webbukkit/dynmap#2210]
While using dynmap on a personal server, we've found we dont want the plugin rendering all generated chunks as the exploration of the game is a lot of fun, however, I don't want to completely disable the map, just remove texture from it. I've found the 'visibilityliimits' configuration option, which is useful, however I think a new hidestyle mode could be incredibly helpful - if it could reveal a map rendered with a different shader, it would allow the map to retain it's functionality, and display multiple maps on the same map layer.

Looking at recent progress, however, I understand that development is slow at the moment. How much longer is dynmap going to be worked on?

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
