### ISSUE TITLE
Some issues with rendering chiselled stone bricks.

### ISSUE THREAD

**Issue by simonjonnemeth** [webbukkit/dynmap#2211]
Some render fine, most are completely black. This issue has been around since at least version 2.5. See here: [http://minessmap.lidosofbritain.co.uk/](url) 
(zoom in to spawn to the castle).

**Comment by jwshields** [comment]
Could you show a screenshot of what you're seeing?
I checked out that map and saw no black spots around the castle

**Comment by simonjonnemeth** [comment]
Apologies, I should have mentioned that this only seems to apply in the 'Surface' map type. Here:
![castle](https://user-images.githubusercontent.com/1496797/37789460-e36979d0-2dfb-11e8-8b50-1be3428bf022.PNG)

**Comment by jwshields** [comment]
Ah, sorry about that!
I guess I should've looked harder.
What happens if you go to the area and perform a radiusrender?
Also, are there any logs/errors you're seeing from MC or Dynmap?

**Comment by simonjonnemeth** [comment]
Hi, radiusrender in that area didn't make any difference unfortunately. As for errors, I'm not actually sure where to look. I can provide any standard logs from the server though.

**Comment by simonjonnemeth** [comment]
As it happens, I don't see anything in the console during a radius render, and I don't see any logs in the dynmap plugin directories, so should I presume there isn't?

**Comment by simonjonnemeth** [comment]
Has this been looked at yet?

**Comment by FedUpWith-Tech** [comment]
Sorry to necro this thread- Cannot reproduce on the latest version. I believe this was fixed but cannot find it in the patch notes. Please re-open if the issue still persists.
