### ISSUE TITLE
Embedding dynmap into a div

### ISSUE THREAD

**Issue by PsychoNavigator** [webbukkit/dynmap#2212]
I am having problems with using iframes and making dynmap fill a div so that it takes up the whole page and doesn't add any scrollbars.

It'd be really nice to be able to dump code into a div and make this work, filling up the entire div with no 

I am wondering if it's possible to just copy all the code from the index page and paste it into a div and change src locations to reflect that change?

Looking at it, I'm not so sure it will work but am trying my luck.

iframes are a depreciated tag, and it'd be nice to push dynmap away from having to use it at all.

**Comment by jwshields** [comment]
I'm not fully sure what's being asked here.

Dynmap doesn't use iframes as a part of how it works overall really.
Nobody should be using iframes as they also introduce a layer of complexity and insecurity.

What are you trying to accomplish?

**Comment by Lorrainrm** [comment]
I use the following:
<iframe src="dynmap-ip" width="100%" height="800">
</iframe>

Result here:
https://dbnation.enjin.com/mapa

**Comment by PsychoNavigator** [comment]
@jwshields 
I am not asking for iframes to be implemented, I want to avoid having to use them entirely. I am asking for a way to be able to use the webpage code inside of a div so that i can have a full page map that is consistent in design with the rest of my website; Sidebar, header, footer. The dev's solution in the past has been to use iframe within a div, but that is both messy and depreciated. Hiding the scrollbars is dirty and inconsistent across browsers.

It would be nice to have an option where you can copy code into a div, and the map will work exactly the same within it as it does with its own page.

I am not having luck. I copy/pasted the scripts into my test page, edited the src's to reflect the changed folder location, then used the body portion of code within my div and its not loading.

**Comment by ssshake** [comment]
I think you need to answer why you don't want to use iframes, it's a perfectly good solution that I'm sure plenty of people including me use to accomplish what you want.  

I don't see what is messy about this. Wanting to bring it all into your markup sounds messy to me. 

Another example: https://daggasoft.com/minecraft/

From what little information I can gather this sounds like a css issue.

**Comment by PsychoNavigator** [comment]
Because iframes are a depreciated asset, don't display consistently across all browsers and it looks like shit. I don't want it in a frame on a page. That shit looks like it was made 10 years ago when it's in a frame.

@mikeprimm 

Can you please help me out on this? It would be nice to have a snippet of code to chuck into a div and call it done. Far more elegant solution than using iframes.

**Comment by kalleswe** [comment]
Any update on this? We can't be the only one wanting this.

**Comment by ThisIsTenou** [comment]
You're not the only one, we'd also greatly appreciate this being implemented.
  

  

  

  
  
  
  
  
>

**Comment by mikeprimm** [comment]
If you look at the source code for the index.html provided by dynmap, I think you'll see what you're asking for:

https://github.com/webbukkit/dynmap/blob/v3.0/DynmapCore/src/main/resources/extracted/web/index.html

Specifically, that page is essentially all the script import and logic you need to do what your asking for - you'll need to integrate that into your own page (there isn't a way for me to add scripts and a <div> into your pages...), but the pattern should be easy enough to follow.
