### ISSUE TITLE
BlackMap

### ISSUE THREAD

**Issue by winnipeg21** [webbukkit/dynmap#2213]
Hello,

 on my dynmap i'm getting only a black screen. I deleted all the world renderd tiles and did a full render and nothing worked. It was working until last week everything just stopped. Please help me

dynmap config - https://pastebin.com/WRJVfdYE
When loading dynmap - https://pastebin.com/RsCqayfL

site - http://104.149.239.2:4597/

**Comment by jwshields** [comment]
When you say `deleted all the world rendered tiles` - can you clarify what you mean by that?
I just tested accessing your map from my machine, the basic bits of the page load, but all requests to `/images/*` are 404'ing

What does your directory `plugins\dynmap\web` look like?
Who owns those files, and what are the permissions on them?

**Comment by winnipeg21** [comment]
Well one of the other admins did /dynmap purge and all the files in `tiles` have been deleted. We are using multicraft as well. In the `plugins/dynmap/web` all i seen is;

1. Css (folder)
2. Js (folder)
3. tiles (folder)
4. gettiles.php
5. inactive.html
6. index.html
7. robots.txt
8. up.php

**Comment by winnipeg21** [comment]
> but all requests to /images/* are 404'ing

Looking in the dynmap folder there is no `images` folder.

**Comment by jwshields** [comment]
1. Stop the game server
2. Move/copy the entire dynmap folder (in plugins) to a safe location. 
3. Restart the game server
4. The entire dynmap folder should regenerate
5. Move your config, tiles, and other files/configs you've modified - back into this new folder that was just created.
6. Restart the game server

That should get you back up and running again.
I'd hazard a guess that the deletion didn't do exactly what was wanted and got more than the tiles.

**Comment by winnipeg21** [comment]
Thanks for the help, it's up and running! just doing a full render so players can see it! Thanks!
