### ISSUE TITLE
Dynmap3 with Conquest 1.12.2 resource pack.

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#2214]
Hello.

I would like to use the Conquest Resource Pack - ver. 1.12.2 (latest) with Dynmap in my server.
I added the texture pack into the right folder, but I get this error in loading:
https://pastebin.com/Cx98iHPz

Can you help me please?

**Comment by RanmaKei** [comment]
try removing the mcpatcher folder in the texture pack or texture zip.
