### ISSUE TITLE
Dynmap Issue, can't find a way to view it.

### ISSUE THREAD

**Issue by rapperedog** [webbukkit/dynmap#2215]
I have dynmap installed, plugin itself is working fine, but I can't see it. I've tried using the basic link, "http://yourserverip:8123/" but when I put my IP in, it's a totally different server, I have also tried changing the port (in configuration.txt)- which causes it to just not connect to anything. I would appreciate any help you're willing to give, at this point i'm lost.

**Comment by jwshields** [comment]
Are you hosting the server yourself or using a hosting provider?
If self hosting, are you inside a LAN/NAT'ed? Are you using your internal or external IP?
**What addresses are you typing into your browser?**
Have you forwarded ports properly?
Have you tried from `localhost`?

**Comment by Too-DAMN-Much** [comment]
i have this issue or a very similar one as well.

1. it's on my LAN, i can use either internal or external IP and have verified that they are reachable for EVERYTHING except dynmap both externally and internally
2. 192.168.1.11:8123 (as well as port 8124, changed it in case of conflicts), http://192.168.1.11:8124, https://192.168.1.11:8124
3. yes, i have verified that the ports are reachable, BOTH externally and internally, the ONLY issue is the dynmap ports.
4. need further instructions to do, please provide the exact string that should be entered.

not positive this is the same issue but it appears to be the same as #2217

**Comment by Too-DAMN-Much** [comment]
just in case it helps anyone else, if you're using a linux OS you'll need to edit the iptables (built in firewall) and allow the dynmap port, go find the relevant manpages to open and forward the relevant port you set for dynmap and see if that fixes the issue for you as well.

bit of a stupid thing to have missed, but i really had no clue a dedicated server hosting OS would have any kind of built in firewall.

**Comment by NorthWestTrees** [comment]
have you port forwarded the port on your router or modem? I don't have Linux but I know that ports regardless need to get past the router firewall on your server PC. all routers are different, I own a TP-Link N750, it does good and supports a lot more then 5 ports I think its endless porforwarding.
