### ISSUE TITLE
[Question, not issue] Set a default for new worlds?

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [webbukkit/dynmap#2220]
I just need 1 world with dynmap. How do i set new worlds to be disabed by default?
Am i missind an config entry?
Using 1.8.8

**Comment by FedUpWith-Tech** [comment]
this is possible in later versions using dmap or editing words.txt directly. I'm closing this as I don't believe it is relevant due to age but please re-open or open a new issue if you need more help
