### ISSUE TITLE
HTTPS Support?

### ISSUE THREAD

**Issue by NorthWestTrees** [webbukkit/dynmap#2221]
Ok, I have a bit of a problem I am sure there is a very easy fix or setting I can just enable but I am not seeing it.

I have several years of designing websites on Wix.com which is an HTTPS site, however, I have been having problems getting an Iframe to display the Dynmap page on the site.

I did some reading up and apparently you can use Iframes to display other than the same type of HTTP, so because wix.com uses HTTPS:// I can only use HTTPS:// URLs and if its HTTP:// I can only use HTTP://

I have been using this code below but people need to deactivate the security on their browser to view the map.

<style>
*, iframe {
    padding:0px;
    margin:0px;
    width:100%;
    height:100%;
    overflow: hidden;
}
</style>
<iframe src=http://serverIP:8123/"></iframe>

Is there a way I can make the website an https in the config somewhere or can you add support for that, please? And if so when will the update be?

**Comment by DmitryRendov** [comment]
ReverseProxy+LetsEncrypt works like a charm for me.

Also - https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-apache2-under-Debian and  #2071, #2122

**Comment by ssshake** [comment]
It's common practice that you would use SSL termination. That is having something like nginx, apache, haproxy as your front end, handling ssl, And then proxy out to this unencrypted service locally.

If you browse to my website to view the map, you access it on port 443 like the rest of my website, But that is being proxied locally to 8123.
