### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Zorock666** [webbukkit/dynmap#2222]
I have this issue where dynmap doesn't want to load and let people see it. This persists until a player opens up MC, and refreshes the server list to ping my server, and then dynmap loads up for them. They don't even need to log on to the server. Trouble is, both "login-enabled" and "login-required" are set to false. I can provide a link to pastebin with the config if needed, or just write what other information you might need to know. But could you please tell me why dynmap won't just show to players right away? I've tried reinstalling dynmap and keeping all the default settings and it still won't just show right away. I'm using Spigot if that matters.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
