### ISSUE TITLE
Hide worlds with name pattern

### ISSUE THREAD

**Issue by koca2000** [webbukkit/dynmap#2225]
Hi!

I have plugin DungeonsXL on my server that is creating new worlds at runtime an deleting them after some time. World name is always DXL_Edit_X or DXL_Game_X where X is any number. I want to hide all of these world in dynmap. Is it possible or can you make it possible?

Best regards.

**Comment by jwshields** [comment]
If your plugin allows you to have it run arbitrary commands before/during/after map creation, you could utilize something like the suggestions [on this page](https://github.com/webbukkit/dynmap/wiki/Configuring-Maps-and-Worlds-using-dmap).

```
/dynmap worldset {worldname} enabled:false
```

**Comment by jwshields** [comment]
Also, this resource appears to contain relevant information: https://github.com/webbukkit/dynmap/wiki/Configuration-of-worlds
