### ISSUE TITLE
dynmap chatname / playername from url

### ISSUE THREAD

**Issue by larryl79** [webbukkit/dynmap#2226]
I've set trustclient and allowurlname to true and still not working in 2.5
example.com/dynmap/?cahtname=Larry

```
class: org.dynmap.InternalClientUpdateComponent
allowwebchat: true
webchat-interval: 5
hidewebchatip: true
trustclientname: true

class: org.dynmap.ClientComponent
type: chat
allowurlname: true
```

what I doing wrong or this is an issue?
I want do joomla pass trough the authenticated username to dynmap into an ifarme, but the dircet link doesn't work already...

**Comment by Draesia** [comment]
Also having this same issue... Still not working 2 years later :o

**Comment by larryl79** [comment]
looks like nobody developing this plugin already... :(

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
