### ISSUE TITLE
Disabling chat doesn't stop server sending chat to clients in background

### ISSUE THREAD

**Issue by ssshake** [webbukkit/dynmap#2228]
Love this plugin but I have one big issue I can't solve and I think it's kind of important security wise.

In order to disable the chat in the map, you have to disable the chat balloons, web chat and the chat box. 

BUT all this does is visually disable the chat. Every chat message from connected users still gets served up from dynmap and is available in the inspector on the client.

I want to allow the public to see my world, but I don't want to allow the public to spy on people chatting. I don't want to use logins because this goes against my goal.

Is there a way to actually prevent the dynmap server from sending the chat messages in the XHR requests?

**Comment by ItsTauTvyDas** [comment]
From my understanding, you want to disable chat and chat spy?
You need to set `allowwebchat: true` to `false`, maybe `hidewebchatip: false` to `true`, set `allowchat: true` to `false` and to this: 
```
  - class: org.dynmap.ClientComponent
    type: chat
    allowurlname: false
  - class: org.dynmap.ClientComponent
    type: chatballoon
    focuschatballoons: false
  - class: org.dynmap.ClientComponent
    type: chatbox
    showplayerfaces: true
    messagettl: 5
    # Optional: set number of lines in scrollable message history: if set, messagettl is not used to age out messages
    scrollback: 100
    # Optiona; set maximum number of lines visible for chatbox
    #visiblelines: 20
    # Optional: send push button
    sendbutton: true

```
add # to disable it, like `#- class: org.dynmap.ClientComponent`, `#type: chat` and etc..

**Comment by ssshake** [comment]
I believe the original scenario described is the result of toggling those options.

If you do that yourself and then open up chrome developer tools, check the network tab and inspect what data comes in from the server, you'll see that the chat data is still being sent from the server. So that is what I am talking about.

**Comment by mikeprimm** [comment]
If you remove the back end components - org.dynmap.SimpleWebChatComponent - this accomplished the goal.  The other flags are for the front end components, and are just presentational feature controls.

**Comment by JurgenKuyper** [comment]
closing, documentation has been updated (last FAQ entry has the ways to disable chat fully).
