### ISSUE TITLE
Unable to find link

### ISSUE THREAD

**Issue by KyanG7** [webbukkit/dynmap#2229]
I have full rendered my world but I cannot go to my link? How do I find  my link and what is it?

**Comment by Argetan** [comment]
**Method 1**
Dynmap will give the link to the web interface when it starts up, in your console, you will see something like `[dynmap] Web server started on address 0.0.0.0:8123` enter that in your browser and you should be good.

**Method 2 (in case you can't access the console)**
The link to the Dynmap is your server's IP-address and Dynmap's port. By default Dynmap uses port `8123`, assuming you didn't change that you'd get something like this: `play.myserver.net:8123` or `12.34.567.890:8123` if you don't have a domain name.

Once you have Dynmap loaded you can use the menubar that appears on the right side of your browser to select another world or view.

**Comment by KyanG7** [comment]
How would I make it a domain? I currently own forgesurvival.us and if I were to want to make it into map.forgesurvival.us how would I do that?

**Comment by KyanG7** [comment]
Also nothing like "Web Server started on 0.0.0.0:8123" ever pops up.

**Comment by Argetan** [comment]
Assuming your forum is up to date the IP of your server is `107.173.65.73`. That means that if Dynmap is hosted on the default port you should be able to connect to `107.173.65.73:8123`. You might want to check your config files from Dynmap to make sure it is.

Furthermore, for you it might not say `Web Server started on 0.0.0.0:8123`, but it will probably give you a different IP if you go to console and look for `Web Server` or `[dynmap]` you'll probably find something. If not then that is probably the issue.

I don't know how you'd go about using `map.forgesurvival.us` to go to Dynmap.

**Comment by KyanG7** [comment]
Honestly that page just doesn't load. Would anything like votifier or me having a dedicated ip interfere with it?
