### ISSUE TITLE
High resolution icons

### ISSUE THREAD

**Issue by MicleBrick** [webbukkit/dynmap#2234]
Is there a way to use high resolution images for icons, and customize their scaling so they don't look incredibly enormous? ATM, anything over 16x16 is simply too big.

**Comment by Miclebrick** [comment]
Example:
32x32 https://cdn.discordapp.com/attachments/437031428447010816/441824216954961920/wrong.PNG
16x16 https://cdn.discordapp.com/attachments/248609919618646016/441825691261075466/unknown.png

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
