### ISSUE TITLE
Map following cursor after left-click

### ISSUE THREAD

**Issue by simonchow96** [webbukkit/dynmap#2237]
I did no modification since the problem solved last time (about 4 months ago I guess?). Recently the dynmap has a little bit problem: The map follows the cursor once after the user left-clicked the map. Here is the situation video: https://youtu.be/Kr9Sv20S2W0
The cursor shows the user is pressing the key, but in fact we don't.

Here is the link to the map: https://www.synercraft.net/maps/watersuno

OS: Ubuntu 17.10
Web Server: Apache2
Minercraft server kernel: Spigot 1.12.2
Dynmap Version: 2.5-Dev201706100405
Dynmap config: https://pastebin.com/tjMfbrDL
Apache config: https://pastebin.com/PCFF4fns

Thanks for all everything!

**Comment by jwshields** [comment]
I want to say that's something to do with your browser and/or mouse and how it interacts with the web browser.

**Comment by simonchow96** [comment]
@jwshields I have received many users reporting this to me recently (for last 2 weeks I think). I don't think it's browser problem, is it?
I have tried different browsers on different OS already, such as chrome, firefox, safari and IE, and MacOS, Windows etc., and the outcomes are the same.

**Comment by jwshields** [comment]
It looks like the files that control the click and drag functions for Dynmap haven't changed in years.

I was able to replicate this on my computer, and it seems when you let go/"un-click" - the page changes to stop the dragging, but the browser isn't responding to it. This isn't my strong area. But that's what I'm seeing right now.
Something to do with the browser and how it handles leaflet.js
