### ISSUE TITLE
Custom Blocks Renderer

### ISSUE THREAD

**Issue by Kirbyarm** [webbukkit/dynmap#2238]
Hallo dynmap and followers! I love this mod and am grateful to see it ported over to a forge version using MC 1.10.2. Previously I only used this for vanilla Minecraft years ago when I used to play the game only in vanilla (craftbukkit server however). No issues of note come to mind in the past, but this version is rendering almost all the blocks we build with as invisible or black/void. It is obvious that it's because they are custom blocks that Dynmap does not recognize/support. Given the modpack is fairly hefty at 140+ mods, that is only understandable.

I looked over the wiki documentation and I am really confused how to implement custom blocks to the dynmap renderer. My ability to program and code is limited at best, but I can configure with relative ease once I see it in action. I was hoping someone wouldn't mind writing a quick little write up explanation of simple steps? Like...

-get texture ids(?) and block ids/data from (this) typical location/file within a mod's assets

-create a text file named texture ids in this folder
-paste this code in it with some examples of custom textures

-create text file named customblocks in this folder
-paste this code in it with some examples of a custom block or two
-I fill out the rest with desired blocks to be rendered
-yayy my server is happy with no more void blocks!

I really think I could do this if I only saw the information in action by example, you know? I really need help with this, so I figured it can't hurt to ask, right?

**Comment by BonaireDreams** [comment]
You could also add Dynmaps Blockscan mod. It will attempt to scan all the blocks it doesn't support. It's now rendering 90% of my blocks. Note: most models will never render (IE Immersive engineering multiblock structures) and any blocks created by Chisel.

**Comment by generrosity** [comment]
Chisel may adapt vanilla JSON, and dynmap automatically work - https://github.com/Chisel-Team/Chisel/issues/656

**Comment by FedUpWith-Tech** [comment]
DynmapBlockScan has implemented this functionality
