### ISSUE TITLE
Unable to change perspective on 

### ISSUE THREAD

**Issue by Brytone** [webbukkit/dynmap#2239]
Hey I've tried googling and reading but I'm a little confused on how to change the perspective of the map, everyone refers to the page but I really just keep breaking my dynmap.

https://imgur.com/a/CXDJU01 this is what my map looks like right now, its pointing NW but I would like to to be pointing SE. 

I understand I need to edit the perspectives.txt but I don't know what needs to be cut or added.
Any help would be greatly appreciated!

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
