### ISSUE TITLE
Unable to change map center position

### ISSUE THREAD

**Issue by AbsintheNishi** [webbukkit/dynmap#2240]
Hi there, I've tried searching but couldn't find anything on this, apologies if I've missed something.

I'm unable to change the center position on the map. I'm using the following commands and not getting an error message, but the center doesn't change on the map when viewed in browser or when queried with /dmap worldlist. Other than that, the map appears to be functioning correctly; it's showing some terrain (mainly black as only been running since last night), players are visible, as are their chat messages.

/dynmap pause all
/dmap worldset Amity center:64/97/194  (after entering this I get the message saying "if you are done editing map data, run '/dynmap pause non' to resume rendering")
/dynmap pause none

The world name is the same as reported using /dmap worldlist (reported as Amity, not amity)

Currently running Spigot 1.12.2-R0.1-SNAPSHOT and Dynmap v2.5

Any help would be very much appreciated :)

**Comment by BonaireDreams** [comment]
Don't use slashes in your co-ordinates. Should be: 
/dmap worldset Amity center:64 97 194 

Or even better, if you are logged into the server go to the actual spot you want as the center and enter
/dmap worldset Amity center:here

**Comment by AbsintheNishi** [comment]
The coordinate option still wasn't working, but using "here" did work, although the server needed a restart for it to take effect. I did try "here" before posting but must have got the syntax slightly wrong. Thanks very much for replying, I really appreciate it! :)
