### ISSUE TITLE
Can someone show me how to use dynmap with Xampp?

### ISSUE THREAD

**Issue by Sonic8608** [webbukkit/dynmap#2241]
I Currently have Dynmap on my server and it is taking a lot of space on my hard drive. Has anyone use dynmap with Xampp mysql before? Any tips?

**Comment by jwshields** [comment]
There's no good way to transition from using disk storage to MySQL. You'll need to rerender all worlds and views.

If you want to reduce space utilization, consider reducing the quality of the map images by using `image-format` in the dynmap config: 
https://github.com/webbukkit/dynmap/wiki/HD-Map-Configuration#additional-hdmap-settings

Also, check this out for switching over to mysql: https://github.com/webbukkit/dynmap/issues/2026

**Comment by Nick2253** [comment]
I have a 17k x 20k map, and I too was running out of hard drive space with my default render.  By default, Dynmap will do a high-res render saved as PNG, which I calculated at over 150GB of space.

To reduce space, I changed my top-down map to vlowres with PNG, and my ISO view to medres with jpg-q95.  This significantly reduced my space.  All together, my renders (I'm also doing topo) only take up about 30GB.

```
  - name: world
    title: "Overworld"
    extrazoomout: 4
    center:
      x: 5500
      y: 40
      z: 3000
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "Surface"
        prefix: t
        perspective: iso_SE_30_medres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1
        image-format: jpg-q95
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_vlowres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 2
        image-format: png
      - class: org.dynmap.hdmap.HDMap
        name: topo
        title: "Topographic"
        prefix: topo
        perspective: iso_S_90_vlowres
        shader: topo-noplants-custom
        lighting: default
        mapzoomin: 2
        image-format: png```

**Comment by Sonic8608** [comment]
I want to use mysql on Xampp 1.8.1. I tried downloading the . jar files under platform independent and drop the jar into the dynmap folder. It does not seem Dynmap is loading any tables in. Unless I have to create it myself... If I need to create the tables manually how could I do that?

**Comment by FedUpWith-Tech** [comment]
Closing this due to age, please make a new issue if you still need help
