### ISSUE TITLE
Does Dynmap use .getDisplayName() instead of .getName()?

### ISSUE THREAD

**Issue by freddedotme** [webbukkit/dynmap#2245]
Since I've updated the display name of a player from another plugin _Dynmap_ seems to fetch the display name when getting skins resulting in skins not being found.

Can I fix this somehow?

**Comment by mikeprimm** [comment]
It used getName, not getDisplayName - mojang broke their old URLs, though, so only fetching using the UUID actually works now.  You'll want to grab the latest dev build of 2.6 or 3.0

**Comment by freddedotme** [comment]
Cheers, thank you!
