### ISSUE TITLE
Suggestion - Quark "greener grass"

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#2246]
Greener Grass - Grass is greener on the Quark side. Biome colors are still respected, but are greener non the less.

Vaskii's Quark mod makes our world 'pop' just a little more. Image comparison from his website - 
https://quark.vazkii.us/img/modules/client/greener-grass.jpg

Are there "easy" options to do this in dynmap? 

I don't know if you have ever heard of NVidia's "digital vibrance",  but if feels like it might do a similar thing. It would be nice to have the client-colours from via Quark but I imagine its not easy.

**Comment by FedUpWith-Tech** [comment]
I bet this is doable with custom shaders or resource packs if thats what you are asking for- I'm going to close this due to age and its likely no longer relevant
