### ISSUE TITLE
Custom sea level setting please?

### ISSUE THREAD

**Issue by k-jiang** [webbukkit/dynmap#2247]
Some of my worlds, like skyland, have different default sea level height instead of 63. And they are void worlds (which do not have sea level setting by default). It also makes markers off centered, like WorldGuard regions etc.

Can I have a custom sea level setting for those worlds please? Thank you!

**Comment by FedUpWith-Tech** [comment]
Assuming this is doablein a later release or otherwise no longer relevant- please open a new issue if this persists.
