### ISSUE TITLE
Biome & topo shader

### ISSUE THREAD

**Issue by HanatakeYurii** [webbukkit/dynmap#2251]
Hi,

Is there a shader that combines topographic view and default colors for biomes (to have the 2 informations)? Or a way to create it?

I know I can create multiple maps to get each, but I wanna know if there are any possibilities to get them on a sole one.

Thanks

**Comment by mikeprimm** [comment]
possible, yes - it'd be a custom shader combining the two.  How would you propose the color coding scheme for the combination be defined?  the height offers some easy options to interpolate based on a few specified color-vs-height combinations, but biomes are only vaguely an 'ordered' set, so they really don't offer much for interpolation.  I could extend the biome shader to allow for a set of color-vs-height values for a given biome vs just a single color per biome....

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
