### ISSUE TITLE
I just wonder..

### ISSUE THREAD

**Issue by ItsTauTvyDas** [webbukkit/dynmap#2252]
I just wonder if I can like create php file and include *out of /web/ folder* latest.log, like console in web 😆 I have test `<?php echo "test"; ?>` and php don't work, why? How do I enable it? And it is possible to include file out of /web/ folder?

EDIT: And I wonder, PHP need to be installed

**Comment by generrosity** [comment]
I'm pretty sure the "internal web server" is just a simple machine - You probably want to use a proper php instance, and bring the files across. 

Also - I dont know if you really want a Minecraft server java to be running PHP, as the web could suddenly impact your TPS!
