### ISSUE TITLE
Webserver help pls

### ISSUE THREAD

**Issue by DatNubTriz** [webbukkit/dynmap#2253]
I honestly, for the life of me, cannot figure out how to use the webserver?

Im trying http://serverip:port/ in my browser and i get the error:

'This site can't be reached!'

Any help is very much appreciated!

**Comment by ItsTauTvyDas** [comment]
Maybe webserver is disabled in configuration.txt ?

**Comment by jwshields** [comment]
Are you putting, literally `http://serverip:port/`?
Try the actual IP address, with the default dynmap port, 8123

**Comment by DatNubTriz** [comment]
all good i got help from my server host. They had it finished within a few minutes 👍
