### ISSUE TITLE
Standalone web server not working + tutorial out of date

### ISSUE THREAD

**Issue by Etretats** [webbukkit/dynmap#2254]
Hello,

I try for now few days to configure and make the standalone dynmap web server working.

I followed step by step this tutorial : 
https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server

Then I found out trough this post that this tutorial might be out of date ; and updated my configuration thanks to the given advices ( https://github.com/webbukkit/dynmap/issues/883 )

Finally I had reached this post too and tried out to modify my configuration ; in an attempt to make things work. (https://github.com/webbukkit/dynmap/issues/1008)

I'm not very familiar to the JSON or PHP code and I feel a bit lost. I didn't not understand what should  be written from line 431 to 446 (cf following pastebin)

https://pastebin.com/KUavmi8G

I managed to make the tiles folder working ; the fullrender of my only world create tiles in the right folder.
In /standalone the dynmap_world.json file as pop out.

Finally when I do https://myserverip/dynmap/web only a black screen can be seen in my explorer

Can someone help me out ?

Thank you

**Comment by jwshields** [comment]
If you're getting a black screen, that means the PHP portion isn't working properly.
What web server are you using, what PHP install as well? Versions of each?

**Comment by Etretats** [comment]
Hi jwshields ;

Thank you for your answer/question : 

Php 7.2 is installed and phpmyadmin is working. I'm using an Apache2 server on UNIX OS ; both latest version

**Comment by Etretats** [comment]
hi @jwshields I found out the begining of an answer : 

  configuration: 'standalone/dynmap_config.json?_={timestamp}',
  update: 'standalone/dynmap_{world}.json?_={timestamp}',
  sendmessage: 'standalone/sendmessage.php',
  login: 'standalone/login.php',
  register: 'standalone/register.php',
  tiles: 'tiles/',
  markers: 'tiles/'


But I haven't tested it yet ; since my dynmap has reach the inode limit of my server and I have to test the MYSQL option.

I will forward you if this changes do works.

**Comment by jwshields** [comment]
When moving to MySQL, you'll need to rerender the entire map, as it's not easily portable between two storage methods.

Also, I might suggest taking a look at this: https://github.com/webbukkit/dynmap/issues/2027

**Comment by Etretats** [comment]
So @jwshields thanks to your own tutorial https://github.com/webbukkit/dynmap/issues/2026 I manage to swap from the filetree to the MYSQL storage.

Then I verified my configuration it appear that this configuration for line 431 to 446 ; the right config to write his : 
configuration: 'standalone/dynmap_config.json?={timestamp}',
update: 'standalone/dynmap_{world}.json?_={timestamp}',
sendmessage: 'standalone/sendmessage.php',
login: 'standalone/login.php',
register: 'standalone/register.php',
tiles: 'tiles/',
markers: 'tiles/'

And don't forget to disable the web-server on line 328.

Everything works just fine and I will be happy to close the issue.
