### ISSUE TITLE
[1.7.10] Sign markers don't show on map

### ISSUE THREAD

**Issue by AnrDaemon** [webbukkit/dynmap#2259]
Forge 1614
FE 1.4.6.1351
Dynmap 2.4
```
  - class: org.dynmap.MarkersComponent
    type: markers
    showlabel: false
    enablesigns: true
    # Default marker set for sign markers
    default-sign-set: markers
    # (optional) add spawn point markers to standard marker layer
    showspawn: true
    spawnicon: world
    spawnlabel: "Spawn"
    # (optional) layer for showing offline player's positions (for 'maxofflinetime' minutes after logoff)
    showofflineplayers: false
    offlinelabel: "Offline"
    offlineicon: offlineuser
    offlinehidebydefault: true
    offlineminzoom: 0
    maxofflinetime: 30
    # (optional) layer for showing player's spawn beds
    showspawnbeds: false
    spawnbedlabel: "Spawn Beds"
    spawnbedicon: bed
    spawnbedhidebydefault: true
    spawnbedminzoom: 0
    spawnbedformat: "%name%'s bed"
```

**Comment by Cubox-** [comment]
Having this issue as well

**Comment by Cubox-** [comment]
You need to set offlinehidebydefault to false and spawnbedhidebydefault

**Comment by AnrDaemon** [comment]
How's that related to sign markers?

**Comment by Cubox-** [comment]
Sorry, thought you meant beds and offline people.

You mean signs with [dynmap] on them?

**Comment by AnrDaemon** [comment]
I mean signs that dynmap is supposed to recognize as markers.

**Comment by Cubox-** [comment]
When you place the sign, does the [dynmap] tag becomes invisible?
If you add for example an icon: pin, that line should also become invisible

**Comment by AnrDaemon** [comment]
No, it doesn't. All documentation I've googled points to some "permission" that simply does not exist on Forge servers.

**Comment by Cubox-** [comment]
I don't know a thing about forge servers, but there is one permission needed, that is granted to OPs by default.
If you are not op, or cannot be, you can edit the .jar (unzip it and rezip it) of the plugin, going into plugin.yml
find this
`  dynmap.marker.sign:
    description: Allows creation of markers using signs
    default: op`

change the default: op to default: true

This will make anyone able to create markers using signs, but if after the modification it works, this means the problem was indeed permission based

**Comment by AnrDaemon** [comment]
There's no such file.

**Comment by AnrDaemon** [comment]
And even ops can't place sign markers.

**Comment by Cubox-** [comment]
Alright, the plugin.yml thing only is for spigot/craftbukkit.

There is a file in the jar, which I assume is copied into the plugin/dynmap directory.
permissions.yml.example

Content is :
```

# Sample permissions.yml for dynmap - trivial, flat-file based permissions for dynmap features
# To use, copy this file to dynmap/permissions.yml, and edit appropriate.  File is YAML format.
#
# All operators have full permissions to all functions.
# All users receive the permissions under the 'defaultuser' section
# Specific users can be given more permissions by defining a section with their name containing their permisssions
#   All permissions correspond to those documented here (https://github.com/webbukkit/dynmap/wiki/Permissions), but
#  do NOT have the 'dynmap.' prefix when used here (e.g. 'dynmap.fullrender' permission is just 'fullrender' here).
#
defaultuser:
  - render
  - show.self
  - hide.self
  - sendtoweb
  - stats
  - marker.list
  - marker.listsets
  - marker.icons
  - webregister
  - webchat
  #- marker.sign

#playername1:
#  - fullrender
#  - cancelrender
#  - radiusrender
```

Try to rename this file into permissions.yml (remove the .example part), and uncomment the -marker.sign lign.
Then reboot server and try placing a sign.

I don't know at all forge servers so I'm trying blindy here, tell me if there is any error anywhere.

**Comment by Cubox-** [comment]
I don't know then. I'll let a plugin dev help you

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
