### ISSUE TITLE
[wishlist] Autostart fullrender, pause if players logging in, resume otherwise

### ISSUE THREAD

**Issue by DDzwiedziu** [webbukkit/dynmap#2261]
I'm asking for such feature, because on weaker rigs (namely my i7-2600K) the rendering causes server lag and hinders gameplay. As the server is not utilized 24/7 this would use the spare cycles when they're available.

**Comment by Pingger** [comment]
I might point you to the configuration.txt ... there is a setting causes fullrender to pause once there <setting> players on the server, if set to 1 rendering will pause when any player is connected and will continue once the play leaves. 
for initially autostarting the fullrender I can point you to https://dev.bukkit.org/projects/bukkitcron?gameCategorySlug=bukkit-plugins&projectID=292481 which allows you to just periodically run the fullrender command. When the fullrender is already running dynmap effectivley ignores it, when no fullrender is running, it starts a new fullrender.

**Comment by Derkades** [comment]
>if set to 1 rendering will pause when any player is connected and will continue once the play leaves.

When I set the player limit to 1, dynmap pauses the render when a player joins, but it doesn't resume render(s) when all players have left.
