### ISSUE TITLE
[1.12.2] [Forge] Biomes o' Plenty. Again.

### ISSUE THREAD

**Issue by Hexawolf** [webbukkit/dynmap#2262]
![map](https://i.imgur.com/8Dt2xZp.png "map")

Basically, #2077 #1955 #1392 #2077

Do you guys have any plans on finally fixing this? I heard you were working on some magic system that uses jsons from mods to gather textures, is there any real progress since 2017?

**Comment by Starivari** [comment]
Need the DynmapBlockScan.
http://www.dynmap.us/builds/DynmapBlockScan/

**Comment by durand1w** [comment]
Question on that tool.  Do you run it once in a single player and then dump output files to the renderdata directory, or should it be installed permanently like any other mod?  I tried running it prior to our 1.12.2 upgrade last week and it was stuck in a loop on startup.

**Comment by durand1w** [comment]
Thanks.  I started up a new test world without any dynmap, and had the same result.  It doesn't like something regarding textures, so I'll open a new issue.

**Comment by generrosity** [comment]
dynmap + blockscan works for most people. OP says he was looking at opening a new issue, so closing this one.
