### ISSUE TITLE
Failed to open blockstate

### ISSUE THREAD

**Issue by Starivari** [webbukkit/dynmap#2264]
Not sure why it's not loading these blockstates...
I've wiped dynmap, tried to start over a few times...
Leaving some areas unrendered
I have the Dynmap-2.6-beta-1-forge-1.12.2.jar with DynmapBlockScan-3.0-alpha-1-forge-1.12.2.jar

Blockstate Errors:
[Error.txt](https://github.com/webbukkit/dynmap/files/2199450/Error.txt)

Full Startup Log:
[fullstart.txt](https://github.com/webbukkit/dynmap/files/2199453/fullstart.txt)

**Comment by Starivari** [comment]
Found the Dynmap 3.0 Alpha for 1.12.2, everything seems to be rendering now, 
Still getting same blockstate errors, but is rendering now!

I'm guessing black spots are just holes in ground?
My map is here: https://craftymines.tk/map/

**Comment by Starivari** [comment]
So after some digging, I found the Dynmap 3.0 Alpha to match the DynmapBlockScan.

Now most tiles are rendering!
Looks like just quicksand is not rendering.

My Map: [CraftyMines Map](https://craftymines.tk/map)

Might be this:
[02:13:50] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] biomesoplenty:assets/biomesoplenty/blockstates/sand.json : Failed to open blockstate

This might also cause invisable blocks?
[02:13:50] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] biomesoplenty:assets/biomesoplenty/blockstates/hot_spring_water.json : Failed to open blockstate

This looks like something...
`[02:13:52] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] Unresolved texture ref: #edge
[02:13:52] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] { parent=twilightforest:block/util/dummy ambientOcclusion=true textures={particle=blocks/soul_sand}}
[02:13:53] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] Unresolved texture ref: #edge
[02:13:53] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] { parent=twilightforest:block/util/dummy ambientOcclusion=true textures={particle=blocks/soul_sand}}
[02:13:53] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] Unresolved texture ref: #edge
[02:13:53] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] { parent=twilightforest:block/util/dummy ambientOcclusion=true textures={particle=blocks/soul_sand}}`

Attached new startup log

[fullstart.txt](https://github.com/webbukkit/dynmap/files/2201368/fullstart.txt)

**Comment by Enverex** [comment]
Same here, latest versions of Dynmap and Blockscan from the Builds folder. Seems to eccho a "failed to open blockstate" message for every single block in the game.

**Comment by davidsiaw** [comment]
> So after some digging, I found the Dynmap 3.0 Alpha to match the DynmapBlockScan.
> 
> Now most tiles are rendering!
> Looks like just quicksand is not rendering.
> 
> My Map: [CraftyMines Map](https://craftymines.tk/map)
> 
> Might be this:
> [02:13:50] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] biomesoplenty:assets/biomesoplenty/blockstates/sand.json : Failed to open blockstate
> 
> This might also cause invisable blocks?
> [02:13:50] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] biomesoplenty:assets/biomesoplenty/blockstates/hot_spring_water.json : Failed to open blockstate
> 
> This looks like something...
> `[02:13:52] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] Unresolved texture ref: #edge [02:13:52] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] { parent=twilightforest:block/util/dummy ambientOcclusion=true textures={particle=blocks/soul_sand}} [02:13:53] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] Unresolved texture ref: #edge [02:13:53] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] { parent=twilightforest:block/util/dummy ambientOcclusion=true textures={particle=blocks/soul_sand}} [02:13:53] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] Unresolved texture ref: #edge [02:13:53] [Server thread/INFO] [DynmapBlockScan]: [DynmapBlockScan] { parent=twilightforest:block/util/dummy ambientOcclusion=true textures={particle=blocks/soul_sand}}`
> 
> Attached new startup log
> 
> [fullstart.txt](https://github.com/webbukkit/dynmap/files/2201368/fullstart.txt)

Hey @Starivari could you tell me which versions of Dynmap and DynmapBlockScan are you using? Specifically the filenames ?

**Comment by kotoroshinoto** [comment]
I am still getting this kind of message on 4/26/2019 using Dynmap-3.0-beta-3-forge-1.12.2.jar and DynmapBlockScan-3.0-beta-1-forge-1.12.2.jar on All-The-Mods-3 remix + 9 mods

omlib-1.12.2-3.1.0-224.jar
ReWIRED-1.0.4.jar
ProjectIntelligence-1.12.2-1.0.4.17-universal.jar
zombieawareness-1.12.1-1.11.16.jar
openmodularturrets-1.12.2-3.1.0-326.jar
cyberware-1.12.2-0.2.10.15.jar
coroutil-1.12.1-1.2.31.jar
ICBM-classic-1.12.2-3.3.0b63.jar
SGCraft-2.0.0-beta-6.jar

quite a number of these unable to open blockstate messages in the log.

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
