### ISSUE TITLE
[Feature Request] Banner Markers

### ISSUE THREAD

**Issue by durand1w** [webbukkit/dynmap#2266]
I wanted to throw out a possible change to improve how forge markers are implemented.  Suggestion below is after having looked at what is possible today inside the code for 1.12.2.

-Use of signs for forge markers would be deprecated.
-Dynmap updated to use Forge block PlaceEvent from BlockEvent class.
-If Block equals Standing Banner (marker set 1) or Wall Banner (marker set 2).
-And If TileEntityBanner getCustomName is not null.
-Get TileEntity Custom Name, Banner Base Color and Block/TileEntity Position.

Instead of trying to allow for all the unique icon sets by name, you would simply have sets of 16 colored icons.  Circles, Squares, Stars, Flags.  
-Let the configuration file define which of the available sets to use for either Standing or Wall Banners.

Have the icons removed by listening for On Block Break Event if it is a Banner with a Custom Name and if  the Existing location is saved in Dynmap marker list.

I'm not sure if there would be support for naming a Banner and not breaking/re-placing it to trigger the event.

**Comment by ryantheleach** [comment]
I'd love to see support for using Custom Banners as markers with custom icons, not just on Forge.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
