### ISSUE TITLE
Server Crash with Dynmap-2.6-beta

### ISSUE THREAD

**Issue by BonaireDreams** [webbukkit/dynmap#2269]
Dynmap-2.6-beta-1-forge-1.12.2 downloaded today
DynmapBlockScan-3.0-alpha-1-forge-1.12.2 downloaded today
Forge 1.12.2-14.23.4.2732

Crashed on server start. 
Completely deleted /dynmap folder. Same crash.
Replaced dynmap folder from back, switched back to Dynmap-3.0-alpha-1-forge-1.12.2
Server stable.

[crash-2018-07-17_17.23.18-server.txt](https://github.com/webbukkit/dynmap/files/2203833/crash-2018-07-17_17.23.18-server.txt)

Let me know if there are any other logs you need that may be helpful.

**Comment by generrosity** [comment]
Just to chip in - I understand they must be the same. I'd also suggest using the HEAD versions as they are typically rock solid

**Comment by BonaireDreams** [comment]
Thanks for that. i somehow completely missed the HEAD versions when I was looking through the downloads. Working great now.
