### ISSUE TITLE
[QUESTION] Model support?

### ISSUE THREAD

**Issue by BonaireDreams** [webbukkit/dynmap#2270]
Will dynmap ever be able to support models such as Immersive engineering tanks/machines, Immersive railroading tracks/machines, Draconic Evolution energy spheres etc etc. Or is that just not feasible?  Not a big deal, just wondering if its even technically possible and on the roadmap for future development.

**Comment by generrosity** [comment]
Quick answer yes, but only if the mod supports the standard minecraft modelling system. Mods like 'statues mod' work out of the box, putting little zombie statues directly on the map with the correct shape and transparencies and textures.

Unfortuantely this isn't something that can be supported from the Dynmap end, and the one dev is focused on getting 1.13 over the line (and 1.14 after that) - best to hit up the mods themselves and see what modelling options are available from their side.
