### ISSUE TITLE
Not loading Page ... ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by rotus1122334455** [webbukkit/dynmap#2278]
**Hi I am configuring the plugin in a server and : ERR_EMPTY_RESPONSE    This server is in a shared hosting provider**
I am using port 25699 which is open ...
 here is my config : https://pastebin.com/aSMpq4EX
 here is my log : https://pastebin.com/fXdws5iW

**How do I fix it ?**

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
