### ISSUE TITLE
How are the webserver files downloaded?

### ISSUE THREAD

**Issue by TomSputz** [webbukkit/dynmap#2279]
Sorry to be a nuisance, but while looking through the code, hoping to add something, I found myself with a bit of a roadblock - where are the webserver files hosted? I can't for the life of me figure out where the code for setting up that folder is. As there are no direct references to the text in it I have to assume they are downloaded from some server on first start? It would be great to know where they are downloaded from

**Comment by masterX244** [comment]
Found them inside the jar inside the extracted/web folder. Extraction path creation is probably done by string concatenation so no full string can be found inside the sourcecode directly.
