### ISSUE TITLE
Dynmap Block Scan missing renders

### ISSUE THREAD

**Issue by TakunSho** [webbukkit/dynmap#2285]
I'm running 3.0 alpha for both the map and block scan. When doing a render, I have found that some items are either not rendering, or rendering incorrectly.

Here is a list of what I have found so far:
https://imgur.com/a/xkYdX3c
The mods affected are:
Streams, Traverse, Better with Mods, Better with Addons, Tinker's Construct, Totemic, and vanilla.

For reference:
Minecraft 1.12.2
Forge: 2707
Modpack: Sevtech Ages 3.0.8
Dynmap: 3.0a
BlockScan: 3.0a

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
