### ISSUE TITLE
Dynmap with a lot of tiles returning Error 404

### ISSUE THREAD

**Issue by simonchow96** [webbukkit/dynmap#2287]
I have set it following your instructions provided here: https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server . Everything looks great except an issue, which I know I asked before but cannot find back the solution.

[https://www.synercraft.net/maps/watersuno/](https://www.synercraft.net/maps/watersuno/)
When you browse this dynmap it looks properly; yet, when you switch to the develop console there are many error 404 for the tiles. I have tried purging the world (/dynmap purgeworld world) and running a full render again, reinstalling the plugin, purging the cache, and even re-copying the whole web folder (except the tiles folder of course); but nothing works.

Please advise if you need any further information. Thank you!

Spec:
OS: Ubuntu 17.10
Web Server: Apache2
Minercraft server kernel: Spigot 1.11.2 (both)
Dynmap Version: 2.5-Dev201706100401 (both)

Config: https://hastebin.com/jamoxamufo.shell
Apache2 site config: https://hastebin.com/docomoweti.apache (I have used symbolic link to the respective tiles folder, and my third dynmap works perfectly so I think it's not the case.)

**Comment by mikeprimm** [comment]
Just how it works - I don't specifically have a way to know which tiles exist on the client side other than trying to load them, and handling the fact that they aren't there.
