### ISSUE TITLE
Using SSL with the MySQL connection options

### ISSUE THREAD

**Issue by nate2014jatc** [webbukkit/dynmap#2289]
Hi there,
I'm trying to accomplish one of two things;
1). Disable the SSL check on the connection between DynMap and my MySQL database WITHOUT globally disabling SSL checks on ALL connections.
or
2). Tell the DynMap plugin to use SSL on it's connection ,and provide it with a keystore that says my certs are valid.

I get the following message whenever I spin up the server with SSL enabled in the MySQL config.
```
[02:10:25] [Server thread/INFO] [STDERR]: [com.mysql.cj.log.StandardLogger:logInternal:308]: Wed Aug 15 02:10:25 MDT 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

we're running a `forge-1.12.2-14.23.4.2705` server and using version `Dynmap-2.6-beta-1-forge-1.12.2` in conjunction with `DynmapBlockScan-3.0-alpha-1-forge-1.12.2.jar `

**Comment by ArVdC** [comment]
Hi,
Did you try to put the SSL params after the database name ?
_database: yourDbName?useSSL=false_
With the last update, i think its needed to put a '&' at the end of the line, because dynmap adds an invisible 'autoReconnect=true' value at the very end :
_database: yourDbName?useSSL=false&(autoReconnect=true)_
I suggest you to add an 'allowMultiQueries=true' value at the same place :
_database: yourDbName?useSSL=false&allowMultiQueries=true&(autoReconnect=true)_

**Comment by nate2014jatc** [comment]
Adding the suggested text yields the following results.
`[11:43:24] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Error updating Maps table - Cannot load connection class because of underlying exception: com.mysql.cj.exceptions.WrongArgumentException: Malformed database URL, failed to parse the connection string near '?allowReconnect=true'.`

(I apologize for broken formatting, I'm replying via email) 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nate2014jatc** [comment]
Configuration used is as follows.

```
  type: mysql
  hostname: localhost
  port: 3306
  database: dynmap?useSSL=false&allowMultiQueries=true&
  userid: dynmap
  password: ******
  prefix: "MCR"
```

**Comment by nate2014jatc** [comment]
@ArVdC Sorry to ping you, but I haven't heard back from anyone.

**Comment by derimagia** [comment]
it looks like flags can now be set in the configuration: https://github.com/webbukkit/dynmap/blob/ee20ea84e04ed80a1cb78a9525e6404cfcfa48c1/spigot/src/main/resources/configuration.txt#L36

And it's used here in the code: https://github.com/webbukkit/dynmap/blob/v3.0/DynmapCore/src/main/java/org/dynmap/storage/mysql/MySQLMapStorage.java#L284

I confirmed this seemed to be setting it properly for me
