### ISSUE TITLE
Right sidebar unusable on mobile in web ui

### ISSUE THREAD

**Issue by Xayer** [webbukkit/dynmap#2291]
Hi. You can't hover on mobile, and therefore you can't toggle the right sidebar. It's pretty easy to fix for me as I work with web development. So if anyone can guide me in the right direction as to where I can fix this, then I'd be happy to suggest a solution to this problem.

**Comment by TomSputz** [comment]
Feel free to fork the mod, and recompile it (I'd use eclipse) if you want people to be able to use your version. If you just want to have a better ui for yourself though, the webroot is in `[serverdir]/plugins/dynmap/web`

On a related note, I'd really reccomend to switching to directly hosting with nginx if you're hosting this for any length of time, the server load it generates is ridiculous

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
