### ISSUE TITLE
[Feature Request] Do-It-Yourself Decorative Blocks support

### ISSUE THREAD

**Issue by whocallmetim** [webbukkit/dynmap#2297]
Could you make Dynmap for Forge compatible with the [Do-It-Yourself Decorative Blocks](https://minecraft.curseforge.com/projects/do-it-yourself-decorative-block) mod?

Thanks.

**Comment by FedUpWith-Tech** [comment]
Assuming this is added in a later release of dynmap blockscan or otherwise no longer relevant- please open a new issue if this persists.
