### ISSUE TITLE
[Question] Dynmap Block Scan

### ISSUE THREAD

**Issue by NJDaeger** [webbukkit/dynmap#2299]
Will/has dynmap block scan been implemented into dynmap? I'd really like for some of my blocks in my texturepack use the models I have set for them.

**Comment by mikeprimm** [comment]
That's the plan - once I get some time, the goal for DynmapBlockScan was always to incorporate it in as a fundamental feature of Dynmap v3.x.  While it has been worked on, it was not really what I'd call 'production ready', so I didn't want to hamstring use of the stable, production-grade Dynmap with it as a built-in feature.

**Comment by NJDaeger** [comment]
Okay, thank you for the info and all your work!
