### ISSUE TITLE
Dynmap Rendered Redstone wrong

### ISSUE THREAD

**Issue by Sugar250** [webbukkit/dynmap#2301]
This is what the redstone look like in game.

![image](https://user-images.githubusercontent.com/21377465/44619533-96ab6b00-a8ba-11e8-86bf-206f0ba1e031.png)

And this is what it look like in dynmap website:

![image](https://user-images.githubusercontent.com/21377465/44619540-c6f30980-a8ba-11e8-8f91-2aca1e1f65a2.png)

The direction of redstone is wrong.

Server is running **CraftBukkit version git-Spigot-fe3ab0d-f41aae4 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)**

Dynmap version : **core=3.0-SNAPSHOT-55, plugin=3.0-SNAPSHOT-55**

PS:
And also the Glass.

In Website:

![image](https://user-images.githubusercontent.com/21377465/44619572-83e56600-a8bb-11e8-8287-8c405c965ca0.png)

In game:

![image](https://user-images.githubusercontent.com/21377465/44619580-96f83600-a8bb-11e8-883c-b3dfee728d7e.png)

**Comment by Sugar250** [comment]
Another wrong example：

In Game:

**Comment by mikeprimm** [comment]
Fixed in v3.0-alpha-2
