### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by xopez** [webbukkit/dynmap#2302]
After a specific time i get always following error in Firefox. I have to restart the server to make it work again.
Dynmap version: core=3.0-SNAPSHOT-55, plugin=3.0-SNAPSHOT-55
Spigot 1.13
EDIT: OK, SSL doesn't seem to work even after restart. On http / unsecured it's working.

**Comment by mikeprimm** [comment]
I don't specifically supply or support SSL - there is nothing in the Dynmap code that is specific to SSL, and the internal server doens't support it.  How are you configuring SSL?

**Comment by xopez** [comment]
thats the point. Forgot that it have to be extra configured at another port. My Bad. Case closed
