### ISSUE TITLE
Dynmap-Head-spigot-1.13.jar fails with Spigot 1.13.1 build

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#2303]
Spigot just released 1.13.1 and updated my 1.13 test server to see which plugins will still work and found that Dynmap again was impacted due to recent changes in Spigot/Mojang code.
![image](https://user-images.githubusercontent.com/10309346/44627835-bb2b3580-a902-11e8-8cd4-b237d314bf13.png)
![image](https://user-images.githubusercontent.com/10309346/44627836-c0888000-a902-11e8-9475-cb12957c6a0a.png)

**Comment by mikeprimm** [comment]
Yep - 1.13.1 has more internal changes than you might expect.  Just finishing adding support now - should be ready as a dev build in a few minutes.

**Comment by mikeprimm** [comment]
Latest development build now supports 1.13 and 1.13.1.  Both will be in 3.0-alpha-2, which I expect to release tonight sometime....
