### ISSUE TITLE
Full render skips large sections of the map

### ISSUE THREAD

**Issue by lagnat** [webbukkit/dynmap#2304]
I've seen some similar discussions as it relates to world borders.  I'm seeing the issue still and nowhere near any world border.  I force renders by placing and destroying blocks, and when I issue the full render, those areas are gone again.  

Attached is a picture that shows this issue.  The rendered chunks of that very large structure in the center were forced to render by placing and removing some blocks.  After a full render, it's totally gone.

Edit:  I've seen this issue from the start of the 1.13 builds and all through the latest code and 1.13.1.

![screen shot 2018-08-26 at 9 53 34 pm](https://user-images.githubusercontent.com/2048655/44636759-7c859180-a97b-11e8-9646-bf55e731b565.png)

**Comment by smmmadden** [comment]
have you updated Dynmap to the latest alpha version?

**Comment by lagnat** [comment]
Using latest master as of a few hours ago

**Comment by mikeprimm** [comment]
fullrender has never been able to skip over breaks in the world data: the generated chunks need continuity, so teleporting someplace and creating an 'island' of generated chunks doesn't work, by default,  If you issue a fullrender pr the like using a character located at the given patch, it'll render it, but MC lacks any supported way to find the range of valid chunks that exist (and trying everything isn't an option for MC worlds that are allowed to potentially be hundreds of millions of blocks across), so chunks are found and rendered via a 'flood fill' style algorithm starting from spawn.

**Comment by Sikatsu** [comment]
Is there anyway to fix this? I also seem to have a weird fullrender.

http://mc.villagercraft.nl:8050

**Comment by lagnat** [comment]
Perhaps you could look at the region file names to discover what chunks to render for a full render, but going by your reply above, this is working as designed.
