### ISSUE TITLE
closed trapdoors are rotated incorrectly

### ISSUE THREAD

**Issue by NJDaeger** [webbukkit/dynmap#2310]
![image](https://user-images.githubusercontent.com/18237863/44818296-92cb6180-abb6-11e8-8c18-65d43a2f9998.png)
The trapdoors which are not on the ground in the picture provided are supposed to be closed against the block its surrounding. They are rotated incorrectly it seems.

**Comment by einargizz** [comment]
I have the same issue.
Am currently testing 3.0-alpha-3

It seems like there's a default alignment on the trapdoors, that doesn't represent the actual open/closed alignment.

How it looks like on map:

![screenshot 2018-09-04 21 57 54](https://user-images.githubusercontent.com/2683765/45060326-ea723d00-b08e-11e8-85ad-7f3a8ae61f4c.png)

In game:

![screenshot 2018-09-04 21 56 20](https://user-images.githubusercontent.com/2683765/45060334-f3630e80-b08e-11e8-9eef-4389d998dbe6.png)

In game, with trapdoors in an "open" position:

![screenshot 2018-09-04 21 57 14](https://user-images.githubusercontent.com/2683765/45060350-01189400-b08f-11e8-9508-8b268b024d86.png)

**Comment by smmmadden** [comment]
yes, they do appear to be off on mine as well.  I didn't have any lamps set up, but added a few blocks with the trap doors on them (closed position) and it shows as open on the map and not the same orientation.

**Comment by einargizz** [comment]
Ok. So I was looking at this some more and it looks like the doors are in the right position, when horizontal, but when you flip them to vertical position, the axis of rotation is on the wrong edge.

![45062922-bbfa5f00-b09a-11e8-890a-2397950d4ed4](https://user-images.githubusercontent.com/2683765/45194563-16ceba80-b243-11e8-888f-c9deb490b9fc.png)

It would probably be fixed by rotating the texture 90 degrees clockwise.

**Comment by smmmadden** [comment]
You are correct.  After changing the perspective I can finally see close up and notice that the orientation and current state are not the same.
![image](https://user-images.githubusercontent.com/10309346/45253967-74dfc880-b33d-11e8-87cc-b06b70fec220.png)

**Comment by einargizz** [comment]
This issue was fixed in v3.0-beta-1, so I think this ticket can be closed.
