### ISSUE TITLE
Black Screen when login-enabled: false

### ISSUE THREAD

**Issue by Psy-Virus** [webbukkit/dynmap#2312]
Hey there,
when you disable the login feature by setting `login-enabled: false`, dynmap looks for the tiles in the wrong web path and creates 404s. Using HEAD versions of Dynmap for 1.7.10; 1.10.2; 1.12.2

The path, Dynmap checks for tiles: `[...]/dynmap/1.7.10/tiles/`
The path, set in the dynmap config: `[...]/dynmap/1.7.10/`

Dynmap also doesn't auto update and the login-button is not hidden.

weird but funny.
The following issues are probably related: #1887 (shitty to read); #2222; #2254

Have fun fixing^^

**Comment by Psy-Virus** [comment]
I thought that it's maybe worth it, checking the dev console in my browser for more info and I found this:
If the login is disabled, dynmap doesn't format the GET request for tiles.php. I am digging around but I still don't see, where this could happen.

on `login-enable: true`: domain.tld/standalone/tiles.php?tile=world/world_flat/1_1/zz_32_32.png&ts=1535817212058
on `login-enable: false`: domain.tld/tiles/world/world_flat/13_-11/420_-326.png

**Comment by Psy-Virus** [comment]
So, when I configure the url: section in the config.txt to the stuff from the working config.js, it works.
@mikeprimm, is it by design or it this a bug?

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
