### ISSUE TITLE
Dynmap 3.0 Snapshot  forge 1.12.2

### ISSUE THREAD

**Issue by durand1w** [webbukkit/dynmap#2319]
I noticed the latest upload of Dynmap and decided to test with the Dynmap Block Scan for Forge 1.12.2 2705.  Rendering and performance seem to be greatly improved, no issues with the block scanner running on startup.  

The only issue I would note is that I believe that petrified wooden slabs are not rendering.  Mojang did not include a texture for those for 1.12.2, so not really surprising.  

Thank you for the update!

**Comment by mikeprimm** [comment]
Unless I'm mistaken, petrified wood slabs are a 1.13 block - are you using a mod or the like to include them in 1.12.2?

**Comment by durand1w** [comment]
Hey Mike,

The petrified oak wood slabs have actually existed in the game for many years.  When slabs were first introduced, they had a release where the hardness was incorrectly set to stone and they would not stack with other oak wood slabs.  You have to mine these with a pickaxe.  With the 1.12 changes, they forgot about this old issue in existing world, and the item texture is missing.  For 1.13 they corrected that and the renamed them.

Here you can several buildings where the roofs were constructed with recycled petrified oak wood slabs, but Dynmap has no texture to use for the slabs.

http://livemap.ambethtyr.com:32177/?worldname=world&mapname=surface&zoom=6&x=-911&y=64&z=-2582

It's not a big issue for 1.12, but wanted to bring this up in case it's an issue for 1.13+.

**Comment by mikeprimm** [comment]
Just trying to find out the associated world data for these (block name and state information).  I don't see the blocks as placeable items in game, and no labels for 'petrified'.  I'm assuming its a command-acquired item (e.g. worldedit or the like), since it doesn't show in creative inventory.

**Comment by mikeprimm** [comment]
OK - I found it - stone_slab:2 - it SHOULD be working, and I've tried it on 1.12.2 with the latest dev build, and it looks OK.  Could you check it out?  Latest is here - http://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-forge-1.12.2.jar

**Comment by durand1w** [comment]
I tried the latest version and that seems to have corrected the issue for the area I rendered.  Thanks for following up.

**Comment by mikeprimm** [comment]
Cool - also, I'm about to release 3.0-beta-3, and just fixed a long standing problem with the chunk generation and population triggers (which was making automatic on-demand map updating as people explored more areas less reliable), so I'd definitely suggest grabbing that when you get a chance - the release candidate is here https://dynmap.us/builds/dynmap/Dynmap-3.0-beta-3-forge-1.12.2.jar
