### ISSUE TITLE
Dynmap Forge Soft-Crashes with JustEnoughIDs

### ISSUE THREAD

**Issue by SalmonSays** [webbukkit/dynmap#2322]
Forge 14.23.4.2749 Universal coupled with the latest Dynmap Forge 3.0 alpha-3 and the latest NotEnoughIDs 1.5.4.2 appears to work normally in my test server environment, but swapping out NotEnoughIDs for JustEnoughIDs results in this soft-crash immediately on starting any render:

https://pastebin.com/raw/KDDA29iW

EDIT: Likely a further result of the same problem, logging in with a client results in an actual hard-crash, as demonstrated here:

http://pastebin.com/raw/b9yCCept

**Comment by mikeprimm** [comment]
Error implies chunks loading without biome data, which is odd - but, given what NotEnoughIDs does, I suspect the NBT format of the chunks has been screwed with.  I've put in some defensive coding in the latest build, but I'll need to look at what this mod specifically does to see if it is supportable.  The 1.12 code has some hard coded assumptions around 4096 blocks that are WAY less since I reworked the 3.0 core to handle 1.13, but there are still some.

**Comment by SalmonSays** [comment]
JustEnoughIDs has a biome extension feature that NotEnoughIDs doesn't if I understand correctly, which may be partially at fault here. I brought it up with the mod author over here:

https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/30

I'm super hopeful there's a fix here- while switching back to NotEnoughID's serves as a temporary workaround, I'd prefer not to since JustEnoughIDs handles a lot of interactions in a more tasteful way.

**Comment by SalmonSays** [comment]
Scratch some of that, even though the server doesn't crash the actual render is wholly problematic whether or not PMP is installed. Here's a full render with just PMP installed alongside Dynmap and JustEnoughIDs:

https://i.imgur.com/DBhsWWD.png

The full render from running mods without PMP is equally bad:

https://i.imgur.com/WBbskUe.png

**Comment by mikeprimm** [comment]
Found some more 'only 4096 blocks max' references still in code - bopped those gophers, so latest dev build (as of a few minutes from now) should be worth trying.

Do you have a specific standard mod pack that has more than 256 biomes and/or more than 4096 blocks you can refer to?  It'd be convenient to have a 'known ok' case to test with.

**Comment by SalmonSays** [comment]
Some positive news, it's definitely launching without hard-crashing now. I'm in the process of running a render, though early results seem to indicate the map is still rendering splotchy and somewhat sporadic if admittedly evenly vertically spaced lines:

https://i.imgur.com/SiCgfzI.png

Interestingly, at just the right zoom level it appears like there's some roughly continent border shaped trends/clusters possibly happening:

https://i.imgur.com/mSwn2BV.png

A live map is up for now at least at http://map.smisc.net if you need better reference.

The modpack I'm testing against is a pretty highly customized kitchen sink-ish pack I've been setting up myself for use privately with some friends. It's about 150 mods that for the most part play nicely and (I think) compliment each other. Here's a modlist: 

https://docs.google.com/spreadsheets/d/1TCAm6FkGXCAcL65hZtvEukqqGDJbLFN2ArAHA228gQg/edit?usp=sharing

I don't know if there's a pack out there more qualified to test against, but I'm happy to let you use any resources of my own that I've got on hand for testing purposes if you need.

**Comment by SalmonSays** [comment]
Quick update- sure enough, the features I said look sort of continent-y are actually representative of a continent after matching up in-game. Here's an instance of sandy borders against water looking obviously broken but sort of traceable if you squint hard enough:

https://i.imgur.com/w55AzIr.png

It's a far cry from an actual usable render, but at least something interesting is happening that isn't a crash.

**Comment by mikeprimm** [comment]
Which build number were you running?

**Comment by mikeprimm** [comment]
Ugh - OK - the problem you are seeing is something I fixed last night, but I must not have pushed the fix to github when I called it a night :) .  I'll post an update when it is out there tonight after I get home...

**Comment by mikeprimm** [comment]
OK - new build is up - give it a spin!

**Comment by SalmonSays** [comment]
The results speak for themselves: https://i.imgur.com/r5rvSJ3.jpg

The weird tree shadows on the lower left was before I loaded in DynmapBlockScan alpha-2, and the weird missing river is from Streams-1.12-0.4.4 water not rendering as plain water, but otherwise so far I'd call this build massively successful and totally serviceable!

**Comment by SalmonSays** [comment]
I assume this is now on Blockscan- terrain from BiomesOPlenty-1.12.2-7.0.1.2399 is coming out grey:

https://i.imgur.com/twABOiO.jpg

When it should be coming out looking roughly this color:

https://i.imgur.com/Wn5ceiK.jpg

In this particular case the offending block is <biomesoplenty:grass:2> or "Loamy Grass Block" but I'm sure there's about 3 or 4 other varieties of grass experiencing the same issue

All that said, I think *tentatively* the major issues preventing launch and core functionality are ironed out against JustEnoughIDs/NEIDs- so if you'd prefer this issue can be closed and I can start a new one for basically cosmetic scan/render related issues?

**Comment by mikeprimm** [comment]
Might be a good idea, since this itself was a pretty focused issue that I think we've got resolved.  A separate focused issue will be easier for others who may be experiencing the same distinct issue to find and join in on vs report a duplicate for.  Thanks!!

**Comment by Sunconure11** [comment]
While this is a bit old, I'm going to ask in advance. Were these builds released to curse ever?
