### ISSUE TITLE
resolutions of map

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#2323]
Hi Mike, was wondering if I should see the map resolutions change between each setting and whether they would be noticable?  I did a fullrender after changing each of the settings for configuration.txt up to hi_boost_xhi where I thought it was the highest/best resolution of the map but saw no difference.
What I'm trying to see is the resolution that some are showing while zoomed in on the surface maps like the below where it shows as fuzzy (for mine) compared to in-game.
![image](https://user-images.githubusercontent.com/10309346/45093473-76fc1a00-b0e6-11e8-8180-78359b29a49c.png)
![image](https://user-images.githubusercontent.com/10309346/45093570-c93d3b00-b0e6-11e8-9e32-30b71e2bdf3c.png)
Whereas, I zoom into max and the log blocks with trapdoors are blurry.
![image](https://user-images.githubusercontent.com/10309346/45093614-ea059080-b0e6-11e8-9f81-9c0aa0e6b5a6.png)
Thanks. Steve
Do I need to actually purge the old maps and then do a fullrender?

**Comment by mikeprimm** [comment]
if you look at the '/dmap maplist <world>', you will see the settings for your maps, and can use /dmap mapset <world>:<map> to alter settings.  The resolution is based on the perspective used - which are found in the perspectives.txt file.  To juice up your resolution (remember: doubling res = 4x file size....),  you can do any of the following:

1) The standard surface map uses the iso_SE_30_hires perspective (isometric view from southeast at 30 inclination with hi resolution) - this uses a scale value of 16 (16 pixels per block edge).  Make sure your main map is using this
2) If that isn't good enough, edit the 'scale, setting for that perspective (or copy the perspective, set a new name, change the value, and change your map to use the new perspective).  Setting to scale 32 is VERY nice - 64 is really only practical for developing, but it does work....

Alternately, there is a way to 'boost' resolution around areas of interest - it involves setting the 'boost' attribute on either an 'areamarker' or a 'circlemarker' to true.  When you do that, the resolution of tiles within the area of that marker will be rendered with higher resolution of the rest of the map, by default.  This makes the 'nice' areas look nice without making the whole map 4x as big - the marker can be invisible, too, so it doesn't need to look bad.  To have it work on a map, you need to use '/dmap mapset' to set the 'boostzoom' attribute above zero: each point is a 2x boost, so boostsoom:1 means double, boostzoom:2 is 4x, 3 is 8x, etc....

**Comment by smmmadden** [comment]
Sorry for delay - been reading and reviewing the details and it was driving me nuts that every fullrender I did I was hoping the resolution was going to change even by using what you stated above to make the scale 32.  The dmap maplist I think just gave me the reason why.

> dmap worldlist
[22:49:37 INFO]: world world: loaded=true, enabled=true, title=world, center=144.0/78.0/-33.0, extrazoomout=2, sendhealth=true, sendposition=true, protected=false
[22:49:37 INFO]: world world_nether: loaded=true, enabled=true, title=world_nether, center=0.0/0.0/0.0, extrazoomout=2, sendhealth=true, sendposition=true, protected=false
[22:49:37 INFO]: world world_the_end: loaded=true, enabled=true, title=world_the_end, center=0.0/0.0/0.0, extrazoomout=2, sendhealth=true, sendposition=true, protected=false

> dmap maplist world
[22:50:13 INFO]: map flat: prefix=flat, title=Flat, **perspective=iso_S_90_lowres**, shader=stdtexture, lighting=shadows, mapzoomin=4, mapzoomout=3, img-format=default, icon=, append-to-world=, boostzoom=0, protected=false

[22:50:13 INFO]: map surface: prefix=t, title=Surface, **perspective=iso_SE_30_lowres**, shader=stdtexture, lighting=shadows, mapzoomin=4, mapzoomout=3, img-format=default, icon=, append-to-world=, boostzoom=2, protected=false

[22:50:13 INFO]: map cave: prefix=ct, title=Cave, perspective=iso_SE_60_lowres, shader=cave, lighting=default, mapzoomin=4, mapzoomout=3, img-format=default, icon=, append-to-world=, boostzoom=0, protected=false

[22:50:13 INFO]: map underwater: prefix=underwater, title=underwater, **perspective=iso_SE_30_hires**, shader=stdtexture-underwater, lighting=default, mapzoomin=2, mapzoomout=3, img-format=default, icon=, append-to-world=, boostzoom=0, protected=false

What's odd is I have the configuration.txt set to use 
deftemplatesuffix: hires

The template file for normal-hires.txt confirms the flat map to use iso_S_90_lowres which is fine, but the surface map I wanted to make sure it was using iso_SE_30_hires and noticed it does but not according to the maplist command as it shows iso_SE_30_lowres.
Shouldn't the defaulted normal-hires.txt file all have iso_S or iso_SE_30_hires ?  
![image](https://user-images.githubusercontent.com/10309346/45196162-f3971180-b228-11e8-8d48-b0855fe4f74f.png)
It would explain why every change I made to the perspectives.txt file wasn't getting picked up because there is a mismatch of which ones to use.
![image](https://user-images.githubusercontent.com/10309346/45196235-42dd4200-b229-11e8-85ab-aacd95ac00d3.png)
Should I be using the custom-perspectives.txt file and custom-shaders.txt file to make the changes or should it be on the main files?

**Comment by mikeprimm** [comment]
any of the '90' views are 'top down' (90 degrees from horizontal), so all flat maps use those (and the facing is just the rotation.  The standard cave map doesn't benefit from higher resolution (no textures), which is why it is lowres - if you shift the cave map to the 'stdtexture-cave' shader, though, a higher res would likely be in order.

The iso_SE_30_hires is the default for the 'surface' map, which is the one that uses textures and has a non-top-down perspective that really benefits from resolution: the 'flat' map can certainly be shifted to a higher resolution perspective, if you like.

As for customization: ideally, copy the definition from perspectives.txt to custom-perspectives.txt and modify it there - that will assure that I don't overwrite it if a new version alters the default settings for an existing perspective (I just about never do that, but it has happened in the past).

**Comment by smmmadden** [comment]
Thanks - I've been regenerating the maps all day with no luck including a purging of all four.  What I can't seem to get pulled in is the hires resolution for surface so when I zoom in, the detail of a oak log post with trap doors around it is blurry still.  I thought well, let me purge the map cause fullrender may not be detecting the changes to the custom-perspective or the perspective files.  I did a server restart, a dynmap reload to no avail.
![image](https://user-images.githubusercontent.com/10309346/45248032-7330e900-b2da-11e8-8168-c578bccfd988.png)
**custom-perspectives.txt file**
![image](https://user-images.githubusercontent.com/10309346/45248069-c440dd00-b2da-11e8-866a-8dcf73c490c3.png)
**configuration.txt file resolution**
![image](https://user-images.githubusercontent.com/10309346/45248080-e76b8c80-b2da-11e8-9c6a-59c15c6afb63.png)
**normal-hires.txt file for surface map**
![image](https://user-images.githubusercontent.com/10309346/45248107-2568b080-b2db-11e8-9cbe-72fab781e2d1.png)

I then decided to look for something that might be cached or holding on to the original settings and not seeing the changes.  Two files stood out.  One file (world.pending) because I paused the underwater map (given the time it takes to fully generate) and the worlds.txt file.  It was the worlds.txt file that appears to have not been updated to show the change in perspective.  I've attached here in case you see something that I've missed (which is definitely possible), but the question now is, shouldn't the changes I made have been reflected in this file?  Or is this file another one I have to manually update to reflect the other changes?  Will it get overwritten if I make changes to it directly and reload the plugin or restart the server?

Thanks for your patience - this has been a great learning experience trying different settings zooms, boosts, etc., though I haven't me the original goal in making blurry scenes disappear. :-) -Steve
[worlds.txt](https://github.com/webbukkit/dynmap/files/2362840/worlds.txt)

**Comment by smmmadden** [comment]
I decided to give it a shot and update the worlds.txt file to make surface using the iso_SE_hires and regenerated the map.  As expected, now the resolution is crystal clear.
![image](https://user-images.githubusercontent.com/10309346/45253895-4f9e8a80-b33c-11e8-9a8b-beeeaf369b23.png)
So I think it confirms that we're not updating the worlds.txt file when the configuration files have been updated.
