### ISSUE TITLE
Dynmap Rendering Colors From Some Modded Blocks Incorrectly

### ISSUE THREAD

**Issue by SalmonSays** [webbukkit/dynmap#2325]
I'm currently only able to reproduce/notice this with BiomesOPlenty-1.12.2-7.0.1.2399 and not any other specific mods as of yet, but colors are coming out flat/grey from the added grass types:

https://i.imgur.com/twABOiO.jpg

Here's a sample of what some of that grass on the upper right actually looks like:

https://i.imgur.com/Wn5ceiK.jpg

In this particular case the offending block is biomesoplenty:grass:2 or "Loamy Grass Block" but I'm sure there's about 3 or 4 other varieties of grass also from BoP experiencing the same issue.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
