### ISSUE TITLE
Dynmap Block Scan Missing Some Special-Case Modded Blocks

### ISSUE THREAD

**Issue by SalmonSays** [webbukkit/dynmap#2326]
Certain slightly more exotic/unique blocks are missed by Dynmap Blockscan and might require special exceptions/handling.

The first mod to note is DynamicTrees-1.12.2-0.7.8, the most current release/non-alpha build as of writing. Here's an example of Dynamic Trees in-game:

https://i.imgur.com/3hchuOS.jpg

And their appearance (or rather lack of) on a map render:

https://i.imgur.com/PoktBSy.png

This is admittedly not a major issue in that the leaves are enough to give trees readability on a map, but I figured it was worth noting. Since using the actual item models would be a headache/nightmare it might be worth exploring replacing their instances with regular logs. Grabbing any part/thickness of the branch from this Biomes O Plenty dynamic Willow Tree in creative results in the same <dynamictreesbop:willowbranch> item being granted.

The other problem child of a mod I've run into is Streams-1.12-0.4.4. It acts as a directionally flowing water source much like how a single vanilla liquid source block tapers and carries objects over a flat surface, only it continues to do so while flat and next to similar source blocks. It looks like this in-game:

https://i.imgur.com/REwel3w.jpg

Here's what they look like on a map render:

https://i.imgur.com/QBt0RmZ.png

In this particular instance I'm unable to grab a source block from in-game to reference the item name because it doesn't appear to be obtainable/place-able by players. Ideally it'd just use the default water texture.

**Comment by generrosity** [comment]
Yea, anything with a custom non-full-block shape won't render. Possible that the water is custom rendered or custom textured (like chisel) that is different from vanilla techniques.

Your server logs would confirm as it scans the blocks which it is and why it can't render

**Comment by Too-DAMN-Much** [comment]
it happens with full block shapes as well, load up the mario mod 2 and find it's biome and see that every ground block added by that mod is unrenderable by dynmap as well.

**Comment by generrosity** [comment]
Again, possible that the ground blocks use a different rendering mechanism than what vanilla uses.

As such, I think I've seen that the dynmap maker retired, and was pulled out for something specific, and miss like Chisel recognise that they don't render per spec and are planning to fix it their side. 

It might be worth telling the mario mod ppl. And confirming against other mapping mods

**Comment by Too-DAMN-Much** [comment]
@generrosity it's been quite a few months or i'd accept that as an excuse.

**Comment by generrosity** [comment]
Unfortunately, that's the kind of reason why he got out of the modding community; "modder burnout"... especially if people are particularly unwilling to be open with how much they appreciate the free mod. 

I think the only reason he is still working on it is that 1.13 looks to be the big change to file structure that should last for a number of years, at which point he might return

I for one am appreciative of the map working at all, let alone with 97% of the 300 mods on my server. And noone should be relying on the maps as anything more than a cool display and helper. 

If you have time, the code *is* open source, so you can roll your sleeves up and contribute too - every little bit helps, and yes nonmodders can read code enough to figure out where a bug is

**Comment by Too-DAMN-Much** [comment]
i've never willingly ran a server without dynmap, how's that for a recommendation, i just wish we could get some fixes to essential bugs rendering it totally unusable, what say you @mikeprimm ???

**Comment by generrosity** [comment]
I think it's a little unkind to say a few missing modded blocks make the whole thing "totally unusable".

**Comment by Too-DAMN-Much** [comment]
i also never got any help with the issue of dynmap perpetually stalling the server instead of shutting down on mineos.

**Comment by generrosity** [comment]
There are configurations so that dynmap is not as active on underpowered servers (and you run a daily or weekly fullrender to get things underway). There are a dozen java parameters I could recommend that helps performance, and a dozen mods that help with performance and avoiding people dropping off or timing the server out (watchdog etc).

I haven't got signs working either, but then I haven't looked into the various permission systems that are needed to activate that particular feature. I have an old feature request to bypass it but more likely I'll code it and submit it myself later this/next year.

**Comment by Too-DAMN-Much** [comment]
as far as i can tell through the config spaghetti of this mod i have done everything possible to activate sign markers.

**Comment by Too-DAMN-Much** [comment]
Except it's simply being honest if you recall pahimar a forgecraft developer stated there was no way he would ever understand the config because it's as hard as coding.

**Comment by Too-DAMN-Much** [comment]
all i'm doing here, is stating the obvious, a mod which has no development effort going into furthering it, fixing nothing and improving exactly jack fucking shit, is dead, end of discussion.

**Comment by Too-DAMN-Much** [comment]
the mod is a fucking joke at best, fix the config spaghetti if you ever want people to stop laughing at your mod mike, it's literally actively driving people away because you are too lazy to do anything to make the mod usable.

plus that whole refusal to fix critical bugs issue that some of you fucktards (@generrosity ) have apparently already forgotten about....

**Comment by generrosity** [comment]
Sorry - you are wrong on all accounts, and I can see you getting other mod authors from AdvancedRocketry and JED also telling you to pull your head in and stop being so entitled 😜

Winding yourself up and unleashing on the internet isn't going to help anyone - we have measureable proof its people like you that drive modders to quit. I'm not sure how modders force users to quit - they vote with their feet and use something else - there are plenty of options out there.

So - again - if its a joke, and driving you away ... please go? 😜
