### ISSUE TITLE
No full rendering

### ISSUE THREAD

**Issue by Hobbit041** [webbukkit/dynmap#2327]
I execute commands /dynmap fullrender or /dynmap radiusrender 4000 with my WordBorder turned on or off, but instead of rendering 8000 blocks "radius render of 'world' finished" at small square http://pastexen.com/i/6Ro2JTSk8H.png

**Comment by mikeprimm** [comment]
Have you done a '/wb fill' type of operation?  Dynmap doesn't generate chunks - it only renders chunks that have been generated - whether by player activity, world editors, or things like the WorldBorder fill function.  For 1.13, the current WB has a bug that prevents proper chunk generation for all chunks - to do it properly, be sure to run it with the 'force' option.  After that, a dynmap fullrender or radiusrender should get the job done.

**Comment by vlcty** [comment]
I had the same problem and a force fill fixed it for me. Thanks :-)
