### ISSUE TITLE
Dynmap "y out of range (expected 0-255, got 256)"

### ISSUE THREAD

**Issue by Puggetty** [webbukkit/dynmap#2329]
Hello,
I've switched to PaperSpigot which is probably causing the issues but I was wondering if anyone could tell me how to fix it:
 I load up the server and get this:
`Enabled plugin with unregistered PluginClassLoader dynmap v3.0-alpha-3-111`
Dynmap then tells me this:
`[dynmap] Exception during render job: world=world, map=null`
And spits an error in console like this:
https://pastebin.com/cqzwHcE8 
Any help is appreciated!
Thanks

**Comment by mikeprimm** [comment]
Got it - fix is building now - get latest dev builds from http://dynmap.us/builds/dynmap in a few minutes :)

**Comment by Puggetty** [comment]
thanks mike :)

**Comment by mikeprimm** [comment]
Build is out there now - let me know if it handles the issue
