### ISSUE TITLE
Bug Button Dynmap

### ISSUE THREAD

**Issue by TheCalypso** [webbukkit/dynmap#2330]
Hello,

I found a bug on my dynmap, I explain. The buttons are changed by blocks of wood or stone if the button is a wood button or stone button. Can you fixed this bug ?

Thank you very much, and all my congratulation to you, it's a great job !

TheCalypso

**Comment by mikeprimm** [comment]
Version info?  You guys doing Spigot 1.13.1 with Dynmap 3.0-alpha-3?

**Comment by mikeprimm** [comment]
Dup of #2331 - problem addressed in dev builds
