### ISSUE TITLE
Most buttons do not render correctly. [More in depth information in ticket]

### ISSUE THREAD

**Issue by NJDaeger** [webbukkit/dynmap#2331]
There was a ticket formed about two hours before mine which was about a bug with buttons (#2330 ). I figured I would make a new ticket with a deeper look at what is happening behavior wise.

From what I have observed, this is the following behavior:
---
**On ceilings/floors:**
- All buttons facing downwards render as their respective base block. (Eg spruce button = spruce planks)
- Buttons which are on the ground facing west render as if they're on the ground facing north
- Buttons which are on the ground facing south render as if they're on a wall facing west
- Buttons which are on the ground facing east render as their respective base block
- Buttons which are on the ground facing north render as if they're on a wall facing east
---
**On walls:**
- Buttons which are on a wall facing west render as if they're on the ground facing north
- Buttons which are on a wall facing east render as their respective base block
- Buttons which are on a wall facing north render as if they're on a wall facing east
---
Here's the expected behavior in game:
![2018-09-08_15 07 50](https://user-images.githubusercontent.com/18237863/45257873-2b15d300-b37b-11e8-9936-40c23e468899.png)

Here's the returned behavior in dynmap:
![image](https://user-images.githubusercontent.com/18237863/45257881-4680de00-b37b-11e8-84d9-e4ae4637fb31.png)

**Comment by mikeprimm** [comment]
Version info?

**Comment by NJDaeger** [comment]
Output from dynmap version is 3.0-SNAPSHOT-Dev

**Comment by NJDaeger** [comment]
Built it from the source.

**Comment by mikeprimm** [comment]
I'm assuming 1.13.x, yes?  The rendering models for 1.12.x and earlier vs 1.13 are independent

**Comment by mikeprimm** [comment]
OK - just committed fixes for this: if you are building your own copy, pull and clean build from the v3.0 branch.  Otherwise, latest dev builds at http://dynmap.us/builds/dynmap should have fix in a couple minutes.
