### ISSUE TITLE
Render Bug

### ISSUE THREAD

**Issue by Sugar250** [webbukkit/dynmap#2332]
something not right with this things:
**Buttons:**
In game:

![2018-09-10_03 14 51](https://user-images.githubusercontent.com/21377465/45267918-cad07f80-b4a7-11e8-95af-9025c023cd2f.png)

In Dynmap:

![image](https://user-images.githubusercontent.com/21377465/45267920-da4fc880-b4a7-11e8-8703-d71f5a6a287d.png)

**Iron trapdoor:**

In game:

![2018-09-10_03 17 49](https://user-images.githubusercontent.com/21377465/45267940-1be07380-b4a8-11e8-9ae0-2a2cfa81f0d9.png)

In Dynmap:

![image](https://user-images.githubusercontent.com/21377465/45267962-46323100-b4a8-11e8-8e50-f5ccc30fd72e.png)

**Big chests:**

something wrong with my net that I can't upload my pic bu anyway it's wrong.

runing spigot 1.13.1-R0.1-snapshot

dynmap version:3.0-alpha-3-111

**Comment by mikeprimm** [comment]
Buttons part is dup of #2331 - just deployed fix for that.

**Comment by mikeprimm** [comment]
Trapdoor models are now fixed - build is running now: dev build with fix will be at http://dynmap.us/builds/dynmap in a couple minutes.

**Comment by mikeprimm** [comment]
And I just pushed fix for 1.13 chest models - build with that fix is running now (same place - version will report build 128 or later)
