### ISSUE TITLE
Other Dynmap mods be updated to support Dynmap 3.0+ and Minecraft 1.13.1+.

### ISSUE THREAD

**Issue by simonjonnemeth** [webbukkit/dynmap#2335]
There are several Dynmap related mods (from the build server) that I use along side that add extra functionality do Dynmap. These haven't been updated in quite some time, like Dynmap Mobs for instance which works perfectly but it lacks lots of newer mobs. I'd like drowneds to show up on my map.

**Comment by smmmadden** [comment]
I agree, I noticed those on the Spigot page and wondered about them.  Two that I would use are a couple years behind the latest updates to MC.
[https://dev.bukkit.org/projects/dynmap-mobs](https://dev.bukkit.org/projects/dynmap-mobs)
[https://dev.bukkit.org/projects/dynmap-essentials](https://dev.bukkit.org/projects/dynmap-essentials)

**Comment by mikeprimm** [comment]
I've started work on Dynmap-Worldguard.   Dynmap-Essentials will be next, and Mobs will probably be after that.

**Comment by mikeprimm** [comment]
Initial Dynmap-WorldGuard build available - http://dynmap.us/builds/Dynmap-WorldGuard/Dynmap-WorldGuard-1.1-alpha-1.jar

**Comment by smmmadden** [comment]
I'm using the EssentialsX from https://ci.ender.zone/job/EssentialsX
That's the one I'd be interested in

**Comment by fichdlmaa** [comment]
LuckPerms is working fine
https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/

**Comment by SlimeDog** [comment]
EssentialsX

**Comment by Too-DAMN-Much** [comment]
what about the dynmap scraper tool? i really wish to have that back so that there aren't so many unrendered places ruining the maps.

**Comment by edgeman16** [comment]
Can I bump this to get an update to dynmap-mobs to support the newest mobs (eg. pillagers) please?

**Comment by FedUpWith-Tech** [comment]
Closing due to age, requests for updates should be made on each specific project's repo
