### ISSUE TITLE
Dynmap doesn't support touchscreen or touchpad zoom

### ISSUE THREAD

**Issue by andritolion** [webbukkit/dynmap#2337]
When you use a touchscreen or touchpad to zoom in/out, it just zooms the whole webpage, not just the map.

**Comment by generrosity** [comment]
Can you be more specific on what device you use? Works fine in Chrome on the various androids I've used

**Comment by andritolion** [comment]
I'm using Microsoft Edge on a 2-in-1.

**Comment by generrosity** [comment]
Yup, I can confirm on my touch screen laptop that Edge doesn't play nicely. IE and Chrome are fine.

Other than suggesting you use another browser in the mean time, unless someone knows a quick truck to force Edge into rendering more like IE this case might suit a while looking for someone with web knowledge or Google fu

**Comment by xorinzor** [comment]
Perhaps this could help? https://stackoverflow.com/questions/49299496/html5-pointermove-touchmove-not-working-in-microsoft-edge
