### ISSUE TITLE
Feature request: Webchat to specific channel(s)

### ISSUE THREAD

**Issue by smellyonionman** [webbukkit/dynmap#2341]
I don't know much about Java but however Dynmap gets its web chat into the game, is not a method that gets picked up and echoed by DiscordSRV.  I'd like a more holistic chat experience for the players, if possible!  Maybe a config option to specify a channel to which Dynmap sends web chat?  I could then easily link it (and more.)  Thanks for the recent updates.

**Comment by mikeprimm** [comment]
Support for channels needs to be a plugin-by-plugin feature: Spigot/Bukkit and Forge lack any concept of channels, and the plugins that implement them do so uniquely (which is why they clash with one another quite a lot).  Which channel-providing plugin are you referring to?
