### ISSUE TITLE
dynmap purgemap <world> too slow

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#2343]
Hi Mike, with all the regenerating I've been doing in varying builds, the map isn't generating completely and appears to be out of sync (missing sections skipped).  I suspect it was due to using a -spigot- build versus alpha, beta and current dev builds interchangeably which of course is a no-no. :-)

So I want to purge/delete the flat, surface and underwater maps and leave the nether, the_end and cave maps in place (they look fine).  I'm on the server console and typed in:
dynmap purgemap world flat
dynmap purgemap world surface
dynmap purgemap world underwater

I get the proper messages that the Map tile purge started on each map.  However, it doesn't seem efficient to run tile by tile as it takes literally hours to days on a hires 5000 radius world.  Wouldn't it be more effective to simply delete the named map outright and be done in minutes?  Or is there a better way to do the same thing as purgemap that won't take as long?

Thanks -Steve

**Comment by mikeprimm** [comment]
I'd suggest zapping the tree yourself: using Java functions to do a directory tree traversal and file-by-file delete is slower than, say, doing an 'rm -r -f' on Linux.

**Comment by smmmadden** [comment]
I like that option much better :-)  Was there a reason to purge tile-by-tile and not just remove the web/tiles/world* provided explicitly?

**Comment by mikeprimm** [comment]
There is no such thing as deleting a directory tree, from a file system API point of view; even 'rm -r -f' is just implementing a tree traversal to remove the files and directories one at a time: it's just fast native code that is a bit faster than the Java file APIs (see https://github.com/lattera/freebsd/blob/master/bin/rm/rm.c#L177 for implementation of 'rm' - all just breaks down to calling unlink() on each file...).
