### ISSUE TITLE
Optimal settings for render as map is explored?

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#2344]
Dynmap seems to be running very slow on my server. We are using Aikar's new async chunk gen version of Paper and it seems like sometimes the chunks we generate don't show at all, and those that do appear several hours after generation. There is usually a 30,000+ render queue (I see the message when rebooting the server) and during a fullrender the queue grew to 300,000. 

Here is my version:

```> dynmap version
[13:45:40 INFO]: Dynmap version: core=3.0-SNAPSHOT-134, plugin=3.0-SNAPSHOT-134
> version
[13:45:44 INFO]: This server is running Paper version git-Paper-"28a6b607" (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[13:45:44 INFO]: Previous version: git-Paper-253 (MC: 1.13.1)
[13:45:44 INFO]: Checking version, please wait...
[13:45:44 INFO]: Error obtaining version information
```

Here is my config:
https://pastebin.com/HV53HuzX

Hardware:
i7 6700k
8GB ram dedicated to server
2x 500GB SSD in RAID1

**Comment by smmmadden** [comment]
I've been doing rendering in various configurations for the last couple weeks now and finally settling on what I think is the last of them for my server (for now). :-)  I was using the lowres setting and it was much faster than what I'm showing below.  I've increased the resolution quite a bit based on some earlier feedback from Mike.

Here are some numbers for what I've been running on a map of 5,000 radius rendering with:
configuration.txt uses deftemplatesuffix: hires
custom-perspectives.txt uses iso_SE_30_hires with scale of 32
normal-hires.txt perspective for FLAT: iso_S_90_hires  (total tiles: 1,339,608 / 7.5 hour run)
normal-hires.txt perspective for SURFACE: iso_SE_30_hires (total tiles: 417,500 still running 9 hrs+)
normal-hires.txt perspective for CAVE: iso_SE_60_hires (pending...)

I'm running the same snapshot build of Dynmap, with Paper build 253 and on Windows 10 Pro x64.  All my renders are on 500GB HDD for the server and with 6GB dedicated to the JVM.  I wasn't happy with the rendering speed, so I increased my parallelrendercnt to 4 and now I'm getting about 45K-47K renders per hour depending on whatever else I'm doing on the server - so it isn't solely dedicated for MC.  Prior to increasing the default parallelrendercnt (was commented out), it was much slower.

**Hardware:**
2.50 gigahertz **Intel Core i7-4710HQ**
256 kilobyte primary memory cache
1024 kilobyte secondary memory cache
6144 kilobyte tertiary memory cache
64-bit ready
**Multi-core (4 total)**
Hyper-threaded (8 total)
24GB Server, **6GB dedicated to JVM**
GeForce GTX-970M Graphics w/3GB Dedicated Memory

Are you seeing similar results or lower?

**Comment by eightbitx** [comment]
@smmmadden How are you seeing your renders per hour?

**Comment by eightbitx** [comment]
I've increased the parallelrendercnt and it seems to be running at a decent speed during a full-render. Is there any way to check performance of normal updates, NOT full renders?

**Comment by generrosity** [comment]
Nice! I love the community coming together to share tips and configs. I might be able to assist with a wiki page if this gets particularly good - let me know!

I'm quite unfamiliar with the optimization options myself. I could imagine running a dev/desktop instance at full-max-speed and pre-rendering the tiles might be a solution?? I also haven't looks at the effect of Java Args and 'optimization' mods on Dynmap performance either ...

**Comment by FedUpWith-Tech** [comment]
Closing due to age
