### ISSUE TITLE
webregister, login, logoff and deregistration?

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#2347]
Hi Mike, I've been rewriting the login files to enable registrations and splitting out the register from the login itself.  I did find that I can't remove either <form> statement as there is a check being made and if it isn't there, you get the <success> line written out instead of the login itself.  That's not a big deal as I can just leave the form in there and just change the class from login to register and everything works fine.

What I'm not finding though is:
  a) where does the registrant data get added to (flat file, db, txt file?)
  b) how do I de-register someone?
  c) How do provide an option to change/reset player password like "forgot password/user id" link.
  d) where is the logoff link coming from so I can change its appearance/location
![image](https://user-images.githubusercontent.com/10309346/45604227-5c884180-ba00-11e8-9342-c9234ff04927.png)

What I've done so far was just customizing it so I can use my logo as the background to make it professional looking for a login, timeout, registration for consistency in my branding.  Still have some cleanup to do once I add the password reset option and deregistration.
**Login Screen**
![image](https://user-images.githubusercontent.com/10309346/45604828-277eed80-ba06-11e8-9873-e89e6881ddaa.png)
**Timeout Screen**
![image](https://user-images.githubusercontent.com/10309346/45605586-0caf7780-ba0c-11e8-957e-e099c9362bdc.png)
**Registration Screen**
![image](https://user-images.githubusercontent.com/10309346/45605614-34064480-ba0c-11e8-9c55-a6f15710f307.png)

**Comment by SimonOrJ** [comment]
a) Registration data is stored in a .txt file in `plugins/dynmap/` directory.
b) I am unsure if there's an official way, but you can remove permission for logging in for a person.  If banned player is an issue, dynmap should already handle that based on vanilla banlist if I'm not mistaken.
c) There's no password change/reset.  Players can register again to reset their password, and that's the only way. You can leave such instructions in the reset password/registration page instead.
d) Logout button seems to be handled by Javascript.  Play around with inspection tool and check out the network tab. Check "Preserve log" checkbox and see where clicking on the logout button leads to.  Or you can change CSS as well.
