### ISSUE TITLE
Render bug. After i updated from 1.12.2 to 1.13

### ISSUE THREAD

**Issue by Pomdre** [webbukkit/dynmap#2348]
After i updated from 1.12.2 to 1.13 then this appeared.
![image](https://user-images.githubusercontent.com/30056774/45769665-98114e80-bc40-11e8-8e6d-2b5cd3e9806a.png)

![image](https://user-images.githubusercontent.com/30056774/45769851-153cc380-bc41-11e8-8564-6fceffb679b9.png)

This server is running CraftBukkit version git-Spigot-6b015b4-94b8708 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

And Dynmap v3.0-beta-1

**Comment by vlcty** [comment]
do a wb fill with force option set to true and then wait for dynmap to re-render the spots

`wb world fill 20 208 true`

**Comment by Pomdre** [comment]
What do you mean by wb?

**Comment by vlcty** [comment]
World Border plugin.

**Comment by Pomdre** [comment]
I dont haw that plugin...

**Comment by generrosity** [comment]
Have you done a fullrender on your map? Or a purgemap then fullrender?

**Comment by Pomdre** [comment]
None of them..

**Comment by generrosity** [comment]
Well, try it! A "/dynmap fullrender" might cleanup the pieces you are missing. This is relatively normal for the engine to not back-process missed tiles. Running a rullrender once a week seems like good practice to me.

**Comment by generrosity** [comment]
You could travel to one of the locations and do a modest radiusrender if you want to confirm it on a smaller scale. But yes, it takes a few hours to do... But then it's been a few days since I made the suggestion 😜

**Comment by Pomdre** [comment]
But why does this happen?

**Comment by generrosity** [comment]
Root cause unknown, had been a problem for a while particularly if server crash or configs change (like migrating between versions). I think it sees the full file as rendered.

Regardless, the general first step of diagnostics for render issues is to actually do a full render. How is it going?

**Comment by Pomdre** [comment]
I'll start with it: P

**Comment by Pomdre** [comment]
I think I'm taking radius

**Comment by xorinzor** [comment]
If you have hashes enabled, theoretically it should check if the rendered file is still correct and skip it.
Just give the fullrender a try

**Comment by Pomdre** [comment]
Ok thanks it worked! Now only a few days of afk...

**Comment by generrosity** [comment]
Afk?

**Comment by Pomdre** [comment]
found that I can do it via the console instead :)

**Comment by Pomdre** [comment]
then I do not have to stand afk :P

**Comment by Pomdre** [comment]
Thanks for the help!
