### ISSUE TITLE
Certain mods not showing on render

### ISSUE THREAD

**Issue by xorinzor** [webbukkit/dynmap#2351]
Dynmap version: 3.0 Beta 1 - forge 1.12.2

I've made a list of mods from the FTB Revelation pack which don't show up in the render (they render as transparent blocks, and will cause black squares on the connected blocks that do render):

- Thermal Foundation
- Astral Sorcery (the marble blocks, pillars, etc , as an example)
- Traverse (The Fir leaves, as an example)
- ProjectRed Exploration
- Rustic (the wildberry bushes, as an example)

I put them in what I'd consider highest priority based on how much you'd see them on the surface as well as the visual impact, where the highest priority would be top, and lowest, bottom.

Would really appreciate it these could be added :)

**Comment by xorinzor** [comment]
EDIT: After using DynMapBlockScan and doing some manual tweaks to the produced texture files I got the desired result.

**Comment by mdestombes** [comment]
Hi,

I have the same problème as you.

Somes Mobs from FTB Revelation will not be rendered on Dynmap.

I trying to used DynMapBlockScan, but server crashed.

Can you explain your "manual tweaks" to produce "texture files" and where do you put them ?

**Comment by xorinzor** [comment]
I honestly can't remember, this is way too long ago.

I also doubt your server actually crashed, check the config files and make sure the watchdog time limit is increased massively, as it will take a *long* time for the dynmapblockscan to complete. And the default settings was something along the lines of detecting the server as crashed after 30 seconds if it hadn't booted yet.

As for manual tweaks, I think all I did was just look at the kind of output that was being generated, and add / edit such entries manually to the list by looking at what's inside the mod jar files (using something like winrar to open the jar).

That's all I can think of.

**Comment by mdestombes** [comment]
OK.

Thanks for advice.

Can you say me what/where is the "config file" for watchdog.

I have lost connexion for user at initial connexion.
Because connexion is too long.
I think it can be configure in the same file.

**Comment by xorinzor** [comment]
Just the minecraft server config, or bukkit.yml or something.
Not mod-related.
