### ISSUE TITLE
How to fix Tile read error?

### ISSUE THREAD

**Issue by Pomdre** [webbukkit/dynmap#2353]
01.10 12:55:27 [Server] ERROR [dynmap] Tile read error - The last packet successfully received from the server was 41 873 183 milliseconds ago. The last packet sent successfully to the server was 41 873 288 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

**Comment by generrosity** [comment]
That sounds like your server might be under powered. It had instructions right there for wait_timeout and autoreconnect? That seems reasonable. Have you done those (googling if nessesary)?

**Comment by Pomdre** [comment]
the server has 8gb ram ...

**Comment by mikeprimm** [comment]
Looks like you are using a database for tile storage - which type and version?

**Comment by Pomdre** [comment]
Mysql 
![image](https://user-images.githubusercontent.com/30056774/49446346-4a829780-f7d4-11e8-9656-9bcd313ff813.png)


> Looks like you are using a database for tile storage - which type and version?

**Comment by Pomdre** [comment]
Closed due to not longer using dynmap.
