### ISSUE TITLE
Error connecting too MariaDB database with mysql/mariadb java drivers

### ISSUE THREAD

**Issue by Laikar** [webbukkit/dynmap#2354]
I have a MariaDB server, and when i try to connect to it with both the mySQL java driver and the MariaDB java driver it constantly outputs these errors:
With mySQL driver: 
`The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.`
With MariaDB driver: 
`Standalone file write error - Could not connect to address=(host=localhost)(port=3306)(type=master) : Connection refused (Connection refused)`

I have the address, the port and the username/password well.
In the past i managed to stablish connections with the mySQL driver with my exact same settings, so it might be something with my database.

**Comment by collinator24** [comment]
How did you fix it?

**Comment by Laikar** [comment]
I had missconfigured the Database and the user for dynmap didn't really exist

**Comment by collinator24** [comment]
Ah. Mine does something similar but works correctly
