### ISSUE TITLE
Cannot Hide Item ID in Nether

### ISSUE THREAD

**Issue by rufo123** [webbukkit/dynmap#2355]
Hi so I wanted to hide Netherrack from showing in my Nether World Map. I tried to set it up in the custom-shaders file and yes I also enabled the shader in configuration. But the netherrack is still there showing up.

# No Netherrack
  - class: org.dynmap.hdmap.TexturePackHDShader
    name: stdtexture_nether
    texturepack: standard
    hiddenids: [ 87 ]

Am I doing something wrong?

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.

not sure about what version you are using, but mojang dropped support for item ids and require names.
