### ISSUE TITLE
1.13.1 - DynMap 3 beta render only chunks visited since update

### ISSUE THREAD

**Issue by menelmir** [webbukkit/dynmap#2359]
I need to full re-render a world on my server.
I noticed it doesn't works properly, so to understand, I purged the maps for this world, and retry fullrender.

And so DynMap generated only the chunks visited since server has been updated to 1.13.1 : it do not detects other chunks, so it stops and says "render complete", but 99% of map is black and no rendered !

**Comment by Ste3et** [comment]
Same here i do a --forceUpgrade for a pre generated World with 602501 Generated Chunks but only a little bit of the chunks will be rendered.

**Comment by robotnikthingy** [comment]
Having the same problem as well

**Comment by Luysita** [comment]
Same here. I think this is the problem: https://github.com/Brettflan/WorldBorder/issues/113

**Comment by menelmir** [comment]
So, as this is issue is not resolved, I made a very little plugin witch refresh all chunks in all worlds.
And... IT'S WORKS ! Waiting for this issue to be resolved, it's a a temporary solution.
It's provided as is and comes with no warranty, save your server first.
Make sure your read the joigned readme.txt file !!!
Just a command to use, from console.

[ChunksRefresher_0_0_1-SNAPSHOT-2018-11-02.zip](https://github.com/webbukkit/dynmap/files/2568499/ChunksRefresher_0_0_1-SNAPSHOT-2018-11-02.zip)

**Comment by robotnikthingy** [comment]
> 
> 
> So, as this is issue is not resolved, I made a very little plugin witch refresh all chunks in all worlds.
> And... IT'S WORKS ! Waiting for this issue to be resolved, it's a a temporary solution.
> It's provided as is and comes with no warranty, save your server first.
> Make sure your read the joigned readme.txt file !!!
> Just a command to use, from console.
> 
> NB : there can exist issues on some case in large worlds... Beware...
> 
> [ChunksRefresher_0_0_1-SNAPSHOT-2018-11-02.zip](https://github.com/webbukkit/dynmap/files/2568499/ChunksRefresher_0_0_1-SNAPSHOT-2018-11-02.zip)

What kind of issues?

**Comment by hyukuri** [comment]
> ChunksRefresher_0_0_1-SNAPSHOT-2018-11-02.zip
Thanks a lot ! It Works Fine for me !

My 2.5GB Wolrd Chunk Data needed 32GB RAM to run the plugin.
On 16GB RAM machine, I got An Error of "GC overhead limit exceeded".

For safety, I only use the generated map data, and the chunk data remains as it was before the refresh.

**Comment by seema84** [comment]
and a solution for server with less memory?

**Comment by menelmir** [comment]
> and a solution for server with less memory?

I just upload new version, 0.0.2-SNAPSHOT, you can use it on any server, issues are fixed. When the server goes near out of memory, tasks stops. You can start them again, after cleaning memory or restarting server. It will skip regions already refreshed ;)

**Comment by seema84** [comment]
that sounds good :)

**Comment by mikeprimm** [comment]
Spigot bug - added workaround in latest dev build ( http://dynmap.us/builds/dynmap/ ) on 1.13.2 (workaround not available on 1.13.1).  Issue opened for Spigot - https://hub.spigotmc.org/jira/browse/SPIGOT-4512

**Comment by mikeprimm** [comment]
Dup of #2313
