### ISSUE TITLE
my visibilitylimits don't work

### ISSUE THREAD

**Issue by L27SlubbyGames** [webbukkit/dynmap#2361]
it showing the whole map and not the map site what I want.

Link to my dynmap:
http://slubbecraft.serveminecraft.net:25575/?worldname=Zombie&mapname=flat&zoom=0&x=3472&y=64&z=7768

My world folder:
worlds:
  - name: Zombie
    title: "Zombie"
    enabled: true
    sendposition: false
    sendhealth: false
    visibilitylimits:
      - x0: 500
        z0: 400
        x1: 14300
        z1: 13300
    hidestyle: air
    center:
      x: 7500
      y: 125
      z: 7400
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "Surface"
        prefix: t
        perspective: iso_SE_30_hires
        shader: stdtexture
        lighting: shadows
        mapzoomin: 1

**Comment by generrosity** [comment]
Did you have already have pre-rendered tiles? If so, you need to purge and run a full render

**Comment by mikeprimm** [comment]
The indentation on the clip LOOKS off - could you cut/paste it to a pastebin.com ?
