### ISSUE TITLE
A texture (acacia) not showing up properly on dynmap?

### ISSUE THREAD

**Issue by MegaMinerDL** [webbukkit/dynmap#2362]
![image](https://user-images.githubusercontent.com/39650382/46853733-d8568d80-cdf6-11e8-9863-1433d42f2651.png)
![image](https://user-images.githubusercontent.com/39650382/46853747-e2788c00-cdf6-11e8-9a9f-e267a480fb51.png)
![image](https://user-images.githubusercontent.com/39650382/46853753-e6a4a980-cdf6-11e8-8506-b4afa423a295.png)

**Comment by mikeprimm** [comment]
Can I get a link to the custom texturepack definition?

The question I've got is whether the custom RP is just replacing existing PNG texture files, or does it include custom model and/or block state definitions (which are not yet supported....).

**Comment by MegaMinerDL** [comment]
> 
> 
> Can I get a link to the custom texturepack definition?
> 
> The question I've got is whether the custom RP is just replacing existing PNG texture files, or does it include custom model and/or block state definitions (which are not yet supported....).

The texturepack is http://www.mediafire.com/file/04pprftlezi5a7o/Inside_Textures_v.4.zip/file
It has a Assets>Minecraft>Models folder in it, if that's what you mean? Is that the problem? Although why is it happening to acacia; everything else works... Would removing the model of acacia do anything..? Since the texture would simply load anyway without the model, and solve the problem since models aren't supported? From what I understand.

**Comment by mikeprimm** [comment]
I'll need to look more at the RP, but to summarize: in post 1.8 RPs, you can have the following resources for describing blocks:
1) Images replacing the images of the same name from the vanilla blocks (this is basically 100% of RPs)
2) Alternate descriptions for the model for each block state - this can include altering the shape and/or altering which image file names are used to texture the faces of the model.   Relatively few RPs do this, and Dynmap doesn't support reading these model files - so if an RP, say, puts a custom model in that switches the names of the texture files vs Vanilla, the Dynmap render will miss this.
3) Alternate block state mappings - which basically are what describes which model to use (possibly with modifications like rotation) for each of the states a block might be in (e.g. different wood, top vs bottom slabs, rotations of stairs).  This is even less common to see in RPs, and is also not processed by Dynmap currently.

Your RP looks like the author more or less copied in the blockstate and model data from vanilla - either they made some subtle changes I'm missing, or most (all?) of the block states and models are unchanged.  So, I'm not sure if this is or isn't the issue - Dynmap ignores them, so it'd only matter if they were altering which texture files were being used for the blockstates for the acacia planks blocks - at a glance, it doesn't look like it, but I'll need some more time to confirm.

**Comment by MegaMinerDL** [comment]
Ok, thanks. Is there anything I can do to help or..? Only acacia is the issue, which is strange since many other models have been replaced but I _think_ they work.. Haven't checked actually. And also, I am the pack author ;)

**Comment by MegaMinerDL** [comment]
> 
> 
> I'll need to look more at the RP, but to summarize: in post 1.8 RPs, you can have the following resources for describing blocks:
> 
>     1. Images replacing the images of the same name from the vanilla blocks (this is basically 100% of RPs)
> 
>     2. Alternate descriptions for the model for each block state - this can include altering the shape and/or altering which image file names are used to texture the faces of the model.   Relatively few RPs do this, and Dynmap doesn't support reading these model files - so if an RP, say, puts a custom model in that switches the names of the texture files vs Vanilla, the Dynmap render will miss this.
> 
>     3. Alternate block state mappings - which basically are what describes which model to use (possibly with modifications like rotation) for each of the states a block might be in (e.g. different wood, top vs bottom slabs, rotations of stairs).  This is even less common to see in RPs, and is also not processed by Dynmap currently.
> 
> 
> Your RP looks like the author more or less copied in the blockstate and model data from vanilla - either they made some subtle changes I'm missing, or most (all?) of the block states and models are unchanged. So, I'm not sure if this is or isn't the issue - Dynmap ignores them, so it'd only matter if they were altering which texture files were being used for the blockstates for the acacia planks blocks - at a glance, it doesn't look like it, but I'll need some more time to confirm.

**Comment by MegaMinerDL** [comment]
_think_

**Comment by mikeprimm** [comment]
OK - sorry - just notices this was still open.  You say just acacia?  Which specific acacia blocks (stairs, half slabs double slabs, planks?)   I'll give it a look, but if you have specifics - particularly as of beta-2 or (better) the latest dev build, that'd be cool.

**Comment by mikeprimm** [comment]
OK - reproduced this, and an investigation revealed some serious breakage in the CTM processing logic (basically, a bunch of changes I needed to make due to the internal changes that were needed for the full refactor of the block model handling driven by 1.13+).  I've finished this work now, and my test of your RP doesn't exhibit the acacia problem (which was really due to the CTM for, I believe, the lever being applied to the acacia block....).
You should be able to grab the latest SNAPSHOT dev build from http://dynmap.us/builds/dynmap/ - please let me know if this fixes your issue!

**Comment by MegaMinerDL** [comment]
Hmm, I have a spigot server and tried-

>    Dynmap-3.0-SNAPSHOT-spigot.jar                               09-Dec-2018 18:26  5.3M 

I think it's the right one, but still, nothing fixed... for now I'm going back to the version I had (3.0 alpha-2), and am still stuck as to why this is happening... :confused:

**Comment by mikeprimm** [comment]
You rerun the render?  I specifically tested with your RP....

**Comment by MegaMinerDL** [comment]
**OK SO, IT's FIXED!! I was ready to give up and let the small issue be, but now that it's fixed, it looks great! Updating to latest snapshot and rerendering fixed it (also after I managed to load the texture pack)!**
![image](https://user-images.githubusercontent.com/39650382/50345453-0d820900-0527-11e9-9a90-a2d6754e1e5c.png)

**Comment by MegaMinerDL** [comment]
**OK SO, IT's FIXED!! I was ready to give up and let the small issue be, but now that it's fixed, it looks great! Updating to latest snapshot and rerendering fixed it (also after I managed to load the texture pack)!**
