### ISSUE TITLE
Dynmap and Hiddenids configuration

### ISSUE THREAD

**Issue by rufo123** [webbukkit/dynmap#2363]
Dynmap is not accepting numbers from hiddenids [ 87 ]

**Comment by rufo123** [comment]
Oh, it was long time ago when I issued this. It's end of semester at my university. So I don't have much time here now, sorry. But I will send you more info soon, hopefully. :)

**Comment by mikeprimm** [comment]
In 3.0, 'hiddenids' are no longer supported (as numbers), the alternative setting 'hiddennames' is used to provide block names to be hidden.  Block IDs have been deprecated in MC for a long while, and are completely gone in 1.13 (even internally).  I missed migration some of the stock shaders (in shaders.txt) to use the new setting - I'll take care of that ASAP.

**Comment by mikeprimm** [comment]
For the original query, try:

hiddennames: [ "minecraft:netherrack" ]
