### ISSUE TITLE
[1.13.2] Errors on startup.

### ISSUE THREAD

**Issue by Sikatsu** [webbukkit/dynmap#2366]
https://pastebin.com/UsMXs6Km

**Comment by Quavelen** [comment]
Oh, good; I'm glad someone already opened an issue. I'm also on 1.13.2 now, and have the same as @Sikatsu: https://paste.ubuntu.com/p/MPhDWkvrbD/

**Comment by Mundo-Minecraft** [comment]
You are fast reporting bugs xd. I have the same problem.

Thanks

**Comment by DuckCaller** [comment]
Same problem.

**Comment by Mick43** [comment]
For me too.

**Comment by mikeprimm** [comment]
1.13.2 supported in latest dev build.   Will release 3.0-beta-2 later tonight.

**Comment by mikeprimm** [comment]
3.0-beta-2 released to spigotmc.org and dev.bukkit.org
