### ISSUE TITLE
(1.13.1 Spigot) Connection Refused

### ISSUE THREAD

**Issue by Houpatt** [webbukkit/dynmap#2368]
I have tried loading my 1.13 Spigot server on several versions of Dynmap, however nothing I do works.

When attempted to set up a Dynmap for my server, I do all of these actions in order.
1. Install any version of Dynmap that supports 1.13
2. Memorize the port from Dynmap configuration.
3. Add the port on to the end of my server address. I end up with 158.69.124.32:8123. (I have tried changing the port, it does not work).
4. Restart the server.
5. Enter the address into my browser.

Once I do this, I get a message from my browser saying "This site can't be reached". What am I missing?

**Comment by gamer4life1** [comment]
I have this problem too. I use ServerMiner and I don't have acess to their firewall. They give me certain ports to use and when I put one in, it dosen't work.

**Comment by krusic22** [comment]
For anyone else having this problem, check that server-ip= in server.properties is set to the servers public IP and not localhost.

**Comment by melody-au** [comment]
Respond to above; if you must use localhost to host your server for some reasons like bungeecord you may change the setting of dynmap (webserver-bindaddress) to 0.0.0.0 to launch the dynmap webserver on the public ip~
