### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by EnChouu** [webbukkit/dynmap#2372]
![capture](https://user-images.githubusercontent.com/32703412/47784856-44962400-dd07-11e8-9c07-827f2dc8dcc5.PNG)

So I followed multiple tutorials on how to setup dynmap, but its not working.

Anyone able to help me? Im running spigot 1.13.2, with multicraft as webpanel.

**Comment by smmmadden** [comment]
did you open the port in the firewall?  It's not enabled by default, you will need to add it to the firewall rules or ask the hosting company to do so.

**Comment by EnChouu** [comment]
I will send the hosting company an email. Thanks for the quick repsondse!
