### ISSUE TITLE
Health bar wrong at low hp

### ISSUE THREAD

**Issue by Azulear** [webbukkit/dynmap#2377]
Hi,

i wrote a small webextension for my browser to read data from the dynmap of a server i'm playing on.

I noticed if a player has only 1 heart left than at the next update the dynmap shows only half a heart and if the player loses half a heart, the dynmap shows the player as dead, but ingame he has half a heart.
If the player eats and recovers the dynmap shows his health always with half a heart below the ingame real health until he has full health again.
If then the player loses health its all ok until he is at 1 heart and the wrong display starts again.

I looked at HTML style-code for the health-bar:
Full health bar = 50px  |  1 heart = 5 px  |  1 HP ingame (half a heart) = 2.5px
If the value hits 5px at next update (2 sec) the value changed to 2.5px at no change ingame.
If I lose half a heart ingame, it shows 0px.
If I eat and regen to 8 hearts ingame, it shows 37.5px whats wrong. (2.5 less - half a heart)
This wrong value is until the next full regen at 50px.

Dynmap version 3.0-beta-2-138
Minecraft version 1.13.2
Spigot Server latest build

**Comment by mikeprimm** [comment]
Fix coded in latest dev builds - https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar

**Comment by mikeprimm** [comment]
Give the 3.0-beta-3 release candidate a try (expected to release later today) - https://dynmap.us/builds/dynmap/Dynmap-3.0-beta-3-spigot.jar . Reopen issue if you still see problems.
