### ISSUE TITLE
Dynmap not working with Spigot 1.13.2?

### ISSUE THREAD

**Issue by Cassolotl** [webbukkit/dynmap#2381]
I just updated the server to spigot 1.13.2 and Dynmap to the latest Spigot snapshot. It worked perfectly before but now it won't load in my browser at all.

I get this in the console at start-up:

> [13:59:28] [Server thread/INFO]: [dynmap] Enabling dynmap v3.0-beta-1-129
> [13:59:28] [Server thread/INFO]: [dynmap] Dynmap is disabled (unsupported platform)

I installed the Spigot one of these releases: https://github.com/webbukkit/dynmap/releases/tag/3.0-beta-1

When I do `/version` I get:

> [14:01:56] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-947a8e7-17ff1e0 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
> [14:01:56] [Server thread/INFO]: Checking version, please wait...
> [14:01:56] [Thread-15/INFO]: You are running the latest version

When I do `/version dynmap` I get:

> [14:03:50] [Server thread/INFO]: dynmap version 3.0-beta-1-129
> [14:03:50] [Server thread/INFO]: Website: http://www.minecraftforum.net/topic/1543523-dynmap-dynamic-web-based-maps-for-minecraft/
> [14:03:50] [Server thread/INFO]: Author: mikeprimm

But when I go to the URL...

![screen shot 2018-11-13 at 14 02 34](https://user-images.githubusercontent.com/6607512/48418281-ceed7780-e74c-11e8-8488-7d0d9cf6ea20.png)

Is there something that might have changed in the config files or something that I need to change for 1.13.2? Any ideas? :S 

**Edit:** It works fine with Spigot 1.13.1 so I've downgraded to that for now. :)

**Comment by mikeprimm** [comment]
Spigot 1.13.2 requires Dynmap beta 2 - see https://dev.bukkit.org/projects/dynmap/files or https://www.spigotmc.org/resources/dynmap.274/update?update=249313
