### ISSUE TITLE
Avatar 1.12.2

### ISSUE THREAD

**Issue by BrightYC** [webbukkit/dynmap#2383]
Skin is displayed incorrectly. The "helmet" becomes transparent.
![270b572cc5a015826f13806f1a6b5d9d](https://user-images.githubusercontent.com/28766913/48609676-f8004900-e994-11e8-9912-e5ba74636c69.png)
Dynmap version - "v3.0-beta-1 for Forge 1.12.2"

**Comment by Psy-Virus** [comment]
Closing this because there was no answer since several weeks. Assuming it's fixed or resolved.

This also seems to be a support request. For further support, please head over to the new community support forum at: https://forums.dynmap.us

Thank you

**Comment by SylveonBottle** [comment]
Requesting ticket to be re-opened, I've been having this issue myself.

If need-be, I can simply create a new ticket based on it.

My dynamap is located at http://eeveesanctuary.com:8123/
My configuration is https://gist.githubusercontent.com/SylveonBottle/fcce9927d5af3cf9fe001ee570de9a2b/raw/f5c0df2546920fd697e32c9cbe1b1794364ef082/configuration.txt

![image](https://user-images.githubusercontent.com/17802843/55674932-bc511780-5880-11e9-9e5f-f0722ece1a9d.png)
