### ISSUE TITLE
[Feature Request] Minecolonies

### ISSUE THREAD

**Issue by Pulz-TCP** [webbukkit/dynmap#2385]
I'd like to request support for Minecolonies within Dynmap, if possible.

Edit: I'm referring to displaying colony information on the map, the textures are all fine except the roofing.

It's extremely popular, and its built in claim/permission system means that GriefPrevention (which also has excellent Dynmap support) isn't necessary. 

Link: https://minecraft.curseforge.com/projects/minecolonies

**Comment by BonaireDreams** [comment]
Dynmap has rendered my entire Minecolonies towns aside from the sloped tile roofs. But thats because they are models and Dynmap doesnt do models anyway.

![image](https://user-images.githubusercontent.com/5133282/48805969-be4d7c00-eccd-11e8-81e7-91d28f4537f7.png)

**Comment by PulzHF** [comment]
@BonaireDreams Sorry, that's not what I meant haha. I thought it was clear me referring to GriefPrevention that I meant an overlay showing the protected area, perhaps with the same kind of information popup when you click on the claim.

My bad, that's what I meant.

**Comment by PulzHF** [comment]
![Example of GP Dynmap](https://cdn.discordapp.com/attachments/513418548731838480/514084997943001111/unknown.png)

**Comment by BonaireDreams** [comment]
Ohh, well nevermind me then. I was wondering what the grief prevention had to do with it. LOL

**Comment by PulzHF** [comment]
> Ohh, well nevermind me then. I was wondering what the grief prevention had to do with it. LOL
Yeah sorry, I didn't realise how poorly I explained that.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
