### ISSUE TITLE
Unable to fullrender maps

### ISSUE THREAD

**Issue by MalowZer** [webbukkit/dynmap#2389]
For somes reasons and without any error log, dynmap can't fullrender all of my chunks, even if they are existing, it just render chunks that are discovered by a player (they are existing in my region folder but just not yet discovered by players).

I did a /wb fill to discover every chunk in a certain radius, and even with that, dynmap won't show them all. 
it's like a "cache region" is existing which concern regions that a player walked on, and dynmap is using this one instead of my region folder, got some idea about this ?

Thx

**Comment by MalowZer** [comment]
Dynmap-3.0-beta-2-spigot.jar and Spigot 1.13.2

**Comment by TheDarknessEmperor** [comment]
Dynmap-3.0-beta-2-spigot.jar works without issue on Spigot 1.13.1 . I'd recommend just dropping the server version for now and maybe using viaversion to allow 1.13.X clients to connect

**Comment by MalowZer** [comment]
Okay, didn't know this plugin even exist ! thx a lot :)

**Comment by MalowZer** [comment]
i did try with a new serv with only dynmap as plugin, and i did remplace the "world" region by my region on my previous map, and even if I fullrender this map, dynmap only render the chunk travelled by players.

**Comment by generrosity** [comment]
Just to understand your last comment MalowZer - you have a new server, the players are wandering around generating chunks, and these are the only chunks that dynmap shows.

Unless you have pre-generated chunks, dynmap will only show chunks generated by players, especially on a new server

**Comment by Derkades** [comment]
I have a feeling you need to re-pre-generate all chunks, probably minecraft only "updates it to 1.13 format" when a chunk loads

**Comment by MalowZer** [comment]
Yep, seems like, but mikeprimm did an hotfix few days ago, it's working now. 
You can download it here : http://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar

**Comment by generrosity** [comment]
Yea - I heard about some edge case that he fixed. Purge if you do any further problems tho eh.

Great its working! Closing.
