### ISSUE TITLE
Dynmap Crashes Server Randomly

### ISSUE THREAD

**Issue by crobey98** [webbukkit/dynmap#2392]
So I have been running a server for the past two weeks and we have been crashing at least once or twice daily and we have talked with our server provider and together we have narrowed the causes of the crash down to Dynmap. Checking the logs after a crash, the only plugin mentioned at all is Dynmap. The other plugins we are running are CoreProtect, UltraVanish, OpenInv, WorldBorder, and LuckPerms. We are running on a Paper 1.13.2 #469 JAR right now but this issue has happened on several other versions of Paper and Spigot for us. Randomly we get a ton of lag even though it allows us to chat, and then the server times out. I'm going to include some snippets of the Dynmap mentions in the log files. Let me know if you need any more information and I'd be happy to provide it.

```
[21:41:19] [Paper Watchdog Thread/ERROR]: Current Thread: Dynmap Render Thread
[21:41:19] [Paper Watchdog Thread/ERROR]: org.dynmap.MapManager$CheckWorldTimes.run(MapManager.java:805)
[21:41:19] [Paper Watchdog Thread/ERROR]: 		org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:207)
[Paper Watchdog Thread/ERROR]: 		org.dynmap.AsynchronousQueue.running(AsynchronousQueue.java:120)
```

**Comment by generrosity** [comment]
Can you post the crashlog.txt to pastbin and link to it here? A single line might not help sorry.

**Comment by Psy-Virus** [comment]
@crobey98,
is this issue still valid?
Did you try the latest version of Dynmap?
