### ISSUE TITLE
DynmapForge should approximate color based on average color of the topside of the block

### ISSUE THREAD

**Issue by martmists** [webbukkit/dynmap#2394]
This would reduce the amount of blocks we server hosts have to reconfigure.

Additionally, slabs and stairs seem to not get rendered, presumably for not being considered "solid".

**Comment by generrosity** [comment]
Heya - can you confirm what version of minecraft and bukkit/forge/etc you are using? Not rendering stairs doesn't sound right - usually it just renders these vanilla things normally.

If you are talking about modded stairs, then drop in Dynmap-blockscan.

**Comment by mikeprimm** [comment]
If you are running Dynmap 3.0 and Forge after 1.9, DynmapBlockScan is the best answer - the dev builds can be found here: http://dynmap.us/builds/DynmapBlockScan/)

**Comment by generrosity** [comment]
As a feature request for vanilla and correctly-moddelled modded slabs, its already implemented so closing.

Do confirm if it is vanilla blocks having issues, do standard fixes, get the latest (HEAD) version, and we can look at specific issues. Need to know the Micecraft version, etc etc still.

**Comment by martmists** [comment]
DynmapBlockScan causes crashes when scanning for too long. We've increased the max tick counter to 10 minutes and it still crashes after being killed by the watchdog.

**Comment by generrosity** [comment]
What pack do you have / number of forge mods?
On my server i have max-tick-time=6000000000
I'd recommend trying that, and using both HEAD for dynmap-forge and the blockscan.

@mikeprimm - I see dynmap-forge december HEAD files in 'forge' as well as October files in dynmapforge ... is there cross pollination or am I getting my files from the wrong place?

**Comment by martmists** [comment]
ATM3-Remix (300+ mods or so)
We had it set to an hour (3_600_000) and it still crashed, so for now we'll be working without it. If it's only a one-time thing where it builds all textures we'll enable it again, but since I haven't looked into the source extensively I have a feeling it caches them every time rather than linking making a `HashMap<ID, Texture>` and saving that data.

**Comment by generrosity** [comment]
TBH I'm not sure that is the case anymore. In ATM2 days I could generate once and leave the generated configs in place. A year ago I was doing ATM3 dynmapping, the configs would vanish on startup.

If you are looking at pre-genning the blockscans, you would be able to do this on a powerful desktop and copy over?

**Comment by martmists** [comment]
We could probably pregen the block scans on the server, how would we go about doing this?
