### ISSUE TITLE
Show optional Playercount + Name from FakePlayer

### ISSUE THREAD

**Issue by o0Julia0o** [webbukkit/dynmap#2396]
hi,

could you show as option the fakeplayers(name + playercount, no position of course) from FakePlayersOnline https://dev.bukkit.org/projects/fakeplayers?gameCategorySlug=bukkit-plugins&projectID=43537 ?

thx

Julia

**Comment by Psy-Virus** [comment]
Well, those links are dead. Could you please update them?

**Comment by mikeprimm** [comment]
Just to be clear: you want them to show in the list of online players in the map, just with no corresponding in-world display (as if they were position hidden)?

**Comment by o0Julia0o** [comment]
Yes - thx. So the fakeplayers would be more fake. Because you see their names on the map, like non-fake players. Sure - you can´t see their icons on the map, because they don´t exists.

**Comment by FedUpWith-Tech** [comment]
Closing this since FakePlayersOnline is no longer maintained and Dynmap does not support any version it supported anymore
