### ISSUE TITLE
[DynmapBlockScan] Crashes when it scans blocks for too long

### ISSUE THREAD

**Issue by Derkades** [webbukkit/dynmap#2397]
I'm trying to run this on a fairly sock FTB Revelation server. At startup, it prints warnings for 60 seconds after which the server crashes. Does this mod run on the main thread, causing it to halt the server for too long when it needs to scan for a lot of blocks?

Unfortunately I can only take a screenshot of the log and not copy it at the moment, so here is a part of it: ![screenshot of log](https://i.ibb.co/qY93PjN/Screenshot-20181204-114247.png)

**Comment by Psy-Virus** [comment]
You can set this in the server.properties.
Simply increase the value of `max-tick-time` and u're good to go.
