### ISSUE TITLE
How to make the custom texture pack show up on dynmap?

### ISSUE THREAD

**Issue by DisneySpace** [webbukkit/dynmap#2398]
Hi. A server I am on is using dynmap and we have a custom texture pack on as well. However, we do not know if it is possible to, and if it is, how to make the texture pack be visible on the dynmap. Any help will be appreciated.

**Comment by seema84** [comment]
yes that works

1. put your texture pack  zip in dynmap/texturepacks
2. add shader in shaders.txt

example:
shaders:
  # Default shader - used if shader not specified or invalid
  - class: org.dynmap.hdmap.TexturePackHDShader
    name: chooseaname
    texturepack: yourtexturepack.zip

3. find your template in (maybe tamplates/normal-hires.txt)
4. change the "shader: stdtexture" to "shader: chooseaname"

that's it
