### ISSUE TITLE
black chunks

### ISSUE THREAD

**Issue by seema84** [webbukkit/dynmap#2399]
after a fullrender i can see some black chunks (a radiusrender to fix this dont work)
only if i build some blocks the chunks will render

https://imgur.com/a/0I4KY7c

Version:
Dynmap version: core=3.0-SNAPSHOT-145, plugin=3.0-SNAPSHOT-145
Spigot-a1f2566-97b0057 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by generrosity** [comment]
Sounds familiar. Are you using the latest build from http://dynmap.us/builds/dynmap/ ?

Was this an upgrade from a previous Minecraft version? Have you done an fullrender or purging the existing tiles?

**Comment by brandonsturgeon** [comment]
Also getting this. Moved from vanilla to spigot, two fullrenders and there are still some black spots. Occasionally, zooming into those squares will render them, but when you zoom back it they return to black.

**Comment by generrosity** [comment]
I'm not sure what can be done about chunks beyond a world border other than use the similar dynmap filtering. If you can guess the X/y/z you can you commands to place blocks to generate chunks

@brandonsturgeon again, if you have moved versions I'd suggest purging all tiles as there are known issues if you don't. Sounds like you have roles in one zoom level that are glitched

**Comment by Psy-Virus** [comment]
As this has been answered, please head over to https://forums.dynmap.us for further support discussions.

If a discussion will lead to the conclusion that this is a bug, feel free to reopen an issue here by use of the provided template.

Thanks
