### ISSUE TITLE
integrating fetching with ely.by skins system

### ISSUE THREAD

**Issue by omatix** [webbukkit/dynmap#2400]
## FEATURE REQUEST
- [X] I would like to propose an additional feature.
- [ ] I would like to propose a config change.
- [ ] I would like to request mod support.
- [ ] I would like to propose another change.

- [X] I have searched the wiki and confirmed that this feature is not already implemented.

## FEATURE INFORMATION

Dynmap could have two fetchings to check in config. Vanilla one and [Ely.by](http://ely.by/) as far as it getting even more popular.
Is it possible to integrate that plugin with this platform in the future?

**Comment by generrosity** [comment]
Is this different from the skin URL config that already exists?

**Comment by Psy-Virus** [comment]
Well it's all Russian and I don't want to even try bothering google translator. But the provided examples look like you simply can use something like `http://skinsystem.ely.by/skins/erickskrauch.png` to get a player skin.
So if you change the 
`skin-url: "http://skins.minecraft.net/MinecraftSkins/%player%.png"`
to
`skin-url: "http://skinsystem.ely.by/skins/%player%.png"`
it should work.
Maybe some one want's to try this?

**Comment by Psy-Virus** [comment]
Well, as nobody answered my question, I assume that everything works like a charm.

closing
