### ISSUE TITLE
Line markers cannot be found (Spigot-1.13.2 & dynmap-3.0-beta3)

### ISSUE THREAD

**Issue by metacoz** [webbukkit/dynmap#2401]
## Server Information

- I can reproduce this issue consistently
     - [ ] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [ ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
After a line has been added by using `/dmarker addline` command, the line is reported not found by using commands like: `/dmarker updateline` or `/dmarker deleteline`, but it can be found in the `markers.yml` file and can be correctly shown on the dynmap web UI.

## Reproduce Steps
1. Add corners for the line, using `/dmarker addcorner`
2. Add a line using the corners, using `/dmarker addline LineName set:LineSet`
3. Try to update the line information, using `/dmarker updateline LineName newlabel:NewName`
4. The response says "Error: Line not found - LineName"
5. The command `/dmarker listlines` returns nothing.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
