### ISSUE TITLE
Not using cpu enough 

### ISSUE THREAD

**Issue by lordkitsuna** [webbukkit/dynmap#2403]
Having a hard time searching for this one because google just keeps giving me threads about Dynmap using too much cpu. That is exactly the opposite problem from what i am having. I have tried increasing the number of tiles it will work on at once and the cores it will use (which works great during a full render) However when just rendering new explored map and such very little cpu is used and Dynmap ends up falling rather far behind. I have dual 6-core Xeons so there is no lack of CPU to spare, how can i get Dynmap to use more when rendering live like it does for fullrender? Here is my Config for reference 
https://pastebin.com/JLkp19b7
Using Spigot 1.13.2
latest Dynmap ver
Server has 12 cores 24 threads, 16GB RAM available to it, is on its own dedicated SSD just for minecraft.

**Comment by smmmadden** [comment]
there are multiple settings in the configuration.txt file that help govern the resources being used by Dynmap.  I'd suggest experimenting with the below to find the right mix for your server.  These are the settings I use for my 1 Socket / 4 Core / 8 Processors and it works pretty well.  Clearly not a powerhouse such as yours but a pretty good start. :-) -Steve
# How many update tiles to work on at once (if not defined, default is 1/2 the number of cores)
tiles-rendered-at-once: 2
# Parallel fullrender: if defined, number of concurrent threads used for fullrender or radiusrender
# Note: setting this will result in much more intensive CPU use, some additional memory use.  Caution should be used when setting this to equal or exceed the number of physical cores on the system.
parallelrendercnt: 4
# How often a tile gets rendered (in seconds).
renderinterval: 15
# How many tiles on update queue before accelerate render interval
renderacceleratethreshold: 60
# How often to render tiles when backlog is above renderacceleratethreshold
renderaccelerateinterval: 0.2
# How many update tiles to work on at once (if not defined, default is 1/2 the number of cores)
tiles-rendered-at-once: 2
# If true, use normal priority threads for rendering (versus low priority) - this can keep rendering
# from starving on busy Windows boxes (Linux JVMs pretty much ignore thread priority), but may result
# in more competition for CPU resources with other processes
usenormalthreadpriority: true

**Comment by Psy-Virus** [comment]
This is not a support forum. Next time please head over to https://forums.dynmap.us

Thanks
