### ISSUE TITLE
Fullrender doesn't load all map size

### ISSUE THREAD

**Issue by kahiii** [webbukkit/dynmap#2404]
Serveur minecraft spigot 1.13.2
Dynmap core=3.0-beta-3-160, plugin 3.0-beta-3-160
WorldBorder set to 20 000 * 20 000 blocs

After fullrender, only 5 000 * 5 000 blocs are loaded on a perfect square. How can i do a fullrender with all my surface of blocs ?

**Comment by masterX244** [comment]
Are the chunks past 5kx5k generated? worldborder only limits how far players can go. Dynmap doesn't generate chunks that don't exist

**Comment by Psy-Virus** [comment]
For support questions please use the new community forums at https://forums.dynmap.us

Thanks
