### ISSUE TITLE
Dynmap doesn't load/enable on 1.13.2 (it randomly broke)

### ISSUE THREAD

**Issue by cloakfox** [webbukkit/dynmap#2407]
Error on startup: https://pastebin.com/NZFxta3d
PaperSpigot build: 481
Dynmap version: v3.0-beta-3

Plugin list: https://imgur.com/a/LbnAhVa

**Comment by Psy-Virus** [comment]
Please use the provided template if you open an issue.

Thanks

**Comment by cloakfox** [comment]
Lol wtf.

**Comment by Psy-Virus** [comment]
That's what it is for, makes it easier to read for everyone.
We are currently cleaning the (a few days ago 700) issues and trying to get some order in the issue posting process. would be nice, if you could respect this.

**Comment by cloakfox** [comment]
I've tried v3 beta 3. And same errors.
