### ISSUE TITLE
Spigot 1.13.2 External web on linux, server on windows. dynmap_access.php problem

### ISSUE THREAD

**Issue by alpe12** [webbukkit/dynmap#2413]
- [x] Latest Bukkit Plugin
  - Version: 3.0-beta-3-spigot
- [ ] Latest Forge Mod
  - Version:

## Issue Description

I run it on windows, and recently copied the server files to my NAS and tried to serve the dynmap page via my Lighttpd server while running the server on my Windows PC.
I configured the "standalone/dynmap_access.php" to point to the correct location (as viewed by the webserver, that is on linux) and it worked fine.
**The problem is:** when I run the server (windows) this file gets changed and shows the path as windows see it (a drive that is mapped to the NAS), which is different from what the linux see. So the page stops working everytime I start/reload the server.
Maybe add an option to configuration.txt to configure this.

PS: Using SQLite.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
