### ISSUE TITLE
HTTPS on Hosting Service Site

### ISSUE THREAD

**Issue by GeekzGamingz** [webbukkit/dynmap#2417]
I'm trying to put my Dynmap in an iframe in Enjin, however Enjin is https and my dynmap is not. I have seen the other tutorials and issues on this GitHub, but my main issue is that I don't have access to the server (aside from FTP access) due to using a hosting service (mc-hosting.pro) for my minecraft server. Is there any work around I can use?

**Comment by stormboomer** [comment]
The problem you are facing is, that you are trying to setup an iframe on a https connection but the iframe does not redirect to an https source. If you open the developer mode of your browser (F12 for chrome /edge) you can check whats happening on the network tab when reloading the page.
You will see that you browser is mostliky trying to fetch the iframe data via https.
You could try to setup Dynmap with an SSL standalone webserver, but i doubt that this will be an option for you.
You mostliky need some kind of reverse proxy which is doing the HTTPS to HTTP handling or if your Hoster supports php curl you could try using the hosting server as "proxy" in case your hoster is not willing on helping you.

also check out this 
https://stackoverflow.com/questions/18327314/how-to-allow-http-content-within-an-iframe-on-a-https-site

**Comment by GeekzGamingz** [comment]
Yeah, I did see that article, but unfortunately I don't know a whole lot about proxies and such so it's a bit hard for me to follow.

**Comment by Psy-Virus** [comment]
> but my main issue is that I don't have access to the server (aside from FTP access) due to using a hosting service (mc-hosting.pro) for my minecraft server. Is there any work around I can use?

Why don't you check your options with your hosting provider first? Maybe there's a way to work around this.

Also, this is not a support forum. It's a bug tracker.

For support please use https://forums.dynmap.us
