### ISSUE TITLE
Storage type migration

### ISSUE THREAD

**Issue by PoQuatre** [webbukkit/dynmap#2419]
## FEATURE REQUEST
- [x] I would like to propose an additional feature.
- [ ] I would like to propose a config change.
- [ ] I would like to request mod support.
- [ ] I would like to propose another change.

- [x] I have searched the wiki and confirmed that this feature is not already implemented.

## FEATURE INFORMATION
Add a way to migrate the storage type of the map

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
