### ISSUE TITLE
Cave Lighting Glitches On Surface Map

### ISSUE THREAD

**Issue by whiteshark445** [webbukkit/dynmap#2423]
Hi I loaded Dynmap on my 1.6.4 Tekkit Main server and everything was working fine until it started rendering the surface map. There are black spots all over the areas where there are caves and shadows.
![1](https://user-images.githubusercontent.com/46824148/51403857-540f5700-1b17-11e9-9941-68ab20783ebb.png)

**Comment by Flipp3rrr** [comment]
I got the same error, re-rendering should do.

**Comment by whiteshark445** [comment]
Re-rendering did not fix. Would prefer not to do a full-render as it takes about 3 real-life days

**Comment by Psy-Virus** [comment]
Mc-Versions < 1.8.9 are not supported anymore. But to fix the black spots, teleport to the spots to trigger a lightning update by placing a block and removing it.

for further support questions, please head over to https://forums.dynmap.us
