### ISSUE TITLE
Staff+ support

### ISSUE THREAD

**Issue by Flipp3rrr** [webbukkit/dynmap#2424]
## FEATURE REQUEST
- [ ] I would like to propose an additional feature.
- [ ] I would like to propose a config change.
- [x] I would like to request mod support.
- [ ] I would like to propose another change.

- [x] I have searched the wiki and confirmed that this feature is not already implemented.

## FEATURE INFORMATION
I would really like Staff+ vanish support for the dynmap as the vanished staff is clearly visible on the dynmap at the moment. Is this possible?

**Comment by sirlinium** [comment]
Hello,
I would like to up this feature.

Even if we hide the nickname and skin of players in the config it is still possible to see if someone (staff) is vanished.

Thank you,

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
