### ISSUE TITLE
Named Banners as Markers

### ISSUE THREAD

**Issue by Wolvan** [webbukkit/dynmap#2425]
## FEATURE REQUEST
- [X] I would like to propose an additional feature.
- [ ] I would like to propose a config change.
- [ ] I would like to request mod support.
- [ ] I would like to propose another change.

- [X] I have searched the wiki and confirmed that this feature is not already implemented.

## FEATURE INFORMATION
Named banners already show up on ingame maps. Is it possible to have them show up as Markers on Dynmap? Preferably its own layer.

**Comment by RealityTest** [comment]
I just released [a plugin](https://www.spigotmc.org/resources/dynmapbannermarkers-create-markers-by-placing-named-banners.88979/) that does exactly that if anyone is still interested in it.

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2266
