### ISSUE TITLE
Mod-scraper Help

### ISSUE THREAD

**Issue by whiteshark445** [webbukkit/dynmap#2426]
I scraped the mod files for my 1.6.4 tekkit main server and put them in the renderdata folder but I can't seem to get them to work. Do I have to re-render the map for the textures to load?

**Comment by Flipp3rrr** [comment]
Re-rendering is always a good idea when dynmap breaks.

**Comment by whiteshark445** [comment]
Re-rendering did not fix

**Comment by djcraft** [comment]
Hi, I have the problem using mods in 1.12..

My server runs on the latest version of the forge and has the following mods:

- railcraft 12.0.0.4 beta

- jei 1.12.2-4.14.4.259

- AE2 rv6 stable 6

- Mekanism 1.12.2-9.4.13.349 (with generator and tools)

- Inv Tweaks .164

- dynamicsurroundings 1.12.2-3.5.4.2BETA

- dynmap 3.160

**Comment by Psy-Virus** [comment]
> frig off dude

being rude doesn't help anyone!
