### ISSUE TITLE
Dynmap not rendering properly in HD

### ISSUE THREAD

**Issue by Flipp3rrr** [webbukkit/dynmap#2427]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [x] Re-rendered missing chunks using /dynmap fullrender
     - [x] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [x] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [ ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
I recently got dynmap to use SQLite for storage because of file limiting at server.pro and reinstalled it. Since then the dynmap stopped rendering properly:
1. Both the flat and surface maps are 3D
2. Although configured as HD it's not HD

## Reproduce Steps
1. Install dynmap on a server.pro server
2. Use the configuration files below at Additional Information (inside `dynmap.tar.gz.zip`)
3. Render the dynmap

### Here's the full dynmap directory (`dynmap.tar.gz.zip`):
https://1drv.ms/u/s!Ai28LPd6kjx4gvZW319jzfqKObu7BA
### Here's the map:
~~http://149.202.215.216:11424/#~~
EDIT: New map at http://149.202.92.149:11577/
### And here's a screenshot:
![schermafbeelding 2019-01-20 om 19 12 46](https://user-images.githubusercontent.com/33151653/51444061-c12b1400-1cf2-11e9-9d14-c0392fb2e240.png)

**Comment by Flipp3rrr** [comment]
I redid the shadows and perspectives. Hope I fixed it.

**Comment by Psy-Virus** [comment]
Hey there,
please retry with the latest version http://dynmap.us/builds/dynmap/Dynmap-HEAD-spigot.jar

and let us know what's happening.

Also your map doesn't look like you did a full render and also as it is a mixture of either different maps or different map versions.

try the following:
`/dynmap purgeworld <worldname>`
 - wait until dynmap is reporting that the world has been purged.
 - refresh your browser by pressing CTRL + F5

`/dynmap fullrender <worldname>`

check if everything is working.

Also please make sure that there a re no errors reported by Dynmap.

**Comment by Flipp3rrr** [comment]
I'm currently rerendering the dynmap. Thanks!

**Comment by Flipp3rrr** [comment]
@Psy-Virus It didn't work sadly. The flat map is still 3D and not in HD. I didn't change anything except the `Dynmap-HEAD-spigot.jar`

**Comment by Psy-Virus** [comment]
Seems like you are using the wrong perspective for the flat map. Could you post your configs and any templates you may have changed?

**Comment by Psy-Virus** [comment]
Okay, I just saw that you already uploaded everything, sry.

You should check your worlds.txt file and add the appropriate perspectives for each world so DM knows exactly what perspective to use. there are also examples in that file. so it shouldn't be hard to do.

**Comment by Flipp3rrr** [comment]
I specified the perspectives and purged the world. It's currently rerendering.
Hope it works!

**Comment by Flipp3rrr** [comment]
@Psy-Virus It still didn't work.
### I got the following error:
`[ERROR] [dynmap] HDMap missing required attribute 'name' - disabled`
### I edited this:
`  - name: Kingdom
    enabled: true
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_lowres
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "Surface"
        prefix: surface
        perspective: iso_SE_30_hires
      - class: org.dynmap.hdmap.HDMap
        enabled: false`

**Comment by Flipp3rrr** [comment]
@Psy-Virus Everything works now except the 3rd map still renders. How do I fix that?

**Comment by Psy-Virus** [comment]
Glad to hear everything is working now!

:)
