### ISSUE TITLE
Dynmap-worldguard breaks with the latest worldguard beta

### ISSUE THREAD

**Issue by Sikatsu** [webbukkit/dynmap#2431]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [ ] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [ ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Reproduce Steps
1. Download the latest dynmap version and dynmap-worldguard
2. Download the latest worldguard beta from devbukkit (couple of days old)
...
## Additional Information

The developer of worldguard has confirmed that the used method does no longer exist since a month or so.

**Comment by mikeprimm** [comment]
Just released Dynmap-Worldguard 1.1-beta-3, which handles WG 7.0.0-beta-3 (thanks to @wizjany for the update)

**Comment by Sikatsu** [comment]
@mikeprimm Updated to dynmap-worldguard 1.1-beta-3 and it's still not working.

Error: https://pastebin.com/R0Rj8d0G
