### ISSUE TITLE
random chunks behind the view distance

### ISSUE THREAD

**Issue by seema84** [webbukkit/dynmap#2437]
**Version:**
Paper version git-Paper-514 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Dynmap version: core=3.0-beta-3-160, plugin=3.0-beta-3-160

**reproduce**
- create a new Dynmap with some chunks
- update a Spigot Server to Paper (or update spigot to a newer spigot version)

The result can you see here ->
https://imgur.com/a/88ZTajy
https://imgur.com/a/KDYzgvm
https://user-images.githubusercontent.com/28217121/28021228-7aa1a7ca-6587-11e7-804d-0a1dda8aafaf.JPG

**Comment by shueja-personal** [comment]
I can confirm this issue happens with Spigot 1.13.2. I have about ten of these around the world edge.

**Comment by skerit** [comment]
I'm also seeing these random chunks pop up on my dynmap, but maybe dynmap isn't to blame? Doesn't dynmap only render chunks that have already been generated?

**Comment by FedUpWith-Tech** [comment]
You can limit the visibility using dmap and the latest version
