### ISSUE TITLE
processWorldEvent(WORLD_LOAD,

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#2440]
Problem: With us, this reloading always comes with reloading

Spigot version: CraftBukkit version git-Spigot-b0f4c22-2ced023 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Dynmap Version : Dynmap-3.0-beta-3-spigot

**processWorldEvent(WORLD_LOAD,org.dynmap.bukkit.helper.BukkitWorld@6c11b92) - exception
java.lang.NullPointerException: null**

**Comment by Straiker123** [comment]
Same problem :D

**Comment by FedUpWith-Tech** [comment]
Reloading is not recommended. Restart your server if you made a configuration change
