### ISSUE TITLE
ArrayIndexOutOfBoundsException during fullrender

### ISSUE THREAD

**Issue by babillon** [webbukkit/dynmap#2441]
## Server Information

- I can reproduce this issue consistently
     - [X] In Multiplayer 
     - [X] After deleting/renaming the DYNMAP folder
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [X] Re-rendered missing chunks using /dynmap fullrender
     - [X] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [X] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [X] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [X] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
When performing a fullrender the render throws an ArrayIndexOutOfBoundsException error after reaching 2300 tiles. No further updates are registered in the console, and no further tiles are loaded on the browser map no matter how much time is allowed. Fullrender cannot be rerun as the system indicates a fullrender is active.

## Reproduce Steps
1. Start server with fresh, standard config (no changes to config file; totally vanilla) Dynmap
2. Wait until initial load has completed
3. Enter 'dynmap fullrender world' in the console
4. Wait until Dynmap Render reaches 2300 tiles
...

## Additional Information
Error at 2300 tiles: https://pastebin.com/BXLAWbzU
Full Dynmap Load Sequence: https://pastebin.com/JT9pTgqQ

**Comment by fipil** [comment]
Same here.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release- please open a new issue if this persists.
