### ISSUE TITLE
Dynmap error: Error creating maps - Table "Maps" already exists

### ISSUE THREAD

**Issue by SpartanPride7** [webbukkit/dynmap#2442]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [x] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
Dynmap not loading into the server. When using /dynmap, an internal error occures. Startup log and error message logs are below. 

## Reproduce Steps
1. Start the server using this config, and it doesn't load. 
2.
...

## Additional Information

Startup log: https://pastebin.com/QYE63fFh
Internal error when doing /dynmap: https://pastebin.com/nMf2dhvc

**Comment by Psy-Virus** [comment]
Hey there, checkout the latest Dynmap version. You're currently using `2.5-Dev201706100405 `

Latest version for [Spigot](http://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar)

**Comment by Psy-Virus** [comment]
@SpartanPride7,
Has this issue been resolved?

**Comment by SpartanPride7** [comment]
Just saw this now, no it did not fix it. I am now running the latest

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later version, if the issue persists open a new issue
