### ISSUE TITLE
Couldn't load chunk (Spigot 1.13.2 - dynmap v3.0-beta-3-160 )

### ISSUE THREAD

**Issue by splintermik** [webbukkit/dynmap#2444]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [ ] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description

Hello, I have a problem with the Dynmap plugin
I tested the plugin, on a separate server, without any other plugin or players, with the same map as my main server
I have this error message that is spam in the console

https://pastebin.com/DLJA3KcQ

I would like to know how to fix this problem? 

thank you

CraftBukkit version git-Spigot-b0f4c22-a2dd0e3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

[18:41:45] [Server thread/INFO]: [dynmap] Loading dynmap v3.0-beta-3-160
[18:41:45] [Server thread/INFO]: [dynmap] version=git-Spigot-b0f4c22-a2dd0e3 (MC: 1.13.2)

java -version
java version "11.0.2" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+7-LTS, mixed mode)

MariaDB [(none)]> SHOW VARIABLES LIKE "%version%";
+-------------------------+--------------------------+
| Variable_name | Value 
+-------------------------+--------------------------+
| innodb_version | 5.6.41-84.1 
| protocol_version | 10 
| slave_type_conversions | 
| version | 10.1.37-MariaDB-0+deb9u1 
| version_comment | Debian 9.6 
| version_compile_machine | x86_64 
| version_compile_os | debian-linux-gnu 
| version_malloc_library | system jemalloc 
| version_ssl_library | YaSSL 2.4.4 
| wsrep_patch_version | wsrep_25.23

**Comment by mikeprimm** [comment]
Corrupted world data - nothing dynmap can do to fix it
