### ISSUE TITLE
Can't Render DungeonsXL Worlds

### ISSUE THREAD

**Issue by ElricBellamy** [webbukkit/dynmap#2446]
So, I can't render DungeonsXL worlds aka dungeons unless it's named "DXL_Edit_0" which I want it named Sjorborough. Not sure where Dynmap is pulling the name from as the world folder that DXL has is named Sjorborough.

Worlds folder: 

-   name: Sjorborough
    title: DXL_Edit_0
    enabled: true
    extrazoomout: 2
    maps:
    -   class: org.dynmap.hdmap.HDMap
        name: flat
        title: Flat
        prefix: flat
        perspective: iso_S_90_lowres
        shader: Conquest
        lighting: shadows
        mapzoomin: 4
    -   class: org.dynmap.hdmap.HDMap
        name: surface
        title: Surface
        prefix: t
        perspective: iso_SE_30_lowres
        shader: Conquest
        lighting: shadows
        mapzoomin: 4
        boostzoom: 2

Note: I've tried using both title and name as Sjorborough, and I've tried title Sjorborough, name DXL_Edit_0 and vice versa and none work? How do I get it to work with the name Sjorborough?

**Comment by ElricBellamy** [comment]
Anything at all on this?

**Comment by Davous3k** [comment]
Hello, are you sure with this name? I think DXL is creating new map for every new game, so every game have uniqe map with same name. So Dynmap can't catch the specific world and it still loading same world from zero. But I am not sure about that.

EDIT: Maps have UUIDs as players, so name of the map is still same, but UUID is different.
