### ISSUE TITLE
The table 'dynmap_Tiles' is full

### ISSUE THREAD

**Issue by DevilishDante** [webbukkit/dynmap#2450]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [x] Re-rendered missing chunks using /dynmap fullrender
     - [x] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
hello i have this in my console, i checked configuration file for see if isn't correct and , he is correct and isn't my sql database because i have logblock on it and it work as expected, how can resolve this thnaks you
##config fil
here -> [https://pastebin.com/9H2nLupr](url)
[https://puu.sh/CVReK/0fd3ef5e7b.PNG](url)

## Reproduce Steps
1. Just render a map of 30k x 30k in 3D and 2D

**Comment by jsmienk** [comment]
Your links don't work.

**Comment by DevilishDante** [comment]
https://puu.sh/CVReK/0fd3ef5e7b.PNG
https://pastebin.com/9H2nLupr

**Comment by DevilishDante** [comment]
the issues provide of my host so isn't related to plugin
