### ISSUE TITLE
body player indicator messed up (instead of face)

### ISSUE THREAD

**Issue by Eld0r** [webbukkit/dynmap#2452]
## Server Information
- [ ] Latest Forge Mod
  - Version: forge-1.12.2-14.23.4.2707
- [X] I can reproduce this issue consistently
     - [X] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [x] Re-rendered missing chunks using /dynmap fullrender
     - [x] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [x] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
After updating to snapshot version the character bodies are messed up (faces are okay) 
- sometimes the left limbs are wider (head posponed may be a optical Ilusion ^^)
- sometimes the left limbs are missing completely

After deleting the faces folder, dynmap (snapshot feb/3) downloaded them wrong again (see pic)
I changed back to Dynmap-3.0-beta-3-forge-1.12.2.jar (09-Dec-2018) and so do the sprites; when a player logs in they update automatically to the correct body again.

## Reproduce Steps
1. use config "showplayerbody: true"
2. update jar to Dynmap-3.0-SNAPSHOT-forge-1.12.2 (03-Feb-2019)
(The version DynmapBlockScan-3.0-beta-3-forge-1.12.2.jar (09-Dec-2018) worked fine)
3. watch the map (or face folder), the player body sprites update automatically when a player log in

## Additional Information
![image](https://user-images.githubusercontent.com/8625950/54136855-d1bb5900-441c-11e9-942a-99a0409dd4c5.png)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
