### ISSUE TITLE
Custom Texture Pack

### ISSUE THREAD

**Issue by Scorpionvssub** [webbukkit/dynmap#2453]
## Issue Description

I followed guides to enable the texture pack and its giving me a  
"14.03 22:35:11 [Server] [Informatie] [dynmap] Loading texture pack ScorpionHD.zip"
Nothing else happens, no confirmation, no error, nothing.

Rendering returns default textures but again, never getting any reason why its not working or what its missing.

Textures to render:
![image](https://user-images.githubusercontent.com/12249763/54393359-422ada00-46aa-11e9-8eeb-0fa89a33e974.png)

Rendering done instead:
![image](https://user-images.githubusercontent.com/12249763/54393373-4bb44200-46aa-11e9-9780-54cf353b670c.png)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
