### ISSUE TITLE
Use MySQL for Player Login

### ISSUE THREAD

**Issue by EliSauder** [webbukkit/dynmap#2456]
## FEATURE REQUEST
- [x] I would like to propose an additional feature.
- [ ] I would like to propose a config change.
- [ ] I would like to request mod support.
- [ ] I would like to propose another change.

- [x] I have searched the wiki and confirmed that this feature is not already implemented.

## FEATURE INFORMATION
I would like to be able to store the player's logins on the SQL server. Right now it is a simple txt file.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
