### ISSUE TITLE
Slime Chunks on DynMap

### ISSUE THREAD

**Issue by EliSauder** [webbukkit/dynmap#2457]
## FEATURE REQUEST
- [x] I would like to propose an additional feature.
- [ ] I would like to propose a config change.
- [ ] I would like to request mod support.
- [ ] I would like to propose another change.

- [x] I have searched the wiki and confirmed that this feature is not already implemented.

## FEATURE INFORMATION
I have made a relavent post on the forum,
https://forums.dynmap.us/viewtopic.php?f=4&t=45

I would like to view slime chunks on dynmap.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
