### ISSUE TITLE
Error while raytracing tile

### ISSUE THREAD

**Issue by SpartanPride7** [webbukkit/dynmap#2459]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [x] Re-rendered missing chunks using /dynmap fullrender
     - [x] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
Every time dynmap is rendering chunks, I am spammed by these errors:
[dynmap]: Error while raytracing tile: perspective=iso_S_90_lowres, coord=196,73,179, blockid=minecraft:leaves2[check_decay=false,decayable=true,variant=acacia], lighting=14:6, biome=DESERT
java.lang.NullPointerException: null

## Reproduce Steps
1. 
2.
...

## Additional Information

Server startup log with the spammy errors at the end: https://pastebin.com/Eu0VxhP1

I had to disable the plugin for now since these errors would not stop

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
