### ISSUE TITLE
Removing sending the players IP address from web chat to the server by default?

### ISSUE THREAD

**Issue by fahlur** [webbukkit/dynmap#2460]
I added dynmap earlier today, I havent set any of the settings yet in the configuration, so why by default for the web chat does it send the persons IP address as the person who sent the message for all to see? This was not only seen by the players on the server but anyone watching on of the players streams that was streaming. I feel this is a very insecure method/tactic for a default setting on this plugin, and decided to submit this request so it couldn't be a future issue. Thank you for taking time to read this message.

For obvious reasons I have blacked out he ip address in the screenshot
![Capture](https://user-images.githubusercontent.com/11714213/54965164-4b833480-4f3d-11e9-8cdd-9c923322d84a.PNG)

**Comment by fahlur** [comment]
I have checked the config
isnt this suppose to hide the ip?

hidewebchatip: true

**Comment by Landy005** [comment]
huh hows this closed with no answer

**Comment by fahlur** [comment]
> 

good question, idk why it was, it wasnt answered and I was clear that I was wondering if that config option was suppose to disable it and it didnt. It was suppose to if I understood that node correctly but it didnt, also iirc back then I just ended up disabling the chat to begin with.  Now currently we don't even use dynmap anyways

**Comment by sudofox** [comment]
We recently disabled this option, hoping to track down someone who was sending abusive messages, but did not think it'd show up anywhere but the console. Extremely surprised when it exposed someone's IP in chat.

**Comment by LucaAndAlberto64** [comment]
Had the same thing happen on my server, It's weird that Dynmap shows the IP in chat too, It would make sense if it only sent the IP in console because that can be useful for finding out who is spamming Dynmap and ban their IP. No one else was active on my server at the time so no one else saw their IP. I fixed it by turning the option back on, It would be great if they could make it only show the IP in console though.
