### ISSUE TITLE
Topo map don't render contour line when the difference isn't 1 block

### ISSUE THREAD

**Issue by 203Null** [webbukkit/dynmap#2461]
Two block difference or grass right next to it will cause the contour line not render
![image](https://user-images.githubusercontent.com/19933093/55118744-c4ad9380-50c5-11e9-8630-108cfc6d6887.png)
and please fix the missing pixel of line intersection, this is really tripping me XD
![image](https://user-images.githubusercontent.com/19933093/55118845-1fdf8600-50c6-11e9-9d2e-e5607d430e58.png)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
