### ISSUE TITLE
How to disable all these messages?

### ISSUE THREAD

**Issue by bloggy** [webbukkit/dynmap#2464]
Latest dynmap on spigot 1.13.2 with custom resourcepack spamming errors on render update:

https://pastebin.com/dPC4eBUh

The question is, how to disable these error messages to appear in console? We are unable to fix all of these issues so we need a way to just disable the dynmap message spam in the console.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
