### ISSUE TITLE
Option to hide marker visibility in certain worlds only.

### ISSUE THREAD

**Issue by mibby** [webbukkit/dynmap#2465]
## FEATURE REQUEST
- [x] I would like to propose an additional feature.
- [x] I have searched the wiki and confirmed that this feature is not already implemented.

Would it be possible to add an option to hide markers in certain worlds? Specifically, I'd like to hide the spawn marker from being shown in a custom world, but keep it active in others.

Adding ``    showspawn: false`` to the worlds.txt file did not seem to do anything.

**Comment by FedUpWith-Tech** [comment]
this is possible using the dmarker command, I'm going to close this issue as it is likely no longer relevant but please reopen it or make a new one if you still need help
