### ISSUE TITLE
Cant unpause render

### ISSUE THREAD

**Issue by LucianDevran** [webbukkit/dynmap#2467]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Reproduce Steps
1. Do /dynmap pause
2. Do /dynmap pause none

## Additional Information
Render does not resume after /dynmap pause none

**Comment by VaiTon** [comment]
Does the plugin log to the sender that the renders have been paused?
Because it should from these lines:
https://github.com/webbukkit/dynmap/blob/57fa00b7c3b3b86aca564f25737744727f82d439/DynmapCore/src/main/java/org/dynmap/DynmapCore.java#L1431-L1446

**Comment by LucianDevran** [comment]
Yes it sends that its paused but if you do  /dynmap pause none it also sends that the renders are paused

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release- please open a new issue if this persists.
