### ISSUE TITLE
Parity for offline/online marker display

### ISSUE THREAD

**Issue by smellyonionman** [webbukkit/dynmap#2468]
## FEATURE REQUEST
- [ ] I would like to propose an additional feature.
- [ ] I would like to propose a config change.
- [ ] I would like to request mod support.
- [X] I would like to propose another change.

- [X] I have searched the wiki and confirmed that this feature is not already implemented.

## FEATURE INFORMATION
I feel offline player icons should be hidden in cases where online player icons would be.  As it stands, I have login required for markers but I see offline players prior to logging in to the map.

**Comment by FedUpWith-Tech** [comment]
this is possible with the config
