### ISSUE TITLE
Could not update map: Not Found

### ISSUE THREAD

**Issue by timr2000** [webbukkit/dynmap#2476]
Hello there, I've set this up http://prntscr.com/nlnfp3, The webserver is working OK. but getting a Could not update map: Not Found, Error. im trying to connect dynmap to an another disk on my server. But seems like its not working. The map render to the disk works, But the website is broken. Searching for this a verry long time. Cant find a solution for this issue. Help! xD

**Comment by FedUpWith-Tech** [comment]
your tilespath is misconfigured, I'm going to close this due to age but please reopen it or open a new one
