### ISSUE TITLE
Spigot 1.14. Chunks not unload

### ISSUE THREAD

**Issue by rumickon** [webbukkit/dynmap#2477]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [x] Re-rendered missing chunks using /dynmap fullrender
     - [x] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
Dynmap for Spigot 1.14 (dev branch v3.0) do not unload chunks after using.

## Reproduce Steps
1. Use any Spigot plugin to display the number of loaded chunks.

## Additional Information
This can help:
1) Do not use World.loadChunk(). Only World.getChunkAt().
2) Do not use World.isChunkInUse(). Method is deprecated.

**Comment by mikeprimm** [comment]
Cannot use getChunkAt - would cause unbounded cascade of world growth, as there is no way to suppress chunk generation.

**Comment by rumickon** [comment]
For test I just change `rslt = w.loadChunk(x, z, true)`; to `rslt = true` in MapChunkCache114.java using commit 641f142cd3ccdcbfb04eda3059be22dd9ed93783
Looks fine.
