### ISSUE TITLE
Player movement update speed config

### ISSUE THREAD

**Issue by MicleBrick** [webbukkit/dynmap#2478]
## FEATURE REQUEST
- [x] I would like to propose an additional feature.
- [x] I would like to propose a config change.
- [ ] I would like to request mod support.
- [ ] I would like to propose another change.

- [x ] I have searched the wiki and confirmed that this feature is not already implemented.

<!-- FEATURE INFORMATION - Please explain what you want changed/added and why.
## FEATURE INFORMATION
I'd like there to be a way to change the rate at which the map updates player positions, for fast movement to show. I searched the config and the wiki but I haven't been able to find it.

**Comment by FedUpWith-Tech** [comment]
please give more info at how you want this implemented if you still would like to see this implemented- please open a new issue if this persists.
