### ISSUE TITLE
Java 12 Support

### ISSUE THREAD

**Issue by Cerexus** [webbukkit/dynmap#2480]
Hey, don't know if it does but if not i hope you could add Java 12 Support. 

Java 12 is in some cases not perfectly supported. At this link you can see the Problem.  
https://github.com/CitizensDev/Citizens2/issues/1779
Thanks :)

**Comment by mikeprimm** [comment]
No plans to support Java 12 at this point in the formal releases - the code is open source, so feel free to build using JDK 12, but if I do the same, everyone running JDK 8 breaks (and that is nearly all of my user base).

**Comment by YourCoalAlt** [comment]
I use Java 12 and have not run into any major issues using Dynmap 3.0-beta4 so far.
