### ISSUE TITLE
All grass blocks colored as plains texture | Spigot 1.14.1

### ISSUE THREAD

**Issue by MonstahGames** [webbukkit/dynmap#2483]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [x] Re-rendered missing chunks using /dynmap fullrender
     - [x] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
Hello! When building the Dynmap from recent commits (1.14), i'm seeing a weird issue when rendering biomes. All biomes' grass blocks appear the same color as the plains grass block.
You can see a Plains and a Jungle biome, both with the same grass block.
This didn't happen on 1.13.2, so i'm not sure what changed that could cause this.
Any help is appreciated!

## Reproduce Steps
1. Render a Dynmap world
2. Enjoy!

## Additional Information
https://imgur.com/a/Kp68hCs

**Comment by MonstahGames** [comment]
Sorry about that, (maybe) reopening soon, accidentaly published the issue before even editing or viewing the template

**Comment by Tonius** [comment]
I'm having the same issue on Spigot version `git-Spigot-01d0f04-455023c` using the `Dynmap-HEAD-spigot.jar` build (commit [`f69ce76`](https://github.com/webbukkit/dynmap/commit/f69ce760f0abe1a2e1472c022d403b8d399415a1)).

It seems to be happening with both newly generated and upgraded worlds. I tried resetting all of Dynmap's configuration, but to no avail.

I also noticed that all water is now rendered with a very dark blue color.

https://i.imgur.com/EubPwST.jpg

**Comment by mikeprimm** [comment]
Should be fixed in v3.0-beta-4 release that just dropped (or latest dev builds)

**Comment by ThybeVB** [comment]
Will start testing soon, but quick question, does this require a rerender of the world?

**Comment by mikeprimm** [comment]
Yep

**Comment by ThybeVB** [comment]
Fixed!
