### ISSUE TITLE
Messages not remaining Paper #28 1.14.1 Dynmap 3.0 Spigot-SNAPSHOT

### ISSUE THREAD

**Issue by Jackietkfrost** [webbukkit/dynmap#2484]
## Server Information

- [x] Latest Bukkit Plugin
  - Version: Dynmap 3.0 Spigot-SNAPSHOT.jar

- I can reproduce this issue consistently
     - [X] In Multiplayer 
     - [X] After deleting/renaming the DYNMAP folder
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [x] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [x] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description
I've tried several ways of fixing my chat to not age out, but something isn't working. I resorted to timing them out at a very long interval.
```java  
...
    messagettl: 250
    # Optional: set number of lines in scrollable message history: if set, messagettl is not used to age out messages
    #scrollback: 150
    # Optiona; set maximum number of lines visible for chatbox
    #visiblelines: 10

...
```

## Reproduce Steps
1.Open Configuration
2. Change scrollback/messagettl
...

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
