### ISSUE TITLE
How does the Tile URL system work?

### ISSUE THREAD

**Issue by Esinko** [webbukkit/dynmap#2486]
How does it generate the file names? I'm just wondering how it works and I'm intrested in learning java, javascript and jquery.

So: How does it generate them -> Where can I find that in the code?

Thanks.

**Comment by samuelh2005** [comment]
@Esinko Sorry to mither you, but do you remember how you solved this? I'm struggling to understand the tile URL to.

**Comment by Esinko** [comment]
I didn't. I built my system in a way that I didn't have to understand the tile URL.
