### ISSUE TITLE
Overlays

### ISSUE THREAD

**Issue by thunderai** [webbukkit/dynmap#2488]
## FEATURE REQUEST
- [X ] I would like to propose an additional feature.
- [ ] I would like to propose a config change.
- [ ] I would like to request mod support.
- [ ] I would like to propose another change.

- [X ] I have searched the wiki and confirmed that this feature is not already implemented.

<!-- FEATURE INFORMATION - Please explain what you want changed/added and why.
## FEATURE INFORMATION

a). Add Regional Overlay layer that allows seeing regional boundaries
b). Add Nether Portal Overlay layer which allows seeing the range of nether portals

**Comment by thunderai** [comment]
Not sure where the requests went, but they were:
a). Regional Boundaries Overlay
b). Nether Portal Range Overlay

**Comment by stormboomer** [comment]
I think you could achieve that by using dynmap worldguard. or are you requesting a different feature?
If you just want the boundaries of a region, set the region style fillOpacity to 0, that will make the fill color transparent

**Comment by thunderai** [comment]
There is a shader that shows the mcr, but that's not really what I want.

**Comment by stormboomer** [comment]
so you are not looking for something like this
![image](https://user-images.githubusercontent.com/25079531/58752938-7c409680-84b7-11e9-829e-13a12452e183.png)

**Comment by thunderai** [comment]
I'm not, but what is that?

**Comment by stormboomer** [comment]
thats dynmap world guard, it basicly allows you to show regions on your dynmap. As far as I understand your request, thats exactly what you want. Dynmap world guard will display regional boundaries of world guard regions and fill them up. please have a look at https://dev.bukkit.org/projects/dynmap-worldguard or add more information to your request.

**Comment by thunderai** [comment]
What I really want is clickable regions which then allow me to delete regions on the fly. I have a PHP tool that does this, but its not perfect and could be done in dynmap easier.

Here is what my app looks like, i just want to be able to do it in dynmap. 

https://i.imgur.com/P22xREh.png

**Comment by Pisi-Deff** [comment]
@thunderai 
I wrote a dynmap component that adds overlays for chunk and region borders. It doesn't use any server data and works entirely in the browser, calculating where borders should be based on coordinates. And I'd be happy to share it.

demo:
![image](https://user-images.githubusercontent.com/1923619/59150403-802a6680-8a2b-11e9-83cb-6775194772b7.png)
![image](https://user-images.githubusercontent.com/1923619/59150407-99cbae00-8a2b-11e9-9ee5-6d03d88f25b0.png)

But it sounds like you also want the region deletion logic to be part of dynmap? I feel like that would just be way out of scope for dynmap.

**Comment by thunderai** [comment]
That's impressive. I'm alwayshappy to see it.

Right nowninjust use the mcr shader.



Sent from my Sprint Samsung Galaxy Note9.


-------- Original message --------

**Comment by Pisi-Deff** [comment]
Sorry for delay, was busy.

Put into `mc/plugins/dynmap/web/js`:
https://gist.github.com/Pisi-Deff/92e00008f809383c82d926f843b6dd0f

Add to `mc/plugins/dynmap/configuration.txt` somewhere under `components:`:
```
  - class: org.dynmap.ClientComponent
    type: regiongrid
```

If I ever am bored enough to give it some proper polish, I'll open a pull request to get it into dynmap officially. But for now, this is it.

**Comment by thunderai** [comment]
Cool. I'll give it a shot.



Sent from my Sprint Samsung Galaxy Note9.


-------- Original message --------

**Comment by thunderai** [comment]
Chunks and Region show up on the map layer list, but nothing is displayed.

Attached is a map with the layer toggled, but not showing.

Thanks.
________________________________

**Comment by Pisi-Deff** [comment]
I don't see any attachments on github.

Also, due to performance reasons, the layers will currently only be drawn if there are less than 1500 chunks/regions respectively visible at a time.
I was still seeing regions at my lowest zoom amount. But perhaps your map is set up for even lower zoom levels or your display just has a bigger resolution.

First check whether you see borders if you zoom in further. If yes, try increasing the `1500` value on line  62 of the js script. Might cause lag though.

I do have an idea to optimize this though. Will try implementing it tomorrow.

**Comment by thunderai** [comment]
I got it working.

Looks great. Now it in could click on them and open a dialog box.



Sent from my Sprint Samsung Galaxy Note9.


-------- Original message --------

**Comment by Pisi-Deff** [comment]
Well, as I mentioned before, the ability to just delete regions seems out of scope for dynmap. Would have to start messing with adding a new permission, having to check that user is logged into dynmap, new AJAX call to request region deletion, support deleting region on the backend, etc. A lot of work for something that is not dynmap's purpose.

If security is not a concern (for example if only you have access to the map) then imo the "best" solution would be that the dialog just sends a request with the region's details to a nearby php script or whatever which then actually handles the deletion.

If you have any less extreme ideas for what kind of info such a dialog would provide users though, I'm all ears :D

**Comment by thunderai** [comment]
I understand. I'm sure I can come up with other cartography tools



Sent from my Sprint Samsung Galaxy Note9.


-------- Original message --------
