### ISSUE TITLE
Setting to disappear on the map as you enter the cave

### ISSUE THREAD

**Issue by zlwkrdmsska** [webbukkit/dynmap#2492]
![asd](https://user-images.githubusercontent.com/47001449/58583715-98fa8580-828f-11e9-968e-0944ad70e332.png)

Who knows how to set it up? I have a faction server running, but what if I go into a cave or house and disappear from the map? Do not configure it.

I go under the basement and keep on the map

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
