### ISSUE TITLE
Enabling color codes makes players not able to view their own positions

### ISSUE THREAD

**Issue by thagreenkronic** [webbukkit/dynmap#2494]
## Server Information

- I can reproduce this issue consistently
     - [x] In Multiplayer 
     - [x] After deleting/renaming the DYNMAP folder
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- I have tried the following diagnostics;
     - [ ] Re-rendered missing chunks using /dynmap fullrender
     - [ ] Cleared cached tiles using /dynmap purgeworld [world] (especially if using a map from an older version)
     - [x] Deleted/Renamed the dynmap folder to regenerate configs and files fresh
     - [ ] Tested using the 'HEAD' version from dynmap.us/builds (these are stable to use)
     - [ ] Rechecked the Minecraft Server and Webserver Config (If using an external Webserver)

## Issue Description

Enabling player color codes makes it so that noone can view themselves on the map (unless they have the admin seeall permission). All config options are correct.

## Reproduce Steps
1. Setup dynmap so that players can only view their own locations when logged in
2. Turn on player color codes
3. Observe that you cannot see yourself on the dynmap unless you have the see all permission
4. Turn off color codes
5. Observe as you can now see your own position on the map
...

## Additional Information

MC version:

1.13.2
Spigot/Paper Version Number: Paper #624 for MC 1.13.2

Plugins being used on the server:

Advanced Portals
Chestshop
Dynmap
DiscordSRV
editable signs
enjinminecraftplugin
essentialsX
essentialsXChat
essentialsXSpawn
FastLeafDecay
LuckPerms-Bukkit
Matrix
Mycommand
NuVotifier
PlayerHeads
plot2dynmap
PlotSquared
PluginConstructorAPI
ProtocolLIB
serverlistMOTD
serverrestorer
simple egg
skript
u-chat
vault
worledit
Worldguard

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
