### ISSUE TITLE
Web not work in the linux centos o.s

### ISSUE THREAD

**Issue by successed** [webbukkit/dynmap#2495]
version 3.0-SNAPSHOT-202

my server version 1.14.2 latest paper

web service not a work on te linux centos o.s

**Comment by mikeprimm** [comment]
It works - confirmed on Centos 6 and 7

**Comment by successed** [comment]
> It works - confirmed on Centos 6 and 7

HOW ? GİVE ME TUTORİAL CENTOS 6 VİDEO PLEASE.

**Comment by mikeprimm** [comment]
There are no special instructions - it installs the same as everywhere else: drop in the plugin and start up the server.  If you have firewall configured, you will need to open TCP 8123 to be able to access it from off the server box, same as you need to do for TCP 25565 for the MC server itself.

**Comment by successed** [comment]
> There are no special instructions - it installs the same as everywhere else: drop in the plugin and start up the server. If you have firewall configured, you will need to open TCP 8123 to be able to access it from off the server box, same as you need to do for TCP 25565 for the MC server itself.

İ DON'T HAVE FİREWALL, İ DİSABLED ALL OF THİS.

**Comment by mikeprimm** [comment]
I DON'T RESPOND TO CAPITALS - SAVE IT FOR YOUTUBE COMMENTS!

You've given me and the other moderators nothing to work with - reopen an issue using the template and provide full information.  "Does't work" is a worthless and pointless statement - what did you do, what did you try, what is it that you are seeing that isn't what you would expect.  Anything less than this is wasting your time and mine....
