### ISSUE TITLE
Render question [1.14.2]

### ISSUE THREAD

**Issue by Sikatsu** [webbukkit/dynmap#2497]
Hey, this is not really a bug report but more like a question I guess.

Last night I extended my worldborder by 3000 radius.
After that I did a worldborder fill and then a dynmap fullrender.

Everything that was already rendered, changed in terms of colors.
But the new areas have not been rendered, the render stopped at the edge of what was already rendered.

What did I do wrong?

http://mc.villagercraft.nl:8050

**Comment by jonassm** [comment]
I don't know about the last part but i also noticed that colors(lightning) has changed.

**Comment by Sikatsu** [comment]
Yeah, grass looks all the same now and water is black

**Comment by mikeprimm** [comment]
Try build 210 or later - https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar
