### ISSUE TITLE
Critical incompat with Dynamic trees at 1.12

### ISSUE THREAD

**Issue by Noire86** [webbukkit/dynmap#2499]
## Server Information
AtomMC 1.12 Forge

## Issue Description
Trees provided and generated by Dynamic trees are not rendered. No leaves or branches.
Even DynmapBlockScan did not help

## Reproduce Steps
1. Install Dynmap 3.0 and Dynamic trees simultaneously
2. Render map
![image](https://user-images.githubusercontent.com/9317997/58763223-c16cd300-8560-11e9-9d4d-3c0a635d56e5.png)

**Comment by Fureniku** [comment]
I'm experiencing this too, which is a shame because the trees are so nice in-game.

Even just having default sized logs and leaves would be nice for the map though, would that be possible as a fix/workaround?

**Comment by Magi1053** [comment]
+1 for this

**Comment by Fureniku** [comment]
Check through the issues for the recent one about Chisel. Someone has a modified build of blockscan which generates a lot more files, and it fixes trees too - although leaves arent coloured, but at least they show!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Magi1053** [comment]
Could you please provide a link?

**Comment by Fureniku** [comment]
Yup, it's here: https://github.com/webbukkit/DynmapBlockScan/pull/40

Sorry, was mobile earlier so couldn't easily check :)

**Comment by AU518987077** [comment]
Even after generating with DynmapBlockScan-3.0-SNAPSHOT-forge-1.12.2.jar and both leaving and restarting, and  moving and restarting 
"dynamictrees-texture.txt"
"dynamictrees-models.txt"
and
"dynamictreestfc-texture.txt"
"dynamictreestfc-models.txt"
from "\dynmap\renderdata\modsupport" to "\dynmap\renderdata\"
I am still not getting any trees wood or leaves to render.
![image](https://user-images.githubusercontent.com/24924661/135702796-0e6f5816-da14-49ea-a051-1576badff4a1.png)
I would love to use dynamic trees and dynamictreestfc on my servers but am very relunctant to if i can't also have a dynmap for my players to see the world with. 
I would even settle for just leaves or full block wood blocks at this point.

Please advise on what I am doing wrong or if this is an issue that will get addressed and addressed for the 1.12.2 versions as well.

**Comment by Bt-Junkie** [comment]
Did anyone find a fix for this? :(

**Comment by ScarletDor** [comment]
why close the issue?

**Comment by ScarletDor** [comment]
its not work @FedUpWith-Tech
