### ISSUE TITLE
DYNMAP İS NOT WORK LİNUX CENTOS6 !

### ISSUE THREAD

**Issue by successed** [webbukkit/dynmap#2500]
i have latest paperspigot #65
dynamap version is  Dynmap version: core=3.0-SNAPSHOT-202, plugin=3.0-SNAPSHOT-202

DYNMAP İS NOT WORK LİNUX CENTOS6 !

İ HAVE NOT İPTABLES, İAM DİSABLED FİREWALL.

**Comment by jwshields** [comment]
It does work; you've likely configured it incorrectly.

**Comment by successed** [comment]
> It does work; you've likely configured it incorrectly.

I did not configure. i use default.

**Comment by mpdk** [comment]
what does your log say ?
Are you using a dedicated server ? or a minecraft host, and have they opened for port 8123. 
I'm running latest paper-65 and latest dynmap snapshot, and it works fine.

**Comment by successed** [comment]
> what does your log say ?
> Are you using a dedicated server ? or a minecraft host, and have they opened for port 8123.
> I'm running latest paper-65 and latest dynmap snapshot, and it works fine.

How? can you tell me how you can do a video?

**Comment by Prof-Bloodstone** [comment]
@successed What host do you use? Dedicated? VPS? Or "Minecraft" server?
If the last, you need to see what ports you do have open or ask your host to check it for you and open more. You should then assign this port in `plugins/dynmap/configuration.txt`, in a field `webserver-port`.
Dynmap has decent documentation: https://github.com/webbukkit/dynmap/wiki/
Same as above, it works for us just fine.

**Comment by successed** [comment]
> @successed What host do you use? Dedicated? VPS? Or "Minecraft" server?
> If the last, you need to see what ports you do have open or ask your host to check it for you and open more. You should then assign this port in `plugins/dynmap/configuration.txt`, in a field `webserver-port`.
> Dynmap has decent documentation: https://github.com/webbukkit/dynmap/wiki/
> Same as above, it works for us just fine.

i have vds and my firewall is not work because i disabled. İ read wiki and used.

**Comment by mikeprimm** [comment]
Check to see if your VPS is running with SELinux enabled - if so, either disable it or configure it to allow TCP 8123 to be accessed from the public port.  Also, if you are on a VPS, you might not have a firewall, but your VPS provider might - it might be necessary to request the port be opened by them.  If you can 'curl http://localhost:8123' and get a response, then it's firewalling outside your server instance.

**Comment by successed** [comment]
> Check to see if your VPS is running with SELinux enabled - if so, either disable it or configure it to allow TCP 8123 to be accessed from the public port. Also, if you are on a VPS, you might not have a firewall, but your VPS provider might - it might be necessary to request the port be opened by them. If you can 'curl http://localhost:8123' and get a response, then it's firewalling outside your server instance.

i have plesk panel.

**Comment by successed** [comment]
i need explain.
