### ISSUE TITLE
without function    /dmap mapdelete Farmwelt:Surface

### ISSUE THREAD

**Issue by xXjojojXx** [webbukkit/dynmap#2502]
10:22:33XXXXJOJOXXXX issued server command: /dmap mapdelete Farmwelt:Surface
10:22:34Unknown command. Type "/help" for help.

10:22:50XXXXJOJOXXXX issued server command: /dmap mapdelete Farmwelt:surface
10:22:55Unknown command. Type "/help" for help.

This happens when I execute the command I have read through the wiki and even that does not work you could give me a command that works to remove.

**Comment by korhox** [comment]
Is dynmap loaded correctly? (/plugins)

What is output of /dynmap version?

**Comment by xXjojojXx** [comment]
Serve restart helped^^ thx
