### ISSUE TITLE
No beds on (1.15.1) - Dynmap v3.0-beta-9

### ISSUE THREAD

**Issue by Konata400** [webbukkit/dynmap#2504]
Tested on Dynmap v3.0-beta-4

Beds not show, in Flat or Surface.

**Comment by ghost** [comment]
No beds on 1.15.1 Dynmap v3.0-beta-9

**Comment by ghost** [comment]
![2019-12-24_01 11 55](https://user-images.githubusercontent.com/34619567/71386001-0e8ec000-25eb-11ea-8860-01aa1a66087f.png)
![imagen](https://user-images.githubusercontent.com/34619567/71386007-13537400-25eb-11ea-9d42-d4ceb01dcffc.png)
![imagen](https://user-images.githubusercontent.com/34619567/71386023-33833300-25eb-11ea-8902-1ff4f6984d1f.png)

**Comment by FedUpWith-Tech** [comment]
this is fixed in a later version. Sorry you never got notified
