### ISSUE TITLE
Dark spots scattered around the map.

### ISSUE THREAD

**Issue by trevholland** [webbukkit/dynmap#2505]
I have no idea if I'm doing this correctly so my apologies if this isn't the correct way to go about this.  I had a fresh install of Spigot with Dynmap starting with 1.14. I've since upgraded to 1.14.1 and now 1.14.2. This issue has been around since the start.

I'm noticing various chunks are rendering darker on the map than others. For no apparent reason, either. These aren't under a cave or anything like that. Here's a screenshot of a portion of the map:

https://i.imgur.com/Vimbsjw.png

**Comment by mikeprimm** [comment]
A biome shading problem was recently fixed - you'll need to do a fullrender of the whole map to see everything with the correct shading.

**Comment by trevholland** [comment]
Awesome. Thanks for the quick reply!
