### ISSUE TITLE
Linux o.s not a work dynmap latest

### ISSUE THREAD

**Issue by successed** [webbukkit/dynmap#2508]
my linux centos 6 operating system is installed on the server.
I have a plesk panel on my server and the firewall is completely closed.

I put the plugin in the plugins folder, restart the server, and the plugin is running.
I'm writing a command from the game it is work.

The web service of the plugin does not work.

**Comment by Teumaat** [comment]
Someone should block this guy..

**Comment by successed** [comment]
> Someone should block this guy..

why? this not work centos 6.

**Comment by Teumaat** [comment]
Because you never seem to give constructive feedback on questions by other users who try to help you. You only repeat your problem. We can not look in our crystal ball and see what is wrong on your system. You need to give information about what you already have tried. What errors you get. Stuff like that.

**Comment by successed** [comment]
> Because you never seem to give constructive feedback on questions by other users who try to help you. You only repeat your problem. We can not look in our crystal ball and see what is wrong on your system. You need to give information about what you already have tried. What errors you get. Stuff like that.


Although the firewall is closed I can not reach the site, only the web part of the site does not work.

**Comment by rautamiekka** [comment]
> > Because you never seem to give constructive feedback on questions by other users who try to help you. You only repeat your problem. We can not look in our crystal ball and see what is wrong on your system. You need to give information about what you already have tried. What errors you get. Stuff like that.
> 
> Although the firewall is closed I can not reach the site, only the web part of the site does not work.

If you say the firewall is closed you mean all network connectivity is blocked.

**Comment by successed** [comment]
> > > Because you never seem to give constructive feedback on questions by other users who try to help you. You only repeat your problem. We can not look in our crystal ball and see what is wrong on your system. You need to give information about what you already have tried. What errors you get. Stuff like that.
> > 
> > 
> > Although the firewall is closed I can not reach the site, only the web part of the site does not work.
> 
> If you say the firewall is closed you mean all network connectivity is blocked.

WTF, ipconfig is disabled.what else do I have to do to understand this?
