### ISSUE TITLE
Dynmap rotation

### ISSUE THREAD

**Issue by William69420420** [webbukkit/dynmap#2509]
So I have a big map and before I fully rendered it I realized it was facing the wrong direction. I have read previous issues about this but I was unable to locate where in the config to change the values. Thanks

**Comment by Aaron2550** [comment]
You can change the perspective in the worlds.txt check out [https://github.com/webbukkit/dynmap/wiki/Full-list-of-predefined-perspectives](https://github.com/webbukkit/dynmap/wiki/Full-list-of-predefined-perspectives)
anything with 90 (90degrees) is topdown, the default is South
