### ISSUE TITLE
Dynmap title shows the MOTD

### ISSUE THREAD

**Issue by Sikatsu** [webbukkit/dynmap#2512]
It seems the latest dynmap version on Spigot shows the MOTD within the webpage title and not the name that is set within the configuration.

**Comment by ghost** [comment]
Found the commit responsible for this https://github.com/webbukkit/dynmap/commit/9746dc19f4f8cd21be1b1c022fc2a48107f8daab (also see https://github.com/webbukkit/dynmap/commit/e8ec7da47d484675684df5f717366322613d4dab#diff-67a2c7e7e72821fc159ee7ba4c8d908c)
Apparently 1.14 spigot removed the method for getting the server name. :confused:

**Comment by ghost** [comment]
So apparently the server-name in server.properties wasn't vanilla but was added by Bukkit, but Bukkit removed that property https://www.spigotmc.org/threads/1-14-2-getting-the-server-name.375568/#post-3419741

**Comment by ghost** [comment]
So you'll just need to set custom title in the configuration https://github.com/webbukkit/dynmap/blob/286a12c4ef8e2b531f2fee2c7bee9a83648e3447/spigot/src/main/resources/configuration.txt#L302
As for the project the configuration comment should be updated to say it uses server motd
or maybe dynmap should be made to just use "Minecraft Dynamic Map" by default

**Comment by mikeprimm** [comment]
The custom name is the only available answer - there is no 'name' for me to show anymore, so cannot fix it beyond supporting the custom name.
