### ISSUE TITLE
Dynamap Will Not Render

### ISSUE THREAD

**Issue by mikelatham** [webbukkit/dynmap#2514]
When I Do /fullrender or /radiusrender it doesnt give me updates in chat and it does not update the render. http://173.2.44.41:25567/?worldname=world&mapname=flat&zoom=2&x=-356&y=64&z=167#
And im useing craftbukket 1.14.1

**Comment by mikelatham** [comment]
please help

**Comment by GamingTrainer** [comment]
1.14.3 fix the issue

**Comment by GamingTrainer** [comment]
Same problem here - Please fix this

**Comment by Teumaat** [comment]
I think I had this same problem. If your server is suffering from low TPS (large village with large amounts of Iron Golems perhaps?) the dynmap renderer will pause. This setting can be changed in configuration.txt:

`update-min-tps: 18.0`
`fullrender-min-tps: 18.0`
`zoomout-min-tps: 18.0`

If you lower these values (I've just changed them to 1.0) the renderer will awaken and start rendering again.
