### ISSUE TITLE
fullrender does not work on sponge server

### ISSUE THREAD

**Issue by gundami** [webbukkit/dynmap#2516]
My server runs on SpongeForge, and i have completed the world fill with Worldborder. But when i try to fullrender the world, it only render the place i walked. How can i render the whole map in the border?
<img src="https://s2.ax1x.com/2019/06/16/VT6tOS.jpg"  alt="screenshot" />

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
