### ISSUE TITLE
Immersive Engineering slabs render black

### ISSUE THREAD

**Issue by BonaireDreams** [webbukkit/dynmap#2518]
MC Version 1.12.2
Forge Version 1.12.2-14.23.5.2838
Immersive Engineering Version 0.12-89
Dynmap Version Dynmap-3.0-beta-4-forge-1.12.2  (latest download available)
Blockscan Version 3.0-beta-1-forge-1.12.2 (lastest download available)
Just upgraded to both latest version of dynmap and blockscan to see if it made a difference.

Immersive Engineering Concrete Slab & Concrete Tile Slab render black. This could be affecting more blocks, but I was only working with these 2 blocks during my testing.

Blockscan is creating the texture and model files for Immersive Engineering
[immersiveengineering-models.txt](https://github.com/webbukkit/dynmap/files/3297864/immersiveengineering-models.txt)
[immersiveengineering-texture.txt](https://github.com/webbukkit/dynmap/files/3297865/immersiveengineering-texture.txt)

Both seem to have the correct data for the blocks.

**Comment by BonaireDreams** [comment]
Just noticed that beta 4 was unable to render Tinkers Construct blue and purple slime island blocks. Reverting back to beta 3 corrected this.

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please open a new issue if this is still relevant.
