### ISSUE TITLE
Chat cant be deactivated on 1.14.2

### ISSUE THREAD

**Issue by banit** [webbukkit/dynmap#2528]
No matter wich option you deactivate, it will allways post chat in the webclient

**Comment by WeltensiedlerDE** [comment]
No, working fine! Have 1.14.2 and no chat.

- class: org.dynmap.InternalClientUpdateComponent
    allowwebchat: false

 - class: org.dynmap.JsonFileClientUpdateComponent
    allowwebchat: false

Both separately works fine!

**Comment by banit** [comment]
you are right, found the problem.. another plugin activated chat again.
