### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by ImLunaUwU** [webbukkit/dynmap#2529]
Would it be possible to make a bridge between Discord and Dynmap chat? (Possibly with DiscordSRV?)

**Comment by WeltensiedlerDE** [comment]
You can hook up your MC Server with discord, so if someone posting in the webchat, it's in the MC-Chat and then also in the discord chat. I don't think there is any need to implement it in dynmap.

**Comment by TonyoBlaster** [comment]
But what about Chisels textures in 1.12.2 ?

**Comment by ImLunaUwU** [comment]
I've heard about someone getting both dynmap to discord and vise versa to work.. I just don't know how

**Comment by FedUpWith-Tech** [comment]
discordSRV now supports this natively

**Comment by ImLunaUwU** [comment]
Nice
