### ISSUE TITLE
Cname / sub domain isnt working...

### ISSUE THREAD

**Issue by Kainzo** [webbukkit/dynmap#2530]
It works just fine whenever I use my "Base" server IP > but whenever I use my "map.hc.to:8199" nothing comes up and it goes to https...
Any thoughts?

http://142.44.143.127:8199/

**Comment by WeltensiedlerDE** [comment]
It's working fine.

**Comment by WeltensiedlerDE** [comment]
Do you have cleared your browser cache?

![Screenshot_1](https://user-images.githubusercontent.com/10679451/60057156-cb0ed400-96e3-11e9-9828-a13ddf7a8150.png)

**Comment by Kainzo** [comment]
weird, chrome cant open but... brave brower does/

**Comment by WeltensiedlerDE** [comment]
My screenshot was madde w ith chrome. Try Strg+F5 in Chrome. And delete your Browserfiles in Chrome with Strg+Shiftt+Del.

**Comment by mikeprimm** [comment]
Still an issue?   I cannot get to either address, and both respond connection refused, which implies nothing on the port
