### ISSUE TITLE
1.7.10 support

### ISSUE THREAD

**Issue by willis936** [webbukkit/dynmap#2531]
Many hosts and players, myself included, are still on MC 1.7.10.  I think it's premature to deprecate it.

Here is my current setup:
Dynmap-2.6-beta-1-forge-1.7.10
DynmapModScraper-2.1-alpha-1-forge-1.7.10
a large swath of mods

I've been trying to get all configs smoothed out.  Things have been working well, all things considered.  The scraper worked wonders on biomes o plenty.  There are still some issues that I haven't been able to sort out.  Specifically so far I have found:

1. RC water tank textures are solid black with some transparency
![image](https://user-images.githubusercontent.com/13720625/60140176-ce0ad280-977e-11e9-8fc2-857df98b333a.png)

2. carpenter's blocks pressure plates render as laid down redstone on top of a clear block
![image](https://user-images.githubusercontent.com/13720625/60140199-ea0e7400-977e-11e9-9866-75ac9638763a.png)

3. gregtech single block machines are generic machine casings without the proper machine casing texture or any overlay texture.
![image](https://user-images.githubusercontent.com/13720625/60140324-5e491780-977f-11e9-9093-a91b862fb121.png)
(this is a charcoal pit igniter and should look like this: an orange machine casing with a fire pit overlay)
![image](https://user-images.githubusercontent.com/13720625/60140328-64d78f00-977f-11e9-974c-fc9b655c0076.png)

There may be more issues but I haven't found them yet.  From my limited understanding I think there are likely only a few small issues to fix with the scraper to make things work.  Fixing these issues by hand making the model and texture configurations would be a large task.  I think some of these issues have been fixed downstream because I ran into fewer of these issues when playing 1.12 recently.  Backporting some of the bugfixes to 1.7.10 would mean a lot to many players.

**Comment by WeltensiedlerDE** [comment]
I don't think so. I was a moderator on a germyn modpack network. On this network all modpacks lower 1.12 will discontinued. The problem with modpacks is, every block in the modpack must be inserted into dynmap and this might be very complicated, cause some id's in the mods will be changed. You can try to render your world with a modpack texturepack pack.

**Comment by willis936** [comment]
I don't claim to know the distribution of players on each version, but I know that there are still an appreciable number of players still on 1.7.10.  I play new horizons mostly.  There are 800 people online in the discord, with a few dozen active daily.  There are 4 official whitelisted servers with a few players on at any given time but I'm sure many players are like me and host their own servers for their own group of friends and extra control.  I don't know what other communities like this exist out there, but I think it's more likely than not that there are others.

What keeps players like me on 1.7.10 is the large number of matured mods on the version.  1.12 is a good replacement but it still doesn't have the same interesting mods yet.  I don't think it's reasonable to add all of the newer features to 1.7.10, but backporting some of the fixes that have been found would be nice.  I don't think dynmap 2.6 beta 1 is a clean stopping point.
