### ISSUE TITLE
forum issue

### ISSUE THREAD

**Issue by willis936** [webbukkit/dynmap#2532]
The repo description links to https://forums.dynmap.us (DON'T CLICK)

The site on the other end appears to have forum names that make sense but most forums have no posts.  The forums that do have posts are mostly in russian.  It seems like computer generated spam.  Somehow I don't think this is where dynmap discussions are held.  I recommend no one make an account there or even visit it.

![image](https://user-images.githubusercontent.com/13720625/60139978-0231c380-977e-11e9-8ecf-fea37d74db8e.png)

**Comment by WeltensiedlerDE** [comment]
Yes, it's a very curious site. I would never registeroon this site.

**Comment by Fexcraft** [comment]
Sadly, it is a common thing these days that a phpBB forum will be overflown with bots, they seem to be able to crack basic captcha codes of phpBB too. I recall only way to fix that is adding a registration check which a generic bot won't pass (oh, some of them also been able to confirm e-mails too I recall now).

But if the link to the forums is on the official post, it must be true :thinking:

**Comment by TNTUP** [comment]
Official yes, I don't bother registering there, lots of spam posts and still checking the minecraftforums/spigots/github. Hope mikeprimm will fix it when he has time for it

**Comment by PikaMug** [comment]
Spigot page links there as well. At one point, I registered with a dummy account to ask an API question. Went unanswered for weeks until I finally figured out the answer myself. Updated the post for future readers and now, months later, my thread was deleted - probably mistaken for spam.

The site is absolute garbage - don't waste your time.

**Comment by katubug** [comment]
Yeah, I was trying to find the name of a Dynmap addon and made the mistake of looking through the forums for it - whoever is currently running it ought to save themselves a couple bucks a month by taking it down. Or get a spam filter, whichever works.

**Comment by FedUpWith-Tech** [comment]
the forum has closed now, closing this ticket
