### ISSUE TITLE
1.14 markers vanishing [signs]

### ISSUE THREAD

**Issue by gravestristen** [webbukkit/dynmap#2533]
Dynmap version: Dynmap-3.0-beta-4-spigot.jar
minecraft version: 1.14.2
server jar: spigot-1.14.2.jar
other plugins: worldedit-bukkit-7.0.0.jar
Config file: https://pastebin.com/bqebh6Cz
Problem: Dynmap markers made using signs disappear after rechecked by Dynmap,
description: I made a marker using a sign with the option enabled in the config, at first the marker stays on the map, but if i hang around the sign too long it'll disappear, if I immediately leave the area, IE go through a portal (I was using signs to mark the portals with Dynmap so they can easily be removed and updated) the marker will stay on the map, but if I re enter the area it'll disappear again, also after further investigating this also causes the marker to actually be removed from the marker.yml file. The format I have been using on the signs is.
`Line1: [dynmap]
Line2: name
Line3: set:portals
Line4: icon:portal`
The portals set has been created correctly.
Edit: formatted the sign example.

**Comment by edelan7** [comment]
I also have the same issue on 1.14.3. Weirdly, one signs is permanent. If I add any others the marker.yml sometimes updates, sometimes doesn't ... as soon as I move away from the sign it disappears from the map and marker.yml. Other times I can add a sign, marker.yml gets updated, but once a third sign is added both the 2nd and 3rd sign disappear from the map. In all of the scenarios I've tested, the first sign never gets removed or deleted.

**Comment by gravestristen** [comment]
I've also managed to make a permanent sign on accident and I had to remove it via commands, how i did it was i just wrote [dynmap] on it then exited the sign and deleted it because I didnt like the placement and I had to remove it via commands because it wouldnt go away.

**Comment by Bernardez** [comment]
I also have this issue for the last few months while running different versions of Spigot 1.14(.3) and Dynmap snapshot releases and the latest beta Dynmap-3.0-beta-4-spigot.
I've only noticed markers 'vanishing' when players add new markers using a sign.

**Comment by Luysita** [comment]
Same issue here.

**Comment by steveabraham** [comment]
Just a +1 from me. I've been pulling my hair out trying to figure out what was wrong. I assumed it my set-up, since I use a standalone web server, but it seems not.

**Comment by steveabraham** [comment]
Today's release doesn't seem to have sorted the issue for me. Some signs are now staying and persisting, some are vanishing after a few moments.

**Comment by steveabraham** [comment]
I'd go as far as saying that signs placed 'freestanding' are persisting, but signs placed on the side of a block are vanishing, can anyone else confirm?

**Comment by edelan7** [comment]
Confirmed, signs placed 'freestanding' are persisting.

Edit:
We went around marking houses and locations today. The first 3 signs we marked stayed and appear to be persistent (placed by server owner) ... the following 5 signs, the first two worked, then the third one erased the previous two, and the remaining three never showed on the map. All signs placed by server owner. We tried changing angle. icon, text, etc ... same results with the markers either staying for 2-10 seconds and disappearing from the map, removing previously placed markers for that "session", or just not showing up at all.
Server is currently busy but we may try to place 1-2 signs later, see if they stay, then reboot the server to see if that "moves" the problem down the file leaving the existing markers in the markers.yml

**Comment by Ellendrios** [comment]
Same issue with 1.14.4 and Dynmap beta 5

**Comment by willrun4fun** [comment]
Same here.  Latest Paper 156 and beta 5

**Comment by tiagoad** [comment]
Can confirm it's happening to me as well

**Comment by tiagoad** [comment]
Seems the problem lies with the usage of deprecated `getBlockTypeIdAt` method. I'll try to fix it once I have some free time.

**Comment by willrun4fun** [comment]
Just an update I am having good luck currently using oak signs only and make them free-standing.

**Comment by gravestristen** [comment]
<qoute> Seems the problem lies with the usage of deprecated getBlockTypeIdAt method. I'll try to fix it once I have some free time.<quote/>

Awesome thank you.

**Comment by gravestristen** [comment]
> Seems the problem lies with the usage of deprecated `getBlockTypeIdAt` method. I'll try to fix it once I have some free time.

awesome thank you!

**Comment by tiagoad** [comment]
Just created a pull-request with code that fixes this for 1.14 spigot, but I'm not sure if it breaks the plugin for older versions.

Here is a compiled version of the plugin: [Dynmap-3.0-beta-5-spigot.jar.zip](https://github.com/webbukkit/dynmap/files/3501127/Dynmap-3.0-beta-5-spigot.jar.zip)

**Comment by JupiterSnarl** [comment]
I have version Dynmap-3.0-beta-5-spigot installed and this bug is still happening.

**Comment by Technoguyfication** [comment]
can confirm that still happens on 3.0-beta-5-218

**Comment by MichelArendt** [comment]
Will this go live only on beta-6? Any ETA for that version?

Only oak signs are working (I've only tested with birch).

**Comment by HuJK** [comment]
Dynmap version: Dynmap-3.0-beta-5-spigot.jar
minecraft version: 1.14.4
server jar: spigot-1.14.4.jar

It still happens!

I record a video for this:
https://www.youtube.com/watch?v=kKTpn9nxu9k
