### ISSUE TITLE
Add option to show marker IDs on map

### ISSUE THREAD

**Issue by Jameskmonger** [webbukkit/dynmap#2539]
It would be useful to have an option to show the marker IDs on the map, so a marker labelled as "Underwater Ruin" could be displayed instead as "Underwater Ruin (marker_id_1)"

I think this setting should be a global config setting, and would require a change in

https://github.com/webbukkit/dynmap/blob/867315fb04a2be582cb5ef0308fbfc77fcb86a76/DynmapCore/src/main/resources/extracted/web/js/markers.js

In the `createMarker` function

**Comment by Jameskmonger** [comment]
@mikeprimm Would you accept a PR for this?

**Comment by Jameskmonger** [comment]
The marker syntax could be like so:

```html
<span class="markerName markerName_markers markerName16x16">
    Underwater ruins <span class="markerId">(marker_id_1)</span>
</span>
```

With the following styling:

```css
.markerId {
    font-style: italic;
    font-weight: 700;
    color: #848484;
}
```

Which looks like this:

![image](https://user-images.githubusercontent.com/2037007/61063950-c42cd480-a3f8-11e9-9131-edf6b0bbdabd.png)

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
