### ISSUE TITLE
All the commands and rendering works, all the files are there, but connection is refused online.

### ISSUE THREAD

**Issue by adamfaridi** [webbukkit/dynmap#2540]
So about a day after we updated to 1.13.2, Dynmap initially worked, but then decided to stop connecting on the webserver, making it impossible to access the actual webepage. This might've been when we updated to paper from spigot, all though i'm not 100% sure. 
A fellow server owner said they have it working fine on 1.13.2 and paper 
We used to be able to connect with blueprint.mc-dns.net:8080 (that is our letter ip) as well as our number IP 167.114.11.236:8080
I'd like to stress the fact that everything works EXCEPT connecting on the web server. 
-------------------------------
Minecraft Version 1.13.2
paper-631.jar
Dynmap-3.0-beta-3-spigot.jar
IP: blueprint.mc-dns.net (167.114.11.236:25595)
-------------------------------

**_THIS IS WHAT IT SAYS ON STARTUP WHEN ENABLING DYNMAP:_**
11.07 16:15:31 [Server] INFO Enabling dynmap v3.0-beta-3-160*
11.07 16:15:32 [Server] INFO Added 11 custom biome mappings
11.07 16:15:32 [Server] INFO Using Bukkit Permissions (superperms) for access control
11.07 16:15:32 [Server] INFO Web interface permissions only available for online users
11.07 16:15:32 [Server] INFO Mod Support processing completed
11.07 16:15:32 [Server] INFO Loaded 25 shaders.
11.07 16:15:32 [Server] INFO Loaded 82 perspectives.
11.07 16:15:32 [Server] INFO Loaded 14 lightings.
11.07 16:15:33 [Server] INFO Web server started on address 167.114.11.236:8080
11.07 16:15:33 [Server] INFO version 3.0-beta-3-160 is enabled - core version 3.0-beta-3-160
11.07 16:15:33 [Server] INFO For support, visit https://forums.dynmap.us/
11.07 16:15:33 [Server] INFO To report or track bugs, visit https://github.com/webbukkit/dynmap/issues

As you can see, no errors. 

Here is a list of plugins: 
ActionBarAPI, BKCommonLib, BlueprintCore, BuildersUtilities, CoralStay, CoreProtect, DeluxeCommands, DeluxeJoin, DiscordSRV, dynmap*, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncVoxelSnyper, FastAsyncWorldEdit, goBrush, goPaint, HeadDatabase*, HolographicDosplays, iControlU*, ImageMaps*, LibsDisguises, LuckPerms, Multiverse-Core, PlotSquared, ProtocolLib*, TAB, Vault, WorldEdit, WorldGuard

**I also tried dynmap 3.0 beta 4, same issue**
Server Properties: 
```
#Minecraft server properties
#Thu Jul 11 16:15:08 UTC 2019
spawn-protection=16
server-name=Blueprint Creative
generator-settings=
force-gamemode=false
allow-nether=false
enforce-whitelist=false
gamemode=0
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=false
max-players=100
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25595
debug=false
server-ip=0.0.0.0
spawn-npcs=true
allow-flight=false
level-name=Spawn
view-distance=10
hellworld=true
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
prevent-proxy-connections=false
use-native-transport=true
enable-rcon=false
motd=\u00A79Blueprint \u00A76Server \u00A7f>> 1.13.2 \n\u00A77Realistic City Building | Join our community
```
Configuration.txt:
---------------------------------
https://pastebin.com/G9pBhMRJ
---------------------------------

Dynmap is a very important part of our server, and we have a fairly large community, so any help ASAP is greatly appreciated
Here is our discord if you'd like to join there and contact one of us:
https://discord.gg/wAGXRAe

Thanks! - Adam

**Comment by adamfaridi** [comment]
Nevermind, i got this working, port was unavailable and had to change server.properties so that the "server-ip" setting wasn;t 0.0.0.0, but our number ip

**Comment by Jameskmonger** [comment]
@adamfaridi Please close your issue if you've solved the problem

**Comment by Zyphrono** [comment]
Hey there.
I have the same issue but unable to change my ip from 0.0.0.0 to my actual server ip.
The server automatically resets it on boot for some reason?

Any ideas on how to solve this?

**Comment by mikeprimm** [comment]
usually, needing to set that host is due to being multi-tenant (like a hosting service), where you have a dedicated IP on the same server as other folks, and using 0.0.0.0 (which will try to bind to all IP addresses) breaks due to conflict on localhost (127.0.0.1) or other public addresses already having someone binding on the same port.  Binding to the 'right' IP is one way to fix it, the other is to switch dynmap to another unused port number (e.g. 8124, 8125 whaterver) that doesn't bump into someone else on the same host that might have already 'grabbed' 8123.
