### ISSUE TITLE
Unable to connect...

### ISSUE THREAD

**Issue by Zyphrono** [webbukkit/dynmap#2545]
Okay so, I'm trying to setup dynmap and I've never got it working.
I've disabled the firewall and the connection is still denied.

IP: 213.136.74.205:24777
Config: 
![image](https://user-images.githubusercontent.com/22412324/61375229-9e8f4780-a89e-11e9-8a7e-b66d8b2b0e21.png)

My Firewall is DISABLED and I tried adding the port to the firewall and enabling it, this didn't work either.

**Comment by Zyphrono** [comment]
Okay, I tried setting my server ip in server properties to my actual server ip and not 0.0.0.0
But it turns out the server automatically resets it to 0.0.0.0 after I booted it..

Any fixes for that?

**Comment by luuklelifeld** [comment]
> Okay, I tried setting my server ip in server properties to my actual server ip and not 0.0.0.0
> But it turns out the server automatically resets it to 0.0.0.0 after I booted it..
> 
> Any fixes for that?

There's no need to set your ip in the config file. Keep it 0.0.0.0 if you want to be able to connect externally, set it to 127.0.0.1 if you only want to connect internally.

As for the port, not being able to connect to the port is an issue in your network settings, not in dynmap's settings / code.
