### ISSUE TITLE
Utilizing full CPU for rendering

### ISSUE THREAD

**Issue by Charkel** [webbukkit/dynmap#2547]
When rendering it only uses 6-10% of my 6 core (12 logic core) 4.1 GHz CPU
Windows 10

I have tried to change these values in config. I have also tried to implement launch option for multithreading in the start bat file. 

```
renderinterval: 0.3
tiles-rendered-at-once: 6
```

**Comment by mikeprimm** [comment]
You need to allow for more than one render thread - see parallelrendercnt setting in configuration.txt ( https://github.com/webbukkit/dynmap/blob/v3.0/spigot/src/main/resources/configuration.txt#L346 )

**Comment by Charkel** [comment]
> You need to allow for more than one render thread - see parallelrendercnt setting in configuration.txt ( https://github.com/webbukkit/dynmap/blob/v3.0/spigot/src/main/resources/configuration.txt#L346 )

Thank you so much for the help it worked great!
