### ISSUE TITLE
1.14.4 support

### ISSUE THREAD

**Issue by wrecktify** [webbukkit/dynmap#2550]
Error on startup with spigot 1.14.4

16:49:22] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-beta-4-213 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:54) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:791) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) [spigot-1.14.4.jar:git-Spigot-9de398a-e73aabd]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-1.14.4.jar:git-Spigot-9de398a-e73aabd]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot-1.14.4.jar:git-Spigot-9de398a-e73aabd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by Blueeyestar** [comment]
**I also have the problem**


[02:45:34] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.0-SNAPSHOT-215 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:159) ~[?:?]
	at org.dynmap.bukkit.helper.BukkitVersionHelperCB.<init>(BukkitVersionHelperCB.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:54) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:791) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [minecraft_server.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by YourCoalAlt** [comment]
You can't use Dynmap on 1.14.4 until Dynamp gets updated for 1.14.4, currently it's only 1.14.3

**Comment by wrecktify** [comment]
Obviously.  I was posting that it needs to be updated to 1.14.4 in case the developer wasn't aware that spigot 1.14.4 was released.

**Comment by chbensch** [comment]
I just updated Dynmap to 1.14.4: 

Build yourself: https://github.com/benschbrothers/dynmap

or download the compiled version: https://github.com/benschbrothers/dynmap/blob/v3.0/compiled/Dynmap-3.0-spigot-1-14-4.jar

(i will change the links when my pull-request to 1.14.4 is merged :) )

**Comment by Blueeyestar** [comment]
> 
> 
> I just updated Dynmap to 1.14.4:
> 
> Build yourself: https://github.com/benschbrothers/dynmap
> 
> or download the compiled version: https://github.com/benschbrothers/dynmap/blob/v3.0/compiled/Dynmap-3.0-spigot-1-14-4.jar
> 
> (i will change the links when my pull-request to 1.14.4 is merged :) )

this isn't an official update from mikeprimm, is it? 

Thanks for the work but I'd rather wait until it's released on https://dynmap.us/builds/dynmap/ 

Often other users have spread malware on servers like this!

**Comment by chbensch** [comment]
> > I just updated Dynmap to 1.14.4:
> > Build yourself: https://github.com/benschbrothers/dynmap
> > or download the compiled version: https://github.com/benschbrothers/dynmap/blob/v3.0/compiled/Dynmap-3.0-spigot-1-14-4.jar
> > (i will change the links when my pull-request to 1.14.4 is merged :) )
> 
> this isn't an official update from mikeprimm, is it?
> 
> Thanks for the work but I'd rather wait until it's released on https://dynmap.us/builds/dynmap/
> 
> Often other users have spread malware on servers like this!

thats why i have forked the Repo and made clear commits to allow everyone to see the changes and build it themself :) 

BTW: its just a change of a codeline to allow the current version.

**Comment by clrxbl** [comment]
@TaskManager91 's Dynmap build works perfect for us, built it from source just in case.

**Comment by ghost** [comment]
Yeah the change to enable 1.14.4 support is just an edit on one line to make it use the same helper as for 1.14.3 and 1.14.2 and 1.14.1 etc: https://github.com/benschbrothers/dynmap/commit/e3c0c9eef6f26c0e142c42be83b624184c452567 (he forgot to change the number in the first commit though: https://github.com/benschbrothers/dynmap/commit/5c39e88cb187dd92ad1bcdf203611519b66c0b72 )

**Comment by ghost** [comment]
I tried building myself but of course it fails even though I did exactly what they said to do :angry: ![](https://i.imgur.com/mZ5TSRf.png) so I'll just use @TaskManager91's build

**Comment by Blueeyestar** [comment]
Have major changes been made to 1.14.4 again? As in other versions? 

Because otherwise the update from dynmap was faster.  Do you already know when the update to 1.14.4 will be released?

**Comment by Blueeyestar** [comment]
I'm improving. The version of TaskManager91 works very well. Well done and thank you very much

**Comment by Nicoolai** [comment]
> I just updated Dynmap to 1.14.4:
> 
> Build yourself: https://github.com/benschbrothers/dynmap
> 
> or download the compiled version: https://github.com/benschbrothers/dynmap/blob/v3.0/compiled/Dynmap-3.0-spigot-1-14-4.jar
> 
> (i will change the links when my pull-request to 1.14.4 is merged :) )

I'm somewhat of a noob at this, but I can't get that file to run.  
I get the following error:

`[17:27:16] [Server thread/ERROR]: Could not load 'plugins/Dynmap-3.0-spigot-1-14-4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml`

I don't have a plugin.yml anywhere, not sure how to get it?
What am I missing here?
My minecraft_server.jar is the 1.14.4 spigot version, made from buildtools.

**Comment by deanemaster** [comment]
If @TaskManager91 was able do it, then how as @mikeprimm not updated this himself yet?

**Comment by clrxbl** [comment]
Because maybe he doesn't have time? Patience is key.

**Comment by mikeprimm-triva** [comment]
Little things called careers and families get in the way of time for this stuff.....

**Comment by mikeprimm** [comment]
https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar - dev build out - I'll do some housework today and hopefully push it as beta-5 tonight :)

**Comment by generrosity** [comment]
Mr @mikeprimm - how are things going? I hope you are keeping sane and feeling to love that you generate in the community

**Comment by mikeprimm-triva** [comment]
Hey - sorry for delay on any response: I've been traveling abroad for last 3 weeks (mostly on a cruise ship doing a trans-Atlantic that has been delayed by Dorian...), so very little and generally poor at best internet access.  I'm expecting to get back to being active once I'm back, later this week :)

**Comment by mikeprimm** [comment]
Hey - sorry for delay on any response: I've been traveling abroad for last 3 weeks (mostly on a cruise ship doing a trans-Atlantic that has been delayed by Dorian...), so very little and generally poor at best internet access. I'm expecting to get back to being active once I'm back, later this week :)

**Comment by generrosity** [comment]
Neat! Looking forward to it, great that you got away for a holiday :D

**Comment by dmetzler1988** [comment]
Hi @mikeprimm 
i hope your holiday was great.
Any update on this project for 1.14.4?
The last update (beta release) is from 10. Sep. Can we use this currently or it is better to wait for stable version?

p.s. thank you a lot for your great work!

**Comment by fichdlmaa** [comment]
Hello @dmetzler1988,
I compiled Beta 6 on Oct. 21st. Works fine with spigot 1.14.4 built on Oct. 22nd with build tools 1.0.3
Greets
FM
