### ISSUE TITLE
[Suggestion] Rendering on another server

### ISSUE THREAD

**Issue by Charkel** [webbukkit/dynmap#2553]
I would like to suggest the possibility to render a map using another server so that the server running the bukkit server doesn't have to take the load. 
I wish I was better at Java and programming in general then I would love to help expand this plugin! All I can do now is suggest and hope :)

(Sorry if you're not allowed to make suggestions in the Issues section, I'm not the best at github)

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
