### ISSUE TITLE
How Can I turn the web map to other direction?

### ISSUE THREAD

**Issue by Luthics** [webbukkit/dynmap#2554]
I made a mistake while creating the world
So the web map also has mistakes.
It doesn't like normal map.
It is upside down
What should I do?
My map address:http://106.12.207.4:8124/#
A picture of the web map
 http://106.12.207.4:2345/2019/07/21/5d34770c1b2de.jpg

**Comment by MentalDisorder** [comment]
Change the perspective in the map definition. 
In the plugin directory there's a perspectives.txt to choose from.
Also here: https://github.com/webbukkit/dynmap/wiki/Full-list-of-predefined-perspectives
```
 - class: org.dynmap.hdmap.HDMap
        name: surface.temp
        title: "Flat Temperature"
        prefix: temp1
        perspective: iso_S_90_vlowres <<<< this is the line to check/change your perspective
        shader: temperature
        lighting: default
        mapzoomin: 2

```
