### ISSUE TITLE
Can't connect to website

### ISSUE THREAD

**Issue by RAdu2005** [webbukkit/dynmap#2561]
Hello, I am running a Spigot 1.14.3 server on another PC at my home. I can access Dynmap from other computers or phones on the same network but when other people try to connect they get

On Chrome: ERR_INVALID_HTTP_RESPONSE
On Edge: ™–{"translate":"disconnect.genericReason","with":["Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 69"]}

I tried the default port and a few custom ports but no success (they are portforwarded) and I tried disabling firewall but it still doesn't work.

I am giving them the same IP as the server with the correct port (public IP), they can connect to the server but not to Dynmap's website. I do not have Essentials installed. I was wondering if any of you had any solutions.

Logs: https://pastebin.com/UEsckth2

**Comment by lukacat10** [comment]
To me, exactly the same thing happend when I configured my plugin (that creates a web server too) to start its webserver on the same port as minecraft - 25565.

Minecraft, netty, or whatever, seems to occupy that port. I didn't receive any exception that is normaly received when 2 listening sockets conflict on the port, but maybe there is another explanation (the helpful error message on firefox/edge could help)

I will try to remember this issue if I find a solution.
