### ISSUE TITLE
Update dynmap-mobs to include mobs up to 1.14

### ISSUE THREAD

**Issue by edgeman16** [webbukkit/dynmap#2562]
Any chance we could get the latest mobs in dynmap-mobs? My server's been having lag issues with Pillagers and I'd like to use the dynmap to help track them down when they appear.

**Comment by gabsoftware** [comment]
I would like an updated dynmap-mobs as well. Too many missing mobs... Sometimes in a raid there is a hidden pillager and the wave cannot end. That would be useful to find it.

**Comment by zrovihr** [comment]
I would love to have raiders on the map since they now spawn more than creepers xD
