### ISSUE TITLE
Dynmap not rendering loaded chunks

### ISSUE THREAD

**Issue by chaoschao11** [webbukkit/dynmap#2563]
Hey I loaded up dynmap onto my paper server and installed world border as well. I had WB generate all the chunks out to a 10000 radius with the /fill command then ran the Dynmap radius render and this is what came from it:

https://imgur.com/a/yPD7yKJ

I also attempted to do full render but it's been at it for several days and none of the holes are far as I can tell have been filled.

**Comment by mylogon341** [comment]
I've had this exact same issue. I know it's not officially supported, but i'm running 1.14.4 with a self-compiled version of dynmap to make it 'compatible'. 
What I did find though, was that if i ran the render again, after reaching 100%, it would then start back at 80% or so and do more rendering, but it didnt help
This is the image I get from flat
https://imgur.com/a/EG1VAOh

and this is the surface one
https://imgur.com/a/lqRyqXw

**Comment by mylogon341** [comment]
@chaoschao11 I think this might be a wb issue. I have just ran `wb world fill 1000 100 true` which forces the fill of areas and now, when running `dynmap fullrender world:flat` the areas appear to be filling in now.

**Comment by chaoschao11** [comment]
I wouldn't be surprised if it was WB I think it might not be updated to the 1.14 rendering system.

I will try to do what you did and report back.

**Comment by chaoschao11** [comment]
@mylogon341 hmm so I did the fill command again as you did, deleted the dymap file, and the jar reinstalled everything and attempted to full render again but still black lines everywhere.

**Comment by mylogon341** [comment]
I'm not sure then. It looks like it's probably a wb issue then as it was the `true` force argument on the end that has fixed this issue twice for me today. It looks like wb just isnt picking up on the fact that it hasn't filled those areas yet. imo this issue should be migrated to the wb github (if it has one)

**Comment by chaoschao11** [comment]
I will enter a bug with World border, thanks for trying to help me!
