### ISSUE TITLE
Question about Startup Error in Spigot 1.14.4

### ISSUE THREAD

**Issue by mercurialmusic** [webbukkit/dynmap#2567]
Not sure if this is a bug report or a request, but I'm getting this error on every startup: https://gist.github.com/mercurialmusic/987b80b1ab38839217fbfc4f5af7d7c2

Using Dynmap-3.0-beta-5-spigot.jar and Spigot 1.14.4 (git-Spigot-1981d55-860b354 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)) - a few versions behind because of the inventory duping thing.

The map loads and works, but I don't think it's rendering new tiles. My fear is that the error indicates a corrupted chunk somewhere, but I'm not able to tell from the stacktrace if that's the case or where I would be able to start looking for it. Are chunk coords something that could be included in the error?

The world was generated in 1.13.2 and upgraded in 1.14.3 and we've had some instances of the chunk-swapping bug pop up. Fun! 

Any advice is appreciated.

**Comment by FedUpWith-Tech** [comment]
Yup, its a corrupt chunk on the world somewhere. I'm going to close this as dynmap didn't cause it and there's nothign we can do to fix it
