### ISSUE TITLE
Dynmap Towny not showing claims on latest towny dev builds 

### ISSUE THREAD

**Issue by FallingCactus** [webbukkit/dynmap#2568]
After changing to the latest dev build of Towny on my 1.14.4 Spigot server towns will no longer show on my map. speaking to the lead dev of towny they say the problem seems to be on your end as the old API calls should direct to the new API on the latest builds.

**Comment by max-bromberg** [comment]
I am in the same situation. Dynmap-Towny was working for me before and is not completely broken. What broke it? Is it planned on being fixed soon?

**Comment by FallingCactus** [comment]
> I am in the same situation. Dynmap-Towny was working for me before and is not completely broken. What broke it? Is it planned on being fixed soon?

try this version https://github.com/TownyAdvanced/Dynmap-Towny/releases/tag/0.73

**0.94.0.2+ Towny dev build is required.**
