### ISSUE TITLE
Rendering only on chunks loaded after 1.13.2

### ISSUE THREAD

**Issue by WELTEINZ** [webbukkit/dynmap#2570]
Hi there,

first: Thanks for providing that awsome plugin.

We have a world that has generated bioms since early 2012 and we are using the dynmap from its start. Since the update from Spigot 1.13.2 to Spigot 1.14.4 and the current Dynmap version, the rendering of chunks will only work for chunks that have been loaded in 1.14.4 (see screenshot).

![image](https://user-images.githubusercontent.com/44711940/62194547-5da53180-b37a-11e9-8215-5033cb2a742c.png)

I hope I can contribute to the debugging with the problem description.

(Please overlook my bad english: I am not a native speaker)

Greetings

WELTEINZ

**Comment by BlisteringSyko** [comment]
Hi,

Looks like this might be a similar issue to what i have. Add --forceUpgrade to the end of your startup command after where it says spigot.jar  and start the server, let it upgrade then stop the server again and remove --forceupgrade   

This solved the majority of my rendering issues in 1.14.4 after upgrading from 1.13.2

https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-4-development-builds.369724/

**Comment by WELTEINZ** [comment]
Hi, thank you very much for caring about my problem. I'll give it a try!

EDIT: --forceUpgrade fixed the problem for me too. Case closed! Thanks again!
