### ISSUE TITLE
Dynmap Errors with MySQL

### ISSUE THREAD

**Issue by JoshA20** [webbukkit/dynmap#2571]
Hi there, My Dynmap plugin is taking absolutely forever to load. I've been stuck on this for the past 4? minutes.
![image](https://user-images.githubusercontent.com/47107236/62232322-d8437080-b3bd-11e9-811e-1fe161c46f1e.png)

I also seem to be getting this error every so often.
`>.... [17:54:15 ERROR]: [dynmap] Tile matches hash error - The last packet successfully received from the server was 611,299 milliseconds ago. The last packet sent successfully to the server was 611,460 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
>.... [17:54:15 ERROR]: [dynmap] Tile exists error - The last packet successfully received from the server was 749,394 milliseconds ago. The last packet sent successfully to the server was 749,474 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
>.... [17:54:15 ERROR]: [dynmap] Tile write error - Duplicate entry '1-0-3-0' for key 'PRIMARY'`

Just Recently, That Number, Has went to upwards of 6 Million ms.

I had posted on the dynmap forums, But no one has responded. So this is my second try.

Even while writing this, Dynmap still isnt loading my server.,

Server Stats:
MC Version: 1.14.4
Paper-152

Please help! :E

**Comment by FedUpWith-Tech** [comment]
This is an issue with myswl but I believe a workaround was implemented in a later update. Please re-open if this still persists
