### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by lKhyst** [webbukkit/dynmap#2573]
I'm always used Dynmap, my server was 1.12.2, worked fine, so I updated to 1.14.4 and I'm getting errors with MySQL

dynmap v3.0-beta-5-218
Spigot-1981d55-da62a66 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Error:
`
> [04:45:58] [Server thread/ERROR]: [dynmap] Error creating tables - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"Maps (ID INTEGER PRIMARY KEY AUTO_INCREMENT, WorldID VARCHAR(64) NOT NULL, MapI' at line 1
> [04:45:58] [Server thread/ERROR]: [dynmap] Map storage initialization failure
> [04:45:58] [Server thread/INFO]: [dynmap] Unloaded 0 components.
> [04:45:58] [Server thread/INFO]: [dynmap] Disabled`

**Comment by FedUpWith-Tech** [comment]
This is likely to due with an update 
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
