### ISSUE TITLE
"Uncaught type error: Cannot read property "error" of null

### ISSUE THREAD

**Issue by ScorprianDev** [webbukkit/dynmap#2578]
It's the only error on my website and is slightly annoying.

function DynMap(options) {
	var me = this;
	if(me.checkForSavedURL())
		return;
	me.options = options;
	$.getJSON(me.options.url.configuration, function(configuration) {
		if(configuration.error == 'login-required') {
			me.saveURL();
			window.location = 'login.html';
		}
		else if(configuration.error) {
			alert(configuration.error);
		}
		else {
			me.configure(configuration);
			me.initialize();
		}
	}, function(status, statusMessage) {
		alert('Could not retrieve configuration: ' + statusMessage);
	});
}

This is what its struggling with, it doesn't like the if(configuration.error == 'login-required').

How can i fix this, link is currently: maps.skyprisonsmc.tk

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
