### ISSUE TITLE
windows directory/path traversal/local file include vulnerability

### ISSUE THREAD

**Issue by cryptolok** [webbukkit/dynmap#2579]
on the windows setup with integrated web server, it is possible to access the whole server data as read-only using the following URL:
**my.server.net:8123/..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c/windows/win.ini**
thus, every file can be remotely read without any authentication
the solution is to filter/encode the input, such as .. / \ or simply use a more advanced version of the web server (that already do it) or whitelist known URLs with a regex/mask

![dirTraversal](https://user-images.githubusercontent.com/13318994/62662633-fc322380-b974-11e9-97f6-1cbff3e486b0.png)

**Comment by fabianmakila** [comment]
This is pretty critical vulnerability, this needs to be fixed ASAP!

**Comment by Kortako** [comment]
Is this being looked into at all?  Now that I'm aware of this vulnerability (and confirmed on my own setup), I either need to figure out how to mitigate this behavior or remove Dynmap from my server immediately.

**Comment by FedUpWith-Tech** [comment]
Tested this just now, couldn't replicate. The web code has gotten some love recently so I believe it was fixed then
