### ISSUE TITLE
/dynmap pause none: does not unpause

### ISSUE THREAD

**Issue by ZedPython** [webbukkit/dynmap#2580]
![bug](https://user-images.githubusercontent.com/24795397/62706973-d9455500-b9f0-11e9-86fd-45408ccc4410.png)
So i was doing /dynmap fullrender & /dynmap pause none, but no matter what parameter i give full/update/none, it always pauses everything and i cant get fullrender to start.
How can i fix this? also my server seems to be lagging

**Comment by NathanCollaert** [comment]
Dynmap has a default value for when it should pause if your TPS is lower then that value to not lag your server more then it already is. You can't unpause if your server TPS is lower then that value.
You can change or disable this function in the configuration file.
