### ISSUE TITLE
Dynmap site does not load: ERR_CONNECTION_REFUSED (in browser)

### ISSUE THREAD

**Issue by sam33256** [webbukkit/dynmap#2582]
Hi everyone, I can't get Dynmap to work for some reason.

It works and binds to the ip and port according to the logs

> [11:54:38 INFO]: [dynmap] Enabling dynmap v3.0-beta-5-218*
> [11:54:39 INFO]: [dynmap] Using Bukkit Permissions (superperms) for access control
> [11:54:39 INFO]: [dynmap] Web interface permissions only available for online users
> [11:54:39 INFO]: [dynmap] Mod Support processing completed
> [11:54:39 INFO]: [dynmap] Loaded 25 shaders.
> [11:54:39 INFO]: [dynmap] Loaded 82 perspectives.
> [11:54:39 INFO]: [dynmap] Loaded 14 lightings.
> [11:54:39 INFO]: [dynmap] Web server started on address 0.0.0.0:8123
> [11:54:39 INFO]: [dynmap] version 3.0-beta-5-218 is enabled - core version 3.0-beta-5-218
> [11:54:39 INFO]: [dynmap] For support, visit https://forums.dynmap.us
> [11:54:39 INFO]: [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
> [11:54:39 INFO]: [dynmap] Loaded 3 maps of world 'world'.
> [11:54:39 INFO]: [dynmap] Loaded 2 maps of world 'world_nether'.
> [11:54:39 INFO]: [dynmap] Loaded 2 maps of world 'world_the_end'.
> [11:54:39 INFO]: [dynmap] Enabled

But, if I go to the IP+port, my browser just says Connection Refused. And this not a PC problem because it works on no other device.

Now here's some important info:
- I am on Minecraft 1.14.4
- This is on a dedicated OVH host
- There is no firewall so the port doesn't need to be opened (and is also available, I tested changing the port multiple times but with no success)
- The server is running via a Pterodactyl Daemon, but the actual panel is on another server
- There is a Wordpress website running on port 80

**Comment by Aarekaz** [comment]
Same issue here. I have MC 1.14.4 its not laoding. The site does not work

**Comment by NobleStrike** [comment]
Someone posted a review with a solution to this. Which worked for me

"ATTENTION ! In this version is a config failure. You must remove the `#` on line 315 "#webserver-bindaddress: 0.0.0.0", otherwise you dont have acces to your Dynmap with www.myserver:8123"

**Comment by Valentijn058** [comment]
That didnt work for me

**Comment by NobleStrike** [comment]
A reload of the plugin isnt enough for that config change. You have to do it while the server is stopped.

**Comment by ant0r10n** [comment]
Which file to edit? mc says dynmap is loaded but there are no configuration files in the plugin folder.?

Thank You

**Comment by geooctation** [comment]
NobleStrike I Tried doing this and I restarted the server but it still won't work
