### ISSUE TITLE
Dynmap 3.0 Beta 5 doesn't load player skins. (Spigot/BungeeCord 1.14.4)

### ISSUE THREAD

**Issue by donut4490** [webbukkit/dynmap#2583]
Faces are all Steve. Running Paper 1.14.4 under Waterfall. As this is a BungeeCord setup, the servers are being run in offline mode. Could that be causing Dynmap to not be able to load the skins? I know that in 3.0, the plugin ignores whatever skin URL you have set and checks the JSON data instead. The skins work fine in the client, just not Dynmap.

**Comment by ExerciseBook** [comment]
The default `skin-url` written in configuration file was abandon by mojang.

Maybe you can fix it by using another skin API.

**Comment by donut4490** [comment]
Doesn't 3.0 and above ignore whatever I put as the URL? I tried uncommenting it and changing it to skinstealer.com anyway, and it still doesn't work.

**Comment by cleme29** [comment]
I put that and it works :
`# Customize URL used for fetching player skins (%player% is macro for name)
skin-url: "https://minotar.net/skin/%player%.png"`

**Comment by 2sh** [comment]
I have the same issue with Dynmap 3.0 Beta 5 on Spigot. All Steves. Changing the URL to the one cleme29 suggested works for me too.

**Comment by FedUpWith-Tech** [comment]
fixed in a later version, closing issue
