### ISSUE TITLE
 Establishing SSL connection without server's identity verification is not recommended.

### ISSUE THREAD

**Issue by Slycraftmcs** [webbukkit/dynmap#2587]
[WARNING] Fri Aug 16 16:49:57 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
im kinda new to sql not sure how to fix this  or where to look 

[WARNING] Fri Aug 16 16:49:57 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

[ERROR] [dynmap] Error creating tables - Unknown error 1045

[ERROR] [dynmap] Map storage initialization failure

[INFO] [dynmap] Unloaded 0 components.

[INFO] [dynmap] Disabled

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
