### ISSUE TITLE
Custom Texture Pack Not Working, Following Report:

### ISSUE THREAD

**Issue by Project49Music** [webbukkit/dynmap#2588]
When booting up my server I come across this:

[INFO] [dynmap] Loading dynmap v3.0-beta-5-218
[INFO] [dynmap] version=git-Spigot-798ea6a-2012f1e (MC: 1.14.4)
**[INFO] [dynmap] Unload queue not found - default to unload all chunks
[INFO] [dynmap] inhabitedTicks field not found - inhabited shader not functional**
[INFO] [dynmap] Mod Support API available

It just doesn't load the given texture pack but goes on loading all default ones with no problem. If I leave everything how it got generated, none of these errors appear.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
