### ISSUE TITLE
IC2 dosen't render Please help me

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#2589]
Sorry, But help me please.
I read wiki. but i can't found how render Ic2 mod...
I couldn't read the document properly because I don't speak English well....
In my native country, I couldn't find any relevant articles, so I gave up on finding them.
It's important to read the tutorial, but I'm sorry that I read it, but I don't understand it.
Please, can you tell me from beginning to end if possible? If you don't have a detailed explanation, that's fine.
(Use Google Translate)

**Comment by luziferius** [comment]
You probably need this add-on to integrate rendering mod blocks: https://github.com/webbukkit/DynmapBlockScan

Compiled archives here: (BEWARE: This _looks like_ it is the author’s homepage, based on the name. Sanity-check this yourself, before loading the JAR archives.) http://mikeprimm.com/dynmap/builds/DynmapBlockScan/
