### ISSUE TITLE
Dynmap Requires Login Causing Dynmap to Not Work

### ISSUE THREAD

**Issue by bobgrey1997** [webbukkit/dynmap#2592]
I just recently installed Dynmap-2.6-beta-1-forge-1.7.10.jar into my Minecraft 1.7.10 modded server.
Upon setting it up and starting the server, navigating to the map's IP results in a login page. I do not want a login to be required to view the map in any way.
Here is a copy of my config file:
https://pastebin.com/CqZLYc14

**Comment by bobgrey1997** [comment]
Anything from anyone?

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release- please open a new issue if this persists.
