### ISSUE TITLE
Dynmap fullrender doesn't work properly (Spigot 1.13.2, Dynmap 3.0 Beta 4)

### ISSUE THREAD

**Issue by 64Discussions** [webbukkit/dynmap#2593]
I have a big custom map and dynmap refuses to fullrender it by only rendering the areas I walked into.
I tried /wb fill (WorldBorder fill) and it still doesn't recognise the custom map.
Is there a way to make it fully render without walking anywhere? I had no issues with this when I had a 1.12.2 server.
You can see the dynmap here: http://51.91.61.63:11671/?worldname=world&mapname=flat&zoom=0&x=3872&y=64&z=-2268
Minecraft 1.13.2

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
