### ISSUE TITLE
map looks broken after restart

### ISSUE THREAD

**Issue by xNinga** [webbukkit/dynmap#2595]
I am new to dynmap only a day of having it on When restarting the server bits of the world are broken on the map when we zoom in its fixes it
![ddsdd](https://user-images.githubusercontent.com/54451921/63614565-4c4af000-c5db-11e9-9751-c12570bb9a73.PNG)

**Comment by FedUpWith-Tech** [comment]
This is due to the quality profile being change and the render not being completed for the zoomout tiles. I'm going to close this as it is likely no longer relevant but please open a new issue if this persists
