### ISSUE TITLE
Unable to fullrender the_end.flat

### ISSUE THREAD

**Issue by Charkel** [webbukkit/dynmap#2596]
When I run a fullrender on the_end it renders the middle island only. It looks like this after a few seconds and then the surface render goes on for many hours and is working.

> [13:06:01 INFO]: Full render starting on world 'the_end'...
> [13:06:12 INFO]: Full render of map 'flat' of 'the_end' in progress - 100 tiles rendered (109.60 msec/tile, 74.67 msec per render)
> [13:06:20 INFO]: Full render of map 'flat' of 'the_end' in progress - 200 tiles rendered (91.09 msec/tile, 54.78 msec per render)
> [13:06:30 INFO]: Full render of map 'flat' of 'the_end' in progress - 300 tiles rendered (89.90 msec/tile, 54.84 msec per render)
> [13:06:33 INFO]: Full render of map 'flat' of 'the_end' completed - 324 tiles rendered (87.07 msec/map-tile, 51.91 msec per render)

**Comment by DelboyDylan** [comment]
I had the same problem. To get round the issue I added an additional "fullrenderlocation" to the "worlds.txt" file for the end. I used the coordinates of the End Gateway on the outer islands.

**Comment by vekunz** [comment]
I have this same issue but with the surface map also. I'm going to try the workaround with the alternate fullrenderlocation.

**Comment by vekunz** [comment]
Actually I just read the documentation of "fullrenderlocations" and this seems to be a known "issue".

https://github.com/webbukkit/dynmap/wiki/World-and-template-settings
> fullrenderlocations : if defined, this list of world coordinates (each consisting of an x, y, and z coordinate) defines a set of additional locations (beyond x=0, y=64, z=0, or the player's current location, if a /dynmap fullrender command is issued by an in-game player) to be used to seed a full-render. Logically, fullrender is implemented like a flood fill in a paint program - if a map has gaps in its areas of defined chunks, such as can happen if maps are explored via teleporting or portals, a fullrender seeded from one point may not reach all the patches of the world that have been generated: adding example locations within the other patches to the fullrenderlocations list will cause those patches to be rendered, as well.

**Comment by FedUpWith-Tech** [comment]
Looks like the default radius of the end has been updated since this issue was filed. Between that and the fullrenderlocations I'll consider this fixed.
