### ISSUE TITLE
Cannot conect to website

### ISSUE THREAD

**Issue by lorda12** [webbukkit/dynmap#2598]
hi.

I've been trying to use the dynmap plugin, (beta-5 version) and it doesn't let me connect to the website, i have configured all as it should be but the website doesn't work 

my config
![Captura](https://user-images.githubusercontent.com/54636953/63872559-845b8580-c983-11e9-9b19-552ace8dad7f.PNG)
![Captura](https://user-images.githubusercontent.com/54636953/63872615-a2c18100-c983-11e9-8ae8-311527d7600a.PNG)
![Captura](https://user-images.githubusercontent.com/54636953/63872663-b79e1480-c983-11e9-8e04-744479fd1608.PNG)
![Captura](https://user-images.githubusercontent.com/54636953/63872715-d13f5c00-c983-11e9-8230-de39f1c9cd5a.PNG)

if someone have the same issue can talk to me by private chat
thx

**Comment by geooctation** [comment]
set the webport bindadress to 0.0.0.0
