### ISSUE TITLE
Pre-cache Map Tiles near the current viewable area

### ISSUE THREAD

**Issue by leumasme** [webbukkit/dynmap#2602]
In the Map View, Download Map Parts arround the Users Current View so that Panning arround the map at Slow/Medium Speed does not show Black Tiles for a short time before they are loaded.
This would make the Map feel Much Smoother.
https://streamable.com/9nask

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.

**Comment by leumasme** [comment]
@FedUpWith-Tech Hi, just fyi you misspelled my name (lmao)
https://github.com/webbukkit/dynmap/issues/3461#issuecomment-902382040

**Comment by FedUpWith-Tech** [comment]
oh rip, my bad. I've fixed it now
