### ISSUE TITLE
dynmap.db-wal weights over 20 gb!

### ISSUE THREAD

**Issue by iperrealistico** [webbukkit/dynmap#2604]
May i ask what is the dynmap.db-wal file for?

I have configured all the settings for dynmap to the lowest possible, the actual dynmap.db file weights only 2gb.

Why do the .db-wal file weights over 20gb??

**Comment by baconwaifu** [comment]
It's an internal structure of the sqlite database; do *NOT* remove it while the server is running. it will automatically be removed the first time the server is shut down, and ones created for subsequent runs should be considerably smaller.
