### ISSUE TITLE
Dynmap not updating.

### ISSUE THREAD

**Issue by hampsterblade** [webbukkit/dynmap#2605]
My dynmap simply does not update on minecraft 1.12.2 forge 14.21.1.2443 in my modpack at https://www.technicpack.net/modpack/hampstermc.1504551 using the default settings. at startup it gives the following errors.
`Server thread/WARN
 
12:01:48

[Dynmap]: Invalid texture block state: minecraft:wheat:8
[Dynmap]: Invalid texture block state: minecraft:wheat:9
[Dynmap]: Invalid texture block state: minecraft:wheat:10
[Dynmap]: Invalid texture block state: minecraft:wheat:11
[Dynmap]: Invalid texture block state: minecraft:wheat:12
[Dynmap]: Invalid texture block state: minecraft:wheat:13
[Dynmap]: Invalid texture block state: minecraft:wheat:14
[Dynmap]: Invalid texture block state: minecraft:wheat:15
[Dynmap]: Invalid texture block state: minecraft:cake:7
[Dynmap]: Invalid texture block state: minecraft:cake:8
[Dynmap]: Invalid texture block state: minecraft:cake:9
[Dynmap]: Invalid texture block state: minecraft:cake:10
[Dynmap]: Invalid texture block state: minecraft:cake:11
[Dynmap]: Invalid texture block state: minecraft:cake:12
[Dynmap]: Invalid texture block state: minecraft:cake:13
[Dynmap]: Invalid texture block state: minecraft:cake:14
[Dynmap]: Invalid texture block state: minecraft:cake:15
[Dynmap]: Invalid texture block state: minecraft:pumpkin_stem:8
[Dynmap]: Invalid texture block state: minecraft:pumpkin_stem:9
[Dynmap]: Invalid texture block state: minecraft:pumpkin_stem:10
[Dynmap]: Invalid texture block state: minecraft:pumpkin_stem:11
[Dynmap]: Invalid texture block state: minecraft:pumpkin_stem:12
[Dynmap]: Invalid texture block state: minecraft:pumpkin_stem:13
[Dynmap]: Invalid texture block state: minecraft:pumpkin_stem:14
[Dynmap]: Invalid texture block state: minecraft:pumpkin_stem:15
[Dynmap]: Invalid texture block state: minecraft:melon_stem:8
[Dynmap]: Invalid texture block state: minecraft:melon_stem:9
[Dynmap]: Invalid texture block state: minecraft:melon_stem:10
[Dynmap]: Invalid texture block state: minecraft:melon_stem:11
[Dynmap]: Invalid texture block state: minecraft:melon_stem:12
[Dynmap]: Invalid texture block state: minecraft:melon_stem:13
[Dynmap]: Invalid texture block state: minecraft:melon_stem:14
[Dynmap]: Invalid texture block state: minecraft:melon_stem:15
[Dynmap]: Invalid texture block state: minecraft:nether_wart:4
[Dynmap]: Invalid texture block state: minecraft:nether_wart:5
[Dynmap]: Invalid texture block state: minecraft:nether_wart:6
[Dynmap]: Invalid texture block state: minecraft:nether_wart:7
[Dynmap]: Invalid texture block state: minecraft:cauldron:4
[Dynmap]: Invalid texture block state: minecraft:cauldron:5
[Dynmap]: Invalid texture block state: minecraft:cauldron:6
[Dynmap]: Invalid texture block state: minecraft:cauldron:7
[Dynmap]: Invalid texture block state: minecraft:cauldron:8
[Dynmap]: Invalid texture block state: minecraft:cauldron:9
[Dynmap]: Invalid texture block state: minecraft:cauldron:10
[Dynmap]: Invalid texture block state: minecraft:cauldron:11
[Dynmap]: Invalid texture block state: minecraft:cauldron:12
[Dynmap]: Invalid texture block state: minecraft:cauldron:13
[Dynmap]: Invalid texture block state: minecraft:cauldron:14
[Dynmap]: Invalid texture block state: minecraft:cauldron:15
[Dynmap]: Invalid texture block state: minecraft:cocoa:12
[Dynmap]: Invalid texture block state: minecraft:cocoa:13
[Dynmap]: Invalid texture block state: minecraft:cocoa:14
[Dynmap]: Invalid texture block state: minecraft:cocoa:15
[Dynmap]: Invalid texture block state: minecraft:anvil:12
[Dynmap]: Invalid texture block state: minecraft:anvil:13
[Dynmap]: Invalid texture block state: minecraft:anvil:14
[Dynmap]: Invalid texture block state: minecraft:anvil:15
[Dynmap]: Invalid texture block state: minecraft:hopper:1
[Dynmap]: Invalid texture block state: minecraft:hopper:7
[Dynmap]: Invalid texture block state: minecraft:hopper:9
[Dynmap]: Invalid texture block state: minecraft:hopper:15`
`Server thread/WARN
 
12:01:49

=============================================================
MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
Offender: org/dynmap/jetty/server/ShutdownMonitor$ShutdownMonitorThread.run()V
Use FMLCommonHandler.exitJava instead
=============================================================`
`Server thread/INFO
 
12:01:49

[Dynmap]: Web server started on address 0.0.0.0:8123
[Dynmap]: version 3.0-beta-4-213 is enabled - core version 3.0-beta-4-213
[Dynmap]: For support, visit https://forums.dynmap.us
[Dynmap]: To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
[Dynmap]: Loaded 3 maps of world 'world'.
[Dynmap]: Loaded 3 maps of world 'DIM20'.
[Dynmap]: Loaded 3 maps of world 'DIM-23'.
[Dynmap]: Loaded 2 maps of world 'DIM1'.
[Dynmap]: Loaded 3 maps of world 'DIM-17'.
[Dynmap]: Loaded 2 maps of world 'DIM-1'.
[Dynmap]: Loaded 3 maps of world 'DIM-9999'.
[Dynmap]: Loaded 3 maps of world 'DIM-11325'.
[Dynmap]: Loaded 253595 pending tile renders for world 'world'
[Dynmap]: Loaded 12232 pending tile renders for world 'DIM20'
[Dynmap]: Loaded 10953 pending tile renders for world 'DIM-23'
[Dynmap]: Loaded 55583 pending tile renders for world 'DIM1'
[Dynmap]: Loaded 15595 pending tile renders for world 'DIM-1'
[Dynmap]: Register events
[Dynmap]: Register commands
[Dynmap]: Enabled`
`Server thread/INFO
 
12:01:49

Overridden 146 commands
Unloading dimension 1
Unloading dimension 20
Unloading dimension -23
Unloading dimension -17
Unloading dimension -11325
Unloading dimension -1
[Dynmap]: Saved 55583 pending tile renders in world 'DIM1'

Dynmap Render Thread/INFO
 
12:01:49

[Dynmap]: Loading resource pack standard

Server thread/INFO
 
12:01:50

[Dynmap]: Saved 12232 pending tile renders in world 'DIM20'
[Dynmap]: Saved 10953 pending tile renders in world 'DIM-23'
[Dynmap]: Saved 15595 pending tile renders in world 'DIM-1'

Dynmap Render Thread/FATAL
 
12:01:52

[Dynmap]: Exception during render job: world=world, map=null

Dynmap Render Thread/INFO
 
12:01:52

[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: java.lang.ArrayIndexOutOfBoundsException: 65535
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.forge_1_12_2.ChunkSnapshot.<init>(ChunkSnapshot.java:229)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.forge_1_12_2.ForgeMapChunkCache.prepChunkSnapshot(ForgeMapChunkCache.java:1241)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.forge_1_12_2.ForgeMapChunkCache.readChunks(ForgeMapChunkCache.java:1407)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.createMapChunkCache(DynmapPlugin.java:887)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:685)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:644)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:193)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:209)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.lang.Thread.run(Thread.java:748)

Dynmap Render Thread/FATAL
 
12:04:15

[Dynmap]: Exception during render job: world=world, map=null

Dynmap Render Thread/INFO
 
12:04:15

[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: java.lang.ArrayIndexOutOfBoundsException: 65535
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.forge_1_12_2.ChunkSnapshot.<init>(ChunkSnapshot.java:229)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.forge_1_12_2.ForgeMapChunkCache.prepChunkSnapshot(ForgeMapChunkCache.java:1241)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.forge_1_12_2.ForgeMapChunkCache.readChunks(ForgeMapChunkCache.java:1407)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.createMapChunkCache(DynmapPlugin.java:887)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:685)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:644)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:193)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:209)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: at java.lang.Thread.run(Thread.java:748)`

**Comment by FedUpWith-Tech** [comment]
This is something that should be handled by dynmap-blockscan and their issue tracker
