### ISSUE TITLE
After /dynmap fullrender have some empty spaces

### ISSUE THREAD

**Issue by writingdeveloper** [webbukkit/dynmap#2607]
Server OS : Ubuntu 18.04 LTS Server
RAM : 16GB
Minecraft Version : 1.14.4
Spigot Version : 1.14.4

I tried /dynmap fullrender command to fill all the maps in Dynmap. I it seems working, but there are some problems. It loads almost done but, there are spaces in some part and even I tried /dynmap fullrender again, it doesn't loaded.

And I also use with WorldBorder.

Is there any solutions with this problem?

[Sample Screen Shot]
![Cap 2019-09-07 11-44-20-829](https://user-images.githubusercontent.com/6832586/64505634-7c9aca00-d30f-11e9-8e38-d96eae69899a.png)

**Comment by YourCoalAlt** [comment]
Apparently this is not a Dynmap issue I come to find out, but a problem if you used /wb fill. https://github.com/Brettflan/WorldBorder/issues/156 If you go to the non-rendered areas yourself and force a render, they should update.

**Comment by writingdeveloper** [comment]
> Apparently this is not a Dynmap issue I come to find out, but a problem if you used /wb fill. [Brettflan/WorldBorder#156](https://github.com/Brettflan/WorldBorder/issues/156) If you go to the non-rendered areas yourself and force a render, they should update.

Thanks for the reply. I thought the problem is from Dynmap.

**Comment by smmmadden** [comment]
Will there be another update of WorldBorder to fix this?  I'm seeing the same on a newly created 1.14.4 PaperSpigot server with Dynmap-3.0-beta-5-spigot.jar and WorldBorder1.9.10.jar

Having to manually go to every spot to generate the blanks shouldn't be the solution.
