### ISSUE TITLE
Visibilitylimits not working..

### ISSUE THREAD

**Issue by dotI0** [webbukkit/dynmap#2608]
Hello, 
I'm using the latest PaperMC with dynmap 3.0 beta 5. 
When I want to use the visibility limits and set a hide style, dynmap renders the visible area but the rest of the world won't be rendered (hide style is stone). Instead, dynmap seems to render in an infinite loop and won't stop rendering tiles. (when I'm using visibility limits, the amount of tiles is much more than the world normally have without visibility limits and dynmap won't stop rendering.)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
