### ISSUE TITLE
[Feature Request] Permissions node to force players being visible on the map

### ISSUE THREAD

**Issue by diamondwelsh** [webbukkit/dynmap#2610]
It would be nice if we could restrict who shows up on the map via a Permission node, that would overrule an individual's show/hide command.
Something like dynamp.forcehide or dynmap.forceshow
My intended usage would be to assign permissions to users for specific contexts that aren't always able to run the show/hide command on a trigger.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
