### ISSUE TITLE
Can't connect 

### ISSUE THREAD

**Issue by Deusie** [webbukkit/dynmap#2611]
I installed the plugin just fine it shows up in mc and i can run the render command in-game but when I try to connect through the browser I can't connect 
in the server console I saw this message pop up: Web server started on address "MyserverIP":8123
but I did also get the error: Error reading plugins/dynmap/markers.yml did I mess something up I haven't messed with any settings or configuration yet so I don't think thats the problem.

**Comment by VortexP** [comment]
Make sure that you don't have firewall blocking the port 8123
