### ISSUE TITLE
Marker not found when trying to update it

### ISSUE THREAD

**Issue by DarckCrystale** [webbukkit/dynmap#2612]
### Scenario:
- Create a new marker by doing `/dmarker add "My marker" icon:pin`
- Create a new marker set by doing `/dmarker addset "My set"`
- Change the set of the market to the new one by doing `/dmarker update "My marker" set:"My set"`

### Expected behaviour:
Either
- `My marker` has now the set `My set`
or
- An error message is displayed:
```
Error: it is not possible to edit the set of a marker
```

### Current behaviour:
- An error message is displayed:
```
Error: marker not found - My set
```

**Comment by DarckCrystale** [comment]
Also, I'm volunteer to edit the Using markers wiki page to make it easier to find information inside if you allow me to edit it.

**Comment by JurgenKuyper** [comment]
@DarckCrystale after some figuring out I found out the set needs to be defined before the marker is added to it. at least in latest beta (3.3-beta-4)
