### ISSUE TITLE
Flat map not loading

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#2615]
On my server one world does not show any chunks outside of spawn do not load for the top-down map of that world,  but the perspective ones work properly. I tried to call a fullrender, restarted the server, tried updating the chunks and breaking/placing a few blocks, and waited for a few days now for it to load. This also happens in other worlds, but its just a few annoying pieces of the map not appearing despite the chunks existing or me travelling there. I also tried using worldborder fill for a circle but the holes still exist. Is there any command/setting i'm missing to fix that?

![image](https://user-images.githubusercontent.com/13966312/65387558-c55b7580-dd48-11e9-9c26-1a2193f5a703.png)
![image](https://user-images.githubusercontent.com/13966312/65387566-d2786480-dd48-11e9-8cb1-aefac4bcdb95.png)

![image](https://user-images.githubusercontent.com/13966312/65387551-b2e13c00-dd48-11e9-82b8-318bfd437218.png)

**Comment by icemagetv** [comment]
Maybe best to try purging the map and re-rendering from scratch.

Consider your world is named "yourworld" and the Flat Map is called "flatmap" then try;
```
dynmap pause all
dynmap purgemap yourworld flatmap
dynmap purgequeue
dynmap fullrender yourworld:flatmap
dynmap pause none
```

Wait for the world to render some and see if it's better.
