### ISSUE TITLE
Support for Forge 1.14.4

### ISSUE THREAD

**Issue by Programie** [webbukkit/dynmap#2616]
Is it already planed to support Forge 1.14.4? It was in beta since July and reached stable a few days ago.

There are [files for Forge 1.13.2](https://github.com/webbukkit/dynmap/tree/v3.0/forge-1.13.2) but I don't know how hard it is to update them to Forge 1.14.4.

I'm currently successfully using the latest beta of Dynmap on my Spigot 1.14.4 server but thinking about switching to Forge.

**Comment by icemagetv** [comment]
Forge 1.14.x is a massive rewrite.  It may take the author some time - it may be just updating the builds to allow for it.  AFAIK the first recommended release was only 11 days ago.

However, a forge server is very different than a Spigot / Vanilla server - and unless you are running a modpack, you likely do not need or want to run a Forge server.  If you currently have Spigot (bukkit) plugins, they will not work on the Forge server (except by some kind of miracle or change I'm unaware of).

**Comment by Programie** [comment]
> AFAIK the first recommended release was only 11 days ago.
As already said, it was in beta since July and reached stable a few days ago.

Don't get me wrong, I'm not trying to say "It's already released and no Dynmap update? Lame!". It's just a question whether we will get a release for Forge 1.14 or whether the next release might even target some other modding framework like Fabric (as I have seen some Forge mods switching to Fabric).

> However, a forge server is very different than a Spigot / Vanilla server
I know the difference between Forge and Bukkit/Spigot and I also know that Bukkit plugins won't work on a Forge server. That's the reason why I'm asking whether Forge 1.14 will be supported in the future.

I'm already thinking about using some Forge mods which also require client mods and therefore impossible to build as a Bukkit plugin. That's the reason I want to switch to Forge.

But I guess there are also some other users waiting for 1.14 updates for their Forge mods.

**Comment by mikeprimm** [comment]
Yep - forge 1.13.x was huge, and I still haven't had time to finish it (I did close to a rewrite of the internals for the sake of 1.13.x+ that has been delivered for Spigot/Bukkit for a while now, but the level of API change for Forge for 1.13.x vs 1.12.x has made that update a whole lot harder (and 1.14.x will come after that, since its dependent on the same more fundamental updates, plus some more incremental ones).  Sorry for the delay, but I'm just fighting for time to work on these versions....

**Comment by smmmadden** [comment]
when you get to the testing phase of 1.14.4 Forge, do let me know.  I'm trying to put 1.12.2 behind and move to 1.14.4 and 1.15 shortly after.  Thanks !!

**Comment by LiskoSlayer63** [comment]
I'm in the same situation with @smmmadden. i need to update the whole server to a newer version than 1.12.2, prefering 1.14.4 at the moment of writing. Dynmap is _almost_ the only reason I haven't done that yet.
