### ISSUE TITLE
Show Forceloaded Chunks

### ISSUE THREAD

**Issue by thunderai** [webbukkit/dynmap#2617]
Can you implement a way to show chunks which have been force-loaded?  This would be easier than trying to add markers to the map for each one. 

Thanks.

**Comment by baconwaifu** [comment]
Given how the backend is written, for it to not be using the marker system, it would either have to be an "alternative" marker system, or require storage of multiple versions of pre-rendered tiles with a border (or other distinguishing feature)

The most likely implementation would be a little stub running server-side that stores a list of all force-loaded chunks, and then automatically adds markers. this would be best implemented as a plugin similar to dynmap-structures.

**Comment by thunderai** [comment]
Works for me!



Sent from my Sprint Samsung Galaxy Note9.


-------- Original message --------
