### ISSUE TITLE
dynmap only starting on local ip

### ISSUE THREAD

**Issue by lrmtheboss** [webbukkit/dynmap#2625]
dynmap is only starting on the local ip (127.0.0.1:8123) and now the main ip (192.168.1.3:8123) It might be a config thing I'm overlooking but any help would be much appreciated!

Setup Details:
paper spigot-209 (1.14.4)
behind
bungeecord #1420

**Comment by Frascar** [comment]
In the configuration.txt there is a line that sets the web server bind address. It would be worth checking that it is uncommented and set correctly.


![image](https://user-images.githubusercontent.com/8135822/66425593-f9e95580-ea07-11e9-9c50-2ad6fe3b02a9.png)

**Comment by lrmtheboss** [comment]
Yes it is set to 0.0.0.0 in the config but in the console when it starts it says “starting web server on ip:
127.0.0.1:8123
