### ISSUE TITLE
forums.dynmap.us

### ISSUE THREAD

**Issue by seema84** [webbukkit/dynmap#2627]
your website: https://forums.dynmap.us/
you urgently need a new forum and/or a better captcha for phpbb :-)
the bots take over the forum

**Comment by rautamiekka** [comment]
phpBB is perfectly viable when it comes to CAPTCHA, you just need to correctly tighten the settings. I know cuz I've done that.

**Comment by FedUpWith-Tech** [comment]
forum has been taken down permanently
