### ISSUE TITLE
Changing lighting does not affect render for nether_world

### ISSUE THREAD

**Issue by deb0ch** [webbukkit/dynmap#2628]
I can't see anything in my Nether world maps and am trying to brighten them up - to no avail.

I am using `deftemplatesuffix: hires` in `configuration.txt`, and the default there is `nethershadows`, which I see having a light level of 4 in the lighing configs. So I went to the `templates/nether-hires.txt` (not the proper way I know) to change `nethershadows` -> `shadows`. I restart my server, check that the changes I made were taken into account with `/dmap maplist nether_world` that showed correctly that the lightings were `shadows` - the same as the normal world maps.

But purging the nether world and `/dynmap fullrender nether_world` led to the same super-dark-can't-see-anything lighting.

Is it a bug ? Did I miss something ?

`/dynmap version` shows `Dynmap version: core=3.0-beta-5-218, plugin=3.0-beta-5-218`

On another note, is it even normal that by default the nether is so dark that unlit netherrack appears as plain black, making tiles undistinguishable ?

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.

**Comment by deb0ch** [comment]
I haven't played since, so I don't know  ¯\\_(ツ)_/¯

**Comment by Larbaco** [comment]
I think it persists
i'm trying to make it brighter with custom-lighting but it wont change the light
Dynmap version: core=3.2-beta-3-512, plugin=3.2-beta-3

**Comment by deb0ch** [comment]
@FedUpWith-Tech Based on @Larbaco 's comment his should be reopened, no ?
