### ISSUE TITLE
Dynmap Web address does not work ever since moving my server to another host

### ISSUE THREAD

**Issue by spookynala** [webbukkit/dynmap#2629]
Hey there,

I have a server through Apex Hosting which uses multicraft. I moved the server within Apex from a Canada host to Virginia. Ever since then, the dynmap (which was working) is no longer working. I uninstalled it completely, reinstalled it, changed the port, and when i load the webpage it just loads blank white. 

I have tried every trouble shoot I can find in forums and youtube pages. I do not know what the issue could be. Here is the web address that it should be on using the ip address and port:

147.135.68.190:5295

I would appreciate any help you can offer. thank you!

**Comment by fichdlmaa** [comment]
Why not http://147.135.68.190:8123 ?
