### ISSUE TITLE
Cant View DynMap

### ISSUE THREAD

**Issue by Bryn-Elliott** [webbukkit/dynmap#2631]
I have followed many tutorials and tried many ports. As far as I can tell DynMap is loading correctly on the server but when I put the address into my webpage I receive a "this site can't be reached, [IP] refused to connect."
![Capture](https://user-images.githubusercontent.com/56700021/67044743-dd929a80-f124-11e9-8ba9-318afb0b3f07.JPG)
 Please Help.
In case its any help, I have attached a .txt of a console script from a server start up and my DynMap Config File.
[configuration.txt](https://github.com/webbukkit/dynmap/files/3741191/configuration.txt)
[Server-StartUp.txt](https://github.com/webbukkit/dynmap/files/3741189/Server-StartUp.txt)

**Comment by fichdlmaa** [comment]
You say DynMap "is loading correctly". According to startup log, that's right.
Therefore this is *not* a DynMap problem!

Why do you use fixed IP an not domain?
If "hosted" locally at home, enable port 8123 in your router.

Public IP of your router changes from time to time: Therefore use a ddns (Dynamic DNS) provider!

I you have no idea, use Google / Startpage / ....   or contact the IT professional of you choice.

**Comment by USMCsky** [comment]
Sorry Boost.... the world is full of buttwipe responses. I am having the same issue. Peeps like ^^^^ make communities toxic.
