### ISSUE TITLE
[Feature Request] Allow webmap to be visible when the server is offline

### ISSUE THREAD

**Issue by TKwSni** [webbukkit/dynmap#2632]
Hi, I was looking for a way to upload the generated map to my website and just show it, no updates, no players moving, just the map so people can see it and get an idea of where they are.

I managed to do this once but i forgot how I did it, anyone can help? thanks.

**Comment by dpsi** [comment]
Do a full render then follow the steps for hosting using an external webserver by copying the tiles and web pages. You don't need the json in your use case.

**Comment by Adam759** [comment]
To be a bit more specific, just copy the contents `web` folder from the `dynmap` folder in plugins to your website document root or to a subfolder of your choice. It should work, just without live server time and player updates. This is assuming your tiles are stored as files in `web` as well.

**Comment by TKwSni** [comment]
I tried both methods, none worked, I just see a black page any ideas ?

**Comment by FedUpWith-Tech** [comment]
Hijacking this thread as a feature suggestion

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
