### ISSUE TITLE
Not my world

### ISSUE THREAD

**Issue by ItsReckliss** [webbukkit/dynmap#2634]
When I do https://reckliss.serverminer.com:8123 it doesn't show my world, it shows someone else world I've never talked to or seen before. I don't know what local IP because I am hosting my server with ServerMiner so I can't try that either. Someone, please help I'm trying to find a village Dx

**Comment by fichdlmaa** [comment]
Did you type a : after reckliss? That is an error! This will surely NOT show your DynMap!

**Comment by ItsReckliss** [comment]
Hahahahaha no, that’s a typo.

**Comment by pavog** [comment]
Have you tried setting a different webserver-port in your config?
