### ISSUE TITLE
Markers disapearing in overworld

### ISSUE THREAD

**Issue by ZEBaker98** [webbukkit/dynmap#2635]
My markers are disappearing in the overworld. Markers in the nether are fine. This seems to happen after a server restart. Creating a new marker causes them to reappear. Using  /dmarker list while the markers are not showing on the map does cause them to be listed but does not update them on the map. I tried deleting dynmap config folder and re-rendering the map and I am still having this issue.

I am running Dynmap-3.0-beta-5 on Spigot git-Spigot-94af569-db98d54 for 1.14.4
Config file in use
[configuration 2.txt](https://github.com/webbukkit/dynmap/files/3769399/configuration.2.txt)

**Comment by JupiterSnarl** [comment]
Are you finding it happening with all markers or just a few that are sign markers?
We have this problem too, but it is only markers that are placed by signs on a vertical side of a block. All other markers are working for us.

**Comment by nshire** [comment]
All of my markers that were made using ingame signs have been removed from the web map as well as the marker list("/dmarker list").

This probably has something to do with the 1.14 change that added signs for all wood types. There is no longer an item called "sign", they have been replaced with "oak_sign", "spruce_sign", etc.

**Comment by JurgenKuyper** [comment]
@ZEBaker98 @nshire no longer the case in latest dynmap. please reopen if the issue still arises.
