### ISSUE TITLE
dynmapforge does not appear to provide any dynmap.* permissions

### ISSUE THREAD

**Issue by miiichael** [webbukkit/dynmap#2639]
Hello, Dynmap-3.0-beta-4-forge-1.12.2 user here. Trying to allow players on my server to create [markers via signs](https://github.com/webbukkit/dynmap/wiki/Using-markers). I initially thought the problem was that users needed the `dynmap.marker.sign` permission, but forge itself doesn't provide any mechanism for granting permissions. So I added ForgeEssentials to my modpack and granted `dynmap.marker.sign` to users. However, I later noticed that ForgeEssentials/PermissionsList.txt (which lists all known permissions) does not list any permissions provided by DynmapForge, only for the commands it provides:
```shell
minecraft@myserver:/path/to/instance$ grep -i dynmap ForgeEssentials/PermissionsList.txt 
command.dynmap                                                                          # (OP only: true) 
command.dynmapexp                                                                       # (OP only: true) 
```
I then notice that even opped players are still unable to create markers via signs. Granting `command.dynmap` works, but I think I'd prefer signs to work as intended. :)

Using forge-1.12.2-14.23.5.2847, forgeessentials-1.12.2-12.3.60, and a bunch of other mods.

**Comment by FedUpWith-Tech** [comment]
This should be taken up with the dynmap-essentials issue tracker

**Comment by miiichael** [comment]
You mean ForgeEssentials? I've never used dynmap-essentials (it being a bukkit thing)...

Though I still think it would be nice if `enablesigns` was usable without adding mods that implement extra permissions frameworks (or that dynmap notices if one isn't installed and complains "this isn't ever going to work" :P)
