### ISSUE TITLE
When I attempt a full render I get this, Any help would be appreicated :)

### ISSUE THREAD

**Issue by 82280zx** [webbukkit/dynmap#2646]
I'm using Dynmap-3.0-beta-4-forge-1.12.2, I did use Dynmap Block Scan to generate my config files for renderdata/custom. I have tried purging my map / redoing a full render without the custom folder and Fullrender still throws an error is that number it gives me a coordinate that I can go inspect in the game? Or Is there a log file / debug mode I can use to find my issue for dynmap?
Thanks!

00:08:15 Full render of map 'flat' of 'world' in progress - 3300 tiles rendered (69.85 msec/tile, 39.04 msec per render)

00:08:25  Full render of map 'flat' of 'world' in progress - 3400 tiles rendered (70.49 msec/tile, 39.66 msec per render)

00:08:34  Full render of map 'flat' of 'world' in progress - 3500 tiles rendered (70.98 msec/tile, 40.21 msec per render)

Dynmap Render Thread/FATAL
 
00:08:34  [Dynmap]: Exception during render job: world=world, map=org.dynmap.hdmap.HDMap@2224313e

Dynmap Render Thread/INFO
 
00:08:34  [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: java.lang.ArrayIndexOutOfBoundsException

**Comment by dansleboby** [comment]
I get  the same issue
