### ISSUE TITLE
s

### ISSUE THREAD

**Issue by fortnitewarrior** [webbukkit/dynmap#2647]

**Comment by 82280zx** [comment]
did you unpause it? /dynmap pause none to make sure its not paused.

**Comment by Adaster54** [comment]
I tried that, didn't work

**Comment by msknight** [comment]
Did you upgrade the server? I'm having an issue whereby I upgraded my server from 1.13 to 1.14.4 and upgraded the plugins to the latest, and when I issue a dynmap /fullrender it only does the chunks which have been re-explored in 1.14.4. It ignores the chunks previously generated, but not "played" since the upgrade.

**Comment by msknight** [comment]
I started with the --forceUpgrade option and it's upgrading all my chunks to 1.14.4 now. I expect that after this, Dynmap will be able to do a full render of the worlds.

**Comment by 82280zx** [comment]
Where do we put the --forceUpgrade in at? I'm running a 1.12.2 server still get the render issues but then again I'm over the block limit to using not enough ids, I kinda wonder if thats my problem.

**Comment by msknight** [comment]
In your java launch command...

java -jar spigot.jar --forceUpgrade

...and check the log output to make sure it's doing it.

Then in the game try a dynmap /fullrender and see what happens.

**Comment by 82280zx** [comment]
Will that work with Forge?

**Comment by msknight** [comment]
I've got no clue. I can't find anything confirming it will. Just try it, I guess. It can but complain.

**Comment by 82280zx** [comment]
Yup I gave it a shot that command won't work with forge :( it errors out, thanks for trying though!
