### ISSUE TITLE
Provide some more information for fullrender

### ISSUE THREAD

**Issue by Programie** [webbukkit/dynmap#2648]
Would it be possible to show the actual percentage progress of a fullrender task and maybe even estimated time remaining to complete it?

There is another project "Minecraft Overviewer" which is able to know the actual progress in percent and the estimated time remaining, so I guess it might be also possible to implement it in dynmap.

Another cool feature would be to provide the render progress in the web frontend.

I know there was already a similar discussion back in 2011 (#140), but maybe today, there are some more possibilities. So I give it another try to ask. :-)

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
