### ISSUE TITLE
Host has an assigned port.

### ISSUE THREAD

**Issue by SG-7** [webbukkit/dynmap#2650]
I'm using FroHost to host my server and their IPs are like 0.0.0.0:25635
I can't shut off the port forwarding, so how would the dynmap address work with an IP like this?

**Comment by dryter97** [comment]
well you choose your port obiviously on the config.txt but your host need to give you an extra port. the port fowarding is important to leave you acces to your server. without port fowarding you cant get any connection to your host.

**Comment by dryter97** [comment]
btw just saying its not an issus and its more like commun documentation you should go read about dynmap
