### ISSUE TITLE
Dynmap won't run on my server

### ISSUE THREAD

**Issue by Dwalin11** [webbukkit/dynmap#2651]
![image](https://user-images.githubusercontent.com/57550251/68521201-4e306100-0264-11ea-8156-600b43607e81.png)
I have limited computer smarts, but follow directions well. I dragged what the web page had for latest Dynmap version into my Plugins folder (Bukkit/Spigot server) and got the attached when it tried to run Dynmap. It clearly failed, it did not create a folder in Plugins like my other plugins did. We like Dynmap. Can anyone diagnose this and suggest a fix? Thanks.

**Comment by DerangedWifi** [comment]
You're running an outdated version of Dynmap, 2.5 on a 1.14 server. You should try the latest version, 3.0 Beta 5. Here's a link https://www.spigotmc.org/resources/dynmap.274/

**Comment by Dwalin11** [comment]
Thanks! I'm not always good at navigating to find the most recent version.
It loaded quickly.
DFG

**Comment by DerangedWifi** [comment]
That's all good. Make sure to close this issue.

**Comment by DerangedWifi** [comment]
Oh, for next time, try looking thorough the errors message and do your best to logically determine whats going on. 

Here's how I knew that you had an outdated version. 
![image](https://user-images.githubusercontent.com/33496590/68829152-c29c4300-065c-11ea-86de-e4c28e368e9f.png)

Then, you see what version you are running at
![image](https://user-images.githubusercontent.com/33496590/68829175-d8116d00-065c-11ea-88e0-fa5030ee1c40.png)

Check the version number, then visit the plugin's website to find it's most recent version, considering you are on the latest version of Minecraft.
![image](https://user-images.githubusercontent.com/33496590/68829223-0000d080-065d-11ea-909d-c6a9b843e7e2.png)

Seems like a version mismatch.
In the version history, it seems like 2.5, your version, is from 2017, which won't be able to work on the latest and greatest.
![image](https://user-images.githubusercontent.com/33496590/68829275-2c1c5180-065d-11ea-8e92-976504491549.png)


Thats pretty much it! Best of luck with your future plugins, hope you learned a thing or two!
