### ISSUE TITLE
Web server won't start on any port

### ISSUE THREAD

**Issue by DerangedWifi** [webbukkit/dynmap#2656]
I'm running a PaperSpigot sever under bungee cord. Dynmap works as intend when using localhost:8123, but not when the servers external IP is being used in place of localhost. In console log, issue is with Dynmap binding to a port, but I've tried ports 8123 - 8129, and the issue is always "cannot assign requested address: bind".

**Comment by DerangedWifi** [comment]
Sorry, forgot to add. Configuration.txt  has webserver-bindaddress: set to the server IP already. The issue still persists.

**Comment by Drc-DEV** [comment]
Does not work for me too

**Comment by Theprim0** [comment]
> 
> 
> Sorry, forgot to add. Configuration.txt has webserver-bindaddress: set to the server IP already. The issue still persists.

Comment out that webserver-bindaddress line, or just leave it but with the ip 0.0.0.0.
Supossing that you are running under a Linux system, with dynmap off, try to do:

`# netstat -vluntp` 

and see if there is any service already using that port.

Other problem you could have, is that you are running this in you home, and not vps, then you should open ports in your router/firewall
