### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by xMPBOI** [webbukkit/dynmap#2659]
So I want to start a geopol server and when I looked at the console it said this:
Failed to start WebServer on address [serverIP]:8123 : Address already in use
the "[serverIP]" is to censor the server ip.
I had a server before with dynmap on the same IP and thought the old one was deleted.
is there any way to fix this so I can go to the website and view the new rendered map and remove the old one?

**Comment by Aquariomel** [comment]
Change the port to another in the settings.
```
# The TCP port that the web server will listen on.
web server port: 8118
```
this is an example

**Comment by xMPBOI** [comment]
did that, same thing

**Comment by baconwaifu** [comment]
Are you using a hosted server, or are you running it yourself?
What platform is the server running on? (Windows, Linux, MacOS, etc.)
Are there any other *running* servers on the same machine?

**Comment by mikeprimm** [comment]
You might also need to change the server address in configuration.txt from 0.0.0.0 to your specific server IP (the IP of the interface ON the server, not the IP of, say, your NAT firewall or anything else).  That is, the IP you would see if you ran the 'ipconfig' command on the box.  You might be restricted from binding ports to other IPs on the box, and the 0.0.0.0 IP means 'all of the IPs, including localhost'.
