### ISSUE TITLE
Dynmap uses motd as the website Title

### ISSUE THREAD

**Issue by Desoru** [webbukkit/dynmap#2660]
`# Title for the web page - if not specified, defaults to the server's name (unless it is the default of 'Unknown Server')
#webpage-title: "Dynmap of TrodR6"`
and I even tried:
`#webpage-title:'Dynmap of TrodR6'`

**Comment by Aquariomel** [comment]
What's your problem? If you need your own name, uncomment 
`#webpage-title:'Dynmap of TrodR6'`
that would be so: 
`webpage-title: 'Dynmap of TrodR6'`

**Comment by Desoru** [comment]
Sorry I didn't think the # was for marking comments. Thank you tho for your help
