### ISSUE TITLE
Add Street View feature

### ISSUE THREAD

**Issue by YJJcoolcool** [webbukkit/dynmap#2661]
It would be great if a Street View feature such as the one in Google Maps is added into dynmap.

Here is my idea:
Users export their own 360 pictures manually (e.g. using ReplayMod) and place them to a folder in dynmap and in a config file declare the coordinates where the picture is.

Maybe have a dedicated layers section for Street View lines and set them as turned off by default.

When a user clicks on the lines, the nearest Street View picture then appears based on coordinates where the mouse pointer is.

For the rendering of 360 photos, there are some javascript codes available for free. Only thing is that there needs to be a way to move between the photos.

**Comment by FedUpWith-Tech** [comment]
This is way beyond what dynmap is capable of and there are no plans to support this currently. Its an incredibly complex task for a relatively unique feature. Feel free to fork this and develop this functionality on your own but maintaining this is a bit outside of the main branch
