### ISSUE TITLE
Dynmap doesn't render world generated by /wb fill

### ISSUE THREAD

**Issue by jintsuu** [webbukkit/dynmap#2663]
Heya,
as stated in the title my problem is that, no matter what I do, the /dynmap fullrender command doesn't render anything that was generated by the /wb fill command.
What I have tried so far:
run the server with the --forceUpgrade flag
execute /wb fill without DynMap installed (as people have been reporting issues with that)

Is this an issue on my part? If not, are there any workarounds until the issue is fixed?

**Comment by fihovi** [comment]
I'm sorry I might disappoint you, but this might work.

[https://www.reddit.com/r/admincraft/comments/cbnacf/dynmap_and_fullrenderlocations/etmr4wv/](url)

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2485
