### ISSUE TITLE
CORS Configuration Support

### ISSUE THREAD

**Issue by dannegm** [webbukkit/dynmap#2666]
There is any way to setup the **CORS** with Dynmap. I want to be able to consume the Dynmap API from third party servers but I have the CORS restriction:

> No 'Access-Control-Allow-Origin'

So that, I want to enable the CORS (with a simple header into the response of any request) like the following:

##### HTTP HEADERS
```http
Access-Control-Allow-Origin YOUR-DOMAIN.TLD
Access-Control-Allow-Headers Origin, X-Requested-With, Content-Type, Accept
```

Could be nice if already exist this option and you guys, could help me with this, otherwise, could be a nice new feature into the plugin.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
