### ISSUE TITLE
Could not retrieve information: Internal Server Error

### ISSUE THREAD

**Issue by BRGustavoRibeiro** [webbukkit/dynmap#2671]
Hello guys!
I'm having some trouble while using Dynmap v3 Beta 5.

I'm trying to use the webserver in a cPanel (external) environment in the following URL ([redacted FQDN to prevent SPAM]/assets/dynmap/index.html), and the tiles are being saved into a MySQL database. The Minecraft server isn't running in the same IP as the webserver ([redacted FQDN to prevent SPAM])
I did everything correctly, but it returns me a black screen saying "Could not retrieve information: Internal Server Error". Can someone please help me?

Here is my configuration.txt -> (https://pastebin.com/ndidMXGJ)

Thx a lot

**Comment by fihovi** [comment]
Could you post log of your server?
Can you see data in MySQL database?

**Comment by fihovi** [comment]
change 
`  - class: org.dynmap.InternalClientUpdateComponent
    sendhealth: true
    allowwebchat: true
    webchat-interval: 5`
to:
`  - class: org.dynmap.JsonFileClientUpdateComponent
    writeinterval: 1
    sendhealth: true
    allowwebchat: false`

**Comment by BRGustavoRibeiro** [comment]
Of course! Here it is: https://hastebin.com/edabihojit.txt
I can see all the data that Dynmap has been rendering in my MySQL server. It looks fine.

**Comment by T-x-T** [comment]
I am facing the same issue, did you manage to find a solution so far?

**Comment by BRGustavoRibeiro** [comment]
Not yet. Dynmap is a great plugin, with the trashiest config system I've ever seen, and the poorest docs I've ever read.
Still waiting for some help, and still trying to fix it.

**Comment by T-x-T** [comment]
I managed to find the solution (at least for me). I had to install php-mysqli using `apt install php-mysqli`
After restarting apache it worked! I hope this might be able to help you.
Some documentation on this would be great tho!

**Comment by BRGustavoRibeiro** [comment]
I'm afraid to not be able to do this - are you running in the same environment as I?
I'm running into a cPanel, CENTOS v7 with PHP 7 and mysqli available and enabled as default..
I do have root access to the system, but it's quite risky to run a command like this in cPanel, isn't it

**Comment by T-x-T** [comment]
Well I’m just running plain Debian 10 with an Apache Webserver. Maybe you can take a look at your webservers logs if you haven’t already. Apache Logs actually helped me figure it out

**Comment by BRGustavoRibeiro** [comment]
FINALLY! AFTER MONTHS OF TRIES, I was able to find a solution to this.
Please check all the permissions of your folder. Dynmap web was fucked up because the permissions of my directory were 747. I changed it to 555 and Dynmap loaded.

I just would like to say that I will write down a complete tutorial on how to config Dynmap at an external server + MySQL soon.
Thanks to everyone.
