### ISSUE TITLE
file delete

### ISSUE THREAD

**Issue by Bobbbe** [webbukkit/dynmap#2673]
The web folder is empty after the restart it starts again at zero! never had we had this problem before! is there an option to purge the file or other! persone has access to the files. the only change that there was as a change, we went from pex to luckperm. we have been using the same version of dynmap for a while. v3.0-beta-5-218 and spigot 1.14.4. a compatibility problem! I do not believe because the plugin just would not work and not empty the web folder or there are backups.
http://www.freebuildminecraft.com/dynmap.html

**Comment by Tsoccerguy3** [comment]
get Dymap beta 6 , and Dynmap is not fully updated to 1.14.x . you can not have a mixture of old format chunks and 1.14.x chunks and update those chunks on the fly without a big TPS hit and other errors . Do a spigot / paper --forceUpgrade once , then remove the switch

Read here for how to prepare your server for 1.14.4 and above https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-4-development-builds.369724/
