### ISSUE TITLE
Usage of selectMapAndPan

### ISSUE THREAD

**Issue by itzarty** [webbukkit/dynmap#2676]
Hi, Im making a website for my server that will provide on the user profiles e.g. if user is online etc, but I want  to also showup (if player for example plays bedwars) the play arena. Everything did go well, but then there was a problem. For example: I have world "Apple" and "Orange", I try to use selectMapAndPan("Apple"), but it doesnt work. How should it look like to switch to the world?

Sorry for my bad english

**Comment by FedUpWith-Tech** [comment]
I'm closing this due to age but if you still need help feel free to reopen this or submit a new issue
