### ISSUE TITLE
Renders outside the visibility limit

### ISSUE THREAD

**Issue by aescraftbr** [webbukkit/dynmap#2678]
hello,

I'm having issues with dynmap as there's renders outside the visibility limits.

`
worlds:
  -
    name: world
    title: "Aescraft Survival"
    enabled: true
    sendposition: false
    sendhealth: false
    visibilitylimits:
      - x: 195
        z: -81
        r: 5000
    hidestyle: air
    extrazoomout: 3
    tileupdatedelay: 30
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: stdtexture
        lighting: shadows
        mapzoomin: 2
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "Surface"
        prefix: t
        perspective: iso_SE_30_hires
        shader: stdtexture
        lighting: shadows
        mapzoomin: 2
`

The area being rendered is 61.000 blocks north, as you can see here:
http://aescraft.tk:8123/?worldname=worldapname=flat&zoom=3&x=-940&y=64&z=-61129

and here:

http://aescraft.tk:8123/?worldname=worldapname=flat&zoom=4&x=18470&y=64&z=-61267

Thanks.

**Comment by Tsoccerguy3** [comment]
get Dymap beta 6 , and Dynmap is not fully updated to 1.14.x . you can not have a mixture of old format chunks and 1.14.x chunks and update those chunks on the fly without a big TPS hit and other errors . Do a spigot / paper --forceUpgrade once , then remove the switch

Read here for how to prepare your server for 1.14.4 and above https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-14-4-development-builds.369724/

**Comment by aescraftbr** [comment]
That's not the case, since this server chunks are all in 1.14.4 (I created the map in 1.14.4)

But i'll see the link you sent

**Comment by aescraftbr** [comment]
Where do I get the dynmpa beta 6?

**Comment by fichdlmaa** [comment]
here it is: [Dynmap-3.0-beta-6-spigot](http://dynmap.us/builds/dynmap/Dynmap-3.0-beta-6-spigot.jar)  :-D

**Comment by fichdlmaa** [comment]
To get rid of most of the "black wholes" in maps I suggest worldborder fill command:

e.g.:
```
wb testworld set 1024 1024 0 0
wb testworld fill 10 50 true            <- *) 
wb fill confirm
```

--- wait until ready ---

`/dynmap fullrender testworld    <- or:  ...   testworld:flat   if 3D surface can wait ...`


_*) 1st param = speed <= 20; 2nd = offset fill beyond border (default=208); 3rd = force_

**Comment by aescraftbr** [comment]
None of the awnsers here helped me.
Anyone else having this issue?

**Comment by FedUpWith-Tech** [comment]
Maybe related to #2485

**Comment by FedUpWith-Tech** [comment]
Removing due to dead links.
