### ISSUE TITLE
Feature Request Luck perms API update v4-v5

### ISSUE THREAD

**Issue by johncsuti** [webbukkit/dynmap#2679]
Updates need to be made to use the v5 luck perms API. if you have v4 of luck perms you will experience no issues but once you upgrade to v5 there will be API dumps from dynmap because it cant create API calls to luck perms this is in response to this update of luck perms. you can see more information about what changed from v4 to v5 here: https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5

**Comment by fihovi** [comment]
Pull request #2670 waiting for merge
