### ISSUE TITLE
Webserver black screen

### ISSUE THREAD

**Issue by PowerKong** [webbukkit/dynmap#2681]
So i'm trying to use dynmap and the webserver is just a blank black screen. I have tried  everything I've seen and nothing is working. I am using version 3-0-beta-5-spigot on 1.14.4, and a couple of other plugins with spigot 1.14.4. Heres is the only thing I see when I go to the website: https://ibb.co/kKd2H1B
If anyone can help me, please do!!! Thanks!

**Comment by fihovi** [comment]
It would be helpful, if you post server log too, please do. Thanks

**Comment by BRGustavoRibeiro** [comment]
Are you having a similar problem? https://github.com/webbukkit/dynmap/issues/2671
