### ISSUE TITLE
ShadowHDLighting rendering shadows from clouds

### ISSUE THREAD

**Issue by hipsterfont** [webbukkit/dynmap#2683]
HI! I'm running on PaperMC, vanilla 1.14.4, and any lighting that utilizes ShadowHDLighting will render shadows from clouds and I can't find any way to disable this. It makes large maps kinda ugly with black spots in random places. Switching to DefaultHDLighting removes the cloud shadows (along with every other shadow of course) and I'd prefer not to have to switch to this :(. I've reproduced this with 3.0 beta 5 and latest build from HEAD.

I don't have any screenshots handy atm but I can reproduce them pretty easily.

**Comment by mikeprimm** [comment]
Note sure what mod you are using to create shadows from clouds, but it sounds like it is altering the world data to bring it about.  If the other mod is modifying the lighting data in the world data to create shadows, there is literally NOTHING dynmap can do to not be affected: that's the world data, and if it has been altered by a mod (whether it's WorldEdit, WorldBorder or someone doing something kludgy with the lighting, as you are describing), all it can do is read the same data as the client and rest of the code in the game is reading.  We get lighting data from the game - we don't generate our own (and will not do so, as the point of the rendering is to attempt to match vanilla client rendering as closely as can be managed).
