### ISSUE TITLE
Dynmap fullrender not working on 1:1000 Earth map

### ISSUE THREAD

**Issue by the-sink** [webbukkit/dynmap#2684]
Hi. Not sure if this is a Dynmap problem or a problem with the map (I can contact the map dev if need be), but I'm having an issue attempting to do a full render of a map that's a scale model of the Earth.
http://earth.motfe.net/ (1:1000 Earth Map, 1.13.2 No Features Edition, Release # 4)
(**EDIT:** I have just now also tried the 1:1000 Earth Map for 1.12 that should be fully generated already, and I've experienced the same issue)
I'm on version 3.0-beta-5-218.
I've already generated the entire map with WorldBorder and have set the boundary to the bounds of the map. I tried running /dynmap fullrender while in the world, as well as /dynmap fullrender earth in the console. Neither worked, only generating maybe 650 or so tiles before saying it was completed.
https://i.imgur.com/k2qgIqZ.png
^ Only generated a tiny portion of the map near spawn.
https://i.imgur.com/aoMqAzp.png
I've also tried resetting all the configs for the world with /dmap worldreset but that didn't seem to do anything either, nor /dynmap purgemap. I can't figure out what's causing this, any ideas?

**Comment by the-sink** [comment]
It seems other people are having this issue too (according to the Planet Minecraft post). I will be contacting the map developer about this.

**Comment by TheJoe49** [comment]
Did you ever hear back from the map creator?
