### ISSUE TITLE
[Feature request] A way to view a map without a web server

### ISSUE THREAD

**Issue by dark-penguin** [webbukkit/dynmap#2686]
Sometimes you just want to view a map - for nostalgic purposes, for example. :) And you don't want to set up a web server or a Minecraft server. Could it be possible to have a way to see the map without a web server, simply opening some HTML file from a browser?

[Overviewer](https://github.com/overviewer/Minecraft-Overviewer) allows that. But it does not include a web chat or players' positions. If tweaking index.html would be too difficult, maybe just add another file ("offline.html") that opens the map without any features that require a running server?

**Comment by Technoguyfication** [comment]
Have you tried opening index.html in your browser? If you're using the flat files storage method, this might work.

**Comment by dark-penguin** [comment]
It did not - that's why I thought maybe it would only take a little tweaking to do it. :)

**Comment by FedUpWith-Tech** [comment]
Duplicate function would be added in #2632
