### ISSUE TITLE
How do I make my Dynmap run on my domain

### ISSUE THREAD

**Issue by Frityet** [webbukkit/dynmap#2687]
I want it to be map.[mydomain]

**Comment by fihovi** [comment]
Then create your subdomain and put folder web (from plugins/dynmap/) in that subdomain folder.

**Comment by fihovi** [comment]
You can redirect from map.[] subdom to dynmap webserver

**Comment by Frityet** [comment]
I know, but I want it to run on my domain so it shows map.mydomain at the top

**Comment by Technoguyfication** [comment]
You need to set up your DNS records to do this, this issue isn't really in the scope of Dynmap. Learn about CNAME and A records and change your DNS zone configuration to match.

**Comment by Frityet** [comment]
Ok thanks!

**Comment by Frityet** [comment]
How would I do the CNAME? Do i do it like i did it with Minecraft?

**Comment by Technoguyfication** [comment]
You want an A or CNAME record as `map.example.com` pointed towards whatever domain or IP your dynmap webserver is located on. If it's an IP, use an A or AAAA record. If it's a domain name, use a CNAME record.

**Comment by partydev** [comment]
To add on to this, if you want your dynmap to run on your webserver, you need to set it up by following this guide: 
https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server
This guide assumes you have a web server set up on the same system as your Minecraft server.

**Comment by mikeprimm** [comment]
As @Technoguyfication indicated, what you are talking about is "How do I use DNS?" and isn't at all about Dynmap (or any other web or IP app) - you need to configure DNS to point to the IP address (using an A or AAAA record) or existing DNS name (using a CNAME record), and doing so is done via your domain registrar/hosting.  DNS controls how you get to a destination - there isn't anything the code at the destination (e.g. Dynmap or a web server) can do to get you there.

**Comment by HuJK** [comment]
I use nginx reverse proxy to do this:
First set DNS record ```map.mc.mydomain.com``` to my your server: 
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# HTTPS server to handle JupyterHub
server {
    listen 80;
    listen 443 ssl;

    server_name map.mc.mydomain.com;
#if you want use https, get letsencrypt cert first 
        ssl_certificate     /etc/letsencrypt/live/map.mc.mydomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/map.mc.mydomain.com/privkey.pem;
        location /.well-known {
            alias /var/www/html/.well-known;
        }
    # 
    location / {
        proxy_pass http://localhost:8123;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Real-IP $remote_addr;

        # websocket headers
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }

}
```

and I think this issue isn't dynmap's issue.

**Comment by LogiBear11** [comment]
> You want an A or CNAME record as `map.example.com` pointed towards whatever domain or IP your dynmap webserver is located on. If it's an IP, use an A or AAAA record. If it's a domain name, use a CNAME record.

How can you do that when these is a port?

**Comment by Technoguyfication** [comment]
> > You want an A or CNAME record as `map.example.com` pointed towards whatever domain or IP your dynmap webserver is located on. If it's an IP, use an A or AAAA record. If it's a domain name, use a CNAME record.
> 
> How can you do that when these is a port?

As mikeprimm said, this isn't within the scope of Dynmap support. DNS and HTTP are technologies you should have some knowledge of _before_ attempting to host a server.

If you have an IP/port combo for your dynmap server then you would point your DNS record to the IP address and append the port number after the domain name when entering the URL, just like normal when you use the IP instead of the domain name. DNS has no concept of port numbers and only replaces the IP part of the URL.

For example, if your dynmap is at `xxx.xxx.xxx.xxx:8123` and you create an A record of `dynmap.example.com` that points to `xxx.xxx.xxx.xxx`, then the URL would become `dynmap.example.com:8123`
