### ISSUE TITLE
[Feature Request] Add the ability to change the light emission of light sources in the world. 

### ISSUE THREAD

**Issue by Technoguyfication** [webbukkit/dynmap#2690]
I created a separate night map for my server. The map generates fine, but it's really dark. I have played with the ambient light value, but right now it looks like Minecraft with the brightness slider set all the way to "moody". Is there a way to change the shader so it looks like the game with the brightness slider set to "bright"?

I understand I can just change the ambient brightness, but I don't want the entire world lit up. I want the areas lit up with torches to be more "fully" lit while keeping the uninhabited areas at the normal ambient brightness. It seems like the brightness slider in-game increases the falloff range or the brightness of light sources, which is what I want to do.

Here's some pictures to demonstrate:

#### This is what it looks like:

Dynmap render:
![](https://tkno.pw/2t8odMX)

Minecraft set to "moody":
![](https://tkno.pw/2PBSWJB)

#### This is what I _want_ it to look like:
Minecraft set to "bright":
![](https://tkno.pw/35blnF2)

**Comment by mikeprimm** [comment]
Bright vs Moody is a client setting, not a server setting.  For dynmap, use the custom lighting options (see the lightings.txt file for pre-defined choices there).  See https://github.com/webbukkit/dynmap/wiki/HD-Map-Configuration for more details here

**Comment by Technoguyfication** [comment]
I've looked at this, I'm saying I don't see an option anywhere to increase the light emission of light sources in the world. I don't believe it's possible to get the effect I want with the current shader options. If it's not possible, then can this PR be tagged with a feature request tag?

The `shadowstrength` and `ambientlight` lighting options don't work in the same way that the Minecraft brightness slider works.

**Comment by Technoguyfication** [comment]
My question really wasn't answered yet, see: https://github.com/webbukkit/dynmap/issues/2690#issuecomment-565841607

**Comment by FedUpWith-Tech** [comment]
I see

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
