### ISSUE TITLE
Very light underwater tiles

### ISSUE THREAD

**Issue by SimisFul** [webbukkit/dynmap#2702]
Since 1.15, using the latest beta 7 build, all the tiles that are in the ocean and got updated look like the water is much more transparent/light than before.

![image](https://user-images.githubusercontent.com/8340181/71035385-5b553100-20e9-11ea-8c46-506ac003f65f.png)

This can be observed live here.

http://monddns.myddns.me/?worldname=world&mapname=surface&zoom=5&x=848&y=64&z=-486

**Comment by SimisFul** [comment]
Tested on beta 8 build, still happens.

**Comment by TheyCallMeLinux** [comment]
![map-light-bug](https://user-images.githubusercontent.com/25093857/71194829-acd0fd80-225a-11ea-9db0-ff35589670ba.png)

**Comment by TheyCallMeLinux** [comment]
![map-bug](https://user-images.githubusercontent.com/25093857/71194901-d4c06100-225a-11ea-86ec-5435054a60fd.png)

**Comment by mikeprimm** [comment]
What version were those chunks generated with?  Lighting comes from chunk data, not from dynmap.   Were they generated by normal game activity (clients), or using WorldBorder fill or the like?

**Comment by SimisFul** [comment]
@mikeprimm All normal activity for me in 1.14.4, then updated from events in 1.15. Never used the wolrdborder command.

**Comment by steveabraham** [comment]
I can confirm we're seeing the same thing, though across the entire map, not just in patches/chunks. Our map was generated in 1.15.1 using WorldBorder, apart from a small section at spawn which was generated manually. There's no difference between these two sections.

**Comment by SimisFul** [comment]
Tested in beta 9, issue still persists

**Comment by Sikatsu** [comment]
Same issue here.
![image](https://user-images.githubusercontent.com/5664135/71472861-f2e70d80-27d4-11ea-8fd2-d28b9964b4da.png)

**Comment by ghost** [comment]
Likewise, although for me the lighting issue is only happening to chunks that were generated before **1.14**
![Lighting](https://user-images.githubusercontent.com/25720855/71543383-c3b5d500-2969-11ea-8123-48247c0ade67.png)

**Comment by SimisFul** [comment]
> Likewise, although for me the lighting issue is only happening to chunks that were generated before **1.14**
> ![Lighting](https://user-images.githubusercontent.com/25720855/71543383-c3b5d500-2969-11ea-8123-48247c0ade67.png)

It happens for me in chunks that probably havr kelp that grew when I flew over there. Try generating new chunks or manually updating tiles where the water is deep enough and you should have the same result.

**Comment by ghost** [comment]
> It happens for me in chunks that probably havr kelp that grew when I flew over there. Try generating new chunks or manually updating tiles where the water is deep enough and you should have the same result.

The same result as what?

**Comment by SimisFul** [comment]
> > It happens for me in chunks that probably havr kelp that grew when I flew over there. Try generating new chunks or manually updating tiles where the water is deep enough and you should have the same result.
> 
> The same result as what?

I meant that you should get the same result as us and as you get, no matter the original version the chunks were generated in.
Sorry if I'm not too clear, just woke up :stuck_out_tongue:

**Comment by ghost** [comment]
Okay, I get that.  But it is _only_ pre 1.14 generated chunks that this is happening to in my world.

**Comment by MrLogano** [comment]
Can confirm that is also happens to me.

[Dynmap Link](https://maps.minecrafting.co.uk/) 

We are using beta-9, and recently upgraded to 1.15.1.

I used the --forceUpgrade argument when upgrading to 1.14.4, and then again upgrading to 1.15.1.

I had tried worldborder fill before hand, but that had no effect on the chunks. 

The render is currently working, but you can see the difference between the older ones generated under 1.14, and then the newer ones generated under 1.15.1 using the beta-9.

**Comment by targuien** [comment]
Having the same issue here, oceans look horrible after re-rendering the whole map using Beta9.

We are using Dynmap Beta-9.  Our world was originally 1.14, we recently upgraded to 1.15.1 and Dynmap Beta 9.  
The bright ocean areas were patchy at first so I issued a /dynmap fullrender command to rebuild all tiles.  Equally ugly everywhere now.  I read that maybe Dynamp is rendering temperature zones and rainfall data over the map?  I can't find any mention of this in the config files or a way to disable these features.

We just want nice looking dark blue oceans like we had pre beta 9.  Is there a way to get this ?

Our online DynMap:   http://phoenixcraft.serv.nu:10445/

**Comment by Lud00** [comment]
Hello,
Same issue here with Beta 9.
It look like only the regions from 1.14 upgraded to 1.15.1 are impacted.
I upgraded my world from 1.14 to 1.15 to 1.15.1 with "--forceUpgrade"
New Generated region are not impacted.
![Screenshot from 2020-01-10 07-14-50](https://user-images.githubusercontent.com/29888620/72134242-6d8a5e00-337b-11ea-8087-66121fccf707.png)

**Comment by MilesBHuff** [comment]
We're seeing the same issue on our server since updating to 3.0-beta9.  We've always run 1.14 on this server, and are currently running 1.14.4.  Going to try reverting to an older version of Dynmap tomorrow.
http://settlescape.duckdns.org:8123

**Comment by MilesBHuff** [comment]
Reverting to v3.0-beta5 fixed the issue (https://github.com/SettleScape/server/issues/15).  This is definitely a regression.

**Comment by htutich** [comment]
For version 1.15.1, using an earlier version is not a solution.

**Comment by Lud00** [comment]
> For version 1.15.1, using an earlier version is not a solution.

I agree. But now we know from what version it's been broken.

**Comment by seema84** [comment]
maybe it was fixed?
https://github.com/webbukkit/dynmap/commit/e74741b7bd965ef36fee581ca18035fda0a9fbf3

**Comment by SimisFul** [comment]
> maybe it was fixed?
> [e74741b](https://github.com/webbukkit/dynmap/commit/e74741b7bd965ef36fee581ca18035fda0a9fbf3)

It was!
Issue is resolved.
