### ISSUE TITLE
Dynmap generates stripes / looks like a maze

### ISSUE THREAD

**Issue by derMiepz** [webbukkit/dynmap#2704]
Main problem in title. We're converted a 1.8 map to 1.14.4 successfully. All chunks are fine. We ran /wb fill with the force flag to pregenerate the map. At first Dynmap didn't load anything by itself, only paths we visited by hand but our database size has grown to about 16GB. After enabling `migrate-chunks: true`, the Dynmap started to generate tiles but it looks like a maze. (See picture). I read that someone fixed this by using radiusrender, but this can't be the solution right?

Thanks for your help <3
![Image](https://i.imgur.com/izytB4w.png)

**Comment by PseudoKnight** [comment]
That is an experimental feature. Apparently it doesn't work completely. What you should have done is --forceUpgrade your worlds when updating to 1.14.4. This converts all the old minecraft chunks to the new format, and makes it so you don't have to rely on that feature.

Also, that looks cool as hell.

**Comment by mikeprimm** [comment]
Dynmap doesn't fix broken chunk data - it just does a good job showing it off.  WB fill routinely doesn't result in properly generated lighting data, and you'll generally find the data will get fixed by actually using a client to visit areas and drive proper chunk update and migration.
