### ISSUE TITLE
Could not pass event BlockPhysicsEvent to dynmap v3.0-SNAPSHOT-245

### ISSUE THREAD

**Issue by Brokkonaut** [webbukkit/dynmap#2705]
Spamming the console since updating to 1.15.1
https://pastebin.com/raw/RX2pZ6ZQ

**Comment by Brokkonaut** [comment]
This change breaks it: https://github.com/webbukkit/dynmap/commit/2c5a467985f30095400d76d497888825de6258a5

**Comment by ishland** [comment]
Removing api-version in plugin.yml fixes this issue.

**Comment by mikeprimm** [comment]
Revering api-version change - latest SNAPSHOT will have change in a few minutes  (build 246 or later)

**Comment by mikeprimm** [comment]
Try this build https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar

**Comment by ishland** [comment]
Thanks and it works fine for me.

**Comment by mikeprimm** [comment]
I'll probably put new formal release out tomorrow night - reviewing over some other bugs first, but the SNAPSHOT should be OK for folks needing a quick fix.   Are folks seeing the previous problem on Spigot or just Paper?

**Comment by ishland** [comment]
> I'll probably put new formal release out tomorrow night - reviewing over some other bugs first, but the SNAPSHOT should be OK for folks needing a quick fix. Are folks seeing the previous problem on Spigot or just Paper?

This issue affects both Spigot and Paper. I tested on Spigot 1.15.1 and it is also spamming.

**Comment by Remanent** [comment]
Downloaded the snapshot from the above link, and running on spigot, i did not get any spam like i did before using a bucket of water. dynmap build 247. spigot version (from /version) 

CraftBukkit version git-Spigot-2ee05fe-d31f05f (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
