### ISSUE TITLE
Blank map spots

### ISSUE THREAD

**Issue by ionstorm66** [webbukkit/dynmap#2706]
So I started a brand new world and I have blank spots in the map. I have teleported to them and they are created and load fine.

Plugins:
Paper
Worldborder
Dynmap

Ran:
- /wb set 2000
- /wb fill
- /wb fill confirm
- waited for it to complete
- /dynmap fullrender world

Then I tried:
- /dynmap purge world
- /dynmap fullrender world

**Comment by MitchTalmadge** [comment]
WorldBorder leaves me with empty spaces as well. I imagine it's WorldBorder's fault and not Dynmap since a fullrender doesn't do anything about it. I wonder if doing `wb fill 20 208 true` (the last part, `true`, forces rendering of "assumed to be rendered" chunks) would fill in the holes.

**Comment by ionstorm66** [comment]
I have teleported to the chunks and they are rendered. Visiting them and even placing a block to modify them doesn't make any difference for dynmap.

**Comment by Tsoccerguy3** [comment]
mentioned here https://github.com/webbukkit/dynmap/issues/2689#issuecomment-568284124

**Comment by ionstorm66** [comment]
> mentioned here [#2689 (comment)](https://github.com/webbukkit/dynmap/issues/2689#issuecomment-568284124)

I am still on 1.14.3.

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2485
