### ISSUE TITLE
How Do I render the whole map completely without flying ?

### ISSUE THREAD

**Issue by lukaplayz** [webbukkit/dynmap#2707]
How Do I render the whole map completely without flying ?Please leave some suggestions below 
P.S (I am doing /wb fill command and I don't know if it will work) Someone help me

**Comment by lukaplayz** [comment]
wait so do i do /wb fill and then /dynmap fullrender @SimisFul

**Comment by galacticwarrior9** [comment]
You do /wb fill, wait for the entire map to generate and then do /dynmap fullrender. It's that simple. You should close this issue.
