### ISSUE TITLE
Retain viewer configuration between sessions

### ISSUE THREAD

**Issue by DaniDipp** [webbukkit/dynmap#2713]
It would be cool if dynmap would save the viewer configuration (Enabled/disabled categories, selected map, zoom level, etc.) to `localStorage` or something so that the users don't have to adjust this to their individual preferences every time they look at the dynmap.

**Comment by High-village** [comment]
That would help a lot and let users customize their dynmap experience.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
