### ISSUE TITLE
Dynmap webview cannot retreive configuration

### ISSUE THREAD

**Issue by mmuziek** [webbukkit/dynmap#2718]
hey there.
i just updated to Dynmap for 1.15.1
i also updated the webfiles and its on mysql mode
however everything runs except for the web part where it always trows
https://prnt.sc/qe8v66
in the error log it shows:
https://prnt.sc/qe8vjn

nothing has changed other then the update.
i tried removing all webfiles and reuploading them
i purched the worlds see if that helps.
i tried fullrendering 

im a bit out of options. did anything change in the webscripts?

**Comment by mmuziek** [comment]
ok i might have fixed it however now it doenst load due to mismatch?
https://prnt.sc/qe8w6y

 the files are new directly from dynmap folder?

**Comment by JochemKuijpers** [comment]
Have you tried following the on-screen instructions? 
Hold shift while you reload the page.

If so, are you using a more advanced web setup? Did you update the web file to synchronize with those in the plugins folder?

**Comment by mmuziek** [comment]
well i worked hard on finding the answer i switched like 10 times i restarted 10 times and installed 10 times and out of the blue it finally works. so i have no clue where it started

**Comment by JochemKuijpers** [comment]
The reason it worked now is probably because your local cache finally expired. 

The message told you to force reload. Did you try that? Did you install the web files to the right directory? Because if you did all of that and that didn't work, this is a bug. But if you failed to follow the instructions, this should be closed indeed.

**Comment by mmuziek** [comment]
i did refresh my cache multiple times however it didnt work so well its
solved for me tho.

Op di 24 dec. 2019 om 15:03 schreef Jochem Kuijpers <
notifications@github.com>:
