### ISSUE TITLE
Cant connect to website

### ISSUE THREAD

**Issue by averwhy** [webbukkit/dynmap#2721]
I use a host, Pebblehost. Server version is craftbukkit 1.8.8. Server IP is 54.39.239.247:25575. I goto https://54.39.239.247:8123/ and it doesnt work. I also tried https://54.39.239.247:25575:8123/ but it ends up in a google search. Is it because of the port?

**Comment by BadgerCode** [comment]
The address will be http://54.39.239.247:8123
Not HTTPs.
IP addresses can only have one port after them.

I can see that your port 8123 isn't open - https://www.yougetsignal.com/tools/open-ports/

Follow this guide for your host
https://help.pebblehost.com/en/article/how-to-set-up-dynmap-j8001n/
