### ISSUE TITLE
DYNMAP: TILE/CHUNK LIGHTING ERROR

### ISSUE THREAD

**Issue by lukaplayz** [webbukkit/dynmap#2723]
Here is the picture of my map on dynmap and it has this weird lighting.So at first when i spawned in to the world i loaded most of the chunks until i loaded the whole world by worldborder. Somebody please tell me If there is a way for me to fix these lights or something.
![03A81A27-45E4-4418-A8E6-7AC1C7A9F655](https://user-images.githubusercontent.com/59068185/71374105-71e70680-2587-11ea-8197-cc05bd57b4fa.png)

Here is the website map.heavenlands.net

**Comment by lukaplayz** [comment]
Ok the website is back up now you can now view it : website map.heavenlands.net

**Comment by FedUpWith-Tech** [comment]
This is fixed in a later release
