### ISSUE TITLE
Dynmap Fullrender not rendering all of the map.

### ISSUE THREAD

**Issue by LB45440078L** [webbukkit/dynmap#2727]
I have a 1.15.1 server with latest dynmap , and when i start a fullrender , with /dynmap fullrender italia:flat , it starts , does about 700 tiles and says its finished, while in reality it the map is much more bigger and it's not finished at all.
![image](https://user-images.githubusercontent.com/29604693/71449684-85929880-2752-11ea-8c44-c170434a4505.png)
![image](https://user-images.githubusercontent.com/29604693/71449687-93481e00-2752-11ea-8b7c-1eb186fdad69.png)

**Comment by Cannafix** [comment]
is your chunk's generated??
They need to be present for dynmap to render them.

**Comment by LB45440078L** [comment]
If you mean by walking and generating chunks, no I haven't explored the map.

**Comment by Cannafix** [comment]
yes that is what i mean. 
you can use this plugin to make a worldborder and pregenerate the chunk's
https://www.spigotmc.org/resources/worldborder.60905/
It may not work on 1.15.1 yet

then do a full dynmap render when its done. but beware that this can take a long time (more that 24 hours) depending on the world size and dynmap configuration.

**Comment by LB45440078L** [comment]
> 
> 
> yes that is what i mean.
> you can use this plugin to make a worldborder and pregenerate the chunk's
> https://www.spigotmc.org/resources/worldborder.60905/
> It may not work on 1.15.1 yet
> 
> then do a full dynmap render when its done. but beware that this can take a long time (more that 24 hours) depending on the world size and dynmap configuration.

yeah that's a little issue... I may just wait for that plugin to support 1.15. But why dynmap doesen't have a built-in feature like that?

**Comment by nkappler** [comment]
why would you want this? there are biome maps for this...
