### ISSUE TITLE
Does fullrender overwrite?

### ISSUE THREAD

**Issue by Sikatsu** [webbukkit/dynmap#2728]
Does a fullrender overwrite existing tiles or will it only add up to the database?

I extended my worldborder a bit and would like to render those parts now with dynmap. Should I first purge the world and then do a fullrender, or can I do a fullrender and it just updates the existing tiles?

(Before I have like an old and new layer in my database and it becomes too huge)

**Comment by Technoguyfication** [comment]
Any time you re-render tiles that are already rendered, it overwrites the old tiles.
