### ISSUE TITLE
Dynmap doesn't work with Cloudflare Proxy with Flexible SSL

### ISSUE THREAD

**Issue by viet** [webbukkit/dynmap#2729]
Here is my Dynmap link for my server: https://map.mc.lectron.com

I set the Dynmap port to 80, and use Cloudflare Flexible SSL to proxy to my server at port 80, so that it still shows up as HTTPS on my website.

However, it now shows a blank page. Can you please help?

**Comment by MAXOUXAX** [comment]
Almost every ressources are returning a 404.
https://share.lyorine.com/files/6sWJZR9aQ30ouDiwcxEzC4Ln1.png

**Comment by viet** [comment]
Yeah that's when it was in https://

If you access via http://, then everything works fine.

The https is supposed to work.

Maybe you can help set everything to // instead of //http

**Comment by viet** [comment]
?

**Comment by viet** [comment]
Can you fix it?

**Comment by johncsuti** [comment]
Works fine for me under full (strict) you will need to have a trusted certificate on your website, or have a origin certificate. I would recommend doing this as this isn't a Dynmap issue. Its a problem with your setup.

**Comment by johncsuti** [comment]
Do you use Apache, and have access to host on port 443?

**Comment by viet** [comment]
I don't use Apache.

I do have access to host on port 443, however I'm currently using that port for my other plugin (Plan Analytics)

**Comment by johncsuti** [comment]
What is your hosting provider? The way you will need to set it up is by having all the files needed as a reverse proxy on your web server so then cloud flare can serve it. Assuming you are on the free plan.

**Comment by johncsuti** [comment]
If you would like/have contact me via discord at johncsuti#0001
Send me a friend request and we can talk quicker.

**Comment by johncsuti** [comment]
This can be closed i will be helping @viet with this issue
