### ISSUE TITLE
Render issues modded stairs + forestry

### ISSUE THREAD

**Issue by JonathanPlovie** [webbukkit/dynmap#2731]
Hello all

I'm running a fairly heavy, private selfmade modpack for 1.12.2 and I love to have an overview of my world using Dynmap. Currenty using Dynmap-3.0-beta-9-forge and DynmapBlockScan-3.0-beta-1-forge.

Most of the things render and I'm overall very happy, however, stairs that aren't vanilla are rendered badly eg. they appear as a 'corner' stair instead of the actual rotation, sometimes the rotation is just completely wrong and this breaks the smooth appearance of buildings in the world. For me it's so bad that I even refrain from using those blocks altogether because it looks hideous on the Dynmap.

The second part is related to forestry planks. Some things render - apiary, and some other things - but anything related to trees don't render at all, instead becoming invisible and leaving behind some black shapes. Is there any way to fix this? There are no planks, no wood blocks, no default leaves or stairs...

**Comment by FedUpWith-Tech** [comment]
This should be in the dynmap-blockscan issue tracker
