### ISSUE TITLE
Ladders facing west and north are rendering facing east.

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#2732]
![ladder](https://user-images.githubusercontent.com/25720855/71533306-e905fd00-28ef-11ea-8878-f2a3cf6f6183.png)

Dynmap-3.0-beta-9-spigot

The two visible ladders in this image are actually attached to the dirt towers next to them and are facing west and north in game.  Dynmap is rendering them facing east.  Ladders facing east and south in game are rendered facing the right way.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
