### ISSUE TITLE
Dynmap Facing West

### ISSUE THREAD

**Issue by Deltros52** [webbukkit/dynmap#2734]
Hi, my Dynmap is facing west and I can't fix it.
Any idea what I can do to fix this? I already looked around online but nothing I found worked.
Thanks.

**Comment by mikeprimm** [comment]
Not sure I understand - can you include picture of what you mean?   If you want to alter the orientation of the rendered maps, you can alter which 'perspective' is used and re-render them - see https://github.com/webbukkit/dynmap/wiki/HD-Map-Configuration and https://github.com/webbukkit/dynmap/wiki/Configuring-Maps-and-Worlds-using-dmap
