### ISSUE TITLE
[question] mysql vs. file storage

### ISSUE THREAD

**Issue by lrmtheboss** [webbukkit/dynmap#2736]
what are the pros and cons of using MySQL instead of files for map storage?

**Comment by Doritanh** [comment]
MySQL will use less storage space since it's more optimized.
Also, if you store your map on mysql, you can uninstall dynmap et reinstall it again, all data will be kept :smile:

**Comment by SiebeBaree** [comment]
+ MySQL is much faster to load in than SQlite
