### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by mortenmoulder** [webbukkit/dynmap#2741]
This is a feature request and not a bug report.

Are there any plans for supporting HTTP/2? Since browsers have a limit on amount of files allowed per second to be transfered, we're limited to about 5 or 10 transfers per second. Since all tiles are loaded as images, the previous images have to be loaded before it can load new ones. With h2 aka HTTP/2, there is parallelism.

I'm not a Java developer by any means, and I wouldn't even know where to start. I'm using Forge 1.12.2 by the way.

**Comment by mikeprimm** [comment]
I'm definitely looking to update the internal web server to something that supports HTTP/2, as it is based on a quite dated version of Jetty (8.6, IIRC).
Independent of that, as always, an external web server (such as Apache or Nginx) can be used, and all recent versions of those include such support.

**Comment by DylanDelobel** [comment]
I would love to see this feature!

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
