### ISSUE TITLE
Dynmap Factions Task 66 Error

### ISSUE THREAD

**Issue by Lazulio** [webbukkit/dynmap#2742]
Plugin was working fine, suddenly factions regions would not update. Attempted to reinstall both dynmap and dynmap factions (latest versions). Now receiving this error: 

`05.01 21:26:20 [Server] WARN [Dynmap-Factions] Task #66 for Dynmap-Factions v0.91-41 generated an exception
05.01 21:26:20 [Server] INFO java.lang.NullPointerException: null
05.01 21:26:20 [Server] INFO at java.lang.String.replace(String.java:2240) ~[?:1.8.0_191]
05.01 21:26:20 [Server] INFO at org.dynmap.factions.DynmapFactionsPlugin.formatInfoWindow(DynmapFactionsPlugin.java:207) ~[?:?]
05.01 21:26:20 [Server] INFO at org.dynmap.factions.DynmapFactionsPlugin.handleFactionOnWorld(DynmapFactionsPlugin.java:312) ~[?:?]
05.01 21:26:20 [Server] INFO at org.dynmap.factions.DynmapFactionsPlugin.updateFactions(DynmapFactionsPlugin.java:507) ~[?:?]
05.01 21:26:20 [Server] INFO at org.dynmap.factions.DynmapFactionsPlugin.access$000(DynmapFactionsPlugin.java:49) ~[?:?]
05.01 21:26:20 [Server] INFO at org.dynmap.factions.DynmapFactionsPlugin$FactionsUpdate.run(DynmapFactionsPlugin.java:133) ~[?:?]
05.01 21:26:20 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
05.01 21:26:20 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
05.01 21:26:20 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
05.01 21:26:20 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
05.01 21:26:20 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
05.01 21:26:20 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
05.01 21:26:20 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

**Comment by FedUpWith-Tech** [comment]
This should be on the dynmap-factions issue tracker
