### ISSUE TITLE
Dynmap Web Map not showing our Map

### ISSUE THREAD

**Issue by evelyegt** [webbukkit/dynmap#2743]
I just started using Dynmap, so i might be missing some things. But I used the link given in the description along with our IP address for the server. When I load in, it doesn't shown my servers map, it shows a different servers map. I don't know if the 8123 numbers in the link should be different. But it is not working.

You can look at the map 
http://hellbringer.apexmc.co:8123/ 

The render should have the earth map on it. But it has someone else's map. If anyone can shed some light on this, that would be epic.

**Comment by Arkieon** [comment]
Oh wait, is it basic settings.
oof, i might have figured it out

**Comment by Aquerr** [comment]
I am not an expert on Dynmap but I can try to help.

When You start a server with Dynmap then by default the map can be accessed by going on url **0.0.0.0:8123** or **localhost:8123**.

Port 8123 can be changed in the dynmap config file. 

If the map that is showing on the website is not yours then maybe some other server (hosted on that domain) is already using port 8123. 

I would recommend trying to change the port in the config (to 8124 for example) and see if you will get a different map on the new port.

**Comment by evelyegt** [comment]
we figured it out. turns out i was using the server address instead of the ip, therefor it wasnt loading the correct map.
