### ISSUE TITLE
Not possible to remove /dynmap hide or /dynmap show permissions from users

### ISSUE THREAD

**Issue by Sentokoo** [webbukkit/dynmap#2744]
I'm using the most recent version of Dynmap and Luckperms 5.0.39 on a Paper 1.15 server.

I set the dynmap.hide, dynmap.hide.self, dynmap.hide.others permission nodes all to false with the permissions plugin. Even when dynmap.* is set to false, all users are still able to use the /dynmap hide and /dynmap show commands.

**Comment by Lud00** [comment]
Did you check with the permission plugin support?
This is not a dynmap issue.
