### ISSUE TITLE
Is my dynmap compromised?

### ISSUE THREAD

**Issue by GeneralDarian** [webbukkit/dynmap#2750]
Hi, for some reason my dynmap is rendering a completely different world, and the browser title has been changed into an insulting message. I have no idea why this is happening and I'm wondering if the world might have been compromised.

I own a minecraft server which is advertised on a (fairly large) discord server. I already changed my password for the console just in case someone is accessing it, but reinstalling dynmap does not fix this issue. What should I do?

**Comment by Lud00** [comment]
Look like someone hacked your config file.
Change the OS password or FTP.

**Comment by johncsuti** [comment]
Change all password's then change the config back to the way you had it. Also choose a better password this time since it seemed to be guessed and/or brute forced.
