### ISSUE TITLE
Base64 Error - Breaks Most of Plugin

### ISSUE THREAD

**Issue by Insilvon** [webbukkit/dynmap#2753]
Hi there, Running v3.0 beta 1 on Paper 1.15.1, build 50. 
I'm having a recurring issue with dynmap where the console gets hit with java errors like the following:
https://pastebin.com/MihB8Phg

All errors recently have had that same core line: **_Length of Base64 encoded input string is not a multiple of 4._** 

This has impacted player joining, removing players from the map on disconnect, and now marker management.

Let me know if there's more info I can provide!

**Comment by mpdk** [comment]
You do know there is a Beta9 that works.

http://mikeprimm.com/dynmap/builds/dynmap/Dynmap-3.0-beta-9-spigot.jar

**Comment by Insilvon** [comment]
Updated to this build several days ago and the above issue persists.

**Comment by Insilvon** [comment]
Bump - 
Continuing to get this issue with snapshots, Paper 1.15.2. Player icons on Dynmap are worthless. 
Full reinstalls of the plugin with new databases aren't changing anything either.
https://hastebin.com/gotepujoyu.apache

**Comment by Insilvon** [comment]
Continuing to bump - same issue on 1.16.1.

**Comment by FedUpWith-Tech** [comment]
Your hastebin link is dead- can you update this issue with a new error, I haven't seen anyone else with a similar error
