### ISSUE TITLE
Exception during render job

### ISSUE THREAD

**Issue by TheMDev** [webbukkit/dynmap#2754]
[Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] Exception during render job: world=world, map=org.dynmap.hdmap.HDMap@a0cf80a
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]: java.lang.ArrayIndexOutOfBoundsException: 1048575
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.forge_1_12_2.ChunkSnapshot.<init>(ChunkSnapshot.java:229)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.forge_1_12_2.ForgeMapChunkCache.prepChunkSnapshot(ForgeMapChunkCache.java:1241)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.forge_1_12_2.ForgeMapChunkCache.readChunks(ForgeMapChunkCache.java:1407)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.forge_1_12_2.DynmapPlugin$ForgeServer.createMapChunkCache(DynmapPlugin.java:887)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.MapManager$FullWorldRenderState.processTile(MapManager.java:685)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.MapManager$FullWorldRenderState.run(MapManager.java:644)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1.run(MapManager.java:193)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:209)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Dynmap Render Thread/INFO] [STDERR]: [org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$1:run:196]:   at java.lang.Thread.run(Thread.java:748)

**Comment by FedUpWith-Tech** [comment]
This is fixed on a later release
