### ISSUE TITLE
Dynmap does not work

### ISSUE THREAD

**Issue by jaevibing** [webbukkit/dynmap#2757]
I set up Dynmap on my Paper 1.14.4 server and when I go to the address it says to go to (serverip:8123) it does not have the dynamp there, instead a connection issue. Have I done something wrong?

**Comment by johncsuti** [comment]
What is the connection issue show a screen shot. Also check if the port is open.

**Comment by mpdk** [comment]
If your renting a server, they need to open your port 8123 for you. If your hosting it on your own, you need to portforward your own router. Or if it's on your own machine, you would use 127.0.0.1:8123.
