### ISSUE TITLE
1.15.2 snapshot breaks my dynmap. 

### ISSUE THREAD

**Issue by lukeeexd** [webbukkit/dynmap#2762]
After updating to 1.15.2 and the 1.15.2 dynmap snapshot, my dynmaps are blank. I then tried the creative server but left the window open, after updating etc I refreshed and a message at the top of the window said https://i.tws.gg/tcXApk1W9B.png Here is a pic of the dynmap https://i.tws.gg/qwUJl0sQ2o.png

When I Downgrade to 1.15.1 and the 1.15 dynmap it works fine

**Comment by Relaxing9** [comment]
Would be helpful if you could provide what error message you are experiencing exactly. You also didn't provide server version and type, but I would assume it would be the latest Spigot version?

**Comment by lukeeexd** [comment]
> Would be helpful if you could provide what error message you are experiencing exactly. You also didn't provide server version and type, but I would assume it would be the latest Spigot version?

I cant get the error to show again. Using Paper

**Comment by Relaxing9** [comment]
Did you try to run a new render on your worlds? (purge old ones get a new one?)

**Comment by lukeeexd** [comment]
> Did you try to run a new render on your worlds? (purge old ones get a new one?)

My dynmap filesize is ~400gb I am not purging and rendering again lol..

I shouldnt need to do that anyway

**Comment by lukeeexd** [comment]
This also happens with the release on spigot. I have tried purging the world and rendering again. Purging the world then deleting the files in /web/tiles and rendering again. None of the mentioned works

**Comment by icemagetv** [comment]
Are you using Beta 10 (released yesterday) - https://dynmap.us/builds/dynmap/

I had a similar issue with my 1.15.2 paper server - updating to Beta 10 seemed to fix it but I've not checked recent renders.

**Comment by lukeeexd** [comment]
> Are you using Beta 10 (released yesterday) - https://dynmap.us/builds/dynmap/
> 
> I had a similar issue with my 1.15.2 paper server - updating to Beta 10 seemed to fix it but I've not checked recent renders.

I am yes

**Comment by lukeeexd** [comment]
@mikeprimm Any ideas?

**Comment by icemagetv** [comment]
Looking at the screenshots, it looks like the webserver files have to be updated.
If you don't have the webserver files, you can extract them from the JAR for the mod under the Extracted\Web directory.

I don't think Dynmap will update the web files if you've relocated them outside of the default directory.

**Comment by lukeeexd** [comment]
> Looking at the screenshots, it looks like the webserver files have to be updated.
> If you don't have the webserver files, you can extract them from the JAR for the mod under the Extracted\Web directory.
> 
> I don't think Dynmap will update the web files if you've relocated them outside of the default directory.

I use the internal webserver not an external one. So all the files are inside the dynmap folder in plugins so they are not located outside the default directory

**Comment by icemagetv** [comment]
I'm using Beta 10, and you're using the snapshot.  Have we tried Beta 10?  I'm looking at the snapshot to see if my amateur eyes spot anything wrong.

**Comment by lukeeexd** [comment]
> I'm using Beta 10, and you're using the snapshot. Have we tried Beta 10? I'm looking at the snapshot to see if my amateur eyes spot anything wrong.

Yep, when I updated to 1.15.2 i used beta 10. Then I got the issue, back to 1.15.1 and beta9 and it works. I'm gona try the files in extracted/web

**Comment by lukeeexd** [comment]
Deleted the web folder, went to 1.15.2 and beta 10 and still blank. 

`Mixed Content: The page at 'https://tws.gg/cr-map' was loaded over HTTPS, but requested an insecure resource 'http://tws.gg/index.html'. This request has been blocked; the content must be served over HTTPS.` shows in f12

**Comment by icemagetv** [comment]
we got some headway - give me a minute and leave that up.

**Comment by lukeeexd** [comment]
will do, appreciate you trying to help as I'm out of ideas and was gona just stay on 1.15.1

**Comment by lukeeexd** [comment]
Also, https://tws.gg/c-map is the map which it pulls the iframe from just redirects to my websites index. But you can see here https://tws.gg/v-map/ for the survival server it doesnt, https://tws.gg/map

**Comment by icemagetv** [comment]
It looks like the map is still working, just not from the iframe - https://tws.gg/c-map/index.html works, but the https://tws.gg/c-map/ isn't redirecting correctly... why an update is breaking that, I'm not sure.

**Comment by lukeeexd** [comment]
Oh wow, now we know the issue. But yeah why beta 10 does that and not beta 9 mhmm

**Comment by lukeeexd** [comment]
Apparently its because of `Update of internal web server to Jetty 9.4 (thanks to Ry0taK!)` which is in beta10 and not beta9

**Comment by FedUpWith-Tech** [comment]
Looking back this issue seems to be a http iframe inside an https webpage which isn't supported under most webservers or modern browsers.  I'm going to close this as I don't believe its relevant anymore but if I am wrong please update me
