### ISSUE TITLE
Lighting Issue - 1.15.1

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#2763]
Hey!
I've recently updated my server to 1.15.1 and I wanted to fix our online map. When the full render started, I noticed a weird issue/feature. Corals and everything beneath water is now visible and it looks rather strange. I really liked the way it looked previously, so if it's not a huge issue, a setting/toggle feature would be really appreciated. 

I am not exactly sure if this is intended actually. It seems a bit buggy and shipwrecks and other underwater structures can be found really easily this way which may be a problem.
https://i.imgur.com/c4V4jrs.png
https://i.imgur.com/903x9k5.png

**Comment by ghost** [comment]
Use the plugin LightCleaner to cleanup de lighting in your world.
https://www.spigotmc.org/resources/light-cleaner.42469/ (Works in 1.15.2)
I explained it here to another user who had this problem:
#2689

**Comment by seema84** [comment]
thats not a shadow bug that lightcleaner can be fixed
should be fixed in the new beta 10

**Comment by ghost** [comment]
Have you tried it?

**Comment by seema84** [comment]
yes

**Comment by seema84** [comment]
see here https://github.com/webbukkit/dynmap/commit/e74741b7bd965ef36fee581ca18035fda0a9fbf3
