### ISSUE TITLE
302 redirect from "/" to "/index.html" is new behavior that can partially break some configurations

### ISSUE THREAD

**Issue by ReadyPlayerEmma** [webbukkit/dynmap#2765]
**Known affected versions:**
beta-10

**Previous (1.15.1 version) behavior (desired):**
Directly returns the index.html page even on the "/" path.

**Current undesired behavior:**
If the root path on the builtin webserver is accessed, it will return a 302 redirect to the `/index.html` path. The full URL passed in location header for the 302 response was set to `http://<requests-host-header>/index.html`.

**Notes:**
I use Cloudflare in front of the webserver. I rewrite the request so that from the user perspective they are accessing over HTTPS on my domain. On the backend it accesses http, but on a different domain. No direct access is allowed to the configured IP or port except through Cloudflare.

Technically, I think this new behavior would also break redirects when accepting traffic on the IP itself and not using port 80, since the port is not preserved in the location header.

 **Workaround:**
I manually configured Cloudflare to intercept requests to the "/" path and rewrite them to "/index.html" using the normal protocol and domain that my users are accessing.

**Possible (untested) solutions:**
1. I think it would break less situations if when it constructed the location response header, it added the configured port appended to the domain that was in the host header.

2. Alternatively, and preferred for me personally, allow the full root URL (with protocol, domain, and port) to be configured so that the config could give the webserver more information about how user's were accessing it, allowing any redirects to access using the correct protocol, domain, and port for that deployment.

3. Both. Maybe set the default behavior to be the first solution, and also allow a configured override as described in the second solution?

4. Revert to the old behavior.

**edit:** clarified after further testing on the old version.

**Comment by DmitryRendov** [comment]
the same for me, beta10 has some breaking changes for my reverse proxy as well:
```sh
        ProxyRequests off
        ProxyPass "/"                    "http://127.0.0.1:8124/" retry=0
        ProxyPassReverse "/"             "http://127.0.0.1:8124/"
```
Now it constantly redirects to /index.html and looks ugly in a browser. Any workaround to solve that using Apache mod_rewrite?

**Comment by lukeeexd** [comment]
Same issue here

**Comment by ReadyPlayerEmma** [comment]
> Now it constantly redirects to /index.html and looks ugly in a browser. Any workaround to solve that using Apache mod_rewrite?

@DmitryRendov
I believe this might work for mod_rewrite to accomplish what I did with Cloudflare:
```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^/?$ "/index.html"
```

**Comment by mikeprimm-triva** [comment]
Check out dev build of PR - https://dynmap.us/builds/dynmap/Dynmap-3.0-SNAPSHOT-spigot.jar
