### ISSUE TITLE
Glitchy rendering when chunks just beyond a fullrender got created

### ISSUE THREAD

**Issue by masterX244** [webbukkit/dynmap#2766]
When a player explores just beyond a fullrendered section there are map-gaps
![grafik](https://user-images.githubusercontent.com/1544922/73119487-fb14a300-3f62-11ea-995f-fd5972026d2c.png)
Tested on 1.15.1 spigot with 3.0-Beta 9

**Comment by ekzhang** [comment]
Can confirm this happens in the latest version for 1.15.2.

**Comment by FedUpWith-Tech** [comment]
maybe related to #2485

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2485
