### ISSUE TITLE
This site cant be reached!

### ISSUE THREAD

**Issue by antri1** [webbukkit/dynmap#2768]
I have checked many tutorials, and done everything! But when I try to go to the website:

158.69.123.184:7098

It just says: This site cant be reached!
I sent the link to many of my friends, and they all said that it didn't work for them.

**Comment by baconwaifu** [comment]
Check your port forwarding, since dynmap uses a different port to base minecraft.
if this is a managed host (ie: you rent a minecraft instance and can only install plugins) then you're out of luck.
