### ISSUE TITLE
Adding an Issue Template

### ISSUE THREAD

**Issue by baconwaifu** [webbukkit/dynmap#2771]
I've noticed a lot of "tech support" issues that never get solved or closed, which only serve to bury legitimate bugs.
An issue template combined with some moderation should probably cut down on this.

something like this would make a good starting template:
```
When posting an issue, please include the following information, issues without it may be deleted:
- A *clear and concise title* describing the issue.
- Dynmap version
- Minecraft version
- Plugin API (Spigot/Bukkit, Forge, etc.)
- Log Files (as an attachment, not inline!)
- Dynmap Configuration (Tile Storage, frontend used, etc.)
- A list of all plugins and mods installed

```

**Comment by FedUpWith-Tech** [comment]
This is in the works, closing this issue now and will link the new page when its created
