### ISSUE TITLE
1.15.2 fullrender isnt rendering anything

### ISSUE THREAD

**Issue by SokuNoWa** [webbukkit/dynmap#2772]
hey guys I have done /wb fill and when i do fullrender is just says 100 tiles rendered and then says render complete. I am on 1.15, what is going on?

**Comment by 32Mikey** [comment]
This is happening to me as well. I was told it's just a bug related to 1.15.2. You'll just have to wait for a fix. Hopefully, me replying will bump it up and get this issue some attention considering fully rendering a map is literally impossible if fullrender doesn't work.

**Comment by ghost** [comment]
me too!

**Comment by mvcutter** [comment]
Same!

**Comment by snail-world** [comment]
Same!

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2760
fixed in a later version
