### ISSUE TITLE
Dynmap not working with 1.15.2

### ISSUE THREAD

**Issue by EsserGaming** [webbukkit/dynmap#2773]
Hello, I am wondering why Dynmap isn't working with 1.15.2. It should support it. It also might be the Protocol Support plugin. (https://protocol.support)

Here is a list of my plugins:

> [Server thread/INFO]: Plugins (38): LuckPerms, PluginConstructorAPI, WorldEdit, AntiCreeper, AutoBroadcast, UltimateAutoRestart, ClearLag, PlugMan, AdminTools, AdvancedBan, Goawayphantom, StaffChatPlus, ProtocolLib, OldCombatMechanics, SignEdit, FastLeafDecay, CompleteRecipes, AntiCropTrample, ServerRestorer, Vault, ProtocolSupport, ChestShop, BlockVersion, Essentials, VeinMiner, Matrix, PlotSquared, Multiverse-Core, MyDog, DiscordSRV, Multiverse-Inventories, TAB, ServerSigns, SuperVanish, GriefPrevention, EssentialsSpawn, Wild, Harbor

**Comment by LigerXT5** [comment]
What is the error when you try to start with dynmap?

**Comment by EsserGaming** [comment]
lol i just updated the version and it works now. XD

**Comment by johncsuti** [comment]
@EsserGaming Why don't you close this issue then?
