### ISSUE TITLE
Setting Spawn Near Vanilla Border Causes Border To Show Incorrectly on Dynmap

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#2774]
I have my spawn only a hundred or so blocks away from the hard limit of 30 million for the world border. The vanilla border makes a rectangular shape that isn't a square when setting the border size to be greater than what the hard limit allows.

To help explain what I'm talking about, here's my border calculations back when I had the World Border plugin setup to complement the vanilla border (that plugin had a different bug that made parts of the nether unbreakable inside the border, so I don't use it anymore).

The vanilla border itself is rectangular. Dynmap, shows the border as square, but it bypasses the hard limit of the border and marks the edge of the border far beyond the 30 million blocks (as if the hard limit didn't exist). The other corner of the border shows in the correct location, but the hard limit side does not show correctly.

```
Overworld
---------
Corner 1: 29999983 29999983
Corner 2: 29974322 29974564
Spawn: 29999322 29999564

Overworld Center
---------
Corner 1: 29999983 29999983
Corner 2: 29974322 29974564
X: 25661 Y: 25419
X/2: 12830.5 Y/2: 12709.5
Center: 29987152.5 29987273.5
```

**Comment by FedUpWith-Tech** [comment]
can you send screenshots of the exhibited behavior and what you expect the behavior to be?
