### ISSUE TITLE
hideores not working

### ISSUE THREAD

**Issue by SkuadMC** [webbukkit/dynmap#2778]
Trying to use the hideores: option in configuration.txt and it just doesn't do anything. Restarting the server doesn't make it work, reloading the plugin does nothing in regard to this option. 

I'm currently using Dynmap 3.0-beta-10-257 on Paper-89 for 1.15.2.

**Comment by masterX244** [comment]
Already rendered tiles don't get a update unless you force a rerender or something changes in the chunk. run a ```/dynmap fullrender world``` to force a rerender

**Comment by emiliogon** [comment]
This is also not working for me in v3.1-beta-1, despite ``hideores: true`` and several map purges and fullrenders.

![Screen Shot 2020-07-03 at 10 58 58](https://user-images.githubusercontent.com/21245821/86480576-45712b80-bd1c-11ea-816e-a6ebaabddb3d.png)

**Comment by emiliogon** [comment]
After some other configuration changes, ores are now hidden.  This may have to do with running ``migrate-chunks: true`` once.
