### ISSUE TITLE
1.15.1 Not Rendering anything

### ISSUE THREAD

**Issue by SokuNoWa** [webbukkit/dynmap#2782]
Hi, whenever i try to render on 1.15.1 it renders some of the area and then it just stops. when i tried to purge the map and tried again, it rendered the same area and it stops again. pls help

Edit: I have switched to spigot 1.15.2 in hope of it fixing, im using dynmap 3.0 snapshot it says stuff like 100 tiles rendered and so on till it gets to about 1100 and then it says its done.

**Comment by snail-world** [comment]
yes. my 1.15.2 server also does this.

**Comment by snail-world** [comment]
i've already used /wb fill but it still doesn't render anything

**Comment by SkytAsul** [comment]
Same... Fullrender only renders a little area, and radiusrender just doesn't work at some places.
