### ISSUE TITLE
Stops working after awhile

### ISSUE THREAD

**Issue by cinimodphoto** [webbukkit/dynmap#2783]
So I have had my map pre-generated both flat and surface for just my overworld now going on 2 weeks, everything was fine map looked good, updated when new stuff was placed and showed players and everything worked. Then all the sudden 3 hours ago on 2/6 at 1300 Eastern Time the map page gave me the following error and everyone else too. https://imgur.com/a/he1GPLI  It took removing the jar restart the server then add the jar again restart server and poof fixed it except my map is empty again and needs to be regenerated again which I am doing now.

**Comment by FedUpWith-Tech** [comment]
your web files were deleted. Not sure why this happened to you but dynamp doesn't have the capability to delete the web files. My guess it was due to incorrect permissions allowing write access to the web or a mistype
