### ISSUE TITLE
Legacy Material Support due to missing api-version in plugin.yml

### ISSUE THREAD

**Issue by CraigParton** [webbukkit/dynmap#2784]
Your plugin.yml file needs the following line:
api-version: 1.15

Because it is missing it forces Spigot into legacy material support mode. This isn't a major issue but it's also unnecessary. This debug message was just added in Spigot 1.15.2 and displays on startup because of dynmap:

Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
Legacy plugin dynmap v3.0-SNAPSHOT-257 does not specify an api-version.

I edited plugin.yml in the jar and added the line myself and dynmap works just fine. This really should be added to the main build.

**Comment by ishland** [comment]
This line caused a lot of issue: #2705

**Comment by CraigParton** [comment]
Hmm.. after adding api-version to plugin.yml I did a full map render and there were no errors in the console log. None during the render and none since. I noticed that error was on 1.15.1 and seemed to be on the internal Minecraft Block class. Maybe they've changed something in 1.15.2 that fixed it? I'll keep an eye on the logs and see if I notice any spam.

**Comment by Santobert** [comment]
Is this really fixed? I've noticed the warning about legacy material support with the latest version of papermc and the current v3.1-beta-5. Thanks in advance

**Comment by ThisIsTenou** [comment]
Same here with beta 6.

**Comment by MrDarn** [comment]
Confirmed with Beta 6. Legacy mode due to no API version.
Error:
"Legacy plugin dynmap v3.1-beta6-438 does not specify an api-version."
