### ISSUE TITLE
java.lang.IllegalAccessError: Server crash

### ISSUE THREAD

**Issue by znepb** [webbukkit/dynmap#2785]
I'm getting the error mentioned in the title when I start my server. I'm using a Sponge 1.12.2 server with Dynmap.
[crash-2020-02-08_23.18.19-server.txt](https://github.com/webbukkit/dynmap/files/4175575/crash-2020-02-08_23.18.19-server.txt)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
