### ISSUE TITLE
Standalone configuration does not always generate properly

### ISSUE THREAD

**Issue by zontreck** [webbukkit/dynmap#2787]
If you configure the plugin to not use the internal webserver, so that you could instead use a PHP server that supports SSL for example, the config does not always reliably generate. I found that I had to reboot the server the first time almost 20 times to get the dynmap_config and config.js to populate with configuration. However on reboot it changes something that causes it to reload. But if the config does not auto populate due to the above mentioned bug, then you sometimes will get a reload loop until the config gets properly generated. 

Similar tickets: #1008, #2445. There are probably other similar ones though.

**Comment by FedUpWith-Tech** [comment]
every time I've encountered this its due to permissions issues or config issues. I'm going to close it and watch if other similar issues are reported on recent versions
