### ISSUE TITLE
Crashed: Exception in server tick loop, Minecraft 1.12.2 Forge

### ISSUE THREAD

**Issue by QboiDev** [webbukkit/dynmap#2792]
Dynmap for Forge 1.12.2 was crashed, here are the details

Version: `v3.0-beta-4 for Forge 1.12.2`
Minecraft Version: `1.12.2`
Forge Version: `forge-14.23.5.2847`

Link to crash report:
https://paste.dimdev.org/ifixixuvoy.mccrash

World Type: `Client`
**This happend when loading a world, where with dynmap already played on.**

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
