### ISSUE TITLE
Add Dynmap Beta 3.0 to maven repository

### ISSUE THREAD

**Issue by Articdive** [webbukkit/dynmap#2793]
I would appreciate if The dynmap beta builds (that everyone is using on Spigot/Bukkit for 1.14) could have their APIs and Core uploaded to a maven-repository, I would propose a new repo @ repo.dynmap.us but I don't mind using repo.mikeprimm.com. I could also (if you give me permission @mikeprimm) host it on my own repo @ repo.articdive.de.

**Comment by FedUpWith-Tech** [comment]
They are here https://dynmap.us/builds/dynmap/
