### ISSUE TITLE
(UI) Login button blocked

### ISSUE THREAD

**Issue by YJJcoolcool** [webbukkit/dynmap#2796]
I'm accessing my Dynmap from a Samsung Galaxy S10. The Login button is being blocked by the background for the Chat Requires Login text. Attached is the screenshot.
![Screenshot_20200217-170417_Chrome](https://user-images.githubusercontent.com/39160923/74639116-4871e200-51a8-11ea-8c26-8302e730510c.jpg)

**Comment by FedUpWith-Tech** [comment]
Unfortunately not much development has happened on the web interface so I doubt this will get fixed. I'll leave this open till it does tho

**Comment by generrosity** [comment]
In CSS, .messagelist and .chatinput has a fixed width.

The workaround would be to add some custom CSS to have a enforce a right padding or remove that fixed width or hide elements when they are not needed.

Closing for now, and adding to the Features Megathread so it is not lost if/when the interface update does occur
