### ISSUE TITLE
Webpage Wont load

### ISSUE THREAD

**Issue by waylenwasywas** [webbukkit/dynmap#2797]
I installed dynmap and rendered my world but webpage wont show
17.02 20:20:13 [PebbleHost] Starting server!
17.02 20:20:14 [PebbleHost Loader] -----------------------------------
17.02 20:20:14 [PebbleHost Loader] PebbleHost Server Loader Starting...
17.02 20:20:14 [PebbleHost Loader] The following settings have been detected: RAM: -Xmx4096M, JAR: spigot-1.15.2.jar, SERVERID: 104024, SIZE: 433M
17.02 20:20:14 [PebbleHost Loader] Testing server configuration...
17.02 20:20:14 [PebbleHost Loader] Server loader version: v3.0.2 (using configuration version v1.3.4)
17.02 20:20:15 [PebbleHost Loader] Jar passed checksum check
17.02 20:20:15 [PebbleHost Loader] Jar passed composition check
17.02 20:20:15 [PebbleHost Loader] Jar passed size check
17.02 20:20:15 [PebbleHost Loader] Server passed size check
17.02 20:20:15 [PebbleHost Loader] Server passed file check
17.02 20:20:15 [PebbleHost Loader] Configuring your servers settings...
17.02 20:20:15 [PebbleHost Loader] Server passed all checks, Booting...
17.02 20:20:15 [PebbleHost Loader] -----------------------------------
17.02 20:20:15 [Server] INFO *** Error, this build is outdated ***
17.02 20:20:15 [Server] INFO *** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
17.02 20:20:15 [Server] INFO *** Server will start in 20 seconds ***
17.02 20:20:35 [Server] INFO Loading libraries, please wait...
17.02 20:20:49 [Server] Server thread/INFO Starting minecraft server version 1.15.2
17.02 20:20:49 [Server] Server thread/INFO Loading properties
17.02 20:20:50 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-800b93f-29737cc (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
17.02 20:20:50 [Server] Server thread/WARN Couldn't load server icon
17.02 20:20:50 [Server] INFO java.lang.IllegalArgumentException: Must be 64 pixels wide
17.02 20:20:50 [Server] INFO at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
17.02 20:20:50 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadServerIcon0(CraftServer.java:1721) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
17.02 20:20:50 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadServerIcon0(CraftServer.java:1709) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
17.02 20:20:50 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadIcon(CraftServer.java:825) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
17.02 20:20:50 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.<init>(CraftServer.java:314) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
17.02 20:20:50 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerList.<init>(PlayerList.java:76) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
17.02 20:20:50 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedPlayerList.<init>(SourceFile:14) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
17.02 20:20:50 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:162) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
17.02 20:20:50 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
17.02 20:20:50 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
17.02 20:20:51 [Server] Server thread/INFO Server Ping Player Sample Count: 12
17.02 20:20:51 [Server] Server thread/INFO Using 4 threads for Netty based IO
17.02 20:20:51 [Server] Server thread/INFO Debug logging is disabled
17.02 20:20:51 [Server] Server thread/INFO Default game type: SURVIVAL
17.02 20:20:51 [Server] Server thread/INFO Generating keypair
17.02 20:20:51 [Server] Server thread/INFO Starting Minecraft server on 192.99.38.208:25581
17.02 20:20:52 [Server] Server thread/INFO Using epoll channel type
17.02 20:21:03 [Server] Server thread/WARN Plugin NickNames v2.3 does not specify an api-version.
17.02 20:21:03 [Server] Server thread/WARN Plugin dynmap v3.0-beta-10-257 does not specify an api-version.
17.02 20:21:03 [Server] Server thread/INFO [LuckPerms] Loading LuckPerms v5.0.72
17.02 20:21:04 [Server] Server thread/INFO [NickNames] Loading NickNames v2.3
17.02 20:21:04 [Server] Server thread/INFO [AdvancedTeleport] Loading AdvancedTeleport v5.0.13
17.02 20:21:04 [Server] Server thread/INFO [BlockLocker] Loading BlockLocker v1.7.1
17.02 20:21:04 [Server] Server thread/INFO [dynmap] Loading dynmap v3.0-beta-10-257
17.02 20:21:04 [Server] Server thread/INFO [dynmap] version=git-Spigot-800b93f-29737cc (MC: 1.15.2)
17.02 20:21:07 [Server] Server thread/INFO [dynmap] Unload queue not found - default to unload all chunks
17.02 20:21:07 [Server] Server thread/INFO [dynmap] inhabitedTicks field not found - inhabited shader not functional
17.02 20:21:07 [Server] Server thread/INFO [dynmap] Mod Support API available
17.02 20:21:07 [Server] Server thread/INFO [LuckPerms] Enabling LuckPerms v5.0.72
17.02 20:21:07 [Server] Server thread/INFO __
17.02 20:21:07 [Server] Server thread/INFO | |__) LuckPerms v5.0.72
17.02 20:21:07 [Server] Server thread/INFO |___ | Running on Bukkit - CraftBukkit
17.02 20:21:07 [Server] Server thread/INFO [LuckPerms] Loading configuration...
17.02 20:21:08 [Server] Server thread/INFO [LuckPerms] Loading storage provider... [H2]
17.02 20:21:10 [Server] Server thread/INFO [LuckPerms] Loading internal permission managers...
17.02 20:21:10 [Server] Server thread/INFO [LuckPerms] Performing initial data load...
17.02 20:21:11 [Server] Server thread/INFO [LuckPerms] Successfully enabled. (took 4116ms)
17.02 20:21:11 [Server] Server thread/INFO [BlockLocker] Enabling BlockLocker v1.7.1
17.02 20:21:11 [Server] Server thread/INFO Preparing level "world"
17.02 20:21:12 [Server] Server thread/INFO Reloading ResourceManager: Default, bukkit
17.02 20:21:14 [Server] Server thread/INFO Loaded 6 recipes
17.02 20:21:16 [Server] Server thread/INFO -------- World Settings For [world] --------
17.02 20:21:16 [Server] Server thread/INFO Cactus Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Cane Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Melon Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Mushroom Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Pumpkin Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Sapling Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Beetroot Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Carrot Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Potato Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Wheat Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO NetherWart Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Vine Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Cocoa Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Bamboo Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO SweetBerry Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Kelp Growth Modifier: 100%
17.02 20:21:16 [Server] Server thread/INFO Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
17.02 20:21:16 [Server] Server thread/INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
17.02 20:21:16 [Server] Server thread/INFO Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
17.02 20:21:16 [Server] Server thread/INFO Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
17.02 20:21:16 [Server] Server thread/INFO Max TNT Explosions: 100
17.02 20:21:16 [Server] Server thread/INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
17.02 20:21:16 [Server] Server thread/INFO Experience Merge Radius: 3.0
17.02 20:21:16 [Server] Server thread/INFO Mob Spawn Range: 6
17.02 20:21:16 [Server] Server thread/INFO View Distance: 8
17.02 20:21:16 [Server] Server thread/INFO Allow Zombie Pigmen to spawn from portal blocks: true
17.02 20:21:16 [Server] Server thread/INFO Item Despawn Rate: 6000
17.02 20:21:16 [Server] Server thread/INFO Item Merge Radius: 2.5
17.02 20:21:16 [Server] Server thread/INFO Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
17.02 20:21:16 [Server] Server thread/INFO Zombie Aggressive Towards Villager: true
17.02 20:21:16 [Server] Server thread/INFO Nerfing mobs spawned from spawners: false
17.02 20:21:17 [Server] Server thread/INFO -------- World Settings For [world_nether] --------
17.02 20:21:17 [Server] Server thread/INFO Cactus Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Cane Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Melon Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Mushroom Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Pumpkin Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Sapling Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Beetroot Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Carrot Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Potato Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Wheat Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO NetherWart Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Vine Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Cocoa Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Bamboo Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO SweetBerry Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Kelp Growth Modifier: 100%
17.02 20:21:17 [Server] Server thread/INFO Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
17.02 20:21:17 [Server] Server thread/INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
17.02 20:21:17 [Server] Server thread/INFO Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
17.02 20:21:17 [Server] Server thread/INFO Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
17.02 20:21:17 [Server] Server thread/INFO Max TNT Explosions: 100
17.02 20:21:17 [Server] Server thread/INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
17.02 20:21:17 [Server] Server thread/INFO Experience Merge Radius: 3.0
17.02 20:21:17 [Server] Server thread/INFO Mob Spawn Range: 6
17.02 20:21:17 [Server] Server thread/INFO View Distance: 8
17.02 20:21:17 [Server] Server thread/INFO Allow Zombie Pigmen to spawn from portal blocks: true
17.02 20:21:17 [Server] Server thread/INFO Item Despawn Rate: 6000
17.02 20:21:17 [Server] Server thread/INFO Item Merge Radius: 2.5
17.02 20:21:17 [Server] Server thread/INFO Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
17.02 20:21:17 [Server] Server thread/INFO Zombie Aggressive Towards Villager: true
17.02 20:21:17 [Server] Server thread/INFO Nerfing mobs spawned from spawners: false
17.02 20:21:18 [Server] Server thread/INFO -------- World Settings For [world_the_end] --------
17.02 20:21:18 [Server] Server thread/INFO Cactus Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Cane Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Melon Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Mushroom Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Pumpkin Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Sapling Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Beetroot Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Carrot Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Potato Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Wheat Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO NetherWart Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Vine Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Cocoa Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Bamboo Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO SweetBerry Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Kelp Growth Modifier: 100%
17.02 20:21:18 [Server] Server thread/INFO Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
17.02 20:21:18 [Server] Server thread/INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
17.02 20:21:18 [Server] Server thread/INFO Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
17.02 20:21:18 [Server] Server thread/INFO Custom Map Seeds: Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
17.02 20:21:18 [Server] Server thread/INFO Max TNT Explosions: 100
17.02 20:21:18 [Server] Server thread/INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
17.02 20:21:18 [Server] Server thread/INFO Experience Merge Radius: 3.0
17.02 20:21:18 [Server] Server thread/INFO Mob Spawn Range: 6
17.02 20:21:18 [Server] Server thread/INFO View Distance: 8
17.02 20:21:18 [Server] Server thread/INFO Allow Zombie Pigmen to spawn from portal blocks: true
17.02 20:21:18 [Server] Server thread/INFO Item Despawn Rate: 6000
17.02 20:21:18 [Server] Server thread/INFO Item Merge Radius: 2.5
17.02 20:21:18 [Server] Server thread/INFO Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
17.02 20:21:18 [Server] Server thread/INFO Zombie Aggressive Towards Villager: true
17.02 20:21:18 [Server] Server thread/INFO Nerfing mobs spawned from spawners: false
17.02 20:21:18 [Server] Server thread/INFO Preparing start region for dimension 'world'/minecraft:overworld
17.02 20:21:21 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:21 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:21 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:21 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:21 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:21 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:21 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:22 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:43 [Server] Server-Worker-1/INFO Preparing spawn area: 0%
17.02 20:21:44 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:44 [Server] Server thread/INFO Preparing spawn area: 72%
17.02 20:21:45 [Server] Server thread/INFO Time elapsed: 26661 ms
17.02 20:21:45 [Server] Server thread/INFO Preparing start region for dimension 'world_nether'/minecraft:the_nether
17.02 20:21:47 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:47 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:47 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:47 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:47 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:47 [Server] Server thread/INFO Time elapsed: 2798 ms
17.02 20:21:47 [Server] Server thread/INFO Preparing start region for dimension 'world_the_end'/minecraft:the_end
17.02 20:21:48 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:48 [Server] Server thread/INFO Preparing spawn area: 0%
17.02 20:21:48 [Server] Server thread/INFO Preparing spawn area: 83%
17.02 20:21:49 [Server] Server-Worker-1/INFO Preparing spawn area: 83%
17.02 20:21:49 [Server] Server-Worker-1/INFO Preparing spawn area: 83%
17.02 20:21:50 [Server] Server-Worker-1/INFO Preparing spawn area: 92%
17.02 20:21:50 [Server] Server thread/INFO Time elapsed: 2874 ms
17.02 20:21:50 [Server] Server thread/INFO [NickNames] Enabling NickNames v2.3
17.02 20:21:50 [Server] Server thread/INFO [AdvancedTeleport] Enabling AdvancedTeleport v5.0.13
17.02 20:21:50 [Server] Server thread/INFO Advanced Teleport is now enabling...
17.02 20:21:50 [Server] Server thread/INFO [dynmap] Enabling dynmap v3.0-beta-10-257
17.02 20:21:51 [Server] Server thread/INFO [dynmap] Using LuckPerms 5.0.72 for access control
17.02 20:21:52 [Server] Server thread/INFO [dynmap] Mod Support processing completed
17.02 20:21:53 [Server] Server thread/INFO [dynmap] Loaded 25 shaders.
17.02 20:21:53 [Server] Server thread/INFO [dynmap] Loaded 82 perspectives.
17.02 20:21:53 [Server] Server thread/INFO [dynmap] Loaded 14 lightings.
17.02 20:21:54 [Server] Server thread/INFO [dynmap] Web server started on address 192.99.38.208:2442
17.02 20:21:54 [Server] Server thread/INFO [dynmap] version 3.0-beta-10-257 is enabled - core version 3.0-beta-10-257
17.02 20:21:54 [Server] Server thread/INFO [dynmap] For support, visit https://forums.dynmap.us
17.02 20:21:54 [Server] Server thread/INFO [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
17.02 20:21:54 [Server] Server thread/INFO [dynmap] Loaded 3 maps of world 'world'.
17.02 20:21:54 [Server] Server thread/INFO [dynmap] Loaded 6 pending tile renders for world 'world'
17.02 20:21:54 [Server] Server thread/INFO [dynmap] Loaded 2 maps of world 'world_nether'.
17.02 20:21:54 [Server] Server thread/INFO [dynmap] Loaded 2 maps of world 'world_the_end'.
17.02 20:21:54 [Server] Server thread/INFO [dynmap] Enabled
17.02 20:21:54 [Server] Server thread/INFO Server permissions file permissions.yml is empty, ignoring it

**Comment by FedUpWith-Tech** [comment]
I'm going to assume due to the age of this issue it is no longer relevant but it appears that dynmap was working as intended. sounds like a port wasn't forwarded by your server host properly
