### ISSUE TITLE
Jagged lines at 35.2643896828 degrees

### ISSUE THREAD

**Issue by MitchTalmadge** [webbukkit/dynmap#2798]
The number in the title is not random. It is equal to arcsin(tan(30 deg)) which is the exact angle to preserve aspect ratio in an [isomorphic projection](https://en.wikipedia.org/wiki/Isometric_projection). I have created a custom perspective and used values such as 35, 35.3, 35.264, and the one in the title, but it always comes out with jagged lines like the following:

![image](https://user-images.githubusercontent.com/8848080/74800184-e5f41100-528f-11ea-94bb-c6c715749fcd.png)

Notice that the edges of the blocks are not very straight/linear. They jump around a lot. 

Here is what we are looking at from the top:

![image](https://user-images.githubusercontent.com/8848080/74799863-0374ab00-528f-11ea-933f-3abd45644ee6.png)

I thought it could be a scaling issue so I rendered it at scale 16 instead of 4:

![image](https://user-images.githubusercontent.com/8848080/74799960-4767b000-528f-11ea-9a6d-0b8a240be1d4.png)

It looks great zoomed out, but up close the problem persists:

![image](https://user-images.githubusercontent.com/8848080/74799974-5189ae80-528f-11ea-874c-10aab2bfcd3a.png)

I know, I'm being picky, but I am curious why it's not perfect and if there is a solution to make it so. If not, oh well I guess. 16 looks great but I can only render the whole map at 4 on my hardware due to disk size constraints. It would be amazing to have it at a perfect aspect ratio without the jaggies.

Thanks for any help. Here are my perspectives:

```
  - class: org.dynmap.hdmap.IsoHDPerspective 
    name: iso_SE_35_vlowres
    azimuth: 135
    inclination: 35.2643896828
    scale: 2

  - class: org.dynmap.hdmap.IsoHDPerspective 
    name: iso_SE_35_lowres
    azimuth: 135
    inclination: 35.2643896828
    scale: 4

  - class: org.dynmap.hdmap.IsoHDPerspective 
    name: iso_SE_35_medres
    azimuth: 135
    inclination: 35.2643896828
    scale: 8
    
  - class: org.dynmap.hdmap.IsoHDPerspective 
    name: iso_SE_35_hires
    azimuth: 135
    inclination: 35.2643896828
    scale: 16
```

**Comment by mikeprimm** [comment]
Avoiding that would require anti-aliasing via super-sampling and blending pixels, which would increase render time by 2x or 4x.  Not going to happen.  Dial up your resolution - that'll give you the equivalent results, and switch to JPEG format if you'd prefer softer edges.
