### ISSUE TITLE
Marker Problem

### ISSUE THREAD

**Issue by Inxity** [webbukkit/dynmap#2800]
Hello i see you dont have any support for ultimateclaims and i found a plugin https://www.spigotmc.org/resources/mcg-ucdm-ultimateclaims-dynmap.70472/
i setup it and plugin works fine but dynmap is not i talked to it's developer and he said it is something wrong with dynmap so i came here when i claim somewhere it is not showing any claim markers on my website

**Comment by FedUpWith-Tech** [comment]
dynmap doesn't support ultimate claims. you can try dynmap-factions but any issues should be created there.
