### ISSUE TITLE
Could not update map: Not Found after I editied level-name

### ISSUE THREAD

**Issue by UgleeChicken** [webbukkit/dynmap#2801]
Hello my enlgsh isnt the best but I will give my best to explain my problem.

Im using DynMap on my Server. It all worked fine till I thought its a good idea (for no reason) to delte the "level-name" on the server.properties to nothing. its just "level-name=".

For a little test i changed "level-name=world" - and everything works fine with dynmap again. But
yy friends and I start to play and build up our new world... of course would it be awesome to run Dynmap again without start from the beginning.

Is there something I can do ?

**Comment by UgleeChicken** [comment]
Help?

**Comment by FedUpWith-Tech** [comment]
if you change the world name you need to tell dynmap what the world name is in the config, if you changed the world name after starting you will need to restart the render
