### ISSUE TITLE
Show people who are in the nether, in the overworld?

### ISSUE THREAD

**Issue by GuyInGrey** [webbukkit/dynmap#2804]
Is it possible to show people who are in the nether, in the overworld at their matching coordinates? (8x nether coords). I've already removed the nether map in dynmap, I just have the overworld one, but when people go in the nether you can't see them anywhere.

**Comment by FedUpWith-Tech** [comment]
No, this wouldn't really make sense, they aren't in the dimension so they won't show up in the dimension to get the coords from.

If you want to modify the plugin yourself feel free to fork it and add the functionality but this is too niche to add to the main repo and support
