### ISSUE TITLE
Add an event when you click on the map

### ISSUE THREAD

**Issue by Spliterash** [webbukkit/dynmap#2808]
I have a wonderful idea, in the browser when you click on the map, Event will be called in spigot which contains
Location - Clicked location
OfflinePlayer - If the player has logged in, this field will be filled, otherwise null.
This will allow you to do so many things, and I hope that one day such an event will be in dynmap

**Comment by FedUpWith-Tech** [comment]
This is a bit beyond what dynmap is mean to be. Feel free to fork it yourself and add this functionality but we don't plan to include this in the main repo
