### ISSUE TITLE
Image file unable to write.

### ISSUE THREAD

**Issue by bluuberi** [webbukkit/dynmap#2812]
I'm on the latest version of dynmap for 1.15.2 and my console is being flooded by this error.

[dynmap] Image file plugins/dynmap/web/tiles/_markers_/marker_world_new.json - unable to write - failed

I've tried to cancel render, paused all renders, and the error still appears. Is there a fix?

**Comment by grossly** [comment]
I have the same problem but using 1.14.4, The console is getting flooded by 
[dynmap] Image file plugins/dynmap/web/tiles/_markers_/marker_Batz Creative World.json - unable to write - failed
and 
[dynmap] Image file plugins/dynmap/web/tiles/Batz Creative World/t/2_2/66_86.png - unable to write - failed

What has to be done to fix it?

**Comment by FedUpWith-Tech** [comment]
This is a common bug but is likely due to permissions errors or config errors. Please reopen if the issue persists.

**Comment by Bingcheng2023** [comment]
> 这是一个常见的错误，但可能是由于权限错误或配置错误造成的。如果问题仍然存在，请重新打开。
Is it possible that his disk space or node is full (I also have this problem because there are too many dynmap images taking up 100% of the nodes？
