### ISSUE TITLE
Causing player data not to save

### ISSUE THREAD

**Issue by Kade-Donohoue** [webbukkit/dynmap#2818]
dynmap was taking up 6 gb and had over 500000 files taken up and was spitting out a lot of errors. log is below.
[2020-03-20-2.log](https://github.com/webbukkit/dynmap/files/4361284/2020-03-20-2.log)

**Comment by FedUpWith-Tech** [comment]
this isn't an error- this is how dynmap works. It creates thousands of files and uses tons of space.
