### ISSUE TITLE
Impossible world?

### ISSUE THREAD

**Issue by mmuziek** [webbukkit/dynmap#2819]
Hello i have a question. i want to show my world on dynmap.
Strange enough worldborder filled the world. but dynmap doesnt see those.
its a map that already was made before and was upgraded to 1.15 using spigot server with startup argument.

however it did not work. i tried the program chunksrefresher but i keep getting 0 generated chunks found? in each region.

The point is when i move manually it does show those chunks on dynmap.
how can i show the entire world since the player teleportation afk pre render tools do it in a square and my map is not a square

i now have no clue beside days of flying to get it showing

**Comment by masterX244** [comment]
did you try `/dynmap fullrender`?  
that should force rendering all chunks. (might take a few hours/days, too but doesn't require player interaction after it started

**Comment by mmuziek** [comment]
i tried yes. it now took 3 days total.
but i have it working.
I did a worldborder Forced Render + Dynmap fullrender and then another  Worldborder normal render then again a Dynmap fullrender then it finally started showing the world.
and i still have No clue why
