### ISSUE TITLE
[question] How to hide myself from dynmap playerlist?

### ISSUE THREAD

**Issue by zebravis** [webbukkit/dynmap#2821]
Hello, can someone help me with removing names of Admins on the dynmap playerlist?

If this isn't something that's possible, maybe it would be a great feature.

Thanks!

**Comment by Guerout-Arnaud** [comment]
Hi! I think it's /dynmap hide. To be visible again just use /dynmap show

**Comment by zebravis** [comment]
> Hi! I think it's /dynmap hide. To be visible again just use /dynmap show

Hi, thanks for replying, but that's not what i'm looking for. /dynmap hide hides me on the map, but grays me out in the playerlist. I'm looking to remove my name from the dynmap playerlist :)

**Comment by FedUpWith-Tech** [comment]
The config to change the behavior of /dynmap hide to completely hide the player is in the wiki
```includehiddenplayers : if set to true, players that are hidden (via the /dynmap hide command) will be reported to the UI as online, but with their position, health, and messages still hidden. They will appear in the player list.```
