### ISSUE TITLE
Dynmap doesnt save dmap changes

### ISSUE THREAD

**Issue by mmuziek** [webbukkit/dynmap#2823]
Well i worked about a hour or 2 on making the maps look great and configurating them all.
Sadly dynmap doesnt save it so once the server restarts its back what it was before.

Can someone please tell me how to fix that or save it as i lost all my work...
i changed all maps names icons locations 
i removed some maps and appended others
everything is back what it  was.....

**Comment by FedUpWith-Tech** [comment]
Duplicate of #1936
