### ISSUE TITLE
Web server started on an adress that is not working.

### ISSUE THREAD

**Issue by Bekron** [webbukkit/dynmap#2825]
[Server thread/INFO]: [dynmap] Web server started on address 0.0.0.0:4492

I switched the port from 8123 to 4492 but the IP is 0.0.0.0 for some reason. Is there a fix for this?
I can check the map using localhost as IP but people who dont have the same IP cant use it obviously.

**Comment by kroltan** [comment]
0.0.0.0 means to listen on all exposed addresses. (it's not a dynmap thing, this applies to basically all kinds of servers)

So you can check your server computer's public IP address and connect to that (you still need the port though)
