### ISSUE TITLE
Web Name - can it be changed?

### ISSUE THREAD

**Issue by MinecraftCitiesNetwork** [webbukkit/dynmap#2831]
![Capture](https://user-images.githubusercontent.com/62296630/77655661-d40c3900-6fc6-11ea-8608-6cc10f1c6ece.png)

**Comment by MinecraftCitiesNetwork** [comment]
How do I change it from MOTD?

**Comment by pavog** [comment]
Use `#webpage-title` in your configuration.txt and remove the `#`.

---

> webpage-title : this setting, a string, is used to specify the title for the Dynmap maps web page. If not specified, it will attempt to use the 'server-name' property from server.properties. If that is undefined or set to 'Unknown Server', the title will default to 'Minecraft Dynamic Map'.

Reference: [Wiki: Base-Plugin-Settings](https://github.com/webbukkit/dynmap/wiki/Base-Plugin-Settings)
