### ISSUE TITLE
Old North gone?

### ISSUE THREAD

**Issue by Eneroth3** [webbukkit/dynmap#2833]
Hi,

I've recently gotten back to the game and am trying to update my 1.8 server to 1.15. The server was originally created in Beta 1.8 Pre Release, long before the north direction changed. After updating Dynmap from 2.2 to 3.0 beta 10 it seems "compass-mode: pre19" is ignored. Has this option been deprecated?

It is crucial for this server to kep the old north as street names, station names, buildings and other things are oriented this way, as well as the mental maps for all of the players.

**Comment by Eneroth3** [comment]
I've succeeded with a workaround/hack for this.

In my custom templates I've changed all perspective, e.g. replaced iso_S_90_vlowres with iso_E_90_vlowres and in the css override I've added a transformation to the the compass (`.compass { transform: rotate(-90deg); }`).

It has the drawback that the small letters around the compass are rotated but I can live with it. The bigger problem is that it feels kinda hacky. Any response on whether pre19 is intentionally removed or what is happening here would be useful.

**Comment by leetmaster4004** [comment]
I've run into the same issue, a pre-1.8 map that has been gradually updated over years that I am now seeing compass issues when upgrading to spigot-1.13.2 with Dynmap-3.0.1-spigot. I would do the same as Eneroth3 but I am not sure where id input the css override. Any help would be appreciated.

**Comment by Eneroth3** [comment]
The HTML file has a commented put reference to a style sheet named something with override. You can un-comment this line and use that CSS file. However it feels quite dirty and I prefer a more formal way. Among other things it forces a total re-render, as Dynmap consider the perspectives to be new.

**Comment by mikeprimm** [comment]
Just added a custom perspective setting, compassazimuth, which can be used to control the compass rose on a map using the perspective to override the rendering azimuth.  There is also a sample perspective in perspectives.txt, 'oldnorth', that shows the old 'north is east' compass rose.
