### ISSUE TITLE
hires renders 4x4 

### ISSUE THREAD

**Issue by gimbolark** [webbukkit/dynmap#2834]
It is not rendering world 16x16
hires renders 4x4 
![4x4](https://user-images.githubusercontent.com/40950342/77823659-d4631c00-710d-11ea-80d2-98cf47765fcb.PNG)
![hires](https://user-images.githubusercontent.com/40950342/77823660-d5944900-710d-11ea-96f4-8f05cbb592a4.PNG)

**Comment by FedUpWith-Tech** [comment]
Who is your server host. Shockbyte resets the quality profile every time you restart the server to vlowres.

Also, did you re-render after you changed the quality profile?

**Comment by JurgenKuyper** [comment]
@GimboLark hires renders the flat map in lowres, if we were to change this too many servers would get render glitches because of the sudden map change. you can change the setting by using the `dmap mapset worldname:mapname perspective:iso_S_90_hires` command and do a rerender.
