### ISSUE TITLE
Default load world won't change

### ISSUE THREAD

**Issue by IIF4D3II** [webbukkit/dynmap#2835]
By default dynmap loads the Survival world, I tried changing it to my spawn world with:

"defaultzoom: 5
defaultworld: Spawn
defaultmap: flat"

However it won't change anything, I've also tried adjusting the zoom with the command but also does nothing. Am I doing something wrong here?

**Comment by huangzong1998** [comment]
maybe your world name is wrong.
for example , my server is forge ,and my worlds name are like DIMxxx 
you can go to the "world" direction to see the name.

**Comment by IIF4D3II** [comment]
I've checked but have the right name

**Comment by FedUpWith-Tech** [comment]
What is your world name?
