### ISSUE TITLE
Dynmap not loading

### ISSUE THREAD

**Issue by XxRosiexX** [webbukkit/dynmap#2836]
The plugin is loading and everything is starting correctly however nobody can connect.
it's set to the servers IP address but not loading that either.

http://0.0.0.0:3444/

https://hastebin.com/qaxodaxape.coffeescript

**Comment by Eneroth3** [comment]
If you haven't already you can check the server log. I had a similar issue and in my case I had simply forgot to give the user running the server permission tot he dynmap folder.

**Comment by FedUpWith-Tech** [comment]
This is either a permissions issue or a port forwarding issue
