### ISSUE TITLE
Dynmap Chat not working and Player movement no updating

### ISSUE THREAD

**Issue by apatuka** [webbukkit/dynmap#2837]
Hello, when i load the dynmap it shows the lastest messages but not the newer ones, and the js drops this error:

This happened when i started to use a chat system for bungeecord

```
TypeError: set is undefined
2 markers.js:372:4
    markers xxx:8123/js/markers.js:372
    jQuery 7
    component xxx:8123/js/map.js?_=3.0-beta-10-257:710
    swtch xxx:8123/js/dynmaputils.js?_=3.0-beta-10-257:406
    update xxx:8123/js/map.js?_=3.0-beta-10-257:699
    each jQuery
    update xxx:8123/js/map.js?_=3.0-beta-10-257:694
    jQuery 6


```

What can i do ? Thank you !

**Comment by FedUpWith-Tech** [comment]
Bungee isn't supported with dynmap so most bungee plugins don't interface with dynmap properly. Does the issue persist on standalone servers?

**Comment by apatuka** [comment]
Thanks for reply,

After restarting the markers.yml it works again.
