### ISSUE TITLE
Map only loading a maximum of 169 tiles despite loading chunks with WorldBorder

### ISSUE THREAD

**Issue by LouWasHere** [webbukkit/dynmap#2840]
Mostly as in title, I have a world border radius 4500, I have run the wb fill command, and yet Dynmap only renders the 169 tiles surrounding the spawn area.

Any guidance welcome!

**Comment by D0ublek1ll** [comment]
Loading chunks with worldborder should be done before anything else happens in the world.
Make sure dynmap is NOT rendering during the worldborder fill process.

When the worldborder fill is done, typ /dynmap fullrender <world> and wait..
