### ISSUE TITLE
IndustrialCraft 2 won't render on Dynmap

### ISSUE THREAD

**Issue by Krosta8** [webbukkit/dynmap#2842]
Hello,
I have Dynmap on Forge 1.12.2 and it won't render almost anything from Industrial Craft 2. I tried to find on Google, even on wiki for dynmap how to do it, nothing helped. Is it possible, that there is no way how to make it render, right now?
I was able to add modsupport for Applied Energistics mod, but not for Industrial Craft 2.
I am using latest dynmap for forge: V3.0 Beta 4, forge 1.12.2
And latest forge 14.23.5.2847

**Comment by FedUpWith-Tech** [comment]
ic2 doesn't use blocks they use model which are rendered client side. There is no current way to render those blocks with dynmap
