### ISSUE TITLE
Is there a way to set player name colour on the dynmap via the api?

### ISSUE THREAD

**Issue by KarlOfDuty** [webbukkit/dynmap#2843]
As the title says, I have a plugin and I want it to be able to customize the name colour of players on the dynmap.

**Comment by FedUpWith-Tech** [comment]
Yes most permissions plugins or nickname plugins will interface with dynmap and allow colors in names. you aso need to enable the colors in the config

**Comment by KarlOfDuty** [comment]
Well let me re-phrase that then, how do I set name colours?

**Comment by FedUpWith-Tech** [comment]
What plugin are you using?

**Comment by KarlOfDuty** [comment]
Well I'm not using any plugin at all at the moment, I am looking to create a small helper plugin that decides player name colors on the dynmap depending on certain server, area and individual player conditions. I am only wondering how I set a player's name colour on the dynmap as I could not find an api function for that.

**Comment by generrosity** [comment]
@KarlOfDuty  You are keen to write plugins?! Come to the Discord and chat there. Its possible that its not possible in the API currently (there is another case talking about bungeecord that passes over its own custom colours to dynmap and dynmap basically passes them straight through).

Maybe there is a translation step just before display that is doable at API. Come chat!

**Comment by KarlOfDuty** [comment]
> @KarlOfDuty  You are keen to write plugins?! Come to the Discord and chat there. Its possible that its not possible in the API currently (there is another case talking about bungeecord that passes over its own custom colours to dynmap and dynmap basically passes them straight through).
> 
> Maybe there is a translation step just before display that is doable at API. Come chat!

Hello, I don't really make minecraft plugins anymore but thanks anyway

**Comment by JurgenKuyper** [comment]
thanks for the notice, I am going to go ahead and close this issue, if you ever want to pick it back up and join the discord, feel free to do so.
