### ISSUE TITLE
Civs compatibility

### ISSUE THREAD

**Issue by TofPlays** [webbukkit/dynmap#2845]
Please add Civs compatibility. Its a land claim plugin with complex features.

**Comment by pavog** [comment]
There won't be a builtin civs addon.
Someone else might build an extra Civs plugin for dynmap, like [Dynmap-WorldGuard](https://github.com/webbukkit/Dynmap-WorldGuard) but this is not the job for the authors of dynmap.
So you should better ask someone else to do this.
