### ISSUE TITLE
Cannot Connect to Webpage

### ISSUE THREAD

**Issue by JoshIA6** [webbukkit/dynmap#2846]
Seems to work just fine from the server end, but when I try to connect to the map via google chrome, I get this error (yes I do put the port in, which is 8123 in my instance):
This site can’t be reached
51.79.83.152 refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

Here is my console log. Everything looks fine to me

[INFO] .... [dynmap] Enabling dynmap v3.0-beta-10-257*
[WARNING] .... Enabled plugin with unregistered PluginClassLoader dynmap v3.0-beta-10-257
[INFO] .... [dynmap] Starting Scheduled Write Job (markerAPI).
[INFO] .... [dynmap] Using LuckPerms 5.0.72 for access control
[INFO] .... [dynmap] Mod Support processing completed
[INFO] .... [dynmap] Loaded 25 shaders.
[INFO] .... [dynmap] Loaded 82 perspectives.
[INFO] .... [dynmap] Loaded 14 lightings.
[INFO] .... [dynmap] Web server started on address 51.79.83.152:8123
[INFO] .... [dynmap] version 3.0-beta-10-257 is enabled - core version 3.0-beta-10-257
[INFO] .... [dynmap] For support, visit https://forums.dynmap.us
[INFO] .... [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
[INFO] .... [dynmap] Loaded 3 maps of world 'world'.
[INFO] .... [dynmap] Loaded 2 maps of world 'world_nether'.
[INFO] .... [dynmap] Loaded 2 maps of world 'world_the_end'.
[INFO] .... [dynmap] Enabled

I did have to force the IP in the config file though because whenever I didnt set it, it would show up in console as 0.0.0.0:8123 and would not connect. Anyone know of a fix to this? I am running my server through server.pro hosting

**Comment by dan-lee76** [comment]
Having the same issue as well, tried changing the port but still nothing

**Comment by Mr1Vgy** [comment]
I am also having this problem, I've tried switching minecraft and dynmap versions, but nothing fixes it

**Comment by JoshIA6** [comment]
I got it to work, the port 8123 wasn't open in my case, so to fix it I needed to get an open port. Some hosts you have to contact and request an open port from, but server.pro which is my host has 2 extra open ports and one of them ended up working for me
