### ISSUE TITLE
Add auto login by IP address?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [webbukkit/dynmap#2850]
I'm thinking if someone already login in Minecraft game(joined server),  
and he will be able to use the same IP address to directly access to dynmap,  
with his own permissions.

Then if someone is not in Minecraft game, just share him a fake Nginx 404 page lol

**Comment by jaboy** [comment]
There is no reason to add what is already in the plugin.

Go here and search for "use-player-login-ip"
https://github.com/webbukkit/dynmap/wiki/Component-Configuration
