### ISSUE TITLE
Mystcraft: Dimensions detected as the same

### ISSUE THREAD

**Issue by rbroderi** [webbukkit/dynmap#2851]
Dynmap is detecting my mystcraft dimensions as the same dimension and is therefore overwritten the map of one with the other, depending on which is loaded. Is is also detecting the dimension number as a very large number DIM1210950779 instead of what it should be. They show as DIM_MYST9 and DIM_MYST10 in worlds folder, DIM9, DIM10 inside of minecraft. Running 1.12.2 and dynmap version Dynmap-3.0-beta-4-forge-1.12.2

[image](https://user-images.githubusercontent.com/15883611/78621047-9c678180-784f-11ea-8037-cf1062ddb981.png)

**Comment by JurgenKuyper** [comment]
closing because this is not in scope and an issue on mystcraft's dimension registration's end, don't know if this is still the case.
