### ISSUE TITLE
Question: show loaded chunks?

### ISSUE THREAD

**Issue by Cobecc** [webbukkit/dynmap#2854]
Hi! I have a question about how to show the loaded chucks in the dynmap, a friend of mine told me it's possible to know which chuck is on or not using the dynmap an a flag or something. Is it possible?

**Comment by D0ublek1ll** [comment]
Not to my knowledge, you can make an estimated guess by looking at a players location.
There is probably some plugin out there that adds a layer to dynmap that does this.. But I don't think its possible in dynmap itself.

**Comment by Cobecc** [comment]
Not is not possible, a friend of mine told me I need to use Dypmap Diag to know that. Sorry for the question!

**Comment by Timi7007** [comment]
For all having the same thought: The Dynmap Diag plugin is available here: http://www.dynmap.us/builds/Dynmap-Diag/
Version 0.30 seems to work fine with Dynmap 3.1 and Paper 597 / Minecraft 1.16.5.

It shows loaded chunks in a blue border. I've used this with "KeepChunks 1.6.7" to ensure automatic railroads always work.

The source-code is here: https://github.com/webbukkit/Dynmap-Diag
