### ISSUE TITLE
Dynmap does not work at all

### ISSUE THREAD

**Issue by matthiasdevreede** [webbukkit/dynmap#2857]
org.bukkit.command.CommandException: Unhandled exception executing command 'dynmap' in plugin dynmap v2.5-Dev201706100405
,[15:06:44 ERROR]: null
,	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper.jar:git-Paper-162]
,	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper.jar:git-Paper-162]
,	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[paper.jar:git-Paper-162]
,	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[paper.jar:git-Paper-162]
,	at java.lang.Thread.run(Thread.java:834) [?:?]
,Caused by: java.lang.NullPointerException
,	at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:937) ~[?:?]
,	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper.jar:git-Paper-162]

**Comment by D0ublek1ll** [comment]
It seems that you're running an outdated plugin, 1.15 support was most definetely not added on 10-06-2017 :)

Have you checked if the latest dynmap version does work? If not I'd recomment updating, I figure that will solve this problem for you.
