### ISSUE TITLE
Setting up Dynmap with custom domain.

### ISSUE THREAD

**Issue by ModdingZerp** [webbukkit/dynmap#2858]
How do I set up dynmap with a custom domain?

**Comment by ilsubyeega** [comment]
use reverse proxy like nginx to do that

**Comment by iangioffre** [comment]
I used a subdomain to forward to the ip:port site. Then, add an A Record that points that same subdomain to your ip. It's a little bit of a workaround but it works for me!

**Comment by alex17lol** [comment]
iangioffre how exactly did you that? I mean what did you put in Host weight and prio

**Comment by iangioffre** [comment]
@alex17lol An A record shouldn't require weight and priority. I used GoDaddy and I was able to easily setup a subdomain in the forwarding tab. Then I add an A record with the same subdomain name with my ip and a TTL of 1/2 hour.
