### ISSUE TITLE
How Do I Change Default Map/Delete Others?

### ISSUE THREAD

**Issue by DistortionVEVO** [webbukkit/dynmap#2859]
I want to change my default world on Dynmap, but it isn’t working. I also want to get rid of others, and just have 1 Dynmap. How do I do this exactly? (Also extra problem, how do I rename them?) thanks in advanced.

**Comment by D0ublek1ll** [comment]
/dmap mapadd <world>:<mapname>
/dynmap mapdelete <world>:<mapname>

You can also modify them by hand, edit worlds.txt to do so.
