### ISSUE TITLE
Dynmap iframe issues

### ISSUE THREAD

**Issue by Brand0n1** [webbukkit/dynmap#2862]
Hello, I am currently having issues setting up Dynmap with iframe. I need it to work with https rather than HTTP so that it can work with my forced SSL settings on my website. I've looked around for a while and can't figure out how to fix it. The only error I get is the following: "SERVER IP refused to connect."

I know that my current configuration works because I have tried it on a normal file hosted on my computer. I know this is caused by the webserver being forced to use https rather than just using HTTP however I don't know how to fix it to make Dynmap run on https.

Any help will be greatly appreciated.

My website code for the map:
`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Server Maps</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body,html,iframe{width:100%;height:100%}iframe{border:none}body{display:flex}</style>
</head>
<body>
<iframe frameborder="0" height="95%" src="SERVER ADRESS:32865/" width="100%">
  <p>Your browser does not support iframes.</p>
</iframe>
</body>
</html>`

**Comment by D0ublek1ll** [comment]
You can only fix this by using a standalone dynmap setup, dynmap itself is not designed to work over https, however, if you connect it to a database you can put setup the standalone map on your webserver and the plugin will write all the tiles and other config items to the database.

For instructions on how to do this you should refer to the documentation.

**Comment by l1m3r** [comment]
For smaller setups you can use [stunnel](https://www.stunnel.org/) to SSL-ify DynMaps internal webserver instead of a fully fledged reverse proxy.

Just install it and edit `stunnel.conf` a little:
```
[dynmap]
accept = 8124
connect = 8123
cert = stunnel.pem
TIMEOUTclose = 0
```

- `Stunnel.pem` is the auto generated private cert (from installing stunnel)
- `8123` is dynmap's http server port
- and `8124` the ssl-ified new server port.

**Comment by Brand0n1** [comment]
> You can only fix this by using a standalone dynmap setup, dynmap itself is not designed to work over https, however, if you connect it to a database you can put setup the standalone map on your webserver and the plugin will write all the tiles and other config items to the database.
> 
> For instructions on how to do this you should refer to the documentation.

Are there any good tutorials for this? I've been stuck with a black map for about 2 weeks and the discord hasn't helped much with it.
