### ISSUE TITLE
DynmapForge - Help adding support for modded biomes 

### ISSUE THREAD

**Issue by badhaloninja** [webbukkit/dynmap#2863]
There is a lack of documentation on adding support for modded biomes. So far I have figured out most of it by looking at [Thaumcraft-texture.txt](https://github.com/webbukkit/dynmap/blob/v3.0/forge-1.12.2/src/main/resources/renderdata/Thaumcraft-texture.txt) and [BiomesOPlenty-texture.txt](https://github.com/webbukkit/dynmap/blob/v3.0/forge-1.12.2/src/main/resources/renderdata/BiomesOPlenty-texture.txt), However I am confused by the color multipliers, in most if not all of the examples the values for `grassColorMult` and `foliageColorMult` are 7 hex digits while the `waterColorMult` is 6. 

So I looked into it and found `R << 16 | G << 8 | B` so lets say the 6 digit color I have is `#800040` the output would be `8388672`, however that is just the hex value as an integer not a 7 digit hex, and when using the original hex value in `biome:id=biomes/EXAMPLE,grassColorMult=800040,foliageColorMult=800040,waterColorMult=800040` only the water is the expected color.
What am I missing?

**Comment by Orhideous** [comment]
Maybe, this commit will explain some internals: https://github.com/webbukkit/DynmapCore/commit/889029c94431ca8e3393a0297a82b2a1f2cb5883
