### ISSUE TITLE
Update Commands Wiki page to include new commands

### ISSUE THREAD

**Issue by greenywd** [webbukkit/dynmap#2864]
Let me preface by saying I'm not sure if the following are the only commands missing from the [Commands](https://github.com/webbukkit/dynmap/wiki/Commands) Wiki page, 

I came across a PR (#2633) that added new commands and got merged, however the Wiki page hasn't been updated to add them. I believe the following should reside under the 'Rendering' section.

- `dynmap fullrender resume <world>`: Resume render of all maps for world <world>. Skip already rendered tiles.
- `dynmap fullrender resume <world>:<map>`: Resume render of map <map> of world <world>. Skip already rendered tiles.

Cheers!

**Comment by FedUpWith-Tech** [comment]
This will be updated soon, I plan to update the wiki as soon as I finish getting through the github issue backlog, I'll update this issue once the commands are added
