### ISSUE TITLE
Missing Map When Zoomed Out

### ISSUE THREAD

**Issue by AquaLawng** [webbukkit/dynmap#2865]
Does anyone know what causes this? When zoomed all the way out, all areas explored render perfectly except for these 2 black bars. But when you zoom in on them, the map renders and shows what was missing from the zoomed out perspective.

EDIT: Nether is even worse

![Render](https://user-images.githubusercontent.com/61892317/79046138-147dd080-7bdd-11ea-826d-89b7416b332b.png)
![Zoom](https://user-images.githubusercontent.com/61892317/79046141-18115780-7bdd-11ea-9ade-742fb32feb92.png)
![nether](https://user-images.githubusercontent.com/61892317/79046258-e3ea6680-7bdd-11ea-9e46-61f0f14f79d0.png)

**Comment by D0ublek1ll** [comment]
/dynmap fullrender <worldname>

It may take a while.

**Comment by ice-fly** [comment]
Your render was interrupted and parts of tiles are incomplete do a full render

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2485
