### ISSUE TITLE
Forge 1.12 - BoP biomes shown black on dynmap

### ISSUE THREAD

**Issue by vico93** [webbukkit/dynmap#2866]
I currently playing on my dedicated server and when entering a Pasture biome this happened (only lava lakes, lakes/rivers, caves and ravines and structures are rendered, the barley fields not:
![image](https://user-images.githubusercontent.com/3485505/79048804-fa9cb780-7bf5-11ea-85a4-0614b5484adf.png)

How can i mitigate the issue?

**Comment by asvany** [comment]
#2826

**Comment by asvany** [comment]
there is a posssible workaround: #2826
