### ISSUE TITLE
I cannot figure out how to remove worlds from dynmap

### ISSUE THREAD

**Issue by JohnnyS** [webbukkit/dynmap#2867]
The configs are confusing to me and I tried following some steps from a page using worlds: and putting the name and all  that but it didnt work. Can someone help?

**Comment by D0ublek1ll** [comment]
in the folder dynmap/web/css you need to modify standalone.css to include the following lines (add them to the end of the file)

```css
.baloonmessage{display:none !important;}
```
This will disable the message popups regardless of the configuration

**Comment by D0ublek1ll** [comment]
You use the /dmap command for that.
In order to remove a world you remove all the maps from that world.
format: /dmap mapdelete <worldname>:<mapname>

Note: Nether and end maps are not called surface, even if the label says so.
their respective names are: the_end and nether

**Comment by JohnnyS** [comment]
@D0ublek1ll Thank you so much this helped GREATLY!!
