### ISSUE TITLE
Dynmap: artifacts of render with railcraft

### ISSUE THREAD

**Issue by Harchvertelol** [webbukkit/dynmap#2868]
I have a v2.6-beta-1 for Forge 1.7.10 (dynmap 2.3 for 1.7.10 I tried similarly). I have mod 
Railcraft 9.12.2.1 - MC 1.7.10 (Railcraft 9.12.2.0 I tried similarly). The map draws strange blocks that appear after the player moves (player trace) (these blocks are not visible in the game). They have the texture of dry grass (so i'm sure this is a bug). After some time, these blocks disappear from dynmap. Maybe the Railcraft adds an invisible gas that comes from the player, and Dynmap does not see this gas? 

What could it be, how to fix it? Maybe you can prevent Dynmap rendering some specific blocks? Then I will find out the id of these blocks and add to the list of render exceptions. But I do not know how to do this.

P. S. This error is and with DynmapModScrapper config files (files in render data), and without it.

Screenshot is attached.

![qwe](https://user-images.githubusercontent.com/63555997/79075841-e348f180-7cfd-11ea-8db8-af82b1dde3c2.jpg)

**Comment by Harchvertelol** [comment]
I found problems, this is a block of mod railcraft - heat. I disbaled this block in config of Railcraft. Now all is well.

P.S. Disabling:

Its in "config\railcraft\blocks.cfg", parameter "residual.heat" to false.

**Comment by Harchvertelol** [comment]
We have other problem: vertical and horizontal black lines with high resolution (my screen have resolution ultrahd 4k).

P. S. Screenshoot above with this lines.

**Comment by FedUpWith-Tech** [comment]
minecraft 1.7.10 is no longer supported, the vertical lines is related to #2470 you can try any of the fixes there but no guarantees they will even be viable for this version
