### ISSUE TITLE
Dynmap making too much server files

### ISSUE THREAD

**Issue by FCulig** [webbukkit/dynmap#2870]
I keep getting emails from hosting provider that there is too much files on server (number of files, there is more than third of storage free left). Any tips on how to reduce number of files? Ideas I had are disabling end and nether rendering or disabling isometric view(3D).

Some additional information if it is needed:
I am hosting my Minecraft server on Server Pro. I have a default vanilla server (6gb of RAM, 20GB of storage). Server is usally averaging around 15 players at one time.

**Comment by A-UNDERSCORE-D** [comment]
Changing from the flat file option to a database (even sqlite) will resolve the file count issues, rather than lots of small files there will be one huge file

**Comment by ice-fly** [comment]
Issue is with hosting provider not dynmap.
(also try jpg)

**Comment by A-UNDERSCORE-D** [comment]
>Issue is with hosting provider not dynmap.

Given that dynmap can make many millions of files for a large server, that may not be the case. Given that there are only so many [inodes](https://en.wikipedia.org/wiki/Inode) available on a given disk partition, its quite easy to run out of inodes. Switching to sqlite or one of the other DB options will solve that, assuming disk space isn't also an issue.
