### ISSUE TITLE
Turning off webchat and the chat bubbles

### ISSUE THREAD

**Issue by JohnnyS** [webbukkit/dynmap#2871]
I have not been able to find where to turn these off even  I turned off the webchat but it still shows the bubble

**Comment by D0ublek1ll** [comment]
in the folder dynmap/web/css you need to modify standalone.css to include the following lines (add them to the end of the file)
```css
.leaflet-popup{display:none !important;}
```
This will disable the message popups regardless of the configuration, but this will also disable all other similar style popups.

**Comment by JohnnyS** [comment]
This helped too thank you for the help bro
