### ISSUE TITLE
WorldBorder and Dynmap 1.12.2

### ISSUE THREAD

**Issue by Harchvertelol** [webbukkit/dynmap#2877]
Last "World Border 1.12.2-1.0.6" don't work with last Dynmap "v3.0-beta-4 for Forge 1.12.2" (dynmap 2.6 too). World border not visible on map. What can I do?

**Comment by FedUpWith-Tech** [comment]
Does this issue persist on the latest dynmap version?

**Comment by Harchvertelol** [comment]
Unfortunately, yes. Last dynmap (v3.1-beta-2 for Forge 1.12.2) not showing World Border with "World Border 1.12.2-1.0.6".

**Comment by Harchvertelol** [comment]
But showing it with World Border 1.12.2-1.0.5.

But World Border 1.12.2-1.0.5 crashing server on world generating. My temporary solution: generate world with World Border 1.12.2-1.0.6, but using for showing World Border 1.12.2-1.0.5 (replace plugin file after generation). Bad solution :)

**Comment by xemnes** [comment]
any new news on this issue? im using mohist and tried the dynmap bridge plugin with the spigot version of worldborder, that didnt work either. cant seem to find any mod equivalent that renders a world border on dynmap

**Comment by xemnes** [comment]
could i ask what you were doing to make it work? because i consistently cannot get this to work with worldborder forge version on 1.12.2

**Comment by FedUpWith-Tech** [comment]
This is a better issue for the worldborder issue tracker not Dynmap. We don't support mohist or the the forge/spigot hybrid servers and the worldborder function is added via worldborder not dynmap

**Comment by xemnes** [comment]
makes sense, fair enough.
