### ISSUE TITLE
Map on site shows up completely blank after switching the world

### ISSUE THREAD

**Issue by Apothic0n** [webbukkit/dynmap#2879]
I had the map fully generated and then when I switched the world the map became blank and no longer updated the tab label for it with the server motd. It's just completely white and has absolutely nothing on the page.

**Comment by Apothic0n** [comment]
![image](https://user-images.githubusercontent.com/63724868/79347420-af3e1e00-7f01-11ea-920a-8cab4abc233c.png)
there is a screenshot of what it looks like

**Comment by Apothic0n** [comment]
also just to clarify:
Server version: 1.15.2
I have tried rebooting the server
I have tried switching to a new world
I have tried doing a full render, it appears to be rendering with the chat messages, but the map site is still blank.

**Comment by ice-fly** [comment]
Guessing its a user error. Try renaming dynmap folder to something else.

**Comment by MildPotato** [comment]
I have the same issue,nearly exactly the same. The web page shows you, and I know the port is not used as I used a un-used port generator on shockbyte. (the provider I use). I get the same blank web page, as shown in the screenshot. 

Here's the link : 
http://heliosphere.mc-shock.com:3441/index.html 

If anyone knows whats going on please tell us. Thanks

**Comment by ice-fly** [comment]
If you're on chrome try inspect element, and see if you're actually being served a dynmap page
