### ISSUE TITLE
how to modify the original spawn point (world)?

### ISSUE THREAD

**Issue by Cobecc** [webbukkit/dynmap#2880]
Excuse me for asking this, I have tried to figure the answer with the wiki and other posts but I can't find the solution. I have in my dynmap a spawnpoint of the world (the original spawn point) and I have moved it to another area. the problem that I try to modify its ID/ ubication /Label but I have only managed to modify the spawn of the end world and not the normal one. I have used :

/ dmarker movehere id: <id>
/ dmarker movehere <label>

how I can know the id/label of my current world spawn  and modify it's ubication?

**Comment by ice-fly** [comment]
Config files
**[RTFM](https://github.com/webbukkit/dynmap/blob/recommended/src/main/resources/configuration.txt#L110)**

**Comment by Cobecc** [comment]
Thanks!
