### ISSUE TITLE
shadow bug

### ISSUE THREAD

**Issue by seema84** [webbukkit/dynmap#2881]
after a fullrender i have some chunks with shadow bugs ->

https://imgur.com/a/nENkH2J

Version: Dynmap version: core=3.0-beta-5-218, plugin=3.0-beta-5-218

**Comment by ice-fly** [comment]
Temp fix: Error can be fixed by going to chunk and doing a radius render

**Comment by seema84** [comment]
yes i know (thats what i do)

**Comment by FedUpWith-Tech** [comment]
shouldn't happen if you fullrender on the latest version- please reopen if it persists on the latest version

**Comment by seema84** [comment]
the bug still exists in version v3.1-beta-4

**Comment by JCDriessen** [comment]
Still exists in version V3.3-beta-3-spigot

https://imgur.com/8evr7Fj

(minecraft spigot 1.18.1 server)

**Comment by JurgenKuyper** [comment]
> Still exists in version V3.3-beta-3-spigot
> 
> https://imgur.com/8evr7Fj
> 
> (minecraft spigot 1.18.1 server)

please update to V3.3-beta-4-spigot, in which most shadow problems are fixed.

**Comment by JCDriessen** [comment]
> > Still exists in version V3.3-beta-3-spigot
> > https://imgur.com/8evr7Fj
> > (minecraft spigot 1.18.1 server)
> 
> please update to V3.3-beta-4-spigot, in which most shadow problems are fixed.

Thankyou for the very fast reply.
I probably need to do a re-render of the affected tiles (fullrender or regionrender of the tiles)?

**Comment by JurgenKuyper** [comment]
> > > Still exists in version V3.3-beta-3-spigot
> > > https://imgur.com/8evr7Fj
> > > (minecraft spigot 1.18.1 server)
> > 
> > 
> > please update to V3.3-beta-4-spigot, in which most shadow problems are fixed.
> 
> Thankyou for the very fast reply. I probably need to do a re-render of the affected tiles (fullrender or regionrender of the tiles)?
affermative (`/dynmap fullrender <worldname>` or `/dynmap radiusrender <world> <x> <z> <radius> `
