### ISSUE TITLE
Connecting to webserver from WAN shows error

### ISSUE THREAD

**Issue by SugarBooty** [webbukkit/dynmap#2882]
I have recently downloaded this plugin and it works wonderfully on LAN. I have forwarded the port that I specified (20000) and am using cloudflare as a DNS for my domain to resolve to my private IP address. I have disabled all the speed optimization features and am running it unencrypted over HTTP. I can connect to the map and view it fine on LAN using the specified port, but when I try to connect using the domain or even my private IP address I get an error which is as follows:

`Ť¨{"translate":"disconnect.genericReason","with":["Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index: 69, Size: 1"]}`

Is this from a misconfiguration on my end or is it some kind of bug? Either way I would appreciate if someone could shed some light on why this is happening

**Comment by ice-fly** [comment]
Guessing its a misconfiguration.

**Comment by SugarBooty** [comment]
A misconfiguration of what? Is it a misconfiguration of the plugin?

**Comment by ice-fly** [comment]
**Idk, this ins't a help forum...** I tunneled over ssh to mysql and I don't have that issue. io.netty is the built in network function, so there's a network issue of some type.

**Comment by SugarBooty** [comment]
Thank you so graciously
