### ISSUE TITLE
Worldborder player update Hidestyle:'stone', normal render fine

### ISSUE THREAD

**Issue by Jokkaj** [webbukkit/dynmap#2888]
(Paper 1.15.2, latest dynmap release) I configured my dynmap hidestyle to be "air" but everytime a player get close to the worldborder gray "stone" tiles generate, but if I re-render the zone those gray tiles disappear.
please fix this issue (maybe you could set air as a default hidestile?)

**Comment by JurgenKuyper** [comment]
not longer present in latest release

**Comment by ephun** [comment]
I still have this issue on the most recent version. I do not believe this is closed

**Comment by mikeprimm** [comment]
Please include worlds.txt

**Comment by ephun** [comment]
I apologize. It was an error on my end and this is no longer an issue for me.
