### ISSUE TITLE
Adding dynmap to website

### ISSUE THREAD

**Issue by alex17lol** [webbukkit/dynmap#2889]
I have a minecraft server using dynmap on one host and a website on another host.
How do I add the dynmap to the the website without iframe(because it shows the dynmap's ip)

**Comment by MoCaveman** [comment]
I am just starting this goal today (ish).  This article talks about the two main options.  Reverse DNS and use of a subdomain.  It is primarily about setting up SSL but it includes moving the website to Apache and how to.  Might help.  https://www.reddit.com/r/admincraft/comments/8j2cbg/setting_up_dynmap_on_a_standalone_webserver_using/

**Comment by ice-fly** [comment]
Can confirm, royal pain in the arse.

**Comment by LiskoSlayer63** [comment]
If you jus want to use external web server with Dynmap, the this is fairly simple task to do.

1. Disable Dynmap internal web server through the config
2. Install some external web server like Apache or IIS
3. Add new site to the web server and link it to the "web" -directory inside of the main "dynmap" -directory
4. Add a domain to your website
5. Profit

Now Dynmap is hosted by an external web server (which is on the same machine) and it also has an own domain name. You can now directly access to your map using the domain. If you want to embed it to website, then as far as I know there's apparently no other way than Iframe, but at least the IP-address isn't visible straight away.

**Comment by T-x-T** [comment]
Use your webserver to reverse-proxy the dynmap webserver, then out the reverse proxied site in the iframe

**Comment by twixi** [comment]
my site on server1, my mc server on server2 how should i be?

**Comment by T-x-T** [comment]
You can use your webserver on server2 to create a [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy).
This means all clients connect to server2 and server2 in the background asks server1 for the website. Your clients will never know about anything from server1, they are just ever talking to server2

**Comment by alex17lol** [comment]
I can't create a reverse proxy because im using a webhost not vps
