### ISSUE TITLE
dynmap won't load areas other than where players are.

### ISSUE THREAD

**Issue by jbg0801-2** [webbukkit/dynmap#2892]
I have dynmap running on my 1.15.2 server, where we have a 1/2000 scale map of the earth, so we plan to use our dynmap to get everyone to their country of choice. However, whenever I go to do a fullrender, it merely renders the area around each player that is on, and then ceases to continue. Does anyone know an easy fix for this? Or any fix at all?
attached is an image of what our server looks like from dynmap
![dynmapdebug](https://user-images.githubusercontent.com/64034442/79782871-a4d3b800-8337-11ea-84f4-29d09f2ca8d9.png)

**Comment by ice-fly** [comment]
Check fullrenderinterval setting, & 'fullrenderplayerlimit'

**Comment by promlgxd** [comment]
oh my god... I'm having the exact same issue and it is annoying... please someone help i need help asap

**Comment by Webbeh** [comment]
BACKUP FIRST !!!

...and then, I believe the server won't load a chunk that hasn't been upgraded between 1.13 and 1.14.

It upgrades it either when a player loads a chunk or if you force their upgrade, by launching the server with the --forceUpgrade argument.

**Comment by FedUpWith-Tech** [comment]
This is likely due to tps pause or player count pausing if you run `/dynmap pause` it should let you see if something is paused any why. I'm going to close this due to age but if the issue persists and it says the render is active then reopen or submit a new issue

**Comment by Webbeh** [comment]
I confirm that this issue still persists as of the latest versions of dynmap/paper/...

Since I'm the only player on the server, I highly doubt I mistakenly typed "/dynmap pause".

:)
