### ISSUE TITLE
can you use your gpu to render the map?

### ISSUE THREAD

**Issue by TIBTHINK** [webbukkit/dynmap#2894]
so I have a server running on ubuntu 18.04
it has an AMD Phenom II x6 1075t for the CPU
and an NVIDIA GeForce GTX 960 2gb for the GPU

is it possible to use the GPU to render the map instead of the CPU?

**Comment by T-x-T** [comment]
There isnt any option for that and I dont think it would be very useful as there is a lot in the render process thats dependent on cpu and I/O (Like gathering all the data, writing the file, etc)

**Comment by Redd56** [comment]
i mean for the iso view it would help alot i would think

**Comment by Redd56** [comment]
> so I have a server running on ubuntu 18.04
> it has an AMD Phenom II x6 1075t for the CPU
> and an NVIDIA GeForce GTX 960 2gb for the GPU
> 
> is it possible to use the GPU to render the map instead of the CPU?

also there is a setting that i didnt know about till recently that allows for parrallel rendering, i have it set to 15 wich seems to be most optimal for my 12 core system, get about 31 ms/t and 95ms/r
