### ISSUE TITLE
Dynmap Not Loading on Mobile Device

### ISSUE THREAD

**Issue by BD103** [webbukkit/dynmap#2897]
Hey all. I have quite the predicament. I have a server through MCProHosting and thought it would be cool to set up Dynmap. I set it up, and it's all cool and stuff. Now, something weird is happening. I can access Dynmap just fine on any computer, but I have issues with any mobile device. For instance, I go to the IP address on an iPad, and it gives me the login screen. (This is all normal. Here's where it gets weird.) So, after clicking "login", the index page starts loading. But, it never finishes. the loading bar stays at the 1/7 point of the screen. I tested this multiple times, including restarting the server, rendering Dynmap again, etc. Does anyone know a fix?
Thanks!
-BD103

**Comment by FedUpWith-Tech** [comment]
mobile isn't supported with the internal webserver or default frontend- you'll have to update the front-end yourself to fix this
