### ISSUE TITLE
Failed to start WebServer on address

### ISSUE THREAD

**Issue by Bapelzien** [webbukkit/dynmap#2898]
[Server] Server thread/ERROR: Failed to start WebServer on address 94.23.156.138:8123 : Failed to bind to /94.23.156.138:8123

What does this mean and how do I fix it?

![MC](https://user-images.githubusercontent.com/64365574/80310587-d2a77980-87db-11ea-8bc4-0424ebfda4c7.JPG)

**Comment by ice-fly** [comment]
Check port isn't being used by another process & check port forward
