### ISSUE TITLE
problème graphisme

### ISSUE THREAD

**Issue by ER-28** [webbukkit/dynmap#2899]
on ne vois pas le bouton pour changer entre 2d/3d

**Comment by FedUpWith-Tech** [comment]
Désolé pour mon français, en utilisant Google Translate.
@BananaSmoothii pourra peut-être vous aider ou il existe un canal de support français sur la discorde. Je vais fermer ce problème afin que vous puissiez obtenir de l'aide.
https://discord.gg/s3rd5qn
