### ISSUE TITLE
Weird textures 

### ISSUE THREAD

**Issue by JulioJpk** [webbukkit/dynmap#2900]
![image](https://user-images.githubusercontent.com/64458454/80453654-52256d80-88ee-11ea-918d-50ab4e7cf53c.png)
![image](https://user-images.githubusercontent.com/64458454/80453753-8305a280-88ee-11ea-8942-6626841c4690.png)

As you can see, my end just started having this weird issue, actually the nether started having this weird black giant squares on the same place that the end, just that the nether has the textures fine, the only world that seems to be changing the textures is the end, I tried a radiusrender but it only extended the problem. I´m using paper 1.14.4 and Dynmap 3.0b5

This is my template for the end:
  - name: world_the_end
    title: "The End"
    maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "Flat"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: defaultscheme
        lighting: default
        mapzoomin: 2
      - class: org.dynmap.hdmap.HDMap
        name: the_end
        title: "Surface"
        prefix: st
        perspective: iso_SE_30_hires
        shader: defaultscheme
        lighting: default
        mapzoomin: 2

Is this a bug or a config that I´m doing wrong?

**Comment by ice-fly** [comment]
Check your texture pack

**Comment by JulioJpk** [comment]
> Check your texture pack

Thank you for your reply, but I have not change the texture pack at all, anyway, how could I check that the default is being used?

**Comment by FedUpWith-Tech** [comment]
Can you pastebin your configuration.txt
