### ISSUE TITLE
DynmapExport Incorrect Grass Render and Troches etc.

### ISSUE THREAD

**Issue by Kili-97** [webbukkit/dynmap#2901]
![image](https://user-images.githubusercontent.com/42013222/80458976-f54ba680-8931-11ea-8561-d1f84698eeb6.png)

This problem happens with default texture pack and a other Texture pack i tried.
It seems that the Alpha of Grasss texture didnt get applied.

Mayby it´s blender related Problem?

**Comment by FedUpWith-Tech** [comment]
Going to close this as its a very low priority and likely not very relevant anymore
