### ISSUE TITLE
Dynmap - ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by TheRealLuna** [webbukkit/dynmap#2902]
I've been working on trying to work with dynmap for a few days now, but with no hope. I've been following solutions to other peoples problems, but nothing has helped. A few things to note:
- I'm working on Paper 1.15.2
- I'm working with a hosting company
I will post with the console error and config.

What do I do?

**Comment by TheRealLuna** [comment]
Console error(s)
28.04 17:03:20 [Server] WARN Enabled plugin with unregistered PluginClassLoader dynmap v3.0-beta-10-257
28.04 17:03:20 [Server] INFO [dynmap] Starting Scheduled Write Job (markerAPI).
28.04 17:03:20 [Server] INFO [dynmap] Using LuckPerms 5.0.72 for access control
28.04 17:03:20 [Server] INFO [dynmap] Mod Support processing completed
28.04 17:03:21 [Server] INFO [dynmap] Loaded 25 shaders.
28.04 17:03:21 [Server] INFO [dynmap] Loaded 82 perspectives.
28.04 17:03:21 [Server] INFO [dynmap] Loaded 14 lightings.
28.04 17:03:21 [Server] ERROR [dynmap] Failed to start WebServer on address (PUBLIC IP):8159 : Failed to bind to /(PUBLIC IP):8159

Config File:
webserver-bindaddress: (PUBLIC IP)

# The TCP-port the webserver will listen on.
webserver-port: 8159

**Comment by ice-fly** [comment]
Check that the port isn't being used by another service and that you have port-forwarded
I'm on paper 1.15.2 and it's working fine

**Comment by TheRealLuna** [comment]
My host allows to create ports easily, and I've been trying different ports provided by the host, but to no change. All console errors are the same.

**Comment by FedUpWith-Tech** [comment]
set the ip in configuration.txt to 0.0.0.0
