### ISSUE TITLE
deftemplatesuffix: resets with every restart

### ISSUE THREAD

**Issue by Sorphius** [webbukkit/dynmap#2903]
in my configuration.txt file the deftemplatesuffix: is set to vlowres. It has worked fine for a couple of days now but I want to increase the resolution. Whenever I try to set deftemplatesuffix: to hires, it resets when I restart the server. 

What am I doing wrong?
[configuration.txt](https://github.com/webbukkit/dynmap/files/4553258/configuration.txt)

**Comment by 2lol555** [comment]
I have the same issue

**Comment by FedUpWith-Tech** [comment]
Your server host (shockbyte im guessing) limits the resolution dynmap can run at. This isn't something we can fix as they modify the config file on server restart.
