### ISSUE TITLE
Near-black fringes / pixels on the sides of grass

### ISSUE THREAD

**Issue by otse** [webbukkit/dynmap#2905]
Hi,

I'm getting these black spots on most grass blocks.

Chroma Hills / Winthor Medieval
![chrome_p9FCMgiNqY](https://user-images.githubusercontent.com/1123362/80687868-3c20d400-8acb-11ea-95c2-36b45f81d9fc.png)
![image](https://user-images.githubusercontent.com/1123362/80687892-4773ff80-8acb-11ea-9a96-49e1c883c411.png)

**Comment by otse** [comment]
Winthor+Medieval+v3.4+MC+1.14 and ChromaHills-128x-1.14-v2 do the same
![image](https://user-images.githubusercontent.com/1123362/80688474-219b2a80-8acc-11ea-91ac-ce177cc0fcee.png)

**Comment by FedUpWith-Tech** [comment]
This looks like an issue with your texture pack, might be due to an incompatible resolution in dynmap
