### ISSUE TITLE
Request - Client side marks

### ISSUE THREAD

**Issue by NightKosh** [webbukkit/dynmap#2907]
Hello. I'd like to ask you about a tiny feature, which should be extremely useful - client side marks.
I'm talking about additional web UI parameter, which allows to open map in the certain location with certain mark(without adding this mark in the map database). This should allow players share links on some important places, and provide better integration with some other tools. At the same time "original map" will not be filled with all sorts of garbage custom marks.

**Comment by otse** [comment]
Dynmap is old. Dmarker is rough. As a feature request this is probably not going to make it. You could try to use the API yourself?
