### ISSUE TITLE
Adding another map type?

### ISSUE THREAD

**Issue by slitterell** [webbukkit/dynmap#2909]
Is there a way to add another map type? I would like to add another Nether layer above the bedrock at the top (128-256 height) as a seperate flat and surface render. Is there an easy way without rewriting all the code? I don't know where else to ask, though this isn't really an "issue".

**Comment by otse** [comment]
worlds.txt
custom-shaders.txt
custom-perspectives.txt
:)

**Comment by slitterell** [comment]
Hmm...I might be dense but I can't grapple with what I am editing. I am pretty computer literate, use linux, and normally do everything myself for installing game servers and editing them but normally I just read up on it.

**Comment by slitterell** [comment]
I figured it out. It took some work to figure out but I can help if someone needs it now :)
