### ISSUE TITLE
Players dont show on surface map

### ISSUE THREAD

**Issue by Sylvamy** [webbukkit/dynmap#2910]
I have cave and flat map disabled, only surface enabled. When players go underground they vanish from the map, i would still like it to show their location

**Comment by otse** [comment]
I'm new to dynmap too, but I accidentally found this for you in configuration.txt, maybe its a fix

\#  \# Optional - make players hidden when they are inside/underground/in shadows (#=light level: 0=full shadow,15=sky)
\#  hideifshadow: 4

**Comment by Sylvamy** [comment]
> I'm new to dynmap too, but I accidentally found this for you in configuration.txt, maybe its a fix
> 
> # # Optional - make players hidden when they are inside/underground/in shadows (#=light level: 0=full shadow,15=sky)
> # hideifshadow: 4

For anyone else with this "issue", this is the fix, commented out hideifshadow and hideifundercover and it shows players, thanks for your help
