### ISSUE TITLE
Config option to restrict radius render maximum size.

### ISSUE THREAD

**Issue by mibby** [webbukkit/dynmap#2912]
Would it be possible to add a config option to restrict the radius render maximum size to allow others access to the command without concerns of them entering absurd radius sizes?

**Comment by otse** [comment]
I need a bit of info, first how can you allow others access to the command? Why not write and compile a simple server java that min maxes an integer for you?

**Comment by mibby** [comment]
What? Access to the command is given by the permission node. ``dynmap.radiusrender``

I'm requesting a configurable maximum so players can't type ``/dynmap radiusrender 5000000`` to crap up the update queue.

**Comment by ice-fly** [comment]
if configured properly, normal users shouldn't have the need to use `/dynmap radiusrender`
*I disagree with the need for this feature when there are plenty of bugs that need squashed.*

**Comment by mibby** [comment]
In most cases you are probably right, however there are always going to be lighting bugs caused by minecraft generation, dynmap rendering, or worldediting. 

Dynmap does not always pick up when the area is changed due to worldedit or manual fixing of light, so players and staff have access to the radiusrender command to re-render broken or outdated areas on the map. An option to restrict a maximum render size, whether that be by config option or permission integer such as ``dynmap.radiusrender.50`` is a nice safety net to have.

**Comment by FedUpWith-Tech** [comment]
worldedit render trigger is a feature that is planned that would fix this likely. I'll leave the issue open as a feature request but this specific implementation is not likely

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
