### ISSUE TITLE
Missing Wiki page for map configuration

### ISSUE THREAD

**Issue by T-x-T** [webbukkit/dynmap#2913]
At the bottom of https://github.com/webbukkit/dynmap/wiki/World-and-template-settings there is a link to map configuration which doesn't exist.
I also couldn't find any information on map configuration elsewhere, apart from the hd map config, which doesn't seem to include all configuration options.
Please add that page, as that would be of great help.

**Comment by FedUpWith-Tech** [comment]
I'm going to edit the wiki and update it once I finish consolidating the github issues. I'm almost done so the wiki should be done next week. I fixed this page so I'm going to close this issue now
