### ISSUE TITLE
dynmap only loads places where players are... (1.14.4)

### ISSUE THREAD

**Issue by promlgxd** [webbukkit/dynmap#2915]
when doing /dynmap fullrender it only loads places playes are or have been... idk what to do anymore... i tried filling with world border, turning chunk migrating on... nothing, the problem is still there. I also tried the --forceUpgrade thing with no results. What else can i do??
im running akarin (a paperspigot fork) on 1.14.4

**Comment by qantourisc** [comment]
Correct. You'd need to tell the minecraft server to generate the chunks. (I think you need a plugin to do this though.)
Dynmap cannot render chunks that have not been generated yet.

**Comment by T-x-T** [comment]
have you tried paper/spigot?

**Comment by FedUpWith-Tech** [comment]
maybe related to #3003
