### ISSUE TITLE
Dynmap has a white screen not a map.

### ISSUE THREAD

**Issue by SeasonedTrash** [webbukkit/dynmap#2916]
I have just set up my Dynmap but when I try to go to the web-map it is just a white screen here's the link: 142.44.215.204:9467
Thanks!

**Comment by T-x-T** [comment]
Are you using an external webserver? You get redirected to /index.html on your setup, that shouldnt happen AFAIK

**Comment by otse** [comment]
index.html is fine, mine does that too. You may have to chmod your files. Else try reinstall.

**Comment by SeasonedTrash** [comment]
What do you mean by chmod? sorry i am new to coding and computer-talk. thanks
And my server is being hosted by Shockbyte and I used their tutorial to set it up but they got a black screen on first time and they had to just render but that's not with mine

**Comment by T-x-T** [comment]
Do you have direct console access to the server? 
chmod changes the file permissions, as this might be a permission issue

**Comment by SeasonedTrash** [comment]
ok thanks! i will try that

**Comment by SeasonedTrash** [comment]
I do not think it was a permissions issue as I still have a white screen while opening
142.44.215.204:7689 this is the web page I am using and everything is set up
