### ISSUE TITLE
DynmapCore 3.0 maven

### ISSUE THREAD

**Issue by Martmists-GH** [webbukkit/dynmap#2917]
I seem to be unable to retrieve DynmapCore 3.0-beta-10 from various maven instances; mikeprimm's repository is outdated, jitpack seems to attempt to fetch a `DynmapCoreAPI-3.0-beta-10-all.jar`, and others are not responding.

**Comment by FedUpWith-Tech** [comment]
dynmap now uses gradle not maven. I need to update that doc but I haven't had time yet will do soon

**Comment by FedUpWith-Tech** [comment]
All references to maven have no been removed and the docs now reflect the gradle build
