### ISSUE TITLE
Failed to start WebServer - Adress has been taken by another server ??

### ISSUE THREAD

**Issue by Zhuull** [webbukkit/dynmap#2918]
[Server thread/ERROR]: [dynmap] Failed to start WebServer on address 62.210.45.52:8123 : Failed to bind to /62.210.45.52:8123

This plugin perfectly worked during 3 months, but I saw this error in log today.
The address has not changed (I bookmarked it) but when I try to launch it, it loads the map from a server that I don't know. It's like an other dynmap overrode mine or tooks the same IP adress ? :/

Do you know how to fix this ? 

![dynmap](https://user-images.githubusercontent.com/4500723/81352748-91f70c80-90c7-11ea-96c8-1338cad2e1fe.jpg)

**Comment by masterX244** [comment]
Are you on a shared hosting provider? Then another Dynmap instance of a different customer snatched the port. Thats also the reason why you see a entirely different map.

**Comment by Zhuull** [comment]
Ok, it seems that this was simply the cause. So I guess I just have to change the port config and everything will be ok..
Thank you.
