### ISSUE TITLE
How do I change the height?

### ISSUE THREAD

**Issue by Scheshi** [webbukkit/dynmap#2919]
I searched in issues and didn't find it.
I didn't find anything in the wiki that made sense either.
I need to increase the minimum height on the map, because I have this happening:
![image](https://user-images.githubusercontent.com/47576867/81427544-cbec0100-910f-11ea-9c84-b657315597c0.png)

**Comment by FedUpWith-Tech** [comment]
https://github.com/webbukkit/dynmap/wiki/Configuration-of-worlds#server-side-section
