### ISSUE TITLE
Slabs at level 255 render as partially transparent on both ISO 30 and flat (90)

### ISSUE THREAD

**Issue by RobinWhitfield** [webbukkit/dynmap#2921]
![image](https://user-images.githubusercontent.com/63362209/81472854-645ab200-91f2-11ea-85f4-7cf3dfed5608.png)
![image](https://user-images.githubusercontent.com/63362209/81472865-72a8ce00-91f2-11ea-8b74-dabca044d689.png)

**Comment by FedUpWith-Tech** [comment]
This should be fixed on the latest version, please reopen if this issue still persists.
