### ISSUE TITLE
Reduce size of dynmap

### ISSUE THREAD

**Issue by Bruhhmomentus** [webbukkit/dynmap#2922]
Okay so basically I messed up world border,and missed by like 5k blocks maybe even more Is there a way to reduce the size of dynmap here's the link http://149.56.182.18:8123/index.html  I just want that custom map in the centre everything other is something that I dont want to be shown

**Comment by T-x-T** [comment]
You can define visibility-limits on a per world basis: https://github.com/webbukkit/dynmap/wiki/World-and-template-settings
This means that only the blocks within these limits will get rendered.
After that you can do a fullrender, but Im not sure if that is necessary
