### ISSUE TITLE
Allow network segments in trusted-proxies

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#2923]
Right now, one can only specify a list of ip addresses for trusted-proxies. I run dynmap in a k8s cluster, and can't specify one, since it can change per each rollout. Instead, I'd like it to allow pass a CIDR such as 10.244.0.0/16. Notice you can still specify a single ip with a /32 suffix if desired

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
