### ISSUE TITLE
Map rendering fails

### ISSUE THREAD

**Issue by Martmists-GH** [webbukkit/dynmap#2924]
I'm working on a port to Fabric, and during testing I noticed that Dynmap fails to load the view with the following error:

![Screenshot_20200510_125016](https://user-images.githubusercontent.com/16361449/81497144-e44d4e80-92bc-11ea-8793-100f55759e4b.png)

![Screenshot_20200510_125148](https://user-images.githubusercontent.com/16361449/81497159-0941c180-92bd-11ea-840c-ccfd05daee5b.png)

**Comment by Martmists-GH** [comment]
Update: Having resolved the worlds issue, the map is still black (albeit with a few new elements) but console seems to spam the following: 
```
...
May 10, 2020 3:00:11 PM org.dynmap.Log verboseinfo
INFO: [Dynmap] Block minecraft:red_wall_banner[facing=south] - no texture mapping
May 10, 2020 3:00:11 PM org.dynmap.Log verboseinfo
INFO: [Dynmap] Block minecraft:red_wall_banner[facing=west] - no texture mapping
May 10, 2020 3:00:11 PM org.dynmap.Log verboseinfo
INFO: [Dynmap] Block minecraft:red_wall_banner[facing=east] - no texture mapping
May 10, 2020 3:00:11 PM org.dynmap.Log verboseinfo
INFO: [Dynmap] Block minecraft:black_wall_banner[facing=north] - no texture mapping
May 10, 2020 3:00:11 PM org.dynmap.Log verboseinfo
INFO: [Dynmap] Block minecraft:black_wall_banner[facing=south] - no texture mapping
May 10, 2020 3:00:11 PM org.dynmap.Log verboseinfo
INFO: [Dynmap] Block minecraft:black_wall_banner[facing=west] - no texture mapping
May 10, 2020 3:00:11 PM org.dynmap.Log verboseinfo
INFO: [Dynmap] Block minecraft:black_wall_banner[facing=east] - no texture mapping
```
![Screenshot_20200510_171818](https://user-images.githubusercontent.com/16361449/81503143-48363e00-92e2-11ea-909e-0caa5cbaf117.png)

**Comment by mikeprimm** [comment]
Your configuration.txt is bad - specifically the 'defaultmap:' setting.
