### ISSUE TITLE
[Feature Request] Add the ability to define visibility limits per map

### ISSUE THREAD

**Issue by T-x-T** [webbukkit/dynmap#2926]
You can define visibility limits for a world to render only certain locations. I would like to define such a limit only for the 3d view of my overworld as thats pretty huge (around 150GB+ for a 30k*30k world).
To me it seems like you can only set these limits for a world, not for a single map on that world.
Is there a workaround for this?

**Comment by rwtallant13** [comment]
I would very much like the same exact thing. Flat map for my entire rendered world and surface map just for home base. Very much would like to find a workaround or see this implemented.

**Comment by FedUpWith-Tech** [comment]
you can do this with the latest version and dmap or by editting the world.txt documentation on how to do this is in the wiki

**Comment by rwtallant13** [comment]
The visibility limits commands added in the latest update have always been available in worlds.txt, and unless I am mistaken do not work on a map by map basis but rather world by world. If mistaken can you point me to the page that shows how to do this?

**Comment by FedUpWith-Tech** [comment]
Here is info from the dev on how to do this per-world. Its always been able to be done in worlds.txt per world but only in the most recent version using dmap
```
/dmap worldgetlimits<world> - this returns the visibility and hidden limits for a world, as a single list with 'limittype' of visible or hidden, and the settings showing the shape's attributes

/dmap worldaddlimit <world> corner1:<x1>/<z1> corner2:<x2>/<z2> - this adds a visibility limit, shaped as a rectangle, from block coordinate x1, z1 to x2, z2.  You can add as many as you choose.

/dmap worldaddlimit <world> type:round center:<x>/<z> radius:<radius> - this adds a visibility limit, shaped as a circle, centered at block x, z and with radius <radius>.  You can add as many as you choose.

/dmap worldremovelimit <world> <index> - this removes the limit with index <index> (as shown in the list from /dmap worldgetlimits

When chunks are hidden, there is also a 'hiddenstyle' setting to control HOW this is done - options include 'air' (show the chunk as empty/undefined), 'stone' (show the chunk as a stone chunk of 64 height), or 'ocean' (show the chunk as water of 64 height).  To alter this, use:

/dmap worldaddlimit <world> style:<air|stone|ocean>
```

Edit: the wiki doesn't reflect this new info currently. I'm slowly updating the wiki and reformatting it to be readable

**Comment by T-x-T** [comment]
yes we are aware of that. But we want to be able to specify the visibility-limit on a per map basis so we can something like a 2d map for the entire world and then a 3d map for only a small section of the world
Btw thanks for working through the issues, really nice to see that the project gets actively brought forward through this again

**Comment by FedUpWith-Tech** [comment]
Okay I think I understand what you want now*. Let me do some digging

**Comment by FedUpWith-Tech** [comment]
After a minor amount of digging this may be possible using some hacky methods but none I would be comfortable recommending without testing myself (I don't have the time to test my theory yet). This would be an incredibly good candidate to add to the dmap command. maybe @mikeprimm can let us know if this is a reasonable feature request?

**Comment by robiworks** [comment]
Bump, is anything happening with this? It would be a great feature.

**Comment by atasak** [comment]
Truncating the 3d map would be a great way to save some server resources, on CPU as well as storage. I want to express my interest in this feature as well.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
