### ISSUE TITLE
Dynmap + Dynmap-PreciousStones.jar

### ISSUE THREAD

**Issue by Coldene** [webbukkit/dynmap#2928]
Hello, on Spigot comments for Dynmap https://www.spigotmc.org/threads/dynmap.8210/page-56 you may notice I recently attempted to fix this excellent dynmap/precious stones utility and ended up with a working version for PreciousStones 1.10 > 1.15.2 I just use ClassEditor, console error reports and spigot javadocs to try fix any minor issues and sometimes even broken plugins. I'm not a coder or java user. This plugin has not worked for MC 1.10+ since PreciousStones dev turned a /vectors folder into /fields back in 1.10. As you are the long time manager of this plugin I wonder if you would properly update this with a rebuilt version for 1.10+ that has the new class paths. My nooby fixed version works perfectly but stil throws the below error in console near end of startup.

`WARN java.lang.Exception: Error occurred detecting class name 
WARN at co.aikar.timings.MinecraftTimings.lambda$getPluginTaskTimings$0(MinecraftTimings.java:77) 
WARN at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324) 
WARN at co.aikar.timings.MinecraftTimings.getPluginTaskTimings(MinecraftTimings.java:71) 
WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.<init>(CraftTask.java:62) 
WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:214) 
WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:196) 
WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:191) 
WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:155) 
WARN at org.dynmap.preciousstones.DynmapPreciousStonesPlugin.activate(DynmapPreciousStonesPlugin.java:368) 
WARN at org.dynmap.preciousstones.DynmapPreciousStonesPlugin.onEnable(DynmapPreciousStonesPlugin.java:278) 
WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) 
WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) 
WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) 
WARN at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471) 
WARN at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385) 
WARN at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) 
WARN at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) 
WARN at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) 
WARN at java.lang.Thread.run(Thread.java:748) 
WARN Caused by: java.lang.IncompatibleClassChangeError: org.dynmap.preciousstones.DynmapPreciousStonesPlugin and org.dynmap.preciousstones.DynmapPreciousStonesPlugin$PreciousStonesUpdate disagree on InnerClasses attribute 
WARN at java.lang.Class.getDeclaringClass0(Native Method) 
WARN at java.lang.Class.getDeclaringClass(Class.java:1235) 
WARN at java.lang.Class.getEnclosingClass(Class.java:1277) 
WARN at java.lang.Class.getSimpleBinaryName(Class.java:1443) 
WARN at java.lang.Class.getSimpleName(Class.java:1309) 
WARN at java.lang.Class.isAnonymousClass(Class.java:1411) 
WARN at co.aikar.timings.MinecraftTimings.lambda$getPluginTaskTimings$0(MinecraftTimings.java:73)`

^ This one is probably my fault. Any tip how to fix it would be very handy. I am semi confident at rebuilding plugins from other plugins with Eclipse if have the source or a github address for Eclipse to import source from? Also, if you are not cool with people downloading an amature fixed version of Dynmap-PreciousStones from your Dynmap recent discussions (spigot), let me know and I will delete the post. Thank you for supporting MC. Millions of downloads. /salute

**Comment by FedUpWith-Tech** [comment]
This should be on the dynmap-preciousstones tracker
