### ISSUE TITLE
dynmap on hosting service

### ISSUE THREAD

**Issue by alex17lol** [webbukkit/dynmap#2929]
I have a server on one hosting service and a website on another hosting service and I want to use dynmap on my website without using Iframe 
I used this guide but it did not work out for me https://github.com/webbukkit/dynmap/issues/2609
and tried many others seems like ive searched all of github and google and still nothing
so maybe if someone knows someway for me to do that I will really appreciate it

**Comment by T-x-T** [comment]
The guide looks pretty good to me on first sight, where did you run into issues?

**Comment by alex17lol** [comment]
I don't have access to sudo commands and the issue is it does not work for web hosts try it yourself you will see

**Comment by ice-fly** [comment]
@alex17lol This is a problem with your webhost & not dynmap... Posting here is just going to annoy people. **It is possible to setup on a webhost,** but you have to be knowledgeable on apache htaccess files, php, & sql. From someone who has done it: It's a nightmare and you should just cough up the dough to buy a vps.
