### ISSUE TITLE
Mouse coordinates, Markers, and players do not show up on map

### ISSUE THREAD

**Issue by xHayvok** [webbukkit/dynmap#2932]
So I set up my worlds file to just be the default surface map (60 degree iso from the south west I think). Ever since I did this I haven't been able to get my mouse coordinates, markers, and players to show up on the map. I checked the configuration file to make sure all those things are turned on and they were. At this point I'm not able to find anything else through Google so hopefully someone can help me here. Thanks in advanced and let me know if you need and more files
[configuration.txt](https://github.com/webbukkit/dynmap/files/4627223/configuration.txt)
[worlds.txt](https://github.com/webbukkit/dynmap/files/4627224/worlds.txt)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
