### ISSUE TITLE
Dynmap fails to show many map areas 

### ISSUE THREAD

**Issue by adambash** [webbukkit/dynmap#2934]
Although I full rendered the world, only a small amount of it shows up. Is there a way to make the entire map show. Although my entire map is water based on the map it only shows small patches of land and water.

![image](https://user-images.githubusercontent.com/24509053/82110139-c8004600-96f0-11ea-8218-d6fffffb2412.png)

**Comment by masterX244** [comment]
how did you pregenerate the map? dynmap only renders chunks that exist on disk.
And if you upgraded the map from a older version to the new one MC only converts chunks on load and dynmap doesn't see unconverted chunks. Spigot has a launch parameter to fully upgrade all existing chunks

**Comment by Tsoccerguy3** [comment]
get worldborder plugin and run /wb fill , then /wb trim
