### ISSUE TITLE
Question:  possible to deaktivate all dynmap-render updates

### ISSUE THREAD

**Issue by RedstoneFuture** [webbukkit/dynmap#2935]
Is it possible to deactivate all kinds of updates / render of the map-tiles? The plugin may not to change the blocks in the map. But I would like see the live-position of the player still.

For example, I render a dynmap, then I deactivate  the updates. After this I would like delete a few chunks - without any dynmap-changes in the next days.

**Comment by Tsoccerguy3** [comment]
change the various block update events in the config to false

**Comment by RedstoneFuture** [comment]
@Tsoccerguy3 Do you mean this:

```
render-triggers:
  #- playermove
  #- playerjoin
  - blockplaced
  - blockbreak
  - leavesdecay
  - blockburn
  - chunkgenerated
  - blockformed
  - blockfaded
  - blockspread
  - pistonmoved
  - explosion
  #- blockfromto
  #- blockphysics
  - structuregrow
  - blockgrow
  #- blockredstone
```


-->
"render-triggers: []"

**Comment by ice-fly** [comment]
Yes, comment all those out... Or you can just do /dynmap pause all and never unpause
**Issue should be closed**

**Comment by RedstoneFuture** [comment]
Thank you! :) I will test it.
