### ISSUE TITLE
Card is flooded with black spots-Paper-Spigot Update Problem with Dynmap

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#2936]
Paper-Spigot:Paper version git-Paper-298 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Dynmap-Version: Dynmap-3.0-beta-10-spigot.jar

Since the update to Paper-Spigot Version 298 this morning, black spots have appeared on all loaded zones. If you try to render it again it will get worse instead of going away.
Is there a paper spigot update? before that everything was fine

I'll take the paper version again before the update Paper version git-Paper-284 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

the condition normalizes again and you can remove the black spots again with a radius render.

Therefore the problem must be in an update between the Paper-spigot version 284 -298.

I hope the problem can be found.

![dynmap](https://user-images.githubusercontent.com/35557302/82141071-ae1b4c00-9833-11ea-9c18-11f71f57ef20.png)

**Comment by Tsoccerguy3** [comment]
I just compilied the latest code for 3 RC1 , yes running a render corrupts the maps .
rolling back to last snapshot . I would say that latest code breaks things

**Comment by pKai3** [comment]
Yep, another confirmation here if it means anything to ya.

![image](https://user-images.githubusercontent.com/1890978/82168214-163d5280-9873-11ea-9ff2-1970efca835b.png)

**Comment by Blueeyestar** [comment]
The problem has been reported to Paper. This was also classified as a bug. They are good at what they do, they will fix it again :)


https://github.com/PaperMC/Paper/issues/3386

**Comment by Tsoccerguy3** [comment]
get latest dynmap here , https://dynmap.us/builds/dynmap/ ,

Dynmap-3.0-RC2-spigot.jar

**Comment by pKai3** [comment]
Beautiful, thank you so much!

**Comment by Blueeyestar** [comment]
Thanks the new version works fine
