### ISSUE TITLE
Dynmap iframe http

### ISSUE THREAD

**Issue by alex17lol** [webbukkit/dynmap#2937]
I have a webhost which means I dont have access to sudo commands and I cant use reverse proxy.
My website has https and dynmap uses http so when I try to use iframe to display dynmap its not work
My main goal is to get dynmap working without using the ip:port to access the dynmap I want it to be displayed on my website like mywebsite.com/map/ but its not that easy when you don't have vps
any help?

**Comment by ice-fly** [comment]
**You can't do it...** 
Trust me, I know you're trying to avoid doing the complicated process but it needs to be done.

**Comment by ice-fly** [comment]
Duplicate of #2929 
**Should be closed**
