### ISSUE TITLE
Unsure if Worldborder fill or Dynmap rendering glitch.

### ISSUE THREAD

**Issue by UnsoIved** [webbukkit/dynmap#2942]
I have rendered a 10k block radius. And now when I look at dynmap its a huge unrendered square.
![Screenshot_11](https://user-images.githubusercontent.com/64069825/82372326-a93fcf00-99d0-11ea-8d4b-0dc0e311819d.png)
This spreads up more around.

**Comment by Tsoccerguy3** [comment]
get latest dynmap here , https://dynmap.us/builds/dynmap/   , 

Dynmap-3.0-RC2-spigot.jar

**Comment by ice-fly** [comment]
Paper fixed: https://github.com/PaperMC/Paper/issues/3386
