### ISSUE TITLE
Web server doesnt work

### ISSUE THREAD

**Issue by Jolunas** [webbukkit/dynmap#2944]
just stops workin, ive configured the "saber factions" plugin so the dynmap just stops work.

20.05 14:54:32 [Server] Server thread/INFO [dynmap] Enabling dynmap v3.0-beta-10-257
20.05 14:54:33 [Server] Server thread/INFO [dynmap] Using LuckPerms 5.0.72 for access control
20.05 14:54:33 [Server] Server thread/INFO [dynmap] Mod Support processing completed
20.05 14:54:33 [Server] Server thread/ERROR [dynmap] Could not load colors 'default' ('plugins/dynmap/colorschemes/default.txt'): File not found.
20.05 14:54:33 [Server] INFO java.io.FileNotFoundException: plugins/dynmap/colorschemes/default.txt (No such file or directory)
20.05 14:54:33 [Server] INFO at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_40]
20.05 14:54:33 [Server] INFO at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_40]
20.05 14:54:33 [Server] INFO at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_40]
20.05 14:54:33 [Server] INFO at org.dynmap.ColorScheme.loadScheme(ColorScheme.java:82) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.ColorScheme.getScheme(ColorScheme.java:50) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.hdmap.DefaultHDShader.<init>(DefaultHDShader.java:34) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_40]
20.05 14:54:33 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_40]
20.05 14:54:33 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_40]
20.05 14:54:33 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_40]
20.05 14:54:33 [Server] INFO at org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:328) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:342) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.hdmap.HDMapManager.loadHDShaders(HDMapManager.java:36) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.MapManager.<init>(MapManager.java:1000) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.DynmapCore.enableCore(DynmapCore.java:507) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:930) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:910) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
20.05 14:54:33 [Server] Server thread/ERROR [dynmap] Could not load colors 'ovocean' ('plugins/dynmap/colorschemes/ovocean.txt'): File not found.
20.05 14:54:33 [Server] INFO java.io.FileNotFoundException: plugins/dynmap/colorschemes/ovocean.txt (No such file or directory)
20.05 14:54:33 [Server] INFO at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_40]
20.05 14:54:33 [Server] INFO at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_40]
20.05 14:54:33 [Server] INFO at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_40]
20.05 14:54:33 [Server] INFO at org.dynmap.ColorScheme.loadScheme(ColorScheme.java:82) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.ColorScheme.getScheme(ColorScheme.java:50) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.hdmap.DefaultHDShader.<init>(DefaultHDShader.java:34) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_40]
20.05 14:54:33 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_40]
20.05 14:54:33 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_40]
20.05 14:54:33 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [?:1.8.0_40]
20.05 14:54:33 [Server] INFO at org.dynmap.ConfigurationNode.createInstance(ConfigurationNode.java:328) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.ConfigurationNode.createInstances(ConfigurationNode.java:342) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.hdmap.HDMapManager.loadHDShaders(HDMapManager.java:36) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.MapManager.<init>(MapManager.java:1000) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.DynmapCore.enableCore(DynmapCore.java:507) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.doEnable(DynmapPlugin.java:930) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:910) [Dynmap-3.0-beta-10-spigot.jar:?]
20.05 14:54:33 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:267) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
20.05 14:54:33 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
20.05 14:54:33 [Server] Server thread/ERROR [dynmap] Could not load colors 'flames' ('plugins/dynmap/colorschemes/flames.txt'): File not found.
20.05 14:54:33 [Server] INFO java.io.FileNotFoundException: plugins/dynmap/colorschemes/flames.txt (No such file or directory)
20.05 14:54:34 [Multicraft] Skipped 93 lines due to rate limit (60/s)
20.05 14:54:34 [Server] Server thread/INFO [dynmap] Enabled
20.05 14:54:34 [Server] Server thread/INFO [Factions] Enabling Factions v1.6.9.5-2.3.5-RC
20.05 14:54:34 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] ==== Setup ====
20.05 14:54:34 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] Minecraft Version 1.15 found.
20.05 14:54:34 [Server] Server thread/INFO File was not found for players.json, assuming there is no need to migrate old players.json file.
20.05 14:54:34 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] ==== End Setup ====
20.05 14:54:34 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] === ENABLE START ===
20.05 14:54:34 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] Loaded 11 players
20.05 14:54:34 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] Loaded 4 Factions
20.05 14:54:34 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] Loading board from disk
20.05 14:54:34 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] Loaded 18 board locations
20.05 14:54:35 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] CoreProtect not found, disabling Inspect
20.05 14:54:35 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] Enabling FactionsTop command, this is a very basic /f top please get a dedicated /f top resource if you want land calculation etc.
20.05 14:54:35 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] Economy integration is disabled, and the plugin "Vault" is not hooked into an economy plugin.
20.05 14:54:35 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] Minecraft Version 1.9 or higher found, using non packet based particle API
20.05 14:54:35 [Server] Server thread/INFO [SABER-FACTIONS] - Loaded 1 timers into list!
20.05 14:54:35 [Server] Server thread/INFO [Factions] [1.6.9.5-2.3.5-RC] === ENABLE DONE (Took 896ms) ===
20.05 14:54:35 [Server] Server thread/INFO Server permissions file permissions.yml is empty, ignoring it
20.05 14:54:35 [Server] Startup Done (8.239s)! For help, type "help"
20.05 14:54:35 [Server] Craft Scheduler Thread - 5/INFO [Vault] Checking for Updates ... 
20.05 14:54:35 [Server] Dynmap Render Thread/INFO [dynmap] Texture pack not found - plugins/dynmap/texturepacks/standard
20.05 14:54:35 [Server] Dynmap Render Thread/INFO [dynmap] Loading default resource pack

**Comment by Jolunas** [comment]
I use virtus host. a090m.virtushost.net:8123

**Comment by ice-fly** [comment]
False, webhost works...
User config error:  `20.05 14:54:33 [Server] Server thread/ERROR [dynmap] Could not load colors 'default'`

**Comment by Jolunas** [comment]
So, how i fix it?

**Comment by ice-fly** [comment]
Rename dynmap folder to something else.

**Comment by Jolunas** [comment]
I will try it, ty

**Comment by Jolunas** [comment]
Did not work

**Comment by ice-fly** [comment]
Then re-download dynmap jar cause I'm not getting a `java.io.FileNotFoundException`

**Comment by mikeprimm** [comment]
Looks like something is breaking resource loading using the class loader, or has broken the default current working directory of the MC process - not a dynmap issue: need to talk to whichever plugin guys are breaking it (if that is the 'saber factions' plugin you mentioned, you'll need to talk to them).  Other thing would be a file permissions issue - check if the plugins/dynmap/colorschemes directory exists and has the indicated files - if not, you'll probably need to reinstall (although, you can try zapping the version.txt file and restarting the server, in order to drive Dynmap to refresh its extracted files).
