### ISSUE TITLE
Dynmap + AntiqueAtlas Textures

### ISSUE THREAD

**Issue by 1337god** [webbukkit/dynmap#2946]
I stumbled upon https://github.com/AntiqueAtlasTeam/AntiqueAtlas/issues/86 where the author says "If dynmap allows using custom tiles in this way, then feel free to use our textures to implement this idea by yourself."
Is it possible to use Custom Tiles for Dynmap?

Dynmap looking like this on the flat would look pretty awesome.
![image](https://user-images.githubusercontent.com/18701229/82554383-b76f2600-9b5d-11ea-88d8-fef475b81d58.png)

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
