### ISSUE TITLE
cannot access configuration

### ISSUE THREAD

**Issue by Sylvamy** [webbukkit/dynmap#2947]
Ill start off by saying im not the best with linux servers so this could just be me
When i try and visit my map, hosted on my apache server i get the error
Could not retrieve configuration: Forbidden
This error started appearing after i changed to a Multicraft control panel, i have tried giving every folder involved (server, server plugins, map, public html) the right permissions, tried giving them 777, tried adding the multicraft user, nothing seems to work, please help

**Comment by ice-fly** [comment]
If it's webserver, Check your apache config/htaccess
If it' standalone check database is accessible with the login config
Check php modules
