### ISSUE TITLE
Rendering but the webserver doesnt work

### ISSUE THREAD

**Issue by Jolunas** [webbukkit/dynmap#2949]
Im rendering the map again, after delete the plugin to make it work, but the web server still dont work
![Sem título](https://user-images.githubusercontent.com/65680743/82739714-df9e8680-9d0f-11ea-9d55-557056bdae1b.png)
![Sem título2](https://user-images.githubusercontent.com/65680743/82739721-ecbb7580-9d0f-11ea-83c5-b81a1d90fc99.png)

**Comment by FedUpWith-Tech** [comment]
This is likely due to your server host host not forwarding that port. You will have to open a ticket with them to get a port open for dynmap
