### ISSUE TITLE
dynmap black page

### ISSUE THREAD

**Issue by 73u38** [webbukkit/dynmap#2955]
got error on browser console. and giving back page. this console says

Loading failed for the <script> with source “http://122.248.32.237:8123/standalone/config.js?_=3.0-SNAPSHOT-321”.

ReferenceError: config is not defined122.248.32.237:8123:43:1
    <anonymous> http://122.248.32.237:8123/:43
    jQuery 4

my index.html

<!DOCTYPE html>
<html lang="en">
<head>

	<title>Minecraft Dynamic Map</title>

	<meta charset="utf-8" />
	<meta name="keywords" content="minecraft, map, dynamic" />
	<meta name="description" content="Minecraft Dynamic Map" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
	
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />	

	<link rel="icon" href="images/dynmap.ico" type="image/ico" />

	<script type="text/javascript" src="js/jquery-1.11.0.js?_=3.0-SNAPSHOT-321"></script>
	<link rel="stylesheet" type="text/css" href="css/leaflet.css?_=3.0-SNAPSHOT-321" />
	<script type="text/javascript" src="js/leaflet.js?_=3.0-SNAPSHOT-321"></script>

	<script type="text/javascript" src="js/custommarker.js?_=3.0-SNAPSHOT-321"></script>

	<script type="text/javascript" src="js/dynmaputils.js?_=3.0-SNAPSHOT-321"></script>
	<script type="text/javascript" src="js/sidebarutils.js?_=3.0-SNAPSHOT-321"></script>

	
	<link rel="stylesheet" type="text/css" href="css/standalone.css?_=3.0-SNAPSHOT-321" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/dynmap_style.css?_=3.0-SNAPSHOT-321" media="screen" />
	

	<script type="text/javascript" src="version.js?_=3.0-SNAPSHOT-321"></script>
	<script type="text/javascript" src="js/jquery.json.js?_=3.0-SNAPSHOT-321"></script>
	<script type="text/javascript" src="js/jquery.mousewheel.js?_=3.0-SNAPSHOT-321"></script>
	<script type="text/javascript" src="js/minecraft.js?_=3.0-SNAPSHOT-321"></script>
	<script type="text/javascript" src="js/map.js?_=3.0-SNAPSHOT-321"></script>
	<script type="text/javascript" src="js/hdmap.js?_=3.0-SNAPSHOT-321"></script>
	<script type="text/javascript" src="standalone/config.js?_=3.0-SNAPSHOT-321"></script>

	<script type="text/javascript">
			$(document).ready(function() {
				window.dynmap = new DynMap($.extend({
					container: $('#mcmap')
				}, config));
			});
	</script>

</head>
<body>
<noscript>
 For full functionality of this site it is necessary to enable JavaScript.
 Here are the <a href="http://www.enable-javascript.com/" target="_blank">
 instructions how to enable JavaScript in your web browser</a>.
</noscript>

	<div id="mcmap"></div>
</body>
</html>

anyone can help?

**Comment by lastsamurai26** [comment]
i have the Same problem.

**Comment by kbulgrien** [comment]
I am having the same issue (spigot 1.15.2, Dynmap 3.0 RC2).  json files are not being created for use on the standalone server.

**Comment by jacon500** [comment]
> For full functionality of this site it is necessary to enable JavaScript. Here are the [instructions how to enable JavaScript in your web browser](http://www.enable-javascript.com/).

There's your answer.

**Comment by lastsamurai26** [comment]
I have tested 5 different browsers and computers and Javascript is active everywhere ... 
I already have a map that works .... 
now I have a new MC Server and wanted a new card, but this one does not work

**Comment by 73u38** [comment]
sadly thing. my java script already on. and still black page

**Comment by lastsamurai26** [comment]
It seems that a Config.js is not created the first time the server is started

**Comment by lastsamurai26** [comment]
i have now tested it with different versions and servers Sponge, Bukkit and Forge all versions do not create this config

**Comment by lastsamurai26** [comment]
Do you use your own internal web server or an external one ? 

which version do you use?
MC
Server
dynmap 

maybe i have the solution

**Comment by FedUpWith-Tech** [comment]
99% of time this is a permissions issue and not a dynmap issue
