### ISSUE TITLE
Gaps in generated dynmap

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#2957]
Hi so i generated dynmap with cmd "dynmap fullrender" and these gaps are on the screen. Any possible fix for this?
![image](https://user-images.githubusercontent.com/55282950/83559808-78ee4980-a515-11ea-9f7f-9cc5731116ab.png)

**Comment by T-x-T** [comment]
seems like you are using worldborder, this isnt a dynmap issue, but a worldborder issue.
Use the same command used the pregen just with true at the end. This will make sure that all gaps get properly generated

**Comment by FedUpWith-Tech** [comment]
Related to #2485
