### ISSUE TITLE
Dynmap is no longer updating marker files

### ISSUE THREAD

**Issue by Brokkonaut** [webbukkit/dynmap#2958]
the marker files for the dynmap are no longer updated in the latest snapshots, so they will never update on the client.

**Comment by FedUpWith-Tech** [comment]
related to #1936

**Comment by Brokkonaut** [comment]
I cannot reproduce this bug any more in the most recent builds, so I think it was fixed sometime after my report.

**Comment by FedUpWith-Tech** [comment]
cool glad its fixed!
