### ISSUE TITLE
Clicking players in web map sidebar not working

### ISSUE THREAD

**Issue by kbulgrien** [webbukkit/dynmap#2962]
After updating dynmap to 3.0 RC2 and switching to using a remote MySQL database and web server, it is often no longer possible to click on a player in the side-bar to auto-zoom to their location on a map.  When this happens, the player name is "greyed" out.  As far as I recall, it was never a thing that it wasn't possible to click the player to locate them on the map.  The players are not using invisibility potions.  Usually I also cannot browse the maps and locate the player, though at one time, by fiddling around with zoom/unzoom I could sometimes see their heads on the map.  At first I thought it might be related to having to let fullrender complete, but it occurs even when all maps are fully rendered.

One of my players thinks this occurs when the player is underground.

**Comment by kbulgrien** [comment]
Still having this issue with 3.0.1.  If the player is above ground, it is possible to click and zoom to them.

**Comment by FedUpWith-Tech** [comment]
if a player is greyed out that means they are "hidden" they may have run `/dynmap hide` or are in another dimension than the currently viewed map. Not being able to click to them to track them is expected and intended behavior, Make sure those players have not run /dynmap hide and  are not hidden by another method you may have set in the config
