### ISSUE TITLE
Smooth Stone Uses Old Filename in 1.13+

### ISSUE THREAD

**Issue by yurisuika** [webbukkit/dynmap#2963]
Uses "stone_slab_top" instead of "smooth_stone" when rendering from texturepacks.

Perhaps also the slab uses "stone_slab_side" instead of "smooth_stone_slab_side", but I haven't tested that yet.

I first noticed this probably in 1.13 on Spigot up to 1.15.2, and see it still does this on the v3 release for Forge 1.15.2 from today.

**Comment by FedUpWith-Tech** [comment]
Fixed in latest version
