### ISSUE TITLE
Does every user in a forge server have to have the dynmap mod downloaded?

### ISSUE THREAD

**Issue by Wesley51** [webbukkit/dynmap#2964]
The server has been up for a while and it will be a hassle if I have to have every user running it since some of the players aren't experienced with Minecraft and Forge

**Comment by kbulgrien** [comment]
dynmap is a server process that has to run on the server where the map files are stored.  Users view the dynmap generated maps with a browser (not the minecraft client), so they don't need a mod to view the maps.
