### ISSUE TITLE
Render Issue

### ISSUE THREAD

**Issue by LordMike1** [webbukkit/dynmap#2967]
I have tried to get Dynmap to display the whole map at once, without the need for a user to be present in a chunk for it to load onto the website.

I have tried doing /dynmap fullrender <worldname>, I have also tried to do /wb fill and /wb trim in every combination I could think of and nothing has worked.

I don't know if this is even possible at this point. I opened 3 or 4 tickets with my server host and each time the issue wasn't fixed.

Let me know if you need any details or info! Oh and this has happened on a previous server I made but I didn't want to reveal the whole map at once so it was ok.

**Comment by FedUpWith-Tech** [comment]
What version was this map craeted on?
