### ISSUE TITLE
standalone/config.js is not being generated

### ISSUE THREAD

**Issue by Fish1** [webbukkit/dynmap#2968]
`(index):43 Uncaught ReferenceError: config is not defined
    at HTMLDocument.<anonymous> ((index):43)
    at fire (jquery-1.11.0.js?_=3.0-SNAPSHOT-338:3099)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.js?_=3.0-SNAPSHOT-338:3211)
    at Function.ready (jquery-1.11.0.js?_=3.0-SNAPSHOT-338:3423)
    at HTMLDocument.completed (jquery-1.11.0.js?_=3.0-SNAPSHOT-338:3453)`

`GET http://yapms.net/minecraft/standalone/config.js?_=3.0-SNAPSHOT-338 net::ERR_ABORTED 404 (Not Found)`

I get these errors when trying to access the server via browser. The webpage is black. standalone/config.js does not exist.

**Comment by lastsamurai26** [comment]
Same error here 

https://github.com/webbukkit/dynmap/issues/2955

**Comment by Fish1** [comment]
The error went away and config.js was generated. I have no idea if I did something to fix it, or if it just sorted itself out.

**Comment by lastsamurai26** [comment]
strange :( I can't get it generated

**Comment by Fish1** [comment]
All I did was reset the server a few times, delete the plugin a few times, and waited a few hours.

**Comment by mikeprimm** [comment]
This is usually a permissions issue - either the user account running the MC server not having write permission to the target directory, or the web server not having the necessary permission to read it.

**Comment by lastsamurai26** [comment]
I'm not using the internal server and I had switch 
from 
 - class: org.dynmap.InternalClientUpdateComponent

to
  - class: org.dynmap.JsonFileClientUpdateComponent


then that worked for me

**Comment by mikeprimm** [comment]
That is a big one - the two different 'class' settings there are for the internal server versus the external (JSON file) based support, so no JsonFileClientUpdateComponent, no files for an external server to use.
