### ISSUE TITLE
[Feature Request] Update Leaflet to allow canvas layer

### ISSUE THREAD

**Issue by kaiserproger** [webbukkit/dynmap#2970]
Hello,
I'm trying to use canvas instead of svg to draw areas, because of low performance. But, I have one problem: leaflet canvas doesn't work, Google said it's happening due to Leaflet's old version. Can you update Leaflet library? We've tried to do that, but Dynmap web code have some incompatibilities with new Leaflet version(for example, in utils).

**Comment by FedUpWith-Tech** [comment]
This is a bit bigger of a feature than the dev is currently looking to implement. If someone made a PR with this change it may be accepted but for now there are no plans to change the leaflet library version

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.

**Comment by FedUpWith-Tech** [comment]
Sorry for the delay but this feature request was implemented in #3467 by @JLyne we are now running Leaflet 1.7.1 which means canvas layer additions should now be possible 😊
