### ISSUE TITLE
Not Rendering

### ISSUE THREAD

**Issue by monktin** [webbukkit/dynmap#2971]
Dynmap is one of the most important plugins for what I'm going on my server but I can't it to render. I've tried everything. I /wb fill > /dynmap fullrender earth twice and it lasts for about 20 minutes when it's a huge map and should take hours. My border is fine, it's where i want it and each side is correct and it's visible in the map online. Some places I've tped are really messily rendered but it showed up hours after. Now when I do /dynmap radiusrender 500 it loads a small square and stops. I've uninstalled and installed and it's up to date but I can't get the thing to render. I've also tried flying around and walking and nothing.

**Comment by Sk8nkillDT** [comment]
+1 Same exact issue I am having.

**Comment by monktin** [comment]
> +1 Same exact issue I am having.

monktin#4598 found a solution

**Comment by ClayCoffee** [comment]
+1

**Comment by Pulz-TCP** [comment]
> > +1 Same exact issue I am having.
> 
> monktin#4598 found a solution

If you have a solution, post here or close your issue please.
