### ISSUE TITLE
Ability to control when player locations are updated

### ISSUE THREAD

**Issue by hamletateham** [webbukkit/dynmap#2972]
I am wondering if it is possible to add a feature to this plugin. This feature would allow the ability to control the interval when player locations are updated. If possible, allow the user to set a different interval for different dimensions (Overworld, Nether, End). An example of this would be setting Dynmap to update player locations in the Overworld every 15 minutes, Nether instantly, and End every 60 minutes.

Thanks

**Comment by FedUpWith-Tech** [comment]
I know you can set the global player update limit in configuration.txt not sure if you can do them per world

**Comment by generrosity** [comment]
I'm going to go ahead and close this request. This might be better served as a plugin commissioned and created a coder, but from the description I am kinda unsure what difference updating player locations 15m vs 30m would make, and if making global player update limit 30m overall would solve the problem you are trying to fix.
