### ISSUE TITLE
Dynmap/Towny integration

### ISSUE THREAD

**Issue by ElCobraBoss** [webbukkit/dynmap#2975]
After i installed the Dnymap - Towny 0.80 i get alot of errors in the consolo; its the same error, but it generates 12 lines of error, and one line for every town, every 15 seconds, so it happens to be too much spam in the console.

How could i possible fix this?

**Error:**
_INFO error adding area marker Alcatraz__0
INFO error adding area marker Akihabara__0
INFO error adding area marker Los__0
INFO error adding area marker oofie__0
INFO error adding area marker SafeHaven__0
INFO error adding area marker TyroN__0
INFO error adding area marker HypeTown__0
INFO error adding area marker Harkadia__0
INFO error adding area marker Gorordos__0
INFO error adding area marker Bod_0
WARN Plugin Dynmap-Towny v0.80 generated an exception while executing task 86
INFO java.lang.NoSuchMethodError: 'java.util.Map com.palmergames.bukkit.towny.TownyUniverse.getTownsMap()'
INFO at org.dynmap.towny.DynmapTownyPlugin.updateTownBanks(DynmapTownyPlugin.java:385) ~[?:?]
INFO at org.dynmap.towny.DynmapTownyPlugin.access$3(DynmapTownyPlugin.java:384) ~[?:?]
INFO at org.dynmap.towny.DynmapTownyPlugin$TownyUpdate.run(DynmapTownyPlugin.java:310) ~[?:?]
INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-334]
INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-334]
INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-334]
INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
INFO at java.lang.Thread.run(Thread.java:834) [?:?]_

**Comment by mikeprimm** [comment]
Need to talk to the Dynmap-Towny folks - I handed off this plugin a couple of years ago.  It looks like the version of Dynmap-Towny you are running does not match the version of Towny you are using.
