### ISSUE TITLE
block-id-alias not functional

### ISSUE THREAD

**Issue by dfsek** [webbukkit/dynmap#2978]
I have been trying to configure block-id-alias to have the plugin not render certain blocks. Here's my config:
```yaml
block-id-alias:
  "minecraft:white_stained_glass": "minecraft:air"
  "minecraft:quartz_pillar": "minecraft:air"
  "minecraft:chiseled_quartz_block": "minecraft:air"
  "minecraft:quartz_slab": "minecraft:air"
  "minecraft:smooth_quartz_slab": "minecraft:air"
  "minecraft:smooth_quartz_stairs": "minecraft:air"
  "minecraft:smooth_quartz": "minecraft:air"
  "minecraft:quartz_block": "minecraft:air"
```
There is no change at all when I reload the plugin/restart my server. I have also tried using the numerical IDs (which became deprecated as of 1.13), and those do not work either. Note that this is also not an issue with attempting to render blocks as air, as the below config gave no results either:
```yaml
block-id-alias:
  "minecraft:white_stained_glass": "minecraft:stone"
  "minecraft:quartz_pillar": "minecraft:stone"
  "minecraft:chiseled_quartz_block": "minecraft:stone"
  "minecraft:quartz_slab": "minecraft:stone"
  "minecraft:smooth_quartz_slab": "minecraft:stone"
  "minecraft:smooth_quartz_stairs": "minecraft:stone"
  "minecraft:smooth_quartz": "minecraft:stone"
  "minecraft:quartz_block": "minecraft:stone"
```

Dynmap version: core=3.0-SNAPSHOT-338, plugin=3.0-SNAPSHOT-338
Paper version: git-Paper-325 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Installed Plugins: BetterEnd, dynmap*, LibsDisguises, MythicMobs, ProtocolLib, WorldBorder, WorldEdit

My apologies if I am setting something up incorrectly, I could simply find no documentation other than the outdated documentation included in the config.

**Comment by mikeprimm** [comment]
Apologies for this - when I migrated it from numbers to names, I failed to update the examples in configuration.txt.  Try the same format as you have, but with block-alias as the section name.

**Comment by dfsek** [comment]
This worked for me, thanks!

**Comment by dfsek** [comment]
This should be left open until documentation is added, as it is basically a documentation issue now, I presume?

**Comment by mikeprimm** [comment]
It's been added to all the configuration.txt base files, so I think we're good
