### ISSUE TITLE
Can't cast Super_Perms to RegisteredServiceProvider

### ISSUE THREAD

**Issue by aurorasmiles** [webbukkit/dynmap#2979]
https://github.com/webbukkit/dynmap/blob/e38b1fc6324f68535010cb6e8fc29fb14f09fc20/spigot/src/main/java/org/dynmap/bukkit/permissions/VaultPermissions.java#L52

https://waste.cutiepie.at/unjw8408ojd994f

**Comment by generrosity** [comment]
Heya @aurorasmiles - are you a coder who is working on details, or is this just as a regular user of dynmap?

There is usually a bunch of info that we suggest adding into the bug requests. Also, we have a new release which might even fix things. We are also getting our 'not really supported' list polished up, incase this is a specific mod that is doing things differently

**Comment by JurgenKuyper** [comment]
closing due to lack of input from the user
