### ISSUE TITLE
problem with webchat 

### ISSUE THREAD

**Issue by xana43** [webbukkit/dynmap#2981]
Dynmap version: 3.0.1
Situation: 
          Main server: running on a purpose built windows machine (Paper-353, Minecraft 1.15.2)
          Dynmap web server: running on a Raspberry Pi 4
Expected behavior:
When someone types in the webchat, both the players on the server and the players viewing the map should see the message formatted as [WEB]<Player Name>: 'Message'
Issue:
      Whenever someone types in the webchat only the players in-game and the console can see the intended message. it doesn't do this if the dynmap is being served on the same machine as the server
Error reported by the console:
    https://pastebin.com/LRy3a8xs

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
