### ISSUE TITLE
Dynmap run on USB

### ISSUE THREAD

**Issue by DubblePumper** [webbukkit/dynmap#2982]
hey, i have a low storage server and would like to use dynmap. Is there a possibility to run dynmap on a USB / disk?

**Comment by bananasmoothii** [comment]
no.

**Comment by DubblePumper** [comment]
is there any other way to run it

**Comment by bananasmoothii** [comment]
Dynmap needs to be in the "plugins" folder, if it's taking too much place, you can try to lower the resolution, remove some maps (don't forget to remove the files), and I'm not sure if that works but set the storage system to SQLite. If you have MySQL, then I think this will be helpful for you.

**Comment by DubblePumper** [comment]
okay thanks I'm going to inform myself about it thnx

**Comment by RobinWhitfield** [comment]
I don't know whether there would be any issues moving the dynmap plugin (or simply the tiles) to an external location with a symbolic link, but I'd definitely not be recommending doing so.

**Comment by Crousus** [comment]
Change from png to jpg in the configuration. Small loss of details but massively less storage required

**Comment by RobinWhitfield** [comment]
> Change from png to jpg in the configuration. Small loss of details but massively less storage required

Just to note that this is now the default option in the config.
