### ISSUE TITLE
Conquest Reforged Dynmap

### ISSUE THREAD

**Issue by Regisoo** [webbukkit/dynmap#2983]
How do i add textures from Conquest Reforged mod to dynmap?
Thx for answering

**Comment by bananasmoothii** [comment]
This isn't supported yet, but it's coming soon

**Comment by jaz-on** [comment]
@Regisoo Hava a look at this it works for me on my server (spongeforge 1.12.2):
https://www.reddit.com/r/Dynmap/comments/h9qlve/dev_builds_of_dynmapblockscan_for_forge_1132_1144/

**Comment by FedUpWith-Tech** [comment]
This can be done with dynmap blockscan
