### ISSUE TITLE
Dynmap Fullrender Problem

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#2988]
I have a little problem and I hope someone can help me here.

Since 1.15 we have always had a corner on the Dynmap that is rendered incorrectly.

it does not render smoothly on the spot but always makes a notch.

Even if I delete the complete dynmap folder and let everything render again, the same problem arises at exactly the same place.

everything else is fabulously round. Does anyone know the problem that it always causes the same problem in the same place?

![map](https://user-images.githubusercontent.com/35557302/85455122-e4b85500-b59d-11ea-9688-3af512bfbc05.png)

**Comment by bananasmoothii** [comment]
I don't think this problem is related to dynmap. Dynmap just renders existing chunks, so I think these chunks just exist and you have to delete them and rerender your map if you want to get rid of them.

**Comment by Blueeyestar** [comment]
So I should delete the chunk where the errors always appear so that they can regenerate?

**Comment by KarlOfDuty** [comment]
Yes, delete those chunks in the world files and re-render the area and dynmap should remove them.

**Comment by Blueeyestar** [comment]
If so, the question is what chunk is it? this place is at -3371 3388 how do I get the name of the chunk out?
in which folder can I find the chunks?

**Comment by KarlOfDuty** [comment]
https://dinnerbone.com/minecraft/tools/coordinates/

In your world folder, idk the best way to do it, either delete the region file or edit it with an nbt editor.

**Comment by Blueeyestar** [comment]
Thank you so much. I'll test it out and let you know :)

**Comment by Blueeyestar** [comment]
it really helped. Good that nothing was built in the chunk. Otherwise the problem would not have been repairable. Thanks for the hint

**Comment by bananasmoothii** [comment]
If you're using the WorldBorder plugin, it has a command to delete chunks outside the worldborder
