### ISSUE TITLE
Pistons not rendering correctly in 1.15.2

### ISSUE THREAD

**Issue by griverat** [webbukkit/dynmap#2991]
Pistons, either sticky or regular, will show as a black block in the flat and surface view.

Tested with pistons facing multiple directions and two different perspectives.

<details>
<summary> In-game view </summary>

![image](https://user-images.githubusercontent.com/23618263/85906117-f9316300-b7d2-11ea-9326-1157baa3f29d.png)

</details>

<details>
<summary> Flat view </summary>

![image](https://user-images.githubusercontent.com/23618263/85906165-16663180-b7d3-11ea-83b8-0fb7d0b7885f.png)

</details>

<details>
<summary> Surface view </summary>

![image](https://user-images.githubusercontent.com/23618263/85906172-1e25d600-b7d3-11ea-8e2f-120f06bad9c3.png)
![image](https://user-images.githubusercontent.com/23618263/85906181-24b44d80-b7d3-11ea-8264-9ad68e6830ca.png)
</details>

> dynmap version
Dynmap version: core=3.0-SNAPSHOT-338, plugin=3.0-SNAPSHOT-338

Tested in Paper-355

Also tested in a freshly stated Spigot 1.15.2 server using dynmap as the sole plugin, the same issue is present.

**Comment by RobinWhitfield** [comment]
Why are you running such an old version of dynmap?

Can you try with the latest build?
(http://dynmap.us/builds/dynmap/)

**Comment by griverat** [comment]
That was latest at the time of writing. I'll test with the 1.16 version

Taken from the spigot thread:

![image](https://user-images.githubusercontent.com/23618263/85953301-09615380-b935-11ea-9ef3-9b29a41af486.png)

**Comment by RobinWhitfield** [comment]
Ahh yes, forgot about the hotfix internal naming.


I can confirm that the issue is present on 1.16.1 with 3.1-beta-1-367

**Comment by mikeprimm** [comment]
Check latest dev build - 382 or later (v3.1-SNAPSHOT)
