### ISSUE TITLE
1.16.1 bug with plugin version and webfiles

### ISSUE THREAD

**Issue by mmuziek** [webbukkit/dynmap#2993]
Web files are not matched with plugin version: All files need to be same version (3.0-SNAPSHOT-338) - try refreshing browser cache (shift-reload)

thats what i get when i updated my dynmap and webfiles.
i started searching for the issue and found out everything is updated to the correct version except for 1 line in the dynmap-config.json causing this problem.
the files are up2date and plugin also but sadly i think the dev forgot to adjust that line. causing every server restart to update it to the wrong version tag

please fix this

**Comment by Kimax89** [comment]
Are you using a seperate webhost or the build in webhosting?

**Comment by mmuziek** [comment]
seperate.
i found the issue. the plugin.yml has a different version then the plugin name causing the database to be updated with the wrong version.
i recommend the dev to update the plugin yml next time :D

**Comment by BenRulez** [comment]
Also have this issue with latest realese on spigot

**Comment by Kimax89** [comment]
sound a bit weird.

I never had any issues with the plugin.yml

I just copy everything from plugin/dynmap/web into my webfolder, when ever i have that issue.

**Comment by mmuziek** [comment]
well i just downloaded the new dynmap the version tag is now 3.1-beta-1-367 so its correctly updated :)
