### ISSUE TITLE
Rendering Issue/Low Res

### ISSUE THREAD

**Issue by TravelerJay** [webbukkit/dynmap#2995]
Noticed that the renders look a bit fuzzy on 1.16 compared to 1.15, I am using the same option for the quality of the render.

Dynmap 1.16
![DynmapGrannie1](https://user-images.githubusercontent.com/55771302/85940476-73e0a800-b8d1-11ea-8273-2ae44d5eb3aa.PNG)

Dynmap 1.15
![DynmapGrannie2](https://user-images.githubusercontent.com/55771302/85940484-81962d80-b8d1-11ea-9a81-d6137ee8fd62.PNG)

**Comment by RobinWhitfield** [comment]
I suspect this is due to the default now being jpg rather than png.

Can you do a compare of an old configuration.txt file and your current file?

**Comment by mikeprimm** [comment]
Default is JPG vs PNG - if you want PNG, just switch back and rerender.
