### ISSUE TITLE
 I can't delete the "Dynmap" file

### ISSUE THREAD

**Issue by Jolunas** [webbukkit/dynmap#2996]
This error appears when I try to delete the "dynmap" folder from the plugins folder
![dunmpa](https://user-images.githubusercontent.com/65680743/85960615-d8a00f00-b972-11ea-9260-6cf46356f1ab.png)

**Comment by RobinWhitfield** [comment]
@Jolunas, this looks like an nginx error rather than anything to do with dynmap.

If you've deleted the dynmap folder from your plugins then it's no longer installed.
