### ISSUE TITLE
Cant acess this site ( cant acess the web server)

### ISSUE THREAD

**Issue by Jolunas** [webbukkit/dynmap#2998]
![image](https://user-images.githubusercontent.com/65680743/86048322-54a36100-ba1e-11ea-83f6-997be531ba21.png)
29.06 15:30:05 [Server] Server thread/INFO [dynmap] Enabling dynmap v3.1-beta-1-367
29.06 15:30:05 [Server] Server thread/INFO [dynmap] Added 4 custom biome mappings
29.06 15:30:05 [Server] Server thread/INFO [dynmap] Using Bukkit Permissions (superperms) for access control
29.06 15:30:05 [Server] Server thread/INFO [dynmap] Web interface permissions only available for online users
29.06 15:30:06 [Server] Server thread/ERROR [dynmap] Error reading plugins/dynmap/markers.yml
29.06 15:30:06 [Server] Server thread/INFO [dynmap] Extracted files upgraded
29.06 15:30:06 [Server] Server thread/INFO [dynmap] Mod Support processing completed
29.06 15:30:06 [Server] Server thread/INFO [dynmap] Loaded 25 shaders.
29.06 15:30:06 [Server] Server thread/INFO [dynmap] Loaded 82 perspectives.
29.06 15:30:06 [Server] Server thread/INFO [dynmap] Loaded 22 lightings.
29.06 15:30:06 [Server] Server thread/INFO [dynmap] Starting enter/exit processing
29.06 15:30:06 [Server] Dynmap Render Thread/INFO [dynmap] Finish marker initialization
29.06 15:30:07 [Server] Server thread/INFO [dynmap] Web server started on address a090m.virtushost.net:8123
29.06 15:30:07 [Server] Server thread/INFO [dynmap] version 3.1-beta-1-367 is enabled - core version 3.1-beta-1-367
29.06 15:30:07 [Server] Server thread/INFO [dynmap] For support, visit https://reddit.com/r/Dynmap or our Discord at https://discord.gg/s3rd5qn
29.06 15:30:07 [Server] Server thread/INFO [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
29.06 15:30:07 [Server] Server thread/INFO [dynmap] If you'd like to donate, please visit https://www.patreon.com/dynmap or https://ko-fi.com/michaelprimm
29.06 15:30:07 [Server] Server thread/INFO [dynmap] Loaded 3 maps of world 'NEC'.
29.06 15:30:07 [Server] Server thread/INFO [dynmap] Loaded 2 maps of world 'NEC_nether'.
29.06 15:30:07 [Server] Server thread/INFO [dynmap] Loaded 2 maps of world 'NEC_the_end'.
29.06 15:30:07 [Server] Server thread/INFO [dynmap] Enabled

**Comment by Jolunas** [comment]
so i send a message about the ports to my host, and they call me that:

"In Multicraft hosting, as ips are shared, a single port is released for hosting on the Minecraft server (xxxxx).
To use other ports as well, it is only possible in dedicated hosting, which has a dedicated IP for each hosting."

Do I really need to pay for a dedicated server to use dynmap? Or is there a way around this problem of ports?

**Comment by Davdinges** [comment]
You dont need to do that, most hosts allow you to add extra ports and you can configure the dynmap to run on those. In this case I could visit the dynmap just fine. Case can be closed.

**Comment by Jolunas** [comment]
they said that i have just one port... To get more ports i need to pay for a better server...

**Comment by mikeprimm** [comment]
I

> they said that i have just one port... To get more ports i need to pay for a better server...

If this is the case, there is no way to resolve it using your (dubious) hosting service.
