### ISSUE TITLE
Could not retrieve configuration: Error on a nginx external webhost

### ISSUE THREAD

**Issue by ahmadby100** [webbukkit/dynmap#3000]
I have currently set up everything in a VPS with nginx and mysql.

My minecraft server is hosted by a provider and the VPS is my own

Everything seems to be running fine except when I go to the actual page, the error still comes up:

Could not retrieve configuration: Error

I don't know what the problem is could you please help me

Here's the actual page: http://dyn.bluetables.space

Here's my configurations.txt: https://pastebin.com/BEfe8vS4

I used this method: https://github.com/webbukkit/dynmap/issues/2609

I've been struggling with this for a few days now please help thanks

**Comment by mikeprimm** [comment]
You're getting a '<h1>500 Error</h1>Error opening database' - looks like the SQL configuration is bad

**Comment by iperrealistico** [comment]
Sorry for bringing this up again... i configured everything following this guide:
https://github.com/webbukkit/dynmap/issues/2609

Very useful and well done. My NGINX server is working perfectly under cloudflare, but once i open the actual Dynmap's page, i get the error "Could not retrieve configuration: Error"

I did not configure MySQL for this. I am using SQLite, as i always did

https://www.peacefulvanilla.club/map.html

EDIT:

wasn't a bug, i had to enable php on nginx. did it following this guide:
https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-in-ubuntu-16-04
