### ISSUE TITLE
1.16.1 api-version missing from plugin.yml

### ISSUE THREAD

**Issue by escapables** [webbukkit/dynmap#3001]
[12:45:56] [Server thread/WARN]: Legacy plugin dynmap v3.1-beta-1-367 does not specify an api-version.

Just a small thing, but a thing nonetheless.

**Comment by mikeprimm-triva** [comment]
Not going to add it - Dynmap supports older versions and the api-version thing, when higher than the version being run, breaks the server.  It also breaks the server if the version you specify is 'too old' (currently less than 1.13).  So, basically, you cannot use it and support more than 1.13+ - and as soon as they drop 1.13 support, that will break too, even though Dynmap doesn't need it. The legacy material support is unimportant as it isn't used one way or the other, but the api-version flag is basically broken if you support a wide range of versions in the same binary.  Other than the log noise, there is no consequences, so I'm not changing it.
