### ISSUE TITLE
unsupported platform

### ISSUE THREAD

**Issue by Chainsawwill** [webbukkit/dynmap#3002]
30.06 14:06:27 [Server] Server thread/INFO [dynmap] Enabling dynmap v3.0-SNAPSHOT-338
30.06 14:06:27 [Server] Server thread/INFO [dynmap] Dynmap is disabled (unsupported platform)

Running on spigot 1.16.1.  Port has been changed so as not to interfere with any other servers from host.

**Comment by RobinWhitfield** [comment]
@Chainsawwill, you might have more luck with the beta for 1.16.1. Older versions are not really 1.16.1 compatible.

Currently latest is 3.1 beta 1
http://dynmap.us/builds/dynmap/

**Comment by Chainsawwill** [comment]
Yeah, that seems to be the issue, I have it up and running now.
