### ISSUE TITLE
Compatibility with GroupManager causes Dynmap to disable

### ISSUE THREAD

**Issue by UnweildedBlade** [webbukkit/dynmap#3006]
**Describe the bug**
Dynmap will have an Error with group managers class system

**To Reproduce**
1. Have both dynmap and Groupmanager installed
2. Run server
3. See Error

**Expected behavior**
Both plugins running :)

**Please complete the following information:**
 - OS:  Windows 10
 - spigot/craftbukkit version: 1.16.1
 - Plug-in version [e.g. v2.2

**Additional context**

ERROR Error occurred while enabling dynmap v3.1-beta-1-367 (Is it up to date?)
03.07 02:53:47 [Server] INFO java.lang.IncompatibleClassChangeError: Expecting non-static method 'org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder org.anjocaido.groupmanager.GroupManager.getWorldsHolder()'

**Comment by UnweildedBlade** [comment]
Ive let the author of groupmanager know about this. Would be cool to have these both working in tandem!

**Comment by ElgarL** [comment]
This is Fixed in the current build of GroupManager (v2.3).
