### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by DennisVenema** [webbukkit/dynmap#3009]

**Comment by DennisVenema** [comment]
We've created a custom faction-like plugin, with 10 different groups/teams. To spice things up we've installed the dynmap plugin and it fully works with the Webregister, making you able to see your own location on the map.


I was wondering if we could make players only see their team/group on the dynmap, including themselves after the Login, but not show the other groups their location?

**Comment by athyk** [comment]
It should be coded in, I have the same issue

**Comment by FedUpWith-Tech** [comment]
This is outside the realm of what dynmap is intended to do, I suggest developing an addon to Dynmap that can do this.
