### ISSUE TITLE
Dynmap Webchat Duplicating Messages

### ISSUE THREAD

**Issue by HeavenCrafter** [webbukkit/dynmap#3012]
I'm currently running on the latest version of Dynmap on Minecraft Spigot 1.15.2 and after several days of testing to make sure that one, I'm not going insane and two, this isn't a conflict with other plugins. I've come to the conclusion that this does have the tendency to happen on just standalone Dynmap.

The images below are taken from my Dynmap site. Note TWO messages show up on the Dynmap webchat when I've only sent ONE message in-game. I've only sent one "test" message. And for some reason, it just pops up two.

![image](https://user-images.githubusercontent.com/22242534/86534440-0ce37480-bf0b-11ea-8af5-e44eb36698a0.png)
![image](https://user-images.githubusercontent.com/22242534/86534444-12d95580-bf0b-11ea-9565-81a85d958c24.png)

**Comment by FedUpWith-Tech** [comment]
What chat plugins do you have installed?

**Comment by HeavenCrafter** [comment]
None, I used none. I originally did have DiscordSRV installed but even after removing it and running a clean server. This weirdness still occurs.

**Comment by FedUpWith-Tech** [comment]
what permissions or otherwise chat-modfying plugins do you have?

**Comment by HeavenCrafter** [comment]
Also none. For full and better context.
This was originally first tested on a server with DiscordSRV. I first noticed it started duplicating which I then proceeded to do more testing. I then went ahead to test this on a clean server, with no plugins thats related to modifying chat. Only WorldBorder and Dynmap, bug still persisted to occur.

Permission plugins I used was **LuckPerms**.

**Comment by FedUpWith-Tech** [comment]
Hey! I didn't forget about this, does this still happen on the 1.16.2 version?

**Comment by HeavenCrafter** [comment]
> Hey! I didn't forget about this, does this still happen on the 1.16.2 version?

When I was testing this, I was using Minecraft 1.15.2 and 1.13.2 and the latest version of Dynmap. Though I never tested it on 1.16.2 so I'm unsure.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
