### ISSUE TITLE
Dynmap rendering not quite correct for 256 tall nether

### ISSUE THREAD

**Issue by retep998** [webbukkit/dynmap#3013]
Using the new custom world generation options in 1.16 it is possible to have 256 tall nether in vanilla Minecraft. Unfortunately dynmap currently makes assumptions regarding the height of the nether [here](https://github.com/webbukkit/dynmap/blob/867315fb04a2be582cb5ef0308fbfc77fcb86a76/DynmapCore/src/main/java/org/dynmap/hdmap/IsoHDPerspective.java#L1237). This results in the upper half of the nether not being rendered at all.

**Comment by FedUpWith-Tech** [comment]
In worlds.txt you can specify custom properties for each world. You need to specify a custom height of the nether map

**Comment by retep998** [comment]
Where is the custom height property documented?

**Comment by dkfdevil** [comment]
this is what i have in custom-perspectives.txt

  - class: org.dynmap.hdmap.IsoHDPerspective
    name: nether_top_map_hires
    maximumheight: 256
    minimumheight: 128
    inclination: 90
    scale: 16
    azimuth: 180
  - class: org.dynmap.hdmap.IsoHDPerspective 
    name: nether_top_map_surface_hires
    maximumheight: 256
    minimumheight: 128
    azimuth: 135
    inclination: 30
    scale: 16
