### ISSUE TITLE
Apache server shows nothing but black

### ISSUE THREAD

**Issue by TechieAndroid** [webbukkit/dynmap#3015]
I started by following this guide https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-Apache-httpd-under-Arch-Linux to use Dynmap on my Apache webserver on Arch. I followed every step to the T and double-checked everything.

Here's what I get on Apache:
https://imgur.com/birVovy.png

Here's what I get using the port:
https://imgur.com/7zv7Gks.png

**Comment by FedUpWith-Tech** [comment]
pastebin your configuration.txt

**Comment by TechieAndroid** [comment]
So apparently I didn't need the internal webserver or the proxy to use it under Apache. I'm confused as to why that wiki page exists.
I removed all the changes to my httpd.conf and vhosts and just followed this guide https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server and it's working fine now.
