### ISSUE TITLE
Dynmap not fully rendering

### ISSUE THREAD

**Issue by SiphMC** [webbukkit/dynmap#3016]
Hello,

I would like to load all the map on dynmap, but actually, it doesn't work.

I tried to do:
/wb trim
/wb fill
/dynmap fullrender

I did go throught the issue on here to find out how I could do it, but I didn't find anything working.

I have been working for a week now on this, without any success!

- dynmap version: 0.96.2.0
- Worldborder
- paper build 378 1.15.2

**Comment by FedUpWith-Tech** [comment]
So you have a worldborder set, all the chunks generated in your world, and you ran a fullrender and dynmap doesn't render everything?

**Comment by SiphMC** [comment]
It got fixed thanks
