### ISSUE TITLE
Display multiword on the same map? 

### ISSUE THREAD

**Issue by CarolusFPV** [webbukkit/dynmap#3018]
Hey, I have 1 map divided over 2 servers.
Would it be possible to merge the 2 halves of the map to make it look like it is one?

**Comment by FedUpWith-Tech** [comment]
Can you give more details on how the servers are set up and how the maps are set up?

From your brief description there isn't a way to display to separate worlds on the same map. Using an external webserver you can get 2 worlds on the same website but there is no support for merging maps.
