### ISSUE TITLE
Stone Slabs in 1.16 render as smooth stone slabs

### ISSUE THREAD

**Issue by FedUpWith-Tech** [webbukkit/dynmap#3019]
One latest version of both dynmap and spigot 1.16.1 stone slabs render as smooth stone slabs under default settings

**Comment by mikeprimm** [comment]
Fixed in latest dev builds (v3.1-SNAPSHOT 382 or higher)

**Comment by athyk** [comment]
@FedUpWith-Tech You should close this issue
