### ISSUE TITLE
Confussion

### ISSUE THREAD

**Issue by Voligoma** [webbukkit/dynmap#3020]
When I put the ip of my srvr y see another server that y dont know help plese
![Screenshot_9](https://user-images.githubusercontent.com/49576569/87236108-26793600-c3bb-11ea-822a-79e0c92d8559.png)

**Comment by FedUpWith-Tech** [comment]
Are you using a server hosting solution such as heavynode/mcprohost/etc?

port 8123 is likely taken by another server and you will have to request another port to use for dynmap then specify the new port in configuration.txt

**Comment by Voligoma** [comment]
yes i dont know how to solicitate a new port

**Comment by FedUpWith-Tech** [comment]
You will have to contact your server hosting provider to get a new port.
