### ISSUE TITLE
Pre-generated chunks don't display on the Dynmap

### ISSUE THREAD

**Issue by HenrikoMagnifico** [webbukkit/dynmap#3022]
There is currently no way to pre-generate chunks in the world so that they appear on the Dynmap, using plugins or mods of any kind. Please add this feature natively into Dynmap or make it easier for chunk-pregen developers to hook into the Dynmap API to do this!

Cheers!

**Comment by FedUpWith-Tech** [comment]
have your checked out either of these plugins? They pregenerate the world.
https://dev.bukkit.org/projects/worldborder
https://www.spigotmc.org/resources/fast-chunk-pregenerator.74429/
