### ISSUE TITLE
Dynmap Web Chat

### ISSUE THREAD

**Issue by KentBrought** [webbukkit/dynmap#3024]
I've been trying to make changes to the format of the dynmap webchat from the default, but I've been having multiple issues. I am using TownyChat as my chat formatting tool. On my main server, any changes that I make to the dynmap web chat portion do not show up in chat. In addition, on my test server, the name of the player does not show up in chat. Here's what I am trying to change it to:

`&color;f[&color;7Map&color;f] %playername%: %message%
`

If you need any more information, let me know.

**Comment by FedUpWith-Tech** [comment]
Are there any errors in the console during startup/when a player sends the message? 

dynmap does not natively recognize %playername% as playernames (I'm assuming you are seeing IP's when people chat) you have to manually link IP's to playernames or have people run `/dynmap webregister` and then enable login support in the config for people to link their dynmap web accounts and their minecraft accounts.

As to why you are seeing no changes make sure the webmessage format is surrounded by quotations "&color;f[&color;7Map&color;f] %playername%: %message%" or else the plugin will use the default (should throw a console error though)
