### ISSUE TITLE
How can I increase  the scale of the map

### ISSUE THREAD

**Issue by eirikh1996** [webbukkit/dynmap#3025]
Hello. Is there a way I can make the map show a 100k X 100k map at max zoomout. By default, it is 5k x 5k. Have seen other servers do that. How do I increase the scale of the map?

**Comment by voroxity** [comment]
"/dmap worldset worldname extrazoomout:<N> : set extra zoom out levels for world 'worldname'".

[source:[https://github.com/webbukkit/dynmap/wiki/Commands](url)

**Comment by eirikh1996** [comment]
Thanks alot. Really fixed it
