### ISSUE TITLE
RGB color mix up 

### ISSUE THREAD

**Issue by voroxity** [webbukkit/dynmap#3026]
when using essentialsEX /nick with 1.16 RGB color codes to change player names the colors displayed on map are not the same as the ones picked. it seems that the hex codes get mixed up.
![RGB TEST](https://user-images.githubusercontent.com/47036119/87470959-8eae5e80-c5eb-11ea-8534-4c82bbad14c0.PNG)
![dynmap test](https://user-images.githubusercontent.com/47036119/87470967-93731280-c5eb-11ea-8d39-3eab29f3e08e.PNG)

**Comment by voroxity** [comment]
after talking to the author of another plugin that fixed this problem a solution could be adding support for &x&r&r&g&g&b&b.

**Comment by Sydnxt** [comment]
Can confirm as unsupported

**Comment by FedUpWith-Tech** [comment]
Is this supported on the latest dynmap version? Color codes were added in .2
