### ISSUE TITLE
Embedding Dyn Map into a Website

### ISSUE THREAD

**Issue by CaptainRanger** [webbukkit/dynmap#3028]
I realise this is a question that has come up many times. However, none of the previously asked questions seems to answer my question.

I am setting up a Minecraft Server Website and I am trying to embed the Server's DynMap into the website while providing a direct link to it as well. I am using iframe specifically this line of code:

`<iframe src="http://myexampleserver:8123/?worldname=Exampleserver&hidechat=true&" attribute-id=value frameborder="0" class="map"></iframe>`

When I run it locally, the website seems to load fine however when I try to upload it to a hosting website like Github or custom domain, the map doesn't show. I am morbidly confused as to why this is happening. Can someone advise what I am doing wrong and what I need to do to fix this issue?

**Comment by bananasmoothii** [comment]
Sorry, but this isn't a dynmap issue...
