### ISSUE TITLE
Not rendering the nether or the end

### ISSUE THREAD

**Issue by TIBTHINK** [webbukkit/dynmap#3031]
I've done multiple full renders with no errors in the server log

but I'm not sure whats wrong

**Comment by FedUpWith-Tech** [comment]
Are you running the command from the console I.E. `dynmap fullrender world` or are you running `/dynmap fullrender` in game?

If you run it from the console you need to specify also `dynamp fullrender world_nether` and `dynmap fullrender world_the_end`.

If you aren't seeing it after that make sure the worlds are enabled in world.txt and you can see the icons for those maps in the sidebar
