### ISSUE TITLE
support for native leaflet.js calls

### ISSUE THREAD

**Issue by XuPuPG** [webbukkit/dynmap#3036]
I am working on a plugin that uses a dynamic map api and I would like to modify the map view within an api leflet, however I cannot do this without editing the js files of your plugin plugin. could you add support native calls like this for example 
https://github.com/dukescript/leaflet4j

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
