### ISSUE TITLE
Dynmap web SSL error

### ISSUE THREAD

**Issue by SeluneArkady** [webbukkit/dynmap#3037]
Hi
We can't access to the Dynmap page on our server, using Apache2 : **SSL_ERROR_RX_RECORD_TOO_LONG**
Minecraft server version : **Spigot 1.16.1**
Dynmap version : **Dynmap-HEAD-spigot.jar (7/19/20)**
Apache2 config : 
```
VirtualHost _default_:8123>
        ServerName #####.##:8123
    <Directory /var/games/minecraft/server/plugins/dynmap/web/tiles/>
        Order allow,deny
        Allow from all
    </Directory>
    <Proxy http://#####.##:8123/*>
        Order deny,allow
        Allow from all
    </Proxy>
</VirtualHost>
```

**Comment by bananasmoothii** [comment]
Is the dynmap page accessible from ip:port ?
