### ISSUE TITLE
Is there a way there a way to hide the ip for dynmap

### ISSUE THREAD

**Issue by HyenaGodKing** [webbukkit/dynmap#3039]
https://mail.google.com/mail/u/0?ui=2&ik=de5daf1752&attid=0.1&permmsgid=msg-a:r1456060946263494907&th=1738264a8a6f022f&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ9UV-C9zb-c9Y84dh9hlSn1gEsHaP9WEbt4l8MxDmm-SuCf8kx06gpBCNcQ3wiqyV_X3Hul1JCutPXWCvwPkLUXqBo2WatipTTrwlsQJ5AV--F5wwkY5anlsmo&disp=emb&realattid=ii_kd0n8hyp0

I don't want to be ddosed.

**Comment by FedUpWith-Tech** [comment]
The only way to prevent being DDOS'd is to proxy your connection- obfuscating the IP (http://mydynmap.com/dynmap leads to xxx.xxx.xxx.xxx:port) doesn't prevent anyone from finding your IP and especially not those that will try to DDOS you.

The good news is you hardly ever have to worry about DDOSing. I'm assuming you are selfhosted or don't pay for a hosting solution that offers DDOS protection. If you use a hosting solution the risk to you being ddos'd is incredibly low. If you self host the risk is also incredibly low. DDOSing minecraft servers hasn't been popular for quite some time and you really have to piss off someone who knows their stuff and has the ability to DDOS you (its not easy). 

If you are still concerned research routing your traffic (proxying) through Cloudflare or some other similar service. Thats a bit beyond the help this github is designed for but here is a starting page on what cloudflare is and how it works
https://support.cloudflare.com/hc/en-us/articles/205177068-How-does-Cloudflare-work-

Edit: P.S. your link is dead
