### ISSUE TITLE
Netherite armor

### ISSUE THREAD

**Issue by Harakirikungen** [webbukkit/dynmap#3040]
The new netherite armor does not show armor protection in the user interface.

**Comment by FedUpWith-Tech** [comment]
can you send a screenshot of what you mean?

**Comment by Virenbar** [comment]
Player wears netherite armor, but on map has zero armor.
![image](https://user-images.githubusercontent.com/10138491/89721202-32750980-d9f4-11ea-809d-92460841e84f.png)
![image](https://user-images.githubusercontent.com/10138491/89721209-47ea3380-d9f4-11ea-9376-201d246cb7dd.png)

**Comment by FedUpWith-Tech** [comment]
Can confirm this is fixed in most recent builds
![image](https://user-images.githubusercontent.com/7731191/146596496-dfd9af72-3517-4bf2-aa6d-8856f9683f28.png)
![image](https://user-images.githubusercontent.com/7731191/146596521-db37a4fd-4c17-48cf-a454-71d555ec0629.png)
