### ISSUE TITLE
Map template switches to very low res after server restart

### ISSUE THREAD

**Issue by jc-pitt** [webbukkit/dynmap#3041]
Every time I restart my server, the "deftemplatesuffix" setting in my config switches to "vlowres". I keep having to manually change it back to hires and this is usually after it's already rendered some of the map in very low res, rendering over parts of the map that have rendered in hires already. The rest of my config file stays exactly how I set it, the only change is the deftemplatesuffix. I am using Dynmap version 3.1 beta 1.

**Comment by FedUpWith-Tech** [comment]
Who is your server hosting solution?

**Comment by jc-pitt** [comment]
> Who is your server hosting solution?

My server is being hosted using Shockbyte.

**Comment by FedUpWith-Tech** [comment]
Shockbyte edits the dynmap config file every time you restart the server to be vlowres
