### ISSUE TITLE
Others not on my network cannot connect to the live web server

### ISSUE THREAD

**Issue by vestonion** [webbukkit/dynmap#3042]
After many  different possible fixes I'm left confused. I have portfowarded the port needed and it still wont work for them

**Comment by FedUpWith-Tech** [comment]
Hey @vestonion , in order to best get you support please fill out as much of this as you can:
```
• Output of /dynmap version:
• Spigot/Paper Version:
• Pastebin of your configuration.txt:
• Server Hosting Solution/Host OS:
• If it is a host, ports they allow you:
• Using Bungee: (yes/no):
```
