### ISSUE TITLE
won't render all tiles

### ISSUE THREAD

**Issue by thenamesogglaboggla** [webbukkit/dynmap#3045]
my dynmap wont render all of the tiles can someone please help me

**Comment by FrankenBobbo** [comment]
You'll need to pre-generate your world using a plugin like [WorldBorder](https://www.spigotmc.org/resources/worldborder.60905/) or [ChunkMaster](https://www.spigotmc.org/resources/chunkmaster.71351/), before the whole map will be revealed, as dynmap will only render generated chunks.

**Comment by FedUpWith-Tech** [comment]
I recommend ChunkMaster or FastChunkPregenerator over worldborder. Worldborder misses chunks 1.15+
