### ISSUE TITLE
Foliage/leaves won't load.

### ISSUE THREAD

**Issue by SentinelR** [webbukkit/dynmap#3048]
Dynmap won't render leaves it's just showing up like this (leaving shadows):

https://gyazo.com/a01ce96f0cf2b74f7c480b3ae378d8a3

This is annoying, I downloaded the newest version for podzol turning white as well.

Setup:

Dynmap-3.1-beta-2-spigot
    - full render
    - migrate-chunks: true
    - hi res

Private server (not public, for testing purposes only)
1.15.2 paper jar

**Comment by FedUpWith-Tech** [comment]
turn off `migrate-chunks:true` that should only ever be used once for migration and was build for converting 1.12 or earlier worlds to 1.13.2 or later.
