### ISSUE TITLE
Dynmap Folder suddenly Empty

### ISSUE THREAD

**Issue by downspath** [webbukkit/dynmap#3049]
I am currently rendering a big world. (20k by 20k) in Highres.  (Fullrender)

I suddenly got an 404 Page when trying to go the map page.

so i checked the pluggin folder of dynmap.

there is only one file left inside > world.pending

the rendering is still going (all files are getting stored to an sql database witch still works)

Is this a known issue?

(my sql database is also still receiving new files, ill let it run until its finished and fix the missing files later, ill update  if more issues arrise)

**Comment by FedUpWith-Tech** [comment]
Who is your server host?
Dynmap doesn't delete its own files, some server hosts delete/modify dynmap files or they may have been moved accidentally.

**Comment by downspath** [comment]
@FedUpWith-Tech I am hosting it my self. The files have gone missing while rendering. (luckly i havend made any config changes besides sql, since i had no backup)

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
