### ISSUE TITLE
Fabric version

### ISSUE THREAD

**Issue by MrKashew** [webbukkit/dynmap#3051]
Is there a version for fabric servers for this mod? This mod is literally the cornerstone mod to any mc server <3

**Comment by FedUpWith-Tech** [comment]
No, there isn't an no current plans to support fabric.

**Comment by MrKashew** [comment]
Fabric Essentials stopped developing the port as well, that's a huge shame

**Comment by zwollner** [comment]
> Fabric Essentials stopped developing the port as well, that's a huge shame

Really?

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2697
