### ISSUE TITLE
Transition for smoothing player markers movement overrides the transition for zooming

### ISSUE THREAD

**Issue by reviiii** [webbukkit/dynmap#3052]
The styles for smoothing player movements overrule the styles for zoom animations, causing the player markers to move erratically.

relevant css:

https://github.com/webbukkit/dynmap/blob/4f2cfdb11dbc1763a88c4c3c15034561d477ae48/DynmapCore/src/main/resources/extracted/web/css/leaflet.css#L124-L129

https://github.com/webbukkit/dynmap/blob/4f2cfdb11dbc1763a88c4c3c15034561d477ae48/DynmapCore/src/main/resources/extracted/web/css/dynmap_style.css#L565-L571

This can be solved by changing the source order or adding !important to the zoom animations

**Comment by reviiii** [comment]
(The player markers only move erratically during the zoom animation)

**Comment by FedUpWith-Tech** [comment]
correct me if I'm wrong but isn't the !important tag frowned upon?

**Comment by reviiii** [comment]
The !important tag is indeed frowned upon, but changing the source order would mean that there would be code from dynmap.css in leaflet.css or vice versa.
Another option would be to add a more specific css rule for the zoom animation for players.

**Comment by FedUpWith-Tech** [comment]
Hey! Sorry to necro this post. @JLyne updated the leaflet code in #3467 and I believe this was fixed. I'll go ahead and close this this under that assumption but will reopen it if I am wrong
