### ISSUE TITLE
Dynmap won't show layers

### ISSUE THREAD

**Issue by matthewblack04** [webbukkit/dynmap#3055]
Hello there,

I recently encountered a problem that caused my dynmap to not show any layers besides players (playerheads) whereas I want it to show the worldborder and my dynmap towny, I've established with the dynmap towny team that my issue is not with dynmap towny, or with towny, so Im guessing the problem is with dynmap itself.

here are some of my config files that may have an error in them:
dynmap worlds: https://pastebin.com/a3E3RZ79
dynmap config: https://pastebin.com/5AKta2cM

this issue is quite gamebreaking for a towny server, so I would really appreciate some support, and i'm of course happy to help where possible.

Thank you!

**Comment by FedUpWith-Tech** [comment]
Your visibility limits is incorrect. Try commenting back out your visibility limits and restarting and see if the layers show back up

**Comment by matthewblack04** [comment]
Thanks for the reply, I removed visibility limits (put a #before everything) and the problem still persists

**Comment by FedUpWith-Tech** [comment]
Have you at any point run `/dynmap reload`

**Comment by matthewblack04** [comment]
Have done it at least 10 times today only sadly.

**Comment by FedUpWith-Tech** [comment]
/dynmap reload breaks markers (what the towny layer is) 

Whoops , sorry wrong button

**Comment by matthewblack04** [comment]
Alright, that might be a problem, however I doubt it as it wasn't working before today and I never used dynmap reload before today
