### ISSUE TITLE
Dynamap /show error

### ISSUE THREAD

**Issue by AmusedGenie** [webbukkit/dynmap#3057]
I was told to go here to explain the issue and that it is likely a 1.16.1 issue. Whenever the command /show is used in order to attempt to get players to appear on the map I get an error.

31.07 13:36:18 [Server] ERROR null
31.07 13:36:18 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'dynmap' in plugin dynmap v3.0-SNAPSHOT-338
31.07 13:36:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1260) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
31.07 13:36:18 [Server] INFO Caused by: java.lang.NullPointerException
31.07 13:36:18 [Server] INFO at org.dynmap.bukkit.DynmapPlugin$BukkitPlayer.<init>(DynmapPlugin.java:606) ~[?:?]
31.07 13:36:18 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.onCommand(DynmapPlugin.java:1028) ~[?:?]
31.07 13:36:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-129]
31.07 13:36:18 [Server] INFO ... 18 more

**Comment by FedUpWith-Tech** [comment]
you are not on the lastest version of dynmap. Please use the latest version [found here](https://www.spigotmc.org/resources/dynmap.274/) and let me know if the issue persists

**Comment by AmusedGenie** [comment]
I have updated to the latest version of dynmap. What can I do next in order to make player heads appear on the map?

**Comment by FedUpWith-Tech** [comment]
can you pastebin your configuration.txt?

Do you see player locations on the map but not heads? can you send a screenshot of this as well

**Comment by AmusedGenie** [comment]
EDIT: remove pastebin link due to password 
Here it is.
![image](https://user-images.githubusercontent.com/69053658/89146445-be34f480-d521-11ea-92df-bbde0b3e0027.png)
Player heads do at their location but the map will direct if you click them on the right.

**Comment by FedUpWith-Tech** [comment]
Don't forget to remove your mysql passwords before you pastebin configs 😉  I removed the link but you don't want that falling in the wrong hands

**Comment by FedUpWith-Tech** [comment]
in this section of the config 
```
  # Note: this component is needed for the dmarker commands, and for the Marker API to be available to other plugins
  - class: org.dynmap.MarkersComponent
    type: mysql
    showlabel: false
    enablesigns: false
```
change this line to 
`type: markers`

**Comment by AmusedGenie** [comment]
Alright it has been changed! Ill let you know if it worked! Also thanks for that haha

**Comment by AmusedGenie** [comment]
![image](https://user-images.githubusercontent.com/69053658/89147240-140a9c00-d524-11ea-95b5-1e83564c1694.png)
At least I can see the spawn marker, but I do get this error message.

**Comment by FedUpWith-Tech** [comment]
did you do a `/dynmap reload` or a full server restart

**Comment by AmusedGenie** [comment]
server restart

**Comment by FedUpWith-Tech** [comment]
someone else is having that exact same error on the discord for a completely unrelated issue let me do some more digging

**Comment by AmusedGenie** [comment]
any ideas?

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
