### ISSUE TITLE
Error using v3.1-beta-2 for Forge 1.16.1 - World won't render

### ISSUE THREAD

**Issue by DigitalPopsicle** [webbukkit/dynmap#3059]
I previously used the Spigot version which ran perfectly fine for 1.16.1, but since switching to Forge I can't get the world to render.

It renders a small distance around spawn before giving me errors:

"[Dynmap Render Thread/FATAL] [Dynmap/]: [Dynmap] Exception during render job: world=world, map=org.dynmap.hdmap.HDMap@52914285"
"[Dynmap Render Thread/FATAL] [Dynmap/]: [Dynmap] Exception during render job: world=world, map=null"

I opened a support ticket with my server host and they've come back saying it's a apparently a known issue with the Forge 1.16.1 version.

The map URL still works and icons are still shown when users are online and where they're located, but the map itself won't render.
http://104.193.181.2:63364/

If there's anything I can do to sort it then please let me know but otherwise eagerly awaiting a fix for this

**Comment by FedUpWith-Tech** [comment]
Forge is currently broken in 1.16.1 for dynmap, will update this issue when a patch is released
Related to #3044
