### ISSUE TITLE
Dynmap Rendering Double Slab with Block Texture [Custom Texturepack]

### ISSUE THREAD

**Issue by stormboomer** [webbukkit/dynmap#3060]
Problem is probably related to #2206 

I have a problem with the texture dynmap uses when rendering blocks which also have double slabs. It seems like Dynmap is using the texture for the Block instead of the Double Slab texture to render:

![image](https://user-images.githubusercontent.com/25079531/89097107-32658000-d3dc-11ea-9015-5be791a5c1fc.png)

Tested with
`[dynmap] version 3.1-beta-2-389 is enabled - core version 3.1-beta-2-389`

**Comment by mikeprimm** [comment]
Dynmap doesn't support custom models and block state maps - at least not directly: we only support texture substitution (and, to a degree, Optifine/MCPatcher CTM textures).  The latter is probably the most practical option for you, in the foreseeable future.  The vanilla blockstate maps for slabs, for all the ones I checked, point to the same model as the full block, and this is what our mappings are derived from.
