### ISSUE TITLE
Markers with holes

### ISSUE THREAD

**Issue by XuPuPG** [webbukkit/dynmap#3065]
why did you abandon markers with holes if the leaflet supports this type of markers. Is it possible to add this?

**Comment by FedUpWith-Tech** [comment]
I don't believe this feature was abandoned but rather not implemented. Almost no development has happened on the web side of the plugin for many years- I wouldn't count on this getting implemented soon

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
