### ISSUE TITLE
extrazoomout: 4 not rendering the first two zoom out levels

### ISSUE THREAD

**Issue by TechieAndroid** [webbukkit/dynmap#3070]
![image](https://user-images.githubusercontent.com/17918163/89372438-c882fa00-d6ab-11ea-9dd8-83fb1e87588a.png)

Setting extrazoomout: 4 I don't get anything to load in for the first two extra zoom out levels, past that (at the normal extrazoomout: 2 value) things load in like normal.

I shouldn't need to rerun fullrender to get it to downsample what's alreadly been generated. How can I adjust the threshold for loading the map at a higher zoom out value?

**Comment by FedUpWith-Tech** [comment]
2 things
1, you may need to fullrender, at the very least update the render in one spot of every tile for the higher zoomouts
2, there is a config option saying how often to update the zoom out tiles it may not have gotten around to update those yet if it ever will

**Comment by TechieAndroid** [comment]
> 2 things
> 1, you may need to fullrender, at the very least update the render in one spot of every tile for the higher zoomouts
> 2, there is a config option saying how often to update the zoom out tiles it may not have gotten around to update those yet if it ever will

Thank you for replying quickly. I tried editing those options in the config and I set it to update every 2s but I never saw the process run while zooming out on a device, no cpu usage at all which tells me it wasn't going to update.

I'll try fullrendering again and I'll post my results, I just hope the fullrender doesn't have to start from scratch because I have a 16,000x16,000 world.

**Comment by TechieAndroid** [comment]
It's taking a long time to render but the fullrender seems to be working thanks.
