### ISSUE TITLE
[Feature Request] Clarify errors on first time-startup log

### ISSUE THREAD

**Issue by jordi00113** [webbukkit/dynmap#3073]
First time starting server with the dynmap plugin generates error:
`>.... [16:15:42 ERROR]: [dynmap] Error reading plugins/dynmap/markers.yml`

Other information:

- Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT
- Dynmap v3.1-beta-2

**Comment by FedUpWith-Tech** [comment]
Can you pastebin your markers.yml file

**Comment by jordi00113** [comment]
Markers.yml pastebin: https://pastebin.com/rkJwZbcR

**Comment by FedUpWith-Tech** [comment]
Does this only ever happens on a fresh server with a new installation of dynmap?

Or does this error happen every time you start the server?

**Comment by jordi00113** [comment]
It does produce the error **only** with a fresh installation of dynmap!

Steps to reproduce:

1. Use paper 1.16.1 & setup the server
2. Stop server & drag Dynmap v3.1-beta-2 into plugins
3. Start server and you'll see the error message

Just confirmed a second time on another server without dynmap.

`>.... [00:33:20 ERROR]: [dynmap] Error reading plugins/dynmap/markers.yml`

**Comment by FedUpWith-Tech** [comment]
I honestly think this is intended behaviour. The plugin doesn't find a markers.yml (because its a fresh install) which promts the code to create one from the default template. This first-run error should probably read differently but I think it was just a quick fix and reusing code to generate the config on the first run.

**Comment by jordi00113** [comment]
As server administrator it is confusing, I suggest to give a clearer message.

**Comment by JeanRenard** [comment]
Hello, same error nut on an linux isntance (with forge 1.16.1). The only difference is that markers.yml isnt created after the error's message. 
So,what have I to  do to resolve that ?
I tried to create myself the file but where can I have the right configuration ?
Thx

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.

**Comment by FedUpWith-Tech** [comment]
Good news! This feature request was implemented in https://github.com/webbukkit/dynmap/commit/d5354898cb5ba45c7b0ef4257a4474ad942506b6 and has been in Dynmap releases 3.3beta2+
