### ISSUE TITLE
Fetching Player Skins On 1.7.10

### ISSUE THREAD

**Issue by MyrstaL** [webbukkit/dynmap#3076]
"# Customize URL used for fetching player skins (%player% is macro for name)"

**Issue Description:** _Trying to fetch player skins but all I can find is sites using UUID instead of username. From Crafatar: "By disabling a legacy API in 2018, Mojang has made it practically impossible for Crafatar to support usernames. Please use UUIDs instead! All usernames are rejected." is there a way to work with this?_

**Dynmap Version:** _2.3-2074_
**Server Version:** _forge-1.7.10 Build 10.13.4.1614_
**Pastebin of Configuration.txt:** _Pastebin servers down right now?_
**Server Host (if applicable):** _Self Hosted_

**Comment by FedUpWith-Tech** [comment]
This was fixed in later versions of dynmap. Unfortunately 1.7.10 support was dropped several years ago and won't be receiving that update.

**Comment by MyrstaL** [comment]
Another quick issue, iso_NW_30_hires renders grass as grey. [Image link here](https://media.discordapp.net/attachments/628234777639649280/741541237206810686/unknown.png?width=493&height=460) I wanted to know if this was fixed as well, or if there is a way I can fix this personally

**Comment by MyrstaL** [comment]
I also just noticed I was using a version uploaded 2 years before the latest 2.6 beta for 1.7.10, I had been using 2.3.
