### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by johnorlic** [webbukkit/dynmap#3080]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** *dynmap-3.1-beta-1-spigot*
* **Server Version:** *git-Paper-134 (MC: 1.16.1)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Server Host (if applicable):** *MC Node*
* **Pastebin of crashlogs or other relevant logs:** *

I get these errors in the console:
 
 
[01:51:58 ERROR]: [dynmap] Marker file write error - Communications link failure
The last packet successfully received from the server was 299.964 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
 
[01:43:46 ERROR]: [dynmap] Tile matches hash error - Communications link failure
The last packet successfully received from the server was 166.064 milliseconds ago. The last packet sent successfully to the server was 48 milliseconds ago.
[01:44:13 ERROR]: [dynmap] Tile matches hash error - Communications link failure
The last packet successfully received from the server was 192.723 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
[01:44:13 ERROR]: [dynmap] Tile exists error - Communications link failure
The last packet successfully received from the server was 192.859 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.
[01:44:13 ERROR]: [dynmap] Tile write error - Communications link failure
The last packet successfully received from the server was 192.674 milliseconds ago. The last packet sent successfully to the server was 2 milliseconds ago.*
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
~~Are you using mysql?~~

I just read your config nvm.

This is an issue with the file system not dynmap. For whatever reason your filesystem is super slow and not allowing dynmap to get the hash of the tiles.

Can you enable verbose logging (near bottom of configuration.txt and pastebin the error again but the verbose version

**Comment by johnorlic** [comment]
Do you mean this?
https://pastebin.com/ifrG73X8

**Comment by FedUpWith-Tech** [comment]
Wait, the startup log says you are using mysql but your configuration.txt doesn't show you are using mysql? Did you fill out the template?

**Comment by johnorlic** [comment]
This is my config.
EDIT BY FedUpWith-Tech: removed pastebin link due to mysql password

**Comment by FedUpWith-Tech** [comment]
Yes, you are using mysql (please be sure to remove passwords before you post configs in the future, i edited out your link but you don't want that falling in the wrong hands)

The issue here isn't with dynmap, its your  mysql server, it is either closing connections too early or getting bottlenecked by the host OS. Dynmap can't effectively use mysql for maps if the mysql server is slow. I know you use a server host so you can't control the mysql server but I would open a ticket with them and let them know that the mysql server is bottlenecking dynmap

**Comment by johnorlic** [comment]
thanks for the assistance.
