### ISSUE TITLE
Dynmap 1.16.2

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#3081]
Spigot-Version:CraftBukkit version git-Spigot-379750e-9c9fb59 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

A new MC version is out now, 1.16.2, and so the fun starts all over again for all server owners. I hereby post the first mistake

```

[23:47:08] [Server thread/INFO]: [dynmap] Loading dynmap v3.1-beta-2-389
[23:47:08] [Server thread/INFO]: [dynmap] version=git-Spigot-379750e-9c9fb59 (MC: 1.16.2)
[23:47:08] [Server thread/ERROR]: [dynmap] Unable to find field g for net.minecraft.server.v1_16_R2.BiomeStorage
[23:47:08] [Server thread/ERROR]: Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.1-beta-2-389 (Is it up to date?)
java.lang.IllegalArgumentException: Error initializing dynmap - bukkit version incompatible!
	at org.dynmap.bukkit.helper.BukkitVersionHelperGeneric.<init>(BukkitVersionHelperGeneric.java:166) ~[?:?]
	at org.dynmap.bukkit.helper.v116.BukkitVersionHelperSpigot116.<init>(BukkitVersionHelperSpigot116.java:45) ~[?:?]
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:38) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:821) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:386) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:186) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-379750e-9c9fb59]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**Comment by MJRLegends** [comment]
You beat me too it xD

**Comment by TNTUP** [comment]
Hope they will fix the ongoing issue with converted chunks (1.12.2 forceupgraded to 1.16.1) to dynmap (1.16.2)...

**Comment by FedUpWith-Tech** [comment]
> A new MC version is out now, 1.16.2, and so the fun starts all over again for all server owners. I hereby post the first mistake

Spigot/Paper still haven't released a "release" version so I wouldn't expect a dynmap update till that happens. Work is obviously still going on behind the scenes to get dynmap up to date but it will be a bit. Please be patient with us as we confirm any changes we have to make for 1.16.2 don't break all the other version.
 
> Hope they will fix the ongoing issue with converted chunks (1.12.2 forceupgraded to 1.16.1) to dynmap (1.16.2)...

This will not be included in the 1.16.2 update patch. This is an incredibly hard issue to patch as we have to debug and manually test with creating worlds at later versions then testing the dozens of ways people have updated over the years. This patch will likely be a standalone patch and I can't give any status on to when this will be fixed to due the large reworking of the plugin required for this to be fixed.

**Comment by Blueeyestar** [comment]
> 
> 
> > A new MC version is out now, 1.16.2, and so the fun starts all over again for all server owners. I hereby post the first mistake
> 
> Spigot/Paper still haven't released a "release" version so I wouldn't expect a dynmap update till that happens. Work is obviously still going on behind the scenes to get dynmap up to date but it will be a bit. Please be patient with us as we confirm any changes we have to make for 1.16.2 don't break all the other version.
> 
> > Hope they will fix the ongoing issue with converted chunks (1.12.2 forceupgraded to 1.16.1) to dynmap (1.16.2)...
> 
> This will not be included in the 1.16.2 update patch. This is an incredibly hard issue to patch as we have to debug and manually test with creating worlds at later versions then testing the dozens of ways people have updated over the years. This patch will likely be a standalone patch and I can't give any status on to when this will be fixed to due the large reworking of the plugin required for this to be fixed.

**If that is not a "release" ... then I ask ... what is it then ??**

https://www.spigotmc.org/threads/spigot-bungeecord-1-16-2.457579/

**Comment by FedUpWith-Tech** [comment]
its a working build is what it is. If it was a release they would set the default version to 1.16.2

**Comment by MJRLegends** [comment]
Its the same with 1.16.1 my man its a spigot build that is stable to use

**Comment by CloudeLecaw** [comment]
They wrote allready they will set it to default the next days, you can aoswct this Version at the Moment is same as release.
Its publisher in official news as a release

**Comment by jacob1** [comment]
Anyway, looks like you can follow updates here again: https://www.reddit.com/r/Dynmap/comments/i8ebyd/spigotpaper_1162_is_breaking_update_for_existing/

The plan was originally to have it by tonight, but mojang changed a lot of stuff internally this release (probably to support the custom biomes), so it's not clear when dynmap will be ready.

**Comment by Blueeyestar** [comment]
mikeprimm did it again and created a working dynmap for 1.16.2. Thank you very much for that. Your work is a valuable part of the Minecraft community.


https://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-spigot.jar

**Comment by FedUpWith-Tech** [comment]
Going to close this now since a release is available

**Comment by MJRLegends** [comment]
Lol
