### ISSUE TITLE
[Repost] Icon Issue

### ISSUE THREAD

**Issue by ZommbieWasTaken** [webbukkit/dynmap#3086]
On my dynmap I can't see coords on it, options to see things like worldborder or chunkmaster, unable to see players and world spawn stuff like that. Also every so often I get a sql js error. I will put a picture attached please help.

Details:

Dynmap version: v3.1-beta-2

Server Version is paper 1.15.2

Ima use mcpaste: https://mcpaste.io/f273d0f586daa49c

Server Host: Pebblehost
![ok](https://user-images.githubusercontent.com/69566335/90143946-31bdd980-dd4c-11ea-99d9-cd8a759acf24.png)

Other data: None

**Comment by FedUpWith-Tech** [comment]
Please don't open duplicate issues  Please use #3082
