### ISSUE TITLE
Blank html

### ISSUE THREAD

**Issue by Lehneredv** [webbukkit/dynmap#3087]
Hello,

i am currently writing my own Website. (Html and javascript).

I dont know how to eddit the index.html since everything seems to use javascript.

is there a blank version of the .html where i only get the map? 

i would use  buttons with /map/?worldname=world&mapname=flat to change the iframe. this way i could nicely integrate it into my website without having to know how to write js.

if i try to delete the corresponding .js files i can remove the ui (compas, sidebar usw) but i keep getting red error boxes that these files are missing :(

**Comment by FedUpWith-Tech** [comment]
javascript is integral to running this plugin, you can use iframe buttons to change the map but you will need to learn how to use js. 

Unfortunately there is almost no way to run dynmap with plain html, there are ways to do similar functions in html5 but it would honestly be easier for you to learn JS, all the functionality it sounds like you want is available with an api or tags.

**Comment by downspath** [comment]
> javascript is integral to running this plugin, you can use iframe buttons to change the map but you will need to learn how to use js.
> 
> Unfortunately there is almost no way to run dynmap with plain html, there are ways to do similar functions in html5 but it would honestly be easier for you to learn JS, all the functionality it sounds like you want is available with an api or tags.

I would be interrested if there is a solution to this. iframe buttons are no problem for me. a plain map would be sufficient, i dont need the ui.

**Comment by downspath** [comment]
I found a solution:

http://steven.onthewifi.com/map/?worldname=world&mapname=flat&nogui=true

add &nogui=true to the end of the link and you will get a map with no gui.
