### ISSUE TITLE
Dynmap doesn't support Minecraft 1.16.2？

### ISSUE THREAD

**Issue by ShulkerSakura** [webbukkit/dynmap#3088]
I update my Spigot Minecraft Server from 1.16.1 to 1.16.2 and I found the dynmap is not working,even the latest build.I found "Dynmap is disabled (unsupport platform)"in the console.

**Comment by FedUpWith-Tech** [comment]
Duplicate of #3081 
Dynmap 1.16.2 is now out, go to your normal distribution channels to get the new build
