### ISSUE TITLE
Sign Mark can't be removed.

### ISSUE THREAD

**Issue by ShulkerSakura** [webbukkit/dynmap#3090]
I set "enablesign: true" in the configuration and placed a sign with [dynmap] in the first line in Minecraft. It successfully created a sign in dynmap, but when I removed the sign, the mark on the dynmap has not been removed.
![Screenshot_20200815-141417](https://user-images.githubusercontent.com/50770360/90306614-a1c19080-df01-11ea-8970-c66c0bf0384e.png)

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2473
