### ISSUE TITLE
Invalid length of given storage, got: 320 but expected: 342 : Causes rendering to crash.

### ISSUE THREAD

**Issue by LarveyOfficial** [webbukkit/dynmap#3092]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** *Newest Beta 1.16.1*
* **Server Version:** *forge 1.16 build 32.0.66*
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Server Host (if applicable):** *Self Hosted*
* **Pastebin of crashlogs or other relevant logs:** 
![image](https://user-images.githubusercontent.com/39219859/90316893-759f1300-def3-11ea-899f-85d0706c561c.png)
* **Steps to Replicate:** *start rendering any world*

**Comment by lhns** [comment]
Probably related to #3083

**Comment by mikeprimm** [comment]
Should be fixed in latest dev builds (402 or later

**Comment by mikeprimm** [comment]
Dup of #3083.- fixed in 3.1-beta-3
