### ISSUE TITLE
[Feature Request] Add option to disable messages sending via the API

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#3096]
Spigot-Version:CraftBukkit version git-Spigot-379750e-e850144 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

Dynmap Version:Dynmap_3.1-Build397

The chat in the Dynmap configuration is deactivated

 **allowwebchat: false**

We use so that users can write in the chat via discord:
**DiscordSRV-Build-1.19.1**

Users who write in the game cannot see the chat on the dynmap. That should be the case.

But if the game is now written to via discord, it appears on the dynmap although it shouldn't be.

**Comment by FedUpWith-Tech** [comment]
This is something discordsrv implemented. Somewhere in their config there is an option to toggle dynmap send to web, they just use the dynmap API to send messages, nothing we can do from dynmap side to disable that

**Comment by FedUpWith-Tech** [comment]
Admittedly, dynmap should block the chat API when webchat is disabled, which is a dynmap issue but I believe the webchat predates the API and when that config was created minecraft chat was the only one to worry about. I'll update the title and make it a feature request

**Comment by Blueeyestar** [comment]
> 
> 
> Admittedly, dynmap should block the chat API when webchat is disabled, which is a dynmap issue but I believe the webchat predates the API and when that config was created minecraft chat was the only one to worry about. I'll update the title and make it a feature request

Super thank you :)

**Comment by FedUpWith-Tech** [comment]
Could also address #2228 when this gets looked at

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
