### ISSUE TITLE
Legend Icons not appearing

### ISSUE THREAD

**Issue by WieldSoftwareDevelopement** [webbukkit/dynmap#3100]
**Issue Description:** View icons not appearing in the legend of web interface

* **Dynmap Version:** latest - v3.1-beta-3
* **Server Version:** spigot 1.16.2

The issue is that the web interace is look for the icon file names like: block_{world}_{view}.png.  When the file names do not have the world name in them.  

Not sure if this an intentional change, but I am getting around it by copying the files and renaming them to make the web interace happy.

**Comment by Tsoccerguy3** [comment]
I can confirm , This bug occurs after commit 4e7ae8b74c75f1c64bb1c204ac6372de1354a069

**Comment by FedUpWith-Tech** [comment]
It was PR #3008 that changed this. @WieldSoftwareDevelopement can you test for me if newly made markers are correctly showing up or is just icons made on older versions of dynmap?

**Comment by mikeprimm-triva** [comment]
Yep - I flagged the error, and then mistakenly thought a fix had been added.....

**Comment by FedUpWith-Tech** [comment]
Haha, oh the perils of community development

**Comment by mikeprimm-triva** [comment]
Yep - I'll work a fix for it once I'm done with the 'pay the bills' job tonight (I've got a deployment to handle, so it'll be late)

**Comment by WieldSoftwareDevelopement** [comment]
> It was PR #3008 that changed this. @WieldSoftwareDevelopement can you test for me if newly made markers are correctly showing up or is just icons made on older versions of dynmap?

Yes, newly made markers appear correctly.  Also, all the previously made markers appear correctly as well.

**Comment by FedUpWith-Tech** [comment]
Mike has fixed this in the latest dev build (relevant commit: https://github.com/webbukkit/dynmap/commit/6e35b7e87239f799fdfbe76b98b90704ec356527 )
I'm going to close this but let me know if the issue still persists

**Comment by WieldSoftwareDevelopement** [comment]
> Mike has fixed this in the latest dev build (relevant commit: [6e35b7e](https://github.com/webbukkit/dynmap/commit/6e35b7e87239f799fdfbe76b98b90704ec356527) )
> I'm going to close this but let me know if the issue still persists

I took a look at the code changes and it definitely fixes up the js code. 

I'll watch for the next release and give it a try then.

**Comment by mikeprimm-triva** [comment]
Check this build, if you'd like to see it sooner - https://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-spigot.jar
