### ISSUE TITLE
Chests don't render in forge 1.16.1

### ISSUE THREAD

**Issue by lhns** [webbukkit/dynmap#3102]
> template is **bold**
> sample data is *italicized*

**Issue Description:** ***normal** and **trapped** chests don't render at all while ender chests do.*

* **Dynmap Version:** *3.1-beta-3-forge-1.16.1*
* **Server Version:** *forge 1.16 beta 3*
* **Pastebin of Configuration.txt:** *default*
* **Server Host (if applicable):** *local multiplayer*
* **Pastebin of crashlogs or other relevant logs:** *none*
* **Other Relevant Data/Screenshots:**
![image](https://user-images.githubusercontent.com/1524059/90512209-10028f00-e15e-11ea-92eb-ebc08f7c40ca.png)
![image](https://user-images.githubusercontent.com/1524059/90512233-1db81480-e15e-11ea-9d45-a6373a07c4b8.png)
*I stood directly between the chests and did a radiusrender 10 on the map. The ender chests appeared and the **normal** and **trapped** chests didn't*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Good catch! Have you by chance tested if this is specific to 1.16.1 forge/fabric or is it all versions on beta-3?

Thanks in advance.

**Comment by lhns** [comment]
Not yet. I know that it happens on 1.16.1 and 1.16.2 forge and fabric.

**Comment by FedUpWith-Tech** [comment]
I can confirm this only happens on forge/fabric

**Comment by mikeprimm-triva** [comment]
Weird - lemme check on this

**Comment by mikeprimm** [comment]
Should be fixed in 3.1-beta-3a release from last night
