### ISSUE TITLE
Div are not "injected" properly into Dynmap anymore.

### ISSUE THREAD

**Issue by KyroOW** [webbukkit/dynmap#3103]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Divs from other plugins are not getting "injected" into dynmap properly, a div like (div id="something") is returned (div) in the browser, unnamed.*

* **Dynmap Version:** *3.1 beta 3*
* **Server Version:** *paper 1.16.1 build 92*
* **Pastebin of Configuration.txt:** *https://pastebin.com/1RVDngN1*
* **Server Host (if applicable):** *TitanNodes*
* **Steps to Replicate:** *From a plugin like Kingdoms X or factions (happens on both), the divs in the config files end up unnamed in the browser.*

KingdomsX config: https://i.imgur.com/y77L4f4.png
Result in browser: https://i.imgur.com/1l4wFoU.png

After reloading Kingdoms and Factions, the div gets injected properly in the dynmap, this is how it should be:

https://i.imgur.com/h72vQKn.png

But after reloading the browser, the div is bugged again

https://i.imgur.com/1l4wFoU.png

This is not a bug with KingdomsX or Factions as this happens on both plugins and this was NOT happening in old versions of Dynmap. (MC 1.11.2 Dynmap)

 [V] *I have looked at all other issues and this is not a duplicate*  
 [V] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
As the dynmap plugin updates things that modify the plugin will need to be updated too. 
This *is* an issue with both of those plugins as they will need to be updated to support the dynmap update.
