### ISSUE TITLE
Apply to get the plugin on minehut

### ISSUE THREAD

**Issue by OkiStuff** [webbukkit/dynmap#3105]
**Feature Description:** *It would be amazing if the plugin is available on Minehut*

* **Additional context:** *Me and my friends are trying to start a Minecraft Earth Server on Minehut but its hard without dynmap*

**Comment by FedUpWith-Tech** [comment]
Can you not upload with FTP?

**Comment by OkiStuff** [comment]
no i dont think you can upload anything with FTP to a minehut server.. they don't allow it. If I'm wrong please tell me

**Comment by ryantheleach** [comment]
This is not the place to request that Dynmap be on Minehut.

https://forums.minehut.com/forum/20-plugins/

In addition, Dynmap tends to be pretty heavy, and I really really doubt they would let you use Dynmap on the free tiers anyway.

Searching their forums shows it's often requested: https://forums.minehut.com/search/?q=dynmap&updated_after=any&sortby=newest&search_and_or=or

And that they don't currently have the web / port infrastructure to make this possible: https://forums.minehut.com/topic/15721-plugin-request-dynmap/?tab=comments#comment-50405

**Comment by OkiStuff** [comment]
Oh ok.. thanks! i guess ill just close this issue now

**Comment by ryantheleach** [comment]
See my edit for additional info.
