### ISSUE TITLE
[1.12.2 mohist server] dynmap crash when switching worlds (i think its dynmap?)

### ISSUE THREAD

**Issue by xemnes** [webbukkit/dynmap#3106]
**Issue Description:** *Dynmap is crashing my server sometimes when i switch worlds, i assume its dynmap as i see lots of dynmap references in the crash report and happens after dynmap saves pending tile renders for the world i just left*

* **Dynmap Version:** *Dynmap-3.1-beta-3-forge-1.12.2*
* **Server Version:** *mohist server build e28b82d for 1.12.2*
* **Pastebin of Configuration.txt:** *https://pastebin.com/8iKng30G*
* **Server Host (if applicable):** *pebblehost*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/pxLjbpuD*
* **Steps to Replicate:** *it only ever happens when switching worlds*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this* < its inconsistent, only happens when switching worlds and doesnt happen all the time.

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
