### ISSUE TITLE
Dynmap crashing server by loading chunks

### ISSUE THREAD

**Issue by averwhy** [webbukkit/dynmap#3107]
**Issue Description:** *When the server sends the 'Done!' message, it crashes soon after, with the message *

* **Dynmap Version:** *3.1*
* **Server Version:** *paper 138 (1.16.1)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/wQV8ppYe*
* **Steps to Replicate:** *install latest version of dynmap (3.1)*

- [x] *I have looked at all other issues and this is not a duplicate*  

- [x] *I have been able to replicate this*

Note: i have been able to fix this by changing to previous dynmap version

**Comment by FedUpWith-Tech** [comment]
Please post the crash report

**Comment by averwhy** [comment]
there isnt really a crash report... it just says:
`[16:17:59 WARN]: java.lang.RuntimeException: Server attempted to load chunk saved with newer version of minecraft! 2578 > 2567`
after that, all server activity ceases. Cant connect, if you were connected, you got timed out. Discord SRV also stops responding.

**Comment by FedUpWith-Tech** [comment]
So why do you believe dynmap is at fault for this error?

**Comment by averwhy** [comment]
> 
> 
> So why do you believe dynmap is at fault for this error?

When i take the plugin away, server runs normally.

**Comment by FedUpWith-Tech** [comment]
What plugins do you have installed, also did you revert server versions ever?

**Comment by averwhy** [comment]
> 
> 
> What plugins do you have installed, also did you revert server versions ever?

`Plugins (21): ChatColor2*, CoreProtect, DiscordSRV, dynmap*, Essentials, floodgate-bukkit, Geyser-Spigot, HolographicDisplays, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, PowerRanks, ProtocolLib, QuickShop, Towny, TownyChat, Vault, WorldEdit, WorldGuard`

I never changed Minecraft versions

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
