### ISSUE TITLE
Allow http for /dmarker addicon

### ISSUE THREAD

**Issue by ryantheleach** [webbukkit/dynmap#3108]
This would allow me to let server staff to add new icons, say from discord emote repositories, without giving them direct file access.

**Comment by mikeprimm-triva** [comment]
This is a good idea - lemme look into it

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.

**Comment by FedUpWith-Tech** [comment]
@ryantheleach discussion will still happen in either a PR or in the original thread but I want to track them via a megathread and allow everyone to vote for them in the same place

**Comment by ryantheleach** [comment]
@FedUpWith-Tech 
Locking to contributers seems to have locked voting too. But it would have resolved my primary complaint.

**Comment by FedUpWith-Tech** [comment]
Ah bummer, I was really hoping that wouldn't lock voting. I think it will still work as just mentioning someone will not subscribe them to the thread for every new request that gets posted.

**Comment by ryantheleach** [comment]
I'm just going to unsub from the thread, but I believe I noticed it (and complained) exactly because it DID subscribe me. But eh, sorry I was overly passionate with my original response, I was just trying to get my point across, when my phone started blowing up with notifications.
