### ISSUE TITLE
Netherite armor level not visible on 1.16.2

### ISSUE THREAD

**Issue by Bloodlex** [webbukkit/dynmap#3110]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Level of netherite armor player on map is not visible*

* **Dynmap Version:** *Dynmap version: core=3.1-beta-3-406, plugin=3.1-beta-3-406*
* **Server Version:** *git-Paper-148 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/SCZz2mAH*
* **Server Host (if applicable):** *Apex*
* **Steps to Replicate:** *See player in full netherite armor on map*

![dynmap](https://user-images.githubusercontent.com/1086720/91414329-b2043480-e84c-11ea-94ab-e4cfb797cc11.png)

 [X ] *I have looked at all other issues and this is not a duplicate*  
 [X ] *I have been able to replicate this*

**Comment by Technoguyfication** [comment]
Can confirm this is happening still, netherite armor isn't being counted at all towards armor:

![image](https://user-images.githubusercontent.com/8218061/99158915-3076b280-2695-11eb-81f5-f2204f4445c9.png)
![image](https://user-images.githubusercontent.com/8218061/99158916-32d90c80-2695-11eb-851d-7180cf3bd332.png)

Diamond works fine:
![image](https://user-images.githubusercontent.com/8218061/99158917-379dc080-2695-11eb-9a7b-9826694373fd.png)
![image](https://user-images.githubusercontent.com/8218061/99158920-39678400-2695-11eb-9b3c-a26751db78d5.png)

Interestingly, the elytra counts towards armor (even when paired with netherite):
![image](https://user-images.githubusercontent.com/8218061/99158931-46847300-2695-11eb-932f-6996f8ecf1ef.png)
![image](https://user-images.githubusercontent.com/8218061/99158933-47b5a000-2695-11eb-96f1-f23d82c578e8.png)

**Comment by FedUpWith-Tech** [comment]
Fixed in later versions
![image](https://user-images.githubusercontent.com/7731191/147006574-032f2f7b-2913-4969-a120-cb5a07016b25.png)
![image](https://user-images.githubusercontent.com/7731191/147006589-c9a1345c-4dee-4803-b0bd-dc4442c313be.png)
