### ISSUE TITLE
Shadow Bugs Present on Map

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#3111]
**Issue Description:** *Dark square spots remain on Dynmap after a fullrender, for both surface and flat maps. The chunk data appears to be there, so it's more of a lighting issue. Any help here would be much appreciated.*

* **Dynmap Version:** *Dynmap-3.1-beta-3-spigot*
* **Server Version:** *Spigot 1.16.2*
* **Pastebin of Configuration.txt:** *https://pastebin.com/zi5E1nWu*
* **Server Host (if applicable):** *Pebblehost*
* **Other Relevant Data/Screenshots:** *https://imgur.com/At174hM*
* **Steps to Replicate:** *Run a fullrender of the world, these spots are left over after.*

 [x] *I have looked at all other issues and this is not a duplicate*  
(An issue similar to this got closed for a previous build.)
 [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Dynmap doesn't modify world data it just reads the lighting data already in the world, do you see shadows like that in the map?

**Comment by ghost** [comment]
No, if I go back to where the lighting issues are then it looks perfectly normal.

So is this could be an issue with the lighting data on the map already?

**Comment by MaximMaximS** [comment]
I have the same issue.
![image](https://user-images.githubusercontent.com/60849730/98918545-08892280-24ce-11eb-935e-dc2e7a7ae585.png)

![image](https://user-images.githubusercontent.com/60849730/98918588-176fd500-24ce-11eb-8ee6-6b4575e339a3.png)

**Comment by ghost** [comment]
@MaximMaximS Did you also do some kind of pregeneration for chunks? I did that with WorldBorder before then generating the Dynmap, which I think is partly the cause of the strange shadows.

I haven't found a solution to this yet, other than manually using CleanLight to update the lighting on the affected chunks. 
I have noticed that new lighting issues continue to appear though...

**Comment by MaximMaximS** [comment]
Yes, I used WB Fill.

**Comment by ghost** [comment]
I think that's the cause then, I used other chunk pregenerators for the rest of my map (FastChunkPregenerator) and there were no lighting issues after that, I'd recommend switching if you haven't already; it's faster too.

**Comment by seema84** [comment]
it is not the pre-generation
with older dynmap versions these problems did not exist (also with pre-generation worlds)
sometimes there is indeed a shadow in the map but sometimes not
i can confirm this issue

**Comment by mikeprimm** [comment]
See #3565 - this is same issue with same fixes as there (it's not 1.18 specific)
