### ISSUE TITLE
inhabitedTicks field not found - inhabited shader not functional

### ISSUE THREAD

**Issue by Compbuild** [webbukkit/dynmap#3113]
I tried loading a pack on dynmap, but I got this error:

`[INFO] .... [dynmap] inhabitedTicks field not found - inhabited shader not functional`

Using PaperMC 1.15.2-R0.1-SNAPSHOT

Pack (1.14.4, I changed the format to `5` and that's the only thing that is different): https://www.dropbox.com/s/d1o0851mxfvmnpe/Compbuild%20Textures%202.0.1.2.zip?dl=1

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
