### ISSUE TITLE
Dynmap crashing server on startup

### ISSUE THREAD

**Issue by apertureos** [webbukkit/dynmap#3116]
**Issue Description:** I am hosting a Forge server with about 110 mods. Upon startup, the server crashes due to the dynmap causing an exception in the server tick loop.

* **Dynmap Version:** Occurs with the first 3.0 beta and up to the current version (3.1 SNAPSHOT).
* **Server Version:** 1.12.2-forge-14.23.5.2854
* **Pastebin of Configuration.txt:** 
* **Server Host (if applicable):** None.
* **Pastebin of crashlogs or other relevant logs:**
* **Other Relevant Data/Screenshots:** Mods used are in the crash log.
* **Steps to Replicate:** Start up a forge server running the version previously stated using the startup arguments above and the mods provided in the crash log.

**Comment by FedUpWith-Tech** [comment]
Does it crash without those specific startup args?
For example if you used "simple" args like `java -Xmx10G -Xms10G -jar forgeserver.jar nogui`
Does it still crash during startup?

**Comment by CrypticSiri** [comment]
The server starts, but the dynmap itself still crashes. Here's the pastebin of the error: https://pastebin.com/hNeAxgPg

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
