### ISSUE TITLE
Wheat, plant, flower,... not display

### ISSUE THREAD

**Issue by sankakacomplux** [webbukkit/dynmap#3117]
> template is **bold**
> sample data is *italicized*

**Issue Description:** Flower, plant, wheat not display on web map

* **Dynmap Version:** v3.1-beta-3a
* **Server Version:** Paper 1.13.2
* **Pastebin of Configuration.txt:** *https://pastebin.com/EzVf3rUP
* **Server Host (if applicable):** Server.pro
* **Pastebin of crashlogs or other relevant logs:** No error happened
* **Other Relevant Data/Screenshots:** No texturepack and map from 1.13.2
* **Steps to Replicate:**

- Build a farmland with wheat flower etc
- Render the map

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by MrFlacko** [comment]
It won't even let you map this to other blocks

**Comment by FedUpWith-Tech** [comment]
Not showing up on the flat map is expected as plants have 0 width. They do show up on the surface map in 3.3 beta 3 
![image](https://user-images.githubusercontent.com/7731191/147000096-6860dc12-b77e-464a-9c30-adda5efe3919.png)
