### ISSUE TITLE
Support for object storage

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#3118]
I would like to see support for uploading images to object storage (e.g. AWS S3).  
It's useless to allocate image resources for web delivery to storage optimized for Minecraft world data.  
I've dealt with this by going through a CDN or setting up a reverse proxy, but I think it's better to follow the recent standards of web publishing; I don't think it's cool to deliver images from a web server.  
Thanks for reading.

**Comment by FedUpWith-Tech** [comment]
Feel free to make a PR with this functionality

**Comment by ghost** [comment]
@FedUpWith-Tech 
This is **__Feature Request__**.    
I'm truly grateful to you for keeping this project alive, but I'll be sad to close Issue for it.
