### ISSUE TITLE
 Exception during render job

### ISSUE THREAD

**Issue by nicola-de-smet** [webbukkit/dynmap#3120]
> template is **bold**
> sample data is *italicized*

**Issue Description:** Exception during a fullrender of a world which stop the process.

* **Dynmap Version:** dynmap 3.1 beta 3a 1.12.2 but I got the error on older version too
* **Server Version:** Forge 1.12 build
* **Pastebin of Configuration.txt:** http://pastebin.fr/64824
* **Server Host (if applicable):** RoxServer
* **Pastebin of crashlogs or other relevant logs:** http://pastebin.fr/64825
* **Other Relevant Data/Screenshots:** 
* **Steps to Replicate:** I start my server and try to launch a fullrender on my world

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
closing due to dead links
