### ISSUE TITLE
Dynmap crashes with Minecraft 1.16.3 and paper-191.jar.

### ISSUE THREAD

**Issue by randolf** [webbukkit/dynmap#3121]
Thanks in advance for looking into this...

* **Dynmap Version:** *v3.1-beta3a-409*
* **Server Version:** *paper 1.16.3 build 191*
* **Server Host (if applicable):** *Selfhosted on Debian Linux*
* **Steps to Replicate:** *Upgraded from paper-148.jar to paper-191.jar which automatically upgraded Minecraft 1.16.2 to 1.16.3, and now dynmap crashes at start (logs included below); all other plugs that we use are working without any problems*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

Relevant portion of log file...
-------------------------------------

[09:09:06] [Server thread/INFO]: [dynmap] Enabling dynmap v3.1-beta3a-409*                                                                                                                                         
[09:09:07] [Server thread/ERROR]: Error occurred while enabling dynmap v3.1-beta3a-409 (Is it up to date?)                                                                                                         
java.lang.NoSuchMethodError: 'net.minecraft.server.v1_16_R2.IRegistryCustom net.minecraft.server.v1_16_R2.MinecraftServer.aX()'                                                                                    
<------>at org.dynmap.bukkit.helper.v116_2.BukkitVersionHelperSpigot116_2.getBiomeReg(BukkitVersionHelperSpigot116_2.java:70) ~[?:?]                                                                               
<------>at org.dynmap.bukkit.helper.v116_2.BukkitVersionHelperSpigot116_2.getBiomeBaseList(BukkitVersionHelperSpigot116_2.java:84) ~[?:?]                                                                          
<------>at org.dynmap.bukkit.DynmapPlugin.loadExtraBiomes(DynmapPlugin.java:781) ~[?:?]                                                                                                                            
<------>at org.dynmap.bukkit.DynmapPlugin.onEnable(DynmapPlugin.java:856) ~[?:?]                                                                                                                                   
<------>at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-191]                                                                                                   
<------>at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-191]                                                                                     
<------>at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-191]                                                                                    
<------>at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.3.jar:git-Paper-191]                                                                                      
<------>at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.3.jar:git-Paper-191]                                                                                     
<------>at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-191]                                                                                   
<------>at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.3.jar:git-Paper-191]                                                                                        
<------>at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-191]                                                                                           
<------>at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-191]                                                                                  
<------>at java.lang.Thread.run(Thread.java:834) [?:?]                                                                                                                                                             
[09:09:07] [Server thread/INFO]: [dynmap] Disabling dynmap v3.1-beta3a-409                                                                                                                                         
[09:09:07] [Server thread/ERROR]: Error occurred while disabling dynmap v3.1-beta3a-409 (Is it up to date?)                                                                                                        
java.lang.NullPointerException: null                                                                                                                                                                               
<------>at org.dynmap.bukkit.DynmapPlugin.onDisable(DynmapPlugin.java:998) ~[?:?]                                                                                                                                  
<------>at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Paper-191]                                                                                                   
<------>at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Paper-191]                                                                                    
<------>at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Paper-191]                                                                                   
<------>at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.3.jar:git-Paper-191]                                                                                     
<------>at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-191]                                                                                    
<------>at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.3.jar:git-Paper-191]                                                                                      
<------>at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.3.jar:git-Paper-191]                                                                                     
<------>at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-191]                                                                                   
<------>at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.3.jar:git-Paper-191]                                                                                        
<------>at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-191]                                                                                           
<------>at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-191]                                                                                  
<------>at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by FedUpWith-Tech** [comment]
This has already been fixed in Build #414, and build prior to 414 will not work on 1.16.3

Latest dev build can be found [here](https://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-spigot.jar)
