### ISSUE TITLE
Black spaces where modded blocks should be

### ISSUE THREAD

**Issue by Gartosz** [webbukkit/dynmap#3122]
**Issue Description:** *Dynmap shows Chisel, Chisel&Bits and Flatcoloredblocks(and probably some more) mods blocks as a black space.*

* **Dynmap Version:** *Dynmap-3.0-RC3-forge-1.12.2.jar + DynmapBlockScan-3.0-SNAPSHOT-forge-1.12.2.jar*
* **Server Version:** *magma 1.12.2 HEAD-ade7751*
* **Pastebin of Configuration.txt:** *default*
* **Server Host (if applicable):** *Google Cloud*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/PwvbuFrk*

**Comment by FedUpWith-Tech** [comment]
Duplicate of #3112

**Comment by Gartosz** [comment]
Thanks :)
