### ISSUE TITLE
[BUG REPORT] Missing overworld dimension in FTB Interactions 2.0.9

### ISSUE THREAD

**Issue by RappsFF7** [webbukkit/dynmap#3123]
**Issue Description:** *Dynmap won't render or show the overworld dimension on the web using a default configuration in the FTB pack Interactions 2.0.9. Using the command, "dynmap fullrender world" does not work saying, "World 'world' not defined/loaded". Using the command, "dynmap fullrender DIM100" does not work saying, "Could not render: world 'null' not defined in configuration.". Using the command, "dynmap fullrender DIM0" renders the void world. Using the command, "dmap worldlist" shows both DIM0 and DIM100. This pack appears to use Just Enough Dimensions to override the overworld to a void world, and give access to the overworld at a later time (as DIM100?) when the players is better prepared. I don't if JED is causing the issue, but it's my best guess.*

* **Dynmap Version:** *Dynmap-3.1-beta-2-forge-1.12.2 (also tried Dynmap-3.0.1-forge-1.12.2)*
* **Server Version:** *forge 1.12 build 2847*
* **Pastebin of Configuration.txt:** *https://pastebin.com/jxZFaL6G*
* **Server Host (if applicable):** *Private, Windows 10 server*
* **Pastebin of crashlogs or other relevant logs:** *none*
* **Other Relevant Data/Screenshots:** *https://imgur.com/a/PtFiqTA*
* **Steps to Replicate:** *(1) Download the FTB Launcher (https://www.feed-the-beast.com/) (2) Install pack "FTB Interactions 2.0.9. Manually install Dynmap (drop in mods folder) (3) Create a new world. Note, the dynmap will not show an overworld dimension (4) Play or cheat in the overworld portal (5) While in the overworld notice dynmap still doesn't show it but shows you as still in the JED void world.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by dualdragoon** [comment]
I was also wondering if anyone has a fix for this. Best I can figure is that it's somehow due to how JED registers dimensions but I've got no idea how to go about getting it to work.

**Comment by Lambenttelos** [comment]
I'm very unfamiliar with how this is setup but I did notice that the overworld(DIM100) is not defined in the forgeworlds.yml but adding it also did not solve the issue.

**Comment by generrosity** [comment]
Closing this for now as there sounds like there are confounding situations. Major version has been released too - please test and confirm. 

Please also test without JED (or only with JED) and narrow down if it is a dimention mod interaction - this might be unsolvable, but we don't have the setups to do the diagnostics
