### ISSUE TITLE
[Feature Request] Render player heads' skin to show on map

### ISSUE THREAD

**Issue by RWoof** [webbukkit/dynmap#3124]
**Issue Description:** Custom heads from the Head Database plugin are rendered as Steve heads. Could this be a setting in my config? I can see the custom heads properly in-game.

* **Dynmap Version:** Dynmap version: core=3.1-beta3a-409, plugin=3.1-beta3a-409
* **Server Version:** This server is running Paper version git-Paper-138 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
* **Pastebin of Configuration.txt:** https://pastebin.com/yHTzgZ6A
* **Server Host (if applicable):** Self hosted
* **Pastebin of crashlogs or other relevant logs:** N/A
* **Other Relevant Data/Screenshots:** https://imgur.com/a/Y77sJ1Q
* **Steps to Replicate:** Place a custom head in game, when it renders on the map it will be a Steve head.

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
I don't think this is a bug- im not sure you've every been able to see player heads just like you can't read sign text from dynmap

**Comment by RWoof** [comment]
Thanks for the reply, if possible, please move this over to suggestions then, I think if dynmap can gather player skins it should be able to render custom heads as well 👍

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
