### ISSUE TITLE
Web standalone doesn't find configuration?

### ISSUE THREAD

**Issue by arkD** [webbukkit/dynmap#3125]
**Issue Description:** *Hi! I am trying to setup dynmap using s3 static hosting. I followed the guide here: https://github.com/webbukkit/dynmap/issues/2609
*

* **Dynmap Version:** *beta 3a-409*
* **Server Version:** *paper 1.16.2 161*
* **Pastebin of Configuration.txt:** *https://pastebin.com/Xwn3SAKa*
* **Server Host (if applicable):** *HumbleServer, aws S3*
* **Pastebin of crashlogs or other relevant logs:** *None*
* **Other Relevant Data/Screenshots:** 
*Uncaught TypeError: Cannot read property 'error' of null
    at map.js?_=3.1-beta3a-409:29
    at success (jquery.json.js?_=3.1-beta3a-409:82)
    at Object.obj.success (jquery.json.js?_=3.1-beta3a-409:19)
    at fire (jquery-1.11.0.js?_=3.1-beta3a-409:3099)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.js?_=3.1-beta3a-409:3211)
    at done (jquery-1.11.0.js?_=3.1-beta3a-409:9310)
    at XMLHttpRequest.callback (jquery-1.11.0.js?_=3.1-beta3a-409:9720)*
* **Steps to Replicate:** *setup everything in configuration.txt, reload server, copy web folder to s3, setup static hosting, try to load page, encounter error.*

 [X] *I have looked at all other issues and this is not a duplicate*  
it is very similar to a closed issue, and I am not sure it qualifies as the same since I am using amazon s3
 [X] *I have been able to replicate this*

**Comment by arkD** [comment]
I am also having this issue on my local and on a dedicated host with Nginx, PHP-fpm, and required dependencies.

**Comment by arkD** [comment]
in the interest of providing more information:
server:  http://18.216.86.164/dynmap/index.html
<details>
  <summary>Nginx</summary>

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        server_name REDACTED;

        location / {
                index index.html index.php;
                try_files $uri $uri/ /index.php?q=$uri&args =404;
        }

        location ~ [^/]\.php(/|$) {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                include fastcgi.conf;
        }

        location ~ /\.ht {
                deny all;
        }
}
```
</details>
<details>
  <summary>fastcgi.conf</summary>

```
try_files $fastcgi_script_name =404;

# default fastcgi_params
include fastcgi_params;

# fastcgi settings
fastcgi_index                   index.php;
fastcgi_buffers                 8 16k;
fastcgi_buffer_size             32k;
fastcgi_hide_header             X-Powered-By;
fastcgi_hide_header             X-CF-Powered-By;
```
</details>
all files in html folder owned by www-data

**Comment by LLIaMMaH** [comment]
Поддерживаю Подобные настройки и такая же ошибка.
I support Similar settings and the same error.

**Comment by FedUpWith-Tech** [comment]
closing due to age

**Comment by lUNuXl** [comment]
> closing due to age

a classic of the genre

I'm pulling my hair out trying to figure out why dynmap is trying to call configuration.php on a host where dynmap is supposedly configured to just provide static files...
