### ISSUE TITLE
[BUG REPORT] Paper 1.16.3 support

### ISSUE THREAD

**Issue by danielledeleo** [webbukkit/dynmap#3127]
**Issue Description:** *The latest dynmap release does not appear to support Paper 1.16.3*

* **Dynmap Version:** *3.1-beta-3a*
* **Server Version:** *paper 1.16.3 build 198*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/2skYzyER*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
This isn't a bug, the latest release doesn't support 1.16.3 but the latest dev build does. 

You can find a link in the announcements channel of the discord or on reddit
