### ISSUE TITLE
dynmap v3.1-beta3a-409 will freeze randomly & get stuck in a reload loop until cache is cleared 

### ISSUE THREAD

**Issue by TomLewis** [webbukkit/dynmap#3128]
**Issue Description:** Using Paper 1.12.2 with dynmap v3.1-beta3a-409, Dynmap will freeze, as in no data is being updated, but the people on at the time will still be displayed on screen at time of it getting stuck.
When I do `/dynmap reload` this will resolve the issue, but Dynmap will get stuck in a loop of refreshing itself until you clear the cache client side (Video attatched)

Ive been using Dynmap since the early days, so this isn't a new install. 

I host Dynmap myself for HTTPS with Nginx for the last year or so its been fine, its only since I updated to v3.1-beta3a-409.

* **Dynmap Version:** v3.1-beta3a-409
* **Server Version:** Paper 1.12.2
* **Pastebin of Configuration.txt:** https://gist.github.com/TomLewis/18f00275aaad3c065bbab9395a8f27e1
* **Server Host (if applicable):** Dedicated.
* **Map URL:** https://map.piratemc.com
* **Other Relevant Data/Screenshots:** 
The map when it had frozen itself, we had 40+ online at the time.
![Screenshot_2020-09-18 PirateCraft Live Map](https://user-images.githubusercontent.com/144046/93636383-beaf1f00-f9eb-11ea-97ad-fedbdce3536a.jpg)

Video of Loop until you clear cache.
https://streamable.com/2qoc8g

* **Steps to Replicate:** Leave the server running, it'll happen once every few days randomly, nothing in logs to say why. It will only fix once the plugin gets a reload/server reloads.

 [X ] *I have looked at all other issues and this is not a duplicate*  
 [] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Thanks for getting a video of this! Its an uncommon but well known bug and I'm not familiar enough with the web end to take a look at it myself. This is fantastic data for us though!

**Comment by TomLewis** [comment]
No sweat, I wish I now loaded Dev tools in my browser to see if I could figure out what was going on, hindsight is 2020 and all that.

If it happens again, I will pull up Devtools, it might show errors when it tries to pull the JSON or something.

Another piece of information on my setup, I use PHP 7.3.19-1 just in-case there's a conflict somewhere.

There is a difference with output when you host the web server yourself if the plugin gets stuck, self hosted will still display the map HTML as the web server is still up and running (NGINX) as opposed to if it gets stuck with someone using the internal web server where it will fully not show anything, so that may be the only difference with my report if you have had this reported before.
