### ISSUE TITLE
I'm getting this error when i'm setting up dynmap on my website

### ISSUE THREAD

**Issue by Mcdikmen** [webbukkit/dynmap#3131]
Hi,

I followed all the steps on the wiki. But i'm still gettin this error: "Could not retrieve configuration: error". 

How can i fix this?

Thank you.

Here's my configiration.txt: https://pastebin.com/sgUA8cC1

**Comment by Mcdikmen** [comment]
My dynmap version: 3.1 Snapshot
Server Version: 1.16.3

**Comment by notaskunk** [comment]
Had the same issue. Check if adding skip-grant-tables to the MySQL config and restarting MySQL solves the issue. Refer to this answer: https://stackoverflow.com/a/41793945
