### ISSUE TITLE
Dynmap 3.1 Beta 3a -  Exception while loading on spigot 1.16.3 server jar.

### ISSUE THREAD

**Issue by Jake-Thomas-Hall** [webbukkit/dynmap#3132]
**Issue Description:** *Dynmap throws an exception in the log when loading on a spigot 1.16.3 spigot server*

* **Dynmap Version:** *3.1 Beta 3a*
* **Server Version:** *Spigot 1.16.3*
* **Pastebin of Configuration.txt:** *https://pastebin.com/bM66C2Xj*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/pDFXq3Pg*
* **Other Relevant Data/Screenshots:** *N/A*
* **Steps to Replicate:** *Attempt to use dynmap 3.1 Beta 3a on a Spigot 1.16.3 server, maybe with other plugins that are being loaded in the log pastebin, although it's likely this is not related to the other plugins being used.*

- [x] *I have looked at all other issues and this is not a duplicate*  
- [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Use a dev build found on reddit or discord
Beta3a does not support 1.16.3

**Comment by Jake-Thomas-Hall** [comment]
@FedUpWith-Tech Sorry about this, I should have checked the closed issues first...

**Comment by FedUpWith-Tech** [comment]
No worries, you're not the first and you probably won't be the last
