### ISSUE TITLE
Lastest beta bug?

### ISSUE THREAD

**Issue by luismayme** [webbukkit/dynmap#3140]
Dynmap Version: Dynmap-3.1-beta4-spigot
Server Version: Paper-204 (1.16.3)
Pastebin of Configuration.txt: https://pastebin.com/4uzrDVtB
Server Host (if applicable): Local computer
Pastebin of crashlogs or other relevant logs: https://pastebin.com/ZTvE2i4P
Other Relevant Data: My own plugin implements the Dynmap API and so, it has dynmap as softdependance.
Steps to Replicate: Pretty simple:
1-Drop the dynmap jarfile on the plugins folder.
2-Boot the server (first run with dynmap on). ->You'll get the following error on the console (idk if it's relevant to the follow up crash). https://pastebin.com/fFawz7vK.
3-Stop the server and run it again and you'll get the error I'm reporting.

**Comment by ColinShark** [comment]
I'm also using Dynmap `v3.1-beta-2` (specifically `Dynmap-3.1-beta-2-spigot.jar`), but with Paper-206 (1.16.3).

I've pasted my logs at https://mclo.gs/5o02E2t

**Comment by luismayme** [comment]
> I'm also using Dynmap `v3.1-beta-2` (specifically `Dynmap-3.1-beta-2-spigot.jar`), but with Paper-206 (1.16.3).
> 
> I've pasted my logs at https://mclo.gs/5o02E2t

You're using an outdated build of dynmap that doesn't support 1.16.3, that's why your errors.

**Comment by ColinShark** [comment]
> You're using an outdated build of dynmap that doesn't support 1.16.3, that's why your errors.

Huh, and I've taken my file straight from GitHub Release page :/
Anyway, [r/Dynmap's Sticky post](https://www.reddit.com/r/Dynmap/comments/iqkif9/first_official_snapshot_build_for_spigotpaper_1163/) got my up and running.

**Comment by luismayme** [comment]
While doing a bit of research I discovered that probably is something wrong with the use of the API? I'm going to post here the markers.yml that dynmap is unable to read (althought it is written via its API): https://pastebin.com/dMBMANn7

Now the code that creates this: https://pastebin.com/kKrwsLGb
I know there might be a better way of getting the server path or I could just drop the png file in the plugins folder, but that doesn't seem to be the problem since the first startup works just fine.

**Comment by FedUpWith-Tech** [comment]
Your pastebin crashlogs have been deleted, please update then reopen
