### ISSUE TITLE
How do I disable sidebar player list & server player list info?

### ISSUE THREAD

**Issue by hostkimjang** [webbukkit/dynmap#3141]
Hello!
My server is hide player list & When connecting to the server, the number of users is being displayed as'???'
but, where dynmap sidebar is announce player list. How can i hide sidebar player list?

**Comment by FedUpWith-Tech** [comment]
You can disable the sidebar in the config, warning if you disable the sidebar you will disable the ability to switch maps. I recommend you disable player locations or disable players in the sidebar instead

**Comment by hostkimjang** [comment]
I solve it
I modify map.js and Annotation it

		//var playersSection = SidebarUtils.createListSection(me.options['msg-players']);
		//me.playerlist = playersSection.content.addClass('playerlist');
		//playersSection.section.appendTo(panel);
		//me.playerfield = playersSection.legend;
		//me.sidebarSections.push(playersSection);
