### ISSUE TITLE
Not Work JDynmapGriefPrevention

### ISSUE THREAD

**Issue by kotarobo** [webbukkit/dynmap#3144]
* **Dynmap Version:** *3.1-beta4-421*
* **Server Version:** *paper(202) 1.16.3-R0.1-SNAPSHOT*
* **Pastebin of Configuration.txt:** *https://pastebin.com/SK1xgQBM*
* **Server Host (if applicable):** *Selfhosted*
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *JDynmapGriefPrevention was the best plugin for checking GriefPrevention's protected areas, but after updating to 1.16.3, it no longer appears.
It was visible in 1.16.2.
It would be great if you could fix the compatibility.*

 [✔] *I have looked at all other issues and this is not a duplicate*  
 [✔] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
https://github.com/webbukkit/Dynmap-GriefPrevention/issues

**Comment by kotarobo** [comment]
Here.
https://www.spigotmc.org/resources/jdynmapgriefprevention.818/
I'm sad to say that there probably won't be any updates.

**Comment by FedUpWith-Tech** [comment]
Well that isn't even made by the dynmap team, any support needs to be taken up with the plugin author jahangir13
