### ISSUE TITLE
Tiles don't update when switching players

### ISSUE THREAD

**Issue by Insprill** [webbukkit/dynmap#3146]
**Issue Description:** *When switching between players on the little menu on the right, rendered tiles from where the previous was, show up in un-rendered spawn where the new player is.*

* **Dynmap Version:** *core=3.1-beta-421, plugin=3.1-beta-4-421*
* **Server Version:** Paper-221 (1.16.3)
* **Pastebin of Configuration.txt:** *https://pastebin.com/mTqgW1cz*
* **Other Relevant Data/Screenshots:** *https://prnt.sc/uwvpyu*
* **Steps to Replicate:** *Render in a few tiles in one part of the world, then in another. then with a player in each, click on the first player to load where they are, then the second. if rendered tiles from the first are in the blank at the second, they will still show.*

 [✔️] *I have looked at all other issues and this is not a duplicate*  
 [✔️] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
This is probably an issue with your local browser cache try pressing `shift f5` on the dynmap page then switching players. 

(if that is the issue then its likely fixed by now anyways due to browser cache resetting on its own)

**Comment by Insprill** [comment]
Yeh but it happens all the time, not just here and there.

**Comment by generrosity** [comment]
Closing - potentially a local browser issue, or Leaflet issue (which has been upgraded since then I belive) -  major version is out, so if you can still replicate the issue and confirm others can replicate it too happy to see this re-opened but might get hit with 'workaround: just refresh'
