### ISSUE TITLE
Logging in shows JSON

### ISSUE THREAD

**Issue by g-regor** [webbukkit/dynmap#3150]
**Issue Description:** Logging in navigates to `/up/login` and shows a JSON response instead of redirecting to `index.html`.
Same for registering.

* **Dynmap Version:** v3.1-beta4
* **Server Version:** Spigot 1.16.3
* **Steps to Replicate:** Enable login and register. After that also logging in reproduces this.

- [x] *I have looked at all other issues and this is not a duplicate*  
- [x] *I have been able to replicate this*

The problem is that `login.html` tries to load an older version of jQuery (1.11.0) instead the newer one (3.5.1). This results in 404 for the .js file and `login.html:17 Uncaught ReferenceError: $ is not defined` and eventually failing to redirect to `/index.html`.

https://github.com/webbukkit/dynmap/blob/56076f44ef9109cf3e9dda630fc50cfeba893cfe/DynmapCore/src/main/resources/extracted/web/login.html#L14

**Comment by Polda18** [comment]
I can confirm that, too. Plugin version:
```
[18:37:04 INFO]: Dynmap version: core=3.1-beta4-421, plugin=3.1-beta4-421
```

**Comment by FedUpWith-Tech** [comment]
Fixed in https://github.com/webbukkit/dynmap/commit/9983bef35303b6a2751655fba13996d0f2e5edba
