### ISSUE TITLE
Set a temporary marker at the urls position

### ISSUE THREAD

**Issue by Schpammer** [webbukkit/dynmap#3151]
**Feature Description:** *When generating or opening a link that includes coordinates as query parameter (e.g. https://map.example.com/?worldname=world&mapname=flat&zoom=4&x=616&y=64&z=4010), show a temporary marker to the user at the given position.
This should be helpful to see the precise position on the map. The map generator 'Overviewer' already supports the creation of clientside markers by adding parameters to the url.
It would be nice to have to define a default marker icon in the config or even pass the icons id as url parameter.*

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
