### ISSUE TITLE
Can't use custom map icons on custom maps in web legend

### ISSUE THREAD

**Issue by SajmonOriginal** [webbukkit/dynmap#3153]
**Can't use custom map icons on custom maps in web legend**
> sample data is *italicized*

*Hi on the dynmap I have 3 maps in the world named flat, surfaceday and surfacenight in the images folder I named the icon file: "block_world_surfaceday.png" last time it worked on 1.14 when i tried to use dynmap, but this time nothing was displayed only black icon, it was supposed to be fixed in the latest dynmap beta version I use now but the only thing it caused it's just that no matter what I do, I'll name the icon file so one and the same flat map icon is applied to all maps in the legend. When I try to set it manually with the command, there is again a black icon. I don't know if it's just a dynmap error or I'm doing something wrong but please help .. thank you in advance. It tried to look at web elements with CTRL+SHIFT+I and find out that every map has `style="background-image: url("images/block_world_flat.png");"` as image and cannot be changed with command in game*

* **Dynmap Version:** *v3.1-beta-4*
* **Server Version:** *Latest paper spigot build-240 uploaded: 17. 10. 2020 20:55*
* **Pastebin of Configuration.txt:** *https://pastebin.com/vftPfTXR*
* **Other Relevant Data/Screenshots:** *https://i.imgur.com/6YM7WK7.png - web elements, https://i.imgur.com/Yz8A92a.png - before "fix", https://i.imgur.com/WMHipTM.png - after fix *
* **Steps to Replicate:** *Just create custom map with custom name and give it custom png icon in 16x16 and you will see*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this on my Windows computer*

I tried to solve this issue on Reddit but no answer whole month so im trying here now.. 
https://www.reddit.com/r/Dynmap/comments/iitjgj/cant_use_custom_icons_on_custom_map_in_legend/

**Comment by FedUpWith-Tech** [comment]
closing due to age
