### ISSUE TITLE
Legacy plugin dynmap v3.1-beta4-421 does not specify an api-version.

### ISSUE THREAD

**Issue by FaMa91** [webbukkit/dynmap#3154]
As far as I know, you can fix that issue adding api-version: 1.13 in your plugin.yml file. There is no problem with previous versions.

Thank you.

**Comment by FedUpWith-Tech** [comment]
This doesn't work as the dynmap is build for many versions of minecraft which don't support the 1.13 api. The same core code supports minecraft 1.11.2-1.16.3 spigot/bukkit/paper/forge/fabric and other unofficially supported server platforms so specifying an api version would break legacy platforms.

**Comment by FaMa91** [comment]
if forge/fabric and other unofficially supported server platforms didn't use the option api-version, they shouldn't read that option at all.

And versions < 1.13 will ignore it for sure.

I can't see the problem, have you already tried?

**Comment by molor** [comment]
@FedUpWith-Tech & @mikeprimm, this warning slows down the server starting time every time for 5-15 seconds.. :c
Maybe you should build two versions of the dynmap, one for versions >= 1.13 and one for <1.13?

**Comment by LaurenceBarnes** [comment]
> @FedUpWith-Tech & @mikeprimm, this warning slows down the server starting time every time for 5-15 seconds.. :c
> Maybe you should build two versions of the dynmap, one for versions >= 1.13 and one for <1.13?

I agree with that

**Comment by molor** [comment]
omg, adding `api-version: 1.13` to the `plugin.yml` of downloaded dynmap jar don't break anything on Paper 1.16.5 server. It works perfectly and now starts up much faster..

Older servers will just ignore this line, newer can start faster.. What are the problems, developer?
@mikeprimm @FedUpWith-Tech

**Comment by mikeprimm** [comment]
Older spigot servers do NOT ignore the line - this has been discussed and confirmed before...

Edit: I don't know that 1.13 was tried - will confirm this vs 1.12, but we had to pull the last 'clever' PR that added it and broke hundreds of existing server.

**Comment by molor** [comment]
Hmmm, strange, but OK, thanks for clarification — for some reason I remembered that older servers ignored this line

**Comment by mikeprimm** [comment]
I will revisit this - I'm pretty sure the last time someone jammed it in, it might have been 1.14 or 1.15 - sorry, the behavior of that flag is irritating, as things do work, and there is really no reason to be fussing about it, much less slowing down startup.

**Comment by molor** [comment]
In my case adding this line increased startup speed from 25s to 15s (**~60%!**) with 60 plugins including the dynmap.. Considering how often I have to restart my test server during a working day for development and testing — reducing the starting time is a huge time saver and therefore for me (and I think I am not alone) this is very important.

Thanks
