### ISSUE TITLE
Dynmap Fullrender Not Working (Have Tried All Solutions On Google)

### ISSUE THREAD

**Issue by deprante** [webbukkit/dynmap#3155]
Hi!

So as you can see from the title Dynmap won't fullrender no matter what. I've tried every single solution online including, deleting tiles folder, purgingworld uninstalling /wb fill then reinstall and fullrender, /wb fill, reuploading world file, and more... The strangest part imo is that for some reason the nether world worked fine when rendering.  Whenever I /dynmap fullrender it just renders the chunks that I've explored and says complete. I've installed another chunk loading plugin called "Chunky" to see if it makes a difference but I do think that Dynmap is actually the problem since the /wb fill worked fine for the nether world. I've been trying to fix this for the past week but nothing worked.

**Comment by deprante** [comment]
I've also even tried using a different Dynmap version (didn' work)

**Comment by isaaclepes** [comment]
I had a similar symptom when I first started.  For me, I needed to optimize my server because the TPS rate was below the threshold for Dynmap rendering. Try "/dynmap pause" and see if it shows Active, Paused, or TPS Paused for anything.

**Comment by FedUpWith-Tech** [comment]
closing due to age
