### ISSUE TITLE
Server crashing randomly

### ISSUE THREAD

**Issue by MinecraftCitiesNetwork** [webbukkit/dynmap#3158]
**Issue Description:** 
Our server is randomly crashing out of nowhere with this one error. There is nothing broken before it.
* **Dynmap Version:*  3.1-beta4-421
* **Server Version:**  1.16.3 Paper
* **Pastebin of Configuration.txt:** https://pastebin.com/tUjPZeJQ
* **Server Host (if applicable):** *McProHosting, Shockbyte, Selfhosted, etc.* Dedicated VPS, will give host if applicable
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/VxH2W3U9* 
* **Other Relevant Data/Screenshots:** The only remotest error before it happened was "Can't keep up! Is the server overloaded? Running 14133ms or 282 ticks behind", nothing else.
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*
Have a bunch of players playing, there is nothing else or special I have done.
 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
This is why your server is crashing, not dynmap
`[20:55:01] [Paper RegionFile IO Thread/ERROR]: Chunk [-886, -235] stream is truncated: expected 4767 but read 4091`
this usually indicates world corruption
