### ISSUE TITLE
Dynmap is disabled (unsupported platform)

### ISSUE THREAD

**Issue by soshimee** [webbukkit/dynmap#3160]
> template is **bold**
> sample data is *italicized*

**Issue Description:** Dynmap says `Dynmap is disabled (unsupported platform)` in startup. The strange thing about this is that /dynmap commands work properly, except everything else does not.

* **Dynmap Version:** 3.0.1
* **Server Version:** This server is running Tuinity version git-Tuinity-"de1983b" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
* **Pastebin of Configuration.txt:** configuration.txt does not generate
* **Server Host (if applicable):** GGServers (has ports range that includes 8123 open)
* **Pastebin of crashlogs or other relevant logs:** Title.
* **Other Relevant Data/Screenshots:** None.
* **Steps to Replicate:** IDK, just happens when I use Dynmap.

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this* (by downloading latest Dynmap again)

**Comment by FedUpWith-Tech** [comment]
You're not running the latest version of dynmap. Please update and re-open if the issue persists.

**Comment by soshimee** [comment]
Sorry for that, I just downloaded it though.

**Comment by akacdev** [comment]
I'm using the version 3.1 beta4 for Spigot on a 1.16.4 server and I'm having the same issue.

**Comment by thefirstmine** [comment]
Hi, 1.16.4 is not supported yet for Dynmap, please wait for them to release a new update :)

**Comment by akacdev** [comment]
From the readme I see it's up to for 1.16.1, is this the latest version? @thefirstmine

**Comment by akacdev** [comment]
How is this person running it on 1.16.3 after updating?

**Comment by thefirstmine** [comment]
Hi AkaCrafterCZ, beta versions of Dynmap exist.
https://www.spigotmc.org/resources/dynmap.274/updates
![IMG_1227](https://user-images.githubusercontent.com/53891525/98462841-0daa5100-21f2-11eb-844d-a5df2d5c82da.jpeg)

**Comment by akacdev** [comment]
@thefirstmine I see now, works just fine on 1.16.3. Thanks!
