### ISSUE TITLE
Support for 1.16.4

### ISSUE THREAD

**Issue by molor** [webbukkit/dynmap#3162]
Add support for MC 1.16.4 (v1_16_R3) please.

**Comment by FedUpWith-Tech** [comment]
Support will come, please be patient as we update the plugin 😃

**Comment by Blueeyestar** [comment]
Is everything ok with you? You never had to wait that long for a new version. There are several versions of Dynmap 1.16.4 on the Internet that run clean and well. So this time I'm really surprised why Dynmap takes so long this time. Since actually only the version number has to be rewritten in the file.
I hope you will manage to update the dynmap soon ... as I said, this time I'm really surprised ............

**Comment by sems** [comment]
@molor Currently #3163 is open for review. So hopefully soon :D

**Comment by Auliyaa** [comment]
In the meantime, is there a branch I can build locally to try for myself ?

**Comment by Blueeyestar** [comment]
> 
> 
> In the meantime, is there a branch I can build locally to try for myself ?

We are currently using a private fix that is working. I am surprised that so far neither a message nor an update has come from the official side.

**Comment by FedUpWith-Tech** [comment]
> > 
> > 
> > In the meantime, is there a branch I can build locally to try for myself ?
> 
> We are currently using a private fix that is working. I am surprised that so far neither a message nor an update has come from the official side.

I commented on the update status on the 1.16.4 PR as well as on the discord last night

**Comment by Blueeyestar** [comment]
> 
> 
> > > In the meantime, is there a branch I can build locally to try for myself ?
> > 
> > 
> > We are currently using a private fix that is working. I am surprised that so far neither a message nor an update has come from the official side.
> 
> I commented on the update status on the 1.16.4 PR as well as on the discord last night

we're not in Discord here on Github ... how should users know? the info would be appropriate here not discord

**Comment by FedUpWith-Tech** [comment]
I literally just said I commented on the 1.16.4 PR **as well as** the discord. 
https://github.com/webbukkit/dynmap/pull/3163#issuecomment-723454044

**Comment by FedUpWith-Tech** [comment]
Update from mike on discord- PR is merged and the 1.16.4 beta is being built.

He's been super busy with 80+ hour weeks for the past couple weeks and progress is moving slowly but I would imagine we will get the official announcement and build later today

**Comment by Blueeyestar** [comment]
There is now a 1.16.4 version at https://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-spigot.jar

Thanks a lot for this
