### ISSUE TITLE
Error 500 on Paper 1.12.2 build 1618

### ISSUE THREAD

**Issue by PerchunPak** [webbukkit/dynmap#3165]
**Issue Description:** *Error 500 when trying load page (http://217.106.107.176:30001).*

* **Dynmap Version:** *Dynmap version: core=3.1-beta4-421, plugin=3.1-beta4-421*
* **Server Version:** *Paper 1.12.2 build 1618*
* **Pastebin of Configuration.txt:** *https://pastebin.com/eFUEm2PQ*
* **Server Host (if applicable):** *https://bungee.host*
* **Pastebin of crashlogs or other relevant logs:** *nothing find*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by PerchunPak** [comment]
i used rcon port

**Comment by FedUpWith-Tech** [comment]
Your port `30001` [is closed.](https://imgur.com/ovygOxI)
