### ISSUE TITLE
"Error occurred while disabling dynmap v3.1-SNAPSHOT-426", site "can't be reached"

### ISSUE THREAD

**Issue by Cassolotl** [webbukkit/dynmap#3166]
**Issue Description:** Our Dynmap "can't be reached" by the browser following an update to Spigot 1.16.4 and updating Dynmap to the latest version. There are error messages in the console when shutting down the server.

* **Dynmap Version:** dynmap version 3.1-SNAPSHOT-426
* **Server Version:** This server is running CraftBukkit version git-Spigot-aa47792-6fd677c (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
* **Pastebin of Configuration.txt:** https://pastebin.com/A4AdsgRs
* **Server Host (if applicable):** Nitrous Networks
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/eUsRrsfq
* **Other Relevant Data/Screenshots:** N/A
* **Steps to Replicate:** I updated Spigot to the version above, which is what Nitrous Networks have in their modpacks section. Then I updated Dynmap to "Dynmap-HEAD-spigot.jar | 2020-10-25 19:20 | 6.8M" from [here](http://dynmap.us/builds/dynmap/?C=M;O=D). Now when I try to load [the map](http://89.34.96.19:8765/), the browser says "this site can't be reached".

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by Cassolotl** [comment]
Why has this been closed, please? Has it been fixed, or is it a duplicate, or is it not a Dynmap bug, or something else?

**Comment by FedUpWith-Tech** [comment]
There is no dynmap build for 1.16.4, if you look at the recent github issues you will see one asking for 1.16.4 support

**Comment by Cassolotl** [comment]
Ah I see. Is this the right issue to follow? *Dynmap error on 1.16.4 with Beta5 #3178*

**Comment by FedUpWith-Tech** [comment]
No that isn't the same version of minecraft server. They are using Purpur Server which is a custom paper fork, custom forks break dynmap more often that not. There is now a beta release of 1.16.4 which should work for the major server softwares (Paper, Spigot, Bukkit)

**Comment by Cassolotl** [comment]
Great, I'll try updating tomorrow sometime and let you know if it doesn't work. Thanks!
