### ISSUE TITLE
Nether icons are set to default and can't be set.

### ISSUE THREAD

**Issue by WELTEINZ** [webbukkit/dynmap#3175]
See Topic: Nether icons in the Sitemap are set to default and can't be set.

3.1-beta5
paper 1.16.4 build 265

![2020-11-11 11_30_54-Window](https://user-images.githubusercontent.com/44711940/98801146-ad91f580-2411-11eb-99be-ca1885deb70e.png)

![2020-11-11 11_59_06-Window](https://user-images.githubusercontent.com/44711940/98803998-d916df00-2415-11eb-9766-7ceaf798255c.png)

Edit: Same for the favicon (dynmap.ico) as you see in the screenshot above, normally it's that:

![2020-11-11 12_13_20-Window](https://user-images.githubusercontent.com/44711940/98805156-73c3ed80-2417-11eb-86b1-839e97a99266.png)

**Comment by FedUpWith-Tech** [comment]
Not sure if this is still relevant as it is a very old issue:

Was not able to replicate this issue:
![image](https://user-images.githubusercontent.com/7731191/147004579-d23b2fbf-00f1-4b45-87b7-226bc37ecea8.png)
Make sure you run `/dynmap pause all` before making changes to the map icons.
