### ISSUE TITLE
Include Nether-Ores such as Ancient Debris in hideores

### ISSUE THREAD

**Issue by WELTEINZ** [webbukkit/dynmap#3176]
See Topic: Please include Nether-Ores such as Ancient Debris related to the parameter hideores:true.

3.1-beta5
paper 1.16.4 build 265

![2020-11-11 12_00_39-Window](https://user-images.githubusercontent.com/44711940/98804042-ecc24580-2415-11eb-97ba-8af70a204ef5.png)

**Comment by FedUpWith-Tech** [comment]
Great idea! This definitely would make sense.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
