### ISSUE TITLE
Dynmap error on 1.16.4 with Beta5

### ISSUE THREAD

**Issue by JustAMatt** [webbukkit/dynmap#3178]
**Issue Description:** *During 1.16.4 trials I've found issues with the latest beta of Dynmap. Once I did an 100% clean install with default generated files I got a disabled on startup error. Using Purpur 822 (1.16.4).*

* **Dynmap Version:** *v3.1-beta5-431*
* **Server Version:** *Purpur (Paper, Tuinity) 1.16.4*
* **Pastebin of Configuration.txt:** *Default Dynmap config*
* **Server Host (if applicable):** *Selfhoted (Test server)*
* **Pastebin of crashlogs or other relevant logs:** *https://hastebin.com/eturovoyeg.sql*
* **Steps to Replicate:** *v3.1-beta5-431 + Purpur 1.16.4*

 [Yes] *I have looked at all other issues and this is not a duplicate*  
 [Yes] *I have been able to replicate this*

**Comment by JustAMatt** [comment]
After updating the server jar the error changed, but they seem to be different each time as well. https://hastebin.com/nixasumuku.properties

**Comment by FedUpWith-Tech** [comment]
I can't replicate this issue on default Paper. We don't officially support Purpur so I can't give an ETA on when this will be fixed if ever.

**Comment by JustAMatt** [comment]
#3180

**Comment by JustAMatt** [comment]
This is a similar issue as "Dynmap Beta5-431 Startup Initialization Error" #3180 and other comments found in the Dynmap discord

**Comment by FedUpWith-Tech** [comment]
You referenced this issue in your comment?

**Comment by JustAMatt** [comment]
Sorry wrong issue, I edited the comment with the proper #3180

**Comment by FedUpWith-Tech** [comment]
Thats a different error, your error is related to the marker code whereas their error is related to an incompatible server version. I can't replicate #3180's error with a fresh paper server and v3.1-beta5-431

**Comment by JustAMatt** [comment]
I was able to replicate the issue in Paper 276 https://hastebin.com/hesebukaco.yaml

**Comment by JustAMatt** [comment]
I just waited for a few paper updates and after 280 it worked 🤷
