### ISSUE TITLE
Campfire sprite still broken

### ISSUE THREAD

**Issue by Aaron2550** [webbukkit/dynmap#3181]
This is basically #2527 but in new

**Issue Description:** The campfire sprite is rendered incorrectly on flat maps.

* **Dynmap Version:** v3.1-SNAPSHOT-426
* **Server Version:** git-Paper-252 1.16.3
* **Pastebin of Configuration.txt:** Shouldn't matter
* **Other Relevant Data/Screenshots:** It looks like this https://files.catbox.moe/4bellt.jpg and should look something like this https://files.catbox.moe/fl49tc.jpg
* **Steps to Replicate:** 1. Place campfire 2. Render flat map

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Thanks for the update on this!

**Comment by FedUpWith-Tech** [comment]
@mikeprimm I know this is a low-priority issue but wanted to give it a bump since its been a year.

Still present in [dynmap] version 3.3-beta-3-591 - core version 3.3-beta-3-591
![image](https://user-images.githubusercontent.com/7731191/146999575-a3ac03cd-e59d-4d7c-a0b8-9aa6d8fe17e1.png)

**Comment by Aaron2550** [comment]
I could make a PNG with the correct texture but idk if that's how you guys implement broken texture fixes and also idk if that would violate mojank copyrights etc ..
