### ISSUE TITLE
People not in my network cant view the map 

### ISSUE THREAD

**Issue by ArabianBoi1259** [webbukkit/dynmap#3186]
this has been reported before but none of the solutions really help. dynmap works for me as i am the host of the server it is locally run on my own computer and i have the map rendered (in short it works and its setup). ive had friends test it for me by me sending them links to the webpage but they either cant connect or its just a blank screen i have dynamap on port 25566 as the mc server itself is on 25565 and i have port forwarded it in my router. 
in the config settings  # webserver-bindaddress: (my ipv4)  and in webserver-port: 25566 

these are the settings i have setup am I missing something? (is it something with the fire wall?) idk the Minecraft server itself works fine and people can connect to it . I am fairly new to this and i run paper spigot if that is relevant thanks in advance 

forgot to mention that i am using a 1.16.4 beta but this was a problem even on 1.16.3 

edit: i found this error in my console when the server is starting 

WARN]: [dynmap] cwebp or dwebp not found, or cwebpPath or dwebpPath is invalid: webp format disabled

**Comment by GlorifiedToastr** [comment]
@ArabianBoi1259 

Try setting webserver-bindaddress to 0.0.0.0 maybe? Thats what I have to do and it works like a charm.

**Comment by ArabianBoi1259** [comment]
> @ArabianBoi1259
> 
> Try setting webserver-bindaddress to 0.0.0.0 maybe? Thats what I have to do and it works like a charm.

Thanks for the suggestion i tried it and sadly it still does not work they still see nothing and cant connect

**Comment by Genau6502** [comment]
This may be a poor question but have you port forwarded 25566?
