### ISSUE TITLE
Dynmap plugin loads, but external web server not functioning properly

### ISSUE THREAD

**Issue by partydev** [webbukkit/dynmap#3187]
**Issue Description:** _Dynmap seems to be functioning properly, but we used an external web server and have the files hosted on our website directly. However, we are just getting a black screen. Worked fine on 1.16.3, we updated and replaced the folder on the web server with the web folder contents from the plugins/dynmap folder. Just a black screen. Debugging points to some JS issues?_

Relevant config:
The path where the tile-files are placed.
tilespath: /var/www/bartyrealms.com/html/mapsource/tiles

The path where the web-files are located.
webpath: /var/www/bartyrealms.com/html/mapsource

Website for map:
https://bartyrealms.com/mapsource/

Web directory
![image](https://user-images.githubusercontent.com/42015460/99600931-5f11c780-29cc-11eb-9179-3b40ea30b61f.png)

* **Dynmap Version:** *3.1-beta5-spigot*
* **Server Version:** *Purpur 1.16.4 Build 839*
* **Pastebin of Configuration.txt:** *https://pastebin.com/3HwuS145*
* **Server Host (if applicable):** *OVH*
* **Pastebin of crashlogs or other relevant logs:** *No errors/logs.*
* **Other Relevant Data/Screenshots:** *N/A*
* **Steps to Replicate:** *Described in issue description.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by GlorifiedToastr** [comment]
Yes same exact issue here:

Seems it is a JS issue as config.js has a status of 404 for some reason but only on an external web server.
If I load the map locally using the Minecraft Server IP and Dynmap port I have no issues. Only on an external web server there is issue.

Can confirm external web servers DID work on 1.16.3, issue occurs only when running on 1.16.4.

**Comment by partydev** [comment]
> 
> 
> Yes same exact issue here:
> 
> Seems it is a JS issue as config.js has a status of 404 for some reason but only on an external web server.
> If I load the map locally using the Minecraft Server IP and Dynmap port I have no issues. Only on an external web server there is issue.
> 
> Can confirm external web servers DID work on 1.16.3, issue occurs only when running on 1.16.4.

This was fixed by us by regenerating the web directory to the new default files.

**Comment by GlorifiedToastr** [comment]
Yes, I just had to update my config to point back to my external webserver. oof lol

Best of luck!

**Comment by partydev** [comment]
Going to go ahead and close this, hope this helps others in the future.
