### ISSUE TITLE
Show last 15 messages in webchat while typing

### ISSUE THREAD

**Issue by MSiegrist** [webbukkit/dynmap#3188]
**Feature Description:** 
* On the webpage, when the chat input box is in focus (so the user is either typing or just clicked into the chat input) the last 15 messages should appear again. 
* If the focus of the chat input is lost or a message is sent by the user, the chat box returns to normal, displaying the recent messages that not have reached their timeout/ttl yet. 
* The number of messages shown could be a setting. 
* Messages that where sent before the webpage was opened might not be shown.

**Additional context:** Goal of this feature request is to bring the web chat closer to the in-game chat experience. 
It's easy to miss someone’s message, especially when the map is open on another tab or screen. With this feature users would be able to see the last messages again just like in-game when you open chat with 'T'. By only showing up when the chat is being used, this does not block the view of the map.
On the technical side, all messages shown in the chat box need to be saved temporarily and deleted as new ones come in. That includes join and quit messages. This could all be done client side in the existing JavaScript.

**Future improvements:** The suggested feature and its scope was chosen because its perceived simplicity and ease of implementation. The next logical step would be to have all messages saved and offer a scrollable chat box when in focus. Another possible improvement would be to fetch the most recent messages from the server when the webpage is opened.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
