### ISSUE TITLE
Adding more GET parameters: remove certain GUI elements but keep player heads & markers

### ISSUE THREAD

**Issue by skerit** [webbukkit/dynmap#3193]
**Feature Description:** *Currently `nogui=true` disables everything so that only the map is visible, but I actually would like to show the markers & the playerheads. Maybe even allow enabling specific marker sets.*

* **Additional context:** *There is quite a lot of clutter when embedding the map on another page as-is. Nogui helps, but then the map kind of feels "empty" because you can't see players or their markers on the map. Ideally I would like to hide the location info, the layer selection, the link button, the login button & the current time, but keep player heads, markers & zoom controls*

**Comment by FedUpWith-Tech** [comment]
You can 
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
