### ISSUE TITLE
cpu load

### ISSUE THREAD

**Issue by seema84** [webbukkit/dynmap#3194]
**Feature Description:** *is there an option to reduce the cpu load and therefore increase the render time?*

* **Additional context:** *some gameserver hoster restart servers if the cpu load is to hight*

**Comment by thefirstmine** [comment]
If your CPU load is too high, just reduce the quality of the render.

**Comment by seema84** [comment]
but then things look worse

**Comment by YamiOdymel** [comment]
you may check the options in `configuration.txt`:

```
# How many update tiles to work on at once (if not defined, default is 1/2 the number of cores)
tiles-rendered-at-once: 1

# If true, use normal priority threads for rendering (versus low priority) - this can keep rendering
# from starving on busy Windows boxes (Linux JVMs pretty much ignore thread priority), but may result
# in more competition for CPU resources with other processes
usenormalthreadpriority: true

# Parallel fullrender: if defined, number of concurrent threads used for fullrender or radiusrender
#   Note: setting this will result in much more intensive CPU use, some additional memory use.  Caution should be used when
#  setting this to equal or exceed the number of physical cores on the system.
parallelrendercnt: 1
```

**Comment by seema84** [comment]
thanks i will check this settings
are the values of your proposals?

**Comment by YamiOdymel** [comment]
> thanks i will check this settings
> are the values of your proposals?

Those are mine values for the minecraft server that running on my NAS (Intel Pentium G6400, Dual-Cores), but might fits for your situation.

**Comment by seema84** [comment]
okay i will try

**Comment by Pingger** [comment]
Additionally you should take a look at this setting:

```
# Period between tile renders for fullrender, in seconds (non-zero to pace fullrenders, lessen CPU load)
timesliceinterval: 0.0
```

And this one
```
# Maximum chunk loads per server tick (1/20th of a second) - reducing this below 90 will impact render performance, but also will reduce server thread load
maxchunkspertick: 200
```

**Comment by seema84** [comment]
I will do, thanks

**Comment by rautamiekka** [comment]
1 is to use WebP instead of PNG, or, Heaven forbid, JPG. A lossy WebP has a higher quality on a lower setting than JPG, doesn't take as long to process, and takes less space.

^ Chrom{e|ium}, Firefox Quantum, Opera (dunno about pre-Chromium), and even that piece-of-shit pre-Chromium Edge (among others) support WebP.

**Comment by Pingger** [comment]
> 
> 
> 1 is to use WebP instead of PNG, or, Heaven forbid, JPG. A lossy WebP has a higher quality on a lower setting than JPG, doesn't take as long to process, and takes less space.
> 
> ^ Chrom{e|ium}, Firefox Quantum, Opera (dunno about pre-Chromium), and even that piece-of-shit pre-Chromium Edge (among others) support WebP.

1. No, webp takes more cpu processing time. (The entire point of webp is to provide small files at the cost of creation time, so that servers can serve the same file to more people with the same bandwidth limits)
2. Most serverproviders don't provide the necessary binaries for webp
3. AFAIK The implementation of dynmap for webp is actually creating a png and converting it afterwards with an external tool to webp (which as mentioned in the previous point, most servers don't have installed)

**Comment by rautamiekka** [comment]
> > 1 is to use WebP instead of PNG, or, Heaven forbid, JPG. A lossy WebP has a higher quality on a lower setting than JPG, doesn't take as long to process, and takes less space.
> > ^ Chrom{e|ium}, Firefox Quantum, Opera (dunno about pre-Chromium), and even that piece-of-shit pre-Chromium Edge (among others) support WebP.
> 
> 1. No, webp takes more cpu processing time. (The entire point of webp is to provide small files at the cost of creation time, so that server can server the same file to more people with the same bandwidth limits)
> 2. Most serverproviders don't provide the necessary binaries for webp
> 3. AFAIK The implementation of dynmap for webp is actually creating a png and converting it afterwards with an external tool to webp (which as mentioned in the previous point, most servers don't have installed)

Well shit, that really sucks.
