### ISSUE TITLE
End Islands not rendering

### ISSUE THREAD

**Issue by seema84** [webbukkit/dynmap#3197]
**Issue Description:** *Fullrender is not rendered completely. 
The full rendering is completed successfully. But not everything is rendered.*

* **Dynmap Version:** *dynmap v3.1-beta5-431*
* **Server Version:** *This server is running Paper version git-Paper-288 (MC: 1.16.4)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/8xYsTQw5*
* **Other Relevant Data/Screenshots:** 

surface: https://i.imgur.com/xlAbJ0b.png

flat: https://i.imgur.com/KyiFU9N.png

* **Steps to Replicate:** *create and finish a fullrender in world_the_end*

**Comment by Anthropomorphed** [comment]
Same issue with End Flat, Spigot 1.16.4.
Dynmap version: 3.1-beta6-438.
End Surface worked
Update:
doing '/dynmap fullrender world_the_end:flat' didn't work until i started the '/dynmal fullrender world:flat'
Now it runs simultanously.

**Comment by seema84** [comment]
on topic
https://www.reddit.com/r/Dynmap/comments/hi2gvu/fullrender_does_not_render_all_chunks/

**Comment by lazaroblanc** [comment]
Any update on this?

**Comment by Doregon** [comment]
Have you explored/pregenerated the world? Dynmap won't render chunks that haven't been "explored"--which is that it won't render chunks that there's no data to read from. If you're looking to render the entire map, you'll need to pregenerate the chunks beforehand.

If you have, then there is something more to this. I might look at it if that's the case.

**Comment by crystall1nedev** [comment]
@seema84 Have you explored/pregenerated the world? Dynmap won't render chunks that haven't been "explored"--which is that it won't render chunks that there's no data to read from. If you're looking to render the entire map, you'll need to pregenerate the chunks beforehand.

If you have, then there is something more to this. I might look at it if that's the case.

**Comment by lazaroblanc** [comment]
> 
> 
> @seema84 Have you explored/pregenerated the world? Dynmap won't render chunks that haven't been "explored"--which is that it won't render chunks that there's no data to read from. If you're looking to render the entire map, you'll need to pregenerate the chunks beforehand.
> 
> If you have, then there is something more to this. I might look at it if that's the case.

Look at his screenshots. Surface renders chunks that aren't rendered in flat. We all have the same issue.

Btw: Update render with coordinates outside of the main end island works. Just full render only renders up to the main end island and not the rest of the end dimension

**Comment by crystall1nedev** [comment]
Ohhh okay, I see.

**Comment by seema84** [comment]
radiusrender does not work for me either

**Comment by seema84** [comment]
problem still exists

Paper version git-Paper-529
dynmap v3.1-beta7-449

**Comment by Doregon** [comment]
I'm currently busy working on asynchronous chunk loading for Paper servers, so I can't really work on this just yet. However, I haven't forgotten and will reach out again once I'm done with that project.

**Comment by FedUpWith-Tech** [comment]
In worlds.txt you can add fullrenderlocations to maps that will add locations dynmap will try to render during fullrenders. The end doesn't always get rendered by fullrender because the chunks are not contiguous

**Comment by cfazilleau** [comment]
Managed to get a workaround by going in the end in creative and flying between from the main island to the outer ones. (a way to "link" the main island to the other ones). now everything works correctly in full_render
