### ISSUE TITLE
Web files are not matched with plugin version.

### ISSUE THREAD

**Issue by yurinogueira** [webbukkit/dynmap#3201]
**Issue Description:** *Web files are not matched with plugin version: All files need to be same version (undefined) - try refreshing browser cache (shift-reload)*

* **Dynmap Version:** *Dynmap-3.1-beta5-spigot.jar*
* **Server Version:** *Paper 1.16.4*
* **Pastebin of Configuration.txt:** *https://pastebin.com/94hEd9pm*
* **Server Host (if applicable):** *My own dedicated*
* **Steps to Replicate:** *I have dynmap installed with Nginx server, i use a symbolic link from the plugin folder to /var/www/eterniaserver.com.br/dynmap (the dynmap url of my site are eterniaserver.com.br/dynmap)*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
This usually happens when the plugin is updated and goes away with time. I'm going to close this due to age but please reply if you still need help
