### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by Pingger** [webbukkit/dynmap#3202]
There is a typo in the Method name of `getPlayerVisbility` ... the second `i` missing.

https://github.com/webbukkit/dynmap/blob/e962323e001328740d322743c670b7ba33b1e4be/spigot/src/main/java/org/dynmap/bukkit/DynmapPlugin.java#L1094

And in this one, the third `i` is missing.

https://github.com/webbukkit/dynmap/blob/e962323e001328740d322743c670b7ba33b1e4be/spigot/src/main/java/org/dynmap/bukkit/DynmapPlugin.java#L1125

As far as I can tell, these typos go through the entire API...

**Comment by FedUpWith-Tech** [comment]
Because this would be a breaking change and the spelling error doesn't cause any errors and has existed this long we are going to leave it and not potentially break the 20k+ servers who use this plugin at any point in time. We have noted this down in the event we change our minds
