### ISSUE TITLE
shadow bug

### ISSUE THREAD

**Issue by seema84** [webbukkit/dynmap#3205]
after a fullrender i have some chunks with shadow bugs ->

https://imgur.com/a/nENkH2J

Version: Dynmap v3.1-beta-4

**Comment by seema84** [comment]
https://i.imgur.com/rvakXzx.png

not quite the same but similar

**Comment by seema84** [comment]
![4255t](https://user-images.githubusercontent.com/2832339/103951068-4efda500-513e-11eb-960e-896c1eb1b19b.png)

**Comment by seema84** [comment]
i can fix it with radius render but sometimes it appears the next day in the same place. there are also more with time on my world

**Comment by seema84** [comment]
![55222t](https://user-images.githubusercontent.com/2832339/103952518-d77d4500-5140-11eb-913d-f60501546709.png)

**Comment by mikeprimm** [comment]
Same as #3565 - see discussion and fix details there
