### ISSUE TITLE
[dynmap] ERROR creatomg default for plugins/dynmap/configuration.txt on Paper 1.16.4

### ISSUE THREAD

**Issue by snoglobe** [webbukkit/dynmap#3206]
> template is **bold**
> sample data is *italicized*

**Issue Description:** dynmap doesn't create configuration file when running for first time on Paper 1.16.4 with error `[dynmap] ERROR creatomg default for plugins/dynmap/configuration.txt`

* **Dynmap Version:** *3.1-SNAPSHOT*
* **Server Version:** *paper 1.16.4 build 270*
* **Pastebin of Configuration.txt:** empty because its not generated
* **Pastebin of crashlogs or other relevant logs:**`[dynmap] Using Vault provider SuperPerms for access control
[dynmap] ERROR creatomg default for plugins/dynmap/configuration.txt
 [dynmap] Unloaded 0 components.
[dynmap] Disabled`
* **Other Relevant Data/Screenshots:** older versions of dynmap (including latest stable) just plain do not show up at all in my logs
* **Steps to Replicate:** *put latest dynmap snapshot in and start server*

 [(it might be, but the other issue's solution did not work) ] *I have looked at all other issues and this is not a duplicate*  
 [] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
You are using an outdated version of dynmap please update and the issue will go away
