### ISSUE TITLE
Biom Reset?

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#3207]
This is not a bug but I can't find where I can classify this question. I would know can I undo biomes that I have changed with Worldedit? Unfortunately, you can see very clearly biomes that have been changed. Is there a way to bring them back to normal?

![biome](https://user-images.githubusercontent.com/35557302/100550234-dbcc5d80-3278-11eb-8b1c-19a758096f5d.png)

**Comment by FedUpWith-Tech** [comment]
Why is this a dynmap issue?

**Comment by Blueeyestar** [comment]
ouch my mistake ^^ I confused it
