### ISSUE TITLE
Fullrender won't pause sometimes

### ISSUE THREAD

**Issue by ProClifo** [webbukkit/dynmap#3209]
I have fullrenderplayerlimit set to 1 in the config file so the fullrender pauses when 1 or more players are online. However, the pause feature doesn't always work, and it keeps running even while players are online. This notably happens after a server restart and players rejoin very quickly, before Dynmap has started rendering again.

I've also tried pausing the rendering manually using "/dynmap pause" and "/dynmap pause world" in the console, but all I get is this:

[Wed, 2. Dec 2020 02:30:02 CET INFO] Full/Radius renders are ACTIVE
[Wed, 2. Dec 2020 02:30:02 CET INFO] Update renders are ACTIVE
[Wed, 2. Dec 2020 02:30:02 CET INFO] Zoom out processing is ACTIVE

Nothing gets paused, it just shows which renders are active??

So I either have to restart the server again, which is an annoyance to the players, or cancel the rendering completely to prevent the lag.

**Comment by isaaclepes** [comment]
If you check out the Wiki, you can see there are only 2 options:
/dynmap pause all: pause all map rendering (updates and full/radius renders)
/dynmap pause none: resume all map rendering

There is technically the 3rd command '/dynmap pause' which shows the statuses you already saw.
