### ISSUE TITLE
Railcraft lanterns

### ISSUE THREAD

**Issue by topseb** [webbukkit/dynmap#3210]
Hi,

I´d like to render Railcraft lanterns (these: http://railcraft.info/wiki/structure:lanterns ). Is it possible to render these custom models (dynmap shows them as Iron blocks)
![Bez názvu](https://user-images.githubusercontent.com/15344770/101167138-c1f49700-3639-11eb-9c48-5862f1d3e7d9.png)

**Comment by FedUpWith-Tech** [comment]
https://github.com/webbukkit/dynmap/wiki/FAQ#5-my-dynmap-doesnt-show-modded-blocks
