### ISSUE TITLE
[Docs] Broken links in Wiki

### ISSUE THREAD

**Issue by d-Rickyy-b** [webbukkit/dynmap#3211]
**Issue Description:** On the ['Setting up the Dynamic Map plugin under Linux' wiki page ](https://github.com/webbukkit/dynmap/wiki/Setting-up-the-Dynamic-Map-plugin-under-Linux) the links under 'Big Webservers' are broken.

They are linking to (e.g.) https://github.com/webbukkit/dynmap/wiki/Setting-up-Dynamic-Map-with-Apache2-under-Debian - which should be changed to (e.g.) https://github.com/webbukkit/dynmap/wiki/Dynmap-with-apache2-on-Debian

I initially came to the "Setting up the Dynamic Map plugin under Linux" page via the Home site: https://github.com/webbukkit/dynmap/wiki

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by rautamiekka** [comment]
Why put 'Apache2' to all low case ?

**Comment by d-Rickyy-b** [comment]
@rautamiekka not exactly sure what you mean. The URLs are completely different, not just the Apache2 part. It's just wrong URLs in the docs that need to be changed.

**Comment by rautamiekka** [comment]
> @rautamiekka not exactly sure what you mean. The URLs are completely different, not just the Apache2 part. It's just wrong URLs in the docs that need to be changed.

Ah. I simply assumed the new link didn't even exist, I'm damn tired.

**Comment by FedUpWith-Tech** [comment]
fixed broken links: https://github.com/webbukkit/dynmap/wiki/Setting-up-the-Dynamic-Map-plugin-under-Linux
