### ISSUE TITLE
[bug] Sign Markers do not work on Fabric

### ISSUE THREAD

**Issue by Red3Tango** [webbukkit/dynmap#3212]
**Issue Description:** Sign Markers do not work on Fabric when placed as Non-Op or as Op. Signs placed are not processed and do not show on map

* **Dynmap Version:** 3.1-beta5-fabric-1.16.2
* **Server Version:** fabric-loader-0.10.6-1.16.2 / fabric@0.27.1+1.16
* **Pastebin of Configuration.txt:** https://pastebin.com/3k47n08J
* **Server Host (if applicable):** Selfhosted
* **Pastebin of crashlogs or other relevant logs:** n/a
* **Other Relevant Data/Screenshots:** n/a
* **Steps to Replicate:**
1. Fresh install of server and only mods required (fabric api and dynmap)
2. Set config to enable sign markers
3. Join server with Op user and place a sign with required tag and text

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Added in https://github.com/webbukkit/dynmap/commit/b31d7ebe9d1b651b26cc844f307b2baa8700135e#diff-0d6acfca1f719076eaf25937ea1c1a9ea2cf1f8943ee78a856133e7dcdd42e38

**Comment by kosma** [comment]
Note, for now it only works on 1.18+. Backport is planned but no ETA atm.
