### ISSUE TITLE
latest version of dynmap is the only one compatible with spigot 1.16.4 and it isn't compiled

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#3213]
Hello, i even tried converting the .zip to .jar but its missing a plugin.yml, could you compile it or teach me how i can ?

**Comment by jbhannah** [comment]
You need to have a [JDK](https://adoptopenjdk.net) installed, then follow the [instructions](https://github.com/webbukkit/dynmap#how-to-build) in the README. I was able to build it successfully with OpenJDK 15 on macOS 11.0 and am [running it on a Fabric 1.16.4 server](https://mc.jbhannah.net) with no issues.
