### ISSUE TITLE
S3 Storage Support

### ISSUE THREAD

**Issue by tdfischer** [webbukkit/dynmap#3214]
**Feature Description:** On some large servers, its very easy to run out of disk space and sometimes even filesystem inodes. AWS S3 storage doesn't have those limitations, however it also isn't a filesystem you can just mount; you can only upload files to it through their API. Amazon provides a lovely SDK for doing this and it seems like it fully supports all the same operations as the filetree backend, including storing file metadata inside S3. Another great bonus of S3 is that objects may be read-only accessible using a regular old-fashioned URL that any browser can understand, meaning its possible to offload all of the HTTP file request handling off of dynmap. In effect, server operators can get all the benefits of a fancypants global CDN with zero of the work needed to maintain it and keep it up to date. I might be playing on a server based in Spain (with a 200ms ping :E), but at least the map tiles would be served up lightning fast from the west coast CDN edge nodes!

I myself use DigitalOcean, not AWS, however DigitalOcean's Spaces product provides a S3 compatible API, so this feature wouldn't be limited to just one platform.

I'm hoping to make time over my upcoming winter holiday and hack on this and come back with a pull request.

**Comment by jamesgeddes** [comment]
[Geek.Zone/Minecraft](http://Geek.Zone/Minecraft) just crashed twice because Dynmap filled our HDD. Geek.Zone strongly supports this request.

**Comment by AverageComet250** [comment]
I too think this would be a great idea. I currently SSH into my server whenever I want to make a config change to my server, which takes way too long for my liking. Using S3 would be great, as it means that all I have to do is download the file, change it, and then reupload it. It also means that my hard drive space can be used to save world data, rather than images of it.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
