### ISSUE TITLE
crash report fabric 1.16.4

### ISSUE THREAD

**Issue by jontribs** [webbukkit/dynmap#3215]
crashes when server is launched
mod list:
fabric api .27.1
carpet-autocrafting-1.16.4-1.4.17
fabric-carpet-1.16.4-1.4.20
malib-fabric-1.16.4-0.10.0
minihud-fabric-1.16.4-0.19.0
tweakaroo-fabric-1.16.4-0.19.0
dynmap-3.1-beta5-1.16.2
pastebin of crash
[paste](https://pastebin.com/kmbDj3Yn)
Hopefully you can fix the issue soon!

**Comment by Greg-J** [comment]
This is known. Dynmap for Fabric hasn't been updated to 1.16.4

**Comment by jontribs** [comment]
ok thanks, I just thought it was a mod thing.

**Comment by mikeprimm** [comment]
A PR was provided and integrated for 1.16.4 support, which was included with beta6.  Give that a go.
