### ISSUE TITLE
Disables on startup

### ISSUE THREAD

**Issue by Projecki** [webbukkit/dynmap#3219]
**Issue Description:** *Dynmap did not startup with seemingly no changes from when the server was last online.*

* **Dynmap Version:** *3.1-beta5*
* **Server Version:** *Purpur 1.16.4-906*
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Server Host (if applicable):** *selfhosted dedi*
* **Pastebin of crashlogs or other relevant logs:** *https://hastebin.com/itoyomateg.properties*

 [Y] *I have looked at all other issues and this is not a duplicate*  
 [Y] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
closing due to dead link
