### ISSUE TITLE
day number display support

### ISSUE THREAD

**Issue by richard-ostrochovsky** [webbukkit/dynmap#3220]
**Feature Description:** *Maybe this is possible, but I am not successful to find out how: it would be great addition, to display in dynmap not only current time in MC world, e.g. 8:30, but also number of current day (since world generation), e.g. DAY#8337.*

**Additional context:** *Could I help somehow?*

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
