### ISSUE TITLE
Dynmap not rendering loaded chunks.

### ISSUE THREAD

**Issue by EmerickGrimm** [webbukkit/dynmap#3222]
**Issue Description:** *Dynmap not rendering loaded chunks. Chunks was loaded by /wb fill. Used /dynmap fullrender and update render, still broken map.*

* **Dynmap Version:** *core=3.1-beta5-431, plugin=3.1-beta5-431*
* **Server Version:** *spigot-1.16.4*
* **Pastebin of Configuration.txt:** *https://pastebin.com/heJzdb3z*
* **Server Host (if applicable):** *https://srvgame.ru/*
* **Screenshots:** https://ibb.co/GpQx5t9
                             https://ibb.co/bLwQjH5

**Comment by EmerickGrimm** [comment]
UPD: Some chunks loaded by player are not showing too.

**Comment by FedUpWith-Tech** [comment]
this is what happens when dynmap is running at the same time as a wb /fill
another fullrender should once the chunks are generated should fix this. If not you need to run worldborder again with the force flag

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2485
