### ISSUE TITLE
Incompatible bukkit version error

### ISSUE THREAD

**Issue by Miinoo11** [webbukkit/dynmap#3225]
**Issue Description:** *The Plugin doesn't load. It comes to an Incompatible bukkit version error*

* **Dynmap Version:** *latest*
* **Server Version:** *Spigot 1_16_3_R2*
* **Pastebin of Configuration.txt:** *doesn't exist*
* **Server Host (if applicable):** *localhost*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/tvX4dDh8*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Latest is not a version

**Comment by Miinoo11** [comment]
version 3.0-SNAPSHOT-338

**Comment by FedUpWith-Tech** [comment]
You are using an outdated version of dynmap, use version 3.1-beta5 for 1.16.3 or newer

**Comment by Miinoo11** [comment]
Thank you. 
Where can I download it? On spigot I cant download it. There is no error or anything. When I click the download button it refreshes the page.

**Comment by FedUpWith-Tech** [comment]
Spigot seems to be broken, you can find it one the build server
https://dynmap.us/builds/dynmap/

**Comment by rautamiekka** [comment]
> You are using an outdated version of dynmap

This is precisely why I agree 'latest version' is a completely unacceptable version number; not cuz it's not a number (technically most version numbers aren't numbers at all, so I'm not counting it that way), but cuz the actual version of the used software could be mistakenly old for even reasons not the OP's fault.

> Spigot seems to be broken, you can find it one the build server
> https://dynmap.us/builds/dynmap/

Specifically https://dynmap.us/builds/dynmap/Dynmap-HEAD-spigot.jar, which judging by the timestamps is a symlink to the newest, so simply downloading that every so often should make the plugin newest for the Server Admin for the least effort.

**Comment by Miinoo11** [comment]
https://pastebin.com/ScABwxwW

Im trying Dynmap-3.1-beta-3-spigot.jar and now this error happend

**Comment by FedUpWith-Tech** [comment]
> Specifically https://dynmap.us/builds/dynmap/Dynmap-HEAD-spigot.jar, which judging by the timestamps is a symlink to the newest, so simply downloading that every so often should make the plugin newest for the Server Admin for the least effort.

Actually that link is not the final build. The compiling process is a bit convoluted but helps with the 30 different versions dynmap supports.

The direct link to the most up to date version for spigot at this moment is 
https://dynmap.us/builds/dynmap/Dynmap-3.1-beta5-spigot.jar

**Comment by FedUpWith-Tech** [comment]
> You are using an outdated version of dynmap, use version 3.1-beta5 for 1.16.3 or newer

**Comment by rautamiekka** [comment]
> > Specifically https://dynmap.us/builds/dynmap/Dynmap-HEAD-spigot.jar, which judging by the timestamps is a symlink to the newest, so simply downloading that every so often should make the plugin newest for the Server Admin for the least effort.
> 
> Actually that link is not the final build. The compiling process is a bit convoluted but helps with the 30 different versions dynmap supports.

What're the 'HEAD' files for then ? Last I checked the timestamps are 100% match (mostly anyways), so that's why I figured they're the same as whatever the newest for that type is.

**Comment by Miinoo11** [comment]
does the dynmap api support every dynmap versions?
Like 1.8 - 1.16?
