### ISSUE TITLE
Dynmap v3.1-beta5 not working on 1.16.4

### ISSUE THREAD

**Issue by TMCThomas** [webbukkit/dynmap#3228]
**Issue Description:** *Dynmap not starting up, throws error in the console, I think it has to do with java 11.*

* **Dynmap Version:** *Dynmap v3.1-beta5*
* **Server Version:** *paper 1.16.4 #348*
* **Pastebin of Configuration.txt:** *Default configuration nothing changed yet.*
* **Server Host (if applicable):** *Feroxhosting.*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/EA5aptbL*
* **Steps to Replicate:** *Just launch dynmap on one of the latest paper build with java 11.*

**Comment by mikeprimm** [comment]
Existing fixed bug, when PATH environment variable is not defined.  Either set the PATH environment variable to something valid, or give the latest dev build a try (http://dynmap.us/builds/dynmap/Dynmap-3.1-SNAPSHOT-spigot.jar)
