### ISSUE TITLE
API created Marker Does Not Save.

### ISSUE THREAD

**Issue by weihao** [webbukkit/dynmap#3229]
**Issue Description:** *Marker created using command in-game saved to `plugins\dynmap\markers.yml`, but Marker created using api (with persistent param set to true )does not save and will be lost if the server restart*
API code:
```
markerset.createMarker(null, "Chest", "world", chest.getX(), chest.getY(), chest.getZ(), dapi.getMarkerAPI().getMarkerIcon("chest"), true );
```

* **Dynmap Version:** *v3.1-beta5*
* **Server Version:** *spigot 1.16.4*
* **Pastebin of Configuration.txt:** *default*
* **Server Host (if applicable):** *local*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
Confirm that the marker set was created as persistent: if the marker set isn't persistent, the markers in that set cannot be.

**Comment by weihao** [comment]
```
[dynmap] Marker API has been requested, but is not enabled.  Uncomment or add 'markers' component to configuration.txt.
```
What does this error mean? @mikeprimm
