### ISSUE TITLE
BYG + Dynmap - placing plant in pot crashes server 

### ISSUE THREAD

**Issue by Xyclade** [webbukkit/dynmap#3231]
**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** *Dynmap-3.1-beta5-forge-1.16.3.*
* **Server Version:** *forge-1.16.4-35.1.13*
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *https://paste.ee/p/d5hTo*
* **Other Relevant Data/Screenshots:** *Reproducable with only Forge + Dynmap + [byg-1.1.5](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)*
* **Steps to Replicate:** *Create a clean server with Dynmap + forge + BYG,  place a flower pot and then try to plant a BYG plant, for example a bistort. Server will crash. Note that in single player without Dynmap the texture of the bistort is not working properly. I have filed  https://github.com/CorgiTaco/BYG/issues/220 for this in the BYG repo*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
Yep - we're seeing an invalid block state when we handle the update event for that block.  This is a 'this should never happen' thing, so I suspect BYG is doing something funky with the block state data.  That said, I've added a defensive check for this error that should avoid the problem - should be in beta6
