### ISSUE TITLE
End Chunks not rendering on Paper 1.16.4

### ISSUE THREAD

**Issue by maxeitelwein** [webbukkit/dynmap#3235]
I am running a Paper1.16.4 server with the dynmap version 3.1-beta6. It runs great but it for the overworld and the nether but it only renders the very inner chunks of the end and not the outer ones. Is that just a configuration error I did or does the plugin not find my rendered chunk data?

**Comment by Anthropomorphed** [comment]
#3197 
Had the same issue and saw this first but looked up more

**Comment by maxeitelwein** [comment]
This issue is already being discussed in the issue report mentioned by Anthropomorphed. I am closing mine. [#3197](https://github.com/webbukkit/dynmap/issues/3197)
