### ISSUE TITLE
[Bug] Map Shifts and Throws Off Markers

### ISSUE THREAD

**Issue by Ebeta2** [webbukkit/dynmap#3237]
> template is **bold**
> sample data is *italicized*

**Issue Description:** Upon server restart, the map shifts, making all markers on the map in the wrong locations. Re-rendering the map fixes this, but takes a long process, especially on hires settings.

* **Dynmap Version:** Dynmap-3.1-beta6-spigot
* **Server Version:** *fspigot 1.16.4
* **Pastebin of Configuration.txt:** https://pastebin.com/VRubs3aD
* **Server Host (if applicable):** Shockbyte
* **Pastebin of crashlogs or other relevant logs:** n/a
* **Other Relevant Data/Screenshots:** n/a
* **Steps to Replicate:**
* 1. Apply markers as you see fit.
* 2. Restart the server.

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Shockbyte limits the resolution to lowres, the map isn't shifting on restarts, the config is changing which is making the map appear to shift
