### ISSUE TITLE
Not callable map

### ISSUE THREAD

**Issue by Lorias-Jak** [webbukkit/dynmap#3238]
Today I updated the plugin from version v3.1-beta5 to version v3.1-beta-6. There was the problem that users could no longer call up the map in the browser and only the message with the cache was displayed that they should try to reload the page with shift and the reload button. This did not work either. We currently have the paper version "paper-1.16.4-298". It was also not possible for those affected to open it from other browsers.

**Comment by FedUpWith-Tech** [comment]
closing due to age, please reply if this is still relevant
