### ISSUE TITLE
Crash Happening on Server After updating a few other mods

### ISSUE THREAD

**Issue by zachsai** [webbukkit/dynmap#3242]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** *dynmap-version*  1.16.4 beta 6
* **Server Version:** *forge 1.16 build x, or paper 1.15.2 build x*
* **Pastebin of Configuration.txt:** 
* **Server Host (if applicable):** Bisect
* **Pastebin of crashlogs or other relevant logs:  https://pastebin.com/kGfcFqZH
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
you downloaded the 1.16.3 version of dynmap for this 1.16.4 version of forge.
