### ISSUE TITLE
Add the ability to view light levels in caves.

### ISSUE THREAD

**Issue by xSerpentineX** [webbukkit/dynmap#3244]
There should be the ability to toggle on and off a feature to see the light level in caves. This can be represented with a yellow gradient; the most yellow areas would be light level 14 where as the least yellow areas would be light level 0. This would make it easier for us to see which caves we have fully lit up.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
