### ISSUE TITLE
Bug report after updating 

### ISSUE THREAD

**Issue by siriuscraft-MCAdmin** [webbukkit/dynmap#3245]
**Dynmap Version:** Dynmap-3.1-beta6-spigot.jar
**Server Version:** paper 1.16.5 build 386 and 418.
**Pastebin of Configuration.txt:** *https://pastebin.com/Mm49GtFS*
**Server Host (if applicable):** Self-hosted and managed with Amp
**Pastebin of crashlogs or other relevant logs:** 
w/all plugins installed on server: *https://pastebin.com/Z95LFBDK*  
w/only Dynmap installed on server *https://pastebin.com/fyAw123J*
**Other Relevant Data/Screenshots:** I'm using :
Plugins (32): AdvancedPortals, AdvancedReporter, Autorank, BedrockPlayerManager, BungeeChatBridge*, ChatManager, Citizens, CommandSync*, dynmap*, Essentials, EssentialsMysqlStorage, EssentialsSpawn, ExtraContexts, floodgate-bukkit, HolographicDisplays, LuckPerms, MoreCommands*, Multiverse-Core, Multiverse-Portals, Multiverse-SignPortals, MysqlPlayerDataBridge, NamelessMC, PlaceholderAPI, Plot2Dynmap, PlotSquared, Realistic_World, Vault, ViaBackwards, ViaVersion, WorldBorder, WorldEdit, WorldGuard

**Steps to Replicate:** Occurs on server start. Occurs when running with only Dynmap enabled on server. 

 [ X] *I have looked at all other issues and this is not a duplicate*  
 [ X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Closing this due to age, this was fixed in a later version.
