### ISSUE TITLE
Block state issue: chains are always rendered as vertical

### ISSUE THREAD

**Issue by Xenapte** [webbukkit/dynmap#3247]
**Issue Description:** *Chains are always rendered as vertical regardless of their block state (`axis`: x/y/z)*

* **Dynmap Version:** *v3.1-beta-6*
* **Server Version:** *Paper 1.16.5 build 418*
* **Configuration.txt:** *(just default configuration)*
* **Other Relevant Data/Screenshots:** 
** In dynmap: 
![20210117120300](https://user-images.githubusercontent.com/17661805/104830924-8c8ccb80-58be-11eb-9189-828a757a9877.png)
** In actual game: 
![20210117120736](https://user-images.githubusercontent.com/17661805/104830929-9ca4ab00-58be-11eb-9127-37ad3ddaf7a2.png)

**Notice the horizontal chains in-game being rendered as vertical.** Probably because horizontal chains were only implemented to the game in 1.16.2 (when first added in the game chains can only be vertical).

 [√] *I have looked at all other issues and this is not a duplicate*  
 [√] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
@mikeprimm  yet another bump on a minor block render issue. Still present in beta3
![image](https://user-images.githubusercontent.com/7731191/147003581-6fa885e9-ee7d-4821-afa0-8f604b5a7ce9.png)
![image](https://user-images.githubusercontent.com/7731191/147003610-296ad2bc-a070-4d67-ba4d-171fb5bda0ce.png)

**Comment by mikeprimm** [comment]
Fixed in SNAPSHOT-696+

**Comment by generrosity** [comment]
looking good in build706
![image](https://user-images.githubusercontent.com/12838061/152871997-b0a150f9-13e9-4013-baa8-ba8f7dae02ad.png)
