### ISSUE TITLE
Worldedit changes not reflecting on map

### ISSUE THREAD

**Issue by StoneIron02** [webbukkit/dynmap#3249]
Please understand that I use a translator.

I used worldedit to change the swamp biome into a forest, 
but dynmap has not been able to update it.

Is there a proper solution?

**Comment by Elgorond** [comment]
Ditto

**Comment by mikeprimm** [comment]
Worldedit changes do not fire observable events to drive updates - you need to run the dynmap update manually (dynmap update, radiusrender or fullrender).  Nothing we can do to detect what WE is doing without it firing the standard events from Spigot/Paper
