### ISSUE TITLE
Performances and mariadb

### ISSUE THREAD

**Issue by TheCalypso** [webbukkit/dynmap#3250]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

Hello,

I have several things to share with you. At first, I found that there was a big performance problem with the new version of the plugin. In previous versions the generation of my dynmap did not take so long (2 days compared to 5-6 now). I initially believed that it came from my data ase (mysql) so I wanted to test on a mariadb database but I notice that it does not work with your plugin. I have however looked at the source codes to see how you proceed but I still have an error which you will be able to see in the attached files.

I asked some friends with dedicated machines to test to generate the dynmap and send it to their mysql, but even I worry that it will take too long!

I currently have this OVH server ( but the problem does not come from here, don't worry: p )

* **Dynmap Version:** *dynmap-version* Dynmap v3.1-beta-6
* **Server Version:** *forge 1.16 build x, or paper 1.15.2 build x* paper 1.16.4 388
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2* https://pastebin.com/qjb5vFjS
* **Server Host (if applicable):** OVH https://www.ovhcloud.com/fr/bare-metal/rise/rise-3/
You need this only :p

Have a good day !

- Caly -

[23:49:19] [Server thread/INFO]: [dynmap] Enabling dynmap v3.1-beta6-438*
[23:49:19] [Server thread/INFO]: [dynmap] Using LuckPerms 5.1.93 for access control
[23:49:19] [Server thread/INFO]: [dynmap] Opening MariaDB database 192.168.1.21:3306/gaspezia_dynmap as map store
[23:49:19] [Server thread/ERROR]: [dynmap] MariaDB-JDBC classes not found - MariaDB data source not usable
[23:49:19] [Server thread/ERROR]: [dynmap] Map storage initialization failure
[23:49:19] [Server thread/INFO]: [dynmap] Unloaded 0 components.
[23:49:19] [Server thread/INFO]: [dynmap] Disabled* **Pastebin of crashlogs or other relevant logs:** 
*https://pastebin.com/crashcausedbydynmap*

* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by AverageComet250** [comment]
Maybe try using an sqlite db or plain files.

**Comment by rautamiekka** [comment]
SQLite for pic storage will be a very bad idea cuz performance'll die pretty quickly, especially when the db gets fragmented. Access might be faster than individual files for some time, but only for.

**Comment by AverageComet250** [comment]
I see what you mean. It also moves data onto the same device as the server, instead of keeping it separate.

**Comment by rautamiekka** [comment]
Yep, that too.

**Comment by DarkRider1768** [comment]
You are missing the jar file that contains the code that allows dynmap to communicate with the database server. You need to download mysql-connector-java-**some version number**.jar and place it in your mods folder. Then restart the server and it should start to work. You can find the download by google searching java mysql connector.
