### ISSUE TITLE
Mushroom Stems on the Dynmap

### ISSUE THREAD

**Issue by w1tcherrr** [webbukkit/dynmap#3253]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Only a minor thing I noticed regarding mushroom stems. I use mushroom stems in my builds and the standard texture has white colour on all sides. The problem ist, that even when the top is white in the game (no mushroom stem above it placed) on the dynmap it is shown as the beige/brownish color (from the inside of the mushroom).*

* **Dynmap Version:** *v 3.0.1*
* **Server Version:** *paper 1.16.4*
* **Other Relevant Data/Screenshots:**: Texture how it looks: 
![image](https://user-images.githubusercontent.com/70418164/105484311-6ba3ec00-5cab-11eb-82a5-333411624d01.png)
Texture how it is supposed to look: 
![image](https://user-images.githubusercontent.com/70418164/105484572-d2c1a080-5cab-11eb-8cbb-f6424603e106.png)

* **Steps to Replicate:** *Placing a mushroom stem and looking at it on the dynmap*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
@mikeprimm last one (hopefully) 
![image](https://user-images.githubusercontent.com/7731191/147005656-b656ed46-27d5-4b79-8ffa-e3f03a1018d3.png)
![image](https://user-images.githubusercontent.com/7731191/147005671-97a3d7da-cf1a-4e03-8417-c816d153f3d9.png)
![image](https://user-images.githubusercontent.com/7731191/147005690-7494e1eb-20f4-479c-a475-73f467d72d6b.png)

**Comment by FedUpWith-Tech** [comment]
Fixed on build 626 or later:
![image](https://user-images.githubusercontent.com/7731191/147772423-1a08dd0c-a285-4b0c-b84d-b7ac1522f48d.png)
![image](https://user-images.githubusercontent.com/7731191/147772438-b690734d-1558-4a34-acbb-32d0a09d08b8.png)
