### ISSUE TITLE
Disabling Dynmap at server start

### ISSUE THREAD

**Issue by Aknotl** [webbukkit/dynmap#3254]
**Issue Description:** *Dynmap is disabling when server starts. Don't know if other data is important to know. More info in pastebin*

* **Dynmap Version:** *v3.1-SNAPSHOT-444*
* **Server Version:** *paper 1.16.4 build 345*
* **Pastebin of Configuration.txt:** *https://pastebin.com/LXJn5exv* (I've hidden mysql connection data)
* **Server Host (if applicable):** *None*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/pFtqK5iQ*
* **Other Relevant Data/Screenshots:** *Using Multicraft, but doesn't seem to be related to the PATH issue (problem is still there after patch). Using java 8*
* **Steps to Replicate:** *Occurs at starting*

 [Y] *I have looked at all other issues and this is not a duplicate*  
 [N] *I have been able to replicate this*

Thanks a lot for supporting this plugin, I tried everything I could, I hope my issue is not a lot !

**Comment by AverageComet250** [comment]
Try using the latest stable instead of a snapshot. I know that the download on the spigot page is not a snapshot.
