### ISSUE TITLE
Dynmap webmap time wrong

### ISSUE THREAD

**Issue by BonaireDreams** [webbukkit/dynmap#3255]
**Issue Description:** The Time of Day displayed on dynmap's webmap is out of sync with the actual day/night cycle of the server.  Currently server time is 23927 and the sun is just coming up, Dynmap displays 2:03 with the moon just past the midpoint.
I don't see any place in the configuration to adjust the day time.

* **Dynmap Version:** *3.1-beta6-forge-1.16.3*
* **Server Version:** *forge 1.16.4*

 [X ] *I have looked at all other issues and this is not a duplicate*  
 [X ] *I have been able to replicate this*

**Comment by MisterGumpo** [comment]
Confirmed - I have been able to replicated this.

**Comment by hitech95** [comment]
Looks the same on Fabric

**Comment by JurgenKuyper** [comment]
update, on forge it seems to be fixed, but the fabric timeanddateclock still moves on regardless of time.

**Comment by mikeprimm** [comment]
Right - checked on 1.18 Forge, and it looks right there - I'll check 1.16.5 to be sure

**Comment by mikeprimm** [comment]
OK - it's in Forge 1.13-1.16, but not 1.17+.   Found what is up, and it's also true with all Fabric ports (not too surprising since first one of those was based on 1.14.4, and the bug was just carried forward).  Fix should be in SNAPSHOTs in a little while (build 626 or later)
