### ISSUE TITLE
Change php version recommended in the nginx setup from 5 to 7 or 8.

### ISSUE THREAD

**Issue by Hexalyse** [webbukkit/dynmap#3259]
I've noticed the page at https://github.com/webbukkit/dynmap/wiki/Dynmap-with-Nginx still uses php5-fpm.

PHP 5 has reached its end of life for **more than 2 years** now, and has even been officially removed from the PHP Manual. Which means it will not receive any security update in case a vulnerability is found. Recommending PHP5 in 2021 is really not ideal.

The solution would be to remove the php5 reference entirely by replacing every occurrence of `php5-fpm` with `php-fpm` making it version-agnostic, or with `php7.4-fpm` since it's the latest stable php7 based version of php-fpm.

**Comment by FedUpWith-Tech** [comment]
Done
