### ISSUE TITLE
Integrate a seed-based tool like Amidst/MineAtlas into Dynmap

### ISSUE THREAD

**Issue by ProClifo** [webbukkit/dynmap#3262]
Most of a Minecraft world is unexplored, and it takes a massive amount of storage space to load all the chunks. How about a setting where Dynmap uses an seed-based map like MineAtlas or Amidst to fill in the blanks where there's no world data? This would be useful for servers that don't want to pre-generate all of the chunks within a radius. It would also allow players to scout the map, looking for interesting destinations infinitely far out.

Pictured is a half-arsed example I made in MS Paint. I'd imagine the final result would look prettier than this.

![image](https://user-images.githubusercontent.com/8874666/103579024-ddbcb880-4ed7-11eb-80bb-9fb423db568b.png)

**Comment by jacklollz2** [comment]
I would absolutely love for this to be a thing, there are some maps that already do this and I would love for Dynmap to do it as well.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
