### ISSUE TITLE
(Hires) Minecraft Lanterns only display on Dynmap if they are hanging; Lanterns placed on top of blocks do not display

### ISSUE THREAD

**Issue by kurazarrh** [webbukkit/dynmap#3264]
* **Dynmap Version:** 3.1-beta6-spigot
* **Server Version:** Spigot 1.16.5
* **Pastebin of Configuration.txt:** https://pastebin.com/EwaPaueE
* **Server Host (if applicable):** Self-hosted on Win2008R2
* **Pastebin of crashlogs or other relevant logs:** N/A
* **Other Relevant Data/Screenshots:** Not using any texture packs; the server is 99.9% vanilla. I've attached a screenshot with red arrows pointing to where there are lanterns placed on top of some logs. There are other, hanging lanterns visible in the shot.
![Dynmap-3 1-beta6-spigot_Lantern_Issue](https://user-images.githubusercontent.com/29897889/106700087-1d97be00-65b2-11eb-948f-c726f8d4aa54.png)

Using the hires setting for Dynmap, load up a world. Place a lantern on top of a block, and place a lantern on the underside of a block (such as a chain or fence post so that it is visible at the angle of the dynmap render). View the dynmap. The hanging lantern is visible, but the one placed on a block is not.

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by mabinkitsune** [comment]
A similar problem
![123232](https://user-images.githubusercontent.com/78536362/106889877-6e222f00-670a-11eb-91a0-0b3fbdeed126.PNG)

**Comment by kurazarrh** [comment]
Adding comment to note that this also applies to beds not rendering. See attached screensho
![Dynmap bed render issue](https://user-images.githubusercontent.com/29897889/138486830-586ea9d1-4a13-4758-bf50-3372a242e6e5.png)
t.

**Comment by FedUpWith-Tech** [comment]
@mikeprimm bump, still present in beta3
![image](https://user-images.githubusercontent.com/7731191/147005383-e67c4652-5ecb-464d-aedd-40374472180e.png)
![image](https://user-images.githubusercontent.com/7731191/147005415-849af85f-3b8f-4947-865d-251b79412a9a.png)
![image](https://user-images.githubusercontent.com/7731191/147005432-04e29307-eeed-422b-bfed-ae498230da5a.png)

**Comment by mikeprimm** [comment]
Fix will be in next SNAPSHOT (603 or later)

**Comment by FedUpWith-Tech** [comment]
Sorry to re-open this mike but when testing another issue I noticed the texture for the lanterns is wrong (although does show up on the ground now. 

The top texture just appears to be the side texture mapped to the top:
![image](https://user-images.githubusercontent.com/7731191/147775252-193e867b-4a22-4152-9b39-f599774259c7.png)

Additionally the 3D view seems to cut the lantern in half and not show the top at all:
![image](https://user-images.githubusercontent.com/7731191/147775338-24504f13-2374-483b-9de3-8a7f237b29dc.png)

**Comment by mikeprimm** [comment]
If you look at the resource pack for vanilla, you'll see that there is no top texture... all faces are same texture:

From model:
```json 
{
    "parent": "block/block",
    "textures": {
        "particle": "#lantern"
    },
    "elements": [
        {   "from": [ 5, 0, 5 ],
            "to": [ 11, 7, 11 ],
            "faces": {
                "down":  { "uv": [  0, 9,  6, 15 ], "texture": "#lantern", "cullface": "down" },
                "up":    { "uv": [  0, 9,  6, 15 ], "texture": "#lantern" },
                "north": { "uv": [ 0, 2, 6,  9 ], "texture": "#lantern" },
                "south": { "uv": [ 0, 2, 6,  9 ], "texture": "#lantern" },
                "west":  { "uv": [ 0, 2, 6,  9 ], "texture": "#lantern" },
                "east":  { "uv": [ 0, 2, 6,  9 ], "texture": "#lantern" }
            }
        },
        {   "from": [ 6, 7, 6 ],
            "to": [ 10, 9, 10 ],
            "faces": {
                "up":    { "uv": [  1, 10,  5, 14 ], "texture": "#lantern" },
                "north": { "uv": [ 1, 0, 5,  2 ], "texture": "#lantern" },
                "south": { "uv": [ 1, 0, 5,  2 ], "texture": "#lantern" },
                "west":  { "uv": [ 1, 0, 5,  2 ], "texture": "#lantern" },
                "east":  { "uv": [ 1, 0, 5,  2 ], "texture": "#lantern" }
            }
        },
        {
            "from": [ 6.5, 9, 8 ],
            "to": [ 9.5, 11, 8 ],
            "rotation": { "origin": [ 8, 8, 8 ], "axis": "y", "angle": 45},
            "shade": false,
            "faces": {
                "north": { "uv": [ 11, 1, 14, 3 ], "texture": "#lantern" },
                "south": { "uv": [ 11, 1, 14, 3 ], "texture": "#lantern" }
            }
        },
        {
            "from": [ 8, 9, 6.5 ],
            "to": [ 8, 11, 9.5 ],
            "rotation": { "origin": [ 8, 8, 8 ], "axis": "y", "angle": 45},
            "shade": false,
            "faces": {
                "west": { "uv": [ 11, 10, 14, 12 ], "texture": "#lantern" },
                "east": { "uv": [ 11, 10, 14, 12 ], "texture": "#lantern" }
            }
        }
    ]
}
```

**Comment by FedUpWith-Tech** [comment]
That's odd. 

In-game there is definitely a different texture for the top:
![image](https://user-images.githubusercontent.com/7731191/147779300-94c0af76-3eeb-45f7-8e6b-846658cd5848.png)
Aside from the "bump" part of the lantern there is a gray border around the whole top.
On dynmap the texture is just one of the sides.

**Comment by FedUpWith-Tech** [comment]
If you go into spectator mode to travel inside the bump to see the texture it is a solid gray top:
![2021-12-30_13 43 16](https://user-images.githubusercontent.com/7731191/147779685-2e77232d-a989-44ef-9e3e-8298e5578ca8.png)

**Comment by generrosity** [comment]
Beta-657 - textures looking good. Chain on 'sitting' looks to be off axis, but also not pixel-aligned to grass in 3d (is it hovering?). 'Hanging' same heights as sitting lantern and only one (correct) chain. 

![image](https://user-images.githubusercontent.com/12838061/150704381-97bcade2-b916-4080-99f9-0c3eaf2f72dc.png)
![image](https://user-images.githubusercontent.com/12838061/150704391-03e74e9f-5de8-4c1c-bedb-21664ea2be1b.png)
![image](https://user-images.githubusercontent.com/12838061/150704430-d1c1e45d-f823-4fa5-8443-2962998afa65.png)

**Comment by generrosity** [comment]
Closing as no further comments and its looking pretty damn good even in hirez 👍🏽👍🏽
