### ISSUE TITLE
Dynmap White Screen when connecting to public ip:25575

### ISSUE THREAD

**Issue by AvacadoWizard120** [webbukkit/dynmap#3265]
My server is running papermc version 1.16.5 and I have the beta .jar for dynmap. Everything was working fine for the first day until I installed Regions and factions addons for dynmap. I can still connect using my internal ip and port 25575 but when I try my public up I get stuck loading until it says refused to connect.

**Comment by AvacadoWizard120** [comment]
Edit: I think it may have something to do with PlayerWarps I installed.

**Comment by AverageComet250** [comment]
Did you open the port on you router, the computer, etcetera.

**Comment by AvacadoWizard120** [comment]
yes. I fixed the problem. It was just that my website integration had the port wrong so dynmap was like wtf
