### ISSUE TITLE
[Request] Dynmap only chunk update

### ISSUE THREAD

**Issue by Misio12320** [webbukkit/dynmap#3266]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Dynmap sample feature request description. This description would include as much and as little detail necessary for us to understand the feature in its entirety.* Hello. Add a command "dynmap updatechunk (location)". It should only update title at specific location which is saved in chunks.

* **Additional context:** *Please add any additional information you feel will help us understand the feature* None, I said everything above.

**Comment by Tachi107** [comment]
Is this really needed? Dynmap already updates modified chunks automatically
