### ISSUE TITLE
"hide-if-invisibility-potion" mispelt

### ISSUE THREAD

**Issue by miiichael** [webbukkit/dynmap#3267]
**Issue Description:** A minor bug. I don't know if it's just the configuration.txt spat out by the mod, or if it extends into the code, but I noticed "hide-if-invisiblity-potion" while editing the config for the first time...

* **Dynmap Version:** 3.1-beta6-forge-1.16.3
* **Server Version:** forge-1.16.5-36.0.13
* **Pastebin of Configuration.txt:** [untouched, but here it is anyway](https://gist.github.com/miiichael/f7e027d1afa090c65cad80662caecd1a)
* **Server Host (if applicable):** self-hosted
* **Pastebin of crashlogs or other relevant logs:** N/A
* **Other Relevant Data/Screenshots:**
* **Steps to Replicate:** Right out of the box.

 [:heavy_check_mark:] *I have looked at all other issues and this is not a duplicate (as far as I can tell, mentions of* hide-if-invisiblity-potion *are due to quoted conffiles)*  
 [:heavy_check_mark:] *I have been able to replicate this*

**Comment by Xalaxis** [comment]
I can confirm this is present in my copy of the configuration too.

The incorrect spelling appears to extend to the code: https://github.com/webbukkit/dynmap/blob/f1c0cfa5ac9c245081e1b6acf408ebb7205718d0/DynmapCore/src/main/java/org/dynmap/ClientUpdateComponent.java#L27

**Comment by isaaclepes** [comment]
"Misspelt"..  couldn't resist

**Comment by FedUpWith-Tech** [comment]
Because this would be a breaking change and the spelling error doesn't cause any errors and has existed this long we are going to leave it and not potentially break the 20k+ servers who use this plugin at any point in time. We have noted this down in the event we change our minds

**Comment by miiichael** [comment]
A backwards-compatible solution would be to have the option available under both names, and use the misspelled version's value if the correctly spelled version is unset.

eg.

```java
hideifinvisiblepotion = configuration.getBoolean(
   "hide-if-invisibility-potion",
   configuration.getBoolean("hide-if-invisiblity-potion", true)
);
```
