### ISSUE TITLE
1.16.5 support

### ISSUE THREAD

**Issue by Tachi107** [webbukkit/dynmap#3269]
1.16.5 contains [important stability and security fixes for Minecraft servers](https://www.minecraft.net/en-us/article/minecraft-java-edition-1-16-5). 
Is dynmap compatible with this version? If not, what should be done to make the plugin compatible with it?

**Comment by crystall1nedev** [comment]
I'll be checking right now, let me grab it (3.1-beta-6) and start my server. I know that the version on the Releases page (3.1-beta-2) does not work.

**Comment by crystall1nedev** [comment]
Aaaaand 3.1-beta-6 works on Paper 1.16.5 (463) no extra steps required.

**Comment by Tachi107** [comment]
Nice, guess this can be closed. Still, it would be nice to see it mentioned in the docs.

**Comment by crystall1nedev** [comment]
I'll send a pull request with the additions to the docs @Tachi107
