### ISSUE TITLE
Lands plugin support

### ISSUE THREAD

**Issue by SaltyDonuto** [webbukkit/dynmap#3271]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Dynmap sample feature request description. This description would include as much and as little detail necessary for us to understand the feature in its entirety.*

Please add Lands support! 
https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-nations-wars-1-16-support.53313/

* **Additional context:** *Please add any additional information you feel will help us understand the feature*

**Comment by srnyx** [comment]
> > template is **bold**
> > sample data is _italicized_
> 
> **Feature Description:** _Dynmap sample feature request description. This description would include as much and as little detail necessary for us to understand the feature in its entirety._
> 
> Please add Lands support!
> https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-nations-wars-1-16-support.53313/
> 
> * **Additional context:** _Please add any additional information you feel will help us understand the feature_

Lands already has their own Dynmap integration (enabled by default) and displays claimed land
