### ISSUE TITLE
Hide payer names outside of visibility range

### ISSUE THREAD

**Issue by BRA1L0R** [webbukkit/dynmap#3272]
**Feature Description:** Hide player names and icons when they are outside of the map visibility range.

**Comment by Blitheness** [comment]
What do you mean by “map visibility range”?

Do you mean player names/icons should only be visible within a certain region, and that same logic applies to anybody who views the map?

**Comment by BRA1L0R** [comment]
With visibility range I mean the limit you set with `/dmap worldaddlimit`. Would be really nice if you could prevent plugins from adding marks and colored regions too.
