### ISSUE TITLE
dynmap not disabled cave and surface 

### ISSUE THREAD

**Issue by AaronFrost99** [webbukkit/dynmap#3274]
> template is **normal-hires**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** *v3.1-бета-6*
* **Server Version:** *git-Yatopia-13 (MC: 1.16.5)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/PvjT7DQM*
* **Server Host (if applicable):** *other country*
* **Pastebin of crashlogs or other relevant logs:** *none*
* **Other Relevant Data/Screenshots:** *https://imgur.com/y9sNKZk*
* **Steps to Replicate:** *The normal-hires and custom-normal-hires template configuration file with the surface and cave maps removed doesn't help, the map shows all the unnecessary layers. I also ask you to tell me what command you can use to stop rendering the world world and then start rendering only the world:flat, because the cancel rendering command also has no effect.*

 [x ] *I have looked at all other issues and this is not a duplicate*  
 [x ] *I have been able to replicate this*

**Comment by crystall1nedev** [comment]
To get rid of a map type, use `/dmap mapdelete world_name:map_type`. I ran into this when I was rendering my world but wanted only the surface map, and it's pretty straightforward. Just run these commands in order:

```
/dynmap pause all                       # Required, prevents Dynmap from rendering
/dmap mapdelete world:cave              # Deletes the cave map, substitute world for your world name.
/dmap mapdelete world:surface           # Deletes the surface map, substitute world for your world name.
/dynmap pause none                      # Allows rendering again
```

After the last delete command, you'll see a message like this, indicating that it was successful:

```
[12:39:21 INFO]: Refreshing configuration for world world
[12:39:21 INFO]: [dynmap] Loaded 1 maps of world 'world'.
[12:39:21 INFO]: If you are done editing map data, run '/dynmap pause none' to resume rendering
```

You can double-check by going into your web browser and getting on the web server, hovering over the arrow on the right and checking what maps show under the world name. Once you see that there is only one (marked `flat`), you can run the render with `/dynmap fullrender`, `/dynmap radiusrender`, or `/dynmap render`.

**Comment by AaronFrost99** [comment]
Sir, thank you very much, yes, this is very useful! But after the removal, Dynmap will continue to render surface and cave again? And as a result, the files of these maps will be filled again? Or will it not render the deleted maps in this case?

**Comment by crystall1nedev** [comment]
It will not render any of the deleted maps and will only render `flat.`

**Comment by AaronFrost99** [comment]
Sir thank you very mach! It really help me
