### ISSUE TITLE
Dynmap MySQL Connection Issues - Dedicated Server and Pterodactyl Panel MySQL.

### ISSUE THREAD

**Issue by KrazyKatt1-Github** [webbukkit/dynmap#3275]
Hey there! When I try and connect Dynmap with the MySQL Database on my Dedicated Server which is controlled through Pterodactyl Panel I receive these errors: 

[16:17:09 INFO]: [dynmap] Opening MySQL database 127.0.0.1:3306/s5_dynmap as map store
[16:17:10 ERROR]: [dynmap] Error creating tables - Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[16:17:10 ERROR]: [dynmap] Map storage initialization failure
[16:17:10 INFO]: [dynmap] Unloaded 0 components.
[16:17:10 INFO]: [dynmap] Disabled

Going through my Dynmap's MySQL Configuration I could not find the error, here is the configuration here though (With the login information blurred out):

  type: mysql
  hostname: 127.0.0.1
  port: 3306
  database: s5_dynmap
  userid: blank
  password: blank
  prefix: "dyn"
  flags: "?allowReconnect=true"
  
  Here is a screenshot of the MySQL information through the Pterodactyl Panel and a link to a guide which I followed for setup:
  
 
![image](https://user-images.githubusercontent.com/78825182/107561344-2596d400-6c2a-11eb-9afd-f795b4003639.png)

https://clients.mcprohosting.com/knowledgebase/433/How-to-Setup-Dynmap-with-MySQL-on-OneControlCenter.html

Please help me fix this issue, it'd be really helpful as I've found nothing to help me online.

**Comment by iSn0wNet** [comment]
port is wrong

**Comment by iSn0wNet** [comment]
and please remove that picture and use another one where you also censored the JDBC string

**Comment by KrazyKatt1-Github** [comment]
@iSn0wNet, thank you for that and I'll fix the picture. The issue though is that in the Tutorial it stated that the port for Dynmap is always 3306 so that's what I used, I've tried to use the other ports before but had similar errors.

**Comment by KrazyKatt1-Github** [comment]
@iSn0wNet 
[14:31:33 INFO]: [dynmap] Opening MySQL database 127.0.0.1:7789/s5_dynmap as map store
[14:31:33 ERROR]: [dynmap] Error creating tables - Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[14:31:33 ERROR]: [dynmap] Map storage initialization failure
[14:31:33 INFO]: [dynmap] Unloaded 0 components.
[14:31:33 INFO]: [dynmap] Disabled

**Comment by RedTTG** [comment]
How'd you fix it?

**Comment by JurgenKuyper** [comment]
> How'd you fix it?

Please don't necropost, if you have an issue please create a new thread
