### ISSUE TITLE
MySql not working

### ISSUE THREAD

**Issue by TheBozzz34** [webbukkit/dynmap#3277]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *I am trying to get dynmap to store maps in a database, I have filled out my config with all the database info but when I try to start the server, dynmap won't open the database and then disables itself. Both LuckPerms and CoreProtect are storing data in the database so it's not a problem there*

* **Dynmap Version:** *dynmap-3.1-beta6-spigot*
* **Server Version:** *Paper 1.16.4, git-paper-416 and running through WaterFall 1.16-395*
* **Pastebin of Configuration.txt:** *https://pastebin.com/xZkE9zCG*
* **Server Host (if applicable):** *SelfHosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/fHbhkJKZ*
* **Other Relevant Data/Screenshots:** *No textures packs and the map is up to date, it works with filetree storage*
* **Steps to Replicate:** *Select MySQL, uncomment the neccicary lines, add the data and start the server*

 [possibly, but I didn't see any real help] *I have looked at all other issues and this is not a duplicate*  
 [yes happens every time] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
I'm going to close this due to age but please reply if this is still relevant and I will help as I can, additionally you may want to visit our [discord ](discord.gg/52pqBpw) for faster support
