### ISSUE TITLE
DynmapForge don't rendering blocks textures

### ISSUE THREAD

**Issue by ChefMC** [webbukkit/dynmap#3282]
**Issue Description:** DynmapForge can take textures of any blocks from mods for rendering, but doesn't do it. IC2, BC2 and ProjectRed are rendering. But other mods are not rendering on map. Why Dynmap don't just taking texture for blocks, instead of don't rendering them?

* **Dynmap Version:** 2.6-beta1
* **Server Version:** KCauldron/Thermos 1.7.10 (Forge 1614)

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
DynmapBlockScan was created to do this: [DynmapBlockScan ](https://github.com/webbukkit/DynmapBlockScan)and the [community library of models](https://github.com/FedUpWith-Tech/DynmapBlockScan-Data)
