### ISSUE TITLE
Server say doesn't show

### ISSUE THREAD

**Issue by Naeaeaeaeae** [webbukkit/dynmap#3287]
Webchat doesn`t show the server "say XYZ" message in the webchat.
Every User shows in the chat

**Comment by OskarZyg** [comment]
I don't think this deserves to be a bug. `/say` is a command, not a message.

**Comment by Blitheness** [comment]
These aren't chat messages, I wouldn't expect dynmap to relay them.

You could update your aliases file so "say" invokes
- minecraft:say
- dynmap sendtoweb

Then they'll appear in game as well as on dynmap

**Comment by Naeaeaeaeae** [comment]
It does appear ingame if send ingame from a player.
But not if ussiued from Terminal.

Thanks

**Comment by Blitheness** [comment]
Sending messages from terminal with 'say' is not the same as a player chat event, which is what dynmap listens for. If you want the functionality where dynmap broadcasts the 'say' messages too, try implementing what I said above.
