### ISSUE TITLE
Dynmap Url

### ISSUE THREAD

**Issue by RealMbrads** [webbukkit/dynmap#3288]
This really isnt an issue but how do you get dynmap plugin to have its own url ex minecraftservermap.com like earthmc does

**Comment by Blitheness** [comment]
Hi, this can be achieved by either;
- Setting up an external web server, on the same machine as your Minecraft server, or a machine you can sync files to ([reference](https://github.com/webbukkit/dynmap/wiki/External-Webserver-Basics))
- Setting up an nginx reverse proxy ([reference](https://github.com/webbukkit/dynmap/issues/2025))
