### ISSUE TITLE
Mapping regional difficulty

### ISSUE THREAD

**Issue by berlincount** [webbukkit/dynmap#3290]
Hello!

**Feature Description:**

hearing our players (a dozen or so) curse last night, I read up on https://minecraft.fandom.com/wiki/Difficulty#Regional_difficulty

> The *regional difficulty* (or *local difficulty*) is a value between 0.00 and 6.75 that is calculated by the difficulty setting, the world's _total playtime_, the chunk's _inhabited time_, and the phase of the moon.

... while the phase of the moon is of course always changing, the rest should really be nice to map, so we can have an idea for "hot spots" on a flat map, like the temperature map?

Thank you for your consideration! :)

   count

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
