### ISSUE TITLE
Fullrender shows shadows in chunks that are lit up

### ISSUE THREAD

**Issue by ultraeggplant** [webbukkit/dynmap#3294]
Very sorry if this has been answered before, I couldn't find anyone with the same issue.
I've pregenerated my map with worldborder and later chunkmaster, and fullrendering afterwards left me with a large square of shadowy chunks centered on 0 0. A while ago those areas were dark ingame, however they've fixed themselves, but dynmap doesn't update the area unless I go there ingame and do /dynmap updaterender, which only updates a small part. The affected area is very large, and manually updating everything would take me forever - is there something I can do to go about this better?

Here are some screenshots to demonstrate. Again, very sorry if this is a duplicate.
https://imgur.com/CzAVxW6
https://imgur.com/RSHEp4F

**Comment by Tsoccerguy3** [comment]
My best guess is that you still have chunks of an older minecraft version in your map . You could force the map upgrade , which is a lot faster than flying around opening the chunks , see here how to do this for Spigot and Paper , https://www.spigotmc.org/ . Then fix the maps lighting with https://github.com/bergerhealer/Light-Cleaner , do a /cleanlight world command
