### ISSUE TITLE
Can't use Postgres as Storage

### ISSUE THREAD

**Issue by jithvan** [webbukkit/dynmap#3295]
**Issue Description:** *I did a fresh dynmap install with the latest version. However after I edit the config and add my Postgresql database details I get the following error constantly:*

```
[Server] INFO Dynmap Integration: Could not retrieve the MarkerAPI.
[Server] WARN [dynmap] Marker API has been requested, but is not enabled.  Uncomment or add 'markers' component to configuration.txt.
```

* **Dynmap Version:** *v3.1-beta-7*
* **Server Version:** *Paper version git-Paper-"3dadd97bb" (MC: 1.16.5)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/MsyBTSw4*

* **Steps to Replicate:** *Added dynmap to the plugins folder. Restarted the server and dynmap loads normally. Edited the config, adding only the Postgres details. Restarted the server and the error keeps printing in the console.*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
