### ISSUE TITLE
Dynmap Stopping Server Fully Loading

### ISSUE THREAD

**Issue by Kangy1103** [webbukkit/dynmap#3296]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Server doesn't fully boot with Dynmap installed. Server hits the 1 tick time limit and reboots as it detects the delay as a crash*

* **Dynmap Version:** *3.1 beta7 Forge 1.16.5*
* **Server Version:** *forge 1.16.5 36.0.25*
* **Pastebin of Configuration.txt:** *https://pastebin.com/gHhBg3uU*
* **Server Host (if applicable):** *Bisect Hosting.*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/byn4Edhy*
* **Other Relevant Data/Screenshots:** *Running modpack TNP Limitless 3 1.9.5 w/Discord Integration 2.1.0, Spark, worldedit, world pregenerator*
* **Steps to Replicate:** *Install jar file on server, setup configuration.txt. Watch server hang after generating spawn point*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by miiichael** [comment]
I think this is a dup of #3284.

**Comment by Kangy1103** [comment]
It does seem to be yes. I did check for the issue but my wording didn't bring that up in search

**Comment by miiichael** [comment]
Until it gets fixed, your options are to either bump max-tick-time in server.properties until it stops timing out (which could take an unreasonable amount of time with complex modpacks), or remove mods from your pack to reduce the number of block types.

**Comment by miiichael** [comment]
Try latest (3.1 final) dynmapforge now?
