### ISSUE TITLE
Add to dynmap show entities

### ISSUE THREAD

**Issue by Misio12320** [webbukkit/dynmap#3298]
> template is **bold**
> sample data is *italicized*

**Feature Description:** I would like to see at my server some artworks which is created by paintings but I do not see them. I would like also see item frames with images inside but they are not visible. Feel free to add support to it.

* **Additional context:** None, said above.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
