### ISSUE TITLE
permission node for specific users on the map

### ISSUE THREAD

**Issue by Theamazinggenko** [webbukkit/dynmap#3300]
> template is **bold**
> sample data is *italicized*

A new permission node for specific player on the map such as if i gave this permission to someone dynmap.playermarkers.SenpaiGenko you would now be able to see SenpaiGenko on the map but not other players

So in teams, the team players within their own team can see each other and themselves but are unable to see other users/teams.

**Comment by FedUpWith-Tech** [comment]
This is a cool idea!

**Comment by FedUpWith-Tech** [comment]
While this is a cool idea it is outside the scope of what dynmap is. I would suggest making your own addon for this feature.
