### ISSUE TITLE
Black tiles on dynmap | can't get rid of them

### ISSUE THREAD

**Issue by MayorFluffy** [webbukkit/dynmap#3301]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap is having black tiles, while they are rendered, chunks are rendered as well. Can't get rid of them in any way.*

* **Dynmap Version:** *dynmap-3.1beta7-spigot*
* **Server Version:** *SSSpigotClip 1.16*
* **Pastebin of Configuration.txt:** *https://pastebin.com/pyMWeku0*
* **Server Host (if applicable):** *Syntexxhosting*
* **Pastebin of crashlogs or other relevant logs:** *no crash logs*
* **Other Relevant Data/Screenshots:** *
![image](https://user-images.githubusercontent.com/79901440/109619560-36f04380-7b39-11eb-84df-a85c0abc19b2.png)
*
I've tried multiple new renders, updaterenders, fullrenders, flying through it, chunkrender etc etc, no succes.

I have a server running with an average of 40-70 people online. Would like to fix this as soon as possible.

**Comment by Tsoccerguy3** [comment]
Before posting issues you should search for open issues of the same type . Here is a issue that is currently open ands solution https://github.com/webbukkit/dynmap/issues/3285

**Comment by JeffHD** [comment]
I see that u have 2 red border lines. Is WorldBorder installed and have u made the render with /wb fill?
If yes try /wb [world] fill [freq] 0 true 
world = name of your world and feq = chunks per sec
Had the same blank spots on my map and this was the only thing that helped to get rid of them
