### ISSUE TITLE
Dynmap map "Error loading js/null.js"

### ISSUE THREAD

**Issue by bmr-ramos** [webbukkit/dynmap#3305]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Whenever dynmap website refreshes, occasionally, there will be a red bar on top of the website stating "Error loading js/null.js and then it would disappear.*

* **Dynmap Version:** *3.1-beta6-438*
* **Server Version:** *Airplane 1.16.5*
* **Pastebin of Configuration.txt:** *https://pastebin.com/wJtdEn2k*
* **Server Host (if applicable):** *Dedicated hardware*
* **Pastebin of crashlogs or other relevant logs:** *N/A*
* **Other Relevant Data/Screenshots:** * 
![Screen Shot 2021-03-03 at 12 29 39 AM](https://user-images.githubusercontent.com/65150199/109763486-c50b0f00-7bb7-11eb-8b4b-918a5497b670.png)
*
* **Steps to Replicate:** *Whenever joining the dynmap website, or simply refreshing the website, this message pops up.*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by rlcurrall** [comment]
This appears to be originating from [here](https://github.com/webbukkit/dynmap/blob/v3.0/DynmapCore/src/main/resources/extracted/web/js/map.js#L405).

**Comment by generrosity** [comment]
Can you replicate this on other computers/cellphones? Updated to the latest versions of things?
