### ISSUE TITLE
Chunk sync issue.

### ISSUE THREAD

**Issue by Agaloth** [webbukkit/dynmap#3308]
**Issue Description:** *It seems like dynmap causes a lot of lag on my server even though it doesn't render after 10 players on (set on config), and it seems to be a chunk sync issue.*

* **Dynmap Version:** *dynmap version 3.1-beta7-449*
* **Server Version:** *Purplane version git-Purplane-"b5b6595" (MC: 1.16.5)*
* **Pastebin of Configuration.txt:** *https://ghostbin.com/paste/wGn3U (pastebin wouldn't work for some reason)*
* **Server Host (if applicable):** *Bloom.host (performance+ 16gb, ryzen 9 5950x with 4 logical cores)*
* **Pastebin of crashlogs or other relevant logs:** *https://spark.lucko.me/#7hR5h2WmEF*
* **Other Relevant Data/Screenshots:** *This is the part where dynmap might interfere with:
![image](https://user-images.githubusercontent.com/33335971/110190706-ecb2df00-7e24-11eb-9bd3-2ce6f643b92d.png)
*
* **Steps to Replicate:** *Don't really have any steps about that one.*

 [ x] *I have looked at all other issues and this is not a duplicate*  
 [ x] *I have been able to replicate this*

**Comment by Agaloth** [comment]
Can this be checked?

**Comment by FedUpWith-Tech** [comment]
Purplane is not a supported server fork, We haven't seen this issue on supported server forks
