### ISSUE TITLE
Dynmap and SkinsRestorer v14 integration error

### ISSUE THREAD

**Issue by Bloodlex** [webbukkit/dynmap#3313]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap is not working with newest version of SkinsRestorer. It doesn't show player skins and also throws errors in the console when integration is enabled. Please see the pastebin of crashlogs attachment for details.*

* **Dynmap Version:** *dynmap v3.1-beta7-449*
* **Server Version:** *Paper 1.16.5 build 550*
* **Pastebin of Configuration.txt:** *https://pastebin.com/6PeBX5Uy*
* **Server Host (if applicable):** *ApexMC*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/PfzGmeNa*
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *Download the newest version of SkinsRestorer from here: https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX/lastSuccessfulBuild/artifact/target/SkinsRestorer.jar, enable integration and start server.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by xknat** [comment]
@Bloodlex new release of SR (v14) will be released in ~4 hours but can already be downloaded here: https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX/lastSuccessfulBuild/
~knat from srteam
(make sure your using latest dynmap)

**Comment by Bloodlex** [comment]
@xknat Thank you very much, it works great with the latest development build of dynmap and the latest version of SkinsRestorer. Great job, thanks a lot! 😁

**Comment by kdkasad** [comment]
> ... it works great with the latest development build of dynmap and the latest version of SkinsRestorer. Great job, thanks a lot!

By "development build" do you mean building from source yourself, or is there a development JAR available somewhere?

**Edit:** Dynmap v3.1 (for Spigot) is available on the Spigot plugin page, but not on GitHub, which is where I was looking. Hiding this comment.

**Comment by FedUpWith-Tech** [comment]
Sorry to necro this post but yes. Dynmap 3.1 GA added SkinRestorer v14 support.
