### ISSUE TITLE
ChangeSkin support

### ISSUE THREAD

**Issue by imDaniX** [webbukkit/dynmap#3315]
**Feature Description:** Add [ChangeSkin](https://github.com/games647/ChangeSkin) support for player faces. 

**Additional context:** ChangeSkin is a lightweight alternative for SkinsRestorer (which is considered by some users as a bloatware) with a really straightforward functionality.

**Comment by imDaniX** [comment]
For some future reference

https://github.com/games647/ChangeSkin/blob/570b321fbcbedda96ce1ef608d718e187bb9e709/bukkit/src/main/java/com/github/games647/changeskin/bukkit/ChangeSkinBukkit.java#L102

https://github.com/games647/ChangeSkin/blob/570b321fbcbedda96ce1ef608d718e187bb9e709/core/src/main/java/com/github/games647/changeskin/core/model/UserPreference.java#L84

https://github.com/games647/ChangeSkin/blob/570b321fbcbedda96ce1ef608d718e187bb9e709/core/src/main/java/com/github/games647/changeskin/core/model/skin/SkinModel.java#L151

https://github.com/games647/ChangeSkin/blob/570b321fbcbedda96ce1ef608d718e187bb9e709/core/src/main/java/com/github/games647/changeskin/core/model/skin/TextureModel.java#L29

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
