### ISSUE TITLE
Support of Resource Packs

### ISSUE THREAD

**Issue by kruegermedia** [webbukkit/dynmap#3316]
**Feature Description:** *Support of the Resourcepack format for alternative Textures.*

* **Additional context:** *I would be happy to see support and documentation for Resourcepacks, as there are not any texturepacks for 1.16.5*

Thanks for the consideration :)

**Comment by imDaniX** [comment]
https://github.com/webbukkit/dynmap/issues/1797#issuecomment-639230332

**Comment by kruegermedia** [comment]
@FedUpWith-Tech Just a question, where is this request answered?
Unfortunately I can't find any documentation about the usage of resource packs... As texture packs are outdated since 2013 I would be interested in current status.
kind regards

**Comment by FedUpWith-Tech** [comment]
It's in the linked comment by @imDaniX
