### ISSUE TITLE
Feature request no re-render

### ISSUE THREAD

**Issue by Misio12320** [webbukkit/dynmap#3322]
> template is **bold**
> sample data is *italicized*

**Feature Description:** 
Add a feature when user want to change his mapzoomin: and mapzoomout: then let the render only remove the old tiles not all tiles which won't get any changes. I mean remove only these tiles which won't be used in mapzoomin: and mapzoomout:
* **Additional context:** None I guess

**Comment by FedUpWith-Tech** [comment]
Closing due to age please submit a new ticket if this is sitll relevant
