### ISSUE TITLE
Multiple isometric views for one world override/replace each other when rendered

### ISSUE THREAD

**Issue by VoltroXP** [webbukkit/dynmap#3323]
**Issue Description:** *If multiple isometric views are set for one world, such as a spawn area or hub, they override each other upon trying to render each one. If all of them are attempted to be rendered at once, only the last one ends up being visible across all of them because it was the last to be rendered. In my case, I want to have multiple map type buttons for my spawn so players can view it from different angles. But, only the vertical, above map type and whichever isometric map type I last rendered end up being viewable. Interestingly though, player positions are updated correctly when switching between map types, which can be seen in the screenshots below.*

* **Dynmap Version:** *core=3.1-beta7-449, plugin=3.1-beta7-449*
* **Server Version:** *git-Paper-"8b47131da" (MC: 1.16.5)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/18bMzqRb*
* **Server Host (if applicable):** *PebbleHost*
* **Pastebin of crashlogs or other relevant logs:** *None*
* **Other Relevant Data/Screenshots:** 
![Terrestria Dynmap - Opera 3_28_2021 5_00_06 PM (2)](https://user-images.githubusercontent.com/48335543/112768058-12787180-8fe8-11eb-9743-b2a115bed51d.png)
![Terrestria Dynmap - Opera 3_28_2021 5_00_15 PM (2)](https://user-images.githubusercontent.com/48335543/112768064-1c9a7000-8fe8-11eb-87af-1ef3a155f973.png)
![Terrestria Dynmap - Opera 3_28_2021 5_00_23 PM (2)](https://user-images.githubusercontent.com/48335543/112768072-2623d800-8fe8-11eb-8f08-bf2e9a9807e3.png)
![Terrestria Dynmap - Opera 3_28_2021 5_00_32 PM (3)](https://user-images.githubusercontent.com/48335543/112768082-2e7c1300-8fe8-11eb-8a8f-f784e1667ae3.png)

* **Steps to Replicate:** *Below I have included the relevent world in the worlds.txt file. If one is to replicate it, all information should be given. To replicate, render all isometric views or each one at a time and watch as each map type is rendered then replaced/overrided by the next render.*

 [Y] *I have looked at all other issues and this is not a duplicate (One is seemingly close to this issue, but not quite the same)*  
 [Y] *I have been able to replicate this*

(I also made custom perspectives with the same values as the regular ones, since that was recommended in a similar issue here. Since I'm making this bug report, it obviously didn't do anything.)
This is what I have set in the worlds.txt file:
-   name: spawn
    title: "Spawn"
    enabled: true
    sendposition: true
    sendhealth: false
    extrazoomout: 1
    visibilitylimits:
    -   x0: -220
        z0: -220
        x1: 220
        z1: 220
    hiddenlimits: [
        ]
    hidestyle: air
    center:
      x: 0
      y: 64
      z: 0
    maps:
    -   class: org.dynmap.hdmap.HDMap
        name: spawn0
        title: "Topographic"
        prefix: flat
        icon: images/block_world_biome.png
        perspective: iso_S_90_vlowres
        shader: stdtexture
        lighting: shadows
        image-format: default
        mapzoomin: 3
        mapzoomout: 0
        boostzoom: 0
        append_to_world: ''
    -   class: org.dynmap.hdmap.HDMap
        name: spawn1
        title: "Southwest"
        prefix: st
        icon: images/block_skylands.png
        perspective: iso_SW_30_hires1
        shader: stdtexture
        lighting: shadows
        mapzoomin: 2
        mapzoomout: 3
    -   class: org.dynmap.hdmap.HDMap
        name: spawn2
        title: "Southeast"
        prefix: st
        icon: images/block_world_cave.png
        perspective: iso_SE_30_hires2
        shader: stdtexture
        lighting: shadows
        mapzoomin: 2
        mapzoomout: 3
    -   class: org.dynmap.hdmap.HDMap
        name: spawn3
        title: "East"
        prefix: st
        icon: images/block_world_surface.png
        perspective: iso_E_30_hires3
        shader: stdtexture
        lighting: shadows
        mapzoomin: 2
        mapzoomout: 3
    -   class: org.dynmap.hdmap.HDMap
        name: spawn4
        title: "Northeast"
        prefix: st
        icon: images/block_other.png
        perspective: iso_NE_30_hires4
        shader: stdtexture
        lighting: shadows
        mapzoomin: 2
        mapzoomout: 3

**Comment by FedUpWith-Tech** [comment]
You used the same prefix for all the maps, that is why they are the same

**Comment by VoltroXP** [comment]
Ohhh ok, thank you. Would be nice if there was a note regarding the significance of that in the wiki or something lol
