### ISSUE TITLE
Custom Model Textures

### ISSUE THREAD

**Issue by Cale111** [webbukkit/dynmap#3324]
**Feature Description:** Adding custom models and/or custom model textures for use in resource packs.

* **Additional context:** I was trying to add custom leaves into my resource pack and because I changed birch leaves, I needed to change the model's texture, because of how birch leaves don't use the colormap. Unfortunately dynmap can't use those custom textures so the leaves look like default ones.

**Comment by FedUpWith-Tech** [comment]
Duplicate of #3438
