### ISSUE TITLE
Cannot add custom icons

### ISSUE THREAD

**Issue by PappoYT** [webbukkit/dynmap#3328]
**Issue Description:** *I cannot add custom icons.*

* **Dynmap Version:** *3.1*
* **Server Version:** *Paper 1.16.5 build 575*
* **Pastebin of Configuration.txt:** *[https://pastebin.com/V7j3RscH](https://pastebin.com/V7j3RscH)*
* **Server Host (if applicable):** *GameHosting (Italy)*
* **Pastebin of server logs:** *[https://mclo.gs/ngW420A](https://mclo.gs/ngW420A)*
* **Steps to Replicate:** *

1. upload my-icon.png (32x32pixel) on server root
2. run command /dmarker addicon id:my-icon my-icon file:my-icon.png (my-icon is unique name)
3. run command /dmarker icons to check if my my-icon is listed and it is listed
4. check /plugins/dynmap/web/tiles/_markers_/ to check if my-icon has been copied and it has been copied
5. restart server
6. run command /dmarker icons to check if my my-icon is listed and it is **not** listed
7. check /plugins/dynmap/web/tiles/_markers_/ to check if my-icon is still there and so it is
*

 [X ] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Not sure if this is still relevant but I was able to add a custom icon
![image](https://user-images.githubusercontent.com/7731191/147002935-37023278-27d4-46d5-8106-cbe5b39d7133.png)
