### ISSUE TITLE
Dynmap deletes itself once full render of caves are done

### ISSUE THREAD

**Issue by owen250708** [webbukkit/dynmap#3329]
I try to do a full render, and when it finishes the caves the whole dynmap deletes.

**Comment by FedUpWith-Tech** [comment]
Which server host are you using? Some server hosts will delete Dynmap's files once a render is complete as they take up so much space.

**Comment by owen250708** [comment]
I'm using Shockbyte on 3gb RAM. It works on vlowres but not on lowres.

**Comment by FedUpWith-Tech** [comment]
Yeah, the issue is shockbyte. Unfortunately they are not user-friendly or dynmap-friendly and deleting files is incredibly common with them
