### ISSUE TITLE
Right click causes crash

### ISSUE THREAD

**Issue by tajemniktv** [webbukkit/dynmap#3331]
**Issue Description:** *Right clicking causes a game to crash. Either with a hoe or axe*

* **Dynmap Version:** *v3.1 for Forge 1.16.5*
* **Server Version:** *Forge 1.16 build 36.1.0*
* **Pastebin of Configuration.txt:** *https://paste.ee/p/rNf2E*
* **Pastebin of crashlogs or other relevant logs:** *https://paste.ee/p/nDAT9*
* **Other Relevant Data/Screenshots:** *Here's my mod list: https://paste.ee/p/x9RXv*
* **Steps to Replicate:** *Right click with a hoe on grass*

 [**X**] *I have looked at all other issues and this is not a duplicate*  
 [**X**] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Closing due to dead links
