### ISSUE TITLE
Keep getting this in server console: New generated chunk detected at [-161, -131] for Multiplayer SMP

### ISSUE THREAD

**Issue by GeneralCyber1** [webbukkit/dynmap#3332]
I have a fabric 1.16.4 server with Dynmap 3.1 Beta 7 fabric version. I keep getting this error even though chunks in those coordinates have already been explored by players and generated by dynmap already. I get this message repeatedly and it just spams the server console. Here's an example taken with a gyazo screenshot: https://gyazo.com/e97b74f99a295195832f68da777fa93c

Any ideas guys?

**Comment by FedUpWith-Tech** [comment]
Assuming this is fixed in a later release or otherwise no longer relevant- please open a new issue if this persists.
