### ISSUE TITLE
Dynmap on MySQL

### ISSUE THREAD

**Issue by ElFrod0** [webbukkit/dynmap#3333]
**Issue Description:** *Dynmap is trying to create new tables in database after server restart. I tried MySQL Server 5.7 and MySQL Server 8.0 as well.*

* **Dynmap Version:** *Dynmap-3.1-spigot.jar*
* **Server Version:** *Yatopia 1.16.5 *
* **Pastebin of Configuration.txt:** *https://pastebin.com/VxdmasjK*
* **Server Host (if applicable):** *Fakaheda.eu*
* **Steps to Replicate:** 
*1) Connect Dynmap on MySQL*
*2) Start server*
*3) After loading.. Restart server*
*4) Voilá replicated.*
![image](https://user-images.githubusercontent.com/45905208/114113400-c4fcde00-98de-11eb-8380-80225316a420.png)

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by doppelkool** [comment]
That could be any possible issue:
- the mysql-login-information are set wrong in the configuration.txt
- the user you set up in the configuration.txt has not the permission to manage the dynmap Database.
- the issue literally set "the table already exists", so it tried to create the table, but it is already there. -> We don't know how your database looks like, but i consider that there are tables he wants to use, but they're already there.
- and so on...

I'm really confused, cause I tried to replicate the error, but it did not occur on my system.
The most possible issue can be, that the plugin does not like prefixes in the db-tables - got this error a while ago. Deleted the prefixes and Voilá it worked, instant.

Hope my comment helps - if I missed a detail, please mention it
thx
