### ISSUE TITLE
Does dynmap support listening access from IPv6?

### ISSUE THREAD

**Issue by y1jiong** [webbukkit/dynmap#3335]
My server environment supports IPv6, but I use netstat to check the dynmap listening port and only find tcp and not tcp6.
So I want to ask, does dynmap support IPv6?

**Comment by wioxjk** [comment]
Meanwhile, you could look into setting up a reverseproxy in your webserver. :)

**Comment by y1jiong** [comment]
> Meanwhile, you could look into setting up a reverseproxy in your webserver. :)

I did not use a reverse proxy, and directly exposed port 8123.  Then I used `netstat -tupln` to check the bound port, and found that dynmap only binds to port 8123 of IPv4, so I'm here to ask.

**Comment by FedUpWith-Tech** [comment]
Dynmap only uses IPv4, it doesn't support IPv6 nor has any plans to support it as of now

**Comment by y1jiong** [comment]
> Dynmap only uses IPv4, it doesn't support IPv6 nor has any plans to support it as of now

Is there really no such plan?  IPv6 will be a big trend in the future.
In order to better fit the development, I still hope that dynmap can support IPv6.

Thank you very much.

**Comment by wioxjk** [comment]
@yzy613 
That is why you should look into setting up a reverseproxy with apache for example

https://gist.github.com/DmitryRendov/1efb672a0733aca5314dc3332d9823ac

**Comment by y1jiong** [comment]
@wioxjk 
Have you considered the situation that ports 80 and 443 cannot be accessed?

**Comment by wioxjk** [comment]
@yzy613 You can run apache on other ports too.
And since you probably would want TLS, a reverseproxy is probably something that you would want anyway :)

**Comment by y1jiong** [comment]
Is it really that difficult to support IPv6? There is no need to use httpd for IPv6, right? Isn't it good to be simple? (￣ε(#￣)~

I just wanna make it simple. ( ͡ಠ ʖ̯ ͡ಠ)
