### ISSUE TITLE
[Server] etp1259697046-55/FATAL [Dynmap]: [Dynmap] Error updating Maps table - (conn:108973831) Table 'customer_183318_dynmap.Maps' doesn't exist

### ISSUE THREAD

**Issue by omeletflipper** [webbukkit/dynmap#3336]
I'm running Dynmap Forge on forge-1.12.2-14.23.5.2838 with SpongeForge. I'm able to correctly install the webserver for the Dynmap, but whenever I try to update the map so it shows the tiles/chunks, I always get the same error in console:

10.04 21:16:54 [Server] etp1259697046-55/FATAL [Dynmap]: [Dynmap] Error updating Maps table - (conn:108973831) Table 'customer_183318_dynmap.Maps' doesn't exist
10.04 21:16:55 [Server] etp1259697046-62/FATAL [Dynmap]: [Dynmap] Error updating Maps table - (conn:108973833) Table 'customer_183318_dynmap.Maps' doesn't exist
10.04 21:16:55 [Server] etp1259697046-55/FATAL [Dynmap]: [Dynmap] Error updating Maps table - (conn:108973834) Table 'customer_183318_dynmap.Maps' doesn't exist
10.04 21:38:33 [Server] Dynmap Render Thread/FATAL [Dynmap]: [Dynmap] Error updating Maps table - (conn:108982234) Table 'customer_183318_dynmap.Maps' doesn't exist
10.04 21:38:34 [Server] Dynmap Render Thread/FATAL [Dynmap]: [Dynmap] Error updating Maps table - (conn:108982242) Table 'customer_183318_dynmap.Maps' doesn't exist
10.04 21:38:35 [Server] Dynmap Render Thread/FATAL [Dynmap]: [Dynmap] Error updating Maps table - (conn:108982250) Table 'customer_183318_dynmap.Maps' doesn't exist

The server does not crash or break, and the error keeps spamming itself in console. It's only the Dynmap that stops functioning. I'm using PebbleHost as my host service if that'll help. Any assistance to fix this issue would be greatly appreciated.

**Comment by FedUpWith-Tech** [comment]
Check and make sure your SQL credentials are correct. This error usually happens when Dynmap can't modify the SQL database (Table 'customer_183318_dynmap.Maps does not exist)
