### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by jewome62** [webbukkit/dynmap#3337]
**Issue Description:** 
Dynmap consume too many memory. 
I have launch a fullrender of a flat map. but I will have some memory warning fromFAWE.
So i have checked the memory and dynmap consume 6.75 GB + 1.13 GB GB https://spark.lucko.me/EOVzlTNUXU
In consequence, i have stop (with cancelrender) and purge the queue (purgequeue)
But the heapsummary don't move. 

We have 6 minecraft map with 3 rendering: flat, sw and se
Internal server web is disabled and i use a caddy server for web interface
https://supersamaworld.com/dynmap/build/

On configuration I have 

* **Dynmap Version:** 3.1-457
* **Server Version:** Tuinity 1.16.5 "a0aa5ab"
* **Pastebin of Configuration.txt:** https://pastebin.com/mfWbq7U6
* **Server Host (if applicable):** Dedicated server AMD Ryzen 9 5950X 24 theads,, 126Go RAM, 4To SSD Nvme
Virutal server : No CPU limit, Docker RAM : 30Go, JVM RAM: 25Go
* **Pastebin of crashlogs or other relevant logs:** No logs
* **Other Relevant Data/Screenshots:** memory heapsummary : https://spark.lucko.me/EOVzlTNUXU
* **Steps to Replicate:** Sorry i don't know the origin

 [X] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Dynmap does not support Tuinity and there are known memory leaks when Dynmap runs on Tuinity. As of now, there are no plans to add support for Tuinity.
