### ISSUE TITLE
Bungeecord support in any way?

### ISSUE THREAD

**Issue by JohnB17** [webbukkit/dynmap#3339]
**Feature Description:** Bungeecord support in some way?

* I want to use dynmap on my bungeecord network

**Comment by JurgenKuyper** [comment]
that works just fine, I am using bungee with dynmap

**Comment by JohnB17** [comment]
> that works just fine, I am using bungee with dynmap

How do you link the dynmaps together?

**Comment by JurgenKuyper** [comment]
> How do you link the dynmaps together?
what do you mean? I just have multiple links like survival.domain.com, creative.domain.com and so on

**Comment by isaaclepes** [comment]
I think I know what they mean..

The ability to have 1 URL for the map with the worlds of each server listed.  Possibly in a format like:

ServerName - WorldName - Flat, Surface, Cave, etc.
Survival - Overworld - Flat, Surface, Cave
Survival - Nether - Flat, Surface
Survival - The End - Flat, Surface
Hub - Main Lobby - Flat, Surface
Hub - Minigames Lobby - Flat, Surface
SkyWars - Map 1 - Flat, Surface
SkyWars - Map 2 - Flat, Surface
SkyWars - Map 3 - Flat, Surface
Creative - Skyworld - Flat, Surface
Creative - Cities - Flat, Surface

Really, this looks like it could be made to work using the external web server feature if the 'dynmap_config.php' and 'dynmap_login.php' were world-specific.  If we could define additional 'includes' in 'configuration.php' and have sets of these per server, it would be mostly functional.

For config.php's
dynmap_Server1_config.php
dynmap_Server2_config.php

then in configuration.php adjust function to concatenate the lines from multiple files by adjusting this part to merge multiple files into the array.

$lines = file('dynmap_config.php');
array_shift($lines);
array_pop($lines);
$json = json_decode(implode(' ',$lines));

As a test, I manually inserted the 'worlds' from one server's dynmap_config.php into that of another and copied over the tiles folder.  Although the page keeps trying to unsuccessfully refresh itself, I am able to see all of the maps for both servers in one interface.  Seems like it could be made to work without too much reengineering.

**Comment by FedUpWith-Tech** [comment]
Hey! This is a pretty common feature request but the plugin Dev has made it clear that he doesn't plan to add support for this way. As @isaaclepes mentioned this is technically possible but it is not something we want to support and requires advanced per-server configuration.

**Comment by Mikec78660** [comment]
If anyone else comes across this looking for the same thing. It exists :-)
[https://www.spigotmc.org/resources/liveatlas-a-dynmap-frontend-for-the-modern-web.86939/](url)
