### ISSUE TITLE
Market set help request (not a bug)

### ISSUE THREAD

**Issue by morlanius** [webbukkit/dynmap#3342]
Hi,
Is there a method to make a set not enabled by default? I tried editing markers.yml adding in enabled: false into the set but it didn't do what I expected.
The result I am looking for is for the set to be populated and available but not shown by default so the viewer has to enable the set to see the markers rather than having all the markers on at once and the user hiding/unticking them.

Thank you for your time
Morl

**Comment by generrosity** [comment]
I think the attribute is 'hide'
hide:<true|false> is used to control whether the set is visible (checked) or hidden (unchecked) by default
