### ISSUE TITLE
Dynmap set 1000000 blocks outside of world spawn

### ISSUE THREAD

**Issue by YoshiORK** [webbukkit/dynmap#3345]
**Issue Description:** * My dynmap has been set millions of blocks outside of my world spawn
* **Dynmap Version:** 3.1
* **Server Version:** paper 1.16.4
* **Pastebin of Configuration.txt:** "Dont remember the exact date"
* **Server Host (if applicable):** Ploxhost
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** Im not sure

![0jp](https://user-images.githubusercontent.com/82899251/115435912-579f5600-a1d8-11eb-8e2f-9d5b04713423.PNG)

**Comment by FedUpWith-Tech** [comment]
We need your configuration.txt as well as worlds.txt to see what went wrong here. Please upload those to pastebin and send them here.
