### ISSUE TITLE
deftemplatesuffix keeps changing to vlowres

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#3348]
That's basically it. I close the server, set deftemplatesuffix in configuration.txt to hires, hi_boost_vhi or something like that and when I start the server and check the configuration file and it magically turned back again to vlowres.

**Comment by FedUpWith-Tech** [comment]
This is something done by server hosts to limit the amount of storage space dynmap will use. Shockbyte is the biggest offender here, unfortunately there is nothing we can do about this.
