### ISSUE TITLE
Completely new setup of Dynmap is running into this error after reloading (immediately)

### ISSUE THREAD

**Issue by doppelkool** [webbukkit/dynmap#3350]
**Issue Description:** *Completely new setup of Dynmap is running into this 'block scan mod' error after reloading (immediately)*

* **Dynmap Version:** *core=3.1-457, plugin=3.1-457*
* **Server Version:** *paper 1.16.5 build Paper-593*
* **Pastebin of Configuration.txt:** **You dont need to look at it, it's completely new**: *https://pastebin.com/62xWuxki*
* **Server Host (if applicable):** *Strato*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/m1x2TqBi*
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *Set dynmap up (new) -> /dynmap reload -> Error*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Patch to remove the reload command is now implemented via Dynmap 3.2beta3 
Downloads are available at the usual locations:
- Forge/Fabric at CurseForge ( https://www.curseforge.com/minecraft/mc-mods/dynmapforge/files/all )

- Spigot/PaperMC at dev.bukkit.org (https://dev.bukkit.org/projects/dynmap/files ) and spigotmc (https://www.spigotmc.org/resources/dynmap.274/update?update=420301)

Sometimes these folks are slow to approve - if needed, the builds can also be found at https://dynmap.us/releases

**Comment by seema84** [comment]
why is the command removed instead of fixing the problem?
