### ISSUE TITLE
Placeholder %cmi_bungee_current_[ServerName]%

### ISSUE THREAD

**Issue by rapofil** [webbukkit/dynmap#3352]
Placeholder %cmi_bungee_current_[ServerName]% show vanished staff

can it be fixed?

**Comment by FedUpWith-Tech** [comment]
Can you give us a bit more information?
Here is a template you can fill out to help: 
Issue Description: 
Dynmap Version: 
Server Version: 
Pastebin of Configuration.txt: 
Server Host (if applicable): 
Pastebin of crashlogs or other relevant logs: 
Other Relevant Data: (include what chat plugins you use here) 
Steps to Replicate:

**Comment by rapofil** [comment]
1.16.5 paper
dynmap? v3.1 GA

I have a placeholder %cmi_bungee_current_[ServerName]% in hologram in lobby. For example, there are 3 players on that server [ServerName] + 1 staff who has vanish, but the placeholder shows 4 online players. I need the staff in the vanish not to count

**Comment by FedUpWith-Tech** [comment]
> 1.16.5 paper
> dynmap? v3.1 GA
> 
> I have a placeholder %cmi_bungee_current_[ServerName]% in hologram in lobby. For example, there are 3 players on that server [ServerName] + 1 staff who has vanish, but the placeholder shows 4 online players. I need the staff in the vanish not to count

This doesn't sound like a Dynmap issue at all, it sounds like a PlaceholderAPI or Hologram or Vanish plugin issue. I'm going to close this as it seems very unrelated but if you believe it is still related to Dynmap please comment and I will reopen
