### ISSUE TITLE
Use another database types

### ISSUE THREAD

**Issue by karelkryda** [webbukkit/dynmap#3354]
Hey,
can I use another database instead of MySQL? For example MongoDB or Redis or PostgreSQL?
Or can I easily rewrite it to work with this databases?
Thanks :)

**Comment by FedUpWith-Tech** [comment]
I use MariaDB on the plugin version with no changes, PostgreSQL support has been unofficial and untested for quite a while but might work. If you are familiar with hooking Java to a database it shouldn't be too hard to adapt the plugin for your needs.

**Comment by urusaich** [comment]
So what about redis?

**Comment by FedUpWith-Tech** [comment]
> So what about redis?

Probably not
