### ISSUE TITLE
Was wondering if its possible to have the minecraft server and dynmap on the same port and ip?

### ISSUE THREAD

**Issue by utauyo** [webbukkit/dynmap#3356]
I want to have the server on the same port as dynmap so when you go to the ip and port on the browser it goes to dynmap and when you use the same ip and port in minecraft it connects to the server

**Comment by utauyo** [comment]
I couldnt get it working so i was wondering if its even possible

**Comment by Joo200** [comment]
no, that's not possible.

**Comment by FedUpWith-Tech** [comment]
You can use the same IP but not the same port.
