### ISSUE TITLE
Dynmap Sign Setname Permission dynmap.marker.sign.setname

### ISSUE THREAD

**Issue by TomLewis** [webbukkit/dynmap#3358]
**Feature Description:** 
We curerntly have `dynmap.marker.sign` which allows the use of signs to put markers into a  `default-sign-set:`, which works well, but I would like to limit the use of the `set:` on signs based on permissions, I have a hidden set that Contributors can add markers to, but its only toggled on manually by players, they could currently add markers to the main markers set which are default on, but ive not doucmented the `set:` line on signs anywhere at present. At some point someone will figure this out.

Please can you add in permissions to sets users can add markers too using signs, for example;
```
dynmap.marker.sign.* (All sets)
dynmap.marker.sign.markers (Set named "markers")
dynmap.marker.sign.contributors  (Set named "contributors")
```

We also have some third party plugins that auto add sets, which we dont want players being able to add markers into!

Thanks.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
