### ISSUE TITLE
Could not render: world 'world' not defined in configeration... HELP!

### ISSUE THREAD

**Issue by Jg2525** [webbukkit/dynmap#3359]
Well help?

Not a lot else to say 

oh yes I also got World 'world' not defined/loaded

![image](https://user-images.githubusercontent.com/76808734/117537324-04127200-aff8-11eb-9e22-d446e0f8d2a6.png)

**Comment by Jg2525** [comment]
Anyone?

**Comment by Jg2525** [comment]
up

**Comment by FedUpWith-Tech** [comment]
Can you give us some more information?
What server host are you on?
What Dynmap version are you using?
What server version are you using?
Pastebin your configuration.txt
What have you tried to fix this so far?
Was it working before and now it doesn't or is this on a brand new install?
