### ISSUE TITLE
When I prescribe /dynmap fullrender nothing happens.

### ISSUE THREAD

**Issue by Exzept1on** [webbukkit/dynmap#3360]
**Issue Description:** When I prescribe /dynmap fullrender nothing happens. In the chat, it is only written that such a command does not exist.

* **Dynmap Version:** build 3.1
* **Server Version:** *forge 1.16 build 36.1.16
* **Pastebin of Configuration.txt:** I didn't change anything there, except for the server port.
* **Server Host (if applicable):** mgr.hosting-minecraft.ru
* **Pastebin of crashlogs or other relevant logs:** nothing logs
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [1] *I have looked at all other issues and this is not a duplicate*

**Comment by FedUpWith-Tech** [comment]
Can you pastebin your configuration.txt? Additionally what build of Dynmap are you using?

**Comment by Exzept1on** [comment]
Yes. But a little later
