### ISSUE TITLE
Unable to find Configuration File

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#3362]
So for the past week or so I've been setting up my Minecraft server and all this and that, and recently I added dynmap, everything but dynmap appears to work, I've opened its ports and everything.

Right now I'm having two issues, one of which doesn't belong here but I'll still add it.

when I go to my actual domain, map.example.com nothing appears, I have xampp set up, apache is working, going to my IP w/ the port works (although dynmap still doesn't) and I can join my Minecraft server. (although there's no reason cause i'm still setting this broken shit up, including tcpshield)

also also, for some reason I cant join via join.example.com but I can join via the domain and the port (example.com:3001)

![image](https://user-images.githubusercontent.com/72677538/118024741-0abd2400-b32d-11eb-977e-2b6243bdd4e0.png)
idk if they can find stuffs out just from the domain name but just staying safe

second issue is that dynmap cant find the configuration file, I've placed it all over this bitch, in the htdocs folder, in the root folder, in the web folder (in the plugin folder) and in the plugin folder. Nothing.

![image](https://user-images.githubusercontent.com/72677538/118024568-d5b0d180-b32c-11eb-8e8a-868e1580100f.png)
Either of these being fixed would be pretty poggers. thank you.

not sure if this goes here but reddit seems inactive.

**Comment by FedUpWith-Tech** [comment]
Take a look at this page for basic plugin setup and configuration https://github.com/webbukkit/dynmap/wiki/Installation
