### ISSUE TITLE
Setting up with using a hosting service?

### ISSUE THREAD

**Issue by yourlocalvirgo** [webbukkit/dynmap#3366]
So, I've installed/configured Dynmap on my server (to the best of my ability), however, I host my Minecraft server on villagerhost.net and am unable to reach map. Whenever I put in my server's IP address, along with the port, I get a "problem loading page" error, basically saying it's not a valid link. Could anyone help me set this up properly?

**Comment by FedUpWith-Tech** [comment]
Hi! Does this page help? https://github.com/webbukkit/dynmap/wiki/Installation
I couldn't find any knowledgebase articles on VillagerHost's page and they don't seem to have any documentation about plugins that require a second port. You may want to open a ticket with them to get Dynmap set up.
