### ISSUE TITLE
dmap worldaddlimit world type:round center:<x>/<z> radius:<r> add a trailing ".0" to radius value in config file making the parseInt fail

### ISSUE THREAD

**Issue by gmfamily** [webbukkit/dynmap#3367]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Hello community :)

I respawn an previously archived topic about the buggy "dmap worldaddlimit world type:round center:<x>/<z> radius:<r>" command...

Indeed, this command is generating a malformed section un worlds.txt config file adding a trailing ".0" to radius value (i.e. radius:50 in command give r: 50.0 in config file) making the parseInt fail...

Is there any update on the fix?

The worldremovelimit is also concerned as if I use it, it does what it should do (removing the specified limit) but it also updates radius of all others limits (adding again a trailing ".0"). This seems like the world.txt formatter is processing all radius values not as Integer before writing them to file... This is a blocking issue as this is corrupting the world.txt file that need to be fixed manually to get the dynmap services up again..*

* **Dynmap Version:** * dynmap-3.2-SNAPSHOT*
* **Server Version:** *paper 1.16.3*
* **Pastebin of worlds.txt:** *https://pastebin.com/MibMpPGf*
* **Server Host (if applicable):** *not relevant*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/V3F9RVUk*
* **Other Relevant Data/Screenshots:** *not relevant*
* **Steps to Replicate:** *run "dmap worldaddlimit world type:round center:<x>/<z> radius:<r>" then restart server to load corrupted worlds.txt file*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by gmfamily** [comment]
Updated the issue to fully match the bug template.

**Comment by gmfamily** [comment]
Hello team :) any update on this?

**Comment by FedUpWith-Tech** [comment]
There is now a PR that should fix this issue
