### ISSUE TITLE
Dynmap Unload

### ISSUE THREAD

**Issue by EpicRealms** [webbukkit/dynmap#3369]
Hello Dynmap Team,

I have been across with a pretty simple error. Every time my server is restarted (it has a scheduled restart) the dynamp on the url resets too and doesn't render meaning I have to get in the server and re-render it all again. Is there a way to fix this problem so it doesn't 'unrender' when the server its restarted?

Best Regards,
Epic Realms INC Team

**Comment by FedUpWith-Tech** [comment]
This is common on server hosts that don't allow dynmap or that have strict storage rules, they delete dynmap or change the config on server restart which causes the behavior you are experiencing.

To help get you the best support and so I know more about your specific issue can you please full out this info:

***


* **Dynmap Version:** _dynmap-version_
* **Server Version:** _forge 1.16 build x, or paper 1.15.2 build x_
* **Pastebin of Configuration.txt:** _https://pastebin.com/5SETL3z2_
* **Server Host (if applicable):** _McProHosting, Shockbyte, Selfhosted, etc._
* **Pastebin of crashlogs or other relevant logs:** _https://pastebin.com/crashcausedbydynmap_
* **Other Relevant Data:** _I'm using this texture pack and these plugins and my map is from alpha .8_
* **Steps to Replicate:** _Please be clear in this section so we can replicate your issue_

**Comment by EpicRealms** [comment]
I'll provide you with that info as soon as possible, here is what i can already tell you:

- **Dynmap Version:** latest
- **Server Version:** Paper 1.16.4
- **Pastebin:** not available yet
- **Server Host:** BisectHosting
- **No relevant crashlogs or errors**
- **Setps to Replicate:** Restart the server

Sorry for the late answer but it has been a busy week.

Best Regards,
Daniel Antunes AKA IG Noitibos
Epic Realms INC Team

**Comment by rautamiekka** [comment]
'latest' ain't a valid version.

**Comment by EpicRealms** [comment]
- **Dynmap Version:** v3.1

**Comment by EpicRealms** [comment]
the java file is named Dynmap-3.1-spigot.jar

**Comment by FedUpWith-Tech** [comment]
We need the configuration.txt
I recommend taking regular copies of it and checking for changes, Dynmap will never change it's own configuration- any changes are from the server host. I have a feeling Bisect is doing something strange
