### ISSUE TITLE
folder setting uncreated

### ISSUE THREAD

**Issue by Suuiram** [webbukkit/dynmap#3370]
**failure Description:** *i put the file in the plugins folder , i start the server , and turn off it, no dynmap folder in the plugins folder

i check the console and it wrote : >.... [
 [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;
[dynmap] Cannot find net.minecraft.server.BiomeStorage
Error initializing dynmap - bukkit version incompatible! initializing dynmap v3.1-457 (Is it up to date?)*

* **Dynmap Version:** *3.1*
* **Server Version:** *mohist 1.16.5*

* **Server Host (if applicable):** *MineStrator*

* **Steps to Replicate:** *Please be clear in this section so we can replicate your problem*

**Comment by FedUpWith-Tech** [comment]
Try using the Dynmap Forge mod instead of the plugin version
