### ISSUE TITLE
Allow UUIDs to be used instead of Player names.

### ISSUE THREAD

**Issue by Tydium** [webbukkit/dynmap#3371]
> template is **bold**
> sample data is *italicized*

**Feature Description:** instead of using %playername% in the skin URL. There should be an option to use %uuid% instead. This could make more customization to use different API other than the default one. Me specifically I want to use https://tydiumcraft.net/docs/skinapi so I can let bedrock players skins work native without any problems.

* **Additional context:**
Example Usage of the skin api above: https://api.tydiumcraft.net/skin?uuid=00000000-0000-0000-0009-01fa3f915d0a&type=avatar&size=64

**Comment by simonsoundara** [comment]
yes i want this for my friend to be happy

**Comment by KofiZ** [comment]
This would be a nice feature set, might be looked into by other developers as well.. would be great to have

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.

**Comment by FedUpWith-Tech** [comment]
Congrats! This feature request has been implemented and will be a part of the next release. Big thanks to @JLyne for implementing this in #3602

**Comment by Tydium** [comment]
^ You an absolute god @JLyne . Been wanting to use my own API for this for a VERY long time.
