### ISSUE TITLE
Marker From Banner Json

### ISSUE THREAD

**Issue by murat716** [webbukkit/dynmap#3373]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Dynmap sample feature request description. This description would include as much and as little detail necessary for us to understand the feature in its entirety.*
I want to create marker from banners. There is a have option for this?

* **Additional context:** *Please add any additional information you feel will help us understand the feature*

**Comment by FedUpWith-Tech** [comment]
Duplicate of #2266
