### ISSUE TITLE
Mushroom biomes fully green with TerraNetworkOrgTopo shader

### ISSUE THREAD

**Issue by IamMusavaRibica** [webbukkit/dynmap#3374]
I'm using TerraNetworkOrgTopo shader with nightandday-smooth lighting.
This is the result:
![image](https://user-images.githubusercontent.com/65848142/119468627-ed358480-bd46-11eb-931c-fadada4bdcbc.png)

The green islands are mushroom islands/biomes. They aren't supposed to be green, right?
Is it possible to change/fix this behaviour? Shaders settings only allows colors per height (as i understood it), nothing related to biomes

Note that it doesnt happen if mushroom biome is on land, only on islands

**Comment by generrosity** [comment]
Just for my own curiosity - green here represents a height not a biome, right?  Why wouldn't the island be green? Or is it too 'flat'?

**Comment by IamMusavaRibica** [comment]
They are not flat. The height changes at some point, and there are also
trees

**Comment by generrosity** [comment]
There have been some shader updates in recent updates - this still a problem?

**Comment by IamMusavaRibica** [comment]
Unfortunately, cannot test it as I'm not running a server anymore

**Comment by generrosity** [comment]
Closing off for now as I don't think we have someone to replicate, and I suspect it might have been fixed in the recent colours update in dynmap. If someone encounters this, please do reference the URL in your new ticket 👍
