### ISSUE TITLE
Players do not show up on the map.

### ISSUE THREAD

**Issue by PLESOP** [webbukkit/dynmap#3375]
**Issue Description:** *Hi, don't you know why I don't see players' heads on Dynmap? All players are in the overworld. And their heads are not visible on the map, check screenshot: https://i.imgur.com/Yt3KiRJ.png*

* **Dynmap Version:** *3.1-457*
* **Server Version:** *Tuinity 1.16.5 - f0e91a4*
* **Pastebin of Configuration.txt:** *https://pastebin.com/nS8aWX4U*
* **Server Host (if applicable):** *VPS hosting*
* **Pastebin of crashlogs or other relevant logs:** *No crash log*
* **Other Relevant Data/Screenshots:** *https://i.imgur.com/Yt3KiRJ.png*
* **Steps to Replicate:** *I didn't do anything.*

**Comment by PlesCZ** [comment]
Plugins (26): AdvancedMention*, AuthMe, ChatSentinel, Chunky, CoordinatesHud, CoreProtect, dynmap*, EasyWhitelist*, EntityDetection, Essentials, EssentialsChat, EssentialsSpawn, Gatekeeper*, Harbor, LuckPerms, MOTD, NametagEdit*, PL-Hide, PlaceholderAPI, PlayTime*, SkinsRestorer, StofCreeperDetector*, SuperbVote, Vault, Votifier, WorldBorder

**Comment by PLESOP** [comment]
SOLVED
