### ISSUE TITLE
Map rendering question

### ISSUE THREAD

**Issue by Toomas633** [webbukkit/dynmap#3376]
Description: Can i make dynmap render growables like wheat on fields and objects like torches or lanterns?
Also can animals be rendered in?
Dynmap version: latest
Server version: 1.16.5
Host: Selfhosted

**Comment by FedUpWith-Tech** [comment]
Dynmap can render growables and torches, it cannot render animals

**Comment by Toomas633** [comment]
> Dynmap can render growables and torches, it cannot render animals

And how would one enable that, cause currently it only renders blocks for me.
