### ISSUE TITLE
How to change /dynmap webregister  link

### ISSUE THREAD

**Issue by nikawiwi** [webbukkit/dynmap#3378]
Hi, I currently have my dynmap on a URL, and I would like to know how to change it so that when a player does /dynmap webregister the response gives them the URL, rather than HTTP://login.html.
Thank you!

**Comment by FedUpWith-Tech** [comment]
Closing this due to age, please reply if this still is relevant

**Comment by pnarf** [comment]
Is there an answer to OP's question though?
