### ISSUE TITLE
Dynmap chat crash. dynmap v3.1-beta7-449

### ISSUE THREAD

**Issue by Coldene** [webbukkit/dynmap#3385]
Hiya <3

Recently after weeks of NP Dynmap we get randomly once or twice a day Dynmap chat crashing with the below short console output each time. This is the console error. A null pointer exception. https://pastebin.com/qU9rfDsf
It "sometimes" still shows chat in server after the crash but never on the map site. A  restart always fixes it.
Very rarely after same crash the entire maps online disappear leaving just a black screen where the 
console error also states cannot find perspectives etc. Never had this kind of bug in many many 
years of employing Dynmap as server cake. It is cake! Yummy.

We use Paper 1.16.5 very latest version.

Our behemoth plugins list shows ancient abandoned Dynmap addon DynmapPreciousStones. 
This addon now works fine after I poked about in both Dynmap and DynmapPreciousStones 
with Class Editor (Soureceforge.net) top update DynmapPreciousStones's internal class paths 
so it now draws fields on the Dynmap. As seen on this dev server. (http://51.38.212.215:8777/).

Plugins (64): AntiDisconnectSpam, ArmorStandEditor, AutoLapiz*, CaneBully*, ChargedCreeper*, ChatInjector*, ChestShop, ClearLag, ColoredSigns*, CoralStay, CoreProtect, CrazyAuctions, DiceFurniture, dynmap*, Dynmap-PreciousStones*, DynmapEssentials, EditableSign, EffectLib*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn, ExoticGarden, FurnitureLib, GAListener*, GroupManager, HoloDropsX, HolographicDisplays, HolographicExtension, ItemInChatFree, Jobs, LandValue*, LibHatesMods, LibsDisguises, LightAPI, LiteXpansion, LWC, MagicSpells, mcMMO, MobCapturer, Multiverse-Core, Multiverse-Inventories, MyPet, MyPreciousStone*, PlaceholderAPI, PlayerVaults, PreciousStones, ProtectionLib, ProtocolLib, PvPToggle, RandomTeleport*, Rankup, RecipeManager, SignLoggerPlus*, SilkSpawners, SimpleNPC, Slimefun, Towny, Vault, Votifier, WorldBorder, WorldEdit, WorldGuard, Zenchantments

If you have any idea what is causing this at our end or have any plans to address that issue at your end 
comments would be greatly appreciated. Thank you very much for reading this.

**Comment by Coldene** [comment]
Forgot to mention we use Bisect Hosting as our host. They have never had any issues or grumps 
with us using Dynmap, huge high res maps etc. They are perfectly fine with us using that.

**Comment by mikeprimm** [comment]
Based on:

at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2132) ~[patched_1.16.5.jar:git-Paper-775]
    at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:207) ~[patched_1.16.5.jar:git-Paper-775]
    at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:183) ~[patched_1.16.5.jar:git-Paper-775]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.broadcast(CraftServer.java:1592) ~[patched_1.16.5.jar:git-Paper-775]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.broadcast(CraftServer.java:1564) ~[patched_1.16.5.jar:git-Paper-775]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.broadcastMessage(CraftServer.java:600) ~[patched_1.16.5.jar:git-Paper-775]
    at org.dynmap.bukkit.DynmapPlugin$BukkitServer.broadcastMessage(DynmapPlugin.java:392) ~[?:?]

This frankly looks like an 'Audience' code error - the exception is in their handling of the call made to Paper that they are hooking.  Googling leads me to https://github.com/KyoriPowered/adventure (which is some server side user interface mod - maybe used by hoster?)
