### ISSUE TITLE
Full render issues

### ISSUE THREAD

**Issue by OllieJW** [webbukkit/dynmap#3386]
I have full rendered my map but it hasn't loaded on the web UI? Anyone know why?
![image](https://user-images.githubusercontent.com/71931263/121752020-32a7cf00-cb07-11eb-9dd3-2fbaf21904d5.png)
![image](https://user-images.githubusercontent.com/71931263/121752031-389db000-cb07-11eb-9497-74ead44d1136.png)

**Comment by LillySchramm** [comment]
Did you explore the not shown chunks? Fullrender only renders already generated terrain.
