### ISSUE TITLE
Colorschemes seem cannot work in a proper way

### ISSUE THREAD

**Issue by OLdGoogol** [webbukkit/dynmap#3393]
Thank for sparing some time with this. I am trying to switch the color scheme of my map(of main world). However, the integrated color schemes(like"Ovocean","flame")seem cannot work in a proper way.
I just edit the world.txt like this. (Nothing else is changed),
I have not changed the config of shader.txt.
![worldtxt](https://user-images.githubusercontent.com/77193053/122567139-efa3a980-d07a-11eb-9eb0-b3d4c85b6dc2.jpg)

Since I ve previewed the documents about this before, the outcome might be like this:
![shown](https://user-images.githubusercontent.com/77193053/122567136-ef0b1300-d07a-11eb-8301-816be2085088.jpg)

But it came out to be this:
![expected](https://user-images.githubusercontent.com/77193053/122567128-ed414f80-d07a-11eb-80cd-b7fc54223fcd.jpg)

the water turns green and the land turns black!

I am feeling very upset about this, it seems that I have to use the default colorscheme instead.
I have been asking for solutions these days, and try some of them. But they didnt help. Did I got something wrong? or there is some another settings need to adjust?

**Comment by generrosity** [comment]
The black likely comes from lighting:shadows - if you use lighting:default the colours pop out again

It does look like the colour scheme renders weirdly - from this screenshot it looks like its rendering nbt data?? (Tree leaves further from logs have smoothly darker colours) and grass its shown without texture.
![image](https://user-images.githubusercontent.com/12838061/144700627-5bb24a99-4f8b-48f6-9623-852195cb604d.png)

![image](https://user-images.githubusercontent.com/12838061/144700669-821f6cbc-166a-4f50-bf45-c2a61db381b4.png)

this is from a 1.18 preview, just checking variety of versions of things

**Comment by mikeprimm** [comment]
Should be fixed in current release

**Comment by generrosity** [comment]
Looking good in our sample server 👍🏽 thanks!
