### ISSUE TITLE
Depreciated com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by PlayingWithPi** [webbukkit/dynmap#3397]
**Issue Description:**
```yaml
20.06 20:27:52 [Server] INFO [dynmap] Opening MySQL database mysql.apexhosting.gdn:3306/apexMC741534 as map store
20.06 20:27:52 [Server] WARN Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
```
Using old depreciated driver for MySQL integration, needs to be updated.

* **Dynmap Version:** *v3.1-457**
* **Server Version:** *paper 1.16.5 build 778*
* **Pastebin of Configuration.txt:** *https://pastebin.com/duTGWLRW*
* **Server Host (if applicable):** *Apex Minecraft Hosting*
* **Pastebin of crashlogs or other relevant logs:** [check code snippet above]
* **Steps to Replicate:** *Use MySQL for a storage.*

 [ x ] *I have looked at all other issues and this is not a duplicate*  
 [ x ] *I have been able to replicate this*

**Comment by mikeprimm-triva** [comment]
Loading of the driver via that class is deprecated, but supported.  The driver is not.  We can make the change, but understand that there is zero functional consquence.

**Comment by patrix87** [comment]
Thanks for the clarification, I was here for that too.

**Comment by generrosity** [comment]
@PlayingWithPi @patrix87 - ok to close?
