### ISSUE TITLE
Dynmap crash - skins restorer api.

### ISSUE THREAD

**Issue by SzczurekYT** [webbukkit/dynmap#3400]
Issue Description: On server startup dynmap crashes. It has something to do with skins restorer API.

Dynmap Version: v3.2-beta-1-470
Skins Restorer Version: 14.1.0
Server Version: paper 1.16.5 #778
Pastebin of Configuration.txt: https://pastebin.com/6j6adJcL
Server Host (if applicable): On oracle cloud vm
Pastebin of crashlogs or other relevant logs:  Error that dynmap threw on startup: https://pastebin.com/uGvMVXtJ
Steps to Replicate: Run paper 1.16.5 778 server with skins restorer plugin v14.1.0 and dynmap v3.2-beta-1-470 and bug should occur.

**Comment by kdkasad** [comment]
This has been fixed in #3396 and should be part of the next release.
