### ISSUE TITLE
How do I remove the ugly glow from under a logo?

### ISSUE THREAD

**Issue by TomLewis** [webbukkit/dynmap#3402]
I made a 50x50px Logo to show on the dynmap but I cant see any setting to disable the horrible glow under it. Its also not aligned with the coords showing up. https://imgur.com/a/IYIwXtD

**Comment by TomLewis** [comment]
I figures out the css to remove but on reboot it overwrites my changes!

**Comment by tackleza** [comment]
Maybe you have to use "external web server" (disable-webserver: true) then use PHP as web server instead of internal server
since dynmap check "web assets" every time when start up

**Comment by TomLewis** [comment]
I do use the external web server.
I do use PHP.

It still overwrites my files.

**Comment by tackleza** [comment]
Sorry for the slow reply. External web server mean outside of plugins/dynmap/web folder right?
You have to copy that "web" folder to somewhere else
And then use MySQL as storage. That a dirty hack but work
