### ISSUE TITLE
dynmap "disabled"?

### ISSUE THREAD

**Issue by FarmerMisShelley** [webbukkit/dynmap#3403]
Dynmap Version: V3.1
Server Version: Paper 1.17
Pastebin of Configuration.txt: [Configuration.txt](https://pastebin.com/0B6vWYpx)
Server Host (if applicable): PebbleHost
Pastebin of crashlogs or other relevant logs: LOGS (had to use hastebin cause apparently my logs were offensive... somehow...) [latest.logs](https://hastebin.com/soqayefome.sql)
Other Relevant Data: Just trying to get the port to work so the link will work...
Steps to Replicate: I don't know. lol. I couldn't recreate it if I tried.

**Comment by rautamiekka** [comment]
Config and logs missing.

**Comment by FarmerMisShelley** [comment]
> Config and logs missing.

fixed. I didn't realize that if I hyperlinked em here I needed to add something so they would show up

**Comment by mikeprimm** [comment]
v1.17 requires v3.2-beta-1 (or later)

**Comment by FarmerMisShelley** [comment]
> v1.17 requires v3.2-beta-1 (or later)

I miswrote the version. we are running that version
