### ISSUE TITLE
Dynmap can not find biomes!

### ISSUE THREAD

**Issue by ErythroCraft** [webbukkit/dynmap#3407]
> template is **bold**
> sample data is *italicized*

**Issue Description:** 
*On start my 1.17-spigot-server with the plugin v3.1-beta7-449 the console say [can not find Biom xyz].
Please read pastbin*

* **Dynmap Version:** *v3.1-beta7-449*
* **Server Version:** *spigot 1.17 build*
* **Pastebin of Configuration.txt:** *https://pastebin.com/eUgGrqkg*
* **Server Host (if applicable):** *localhost*
* **Steps to Replicate:** *on stating server*

 [0] *I have looked at all other issues and this is not a duplicate*  
 [1] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
1.17 requires at least 3.2-beta-1
