### ISSUE TITLE
Dynmap + NGINX

### ISSUE THREAD

**Issue by Aquamonk** [webbukkit/dynmap#3409]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Hi, great plugin, I have made a custom domain for the dynmap using nginx. Although it enters, the webpage doesnt show the map, as you can see in the link. They say I need to change something in configuration.txt but I dont know what. Could you help me? Thanks, greetings.*

* **Dynmap Version:** *3.2 beta 1*
* **Server Version:** *Paper 1.16.5 652*
* **Pastebin of Configuration.txt:** *https://pastebin.com/hnsXxvnp*
* **Server Host (if applicable):** *Dedicated Server*
* **Pastebin of crashlogs or other relevant logs:** *https://imgur.com/i531kdr*
* **Other Relevant Data/Screenshots:** **
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by ExerciseBook** [comment]
maybe you can try to use nginx upstream. proxy some url to dynmap java.

**Comment by Aquamonk** [comment]
Cool! Thanks!
