### ISSUE TITLE
Map Lines

### ISSUE THREAD

**Issue by Aquamonk** [webbukkit/dynmap#3410]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Hi again, great plugin!, 2 straight black lines have appear in my map, its generating yet but the lines are there, near the spawn zone. When it finishes generating... what would be the commands that will fix it? update or fullrender(again)? Thanks, regards.*

* **Dynmap Version:** *3.2 beta 1*
* **Server Version:** *Paper 1.16.5 652*
* **Pastebin of Configuration.txt:** *I cant show now cause Im fixing the nginx thing*
* **Server Host (if applicable):** *Dedicated Server*
* **Pastebin of crashlogs or other relevant logs:** *none*
* **Other Relevant Data/Screenshots:** **
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by Tsoccerguy3** [comment]
This has been asked before . It is data corruption or lighting errors.
Causes could be improper startup or shutdown , region files in old format , chunks open by another plugin. Try using the light cleaner plugin . Go to the area /dynmap updaterender or radiusrender.

**Comment by Aquamonk** [comment]
Cool! Thanks!
