### ISSUE TITLE
[Feature Request] Layer with chunk borders and Region borders

### ISSUE THREAD

**Issue by Zorock666** [webbukkit/dynmap#3413]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Basically, I think it would help helpful to add a "layer option" that allows people to see where chunk borders are (and region borders, if zoomed out appropriately), just like there are "markers" "players" and "worldborder" layers. This would mostly just be a visual aid, but could possible help admins/players too with administrative stuff.*

**Comment by FedUpWith-Tech** [comment]
My bad. Can't read.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
