### ISSUE TITLE
Web to server chat not coming through in-game on 1.17 beta builds

### ISSUE THREAD

**Issue by kittygaming99** [webbukkit/dynmap#3414]
**Issue Description:** The web interface for dynmap successfully logs messages which the user sends through the chatbox. However, while these messages successfully parse into DiscordSRV and appear in the console; none of the messages show up in-game for the user.

- **Dynmap Version:** v3.2-beta-1-470 (MC: 1.17)
- **Server Version:** Paper version git-Paper-65 (MC: 1.17)
- **Pastebin of Configuration.txt:** https://pastebin.com/jA0etscR
- **Server Host (if applicable):** STIPE Servers Australia (inapplicable)
- **Pastebin of plugins and their versions:** https://pastebin.com/yBc2YB53
- **Steps to Replicate:** Run dynmap with or without any other plugins on the specified Paper version (have not tested other server clients). Make sure web chat is enabled as per the configuration file above. Note messages from users on the web will parse in console, but not appear in game.

 [✅] *I have looked at all other issues and this is not a duplicate*  
 [✅] *I have been able to replicate this*

I'd appreciate any help with this.

**Comment by stormboomer** [comment]
I'm unable to reproduce this with default configuration for:
Paper: version git-Paper-226 (MC: 1.17.1)
Dynmap: v3.2-beta-3-514

Also it seems that in your attached config you have allowwebchat set to false. Can you verify if this is still an issue?
