### ISSUE TITLE
1.17 ore textures not being hidden despite 'hide-ores' option being enabled

### ISSUE THREAD

**Issue by kittygaming99** [webbukkit/dynmap#3415]
**Issue Description:** I wanted to notify you all that the 1.17 ore textures (deepslate) do not get hidden when the 'hide-ores' feature is enabled. I thought you all ought to know this. I will provide you with a link to my dynmap as well as an image of the issue.

[Click here to view my dynmap...](http://119.252.189.26:9049/?worldname=world1&mapname=surface&zoom=6&x=-1375&y=64&z=5200)

[Image of issue](https://preview.redd.it/hys5wow407871.png?width=2026&format=png&auto=webp&s=6184feec5d413bc9b59f2a09d59323df07152695)

- **Dynmap Version:** v3.2-beta-1-470 (MC: 1.17)
- **Server Version:** Paper version git-Paper-65 (MC: 1.17)
- **Pastebin of Configuration.txt:** https://pastebin.com/jA0etscR
- **Server Host (if applicable):** STIPE Servers Australia (inapplicable)
- **Pastebin of plugins and their versions:** https://pastebin.com/yBc2YB53
- **Steps to Replicate:** Render surface map of any world with the hide-ores feature enabled. A possible fix to be implemented for the time being is the manual implementation of each ore; dictating that the textures be replaced by deep slate.

 [✅] *I have looked at all other issues and this is not a duplicate*  
 [✅] *I have been able to replicate this*

Looking forward to this getting updated in future versions.

This was taken from [Reddit](https://www.reddit.com/r/Dynmap/comments/oa6lp9/hide_ores_feature_not_obscuring_117_ore_textures/) and posted here as per the suggestion of Schmensch-.

**Comment by thefeli73** [comment]
Not only deepslate ores but also regular Copper. Same with geodes, although those might be difficult to hide since they are sort of structures

**Comment by mikeprimm** [comment]
FIx added to 3.2 code - will be in next release

**Comment by generrosity** [comment]
@kittygaming99 - fixed in 3.2+ update? Can reopen if required :)
