### ISSUE TITLE
1.17 The official terrain data package cannot be rendered normally 

### ISSUE THREAD

**Issue by YinNue** [webbukkit/dynmap#3419]
When I use the official terrain data package [CavesAndCliffsPreview.zip] under 1.17, When I used the 1.17 official terrain data package to render the world, the rendering could not be performed normally. I hope that a solution can be given, or I can update methods such as setting the rendering world height by myself, thank you 
[CavesAndCliffsPreview.zip](https://github.com/webbukkit/dynmap/files/6759678/CavesAndCliffsPreview.zip)

**Comment by mikeprimm-triva** [comment]
This is a tech preview that Mojang isn't going to support for upgrades to 1.18 - if Mojang doesn't consider it supported, we sure don't either... https://feedback.minecraft.net/hc/en-us/articles/4402614709389-Caves-Cliffs-Prototype-Data-Pack-for-Minecraft-Java-Edition
