### ISSUE TITLE
Migrating config file from bukkit to fabric throws exceptions

### ISSUE THREAD

**Issue by Bond-009** [webbukkit/dynmap#3420]
**Issue Description:** Migrating config file from bukkit to fabric throws exceptions on player join

* **Dynmap Version:** master
* **Server Version:** fabric 1.17
* **Pastebin of Configuration.txt:** https://hastebin.com/tiporahode.yaml
* **Pastebin of crashlogs or other relevant logs:** https://hastebin.com/buqofivelo.css
* **Steps to Replicate:** Copy bukkit config to fabric server

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by inpercima** [comment]
Possible same issue here in a different way. On every command (like /dynmap fullrender) in the game I got following error message: "Während der Ausführung dieses Befehls ist ein Fehler aufgetreten" with Details:

```
Cannot invoke

org.dynmap.permissions.permissionsHandler.hasPermission(String, String) because "ph" is null
```

**Comment by mikeprimm** [comment]
They aren't compatible - things like render triggers are platform specific.

**Comment by Bond-009** [comment]
Sure, but a nullref isn't the way you should find out about that

**Comment by mikeprimm** [comment]
Feel free to kick in a PR with all the thorough foolproofing you'd like to see in the config file loading and processing.
