### ISSUE TITLE
Return 304 to correct 'If-Modified-Since'

### ISSUE THREAD

**Issue by RuofengX** [webbukkit/dynmap#3423]
**Feature Description:** *Dynmap could return 304 code to those request with correct 'If-Modified-Since' header, which could boost much performance.*

* **Additional context:** *This feature comes from the client-side cache and CDN.  CDN has a feature that it could refresh all the modified resources, such as tiles with players building, but not touch those tiles in the wild. This feature is so awesome that it could make the map loading faster meanwhile keep the necessary tiles fresh. CDN also need server-side to response a 304 when using 'If-Modified-Since' header.*

**Comment by FedUpWith-Tech** [comment]
We likely won't implement these changes. You are better off implementing them yourself or hiring a dev to make it for you specifically.
