### ISSUE TITLE
Error spams console

### ISSUE THREAD

**Issue by MinecollYT** [webbukkit/dynmap#3424]
**Issue Description:** this error spams the console

* **Dynmap Version:** v3.2-beta-2-483
* **Server Version:** spigot 1.17.1
* **Pastebin of Configuration.txt:** https://pastebin.com/bdkLqhJ3
* **Server Host (if applicable):** selfhost
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/VE9Lc4Az
* **Other Relevant Data/Screenshots:** -
* **Steps to Replicate:** unknown

 [x] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by MinecollYT** [comment]
removing `blockphysics` from `render-triggers:` fixed it

**Comment by MinecollYT** [comment]
now this error spams the console: https://pastebin.com/NspSxxfg

**Comment by wioxjk** [comment]
Can confirm, and it has been reported as an issue here before.

https://github.com/webbukkit/dynmap/issues/3418

**Comment by MinecollYT** [comment]
oh, seems like a duplicate - sorry.
