### ISSUE TITLE
Rails doesn't show as expected on the 2D and 3D render

### ISSUE THREAD

**Issue by MaxBaktBrood** [webbukkit/dynmap#3429]
> template is **bold**
> sample data is *italicized*

**Issue Description:** 
All the textures of the rails are wrong
![afbeelding](https://user-images.githubusercontent.com/47690551/125998712-54d61fe5-6f99-4abd-9646-5128dfc7db3a.png)

* **Dynmap Version:** dynmap 3.2 beta 2
* **Server Version:** paper 1.17(.1)
* **Steps to Replicate:** Place rail
 [ x] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by Cybornut** [comment]
Just like to pitch in support of this, and add that rails faces (goes) east/west only in the SURFACE render (as seen on the top of the slope here).
![2021-08-08 (3)](https://user-images.githubusercontent.com/51033431/128664275-8f40ad75-e34a-4c42-b827-65d414cd063b.png)

**Comment by GEARED321** [comment]
I got same problem. And unpowered rails are missed their texture in map rendering.

- **Dynmap Version** dynmap v3.2-beta-2-483
- **Server Version** Paper-170 (1.17.1)

**In-game screenshot**
![2021-08-10_19 38 48](https://user-images.githubusercontent.com/88715355/128853949-5bb54b6e-b157-41b2-b1b3-4e25dce476d3.png)

**Dynmap Screen shot**
![image](https://user-images.githubusercontent.com/88715355/128853631-4769e07b-01ca-4c06-82b9-bb4f438cf36a.png)

**Comment by kqfflo** [comment]
I can also confirm this issue. I just compiled the latest snapshot, but looking at the changelog I cannot expect this to be fixed. Am I right? I own a huge map (>30GB) where a fullrender takes some hours.

**Comment by mc680x0** [comment]
I'd like to confirm this issue, and additionally point out that diagonal rails do not show up on the map in any view; please refer to the screenshots attached 

Server: PaperMC 1.17.1 
Dynmap: core=3.2-beta-2-483, plugin=3.2-beta-2-483

![image](https://user-images.githubusercontent.com/1725903/131279620-50d4a7db-5921-44a7-8082-dfeb6ad1b4b8.png)
![2021-08-30_10 29 49](https://user-images.githubusercontent.com/1725903/131279647-3cfb5928-845c-4c2a-b6a0-ac2a5b559e80.png)

**Comment by generrosity** [comment]
@MaxBaktBrood  @mc680x0 @GEARED321 @kqfflo - specifically for rails, have you tried the latest version? I believe it has been fixed there.

**Comment by kqfflo** [comment]
Will try with the latest version. Thanks a lot for updating me on this.
