### ISSUE TITLE
dynmap v3.2-beta-2-483  ```error: DynmapBlockState updated after arrays generated```

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#3430]
> template is **bold**
> sample data is *italicized*

**Issue Description:** 
After running the bucket, I connected to /localhost (port:8123), but **no response. (or Refuse to respond)**
So I tried **reloading** the plugin and got the bellow error.
```
[12:20:00 WARN]: Error: DynmapBlockState updated after arrays generated
[12:20:00 WARN]: java.lang.Exception: Stack trace
```

* **Dynmap Version:** dynmap v3.2-beta-2-483 
* **Server Version:** 
* [12:22:15 INFO]: Checking version, please wait...
[12:22:16 INFO]: This server is running Purpur version git-Purpur-1169 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 112 version(s) behind
Previous version: git-Purpur-1056 (MC: 1.16.5)
* **Pastebin of Configuration.txt:** Not edited (original)
* **Server Host (if applicable):** Localhsot
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/SYmL68dv 
* **Other Relevant Data/Screenshots:** 
* **Steps to Replicate:** 

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
`/dynmap reload` is not a supported command anymore and will cause this issue. Please avoid that command for now
