### ISSUE TITLE
List of markers on the map

### ISSUE THREAD

**Issue by omega9380** [webbukkit/dynmap#3433]
**Feature Description:** Would it be possible to add a listing of all the current map markers?  Perhaps in the left hand flyout or it's own?  It would be a nice feature to see all the markers in one place, a quick click to jump to them.  Would make navigation easier for bigger worlds.

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.

**Comment by HandyHat** [comment]
Apparently this already exists - see: https://www.reddit.com/r/Dynmap/comments/n7lxsg/jump_to_marker/
