### ISSUE TITLE
Player tracking on the map. Automatically pan the map to follow a player exploring.

### ISSUE THREAD

**Issue by level42ca** [webbukkit/dynmap#3435]
**Feature Description:** 
My feature request is rather simple to explain. I think it would be ideal to have a list of players (or simply the ability to select a player on the map), and have Dynmap automatically center the map at all times to the selected player.

This would be most useful during long exploration sessions travelling 10's or thousands of blocks, and not having to stop every 5 minutes to re-center the map to see what is coming up. Ideally, the player should always remain center screen, and the map below should automatically pan around as the player moves.

I hope this makes sense.

Either way, thank you again for Dynmap, still my all time favourite plugin for Minecraft.

**Comment by Pingger** [comment]
This feature already exists. Click the portrait (in the playerlist) instead of the playername in the playerlist. (It can be disabled in the config)

**Comment by level42ca** [comment]
> This feature already exists. Click the portrait (in the playerlist) instead of the playername in the playerlist. (It can be disabled in the config)

I'm ashamed that after all these years using Dynmap that I was not aware of this feature. Thank you for sharing this with me.
