### ISSUE TITLE
dynmap is not rendering correctly.

### ISSUE THREAD

**Issue by SchattenWolf2008** [webbukkit/dynmap#3437]
I installed dynmap on my new 1.16.5 Spigot Server, but the map does not work right.
The map is an earth map that i downloaded online,
Nether does work fine, i didnt test the end.
screenshot: [https://prnt.sc/1e9rudb](url)
https://prnt.sc/1e9rudb

**Comment by SchattenWolf2008** [comment]
![Screenshot_18](https://user-images.githubusercontent.com/31274402/126602076-b835fb73-7dd0-4639-ab7d-548d97c45d04.png)

**Comment by level42ca** [comment]
My suggestion:

Stop your server

In /plugins/dynmap, delete the "web" folder. *This would delete any existing map data that you have.

Once deleted, relaunch your server.

Once server is running, run a fresh "/dynmap fullrender"

Wait for render to complete, check map.

**Comment by FedUpWith-Tech** [comment]
The EarthMC map has many known issues with Dynmap such as, incomplete render, only rendering where players have visited, or not rendering leaves and other foliage.
This is a result of how the map was made and is not an issue with Dynmap, luckily there is a fix.

1. Download the WorldBorder plugin: [WorldBorder](https://www.spigotmc.org/resources/worldborder.60905/)
2. Pause Dynmap: `/dynmap pause all` 
3. Run worldborder with the force flag: `/wb [worldname] fill [freq] [pad] [force]` 
- `[worldname]` is the name of your world folder
- `[freq]` is how many chunks a second are generated, 20 is the default. WARNING: setting this too high will cause server lag
- `[pad]` how many chunks beyond the border to generate, this makes sure that if a player visits the border, all chunks are already generated.  The default is 208, I recommend setting this to 0 for EarthMC
- `[force]` This must be set to true
4. Wait for worldborder to finish
5. Unpause Dynmap `/dynmap pause none`, you may have to restart the fullrender using `/dynmap fullrender [worldname]`

**Comment by FedUpWith-Tech** [comment]
Closing due to age, please follow steps listed above if issue still persists
