### ISSUE TITLE
Support Datapack water and grass colors

### ISSUE THREAD

**Issue by galacticwarrior9** [webbukkit/dynmap#3438]
**Issue Description:**

Dynmap does not support water and grass colors defined by datapacks, even if they are identical to vanilla values. 

**(!) Datapack with which the screenshots below were taken (1.17.1) - [biomes.zip](https://github.com/webbukkit/dynmap/files/6871605/biomes.zip)**

The "vanilla values" I will reference are taken from the [vanilla worldgen datapack](https://github.com/slicedlime/examples). The datapack linked above is simply a modified version of this. No "new biomes", dimensions or anything of that sort, just colour modifications to existing ones.

Water in biomes will appear white. The image below is of a Warm Ocean biome where `water_color` is identical to the vanilla value; only `water_fog_color` has been modified. However, the issue persists even if both values are identical to their vanilla counterparts.] In the image below, not all of the biome was re-rendered after the datapack was added, which is why some parts of it look normal. 
![Screenshot](https://i.gyazo.com/467ca331e470309cf848d555da40543a.png)

Similarly, grass will appear green, regardless of its colour ingame or if it differs from its vanilla value.

Here's an example - a Desert biome:

![Screenshot](https://i.gyazo.com/d721af7c565bd7a43b5396fe53fd0532.png)

And here's the same area from ingame: 

![Screenshot](https://i.gyazo.com/9fd660bba412dd1ec3086364ba17b963.png)

* **Dynmap Version:** *Dynmap v3.2-beta-2*
* **Server Version:** Purpur Build 1287
* **Pastebin of Configuration.txt:** [Link](https://pastebin.com/AdsUkety)

- [x] *I have looked at all other issues and this is not a duplicate*  
- [x] *I have been able to replicate this*

**Comment by Robert-Kidder** [comment]
I have the same problem. I used the [Caves & Cliffs Prototype Data Pack](https://launcher.mojang.com/v1/objects/622bf0fd298e1e164ecd05d866045ed5941283cf/CavesAndCliffsPreview.zip) provided by mojang to create the world. When rendering through dynmap, the water in any biome will appear white, and the grass will turn green without exception.

This is the map I rendered using the Dynmap-3.2-SNAPSHOT-spigot plugin (The latest build version as of the current time):

![image](https://user-images.githubusercontent.com/61925945/128556406-954647a0-1d07-4297-ab0d-8688ec7c9902.png)

This is the original color of grass and water in those biomes: 

![image](https://user-images.githubusercontent.com/61925945/128557528-1b1312ec-9fd3-44ab-ba25-68aa3c8cb55b.png)

It seems that this is indeed a bug. This map rendering method has caused a lot of trouble to me. If it can be fixed in a future version, I will be very grateful.

**Comment by keplergray** [comment]
I'm having the same issue, with [this datapack](https://www.planetminecraft.com/data-pack/william-wythers-caves-and-cliffs-add-on-for-overhauled-overworld-1-17/). All biomes rendering in grayscale. I've found out, however, that the bug only occurs when I have Multiverse installed. If I disable multiverse, the biome coloration works properly and renders correctly. Anyone else getting the same result?

**Comment by the-najjar** [comment]
> I'm having the same issue, with [this datapack](https://www.planetminecraft.com/data-pack/william-wythers-caves-and-cliffs-add-on-for-overhauled-overworld-1-17/). All biomes rendering in grayscale. I've found out, however, that the bug only occurs when I have Multiverse installed. If I disable multiverse, the biome coloration works properly and renders correctly. Anyone else getting the same result?

yes, I'm using terralith datapack, with Dynmap v3.2-beta-3-514, paper 1.17.1 and multiverse installed also
my map: http://map.tatomc.com
datapack terralith: https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/

**Comment by nrbxyz** [comment]
Terralith's custom colours don't work for me either, I am on Dynmap v3.2 for Fabric.

**Comment by 9514854** [comment]
Currently experiencing this same issue using the Terralith datapack. I'm using the most recent version of Dynmap (v3.2.1) on Paper.

**Comment by KermMartian** [comment]
Experiencing this with a tall map (i.e., a datapack just modifying world height) on 1.17.1 using Dynmap v3.2.1 on Paper.

**Comment by mibby** [comment]
Would also like to see this supported. Hopefully it isn't too complicated and quick & easy to implement. Experiencing the same problem with custom colors not properly displaying on the map. Grass, water, and tree biome colors all not being used.

Paper dev 73 (Spigot 1.18.1)
dynmap 3.3-SNAPSHOT-578
Terralith v2.0.4

In-game
![link](https://i.imgur.com/Xy5sDXk.png)

Map render
![link2](https://i.imgur.com/DrTr5lA.png)

**Comment by generrosity** [comment]
I'm looking at locking the conversation on this one - additional screenshots and 'yes please' isn't helping. If you have new info (or offers to help) please hit us up in the Discord.

Note; this is different from configuring a rendering and texturepacks/ in Dynmap for rendering.

Unfortunately this is not trivial to impliment. At a guess, it might take someone figuring out why vanilla Minecraft is not providing the correct colour (or collect it better from the code side), or something similar to DynmapBlockScan to create models and recognize colours.

**Comment by FedUpWith-Tech** [comment]
Added to the megathread #3461
