### ISSUE TITLE
dynmap error could not render: world 'world' not defined in configuration

### ISSUE THREAD

**Issue by duckman111** [webbukkit/dynmap#3439]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *dynmap error could not render: world 'world' not defined in configuration how do I fix this.*

* **Additional context:** *i changed the world to a different world and did the same for the map, im running the server on 1.16.5 version 3.2 on a shockbyte host, this is how i canged the world: Defaultworld: Earth_1-2000, i also changed the file to mysql and jpg*

**Comment by generrosity** [comment]
Is that exactly what it is called in "/dmap worldlist", including capitalization?
