### ISSUE TITLE
Disappearing Players Issue

### ISSUE THREAD

**Issue by murat716** [webbukkit/dynmap#3445]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *I'm not using bungeecord or something. My players randomly dissapear on the dynmap.*

* **Dynmap Version:** *Dynmap v3.2-beta-2*
* **Server Version:** *tuinity-1.16.5 latest*
* **Pastebin of Configuration.txt:** *https://hastebin.com/nojurasifo.yaml*
* **Server Host (if applicable):** *Batıhost*
* **Pastebin of crashlogs or other relevant logs:** *No crash*
* **Other Relevant Data/Screenshots:** *https://ibb.co/BrrsqzM*
* **Steps to Replicate:** *Install Dynmap v3.2-beta-2 and wait for a while. As players join, a few will not appear on the map.*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by tackleza** [comment]
@Kovalski4 
Comment this line then it's work

#hideifundercover: 0
Please use this issue if this solved your problem

**Comment by murat716** [comment]
> @Kovalski4
> Comment this line then it's work
> 
> #hideifundercover: 0
> Please use this issue if this solved your problem

This option isn't completely disappears player. It's just make their name to gray and you can't learn where it is.

**Comment by FedUpWith-Tech** [comment]
Closing this due to age, please reply if this issue is still present, additionally, you can join our [Discord](https://discord.gg/52pqBpw) for faster support.

**Comment by Kovalski4** [comment]
This problem was caused by the siege war plugin. Anyone can fix this problem with turn off map_hiding feature.

**Comment by murat716** [comment]
This problem was caused by the siege war plugin. Anyone can fix this problem turn off map_hiding feature.
