### ISSUE TITLE
External webserver [Nginx]

### ISSUE THREAD

**Issue by DEPSTRCZ** [webbukkit/dynmap#3446]
When i run `nginx -t`
its gonna report this 
`nginx: [emerg] no port in upstream "php5-fpm-sock" in /etc/nginx/sites-enabled/dynmapa:18`
1.17.1 version

What do i have to do?

Code:

server {
    listen       80;
    server_name  mapa.example.online;
    root         /var/www/web/dynmapa/;

    index index.html;

    access_log /var/log/nginx/minecraft.example.com-access_log;
    error_log /var/log/nginx/minecraft.example.com-error_log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_index index.php;
        fastcgi_pass php5-fpm-sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
    }
}

**Comment by rlcurrall** [comment]
Hey @ItzDepstRT !

Could you give a bit more context on your current setup?

* Are you running this in docker containers?
* What version of PHP do you have installed?
* Do you have PHP-FPM installed?

If you are running everything on a physical server, I'd recommend reading through [this article](https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-on-ubuntu-20-04) (assuming you are using Ubuntu).

If you are using Docker I can share my setup with you, which might be helpful. I'm currently running the server using `docker-compose` on my home server.
