### ISSUE TITLE
Geyser Support for logging in

### ISSUE THREAD

**Issue by zentag** [webbukkit/dynmap#3449]
**Get support for bedrock players connecting via geyser:** 
*Currently there is no way to log into the website using geyser. If you do this, it will return invalid ID (which i assume to be UUID), so it would be nice if there was an alternative for using UUIDs to support bedrock players connecting to the server?*

* **Find geyser here:** *https://geysermc.org/ https://github.com/GeyserMC/Geyser*

**Comment by FedUpWith-Tech** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
