### ISSUE TITLE
Fatal Exception ArrayIndexOutOfBounds on getBlockType during startup/render of world

### ISSUE THREAD

**Issue by BrianvdHorst** [webbukkit/dynmap#3452]
**Issue Description:** 
Dynmap will only render 3 to 6 tiles on the world, not sure if the nether is complete, and the end only has the middle island rendered. I get an error during startup or when triggering a new full render and it doesn't render anymore after that.

**Dynmap Version:** Dynmap-3.2-SNAPSHOT-fabric-1.17.1
**Server Version:** Fabric 1.17.1
**Pastebin of Configuration.txt:** Have not changed anything.
**Server Host (if applicable):** Hetzner, Cloud VPS with Docker
**Pastebin of crashlogs or other relevant logs:** https://pastebin.com/Fe16uX4K
**Other Relevant Data/Screenshots:** Datapacks: AFK Display V1.1.0, Armor Statues v2.8.1, Cauldron Concrete V2.0.3, CavesAndCliffsPreview, Coordinates Hud v1.2.0, Custom Nether Portals v2.3.2, Double Shulke Shells v1.3.0, Durability Ping v1.1.0, More Mob Heads v2.9.1, Player Head Drops v1.1.0, Silence Mobs v1.1.0, Villager Workstation Highlights v1.1.0, Wandering Trades v1.5.0
**Steps to Replicate:** I loaded a fresh install of Dynmap on my server and the error was there on startup.

 [ X] *I have looked at all other issues and this is not a duplicate*  
 [X ] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
This is related to the CavesAndCliffsPreview - support was added for it, but I'm not sure if the build you are running did or did not have it.   Please try the latest SNAPSHOT - https://dynmap.us/builds/dynmap/Dynmap-3.2-SNAPSHOT-fabric-1.17.1.jar - also, include the output from '/dynmap version' command of the version tested

**Comment by generrosity** [comment]
Closing as answered - upgrade to newer version. Obviously with new releases, we will eventually soon post out new versions for 1.18 once they become availible - on Reddit and on the Discord.
