### ISSUE TITLE
Dedicated Webserver Issue

### ISSUE THREAD

**Issue by rustyshakelford2** [webbukkit/dynmap#3453]
**Issue Description:** I am having trouble getting dynmap to work on a standalone webserver using [this guide](https://github.com/webbukkit/dynmap/issues/2609). 

* **Dynmap Version:** 3.2-SNAPSHOT-493
* **Server Version:** Paper version git-Paper-161 (MC: 1.17.1)
* **Pastebin of Configuration.txt:** https://pastebin.com/ZNgpd7ZP  (Default settings apart from MySQL server settings and uncommenting the js updater)

nginx version: nginx/1.18.0 (Ubuntu)
PHP 7.4.16 
Linux vps-ac8f9ccb 5.11.0-25-generic

I am trying to set up a standalone webserver on an Ubuntu 21.04 VPS external to my self hosted Minecraft server for bandwidth reasons. The VPS houses the SQL database and webserver. Uploading to the VPS' SQL database via the dynmap plugin works great, but when I try to set up the standalone webserver is where I run into trouble. 

When I try to access the dynmap folder on the VPS I get the following error:
http://135.148.120.59/
Could not retrieve configuration: Error

My config.js is accessible.
http://135.148.120.59/standalone/config.js

I have confirmed PHP-FPM is working. 
http://135.148.120.59/info.php

I tried changing the @dbhost variable in /standalone/MySQL_config.php to localhost but that didn't help. I'm stumped. Any suggestions?

**Comment by rlcurrall** [comment]
Have you been able to verify that the credentials that are in the `standalone/MySQL_config.php` are able to connect you to the MySQL database?

I _looks_ like it would just be a connection issue with the database, but I could be wrong.

**Comment by rlcurrall** [comment]
The error appears to be coming from here: https://github.com/webbukkit/dynmap/blob/v3.0/DynmapCore/src/main/resources/extracted/web/standalone/MySQL_funcs.php#L30

So I would certainly say it is an issue connecting with the database.

**Comment by rustyshakelford2** [comment]
That was it! User error setting up the MySQL user for localhost access. THANK YOU!
