### ISSUE TITLE
[dynmap] Task #965589 for dynmap v3.2-beta-2-483  |  WARN

### ISSUE THREAD

**Issue by Skjolberg** [webbukkit/dynmap#3454]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *I had the previous version that worked perfectly but the skins were not updated in the web map, so I decided to try this latest version and it was solved but the other day I saw this error / warn in console, it does not appear very frequently so I do not know the degree risk by having this problem. I have also noticed that the claims on the web map are not updated. Sorry for my english.*

* **Dynmap Version:** *v3.2-beta-2*
* **Server Version:** *paper-1.16.5-782*
* **Pastebin of Configuration.txt:** *https://pastebin.com/jkBvwnRe*
* **Server Host (if applicable):** *https://dashflo.net/*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/heWauvtd*
* **Other Relevant Data/Screenshots:** *I have nothing to add, it is a warning that appears without further ado, I don't know why, I have the web map in /var/www/mapa.mydomain.net although it never gave me a problem.*
* **Steps to Replicate:**

 [x] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by Skjolberg** [comment]
Solution? Thanks.

**Comment by JurgenKuyper** [comment]
your pastebin is empty, we cannot help without the full log

**Comment by FedUpWith-Tech** [comment]
> your pastebin is empty, we cannot help without the full log

@JurgenKuyper no its not?

**Comment by Skjolberg** [comment]
> su pastebin está vacío, no podemos ayudar sin el registro completo

You're blind.

**Comment by FedUpWith-Tech** [comment]
What plugins do you have? I believe this issue is related to a dynmap addon unsafely removing a marker which is causing this exception

**Comment by Skjolberg** [comment]
> está relacionado con un complemento de dynmap que elimina de mane

Using dynmap and dynmap-griefprevention

**Comment by rautamiekka** [comment]
> > su pastebin está vacío, no podemos ayudar sin el registro completo
> 
> You're blind.

It's only a partial log, not the full one.

**Comment by FedUpWith-Tech** [comment]
Going to go ahead and close this. Its a minor error when griefprevention tries to update the map layers when dynmap is already updating the map error. Not an easy solution for this and since it doesn't cause any real issues it won't be fixed anytime soon.
