### ISSUE TITLE
Not all players visible 1.17.1

### ISSUE THREAD

**Issue by Rezanans-wow** [webbukkit/dynmap#3455]
**Issue Description:** *Sometimes player visible, but on dynmap cant be visible all players in time. Usually max. 2 players, so many players not visible on map (They not sneak, invisible potion, and other). Idk why on 1.16.5 working perfect*

* **Dynmap Version:** *v3.2-beta-2*
* **Server Version:** *Paper 1.17.1*
* **Pastebin of Configuration.txt:** *https://pastebin.com/raw/KyxNrbzC*
* **Server Host (if applicable):** *Pterohost(.com)*
* **Pastebin of crashlogs or other relevant logs:** *No one*
* **Other Relevant Data/Screenshots:** *
![изображение](https://user-images.githubusercontent.com/49691442/129012960-3eb2f3a9-d8a3-4a2a-b7a6-3b8714d57312.png)
*
* **Steps to Replicate:** *Just work with map (Zoom, swipe)*

**Comment by Jogell** [comment]
I have the same issue. I've found that it is only the case when the players DON'T have a Sky in contact.

**Comment by generrosity** [comment]
@Jogell sorry what do you mean "a sky in contact"? They are underground? Or something else?
