### ISSUE TITLE
[Proposal] Enable Github Discussions

### ISSUE THREAD

**Issue by rlcurrall** [webbukkit/dynmap#3456]
[Github Discussions](https://docs.github.com/en/discussions) is a great way to engage the community without it overwhelming the issues section. I've seen a number of OSS communities disable the issues tab completely and have the community interact, submit bug reports, request features through the discussions section (specifically [Alpine.js](https://github.com/alpinejs/alpine)).

I don't know if disabling the issues tab would be the best solution for this project, but I've noticed a number of issues being submitted, especially around setting up a standalone web server, that are unrelated to the project itself, and is mostly just people looking for support or ask questions. Those kinds of "issues" would be best served as discussions.

I'm submitting this as a _proposal_ because I personally have never used Github discussions on one of my own projects, and I'm relatively new to this codebase. The current method may work great, but just wanted to drum up some discussion about a potential alternative.

**Comment by FedUpWith-Tech** [comment]
I like this idea and have seen github discussions work well for some projects however I don't think they will work very well here. Most "support" type questions that aren't bug or code related are answered on the Discord and the github issue tracker isn't super maintained. Maybe @mikeprimm will feel different but I prefer the discord support setup rather than github discussions.

**Comment by rlcurrall** [comment]
I think that makes the most sense, keeping support centralized in discord since it is likely easier to triage and get community engagement.

I'll leave this open for further discussion if anyone else has differing opinions. Feel free to close 😄

**Comment by FedUpWith-Tech** [comment]
I'll close this but if anyone else has an opinion on the matter please continue discussing here and we will consider it as time goes

**Comment by Pulz-TCP** [comment]
@FedUpWith-Tech This is my opinion on the matter. Everyone who has had their issue referenced in the megathread will need to unsubscribe from their original issue and also clean their inbox. I received 45 by the time I unsubscribed.
https://i.imgur.com/F2k2bM3.mp4

**Comment by FedUpWith-Tech** [comment]
@Pulz-TCP I understand you are frustrated. 
My understanding of github notifications was that you only got notified of the specific mention unless you commented on the thread or were otherwise watching. Clearly that was wrong and I apologize.

**Comment by Pulz-TCP** [comment]
> @Pulz-TCP I understand you are frustrated.
> My understanding of github notifications was that you only got notified of the specific mention unless you commented on the thread or were otherwise watching. Clearly that was wrong and I apologize.

Apology accepted- things like this happen. I just wanted to make sure you were aware.
