### ISSUE TITLE
Water is gray (missing biome colors)

### ISSUE THREAD

**Issue by HenrikoMagnifico** [webbukkit/dynmap#3457]
**Issue Description:** The water is gray on the Dynmap after updating from Dynmap 3.1 to 3.2-beta2. There also doesn't seem to be any biome colors outside of the same default one.

* **Dynmap Version:** *Dynmap 3.2-beta2*
* **Server Version:** *PaperMC 1.17.1 build 195*
* **Pastebin of Configuration.txt:** https://pastebin.com/KEKpjL64
* **Server Host (if applicable):** *Local Host*
* **Pastebin of crashlogs or other relevant logs:** latest.log: https://pastebin.com/EJkADCzC
* **Other Relevant Data/Screenshots:** *No texture pack is being used. Only a few popular and recently updated plugins are being used. Removing all other plugins doesn't make a difference. The map was made in Alpha 1.2.6, but has been expanded until today and is now on 1.17.1 PaperMC build 195. The map displayed correctly using the previous version of Dynmap 3.1 on 1.16.5 and earlier.*

**Screenshot of the issue:**
![Skärmbild 2021-08-18 142536](https://user-images.githubusercontent.com/11783274/129897939-7e22788b-eb4d-4417-93e7-3969fecd8141.png)

* **Steps to Replicate:**
*I have not been able to replicate it outside of this particular world.* Maybe it's because the world was created so long ago? However that doesn't explain why it worked up until 1.16.5 on Dynmap 3.1 and stopped working only now on 3.2-beta2. Deleting the dynmap folder and doing a full render of the world again ends up with the same results.

**Comment by galacticwarrior9** [comment]
Are you using any datapack that modifies biomes? If so, this is the same issue as #3438

**Comment by HenrikoMagnifico** [comment]
> Are you using any datapack that modifies biomes? If so, this is the same issue as #3438

I'm using the 1.18 experimental world generation datapack, but that's it.

**Comment by FedUpWith-Tech** [comment]
The 1.18 datapack will cause this. The fix for #3438 will fix this so I will close as a duplicate for tracking purposes
