### ISSUE TITLE
Touch control doesn't work on Firefox & Microsoft Edge

### ISSUE THREAD

**Issue by database64128** [webbukkit/dynmap#3462]
**Issue Description:** Touch control doesn't work on Firefox & Microsoft Edge. Opened this because #1971 has been closed by @FedUpWith-Tech.

* **Dynmap Version:** *v3.1*
* **Server Version:** *forge 1.16 build 36.2.2*
* **Pastebin of Configuration.txt:** *Not relevant*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *Not relevant*
* **Other Relevant Data/Screenshots:** *Not relevant*
* **Steps to Replicate:** *Open dynmap with Firefox or Microsoft Edge on devices with a touchscreen.*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Thank you for resubmitting this 😄
