### ISSUE TITLE
Cannot vote in "Fature Request Megathread"

### ISSUE THREAD

**Issue by Schpammer** [webbukkit/dynmap#3463]
Hi! Just want to inform you, that the new "Feature Request Megathread" #3461 does not allow non-contributors to give a 👍 as intended. 

It's great to see that overview and found some nice requests 😄

**Comment by FedUpWith-Tech** [comment]
Had to lock it while I was still editing it, should be unlocked now

**Comment by Schpammer** [comment]
Yep, thanks!
