### ISSUE TITLE
Fabric missing some blocks

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#3465]
**Issue Description:** Missing 1.17 blocks, something that I'm sure you are already aware of.

* **Dynmap Version:** from Reddit - 3.2-SNAPSHOT-493
* **Server Version:** Fabric API 0.37.0+1.17
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Server Host (if applicable):** self hosting, containers
* **Pastebin of crashlogs or other relevant logs:** N/a
* **Other Relevant Data/Screenshots:** See below
* **Steps to Replicate:** 

 [✅] *I have looked at all other issues and this is not a duplicate*  
 [✅] *I have been able to replicate this*

Missing renderings, something that I'm sure you are already aware of and likely already working on.  Some blocks are not rendered, but some are not picking up orientation / other metadata.

* Cauldrons with levels of powdered snow (picture: hillside of caudrons with various levels of snow) and cauldrons of water
![image](https://user-images.githubusercontent.com/12838061/130344180-1fb9d431-bc97-42e4-b8c2-3a69008d3a08.png)
* lanterns
* beds of any colour
* one of the redstone blocks (not observers or droppers - 
* top surface of a single chest, and ender chest.
![image](https://user-images.githubusercontent.com/12838061/130344598-8408469b-a24f-4fb8-8a14-a7daa28b0e8a.png)
* orientation of rails (#3429), observers, droppers, switches (on wall etc), chorus fruit elbows.
* I think banners are displaying as side-of-white-wool. dragon head as like a creeper head?  
![image](https://user-images.githubusercontent.com/12838061/130344748-aa582998-af5c-4ec3-8d17-160ef73dc0b9.png)
![image](https://user-images.githubusercontent.com/12838061/130344768-78d60773-829f-46d5-b904-e13255ea8bb5.png)

^^^^^^

As always - absolutely blown away with your work with so much of things already working - small snippet from one of our technical players with dripstone and mechanisms, and as always its only a few tiny details that Im noticing. keep up the good work!
![image](https://user-images.githubusercontent.com/12838061/130344506-49e0d69b-526a-43bf-80c6-a058cee23522.png)

**Comment by mikeprimm** [comment]
Most of these should be fixed in v3.2.1 - let me know which are still missing

**Comment by generrosity** [comment]
I'm pretty sure I'm looking at our server in 3.2.1, and the heads and banners are unchanged. I think its also affecting in the 1.18 alpha version too
![image](https://user-images.githubusercontent.com/12838061/144158585-85c87782-5ba4-456b-9be3-822e8163934c.png)

**Comment by generrosity** [comment]
https://github.com/webbukkit/dynmap/issues/3346 dragon head renders as creeper

**Comment by FedUpWith-Tech** [comment]
Going to go ahead and close this in favor of all the unique texture error issues I'm opening since they don't seem to be fabric specific
