### ISSUE TITLE
Stuck on loggin web page with DNS redirection & Google Chrome | Opera

### ISSUE THREAD

**Issue by crizyx** [webbukkit/dynmap#3466]
**Issue Description:** *Hello, I use a DNS redirection and an iframe to show the Dynmap on my website but with Google Chrome I can't login me. This error exist since a long time (2019) with the arrival to the new rule SameSite.*

* **Dynmap Version:** *Dynmap-3.2-beta-2-spigot*
* **Server Version:** *paper-1.17.1-204.jar*
* **Pastebin of Configuration.txt:** *https://pastebin.com/ZKudcM6P*
* **Other Relevant Data/Screenshots:** *https://cdn.discordapp.com/attachments/752565120487391233/878914346724524103/unknown.png*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
There are better DNS solutions that a redirect that won't break login. If you want to make a PR feel free and we will review it but otherwise no fix is necessary

**Comment by crizyx** [comment]
What are these best solutions?

**Comment by FedUpWith-Tech** [comment]
A reverse proxy and a standard A record
