### ISSUE TITLE
Feature request: SVG tiles

### ISSUE THREAD

**Issue by JacobWasFramed** [webbukkit/dynmap#3470]
**Feature Description:** *Instead of continuing to render PNGs in multiple resolutions, take the calculated geometry and render SVG instead.*

* **Additional context:** *SVG would be quicker to render, as the math is already done, file size is smaller and quicker to write, SVG is infinitely scalable, not requiring multiple resolutions, again reducing render times. Smaller file sizes also means quicker load times on the client end and less bandwidth on the server end. Transforms are also possible with SVG allowing easier integration of helper plugins to highlight areas of interest or transform aspects of the map.*

**Comment by FedUpWith-Tech** [comment]
This would be super cool but is a bit outside of the scope of the changes being made right now. If you submit a PR for this we can consider it but for now I'll mark this as low priority and add it to the megathread #3470

**Comment by FedUpWith-Tech** [comment]
Listed in #3461
