### ISSUE TITLE
Add support for mod-related biomes/blocks

### ISSUE THREAD

**Issue by WorldTeacher** [webbukkit/dynmap#3471]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *I know that there is the DynmapBlockScan, but it crashes the server while booting (sell log) 
[crash-2021-08-24_13.19.01-server.txt](https://github.com/webbukkit/dynmap/files/7040369/crash-2021-08-24_13.19.01-server.txt)
I was wondering, if it would be possible to display the blocks created by mods, instead of just displaying a black area (as shown in the screenshot)
![grafik](https://user-images.githubusercontent.com/41587052/130646143-9b12ffd4-94b1-48a2-b07f-28e07cf73515.png)
instead the area should more like this:
![4,0](https://user-images.githubusercontent.com/41587052/130646532-a98121f4-3bbf-4c48-8780-d9a662788518.png)
(ignore the white parts, I haven't explored there yet)
it's a different part of the world, and the image is from journeymap, but I think having a mod-support would make the webmap look better
*
Edit: 
If Full mod-support is not possible, I think support for biome/worldgen-related mods like "Oh the Biomes You'll Go To" or 
"Biomes O' Plenty" would, at least, make the map feel more "complete"

**Comment by FedUpWith-Tech** [comment]
Despite the initial drive to merge the Dynmap mod and BlockScan in #2062 these will stay separate for compatibility. 

I know BlockScan hasn't been updated for 1.16+ but you can still use older version of textures.
Read more here: https://github.com/webbukkit/dynmap/wiki/FAQ#5-my-dynmap-doesnt-show-modded-blocks

Adding support for individual mods isn't going to happen as maintaining support for many plugins increases the scope of supporting this plugin beyond what the dev is currently able to do. For now, I am going to transfer this to the webbukkit/DynmapBlockScan repo as this issue belongs there.

**Comment by FedUpWith-Tech** [comment]
Nevermind, you already have an issue open in that repo for the same crash so I will close this one here
