### ISSUE TITLE
Dynmap shows "Error loading maptype" on startup

### ISSUE THREAD

**Issue by KeldorDE** [webbukkit/dynmap#3473]
**Issue Description:** *Dynmap shows "Error loading maptype" on server start. Please see the Pastebin below to see the full error stack. I've already deleted the whole dynmap Folder to start with a fresh data set but I'm seeing this error when I add my worlds to the worlds.txt configuration file.*

* **Dynmap Version:** *3.2-beta-3-514*
* **Server Version:** *Paper version git-Paper-209 (MC: 1.17.1)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/RsBrSgUg*
* **Pastebin of worlds.txt:** *https://pastebin.com/BCJTZvsi*
* **Server Host (if applicable):** *Selfhosted in Docker Environment*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/dGj7REVM*
* **Other Relevant Data/Screenshots:** *I'm using these plugins: ChestSort, DeadChest, DriveBackupV2, EssentialsX, EssentialsXAntiBuild, EssentialsXChat, EssentialsXProtect, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Vault and WorldEdit*
* **Steps to Replicate:** *Just start the server with Dynmap and the provided configuration to see the error.*

**Comment by FedUpWith-Tech** [comment]
Aside from this error, what isn't working?

**Comment by KeldorDE** [comment]
As I see it, the map works so far, but there are a lot of missing tiles that are displayed with a 404 error, even though all render processes are completely finished. I am not sure if this has something to do with my reported error message.

![error](https://user-images.githubusercontent.com/13310563/130921360-03f12efc-a99b-4be9-a518-cf7610e71871.jpg)

**Comment by FedUpWith-Tech** [comment]
But are any tiles not showing up on the map or are you just seeing 404's? 404's are common with dynmap due to many tiles and caching and not indicative of any malfunction

**Comment by KeldorDE** [comment]
No, I don't see any missing tiles on the map. I did not know that the 404 errors are intentional ;) Then the exception shown doesn't seem to affect anything, but it's still ugly at startup.

**Comment by generrosity** [comment]
Hi! For the 404s, are the full renders completed? I think 'zzzzz's are zoomed tiles that get processed in the background.

Are you still seeing errors in your logs? Not missing anything in Dynmap itself?

Do you have a 'test world'? This might be the fastest way to confirm the 'cause' if it is plugin based. Really guessing, but it could be the Multiverse plugin that is Dynmap doesn't detect the 'map type' for even tho you might not include it on rendering.  Its the only thing not on the supported list and kinda 'map' related, and might be fine to support or fine to mention to just ignore errors from.

**Comment by KeldorDE** [comment]
Yes, the full render is complete.
The errors are still there on server start and in the Browser Console.
The bug does not reduce the functionality, but it always looks ugly when the server is started. I've already disabled the worlds one by one to see if the error persists on server start. The error is shown up for each world loaded alone. So it might be Multiverse related, all worlds are handled by Multiverse
