### ISSUE TITLE
Issue to render correctly marker in surface mod CatServer 1.12.2

### ISSUE THREAD

**Issue by cocosimus** [webbukkit/dynmap#3474]
Issue Description: Dynmap markers isn't correct in surface.

Dynmap Version: dynmap-3.1-spigot
Server Version: catserver 1.12.2
Markers-mod : Landlord-Dynmap, Worldguard

Hello my spawn marker, Landlord-Dynmap marker, playermarkers and worldguard marker isn't place correctly in surface mod : 
in flat :
![dyn](https://user-images.githubusercontent.com/9917403/130769945-1d668a38-427c-4e32-9dff-43a8cbb29d1c.png)

in surface :
![dyn1](https://user-images.githubusercontent.com/9917403/130770036-c060d7a1-a0af-4965-b7d8-98c3ab0f723d.png)

**Comment by FedUpWith-Tech** [comment]
This issue belongs on the LandLord-Dynmap issue tracker as it is an issue with it, not with Dynmap https://github.com/LandlordPlugin/LandLordMap
