### ISSUE TITLE
CTD on loading any world

### ISSUE THREAD

**Issue by Esseit** [webbukkit/dynmap#3481]
**Issue Description:** Dynmap crashes game once the world begins to load in around the player. Game launches just fine and pre loading for the world progresses normally. This may be due to a mod incompatibility as my game is heavily modded.

* **Dynmap Version:** Dynmap-3.2-beta-3-forge-1.16.5
* **Server Version:** forge ver 36.2.0
* **Pastebin of Configuration.txt:** default config used
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/WE4weLnu
* **Other Relevant Data/Screenshots:** no shaders or texture packs used, mod list included inside of crash report at the end.

 [yes] *I have looked at all other issues and this is not a duplicate*  
 [yes] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Dynmap is a server side mod and not a client side mod, it won't work on a modded client.
