### ISSUE TITLE
Players dissapear after a few seconds

### ISSUE THREAD

**Issue by TheBlankSlate** [webbukkit/dynmap#3483]
> template is **bold**
> sample data is *italicized*

**Issue Description:** One thing I've noticed is that every time I start up the server, the players that join will show for a few seconds and then disappear and never show ever until I restart the server, they join, and the whole thing repeats itself. Running `/dynmap show` doesn't do anything.

* **Dynmap Version:** 3.2-beta-3-514
* **Server Version:** Paper version git-Paper-233 (MC Version: 1.17.1)
* **Pastebin of Configuration.txt:** https://pastebin.com/84Whhkn6
* **Server Host (if applicable):** N/A
* **Pastebin of crashlogs or other relevant logs:** n/a - No errors
* **Other Relevant Data/Screenshots:** Other plugins installed that might affect this is `Towny`, `Towny-Dynmap`, and `Siegewar`
* **Steps to Replicate:**
* 1. Startup the server
* 2. Have player join the server
* 3. Wait a few seconds for the player(s) to disappear on the map

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Can you give me a list of plugins you have, this is a known issue with a certain plugin conflict and I want to know if you have it before I look elsewhere
