### ISSUE TITLE
Markers keep getting readded to dynmap

### ISSUE THREAD

**Issue by BamBamTheEggman** [webbukkit/dynmap#3484]
**Issue Description:** 
I am trying to remove the Icon for the spawn points of Towns (Not nations) The amount of markers that get created look very bad on the map and makes it difficult to see certain things. I would remove the home Icon line or remove the data for it but once the server restarts the info gets readded to the config and the flags readded.

* **Dynmap Version:** Dynmap Towny 0.87
* **Server Version:** Purper 1.16.5
* **Pastebin of Configuration.txt:** https://pastebin.com/7numThu4
* **Server Host (if applicable):** DedicatedMC
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/crashcausedbydynmap*

**Comment by FedUpWith-Tech** [comment]
Not an issue with Dynmap, see https://github.com/TownyAdvanced/Dynmap-Towny
