### ISSUE TITLE
Remember pinned state for the player list

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#3485]
**Feature Description:** Store the user's last pinned state for the player list in localStorage. Next time the user opens the page, the player list appears as it did in their previous session.

* **Additional context:** https://www.spigotmc.org/threads/materialdynmap.524109/#post-4257902

**Comment by generrosity** [comment]
Wouldn't this be a javascript thing?

**Comment by ghost** [comment]
Yeah and also incredibly easy. Just need to track pinned state in `localStorage`

**Comment by generrosity** [comment]
The dev is mostly a java developer rather than a javascript dev, and this feels more on the web/javascript side of things. I think he is open to contributions tho! Especially for 'low hanging fruit' 'quality of life' stuff. We have a 'dev' channel in Discord too

**Comment by FedUpWith-Tech** [comment]
Mentioned in #3461
