### ISSUE TITLE
Fabric - Wont work.

### ISSUE THREAD

**Issue by Ref1ax** [webbukkit/dynmap#3486]
Hello i have been trying to fix this myself but i can't. If you could then please make a tutorial or something so that i can figure out how to use this mod. Does the mod work with fabric? Ive tried to look for answers, but noone could help me. So i figuered i would reach out to you to see if you can help. Please kontakt me as soon as possible. Thank you. :D

**Comment by JurgenKuyper** [comment]
the installation page on the wiki is universal, it works on all the versions we currently support, check the console for errors.
If you are using a provider, check if you have opened the required ports, one for dynmap and one for minecraft, after opening, change the dynmap port to the assigned one and restart. if that doesn't work, remove the # in front of webserver-bindaddress: 0.0.0.0. 

If you are self-hosting, check if you can reach the website using the ip of the machine : port, so 10.0.0.5:8123. if that doesn't work, check the firewall rules, and uncomment the webserver-bindaddress.

**Comment by Ref1ax** [comment]
The problem we are having is that when we try to get to the map it just says: Can't connect to the website. Its like we are using the wrong port. But we arent. Just to clarify. Is it a Mod or a Plugin?

**Comment by FedUpWith-Tech** [comment]
The fabric version is a mod, there is a spigot/paper version which is a plugin

**Comment by generrosity** [comment]
@Ref1ax is that "failed to bind to port"? You can't use a port already in use (like re-using the Minecraft server port for dynmap too).
