### ISSUE TITLE
[Bug Report] Unexpected Error Causing Crash

### ISSUE THREAD

**Issue by CarlyFry** [webbukkit/dynmap#3487]
I recently started using Dynmap on a personal world. Since it is a large world, I use command blocks set with "/tp @p x y z" to help navigate around. For some reason, whenever I use one of these command blocks to teleport, Minecraft crashes, giving an exit code of -1. I'm not sure if this is something normal or if it can be fixed.

**Dynmap Version:** Dynmap-3.2-beta-3-forge-1.17.1
**Server Version:** 1.17.1-forge-37.0.15
**Pastebin of Configuration.txt:** https://pastebin.com/KC5jcpfq
**Pastebin of crashlogs or other relevant logs:** https://pastebin.com/vvzBfpwE

I will also note that I have worldedit, but I am not using any of the commands or such when Minecraft crashes.

**Comment by FedUpWith-Tech** [comment]
This is because dynmap only works on server side, it won't work on client side forge.
