### ISSUE TITLE
Dynmap registration not providing player feedback on success nor forwarding from login page

### ISSUE THREAD

**Issue by Fyrinlight** [webbukkit/dynmap#3488]
**Issue Description:** 
During the Dynmap registration process, when a user inputs their registration code, username, and password and registers, no feedback is given to them upon successful registration, nor do any forwards occur. php_error log shows notice.

This is occurring on a Windows server using WAMP 3.1.0 for the webserver. 

I have tested this on my linux box and used dynmap's internal webserver and when a player registers, it forwards them to the main dynmap map logged in which seems to be correct behavior.

This seems to be a duplicate of Issue #1660 which was closed in 2018. Some people commented on this issue earlier this year.

* **Dynmap Version:** Dynmap-3.2-beta-2-spigot.jar And Dynmap-3.2-beta-3-spigot.jar
* **Server Version:** Paper 1.16.5-466.jar (Paper-1.17.1-265.jar tested as well)
* **Pastebin of Configuration.txt:** https://pastebin.com/HT3msxuQ
* **Server Host (if applicable):** Self-hosted
* **Pastebin of crash logs or other relevant logs:**
    * php_error.log https://pastebin.com/UkEcQzdF
* **Other Relevant Data/Screenshots:** I am using WAMP 3.1.0
* **Steps to Replicate:**
    * Run Dynmap web files on Apache server.
    * Run ./dynmap webregister
    * Navigate to the login page, register with correct information
    * Hit Register, nothing occurs. php_error.log logs a notice for the implode method.
* **Troubleshooting Steps Taken:**
    * Tested on Dynmap-3.2-beta-2-spigot.jar and Paper 1.16.5-466.jar
    * Updated to Dynmap-3.2-beta-3-spigot.jar and tried newer paper build. Same issue occurred.
    * Deleted the Standalone and JS folder in the www directory and used new files generated from the web folder. Same issue.

 [#1660] *I have looked at all other issues and this is not a duplicate*  
 [YES] *I have been able to replicate this*

**Comment by mnfu** [comment]
Any update on this?

**Comment by JurgenKuyper** [comment]
I tested this on an nginx external webserver, which works, could be wamp is somehow not processing it properly?

**Comment by Fyrinlight** [comment]
I went ahead and tested some more configurations as it has been a while since I submitted the original bug report.

All attempts are still the same: no feedback is given to them upon successful registration, nor do any forwards occur.  There is no longer any php items logged, and the registration.php shows good. Nothing is logged after the http 200 log.
`[02/Jul/2022:01:27:08 -0400] "POST /dynmap/standalone/MySQL_register.php HTTP/1.1" 200 1599`

Dynmap Builds Used:
- Dynmap-3.3.1
- Dynmap 3.4-beta-4

Apache Versions Used:
- 2.4.27
- 2.4.54

PhP Versions Used:
- 5.6.31
- 7.1.9
- 8.1.7

Wamp Versions Used:
- 3.1.0
- 3.2.9

Paper version: paper-1.18.1-216

I'm curious if anyone is running this on Lamp to see if this is just an apache issue vs a Wamp specific issue?

**Comment by NathanVH8** [comment]
@Fyrinlight If you were to disable needing to login, (AKA Just the default Dynmap page) do you get the error `Could not update map: Not Found`? I've had basically this exact problem on a FAMP jail running on TrueNAS.

**Comment by Fyrinlight** [comment]
> @Fyrinlight If you were to disable needing to login, (AKA Just the default Dynmap page) do you get the error `Could not update map: Not Found`? I've had basically this exact problem on a FAMP jail running on TrueNAS.

I don't force people to log in to see the map, only to see where their player location is. I think what you are experiencing is a different error, as I have not run into that before, even when we didn't have the login system.
