### ISSUE TITLE
Black Chunks and Lines

### ISSUE THREAD

**Issue by Lewes** [webbukkit/dynmap#3489]
**Issue Description:** Player editted chunks are turning black in both flat and surface view.

* **Dynmap Version:** 3.2-beta-3-514
* **Server Version:** Paper 1.16.1
* **Pastebin of Configuration.txt:** https://pastebin.com/AR94Hk6y
* **Server Host (if applicable):** Self-hosted
* **Pastebin of crashlogs or other relevant logs:** None.
* **Other Relevant Data/Screenshots:** View on https://earth.manacube.com/
* **Steps to Replicate:** Launch Dynmap, edit chunks, wait a while, chunk renders as black on the map.

 [#] *I have looked at all other issues and this is not a duplicate*  
 [#] *I have been able to replicate this*
 
 Feel free to contact me on Discord at Boomclaw#7788 if you'd like to investigate closer.

**Comment by mikeprimm** [comment]
Your config has removed the 'chunkgenerated' render trigger - this is what happens when you do that.  See

https://github.com/webbukkit/dynmap/blob/v3.0/spigot/src/main/resources/configuration.txt#L303

for the default triggers
