### ISSUE TITLE
Grey lines outside visibilitylimits, hidestyle not working

### ISSUE THREAD

**Issue by John-H-Smith** [webbukkit/dynmap#3493]
> template is **bold**
> sample data is *italicized*

**Issue Description:** 
I limited the visibility with "visibilitylimits".
But while doing a fullrender, this grey lines are rendered, even if I set hidestyle to "ocean".
Maybe I should tell that the fullrender isn't finished
In Log there are all with skipped tiles:

`[11:21:04 INFO]: Full render of map 'flat' of 'world' in progress - 4400 tiles rendered (8.77 msec/tile, 0.00 msec per render) (100 tiles skipped)`
But rendering per se is working as I can test with other worlds.

The grey lines are also while rendering the surface map.

![image](https://user-images.githubusercontent.com/18233867/134762878-b9f10727-5aee-4b4c-81a2-dd75b3621e56.png)

* **Dynmap Version:** 3.2-beta-3-514
* **Server Version:** paper 1.17.1
* **Pastebin of Configuration.txt:** https://pastebin.com/04xYY1QX
* **Pastebin of worlds.txt:** https://pastebin.com/kVM2dBWQ
* **Server Host (if applicable):** Selfhosted

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by John-H-Smith** [comment]
Update:
I reinstalled dynmap on my local test server, I can reproduce this problem there too.
Even if visibilitylimits and renderlocations are only limited to a size of 1000 Blocks, the map is rendering outside the 100 Blocks. It seems like the limits are ignored. Also, the hidestyle is ignored and is always replaced with stone.

**Comment by FedUpWith-Tech** [comment]
This is an issue that I've seen a few times before regarding visibility limits and haven't been able to replicate. I'll work more on this soon

**Comment by Vyladence** [comment]
If it's not already the plan, how about making dynmap simply not render any tiles whatsoever outside of the set visibility limits?

**Comment by FedUpWith-Tech** [comment]
> If it's not already the plan, how about making dynmap simply not render any tiles whatsoever outside of the set visibility limits?

In theory this would work for 99% of people however if someone then specified an area outside the primary map Dynmap wouldn't be able to render it and display it properly. Dynmap has to render the tiles as invisible, stone, or ocean in order for that edge case.

It would be more efficient to just ignore the non-visible limit area but that would require a bit of an overhaul that likely won't happen soon.

**Comment by mikeprimm** [comment]
> If it's not already the plan, how about making dynmap simply not render any tiles whatsoever outside of the set visibility limits?

That actually is what hidestyle: air is supposed to do.

**Comment by mikeprimm** [comment]
Not having any luck reproducing this with current code - please confirm your current settings and what you see with current code (3.3-beta-4 or 3.3-SNAPSHOT)
