### ISSUE TITLE
Dynmap is unable to initialize (Thermos 1.7.10)

### ISSUE THREAD

**Issue by gavenisaweesome** [webbukkit/dynmap#3494]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap as been unable to function correctly. I've tried multiple versions and altered many things on my server to make it work, but everything I've tried is in vain. *

* **Dynmap Version:** *dynmap v2.2-1118*
* **Server Version:** *Thermos 1.7.10 (/version: This server is running Thermos | https://github.com/CyberdyneCC/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10))*
* **Pastebin of Configuration.txt:** *No config; Dynmap is unable to start*
* **Server Host (if applicable):** *Pebblehost*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/TjBW9FDG*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Dynmap dropped support for 1.7.10 and thermos was never supported.

**Comment by Price-MA-Butta** [comment]
Add the dynmap cbbridge 2.3 to the plugins folder and the 2.3 dynmap forge to the mods folder. You shouldn't need anything else.  https://www.curseforge.com/minecraft/mc-mods/dynmapcbbridge
