### ISSUE TITLE
Lite map view 

### ISSUE THREAD

**Issue by XuPuPG** [webbukkit/dynmap#3496]
preview the map by loading only the top blocks.  changing a chunk will cause it to be fully loaded or just as superficial

**Comment by FedUpWith-Tech** [comment]
What exactly do you mean? Can you elaborate on this feature request a bit more? Thanks!

**Comment by XuPuPG** [comment]
full loading of the map is too long, sometimes you just need to see how it will look from above and quickly

**Comment by mikeprimm** [comment]
Use /dmap to delete the maps you don't want, and the set the perspective for the (flat) map you do to a low res choice (like iso_N_90_vlowres)

 https://github.com/webbukkit/dynmap/wiki/Configuring-Maps-and-Worlds-using-dmap

**Comment by FedUpWith-Tech** [comment]
> full loading of the map is too long, sometimes you just need to see how it will look from above and quickly

You can also speed map loading via storing map files on an SSD, increasing bandwidth between client and server, and using an external webserver like apache and HTTP/2 or HTTP/3 protocols
