### ISSUE TITLE
When i do /dynmap fullrender it only renders the chunks next to spawn and it says "render complete"

### ISSUE THREAD

**Issue by escaleirex** [webbukkit/dynmap#3497]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *When i do /dynmap fullrender it only renders the chunks next to spawn and it says "render complete"*

* **Dynmap Version:** *3.2-beta-3-spigot*
* **Server Version:** *Paper 1.17.1*
* **Pastebin of Configuration.txt:** *https://pastebin.com/GwSvL0mm*
* **Server Host (if applicable):** *Self Hosted*
* **Pastebin of crashlogs or other relevant logs:** **
* **Other Relevant Data/Screenshots:** *
![image](https://user-images.githubusercontent.com/69918820/135339816-0a0e8c0e-4748-4f17-b06d-b4c7236d7bd6.png)
Look at my map to see the issue: http://craven-surprise.auto.playit.gg:48800/*
* **Steps to Replicate:** *When i do /dynmap fullrender it only renders the chunks net to spawn, and then it says "render complete*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by Escaleirex** [comment]
I Just Deleted everything on the dynmap folder and it worked ;)

**Comment by escaleirex** [comment]
clicked on the wrong button

**Comment by escaleirex** [comment]
![image](https://user-images.githubusercontent.com/69918820/135346903-293cff90-f648-471a-abdc-ea8f4faca3b3.png)
deleted everything on the dynmap folder and now it rendered a bit more but still doesnt render everything

**Comment by FedUpWith-Tech** [comment]
FAQ 1
https://github.com/webbukkit/dynmap/wiki/FAQ#1-i-did-a-dynmap-fullrender-but-the-map-is-pretty-much-empty
