### ISSUE TITLE
ERR_INVALID_HTTP_RESPONSE 1.17.1

### ISSUE THREAD

**Issue by Bertogim** [webbukkit/dynmap#3498]
**Issue Description:**
config.txt is like this

The TCP port on which the web server will listen on.
web server port: 25565

In the console it says: [dynmap] Web server started on address 0.0.0.0:25565

On the web it says:
ERR_INVALID_HTTP_RESPONSE

And even if the port of the web server put port: 12915 is still not going

* **Dynmap Version:** *3.2-beta-3-spigot.jar*
* **Server Version:** *PaperMC 1.17.1*
* **Pastebin of Configuration.txt:** *https://pastebin.com/Vj350kkh*
* **Server Host (if applicable):** *CentroNodes*
* **Pastebin of crashlogs or other relevant logs:** *No but here is the console: https://pastebin.com/390EYNnM*
* **Steps to Replicate:** **Launch Dynmap, open the browser, put the server IP, ti says: ERR_INVALID_HTTP_RESPONSE**

 [#] *I have looked at all other issues and this is not a duplicate*
 [] *I have been able to replicate this*

Feel free to contact me on Discord at **Bertogim#4868** if you'd like to investigate closer.

**Comment by FedUpWith-Tech** [comment]
You can't set the webserver port to be the same port as your minecraft server. I suggest using a second port. Most hosting services will have specific ports you can and can't use

**Comment by Bertogim** [comment]
I ask my host if they have a have specific ports you can and can't use
I'll tell you if they tell me something

**Comment by Bertogim** [comment]
[Solved]
I need a port from my host
Thanks

**Comment by Bertogim** [comment]
- [closed]

**Comment by Bertogim** [comment]
How i close this?
