### ISSUE TITLE
Embed URLs in icons

### ISSUE THREAD

**Issue by KonohanaSakuya2680** [webbukkit/dynmap#3513]
I would like to be able to connect to a set website when I click on the icon displayed in the WebMap.
Is this possible?

**Comment by Cobbert** [comment]
Can you please explain a bit more in detail?

Reading the config file you will find a sections at line 182-189, at least on my config file. 

```
  # Note: more than one logo component can be defined
  #- class: org.dynmap.ClientComponent
  #  type: logo
  #  text: "Dynmap"
  #  #logourl: "images/block_surface.png"
  #  linkurl: "http://forums.bukkit.org/threads/dynmap.489/"
  #  # Valid positions: top-left, top-right, bottom-left, bottom-right
  #  position: bottom-right
```

I have never used this component but it seems like what you may be looking for and is somewhat self explanatory, if its not what you need, please explain what link you want to change and I will see if I can be any help with finding the link for you to edit yourself.

Also remember that you need to remove the '#' comments before this component will load. Maybe someone else can elaborate.
