### ISSUE TITLE
How do you make everyone invisible but not yourself?

### ISSUE THREAD

**Issue by ZorRayel** [webbukkit/dynmap#3515]
I was wondering if there is a way where I can hiden everyone on the dynmap but not me. So that you only see yourself on the dynmap. 
If there is a way for this, can someone let me know and how to do it?

Greetings,
ZorRayel

**Comment by JurgenKuyper** [comment]
as far as I know you can only hide players gobally, not per client.

**Comment by generrosity** [comment]
Im going to jump in and say "no" - or at least unlikely out of the box - the main program can guess someone from their home IP, but IPs change, and two people could be at the same house, and it can be easily fooled.
