### ISSUE TITLE
Skins not updating in dynmap

### ISSUE THREAD

**Issue by erlandyt** [webbukkit/dynmap#3520]
**Issue Description:** Skins don't update in the map when the player's skin is changed. 

* **Dynmap Version:** 3.2.1
* **Server Version:** 1.16.5 paper
* **Pastebin of Configuration.txt:** too hard to copy-paste. I can get it if it is important
* **Server Host (if applicable):** Contabo? (Justa plain hosting service not intended for only games)
* **Pastebin of crashlogs or other relevant logs:** No logs
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** (Unsure of the steps)

- Have full-body user icons on (Unsure if it is part of the problem)
- Go on the server
- render (Unsure if it is part of the problem)
- leave and change skin
- go back on the server
- check dynmap and the player skin is the old one

 [x] *I have looked at all other issues and this is not a duplicate*  
 [-] *I have been able to replicate this* (Unable to fix and therefore unable to replicate)

**Comment by erlandyt** [comment]
[https://minotar.net/armor/bust/erland_2/100.png](https://minotar.net) I tried using a different service for skins but it also failed

**Comment by FedUpWith-Tech** [comment]
You will need to enable fetchskins: true in the config in order for skins to be updated

**Comment by erlandyt** [comment]
Did it and changed the URL to default but now my profile pic looks like this: http://play.erland.fi:8123/tiles/faces/32x32/Erland_2.png

**Comment by erlandyt** [comment]
Here is the configuration.txt's skin part btw
```# ctm-support: if true, Connected Texture Mod (CTM) in texture packs is enabled (default)
ctm-support: true
# custom-colors-support: if true, Custom Colors in texture packs is enabled (default)
custom-colors-support: true

# Control loading of player faces (if set to false, skins are never fetched)
fetchskins: true

# Control updating of player faces, once loaded (if faces are being managed by other apps or manually)
refreshskins: true

# Customize URL used for fetching player skins (%player% is macro for name)
skin-url: "http://skins.minecraft.net/MinecraftSkins/%player%.png"
#skin-url: "https://minotar.net/avatar/%player%"
#skin-url: "https://minotar.net/armor/bust/%player%/100.png"

# Enable skins via SkinsRestorer plugin instead of internal legacy implementation (disabled by default)
#skinsrestorer-integration: true
```

**Comment by FedUpWith-Tech** [comment]
The pic in the link looks like a skin, what's the issue?

**Comment by erlandyt** [comment]
Weird that it updated so late even though I had restarted the server multiple times.
