### ISSUE TITLE
Part of map not rendered

### ISSUE THREAD

**Issue by IsolatedHunter** [webbukkit/dynmap#3522]
I used [Worldborder](https://www.spigotmc.org/resources/worldborder-1-15.80466/) to fill the chunks and after I put on Dynmap I don't know what happened? The map is on http://map.isolatedgamers.com/ !
![map1](https://user-images.githubusercontent.com/82542749/139255827-6e6dc4f5-b456-4cc2-8cb0-5d953db3a239.PNG)
![map2](https://user-images.githubusercontent.com/82542749/139255830-2009ab84-68fc-47c8-8d16-dbd02c010bfb.PNG)
![map3](https://user-images.githubusercontent.com/82542749/139255832-b9435042-356e-4321-9d6d-cd9a2bf614a3.PNG)

**Comment by FedUpWith-Tech** [comment]
Looks like it's showing up now:
![image](https://user-images.githubusercontent.com/7731191/139477862-f15de40a-3764-4a94-bbb5-20e7e56fdc12.png)

**Comment by IsolatedHunter** [comment]
I had to manually go through the chunks and do /render
