### ISSUE TITLE
Indexed JPEG output profiles

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#3524]
> template is **bold**
> sample data is *italicized*

**Feature Description:** An option to output rendered images as indexed JPEGs using a web-optimised profile such as 8-bit or 12-bit. This would allow people to store high-res maps on hosts like Shockbyte.

* **Additional context:** Unfortunately IDK how image profiles work here so can't provide pointers.

**Comment by generrosity** [comment]
I assume you know about the render image output defaults here like highly compressed jpeg - https://github.com/webbukkit/dynmap/wiki/HD-Map-Configuration#additional-hdmap-settings

I don't know if JPEG supports indexed colours. PNG would. Are you thinking of a preset like "png-8bit", and how do you image it looking and choosing colours? Predefined index? If it was let loose it would choose colours per image tile

**Comment by ghost** [comment]
Sure, PNG or BMP even. Perhaps conversion to 8bit with dithering.

> Predefined index? If it was let loose it would choose colours per image tile

Hmm can ImageMagick choose colors between a set of images?

**Comment by generrosity** [comment]
One thing I notice not on that page but referenced elsewhere is that you can use WebP, webp-q7 etc.

I'm not sure what your Shockbyte requirements actually are - is it maximum file size? Total size across the whole map? What are you trying to achieve

**Comment by ghost** [comment]
I don't use Shockbyte anymore thank goodness, but WebP sounds perfect.
Probably addresses this issue actually.

**Comment by generrosity** [comment]
Nice. Try it at both resolutions if you can, and report back here compared to current (jpg? jpg-60?) - always keen to hear things work out.

And if not, there might be more room for quick tests and improvement 😁👌🏽

**Comment by mikeprimm** [comment]
Nothing gained by this - no reason to expect we'll ever do it.

If you want to save space, use JPG format with lower quality settings (which is already supported) - this effectively reduces color precision in order to reduce size.
