### ISSUE TITLE
External Webserver: Could not retrieve configuration

### ISSUE THREAD

**Issue by F-fengzi** [webbukkit/dynmap#3525]
**Issue Description:** *Error prompt 'Could not retrieve configuration: Not Found' shows up while I'm trying to host dynmap on a external webserver (same machine, LN~~M~~P)*

*Some other info:
I followed #2609 to set up the standalone web server, but my approach was to move the whole `plugins/dynmap/web/*` into `/usr/share/nginx/html/` (the default web root) and then change the configurations*

- Internal webserver has no problem
- Using SQLite which is under `plugins/dynmap/dynmap.db`, full render finished
- Web server and PHP(-fpm) works fine
- `html` and all subfolders have 777 permissions
- Can access `host/standalone/config.js` through http, but got 404 trying to access `host/standalone/configuration.php`, don't know if that's normal*

------

* **Dynmap Version:** *v3.2.1*
* **Server Version:** *Paper 1.17.1 build 356*
* **Pastebin of Configuration.txt:** *https://pastebin.com/3q9fe9CM*
* **Server Host (if applicable):** *Self hosted*
* **Steps to Replicate:** *Not sure, but see the info above*

I will be happy to provide any other information needed 

 [Similar ones, but didn't help] *I have looked at all other issues and this is not a duplicate*  
 [Sorry, no] *I have been able to replicate this*

**(Thanks in advance!)**

**Comment by F-fengzi** [comment]
~~anyone?~~

**Comment by Cobbert** [comment]
If your web server and minecraft server are on the same host, have a look at the basic external web host tut on the wiki. You used a tut that is for using mysql but you didn't use it and stuck with sqllite. 

You probably just missed something or have a nonstandard setup.

Maybe let us know what parts of the tut you referenced that you followed and we can go from there? 
If you solved your issue, please let us know what you did so others with your possible issue can find some help.

Also proceed with caution when using chmod to 777 for any files. This allows ANYONE to edit those files on your system. 777 allows user,group,other to read,edit,execute.
