### ISSUE TITLE
Notifications in browser

### ISSUE THREAD

**Issue by plutonium-239** [webbukkit/dynmap#3530]
**Feature Description:** Notifications in the browser whenever a new message is received. 

**Additional context:** Notification could be anything from an actual browser notification to just playing a 'ping' sound and having the tab show a notification badge (might be just a plain badge or number of messages since last tab visit)
image for reference
![image](https://user-images.githubusercontent.com/29684689/142079653-5a21a56f-9309-4517-a7a7-080385b2113e.png)

**Comment by generrosity** [comment]
Cool idea. As this is built mostly in the webpage, its likely a whole bunch of javascript type scripting that is needed. Might be idea for a plugin or web frontend to impliment possibly. I don't think the core dynmap messaging was designed to be a true messaging service.

I'm going to mark this as 'low priority' as both quality-of-life and outside core java coding

**Comment by plutonium-239** [comment]
True, I'll look into contributing, but it'll be my first experience with notifications in js/browser handling etc
I'll try and make a simple notification thing for now, will update you!

**Comment by generrosity** [comment]
Nice!

**Comment by generrosity** [comment]
there is a dev channel on Discord if that helps too - tho again most of them aren't into the javascript side of things, they can help with pushing code and testing potentially

**Comment by FedUpWith-Tech** [comment]
Listed in megathread #3461
