### ISSUE TITLE
Mods for Minecraft 1.17.x require additional changes for compatibility

### ISSUE THREAD

**Issue by smmmadden** [webbukkit/dynmap#3531]
**FYI:** Mostly a reminder than issue since these files are often forgotten to be updated.  There are files to change for 1.17.1 to work.
**mods.toml**, ***mixins*** and **pack.mcmeta** need updating for every major release of Minecraft depending on what is included.
Minecraft 1.17.x - Minimum Java Level Supported: 16.0.1
pack.mcmeta files Pack Format=7 for 1.17.x release, 6 for 1.16 and 5 for 1.15, etc.
Minecraft Vanilla Launcher (new one from Microsoft Store) has loading issues that require additional changes to our mods and modpacks.  Read conversation towards the bottom on Forge Support: https://forums.minecraftforge.net/topic/105079-forge-1171-not-launching/?_fromLogin=1
This describes how to workaround the breaking change Microsoft made with the new Vanilla Minecraft launcher.  I'm posting here as I've looked at this 1.17.x version of the mod and found one or both issues exist.  It wasn't an easy process figuring out why mods were not working properly so I've provided the data so you don't have to waste time trying to figure out why.

**Comment by generrosity** [comment]
@mikeprimm @kosma  apologies - going to tag you here for some tips on coding, might be able to just close, but maybe add comment to the top of your main build script too? 😜

**Comment by mikeprimm** [comment]
Not sure I understand the problem, as we're only a server mod - but I suppose there are a couple of folks that might jam it into their client (honestly don't know that that works, since it isn't a tested or supported configuration, as far as we're concerned).   Only item I saw as relevant is the pack.mcmeta for Forge 1.17.1 to have pack_format set to 7
