### ISSUE TITLE
Dynmap forgot where it left off after server restart, won't continue fullrender.

### ISSUE THREAD

**Issue by Strahilchu** [webbukkit/dynmap#3532]
> template is **bold**
> sample data is *italicized*

**Issue Description:** Dynmap has been rendering for a few days and normally I can restart the server and it would just continue but today it stopped and /dynmap stats shows zero progress and render is not continuing...
Is there a way for me to get it back on track?

* **Dynmap Version:** Dynmap version: core=3.2.1-531, plugin=3.2.1-531
* **Server Version:** Paper version git-Paper-381 (MC: 1.17.1)
* **Pastebin of Configuration.txt:** https://pastebin.com/LNeUj62a
* **Server Host (if applicable):** BloomHost
* **Pastebin of crashlogs or other relevant logs:** None
* **Other Relevant Data/Screenshots:** None
* **Steps to Replicate:** Unknown

**Comment by generrosity** [comment]
I think the quick answer here might be "no" - you could try running "/dynmap fullrender resume <world>"   or "/dynmap updaterender" both of which should only target tiles that dont need updating.

Yea - server stopping suddenly or crashing or rebooting too slow might kill the dynmap process where it cant recover. 

Let us know if its re-occurring, close when youve got it fixed up

**Comment by mikeprimm** [comment]
A crash is a crash - we don't save progress transactionally, because it would kill performance and generate unneeded file I/O.  MC loses chunk updates since the last 'save-all' under the same conditions, so integrity at that point is suspect anyway....

**Comment by generrosity** [comment]
@mikeprimm   - for my later wiki edits, is there a way to force a save of the progress (or is it just 'pause all' or a clean shutdown), and what is the best command to kick things back alive if any
