### ISSUE TITLE
"/" in marker or marker set names causes server to crash when Dynmap loads the markers.yml file

### ISSUE THREAD

**Issue by AngelofWoe** [webbukkit/dynmap#3533]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *"/" in marker or marker set names causes server to crash when Dynmap loads the markers.yml file, removing all instances of '/' from the file resolves the issue..*

* **Dynmap Version:** *Dynmap-3.2.1-fabric-1.17.1.jar*
* **Server Version:** *fabric 1.17.1, Fabric launcher*
* **Pastebin of Configuration.txt:** *https://pastebin.com/GVgfgngq*
* **Server Host (if applicable):** *Self hosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/YdSse1Lf, https://pastebin.com/86V8QT8z*
* **Other Relevant Data/Screenshots:** *Map is from 1.17, mods are: Dynmap-3.2.1-fabric-1.17.1.jar  datapackportals-1.0.4-1.17.jar  fabric-api-0.42.1+1.17.jar  fabric-chunkpregen-0.3.4.jar  lithium-fabric-mc1.17.1-0.7.5.jar, datapacks are: CraftingTweaks.zip     anti_enderman_grief_v1.1.0.zip  coralcraft-v2-2-datapack-1563828610.zip  mapart-world.zip              silence_mobs_v1.1.0.zip                track_statistics_v1.1.0.zip
OnePlayerSleepV42.zip  armor_statues_v2.8.1.zip        double_shulker_shells_v1.3.0.zip         more_mob_heads_v2.9.2.zip     terracotta_rotation_wrench_v1.1.1.zip  wandering_trades_v1.5.0.zip
SporeBlossom.zip       coordinates_hud_v1.2.0.zip      dragon_drops_v1.3.0.zip                  player_head_drops_v1.1.0.zip  track_raw_statistics_v1.5.0.zip*
* **Steps to Replicate:** *Name a marker set or marker with a / in the name, such as "Claims / Bases". Restart the server. Server crashes when marker.yml is read. Removing all instances of "/" from the file corrects the issue.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by generrosity** [comment]
Nice find! It should proberbly handle this situation more elegantly.

Were you editing the file yourself, or via commands?

**Comment by AngelofWoe** [comment]
I had in the / in the names when the markers were added through commands, I ended up removing them directly with sed in the shell.

**Comment by JurgenKuyper** [comment]
did you enclose the marker name with quotes? ("/test")?

**Comment by AngelofWoe** [comment]
/dmarker add id:"/test" - Crash after server.jar is restarted.
/dmarker add id:"This is a test" - Expected behavior
/dmarker add id:"This is a / test" - Crash after server.jar is restarted.
/dmarker add id:This is a test - Marker created named 'This'

Went into the markers.yml and added encapsulating quotes to the ids, both for " and ', still results in a crash in either situation. Removing / from all ids still fixes it.

**Comment by JurgenKuyper** [comment]
@mikeprimm there seems to be a crash related to / in front of marker names, also enclosed with quotes on paper, can you check why this is happening? (when you have time)

**Comment by AngelofWoe** [comment]
Just to clarify, it's not just at the front of the name, it's anywhere in the string at all. I tried front, middle, end, etc.

**Comment by mikeprimm** [comment]
Fix added - it'll be in next dev build (build 562), and 3.3-beta-1 release
