### ISSUE TITLE
How to enable friend to see map when im hosting server with ngrok?

### ISSUE THREAD

**Issue by dominox5** [webbukkit/dynmap#3534]
Hello, i am hosting a minecraft server with ngrok and I install dynmap. I can dynmap see but my friends no. Can anybody help me?

**Comment by JurgenKuyper** [comment]
you have to port forward the dynmap port if you are selfhosting the server (by default 8123 but changable in configuration.txt by altering webserver-port)

**Comment by leon0399** [comment]
Look here 

* https://ngrok.com/docs#multiple-tunnels
* https://newbedev.com/ngrok-configure-multiple-port-in-same-domain

**Comment by Cobbert** [comment]
If leon helped you solve this issue don't forget to mark it as solved! :)

If leon did not help you, can you please explain more about your situation and network setup please? I never used ngrok, but it seems simple enough for a very basic setup.

Please explain the rundown of how you initiated your tunnel, how your friends are connecting and from where, LAN, WAN, etc.

Networking is not the most simple thing so please provide as much detail as you can and I'm sure someone can assist you more in depth, as well as what systems you are running on.
