### ISSUE TITLE
SQLite NGINX Web File version Mismatch

### ISSUE THREAD

**Issue by Happyrobot33** [webbukkit/dynmap#3535]
I am having a similar issue as is described in #2997.

Setup:
- MineOS running in a VM
- NGINX server using dynmaps own web folder, not a copied version
- SQLite (I couldn't get MySQL to work)

Ive already tried refreshing the browser cache, restarting services and the whole VM itself, no luck

both version.js and all other files I could find that reference the version use the same version identifier

**Comment by generrosity** [comment]
Hey! Has this come right? Is cloudflare involved? Tried it on in a incognito or different browser? Was this previously working, or working on the internal web service?

**Comment by Happyrobot33** [comment]
This isn't fixed yet, no cloudflare involved, I've tried all the browser things I can with no affect. It worked on the internal webserver in filetree mode, but unless I am mistaken you can't use SQlite with the default web server?

**Comment by Happyrobot33** [comment]
Okay, so for anyone running into this issue in the future, and you are just trying to get dynmap to use a database solution like SQLite, make sure your configuration is reset to the default all for except the file schema, which can stay to your SQL solution. you DO NOT NEED a seperate web server for SQL support. I suggest this be clarified in the configuration, as there is alot of tutorials that make it seem like you do

**Comment by generrosity** [comment]
I have the ability to edit the wiki, and possibly make suggestions on the config. Do you have specific places that you suggest would be best updated?

**Comment by Happyrobot33** [comment]
I would suggest adding a suggestion in the wiki talking about file size limits, and overall how easy it is to switch to SQLite mode. I would also suggest maybe adding into the SQLite comment lines that an additional webserver is not needed. Lastly, I'm wondering if it would be beneficial to just make the default SQlite anyway, as it would fix any future issues users have with Inodes (This was my issue) or with web interfaces like MineOS slowing down when looking through all the tile images. I know it needs an additional jar file but honestly I think it would be worth it to just make it a dependency

**Comment by Happyrobot33** [comment]
Example for what could be added to the wiki under FAQ perhaps?

***Im having an issue with too many tiles/max INODE usage***
If you are running into an issue where dynmap is generating too many tiles and slowing down web GUI's or maxing out the Inodes on your machine, then switching to the SQLite tile mode should solve your problem. **Warning, you will have to do a fullrender after switching to this mode as you cannot transfer pre-existing tiles**

Steps should also be gone through on how to set this up on a fresh install, and where to get the SQLite driver that needs to be in the server files for it to work

**Comment by Happyrobot33** [comment]
having this show up in google searches instead of things suggesting both SQL AND a separate web server would really be beneficial
