### ISSUE TITLE
dynmap keeps giving me the error message, "error updating map tables"

### ISSUE THREAD

**Issue by CandyMantis** [webbukkit/dynmap#3536]
Hey!

I recently started a pixelmon survival with some friends and I thought it would be fun to use dynmap. I followed my server providers tutorial on how to install it, but it keeps spamming me with the error message 

"Error updating Maps table - (conn=14988656) Table 'customer_194836_dynmap.Maps' doesn't exist"

I think it has something to do with MySQL but I'm not for sure. did I just miss a step that wasn't in the video or am I doing something horribly wrong?

I'm using dynmap 3.1 on forge 1.12.2 and pebble host is hosting my server

I don't know if this has anything to do with it but I'm also using pixelmon and I also have spongeforge installed

**Comment by generrosity** [comment]
I believe that LostBot answered this question on the Discord - its likely not a dynmap problem but a configuration issue at the host;

Dynmap couldn't create the table, contact your host support on how to fix it
