### ISSUE TITLE
[Feature Request] JPEG XL/.jxl Image File Format Support

### ISSUE THREAD

**Issue by NickVHoy11** [webbukkit/dynmap#3537]
JPEG XL offers significantly better image quality and compression ratios than legacy JPEG, plus a shorter specification. It is designed for computationally efficient encoding and decoding using software implementations without the need for additional hardware acceleration, even on mobile devices.

**Comment by generrosity** [comment]
Nice. 

Have you tried the google format webp? You can use it in the same place as jpg-90 eg webp, webp-q75

I'd be interested if this would satisfy your space needs, and if you are able to compare to converting from png-to-jpeg-xl

**Comment by NickVHoy11** [comment]
> Nice.
> 
> Have you tried the google format webp? You can use it in the same place as jpg-90 eg webp, webp-q75
> 
> I'd be interested if this would satisfy your space needs, and if you are able to compare to converting from png-to-jpeg-xl

```
codec         vmaf score   size in bytes     command
JXL        94.379052    197191            cjxl -q 90
AVIF       94.481718    227924            avifenc --min 11 --max 11
WEBP       94.479717    308780            cwebp -q 91
MozJPEG    94.640120    539974            cjpeg -q 90 -baseline
```

Using VMAF to compare, jxl has on pare image compression quality with WEBP and almost half the file size.

**Comment by generrosity** [comment]
I think Mike is always keen for little optimizations and checking our assumptions. He has done the occasional post out with his own epic maps and comparisons :) Some websites arent as glowing about jpegxl (jizzel?), one says "Most images on the web are (the equivalent of) libjpeg q60-90. AVIF beats JXL below the equivalent of q40. Above q50, JXL is better."

This worries me a little - how many browseers currently support JXL? What browser are you using currently?
![image](https://user-images.githubusercontent.com/12838061/144344741-e685edf3-94f4-49e7-95be-ec41d19575d3.png)

Having a java library for the image type helps. I'm failing to find one in google today, doesn't mean it isn't out there.... unless this is the correct repository for it? https://github.com/libjxl ... /libjxl/issues/396 and tools/CMakeLists.txt ... references to Make Files for Java but I don't see things in their Releases

**Comment by NickVHoy11** [comment]
@generrosity Was not thinking of browser support, which is currently none by default I enabled it in Chrome:[https://caniuse.com/jpegxl] (https://caniuse.com/jpegxl)
According to wikipedia it will be standardized in 2022(I assume this is when it gets built in browser support):
https://en.wikipedia.org/wiki/JPEG_XL

It currently is not support by the majority of browsers unless enabled. IMO While jxl is part of the future, adding it right now might not be worth it due to the incompatibility, but could be part of future proofing. 
I used bash to make the files using the same repository referenced. I do not know about java support.

In terms of quality:
https://cloudinary.com/blog/how_jpeg_xl_compares_to_other_image_codecs
This articles is represents the outcome I get.

**Comment by GBeauregard** [comment]
> Nice.
> 
> Have you tried the google format webp? You can use it in the same place as jpg-90 eg webp, webp-q75
> 
> I'd be interested if this would satisfy your space needs, and if you are able to compare to converting from png-to-jpeg-xl

It's a bit premature to implement as nothing major has merged in stable support yet, but in case it isn't clear JPEG XL is intended to completely supersede PNG. It has a separate lossless encoding mode based on prior formats that blows PNG out of the water. This encoder is not the same as its lossy one, which would probably be competitive for dynmap's purposes anyway.

It's also not clear support will come down the pipe as last I read mozilla steering is being a bit hesitant with it given the existence of avif (which is a shame since I love JXL's lossless encoder).

**Comment by generrosity** [comment]
It looks great.

Once there is browser support, and a java library to just slot it, yea likely a good one. But likely to be shelved for a while

**Comment by generrosity** [comment]
Actually, given the requirement for webp command line tools, that might be easily circumvented.

`Note: any webp format requires the presence of the 'webp command line tools' (cwebp, dwebp) (https://developers.google.com/speed/webp/download)`

**Comment by mikeprimm** [comment]
https://caniuse.com/?search=jpeg-xl given current status, this is not happening in the foreseeable future.  Small compression improvements are just not work the effort - I frankly regret the webp support, as it is also quite marginal and has generated more support load than is justified.
