### ISSUE TITLE
1.18 support

### ISSUE THREAD

**Issue by vaporvee** [webbukkit/dynmap#3538]
1.18 support would be cool
Log: https://mclo.gs/cYbxx6w

**Comment by ghost** [comment]
https://www.reddit.com/r/Dynmap/comments/qwa1ec/comment/hl6pxwi/?utm_source=share&utm_medium=web2x&context=3

**Comment by generrosity** [comment]
Please be patient - 1.18 has only just been released. Check the usual announcement places for all updates. Theyve changed many core coding so not all features will be availible in first releases

**Comment by FedUpWith-Tech** [comment]
Going to lock this to collaborators as well all want this and further discussion or "bumps" won't make the plugin be updated faster.

**Comment by FedUpWith-Tech** [comment]
Update from @mikeprimm in the Discord:

> OK folks - the first EXPERIMENTAL builds for 1.18 are now available!    As all the servers (Spigot, Paper, Fabric and Forge) are all also considered experimental, you should consider using these servers as risky - and using these Dynmap builds with those servers as additional risk - be sure you've got good backups before messing with 1.18 on a server with worlds that you are attached to!
> 
> In any case, the latest 1.18 enabled builds are here:
> - for Spigot or Paper is here - https://dynmap.us/builds/dynmap/Dynmap-3.3-SNAPSHOT-spigot.jar
> - for Fabric (big thanks here to @kosma  and @ajmadsen  for this port!) - https://dynmap.us/builds/dynmap/Dynmap-3.3-SNAPSHOT-fabric-1.18.jar
> - for Forge 1.18 - https://dynmap.us/builds/dynmap/Dynmap-3.3-SNAPSHOT-forge-1.18.jar
> 
> Testing on these builds has been light, and there are likely some issues - I know a few blocks are missing, although most of the new blocks were already supported as part of supporting Caves and Caverns Part I in 1.17.1.
