### ISSUE TITLE
[Feature Request] Add coordinate arguments to regular /dmarker command

### ISSUE THREAD

**Issue by ephun** [webbukkit/dynmap#3542]
I would like to see an added ability to execute the `dmarker` command from a server console, for example, and be able to remotely assign the coordinates of the marker. To my knowledge, this feature is not possible in the current builds of dynmap.

**Comment by ephun** [comment]
To elaborate, I am the owner of a Spigot server. Ideally, I could have players submit marker requests through Discord. They give me the coordinates, name, and marker "type" (icon) and I can set it console-side without having to get out of survival, write down my coordinates, teleport to theirs, set the marker, teleport back, and switch back to survival.

**Comment by generrosity** [comment]
Ah - so the full command here doesn't work?

`/dmarker add id:<id> <label> icon:<icon> set:<set-id> x:<x-coord> y:<y-coord> z:<z-coord> world:<Worldname>`

**Comment by ephun** [comment]
Oh man. I feel silly. I read documentation, but apparently missed this. I'm sorry haha
