### ISSUE TITLE
1.18 MySQL_config.php file missing in web/standalone

### ISSUE THREAD

**Issue by controlol** [webbukkit/dynmap#3545]
> template is **bold**
> sample data is *italicized*

**Issue Description:**
After a fresh install and enabling the external webserver as explained on the wiki I try to open the interface with php-fpm but the `MySQL_config.php` file is missing. I see it does exist for a older server version (1.16) which I haven't touched in a long time.

* **Dynmap Version:** Dynmap 3.3, either first experimental or build 
* **Server Version:** Paper 1.18 build 21
* **Pastebin of Configuration.txt:** [ *https://pastebin.com/5SETL3z2*](https://pastebin.com/B1cDyYA5)
* **Server Host (if applicable):** Selfhosted
* **Pastebin of crashlogs or other relevant logs:** 
* **Other Relevant Data/Screenshots:** 
![image](https://user-images.githubusercontent.com/46456214/144573141-80fd3a0b-d97e-49ca-aab1-17dfda4053e6.png)
This screenshot shows the `MySQL_config.php` file is missing, and on the right MySQL_configuration.php. (I tried different type of includes before I found out the file was missing so it's a little edited)
* **Steps to Replicate:** Fresh install of Paper 1.18, add Dynmap plugin. Let it start once, change config to use MySQL and [external webserver](https://github.com/webbukkit/dynmap/wiki/External-Webserver-Basics). Use php-fpm to load php files, use nginx to load all other (static) files.

- [x] *I have looked at all other issues and this is not a duplicate*
- [x] *I have been able to replicate this*
Tried a second fresh install using latest Paper (build 24), but the file was not created again.

**Comment by controlol** [comment]
Adding the config file like it was in the 1.16 version allows the dynmap to function properly. 
Unfortunately the files get updated when the server restarts, thus it is removed again.

```php
<?php
$dbname = 'mc';
$dbhost = 'mariadb';
$dbport = 3306;
$dbuserid = 'user';
$dbpassword = 'xxxx';
$dbprefix = 'map118';
$loginenabled = false;
?>
```

**Comment by generrosity** [comment]
From the Discord: 

Please be patient as we update the plugin. We do not have an eta for the full release at this time.
NOTE These are experimental and there will likely be bugs and missing features. Please follow announcement-updates for the most up-to-date information on Dynmap's update status.

https://github.com/webbukkit/dynmap/issues/3538

**Comment by controlol** [comment]
I understand, this was a bug report, not a "fix now please" :)

**Comment by mikeprimm-triva** [comment]
Set disable-webserver: true
The PHP support isn't enabled while the internal web server is still enabled.

**Comment by controlol** [comment]
This solved the issue thanks! 

The missing file is now created when the server starts

Updated the wiki to add this information.
https://github.com/webbukkit/dynmap/wiki/External-Webserver-Basics/_history
