### ISSUE TITLE
1.18 - Forge crash on Player join

### ISSUE THREAD

**Issue by Pokihead** [webbukkit/dynmap#3546]
**Issue Description:** *Dynmap is crashing my Forge 1.18 server at them moment someone wants to join the server. 
Without Dynmap it is working and Dynmap is the only installed mod on the server. Client was clean Vanilla 1.18*

* **Dynmap Version:** *Dynmap 3.3 Snapshot Forge, from 2021-12-02*
* **Server Version:** *forge 1.18 build 38.0.12*
* **Pastebin of Configuration.txt:** *https://pastebin.com/kSAKicGA*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/vDhySMJC*
* **Other Relevant Data/Screenshots:** **
* **Steps to Replicate:** *Just start a server with dynmap and forge and join it. It is always crashing for me^^*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by generrosity** [comment]
From the Discord:
Please be patient as we update the plugin. We do not have an eta for the full release at this time.
NOTE These are experimental and there will likely be bugs and missing features. Please follow announcement-updates for the most up-to-date information on Dynmap's update status.

https://github.com/webbukkit/dynmap/issues/3538

**Comment by mikeprimm** [comment]
Fix in recent DEV builds
