### ISSUE TITLE
Suppress updates within a Region

### ISSUE THREAD

**Issue by Plecra** [webbukkit/dynmap#3548]
**Feature Description:** 

I want my players to be able to place marker signs within a `set:hidden`, which should force the map to automatically ignore any structures they build near those signs, instead rendering the area as if it was in its initial generation state.

I'd imagine this could be implemented by creating a `/dmarker addcircle radiusx:20 radiusy:20 set:suppressed_updates`, which will cause all block updates affecting the region to be ignored.

**Comment by FedUpWith-Tech** [comment]
Listed in megathread #3461
