### ISSUE TITLE
Path Tool

### ISSUE THREAD

**Issue by Mark7625** [webbukkit/dynmap#3552]
**Feature Description:** Add a path tool to the Front end that allows you to click on points to make a path around tiles this will be used for overlays on the map

* **Additional context:** 
![alt text](https://media.discordapp.net/attachments/723278222518779946/917645131258155019/unknown.png)
![alt text](https://media.discordapp.net/attachments/723278222518779946/917645087205363762/unknown.png)

**Comment by FedUpWith-Tech** [comment]
This would be a great add-on to Dynmap but a bit outside the scope of what the plugin is designed to do. This would be further complicated with permissions management and tracking who made what changes.
