### ISSUE TITLE
1.18 Fabric Tile Rendering Not Triggered By ChunkGenerate or ChunkPopulate

### ISSUE THREAD

**Issue by tomassurna** [webbukkit/dynmap#3553]
**Issue Description:** *Dynmap does not seem to be rendering tiles of newly generated chunks. Or chunks that were previously generated, and newly visited (no render yet). The tile is only then loaded when a block event update is triggered.*

* **Dynmap Version:** *Dynmap-3.3-beta-1-fabric-1.18*
* **Server Version:** *Fabric 1.18 - Fabric Loader 12.8*
* **Pastebin of Configuration.txt:** *https://pastebin.com/HyuPj3JJ* (Default config file generated)
* **Server Host (if applicable):** *Pebblehost.*
* **Pastebin of crashlogs or other relevant logs:** *n/a*
* **Other Relevant Data/Screenshots:** *n/a*
* **Steps to Replicate:** 

1. Ensure all fullrenders and radiusrenders are canceled*
2. Navigate to any dimension and fly for a few hundred blocks or to newly generated chunks. (you can delete the map prior if one is already rendered to make this easier)
3. Sit and wait to see if the map renders. After some time of nothing happening, place a block down and wait a few minutes. Notice that the single tile is rendered.

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by kosma** [comment]
@mikeprimm Can you assign to me? I will research it because I think I'm also encountering this.

**Comment by mikeprimm** [comment]
@kosma sounds good - please do check it out!

**Comment by database64128** [comment]
I'm also experiencing this on Paper 1.18.1. Dynmap won't render new chunks on its own. For now I'm using `/dynmap updaterender world x z` as a workaround to get new chunks rendered.

**Comment by kosma** [comment]
Fixed in #3567, will be part of next release.

**Comment by kosma** [comment]
![image](https://user-images.githubusercontent.com/1089580/146653347-e39b44d8-87e5-48f0-8d4e-3c433587deb5.png)

**Comment by kosma** [comment]
> I'm also experiencing this on Paper 1.18.1. Dynmap won't render new chunks on its own. For now I'm using `/dynmap updaterender world x z` as a workaround to get new chunks rendered.

If the problem persists on Paper, please submit a separate issue - this one is just for Fabric.
