### ISSUE TITLE
After updating to Spigot 1.18, chunks visited by player disappear on Dynmap

### ISSUE THREAD

**Issue by Cassolotl** [webbukkit/dynmap#3554]
**Issue Description:** Today I updated to Spigot 1.18. I also updated to the latest stable version of Dynmap on [this page](http://dynmap.us/builds/dynmap/). Now, when players log in and visit locations that have been previously correctly rendered on the Dynmap, those chunks disappear. Fullrender also makes the map start to disappear.

Here's chunks vanishing as a player visits them:
<img width="932" alt="Screenshot 2021-12-07 at 23 34 29" src="https://user-images.githubusercontent.com/6607512/145123696-8dafa016-02cb-4efb-ae19-66348d132d00.png">

Here's a fullrender from spawnpoint in progress:
<img width="700" alt="Screenshot 2021-12-07 at 23 46 24" src="https://user-images.githubusercontent.com/6607512/145124222-a4cd95fe-afd0-48d0-a1b3-76b7170b8981.png">
([Here it is on our Dynmap](http://89.34.99.24:8765/?worldname=world&mapname=flat&zoom=1&x=116&y=64&z=46))

* **Dynmap Version:** *3.3-SNAPSHOT-567*
* **Server Version:** *[23:52:14] [Server thread/INFO]: This server is running CraftBukkit version 3336-Spigot-a5dea1c-a008701 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/6KrkLFsT*
* **Server Host (if applicable):** *Nitrous Networks*
* **Pastebin of crashlogs or other relevant logs:** *Nothing relevant in logs*
* **Other Relevant Data/Screenshots:** *Recently updated Spigot server, from 1.17.1 to 1.18. [Here's our Dynmap](http://89.34.99.24:8765/).*
* **Steps to Replicate:**
There's two situations:

1. Log in after updating to 1.18. Go to previously rendered area of the map. Map rendering vanishes online.
2. Update to Spigot 1.18. Run `/dynmap fullrender world`. Tiles that would usually render anew or more accurately are replaced by black squares.

 [I've done my best but the issue titles and descriptions are not average-user-friendly] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by Cassolotl** [comment]
Update:

I've just stopped the server, backed up my configuration.txt and markers.yml, and deleted the entire dynmap folder and .jar.

Then I uploaded the dynmap .jar again and started the server to regenerate the dynmap folder and config and so on. Stopped the server, opened the configuration and changed the default res to lowres, changed the port, and saved. I also replaced the text in the markers.yml file, after checking that there were no big changes between versions.

Then I started the server again, and started a fullrender of world.

```
[13:07:12] [Server thread/INFO]: This server is running CraftBukkit version 3336-Spigot-a5dea1c-a008701 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)
[13:07:12] [Server thread/INFO]: Checking version, please wait...
[13:07:12] [Thread-62/INFO]: You are 16 version(s) behind
[13:07:18] [Server thread/INFO]: dynmap version 3.3-SNAPSHOT-570
[13:07:18] [Server thread/INFO]: Website: https://www.reddit.com/r/Dynmap/
[13:07:18] [Server thread/INFO]: Author: mikeprimm
```

[This is still the address](http://89.34.99.24:8765/), and it looks like this at 15,000 tiles rendered:

<img width="1440" alt="Screenshot 2021-12-08 at 13 06 22" src="https://user-images.githubusercontent.com/6607512/145213434-8085dde2-735c-4ed7-a175-f32f769f75ed.png">

**Comment by mikeprimm** [comment]
I'll confirm this, but I'm 90% sure that the migration of the chunks to 1.18 format by vanilla/spigot is likely resetting the InhabitedTime data in the chunk - we just read that data, we don't synthesize it.

**Comment by mikeprimm** [comment]
When you updated from 1.17.1 to 1.18, did you use the upgrade procedure recommended by Spigot?

**World Upgrading
Although upgrades from between any two version pairs are technically possible, it is recommended that all upgrades are conducted from 1.17.x. This means that you should first upgrade your world completely on 1.17.x using the --forceUpgrade server argument, and then do the same on 1.18.**

**Comment by VeeBack** [comment]
I have the same issue where the map is just blank. Dynmap says it's rendering, but it's just blank. The world is new and was created in 1.18, not migrated from a different version.

**Comment by mikeprimm** [comment]
Not sure what else you have in the mix, but clearly we and the rest of the folks using this aren't seeing this.  What plugins do you have in the mix?

**Comment by mikeprimm** [comment]
OK - I'm seeing this with current DEV build, but not with the released 3.3-beta-1, so I'd suggest using that for now (since it is, well, released...)
DEV (SNAPSHOT) build go from working to not on a regular basis while I'm doing development, so its generally not safe to count on them unless I specifically say they are ready to be used...

**Comment by mikeprimm** [comment]
That said, thanks for bringing this up - I'm not completely sure WHY it isn't working, so this is useful data :)

**Comment by mikeprimm** [comment]
OK - latest DEV build should have this fixed again:  build number 571 (or later).

**Comment by Cassolotl** [comment]
```
[09:29:52] [Server thread/INFO]: This server is running CraftBukkit version 3336-Spigot-a5dea1c-a008701 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)
[09:29:52] [Server thread/INFO]: Checking version, please wait...
[09:29:53] [Thread-62/INFO]: You are 17 version(s) behind
[09:30:05] [Server thread/INFO]: dynmap version 3.3-SNAPSHOT-572
[09:30:05] [Server thread/INFO]: Website: https://www.reddit.com/r/Dynmap/
[09:30:05] [Server thread/INFO]: Author: mikeprimm
[09:30:23] [Server thread/INFO]: Plugins (7): PermissionsEx, CoreProtect, dynmap, AutismChat3, Seen, PvPManager, GriefPrevention
```

* [PermissionsEx](https://github.com/PEXPlugins/PermissionsEx/releases)
* [CoreProtect](https://www.spigotmc.org/resources/coreprotect.8631/)
* dynmap
* [AutismChat3](https://github.com/RichardsProjects/AutismChat3)
* [Seen](https://dev.bukkit.org/projects/seen)
* [PvPManager](https://www.spigotmc.org/resources/pvpmanager-lite.845/)
* [GriefPrevention](https://github.com/TechFortress/GriefPrevention)

It seems to be working now, but I had to hard-reload [the Dynmap page](http://89.34.99.24:8765/) to get the tiles to show, for some reason! And now that the tiles are regenerating, once again some of the areas where players have newly explored on 1.18 are showing up as black:

<img width="381" alt="Screenshot 2021-12-09 at 09 44 54" src="https://user-images.githubusercontent.com/6607512/145372652-0fa47168-bb84-4c4f-88a6-0845f9ea8f03.png">

This whole area should be map, there should be no black patches, we've explored the area very thoroughly. The black square is my base, where I've spent the most time.

>When you updated from 1.17.1 to 1.18, did you use the upgrade procedure recommended by Spigot?

Unclear - I was on 1.17.1 before, and I used the update function on Nitrous Networks. I have no idea what's happening behind the scenes.

>I'm seeing this with current DEV build, but not with the released 3.3-beta-1, so I'd suggest using that for now (since it is, well, released...)

Since I've tried the new DEV and it's not working, I'm switching to the 3.3-beta-1. I'll let you know what happens.

**Edit:** Switched to 3.3-beta-1, running `/dynmap fullrender world`. [Map](http://89.34.99.24:8765/).

```
[09:50:07] [Server thread/INFO]: dynmap version 3.3-beta-1-564
[09:50:26] [Server thread/INFO]: This server is running CraftBukkit version 3336-Spigot-a5dea1c-a008701 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)
[09:50:26] [Server thread/INFO]: Checking version, please wait...
[09:50:27] [Thread-54/INFO]: You are 17 version(s) behind
```

**Comment by Cassolotl** [comment]
My home base zone is starting to render!

**Comment by Cassolotl** [comment]
Things *are* rendering but *much* slower than usual, and in a kind of spotty way. :S

**Comment by ArctonLin** [comment]
Same problem on spigot 1.18.1 with Dynmap-3.3-beta-2-spigot.jar and Dynmap-3.3-SNAPSHOT-spigot.jar (578)
I am upgrade from 1.17.1 to 1.18.1, all player visted chunk may cause blank map on dynmap.
I only use fullrender to rendering map. (start from 0am to 10am)
Player may not trigger render while playing. (by disable all trigger option)
I think this is a problem related to fullrender on new chunk.
All old chunk is rendering without problem.
Should I submit new ticket for 1.18.1?
 
My map link: http://cargon.net:8123/

**Comment by ArctonLin** [comment]
I have found a workaround solution...
Using radiusrender can rendering new chunk without problem.
 
/dynmap radiusrender world -2863 -2965 100
![image](https://user-images.githubusercontent.com/17915913/145946893-3b90d041-45eb-4cc6-a685-0531df9a55e2.png)
My Dynmap: http://cargon.net:8123/
 
Please fix fullrender when mixing old chunk and new chunk.
Thank You!!

**Comment by ArctonLin** [comment]
The issue is presist even using radiusrender: /dynmap radiusrender world 0 0 1000
I found the issue is related to the border of new chunk (1.18.1) and old chunk (1.17.1)
 
Here is the map I tried to rendering: /dynmap radiusrender world -151 994 1000
Rendering start from new chunk (1.18.1) and when the render touch old chunk (1.17.1) may cause problem.
 
![image](https://user-images.githubusercontent.com/17915913/145950213-5cf03dd7-8280-474a-951f-608a57ab7a8a.png)
This image shows that when it rendering new chunk with minimum z=-64 and reach old chunk with minimum z=0 may stop rendering remaining old chunk.
 
So the problem is related to the border of new chunk and old chunk.
 
If you start radiusrender on new chunk... It may render all nearby new chunk. but old chunk may not being render correctly.
When radiusrender start from old chunk may not render new chunk correctly.

**Comment by ArctonLin** [comment]
Now, the problem is clear.
The border between new chunk(1.18.1) and old chunk(1.17.1):
![image](https://user-images.githubusercontent.com/17915913/145952538-ae8a1295-15ab-4d53-bc17-3c396a92290f.png)
Player visted area may update to 1.18.1 chunk. The border is about 180 blocks wide...
