### ISSUE TITLE
1.18: Topo map render results in a ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by minifisch** [webbukkit/dynmap#3555]
**Issue Description:**
*When starting to render a topo map the server crashes with a ArrayIndexOutOfBoundsException: Index -6 out of bounds for length 256*

* **Dynmap Version:** *core=3.3-beta-1-564, plugin=3.3-beta-1-564*
* **Server Version:** *paper 1.18, build 59*
* **Pastebin of Configuration.txt:** *https://pastebin.com/ydeYhqyS*
*  **Pastebin of worlds.txt:** *https://pastebin.com/UP0prUs2*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/FxGY1NNh*
* **Other Relevant Data/Screenshots:** *Map is from 1.17, converted partially to 1.18, tried also on a new 1.18 world, see description below at "replicate"*
* **Steps to Replicate:** *Create a topographic map of a world and start a fullrender.*

 [x] *I have looked at all other issues and this is not a duplicate*  

 [x] *I have been able to replicate this*
Spun up a fresh 1.18 world with paper 1.18 and dynmap 3.3-beta-1-564 with the same config as above.
Started a fullrender and after a short while the server crashed with the same error.

**Comment by MindStudioOfficial** [comment]
I have the same Issue. Found out that the TopoHD shader only accounts for Y levels 0 to 256 instead of the new -64 to 320 which causes the array out of bounds

**Comment by MindStudioOfficial** [comment]
Should be fixed now in new 3.3 Beta 2 release

Edit: I still get the error in the 3.3 Beta 2 release

**Comment by mikeprimm** [comment]
Wasn't fixed in the beta - was fixed one build AFTER the beta - test with a SNAPSHOT
