### ISSUE TITLE
[1.18 PaperSpigot] DynMap "Zooming In" generated chunks

### ISSUE THREAD

**Issue by LuzrodGaming** [webbukkit/dynmap#3560]
Hi there, before updating to 1.18, there was no problem with Dynmap.

Since then, I encounter a problem where dynmap is kinda zomming in generated chunks.

Before updating my server and Dynmap to 1.18, I used Minecraft's optimizer for all the chunks on the map

As you can see on the screenshot, the chunks at the left of my worldborder (which is on 10kx10k) were generated at about -10k on the x axis ; but in DynMap, these are located at -20k on the x axis.

![image](https://user-images.githubusercontent.com/62514761/145728984-a27b7da1-e5e0-4ad0-810d-b016fafab456.png)

I use MySQL Database to store up all the tiles.

I tried several times to purge all the map, deleting them from the DB and uninstalling & reinstalling DynMap, but the issue is still there.

**Comment by JurgenKuyper** [comment]
10k + 10k is 20k right? seems right that 10k out of the border is location 20k on the x axis

**Comment by generrosity** [comment]
Im not quite understanding the term "zomming in generated chunks" - if there have been changes to zoom levels or most other configuration and world options, then you need to purge and render again as the previous tiles will still be around and/or remembering the previous zoom settings maybe?

This area in particular looks similar to the known issues with having 1.17 and 1.18 chunks in the same map - typically resolve with running "--forceupgrade" on the server - not sure if thats different to optimizer. You could check with a map viewer like Amulet to see if the chunk has extra height or not
![image](https://user-images.githubusercontent.com/12838061/145916297-31df307a-2a71-4d04-9d1a-9622b2aaddf9.png)

**Comment by FedUpWith-Tech** [comment]
If you are on shockbyte it is because they changed the resolution.
If you are not on shockbyte you likely changed the resolution of the map after some of it rendered which results in the two-different levels of zoom
