### ISSUE TITLE
How do i make dynmap run on my own domain name? i want it to be map.example.com

### ISSUE THREAD

**Issue by sexibatka** [webbukkit/dynmap#3564]

**Comment by JurgenKuyper** [comment]
add an A record to the IP, but you cannot hide the port. if you want to hide the port you need to reverse-proxy it to 80 for http or 443 for https. if not using reverse-proxy it should look like http://map.example.com:8123

**Comment by sexibatka** [comment]
how do i use reverse proxy on it?

**Comment by generrosity** [comment]
A reverse proxy is a seperate program that takes web requests, and can do magic to them to hide what is behind. A lot of the time, people either use Apache to reverse proxy, or just provide links with the port as it gets too hard.

Its a bit beyond the scope of dynmap itself - there are soooo many ways of doing it.

Here is one online howto; Apache - https://serverfault.com/questions/799012/dynmap-through-mod-proxy-on-a-external-webserver

**Comment by sexibatka** [comment]
> A reverse proxy is a seperate program that takes web requests, and can do magic to them to hide what is behind. A lot of the time, people either use Apache to reverse proxy, or just provide links with the port as it gets too hard.
> 
> Its a bit beyond the scope of dynmap itself - there are soooo many ways of doing it.
> 
> Here is one online howto; Apache - https://serverfault.com/questions/799012/dynmap-through-mod-proxy-on-a-external-webserver

thanks a lot :D
