### ISSUE TITLE
1.18.1 : Crash on stratup

### ISSUE THREAD

**Issue by julienallexandre** [webbukkit/dynmap#3566]
**Issue Description:** *I put the plugin in the plugins folder and I have this error*

* **Dynmap Version:** *Dynmap-3.3-beta-2-spigot*
* **Server Version:** *1.18.1-R0.1-SNAPSHOT*
* **Server Host (if applicable):** *Inovaperf*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/BfzRRJ8r*

**Comment by JurgenKuyper** [comment]
re upload the plugin and try again

**Comment by julienallexandre** [comment]
it's the same

**Comment by JurgenKuyper** [comment]
redownload from https://www.spigotmc.org/resources/dynmap%C2%AE.274/

**Comment by julienallexandre** [comment]
always the same

**Comment by JurgenKuyper** [comment]
check the hash of the file to be the same as: 
![image](https://user-images.githubusercontent.com/45831568/146176071-d0b46953-71e6-48f7-ae83-68cf0ee7e90d.png)
if not, delete the file and redownload, if that doesn't help, backup and delete the dynmap folder and reupload

**Comment by julienallexandre** [comment]
MD5 (Dynmap-3.3-beta-2-spigot.jar) = 45422ce737e6f0e36cc0cc43c3e46fb0

<img width="502" alt="Capture d’écran 2021-12-15 à 12 49 33" src="https://user-images.githubusercontent.com/58303569/146181360-2b58298e-fca7-4c45-9e95-cd2da7b51257.png">

**Comment by julienallexandre** [comment]
I found a technique actually I installed "Dynmap-3.3-beta-1-spigot.jar" which created the folder "dynmap" in plugins and then I replaced the jar with "Dynmap-3.3-beta-2-spigot.jar" and it works, but if I don't have the folder in plugins it does not work
