### ISSUE TITLE
nether map crash bug

### ISSUE THREAD

**Issue by husitko** [webbukkit/dynmap#3568]
**Issue Description:** *When i have everyhing on default or "hires" when 2 or more players entering/exiting nether it just crash server.
caused by nethermap when i disabled it like u have cave in your DC it worked it doesnt crash now. Tried on vanilla fabric/forge without additional mods same result in crashlogs you have full log of server from simulated time when it crashed ... but it doesnt have any crash reports ...*

* **Dynmap Version:** *Dynmap-3.3-beta-1-fabric-1.18*
* **Server Version:** *fabric 0.44.0+1.18 IDK exactly lastest from 05/12/2021 USED FABRIC INSTALLER 0.10.1*
* **Pastebin of Configuration.txt:** *Default*
* **Server Host (if applicable):** *Linux ubuntu.* also tried it on my localhost Windows 10 same problem
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/DgbXVqc9*
* **Other Relevant Data/Screenshots:** *There is nothing server just shuts off java still runing*
* **Steps to Replicate:** *install vanilla dynmap on forge or fabric and make 2 or more players go trough nether portal at not long time (1-2s or faster) and go go go and server will crash*

* **Specs of Linux : 8GB ram 4 cores from AMD EPYC™ 7742
* **Windows (localhost) 32GB ram Ryzen 7 2700x
 
 [Y] I have looked at all other issues and this is not a duplicate*  
 [Y] I have been able to replicate this*

**Comment by husitko** [comment]
Update when i did purge ... i goes to sleep when i woke up and watch dynmap nether was rendered ... more in video
https://youtu.be/fEb4QFRj_ko
Sorry for lagy quality i forgot to stop mining when i was recording but everything is in

**Comment by mikeprimm** [comment]
Crash log should include information about the crash - your log is clean, and does not indicate a problem, much less anything implying a dynmap issue...

Also, beta-2 has been released for a week now, so any problems with beta-1 are not likely to be considered for further investigation until they are seen to be present in the latest supported release (beta-2 now, beta-3 will be out later this weekend)

**Comment by mikeprimm** [comment]
3.3-beta-3 is now released - please use this one, and include logs that support information about the reported crash, and suggest why dynmap is involved, beyond the fact that any mod adds to the memory use.  Also, your JVM flags might be relevant, since they can impact server memory independent of the size of the memory on the box being used.

**Comment by husitko** [comment]
thanks will try it server is starting by java -Xmx8G -jar fabric-server-launch.jar nogui as default and when i tried full ram of my gaming PC instead of VPS server i used java -Xmx25G -jar fabric-server-launch.jar nogui

**Comment by FedUpWith-Tech** [comment]
> thanks will try it server is starting by java -Xmx8G -jar fabric-server-launch.jar nogui as default and when i tried full ram of my gaming PC instead of VPS server i used java -Xmx25G -jar fabric-server-launch.jar nogui

If your server has only 8GB allocated to it and you allocate 8GB  to java for the minecraft server of course it is going to crash. I suggest leaving 2GB of RAM free. `java -Xmx6G -jar fabric-server-launch.jar nogui`
