### ISSUE TITLE
Black outline on Fabric / unpopulated / unlit chunks are rendered

### ISSUE THREAD

**Issue by DyonR** [webbukkit/dynmap#3574]
**Issue Description:** *Dynmap (Fabric) seems to render chunks of unpopulated chunks and not fully generated lighting generated chunks, causing a dark outline around the map*

* **Dynmap Version:** *3.3-SNAPSHOT-599*
* **Server Version:** *fabric 0.44.0+1.18, Minecraft 1.18.1 with Fabric Loader 0.12.11*
* **Pastebin of Configuration.txt:** *does not apply*
* **Server Host (if applicable):** *Selfhosted.*
* **Pastebin of crashlogs or other relevant logs:** *does not apply*
* **Other Relevant Data:**  
*Seems to apply to all dimenstions and perspectives*
I am fairly sure this issues started after this PR was merged; https://github.com/webbukkit/dynmap/pull/3567 as an fix for https://github.com/webbukkit/dynmap/issues/3553

* **Screenshots:**
![image](https://user-images.githubusercontent.com/16341409/146810426-881e9fda-46e9-452f-bea6-d5e34104126b.png)
![image](https://user-images.githubusercontent.com/16341409/146813608-07e0794d-4030-4efb-aedd-a3f77861e825.png)

* **Steps to Replicate:**
*Just run a Fabric server with Dynmap and check the flat map.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by kosma** [comment]
Possibly the same problem as #3565?

**Comment by kosma** [comment]
And to elaborate: that PR fixed the chunk generation detection - perhaps DynmapCore previously just didn't know about those not-fully-generated chunks. I'd wager this is a DynmapCore problem.

**Comment by DyonR** [comment]
> Possibly the same problem as #3565?

Later on in that issue the author indeed seems to experience the same as I have; https://github.com/webbukkit/dynmap/issues/3565#issuecomment-995543724  
  
I didn't full scroll through that issue so that's my bad, and to be fair it also does diviate from the original reported issue.

**Comment by mikeprimm-triva** [comment]
Give latest snapshot (600) a try - it's more pessimistic about chunks that are supposed to have light data actually having light...

**Comment by DyonR** [comment]
> Give latest snapshot (600) a try - it's more pessimistic about chunks that are supposed to have light data actually having light...
  
I removed the whole flat map of my server and did a new render for it. It seems like it did a little but on a few places, but it's still not fixed. I will try it on an actual clean server later.  

![Naamloos](https://user-images.githubusercontent.com/16341409/147240253-cf879ea4-20f5-4ee7-b78f-e3bd72a1c051.png)
The image above is the exact same size and location as the one in the issue when posted, except a bit more terrain got discovered or visited.

**Comment by DyonR** [comment]
Snapshot 605, new world, issue presists
![image](https://user-images.githubusercontent.com/16341409/147296374-dc631e1a-4412-4812-97df-51e64c074cb1.png)

**Comment by ArctonLin** [comment]
problem presist on snapshot 606
http://dynmap.cargon.net/?worldname=world&mapname=surface&zoom=4&x=-4705&y=64&z=3076

**Comment by mikeprimm** [comment]
Same as #3565
