### ISSUE TITLE
Purpur bug

### ISSUE THREAD

**Issue by zentixua** [webbukkit/dynmap#3578]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *If you are using purpur 1.18.1, the text "Minecraft Dynamic Map" is displayed in the title of the tab with the dynmap map. Everything is fine with paper.*

* **Dynmap Version:** *v3.3-beta-3*
* **Server Version:** *purpur 1.18.1*
* **Pastebin of Configuration.txt:** *https://pastebin.com/MCeHT3rY*
* **Server Host (if applicable):** *Home host*
* **Other Relevant Data/Screenshots:**
*![image](https://user-images.githubusercontent.com/65168490/147408476-5aa7c907-282a-49d7-98dc-ea20e3faf3af.png)*
* **Steps to Replicate:** 
*1.Install purpur
  2. Install dynmap
  3. You will see the wrong name of the map in the browser
*

 [ + ] *I have looked at all other issues and this is not a duplicate*  
 [ + ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Not a bug, you can change the title in webserver-title in configuration.txt
