### ISSUE TITLE
Some chunks are not able too see when zoomed out link: fierce-fifth.auto.playit.gg:51771

### ISSUE THREAD

**Issue by Baju8** [webbukkit/dynmap#3581]
Hello, I host a 1.18.1 spigot server with dynmap. Everithing works fine but when dynmap renders world its good but just two little areas are not able too see if your not zoomed in really much.  Its not fully rendered but it seems only the two areas are not properly rendered
If it needs to render full map and then it will rerender the broken areas ok just tell im not skilled really much in dynmap.
Here is my dynmap. 
![Dynmap](https://user-images.githubusercontent.com/71509078/147645063-73f910a0-05c8-40b8-b105-13ed0d840b61.png)

**Comment by Baju8** [comment]
![image](https://user-images.githubusercontent.com/71509078/147645115-c988c390-e18e-4157-a66f-73696128d379.png)
Its not that big problem but  if its possible i would like to have it fully rendered and i have been rendering world with worldborder.

**Comment by JurgenKuyper** [comment]
check if a `/dynmap radiusrender 100 surface` in the black spots fixes the problem

**Comment by Baju8** [comment]
Oh thanks really really much
im gonna try.

**Comment by Baju8** [comment]
Thanks again
