### ISSUE TITLE
output render progress to console for renders started via Rcon

### ISSUE THREAD

**Issue by DefectiveNu** [webbukkit/dynmap#3582]
**Feature Description:** Make commands issued via Rcon behave like they were entered via the console.  Currently, if you issue a command like radiusrender via Rcon you will get the message that the render started, but status updates seem to go nowhere

**Comment by JurgenKuyper** [comment]
What if you use the syntax as if you were on console, like add the world and map?

**Comment by FedUpWith-Tech** [comment]
This is default minecraft server behavior and isn't Dynmap specific. 

There's no way to implement this within the bounds of the RCON protocol
