### ISSUE TITLE
ConcurrentModificationException / DynmapTowny incompatibility

### ISSUE THREAD

**Issue by ewof** [webbukkit/dynmap#3583]
**Issue Description:** Dynmap with Dynmap towny produces a ConcurrentModificationException which lags/crashes the server

* **Dynmap Version:** 3.3-beta-4
* **Server Version:** Paper 1.17.1
* **Pastebin of Configuration.txt:** [*https://pastebin.com/5SETL3z2*](https://pastebin.com/vGX1790G)
* **Server Host (if applicable):** selfhosted
* **Pastebin of crashlogs or other relevant logs:** [*https://pastebin.com/crashcausedbydynmap*](https://ghostbin.com/2y0D7/fish)
* **Steps to Replicate:** Install dynmap and dynmap towny

 [Yes] *I have looked at all other issues and this is not a duplicate*  
 [Yes] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
This is a known issue with dynmap addons that create markers (towny, worldgaurd, factions). What's new about this is it actually crashes the server.

**Comment by ewof** [comment]
is there any plan to fix?

**Comment by mikeprimm** [comment]
Calls being made from off server thread aren't supported (and this looks to be an async task call) - never have been, since in general the Spigot/Paper API is not thread-safe from off of the server thread (with specific exceptions).

**Comment by ewof** [comment]
what can i do? dynmap towny dev says issue isn't with dynmap towny

**Comment by LlmDl** [comment]
paraphrased at best

**Comment by ewof** [comment]
am not trying to be rude i just dont know what to do

**Comment by ewof** [comment]
I had JsonFileClientUpdateComponent with disable-webserver set to true so i commented it out and works fine now
