### ISSUE TITLE
TexturePackLoader.getEntries does not return added/overridden files for standard texture pack

### ISSUE THREAD

**Issue by hammer065** [webbukkit/dynmap#3584]
**Issue Description:** 
While trying to add CTM files to the standard texture pack, dynmap fails to find the added CTM files.
If I read the source correctly, the bug should result from https://github.com/webbukkit/dynmap/blob/0166895a7fb892af089aa671bd282089fa1abe56/DynmapCore/src/main/java/org/dynmap/hdmap/CTMTexturePack.java#L907 not returning the files which have been added to the folder.
Adding the CTM files + the default Minecraft textures (CTM files from OptiFine, default textures from the Minecraft jar) to a separate zip file and setting this as the texture pack to be used makes it work.

* **Dynmap Version:** core=3.3-beta-3-591, plugin=3.3-beta-3-591
* **Server Version:** git-Paper-110 (MC: 1.18.1)
* **Server Host (if applicable):** Selfhosted
**Steps to Replicate:**
1. Put custom files (in my case CTM files) in `dynmap/texturepacks/standard/assets/minecraft/optifine/ctm/`
2. Restart the server
3. Re-render a glassy part of the map

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by generrosity** [comment]
Only CTM v1 is supported.  Newer forms of CTM is not supported, and currently on the "will not impliment" list

**Comment by hammer065** [comment]
The error is _not_ that the CTM-files themselves are broken; they actually work just fine, even with Dynmap (as stated with my first sentence).

The mentioned and _actual_ problem is, that the given line of code will return no entries, even when they have been copied to the “standard” folder, as the README.txt itself states should work just fine as it’s supposed to be an overlay.

My current workaround to that problem is by extracting the standard texture pack included in the given Dynmap jar, add the files and re-pack it to a zip and setting this “custom” texture pack inside the config.

**Comment by generrosity** [comment]
I understood that, but CTM v2 included more features that aren't implimented, potentially including having different folder names.

You are still using a CTM feature afaik, not a vanilla one, and its not supported? Does that make sense?
