### ISSUE TITLE
Cannot use Dynmap commands, I am OP and have Perms

### ISSUE THREAD

**Issue by Momentusm** [webbukkit/dynmap#3589]
**Issue Description:** *Cannot do Dynmap commands so cannot render map, permissions still exist/can be added/found*

* **Dynmap Version:** *dynmap-3.3-beta-4-spigot*
* **Server Version:** *Spigot 1.18.1*
* **Pastebin of Configuration.txt:** *https://pastebin.com/ZJ70ZwGp*
* **Server Host (if applicable):** *Selfhosted*
* **Other Relevant Data/Screenshots:** *I'm using plugins: BetterMobs, Coreprotect, Dynmap, EssentialsX, FactionUUID, ImageMaps, LuckPerms, Staff+, Vault, Vehicles, VehiclesWorldguardFlags, Worldedit, WorldGuard.*
* **Steps to Replicate:** *1. Server start, 2. Login 3. /dynmap [anything] 4. "commands arent currently working"*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Can you send the latest.log? Use https://mclo.gs/ to hide ips

**Comment by Momentusm** [comment]
> Can you send the latest.log? Use https://mclo.gs/ to hide ips

My logs are bugged but I just found an error from the plugin. It tells me to go to yamllint,com to check for errors in the config
It showed me what the problem was, there wasnt a space between the **sendhealth:** option and the answer to the option
After fixing this everything works
