### ISSUE TITLE
HandlerRouter.java uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by kosma** [webbukkit/dynmap#3590]
There is a warning from the compiler when building the source on Adoptium 17 JDK:

```
> Task :DynmapCore:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\kosma\IdeaProjects\dynmap\DynmapCore\src\main\java\org\dynmap\web\HandlerRouter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

Additionally `PathMap` itself is showing deprecation warnings. I am myself sadly not good enough in Java to fix this. This is a part of my small effort to get rid of all compile warnings so the real compile warnings won't be as easily ignored. :)

* **Dynmap Version:** v3.0
* **Steps to Replicate:** `gradlew build`

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
Added suppress warning to component.  It's pointless to worry about deprecation when the web server with the deprecated classes doesn't update until we decide to update it....
