### ISSUE TITLE
Grid visible on QHD monitor

### ISSUE THREAD

**Issue by GrymoCZ** [webbukkit/dynmap#3596]
Hello, I found this issue that the grid is showing on my 2560x1440 QHD monitor. It doesn't show up on my second FHD monitor.
![image](https://user-images.githubusercontent.com/68050808/148212818-a1fb1d8f-b293-407c-8234-d74d5dfc5900.png)

**Comment by JurgenKuyper** [comment]
That's because of a problem / bug in the leaflet.js dynmap uses, we unfortunately cannot fix this issue untill leaflet updates their library.
