### ISSUE TITLE
How setup plugin on server with mods?

### ISSUE THREAD

**Issue by galaxyandrew** [webbukkit/dynmap#3600]
I have i server with mods + plugins , if i setup dynmap it doesn't work !!!! How to setup it????

**Comment by Jcodeerd** [comment]
https://github.com/webbukkit/dynmap/wiki/Installation

**Comment by JurgenKuyper** [comment]
You need to use the forge version, not the plugin, the rest is the same as always, on the page sent by Jcodeerd.
