### ISSUE TITLE
Web Adress Problem

### ISSUE THREAD

**Issue by Peterowski** [webbukkit/dynmap#3604]
**Issue Description:** *I have a normal server ip in properties, and when I enter the address 192.168.1.10:8123 it works, but my friends don't, what should I do?.*

* **Dynmap Version:** *Dynmap-3.3-beta-4-spigot*
* **Server Version:** *spigot 1.18*

**Comment by JurgenKuyper** [comment]
you need to open a port in your router panel, and give your friends your external IP to connect to, found by googling whats my ip.

**Comment by Peterowski** [comment]
> you need to open a port in your router panel, and give your friends your external IP to connect to, found by googling whats my ip.

 So I understand correctly that I need to add TCP / UDP port **8123** or another port in my config to the router, and then use _What is my IP?_ and send it to my friends with the ending _:8123_ (or another)?


P.S. Thank you!

**Comment by JurgenKuyper** [comment]
Exactly, so if your external IP is 40.56.30.17, then the full link would be `http://40.56.30.17:8123` by default, and if you allowed TCP port 8123 through your router.

**Comment by Peterowski** [comment]
> Exactly, so if your external IP is 40.56.30.17, then the full link would be `http://40.56.30.17:8123` by default, and if you allowed TCP port 8123 through your router.

Thanks!
