### ISSUE TITLE
Most sets/regions not displaying on map but working ingame

### ISSUE THREAD

**Issue by Vidcom** [webbukkit/dynmap#3605]
**Issue Description:** *Our markers.yml file does not seem to work as intended since we updated from 1.17.1 to 1.18.1. The browser map does not show the vast majority of regions or icons, and does not display most of the sets, but still shows some sets as well as sets that are incomplete. Ingame, greeting/farewell messages still show for regions that are not appearing on the map. We are not sure how to fix this and have tried to clean up the markers.yml file on a backup server to no avail.*

* **Dynmap Version:** *3.3 beta 4 617*
* **Server Version:** *Paper 1.18.1-142*
* **Pastebin of Configuration.txt:** *https://pastebin.com/ACPWVPdd*
* **Server Host (if applicable):** *self hosted Ubuntu Server 21.10*
* **Pastebin of crashlogs or other relevant logs:** *N/A*
* **Other Relevant Data/Screenshots:** *Markers.yml (https://pastebin.com/sQB3MCZu). We also tested on Spigot/Win11 with the same bug replicating.*
* **Steps to Replicate:** *Use these files on any map.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by stereoknife** [comment]
Adding the log for dynmap web, it seems it fails at adding a polygon but I haven't identified anything in the markers file that causes the failure.

```
[Error] TypeError: undefined is not a constructor (evaluating 'new L.MultiPolygon(polylist, style)')
	create3DOutlineLayer (markers.js:352)
	createArea (markers.js:185)
	(anonymous function) (markers.js:65)
	each (jquery-3.5.1.js:387)
	(anonymous function) (markers.js:61)
	each (jquery-3.5.1.js:387)
	(anonymous function) (markers.js:34)
	success (jquery.json.js:82)
	(anonymous function) (jquery.json.js:19)
	fire (jquery-3.5.1.js:3496)
	fireWith (jquery-3.5.1.js:3626)
	done (jquery-3.5.1.js:9786)
	(anonymous function) (jquery-3.5.1.js:10047)
```

**Comment by stereoknife** [comment]
Actually, removing areas with height fixed the issue. There's a problem with rendering 3D areas which is causing the renderer to fail while processing the markers file and it's not able to recover from there.

**Comment by mikeprimm** [comment]
I'll look at this over the weekend - the 'upgrade' to a newer version of Leaflet broke a lot of things....
