### ISSUE TITLE
Command to force regenerate zoomout tiles

### ISSUE THREAD

**Issue by colehammond65** [webbukkit/dynmap#3606]
**Feature Description:** *Command to force regenerate zoomout tiles. Pretty self-explanatory, I think it would be helpful if we had a command(s) to force regenerate zoomout tiles. Personally I have been affected by the issue related to mySQL storage type [as seen here](https://github.com/webbukkit/dynmap/issues/3182) and it would be easy to fix if we could do say `/dynmap zoomoutradiusrender world radius x y` to force those zoomout tiles to render.

**Comment by generrosity** [comment]
I think I saw this conversation on Discord - you can do a radiusrender and get the cooresponding zoomout tiles to re-render. I don't think there is the demand for only triggering zoomouts (ie workarounds for errors, full render is unfortunately the usual 'fix')
