### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by PhoenixSK1** [webbukkit/dynmap#3608]
After the Dynmap is successfully installed on the server, no command can be used. I have tried all the commands that exist for this plugin but the same message "unknown chapter" is always displayed. I tried to write commands via the console, but the same thing still appears. I am attaching a log to show that the plugin is installed correctly and running without any problems

https://pastebin.com/RLYWxK4s

And yes, it doesn't really matter which version I use at the moment ... For every one there is the same problem from "v3.3-beta-1" to "v3.3-beta-4"

**Comment by FedUpWith-Tech** [comment]
What server version are you running

**Comment by PhoenixSK1** [comment]
> 

1.18.1 Paper

I tried removing the LuckPerms plugin to make sure there was no problem with that plugin but unsuccessfully.

**Comment by FedUpWith-Tech** [comment]
can you upload the error for 3.3beta4?

**Comment by PhoenixSK1** [comment]
> 

Yes I can, I don't have a problem with that but I don't think it will be necessary. The same thing will happen as with this version. I tried them all and I finished this and decided to write here. In any case, the log was the same without any problems

**Comment by FedUpWith-Tech** [comment]
I understand that, we've never seen this issue before on paper so it would help for me to see that this issue occurs on the latest version of Dynmap so we can start looking at things that aren't Dynmap related as to why this isn't working

Dynmap v3.3beta4 and paper 1.18.1 work on their own so if it is not working in your case then there is some external factor causing Dynmap to fail. Additionally, I would recommend you run 3.3beta4 as it fixed many many issues found in the earlier beta versions and I don't want another issue filed for a bug that could have been solved by updated.

**Comment by PhoenixSK1** [comment]
> I understand that, we've never seen this issue before on paper so it would help for me to see that this issue occurs on the latest version of Dynmap so we can start looking at things that aren't Dynmap related as to why this isn't working
> 
> Dynmap v3.3beta4 and paper 1.18.1 work on their own so if it is not working in your case then there is some external factor causing Dynmap to fail. Additionally, I would recommend you run 3.3beta4 as it fixed many many issues found in the earlier beta versions and I don't want another issue filed for a bug that could have been solved by updated.

https://pastebin.com/pPWLB0QA log with latest version

**Comment by FedUpWith-Tech** [comment]
What's the issue? I don't see an error with the logs. There is no essentials info for this plugin

**Comment by PhoenixSK1** [comment]
> What's the issue? I don't see an error with the logs. There is no essentials info for this plugin

Lines 29 and 30 - same problem with broken command. I think something of that Dynmap block but I'm not able to figure out what. "Neznáma kapitola" is "Unkown chapter"

**Comment by FedUpWith-Tech** [comment]
The essentials info command has nothing to do with Dynmap

**Comment by PhoenixSK1** [comment]
The problem has been fixed. For some reason, the "commands.yml" file contained what is also on the screen. Once fixed, the problem is fixed and everything works. Well, I definitely 100% rule out that I would enter this command because I don't use the "commands.yml" file by any means. 

https://ctrlv.sk/gc7n
