### ISSUE TITLE
Builds at Y≥304 get cut off

### ISSUE THREAD

**Issue by nshire** [webbukkit/dynmap#3613]
**Issue Description:** *Builds at Y≥304 get cut off*

* **Dynmap Version:** *3.3-SNAPSHOT-643*
* **Server Version:** *Paper-162 (MC: 1.18.1)*
* **Pastebin of Configuration.txt:** *https://gist.github.com/nshire/ef575de11ec23980d308629fecd8f2da*
* **Server Host (if applicable):** *Selfhosted*
* **Other Relevant Data/Screenshots:** *Note that in my screenshots, the dirt at Y=303 gets rendered but the gravel at Y=304 does not. Issue is present in the flat and isometric views.*

<img width="728" alt="dynmap not showing above y303" src="https://user-images.githubusercontent.com/26775827/150057975-dce02306-c90a-4792-8b1d-304de633273e.png">

![2022-01-18_19 13 00](https://user-images.githubusercontent.com/26775827/150058052-bfd09ea7-6789-44b3-b522-79e28a9f75c3.png)

**Comment by mikeprimm** [comment]
Found off-by-one error that caused top section (16 block cube) to not be loaded.  Will be fixed in SNAPSHOT #647 or later
