### ISSUE TITLE
Bell texture error

### ISSUE THREAD

**Issue by FedUpWith-Tech** [webbukkit/dynmap#3614]
Another texture error to track: Bells
3D:
![image](https://user-images.githubusercontent.com/7731191/150171618-4df3a404-20a4-4cd3-945d-edae507a9c8b.png)
Flat:
![image](https://user-images.githubusercontent.com/7731191/150171645-d3c32b2b-5759-4229-93c0-e8e00a1cb2e9.png)

**Comment by mikeprimm-triva** [comment]
Fix will be in SNAPSHOT 648+

**Comment by generrosity** [comment]
Confirmed bell working, beta-657 👌
![image](https://user-images.githubusercontent.com/12838061/150702435-d645d41b-7ee2-43f4-adf9-38c9c1b40a84.png)
![image](https://user-images.githubusercontent.com/12838061/150702442-ac9da0a0-3184-4609-aa0a-12fd27fa6c1b.png)
