### ISSUE TITLE
Texture error: Grindstone

### ISSUE THREAD

**Issue by FedUpWith-Tech** [webbukkit/dynmap#3615]
Another texture error: Grindstone
3D:
![image](https://user-images.githubusercontent.com/7731191/150171869-44646f26-fb42-49fd-96e4-bbd5e392d5d6.png)

Flat:
![image](https://user-images.githubusercontent.com/7731191/150171833-6ff0de4a-8898-4514-871d-25de0d47d685.png)

**Comment by mikeprimm** [comment]
Should be fixed in SNAPSHOT 649+

**Comment by generrosity** [comment]
not quite fixed in beta-657, "right" leg missing top texture. 
![image](https://user-images.githubusercontent.com/12838061/150702369-8cbaa862-cb3a-4525-89c3-a6d0aa46f1a1.png)
![image](https://user-images.githubusercontent.com/12838061/150702391-c2702577-0873-4752-a7dd-ca7e58749b55.png)

**Comment by mikeprimm** [comment]
Fixed in 701

**Comment by generrosity** [comment]
Thanks Mike! 💚 and for the many many before this
