### ISSUE TITLE
Texture Error: Composter Contents

### ISSUE THREAD

**Issue by FedUpWith-Tech** [webbukkit/dynmap#3616]
The contents of composters aren't rendered on the map- the composter circled in red should be the only empty one, each other one has a new level of compose in it.
3D:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/7731191/150172188-a0eb39b7-6fd7-480e-bfc8-1dca8da8c210.png">
Flat:
<img width="221" alt="image" src="https://user-images.githubusercontent.com/7731191/150172242-e4d8512f-3bf1-4ce0-b493-7c118e557964.png">

**Comment by mikeprimm** [comment]
Contents level for composter model should be in for SNAPSHOT 650+

**Comment by generrosity** [comment]
confirmed composter working in beta-657 2d+3d 👌
