### ISSUE TITLE
Texture Error: Extended Piston

### ISSUE THREAD

**Issue by FedUpWith-Tech** [webbukkit/dynmap#3617]
Extended pistons seem to have a bit of an issue with the head of the piston
3D:
![image](https://user-images.githubusercontent.com/7731191/150173156-58ada8ee-4fd6-4002-a46a-127f2fe52ad2.png)

Flat:
![image](https://user-images.githubusercontent.com/7731191/150173123-23152ded-45cc-4b44-bfa7-6cb53cc835b1.png)

**Comment by mikeprimm** [comment]
Fix for pistons should be in SNAPSHOT 651+

**Comment by generrosity** [comment]
confirming fixed beta-657, 2d/3d piston head
![image](https://user-images.githubusercontent.com/12838061/150702280-c689a64b-aab0-41e4-99a0-6dbe64a09895.png)
