### ISSUE TITLE
Texture Error: End Portal Frames

### ISSUE THREAD

**Issue by FedUpWith-Tech** [webbukkit/dynmap#3618]
End portal frames without eyes have some peculiarities and end portal frames without eyes also seem to be messed up
3D:
![image](https://user-images.githubusercontent.com/7731191/150177138-1e7393aa-51e0-4867-a8f3-b23c967adc17.png)
![image](https://user-images.githubusercontent.com/7731191/150177157-36981eab-ba53-4ea3-a447-a95ac3cb1441.png)

Flat:
![image](https://user-images.githubusercontent.com/7731191/150177185-1e00a9a2-3be2-4e41-a5cb-a9d685aad7c1.png)
![image](https://user-images.githubusercontent.com/7731191/150177202-a9d4dcaf-f69a-4565-85a7-1024ef8640be.png)

In Game:
![image](https://user-images.githubusercontent.com/7731191/150177057-2950c7ce-1ff5-4462-a56b-504269cc5d5a.png)
![image](https://user-images.githubusercontent.com/7731191/150177084-34cbcb8d-24e3-4e22-af5a-59c72abc9023.png)

**Comment by mikeprimm** [comment]
Models for end portal should be fixed in SNAPSHOT 652+

**Comment by generrosity** [comment]
confirmed working beta-657 - filled and unfilled, 3d and topdown
![image](https://user-images.githubusercontent.com/12838061/150702186-116ce90f-9695-4a2a-89b2-71c6324af374.png)
![image](https://user-images.githubusercontent.com/12838061/150702218-d2ec8e8e-f49d-453f-9b22-5e2bdb3e8950.png)
