### ISSUE TITLE
Texture Error: Redstone Repeaters/Comparators

### ISSUE THREAD

**Issue by FedUpWith-Tech** [webbukkit/dynmap#3619]
another texture issue
3D:
![image](https://user-images.githubusercontent.com/7731191/150177594-7075626a-488e-42c3-b19b-1ace2ef57a9f.png)

Flat:
![image](https://user-images.githubusercontent.com/7731191/150177641-fa83e60d-d799-4def-9df9-d70b940f7127.png)

**Comment by Aaron2550** [comment]
Repeaters also face wrong directions on the map
![image](https://user-images.githubusercontent.com/24834067/151674278-2b20239f-e54b-4e02-8fba-646c94bccb36.png)

**Comment by mikeprimm** [comment]
Fix will be complete in SNAPSHOT 666+
