### ISSUE TITLE
Texture Error: rotation of blocks

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3620]
pumpkins and workbenches are not rotated properly. top of furnace is not rotated properly
3D:
![image](https://user-images.githubusercontent.com/45831568/150187663-9b25110f-87ea-455b-a027-24ab4140dc59.png)
2D:
![image](https://user-images.githubusercontent.com/45831568/150187718-4efdd958-ea5c-4a09-ab23-d2089fa14f30.png)
in-game
![image](https://user-images.githubusercontent.com/45831568/150187002-fce1b64b-7791-40a8-b5ae-658486b42390.png)

**Comment by mikeprimm** [comment]
Should all be fixed in SNAPSHOT 654+

**Comment by generrosity** [comment]
@mikeprimm adding a few more to this particular rotation business - might already be fixed?

Ingame:
![image](https://user-images.githubusercontent.com/12838061/150633259-674af3f1-6790-4659-914d-9229922483ac.png)

On Map:
![image](https://user-images.githubusercontent.com/12838061/150633279-aef5292f-07ec-4239-b91c-6930195a6188.png)

**Comment by mikeprimm-triva** [comment]
Rotation isn't "a problem" - it's just different block model definition problems.   Grouping them doesn't really accomplish anyting.

**Comment by generrosity** [comment]
Sweet as, I'll raise as distinct issues (sorry thought it looked like a shared thing)

**Comment by mikeprimm** [comment]
Yep - it'd be nice if it were common, but MC has not really consistent notions between block state and orientation, so it's kind of a one off for each block... :)

**Comment by generrosity** [comment]
above pumpkin and workbench confirmed working in beta 657
![image](https://user-images.githubusercontent.com/12838061/150702074-30f7cdfa-1c0b-4378-8504-eaee85d2e31f.png)
