### ISSUE TITLE
Dynmap throws a NPE on Shutdown after map rename

### ISSUE THREAD

**Issue by Aaron2550** [webbukkit/dynmap#3621]
**Issue Description:** I renamed a map from `surface` to `sse`.

* **Dynmap Version:** v3.3-beta-4-617
* **Server Version:** Paper 1.18.1 Build 166
* **Pastebin of Configuration.txt:** Not relevant, as far as i can see
* **Pastebin of maps section of worlds.txt:** https://pastebin.com/ZJSsn75L
* **Server Host (if applicable):** Selfhosted
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/xszfPSKC
* **Other Relevant Data/Screenshots:** See screenshots and files at the bottom. My Tiles Table has ~4.2m entries. Maybe thats causing some issues?
* **Steps to Replicate:** Im unsure about this. Like i said, i cleared both my Database and world.pending after renaming that map. And this issue didnt happen until roughly 18 hours into the fullrender when i restarted the server.

 [x] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

[world.pending.txt](https://github.com/webbukkit/dynmap/files/7908070/world.pending.txt)
![chrome_rlbIJg0rMS](https://user-images.githubusercontent.com/24834067/150411858-37ba6588-d9ca-46b7-aa50-bc4bed05e755.png)

**Comment by Aaron2550** [comment]
I did nothing. I swear on my life i did not touch dynmap at all, but it just stopped throwing a NPE on shutdown...

**Comment by Aaron2550** [comment]
Just happened again. This time with the storage method being filetree and not mysql. i havent renamed the maps, i just `dynmap purgeworld world`, shutdown the server, switched to filetree, deleted world.pending.
![image](https://user-images.githubusercontent.com/24834067/151670746-f4c77593-f786-46bc-8f4d-d8d2d281ef3e.png)

**Comment by mikeprimm** [comment]
Check new SNAPSHOT (675+) - render job shutdown can take too long when many are active or the render jobs are big (particularly when using boost), and new code forces interrupt of those threads if orderly shutdown doesn't result in them finishing within 5 seconds.
