### ISSUE TITLE
Wiki page replaced by test message

### ISSUE THREAD

**Issue by jmtrafny** [webbukkit/dynmap#3622]
Following [this link](https://github.com/webbukkit/dynmap/wiki/Setting-up-without-the-Internal-Web-Server) from [CurseForge](https://www.curseforge.com/minecraft/mc-mods/dynmapforge) website leads to a wiki page that has been replaced with a test message by user Darkwinged.

**Comment by JurgenKuyper** [comment]
It should route to this link: https://github.com/webbukkit/dynmap/wiki/External-Webserver-Basics probably changed when the wiki revamp took place. I emptied the page for now, but it needs to be fixed by changing the link on the curseforge page, which only MikePrimm can do.

**Comment by mikeprimm** [comment]
OK - should be fixed on both Dynmap (dev.bukkit.org) and Dynmap-Forge/Fabric (curseforge.com proper)
