### ISSUE TITLE
Powered Rails always show north/south

### ISSUE THREAD

**Issue by aschmois** [webbukkit/dynmap#3623]
**Issue Description:** Dynmap flat doesn't seem to be rendering powered rails in the correct orientation. Normal rails are seemingly fine.

* **Dynmap Version:** 3.3-beta-4-forge-1.18
* **Server Version:** forge 1.18.1 39.0.19
* **Pastebin of Configuration.txt:** https://pastebin.com/gNu4nYMu
* **Server Host (if applicable):** Selfhosted
* **Other Relevant Data/Screenshots:** Custom `worlds.txt`: https://pastebin.com/Ff82iyCv
![image](https://user-images.githubusercontent.com/4064285/150622739-296f5589-6fce-44e2-8da1-97e9b84a3d79.png)

* **Steps to Replicate:** Unsure if this issue is happening on other resolutions/iso since this config is gonna take a while to render :p

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
Are you sure this render is current?   This was fixed back before 1.18 was supported, and I've attempted unsuccessfully to reproduce this.  The fix was done about 4 months ago, so if your world was rendered back during 1.17 and has not been fullrendered since then, you might have left-over incorrect renders.   If you could try doing a radiusrender at this location, and see if you still see a problem after it completes, that would help confirm if this is the case.

**Comment by aschmois** [comment]
This render was done very recently, I am currently running a fullrender from scratch (empty world) after adding all the custom maps. The world didn't exist pre 1.18.1 :)

**Comment by mikeprimm** [comment]
OK - so reproduced this - it is, surprisingly enough, Forge specific (doesn't happen on Spigot nor Fabric 1.18.1).

**Comment by mikeprimm** [comment]
OK - figured this out (95% sure this is true for you too).   If you had the latest, as of a few minutes ago, DynmapBlockScan installed, it had a problem where I left on the 'vanilla' block scanning (I use it for testing, but its not suitable for production), and the generated mapping for the vanilla blocks was overriding the better (more accurate) internal ones.  Net-net, either remove DynmapBlockScan OR update to the latest build - https://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.2-SNAPSHOT-forge-1.18.1.jar

**Comment by aschmois** [comment]
This fixed the issue, thanks @mikeprimm
