### ISSUE TITLE
Texture Error: Cauldron bottoms

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3625]
cauldrons seem to have a bit of an issue with their bottoms being rendered, also they are empty. they should have snow, lava and water in them.
3D:
![afbeelding](https://user-images.githubusercontent.com/45831568/150633531-98be27ea-9f3f-411e-9a1c-a68907173364.png)
2D:
![afbeelding](https://user-images.githubusercontent.com/45831568/150633128-6ddd7dce-2223-4b3c-8478-aa93eaba71c9.png)

**Comment by mikeprimm** [comment]
Fixed in 722

**Comment by JurgenKuyper** [comment]
Confirmed, thanks!
