### ISSUE TITLE
Texture Issue: Observers

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#3627]
Observers looks to have texture issues matching directions

Ingame all directions: 
![image](https://user-images.githubusercontent.com/12838061/150702600-72ff43fb-bb94-4ee2-ac35-50e0cfc58bb1.png)

Dynmap:
![image](https://user-images.githubusercontent.com/12838061/150702618-886f1b27-381a-44c8-aa48-574dc6903fb5.png)
![image](https://user-images.githubusercontent.com/12838061/150702622-ec5f1ae0-40fb-4168-abd3-471e41ffcd0d.png)

Thanks!

**Comment by mikeprimm** [comment]
Fix in SNAPSHOT 671
