### ISSUE TITLE
Texture Error: Magenta Terracotta

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#3629]
It looks like the arrow terracotta has issues with the texture/directionality

Its a handy one!

Ingame:
![image](https://user-images.githubusercontent.com/12838061/150702704-f0bfb800-9571-4acb-94a2-c303ada2b049.png)

Dynmap;
![image](https://user-images.githubusercontent.com/12838061/150702711-9c6dcd0e-7739-4ecc-9473-d83b0bf3c3b3.png)

beta-657

Thanks!

**Comment by mikeprimm** [comment]
Fixed in SNAPSHOT 667+
