### ISSUE TITLE
Texture Error: Skulk Sensor

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#3630]
New block has isssues with textures on model sides and wavey top

Ingame:
![image](https://user-images.githubusercontent.com/12838061/150702812-d9edcc67-5332-4c7f-825f-2838afa925fe.png)

Dynmap:
![image](https://user-images.githubusercontent.com/12838061/150702821-3dc170b4-f186-4416-a984-6d05556b26c3.png)

beta-657, thanks!

**Comment by mikeprimm** [comment]
Fix in SNAPSHOT 671+
