### ISSUE TITLE
Texture Error: cake

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#3631]
~~The cake is a lie~~ There seems to be texture/model issues with the cake eaten states.

Ingame:
![image](https://user-images.githubusercontent.com/12838061/150702925-101282cd-6cf1-4a1d-957e-0b8d79c0ec48.png)

Dynmap:
![image](https://user-images.githubusercontent.com/12838061/150702933-62e16e19-b76c-4db8-9a59-f316bad32bcf.png)

beta-657, thanks

**Comment by mikeprimm** [comment]
Fixed in SNAPSHOT 674+
