### ISSUE TITLE
Texture Issue: Azalea Leaves colour?

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#3633]
Looks to be a colour (?) model issue with azalea leaves and azalea flowering leaves. Azalea bushs look fine.

ingame with other azalea:
![image](https://user-images.githubusercontent.com/12838061/150703139-c607498d-c3b2-42f8-8675-0dad725ac2be.png)

dynmap:
![image](https://user-images.githubusercontent.com/12838061/150703147-12da4e17-2a0a-40d8-9112-f5ab1d325724.png)

beta-657, thanks

**Comment by mikeprimm** [comment]
Removed incorrect biome shading from azalea (SNAPSHOT 670+)
