### ISSUE TITLE
Texture Issue: campfire

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#3634]
I think there are some texture/model issues with the campfire (lit and unlit) - slightly different issues for each one.

Ingame:
![image](https://user-images.githubusercontent.com/12838061/150703437-10dd6926-6343-4f00-ba8e-89a7f6cf9291.png)
2d:
Looks like the lit charcoal texture is on top, and the fire likely should be invisible at this angle. wood looks correct. Unlit model not set up.
![image](https://user-images.githubusercontent.com/12838061/150703447-f764680f-f26d-4a51-bd9a-f1e97bad68cc.png)
3d:
![image](https://user-images.githubusercontent.com/12838061/150703473-41ef7e3e-fdb7-4c21-89c9-9e0333adf58a.png)

Im arranging some better images, its just taking time to render (will update)
Ingame:
![image](https://user-images.githubusercontent.com/12838061/150703502-571345a3-50c1-46ad-bdff-d4b1a46ef42d.png)
2d:
3d:
![image](https://user-images.githubusercontent.com/12838061/150703517-18196d95-0293-4b48-bd25-464a0db58e9e.png)

**Comment by Aaron2550** [comment]
Pretty much the same as #3181 but more detailed btw

**Comment by generrosity** [comment]
yea, I did notice that later when I did a search on texture errors to close. Mike has been kind enough to do some texture/model work recently on latest betas, so having it higher up with details miiiight get it completed faster (and the rotated/unlit versions sorted too)

**Comment by mikeprimm** [comment]
Should be fixed in SNAPSHOT 665+
