### ISSUE TITLE
Dynmap 3.3 Beta5 fails to update the Database Schema

### ISSUE THREAD

**Issue by Aaron2550** [webbukkit/dynmap#3635]
**Issue Description:** Dynmap tries to update the Database Schema and fails while doing so.

* **Dynmap Version:** v3.3-beta-5-657
* **Server Version:** git-Paper-175 (MC: 1.18.1)
* **Server Host (if applicable):** Selfhosted
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/rqZ5bZM4
* **Other Relevant Data/Screenshots:** Using MariaDB 10.6.5 with default settings
* **Steps to Replicate:**
- Update from Beta 4 to Beta 5,
- start server,
- wait
- see error

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by Aaron2550** [comment]
If manually updating the Database is feasible: I dont really feel comfortable copy pasting sql statements from the source code and running them directly. Would be appreciated if you guys could maybe tell me which ones i need to run....

**Comment by mayaankgally** [comment]
I ended up rolling back to the Beta 4 version, I updated last night and has the same issue except it just got hung up on the upgrade.

**Comment by 0liverGMC** [comment]
I ended up rolling back to the Beta 4 version, I updated last night and has the same issue except it just got hung up on the upgrade.

**Comment by Aaron2550** [comment]
Thats what i did too.
LostBot over on the Discord suggested trying with `innodb_buffer_pool_size=1G` under `[mysqld]` in `/etc/my.cnf` or `/etc/my.cnf.d/server.cnf`

I havent tried that yet because im still waiting for everyone to go offline for the night

**Comment by mikeprimm** [comment]
OK - I've come up with another (somewhat more complicated) procedure to provide the MEDIUMBLOB column needed for bigger tiles (particularly due to boosting) that is a more lazy process (it adds a new column vs modifying the existing one, and changes the queries to handle new insert/updates into the new column, and pulling from both columns on read).  In any case, give the latest SNAPSHOT a try (build 661+).
