### ISSUE TITLE
Error in log when server starts up. File plugins/dynmap/colorschemes/biome_rainfall_temp.txt is missing

### ISSUE THREAD

**Issue by PatBoud** [webbukkit/dynmap#3636]
**Issue Description:** 
Error in log when server starts up. File  **plugins/dynmap/colorschemes/biome_rainfall_temp.txt** is missing.
* **Dynmap Version:** core=3.3-beta-5-657, plugin=3.3-beta-5-657
* **Server Version:** *paper 1.18.1 build 176*
* **Server Host (if applicable):** Selfhosted

Logged event:
[13:25:35 ERROR]: [dynmap] Could not load colors 'default' ('plugins/dynmap/colorschemes/default.txt'): File not found.
java.io.FileNotFoundException: **plugins/dynmap/colorschemes/biome_rainfall_temp.txt (No such file or directory)**
[13:25:35 ERROR]: [dynmap] Could not load colors 'ovocean' ('plugins/dynmap/colorschemes/ovocean.txt'): File not found.
java.io.FileNotFoundException: **plugins/dynmap/colorschemes/biome_rainfall_temp.txt (No such file or directory)**

 [x ] *I have looked at all other issues and this is not a duplicate*  
 [x ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
can you append the full log?

**Comment by PatBoud** [comment]
Sure, there you go:
https://pastebin.com/LgrBYz3y

Pat

**Comment by JurgenKuyper** [comment]
does dynmap has the ability to write?
try with a fresh dynmap.jar from spigotmc.
if you can, backup and delete the dynmap folder and restart the server.

**Comment by PatBoud** [comment]
Dynmap does have the ability to write, as everything apparently works fine. I opened the issue to make sure you are aware of it :)
I automatically restart the server daily to backup everything, and I check startup logs daily as well. Never saw any Dynmap problem prior to running beta5.

- I downloaded a fresh jar from Spigot. Had same name and exact same size. Same error. I confirm the missing file is, well, missing, in the colorschemes folder.

- For fun, I created an empty "biome_rainfall_temp.txt". No more error at startup. It was created with same permissions than other files in the folder. (644)

- I changed permission to 664, no change eitheer, file remains empty, still no more error in log. Here's all entries in the log containing "dynmap".

https://pastebin.com/ULuNNG3q

**Comment by JurgenKuyper** [comment]
I see now, this is because of a recent change that those colourschemes are no longer rendering the normal way, idk why it doesn't get created on boot though, I will leave @mikeprimm to see if he can see why.

**Comment by mikeprimm-triva** [comment]
All the extracted files are only extracted during a version update (same as the web files) - cannot reproduce the problem with an upgrade or a pristine install, so not sure what to tell you...

**Comment by FedUpWith-Tech** [comment]
We've had at least a dozen people on the discord support server with this issue so there must be something we are missing to be able to replicate this. I'll do more investigating and send an update if I figure out how to reliably reproduce.

**Comment by PatBoud** [comment]
All info I can add is that the logs started showing up as soon as I updated from beta4 to beta5.

**Comment by mikeprimm** [comment]
I need a reproduce scenario - I have not been able to make this happen.  If someone's hoster is being 'clever' and deploying an update assuming they know all the files that get extracted by dynmap runtime, then them failing to include a new file would not be surprising.  But, until I can get a reproduce that includes step by step and does not involve someone else's potentially bad deployment procedure, I've got nothing to look at.

**Comment by mikeprimm** [comment]
One way to force the extraction process to run again is to zap the 'versions.txt' file in the dynmap directory, and rerun - that is the file we use to determine whether to extract the files again or not.  If a deployment process pushed that file along with the JAR, but didn't include the correct other files, that would look like what you are seeing.
