### ISSUE TITLE
Provide direct download link via spigot resources

### ISSUE THREAD

**Issue by starcraft66** [webbukkit/dynmap#3638]
**Feature Description:** It would be nice if the download for dynmap went back to being hosted directly on spigot resources. I used to use the spiget api via the `itzg/minecraft-server` docker image to download/update plugins including dynmap on startup. Since the latest update, it seems that the download link has moved to an external site, making it impossible to download the plugin reliably via the spiget api.

* **Additional context:** The behavior I described above only started happening since the update on monday. Related issue: https://github.com/itzg/docker-minecraft-server/issues/1307

**Comment by mikeprimm** [comment]
Sorry - the only trivial monetization we get is from curseforge, and providing a download link on Spigot that isn't consistent with that sidesteps that.

**Comment by starcraft66** [comment]
I see, thanks for the answer.
