### ISSUE TITLE
[Question] Malformed response from skin URL check

### ISSUE THREAD

**Issue by ilfarpro** [webbukkit/dynmap#3639]
**Issue Description:** *I'm getting "Malformed response from skin URL check" warnings in console from time to time. but often enough to worry about it. Currently, I don't know how to solve it. Of course I've tried to Google it, but there no relevant information about this warning. Could you, please tell, what is it, and how to solve this?*

* **Dynmap Version:** *Dynmap-3.3-beta-5-spigot.jar*
* **Server Version:** *purpur-1.18.1-1533.jar*
* **Pastebin of Configuration.txt:** *https://pastebin.com/FP9UWMg6*
* **Server Host (if applicable):** *Selfhosted, etc.*
* **Console log:** *https://pastebin.com/hpvMEVhr*
* **Steps to Replicate:** *I don't know*

 [true] *I have looked at all other issues and this is not a duplicate*  
 [false] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
Apparently, the Base64 decode in SnakeYAML (which we've used for years) is apparently flaking out on the base-64 encoded response on the skin URLs sometimes.... switched to the Base64 decode in the JDK (8+ has one), and it seems to work with the bad value from your logs.
