### ISSUE TITLE
mcmmo party chat displaying in web chat

### ISSUE THREAD

**Issue by SideLo98** [webbukkit/dynmap#3640]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *when using mcmmo plugin which has /partychat so only players in their specific party can see their party chat But dynmap web chat shows that partychat in web.*

* **Dynmap Version:** *3.3-beta-5-657*
* **Server Version:** *1.18.1 git-Pufferfish-38*
* **Pastebin of Configuration.txt:** *https://pastebin.com/AT7ysb8r*
* **Server Host (if applicable):** *BloomHost*
* **Pastebin of crashlogs or other relevant logs:** *-*
* **Other Relevant Data/Screenshots:** *below:*
![image](https://user-images.githubusercontent.com/67060780/151297023-ee4761ca-7a8e-4435-9916-0ea7387780d2.png)
![image](https://user-images.githubusercontent.com/67060780/151297061-689dc77a-cd7c-46bf-96eb-f71b7a98abb6.png)
* **Steps to Replicate:** *install mcmmo, dynmap plugins then create a party and use /partychat to chat with your party members, in dynmap web link everyone can read your party chat.*

 [Yes] *I have looked at all other issues and this is not a duplicate*  
 [Yes] *I have been able to replicate this*

**Comment by FedUpWith-Tech** [comment]
Nothing we can do about this, Dynmap isn't a chat plugin and just pulls from the "global" channel

**Comment by mikeprimm** [comment]
The solution for this is via the API - as stated, we work with standard chat messages, as defined by the Spigot/Bukkit API, by default, but the API does have mechanisms to allow 3rd party plugins to override that behavior - https://github.com/webbukkit/Dynmap-HeroChat is an old, but still relevant, example of this.  As a rule, we don't bake plugin support into Dynmap (only exception is permissions), but do try to enable plugins to work with a supported API - whether directly (WorldBorder directly uses our API) or indirectly, via 'linking' plugins, like Dynmap-WorldGuard or the like
