### ISSUE TITLE
Cocoa beans rendered incorrectly

### ISSUE THREAD

**Issue by Aaron2550** [webbukkit/dynmap#3641]
**Issue Description:** Cocoa beans show up wrong on renders.

* **Dynmap Version:** core=3.3-beta-5-657, plugin=3.3-beta-5-657
* **Server Version:** git-Paper-175 (MC: 1.18.1)
* **Other Relevant Data/Screenshots:** see below
* **Steps to Replicate:** Just place some Cocoa beans and wait for them to 

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

![image](https://user-images.githubusercontent.com/24834067/151701274-9eb49751-cbf9-42f5-935a-8c2ef03522a0.png)
![image](https://user-images.githubusercontent.com/24834067/151701342-9015113e-16a4-4790-a6ca-139eceb76aa5.png)

**Comment by mikeprimm** [comment]
Fixed in 3.4-SNAPSHOT (681+)
