### ISSUE TITLE
1.12.2 Paper / Bukkit crash on first start

### ISSUE THREAD

**Issue by lightly-existing** [webbukkit/dynmap#3642]
**Issue Description:** 1.12.2 Bukkit crash on any render

* **Dynmap Version:** *v3.3-beta5*
* **Server Version:** *Paper version git-Paper-1620 (MC: 1.12.2)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/DeL2dqg2*
* **Server Host (if applicable):** *Ubuntu 20.04 selfhosted OpenJDK 16*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/30bEG52h*
* **Other Relevant Data/Screenshots:** *Happens on first join on brand new world*
* **Steps to Replicate:** *Run Paper-1620 on a brand new configuration, with no world, and only Dynmap (no other plugins).*

 [y ] *I have looked at all other issues and this is not a duplicate*  
 [y ] *I have been able to replicate this*
Reproduced on brand-new test paper install, isolated to only Dynmap loaded as a plugin, on first start.

I saw there was a recent commit for Forge 1.11.2/1.12.2 with a similar function (getblockemittedlight) but this is for Bukkit.

**Comment by mikeprimm** [comment]
Yep - a common code change affected these platform specific lighting modules, and I forgot to do the corresponding update on the old Spigot/Paper specific code.  Should probably have a SNAPSHOT with a fix sometime tomorrow.

**Comment by lightly-existing** [comment]
Awesome! Thank you :D very much appreciated. You have an awesome plugin

By the way, I had another issue with Dynmap <--> Discord (VentureChat using DiscordSRV integration) working,
Dynmap --> ingame working, 
but Ingame --> Dynmap chat not working.

Join/quit messages work, though.

Is that more a configuration thing or should I make a formal issue? I see a lot of discussion with fixing Dynmap --> ingame not working, but here I have the reverse. Everything else works. No error message from DiscordSRV regarding api.sendBroadcastToWeb (https://github.com/DiscordSRV/DiscordSRV/blob/41b8f04815b028463cbccec42664943b94c199a6/src/main/java/github/scarsz/discordsrv/hooks/DynmapHook.java) so from their end it appears to be working. In the startup logs it shows registering both Dynmap and Venturechat integrations of course.

On DiscordSRV v1.24- September 2021. Maybe I should try 1.25 from the dev branch? Update--develop branch has no additional changes to that file from 1.24 so it doesn't seem to be on their end

**Comment by mikeprimm** [comment]
As a rule, dynmap uses the standard chat for the given platform (as defined by Spigot, in this case), but provides APIs for plugins that manipulate standard chat to do the same for Dynmap - we don't bake in support for the literally dozens of chat and chat manipulation plugins that have come and gone over the years: just isn't practical.  If someone wants to handle VentureChat, there are examples like Dynmap-HeroChat (dated, but the API is still there, and the pattern still works) available, and they are free to do so.

**Comment by lightly-existing** [comment]
I'll take that to mean I should consult them about this instead of here? The API is really simple so it doesn't seem like there's anything wrong on your end

**Comment by mikeprimm** [comment]
Right - chat works as it should without the chat modifying plugin, so that is kind of that...  chat plugins rarely work together well (frankly, the Bukkit API model for how to handle Chat events was pretty broken, last I checked, around what chat plugins really like doing, like 'channels' and selected recipients and the rest, unless they've done some improvements I don't know of :) ).
The model, as I last looked into it, was essentially on the level of 'modify the message content' and 'cancel the message', which creates an impact on anyone who observes the chat messages relative to any additional concepts (such as a channel, a recipient list, or the like).

**Comment by mikeprimm** [comment]
Fix should be in latest 3.4-SNAPSHOT build (681+)
https://dynmap.us/builds/dynmap/Dynmap-3.4-SNAPSHOT-spigot.jar

**Comment by mikeprimm** [comment]
Fix released in 3.3.1
