### ISSUE TITLE
COnfiguration.txt resests at start of server [1.18.1 paper / spigot]

### ISSUE THREAD

**Issue by Matthieu-Sauer** [webbukkit/dynmap#3643]
> template is **Untouched**
> sample data is *Not needed here (I think)*

**Issue Description:** *Using PaperSpigot 1.18.1 (or Spigot 1.18.1) The configuration file keeps being resetted at every restart of the server, preventing the generation of a high res map*

* **Dynmap Version:** *v3.3-beta-5 for Spigot/PaperMC 1.10.2 to 1.18.1*
* **Server Version:** *PaperSpigot 1.18.1 build 68*
* **Pastebin of Configuration.txt:** *Unimportant*
* **Server Host (if applicable):** *OMGServ*
* **Pastebin of crashlogs or other relevant logs:** *No unexpected logs are written (only startup classics ones)*
* **Other Relevant Data/Screenshots:** *Only other plugin used is SkinRestorer, this is vanilla 1.18.1 otherwise. I wanted to do a High Res of the dynmap, so I purged every worlds then restarted the server with the new configuration, which was then overwritten I don't know by what or why*
* **Steps to Replicate:** *I have no clue if it is common to every server therefore I cannot provide a way to replicate it*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this each time I reboot my server*

**Comment by FedUpWith-Tech** [comment]
Open a ticket with OMGserv, this is likely something they do when a configuration change that they don't like gets made

**Comment by Matthieu-Sauer** [comment]
Okay, will do, thank you for your answer

**Comment by Matthieu-Sauer** [comment]
Indeed, omgserv replaces every default files of the dynmap plugin to disallow the usage of it in high res, sorry for bothering
