### ISSUE TITLE
Mods that Effect BlockStates Break Dynmap (Ex: Statement)

### ISSUE THREAD

**Issue by Gryzle** [webbukkit/dynmap#3644]
**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** v3.3
* **Server Version:** Fabric 1.18.1
* **Pastebin of Configuration.txt:** *Irrelevant*
* **Server Host (if applicable):** Self-Hosting
* **Pastebin of crashlogs or other relevant logs:** *Irrelevant*
* **Other Relevant Data/Screenshots:** Here's a screenshot of how the map appears with a blockstate changing mod: 
 ![unknown](https://user-images.githubusercontent.com/51198087/151853383-6aeb8990-c39e-4661-a486-3503e5724df9.png)
* **Steps to Replicate:**
1. Have `Dynmap for Fabric` and `Statement` installed, along with their dependencies. (Statement is an example of a mod that changes blockstates)
2. Start a render with Dynmap.
3. Observe incorrectly rendered blocks (examples: non-waterlogged blocks appear waterlogged, grass blocks appear invisible)

This has been replicated by `Kosmolot#7888` on the Dynmap Discord

 [✅] *I have looked at all other issues and this is not a duplicate*  
 [✅] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
Yep - breaking the standard state space for vanilla doesn't work.  Don't expect it to be supported anytime soon - sorry.

**Comment by kosma** [comment]
I'll see if the Fabric port can defer loading the vanilla block list until after all the other mods had a chance to do their shenanigans.

**Comment by mikeprimm** [comment]
It will not help - we currently depend upon the consistency of the number and order of the block states for a given block (this is the 'data=' stuff in the model and texture files that is a 'work-alike' for the old metadata values - just with a bigger block specific range).  I already want and need to add model/texture file support for state id/value pattern matches, but until ALL the existing render data are changed to this (including ones generated using DynmapBlockScan....), this isn't gonna work.

**Comment by mikeprimm** [comment]
OK - I started the work that will enable this to work at some point:  I'm going to take a look at the specific blocks that Statement screws with, to see if it is a practical subset to prioritize in converting to the state pattern based mappings.

**Comment by mikeprimm** [comment]
So, Statement is a library - is there some specific mods we're talking about here?

**Comment by kosma** [comment]
The offender in this case: https://www.curseforge.com/minecraft/mc-mods/scaffolding-extension

**Comment by mikeprimm** [comment]
OK - the scaffolding has been switched in the latest SNAPSHOT to be the more dynamic state matching base mapping: if you could let me know if it works out for you, that'd be good.   (3.4-SNAPSHOT 705+)

**Comment by generrosity** [comment]
@Gryzle @kosma have either of you had a moment to check this snapshot out and confirm?

**Comment by JurgenKuyper** [comment]
tried out this issue and doesn't seem to be an issue anymore with the latest dynmap and fabric installed available for statement
