### ISSUE TITLE
Bamboo shows up wrong on renders

### ISSUE THREAD

**Issue by Aaron2550** [webbukkit/dynmap#3645]
Issue Description: Bamboo doesnt have its leaves at the top

Dynmap Version: core=3.3-beta-5-657, plugin=3.3-beta-5-657
Server Version: git-Paper-175 (MC: 1.18.1)
Other Relevant Data/Screenshots: see below
Steps to Replicate: Just place somebamboo, wait for it to grow, and check the map
[x] I have looked at all other issues and this is not a duplicate
[x] I have been able to replicate this

![image](https://user-images.githubusercontent.com/24834067/151868859-4b07388e-3c70-4353-a5f3-69a0fecf0500.png)
![image](https://user-images.githubusercontent.com/24834067/151869034-0bff3d29-5a47-4741-9db4-39b5dab874c6.png)

**Comment by mikeprimm** [comment]
Fixed in 3.3.2 and 3.4-SNAPSHOT (696+)

**Comment by generrosity** [comment]
Looking good in 705

![image](https://user-images.githubusercontent.com/12838061/152774770-4e18dfed-58b3-444e-a0a3-55bb3b81f645.png)
![image](https://user-images.githubusercontent.com/12838061/152774790-214608ac-e43c-4f20-8c81-33c1407a998d.png)
