### ISSUE TITLE
Selecting Texture Pack

### ISSUE THREAD

**Issue by TillVogelsang** [webbukkit/dynmap#3648]
Is it possible to get a menu, where you can select between texture packs, so you can have Vanilla Textures and for example BDCraft?

**Comment by JurgenKuyper** [comment]
that is currently not possible, however, you can define different texturepacks and have multiple maps next to eachother for each texturepack.

**Comment by TillVogelsang** [comment]
Ok... Will something like this come soon?

**Comment by JurgenKuyper** [comment]
It's not on the roadmap, as each texture pack needs a new renderjob to be done, which take a long time
