### ISSUE TITLE
Add the ability to use fillcolor and fillopacity on a line marker

### ISSUE THREAD

**Issue by BossDaily** [webbukkit/dynmap#3649]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Add the ability to fill in line markers with color and also edit the fills opacity*

* **Additional context:** *Please add any additional information you feel will help us understand the feature*

**Comment by mikeprimm** [comment]
Not sure I understand the requirement - line markers are one or more line segments: there really isn't an interior to fill or be opaque.   Area markers are basically the version of line markers that have an interior (by virtue of the last corner closing the cool formed by the other corners).   Am I missing something?
