### ISSUE TITLE
Error only in dynamap-3.3.1-spigot compared to dynamap-3.3-beta-5-spigot

### ISSUE THREAD

**Issue by itcools** [webbukkit/dynmap#3652]
In the same environment, the dynamap-3.3-beta-5-spigot operates normally, but the dynamap-3.3.1-spigot causes errors. 

The attached log is the log that occurred when dynamap-3.3.1-spigot was executed.

[16:06:45] [Server thread/ERROR]: [dynmap] SQLException: Error updating tables to version=3
[16:06:45] [Server thread/ERROR]: [dynmap]   ErrorCode: 1060, SQLState=42S21
[16:06:45] [Server thread/ERROR]: [dynmap]   Message: Duplicate column name 'NewImage'

**Comment by generrosity** [comment]
@itcools  version 3.3.2 was released just yesterday too - could you give that a go?
- Fix for MySQL upgrade issue, and MySQL PHP scripts (external server)

**Comment by itcools** [comment]
> @itcools version 3.3.2 was released just yesterday too - could you give that a go?
> 
> * Fix for MySQL upgrade issue, and MySQL PHP scripts (external server)

I checked it right away, and this error occurred. 

[23:52:54] [Server thread/INFO]: [dynmap] Loading dynmap v3.2.1-531
[23:52:54] [Server thread/INFO]: [dynmap] version=git-Paper-187 (MC: 1.18.1)
[23:52:54] [Server thread/ERROR]: [dynmap] Cannot find [Lnet.minecraft.server.BiomeBase;
[23:52:54] [Server thread/ERROR]: [dynmap] Cannot find net.minecraft.server.BiomeStorage
[23:52:54] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R1.CraftServer] Error initializing

**Comment by JurgenKuyper** [comment]
can you send the full latest.log?

**Comment by mikeprimm** [comment]
v3.2.1-531 is old...   (and that is what is in your log) - be sure you've removed the old JAR...

**Comment by itcools** [comment]
> can you send the full latest.log?

Oh, I'm sorry, but I can't give it to you because I've already erased the log. What should I do?

**Comment by itcools** [comment]
> v3.2.1-531 is old... (and that is what is in your log) - be sure you've removed the old JAR...

Stop the illusion that you're the only one who knows that.

**Comment by JurgenKuyper** [comment]
update to the latest dynmap as the dev said, and check if the error still occures

**Comment by itcools** [comment]
> update to the latest dynmap as the dev said, and check if the error still occures

I changed it to a new version, and it's working well. Thank you!

**Comment by JurgenKuyper** [comment]
nice, Imma close this for now, reopen if you have the same issue again.

**Comment by gmfamily** [comment]
Up! again... sadly...

**Please ping me if I have to open a new issue (as this one is mentionning 3.3.1 version).**

>.... [11:56:53 INFO]: [dynmap] **Enabling dynmap v3.3.2-696**
>.... [11:56:53 INFO]: [dynmap] Added 18 custom biome mappings
>.... [11:56:53 INFO]: [dynmap] Using LuckPerms 5.4.0 for access control
>.... [11:56:53 INFO]: [dynmap] Opening MySQL database ***.***.***.***:3306/************* as map store
>.... [11:56:53 INFO]: [dynmap] Updating database schema from version = 4
>.... [11:56:53 ERROR]: [dynmap] **SQLException: Error updating tables to version=3**
>.... [11:56:53 ERROR]: [dynmap] **ErrorCode: 1064, SQLState=42000**
>.... [11:56:53 ERROR]: [dynmap] Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALGORITHM=INPLACE, LOCK=NONE' at line 1
>.... [11:56:53 ERROR]: [dynmap] ConnectionString: jdbc:mysql://***.***.***.***:3306/*************?allowReconnect=true
>.... [11:56:53 ERROR]: [dynmap] **Map storage initialization failure**
>.... [11:56:53 INFO]: [dynmap] Unloaded 0 components.
>.... [11:56:53 INFO]: [dynmap] Disabled

I have restored previous beta-5 version that is running fine : 

>.... [11:58:31 INFO]: [dynmap] Enabling dynmap v3.3-beta-5-657
>.... [11:58:31 INFO]: [dynmap] Added 18 custom biome mappings
>.... [11:58:31 INFO]: [dynmap] Using LuckPerms 5.4.0 for access control
>.... [11:58:31 INFO]: [dynmap] Opening MySQL database ***.***.***.***:3306/************* as map store
>.... [11:58:31 INFO]: [dynmap] Schema version = 4
>.... [11:58:31 INFO]: [dynmap] Mod Support processing completed
>.... [11:58:34 INFO]: [dynmap] Loaded 27 shaders.
>.... [11:58:34 INFO]: [dynmap] Loaded 82 perspectives.
>.... [11:58:34 INFO]: [dynmap] Loaded 22 lightings.
>.... [11:58:34 INFO]: [dynmap] Starting enter/exit processing
>.... [11:58:35 INFO]: [dynmap] Web server started on address 0.0.0.0:25575
>.... [11:58:35 INFO]: [dynmap] version 3.3-beta-5-657 is enabled - core version 3.3-beta-5-657
>.... [11:58:35 INFO]: [dynmap] For support, visit our Discord at https://discord.gg/s3rd5qn
>.... [11:58:35 INFO]: [dynmap] For news, visit https://reddit.com/r/Dynmap or follow https://twitter.com/Dynmap
>.... [11:58:35 INFO]: [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
>.... [11:58:35 INFO]: [dynmap] If you'd like to donate, please visit https://www.patreon.com/dynmap or https://ko-fi.com/michaelprimm
>.... [11:58:35 INFO]: [dynmap] Loaded 2 maps of world 'world'.
>.... [11:58:35 INFO]: [dynmap] World 'world_nether' disabled
>.... [11:58:35 INFO]: [dynmap] World 'world_the_end' disabled
>.... [11:58:35 INFO]: [dynmap] Enabled
>.... [11:58:35 INFO]: [Essentials] Enabling Essentials v2.19.2
>.... [11:58:35 INFO]: [dynmap] Finish marker initialization

**Comment by itcools** [comment]
I have no problem using the same version as you.

Because I used MySQL before, but the DB capacity was too big and too hard to manage, so I just used the default value. You should just use it as a default, too. I think it's better.

[17:50:39] [Server thread/INFO]: [dynmap] Enabling dynmap v3.3.2-696
[17:50:40] [Server thread/INFO]: [dynmap] Added 18 custom biome mappings
[17:50:40] [Server thread/INFO]: [dynmap] Using LuckPerms 5.4.0 for access control
[17:50:40] [Server thread/INFO]: [dynmap] Mod Support processing completed

**Comment by gmfamily** [comment]
Thank you for your feedback. What "default value" did you use ? We are on standard MySQL version offered by our server hosting and we didn't change anything on this side (as far as I know). We use MySQL for its external storage feature.

**Comment by itcools** [comment]
> Thank you for your feedback. What "default value" did you use ? We are on standard MySQL version offered by our server hosting and we didn't change anything on this side (as far as I know). We use MySQL for its external storage feature.

The default setting is [type: filetree] Try using

**Comment by gmfamily** [comment]
Ok :) Thank you for sharing... Indeed, if you use filetree, you disable the MySQL external storage so the specific problem afferent to this option is no more a problem (you don't run the faulty code) ;) I use it already locally on my backup instance (for testing purpose when I add features to our own plugin). For our "online" instance we prefer use the external storage feature of dynmap.
