### ISSUE TITLE
API artifacts are missing on repository

### ISSUE THREAD

**Issue by josephjthomas** [webbukkit/dynmap#3653]
I was going ahead and update my buildscripts to use Dynmap v3.3.2, but the "dynmap-api" and "DynmapCoreAPI" artifacts are missing for 3.3.2.
I was taking a look at "DynmapCore" but that misses 3.3 at all? The newest is 3.2-beta-1.
Can you upload the missing artifacts please?

**Comment by mikeprimm** [comment]
DynmapCore is a common component of the build, not a published artifact

**Comment by josephjthomas** [comment]
> DynmapCore is a common component of the build, not a published artifact

It is published right here: https://repo.mikeprimm.com/us/dynmap/DynmapCore/

**Comment by mikeprimm** [comment]
I'll be removing that, then... those were copied accidentally from build server, not intentionally published.

**Comment by mikeprimm** [comment]
In any case, 3.3 is the current API release.   3.3.1 and 3.3.2 were hotfix releases with zero changes to published API.
