### ISSUE TITLE
Texture Issue: End Rods

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#3655]
Looks like End Rods are currently not displaying (b705, possibly pre6xx)

![image](https://user-images.githubusercontent.com/12838061/152780651-30dd3795-c44a-4ca1-9c20-bd20ae2a16e2.png)
![image](https://user-images.githubusercontent.com/12838061/152780680-fd12ce7e-acc2-48ae-b011-55eff8fe3c8a.png)

Off topic - Also - looks at those smexy nether anchors! The detail rendering is so good 😁

**Comment by mikeprimm** [comment]
Fixed in 723

**Comment by JurgenKuyper** [comment]
EndRods seem to miss their bottom texture on build: 723
![image](https://user-images.githubusercontent.com/45831568/153921592-76b96a07-8c22-4123-ad03-053ec8195325.png)

**Comment by mikeprimm** [comment]
The pedantics on this are getting a bit tiresome.... I'll get to it when it is important enough to justify the time being spent....

**Comment by JurgenKuyper** [comment]
sure thing, you are doing an awesome job squashing the bugs, take all the time you need

**Comment by mikeprimm** [comment]
Sorry for being cranky...  just trying to get the issue count down, and it's kind of irritating when I'm back looking at ones that really should be done.

**Comment by JurgenKuyper** [comment]
it's okey, I understand it, you've already done so much, there really aren't many left, I'd say use your energy on the bigger tasks, the texture fixes will come eventually.

**Comment by generrosity** [comment]
> EndRods seem to miss their bottom texture on build: 723 ![image](https://user-images.githubusercontent.com/45831568/153921592-76b96a07-8c22-4123-ad03-053ec8195325.png)

yea, agreed - this is sweet-as. Love your work Mike!  

We are just fan-boying over how good things look in high-rez, and we aren't sure how to do it ourselves.

Cheers! Closing this as Done
