### ISSUE TITLE
Droppers not facing the right direction

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3656]
Tested in build 3.4-SNAPSHOT-705 (spigot) 
Droppers don't face in the right direction:
![image](https://user-images.githubusercontent.com/45831568/152798131-02e7ec50-c9f9-4976-b39f-d83a8ea1b8b3.png)
ingame:
![image](https://user-images.githubusercontent.com/45831568/152798061-142f0662-c126-4a13-ab58-b557cb6dfc2e.png)

**Comment by mikeprimm** [comment]
Fixed in 729

**Comment by JurgenKuyper** [comment]
confirmed in 731, thanks! 💚
