### ISSUE TITLE
end portal image not like in-game or texture

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3657]
Tested in build 3.4-SNAPSHOT-705 (spigot)
the portal block is not shown correctly: 
![image](https://user-images.githubusercontent.com/45831568/152799799-410f6844-8d20-4acb-84da-16346d07826d.png)
in-game:
![image](https://user-images.githubusercontent.com/45831568/152799873-7e163765-dcf0-4f7f-8729-12bec12b55a6.png)

texture.png
![end_portal](https://user-images.githubusercontent.com/45831568/152799995-784c685d-ffbf-4b8d-8cf4-45293173c3fa.png)

**Comment by FedUpWith-Tech** [comment]
I'm a fan of the texture Dynmap uses for what it's worth

**Comment by generrosity** [comment]
Ditto. The dynmap texture is far sexier and far more striking, and its unlikely to appear for most users maps.

Mike, please do consider the 'wont fix' tag for this 😜

**Comment by mikeprimm** [comment]
Yep - I'm actually having difficulty FINDING where that texture comes from: not sure if it is a texture resource, or a code generated texture :).  I used what I used because there WAS a texture for it (it's the 'end_sky' texture, which is an environment texture vs a block texture :) ).

**Comment by generrosity** [comment]
Checking out some resource pack forums, it looks like the sky texture is reused for the portal, but "It is recolored per-layer, (meaning the hues you see in-game is put there by the game"

unless a better representation is suggested, closing up and will add to our minilist
