### ISSUE TITLE
Chorus plant stem too fat

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3658]
Tested in build 3.4-SNAPSHOT-705 (spigot)
Chorus plant is wider than in game:
![image](https://user-images.githubusercontent.com/45831568/152800279-358a09da-67aa-4997-98ff-f6310dc3125d.png)
browser:
![image](https://user-images.githubusercontent.com/45831568/152800379-1d86d1e0-55af-480e-94bb-5f3ff7278e2d.png)

**Comment by mikeprimm** [comment]
Fixed in 720

**Comment by JurgenKuyper** [comment]
Confirmed, thanks!
