### ISSUE TITLE
Markers Component is not enabled 

### ISSUE THREAD

**Issue by Ghir8** [webbukkit/dynmap#3659]
**Issue Description:** *As the title says, the markers component is not enabled, I've already tried to restart, do a clean install and reset all Dynmap's data (even with a fresh new database) but nothing seems to resolve the problem.*

* **Dynmap Version:** *3.3, core version 3.3-679*
* **Server Version:** *Fabric 0.44.0+1.18.1 , fabric loader 12.12, mysql-jdbc 8.0.27+20211227*
* **My Configurations:** [configuration.txt](https://github.com/webbukkit/dynmap/files/8015601/configuration.txt)
* **Server Host (if applicable):** *Multicraft, hosted, I don't have a Linux terminal for more info*
* **Server logs at startup:** : [Server Log.log](https://github.com/webbukkit/dynmap/files/8015766/Server.Log.log)

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
version 3.3.2 was released a few days ago - could you give that a go?

    Fix for MySQL upgrade issue, and MySQL PHP scripts (external server)

**Comment by Ghir8** [comment]
Sure thing, I'll post the results!

**Comment by Ghir8** [comment]
Markers Component now up and running, thanks a lot @JurgenKuyper !
One question though: is right that the map is completely rested after the update? (this is my first update of this mod); not so big of an issue, our map is not that big (1-2 night and all tiles are processed).

**Comment by JurgenKuyper** [comment]
it probably reset because your mysql connection couldn't be made, and thus the database wasn't updated. you can rerender, glad it wasn't that long of a render because there is no good manual way to move the filetree tiles to mysql. 
I am going to go ahead and close this issue for now, please reopen if there seems to be an issue with regards to the title.

**Comment by Ghir8** [comment]
oh ok, i suspected that. good than, thanks again!
