### ISSUE TITLE
Crops not shown correctly

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3660]
Tested in build 3.4-SNAPSHOT-705 (spigot)
pumpkin and melon stems don't have different heights according to their growth state, also when connected to a pumpking or melon their texture is incorrect:
![image](https://user-images.githubusercontent.com/45831568/152800918-ff445a6b-be6e-46f3-9a04-6bd47fff80e9.png)

In-game:
![image](https://user-images.githubusercontent.com/45831568/152800720-65ae821e-9002-49db-bc2d-cf7155e3c178.png)

Nether wart is only shown half of their fungi:
![image](https://user-images.githubusercontent.com/45831568/152801723-ad8b07e5-bb0b-4bc7-9d97-e770993da93f.png)
In-game:
![image](https://user-images.githubusercontent.com/45831568/152801534-e80a5d52-a17a-4bed-bb7a-21243a5e330b.png)

**Comment by mikeprimm** [comment]
Fix in 719

**Comment by JurgenKuyper** [comment]
Confirmed, thanks!
