### ISSUE TITLE
Brewing stand bottom a plane instead of 3 circles

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3662]
Tested in build 3.4-SNAPSHOT-706 (spigot)
bottom of brewing stands are not like in-game, and also don't show their contents:
Dynmap:
![image](https://user-images.githubusercontent.com/45831568/152950355-d934bbba-a1ed-41d4-9d0a-2c855cd7c09b.png)
In-game: 
![image](https://user-images.githubusercontent.com/45831568/152950558-5f22d7a6-8b27-4bd9-8b75-6d2b1e5234fe.png)

**Comment by mikeprimm** [comment]
Fixed in 730

**Comment by JurgenKuyper** [comment]
confirmed in 731, thanks! 💚
