### ISSUE TITLE
Glass Panes are missing side texture

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3664]
Tested in build 3.4-SNAPSHOT-706 (spigot)
Dynmap:
![image](https://user-images.githubusercontent.com/45831568/152963774-772f81b7-69ce-4103-b836-34cec2f46b10.png)
In-game:
![image](https://user-images.githubusercontent.com/45831568/152964026-45b9214f-596d-458d-b231-1ade92fdfaba.png)

**Comment by mikeprimm** [comment]
Fixed in 718+

**Comment by JurgenKuyper** [comment]
Confirmed, thanks!
