### ISSUE TITLE
Path block lighting too bright

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3665]
Tested in build 3.4-SNAPSHOT-706 (spigot)
Dynmap:
![image](https://user-images.githubusercontent.com/45831568/152964328-b4156a8a-3861-40d3-89ff-85ca6ad24b96.png)

In-game:
![image](https://user-images.githubusercontent.com/45831568/152964274-1a99cf6e-cb47-4d41-bdd1-09bc7b9fbee6.png)

**Comment by mikeprimm** [comment]
lighting adjusted for path

**Comment by JurgenKuyper** [comment]
The side still seem a bit too bright in build 720:
Dynmap:
![image](https://user-images.githubusercontent.com/45831568/153766295-432af831-5a17-4413-8100-a0d1873005b2.png)
In-game:
![image](https://user-images.githubusercontent.com/45831568/153766307-e165c47f-25f3-4339-afc0-b8f8b611d1e0.png)

**Comment by mikeprimm-triva** [comment]
Same answer as #3666
