### ISSUE TITLE
Non-full blocks are brighter than their full-block counterparts

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3666]
Tested in build 3.4-SNAPSHOT-706 (spigot)
Dynmap:
![image](https://user-images.githubusercontent.com/45831568/152965625-4fd7cf11-73a3-4fb9-96f9-7277afdd4f7a.png)

In-game:
![image](https://user-images.githubusercontent.com/45831568/152965713-e86238ea-4d4c-4353-ae5e-2ca2073bbb89.png)

**Comment by JurgenKuyper** [comment]
probably contains the same fix as #3665 , found after further investigation.

**Comment by mikeprimm** [comment]
Same lighting isn't practical - not fixing
