### ISSUE TITLE
Sunflower seedbed not showing

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3668]
Tested in build 3.4-SNAPSHOT-706 (spigot)

Dynmap:
![image](https://user-images.githubusercontent.com/45831568/152968859-76fb01f2-0222-4c4e-89f1-a9a110a3d7d1.png)

In-game:
![image](https://user-images.githubusercontent.com/45831568/152968840-6a7a1b5a-d596-4aad-9cf9-7f95139f43a0.png)

**Comment by mikeprimm** [comment]
Fixed in 727

**Comment by JurgenKuyper** [comment]
confirmed, thanks! 💚
