### ISSUE TITLE
Dripleaf states not being rendered

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3670]
Tested in build 3.4-SNAPSHOT-706 (spigot)

Dynmap:
![image](https://user-images.githubusercontent.com/45831568/152976299-fda80d29-5fca-41dd-91da-0682fba29136.png)

In-game:
![image](https://user-images.githubusercontent.com/45831568/152976348-054a3872-f802-4a86-8a68-de4144593560.png)

**Comment by mikeprimm** [comment]
Fixed in 726

**Comment by JurgenKuyper** [comment]
I hate to be the bringer of bad news, but the rotation doesn't seem to be fixed on the big dripleaves at least, sadly: 
![image](https://user-images.githubusercontent.com/45831568/154270464-e30ac911-9390-45a7-9bc4-9c1354a0c210.png)

you have already done so much good work so far! thanks for all the work so far.

**Comment by mikeprimm** [comment]
<img width="863" alt="Screen Shot 2022-02-16 at 8 46 30 AM" src="https://user-images.githubusercontent.com/654487/154290092-953f7ef8-24ce-495d-aeb3-3ba9a6192402.png">

Vs 
![2022-02-16_08 50 37](https://user-images.githubusercontent.com/654487/154290191-fe58c9f0-1b38-4cdc-8f17-da35a1fa42df.png)

Sure looks right to me.

**Comment by JurgenKuyper** [comment]
hmm yes, must have been an optical illusion, checked it again and seems right, sorry
