### ISSUE TITLE
Spore Blossom not being rendered properly

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3671]
Tested in build 3.4-SNAPSHOT-708 (spigot)
Spore blossom is inverted, the green part should be rendered, but it isn't, also, the kelp-block top plane rotation is incorrect as seen by the white lines that don't match.
Dynmap:
![image](https://user-images.githubusercontent.com/45831568/153010530-8c9248b7-6e77-49b9-9915-e0e768c4260d.png)

In-game:
![image](https://user-images.githubusercontent.com/45831568/153010712-199c816f-0ae5-437c-8ce7-1e7ac6f2bc2c.png)

**Comment by mikeprimm** [comment]
Fixed in 728

**Comment by JurgenKuyper** [comment]
confirmed, thanks!
