### ISSUE TITLE
Unable to write web tiles error dynmap

### ISSUE THREAD

**Issue by Fefedu973** [webbukkit/dynmap#3672]
i am flood by this :
[12:00:57 INFO]: [dynmap] Image file plugins/dynmap/web/tiles/_markers_/marker_world.json - unable to write - failed
and dynmap map is totaly black

Dynmap version: core=3.3.2-696, plugin=3.3.2-696
Server Version: paper 1.18.1

**Comment by JurgenKuyper** [comment]
looks like a permissions issue, check wether the user and group is the same

**Comment by Fefedu973** [comment]
I have resolved the bug my folder was corrupted

**Comment by JurgenKuyper** [comment]
👍, I am going to close this for cleanness sake, if you still have an issue, open another one if not on this topic.
