### ISSUE TITLE
Texure Issue: Candles and cake

### ISSUE THREAD

**Issue by generrosity** [webbukkit/dynmap#3674]
Checking on snapshot [717], looks like candles and the cake-with-candle models arent working.

![image](https://user-images.githubusercontent.com/12838061/153707454-f9d616ae-79a1-497e-a049-df2d389646fc.png)
![image](https://user-images.githubusercontent.com/12838061/153707502-e6d8ecdb-5626-4bf0-a6ea-0262985c4823.png)

![image](https://user-images.githubusercontent.com/12838061/153707468-54894425-c358-4b00-8ef0-6098c08ce8da.png)
![image](https://user-images.githubusercontent.com/12838061/153707509-df96231b-3300-4d09-aa9d-fdd7698f0795.png)

Love your work Mike 💚👍

**Comment by mikeprimm** [comment]
Models added - like torches, we don't do the flame sprites, so lit vs unlit don't look different.   750 or later

**Comment by generrosity** [comment]
Ah, I thought the 'lit' candles had a different texture that was swapped over - not really important anyway, will get setup site to rerender tomorrow, cheers!

**Comment by mikeprimm** [comment]
Ironically, there are different texture files:
![candle_lit](https://user-images.githubusercontent.com/654487/155382898-f755c0a7-8adb-4833-a2b1-f37fc9744987.png)
![candle](https://user-images.githubusercontent.com/654487/155382916-ffd68310-2d9b-48c2-a808-1a691d9f11dc.png)
The differences are only in the 'lightening' of the body towards the wick - akin to what you see on the textures for redstone torches - versus the particle effects that are where the flame comes in.  We're using the texture files and models, as defined in the RP, but there is nothing to do to handle particle effects that wouldn't basically be block-by-block custom coding (which isn't gonna happen....)

**Comment by generrosity** [comment]
Interesting. Looking great! Thank you 💚
