### ISSUE TITLE
[dynmap] Exception while parsing JSON-file.

### ISSUE THREAD

**Issue by SkySai1** [webbukkit/dynmap#3675]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *After installing the plugin i have catching this warning message which cause freeze on server*

* **Dynmap Version:** *Dynmap version: core=3.3.1-683, plugin=3.3.1-683*
* **Server Version:** *This server is running CraftBukkit version 3423-Spigot-7fbc6a1-8f361ec (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/9XCLJvsZ*
* **Server Host (if applicable):** *Selfhosted on Ubuntu 18.04.2 LTS.*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/iQ3MZm7H*
* **Other Relevant Data/Screenshots:** *none
* **Steps to Replicate:** *IDK how its happening, this error often appears*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
try to update to the latest version of dynmap, backing up the old web files, and reuploading them from the dynmap folder.

**Comment by mikeprimm** [comment]
You've got a munged dynmap_webchat.json file (this is used to communicate web chat input from the web to the server via the PHP scripts) - just delete it

**Comment by SkySai1** [comment]
> You've got a munged dynmap_webchat.json file (this is used to communicate web chat input from the web to the server via the PHP scripts) - just delete it

Can u said where it place, because i didnt find it?

**Comment by JurgenKuyper** [comment]
it should be in your webpath\standalone folder which is in your case: /var/www/minecraft/standalone. check if the json file is there

**Comment by SkySai1** [comment]
> it should be in your webpath\standalone folder which is in your case: /var/www/minecraft/standalone. check if the json file is there

Thank you, found it and deleted.

**Comment by JurgenKuyper** [comment]
did that fix your issue? if so, you can go ahead and close this issue

**Comment by SkySai1** [comment]
> did that fix your issue? if so, you can go ahead and close this issue

Well dynmap creating a new dynmap_webchast.json file

**Comment by JurgenKuyper** [comment]
yes that is ok, as long as the error doesn't arise again it all works as expected

**Comment by SkySai1** [comment]
> yes that is ok, as long as the error doesn't arise again it all works as expected

Well it seems problem truly was in dynmap_webchat,sjon file.
I have turned off it (allowwebchat: false) in configuration.txt and problem is gone.
Thank you.
