### ISSUE TITLE
Up! again... sadly... SQLException: Error updating tables to version=3

### ISSUE THREAD

**Issue by gmfamily** [webbukkit/dynmap#3676]
Up! again... sadly...

**Please ping me if I have to open a new issue (as this one is mentionning 3.3.1 version).**

>.... [11:56:53 INFO]: [dynmap] **Enabling dynmap v3.3.2-696**
>.... [11:56:53 INFO]: [dynmap] Added 18 custom biome mappings
>.... [11:56:53 INFO]: [dynmap] Using LuckPerms 5.4.0 for access control
>.... [11:56:53 INFO]: [dynmap] Opening MySQL database ***.***.***.***:3306/************* as map store
>.... [11:56:53 INFO]: [dynmap] Updating database schema from version = 4
>.... [11:56:53 ERROR]: [dynmap] **SQLException: Error updating tables to version=3**
>.... [11:56:53 ERROR]: [dynmap] **ErrorCode: 1064, SQLState=42000**
>.... [11:56:53 ERROR]: [dynmap] Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALGORITHM=INPLACE, LOCK=NONE' at line 1
>.... [11:56:53 ERROR]: [dynmap] ConnectionString: jdbc:mysql://***.***.***.***:3306/*************?allowReconnect=true
>.... [11:56:53 ERROR]: [dynmap] **Map storage initialization failure**
>.... [11:56:53 INFO]: [dynmap] Unloaded 0 components.
>.... [11:56:53 INFO]: [dynmap] Disabled

I have restored previous beta-5 version that is running fine : 

>.... [11:58:31 INFO]: [dynmap] Enabling dynmap v3.3-beta-5-657
>.... [11:58:31 INFO]: [dynmap] Added 18 custom biome mappings
>.... [11:58:31 INFO]: [dynmap] Using LuckPerms 5.4.0 for access control
>.... [11:58:31 INFO]: [dynmap] Opening MySQL database ***.***.***.***:3306/************* as map store
>.... [11:58:31 INFO]: [dynmap] Schema version = 4
>.... [11:58:31 INFO]: [dynmap] Mod Support processing completed
>.... [11:58:34 INFO]: [dynmap] Loaded 27 shaders.
>.... [11:58:34 INFO]: [dynmap] Loaded 82 perspectives.
>.... [11:58:34 INFO]: [dynmap] Loaded 22 lightings.
>.... [11:58:34 INFO]: [dynmap] Starting enter/exit processing
>.... [11:58:35 INFO]: [dynmap] Web server started on address 0.0.0.0:25575
>.... [11:58:35 INFO]: [dynmap] version 3.3-beta-5-657 is enabled - core version 3.3-beta-5-657
>.... [11:58:35 INFO]: [dynmap] For support, visit our Discord at https://discord.gg/s3rd5qn
>.... [11:58:35 INFO]: [dynmap] For news, visit https://reddit.com/r/Dynmap or follow https://twitter.com/Dynmap
>.... [11:58:35 INFO]: [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
>.... [11:58:35 INFO]: [dynmap] If you'd like to donate, please visit https://www.patreon.com/dynmap or https://ko-fi.com/michaelprimm
>.... [11:58:35 INFO]: [dynmap] Loaded 2 maps of world 'world'.
>.... [11:58:35 INFO]: [dynmap] World 'world_nether' disabled
>.... [11:58:35 INFO]: [dynmap] World 'world_the_end' disabled
>.... [11:58:35 INFO]: [dynmap] Enabled
>.... [11:58:35 INFO]: [Essentials] Enabling Essentials v2.19.2
>.... [11:58:35 INFO]: [dynmap] Finish marker initialization

_Originally posted by @gmfamily in https://github.com/webbukkit/dynmap/issues/3652#issuecomment-1037169520_

**Comment by mikeprimm** [comment]
You're running a too old MySQL version (sorry, cannot support obsolete versions indefinitely, and this works on MySQL 5.6 or later, which became the newest version back in 2011.....).

You can get past this manually by running the following SQL by hand:

ALTER TABLE Tiles ADD COLUMN NewImage MEDIUMBLOB;

Once this is run, you should be able to start again without error from the SQL reported.

If your table is too big, this might run out of row locks, and then you're kind of toast and will need to recreate the database in order to get things working (the problem SQL is only needed for upgrade of existing version 3 schemas to the current version 5 schema, and a new database will be built directly with version 5).

**Comment by gmfamily** [comment]
Hello, thank you so much for your quick reply. I apply that and give you a feedback ASAP.

**Comment by gmfamily** [comment]
It's all ok now. Thank you so much for your quick valuable support. Also I don't know how we would do without your magical plugin ^^. Great work!
