### ISSUE TITLE
IP subnet in trusted proxy list

### ISSUE THREAD

**Issue by Foxite** [webbukkit/dynmap#3677]
**Feature Description:** Allow ip subnets to be specified in the list of trusted proxies in configuration.txt. For example, 192.168.0.0/24 or 172.0.0.0/8.

* **Additional context:** I need this because my minecraft server is running inside a docker container, and the proxy server is likewise running inside a docker container on the same machine. The minecraft server will see the request coming from an IP address such as 172.0.16.1, but the exact IP address is unpredictable as it may change with every restart of the proxy server container. I would like to simply add 172.0.0.0/8 to the list of trusted proxies, however a cursory reading of the [source code](https://github.com/webbukkit/dynmap/blob/v3.0/DynmapCore/src/main/java/org/dynmap/servlet/SendMessageServlet.java#L95) tells me this won't work.

If it does please tell me and close this issue.

Edit: Fixed "ip range" -> "ip subnet"

**Comment by jondycz** [comment]
Hello Foxite, I see you made changes to support IP ranges. While you're at it, would you mind taking a look at this? Unless I missed something, it's a minor code change in the same file: https://github.com/webbukkit/dynmap/issues/3678

**Comment by generrosity** [comment]
@Foxite you are contributing? awesomesause :) 💚 consider popping onto the Discord #dev chat and talk with the folks there. Mike is often quite happy to include contributers code - tho he does tend to look into the far future when it comes to adding any kinds of new dependancies

**Comment by mikeprimm** [comment]
Hey - I've got this implemented at this point (without adding any dependencies, which are generally problems for mods unless they get shaded and rebased, since they can cause conflict).  My change should also deal with #3678

**Comment by mikeprimm** [comment]
OK - code is in for 3.4-SNAPSHOT (build 750 or later) - please give it a look

Documented in https://github.com/webbukkit/dynmap/blob/v3.0/spigot/src/main/resources/configuration.txt#L413

**Comment by Foxite** [comment]
The feature works in the snapshot version. Thanks!
