### ISSUE TITLE
Dynmap port forwarding.

### ISSUE THREAD

**Issue by MrDeadGod** [webbukkit/dynmap#3679]
I know that it is years old issue, but i still didn't found the answer yet.

I port forward the dynmap web port "25566" and the server port "25565" TCP/UDP. Localhost:25566 works, but i want to share it with friends.

I don't use hosting service and i use latest version of dynmap.

I typed [SERVERIP]:25566, but it still didn't work. Then i tried my public [IPV4]:25566 and again, it still didn't work.

My web configuriation:

- tilespath: web/tiles
- webpath: web
- webserver-port: 25566
- webserver-bindaddress: 0.0.0.0

How can i fix this?

**Comment by MrDeadGod** [comment]
![image](https://user-images.githubusercontent.com/82360254/154019827-ffa96240-4c65-43e5-83af-1507212d23f9.png)
The port forwading..

**Comment by JurgenKuyper** [comment]
check while the server is running, if the port is open, using something like [yougetsignal.com](https://www.yougetsignal.com/tools/open-ports/), make sure you use http, not https as ssl is not supported on a bare dynmap webserver.

**Comment by MrDeadGod** [comment]
![image](https://user-images.githubusercontent.com/82360254/154023494-ba961203-f03b-4c92-9de2-3541e4bc296f.png)
It is opened, but its not working.
I tried on another browser its still not working..
![image](https://user-images.githubusercontent.com/82360254/154022764-cadbc475-2745-484d-bdc4-f2eb238b44c9.png)

**Comment by jondycz** [comment]
> ![image](https://user-images.githubusercontent.com/82360254/154019827-ffa96240-4c65-43e5-83af-1507212d23f9.png) The port forwading..

Why did you scramble the destination IP? You probably messed up that part. The port is open on the router but the router doesn't point to your computer. Use ipconfig in cmd to get your computer's IP address. Also make sure to make it static. Your issue is also not a big report and is completely inrelevant to dynmap.

**Comment by MrDeadGod** [comment]
> > ![image](https://user-images.githubusercontent.com/82360254/154019827-ffa96240-4c65-43e5-83af-1507212d23f9.png) The port forwading..
> 
> I used cmd to get my IPv4 adress and i typed it in...

**Comment by MrDeadGod** [comment]
![image](https://user-images.githubusercontent.com/82360254/154024942-2a9b5725-87e1-44a0-999e-f8a3ef9315dd.png)
put it in the 
![image](https://user-images.githubusercontent.com/82360254/154024754-d475f727-48e4-421c-b66c-9be0cd733b78.png)

**Comment by jondycz** [comment]
Can you connect to your Minecraft server from WAN? Whether you only have issues with dynmap or Minecraft fails to connect too. Another thing to do might be to open the ports on your computer's firewall.

**Comment by MrDeadGod** [comment]
> 

Yes i can connect to it

**Comment by MrDeadGod** [comment]
![image](https://user-images.githubusercontent.com/82360254/154025679-8aac8571-5fa6-45ca-8aec-9e7174d15bd5.png)
![image](https://user-images.githubusercontent.com/82360254/154025774-d5da267e-ba7f-4de9-9879-b931380e9649.png)

**Comment by JurgenKuyper** [comment]
don't use / port, use :port, so like 78.58.26.45:25566

**Comment by MrDeadGod** [comment]
> don't use / port, use :port, so like 78.58.26.45:25566

![image](https://user-images.githubusercontent.com/82360254/154026075-3fe65c63-b7a6-4c87-ac9d-17fdc336fb29.png)
like this?
It don't let me join...

**Comment by JurgenKuyper** [comment]
in browser, yes, in minecraft it should be 25565...

**Comment by MrDeadGod** [comment]
![image](https://user-images.githubusercontent.com/82360254/154026331-62820a9b-40a7-4645-a882-9f8d369a0564.png)

**Comment by JurgenKuyper** [comment]
![image](https://user-images.githubusercontent.com/45831568/154026362-d2f64ec1-bc8b-41cf-bc08-e783f353786d.png)
I again see a /. use : as I said, so `25.58.69.15:25566` not `25.58.69.15/25566`

**Comment by MrDeadGod** [comment]
I was a bit dum... I worked thx alot...

**Comment by Paranthaman-06** [comment]
Try this method its works 100% without any additional port

https://www.lunarmc.live/2024/09/how-to-setup-dynmap-without-additional.html?m=1
