### ISSUE TITLE
webp Tile background color is not transparent

### ISSUE THREAD

**Issue by ApliNi** [webbukkit/dynmap#3683]
It is normal in png format, this problem occurs after changing it to webp-l
tried setting background: 'transparent or #00000000 or reg(0,0,0,0)' in world.txt, but it doesn't work
Am I setting it wrong?

But you can get translucent tiles through glass
![112](https://user-images.githubusercontent.com/59365724/154267765-ce8bd13f-3817-40f3-be84-d2fbce71377f.png)
I modified the CSS to get a background with a pattern, so I need transparent tiles
thanks )

**Comment by JurgenKuyper** [comment]
are you still using the default jpg storage standard, which cannot create transparent backgrounds IIRC? Try to use PNG as storage standard. also: there have been many changes after 3.3-beta-2, maybe this is changed in the latest version, 3.3-beta-5

**Comment by ApliNi** [comment]
> ry to use PNG as storage standard

png does not have this problem, i changed it to webp (i forgot to describe webp..

**Comment by mikeprimm** [comment]
I think I've got a lead on this - we encode the image for WEBP internally as PNG (which handles alpha fine) before passing it to the external cwebp tool to encode, BUT the rendering logic was treating anything that wasn't PNG as not supporting alpha (transparency), so the PNG had the background color baked in, and this was true in the resulting WEBP too.  Coding fix now.

**Comment by mikeprimm** [comment]
Fixed in 3.4 SNAPSHOT 746 or later

**Comment by ApliNi** [comment]
Thanks
