### ISSUE TITLE
Dynmap webserver title not changing

### ISSUE THREAD

**Issue by Syntaxwastaken** [webbukkit/dynmap#3686]
hello, i setuped dynmap webserver and changed the title from dynmap\web\index.html.
Then i restarted the server and when i opened webserver and when its loading it showed the title i changed but after site if fully loaded it is showing the server motd as the title of webserver map. help me to change the title...

**Comment by JurgenKuyper** [comment]
Change webpage-title in configuration.txt

**Comment by Syntaxwastaken** [comment]
@JurgenKuyper tysm it worked, i removed that # and added webpage-title to server name now its working
