### ISSUE TITLE
How to set dynmap spawn

### ISSUE THREAD

**Issue by Swapneel665** [webbukkit/dynmap#3694]
What is the command for dynmap spawn my spawn is at 29000-x , 64-y , 29000-z

**Comment by JurgenKuyper** [comment]
dynmap uses the worldspawnpoint, as stated in the component section: https://github.com/webbukkit/dynmap/wiki/Component-Configuration

**Comment by generrosity** [comment]
You may otherwise be wanting to set the world or map 'center'

**Comment by Swapneel665** [comment]
So do I have to use the command /setspawn or /setworldspawn will that change the spawn point in dynmap like i wanna move that spawn icon to 29k-x 29k-z

**Comment by JurgenKuyper** [comment]
Setworldspawn should do it.

**Comment by Swapneel665** [comment]
K lemme try it
