### ISSUE TITLE
Use both URL and SkinsRestorer plugin

### ISSUE THREAD

**Issue by ApliNi** [webbukkit/dynmap#3698]
Get skin from URL when there is no skin in SkinsRestorer.
This is suitable for some online servers with SkinsRestorer installed.

**Comment by generrosity** [comment]
It might be easier for skinrestorer to return the correct skin when asked? Maybe you can suggest to them too? 

Im not sure if we actually 'check' to see there is a skin, just pass the URL to the frontend to handle. That might even need to be done in javascript.

I'm not certain our Dev included the code for SkinRestorer, so its possible unless someone comes to add code this wont get resolved.

**Comment by ApliNi** [comment]
It's probably really bad to put this question here, and it's not a commonly used feature. 

I found that dynmap always generates a skin in tiles, even if it's Steve, But I can only choose one skin source, SkinsRestorer or URL. 
What the front end receives is the skin or avatar in tiles, even if I choose to only get the skin through the URL. 

Thank you for answering this question though)
