### ISSUE TITLE
us.dynmap:spigot is missing from Maven repository

### ISSUE THREAD

**Issue by Sytm** [webbukkit/dynmap#3701]
To build my plugin which uses Dynmap as an optional component I need to have the `us.dynmap:spigot:VERSION:unshaded` artifact in my classpath so I can get an instance of the Dynmap API, but `us.dynmap:spigot` [is completely missing](https://repo.mikeprimm.com/us/dynmap/) in the repository.

Alternatively consider using the [Bukkit Service Provider API](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/plugin/ServicesManager.html) so you can grab a Dynmap API instance without the full platform build.

**Comment by generrosity** [comment]
Heya! Do you mind providing a screenshot or upload of where that reference is used so the guys can make comment? And, if you use gradle, the gradle reference? (sorry if that is off the mark)

I'm pretty sure that the API is working, so it just might be something trivial.

**Comment by Sytm** [comment]
I used it in this line [here](https://github.com/Sytm/waypoints/blob/92b449e3c40f9c71fffc6a2cb978145b938f7b66/waypoints/src/main/kotlin/de/md5lukas/waypoints/integrations/DynMapIntegration.kt#L36).

Or is there any other way of getting an API instance?

**Comment by mikeprimm** [comment]
Including the concrete class defeats the point of an interface-based API contract.   Here's an example of the right way to do it:

https://github.com/webbukkit/Dynmap-EssentialsX/blob/master/src/main/java/org/dynmap/essentialsx/DynmapEssentialsXPlugin.java#L394

**Comment by Sytm** [comment]
> Including the concrete class defeats the point of an interface-based API contract. Here's an example of the right way to do it:
> 
> https://github.com/webbukkit/Dynmap-EssentialsX/blob/master/src/main/java/org/dynmap/essentialsx/DynmapEssentialsXPlugin.java#L394

Yeah that solves it.

Additionally the way it is done should also appear somewhere in the wiki of this repository

**Comment by generrosity** [comment]
> Additionally the way it is done should also appear somewhere in the wiki of this repository

The wiki is editable - where were you looking, and what would you suggest?
