### ISSUE TITLE
DynMap - Render Bugging Out

### ISSUE THREAD

**Issue by ac96789** [webbukkit/dynmap#3706]
Hi,

After performing multiple full renders of the map. I keep eventually getting the same issue. (See Screenshot)
![image](https://user-images.githubusercontent.com/17512776/157154143-20cc53f3-8da5-4e85-bdfb-ce49eb0f6a41.png)

I'm using the latest version of the plugin on 1.18.2.

To see the issue for yourself, click here: http://139.99.212.193:7301/

**Comment by JurgenKuyper** [comment]
Are you self-hosting or using a provider?

**Comment by ac96789** [comment]
Shockbyte Hosting

**Comment by JurgenKuyper** [comment]
https://shockbyte.com/billing/knowledgebase/92/How-to-Set-Up-Dynmap.html 
Maybe you forgot to set the resolution to lowres or vlowres?

**Comment by ac96789** [comment]
> https://shockbyte.com/billing/knowledgebase/92/How-to-Set-Up-Dynmap.html Maybe you forgot to set the resolution to lowres or vlowres?

Had already checked that. It's set to lowres

**Comment by FedUpWith-Tech** [comment]
can you send the logs after you ran a fullrender?

**Comment by generrosity** [comment]
checking linked site - looks to be rendering - if further issues do reopen the case and add the usual logs and details
