### ISSUE TITLE
Only showing overworld, no nether, no end.

### ISSUE THREAD

**Issue by MinqApoc** [webbukkit/dynmap#3707]
Hello everyone

I've run into the problem of having missing worldmaps. The server  i was asked to admin hast a personalized worldname which i'll just call  'Boop'.

The plugin shows the following:

world/overworld
world/lostcities
world/the_end
world/thenether
Boop/overworld

But nothing else? How do i get the other 3 maps besides overworld for world 'Boop'??

**Comment by FedUpWith-Tech** [comment]
You can enable and disable worlds as well as add or remove maps using the dmap command
https://github.com/webbukkit/dynmap/wiki/Commands#mapworld-configuration-commands

**Comment by MinqApoc** [comment]
Except i can't. I mean yeah, technically i can enable and disable worlds. I disabled the standard world named 'world' so only 'Boop' is left. But 'Boop' is not showing nether, end, or lostcities on Rlcraft. They don't exist. And the link you provided (which i already had open anyway) is not really helpful because none of the commands helps me with my problem :)

Boop/the_nether does not show up in the browser and not in the files. And the commands don'T solve that.

**Comment by generrosity** [comment]
I'm wondering if there is a terminology difference here. 

In dynmap, Overworld, Nether (DIM-1) and the End (DIM1) are each worlds. Worlds and dimensions are kinda the same thing. Especially if you are live on Dynmap, change dimensions and see if you can click to follow the character movement.

Just to confirm - this is just one server? You have removed the template of information that we usually ask for, things like confirming you are on a Forge 1.12 server with hub worlds or other unusual mods that change the way dimension IDs work, anything extra added or how the server is hosted, if you have tested this in a laptop test world, etc.

**Comment by MinqApoc** [comment]
Sorry about template info, this is my very first time using github in any capacity, i have no idea how stuff works and i made this account specifically for this problem.

For confirmation: It is just one server, it is on Forge 1.12, no unusual mods that change dimension IDs as fas as i am aware, nothing added.

About terminology:

Yes, i know they're all worlds. My problem seems to be that whoever administrated this server before, wanted the world people actually play on to have a specific community-name ('Boop') but didn't bother with deleting the default world 'world'. And in the dynmap data, there's the world 'world' and all its dimensions (DIM-1, DIM1, etc) but they're all for 'world' and there is no nether, end or else to be found for 'Boop'. Even though there's clearly nether portals and you can enter and leave the nether. Yet it doesn't generate any data for Dynmap.

Clicking to follow the character movement does nothing. Like literally nothing.

Again i wanna apologize for violating github manners :/

**Comment by JurgenKuyper** [comment]
no problem, can you check the output of /dmap worldlist, all the found worlds by dynmap should be there.
maybe the other worlds are actually nether and end, they are just misnamed?

**Comment by MinqApoc** [comment]
/dmap worldlist
[01:32:14] [Server thread/INFO]: world Boop: loaded=true, enabled=true, title=Boop/overworld, center=-38.0/64.0/264.0, extrazoomout=2, sendhealth=true, sendposition=true, protected=false, showborder=true§r
[01:32:14] [Server thread/INFO]: world DIM111: isenabled=false§r
[01:32:14] [Server thread/INFO]: world DIM1: isenabled=false§r
[01:32:14] [Server thread/INFO]: world DIM-1: isenabled=false§r
[01:32:14] [Server thread/INFO]: world DIM-1: isenabled=false§r

Freshly copied from the server's console.

Edit: sorry for the wait, family issues ^^'

**Comment by ghost** [comment]
Im fairly sure in thinking one of the DIM-1 and DIM1's are the nether and end for your specific world, as thats how dynmap does it on my world. You could try deleting the /web/tiles/world data, leaving only boop, also delete /dynmap/forgeworlds.yml and restart, you should end up with a clean yml file for dynmap to load the data for boop.

**Comment by JurgenKuyper** [comment]
@MinqApoc do you still require help with this issue?
if not you can go ahead and close this one.
