### ISSUE TITLE
The site with the map does not work

### ISSUE THREAD

**Issue by Salik001** [webbukkit/dynmap#3709]
![Screenshot_1](https://user-images.githubusercontent.com/60126183/157603362-2f7379f3-8881-4479-9ea8-22dec69af68b.png)

**Comment by JurgenKuyper** [comment]
that is because you use the same port for minecraft as for dynmap, which is not allowed. use another port for dynmap. your host might be able to open a secondary port.

**Comment by Salik001** [comment]
I created a server on a hosting computer there is no port and use another one

**Comment by generrosity** [comment]
If your host can't provide you with another port you can use, then you can't use dynmap, sorry. There are no workarounds to that problem

**Comment by generrosity** [comment]
Closing - happy to reopen, but sounds like you need your host to open a second port for you
