### ISSUE TITLE
Add Support For Microsoft SQL Storage

### ISSUE THREAD

**Issue by nmills3** [webbukkit/dynmap#3711]
> template is **bold**
> sample data is *italicized*

**Feature Description:** Would it be possible to add support for storing data in a MSSQL db in the same way that we have sqlite, mariadb and mysql support?

* **Additional context:** *Please add any additional information you feel will help us understand the feature*

**Comment by generrosity** [comment]
Just to pitch in, from [previous requests](https://github.com/webbukkit/dynmap/issues/3085) we've confirmed that connections to databases generally comes bundled from the host system like Spigot or Forge. In their case, someone took ownership and created a [MySQL JDBC mod](https://www.curseforge.com/minecraft/mc-mods/mysql-jdbc). 

It might be that a feature doesn't get added here, but similarly someone owns and creates a small shim mod to provide the MSSQL connector for the correct Forge/Spigot/etc.

**Comment by generrosity** [comment]
From the Discord, I see these mentions:

- The Dev: "Just checked in 'microsoftsql' type - so should be in build in a little while" - this likely means you can test via the 'head' or 'snapshot' version of dynmap, tho I don't see a PR specifically for it
- @kosma has very kindly created a MSSQL driver that you can test with https://www.curseforge.com/minecraft/mc-mods/mssql-jdbc
