### ISSUE TITLE
Map not working on 1.18.2

### ISSUE THREAD

**Issue by NikiT0x1c** [webbukkit/dynmap#3712]
After updating the plugin from 1.18.1 to 1.18.2, the plugin stopped loading, updated to the latest version.
The core is Paper.
Pastebin of latest.log: https://pastebin.com/kLRtwHbG

**Comment by JurgenKuyper** [comment]
3.3-beta is not latest, 3.4-beta-2 is, try that one

**Comment by NikiT0x1c** [comment]
Sorry my problem. Now everything works. Thanks.
