### ISSUE TITLE
Server startup hangs on "Updating database schema from version = 4"

### ISSUE THREAD

**Issue by JCombee** [webbukkit/dynmap#3715]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Server startup hangs on "Updating database schema from version = 4".*

* **Dynmap Version:** *Dynmap-3.4-beta-2-spigot.jar*
* **Server Version:** *Paper version git-Paper-242 (MC: 1.18.2)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/Lxqhezza*
* **Server Host (if applicable):** *apexminecrafthosting.com*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/TuBzReQN*
* **Other Relevant Data/Screenshots:** *I'm using a map from minecraft 1.18.1 and besides dynmap there is Chunky v1.2.164, WanderingTrades v1.7.1, LuckPerms v5.4.9*
* **Steps to Replicate:** *I have not gone to the length of replicating it yet since I did not wan't to risk corupting my dynmap database yet. Since I do not know what the inner workings are of this step where he is stuck I was not yet willing to stop it. And I belive it's a incredible data set to download to actually try to replicate it locally.*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
that is not a bug, it just needs to update the database, which if having a huge map, takes a long time

**Comment by Aheradin** [comment]
For the next time it should have an option to do this in parallel while the server is opened.

**Comment by JurgenKuyper** [comment]
That sadly is not possible iirc, as dynmap needs the storage to work

**Comment by JCombee** [comment]
Hmm, I think still something went wrong. It after waiting a while it just killed dynamo and continued starting the server. When it was fully started dynmap didn’t work. I’ll send a update from the log file at a later moment.

after a few tries though it worked so I don’t need more support on this but I will leave the log file for completeness if I get to it.
