### ISSUE TITLE
[bug] 1.18.1 class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel

### ISSUE THREAD

**Issue by CKY-** [webbukkit/dynmap#3716]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

placing backpacks on the ground from Sophisticated Backpacks 
or Open iron door with button 

* **Dynmap Version:** *Dynmap 3.3.2-696*
This is the crashlog has way more information then you need but its better to have too much then not enough 

Place backpack 
https://crashy.net/mWbttqmCj0vKx9CXYAcn

open iron door 
https://crashy.net/Q0Mrizpuzqmi228Sd2iW

 [x ] *I have looked at all other issues and this is not a duplicate*  
 [x ] *I have been able to replicate this*

**Comment by mikeprimm-triva** [comment]
We don't technically support running Dynmap in the client (which is what this appears to be associated with), but I'll give working around it a look.

**Comment by mikeprimm-triva** [comment]
Try latest development build - it should not throw error, but update triggers will likely not work.

**Comment by CKY-** [comment]
I can confirm that the bandaid stopped the crash with iron doors and backpacks placed in the world while im testing things client side. Thank you for such a fast patch and quick reply. 
I do understand that this is a server side ONLY plugin, and you really wouldn't want to run it on clients. 
again thank you.
