### ISSUE TITLE
Why is the 3D pixelated soapy mode

### ISSUE THREAD

**Issue by Salik001** [webbukkit/dynmap#3718]
Why is the 3D pixelated soapy mode
![Screenshot_1](https://user-images.githubusercontent.com/60126183/158946546-09d90fe4-15f4-407f-ae1d-5eb347968e2b.png)

**Comment by Salik001** [comment]
![изображение](https://user-images.githubusercontent.com/60126183/158946595-91f43498-6f57-4f68-9c47-7f76a685e143.png)

**Comment by JurgenKuyper** [comment]
you probably have the resolution set to lowres or vlowres, which generates what you see. if you host/storage allows for it, change to the default hires, and rerender the world.

**Comment by Salik001** [comment]
how to do?

**Comment by JurgenKuyper** [comment]
set the deftemplatesuffix to hires in configuration.txt and rerender

**Comment by JurgenKuyper** [comment]
@Salik001 did you get it to work?
