### ISSUE TITLE
Certain blocks rendering without proper shading

### ISSUE THREAD

**Issue by NJDaeger** [webbukkit/dynmap#3719]
**Issue Description:** *I recently updated to dynmap 3.4-beta-2-761, and it seems that certain blocks (typically stairs, slabs, and trapdoors- there may be others) render with no shading applied to them.*

* **Dynmap Version:** *3.4-beta-2-761*
* **Server Version:** *git-Paper-409 (MC: 1.17.1)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/5ziUPyQK*
* **Server Host (if applicable):** *N/A*
* **Pastebin of crashlogs or other relevant logs:** *N/A*
* **Other Relevant Data/Screenshots:** 

> [Example 1. (Ignore the red brick texture, that was an actual change.) Shows trapdoors, stairs, and slabs turning from their original rendering to their new rendering](https://media.discordapp.net/attachments/722558498470101048/955179247574605895/unknown.png)

> [Example 2](https://media.discordapp.net/attachments/722558498470101048/955179903769251910/unknown.png)

* **Steps to Replicate:** *Render the dynmap with this version*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

I will mention, another friend and I have both seen this issue recently. I am coming from version 3.2-beta-3

**Comment by JurgenKuyper** [comment]
I don't see the issue on the map? maybe because of the lower resolution. can you elaborate on the issue?

**Comment by NJDaeger** [comment]
The map shown is a bit of a lower resolution.

For context, I have circled a few examples of stairs in the second example image.
![image](https://user-images.githubusercontent.com/18237863/159189778-6b38f760-283b-42fd-8df9-560e5ac14b6c.png)

This also shows the typical shading of a stair block, for reference.

Basically, there is no shading on the stair block, even though there should be. (NOTE: This extends further than the stair block, it's also walls, slabs, and trapdoors)

Edit: View the image sent in another window. The background in GitHub completely kills the shading on that
Edit 2: here is an image of a properly shaded stair block on dynmap:
![image](https://user-images.githubusercontent.com/18237863/159189886-908ae9e1-9da9-493d-aafc-3812789006d1.png)

And here is an image of an improperly shaded stair block: 
![image](https://user-images.githubusercontent.com/18237863/159189913-ee94423c-d6f1-4b97-9db7-a48be199a076.png)

**Comment by generrosity** [comment]
@JurgenKuyper @FedUpWith-Tech could this be related to something we talked to Mike about with transparent blocks lighting? We found a few blocks (slabs, path) that weren't quite right https://github.com/webbukkit/dynmap/issues/3666

**Comment by JurgenKuyper** [comment]
> @JurgenKuyper @FedUpWith-Tech could this be related to something we talked to Mike about with transparent blocks lighting? We found a few blocks (slabs, path) that weren't quite right #3666

Could be yes, would require investigationwith the boosted maps from the setup page, but I guess I already know the answer as it are not full blocks.

**Comment by NJDaeger** [comment]
I've got another example I think shows this better than my previous ones. Before and after images of the same location:

Old:
![image](https://cdn.discordapp.com/attachments/308045730105262080/943953973096882206/IMG_3172.png)

New:
![image](https://user-images.githubusercontent.com/18237863/159524317-8ba07fba-be95-41db-97fd-f47b189a4e6c.png)

**Comment by generrosity** [comment]
sorry - before and after what? Dynmap version change, config change?

**Comment by NJDaeger** [comment]
> sorry - before and after what? Dynmap version change, config change?

My apologies, I should have clarified. I mentioned it in my original message- I updated dynmap from 3.2-beta-3 (what the old image is from) to 3.4-beta-2-761 (what the new image is from)

**Comment by mikeprimm** [comment]
Check current DEV build

**Comment by NJDaeger** [comment]
This is fixed as far as I can tell in the dev build, thanks!
