### ISSUE TITLE
The End fullrender problem

### ISSUE THREAD

**Issue by NERFER-4** [webbukkit/dynmap#3722]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *When I do the fullrender of the End the flat map is't completely rendered, dynmap renders only the central island of the End. Instead, the entire dimension of the End is rendered in the surface map. How can I solve this problem?*

* **Dynmap Version:** *3.4-beta-2-761*
* **Server Version:** *Paper version git-Paper-267*
* **Pastebin of Configuration.txt:** *https://pastebin.com/uH22gYCq*
* **Server Host (if applicable):** *My computer (Windows 11)*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/crashcausedbydynmap*
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *I just used the <dynmap fullrender "world-name":flat> command*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
did you do a /dynmap fullrender world_the_end:flat? 
did dynmap state it finished the flat map render?
try to manually fly over to the islands once to generate the chunks, could be dynmap doesn't "see" them as they are too far apart. you can also take a look at fullrenderlocations in worlds.txt.

**Comment by NERFER-4** [comment]
-I did /dynmap fullrender c_the_end:flat
-Yes
-Ok, but why was the End surface map fully rendered?

**Comment by JurgenKuyper** [comment]
I don't know, could be the surface found a chunk, and the flat didn't. I don't know. Anyway, the options stated in my previous message should fix it.

**Comment by NERFER-4** [comment]
Ok, I'll try to do it.

**Comment by ghost** [comment]
Have you explored the end? If you have only loaded the End spawn island chunks, thats why. If not, check configuration.txt, and check your update triggers. Its also a suggestion to try /dynmap radiusrender <YourWorldName> 0 0 3000 and see if it then shows up, if not theres an issue somewhere. RadiusRender is also less intensive in my view, as you can pick a defined area, then just have exploring load new chunks.

EDIT: Just re-read the post. Check worlds.yml and see what your definitions are, then check the /web/tiles/ folder, delete the DIM1 folder, then rerun the radiusrender to start with a fresh map

**Comment by NERFER-4** [comment]
> Non lo so, potrebbe essere la superficie trovata un pezzo, e l'appartamento no. Non lo so. Ad ogni modo, le opzioni indicate nel mio messaggio precedente dovrebbero risolverlo.

I finally had the time to try; I went to the other islands starting from the central one running across the entire distance (without using the portals). Re-running the fullrender, dynmap finally rendered the entire flat map.

**Comment by NERFER-4** [comment]
> Hai esplorato la fine? Se hai caricato solo i pezzi dell'isola di Spawn End, ecco perché. In caso contrario, controllare la configurazione.txt e controllare i trigger di aggiornamento. È anche un suggerimento per provare / dynmap radiusrender 0 0 3000 e vedere se poi si presenta, se non c'è un problema da qualche parte. RadiusRender è anche meno intenso a mio avviso, in quanto è possibile scegliere un'area definita, quindi basta esplorare nuovi blocchi di carico.
> 
> EDIT: Basta rileggere il post. Controlla worlds.yml e vedi quali sono le tue definizioni, quindi controlla la cartella /web/tiles/, elimina la cartella DIM1, quindi riesegui il radiusrender per iniziare con una nuova mappa

Yes, I have already explored the End, however Dynmap completely rendered only the surface map, but of the flat one only the central island was rendered.
worlds.yml has # in front of each line so I don't think the file interacts with the configurations in my case.
As I wrote in the previous message I solved the problem but I'd like to know if there is some other way to solve it without running across the entire distance between the main island and all the others.

Thanks for the replies!

**Comment by Mendanbar** [comment]
Just like to chime in that I've just encountered this exact same issue.  In my case the flat map was working fine and rendering the entirety of the end, as was the isometric map.  There were some choppy renders due to elytra flight, so I kicked off a fullrender today of the end, and it removed everything from the flat map except the central island and reported job done.  The isometric map behaved as expected: updating tiles in all the missing sections.  Subsequent fullrenders have the same effect.  It's definitely suspicious that this just started happening, and that it seems to only render the central island. I'm using paper 1.20.4, and the only other plugins I have loaded are RHLeafDecay and FastChunkPregenerator (both of which weren't doing anything actively during the fullrender).

**Comment by Mendanbar** [comment]
I should also note that I tried deleting all tiles for `world_the_end` in the web\tiles directory and did a fullrender to see if I could get past the problem.  The iso map re-rendered all tiles without issue, but the flat map still only rendered the chunks surrounding the central island.

Oh, some more context that may or may not be relevant:  I'm using a custom end terrain gen datapack called Nullscape.  Seems unlikely to be the culprit though seeing as how the iso map generates without any problems.
