### ISSUE TITLE
Config to improve zoom quality

### ISSUE THREAD

**Issue by gdcmarinho** [webbukkit/dynmap#3724]
![image](https://user-images.githubusercontent.com/34725877/160253815-3c15a46d-15b5-4ca7-8274-e8730ce8530f.png)

What config should I use to improve the zoom texture quality?

**Comment by masmc05** [comment]
improve resolution, like if it's vlowres now, use lowres, is lowres, then highres, or your own perspectives where you define scale

**Comment by masmc05** [comment]
if you don't see your world in worlds.txt, then execute `dmap worldset worldname title:<label>`, where label is a custom name for the world, like "Overworld", then your world will appear in worlds.txt 
after that, search for all `perspective: <name>_<resolution>` and change resolution to a better one, and save worlds.txt
and finally, restart the server, purge rendered data, and redo a fullrender for the world
resolutions are: (resolution-explanation, higher scale= better quality in zoom, more lags from render)
vlowres - very low resolution (scale:2)
lowres - low resolution (scale:4)
medres - medium resolution (scale:8)
highres -high resolution (scale:16)
