### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by AloneBown** [webbukkit/dynmap#3730]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *map didn't shows, i get this text: net/http: HTTP/1.x transport connection broken: malformed HTTP status code "Exception:"*

* **Dynmap Version:** *dynmap v3.4-beta-3-774*
* **Server Version:** *paperspigot 1.18.2 *
* **Pastebin of Configuration.txt:** *https://pastebin.com/RbEjY3KD*
* **Server Host (if applicable):** *Hosting-Minecraft*
* **Steps to Replicate:** *just start a server*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
is 25679 the same port you use for minecraft? that is not possible, you need to get another one

**Comment by AloneBown** [comment]
thanks, its start working
