### ISSUE TITLE
extrazoomout: 3 not works

### ISSUE THREAD

**Issue by Skjolberg** [webbukkit/dynmap#3732]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *I have gone from having the map rendered in "Hires" to have it in "Lowres" because it occupied too much space, when I deleted the data and rendered again the map did not work, I have the modified worlds.txt and I suppose that the previous configuration that I had was not adequate for the resolution of "Lowres", so I tried to remove functions of the worlds. txt until it worked again and the problem is the "extrazoomout: 3" by removing that option I got the web map working again (it didn't load before going from "Hires to Lowres with the data deleted even and rendering again), so I guess there must be some problem there.*

* **Dynmap Version:** *Dynmap-3.4-beta-2-spigot.jar*
* **Server Version:** *Pufferfish 1.17.1*
* **Pastebin of Configuration.txt:** *https://pastebin.com/gYk2hXYP*
* **Server Host (if applicable):** *McProHosting, Shockbyte, Selfhosted, etc.*
* **Pastebin of crashlogs or other relevant logs:** *Worlds.txt -> https://pastebin.com/bKrVxdk7*
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
on Spigot 1.17.1 using the latest dynmap this works fine. could be your unsupported build is messing with the settings, we can only support paper, spigot, forge and fabric.
