### ISSUE TITLE
Who knows the Worldborder/Dynmap render problem?

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#3733]
We wanted to render our map from scratch with Worldboirer and Dynmap, but unfortunately we have had extreme problems and some error messages since 1.18.
It can no longer be properly rendered or generated.
Instead we always get the error message.
Has anyone had this before and knows a way to fix this problem?

https://pastebin.com/mqUU2Wqz

**Comment by JurgenKuyper** [comment]
I've never seen that issue, last I checked worldborder worked fine using spigot and dynmap on 1.18 and 1.18.2, maybe your server flavour is messing with it?

**Comment by FedUpWith-Tech** [comment]
Sounds like corrupted chunks or you are trying to load too many chunks at once, either try a different chunk loader or manually load chunks. Either way, this isn't really a dynmap issue
