### ISSUE TITLE
Hidden Style not working

### ISSUE THREAD

**Issue by pomtom44** [webbukkit/dynmap#3734]
> template is **bold**
> sample data is *italicized*

**Issue Description:** Trying to hide a section of the map, hidden limits has worked, but hidden style isnt working. Map just generates as black in that area, no matter what the hidden style is set to

* **Dynmap Version:** 3.3-beta-2-570
* **Server Version:** Forge-1.12.2-14.23.5.2859
* **Pastebin of Configuration.txt:** [*https://pastebin.com/5SETL3z2*](https://pastebin.com/xbiQP9VC)
* **Server Host (if applicable):** Self
* **Other Relevant Data/Screenshots:** 
Generated before putting hidden section in
https://imgur.com/Bhpexxt
Generated after putting hidden section in
https://imgur.com/AqW93Eh

* **Steps to Replicate:** 
Generate map
Edit config to have hiddenlimits
regenerate map (didnt delete tiles, just did a /dynmap fullrender)

 [ Y] *I have looked at all other issues and this is not a duplicate*  
 [ Y] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
That is what hiddenlimits do, I don't see a bug / issue here

**Comment by pomtom44** [comment]
> That is what hiddenlimits do, I don't see a bug / issue here

Im not talking about hidden limits, im talking about hide style

Reading though the wiki it says you can change the style of the hidden area to be stone or ocean
https://github.com/webbukkit/dynmap/wiki/World-and-template-settings

> hidestyle : If the visibilitylimits and/or hiddenlimits settings have restricted the visible areas of a world, the hidestyle setting is used to control how the chunks of map data being hidden are presented. 3 settings are supported: stone, which causes a stone plain to fill the hidden areas; ocean, which causes a deep ocean to fill the hidden areas; or air, which causes the hidden area to be empty (like the edge of the generated portion of the world map). The default value is stone.

From what im reading, its using the air setting, even though default is stone, and my config is set to ocean

**Comment by JurgenKuyper** [comment]
Just tested in latest dynmap (3.4-beta-3) on forge, stone seems to work.
![image](https://user-images.githubusercontent.com/45831568/162397635-2ff84e94-0c41-4875-aded-f8235d04a449.png)
ocean works too:
![image](https://user-images.githubusercontent.com/45831568/162400184-8a26541a-f912-4f71-a9b4-ebd39046c9c0.png)
air works as supposed to too: 
![image](https://user-images.githubusercontent.com/45831568/162400766-1436f58f-1aec-4a27-a871-38e005a2fa3b.png)

**Comment by pomtom44** [comment]
oh 3.4 isnt showing on github?
only shows 3.3 for me
had to find 3.4 from curseforge so will give that a go now

**Comment by JurgenKuyper** [comment]
yep, github only has releases, not betas

**Comment by pomtom44** [comment]
Nope, updated to 3.4 and still having the same issue
Running Dynmap-3.4-beta-3-forge-1.12.2
forge-1.12.2-14.23.5.2859

No other mods and basic config

what are you using for your one to work?

**Comment by JurgenKuyper** [comment]
I am using the 1.18.2 forge latest version (don't know the exact one as I am on my phone rn)

Can you send the output of /dmap maplist world?

**Comment by pomtom44** [comment]
Could it be an issue with 1.12.2 forge? as we are using that rather than 1.18

**Comment by JurgenKuyper** [comment]
I would have to test that but don't have much time this weekend, can you maybe test in 1.18.2 with the same config wether it works or not?

**Comment by pomtom44** [comment]
Will do soon (a few hours or so) and update you

**Comment by JurgenKuyper** [comment]
@pomtom44 did it work for you?

**Comment by pomtom44** [comment]
Hi, sorry yes
1.18.2 worked fine and shows ocean on the marked area

**Comment by JurgenKuyper** [comment]
Then test wether 3.4-beta-3 works on your version and if so, you can go ahead and close this issue

**Comment by pomtom44** [comment]
I already did
I was testing with 3.4 beta 3 on 1.12.2

> Nope, updated to 3.4 and still having the same issue Running Dynmap-3.4-beta-3-forge-1.12.2 forge-1.12.2-14.23.5.2859
> 
> No other mods and basic config

**Comment by JurgenKuyper** [comment]
that's odd, @mikeprimm in short, on 1.12.2 the hidestyle on lates dynmap doesn't work, but in 1.18.2 it does. Can you fit in time to look at this?

**Comment by pomtom44** [comment]
I will just say its not an issue if you dont have time to investigate
the black square works just as well for what im doing, just would look nicer with the water for the area i want to hide
I do understand 1.12 is very old, and mostly un supported now, 
Just still wanted to file a report if it was something you wanted to know about

**Comment by JurgenKuyper** [comment]
1.12.2 is no longer supported, so unless this issue is present in 1.14.4 or higher it is no longer relevant, closing this issue.
