### ISSUE TITLE
Error when I copyed the web folder to other vps 

### ISSUE THREAD

**Issue by z0z0r4** [webbukkit/dynmap#3735]
purpur 1.18.2 newest version
I render my map, and try to copy the web folder to other vps 
fullrender , /dynmap pause all  ( maybe because I didn't stop it but pause it? 
By SQLite

website return these text 
```
standalone/SQLite_tiles.php?tile=world/_2/0_-12/zzzzzzz_0_-384.webp

Warning: SQLite3::__construct(): open_basedir restriction in effect. File(/server/PCLSurvivalServer/server/plugins/dynmap/web/dynmap.db) is not within the allowed path(s): (/dynmap/:/tmp/) in /dynmap/standalone/SQLite_tiles.php on line 77

Fatal error: Uncaught Exception: open_basedir prohibits opening /server/PCLSurvivalServer/server/plugins/dynmap/web/dynmap.db in /dynmap/standalone/SQLite_tiles.php:77 Stack trace: #0 /dynmap/standalone/SQLite_tiles.php(77): SQLite3->__construct() #1 {main} thrown in /dynmap/standalone/SQLite_tiles.php on line 77
```

```
standalone/SQLite_markers.php?marker=faces/16x16/k0rnyuwu.png

Warning: SQLite3::__construct(): open_basedir restriction in effect. File(/server/PCLSurvivalServer/server/plugins/dynmap/web/dynmap.db) is not within the allowed path(s): (/dynmap/:/tmp/) in /dynmap/standalone/SQLite_markers.php on line 37

Fatal error: Uncaught Exception: open_basedir prohibits opening /server/PCLSurvivalServer/server/plugins/dynmap/web/dynmap.db in /dynmap/standalone/SQLite_markers.php:37 Stack trace: #0 /dynmap/standalone/SQLite_markers.php(37): SQLite3->__construct() #1 {main} thrown in /dynmap/standalone/SQLite_markers.php on line 37
```

/server/PCLSurvivalServer/server/plugins/dynmap/web is from my render vps (I rendered these in this
/dynmap is from my web vps (I copyed web folder to this

**Comment by z0z0r4** [comment]
![image](https://user-images.githubusercontent.com/78744121/162558393-f09b5387-2242-4b62-beb3-7d8f7745ba42.png)
![image](https://user-images.githubusercontent.com/78744121/162558395-f0615d96-0321-4a8c-b0e1-59a07082bbcd.png)
All requests with PHP have this question

**Comment by z0z0r4** [comment]
because this file doesn't be changed?
![image](https://user-images.githubusercontent.com/78744121/162558542-338612a5-21e6-4419-9f66-794a56264719.png)

**Comment by JurgenKuyper** [comment]
Your host has restrictions on which paths can be accessed using PHP. You also probably didn't update the new webserver paths and reupload from the "render server"

**Comment by z0z0r4** [comment]
I chmod 777 to /dynmap, but it still doesn't work...
![image](https://user-images.githubusercontent.com/78744121/162574929-faea62eb-ad03-4648-bd3d-03bc7a44c381.png)

what should I do?
![image](https://user-images.githubusercontent.com/78744121/162574945-1365cc25-d47a-4c7d-adca-25ca7e95dcf4.png)
![image](https://user-images.githubusercontent.com/78744121/162574947-8b197c61-b41c-480e-865a-753254cd7596.png)

I have been updated the new webserver paths
![image](https://user-images.githubusercontent.com/78744121/162574982-55fb35fe-b30e-4071-a4bb-03fdb83eaf18.png)
![image](https://user-images.githubusercontent.com/78744121/162574978-491c9a36-5901-4b6c-bb83-b66889a3cf8b.png)

**Comment by JurgenKuyper** [comment]
I'd say, run through the [guide](https://github.com/webbukkit/dynmap/wiki/%5BTutorial%5D-Setting-up-a-standalone-web-server-with-MySQL-SQLite/) for external webserver setup as if it is a new setup and then check if it works
