### ISSUE TITLE
% left on radiusrender

### ISSUE THREAD

**Issue by LarveyOfficial** [webbukkit/dynmap#3736]
### **Feature Description:** 

- When doing a radius render, if a set block radius is set there should be a way to calculate how many tiles are left out of that set block radius. Of course its impossible to tell the exact number as some tiles may already be rendered, but you can either estimate or check how many tiles in that block radius are already rendered and subtract them from the equation 

### **Additional context:** 

- Currently the report is as follows ``Radius render of map 'flat' of 'world' in progress - 100 tiles rendered (148.97 msec/tile, 105.66 msec per render)``

**Comment by JurgenKuyper** [comment]
Thank you for your feature request. Due to the volume of feature requests we receive we have relocated all of our features requests to a single issue #3461.
