### ISSUE TITLE
Hide the "Modellist" error

### ISSUE THREAD

**Issue by YannD-Deltagon** [webbukkit/dynmap#3741]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Hello, add the possibility to hide this error https://i.imgur.com/IRrkJ2j.png*

* **Additional context:** *At each start I end up with millions of lines like this, so yes, I know, I play modded, it doesn't work very well, but hey, if I can avoid wasting 20 minutes of start-up just to calculate each output log :D*
https://i.imgur.com/IRrkJ2j.png

**Comment by JurgenKuyper** [comment]
these error logs are there for a reason, especially since they have the fatal flag. 
we can't do much about it as it is up to the mod creator of that block that is errorring to properly implement the blockstates

**Comment by YannD-Deltagon** [comment]
I understand, but as for the "verbose" flag, you can't have a "modellist" flag.
for once, I understand that there are errors, given the number of mods, it's already really a crazy thing that dynmap and bloackscan happens to generate files like this, but a flag for non-dev, it can lighten the load of the server, there, the logs are heavy to load each time :'(

**Comment by YannD-Deltagon** [comment]
Is there a way with a java argument to hide these logs?
Sincerely, I understand the concern of leaving them displayed for the devs, but, personally, it just fills up my hard disk, and slows down the loading since at each boot, I type billions of bug lines :'(

**Comment by FedUpWith-Tech** [comment]
The logs only indicate what the server is doing, they don't add any meaningful load to the server.
