### ISSUE TITLE
How to add serverTimezone=UTC

### ISSUE THREAD

**Issue by Rinkerbel** [webbukkit/dynmap#3742]
I can't manually add the flag because the field is not there.

Manually adding it doesn't work either.
Typing: _&serverTimezone=UTC_ behind the database name wont work either.
The link ends up as: _&serverTimezone=UTC?allowReconnect=true&autoReconnect=true_

I am using version: 3.4-beta-3-774

**Comment by JurgenKuyper** [comment]
You need to add them behind the last entry, not in front, can you send the MySQL flags snippet?

**Comment by Rinkerbel** [comment]
I can't put it behind it because there is no field for flags, they get automatically added but they don't include serverTimezone

**Comment by Rinkerbel** [comment]
![IMG_20220415_071439.jpg](https://user-images.githubusercontent.com/77461173/163523911-03151bc0-0b99-4a44-ac2f-dce93701eb53.jpg)

**Comment by JurgenKuyper** [comment]
https://github.com/webbukkit/dynmap/blob/v3.0/spigot/src/main/resources/configuration.txt#L42 somehow they got removed on your file

**Comment by Rinkerbel** [comment]
Ty, this fixed it for me!
