### ISSUE TITLE
Unknown Chunk dataVersion: 2975 when running the chunkVersion shader after forceUpgrade

### ISSUE THREAD

**Issue by JurgenKuyper** [webbukkit/dynmap#3743]
**Issue Description:** *world created in 1.16.5, updated server to 1.18.2, ran --forceUpgrade on the first boot of the new server, after succesfull start I get the message: [09:42:37 WARN]: [dynmap] Unknown chunk dataVersion: 2975
the map renders fine, just a warning*

* **Dynmap Version:** *3.4-beta-3-777*
* **Server Version:** *paper 1.18.2 - 274*
* **Pastebin of Configuration.txt:** *https://pastebin.com/SKzpG2Wh*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/HghNUep1*
* **Other Relevant Data/Screenshots:** *none*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

discord user "TAS 2012" found this bug, writing this report to keep track of the issue.

**Comment by mikeprimm** [comment]
Added versions for 1.18.2, 1.19 and (likely) 1.19.1 GA
