### ISSUE TITLE
Include images in the dynmap

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#3744]
Good day,
I don't know if something like this already exists. I've been looking for a bit but haven't found anything.
Maybe something like this already exists, if not it would be great if something like this would come sometime.

I would like the user to click on a maker on the map, then a window opens where you can see a picture of the zone or building where you can also read one.

**Comment by JurgenKuyper** [comment]
That is currently not possible, you can add this request to the mega thread to keep them all in the same spot, if it is not already there
