### ISSUE TITLE
trees are not showing

### ISSUE THREAD

**Issue by 1Pootis1** [webbukkit/dynmap#3747]
![image](https://user-images.githubusercontent.com/73141732/165634929-59f0ff7d-0239-4671-8045-bf1baf68b6bd.png)

**Issue Description:** *I've rendered the map and it doesn't show trees, what should I do?*

* **Dynmap Version:** *Dynmap-3.4-beta-2-spigot*
* **Server Version:** *paper 1.17.1 build 409*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by 1Pootis1** [comment]
re-rendering did not help, also, the dynmap version was updated to beta 3

**Comment by JurgenKuyper** [comment]
The EarthMC and custom worldpainter maps havr many known issues with Dynmap such as, incomplete render, only rendering where players have visited, or not rendering leaves and other foliage.
This is a result of how the map was made and is not an issue with Dynmap, luckily there is a fix.

1. Download the WorldBorder plugin: https://www.spigotmc.org/resources/worldborder.60905/
2. Pause Dynmap: /dynmap pause all
3. Run worldborder with the force flag: /wb [worldname] fill [freq] [pad] [force]
- [worldname] is the name of your world folder
- [freq] is how many chunks a second are generated, 20 is the default. WARNING: setting this too high will cause server lag
- [pad] how many chunks beyond the border to generate, this makes sure that if a player visits the border, all chunks are already generated.  The default is 208, I recommend setting this to 0 for EarthMC
- [force] This must be set to true
4. Wait for worldborder to finish
5. Unpause Dynmap /dynmap pause none, you may have to restart the fullrender using /dynmap fullrender [worldname]

I don't know if worldborder still works, the other way is to fly around the world and generate the chunks that way

**Comment by JurgenKuyper** [comment]
@1Pootis1 did you manage to fix it?

**Comment by JurgenKuyper** [comment]
closing due to lack of response, please reopen if you didn't get it fixed.
