### ISSUE TITLE
Add Band-aid to Forge 1.16.5 like #3716

### ISSUE THREAD

**Issue by serquis** [webbukkit/dynmap#3748]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Dynmap sample feature request description. This description would include as much and as little detail necessary for us to understand the feature in its entirety.*
Add Band-aid to Forge 1.16.5 too.
I understand that Dynmap is a server plugin, but please don't abandon local players.
I at least want to avoid crashes.

* **Additional context:** *Please add any additional information you feel will help us understand the feature*
#3716

**Comment by mikeprimm** [comment]
Just added this - should be in for v3.4-beta-5

**Comment by serquis** [comment]
Thank you very much!
Very pleasant to play with!
I appreciate very much what you have done.
