### ISSUE TITLE
[dynmap] World 'World' disabled. how to fix?

### ISSUE THREAD

**Issue by Doom664** [webbukkit/dynmap#3749]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** *Dynmap-3.4-beta-3-spigot*
* **Server Version:** *Spigot version 1.18.1*
* **Pastebin of Configuration.txt:** *https://pastebin.com/BBPVXpvi*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *no crash log just world disabled and can't enable*
* **Other Relevant Data/Screenshots:** *nope web sever set up just world not rendering and not loaded*
* **Steps to Replicate:** *issue: I set up dynmap and everything even the websever but then when i do the /dynmap fullrender (then the world) it fails saying world not defined when i check the console for the sever it says that the "world" is disabled*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Vlow is nat a valid template, check the valid names in configuration.txt

**Comment by Doom664** [comment]
> Vlow is nat a valid template, check the valid names in configuration.txt

wdym? is vlow not a setting so its not loading? if so I will try

**Comment by JurgenKuyper** [comment]
vlow is not either vlowres, lowres, medres, hires, or vhires no.

**Comment by Doom664** [comment]
OMG i am so stupid;-; ok thanks it worked i am sooooo stupid but thanks for the help i got it working now :D

**Comment by JurgenKuyper** [comment]
no problem.
