### ISSUE TITLE
Some Warnings in LOG File

### ISSUE THREAD

**Issue by GroGaloraGran** [webbukkit/dynmap#3751]
Hello
_when the plugin is running, I see a lot of warnings in the server LOG that bother me.
tell me how to fix it
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
part of the LOG below:_

**Dynmap-3.3-beta-5-spigot.jar
paper-1.18.1.jar:git-Paper-216
https://pastebin.com/YsaXLy22**
[ *] *I have looked at all other issues and this is not a duplicate* 
[ *] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
try 3.4-beta-4

**Comment by GroGaloraGran** [comment]
Ok I will try and give feedback

**Comment by JurgenKuyper** [comment]
As no response was given back, assuming the issue got fixed. Closing this issue. if that is not the case, feel free to open the issue again.
