### ISSUE TITLE
Question: How can I individualize Dynmap?

### ISSUE THREAD

**Issue by Turtle-Boi** [webbukkit/dynmap#3752]
Hi, this is more of a question than a feature request.
So, I have webregister required on my dynmap, and I wanted to make it so that when you log into dynmap, you can only see yourself. So like if a player had webregistered and is currently on my dynmap, I want it to only show them, but then if I log into dynmap, I want to be able to only see myself. Is this possible, and if so, how?

*Also, if this is possible, is it possible for op players to have access to viewing all players? Thanks*

**Comment by JurgenKuyper** [comment]
@Corbinator333 sorry for the late reply, I think what you are looking for is the protected-player-info setting in configuration.txt:

```If true, player positions/status is protected (login with ID with dynmap.playermarkers.seeall permission required for info other than self)```
    protected-player-info: true

**Comment by JurgenKuyper** [comment]
closing thread, user didn't reply so deemed fixed.
