### ISSUE TITLE
Dynmap won't render modded blocks on Ragnamod modpack

### ISSUE THREAD

**Issue by Enohriel** [webbukkit/dynmap#3758]
Hello,
Dynmap won't render any modded block even after a pass of BlockScan ; modpack Ragnamod. 
LostBot on Discord was able to reproduce the issue.

Edit : renderdata folder IS populated after BlockScan pass.

* **Dynmap Version:** *Dynmap-3.4-beta-3-forge-1.16.5*
* **DynmapBlockScan Version:** *DynmapBlockScan-3.4-SNAPSHOT-forge-1.16.5*

* **Server Version:** *forge 1.16.5*
* **Pastebin of Configuration.txt:** *https://pastebin.com/B1Hq8mY3*
* **Server Host (if applicable):** *Selfhosted on dedicated*
* **Pastebin of crashlogs or other relevant logs:** *Log first start with BlockScan : [here](https://cloud.cyberinc.pro/s/C85mfszMNLTDRpL) ; Log next start BlockScan moved out : [here](https://cloud.cyberinc.pro/s/3EXRiTamGwr5JDj)*
* **Other Relevant Data/Screenshots:** *Modpack Ragnamod VI*
* **Steps to Replicate:**  
- Install fresh Ragnamod VI modpack server.
- Add Blockscan and dynmap mods.
- Start server a first time with BlockScan
- Stop the server
- Move remove BlockScan
- Start the server
- Start fullrender
- Map rendered without modded blocks

**Comment by Enohriel** [comment]
I figured out that some mods are incompatible and trigger the error.

I'm still investigating on which ones.

**Comment by Enohriel** [comment]
After many hours of trial and errors, I finally found out the culprits:
Environmental Core and Twilight Forest seems to be incompatible !

**Comment by JurgenKuyper** [comment]
thanks! I will create a list and add those to said list.

**Comment by JurgenKuyper** [comment]
https://github.com/webbukkit/dynmap/wiki/Mods-found-to-be-incompatible-with-Dynmap-and-Dynmap-blockscan
added a list to the github for others to read. As this is out of our control I am going to go ahead and close this issue for now.
