### ISSUE TITLE
Feature request - ModSupport

### ISSUE THREAD

**Issue by ItJustFox** [webbukkit/dynmap#3760]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Dynmap sample feature request description. This description would include as much and as little detail necessary for us to understand the feature in its entirety.*
Is there a way to add more Mod Support like for Chisel or custom mod directly in dynmap ? (if no can we make it manually by adding manually the texture ?)

* **Additional context:** *Please add any additional information you feel will help us understand the feature*

**Comment by JurgenKuyper** [comment]
the only mod support is through dynmap-blockscan, if that doesn't find it, it is not supported

**Comment by ItJustFox** [comment]
And there is now way to force him use texture for some block, because he same to dont load Chisel texture and well our spawn / some base look a bit empty ^^" ?

**Comment by JurgenKuyper** [comment]
Not that I know off no

**Comment by JurgenKuyper** [comment]
closing this report. if you need help with another part of dynmap, you can open another report.
