### ISSUE TITLE
Dynmap cannot be accessed through a standalone web server.

### ISSUE THREAD

**Issue by MooreFoss** [webbukkit/dynmap#3761]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *I followed the tutorial [here](https://github.com/webbukkit/dynmap/wiki/%5BTutorial%5D-Setting-up-a-standalone-web-server-with-MySQL-SQLite/). But dynmap cannot be accessed through a standalone web server. Console output is 'Uncaught TypeError: Cannot read properties of null (reading 'error')'*

* **Dynmap Version:** *Dynmap-3.4-beta-3*
* **Server Version:** *paper 1.18.2 build 333*
* **Pastebin of Configuration.txt:** *https://pastebin.com/RSc3D9Ak*
* **Server Host (if applicable):** *home*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/wXMQn1X1*
* **Other Relevant Data/Screenshots:** *My Nginx conf is https://pastebin.com/LQ5Aievw*
* **Steps to Replicate:** *[this](https://github.com/webbukkit/dynmap/wiki/%5BTutorial%5D-Setting-up-a-standalone-web-server-with-MySQL-SQLite/)*

 [√] *I have looked at all other issues and this is not a duplicate*  
 [√] *I have been able to replicate this*

**Comment by MooreFoss** [comment]
The cause is an error caused by database access permission Settings

**Comment by sudoShiba** [comment]
> The cause is an error caused by database access permission Settings

How do you fix it?
@MooreFoss
