### ISSUE TITLE
Are There Any Standlone Version For Dynmap?

### ISSUE THREAD

**Issue by MRNOBODY-ZST** [webbukkit/dynmap#3762]
Are There Any Standlone Version For Dynmap? Like Bluemap, it has a CLI version for distributed processing.

**Comment by JurgenKuyper** [comment]
No, dynmap only exists as a mod/plugin.

**Comment by FedUpWith-Tech** [comment]
note: while there isn't a standalone version of dynmap it is possible to run the dynmap website without a minecraft server or the dynmap plugin. Dynmap must be configured for an external webserver and files copied at runtime to the webserver location then it will run even if the server is offline. Obviously there won't be live player updates and there is some optimization as your browser doesn't need to poll for updates every second on what is functionally a static, unchanging map. I hope to do a write up of this process soon
