### ISSUE TITLE
[Bug] SQLState=08001 when using sql

### ISSUE THREAD

**Issue by zyxkad** [webbukkit/dynmap#3764]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

I try to run dynmap with sqlite, but I got some problem:  
**The server log:**
```log
[Server] [05:12:24] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap] SQLException: Error updating Maps table
[Server] [05:12:24] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap]   ErrorCode: 0, SQLState=08001
[Server] [05:12:24] [Dynmap Render Thread/FATAL] [Dynmap]: [Dynmap]   Message: No suitable driver found for jdbc:sqlite:/minecraft/server/dynmap/dynmap.db
```
I don't know what's wrong. It also happens when I use mysql

* **Dynmap Version:** *Dynmap-3.4-beta-3-forge-1.12.2*
* **Server Version:** *forge-1.12.2-14.23.5.2860*
* **Pastebin of Configuration.txt:** *https://pastebin.com/8PdUj9Uv*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *See before*
* **Other Relevant Data/Screenshots:** *None*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [ Y ] *I have looked at all other issues and this is not a duplicate*  
 [ Y ] *I have been able to replicate this*

**Comment by zyxkad** [comment]
I actually using docker to start my server, but it will work fine when I use file system (not sql) with dynmap

**Comment by JurgenKuyper** [comment]
Forge needs the SQLite driver, as stated on the wiki: https://github.com/webbukkit/dynmap/wiki/SQLite-Storage

**Comment by zyxkad** [comment]
Thanks for help, would you like add this notice to the main page? I think there are some lazy one like me will not look the wiki
