### ISSUE TITLE
Schema version set wrong PostgreSQL

### ISSUE THREAD

**Issue by MarijnDoeve** [webbukkit/dynmap#3765]
**Issue Description:** When using PostgreSQL as map storage the schema version gets misaligned which breaks markers

* **Dynmap Version:** version 3.4-beta-3 (core version 3.4-beta-3-774)
* **Server Version:** fabric 1.18.2 (0.51.1+1.18.2) PostgreSQL 14.2
* **Pastebin of Configuration.txt:** [click](https://gist.github.com/TheRijn/2d037d8e3e155c656cf2e2f83a8dce8a#file-config-yml)
* **Server Host (if applicable):** Selfhosted via Docker Compose
* **Pastebin of crashlogs or other relevant logs:** [click (part of the same Gist as above)](https://gist.github.com/TheRijn/2d037d8e3e155c656cf2e2f83a8dce8a#file-logs)

* **Steps to Replicate:** 

I had problems with markers sometime after migrating to PostgreSQL, so I started investigating by replacing my config.txt with a new one with a new database. This worked fine, I saw in the logs that it had problems with migrating so I paid particular attention to the schema version on the fresh start of Dynmap. It started with version 4. Everything was working again.

After a server restart, I saw the same issues with markers again. And in the logs, I saw `[Dynmap] Updating database schema from version = 3` again. But I was sure it already was on version 4.

Logging in into the database I saw the `schemaversion` was indeed set 3, I changed it manually to 4 and everything worked again!

- [x] *I have looked at all other issues and this is not a duplicate*  
- [x] *I have been able to replicate this*

**Comment by MarijnDoeve** [comment]
Apparently, the initial version was just set wrong in code, not as complicated as I initially thought.

**Comment by JurgenKuyper** [comment]
yep, that pull request should change that, thanks for bringing this to our attention, the dev is currently very busy, so it might be some time until this gets patched.
