### ISSUE TITLE
web server

### ISSUE THREAD

**Issue by StonFlip** [webbukkit/dynmap#3772]
> template is **bold**
> sample data is *italicized*

**Issue Description:** hello, I used the post https://github.com/webbukkit/dynmap/wiki/External-Webserver-Basics , but the map does not work, it says Dynmap configuration object missing.

* **Dynmap Version:** Dynmap-3.4-beta-2-spigot
* **Server Version:** patina 1.16.5
* **Pastebin of Configuration.txt:** https://pastebin.com/5e4TT2ey
* **Server Host (if applicable):** spacecore
* **Pastebin of crashlogs or other relevant logs:** my map address https://map.cbtpolit.xyz/
* **Other Relevant Data/Screenshots:** https://imgur.com/a/JUdlNGn
* **Steps to Replicate:**  I used the post https://github.com/webbukkit/dynmap/wiki/External-Webserver-Basics

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
That guide can only be used if the webserver and Minecraft server are on the same machine, if that is the case, did you upload the web folder after the external web settings were set in configuration.txt?

**Comment by StonFlip** [comment]
Yes, I uploaded the contents of the web folder to the folder , web server and server minecraft are on the same machine
https://imgur.com/a/WEeTdrB

**Comment by JurgenKuyper** [comment]
please try with the normal frontend, not liveatlas, as that is not supported by us.

**Comment by StonFlip** [comment]
map works but no interface or chunks
https://map.cbtpolit.xyz/

**Comment by JurgenKuyper** [comment]
is standalone/config.js populated and readable by the webserver?

**Comment by StonFlip** [comment]
maybe? I dont know 
https://imgur.com/a/YORcjD8

**Comment by JurgenKuyper** [comment]
That is not the file I am asking about, there should be a config.js in the standalone folder...

**Comment by StonFlip** [comment]
No, there is no config.js file in the standalone folder

**Comment by JurgenKuyper** [comment]
Then there is your issue, it should have been created either by dynmap itself or by the webserver when you changed the settings to external, is it in the mc server's dynmap/web/standalone folder?

**Comment by StonFlip** [comment]
No, config.js is not in standalone , but just web folder, I recreated dynmap directory

**Comment by JurgenKuyper** [comment]
did you check if the config.php was created and uploaded?

**Comment by StonFlip** [comment]
Yes, configuration.php is in the standalone folder

**Comment by JurgenKuyper** [comment]
can delete both web folders and you try to redo step 3?

**Comment by StonFlip** [comment]
folder web in plugins/dynmap and web in var/www/html ?

**Comment by JurgenKuyper** [comment]
yes, if you did render a lot you can back up the tiles directory

**Comment by StonFlip** [comment]
I will delete completely and if it works I will make a new render please wait until the morning and I will answer
Everything is complicated by a large online server and the lack of a dynmap reload command

**Comment by StonFlip** [comment]
I deleted the web files in /plugins/dynmap and var/www/html , but they were not recreated after the restart, and if you go to the map, a small part of the interface still loaded

**Comment by StonFlip** [comment]
Web files are not matched with plugin version: All files need to be same version (undefined) - try refreshing browser cache (shift-reload)

error 
https://map.cbtpolit.xyz/

**Comment by StonFlip** [comment]
I have already tried completely re-creating the dynmap category and the web category.. it doesn't help.

Gives an error message:
Web files are not matched with plugin version: All files need to be same version (undefined) - try refreshing browser cache (shift-reload)

I tried restarting the browser, it didn't help.
Other resources say that with such an error, you just need to recreate the files, but this did not help me

**Comment by JurgenKuyper** [comment]
are you using a proxy with caching on your domain? try using the direct IP of the dynmap server.

**Comment by StonFlip** [comment]
Yes, I'm using BungeeCord + TCPshield and Cloudfare , most likely the direct IP address will not work, I already tried it but I'll try again later

**Comment by StonFlip** [comment]
> are you using a proxy with caching on your domain? try using the direct IP of the dynmap server.

It did not help

**Comment by StonFlip** [comment]
I solved this problem, thanks for your help

**Comment by JurgenKuyper** [comment]
👍 what was the issue?

**Comment by StonFlip** [comment]
I don't know, but I can attach the config

**Comment by JurgenKuyper** [comment]
that won't be needed really. I am going to go ahead and close this issue tracker. If you have any further questions you can reopen this issue or create a new one.
