### ISSUE TITLE
Dynmap to keep track of truly explored chunks when using pregen

### ISSUE THREAD

**Issue by Owlchemist** [webbukkit/dynmap#3774]
**Feature Description:** *In order to help with server lags, some admins will pregen the chunks. However, this takes some of the fun out of exploring when providing a map to players. If dynmap could track player movement and their vis range, perhaps it could keep a running database of chunks that have truly been explored, and only render those.*

**Comment by JurgenKuyper** [comment]
if you only install dynmap after the pregeneration cycle, and enable the playermove trigger, (which is kinda resource expensive) should do what you want.

**Comment by JurgenKuyper** [comment]
closing this issue because the user did not respond for a while, and a workaround is available.
