### ISSUE TITLE
Black screen on external webserver using MySQL

### ISSUE THREAD

**Issue by TurtleException** [webbukkit/dynmap#3781]
After following the instructions from #2609 to setup my external webserver on a different machine with MySQL and NGINX the dynmap is only showing me a black screen (not an empty map, a completely black screen).

Chrome's Developer Tools console shows this error:
![console-error](https://user-images.githubusercontent.com/88295743/174688279-1d319a23-1cfb-4fa1-83de-42329bc49707.png)

Also the site shows this alert:
> Could not retrieve configuration: error

I am using *dynmap-3.4-beta-3-spigot* on *spigot 1.18.2* with [this configuration](https://pastebin.com/AbLT03A9).
The MySQL credentials in `MySQL_configuration.php` do work and have SELECT, INSERT, UPDATE, DELETE, CREATE and INDEX privileges.
Also everything on the gameserver-side _seems_ to be working fine, as the database actually gets filled.

**Comment by JurgenKuyper** [comment]
What do the nginx error logs state? Did you install php-fpm and php-mysqli?, Did you set them to the right version in the nginx site conf?

**Comment by TurtleException** [comment]
The nginx error logs say this
```[error] 9962#9962: *157 connect() failed (111: Connection refused) while connecting to upstream, client: <my ip>, server: map.*, request: "GET /standalone/MySQL_configuration.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "map.[my domain]", referrer: "https://map.[my domain]/"```

> Did you install php-fpm and php-mysqli?

Yes, I did. But is there any way of testing if I made a mistake?
 

> Did you set them to the right version in the nginx site conf?

Honestly I don't know how, as nginx is completely new to me. How exactly would I do that?

**Comment by TurtleException** [comment]
It looks like I didn't install php-mysqli properly and forgot to specify the correct version for php-fpm in my nginx config.
Sorry for wasting your time ^^
