### ISSUE TITLE
Dynmap Remove Outer Layer

### ISSUE THREAD

**Issue by KentBrought** [webbukkit/dynmap#3789]
**Issue Description:** Hey I was wondering if its possible to just disable the outermost zoom layer (the most zoomed out) section of the dynmap and make it not rerender it and not delete more than 1. Thanks! 

* **Dynmap Version:** 3.2-beta-1-470
* **Server Version:** Paper version git-Paper-"e04368045" (MC: 1.16.5)
* **Pastebin of Configuration.txt:** [*https://pastebin.com/5SETL3z2*](https://pastebin.com/hVx2vHEa)
* **Server Host (if applicable):** N/A
* **Pastebin of crashlogs or other relevant logs:** N/A
* **Other Relevant Data/Screenshots:** N/A
* **Steps to Replicate:** Zoom out all the way on dynmap and press the plus button once. That layer is what I mean

**Comment by JurgenKuyper** [comment]
you can change the zoomout level either in worlds.txt or by using the dmap commands, which will as far as I know need a rerender of the map, you can try what it does without the rerender, if that doesn't work you need to do another fullrender of that world / map.

**Comment by KentBrought** [comment]
In the worlds.txt file are you talking about the "extrazoomout" setting? I was going to change this, but my map seems to have six layers that I can zoom into, but the value is set to 2. If I were wanting to remove just one would I have to just change it by 0.5?

**Comment by JurgenKuyper** [comment]
No, you have zoomout levels and zoomin levels, you have the base value set in configuration.txt for all maps, and on top of that the zoomouts / zoomins of each map get added. + The extrazoomouts(int) of that world

**Comment by KentBrought** [comment]
Okay thanks I got it working!
