### ISSUE TITLE
Radiusrender

### ISSUE THREAD

**Issue by sandboxgamer92** [webbukkit/dynmap#3791]
**Issue Description:** *Unfortunately "/dynmap radiusrender" doesn't work anymore since the update to 1.19.
Chatt:
`Render of 10 block radius starting on world 'world'`
`Radius render of map 'flat' of 'world' completed - 0 titles rendered (0,00 msec/map-title, 0,00 msec per render)`
`Radius render of map 'surface' of 'world' completed - 0 titles rendered (0,00 msec/map-title, 0,00 msec per render)`
`Radius render of map 'cave' of 'world' completed - 0 titles rendered (0,00 msec/map-title, 0,00 msec per render)`
`Radius render of 'world' finished.`
This comes in chat in 1 second. I've tried other places, but the result is always the same.
The command: "/dynmap fullrender world" works normally.*

* **Dynmap Version:** *3.4-beta-4*
* **Server Version:** *1.19*
* **Steps to Replicate:** *Use the "radiusrender" command*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
command requires a radius - '/dynmap radiusrender 20' for example.  Just checked it, and it appears to be working as normal.

**Comment by JurgenKuyper** [comment]
Hey Mike, I just tested it with core=3.4-SNAPSHOT-813, plugin=3.4-SNAPSHOT-813, and it still seems to be broken: 
![image](https://user-images.githubusercontent.com/45831568/182022586-8671d38e-e275-4e9b-aaee-0b7c9e863bd6.png)

**Comment by mikeprimm** [comment]
Same build, spigot-1.19.1:
<img width="1134" alt="Screen Shot 2022-07-31 at 1 20 54 PM" src="https://user-images.githubusercontent.com/654487/182040013-22283e9c-02f1-41a4-adf0-2ade163a9520.png">

**Comment by JurgenKuyper** [comment]
so it's a paper 1.19 issue, indeed in 1.19.1 it works, but in 1.19.0 it didn't

**Comment by masmc05** [comment]
@mikeprimm i think it was fixed in https://github.com/webbukkit/dynmap/pull/3794 , had this issue while testing and then fixed it in same pr
@PatrickBronke can you test the beta5?

**Comment by masmc05** [comment]
i think it's related to refusing to work with loaded chunks, and only with saved ones, same issue i had and which i fixed (and since it's broken with 1.19, when async chunk load support came, more reasons to think it was it)

**Comment by sandboxgamer92** [comment]
Hi @mastermc05 . It is all ok.
