### ISSUE TITLE
Forbidden You don't have permission to access this resource.

### ISSUE THREAD

**Issue by StonFlip** [webbukkit/dynmap#3792]
> template is **bold**
> sample data is *italicized*

**Issue Description:** Forbidden
You don't have permission to access this resource.

* **Dynmap Version:** 3.4 beta 3 spigot
* **Server Version:** Purpur 1.16.5
* **Pastebin of Configuration.txt:** not required
* **Server Host (if applicable):** not required
* **Pastebin of crashlogs or other relevant logs:** https://map.cbtpolit.xyz/
* **Other Relevant Data/Screenshots:** not required
* **Steps to Replicate:** I moved the server directory to another folder and also changed the startup user (was root), I gave the right to use the var/vvv/html/ folder, but I still get an error that there are not enough rights

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
did you do it for all the files of the folder? (chown -R www-data:www-data web) instead of the web folder itself?

**Comment by StonFlip** [comment]
only chmod -R 700 /var/www/html/ 
if this is not enough, could you give a command how to do it.. I gave the web server directory above

**Comment by StonFlip** [comment]
It helped setting permissions 775 folder var.

close

**Comment by StonFlip** [comment]
And by the way, before you close, me and my players have a problem with the card flashing ..
This is solved by entering from another browser or waiting for several hours
how can this be solved?
https://imgur.com/a/yUaZUag

**Comment by JurgenKuyper** [comment]
I don't know, that is not the dynmap frontend
