### ISSUE TITLE
Black lines that disappear once zoomed in on surface maps only.

### ISSUE THREAD

**Issue by ultraic-space** [webbukkit/dynmap#3793]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *I'm having a weird issue where lines/rows of chunks appear black once you zoom in. The chunks are rendered, but they appear black until you zoom in. This is happening for maps that are both fully generated or pregenerated; but only happens on **surface maps**.*

You can view my dynmap @ https://map.ultraic.space/
The world shown below is griyego's surface map, on the left; but the issue also shows with the default world's surface map.

fully zoomed out
![image](https://user-images.githubusercontent.com/108235651/177713974-dd3567a2-6f42-4248-89e9-3da59e76e503.png)
zoomed in to the top right
![image](https://user-images.githubusercontent.com/108235651/177713905-92eb9c04-9f7e-4003-92b3-3d94f9af50f6.png)
![image](https://user-images.githubusercontent.com/108235651/177714067-9a367e7d-ac6a-404e-ac81-5cfcd7f52a7e.png)
1 step before being fully zoomed in
![image](https://user-images.githubusercontent.com/108235651/177714128-c3bd942b-c1f8-48f6-909e-b3a47374a75c.png)

* **Dynmap Version:** *Dynmap version: core=3.4-beta-4-792, plugin=3.4-beta-4-792*
* **Server Version:** *git-Purpur-1685 (MC: 1.19)*
* **Pastebin of Configuration.txt:** *https://www.toptal.com/developers/hastebin/releyodale.yaml*
* **Server Host (if applicable):** *WitherHosting*
* **Pastebin of crashlogs or other relevant logs:** *https://www.toptal.com/developers/hastebin/xenibaxova.md*
* **Other Relevant Data/Screenshots:** *I am using MySQL with an external webserver. Both are working and are configured properly.*
* **Steps to Replicate:** *Pregen a world, or/and (issue persists with both in this case) upload a fully generated world with WorldPainter, and then do renders for both.*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Did you restart while you were rendering the map?

**Comment by ultraic-space** [comment]
> Did you restart while you were rendering the map?

Yep, I have my server on daily restarts and this has been running for just over a week now.

**Comment by JurgenKuyper** [comment]
that is not great, as it causes that issue, it is best to do /dynmap pause all before a restart, that prevents this issue. you can radiusrender the areas to fix these chunks.

**Comment by MRNOBODY-ZST** [comment]
wow i had met this issue before
i thought it was a MySQL issue
Anyway THX  :-P
@JurgenKuyper

**Comment by JurgenKuyper** [comment]
no problem, @ultraic-space do you still need help? if so, please feel free to reopen this issue.
