### ISSUE TITLE
Could not retrieve configuration: error

### ISSUE THREAD

**Issue by StonFlip** [webbukkit/dynmap#3795]
> template is **bold**
> sample data is *italicized*

**Issue Description:** dynmap config
Dynmap Version: 3.4 beta 3 spigot
Server Version: Purpur 1.16.5
Pastebin of Configuration.txt: https://pastebin.com/PmzThxH1
Server Host (if applicable): not required
Pastebin of crashlogs or other relevant logs: https://map.cbtpolit.xyz/
Other Relevant Data/Screenshots: not required
Steps to Replicate: This problem appeared this afternoon, I did not touch the configuration.txt file and did not move the web category. Previously, everything worked well, before writing this, I found information about this error, they wrote that there may not be rights to view or write the config.js file, but there are rights. To make sure of this, I recreated the web category, it loaded completely, but the error did not disappear

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by StonFlip** [comment]
Now there's another problem:    Web files are not matched with plugin version: All files need to be same version (undefined) - try refreshing browser cache (shift-reload)

Last time I solved it by changing the config, now it does not help, I did not change the config until the moment of the error, so there is something else.. I tried to run the map without a webserver, it helped... But what could be the problems with the webserver? I have permissions set to 777 and the owner of the directory, and I also tried to completely reinstall the dynmap folder and take the web folder from there - it did not help.

**Comment by StonFlip** [comment]
I fixed it, sorry for the extra panic) but don't close it yet

**Comment by JurgenKuyper** [comment]
I don't see anything wrong on the map, what is the issue that you are facing in which we need to keep this tracker open?
