### ISSUE TITLE
[1.19] Forge changes break this mod

### ISSUE THREAD

**Issue by jellybean13** [webbukkit/dynmap#3796]
**Issue Description:**
There are two breaking changes in Forge 41.0.x:
Breaking change 1: [41.0.64](https://github.com/MinecraftForge/MinecraftForge/commit/4d074f0a1ef1d774786b4f1e1e3e827a9bf576e0).
Breaking change 2: [41.0.94](https://github.com/MinecraftForge/MinecraftForge/commit/b8b40e1f547c16df1d8914a707e338057a7497bd).
Affected classes: https://github.com/webbukkit/dynmap/blob/v3.0/forge-1.19/src/main/java/org/dynmap/forge_1_19/DynmapPlugin.java#L1631
This mod needs to be updated otherwise the game will crash.

* **Dynmap Version:** *3.4-beta-4*
* **Server Version:** *Forge 1.19 build 41.0.98*
* **Server Host (if applicable):** *Selfhosted*
* **Steps to Replicate:** *Use this mod on dedicated server with Forge 41.0.94 and upper installed.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
Fixed in current dev builds: breaking change will break using the fixed code on anything before 41.0.94, but that was Forge's decision when they made breaking API change after a major release was already 94 builds old....

**Comment by jellybean13** [comment]
This issue needs to be closed sinse https://github.com/webbukkit/dynmap/commit/425c87089593658b0e7f2f8ee164e32f712cfae5.
