### ISSUE TITLE
Please add option to disable rendering all worlds by default

### ISSUE THREAD

**Issue by zhro** [webbukkit/dynmap#3799]
I would like to see an option in configuration.txt where all worlds are not enabled by default, but rather only those as defined in worlds.txt. This would be much appreciated since we tend to load and unload worlds periodically on our server, and I only want dynmap to be rendering one of them at any given time.

**Comment by JurgenKuyper** [comment]
That is already possible by setting enabled:false in the template of that is loaded by the deftemplatesuffix

**Comment by zhro** [comment]
Can you clarify how to do this?

My interpretation of this description in the documentation was that this could only be done in worlds.txt:

https://github.com/webbukkit/dynmap/wiki/World-and-template-settings

> enabled : if defined, this allows mapping for a given world to be enabled (by setting true) or disabled (by setting false). All worlds are enabled by default, so defining a worlds entry for a world and setting enabled to false is the only way to prevent a world from being displayed and mapped.

**Comment by JurgenKuyper** [comment]
That is not true, you can just edit the template normal-hires for the deftemplatesuffix hires, and set enabled to false.
