### ISSUE TITLE
Hiding worlds in worlds.txt not working for all worlds

### ISSUE THREAD

**Issue by zhro** [webbukkit/dynmap#3800]
Dynmap-3.4-b4
Tested on Spigot 1.19 and Paper 1.19

Some worlds set to hidden are not actually hidden in the web view.

I have several worlds:

overworld
overworld_the_nether
overworld_end
worlds/1.17.1/overworld
hots
player-heads
worlds/spawn4
worlds/jayteeworld

In my worlds.txt I have the following set to configure which worlds are displayed:

worlds:
  - name: overworld
    title: "Overworld"
    enabled: true
  - name: overworld_the_nether
    enabled: false
  - name: overworld_end
    enabled: false
  - name: worlds/1.17.1/overworld
    enabled: false
  - name: hots
    enabled: false
  - name: player-heads
    enabled: false
  - name: worlds/spawn4
    enabled: false
  - name: worlds/jayteeworld
    enabled: false

But only worlds "hots" and "player-heads" are hidden:

![image](https://user-images.githubusercontent.com/4738876/179350528-59f80b37-df24-426e-bfdf-8c3e4af947ad.png)

**Comment by JurgenKuyper** [comment]
Check the worldnames found by /dmap worldlist, these are the ones dynmap uses

**Comment by zhro** [comment]
It appears to have replaced the slashes with dashes. I have a full render still running at the moment, so I'll check back on this when I'm able to restart the server.

**Comment by zhro** [comment]
This is confirmed working. I also mixed up "nether" with "the_nether" and "the_end" with "end". All worlds are hiding now as expected.

Is there a reason I can't use the path separator when specifying worlds? Dashes are not path separators, and it's confusing to read.

**Comment by JurgenKuyper** [comment]
Because path separators are used to navigate folders, and are not exactly the worldname so that world is not found and thus not disabled.
