### ISSUE TITLE
Dynmap not working on Minehut

### ISSUE THREAD

**Issue by mick8014** [webbukkit/dynmap#3805]
Hey, 
sorry to bother everyone but can someone help me? I just added Dynmap to my Minehut server. But since Minehut has these IP's that end with .minehut.gg, I can't use dynmap. I tried typing the ip and then my port but it just says "This site can't be reached". Anyone know how to fix this issue?

**Comment by JurgenKuyper** [comment]
https://lmgtfy.app/?q=minehut+dynmap
