### ISSUE TITLE
Hide region rectangles

### ISSUE THREAD

**Issue by rustyshakelford2** [webbukkit/dynmap#3807]
I followed this tutorial to boost the resolution of my spawn region:
https://github.com/webbukkit/dynmap/wiki/Boosting-areas-on-Dynmap

Now spawn has an ugly red shaded square over it by default. Is it possible to alter the color scheme/transparency or have regions hidden by default?

**Comment by JurgenKuyper** [comment]
/dmarker updatearea markerId fillcolor:000000 color:000000
MarkerId is found by /dmarker listareas

**Comment by JurgenKuyper** [comment]
added entry to the guide, closing because issue no longer relevant.
