### ISSUE TITLE
1.19.1 fabric/quilt compatibility

### ISSUE THREAD

**Issue by SulpherStaer** [webbukkit/dynmap#3808]
**Issue Description:** The latest 1.19.1 update has broken Dynmap due to the new manner of message handling.

* **Dynmap Version:** Dynmap-3.4-beta-5-fabric-1.19
* **Server Version:** Minecraft 1.19.1 with Quilt Loader 0.17.1
* **Pastebin of Configuration.txt:** https://pastebin.com/U8HcNTvp
* **Server Host (if applicable):** Apex
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/TmQMBexW
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** Use the latest version of fabric or quilt that supports 1.19.1, install only the api mod & dynmap. Observe it crashing due to message handling. special note to  'onGameMessage'

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
The fabric version is not out yet, please wait a little longer.

**Comment by SulpherStaer** [comment]
apologies for the impatience.

**Comment by kosma** [comment]
Please try this build and report success/failure:
https://github.com/kosma/dynmap/releases/tag/v3.4-SNAPSHOT-fabric-1.19.1-build.1

**Comment by SulpherStaer** [comment]
The server starts correctly, dynmap loads & functions. I personally do not use the chat function of dynmap, so I haven't tested that bit. But after a very short 10 minute test + a radiusrender of 100 blocks & chatting for a bit, everything seems to be in order.

**Comment by kosma** [comment]
Now officially available.
https://dynmap.us/builds/dynmap/Dynmap-3.4-SNAPSHOT-fabric-1.19.1.jar
