### ISSUE TITLE
Exception during render job - IllegalFormatConversionException

### ISSUE THREAD

**Issue by Vilican** [webbukkit/dynmap#3810]
**Issue Description:** *After issuing a fullrender on world, this error message shows up when starting server.*

* **Dynmap Version:** *core=3.4-beta-5-806, plugin=3.4-beta-5-806*
* **Server Version:** *Paper version git-Paper-94 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 532dc51)*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** [*https://pastebin.com/raw/W7Qhqf49*](https://pastebin.com/raw/W7Qhqf49)
* **Other Relevant Data/Screenshots:** *Using external server (PostgreSQL 11) for storage*
* **Steps to Replicate:** *Issue fullrender, start server*

**Comment by mikeprimm** [comment]
Please give new SNAPSHOT builds a try - should be fixed (https://dynmap.us/builds/dynmap)
