### ISSUE TITLE
s3 solution gives error if bucket has periods in the name

### ISSUE THREAD

**Issue by atsmith14** [webbukkit/dynmap#3815]
**Issue Description:** *When using a bucket with periods in the name there's an error preventing the connection. This issue prevents setting up a CNAME for use with a subdomain*

**NOTE: In the files below map.domain.com is used as an example**

* **Dynmap Version:** *v3.4-beta-5-806*
* **Server Version:** *git-Purpur-1692*
* **Pastebin of Configuration.txt:** *https://pastebin.com/7d6pqcAU*
* **Server Host (if applicable):** *Self-hosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/JeLXWEji*
* **Steps to Replicate:** *Use any bucket with periods in the name*

 [✓] *I have looked at all other issues and this is not a duplicate*  
 [✓] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
The bucket name is the AWS identifier, not the DNS name - you can add a CNAME if you want, but you cannot use that for the bucket name: the APIs to AWS are HTTPS, and a CNAME will not have the needed SSL certificate on the AWS APIs for the bucket, the calls to deliver data to the bucket will be unusuable.
