### ISSUE TITLE
Forge 42.0.0 changes break this mod

### ISSUE THREAD

**Issue by jellybean13** [webbukkit/dynmap#3817]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *All players can not see any messages from everyone.*

* **Dynmap Version:** *3.4-beta-5*
* **Server Version:** *1.19.1 with Forge 42.0.1 installed*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/GfQBLsFR*
* **Steps to Replicate:** *Join the server --> Say something such as "Hello" --> Players can not see this message. An error occurs.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
With 1.19.2 out now, this will not be fixed and there will be no 1.19.1 forge specific version.  Sorry, just not worth the effort.

**Comment by mikeprimm** [comment]
Actually, I'm 99% sure the 1.19.2. build will work on 1.19.1 (1.19.2 is VERY minor update) - it'll just not be part of our formal support statement.
