### ISSUE TITLE
Problem with the webserver

### ISSUE THREAD

**Issue by Hersheyys** [webbukkit/dynmap#3818]
I had opened a new port for the dynmap too but it dosent work it still tells me webserver opened on 0.0.0.0:XXXXX(Its a five letter)
Hersheys#3323 if you'd want to help
webserver-port: 42631
this is in my config btw
# The network-interface the webserver will bind to (0.0.0.0 for all interfaces, 127.0.0.1 for only local access).
# If not set, uses same setting as server in server.properties (or 0.0.0.0 if not specified)
#webserver-bindaddress: 0.0.0.0

**Comment by JurgenKuyper** [comment]
are you using a provider? then you need to open a port in their panel.
if using docker or pterodactyl. you need to add the port in the port section on the configuration / panel of that container.
if selfhosting, check whether the firewall(s) allows the port through.

**Comment by JurgenKuyper** [comment]
closing issue because user didn't respond, not on github nor on discord.
