### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Siemator** [webbukkit/dynmap#3822]
**Issue Description:** *I add dynmap and fabric api into mod folder on clean install server with default configuration, then i try to start but it is unsuccessful because it crash, without dynmap server starts normaly.*

* **Dynmap Version:** *Dynmap-3.4-beta-5-fabric-1.19.jar*
* **Server Version:** *fabric-server-mc.1.19.2-loader.0.14.9-launcher.0.11.0.jar*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/G6DcMBtP*
* **Other Relevant Data/Screenshots:** *I'm using latest fabricapi*
* **Steps to Replicate:** *I just put dynmap and fabricapi in to mods folder and try to start server*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
we are aware of this issue, currently there is no fabric mod available for 1.19.2, only for 1.19.0 or earlier.

**Comment by Siemator** [comment]
Sadge, but thx for the fast response

**Comment by kosma** [comment]
You're using the wrong jar. Please use the 1.19.1 jar.

https://dynmap.us/builds/dynmap/Dynmap-3.4-SNAPSHOT-fabric-1.19.1.jar
