### ISSUE TITLE
Dynmap not compatible with Minecraft 1.19.1

### ISSUE THREAD

**Issue by ChromesDuzez** [webbukkit/dynmap#3824]
**Issue Description:** *Dynmap causes crashing for server on startup. Disabling it causes the server to launch properly.*

* **Dynmap Version:** *dynmap-v3.4-beta-5 for Fabric*
* **Server Version:** *Fabric 1.19.1*
* **Server Host (if applicable):** *SelfHosted*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Use the proper version for 1.19.1 or higher: https://dynmap.us/builds/dynmap/Dynmap-3.4-SNAPSHOT-fabric-1.19.1.jar
