### ISSUE TITLE
Github releases missing

### ISSUE THREAD

**Issue by zvanelslande** [webbukkit/dynmap#3825]
**Issue Description:** *There are no more releases on github since October 2021?*

* **Dynmap Version:** *+[v3.3-beta-2](https://github.com/webbukkit/dynmap/releases/tag/v3.3-beta-2)*
* **Server Version:** *Paper/Spigot 1.18.1and up*
* **Pastebin of Configuration.txt:** *N/A*
* **Pastebin of crashlogs or other relevant logs:** *N/A*
* **Other Relevant Data/Screenshots:** *![image](https://user-images.githubusercontent.com/8496327/184556948-0018d85d-7da4-49b7-9a46-4c4c11805a08.png)*
* **Steps to Replicate:** *[Navigate to the Github relases page on webbukkit/dynmap](https://github.com/webbukkit/dynmap/releases)*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
GitHub is not the location for releases, you can get them on the usual download locations: [dev.bukkit.org](https://dev.bukkit.org/projects/dynmap/files/3934649) [SpigotMC](https://www.spigotmc.org/resources/dynmap%C2%AE.274/update?update=469425); and for [Forge and Fabric from CurseForge](https://www.curseforge.com/minecraft/mc-mods/dynmapforge/files)

**Comment by rautamiekka** [comment]
> GitHub is not the location for releases

That's the point, it means the readme is wrong.
