### ISSUE TITLE
Major Dynmap Spam logging

### ISSUE THREAD

**Issue by Zelioth** [webbukkit/dynmap#3842]
Dynmap is having a lot of issues on my custom mod pack and figured I would report them to see if it could help in development of the mod any or towards fixing and issues. 

Minecraft 1.19.2
Forge Version 43.1.2
Mod pack Friends United 2.0.6

**Comment by JurgenKuyper** [comment]
it is normal for dynmap to show it's data on modded renders, you cannot disable it as it is most likely about blocks dynmap cannot render because they are not in the vanilla blockstates.
