### ISSUE TITLE
Dynmap don´t open any port

### ISSUE THREAD

**Issue by Lerkista** [webbukkit/dynmap#3843]
Hi

I´ve a problem with my server (Paper 1.19.2 using a Docker installation with Geyser for Bedrock and Java compatibility), when i started it shows:

...
[06:58:52 INFO]: [dynmap] Web server started on address 0.0.0.0:8123
[06:58:52 INFO]: [dynmap] version 3.4-828 is enabled - core version 3.4-828
...

But i can´t access the page (locally using http://127.0.0.1:8123), and if i look the list of open ports in my Linux (Raspberry Pi 4), the port 8123 is not open

What can i do to fix that?

Thanks

**Comment by JurgenKuyper** [comment]
Did you add the port in the docker setup file? It needs to be defined like with the Minecraft port

**Comment by Lerkista** [comment]
That make it work, sorry, my first time using docker
