### ISSUE TITLE
DoFileWrites Lag

### ISSUE THREAD

**Issue by FARF12** [webbukkit/dynmap#3846]
* **Dynmap Version:** *3.4*
* **Server Version:** *Patina 1.16.5.Same lags on Paper*
* **Pastebin of Configuration.txt:** *https://pastebin.
* **Server Host :** *Selfhosted,(Ryzen 7 5800x)*
* **Pastebin of crashlogs or other relevant logs:** *There are no crashes or errors in console*
* **Steps to Replicate:** *I have quite a large number of markers on the map (about a hundred).*
![Screenshot_997](https://user-images.githubusercontent.com/88440932/188313793-c942cd38-ffd8-498f-b9b8-0c2628ddb073.png)

**Comment by mikeprimm** [comment]
Should be handled by same changes as #3884
