### ISSUE TITLE
 Two maps for two servers

### ISSUE THREAD

**Issue by StonFlip** [webbukkit/dynmap#3847]
Hello, how can I make 2 Dynmap maps online if I have 2 servers on the same VDS ?

Map of the first server: https://map.cbtpolit.xyz/

**Comment by JurgenKuyper** [comment]
you can just add another subdomain to the ip, with a different port, like server1.domain.com and server2.domain.com

**Comment by StonFlip** [comment]
> you can just add another subdomain to the ip, with a different port, like server1.domain.com and server2.domain.com

I use my own web server and only have port 80 available for CloudFare

**Comment by JurgenKuyper** [comment]
you can use a reverse proxy to hide the port, so the backend server can have a different port than the http (80) port, any google guide on how to setup a reverse proxy for your webserver flavour has the info needed to set that up.

**Comment by StonFlip** [comment]
> you can use a reverse proxy to hide the port, so the backend server can have a different port than the http (80) port, any google guide on how to setup a reverse proxy for your webserver flavour has the info needed to set that up.

Is TCPShield suitable for hiding a port? I just do not fully understand how this will work, do I need to specify port 25599 in the Dynmap config? Then there will be no https protection from CloudFire

If you can, then you could do it step by step how to do it
well, for example
1. Go to Google
2. Write it
3. Do as it says
4. You did it

Thanks in advance)

**Comment by JurgenKuyper** [comment]
TCPShield is not suitable for that no, you said you have a VDS, maybe you can install a webserver on it, like nginx, and follow a guide like: https://phoenixnap.com/kb/nginx-reverse-proxy#ftoc-heading-8. Setting up a reverse proxy is out of scope for dynmap, as it is not a feature of dynmap itself.

**Comment by StonFlip** [comment]
Apache web server is not suitable for this purpose?

**Comment by JurgenKuyper** [comment]
use google.

**Comment by StonFlip** [comment]
Okay, I got it right..
What can I specify with the port of the first dynmap server 25598, for example, the second 25599, then configure them to be forwarded to port 80 via nginx?

**Comment by JurgenKuyper** [comment]
any port that is not in use can be used by dynmap, and thus be specified in the page's config

**Comment by StonFlip** [comment]
So, did I get it right?

**Comment by JurgenKuyper** [comment]
https://tryitands.ee
