### ISSUE TITLE
NullPointerException: Cannot invoke "java.util.concurrent.ConcurrentHashMap.put(java.lang.Object, java.lang.Object)" because "this.allowedicons" is null

### ISSUE THREAD

**Issue by Nishh** [webbukkit/dynmap#3850]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap throws an error while server is starting, and disables itself.*

* **Dynmap Version:** *v3.4-beta-5-806*
* **Server Version:** *git-Paper-387 (MC: 1.18.2)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/6i3aydan*
* **Server Host (if applicable):** *OVH*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/FFmTjCU4*
* **Other Relevant Data/Screenshots:** *started happening 1-2 days after using this method: https://pastebin.com/Rm9Q79MZ*
* **Steps to Replicate:** *Added new markers with this method https://pastebin.com/Rm9Q79MZ and restarted server.*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
that is not a bug, each marker needs an icon, and from what I can see, that hasn't been defined in that method (maybe the set has no defaulticon?)

**Comment by Nishh** [comment]
Dynmap disables itself before my plugin loads.
This is my markers.yml: https://pastebin.com/9mxxCW8B
All markers have valid deficon and allowedicons.
I'm only using builtin icons (from https://github.com/webbukkit/dynmap/wiki)
Removing markers.yml fixes this, but after my plugin created the same markers and restarting > Dynmap disables itself again

**Comment by JurgenKuyper** [comment]
just tested, if you remove all of the allowedicons entries it works, don't see that feature documented on the api page: https://gist.github.com/JOO200/eb99b294ebd16a353750f83d8dcdce23 
maybe it is not supported?

**Comment by Nishh** [comment]
Sorry, I sent the wrong method, this was what I used: 
DynUtil.marker.createMarkerSet(markerName.toLowerCase(), markerName, Sets.newHashSet(getMarkerIcon()), true).setDefaultMarkerIcon(getMarkerIcon());

Replacing it with:
DynUtil.marker.createMarkerSet(markerName.toLowerCase(), markerName, null, true).setDefaultMarkerIcon(getMarkerIcon());

and removing all allowedicons entries fixed it. Thanks.
