### ISSUE TITLE
[16:15:11 ERROR]: [dynmap] Failed to start WebServer on address 0.0.0.0:25635 : Failed to bind to 0.0.0.0/0.0.0.0:25635?

### ISSUE THREAD

**Issue by jl5442** [webbukkit/dynmap#3852]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** *dynmap-version*
* **Server Version:** *forge 1.16 build x, or paper 1.15.2 build x*
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Server Host (if applicable):** *McProHosting, Shockbyte, Selfhosted, etc.*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/crashcausedbydynmap*
* **Other Relevant Data/Screenshots:** *I'm using this texture pack and these plugins and my map is from alpha .8*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
That means that that port is already in use, dynmap needs a secondary port that is not in use
