### ISSUE TITLE
People Not Seeing on Dynmap 1.8

### ISSUE THREAD

**Issue by ILoveMincraft2** [webbukkit/dynmap#3855]
**Issue Description:** *I cant see people on the dynmap and dont know how to fix this
?.*

* **Dynmap Version:** *1.8*
* **Server Version:** *paper 1.8.9 *
* **Pastebin of Configuration.txt:** *https://pastebin.com/7PhMemjb*
* **Server Host (if applicable):** *FeroxHosting*

**Comment by JurgenKuyper** [comment]
just fyi, anything below 1.14.4 is not supported so your results may vary, most often when users cannot see eachother it is a plugin like essentials or siegewar which hides players if not in a "friendly area" as they hook into dynmap to hide players. check your plugin configs to see if you have such a setting enabled.
