### ISSUE TITLE
Prefix for the playername

### ISSUE THREAD

**Issue by johnorlic** [webbukkit/dynmap#3873]
I have a Kingdom server and would like to have the kingdom name before the player name in the playerlist shown on the right.

But can't get that to work.

Server is 1.19
Dynmap version core=3.4-828, plugin=3.4-828

**Comment by JurgenKuyper** [comment]
dynmap just uses the playername as given to it by the server, so unless you can edit that one somehow by using a plugin that does that, you cannot change it.

**Comment by JurgenKuyper** [comment]
closing issue because user didn't respond, thus deeming not an issue anymore
