### ISSUE TITLE
Can't bind to port

### ISSUE THREAD

**Issue by vld-b** [webbukkit/dynmap#3874]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *I can't get the webserver to work. I've opened the port locally already and it still doesn't work. What can I do?
[19:35:01 ERROR]: Failed to start WebServer on address 0.0.0.0:8123 : Failed to bind to 0.0.0.0/0.0.0.0:8123*

* **Dynmap Version:** *3.4*
* **Server Version:*1.15.2 build 271** *
* **Pastebin of Configuration.txt:** *https://pastebin.com/9bUKhWk4*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *no crash log*
* **Other Relevant Data/Screenshots:** *nope*
* **Steps to Replicate:** *Please be clear in this section so we can replicate your issue*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
That means that that port is already in use, only one port can be used at the same time by a given application
