### ISSUE TITLE
Bug or inconclusive documentation with maven repository for 3.4

### ISSUE THREAD

**Issue by jaylawl** [webbukkit/dynmap#3877]
**Issue Description:** 
- Create a gradle project
- use `compileOnly("us.dynmap:dynmap-api:3.4")`

The library downloaded by using this only contains two classes. `DynmapAPI` and some other of which i forgot the name.
Issue being, that it hardly contains what one would it expect it to. Pretty much all of the actual API is mising.

After some fiddling around with the versions, i figured out you can go back to `3.1` and from there on it would contain all the API again.

On Discord, `@Kosmolot#7888` helped my by suggesting that i use `compileOnly("us.dynmap:DynmapCoreAPI:3.4")` instead. This did the trick, all the API is there.

Prior to achieving anything on my side, unfortunately i did waste a significant amount of time trying to research what  the correct maven library would be.

For the sake of preventing this issue, i suggest this be either included in the documentation or fixed if its a bug.

Thank you.

 [ x ] *I have looked at all other issues and this is not a duplicate*  
 [ x ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
I know it is rudimentary, but I just added some API documentation on the main wiki: https://github.com/webbukkit/dynmap/wiki/Dynmap-API
hope this at least helps, if you have any additions to the page feel free to edit it / message us.

**Comment by jaylawl** [comment]
Rudimentary or not, it now contains all that is needed. Thanks! :-)

I'll leave the issue open for the dynmap team to decide whether or not this solution is sufficient.

**Comment by JurgenKuyper** [comment]
No one said something about it since I created the file, assuming it's good enough, closing issue.
