### ISSUE TITLE
Website map issue

### ISSUE THREAD

**Issue by normaluser12354** [webbukkit/dynmap#3879]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *when trying to do the website map thing it just says took too long to respond

* **Dynmap Version:** *3.4*
* **Server Version:** *paper 1.19.2 x*
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Server Host (if applicable):** *featherclient self host*

 [yes ] *I have looked at all other issues and this is not a duplicate*

**Comment by JurgenKuyper** [comment]
Did you open the dynmapport in both your firewall and other possible routing settings?

**Comment by normaluser12354** [comment]
how do you open the port in my firewall?

**Comment by JurgenKuyper** [comment]
Google how to do that for your operating system.

**Comment by JurgenKuyper** [comment]
closing issue because user didn't respond, thus deeming issue fixed
