### ISSUE TITLE
Ability to turn off Google Fonts or self host fonts

### ISSUE THREAD

**Issue by unknownSaschka** [webbukkit/dynmap#3880]
Due to the European and especially German data privacy policies, website operators have to inform their users which websites processes specific user data. Dynmap is loading Google Fonts by default, which is a big problem, because those fonts have to load from Google servers. On loading the font, the users IP address will be sent to the Google servers, which are user specific data and this is highly problematic for German privacy policy.

It would be great if there's an option to self host fonts and set the URI in the config files. Until now to my knowledge, it is not allowed to use dynmap on German servers.

**Comment by FedUpWith-Tech** [comment]
Dynmap loads the browser's default Sans-Serif font, no external fonts are used.

**Comment by mikeprimm-mirific** [comment]
Key thing here is Dynmap doesn't include any explicit sourcing from google fonts - there are font-family and font tags in the CSS (with the leaflet CSS including a 'font' specification for Helvetica Neue and Lucida Console), but the control of loading fonts from Google is up to the browser.  We do not include any static or dynamic references to fetch google fonts - per https://wicki.io/posts/2022-02-goodbye-google-fonts-data-privacy-gdpr/

If you want to override the CSS font tags, the existing procedure is:

1) uncomment  in the index.html
2) add CSS overrides for the appropriate classes

**Comment by mikeprimm-mirific** [comment]
Per the procedure here, I'm not seeing any sign of font loading going on from https://www.ghacks.net/2022/09/17/how-to-block-web-fonts-to-improve-privacy/ - are you seeing something being loaded, or just assuming it is happening?

**Comment by mikeprimm-mirific** [comment]
One of our support folks noticed that LiveAtlas is using google fonts - if you are using LiveAtlas, or any other non-default Dynmap UI, you'll need to work with them to get that sorted out: their support has nothing to do with Dynmap itself.

**Comment by unknownSaschka** [comment]
It turned out that another team members applied the LiveAtlas UI to our dynmap without noticing me. I just got warnings that our dynmap is loading Google Fonts and we should deactivate it immediately. Removing all static Google Font references in LiveAtlas and adding the CSS overrides didn't helped in my first run but it's working now.

It was my fault that I didn't check more closely and I appologize for any inconvenience. I'm very thankful for your help and I appreciate your time.
