### ISSUE TITLE
Issue rendering large map in SQLite

### ISSUE THREAD

**Issue by Jamboxman5** [webbukkit/dynmap#3881]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *I'm fullrendering my map, and it works completely fine from the start. After letting it generate for a long time the map stops working completely. No images load, it constantly says "Waiting for <my domain>" and it never fully connects. Thinking maybe my map is too big? I've never had this problem before on the same world and nothing has happened to make the map any bigger other than switching from flatfile to sqlite. My database is currently ~23.5GB in size. Everything works again after clearing the database and restarting the render from the beginning.
*

* **Dynmap Version:** *core=3.4-828, plugin=3.4-828*
* **Server Version:** *paper 1.19.2 build 272*
* **Pastebin of Configuration.txt:** *https://pastebin.com/SF4mRLQ2*
* **Server Host (if applicable):** *None*
* **Pastebin of crashlogs or other relevant logs:** *None*
* **Other Relevant Data/Screenshots:** *Completely reset my configuration and this issue persisted on completely default settings*
* **Steps to Replicate:** *Render a giant map in sqlite*

 [ X ] *I have looked at all other issues and this is not a duplicate*  
 [ X ] *I have been able to replicate this*

![image](https://user-images.githubusercontent.com/119700635/205370796-e20000d6-1071-4f1d-b5c9-1f092e93bd33.png)

**Comment by mikeprimm** [comment]
Unlikely we will have much option here - if you have logs showing some errors, that might help, but I suspect we're dealing with one or another of SQLite's limitations (number of pages in the DB, page size, or whatever).  It really isn't a good large data DB - just a convenient one.   I'll give it a look, in case there is something we could do something about, but really cannot make any promises.

**Comment by ApliNi** [comment]
Maybe the problem isn't database size. 
I have a 157GB Dynmap-SQLite database, and I'm still rendering and updating maps. It works fine and loads quickly. 

Edit: 
This database file is placed on the mechanical hard disk.

**Comment by JurgenKuyper** [comment]
@Jamboxman5 what storage are you running on? HDD vs SSD have a huge performance and accessing time difference

**Comment by rautamiekka** [comment]
Might be fragmented to hell.

**Comment by Jamboxman5** [comment]
I'm using a brand new PCIe Gen 4 NVMe SSD, a Western Digital Black 1TB SN770

**Comment by rautamiekka** [comment]
Weird, fragmentation shouldn't matter, then. What filesystem ?

**Comment by Jamboxman5** [comment]
I think GPT, I used whichever the default was in the Ubuntu server installer

EDIT: Just checked and I believe its actually ext4
