### ISSUE TITLE
too many redirects 

### ISSUE THREAD

**Issue by RenzcomStudios** [webbukkit/dynmap#3883]
i added a custom folder in the web folder but i can't acces it. i get the error ERR_TOO_MANY_REDIRECTS. is there a way to fix this?

**Comment by JurgenKuyper** [comment]
dynmap and the dynmap team only supports their own environments, check the webserver's error.log about why it is doing this. the default setup of dynmap works fine, and shouldn't need to be altered in any way. the internal webserver is limited to its own environment, and only the frontend can be altered. maybe a permission issue?

**Comment by JurgenKuyper** [comment]
out of dynmap's scope and didn't recieve an answer of OP, closing issue.
