### ISSUE TITLE
Add to Modrinth

### ISSUE THREAD

**Issue by sylv256** [webbukkit/dynmap#3886]
> template is **bold**
> sample data is *italicized*

**Feature Description:**
Please consider adding this mod to Modrinth to make it easier for modpack creators etc. on Modrinth.

* **Additional context:**
* An increasing number of mods are moving to Modrinth, especially as they recently added monetization support. Modrinth is a platform with better searching, API, and features for mod developers, and their community and developers are very welcoming to developers.

**Comment by mikeprimm** [comment]
Now that they're in beta on their monetization, I'll give this a look (they were promising it for a while, but until it is active, for better or worse, CurseForge is the 'more than zero' option we've been using).

**Comment by sylv256** [comment]
The monetization is about the same in terms of how much you get. It is a little less because of their ad provider, but they are working on it. For now, though, it will be a little low, so it's not a *replacement* yet, just something to consider using alongside.

**Comment by mikeprimm** [comment]
Yep - that's all good, but whatever it is is infinitely more than 'zero, but it'll be there someday' ;)

**Comment by techsolo12** [comment]
Any news on this topic? :)

**Comment by JurgenKuyper** [comment]
> Any news on this topic? :)

https://modrinth.com/plugin/dynmap

**Comment by JurgenKuyper** [comment]
If it proves to be feasible we will continue using it, if not, it will be dropped, will update when results are in

**Comment by techsolo12** [comment]
Very nice! Hopefully modrinth support will be continue. Its very usefull for autoupdate plugins feature on a docker based server like [itzg - docker-minecraft-server](https://github.com/itzg/docker-minecraft-server) 
There a some guys and girls, who should be very thankfully for supporting modrinth! :)

**Comment by sylv256** [comment]
> > Any news on this topic? :)
> 
> https://modrinth.com/plugin/dynmap

~~Where's the Fabric/Quilt version?~~
Nevermind, I see it. Sorry
