### ISSUE TITLE
Fabric server 1.19.2 /dynmap fullrender not working

### ISSUE THREAD

**Issue by JaraSG2** [webbukkit/dynmap#3889]
**Issue Description:** *Fabric server 1.19.2 commands /dynmap fullrender not working and realtime rendering not working*

* **Dynmap Version:** *Dynmap-3.4-fabric-1.19.1.jar*
* **Server Version:** *Minecraft 1.19.2 with Fabric Loader 0.14.9*
* **Pastebin of Configuration.txt:** *https://pastebin.com/Qa6hveS8*
* **Server Host (if applicable):** *https://www.fakaheda.eu/*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*
![obrazek](https://user-images.githubusercontent.com/4647218/206657237-bb90047a-dbd4-41d1-bb25-3e9fab553d8d.png)

**Comment by JurgenKuyper** [comment]
https://github.com/webbukkit/dynmap/wiki/Commands
please read up on the proper command usage, it needs a world to know what to render from console.
