### ISSUE TITLE
Cyrillic messages issue

### ISSUE THREAD

**Issue by mctaylors** [webbukkit/dynmap#3890]
**Issue Description:** *The Cyrillic message is not displayed correctly in Dynmap*

* **Dynmap Version:** *3.4*
* **Server Version:** *Paper 1.19.2-307*
* **Pastebin of Configuration.txt:** *https://mctaylors.ddns.net/raw/pastes/configuration.txt*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *-*
* **Other Relevant Data/Screenshots:** *https://mctaylors.ddns.net/raw/screenshots/cyrillicissue.png*
* **Steps to Replicate:** *If you send a message in Cyrillic from Minecraft, the message will not be displayed correctly in Dynmap webpage*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by mikeprimm** [comment]
Make sure your edit of configuration.txt is using UTF-8 code page, not 1251 or ISO-8859-15 (windows default).   It's a YAML file, and text needs to be either UTF-8, or use unicode escape sequences (e.g. \u2009 )

**Comment by mctaylors** [comment]
> Make sure your edit of configuration.txt is using UTF-8 code page, not 1251 or ISO-8859-15 (windows default). It's a YAML file, and text needs to be either UTF-8, or use unicode escape sequences (e.g. \u2009 )

I am 100% sure that my configuration.txt saved in UTF-8 encoding.

**Comment by rautamiekka** [comment]
If you're on Window$, you can use Notepad++ or Visual Studio Code (or VSCodium) or some other proper editor to check/convert.

^ On Linux (and probly Mac) they're usually UTF-8 by default, but graphical ones tend to have an option to choose, or at least print, and [then there's](https://unix.stackexchange.com/a/11648/11433) `iconv -f utf-8 -t utf-8 < 'FILE.yml' > /dev/null` to test for valid UTF-8.

**Comment by mctaylors** [comment]
> If you're on Window$, you can use Notepad++ or Visual Studio Code (or VSCodium) or some other proper editor to check/convert.
>
> ^ On Linux (and probly Mac) they're usually UTF-8 by default, but graphical ones tend to have an option to choose, or at least print, and [then there's](https://unix.stackexchange.com/a/11648/11433) `iconv -f utf-8 -t utf-8 < 'FILE.yml' > /dev/null` to test for valid UTF-8.

![image](https://user-images.githubusercontent.com/95250141/207072571-f4aef184-52b7-4875-aa72-4de4ffa77612.png)

**Comment by mctaylors** [comment]
![image](https://user-images.githubusercontent.com/95250141/207073226-6e90fa25-33c8-455b-afe1-5caa5cc109b1.png)

**Comment by JurgenKuyper** [comment]
@mikeprimm I managed to fix this by changing line 50 in web/js/minecraft.js to 
```js
utftext += String.fromCharCode(c);
```
![image](https://user-images.githubusercontent.com/45831568/208401185-69d0b050-87c5-4f9e-a74d-0b4024a5cdb5.png)
If I change the value back to 
```js
utftext += String.fromCharCode(c+848);
```
and enable cyrillic support, the cyrillic conversion breaks again and changes to the "thaana" entry of that character. so, long story short, cyrillic support is either broken all the way, or is no longer needed as at least my browser (firefox) handles the utf-16 characters properly.

**Comment by mctaylors** [comment]
yeah, thanks, it worked for me
