### ISSUE TITLE
NoSuchFieldError when enabling on Paper 1.19.3

### ISSUE THREAD

**Issue by Loafabreadly** [webbukkit/dynmap#3894]
**Issue Description:** *When going to enable the v3.4 Dynmap plugin on a PaperMC 1.19.3 server, a NoSuchField error is received, leading to the plugin disabling.*

* **Dynmap Version:** *v3.4*
* **Server Version:** *Paper 1.19.3 build 323*
* **Pastebin of Configuration.txt:** *Unable to provide as the plugin never successfully enables and never generates a Configuration.txt file*
* **Server Host (if applicable):** *Tested on local computer and private cloud instance*
* **Pastebin of crashlogs or other relevant logs:** *https://hastebin.com/gifikekixu.apache*
* **Other Relevant Data/Screenshots:** *Confirmed v3.4 still works with a Paper 1.19.2 build, something changed in .3 causing Dynmap to reference a now none-existent field*
* **Steps to Replicate:** *Download PaperMC 1.19.3 build 323 > Start the PaperMC server once to generate the world, then stop the server > Download the latest version of Dynmap and place in the /plugins folder > Start the PaperMC server once more, the error should pop up*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*
![image](https://user-images.githubusercontent.com/3068229/207081021-2eebbcd4-6c72-4f53-8cf4-f88d3fc057df.png)

**Comment by JurgenKuyper** [comment]
3.4 is not for 1.19.3, use the betas from the regular download locations for now, but these are still experimental, so please report any new bugs found not already in the issue trackers.
- Releases available for Forge and Fabric on https://www.curseforge.com/minecraft/mc-mods/dynmapforge/files,
- and for Spigot/PaperMC on https://dev.bukkit.org/projects/dynmap/files/4167109
