### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by mrturcot** [webbukkit/dynmap#3895]
**Issue Description:** _Build failed -  debug gradle log https://pastebin.com/nYru6DDq_

* **Dynmap Version:** *git master - a6548ec0b7155c11be7f24c72363bcda8ecf1e41*
* **Server Version:** *[10:26:58 INFO]: Current: git-Purpur-"b7671ee" (MC: 1.19.3)**
* **Pastebin of Configuration.txt:** *n/a*
* **Server Host (if applicable):** *n/a*
* **Pastebin of crashlogs or other relevant logs:**
* **What went wrong:**

tail

```
* *FAILURE: Build failed with an exception.
Could not resolve all files for configuration ':forge-1.17.1:runtimeClasspathCopy'.
> Could not find net.minecraftforge:forge:1.17.1-37.0.12_mapped_official_1.17.1_at_1f7edf4b8dc12966c791a209a94440700fe39c92.
  Searched in the following locations:
    - file:/home/mrturcot/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.17.1-37.0.12_mapped_official_1.17.1_at_1f7edf4b8dc12966c791a209a94440700fe39c92/forge-1.17.1-37.0.12_mapped_official_1.17.1_at_1f7edf4b8dc12966c791a209a94440700fe39c92.pom
    - file:/home/mrturcot/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.17.1-37.0.12_mapped_official_1.17.1_at_1f7edf4b8dc12966c791a209a94440700fe39c92/forge-1.17.1-37.0.12_mapped_official_1.17.1_at_1f7edf4b8dc12966c791a209a94440700fe39c92.jar
  Required by:
      project :forge-1.17.1
```

* **Other Relevant Data/Screenshots:** *n/a*
* **Steps to Replicate:** *build latest commit with ./gradlew setup build or ./gradlew :spigot:build*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

```
❯ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment 17.0.5_p8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM 17.0.5_p8 (build 17.0.5+8, mixed mode, sharing)
```

```
➜ cat /proc/version                    
Linux version 6.0.12-gentoo-filthy (root@GentooRig) (gcc (Gentoo 11.3.0 p7) 11.3.0, GNU ld (Gentoo 2.38 p4) 2.38) #9 SMP PREEMPT_DYNAMIC Fri Dec 9 20:46:02 PST 2022
```

**Comment by JurgenKuyper** [comment]
I just ran a clean build of the repo, didn't get this issue, is your gradle version up to date if not using the bundled one?

**Comment by mrturcot** [comment]
> I just ran a clean build of the repo, didn't get this issue, is your gradle version up to date if not using the bundled one?

Is 7.6 not sufficient?  

➜ gradle -version

------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (Gentoo 17.0.5+8)
OS:           Linux 6.0.12-gentoo-filthy amd64

**Comment by JurgenKuyper** [comment]
the bundled gradlew has this output:
![image](https://user-images.githubusercontent.com/45831568/207140046-bbe2c4fe-6c45-4476-a53a-411ae541422b.png)
try with the bundled one and see if you still have the issue

**Comment by mrturcot** [comment]
> the bundled gradlew has this output:
> ![image](https://user-images.githubusercontent.com/45831568/207140046-bbe2c4fe-6c45-4476-a53a-411ae541422b.png)
> try with the bundled one and see if you still have the issue

I did try both in clean env with gradle and ./gradlew

**Comment by mrturcot** [comment]
I guess if you cant replicate it I'm out of luck but is there anyway I can get the 3.5-snapshot.jar for 1.19.3?

**Comment by JurgenKuyper** [comment]
yes, of course, the usual paths:
v3.5-beta-1 released!

- Add support for v1.19.3 (thanks to Kosmolot (Fabric guy) for Fabric!)
- Improve performance (reduce lag) on large map marker populations
- Add better favicon and code for progressive web apps, to - - improve shortcuts and icons. (thanks to surfrock66!)
- Add new biome colors (thanks to mastermc05!)
- Update used paper chunk api (thanks to mastermc05!)
- Stringify json for json file client async (thanks to Warriorrrr!)
- Fix for chunk visibility limits on large maps (thanks to gmfamily!)
- Various other fixes

Releases available for Forge and Fabric on https://www.curseforge.com/minecraft/mc-mods/dynmapforge/files, and for Spigot/PaperMC on https://dev.bukkit.org/projects/dynmap/files/4167109
Bukkit

**Comment by mrturcot** [comment]
Oh my goodness I didn't even know about those 😅 thanks so much for your assistance. You rock 💯😎✌️

**Comment by JurgenKuyper** [comment]
no worries, glad I could help!
