### ISSUE TITLE
Dynmap registration fails - 3.5 beta 1

### ISSUE THREAD

**Issue by papypom** [webbukkit/dynmap#3896]
**Issue Description:** *Impossible to register on dynmap, using external webserver. Webregister works OK, and the data is indeed in the mySQL server.*

* **Dynmap Version:** *3.5 beta 1*
* **Server Version:** *paper 1.19.2 build 307*
* **Pastebin of Configuration.txt:** *https://pastebin.com/aRN7vKYR*
* **Server Host (if applicable):** *Selfhosted, nginx, mySQL(Percona), PHP8.1 on Debian 11.5*
* **Pastebin of crashlogs or other relevant logs:** *N/A*
* **Other Relevant Data/Screenshots:** *See screenshots*
* **Steps to Replicate:** *Create a server using provided configuration.txt. Webserver is remote. Use the /dynmap webregister to get a code. The code is in the DB (standalone files, dynmap_login.php), along the username, but using this exact code and username (copy-pasted from the DB) leads to a "registration failed" screen. Note : I've tried to write the code shown in Minecraft as a first attempt, the DB digging was when that failed.*

![image](https://user-images.githubusercontent.com/30237058/207606547-c162d5ce-3d16-48ef-846b-b7c3fa37a6b5.png)
![image](https://user-images.githubusercontent.com/30237058/207606628-79a52d4e-174f-4b48-963a-b76f1eca13ec.png)

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
any code apart from the one sent to you by in game chat is salted and encrypted iirc, if you use the in-game version of the code the registration should work.

**Comment by papypom** [comment]
> any code apart from the one sent to you by in game chat is salted and encrypted iirc, if you use the in-game version of the code the registration should work.

I tried that at first, but to no avail (tried all capitalization options, all dash length). I then went digging in DB, to see. I found my exact username (in lowercase) and the registration code in the DB, I then copy-pasted that, still to no avail.

**Comment by JurgenKuyper** [comment]
the userID must match the minecraft username, password and verify password need to be entered by the user, the code is in the format xxxx-xxxx, I've never encountered an issue with it, will have to spin up an external webserver dynmap setup to check for sure though

**Comment by papypom** [comment]
> the userID must match the minecraft username, password and verify password need to be entered by the user, the code is in the format xxxx-xxxx, I've never encountered an issue with it, will have to spin up an external webserver dynmap setup to check for sure though

Yup, I followed those steps. Exact same ID, Good format for the code. I've triple checked it before posting the bug report. 

Just tried a downgrade to PHP 8.0, no success there.

**Comment by papypom** [comment]
Found the culprit : I didn't update the code on the web side of things after enabling the chat. Issue closed.
