### ISSUE TITLE
Experimental feature blocks don't render at all

### ISSUE THREAD

**Issue by forkiesassds** [webbukkit/dynmap#3897]
**Issue Description:** Experimental feature blocks introduced in 1.19.3 don't render at all.

* **Dynmap Version:** 3.5-beta-1
* **Server Version:** Paper 1.19.3 Build 328
* **Pastebin of Configuration.txt:** [*https://pastebin.com/5SETL3z2*](https://pastebin.com/z0PdxQKW)
* **Server Host (if applicable):** Self-hosted on test server
* **Pastebin of crashlogs or other relevant logs:** None
* **Other Relevant Data/Screenshots:** 
![image](https://user-images.githubusercontent.com/54495659/207672931-2ed6f885-6c7d-48d6-bba9-03493de34142.png)
* **Steps to Replicate:** 
1. Set up a server running 1.19.3
2. Copy built in datapacks from 1.19.3 jar located in `data/minecraft/datapacks` and paste them into `world/datapacks`
3. Place the new blocks introduced from said experimental features
4. Wait for it to render

 - [X] *I have looked at all other issues and this is not a duplicate*  
 - [X] *I have been able to replicate this*

**Comment by forkiesassds** [comment]
From the looks of it there are no models and textures for 1.19.3+ items and blocks.

**Comment by JurgenKuyper** [comment]
as we are currently on 1.19.4 and no users have complained about missing textures of 1.19.3, I will go ahead and close this issue as resolved.
