### ISSUE TITLE
Dynmap Show Seed Structures 

### ISSUE THREAD

**Issue by Kane-LName** [webbukkit/dynmap#3899]
**Seed Base Structures:** *Dynmap takes the seed of the world and plants structures on the map.*

* **Configuration:** *Configuration file has options of all structures to disable/enable*

**Comment by JurgenKuyper** [comment]
That is not something dynmap will do, we do however have dynmap-structures, but idk if it still works.

**Comment by kosma** [comment]
The seed alone is not enough to display structures as the generation depends on the previous steps of the world generation. The plugin/mod would have to read the actual world data to determine the location of those structures in the *actual world*. This is doable but not currently planned in Dynmap.

Also it seems dynmap-structures has been updated to 1.19.3 last week, but only on Spigot: https://github.com/KovuTheHusky/dynmap-structures

**Comment by Kane-LName** [comment]
Dang, doesn't look like it's functional with fabric. Oh well, thanks for the input everyone
