### ISSUE TITLE
Multiple map filtering options

### ISSUE THREAD

**Issue by Eldeston** [webbukkit/dynmap#3901]
**Feature Description:** Add multiple map filtering options when rendered on the web.

* **Additional context:** Currently Dynmap appears to have bilinear filtering enabled and cannot be disabled. I want an option to be able to disable or enable the filtering or have multiple options for filtering. I wanted to request this feature because I'm using a `hires` map and the filtering looks ugly when zoomed in. Disabling filtering entirely may also help with performance. Example pic here:
![image](https://user-images.githubusercontent.com/59617287/208956502-e44c698f-cbf4-4091-a1ad-279eb9aa6ac1.png)

**Comment by JurgenKuyper** [comment]
unrelated, fix by using boosted maps(wiki).
