### ISSUE TITLE
Dynmap

### ISSUE THREAD

**Issue by DirePlays** [webbukkit/dynmap#3903]
I can't do the fullrender on my server, my hosting staff said to talk to a dynmap developer.. May u help me?

**Comment by JurgenKuyper** [comment]
Please elaborate on the issue

**Comment by DirePlays** [comment]
> Si prega di approfondire la questione

my server can't full render the dynmap site, im using the free method. Do i have to send u the browser link?

**Comment by JurgenKuyper** [comment]
That your server can't fullrender is not an issue from our end, but rather from your host not supporting it, contact them on other options

**Comment by JurgenKuyper** [comment]
Closing issue because user did not respond. If still having an Issue feel free to open a new tracker.
