### ISSUE TITLE
Tiles are black on zoomed out map

### ISSUE THREAD

**Issue by MarcPG1905** [webbukkit/dynmap#3907]
**When the map is zoomed out, there are black stripes like the rendering skipped one part**
When I zoom in, the tiles reappear.
This happened when I set my pc into power saving mode and the server was lagging and I got the error "the server is __ ticks or __ms running behind"(I didn't find it in the logs but I remember seing this after I put my pc out of power saving mode)

* **Dynmap Version:** *Dynmap-3.5-beta-1-spigot*
* **Server Version:** *paper-1.19.3-367*
* **Pastebin of Configuration.txt:** *I didn't change anything*
* **Server Host (if applicable):** *My PC(no server hoster)*
* **Other Relevant Data/Screenshots:** *I'm using worldedit and this map: https://www.planetminecraft.com/project/1-924-scale-earth-map-4909390/
![image](https://user-images.githubusercontent.com/87030363/210257777-183de034-8a0c-4eb4-97cb-c51bcec1faca.png)
*
* **Steps to Replicate:** 
1. Start a fullrender of your map
2. Let it run for a while(i let it run for about 15min)
3. set your pc to power saving mode
4. wait for about 10seconds
5. start your pc again(click with your mouse)
6. wait for about 2min
7. open your map on http://localhost:8123/
8. see the black things

Sorry for bad english...

**Comment by JurgenKuyper** [comment]
Purge the map and rerender, hibernate or sleep is not supported

**Comment by JurgenKuyper** [comment]
@MarcPG1905 did you fix the issue? if so, feel free to close the issue

**Comment by MarcPG1905** [comment]
> @MarcPG1905 did you fix the issue? if so, feel free to close the issue

I just deleted the old map and started again and everything works fine now.
