### ISSUE TITLE
Large disk space consumption

### ISSUE THREAD

**Issue by Hadeslnc** [webbukkit/dynmap#3908]
Hello, this is just a simple question

So, im running server with overworld map of 10k*10k size, when i rendered flat map with only option changed is image quality set to jpg-75 - it took around 5 gigs of disk space and 1kk of tiles. But when i set to render isometric map with image quality set to 85% it took enormously around 30 gigs and 3.5kk tiles to render. I wonder is it normal behavior or not. Sadly i have 70 gigs limitation on server hosting, so i have to concern about disk space consumption

**Comment by JurgenKuyper** [comment]
That is normal as the surface is 3D , isometric so it takes more pixels per block to show depth

**Comment by JurgenKuyper** [comment]
@CalleyInc did you get the answer you wanted? if you don't have any other questions about the toppic, feel free to close the issue
