### ISSUE TITLE
Curseforge file details typo "kosmo"

### ISSUE THREAD

**Issue by lambdakilo** [webbukkit/dynmap#3911]
https://www.curseforge.com/minecraft/mc-mods/dynmapforge/files/4167189

The "Support v1.19.3 (thanks to kosmo!)" should be "kosma" based on the commits and the name of @kosma .

**Comment by JurgenKuyper** [comment]
in discord he is called Cosmolot, it is not an @ so not direct mentioned, and on curseforge he is called https://www.curseforge.com/members/kosmolotlive/followers Kosmolotlive, imo not really an issue

**Comment by kosma** [comment]
I use different names online, it's not a problem, but thanks for spotting this! ❤️

**Comment by lambdakilo** [comment]
Good insights! Thank you ❤️ and thanks again to @kosma for making 1.19.3 happen!
