### ISSUE TITLE
Dynmap with SkinsRestorer in proxy mode

### ISSUE THREAD

**Issue by ReySho** [webbukkit/dynmap#3912]
**Issue Description:** *Good afternoon. Dynmap is running with SkinRestorer in proxy mode and constantly spamming the console when players log in, and due to an error, does not display players skin faces on the online map*

* **Dynmap Version:** *dynmap-v3.5-beta-1*
* **Server Version:** *pufferfish 1.18.2*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/xnD1ZW27*
* **Other Relevant Data/Screenshots:** *![msedge_blQ0fhpIvv](https://user-images.githubusercontent.com/70453575/211047512-b21d7e06-2c8f-486d-91a8-8e2ab42ae91a.jpg)*
* **Steps to Replicate:** *install BungeeCord + SkinsRestorer 14.2.5 in proxy mode*

**Comment by JurgenKuyper** [comment]
Skinsrestorer in proxy mode is currently not supported
