### ISSUE TITLE
mySQLException - Marker file write error (max_allowed_packet)

### ISSUE THREAD

**Issue by LcyDev** [webbukkit/dynmap#3913]
**Issue Description:** This error started showing up in the console for no reason, i don't even know what the hell is the marker file and i tried deleting markers.yml and the markers folder.

* **Dynmap Version:** *Dynmap-3.5-beta-1-spigot*
* **Server Version:** *git-Purpur-1858 (MC: 1.19.2)**
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Server Host (if applicable):** *HeavyNode*
* **Steps to Replicate:** *Unknown*

 [Y] *I have looked at all other issues and this is not a duplicate*  
 [Y] *I have been able to replicate this* (Still happening)

```
[11:11:07] [Dynmap Render Thread/ERROR]: [dynmap] SQLException: Marker file write error
[11:11:07] [Dynmap Render Thread/ERROR]: [dynmap]   ErrorCode: 0, SQLState=S1000
[11:11:07] [Dynmap Render Thread/ERROR]: [dynmap]   Message: Packet for query is too large (5,341,895 > 4,194,304). You can change this value on the server by setting the 'max_allowed_packet' variable.
[11:11:07] [Dynmap Render Thread/ERROR]: [dynmap]   ConnectionString: jdbc:mysql://mce02.mia.us.heavynode.net:3306/s12259_dynmap
```

**Comment by JurgenKuyper** [comment]
Please attach the proper configuration.txt, as the one you sent isn't the one used because then dynmap couldn't be using MySQL. Enfin, the error stated means that the packet sent to the MySQL database server is larger than the maximum allowed size set by the node admin (HeavyNode), contact their support on whether they want to increase that setting.

**Comment by LcyDev** [comment]
Sorry i don't know what happened there
https://paste.gg/p/ConaII_/35ceffdd07c847f88ddb86142f52b5a0

**Comment by JurgenKuyper** [comment]
You can remove it and change your MySQL password, thought you would have remover your credentials, now anyone can use your MySQL server with those credentials. Anyways, i already explained your next course of action in my previous message

**Comment by LcyDev** [comment]
shit, i didn't realize that I'm really stressed with all of this
I already created the ticket so i'm waiting now

**Comment by LcyDev** [comment]
Do you know what it means by "marker file"?
Can i delete and regen that somehow
Why is it so heavy for a mysql query??

**Comment by JurgenKuyper** [comment]
The marker file in MySQL stores all the marker data, and if using many of them (icons or area markers) that file can get quite big, so, ask your host to increase the value max_allowed_packet

**Comment by LcyDev** [comment]
They increased it to 64MB, it's fixed now.
