### ISSUE TITLE
Standalone Error 500 configuration.php

### ISSUE THREAD

**Issue by MathieuSibret-UCLL** [webbukkit/dynmap#3919]
**Issue Description:** *
I'm trying to get a extrernal webserver using the filetree storage system

I made a pterodactyl mount to my minecraft server, and edited configuration.txt to send webserver and tiles data to the mount. For my web server I used a nginx docker container with the www directory pointing to previously mentioned mount directory. This directory does contain dynmap's written content. I've tried  to edit the dir's permission to 777 but dynmap wasn't able to write in the file anymore.

When accessing webserver I get a 500 error: Failed to load resource: the server responded with a status of 500 (Internal Server Error) :5004/standalone/configuration.php:1

after a refresh I get the error pointing to this file: jquery-3.5.1.js?_=3.5-beta-1-844:10099 (https://pastebin.com/m8L6U0uG)
*

* **Dynmap Version:** *version 3.5-beta-1-844 is enabled - core version 3.5-beta-1-844*
* **Server Version:** *paper 1.19.3 build 384*
* **Pastebin of Configuration.txt:** *https://pastebin.com/1bTJzEGb*
* **Server Host (if applicable):** *Selfhosted pterodactyl (docker)*
* **Steps to Replicate:** *
- * *Make a pterodactyl mount to the minecraft server, edit configuration.txt to send webserver and tiles data to the mount. * *
- * *Use nginx docker container with the www directory pointing to previously mounted directory.* *

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by rautamiekka** [comment]
Did you enable the Web Server's debug logging ? Don't ask me how.

**Comment by JurgenKuyper** [comment]
you cannot use filetree with pterodactyl because of file permissions, the container has other user:group sets compared to the webserver container ones, you can however setup a mysql server to serve as a connector between the two containers.

**Comment by JurgenKuyper** [comment]
Closing issue because OP didn't respond, assuming fixed
