### ISSUE TITLE
Missing option to pause rendering by default

### ISSUE THREAD

**Issue by Tunikas** [webbukkit/dynmap#3920]
Hello,

so i run Dynmap on Paper (Spigot).

The reason i do not want rendering is that i want the players to explore the map "normally", meaning they take a map zoomX explore it fully put it onto our map-board and i accept the new map by calling a radiusrender comand. 
I have a few player, who just like it that way as part of the game. And i like that too.

Now i have run into the issue, that from my understanding at server restart Dynmap starts to render again at player position despite "pause all" was comanded.

I tried using visibility options. But by my understanding i can only define rectangles. Players adding map parts will give our board of maps more of a patchwork look, so until they fill the next bigger rectangle i can't use the visibility definition to uncover the new map part.

I would want to either know how to use the visibility option to define multiple areas OR to just pause rendering by default so that every act of rendering comes solely by the OP doings.

Greetings

PS: I'm neither a programmer nor an english native speaker, pls be patient with me

> template is **bold**
> sample data is *italicized*

**Feature Description:** *Dynmap sample feature request description. This description would include as much and as little detail necessary for us to understand the feature in its entirety.*

* **Additional context:** *Please add any additional information you feel will help us understand the feature*

**Comment by JurgenKuyper** [comment]
dynmap indeed restarts the render if restarted, it doesn't save the status to disk on shutdown, however, it just continues with the render where it left off, it doesn't restart it at the player position. you can also define circular visibilitylimits: https://github.com/webbukkit/dynmap/wiki/World-and-template-settings, and they stack, so you can define almost infinite ones (also available in commands: https://github.com/webbukkit/dynmap/wiki/Commands#mapworld-configuration-commands). you cannot without the use of a "startup command plugin" stop dynmap from continuing a fullrender on server start.

**Comment by Tunikas** [comment]
> continues with the render where it left off, it doesn't restart it at the player position

ok but the behaviour that i can see, is that it at some point renders tiles the players have visited. So even if dynmap finishes the jobs it had before restart it will eventually render new tiles i might not want to be visible. Is that correct?

>  /dmap worldgetlimits <world> : this returns the visibility and hidden limits for a world, as a single list with 'limittype' of visible or hidden, and the settings showing the shape's attributes
/dmap worldaddlimit <world> corner1:<x1>/<z1> corner2:<x2>/<z2> : this adds a visibility limit, shaped as a rectangle, from block coordinate x1, z1 to x2, z2. You can add as many as you choose.
/dmap worldaddlimit <world> type:round center:<x>/<z> radius:<radius> : this adds a visibility limit, shaped as a circle, centered at block x, z and with radius . You can add as many as you choose. 

found this. Didn't see that. Thanks, this will practically solve my issue from what i get. 
And thanks again, i will look into that plugin too.

**Comment by JurgenKuyper** [comment]
>ok but the behaviour that i can see, is that it at some point renders tiles the players have visited. So even if dynmap finishes the jobs it had before restart it will eventually render new tiles i might not want to be visible. Is that correct?

that is correct indeed, unless you disable the rendertriggers, then it should be fully manual. 

If this answers your question and you don't have any further questions, feel free to close this thread
