### ISSUE TITLE
Opening links in new tab while using dynmap in iframe

### ISSUE THREAD

**Issue by CichyCze** [webbukkit/dynmap#3922]
**Feature Description:** *Add the <base target=\"_blank\"> tag to the index.html file header of the dynmap for better use in <iframe>. At least make it possible to turn on/off in the config file.*

**Edit**: *I just found out that logo component is not the only link on the dynmap. My intention with this feature was to not open external links while using dynmap in the <iframe> tag which can be simply done with the external link in the logo component. It would be awesome to have that logo component opening in new tab instead of the actual window.*

**Comment by JurgenKuyper** [comment]
you can propose any change by creating a pull request on this github, We don't really provide support that makes other systems work better. Otherwise the support would get too big to handle. If that answers your question, feel free to close this issue.

**Comment by CichyCze** [comment]
Well, I don't know how that works, but I'll try somehow. Thanks for your assistance.
