### ISSUE TITLE
Slow server startup

### ISSUE THREAD

**Issue by cconde** [webbukkit/dynmap#3923]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *On startup all Dynmap rendered files are printed to log by Minecraft, making it really slow to start due to the time spent logging the files*

* **Dynmap Version:** v3.4-828
* **Server Version:** Paper 1.19.2 in Docker
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Other Relevant Data/Screenshots:** ![image](https://user-images.githubusercontent.com/5311254/215869789-4a52eb87-e0b6-495a-b9ee-da6e37b89d81.png)
* **Steps to Replicate:** I just installed the plugin and run the docker

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

Please excuse me if it's a very basic question, but I've tried to search and google around this startup slowness and I can't find anything even related to my issue.

When my Minecraft server starts I see thousands of entries in the log showing each Dynmap file

As I'm tailing the logs during several minutes the only thing I can see is the file entries logged, then after everything is shown server starts properly.

Is there any way to avoid those logs?

Thanks!!!

**Comment by JurgenKuyper** [comment]
that is not something dynmap does, as all dynmap's output is preceded by [dynmap]

**Comment by cconde** [comment]
Thank you, I will look into main Minecraft server behavior

**Comment by JurgenKuyper** [comment]
@cconde did you manage to fix your issue? if so, feel free to close the tracker.

**Comment by JurgenKuyper** [comment]
closing issue, user did not respond, assuming fixed.
