### ISSUE TITLE
Dynmap is showing a black void.

### ISSUE THREAD

**Issue by spikehidden** [webbukkit/dynmap#3924]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** 3.5-beta-2-849
* **Server Version:** git-Purpur-1906 (MC: 1.19.3)
* **Pastebin of Configuration.txt:** https://paste.denizenscript.com/View/105901
* **Server Host (if applicable):** Selfhosted
* **Pastebin of crashlogs or other relevant logs:**
  * Chrome Dev Console Log (Error of missing files/variables): https://pastebin.com/AwFZYLVg
* **Other Relevant Data/Screenshots:**
  * Plugins: https://pastebin.com/PTpBiZUH
  * Site: https://map.foxcraft.biz
* **Steps to Replicate:**
 1. Install Dynmap
 2. Set up the configuration.txt to use mySQL
 3. Copy Web directory to your web server
 4. Open the site and see a black void.

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**EDIT:**
[errormap.foxcraft.biz](https://errormap.foxcraft.biz/) links to the same directory and shows the map perfectly and that regardless of if I host it on my Vserver or at my webhoster. In both cases map.foxcraft.biz shows void and errormap.foxcraft.biz does not.

I wonder why...

**Comment by JurgenKuyper** [comment]
Sounds like a web configuration issue on your end to me?

**Comment by JurgenKuyper** [comment]
closing issue, link seems to work.
