### ISSUE TITLE
Dynmap - RlCraft conflict

### ISSUE THREAD

**Issue by tm6177** [webbukkit/dynmap#3928]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *My server is running on 1.12.2 with the dynmap mod and the RlCraft package. My problem is the empty blocks visible on the map. I know it may be because RlCraft contains its textures, but I don't know how to fix it.*

* **Dynmap Version:** *3.4*
* **Server Version:** *forge 1.12.2 build 14.23.5.2860*
* **Pastebin of Configuration.txt:** *https://pastebin.com/7bDikKDD*
* **Server Host (if applicable):** *Selfhosted*
![rlcraft](https://user-images.githubusercontent.com/124629239/217083197-d9e5886d-1925-4ee2-b93a-4277bf86b644.png)

**Comment by JurgenKuyper** [comment]
FAQ 7)  My dynmap doesn't show modded blocks!
Modded blocks aren't supported out of the box, here are two tools that can help!

1. Dynmap-BlockScan: This mod scans the block textures and model files for most mods and allows dynmap to render them. The most common use case is to render the definitions once, then place the files generated at dynmap/renderdata/modsupport into the dynmap/renderdata folder directly then remove the blockscan plugin. This speeds up server start times and should only need to be run once per server. Once you have done this, upload your files to the repo in #2 
http://dynmap.us/builds/DynmapBlockScan/

2. Dynmap-BlockScanData Repo: I created a github repo for data generated by the dynmap blockscan mod. This repo gives instruction where to place the data and puts the definition files in a easy-to-find location and can be less work than running blockscan yourself. This repo is entirely community driven and needs your help to generate mod definition files for those that we don't have already. Most* definition files are version agnostic (1.12.2 files will work on 1.16 and vice versa) but you obviously won't get new textures added in later versions.
https://github.com/FedUpWith-Tech/DynmapBlockScan-Data

**Comment by tm6177** [comment]
I I downloaded this mod, the files generated in the renderdata folder, but there are still not rendered blocks on the map page.

**Comment by JurgenKuyper** [comment]
you need to rerender the map to show the new blocks.

**Comment by tm6177** [comment]
Okay, now everything works, thanks for your help.

**Comment by JurgenKuyper** [comment]
np, I am going to close this issue now, glad it works!
