### ISSUE TITLE
Option to change the colours of the depth gradient on the cave map

### ISSUE THREAD

**Issue by averixus** [webbukkit/dynmap#3929]
**Feature Description:** A way for users to define the colour gradient used to represent depth on the cave view. 

**Additional context:** I find the default green/blue gradient very subtle and would like a way to make it clearer. [This page](https://github.com/webbukkit/dynmap/wiki/Defining-custom-shaders) from 2021 says "Future Dynmap releases expect to add options for defining the colors used for cave shading.", but I didn't find any more recent mentions of that. If the option has already been added please let me know!

**Comment by JurgenKuyper** [comment]
do you want a start-gradient and end-gradient config or like the topohd shader? (https://dynmap-setup.jurgenmk.nl/?worldname=world_shaders&mapname=surfaceto256)

**Comment by averixus** [comment]
@JurgenKuyper I haven't used other shaders so I'm not 100% on a preferred implementation.. but it seems like a start-gradient and end-gradient config would be the simplest (both to add and to use)?

**Comment by JurgenKuyper** [comment]
Yeah it should, i shall try something out tomorrow Eve and hopefully have a working build somewhere this week

**Comment by JurgenKuyper** [comment]
![image](https://user-images.githubusercontent.com/45831568/217614647-451e7ca2-0a90-497c-9eab-426c156990bc.png)
new colours :D (startColor: "#FF0000"  endColor: "#0000FF")
