### ISSUE TITLE
Dynmap Spamming Console with unknown issue 

### ISSUE THREAD

**Issue by MrPoosa** [webbukkit/dynmap#3930]

**Comment by rautamiekka** [comment]
Dude, delete those pastebin uploads and reupload with your logins censored ! And change the logins !!

**Comment by MrPoosa** [comment]
> Dude, delete those pastebin uploads and reupload with your logins censored ! And change the logins !!

no

**Comment by rautamiekka** [comment]
Well, I warned. Someone is gonna attack the db for sure.

**Comment by MrPoosa** [comment]
> Well, I warned. Someone is gonna attack the db for sure.

nuh uh (i changed it)

**Comment by JurgenKuyper** [comment]
https://github.com/webbukkit/dynmap/wiki/Configuration.txt#storage-scheme

**Comment by JurgenKuyper** [comment]
Closing issue because OP didn't respond, assuming fixed
