### ISSUE TITLE
Better Zoom Out

### ISSUE THREAD

**Issue by Svastojed** [webbukkit/dynmap#3936]
**Feature Description:** *Dynmap sample feature request description. This description would include as much and as little detail necessary for us to understand the feature in its entirety.*
Currently most maps dont fit dynmap extra out settings, so i would like a expansion on that extra zoom out feature:
Instead of 3 it could go 3.1 to 3.9 as well, i got a earth map for example that would be perfect on 3.3 on just 3 i got a lot of black space.
* **Additional context:** *Please add any additional information you feel will help us understand the feature*

**Comment by JurgenKuyper** [comment]
Zoomouts can be defined by a user either using commands or using the file: https://github.com/webbukkit/dynmap/wiki/World-and-template-settings

**Comment by Svastojed** [comment]
Can you read? zoom out is restricted to full numbers thats why you cant get full screen on most maps

**Comment by JurgenKuyper** [comment]
yes, as a matter of fact I can read, and no, it is not possible to use non-integers in the zoomouts, as each adds a new level which is twice as small as the previous, as stated on the wiki, if you read about it.

**Comment by Svastojed** [comment]
So thats hard coded that way? Feature Requests tend to request new features, next time just write it cant be expanded on instead of telling people that how templates work.

**Comment by JurgenKuyper** [comment]
zoomouts can be expanded upon, just on a resolution of 1, not smaller.
