### ISSUE TITLE
login support is not enabled

### ISSUE THREAD

**Issue by iamlucky2020** [webbukkit/dynmap#3939]
whenever I do /dynmap webregister I get an error, "Login support is not enabled" "[02:25:55] [Server thread/INFO]: Login support is not enabled"

v3.5
1.19.3
minefort
I 

it happens every time I do the command, I have done the command 10+ times

**Comment by JurgenKuyper** [comment]
You need to enable login in configuration.txt, after which it will work.

**Comment by JurgenKuyper** [comment]
Assumed fixed, closing issue
