### ISSUE TITLE
Dynmap only rendering blocks below water in chunks

### ISSUE THREAD

**Issue by Skaytacium** [webbukkit/dynmap#3940]
**Issue Description:** I tried full-rendering an Earth map after pregerating the chunks using [Chunky](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator). The pregeneration works fine and dynmap is able to render most tiles that I haven't visited before but for some reason some times are only half rendered. This seems to be an issue with dynmap specifically because the earth file is working fine when I join, the chunk itself is considered "rendered" by dynmap but as shown in the screenshots I can only see the areas that have water on top of them.

* **Dynmap Version:** Fabric 3.5-beta2 1.19.2
* **Server Version:** Fabric 1.19.2
* **Pastebin of Configuration.txt:** https://pastebin.com/tKFhvGgt
* **Server Host (if applicable):** SparkedHost
* **Pastebin of crashlogs or other relevant logs:** No relevant logs
* **Other Relevant Data/Screenshots:**
![image](https://user-images.githubusercontent.com/58383260/222119923-1c4ce8fb-b990-4292-a5ea-a0cd9fffa329.png)
![image](https://user-images.githubusercontent.com/58383260/222120012-6d925334-d66f-4d86-a485-7768ba517681.png)
![image](https://user-images.githubusercontent.com/58383260/222120052-3af6591c-7c63-4103-8815-752f4da98ef5.png)

* **Steps to Replicate:**
    - Start server
    - Queue fullrender
    - Some tiles are missing
    - Try rendering manually by going to tile and doing `/dynmap render`
    - Still half rendered

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Did you use the force-generate-chunks setting of chunky? That is needed for earth maps to be in their propper state

**Comment by Skaytacium** [comment]
No I don't think so, I'll retry with that but it should generate a chunk if I'm standing on it right?

**Comment by Skaytacium** [comment]
Turns out the map was corrupted. Re downloading it worked.
