### ISSUE TITLE
Port forwarding Dynmap to External IP

### ISSUE THREAD

**Issue by Kxvinos** [webbukkit/dynmap#3941]
Hi, im having the exact same issue as this one here: 
https://github.com/webbukkit/dynmap/issues/955

Unfortunately they didnt drop the fix they found, so if anyone can help me, i'd greatly appreciate it, ive been trying to fix it for weeks

everything is the same, event the ports im using.

**Comment by JurgenKuyper** [comment]
You need to port-forward and open the firewalls to allow the traffic of dynmap through, like is stated on the installation page of the wiki.

**Comment by Kxvinos** [comment]
> 



> You need to port-forward and open the firewalls to allow the traffic of dynmap through, like is stated on the installation page of the wiki.

I did, but ofcourse about 5 mins after posting this i figured it out lol, my pc is running 2 ips somehow, i changed the ip and now its working, this thread can be closed!

**Comment by JurgenKuyper** [comment]
Could be two different nics, anyway, glad it works now!
