### ISSUE TITLE
Rotating Dynmap 180 degrees

### ISSUE THREAD

**Issue by Kxvinos** [webbukkit/dynmap#3943]
Hi, so currently on my dynmap i can see the world from the left ish, is there a way to be able to rotate it around the map? (see image)

![image](https://user-images.githubusercontent.com/127102384/223517902-38475d2f-9a03-4c3f-a59d-ad37ad57bac3.png)

**Comment by JurgenKuyper** [comment]
That is possible, you can add a new map using the dmap mapadd command, and define the perspective in that command like iso_NW_60_hires for example: https://github.com/webbukkit/dynmap/wiki/Commands#mapworld-configuration-commands

**Comment by Kxvinos** [comment]
> That is possible, you can add a new map using the dmap mapadd command, and define the perspective in that command like iso_NW_60_hires for example: https://github.com/webbukkit/dynmap/wiki/Commands#mapworld-configuration-commands

Hi, thanks, im not sure what im doing wrong, im getting this error:
![image](https://user-images.githubusercontent.com/127102384/223672041-51ae8c53-8a83-418e-96b8-de5eaff81420.png)

**Comment by JurgenKuyper** [comment]
You need to set the world and mapname in the command too, as stated in the link I sent.

**Comment by Kxvinos** [comment]
> You need to set the world and mapname in the command too, as stated in the link I sent.

yeah i just found that out, tho i cant get the dynmap to show the other side, every option i try it gives this weird top angle, which one would i need to put in to show the other side of the first picture? 
![image](https://user-images.githubusercontent.com/127102384/223676040-299fd027-fe82-47af-a38a-42c22033ef12.png)

**Comment by JurgenKuyper** [comment]
The second part of the perspective dictates the rotate angle in cardinal directions, (NW is opposite of SE), the third part is the tilt angle, normally 30 for low , 60 for high or 90 for topdown view

**Comment by Kxvinos** [comment]
> The second part of the perspective dictates the rotate angle in cardinal directions, (NW is opposite of SE), the third part is the tilt angle, normally 30 for low , 60 for high or 90 for topdown view

/dmap mapadd world:test iso_NW_30_hires 

alright i think i get it, but what else do i need to add to that command to make it work? ^ 

apologies for not really understanding this much!

**Comment by JurgenKuyper** [comment]
No worries, we all gotta start somewhere, after a fullrender of that map, it should show the requested perspective (command to render a single map is also in that wiki link)

**Comment by Kxvinos** [comment]
Alright. currnetly just letting it render w that exact command, i so then after the fullrender is done it'll show it from the opposite side i want? Thanks :D
![image](https://user-images.githubusercontent.com/127102384/223680643-821b33bd-7ae8-4a49-8577-67bff07007af.png)

**Comment by JurgenKuyper** [comment]
You can always check map data using the dmap maplist command, what is the output of that now?

**Comment by Kxvinos** [comment]
![image](https://user-images.githubusercontent.com/127102384/223686939-d03f73e8-8b34-46ec-904e-2ef84af635ff.png)

currently this:

**Comment by JurgenKuyper** [comment]
The last two maps have the same perspective, test and southeast, i don't think that is what you want Right?

**Comment by Kxvinos** [comment]
yh i noticed that too, i just deleted both of them, for some reason the perspective keeps going to "default" even tho i put in iso_NW_30_hires

**Comment by JurgenKuyper** [comment]
Can you show what you are typing in?

**Comment by Kxvinos** [comment]
![image](https://user-images.githubusercontent.com/127102384/223690056-3d179474-2548-482b-a64f-e44b8a00dae1.png)

**Comment by JurgenKuyper** [comment]
You are missing perspective:<perspective type>

**Comment by Kxvinos** [comment]
omg i see, i tried that but it gave me an error, i had a space there apparently 🤦‍♂️ thank you so much, its working now :D

**Comment by JurgenKuyper** [comment]
Nice, glad it works out, if the result turns out to be what you want, you can go ahead and close this issue 👍

**Comment by Kxvinos** [comment]
Yup, thanks! Imma let the perspectives render for a while and see if i get the correct result!

**Comment by JurgenKuyper** [comment]
Assuming the result is wanted, closing the issue
