### ISSUE TITLE
1.19.4 will there be an update to this version

### ISSUE THREAD

**Issue by Jager67** [webbukkit/dynmap#3947]
I know it's soon to ask but 1.19.4 seems to have broke dynmap please let me know what information is needed to help you find the fix for this new version.

**Comment by kosma** [comment]
It's happening as we speak, there are already dev builds for Fabric and Spigot. Join the Discord to get the latest news.

**Comment by mikeprimm** [comment]
Release of v3.5-beta-3, which includes 1.19.4 support for all platforms, is in progress now.
