### ISSUE TITLE
I want to export the map

### ISSUE THREAD

**Issue by Eustiya** [webbukkit/dynmap#3949]
This is a great plugin.
I want to export the generated map image. I found that there are image files in the "dynmap\web\tiles" directory, so I merge them.But there are always fewer images than I see directly on the website
What is the picture prefixed with z?
What is the ratio of image pixels to game location?

Thank you for the great creation of the author. I use 1.12.2 spigot

**Comment by Eustiya** [comment]
I wrote a Bukkit plugin to merge images, and I am sure to merge all images that do not contain the z prefix, but I don't know why a part of the map is missing

**Comment by JurgenKuyper** [comment]
in filetree each folder in tiles is a world, in each world folder is a map prefix folder name, in each map folder are the folders containing the tiles of which the name is the name of the first tile in it binarily shifted 5 0s, each z is a zoomout level, the values are from what i recall either the position or the MCA values

**Comment by Eustiya** [comment]
@JurgenKuyper 
![1679482853312](https://user-images.githubusercontent.com/36254769/226884654-5286023f-5ba8-41d5-a898-ebcadd6d934b.jpg)
Screenshot directly from the website
![map](https://user-images.githubusercontent.com/36254769/226884670-e55f6051-6065-4287-9f45-d81b68addc21.png)
By merging folders "dynmap\web\tiles" files
Is there a lack of images in the directory, but why can all of them be displayed on the website?
How do I determine the pixel relationship between the coordinates in the game and the image? Convenient for me to process on the picture

**Comment by JurgenKuyper** [comment]
You can use the F12 console to inspect the location of all the images, i don't know the relation to images and pixels, could also be the block position of one of the corner blocks
