### ISSUE TITLE
markers.yml (almost) empty

### ISSUE THREAD

**Issue by IkeC** [webbukkit/dynmap#3956]
When I start the server with this markers.yml: [markers.yml.original.txt](https://github.com/webbukkit/dynmap/files/11298189/markers.yml.original.txt)
It soon is regenerated almost empty: [markers.yml.result.txt](https://github.com/webbukkit/dynmap/files/11298188/markers.yml.result.txt) and my markers are gone.

Running latest Paper and Dynmap versions. Any help appreciated.

**Comment by JurgenKuyper** [comment]
If using MySQL the markers are stored in the database

**Comment by IkeC** [comment]
I‘m using flat files.

**Comment by JurgenKuyper** [comment]
Then it's probably not liking the format, please add the markers using commands instead of the files

**Comment by IkeC** [comment]
> Then it's probably not liking the format, please add the markers using commands instead of the files

All markers were added using commands.

I couldn't get a test case to work to figure out the problem, so I ended up starting from scratch. Maybe some additional logging on debug level would help.

**Comment by JurgenKuyper** [comment]
I'm not sure, but i think enabling debugging shows what gets loaded when
