### ISSUE TITLE
Renderizado 

### ISSUE THREAD

**Issue by Alucad-07** [webbukkit/dynmap#3959]
hola, qusiera saber como puedo acelerar el tema de renderizado ya que mi servidor es el mas caro y tiene buenos componentes pero en el renderizado es muy lento, qusiera saber como acelerarlo o como hacer para que el renderizado aploveche todo de hardware de el servidor ya que el mapa que quiero ocupar, me urge bastante que ya este listo

**Comment by JurgenKuyper** [comment]
Please use English, i don't know Spanish and thus cannot help. Also, use the template that was shown when you created this issue tracker.

**Comment by Alucad-07** [comment]
Hello, I would like to know how I can speed up the rendering issue since my server is the most expensive and has good components but the rendering is very slow. I would like to know how to speed it up or how to make the rendering take advantage of all the hardware of the server already that the map that I want to occupy is quite urgent for me to be ready

**Comment by JurgenKuyper** [comment]
```renderaccelerateinterval: .001``` 
```tiles-rendered-at-once: 10``` 
```maxchunkspertick: 400``` 
```parallelrendercnt: 10``` 
```fullrenderplayerlimit: 0``` 
```per-tick-time-limit: 200``` 
```fullrender-min-tps: 5``` 
(configuration.txt) here the server has 10 cores, change the parallelrenderct to the amount of cores you have. Next do /dynmap pause all, restart and finally do /dynmap pause none.

**Comment by JurgenKuyper** [comment]
user didn't respond, assuming fixed.
