### ISSUE TITLE
dynmap error 11

### ISSUE THREAD

**Issue by roistav** [webbukkit/dynmap#3960]
my earth server uses dynmap in sqlite and this massage keeps getting spammed in console 
the server opens today so if someone can fix this asap it would be very helpful
![image](https://github.com/webbukkit/dynmap/assets/105160871/3c8d7b3f-e645-4133-ae07-55a33e184ba0)
if you need a  link to the  map:
http://51.210.208.8:11835/?worldname=world&mapname=surface&zoom=0&x=-2705&y=64&z=-533#

**Comment by JurgenKuyper** [comment]
Your SQLite is corrupted, delete it and re-render the map, nothing much you can do about afaik

**Comment by roistav** [comment]
> 
alr thx

**Comment by JurgenKuyper** [comment]
closing issue as solved
