### ISSUE TITLE
dynmap error to console

### ISSUE THREAD

**Issue by 1Pootis1** [webbukkit/dynmap#3961]
**Issue Description:** *error in console when running dynmap: https://pastebin.com/FaqPZZMb*

* **Dynmap Version:** *Dynmap-3.5-spigot*
* **Server Version:** *paper-1.18.2-388*
* **Pastebin of Configuration.txt:** *https://pastebin.com/6CN1xC32*
* **Server Host (if applicable):** *Timeweb*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Your configuration is malformed, you have both settings for internal and external webserver enabled, that is not supported, please follow the external webserver setup guide on the wiki: https://github.com/webbukkit/dynmap/wiki/%5BTutorial%5D-Setting-up-a-standalone-web-server-with-MySQL-SQLite/

**Comment by JurgenKuyper** [comment]
User didn't respond, assuming no longer an issue
