### ISSUE TITLE
Train lines addon

### ISSUE THREAD

**Issue by Blueeyestar** [webbukkit/dynmap#3963]
We have normal rail traffic and subway traffic on our server.
Since we are using the dynmap it would be great if we could create our own layer that we could toggle on and off to make the lines visible.
Also that you could make the individual rails visible on the dynmap in the desired color.

Or is it already possible and I've overlooked it?

Just like the server did. Is that an extra plugin or did he do it with dynmap?
https://dynmap.minecartrapidtransit.net/#new;flat;0,64,-32;0

**Comment by JurgenKuyper** [comment]
Yes, you can add the max height value in the perspective to set the max render height, like is done here: https://gist.github.com/depwl9992/626bf2c20269abe9cda79eeab0de58af

**Comment by JurgenKuyper** [comment]
Yes, you can add the max height value in the perspective to set the max render height, like is done here: https://gist.github.com/depwl9992/626bf2c20269abe9cda79eeab0de58af

**Comment by Blueeyestar** [comment]
> Yes, you can add the max height value in the perspective to set the max render height, like is done here: https://gist.github.com/depwl9992/626bf2c20269abe9cda79eeab0de58af

That's not really what I'm looking for..but thanks anyway

**Comment by samuelh2005** [comment]
@Blueeyestar 
Look at https://github.com/webbukkit/dynmap/wiki/Commands#Markers. Is that everything? You could use a plugin to make this easier. but it exists in vanilla Dynmap.
