### ISSUE TITLE
WorldEdit event bus support

### ISSUE THREAD

**Issue by RNELord** [webbukkit/dynmap#3964]
**Feature Description:** *Support for re-rendering the map when WorldEdit changes are made.*

* **Additional context:**
Previous issues seem to have been resolved with WorldEdit not emitting the proper events to hook. I managed to make a working hook plugin here: https://github.com/SpawnPixel/DynmapWorldEditHook (disclaimer: it's a very quick implementation and could use some polish).

It'd be great if you could integrate support for the WorldEdit event bus to re-render on edits.

Thanks!

**Comment by mikeprimm** [comment]
As a firm rule, I will not integrate mod or plugin specific support into base dynmap - did that a long time back, and it created a massive problem with support, particularly across versions and platforms - so this isn't going to happen.  What you've done with the plugin is the right solution, and I encourage you to publish and support it.
