### ISSUE TITLE
Unable to find /js/coord.js after full render

### ISSUE THREAD

**Issue by ISlip3890** [webbukkit/dynmap#3966]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Unable to find /js/coord.js after full render*

* **Dynmap Version:** *core=3.5-873, plugin=3.5-873*
* **Server Version:** *Paper version git-Paper-540 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: f9f9079)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/RRaCKdvz*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/xZFXU6bF*
* **Other Relevant Data/Screenshots:** ![image](https://github.com/webbukkit/dynmap/assets/74471699/565e45a5-d77b-4d86-8d98-c3ee66d0fd4e)
* **Steps to Replicate:** 
* Start a full render of world
* Wait for it to complete
* Restart
* Go to the webmap

 [*] *I have looked at all other issues and this is not a duplicate*  
 [*] *I have been able to replicate this*

Map URL:
http://smpworld.mc-join.org:8123/

**Comment by JurgenKuyper** [comment]
Seems to be fixed, closing
