### ISSUE TITLE
Tags in dynmap 

### ISSUE THREAD

**Issue by euvoutepossuir** [webbukkit/dynmap#3967]
how to put the tag of the players in the dynmap like this in the example below?  ![ 7905A2C5-7E8B-45BE-A77C-3DE384E06388](https://github.com/webbukkit/dynmap/assets/104235904/f7a7c618-ac31-4e30-b913-a5adace16711)

**Comment by JurgenKuyper** [comment]
idk, maybe try the mc colours in a nickname?
