### ISSUE TITLE
Duplicated messages on webchat.

### ISSUE THREAD

**Issue by DesolateIntention** [webbukkit/dynmap#3968]
I'm opening this issue to continue #3012. The same issue is present on my server, but it's not consistent.

* **Dynmap Version:** *3.5*
* **Server Version:** *Purpur 1.19.2 1973.*
* **Pastebin of Configuration.txt:** *https://pastebin.com/6ytjn2yY*
* **Steps to Replicate:**
1. I'm not very sure how to replicate this. I know that's a bad thing, but you said that if someone encountered the same bug, they should open a bug report.

![image](https://github.com/webbukkit/dynmap/assets/63953363/bcde5e25-edc5-4ae1-b58a-448770759a33)
![image](https://github.com/webbukkit/dynmap/assets/63953363/2f76480f-4720-4b77-b324-14a17ba49774)

 [Yes] *I have looked at all other issues and this is not a duplicate*  
 [Occasionally] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Purpur is not supported by us so issues might arise, could also be an issue with the domain proxy that might have been enabled

**Comment by JurgenKuyper** [comment]
User didn't respond, assuming no longer needed, closing thread.

**Comment by DesolateIntention** [comment]
What issue with the domain proxy?
