### ISSUE TITLE
Extract Level Data

### ISSUE THREAD

**Issue by ryotayagiABC** [webbukkit/dynmap#3969]
Hey there! 

I've got a quick question for you. 

Is it possible to extract ground surface elevation data in dynmap? 

I've managed to extract surface data already, and now I'm looking to take the next step by creating level data. Any insights or guidance you could provide would be greatly appreciated. Thanks a bunch!

**Comment by JurgenKuyper** [comment]
https://dynmap-setup.jurgenmk.nl/?worldname=world_shaders&mapname=surfaceto256&zoom=0&x=203&y=64&z=-131 you mean like this?

**Comment by ryotayagiABC** [comment]
Thank you for your prompt reply! I appreciate your help.

I have a question regarding extracting a flat image of surface-level data. In the attached picture, it appears to be the default function of dynmap for viewing architecture from a skewed perspective. However, I'm interested in seeing the architecture from an overhead view. Could you advise me on how to achieve this? 

Also, how to add so many layers in your dynmap?

Thank you again for your help!

![Screen Shot 2023-06-18 at 23 01 28](https://github.com/webbukkit/dynmap/assets/105612984/ac34e71b-7c6c-450e-9025-8f6f3547c761)

**Comment by JurgenKuyper** [comment]
You can fully customize the map data and amount of maps, there is a small grey cube on that site that links to the configured configuration behind the site (an updated git repo) it should help you with what you need, if you don't understand, there are explanations on the wiki, and if you need clarification feel free to ask here or on discord

**Comment by JurgenKuyper** [comment]
@ryotayagiABC did you get it working? if so, you can go ahead and close this tracker.

**Comment by ryotayagiABC** [comment]
Thank you very much for your splendid advice! I could make it by changing the configuration of dynmap. This is very useful and I appreciate your advice.
