### ISSUE TITLE
1.20 Plugin brocken

### ISSUE THREAD

**Issue by LeonBoettcher** [webbukkit/dynmap#3972]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap doesnt create Folders in Plugin Folder and so no Config files, Commands dont work either.*

* **Dynmap Version:** *Dynmap-3.5-spigot*
* **Server Version:** *CraftBukkit version 3781-Spigot-16cfc98-fd92f1e (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT)*
* **Steps to Replicate:** *Input any command and look in the plugins folder after starting the server*

 [x ] *I have looked at all other issues and this is not a duplicate*  
 [x ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
That version is not the right one, use the latest one

**Comment by LeonBoettcher** [comment]
It seems like 3.5 is the latest, or do you mean build it by myselfe?

**Comment by JurgenKuyper** [comment]
3.6 beta is out: https://dynmap.us/builds/dynmap, it's there

**Comment by LeonBoettcher** [comment]
Ah thanks
