### ISSUE TITLE
Support other S3 compatible APIs

### ISSUE THREAD

**Issue by p47-6** [webbukkit/dynmap#3973]
**Feature Description:** Please Support additional to Amazon S3 also compatible services like [Cloudflare R2](https://www.cloudflare.com/de-de/products/r2/) or [MinIO](https://min.io/)

Essentially it should be possible to freely configure the URL.

**Comment by NoaHimesaka1873** [comment]
Seriously, why is this, a very simple but very important issue, isn't fixed for years? S3-compatible storages have been there for *years*.

**Comment by MODNMETL** [comment]
Yes PLEASE! It is hideously expensive for us to even think about using AWS for our dynmap storage. The ability to use other S3 providers would be awesome!
