### ISSUE TITLE
Dynmap Crashing Server on Startup

### ISSUE THREAD

**Issue by hunterdavidson** [webbukkit/dynmap#3977]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Every time I run the server with the Dynmap mod in the mods folder I get an error that shuts the server down instantly. When I take it out of the mods folder, everything runs fine. All the files and folders created by Dynmap seem normal, but it keeps casting this error that is in the log when I run the server with the mod loaded in.*

* **Dynmap Version:** *Dynmap-3.6-beta-1-fabric-1.20*
* **Server Version:** *fabric 1.20 build 0.14.21*
* **Pastebin of Configuration.txt:** *https://pastebin.com/D1fug1SW*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/s3ta79qe*
* **Other Relevant Data/Screenshots:** **
* **Steps to Replicate:** *I just ran the server with the mods listed in the log*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by SwordfishBE** [comment]
You are running the fabric version on a bukkit (papermc, spigotmc,..) server. Download the correct dynmap.

**Comment by JurgenKuyper** [comment]
can you try with only dynmap and fabric-api in the mods folder?

**Comment by hunterdavidson** [comment]
I figured out it was a cross issue with the Yetanotherconfiglib mod loading certain libraries, which was just fixed in its most recent update.
