### ISSUE TITLE
Add a feature for a password to be used for staff

### ISSUE THREAD

**Issue by Whitelisted1** [webbukkit/dynmap#3980]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Add a feature which blocks the use of Dynmap for normal players but, with a password or something similar, allows staff to access the website*

* **Additional context:** *Maybe, if possible, allow staff to authenticate in minecraft chat, and, if they have a certain permission, `dynmap.view`, for example, allow them to view the website. This would be useful as it allows admins to more easily moderate their servers without the threat of players using the plugin to find other players*

**Comment by JurgenKuyper** [comment]
Use the standard login feature and only add logins for the admin accounts, should all already be in place

**Comment by Whitelisted1** [comment]
Alright, thanks for the advice
