### ISSUE TITLE
Configuring the texture pack for different modes

### ISSUE THREAD

**Issue by dayd21git** [webbukkit/dynmap#3983]
> template is **bold**
> sample data is *italicized*

**Feature Description:** Hello. Can you please tell me how to assign a different texture pack to each mode? The problem is that my resource pack only works in 3D mode, and it doesn't work in 2D mode :(

**ResourcePack:**
> texturepacks\Pack.zip

**configuration.txt**
> deftemplatesuffix: hires

**templates\normal-hires.txt**
```     maps:
      - class: org.dynmap.hdmap.HDMap
        name: flat
        title: "2D"
        prefix: flat
        perspective: iso_S_90_lowres
        shader: default
        lighting: shadows
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface
        title: "3D"
        prefix: t
        perspective: iso_SE_30_hires
        shader: default
        lighting: shadows
        mapzoomin: 1
```

**custom-shaders.txt**
```shaders:
  - class: org.dynmap.hdmap.TexturePackHDShader
    name: default
    texturepack: Pack.zip
  - class: org.dynmap.hdmap.TexturePackHDShader
    name: stdtexture
    texturepack: Pack.zip
```

**Comment by JurgenKuyper** [comment]
I would say you have a clash in shader naming, maybe change the name to a shader that is not already in use, that would then work for both maps after a fullrender / radiusrender

**Comment by dayd21git** [comment]
> I would say you have a clash in shader naming, maybe change the name to a shader that is not already in use, that would then work for both maps after a fullrender / radiusrender

I'll try to check it out, thanks for the advice!

**Comment by dayd21git** [comment]
> I would say you have a clash in shader naming, maybe change the name to a shader that is not already in use, that would then work for both maps after a fullrender / radiusrender

I may be wrong, but I needed to reset the render and execute it again so that the new textures would apply to the already existing world! Anyway, thanks for the advice again :)
