### ISSUE TITLE
Server crash (MC 1.19.2) Exit code: -1

### ISSUE THREAD

**Issue by vinnyg0621** [webbukkit/dynmap#3984]
**Issue Description:** *when loading a world, the game just crashed and said that special characters are not allowed.*

* **Dynmap Version:** *3.5*
* **Server Version:** *Forge 1.19.2*
* **Pastebin of Configuration.txt:** *https://pastebin.com/5SETL3z2*
* **Server Host (if applicable):** *McProHosting, Shockbyte, Selfhosted, etc.*
* **Pastebin of crashlogs or other relevant logs:** *https://gist.github.com/vinnyg0621/243db5590b90b4f4f99be99e8d97de41*
* **Other Relevant Data/Screenshots:** *I just don't know what that means, "special characters are not allowed"*
* **Steps to Replicate:** *Go onto a world, and then the game will crash on 100% loading screen*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Dynmap is only supported on servers, not clients, please try on a forge server and see if the error persists

**Comment by mikeprimm** [comment]
The specific error is relative to the forgeworlds.yml file - you might try deleting that, but as @JurgenKuyper says, running in the client (or standalone) is not specifically supported, so if it works at all, that's a pleasant surprise.

**Comment by vinnyg0621** [comment]
oh, I wasn't using a server actually
