### ISSUE TITLE
unable to login in website in newer 1.20.1 builds

### ISSUE THREAD

**Issue by CloudeLecaw** [webbukkit/dynmap#3985]
On your dynmap webpage your normaly can login with the door button if your registered
![Snag_5e42eb](https://github.com/webbukkit/dynmap/assets/12080017/afdc97e5-6cea-44c3-99b3-3fabb7c58d30)

![Snag_59fdf6](https://github.com/webbukkit/dynmap/assets/12080017/888730c8-21fd-4f40-ade5-e8e4a61a3c60)

We noticed that trying to login there fails. Your also get a message that your login failed.

We took a while befor noticed its because of a newer build of paper 1.20.1

* **Dynmap Version:** *Dynmap_3.6-beta2*
* **Server Version:** *paper 1.20.1 build 63 and any newer one*

As solution to be able to use the weblog aggin we downgraded now topaper 1.20.1 build 62

I dont know but may dynmap needs to adjust something here for build of paper 1.20.1 63+ (so build 63 and newer)

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Known issue, paper needs to fix for now, unless they say how the new api is going to work

**Comment by CloudeLecaw** [comment]
https://github.com/PaperMC/Paper/issues/9457#issuecomment-1624814676

might you coukd talk with the devs there and ask them about ?

**Comment by JurgenKuyper** [comment]
Latest release of dynmap should have a temporary patch so at least you can login again, please take a look at the 3.6 GA version

**Comment by JurgenKuyper** [comment]
no longer relevant as the login api should work again and dynmap complains if not: https://github.com/webbukkit/dynmap/pull/3988
