### ISSUE TITLE
Trying to render main world

### ISSUE THREAD

**Issue by mcl-playz** [webbukkit/dynmap#3989]
**Issue Description:** *I can't do a full render of my server. It gives the error in the photo. I tried adding it in worlds.txt, but still won't work.*

* **Dynmap Version:** *3.6*
* **Server Version:** *paper 1.20 build*
* **Pastebin of Configuration.txt:** *https://pastebin.com/Ex85ESyZ*
* **Server Host (if applicable):** *Pebblehost*
* **Other Relevant Data/Screenshots:** ![image](https://github.com/webbukkit/dynmap/assets/99476285/9a813483-9025-4042-9490-61787de0ff9a)
* **Steps to Replicate:** *Run the command /dynmap fullrender*

 [ yes ] *I have looked at all other issues and this is not a duplicate*  
 [ yes ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Your deftemplatesuffix values is malformed, check with the available values: https://github.com/webbukkit/dynmap/wiki/Configuration.txt#deftemplatesuffix

**Comment by mcl-playz** [comment]
Wow thanks so much.

**Comment by JurgenKuyper** [comment]
can I assume this as fixed now? (please close the issue tracker if so)

**Comment by mcl-playz** [comment]
Sorry about that.
