### ISSUE TITLE
Dynmap chat not working

### ISSUE THREAD

**Issue by Haltonzo** [webbukkit/dynmap#3991]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Typing a message on Dynmap does not show up in-game nor on dynmap. Nothing has been able to change this as of yet, including being logged into the server while trying to chat. In-game chats show up on Dynmap. It worked when I first began my server 2 weeks ago, and has stopped as of ~4 days ago*

* **Dynmap Version:** *3.6*
* **Server Version:** *paper 1.20.1 build 69*
* **Pastebin of Configuration.txt:** *https://pastebin.com/UNfCXZb5*
* **Server Host (if applicable):** *Shockbyte*

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Did you maybe remove the broadcast permission from users? Or added any chat management plugin?
