### ISSUE TITLE
black chunks after fullrender

### ISSUE THREAD

**Issue by shalopai** [webbukkit/dynmap#3992]
after a fullrender i can see some black chunks (a radiusrender to fix this dont work)
https://imgur.com/a/hvFGiMK
mc version: 1.19.4

**Comment by JurgenKuyper** [comment]
The EarthMC map has many known issues with Dynmap such as, incomplete render, only rendering where players have visited, or not rendering leaves and other foliage. This is a result of how the map was made and is not an issue with Dynmap, luckily there is a fix. 
1. Download the WorldBorder plugin: https://www.spigotmc.org/resources/worldborder.60905/ 
 
2. Pause Dynmap: /dynmap pause all 
 
3. Set the world border radius and center: /wb [worldname] set [radiusX] [radiusZ] [X] [Z] 
 
 - [worldname] is the name of the world you want to set the border in. 
 
 - [radiusX] is the horizontal radius of the world border 
 
 - [radiusZ] is the vertical radius of the world border 
 
 - [X] is the horizontal center point of the world border 
 
 - [Z] is the vertical center point of the world border 
 
4. Run worldborder with the force flag: /wb [worldname] fill [freq] [pad] [force] 
 
 - [worldname] is the world you want to be pregenerated 
 
 - [freq] is how many chunks a second are generated, 20 is the default. WARNING: setting this too high will cause server lag 
 
 - [pad] how many chunks beyond the border to generate, this makes sure that if a player visits the border, all chunks are already generated. The default is 208, We recommend setting this to 0 for EarthMC. 
 
 - [force] This must be set to true 
 
5. Wait for worldborder to finish 
 
6. Unpause Dynmap: /dynmap pause none, you may have to start the fullrender using /dynmap fullrender [worldname]

**Comment by talwat** [comment]
I'm experiencing this too, and even after doing this it hasn't fixed it.

**Comment by talwat** [comment]
Also, worldborder hasn't been updated in 5 years, don't use it.

**Comment by JurgenKuyper** [comment]
@talwat it works fine, just because the last update was a few years ago doesn't mean it is bad or you shouldn't use it, worldborder is one of only 2 plugins that I know can fix those issues.

**Comment by talwat** [comment]
What does the worldborder fix actually do? Does it force load chunks once? Does it pre-generate them? I'm confused on this.

**Comment by JurgenKuyper** [comment]
That is also explained on the worldborder wiki, but it will bring all the chunks in it's set range to their last generation state so dynmap can render them.

**Comment by talwat** [comment]
I tried squaremap and it worked flawlessly, so I think it's a dynmap problem.

**Comment by talwat** [comment]
Was there a commit in dynmap that fixed this problem?

**Comment by JurgenKuyper** [comment]
No, but the aforementioned way of using worldborder works, and we are not going to implement chunk generation in dynmap, so not planned

**Comment by mhtvsSFrpHdE** [comment]
Hi, I've discovered how to fix this

- Update dynmap version to at least `Dynmap-3.7-beta-10-spigot`
- Install chunk pre-gen plugin like Chunky https://www.spigotmc.org/resources/chunky.81534/
- Make a radius render for example radius 8000  
`dynmap radiusrender world 0 0 8000`
- Wait until render complete, check web map and confirm there are still black area
- Run pre-gen plugin  
`chunky world world`  
`chunky radius 8000`  
`chunky start`
- Wait for really long time depends on your radius, after chunky done,  
continue wait dynmap to complete render, in this process, don't stop server
- Now map should clean, if there still black, teleport there and walk around to see if it can be rendered manually

You need to make a render area first, then pre-gen, finally manual teleport and walk, order is matter

https://github.com/webbukkit/dynmap/issues/3907
