### ISSUE TITLE
Reverse proxy website not working

### ISSUE THREAD

**Issue by ImMarsman** [webbukkit/dynmap#3999]
**Issue Description:** *After reverse proxy, website would display 404 not found*

* **Dynmap Version:** *3.6*
* **Server Version:** *spigot*
* **Pastebin of Configuration.txt:** *https://pastebin.com/pdC8mihJ*
* **Server Host (if applicable):** * Selfhosted*
* **Other Relevant Data/Screenshots:** *
![image](https://github.com/webbukkit/dynmap/assets/65621960/11b78f63-4001-4999-8408-b6b3fcc340b8)
![image](https://github.com/webbukkit/dynmap/assets/65621960/bdfa293b-cdb8-4527-8c0d-7ed5ad0c9cfa)
![image](https://github.com/webbukkit/dynmap/assets/65621960/f8f7b94d-ab48-4556-bc9a-df87443c1632)
*
* **Steps to Replicate:** *followed this tutorial https://github.com/webbukkit/dynmap/wiki/%5BTutorial%5D-Setting-up-a-standalone-web-server-with-MySQL-SQLite*

**Comment by JurgenKuyper** [comment]
What do the nginx error.log state? Also, what you are doing is not a reverse proxy but an external webserver

**Comment by ImMarsman** [comment]
Hey, so im not sure exactly what I did to make it work but i followed this other website: https://docs.phoenixnodes.com/advanced-guides/install-nginx-reverse-proxy-on-ubuntu-18.04-for-dynmap
thanks for the reply though :)
my Dynmap is working correctly at: mapa.mundochetos.com

**Comment by ImMarsman** [comment]
Hey, so im not sure exactly what I did to make it work but i followed this other website: https://docs.phoenixnodes.com/advanced-guides/install-nginx-reverse-proxy-on-ubuntu-18.04-for-dynmap
thanks for the reply though :)
my Dynmap is working correctly at: mapa.mundochetos.com
