### ISSUE TITLE
Dynmap keeps reloading | configHash check failed

### ISSUE THREAD

**Issue by KleinDevDE** [webbukkit/dynmap#4002]
> template is **bold**
> sample data is *italicized*

**Issue Description:**
We have the problem that our dynmap constantly reloads and does not stop.

The dynmap is running in a pterodactyl container.  
The folder for the web files is defined to `/dynmap` which is a symlink out of the container to our /var/www.  
We're having 2 servers, each of them has a dynmap which the same configuration and a symlink to 
Our Server "Themona" works perfectly with the dynmap, but our Server "EONA" not.  

What have we already tried?
- Copy config from Themona to EONA and restart EONA.
- Restart host system
- Delete everything and full-render
- Clear Cloudflare cache and create rule for cache bypass
- Use other browser, use cell phone
- Attached cache control headers via Apache

Here some links to the maps:
General: https://dynmap.eona-minecraft.de/  
EONA: https://dynmap.eona-minecraft.de/eona  
-> Symlink /dynmap => /var/www/XX/eona -- configHash problem
Themona: https://dynmap.eona-minecraft.de/themona
-> Symlink /dynmap => /var/www/XX/themona -- Working

We've added some debug output to the map.js, where the reloading thing happens.  
```js
                                if(me.options.confighash != update.confighash) {
                                    console.log("configHash problem!");
                                    console.log(me.options.confighash + " != " + update.confighash);
                                    console.log("me.options", me.options, JSON.stringify(me.options));
                                    console.log("update", update, JSON.stringify(update));
                                    debugger;
                                    window.location = me.getLink();
                                        return;
                                }
```
Here is the result
configHash problem!
-645971886 != -645971893
me.options: https://pastebin.com/1vNgBGpz  
update:  https://pastebin.com/gq2S8ayP

* **Dynmap Version:** core=3.6-899, plugin=3.6-899
* **Server Version:** git-Paper-407 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 8c4e811)
* **Pastebin of Configuration.txt:** [*https://pastebin.com/5SETL3z2*](https://pastebin.com/FQkD0tiJ)
* **Server Host (if applicable):** Netcup
* **Pastebin of crashlogs or other relevant logs:** There is no crash or something
* **Steps to Replicate:** We cannot provide that information, bc we don't know how to reproduce it for others.

 [ ] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*
 
 There are other duplicated and closed issues like: #1726 or #1546
 But none of them could provide a final solution for this.

**Comment by JurgenKuyper** [comment]
Are there any logs in the nginx webserver logs (/var/log/nginx/error.log)?

**Comment by KleinDevDE** [comment]
> Are there any logs in the nginx webserver logs (/var/log/nginx/error.log)?

We're using apache2
Access-Log: https://pastebin.com/LGDvc0yY
Error-Log: https://pastebin.com/xbhVKibk

**Comment by JurgenKuyper** [comment]
Looks like either some files didn't get copied over or it has no permission to read them

**Comment by KleinDevDE** [comment]
A few minutes before posting the logs, I tried to open the dynmap.  
The error logs you see doesn't rely to this current problem, bc it was way before 10:00 AM  

In the access logs, you'll see logs from today 10:53 AM, this was me.  

It seems like there is a problem with the `dynmap_world.json`.  
It is the same as yesterday, at least the configHash
Should this file being updated in a specific interval?  

The symlink itself is working, I've added some files in the Pterodactyl container under `/dynmap`,
the files were accessible via the website.
https://dynmap.eona-minecraft.de/eona/test.html

**Comment by JurgenKuyper** [comment]
yeah I think the confighash is updated every <updateinterval> set in configuration, if your proxy is not that fast, it might fail, but this is not tested, just guessing here

**Comment by KleinDevDE** [comment]
The dynmap_world.json file got not updated the whole time, I would say this is the main reason for the problem.  
You can compare both files and reload after a few seconds.  
[https://dynmap.eona-minecraft.de/eona/standalone/dynmap_world.json](https://dynmap.eona-minecraft.de/eona/standalone/dynmap_world.json)
[https://dynmap.eona-minecraft.de/themona/standalone/dynmap_world.json](https://dynmap.eona-minecraft.de/themona/standalone/dynmap_world.json)

The question here is, why does the file not going to be updated?  
I deleted the configuration.txt to let them generate by the Dynmap plugin.  
I modified the configuration to use `/dynmap` as web-folder and enabled "JsonFileClientUpdateComponent".
-> https://pastebin.com/YmfxRXPr
But this does also not work

The web folder conents got generated, also the dynmap_world.json.
But the dynmap_world.json itself doesn't get updated.
But now, I get some exception from the dynmap about the maptype: https://pastebin.com/DAW0rsKc





Here is a little overview about our architecture with the symlinks.
![image](https://github.com/webbukkit/dynmap/assets/13904220/59128a51-ab24-424b-8501-87657f418048)

**Comment by JurgenKuyper** [comment]
If one works and the other doesn't, check for any config changes in between those, maybe the file permissions are different so Dynmap cannot write

**Comment by JurgenKuyper** [comment]
no update so assuming fixed
