### ISSUE TITLE
Configuration.txt differs greatly by platform/version

### ISSUE THREAD

**Issue by Jameskmonger** [webbukkit/dynmap#4008]
**Issue Description:** The `configuration.txt` files in the `resources` folders differ greatly by platform and version. I have used a diff tool to compare around 10 of them and they all seem to be different in some way (typos, missing values, missing options in example lists, different example values)

I can't find any documentation about whether these differences are intentional, if they are not it would be more robust (and more supportive to change) to have a single `configuration.txt` which gets copied into the builds by Gradle (similar to `worlds.txt` I believe).

**Comment by JurgenKuyper** [comment]
They are different by design and capabilities of the different server types

**Comment by Jameskmonger** [comment]
That may be the case with some of the differences but I doubt it explains most of them.

If it does, that should be documented somewhere - otherwise how do contributors know which versions they should be updating?

**Styling discrepancies**
- There are a lot of typos/mistakes in certain versions that are fixed in other versions
- There are lots of comments that are missing from some versions and present in others

**Functional discrepancies**
- Some versions are missing `webp` listings for `image-format`
- Some versions support all `jpg-q` except `q100`
- Some versions apparently don't support `noPermissionMsg`
- Some versions support `flags` when connecting with `mysql`
- Some versions support `prefix` when connecting with `aws_s3`
- Some versions have `showweather` enabled by default, others don't
- Some versions support `compass-mode`, others don't
- Some versions support `player-sort-permission-nodes`
- Some versions support `round-coordinates`

**Functional discrepancies that I think might be genuine**
- Some versions are missing some default `render-triggers`
- Some versions support `custom-commands`, others don't
- Some versions support SkinRestorer, others don't
- Some versions/platforms support `migrate-chunks`, others don't

**Comment by Jameskmonger** [comment]
There are many more. These ^ are the discrepancies I found from comparing ~6 files

**Comment by mikeprimm** [comment]
Some differences are intentional - others are incidental - ultimately, they go with the specific deliverable (a forge config file will not work as-is on spigot, and vice versa).  They are just default configuration files for a mod that is 12 years old, and many of the missing fields are defaulted consistently with the ones that do have them - folks are free to change them as they see fit for their purposes.
