### ISSUE TITLE
[1.12.2] ArrayIndexOutOfBoundsException/Error while raytracing tile

### ISSUE THREAD

**Issue by andrew121410** [webbukkit/dynmap#4020]
**Issue Description:** When just roaming around or using /dynmap updaterender I get this error.

* **Dynmap Version:** Dynmap version: core=3.7-beta-1-917, plugin=3.7-beta-1-917
* **Server Version:** Paper 1.12.2
* **Pastebin of Configuration.txt:** https://mclo.gs/9A1JEtk
* **Server Host (if applicable):** Self host
* **Pastebin of crashlogs or other relevant logs:** https://mclo.gs/JjKi0gB
* **Other Relevant Data/Screenshots:** Nope.
* **Steps to Replicate:** Unfortunately I was not able to replicate this issue, on my Paper 1.12.2 testing server only plugin installed was Dynmap

 [ ✅] *I have looked at all other issues and this is not a duplicate*  
 [ ] *I have been able to replicate this*

**Comment by andrew121410** [comment]
I decided to delete the whole dynmap/ directory in the plugins folder to just reset everything. I started up the server and did /dynmap fullrender and it started throwing those errors again.

**Comment by JurgenKuyper** [comment]
1.12.2 is EOL, we don't support it anymore for paper and spigot.

**Comment by andrew121410** [comment]
So this bug is a won't fix?

**Comment by JurgenKuyper** [comment]
You might try older builds of dynmap, but you will also loose features

**Comment by andrew121410** [comment]
Fixed it by updating BKCommonLib and Light Cleaner they were many many years out of date. Running /cleanlight fixed it after updating

**Comment by andrew121410** [comment]
Never mind it didn't fix the issue, oh well. How much money :wink would you fix it for?

Should I re-open this or just leave it closed?

**Comment by JurgenKuyper** [comment]
None, we cannot be bartered, it is EOL, we won't pull it back to support, we already support many versions across 4 distros.
