### ISSUE TITLE
Dynmap crashes on paper 1.20.2 build 217

### ISSUE THREAD

**Issue by SileboxUnderfined** [webbukkit/dynmap#4024]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap plugin crashes on version 1.20.2. See pastebin of server startup log to view errors.*

* **Dynmap Version:** *dynmap v3.6 Paper/SpigotMC*
* **Server Version:** *paper 1.20.2 build 217*
* **Pastebin of Configuration.txt:** *https://pastebin.com/GMGrDwdG*
* **Server Host (if applicable):** *minecraft.rent.*
* **Pastebin of crashlogs or other relevant logs:**
 *https://pastebin.com/3cBdyzwF*
* **Other Relevant Data/Screenshots:** *n/a*
* **Steps to Replicate:** *start paper server version 1.20.1 with dynmap v3.6, and after start paper server on 1.20.2 build 217 with dynmap 3.6 *

 [ x ] *I have looked at all other issues and this is not a duplicate*  
 [ x ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
Please update to the latest version, 3.7-b2

**Comment by SileboxUnderfined** [comment]
> Please update to the latest version, 3.7-b2

Thanks, it worked!
