### ISSUE TITLE
你们怎么想的 把reload的功能移除了

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [webbukkit/dynmap#4031]
我们编辑了插件的配置文件之后总得需要重载，但是你的插件为什么没有相关指令？
如果是插件版本那还可以使用服务端直接重载插件，但要是MOD版，你说怎么重载？？！只能关掉服务器重新开。这让我们很难堪，根本没法正常游戏了
<img width="677" alt="reload呢" src="https://github.com/webbukkit/dynmap/assets/141799770/44634e02-a0b4-4e9f-aba8-bc37e03d1ae4">

**Comment by JurgenKuyper** [comment]
support is only given in English using the template to do so, please follow the guidelines to do so and open a new ticket.

**Comment by MinecraftEarthVillage** [comment]
> 使用模板仅以英语提供支持，请按照指南执行此操作并打开新票证。

After editing the configuration file of the plugin, we always need to reload it, but why doesn't your plugin have any relevant instructions?

If it's a plugin version, you can still use the server to directly reload plugins, but if it's a MOD version, how do you think about reloading??! You can only turn off the server and restart it. This makes us very embarrassed, we can't play normally anymore
