### ISSUE TITLE
We need a feature to overload(reload the config) configuration files

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [webbukkit/dynmap#4032]
(I'm from Guangdong, sorry I don't speak very good English, most of which are translation plugins)

Everyone should know that Minecraft Server plugin usually has editable configuration files. After editing and saving, use the reload command to reload (refresh), for example,/ess reload is the refresh configuration file command for the EssentialsX plugin. However, during actual testing, there were no relevant instructions for your Dynmap.

If I edit the relevant configurations of Markers in the background, but the editing does not work due to the inability to refresh, so we have to restart the entire server every time we edit the webpage map, which is very troublesome

**Comment by JurgenKuyper** [comment]
you again didn't adhere to the template.
Most settings needed during normal operation can be changed using commands, restarting is only needed in the first setup configuration to change stuff like port or credentials of storage. everything is documented on our wiki.
