### ISSUE TITLE
We need a feature to overload(reload the config) configuration files

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [webbukkit/dynmap#4033]
[(I'm from Guangdong, sorry I don't speak very good English, most of which are Edge translation)](https://github.com/webbukkit/dynmap/issues/4031)

Everyone should know that Minecraft Server plugin usually has editable configuration files. After editing and saving, use the reload command to reload (refresh), for example,/ess reload is the refresh configuration file command for the EssentialsX plugin. However, during actual testing, there were no relevant instructions for your Dynmap.

If I edit the relevant configurations of Markers in the background, but the editing does not work due to the inability to refresh, so we have to restart the entire server every time we edit the webpage map, which is very troublesome

Unless it can be guaranteed that all operations of dynmap can be completed only in the game, do not easily remove the reload command, which is a very important basic function

**Oh! Also, the most important thing is that I am using a Mods server with version 1.19.4 and **Dynmap Mod** with version -3.7-beta-1. Remember to update it~~**

**Comment by TimBuckrue** [comment]
I currently use Plugman to unload and load the dynmap plugin and it works for reloading the configs. Having a dedicated reload command would be really nice though.

**Comment by JurgenKuyper** [comment]
was there, but broke the webserver, thus decided to remove it, it's not that hard to restart a server for a config change, most settings are either set only during initial configuration, or can be changed using the dmap / dmarker commands and thus not requiring a restart.
