### ISSUE TITLE
Black lines in between tiles on chromium based browsers

### ISSUE THREAD

**Issue by TimBuckrue** [webbukkit/dynmap#4035]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Black seams appear in between every tile on chromium browsers.*

* **Dynmap Version:** *3.7-beta-2-923*
* **Server Version:** *git-Paper-307 (MC: 1.20.2)*
* **Pastebin of Configuration.txt:** *https://pastebin.com/ydufZ7Qv*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *N/A*
* **Other Relevant Data/Screenshots:** *[Chromium based browser](https://github.com/webbukkit/dynmap/assets/30376835/7a0c64ae-8675-44ba-9002-02c0190c5344) [Firefox](https://github.com/webbukkit/dynmap/assets/30376835/fccd7cb9-260e-41b9-9df9-b78372f2752c)*
* **Steps to Replicate:** *Look at the map in a chromium browser. Helps if you are looking at a plain area like an ocean or a desert. This happens in both Microsoft Edge and Google Chrome and is extremely distracting. Happens no matter the image format (webp, png, jpg). This does not appear to affect Chrome on Android.*

 [ x ] *I have looked at all other issues and this is not a duplicate*  
 [ x ] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
that is because your monitor is probably 4K, and the underlying leaflet.js cannot work with that properly, nothing to do about it from our side.
