### ISSUE TITLE
Some tiles doesn't render at all leaving holes in the map (not even using updaterender, have to go manually to update the chunk)

### ISSUE THREAD

**Issue by ItsYuriil** [webbukkit/dynmap#4037]
**Issue Description:** 
Whenever I render some chunks, theres lots of them that appear black or are just not rendered on the map, altough the mod still thinks it has been rendered. (since the updaterender command skips those chunks instead of generating them)

![image](https://github.com/webbukkit/dynmap/assets/91994171/08564961-4d91-4b5b-bc03-f952d49d1e2c)

And some chunks only render this way, on the surface map they doesn't render, I end up having to go there manually and rendering an radius around myself.

![image](https://github.com/webbukkit/dynmap/assets/91994171/254ffadb-b454-44f5-9cad-1285aeadce39)

![image](https://github.com/webbukkit/dynmap/assets/91994171/c6cdd0ad-04b0-4cf2-a61a-83368856c58b)

These two views have different renders, and even worse, they skipped in the surface map. (again, using updaterender  command doesn't fix it at all)

All the empty rendered chunks are already generated ones, I did pregen the map on start and players actually traverse those empty chunks, not updating them.

Some Image examples here:
![image](https://github.com/webbukkit/dynmap/assets/91994171/eada474a-cc4f-483e-b702-736e26c770b9)
![image](https://github.com/webbukkit/dynmap/assets/91994171/fa15804a-8275-49a7-aa02-a5bb9262399b)
I did have to come there and generate the chunks manually, but since theres no queue for radius renders I have to wait everytime I want to fill thoose gaps.

To be honest, from all the info I've looked up, nothing has worked, I increased the tickrate, did a pregen of thoose chunks, used the update render, cleared the queue and stuff to see if some tiles got suck in it... but nothing works.

I love this plugin/mod, but looking at the map just shows a really ugly perspective, where all the buildings are not rendered leaving holes in the map.

![image](https://github.com/webbukkit/dynmap/assets/91994171/d28ae8c2-2b66-4a02-accb-f4785ded3b74)

(image example)

Please, I'd like if someone could help me troubleshoot this.

* **Dynmap Version:** *Dynmap-3.6 forge 1.18.2*
* **Server Version:** Forge 1.18.2
* **Pastebin of Configuration.txt:** *https://pastebin.com/WsTmNGEV*
* **Other Relevant Data/Screenshots:** *I'm using DawnCraft Modpack with its resource pack (Excalibur) and its modded blocks, but 90% are already defined by DynmapBlockScan (using 3.6-forge-1.18)*
* **Steps to Replicate:** *Just rendering a bulk of chunks, then trying to update the surrounding chunks and see its not woking at all*

 [ ] *I have looked at all other issues and this is not a duplicate*  (I've searched this forum and none of the black holes issues are like this one, they are generated chunks, it only happen on the firsts chunks generated on the server instead of random noise.

 [ ] *I don't know or why it does replicate this*

**Comment by ItsYuriil** [comment]
![image](https://github.com/webbukkit/dynmap/assets/91994171/38c80c1c-9ef6-4128-92fc-a6f8fb45fcb1)
I really hate to see this holes everywhere near the player zone, where everyone is currently playing, the chunks doen't render at all, not even when a player goes by and updates it... I seriously have no idea on how to fix it

**Comment by JurgenKuyper** [comment]
use radiusrender, not updaterender, that should fix those issues, dynmap doesn't understand paper's async chunk generation so it doesn't know which ones are already generated properly, you can also fix it by enabling the playermove trigger (if using paper / spigot that is)
