### ISSUE TITLE
Dynmap fails on Paper 1.20.4

### ISSUE THREAD

**Issue by BKO** [webbukkit/dynmap#4041]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** v3.7-beta-2-923
* **Server Version:** Paper 1.20.4
* **Pastebin of Configuration.txt:** https://pastebin.com/Tg4z77W9
* **Server Host (if applicable):** Pebblehost
* **Pastebin of crashlogs or other relevant logs:** https://pastebin.com/3UK5XCUw
* **Other Relevant Data/Screenshots:** These failures began after I updated my world to 1.20.4
* **Steps to Replicate:** With dynmap installed on version v3.7-beta-2-923, update server version to 1.20.4

 [x ] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
dup #4042
