### ISSUE TITLE
When doing a fullrender in the overworld, check all chunks which have existing corresponding nether chunks.

### ISSUE THREAD

**Issue by sebseb7** [webbukkit/dynmap#4045]
When doing a fullrender in the overworld "islands" not connected to spawn stay unrendered.

for each nether chunk connected to nether 0;0 check if there is a corresponding overworld chunk and vice versa to find most "islands"

**Comment by JurgenKuyper** [comment]
fullrender is only capable of rendering connected chunks, if ones are not connected, you can define fullrenderlocations for your islands as an extra starting point.

**Comment by sebseb7** [comment]
Iam aware of that, but it should "connect" chunks interdimensional between nether and overworld, this way most islands would be found without any additional fullrenderlocations.

**Comment by JurgenKuyper** [comment]
how would it know that? the nether and overworld are different dimensions

**Comment by sebseb7** [comment]
for every nether chunk, the overworld chunk with a corrdinate x / 8 should be checked

**Comment by JurgenKuyper** [comment]
we cannot implement that, that would have a too big effect on non-island users, just add a skript command on first creation of island add those fullrenderlocations to dynmap for the needed worlds

**Comment by sebseb7** [comment]
"that would have a too big effect on non-island users"

what kind of "effect" ?

**Comment by sebseb7** [comment]
" just add a skript command on first creation of island add those fullrenderlocations"

so everytime a portal gets activated that location should be added to the list, why don't do this automatically?

**Comment by JurgenKuyper** [comment]
> "that would have a too big effect on non-island users"
> 
> what kind of "effect" ?

if we implement a render of nether on the locations of overworld/8, and people don't have islands, unnecessary overhead will be used, which is not wanted, it is best for your usecase to just add the fullrenderlocations on first creation of the user's island, possibly by using skript or some other custom command plugin/mod. we already trigger a render on chunk generation, so essentially we do render them, and dependent on the server type we can catch specific block changes.

**Comment by sebseb7** [comment]
> unnecessary overhead will be used, which is not wanted

A lot of options produce overhead and therefore can be disabled, 3D maps produce overhead for people who don't need 3D maps, thats why it's optional. If you simply don't like it: fine, but it's neither complicated nor very resource intensive. checking whether a chunk was generated is very cheap, in fact it's negletible in real life. and the impact for people who disable it is: zero.
