### ISSUE TITLE
[Feature Request]: Add support for removing vanished players

### ISSUE THREAD

**Issue by lexi-the-cute** [webbukkit/dynmap#4046]
**Feature Description:** Dynmap for Fabric currently shows vanished players. The mod is https://www.curseforge.com/minecraft/mc-mods/vanish

**Comment by PortableGames** [comment]
Use this mod https://modrinth.com/mod/vanish 🤟

**Comment by lexi-the-cute** [comment]
cool, that worked! thanks!
