### ISSUE TITLE
Artifacts on the full render of the world

### ISSUE THREAD

**Issue by LeviLovie** [webbukkit/dynmap#4048]
When I use `/dynmap fullrender world` some levels of blocks in a chunk is missing texture. When i come to place and do `/dynmap radiusrender 32` in the area artifacts disappear.

* **Dynmap Version:** 3.6
* **Server Version:** Paper 1.20-17
* **Other Relevant Data/Screenshots:**

![image](https://github.com/webbukkit/dynmap/assets/107021730/95c454df-a9f1-4cce-8966-4d1ccfe822c5)
![image](https://github.com/webbukkit/dynmap/assets/107021730/9fbcefa2-7c0d-430e-87e9-cbe97def45b1)
![image](https://github.com/webbukkit/dynmap/assets/107021730/737c73ea-2f23-41a6-b885-cb51c295e101)
![image](https://github.com/webbukkit/dynmap/assets/107021730/65331943-5192-42d7-b580-dd2bf15ea458)
![image](https://github.com/webbukkit/dynmap/assets/107021730/490c4a7a-771b-4867-b6a3-8d23a47ef868)

**Comment by JurgenKuyper** [comment]
The EarthMC map has many known issues with Dynmap such as, incomplete render, only rendering where players have visited, or not rendering leaves and other foliage. This is a result of how the map was made and is not an issue with Dynmap, luckily there is a fix.
1. Download the WorldBorder plugin: https://www.spigotmc.org/resources/worldborder.60905/ 
2. Pause Dynmap: /dynmap pause all 
3. Set the world border radius and center: /wb [worldname] set [radiusX] [radiusZ] [X] [Z] 
 - [worldname] is the name of the world you want to set the border in. 
 - [radiusX] is the horizontal radius of the world border 
 - [radiusZ] is the vertical radius of the world border 
 - [ X ] is the horizontal center point of the world border 
 - [ Z ] is the vertical center point of the world border 
4. Run worldborder with the force flag: /wb [worldname] fill [freq] [pad] [force] 
 - [worldname] is the world you want to be pregenerated 
 - [freq] is how many chunks a second are generated, 20 is the default. WARNING: setting this too high will cause server lag 
 - [pad] how many chunks beyond the border to generate, this makes sure that if a player visits the border, all chunks are already generated. The default is 208, We recommend setting this to 0 for EarthMC. 
 - [force] This must be set to true 
5. Wait for worldborder to finish 
6. Unpause Dynmap: /dynmap pause none, you may have to start the fullrender using /dynmap fullrender [worldname]

**Comment by LeviLovie** [comment]
No, that is not EarthMC, that is my server's map. All cunks are generated and because of the fullrender command all the chunks must be rendered, am i correct? And there it don't make a texture for a specific layer of blocks.

Also, all chunks are already generated, so what will the /wb fill command do?

**Comment by JurgenKuyper** [comment]
wb fill force will force the chunks to their latest generation state with lighting data which is needed for dynmap to be able to render them @LeviLovie. that is why the earthmc guide works for all custom maps as they most often clamp down the actual generation of block data because of filesize.
