### ISSUE TITLE
[Question] Dynmap chat hooks into all chats (local, global, staff)

### ISSUE THREAD

**Issue by Joao-Victor-Liporini** [webbukkit/dynmap#4050]
My Dynmap chat hooks into all chats (local, global and staff) beyond discordsrv chat and i can't disable The local and staffchat, I am using nchat one fork of legendchat made to run on newer versions of Minecraft, it's possible to disable the local and staffchat on the Dynmap config.txt?

Greetings from Brazil

**Comment by Joao-Victor-Liporini** [comment]
I marked it as a bug report because I'm not sure if it's a bug or not.

**Comment by Joao-Victor-Liporini** [comment]
I marked it as a bug report because I'm not sure if it's a bug or not.

**Comment by JurgenKuyper** [comment]
you can only disable all or no chat (wiki #FAQ 8), dynmap doesn't know about channels, it just hooks into the default mojang-created chat.
