### ISSUE TITLE
Could not update map: error

### ISSUE THREAD

**Issue by Joshh-Dev** [webbukkit/dynmap#4054]
![IMG_5545](https://github.com/webbukkit/dynmap/assets/89886602/6a46b21c-5713-433f-9e2b-e30f9868d1a2)

I’ve got this plugin recently but here’s the thing, it says it couldn’t update the map after I did a full render request, my port used is 9113, the website has worked before and now randomly nothing is working with it, sometimes instead of displaying that error the website can’t load at all, could I have some assistance please.

**Comment by JurgenKuyper** [comment]
please use the template provided, that gives us essential data, without it we cannot debug properly, please create a new issue tracker with the proper data added.
