### ISSUE TITLE
Dynmap leave map blank + Could not update map

### ISSUE THREAD

**Issue by Joshh-Dev** [webbukkit/dynmap#4055]
**Issue Description:** I’ve been using Dynmap but sometimes it’ll just go blank for no reason, if I’m online it still won’t do anything, help (also I don’t have gradle installed.)

* **Dynmap Version:** Dynmap-3.7-beta-4-spigot.jar
* **Server Version:** Spigot 1.20.4
* **Pastebin of Configuration.txt:** https://pastebin.com/cVaSZ43R
* **Server Host (if applicable):** Apex Minecraft Hosting
* **Pastebin of crashlogs or other relevant logs:** None found
* **Other Relevant Data/Screenshots:** Vanilla texture pack, Here’s all my plugins.
![IMG_2121](https://github.com/webbukkit/dynmap/assets/89886602/24e6b1b8-feda-4c4f-acb6-020aa7d4ac49)
![IMG_2120](https://github.com/webbukkit/dynmap/assets/89886602/d3f59c4a-332a-420b-94aa-6809efb67a8d)
![IMG_2119](https://github.com/webbukkit/dynmap/assets/89886602/b9cea88e-9bbb-4872-9e2a-0560d89eab6e)
![IMG_2118](https://github.com/webbukkit/dynmap/assets/89886602/141e850d-8714-4959-93ef-68353551b004)

* **Steps to Replicate:** Use server address instead of website to replicate “__._.__._.__:9113”

 [1.] I’m pretty sure I downloaded this off the spigot website, So make sure you do that.
 [2.] Download a giant earth sized map off of https://earth.motfe.net/ to exactly replicate this, make sure you full rendered the map then restart and see what happens.

**Comment by Joshh-Dev** [comment]
World dimension is 73728 x 36864

**Comment by JurgenKuyper** [comment]
that sounds to me like a domain proxy error instead of dynmaps, try without proxying the data?

**Comment by Joshh-Dev** [comment]
What exactly do you mean by try to not be proxying the data, I’d like you to elaborate with me please.

**Comment by Frankie6626** [comment]
I am having the same issue. I am able to see dynmap using the server address and port. However, no chucks render and it doesn't show the world center. I wonder for my case it's not loading the correct file. The world folder name isn't "world"

**Comment by JurgenKuyper** [comment]
> What exactly do you mean by try to not be proxying the data, I’d like you to elaborate with me please.

in your domain settings you can toggle proxying of data, at least for cloudflare domains, it is best to not proxy the data as that might break stuff

**Comment by JurgenKuyper** [comment]
> I am having the same issue. I am able to see dynmap using the server address and port. However, no chucks render and it doesn't show the world center. I wonder for my case it's not loading the correct file. The world folder name isn't "world"

thats different, your deftemplatesuffix is probably wrong

**Comment by Frankie6626** [comment]
Oh, I fixed my issue. It was the level.dat level name of the server doesn't match with the configeration.txt and world.txt in the dynmap folder.

**Comment by Frankie6626** [comment]
For you, maybe try /dynmap radiusrender 200 or /dynmap fullrender to see if anything is working. 
Commands are from here: https://github.com/webbukkit/dynmap/wiki/Commands
Also, in dynmap's configuration.txt file search "render-triggers", you probably need to get rid of # for the automatic updates to work and comment out - none using #
```
render-triggers:
  #- blockupdate
  #- blockupdate-with-id
  #- chunkgenerate
  #- playermove
  - none
```

**Comment by JurgenKuyper** [comment]
no update, assume no longer needed.
