### ISSUE TITLE
Feature to start fullrender at specified x1 z1 x2 z2 coordinates

### ISSUE THREAD

**Issue by homerek111** [webbukkit/dynmap#4060]
> template is **bold**
> sample data is *italicized*

**Feature Description:** *Hello, I would like to suggest you adding a possibility to start fullrender at some specified point (using x1 z1 x2 z2 coordinates) to allow skipping bigger parts of the map

On my example: 
I fullrendered all map 20kx20k with stone hidden style and now I need to make a new fullrender to replace stone for air… it will takes days as it needs to start from the middle and I can’t use “resume” feature because it would skip my hidden stone chunks as well…

With that feature I could specify render’s start points from x1:10000 z1:10000 x2:-10000 z2:-10000 and fullrender only these parts outside the border that I need to rerender - that would save hours or even days of rendering

I’m sure that this feature has many possibilities to be used and might help many players fixing only parts of renders that they actually need. Also with that you could stop fullrender -> restart the server  -> and start it again on specified coordinates (instead of starting from the middle again with “resume” feature)*

**Comment by JurgenKuyper** [comment]
you can work around this by using the radiusrender command we have, this should suffice for your needs
