### ISSUE TITLE
Unable to use fullrender with world name with space

### ISSUE THREAD

**Issue by KweezyCode** [webbukkit/dynmap#4061]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** latest
* **Server Version:** forge 1.20.1
* **Pastebin of Configuration.txt:** default
* **Server Host (if applicable):** self
* **Pastebin of crashlogs or other relevant logs:**
```
[19:33:45] [Server thread/INFO] [Dynmap/]: [Dynmap] Loaded 3 maps of world 'New World'.
...
dynmap fullrender New World
[19:36:40] [Server thread/INFO] [minecraft/MinecraftServer]: World 'New' not defined/loaded
[19:36:40] [Server thread/INFO] [minecraft/MinecraftServer]: World 'World' not defined/loaded
```

* **Steps to Replicate:** install terrafirmacraft mod for example, then try to use fullrender

 [ ] *I have looked at all other issues and this is not a duplicate*  idk
 [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
enquote the world name: "world with space"
