### ISSUE TITLE
TFC mod render bug

### ISSUE THREAD

**Issue by KweezyCode** [webbukkit/dynmap#4062]
> template is **bold**
> sample data is *italicized*

**Issue Description:** no textures for terrafirmacraft mod

* **Dynmap Version:** latest
* **Server Version:** forge 1.20.1
* **Pastebin of Configuration.txt:** default
* **Server Host (if applicable):** self

![image](https://github.com/webbukkit/dynmap/assets/36813920/767bfecb-2275-42ab-a492-387401c96578)

* **Steps to Replicate:** install terrafirmacraft mod then go to 127.0.0.1:8123

 [ ] *I have looked at all other issues and this is not a duplicate*  idk
 [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
did you use blockscan?

**Comment by KweezyCode** [comment]
how to use it? is it a command or what?

**Comment by JurgenKuyper** [comment]
> how to use it? is it a command or what?

no, its a mod for texture generation:
https://www.reddit.com/r/Dynmap/comments/q040h7/dynmapblockscan_updated_includes_addition_of_1165/

**Comment by KweezyCode** [comment]
bit buggy, but it works
