### ISSUE TITLE
Login system not working on edge

### ISSUE THREAD

**Issue by thaboy1992** [webbukkit/dynmap#4067]
We tried with a few people on different browsers and the login system doesn't work (even after registering with webregister)

**Comment by JurgenKuyper** [comment]
not enough info, adhere to the template.

**Comment by thaboy1992** [comment]
???

How much info do you need...

Login system doesn't work on edge...   It won't login.  It does on firefox.



Op ma 4 mrt. 2024 19:51 schreef JurgenKuyper ***@***.***>:
