### ISSUE TITLE
Dynmap failing to enable on start 1.20.4

### ISSUE THREAD

**Issue by Ragchel** [webbukkit/dynmap#4071]
> template is **bold**
> sample data is *italicized*

**Issue Description:** *Dynmap sample issue description. This description would include as much and as little detail necessary for us to understand the issue in its entirety.*

* **Dynmap Version:** *3.7-beta-4-935*
* **Server Version:** *arclight-1.20.4-1.0.2-3a2ad8a*
* **Pastebin of Configuration.txt:** *N/A config isn't made as it can't be enabled*
* **Server Host (if applicable):** *Self Hosted (Wings // Ubuntu Linux 5.15.0-94-generic x86_64*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/RukC5iwT*
* **Other Relevant Data/Screenshots:** *Server with the following
mods: and_there_was_only_one_bed, CerbonsAPI, JEI, JustEnoughBeacons, mcwfurniture, worldedit
plugins: Dynmap, EssentialsX (chat, discord, discordlink, spawn) GDhooks, Griefdefender, luckperms, spark, vault, worldborder*
* **Steps to Replicate:** *Start arclight server with dynmap spigot*

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
arclight is not supported, we only support fabric forge paper and spigot. no forks of those.
