### ISSUE TITLE
Blocks from hbm are not displayed on Dynmap

### ISSUE THREAD

**Issue by TheVitya2127** [webbukkit/dynmap#4075]
I know there is a handy tool called DynmapBlockScane, but as far as I understand it doesn't exist as of 1.7.10.  Adding each file manually is very tedious, and I didn’t find any detailed wiki about this.

**Comment by JurgenKuyper** [comment]
we dont support versions belo 1.12.2, there is no real wiki on how to generate the files manually, i don't know if there is a version of blockscan for 1.7.10 at all, and it is probably not being made any more

**Comment by TheVitya2127** [comment]
What a pity

**Comment by andrew121410** [comment]
> we dont support versions belo 1.12.2, there is no real wiki on how to generate the files manually, i don't know if there is a version of blockscan for 1.7.10 at all, and it is probably not being made any more 

1.12.2 ain't even supported either  you should say we don't support anything below 1.13, because if 1.12.2 was supported then my issue would've been fixed... https://github.com/webbukkit/dynmap/issues/4020

**Comment by TheVitya2127** [comment]
What a complete disappointment!
