### ISSUE TITLE
How should I delete a useless map without shutting down the server

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [webbukkit/dynmap#4084]
This world call "失落之城" has been deleted, but the webpage map still shows it. How should I remove it? I am using dynmap-3.7-beta4-forge-1.20
<img width="373" alt="image" src="https://github.com/webbukkit/dynmap/assets/141799770/e7de7410-4879-42fc-ae8b-ad4c43e12bdc">
<img width="320" alt="image" src="https://github.com/webbukkit/dynmap/assets/141799770/7f1f36ba-2da1-4348-8b1f-e7f68ecc029f">
I don't think there is a single instruction about deleting data
<img width="435" alt="image" src="https://github.com/webbukkit/dynmap/assets/141799770/0937d725-d35a-4eb4-9811-596700fede69">

**Comment by JurgenKuyper** [comment]
you are using proxying most likely, if the world is disabled using commands, then it should have removed it form its internal webserver, try on the actual ip and see whether it is gone

**Comment by JurgenKuyper** [comment]
no response.
