### ISSUE TITLE
What do the values in `dynmap stats` represent?

### ISSUE THREAD

**Issue by thetayloredman** [webbukkit/dynmap#4086]
There's a lot of values here with barely any explanation:

```
  [Thu 21:50:58 INFO ] Tile Render Statistics:
  [Thu 21:50:58 INFO ]   world.ct: processed=3025, rendered=3025, updated=1559, transparent=192
  [Thu 21:50:58 INFO ]   world.flat: processed=2641, rendered=2641, updated=1225, transparent=33
  [Thu 21:50:58 INFO ]   world.t: processed=97431, rendered=97431, updated=64363, transparent=29831
  [Thu 21:50:58 INFO ]   world_nether.flat: processed=1418, rendered=1418, updated=886, transparent=122
  [Thu 21:50:58 INFO ]   world_nether.nt: processed=12552, rendered=12552, updated=10194, transparent=3135
  [Thu 21:50:58 INFO ]   TOTALS: processed=117067, rendered=117067, updated=78227, transparent=33313
  [Thu 21:50:58 INFO ]   Triggered update queue size: 0 + 0
  [Thu 21:50:58 INFO ]   Active render jobs: world 
  [Thu 21:50:58 INFO ] Chunk Loading Statistics:
  [Thu 21:50:58 INFO ]   Cache hit rate: 60.11%
  [Thu 21:50:58 INFO ]   Chunks processed: Cached: count=7314212, 0.00 msec/chunk
  [Thu 21:50:58 INFO ]   Chunks processed: Already Loaded: count=80550, 178.69 msec/chunk
  [Thu 21:50:58 INFO ]   Chunks processed: Load Required: count=320632, 3.77 msec/chunk
  [Thu 21:50:58 INFO ]   Chunks processed: Not Generated: count=2066052, 0.00 msec/chunk
```

I'm trying to predict how much longer is left in a render job that's been running for days. There's no documentation anywhere as to what any of these numbers mean and I'd like to know about each.

**Comment by JurgenKuyper** [comment]
not possible to predict as your system is finding chunks slower than it is rendering them, either increase the render speeds (fastrender sequence) or wait:
renderaccelerateinterval: .001
 
tiles-rendered-at-once: 10
 
maxchunkspertick: 400
 
parallelrendercnt: 10
 
fullrenderplayerlimit: 0
 
per-tick-time-limit: 200
 
fullrender-min-tps: 5
 (configuration.txt) here the server has 10 cores, change the parallelrenderct to the amount of cores you have. Next do /dynmap pause all, restart and finally do /dynmap pause none.
 
 the render stats are mostly self-explanatory, the queue size consists of the chunks that are being worked on, and the ones that are in the queue, the cache hit rate is as far as I know, how much percentage of the called chunks to render is already cached, but not sure.

**Comment by thetayloredman** [comment]
@JurgenKuyper What about processed/rendered/updated?

Also, how large is a tile (in blocks) normally?

**Comment by JurgenKuyper** [comment]
> @JurgenKuyper What about processed/rendered/updated?
> 
> Also, how large is a tile (in blocks) normally?

I don't know, but guess they are the amnt of tiles that apply to that state

**Comment by JurgenKuyper** [comment]
@thetayloredman a tile is a chunk normally in size, zooms and stitching can change that
