### ISSUE TITLE
Map damaged after adding Markarea

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [webbukkit/dynmap#4087]
> template is **bold**
> sample data is *italicized*

Just using the/marker addarea command to create two regions, the webpage map immediately does not display images (all are damaged patterns)

Refresh web page to display unsent data

Overloading plugins has led to more errors
![43PK32`}VEE@Y 9ECFTW4FO](https://github.com/webbukkit/dynmap/assets/141799770/6ace122e-8436-4317-a9d3-85bfa86deb68)
![45%J 2VG%QFW3PYH`$KLQF4](https://github.com/webbukkit/dynmap/assets/141799770/0aab829d-dfb1-453a-8169-62b0a2f92163)
![X$HQULUP9WTGYJZ}{(ZIA7I](https://github.com/webbukkit/dynmap/assets/141799770/65a11f94-99a0-4093-9fc0-c31192367292)

**Comment by JurgenKuyper** [comment]
your sqlite database is corrupted
