### ISSUE TITLE
Dynmap require use of command on all worlds to render

### ISSUE THREAD

**Issue by Anora** [webbukkit/dynmap#4089]
**Issue Description:** *Dynmap refusing to continue rendering all maps after doing one dimention*

* **Dynmap Version:** 3.6
* **Server Version:** 1.20.1 
* **forge:** 47.2.20
* **Pastebin of Configuration.txt:** https://pastebin.com/ZtxRbTVm
* **Server Host (if applicable):** none
* **Pastebin of crashlogs or other relevant logs:** no error or crashes
* **Other Relevant Data/Screenshots:** none
* **Steps to Replicate:** use the command dynmap full render will cause dynmap to do the job but will not go past the world that it was done in and will not do caves either,Using mod pack all the mods 9.
Also if using the same command in console it forces the request of world

 [X] *I have looked at all other issues and this is not a duplicate*  
 [X] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
that is intended behavior as explained in our commands page, you eithe execute the fullrender in the worlds, or execute the command with the wanted world added

**Comment by Anora** [comment]
SO i have to do that for every dimention as well

**Comment by JurgenKuyper** [comment]
read the documentation and you will find the answer
