### ISSUE TITLE
Could not pass event PlayerJoinEvent/PlayerQuitEvent to dynmap v3.7-beta-4-935

### ISSUE THREAD

**Issue by kh0mka** [webbukkit/dynmap#4090]
**Issue Description:** *The problem occurs when any player logs out*

* **Dynmap Version:** *3.7-beta-4-935*
* **Server Version:** *Purpur 1.20.4 build 2153*
* **Pastebin of Configuration.txt:** *https://pastebin.com/mShzAbaf*
* **Server Host (if applicable):** *BisquitHost*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/b3MnshN3*
* **Other Relevant Data/Screenshots:** *maybe trouble caused by plugin SuperVanish (i have installed it)*
* **Steps to Replicate:** *Every time a player logs in or logs out I get these errors.*

 - [x] *I have looked at all other issues and this is not a duplicate*  
 - [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
we don't support hybrid servers, only fabric, forge, paper and spigot, no forks of these versions. maybe you can try the forge version as it is more robust to these incompatabilities than the paper one, anyway, its out of our support domain if you don't use the aforementioned versions.
