### ISSUE TITLE
Dynmap trees and other surface stuff are not loaded in

### ISSUE THREAD

**Issue by PufferPLS** [webbukkit/dynmap#4091]
The Dynmap is not loading stuff like trees, podzol and other stuff. It all loads in only if I explore the chunks. The config is set default.

Dynmap Version: v3.7-beta-4
Server Version: Spigot 1.20.1
Pastebin of Configuration.txt: https://pastebin.com/5SETL3z2*](https://pastebin.com/596kteEb)
Server Host: ReviveNode
![image_2024-03-10_023140768](https://github.com/webbukkit/dynmap/assets/78787758/f38164b7-e3fb-4d64-bb2e-42993443e388)

**Comment by JurgenKuyper** [comment]
duplicate #4048
