### ISSUE TITLE
Dynmap throwing error with minio Letsencrypt Certificate on Minio instance

### ISSUE THREAD

**Issue by s3tupw1zard** [webbukkit/dynmap#4095]
**Issue Description:** *Error when trying to use Minio with Dynmap*

* **Dynmap Version:** *dynmap-3.7-beta4*
* **Server Version:** *Fabric 1.20.1*
* **Pastebin of Configuration.txt:** *https://pastebin.com/GPqDhqw6*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/3Af9mX2s*
* **Other Relevant Data/Screenshots:** *Not related to other Mods*
* **Steps to Replicate:** 
* Install Minio on sub domains with ssl from letsencrypt and use the api sub domain for dynmap
* Create access key and secret
* Add information to s3 settings like follows
  type: aws_s3
  bucketname: "dynmapfabricbucket"
  region: "eu-central-1"
  aws_access_key_id: "secret-id"
  aws_secret_access_key: "secret-access-key-id"  
  #prefix: ""
  override_endpoint: "https://minio-api.example.com"

* Start server
* See error

 - [x] *I have looked at all other issues and this is not a duplicate*  
 - [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
out of our domain, we only support the aws-s3 backend storage, and the implementation is very lackluster, as there is no unified way to catch all the different versions of s3 storage
