### ISSUE TITLE
Some times the client desyncs with the server

### ISSUE THREAD

**Issue by Mrgaton** [webbukkit/dynmap#4097]
There is some times that the client disconects or something to the server and until you do f5 it freezes everything
![image](https://github.com/webbukkit/dynmap/assets/68958481/c1b733b4-d452-426a-a754-32a739664787)

**Comment by JurgenKuyper** [comment]
adhere to the template.

**Comment by Mrgaton** [comment]
what template

**Comment by JurgenKuyper** [comment]
the issue template you see when creating one.

**Comment by Mrgaton** [comment]
I send you the folder as a zip

**Comment by Mrgaton** [comment]
?
