### ISSUE TITLE
Some chunks not generating?

### ISSUE THREAD

**Issue by Mrgaton** [webbukkit/dynmap#4099]
![image](https://github.com/webbukkit/dynmap/assets/68958481/6ec32dd6-7ae7-440e-807e-44bbfb8be530)

**Comment by Mrgaton** [comment]
also i cant be able to disable cave on web viiew and prevent it from even generating it

**Comment by JurgenKuyper** [comment]
again didn't use template.

**Comment by Mrgaton** [comment]
what is template aaaaaaaaaaaaa
