### ISSUE TITLE
I can't make the Dynmap URL work

### ISSUE THREAD

**Issue by Ampersand20** [webbukkit/dynmap#4104]
**Issue Description:** *Dynmap loads correctly into the map IP (0.0.0.0:8213) as configured, but the server IP (us3.falixserver.net) is not showing anything. I don't know how to get a URL set up to show the map.

* **Dynmap Version:** *3.7 Beta 4*
* **Server Version:** *Paper 1.20*
* **Pastebin of Configuration.txt:** *https://pastebin.com/CQxLpG36*
* **Server Host (if applicable):** *FalixNodes*
* **Pastebin of crashlogs or other relevant logs:** *Console start log: https://pastebin.com/i4Cg3W9K*
* **Other Relevant Data/Screenshots:** *I am using GeyserMC and floodgate plugins.*
* **Steps to Replicate:** *I don't really know I'm just following internet tutorials step by step and the URL won't work.*

**Comment by JurgenKuyper** [comment]
google falixnodes dynmap
