### ISSUE TITLE
Swapping world make the game crash

### ISSUE THREAD

**Issue by zeid0ne** [webbukkit/dynmap#4106]
**Issue Description:** Open a world, quit it, and open a second world make minecraft load it forever

* **Dynmap Version:** Dynmap-3.7-beta-4-forge-1.20
* **Server Version:** forge 1.20.1 build 47.2.30
* **Steps to Replicate:** Open a world, quit it, and open a second world

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by JurgenKuyper** [comment]
dynmap does not support clients, it is a server only mod/plugin.
