### ISSUE TITLE
Request for a wrong Fabric version

### ISSUE THREAD

**Issue by KilianFelix** [webbukkit/dynmap#4107]
Dynmap Requieres a non existing Forge Version.

* **Dynmap Version:** *Dynmap-3.7-beta-4-fabric-1.20.4*
* **Server Version:** *fabric 1.20.4*

![image](https://github.com/webbukkit/dynmap/assets/68030766/a100b06c-be1a-4085-b97d-781a8bfc934c)
https://github.com/webbukkit/dynmap/blob/v3.0/fabric-1.20.4/src/main/resources/fabric.mod.json#L31

![Screenshot 2024-05-10 113907](https://github.com/webbukkit/dynmap/assets/68030766/c59f86ef-cda7-48bc-9cfb-1d3dee5bd70d)

**Comment by JurgenKuyper** [comment]
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all?page=1&pageSize=20
not true, fabric relates to the api version
