### ISSUE TITLE
Random blocks as black splotches

### ISSUE THREAD

**Issue by Nikkilectric** [webbukkit/dynmap#4113]
**Issue Description:** *On my map, random areas of grass blocks and sand blocks turn into black blocks on Dynmap*

**Dynmap Version:** *core=3.7-beta-5-943, plugin=3.7-beta-5-943*
**Server Version:** *Paper 1.20.4 build 496*
**Pastebin of Configuration.txt:** *https://pastebin.com/qJGpJUyf*
**Server Host (if applicable):** *Hetzner, Using WISP.gg*
**Other Relevant Data/Screenshots:** 
![image](https://github.com/webbukkit/dynmap/assets/136409902/fafbbc17-eab9-41c4-aac0-583435da5d3d)
Using /dynmap fullrender
Even when going there in-game, the black spot is just regular grass blocks/sand. I have also gone over all the world's chunks with Chunky.

 [X] *I have looked at all other issues and this is not a duplicate, at least none of which I could find*  
 [X] *I have been able to replicate this, even after purging the world map files & clearing my cache on my browser AND via cloudflare*

**Comment by Nikkilectric** [comment]
I fixed the issue myself. For those wanting a solution, make sure to set an option similar to `force-load chunks` to true

**Comment by Clyde6790pGIT** [comment]
Hi, I am having the same issue but I can't find anything called force-load-chunks or something within the lines of those in the config.

**Comment by JurgenKuyper** [comment]
they mean the force-generate-chunks in the worldborder plugin settings needed for earthmc maps generation: 
The EarthMC map has many known issues with Dynmap such as, incomplete render, only rendering where players have visited, or not rendering leaves and other foliage. This is a result of how the map was made and is not an issue with Dynmap, luckily there is a fix. ```1. Download the WorldBorder plugin: https://www.spigotmc.org/resources/worldborder.60905/ ``` 
```2. Pause Dynmap: /dynmap pause all ``` 
```3. Set the world border radius and center: /wb [worldname] set [radiusX] [radiusZ] [X] [Z] ``` 
``` - [worldname] is the name of the world you want to set the border in. ``` 
``` - [radiusX] is the horizontal radius of the world border ``` 
``` - [radiusZ] is the vertical radius of the world border ``` 
``` - [X] is the horizontal center point of the world border ``` 
``` - [Z] is the vertical center point of the world border ``` 
```4. Run worldborder with the force flag: /wb [worldname] fill [freq] [pad] [force] ``` 
``` - [worldname] is the world you want to be pregenerated ``` 
``` - [freq] is how many chunks a second are generated, 20 is the default. WARNING: setting this too high will cause server lag ``` 
``` - [pad] how many chunks beyond the border to generate, this makes sure that if a player visits the border, all chunks are already generated. The default is 208, We recommend setting this to 0 for EarthMC. ``` 
``` - [force] This must be set to true ``` 
```5. Wait for worldborder to finish ``` 
```6. Unpause Dynmap: /dynmap pause none, you may have to start the fullrender using /dynmap fullrender [worldname]```

**Comment by Nikkilectric** [comment]
Alternatively, using chunky, set
`force-load-existing-chunks: true`
In chunky's config.yml
