### ISSUE TITLE
[Help requested] Some UI similar to maps.fmdx.pl

### ISSUE THREAD

**Issue by ryanginn** [webbukkit/dynmap#4114]
> **Similar setup to a page I found**

**Feature Description:** *This probably isn't the right wording. But I would like to create a website similar to maps.fmdx.pl using Dynmap. Could someone advise me on how to do such?*

![image](https://github.com/webbukkit/dynmap/assets/98589683/ece773d0-8c89-4f3f-8520-d110aba5afcc)

**Comment by JurgenKuyper** [comment]
no, this just looks like the openstreetmap frontend put on a mc server, and not much to do with dynmap.
