### ISSUE TITLE
Dynmap fails to load under Spigot 1.21

### ISSUE THREAD

**Issue by Fanman03** [webbukkit/dynmap#4121]
**Issue Description:** Dynmap fails to load when used with Spigot 1.21

* **Dynmap Version:** *3.7-beta-5*
* **Server Version:** *Spigot 1.21*
* **Pastebin of Configuration.txt:** *https://pastebin.com/WqTtkSyP*
* **Server Host (if applicable):** *Oracle Cloud under Oracle Linux*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/NGiFEunN*
* **Steps to Replicate:** *1. Install dynmap 3.7-beta-5 on Spigot 1.21 server 2. Start server*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by L1Z3** [comment]
If you want Dynmap on 1.21 right now, you can follow the instructions in the README to compile the latest commit in the `v3.0` branch. If you just want to compile Dynmap for spigot, you can run `./gradlew setup :spigot:build`. I followed these steps to compile a `.jar` for beta-6 and Dynmap loads on my Paper 1.21 server.

**Comment by Fanman03** [comment]
Fixed in v3.7-beta-6
