### ISSUE TITLE
Jenkins builds?

### ISSUE THREAD

**Issue by KweezyCode** [webbukkit/dynmap#4123]
Provide jenkins beta builds to users

**Comment by JurgenKuyper** [comment]
all the builds we have are accessible to everyone already

**Comment by KweezyCode** [comment]
> all the builds we have are accessible to everyone already

where?

**Comment by JurgenKuyper** [comment]
As usual, Curseforge is being slow on approvals, so updates can be found now at https://modrinth.com/plugin/dynmap/versions and [https://www.spigotmc.org/resources/dynmap®.274/](https://www.spigotmc.org/resources/dynmap%C2%AE.274/)

**Comment by KweezyCode** [comment]
> As usual, Curseforge is being slow on approvals, so updates can be found now at https://modrinth.com/plugin/dynmap/versions and [https://www.spigotmc.org/resources/dynmap®.274/](https://www.spigotmc.org/resources/dynmap%C2%AE.274/)

yeah, but my question was about JENKINS, not curseforge or something else

**Comment by JurgenKuyper** [comment]
dev builds are not available, only the dev has them, but you can just pull from source and build it yourself if you so please.

**Comment by KweezyCode** [comment]
okay, thanks
