### ISSUE TITLE
Plugin crash after startup server

### ISSUE THREAD

**Issue by clopolc** [webbukkit/dynmap#4141]
**Issue Description:** *The plugin crashes on server startup*

* **Dynmap Version:** *Dynmap-3.7-beta-6-spigot.jar (for 1.21.1)*
* **Server Version:** *CraftBukkit version 4290-Spigot-5a6439b-b95736b (MC: 1.21.1) (Implementing API version 1.21.1-R0.1-SNAPSHOT)*
* **Server Host (if applicable):** *Selfhosted*
* **Pastebin of crashlogs or other relevant logs:** *https://pastebin.com/aszy4YJb*
* **Other Relevant Data/Screenshots:** *plugins installed : LuckPerms, WorldEdit, Essentials, EssentialsSpawn, EssentialsChat, WorldGuard, EssentialsAntiBuild, dynmap, WorldBorder, EssentialsProtect*
* **Steps to Replicate:** *Just install .jar in plugins folder and start server*

 [x] *I have looked at all other issues and this is not a duplicate*  
 [x] *I have been able to replicate this*

**Comment by Blitheness** [comment]
> Dynmap-3.7-beta-6-spigot.jar (for 1.21.1)

There isn't yet an official Spigot release for 1.21.1, likely causing your crash.
