### ISSUE TITLE
Is there a way to erase the +, - buttons and compass image?

### ISSUE THREAD

**Issue by ghost** [webbukkit/dynmap#4147]
**Is there a way to erase the +, - buttons and compass image?**

![image](https://github.com/user-attachments/assets/015caf91-0e43-4d32-8195-a3a0fdbdcf0a)
![image](https://github.com/user-attachments/assets/cb39bac4-ec04-40c8-b495-c5bf1f3638b5)

**Comment by ashduino101** [comment]
To disable the compass, you can add `&nocompass=true` to the Dynmap URL (make sure to put this before the pound symbol!).  To disable the zoom buttons is a little harder and there doesn't seem to be a built-in way to do it, but you can probably change line 178 (or whatever line specifies zoomControl) of the file `web/js/map.js` to `zoomControl: false,`. You can also disable everything (including the sidebar) by add `&nogui=true`  to the URL query parameters.
