### ISSUE TITLE
Feature Request: Display AFK Status from Essentials

### ISSUE THREAD

**Issue by cmarcera** [webbukkit/dynmap#450]
It would be great if dynmap could detect a player's AFK status from the Essentials plugin.

Once a player goes AFK, dynmap could:
- Add an AFK icon after the users' name or,
- Grey out the user's name or,
- Put the user's name in italics

All three options as configurable settings would be a plus.

**Comment by Psy-Virus** [comment]
Could be achieved by saving and checking the coordinates of players serverside and add a timer.
