### ISSUE TITLE
Rotating the map / display the map from another direction

### ISSUE THREAD

**Issue by mpathy** [webbukkit/dynmap#519]
I have rendered a really big world (it's earth!) a whole evening just to recognize the maps is not in the right direction - how can I get the whole thing 90° clockwise?

Here is my output:
http://zivilisation.mpathy.de:8123/

Please give me a hint.
Also it would be great if you can tell me if a rendering in HD of this big world would work and how much space on disk will be used for a map of this size / how much more space than the normal map will be used.

**Comment by ghost** [comment]
Which file is compass-mode in?
