### ISSUE TITLE
URL parameter for the player's name

### ISSUE THREAD

**Issue by resi23** [webbukkit/dynmap#520]
Hello,
Thank you for this really very beautiful map.
I've already tried it myself for several days but still no solution to my problem.
It would be possible to add a URL parameter for the player's name?

thank-you

**Comment by larryl79** [comment]
I've set trustclient and allowurlname to true and still not working in 2.5 

  - class: org.dynmap.InternalClientUpdateComponent
    allowwebchat: true
    webchat-interval: 5
    hidewebchatip: true
    trustclientname: true

 - class: org.dynmap.ClientComponent
    type: chat
    allowurlname: true

what I doing wrong?

**Comment by jwshields** [comment]
This issue is just 6 years old, almost 7.
Please create a new issue if you're experiencing issues rather than necro-ing an issue that was solved many years ago.
