### ISSUE TITLE
[Feature] Show -all- signs on map, Sorted into marker-set based on string-match (like in Overviewer)

### ISSUE THREAD

**Issue by Scaenicus** [webbukkit/dynmap#542]
Our old marker-system with overviewer was based on signs with the advantage that anyone could place signs.

In Overviewer you are able to create small javascript functions like...

```
{'label':'Portal', 'match':function(s){return s.msg.match("^PORTAL");}, 'icon':'signpost_portal.png', 'checked':true}
```

...to group signs to what would be marker-sets in dynmap and give them an icon.
I.e. every sign starting with the upper-case word "PORTAL" would get the icon "signpost_portal.png", would be grouped in the set "Portal" (lable) and would be displayed by default (checked:true).

What I propose is:
# ) String based matching of every sign in the world to a marker-set and to icons.
# ) A default group (with default icon) for every unmatched sign.

Especially with the live-map a "DANGER" sign freshly placed to a new project and immediately displayed is helpful to all players watching you from "above".

**Comment by TrevorSayre** [comment]
Any chance of this being revisited?

**Comment by mb243** [comment]
I would also love to see this. We use signs on my server to mark locations which are relevant to all players, but they follow a certain format so they're unlikely to be abused.
