### ISSUE TITLE
AFK not showing on Dynmap

### ISSUE THREAD

**Issue by SullyTheUnusual** [webbukkit/dynmap#628]
The Essentials AFK is not showing up on Dynmap.  I thought this might be a VanishNoPacket issue, so I disabled the Essentials hook in its config and dynmap still won't report AFK status.

I'm not sure if this could be related, but I didn't like the fact that HeroChat hijacked the /afk command from essentials so I disabled the alias in HeroChat's plugins.yml.

**Comment by Psy-Virus** [comment]
Duplicate of #450
