### ISSUE TITLE
Dynmap full render runs server out of memory

### ISSUE THREAD

**Issue by SullyTheUnusual** [webbukkit/dynmap#649]
CB 1.2.3-R0.1 and Dynmap 0.34.  Doing a fullrender runs the server out of memory.  The auto-reboot wipes the log, so all I have is a screenshot:

http://snpr.cm/FPP2uG.jpg

**Comment by ljsimin** [comment]
@mikeprimm I'm experiencing reproduce-able out of memory crashes when trying fullrender on my world. I specifically tried with no plugins other than dynmap. Do you have any resources on how could I pinpoint the exact cause? Here's the brief info:

2GB of RAM + 1GB of swap
Debian Linux
Spigot
no plugins
oracle java 8
startup paramerers: -Xms1024M -Xmx1536M
Size of the world: 2.8GB

I'd appreciate any tips and resources on debugging the problem.
