### ISSUE TITLE
[Feature] Ability to ignore grass and trees in TopoHDShader or ability to specify per-map custom-texture.txt

### ISSUE THREAD

**Issue by Blackhex** [webbukkit/dynmap#653]
It would be nice to be able to disable rendering of grass, trees and other stuff not relevant to actual surface elevation in TopoHDShader maps. This could be achived either by special configuration value of the shader or ability to specify custom-texture.txt per-map where desired block rendering would be disabled. Modyfying custom-texture.txt now, disables rendering of those block for all maps.

**Comment by AD-Wright** [comment]
Could we update this feature?  It appears that some inconsistencies have arisen over time between the different shaders, as TopoHDShader no longer looks for `hiddenids`, but `hiddennames` (as does CaveHDShader), but TexturePackHDShader still looks only for `hiddenids` and filters the list for only integers.  

Also, as this was created before *The Flattening*, there are some new blocks that either were not included in the default list (acacia, block id 161 &162; and two-high flowers and grass, block id 175), or do not have a block id (kelp, seagrass, bamboo).  It also appears something may have changed where mushroom-related blocks (red, brown, and stem) are no longer hidden. 

I can create a pull request for all the names in the minecraft: format, but I'm not sure how to update TexturePackHDShader.  I'm also not sure if I'm missing any new blocks that should be included in the `noplants` shaders.  

Looks like #2622 might be related.

**Comment by AD-Wright** [comment]
Unfortunately the block ids can represent multiple blocks at the same time (they are rather compact), so an updated list is rather large.  Here is what I have so far: 

Current blocks converted to new format:
`oak_sapling, spruce_sapling, birch_sapling, jungle_sapling, acacia_sapling, dark_oak_sapling, oak_log, spruce_log, birch_log, jungle_log, acacia_log, dark_oak_log, oak_leaves, spruce_leaves, birch_leaves, jungle_leaves, acacia_leaves, dark_oak_leaves, grass, tall_grass, fern, large_fern, dead_bush, dandelion, poppy, blue_orchid, allium, azure_bluet, red_tulip, orange_tulip, white_tulip, pink_tulip, oxeye_daisy, cornflower, lily_of_the_valley, sunflower, lilac, rose_bush, peony, brown_mushroom, red_mushroom, torch, redstone_wire, snow_layer, cactus, sugar_cane, pumpkin, brown_mushroom_block, red_mushroom_block, melon, pumpkin_stem, melon_stem, lily_pad, nether_wart`

New blocks to be added:
`kelp_plant, seagrass, tall_seagrass, sea_pickle, bamboo_sapling, mushroom_stem`

This seems rather large to put into a config file, so perhaps sticking with the block ids where possible would be good?  It would be more compact, for sure, but readability for those who are not familiar with the id numbers would suffer.  This would also appear three times in the [shaders.txt](https://github.com/webbukkit/dynmap/blob/f1c0cfa5ac9c245081e1b6acf408ebb7205718d0/DynmapCore/src/main/resources/shaders.txt) file.
