### ISSUE TITLE
Image export

### ISSUE THREAD

**Issue by jacky4566** [webbukkit/dynmap#686]
I would like to have the ability to export the rendered image of a map through the commands. The idea is to have a super large hires image suitable for printing large format. The command would only have to be similar to this:
Export (world) (map) (export name?) (zoom depth)

**Comment by MrPowerGamerBR** [comment]
That plugin is inactive, outdated and, by the looks of it, only supported flat maps... 😢

Is there's any alternative to it? What I couldn't figure out was how to convert coordinates (x, y, z) to the folder/tile file.

**Comment by hs-rendov** [comment]
@MrPowerGamerBR https://github.com/martinsik/minecraft-dynmap-timemachine

**Comment by DmitryRendov** [comment]
@MrPowerGamerBR https://github.com/martinsik/minecraft-dynmap-timemachine

**Comment by MrPowerGamerBR** [comment]
@DmitryRendov while coding my own tools I ended up stumbling across that tool (it would've been great if I found it before I started coding it, but better late than never)

Anyway, thanks! :)
