### ISSUE TITLE
Feature request: store night tiles as png mask atop day tiles to enable gradual transition between day and night in-browser.

### ISSUE THREAD

**Issue by mooinglemur** [webbukkit/dynmap#716]
Objective: To facilitate a gradual transition between day and night on the dynmap rather than having it suddenly change at 21:00 and 07:00.

Tile creation: Rather than storing separate day and night tiles, store only the current version of day tiles.  For night, calculate the difference between day and night for each tile, and store that as a PNG with an alpha channel.

Browser rendering: Overlay the night tile mask atop the day tiles.  During the day, set CSS opacity of the mask to 0%.  As it transitions to night, increase the CSS opacity up to 100%.  Do the reverse as the time approaches dawn.

Other info: I'd like to suggest this as an additional map type, not to completely replace the current version of day/night.

Let me know if you need any further explanation.

**Comment by Psy-Virus** [comment]
Even if it would look nice to have a transition, it would eat at least 1 1/2 times the bandwidth of the current implementation. I don't know if such an effect is worth the 'costs'.

I'll add this to the list but with a low priority tag.
