### ISSUE TITLE
Render Farm

### ISSUE THREAD

**Issue by robheffo** [webbukkit/dynmap#755]
I am preposing a feature where the core Dynmap renderer can be run on extra servers and be slave renderers to the minecraft server.

That way, I can have my Minecraft server being free to serve the game while the idle time on some of my other servers can take care of the tile processing.

Being able to have a render pool where I can run multiple renderers on multiple machines would be a real bonus

**Comment by Psy-Virus** [comment]
Could be achieved by programming a standalone or server-slave client with data transfer from and to the master. But probably not worth the effort. Most people wouldn't use this feature. :(

Personally I'd be a fan of it too...
