### ISSUE TITLE
Dynamically Updating Screenshots

### ISSUE THREAD

**Issue by TheVenturiEffect** [webbukkit/dynmap#775]
Could you implement a feature that would allow a player to type a command in-game, and have a dynmap rendered screenshot made from the player's point of view? These snapshots would be saved in a folder that can be linked to websites/forums. As a bonus, what if the snapshots could be updated at intervals, so that we could show progress of a build or active town?

**Comment by Psy-Virus** [comment]
You could create a custom perspective and link the position to that website/forum.
