### ISSUE TITLE
Map Use Idea [Feature Request]

### ISSUE THREAD

**Issue by MathewAlden** [webbukkit/dynmap#798]
Hi.
So Dynmap is awesome. And I like it. But it annoyed me that it made in-game maps totally useless.
Then, I had an idea.

I think it'd be cool if it only mapped the world onto the Dynmap if the player was mapping it on a Minecraft map. You have to have an in-game map to have the land around you rendered onto the Dynmap.

Also, you could have it configured as to whether it stopped mapping once your map was full, or if it only mattered if you're holding the map.

So... I think that'd be cool. Maybe you'd add it?

Thanks,
MathewAlden

**Comment by Psy-Virus** [comment]
I add this to the list because it's a more or less small enhancement to the 'on chunk populate rendering'

**Comment by MathewAlden** [comment]
Oh wow. I didn't know these mods were still being developed. I don't host a Minecraft server anymore, but thanks for your guy's work.
