### ISSUE TITLE
[Feature Request] GPU Support

### ISSUE THREAD

**Issue by xxlostspiritxx** [webbukkit/dynmap#799]
Is there away that you can make it run off of one's video card instead of CPU because my video card is on idle the whole day until i get online... I was thinking it would put allot less stress on my CPU while the server is online... Please if it is possible please add it!

**Comment by samvv** [comment]
Still I'd give it a +1, for those servers who do :)

**Comment by rautamiekka** [comment]
Would serve a purpose.

**Comment by CaptainFunny** [comment]
Little late to the thread, but I'd use this feature quit a bit. I'm running slightly older hardware that has a gpu being completely unutilized. It'd definitely help to take a load off my CPU.
