### ISSUE TITLE
Specify banned-players list

### ISSUE THREAD

**Issue by peman3232** [webbukkit/dynmap#822]
I am not entirely sure how you would do this. But lots of plugins use a different ban list than banned-players.txt

unfortunately they also use a different format =/ Plugins like core, banhammer etc. So banned players can get on the livemap and be annoying. Do you think it would be possible to work around this? (Personally, I use core, but I play on servers that use banhammer and they have the same issue)

**Comment by Psy-Virus** [comment]
The lists could be mirrored with a simple script that's running every now and then, when the server runs.
