### ISSUE TITLE
Feature: Show markers on map for portals

### ISSUE THREAD

**Issue by KovuTheHusky** [webbukkit/dynmap#826]
It would be nice if there was an option to show nether and/or ender portals on maps to make it easier to find the nearest portal. For portals to The End, only activated portals should be shown so players can't find a stronghold by just using the live map.

**Comment by Psy-Virus** [comment]
Most admins wouldn't allow the users to create their own markers. So it would be a good idea to let them decide if portals are shown by default or not.
