### ISSUE TITLE
world and plugins folder not set in default locations

### ISSUE THREAD

**Issue by laramy2020** [webbukkit/dynmap#836]
i use multicraft to manage my minecraft servers, i have loaded dynmap and the web page loads an index list only (shows a link to tiles)
now my plugin is located in
/home/minecraft/multicraft/jar/craftbukkit.jar.plugins/dynmap.jar and dynmap/
jar is /home/minecraft/multicraft/jar/craftbukkit.jar
world is /home/minecraft/multicraft/servers/server1/world
now i have looked through the wiki (probably not hard enough) but how would i tell dynmap that the world is located somewhere diffrent?

**Comment by Psy-Virus** [comment]
Closing due to old issue and involved third party stuff.
