### ISSUE TITLE
More day/night modes

### ISSUE THREAD

**Issue by xZise** [webbukkit/dynmap#863]
Hi, at the moment we are using only the day map as you can see more while its sunny outside ;)

Now one user asked me if he could see the night map, but as I don't add the day/night switch again, I thought maybe you can expand the day/night modes to the following:
- Only day map visible
- Normally the day map is visible but it is possible to show a night version of the map (And vice versa)
- Switch automatically between day/night map, but if wanted the viewer can view the “opposite” time (if it is day you can view the night map and vice versa)
- Only the automatic day/night change

As far as I know only the first and last option are available yet. So maybe you can add the both in between :)

Fabian

**Comment by Psy-Virus** [comment]
Closed due to never answered or commented.
