### ISSUE TITLE
Hiding non-public Towny towns

### ISSUE THREAD

**Issue by Freso** [webbukkit/dynmap#874]
Currently, all towns are shown with the Towny extension/plugin. It would be great if setting the town property "public" to false would make it not show on the map. (Towny doesn't display the chunk co-ord of the town in its info either.)

**Comment by Psy-Virus** [comment]
Wrong issue tracker. Should be reopened in [towny](https://github.com/webbukkit/Dynmap-Towny/issues) if still needed.
