### ISSUE TITLE
Feature Request: Display markers in sidebar

### ISSUE THREAD

**Issue by veN1337** [webbukkit/dynmap#877]
I would like to see all markers (eg. spawn,...) in the sidebar.
They should be clickable to go to their position.
(Like players ;))

**Comment by bmhm** [comment]
I'd give +1 for this.

**Comment by veN1337** [comment]
@bmhm how did you find this issue? its almost 3 years old. i dont even play minecraft anymore and didnt know this thing still exist

**Comment by bmhm** [comment]
I just thought "that would be helpful"  and 
http://lmgtfy.com/?q=Dynmap+marker+sidebar+feature

**Comment by Psy-Virus** [comment]
Listed
