### ISSUE TITLE
Dyn Map only shows on localhost:8123 not myserverip:8123

### ISSUE THREAD

**Issue by t2rq** [webbukkit/dynmap#931]
ive just got a webstie up and running for my minecraft server (still in development). and i had it working on my website http://www.newamestris.enjin.com/livemap

It was working for about half an hour, absolutly fine all my users could see it, and then the next moment all they got was a black screen. i dunno what i am doing wrong ive opened my ports used a port checker to make sure 8123 is open. ive put the dynmap in a i frame

my bukkit version is (1.3.1-R2.0)
and my configuration is default apart from :hires
i'm also using 0.80 dyn map plugin

at the moment i'm just trying to get it open on my IP address:8123 as this is the machine i'm running the server from. as i said it used to work and i went to access it and got nothing. I really want to get this working on my site as your plugin is amazing =)

**Comment by TheGaming900** [comment]
it doesnt fucking!!!!!!!!!!!!!!
