### ISSUE TITLE
Port forwarding Dynmap to External IP

### ISSUE THREAD

**Issue by HDJam** [webbukkit/dynmap#955]
I searched google forever, found this one guide:
http://www.planetminecraft.com/blog/how-to-set-up-dynmap/

I opened the ports on the router and allowed advanced firewall rules to allow the ports(TCP AND UDP)... It just doesn't want to work every time I try it.

This is a home server... The server PC settings:
25565 and 25566 open, I CAN connect to my server via external IP. IE: [ExternalIP]:25565
However I cannot connect using: [ExternalIP]:25566

I am able to use my Internal IP throughout my network, all can access: 192.168.1.6:25566

Dynmap Config info:
webserver-bindaddress: 192.168.1.6
webserver-port: 25566

I also port forwarded 25566 from the server PC the same way I did for the minecraft server.

What am I doing wrong??? I want ANYONE to see my [ExternalIP]:25566

**Comment by Denny966** [comment]
what did you do to fix this i have the same problem
