### ISSUE TITLE
[Feature] List Dynmap Players

### ISSUE THREAD

**Issue by lukecfairchild** [webbukkit/dynmap#996]
So you can see who is on in the server, but you cant see who is on the dynmap from the server. So I would like to request either a dynmap command to list which logged in players are viewing the dynmap or a modification of the command /list. Or even just a file that records who is actively logged in and viewing the dynmap.

**Comment by Psy-Virus** [comment]
If still interesting, pls reopen. Except there's a duplicate of this existing...

:)
